LLVM: lib/Target/AMDGPU/Disassembler/AMDGPUDisassembler.cpp File Reference
AMDGPUDisassembler.cpp File Reference
#include "Disassembler/AMDGPUDisassembler.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "SIDefines.h"
#include "SIRegisterInfo.h"
#include "TargetInfo/AMDGPUTargetInfo.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "llvm-c/DisassemblerTypes.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDecoderOps.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/AMDHSAKernelDescriptor.h"
#include "AMDGPUGenDisassemblerTables.inc"
Classes
struct VOPModifiers
Macros
#define DEBUG_TYPE "amdgpu-disassembler"
#define SGPR_MAX
#define DECODE_OPERAND(StaticDecoderName, DecoderName)
#define DECODE_OPERAND_REG(RegClass) DECODE_OPERAND(Decode##RegClass##RegisterClass, decodeOperand_##RegClass)
#define DECODE_SDWA(DecName) DECODE_OPERAND(decodeSDWA##DecName, decodeSDWA##DecName)
#define PRINT_DIRECTIVE(DIRECTIVE, MASK)
#define PRINT_DIRECTIVE(DIRECTIVE, MASK)
Typedefs
using DecodeStatus = llvm::MCDisassembler::DecodeStatus
Functions
static MCDisassembler::DecodeStatus addOperand (MCInst &Inst, const MCOperand &Opnd)
static int insertNamedMCOperand (MCInst &MI, const MCOperand &Op, uint16_t NameIdx)
static DecodeStatus decodeSoppBrTarget (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus decodeSMEMOffset (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus decodeBoolReg (MCInst &Inst, unsigned Val, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus decodeOperand_VSrc16 (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus decodeOperand_VSrcV216 (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus decodeOperand_VSrcV232 (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus decodeOperand_VS_16 (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus decodeOperand_VS_32 (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus decodeOperand_AReg_64 (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus decodeOperand_AReg_128 (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus decodeOperand_AReg_256 (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus decodeOperand_AReg_512 (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus decodeOperand_AReg_1024 (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus decodeOperand_VReg_64 (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus decodeOperand_VReg_128 (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus decodeOperand_VReg_256 (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus decodeOperand_VReg_512 (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus decodeOperand_VReg_1024 (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus decodeOperand_f32kimm (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus decodeOperand_f16kimm (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus decodeOperand_VS_16_Deferred (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus decodeOperand_VS_32_Deferred (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus decodeOperandVOPDDstY (MCInst &Inst, unsigned Val, uint64_t Addr, const void *Decoder)
static bool IsAGPROperand (const MCInst &Inst, int OpIdx, const MCRegisterInfo *MRI)
static DecodeStatus decodeOperand_AVLdSt_Any (MCInst &Inst, unsigned Imm, AMDGPUDisassembler::OpWidthTy Opw, const MCDisassembler *Decoder)
static DecodeStatus DecodeAVLdSt_32RegisterClass (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeAVLdSt_64RegisterClass (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeAVLdSt_96RegisterClass (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeAVLdSt_128RegisterClass (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus decodeOperand_SReg_32 (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
template<typename T >
static T eatBytes (ArrayRef< uint8_t > &Bytes)
static DecoderUInt128 eat12Bytes (ArrayRef< uint8_t > &Bytes)
static bool isValidDPP8 (const MCInst &MI)
static VOPModifiers collectVOPModifiers (const MCInst &MI, bool IsVOP3P=false)
static int64_t getInlineImmVal32 (unsigned Imm)
static int64_t getInlineImmVal64 (unsigned Imm)
static int64_t getInlineImmVal16 (unsigned Imm)
static MCSymbolizer * createAMDGPUSymbolizer (const Triple &, LLVMOpInfoCallback, LLVMSymbolLookupCallback, void *DisInfo, MCContext *Ctx, std::unique_ptr< MCRelocationInfo > &&RelInfo)
static MCDisassembler * createAMDGPUDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeAMDGPUDisassembler ()
Detailed Description
This file contains definition for AMDGPU ISA disassembler
Definition in file AMDGPUDisassembler.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "amdgpu-disassembler"
Definition at line 39 of file AMDGPUDisassembler.cpp.
DECODE_OPERAND
#define DECODE_OPERAND (StaticDecoderName, DecoderName)
Value:
  static DecodeStatus StaticDecoderName(MCInst &Inst, unsigned Imm,            \
                                        uint64_t /*Addr*/,                     \
                                        const MCDisassembler *Decoder) {       \
    auto DAsm = static_cast<const AMDGPUDisassembler *>(Decoder);              \
    return addOperand(Inst, DAsm->DecoderName(Imm));                           \
  }
Definition at line 110 of file AMDGPUDisassembler.cpp.
DECODE_OPERAND_REG
#define DECODE_OPERAND_REG (RegClass) DECODE_OPERAND(Decode##RegClass##RegisterClass, decodeOperand_##RegClass)
Definition at line 118 of file AMDGPUDisassembler.cpp.
DECODE_SDWA
#define DECODE_SDWA (DecName) DECODE_OPERAND(decodeSDWA##DecName, decodeSDWA##DecName)
Definition at line 380 of file AMDGPUDisassembler.cpp.
PRINT_DIRECTIVE [1/2]
#define PRINT_DIRECTIVE (DIRECTIVE, MASK)
Value:
  do {                                                                         \
    KdStream << Indent << DIRECTIVE " "                                        \
             << ((FourByteBuffer & MASK) >> (MASK##_SHIFT)) << '\n';           \
  } while (0)
Definition at line 1760 of file AMDGPUDisassembler.cpp.
PRINT_DIRECTIVE [2/2]
#define PRINT_DIRECTIVE (DIRECTIVE, MASK)
Value:
  do {                                                                         \
    KdStream << Indent << DIRECTIVE " "                                        \
             << ((TwoByteBuffer & MASK) >> (MASK##_SHIFT)) << '\n';            \
  } while (0)
Definition at line 1760 of file AMDGPUDisassembler.cpp.
SGPR_MAX
#define SGPR_MAX
Value:
  (isGFX10Plus() ? AMDGPU::EncValues::SGPR_MAX_GFX10                           \
                 : AMDGPU::EncValues::SGPR_MAX_SI)
Definition at line 41 of file AMDGPUDisassembler.cpp.
Typedef Documentation
DecodeStatus
using DecodeStatus = llvm::MCDisassembler::DecodeStatus
Definition at line 45 of file AMDGPUDisassembler.cpp.
Function Documentation
addOperand()
static MCDisassembler::DecodeStatus addOperand (MCInst & Inst, const MCOperand & Opnd) inline static
Definition at line 59 of file AMDGPUDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCDisassembler::Fail, llvm::MCOperand::isValid(), and llvm::MCDisassembler::Success.
Referenced by llvm::AMDGPUDisassembler::convertMIMGInst(), decodeBoolReg(), decodeOperand_AReg_1024(), decodeOperand_AReg_128(), decodeOperand_AReg_256(), decodeOperand_AReg_512(), decodeOperand_AReg_64(), decodeOperand_AVLdSt_Any(), decodeOperand_f16kimm(), decodeOperand_f32kimm(), decodeOperand_SReg_32(), decodeOperand_VReg_1024(), decodeOperand_VReg_128(), decodeOperand_VReg_256(), decodeOperand_VReg_512(), decodeOperand_VReg_64(), decodeOperand_VS_16(), decodeOperand_VS_16_Deferred(), decodeOperand_VS_32(), decodeOperand_VS_32_Deferred(), decodeOperand_VSrc16(), decodeOperand_VSrcV216(), decodeOperand_VSrcV232(), decodeOperandVOPDDstY(), decodeSMEMOffset(), and decodeSoppBrTarget().
collectVOPModifiers()
static VOPModifiers collectVOPModifiers (const MCInst & MI, bool IsVOP3P = false) static
Definition at line 762 of file AMDGPUDisassembler.cpp.
References llvm::SISrcMods::DST_OP_SEL, llvm::AMDGPU::getNamedOperandIdx(), MI, llvm::SISrcMods::NEG, llvm::SISrcMods::NEG_HI, VOPModifiers::NegHi, VOPModifiers::NegLo, llvm::SISrcMods::OP_SEL_0, llvm::SISrcMods::OP_SEL_1, VOPModifiers::OpSel, and VOPModifiers::OpSelHi.
Referenced by llvm::AMDGPUDisassembler::convertDPP8Inst(), llvm::AMDGPUDisassembler::convertVOP3DPPInst(), and llvm::AMDGPUDisassembler::convertVOP3PDPPInst().
createAMDGPUDisassembler()
static MCDisassembler* createAMDGPUDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 2169 of file AMDGPUDisassembler.cpp.
References llvm::AMDGPUDisassembler::AMDGPUDisassembler(), and llvm::MCDisassembler::STI.
Referenced by LLVMInitializeAMDGPUDisassembler().
createAMDGPUSymbolizer()
static MCSymbolizer* createAMDGPUSymbolizer (const Triple & , LLVMOpInfoCallback , LLVMSymbolLookupCallback , void * DisInfo, MCContext * Ctx, std::unique_ptr< MCRelocationInfo > && RelInfo) static
Definition at line 2160 of file AMDGPUDisassembler.cpp.
References move.
Referenced by LLVMInitializeAMDGPUDisassembler().
DecodeAVLdSt_128RegisterClass()
static DecodeStatus DecodeAVLdSt_128RegisterClass (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 367 of file AMDGPUDisassembler.cpp.
References decodeOperand_AVLdSt_Any(), llvm::RISCVMatInt::Imm, and llvm::AMDGPUDisassembler::OPW128.
DecodeAVLdSt_32RegisterClass()
static DecodeStatus DecodeAVLdSt_32RegisterClass (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 346 of file AMDGPUDisassembler.cpp.
References decodeOperand_AVLdSt_Any(), llvm::RISCVMatInt::Imm, and llvm::AMDGPUDisassembler::OPW32.
DecodeAVLdSt_64RegisterClass()
static DecodeStatus DecodeAVLdSt_64RegisterClass (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 353 of file AMDGPUDisassembler.cpp.
References decodeOperand_AVLdSt_Any(), llvm::RISCVMatInt::Imm, and llvm::AMDGPUDisassembler::OPW64.
DecodeAVLdSt_96RegisterClass()
static DecodeStatus DecodeAVLdSt_96RegisterClass (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 360 of file AMDGPUDisassembler.cpp.
References decodeOperand_AVLdSt_Any(), llvm::RISCVMatInt::Imm, and llvm::AMDGPUDisassembler::OPW96.
decodeBoolReg()
static DecodeStatus decodeBoolReg (MCInst & Inst, unsigned Val, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 104 of file AMDGPUDisassembler.cpp.
References addOperand().
decodeOperand_AReg_1024()
static DecodeStatus decodeOperand_AReg_1024 (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 219 of file AMDGPUDisassembler.cpp.
References addOperand(), llvm::RISCVMatInt::Imm, and llvm::AMDGPUDisassembler::OPW1024.
decodeOperand_AReg_128()
static DecodeStatus decodeOperand_AReg_128 (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 198 of file AMDGPUDisassembler.cpp.
References addOperand(), llvm::RISCVMatInt::Imm, and llvm::AMDGPUDisassembler::OPW128.
decodeOperand_AReg_256()
static DecodeStatus decodeOperand_AReg_256 (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 205 of file AMDGPUDisassembler.cpp.
References addOperand(), llvm::RISCVMatInt::Imm, and llvm::AMDGPUDisassembler::OPW256.
decodeOperand_AReg_512()
static DecodeStatus decodeOperand_AReg_512 (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 212 of file AMDGPUDisassembler.cpp.
References addOperand(), llvm::RISCVMatInt::Imm, and llvm::AMDGPUDisassembler::OPW512.
decodeOperand_AReg_64()
static DecodeStatus decodeOperand_AReg_64 (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 191 of file AMDGPUDisassembler.cpp.
References addOperand(), llvm::RISCVMatInt::Imm, and llvm::AMDGPUDisassembler::OPW64.
decodeOperand_AVLdSt_Any()
static DecodeStatus decodeOperand_AVLdSt_Any (MCInst & Inst, unsigned Imm, AMDGPUDisassembler::OpWidthTy Opw, const MCDisassembler * Decoder) static
Definition at line 311 of file AMDGPUDisassembler.cpp.
References addOperand(), llvm::SIInstrFlags::DS, llvm::AMDGPU::getNamedOperandIdx(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOpcode(), llvm::RISCVMatInt::Imm, IsAGPROperand(), and MRI.
Referenced by DecodeAVLdSt_128RegisterClass(), DecodeAVLdSt_32RegisterClass(), DecodeAVLdSt_64RegisterClass(), and DecodeAVLdSt_96RegisterClass().
decodeOperand_f16kimm()
static DecodeStatus decodeOperand_f16kimm (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 268 of file AMDGPUDisassembler.cpp.
References addOperand(), and llvm::RISCVMatInt::Imm.
decodeOperand_f32kimm()
static DecodeStatus decodeOperand_f32kimm (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 261 of file AMDGPUDisassembler.cpp.
References addOperand(), and llvm::RISCVMatInt::Imm.
decodeOperand_SReg_32()
static DecodeStatus decodeOperand_SReg_32 (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 373 of file AMDGPUDisassembler.cpp.
References addOperand(), and llvm::RISCVMatInt::Imm.
decodeOperand_VReg_1024()
static DecodeStatus decodeOperand_VReg_1024 (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 254 of file AMDGPUDisassembler.cpp.
References addOperand(), llvm::RISCVMatInt::Imm, and llvm::AMDGPUDisassembler::OPW1024.
decodeOperand_VReg_128()
static DecodeStatus decodeOperand_VReg_128 (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 233 of file AMDGPUDisassembler.cpp.
References addOperand(), llvm::RISCVMatInt::Imm, and llvm::AMDGPUDisassembler::OPW128.
decodeOperand_VReg_256()
static DecodeStatus decodeOperand_VReg_256 (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 240 of file AMDGPUDisassembler.cpp.
References addOperand(), llvm::RISCVMatInt::Imm, and llvm::AMDGPUDisassembler::OPW256.
decodeOperand_VReg_512()
static DecodeStatus decodeOperand_VReg_512 (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 247 of file AMDGPUDisassembler.cpp.
References addOperand(), llvm::RISCVMatInt::Imm, and llvm::AMDGPUDisassembler::OPW512.
decodeOperand_VReg_64()
static DecodeStatus decodeOperand_VReg_64 (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 226 of file AMDGPUDisassembler.cpp.
References addOperand(), llvm::RISCVMatInt::Imm, and llvm::AMDGPUDisassembler::OPW64.
decodeOperand_VS_16()
static DecodeStatus decodeOperand_VS_16 (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 177 of file AMDGPUDisassembler.cpp.
References addOperand(), and llvm::RISCVMatInt::Imm.
decodeOperand_VS_16_Deferred()
static DecodeStatus decodeOperand_VS_16_Deferred (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 276 of file AMDGPUDisassembler.cpp.
References addOperand(), llvm::RISCVMatInt::Imm, and llvm::AMDGPUDisassembler::OPW16.
decodeOperand_VS_32()
static DecodeStatus decodeOperand_VS_32 (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 184 of file AMDGPUDisassembler.cpp.
References addOperand(), and llvm::RISCVMatInt::Imm.
decodeOperand_VS_32_Deferred()
static DecodeStatus decodeOperand_VS_32_Deferred (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 284 of file AMDGPUDisassembler.cpp.
References addOperand(), llvm::RISCVMatInt::Imm, and llvm::AMDGPUDisassembler::OPW32.
decodeOperand_VSrc16()
static DecodeStatus decodeOperand_VSrc16 (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 156 of file AMDGPUDisassembler.cpp.
References addOperand(), and llvm::RISCVMatInt::Imm.
decodeOperand_VSrcV216()
static DecodeStatus decodeOperand_VSrcV216 (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 163 of file AMDGPUDisassembler.cpp.
References addOperand(), and llvm::RISCVMatInt::Imm.
decodeOperand_VSrcV232()
static DecodeStatus decodeOperand_VSrcV232 (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 170 of file AMDGPUDisassembler.cpp.
References addOperand(), and llvm::RISCVMatInt::Imm.
decodeOperandVOPDDstY()
static DecodeStatus decodeOperandVOPDDstY (MCInst & Inst, unsigned Val, uint64_t Addr, const void * Decoder) static
Definition at line 291 of file AMDGPUDisassembler.cpp.
References addOperand().
decodeSMEMOffset()
static DecodeStatus decodeSMEMOffset (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 92 of file AMDGPUDisassembler.cpp.
References addOperand(), llvm::MCOperand::createImm(), and llvm::RISCVMatInt::Imm.
decodeSoppBrTarget()
static DecodeStatus decodeSoppBrTarget (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 77 of file AMDGPUDisassembler.cpp.
References addOperand(), Addr, llvm::MCOperand::createImm(), llvm::RISCVMatInt::Imm, llvm::APInt::sext(), and llvm::MCDisassembler::Success.
eat12Bytes()
static DecoderUInt128 eat12Bytes (ArrayRef< uint8_t > & Bytes) inline static
Definition at line 400 of file AMDGPUDisassembler.cpp.
References assert(), llvm::ArrayRef< T >::data(), llvm::ArrayRef< T >::size(), and llvm::ArrayRef< T >::slice().
Referenced by llvm::AMDGPUDisassembler::getInstruction().
eatBytes()
template<typename T > static T eatBytes (ArrayRef< uint8_t > & Bytes) inline static
Definition at line 393 of file AMDGPUDisassembler.cpp.
References assert(), llvm::ArrayRef< T >::data(), llvm::ArrayRef< T >::size(), and llvm::ArrayRef< T >::slice().
getInlineImmVal16()
static int64_t getInlineImmVal16 (unsigned Imm) static
Definition at line 1357 of file AMDGPUDisassembler.cpp.
References llvm::RISCVMatInt::Imm, and llvm_unreachable.
Referenced by llvm::AMDGPUDisassembler::decodeFPImmed().
getInlineImmVal32()
static int64_t getInlineImmVal32 (unsigned Imm) static
Definition at line 1307 of file AMDGPUDisassembler.cpp.
References f(), llvm::FloatToBits(), llvm::RISCVMatInt::Imm, and llvm_unreachable.
Referenced by llvm::AMDGPUDisassembler::decodeFPImmed().
getInlineImmVal64()
static int64_t getInlineImmVal64 (unsigned Imm) static
Definition at line 1332 of file AMDGPUDisassembler.cpp.
References llvm::DoubleToBits(), llvm::RISCVMatInt::Imm, and llvm_unreachable.
Referenced by llvm::AMDGPUDisassembler::decodeFPImmed().
insertNamedMCOperand()
static int insertNamedMCOperand (MCInst & MI, const MCOperand & Op, uint16_t NameIdx) static
Definition at line 66 of file AMDGPUDisassembler.cpp.
References llvm::AMDGPU::getNamedOperandIdx(), I, and MI.
Referenced by llvm::AMDGPUDisassembler::convertDPP8Inst(), llvm::AMDGPUDisassembler::convertEXPInst(), llvm::AMDGPUDisassembler::convertFMAanyK(), llvm::AMDGPUDisassembler::convertSDWAInst(), llvm::AMDGPUDisassembler::convertVINTERPInst(), llvm::AMDGPUDisassembler::convertVOP3DPPInst(), llvm::AMDGPUDisassembler::convertVOP3PDPPInst(), llvm::AMDGPUDisassembler::convertVOPCDPPInst(), and llvm::AMDGPUDisassembler::getInstruction().
IsAGPROperand()
static bool IsAGPROperand (const MCInst & Inst, int OpIdx, const MCRegisterInfo * MRI) static
Definition at line 297 of file AMDGPUDisassembler.cpp.
References llvm::MCInst::getOperand(), and MRI.
Referenced by decodeOperand_AVLdSt_Any().
isValidDPP8()
static bool isValidDPP8 (const MCInst & MI) static
Definition at line 414 of file AMDGPUDisassembler.cpp.
References assert(), llvm::AMDGPU::DPP::DPP8_FI_0, llvm::AMDGPU::DPP::DPP8_FI_1, llvm::AMDGPU::getNamedOperandIdx(), and MI.
Referenced by llvm::AMDGPUDisassembler::convertDPP8Inst().
LLVMInitializeAMDGPUDisassembler()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeAMDGPUDisassembler ()
Definition at line 2175 of file AMDGPUDisassembler.cpp.
References createAMDGPUDisassembler(), createAMDGPUSymbolizer(), llvm::getTheGCNTarget(), llvm::TargetRegistry::RegisterMCDisassembler(), and llvm::TargetRegistry::RegisterMCSymbolizer().