LLVM: lib/Transforms/Scalar/AnnotationRemarks.cpp File Reference
AnnotationRemarks.cpp File Reference
#include "llvm/Transforms/Scalar/AnnotationRemarks.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/MemoryOpRemark.h"
Macros
#define DEBUG_TYPE "annotation-remarks"
#define REMARK_PASS DEBUG_TYPE
Functions
static void tryEmitAutoInitRemark (ArrayRef< Instruction * > Instructions, OptimizationRemarkEmitter &ORE, const TargetLibraryInfo &TLI)
static void runImpl (Function &F, const TargetLibraryInfo &TLI)
INITIALIZE_PASS_BEGIN (AnnotationRemarksLegacy, "annotation-remarks", "Annotation Remarks", false, false) INITIALIZE_PASS_END(AnnotationRemarksLegacy
Variables
annotation remarks
annotation Annotation Remarks
annotation Annotation false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "annotation-remarks"
Definition at line 27 of file AnnotationRemarks.cpp.
REMARK_PASS
#define REMARK_PASS DEBUG_TYPE
Definition at line 28 of file AnnotationRemarks.cpp.
Function Documentation
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (AnnotationRemarksLegacy , "annotation-remarks" , "Annotation Remarks" , false , false)
runImpl()
static void runImpl (Function & F, const TargetLibraryInfo & TLI) static
Definition at line 45 of file AnnotationRemarks.cpp.
References llvm::OptimizationRemarkEmitter::allowExtraAnalysis(), llvm::OptimizationRemarkEmitter::emit(), F, I, llvm::MapVector< KeyT, ValueT, MapType, VectorType >::insert(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::insert(), llvm::instructions(), REMARK_PASS, and tryEmitAutoInitRemark().
Referenced by llvm::AnnotationRemarksPass::run().
tryEmitAutoInitRemark()
static void tryEmitAutoInitRemark (ArrayRef< Instruction * > Instructions, OptimizationRemarkEmitter & ORE, const TargetLibraryInfo & TLI) static
Definition at line 30 of file AnnotationRemarks.cpp.
References llvm::AutoInitRemark::canHandle(), DL, F, I, Instructions, llvm::Remark, and REMARK_PASS.
Referenced by runImpl().
Variable Documentation
false
annotation Annotation false
Definition at line 115 of file AnnotationRemarks.cpp.
remarks
annotation remarks
Definition at line 114 of file AnnotationRemarks.cpp.
Remarks
annotation Annotation Remarks
Definition at line 115 of file AnnotationRemarks.cpp.
Referenced by llvm::remarks::RemarkLinker::empty(), and llvm::remarks::RemarkLinker::remarks().