LLVM: lib/IR/AutoUpgrade.cpp File Reference
AutoUpgrade.cpp File Reference
#include "llvm/IR/AutoUpgrade.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Triple.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstVisitor.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsAArch64.h"
#include "llvm/IR/IntrinsicsARM.h"
#include "llvm/IR/IntrinsicsX86.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Verifier.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Regex.h"
#include <cstring>
Functions
static void rename (GlobalValue *GV)
static bool UpgradePTESTIntrinsic (Function *F, Intrinsic::ID IID, Function *&NewFn)
static bool UpgradeX86IntrinsicsWith8BitMask (Function *F, Intrinsic::ID IID, Function *&NewFn)
static bool UpgradeX86MaskedFPCompare (Function *F, Intrinsic::ID IID, Function *&NewFn)
static bool ShouldUpgradeX86Intrinsic (Function *F, StringRef Name)
static bool UpgradeX86IntrinsicFunction (Function *F, StringRef Name, Function *&NewFn)
static bool UpgradeIntrinsicFunction1 (Function *F, Function *&NewFn)
static Value * UpgradeX86PSLLDQIntrinsics (IRBuilder<> &Builder, Value *Op, unsigned Shift)
static Value * UpgradeX86PSRLDQIntrinsics (IRBuilder<> &Builder, Value *Op, unsigned Shift)
static Value * getX86MaskVec (IRBuilder<> &Builder, Value *Mask, unsigned NumElts)
static Value * EmitX86Select (IRBuilder<> &Builder, Value *Mask, Value *Op0, Value *Op1)
static Value * EmitX86ScalarSelect (IRBuilder<> &Builder, Value *Mask, Value *Op0, Value *Op1)
static Value * UpgradeX86ALIGNIntrinsics (IRBuilder<> &Builder, Value *Op0, Value *Op1, Value *Shift, Value *Passthru, Value *Mask, bool IsVALIGN)
static Value * UpgradeX86VPERMT2Intrinsics (IRBuilder<> &Builder, CallBase &CI, bool ZeroMask, bool IndexForm)
static Value * UpgradeX86BinaryIntrinsics (IRBuilder<> &Builder, CallBase &CI, Intrinsic::ID IID)
static Value * upgradeX86Rotate (IRBuilder<> &Builder, CallBase &CI, bool IsRotateRight)
static Value * upgradeX86vpcom (IRBuilder<> &Builder, CallBase &CI, unsigned Imm, bool IsSigned)
static Value * upgradeX86ConcatShift (IRBuilder<> &Builder, CallBase &CI, bool IsShiftRight, bool ZeroMask)
static Value * UpgradeMaskedStore (IRBuilder<> &Builder, Value *Ptr, Value *Data, Value *Mask, bool Aligned)
static Value * UpgradeMaskedLoad (IRBuilder<> &Builder, Value *Ptr, Value *Passthru, Value *Mask, bool Aligned)
static Value * upgradeAbs (IRBuilder<> &Builder, CallBase &CI)
static Value * upgradePMULDQ (IRBuilder<> &Builder, CallBase &CI, bool IsSigned)
static Value * ApplyX86MaskOn1BitsVec (IRBuilder<> &Builder, Value *Vec, Value *Mask)
static Value * upgradeMaskedCompare (IRBuilder<> &Builder, CallBase &CI, unsigned CC, bool Signed)
static Value * UpgradeX86MaskedShift (IRBuilder<> &Builder, CallBase &CI, Intrinsic::ID IID)
static Value * upgradeMaskedMove (IRBuilder<> &Builder, CallBase &CI)
static Value * UpgradeMaskToInt (IRBuilder<> &Builder, CallBase &CI)
static bool upgradeAVX512MaskToSelect (StringRef Name, IRBuilder<> &Builder, CallBase &CI, Value *&Rep)
static Value * UpgradeARMIntrinsicCall (StringRef Name, CallBase *CI, Function *F, IRBuilder<> &Builder)
static bool UpgradeRetainReleaseMarker (Module &M)
This checks for objc retain release marker which should be upgraded.
static bool isOldLoopArgument (Metadata *MD)
static MDString * upgradeLoopTag (LLVMContext &C, StringRef OldTag)
static Metadata * upgradeLoopArgument (Metadata *MD)
Function Documentation
ApplyX86MaskOn1BitsVec()
static Value* ApplyX86MaskOn1BitsVec (IRBuilder<> & Builder, Value * Vec, Value * Mask) static
Definition at line 1532 of file AutoUpgrade.cpp.
References Builder, llvm::Constant::getNullValue(), llvm::Value::getType(), getX86MaskVec(), i, llvm::BitmaskEnumDetail::Mask(), and llvm::max().
Referenced by upgradeMaskedCompare().
EmitX86ScalarSelect()
static Value* EmitX86ScalarSelect (IRBuilder<> & Builder, Value * Mask, Value * Op0, Value * Op1) static
Definition at line 1207 of file AutoUpgrade.cpp.
References Builder, llvm::FixedVectorType::get(), and llvm::BitmaskEnumDetail::Mask().
EmitX86Select()
static Value* EmitX86Select (IRBuilder<> & Builder, Value * Mask, Value * Op0, Value * Op1) static
Definition at line 1195 of file AutoUpgrade.cpp.
References Builder, llvm::Value::getType(), getX86MaskVec(), and llvm::BitmaskEnumDetail::Mask().
Referenced by upgradeAbs(), upgradeAVX512MaskToSelect(), upgradePMULDQ(), UpgradeX86ALIGNIntrinsics(), UpgradeX86BinaryIntrinsics(), upgradeX86ConcatShift(), UpgradeX86MaskedShift(), upgradeX86Rotate(), and UpgradeX86VPERMT2Intrinsics().
getX86MaskVec()
static Value* getX86MaskVec (IRBuilder<> & Builder, Value * Mask, unsigned NumElts) static
Definition at line 1175 of file AutoUpgrade.cpp.
References assert(), Builder, llvm::FixedVectorType::get(), i, llvm::isPowerOf2_32(), llvm::makeArrayRef(), and llvm::BitmaskEnumDetail::Mask().
Referenced by ApplyX86MaskOn1BitsVec(), EmitX86Select(), UpgradeMaskedLoad(), UpgradeMaskedStore(), and UpgradeMaskToInt().
isOldLoopArgument()
static bool isOldLoopArgument (Metadata * MD) static
Definition at line 4572 of file AutoUpgrade.cpp.
References S.
Referenced by llvm::upgradeInstructionLoopAttachment().
rename()
static void rename (GlobalValue * GV) static
Definition at line 38 of file AutoUpgrade.cpp.
References llvm::Value::getName(), and llvm::Value::setName().
Referenced by UpgradeIntrinsicFunction1(), UpgradePTESTIntrinsic(), UpgradeX86IntrinsicFunction(), UpgradeX86IntrinsicsWith8BitMask(), and UpgradeX86MaskedFPCompare().
ShouldUpgradeX86Intrinsic()
static bool ShouldUpgradeX86Intrinsic (Function * F, StringRef Name) static
Definition at line 85 of file AutoUpgrade.cpp.
Referenced by UpgradeX86IntrinsicFunction().
upgradeAbs()
static Value* upgradeAbs (IRBuilder<> & Builder, CallBase & CI) static
Definition at line 1492 of file AutoUpgrade.cpp.
References llvm::abs(), llvm::CallBase::arg_size(), Builder, EmitX86Select(), F, llvm::CallBase::getArgOperand(), llvm::Intrinsic::getDeclaration(), llvm::Instruction::getModule(), and llvm::Value::getType().
UpgradeARMIntrinsicCall()
static Value* UpgradeARMIntrinsicCall (StringRef Name, CallBase * CI, Function * F, IRBuilder<> & Builder) static
Definition at line 1867 of file AutoUpgrade.cpp.
References llvm::CallBase::args(), Builder, C1, F, llvm::FixedVectorType::get(), llvm::CallBase::getArgOperand(), llvm::Intrinsic::getDeclaration(), llvm::CallBase::getIntrinsicID(), llvm::Value::getName(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), and llvm_unreachable.
upgradeAVX512MaskToSelect()
static bool upgradeAVX512MaskToSelect (StringRef Name, IRBuilder<> & Builder, CallBase & CI, Value *& Rep) static
Definition at line 1618 of file AutoUpgrade.cpp.
References llvm::CallBase::arg_size(), llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::CallBase::args(), Builder, EmitX86Select(), llvm::CallBase::getArgOperand(), llvm::Intrinsic::getDeclaration(), llvm::Instruction::getModule(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::Type::isFPOrFPVectorTy(), and llvm_unreachable.
UpgradeIntrinsicFunction1()
static bool UpgradeIntrinsicFunction1 (Function * F, Function *& NewFn) static
Definition at line 534 of file AutoUpgrade.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Cases(), llvm::Function::Create(), llvm::StringSwitch< T, R >::Default(), F, llvm::FunctionType::get(), llvm::StructType::get(), llvm::FixedVectorType::get(), llvm::Type::getBFloatTy(), llvm::Intrinsic::getDeclaration(), llvm::VectorType::getElementType(), llvm::Type::getInt1Ty(), llvm::Intrinsic::getIntrinsicInfoTableEntries(), llvm::Intrinsic::getName(), llvm::Type::isFloatingPointTy(), llvm::Regex::match(), memcpy(), llvm::None, llvm::Intrinsic::not_intrinsic, prefetch, R2, llvm::Intrinsic::remangleIntrinsicFunction(), rename(), llvm::ARM_MB::ST, llvm::StringSwitch< T, R >::StartsWith(), llvm::Intrinsic::IITDescriptor::Struct, and UpgradeX86IntrinsicFunction().
Referenced by llvm::UpgradeIntrinsicFunction().
upgradeLoopArgument()
static Metadata* upgradeLoopArgument (Metadata * MD) static
Definition at line 4596 of file AutoUpgrade.cpp.
References E, llvm::MDTuple::get(), I, llvm::SmallVectorImpl< T >::reserve(), and upgradeLoopTag().
Referenced by llvm::upgradeInstructionLoopAttachment().
upgradeLoopTag()
static MDString* upgradeLoopTag (LLVMContext & C, StringRef OldTag) static
Definition at line 4584 of file AutoUpgrade.cpp.
References assert(), llvm::StringRef::drop_front(), llvm::MDString::get(), llvm::StringRef::size(), and llvm::StringRef::startswith().
Referenced by upgradeLoopArgument().
upgradeMaskedCompare()
static Value* upgradeMaskedCompare (IRBuilder<> & Builder, CallBase & CI, unsigned CC, bool Signed) static
Definition at line 1554 of file AutoUpgrade.cpp.
References ApplyX86MaskOn1BitsVec(), llvm::CallBase::arg_size(), Builder, llvm::FixedVectorType::get(), llvm::Constant::getAllOnesValue(), llvm::CallBase::getArgOperand(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm_unreachable, llvm::BitmaskEnumDetail::Mask(), and Signed.
UpgradeMaskedLoad()
static Value* UpgradeMaskedLoad (IRBuilder<> & Builder, Value * Ptr, Value * Passthru, Value * Mask, bool Aligned) static
Definition at line 1469 of file AutoUpgrade.cpp.
References Align, llvm::Aligned, Builder, llvm::TypeSize::getFixedSize(), llvm::Type::getPrimitiveSizeInBits(), llvm::Value::getType(), llvm::PointerType::getUnqual(), getX86MaskVec(), and llvm::BitmaskEnumDetail::Mask().
upgradeMaskedMove()
static Value* upgradeMaskedMove (IRBuilder<> & Builder, CallBase & CI) static
Definition at line 1594 of file AutoUpgrade.cpp.
References B, Builder, llvm::CallBase::getArgOperand(), llvm::BitmaskEnumDetail::Mask(), and llvm::MCID::Select.
UpgradeMaskedStore()
static Value* UpgradeMaskedStore (IRBuilder<> & Builder, Value * Ptr, Value * Data, Value * Mask, bool Aligned) static
Definition at line 1447 of file AutoUpgrade.cpp.
References Align, llvm::Aligned, Builder, llvm::Data, llvm::PointerType::getUnqual(), getX86MaskVec(), and llvm::BitmaskEnumDetail::Mask().
UpgradeMaskToInt()
static Value* UpgradeMaskToInt (IRBuilder<> & Builder, CallBase & CI) static
Definition at line 1609 of file AutoUpgrade.cpp.
References Builder, llvm::CallBase::getArgOperand(), llvm::Value::getType(), getX86MaskVec(), and llvm::BitmaskEnumDetail::Mask().
upgradePMULDQ()
static Value* upgradePMULDQ (IRBuilder<> & Builder, CallBase & CI, bool IsSigned) static
Definition at line 1502 of file AutoUpgrade.cpp.
References llvm::CallBase::arg_size(), Builder, EmitX86Select(), llvm::ConstantInt::get(), llvm::CallBase::getArgOperand(), llvm::Value::getType(), LHS, llvm::BitmaskEnumDetail::Mask(), and RHS.
UpgradePTESTIntrinsic()
static bool UpgradePTESTIntrinsic (Function * F, Intrinsic::ID IID, Function *& NewFn) static
Definition at line 42 of file AutoUpgrade.cpp.
References F, llvm::FixedVectorType::get(), llvm::Intrinsic::getDeclaration(), llvm::Type::getFloatTy(), and rename().
Referenced by UpgradeX86IntrinsicFunction().
UpgradeRetainReleaseMarker()
static bool UpgradeRetainReleaseMarker (Module & M) static
This checks for objc retain release marker which should be upgraded.
It returns true if module is modified.
Definition at line 4230 of file AutoUpgrade.cpp.
References llvm::Module::Error, llvm::MDString::get(), llvm::NamedMDNode::getOperand(), and M.
Referenced by llvm::UpgradeARCRuntime().
UpgradeX86ALIGNIntrinsics()
static Value* UpgradeX86ALIGNIntrinsics (IRBuilder<> & Builder, Value * Op0, Value * Op1, Value * Shift, Value * Passthru, Value * Mask, bool IsVALIGN) static
Definition at line 1224 of file AutoUpgrade.cpp.
References assert(), Builder, EmitX86Select(), llvm::Constant::getNullValue(), llvm::Value::getType(), i, llvm::isPowerOf2_32(), l, llvm::makeArrayRef(), llvm::BitmaskEnumDetail::Mask(), and Shift.
UpgradeX86BinaryIntrinsics()
static Value* UpgradeX86BinaryIntrinsics (IRBuilder<> & Builder, CallBase & CI, Intrinsic::ID IID) static
Definition at line 1331 of file AutoUpgrade.cpp.
References llvm::CallBase::arg_size(), Builder, EmitX86Select(), llvm::Intrinsic::getDeclaration(), llvm::Instruction::getModule(), llvm::User::getOperand(), llvm::Value::getType(), and llvm::BitmaskEnumDetail::Mask().
upgradeX86ConcatShift()
static Value* upgradeX86ConcatShift (IRBuilder<> & Builder, CallBase & CI, bool IsShiftRight, bool ZeroMask) static
Definition at line 1413 of file AutoUpgrade.cpp.
References llvm::CallBase::arg_size(), Builder, EmitX86Select(), llvm::ConstantAggregateZero::get(), llvm::CallBase::getArgOperand(), llvm::Intrinsic::getDeclaration(), llvm::Instruction::getModule(), llvm::User::getOperand(), llvm::Type::getScalarType(), llvm::Value::getType(), llvm::BitmaskEnumDetail::Mask(), and std::swap().
UpgradeX86IntrinsicFunction()
static bool UpgradeX86IntrinsicFunction (Function * F, StringRef Name, Function *& NewFn) static
Definition at line 420 of file AutoUpgrade.cpp.
References F, llvm::Intrinsic::getDeclaration(), rename(), ShouldUpgradeX86Intrinsic(), UpgradePTESTIntrinsic(), UpgradeX86IntrinsicsWith8BitMask(), and UpgradeX86MaskedFPCompare().
Referenced by UpgradeIntrinsicFunction1().
UpgradeX86IntrinsicsWith8BitMask()
static bool UpgradeX86IntrinsicsWith8BitMask (Function * F, Intrinsic::ID IID, Function *& NewFn) static
Definition at line 58 of file AutoUpgrade.cpp.
References F, llvm::Intrinsic::getDeclaration(), llvm::Type::isIntegerTy(), and rename().
Referenced by UpgradeX86IntrinsicFunction().
UpgradeX86MaskedFPCompare()
static bool UpgradeX86MaskedFPCompare (Function * F, Intrinsic::ID IID, Function *& NewFn) static
Definition at line 74 of file AutoUpgrade.cpp.
References F, llvm::Intrinsic::getDeclaration(), and rename().
Referenced by UpgradeX86IntrinsicFunction().
UpgradeX86MaskedShift()
static Value* UpgradeX86MaskedShift (IRBuilder<> & Builder, CallBase & CI, Intrinsic::ID IID) static
Definition at line 1586 of file AutoUpgrade.cpp.
References Builder, EmitX86Select(), llvm::CallBase::getArgOperand(), llvm::Intrinsic::getDeclaration(), and llvm::Instruction::getModule().
UpgradeX86PSLLDQIntrinsics()
static Value* UpgradeX86PSLLDQIntrinsics (IRBuilder<> & Builder, Value * Op, unsigned Shift) static
Definition at line 1109 of file AutoUpgrade.cpp.
References Builder, llvm::FixedVectorType::get(), llvm::Constant::getNullValue(), i, l, llvm::makeArrayRef(), and Shift.
UpgradeX86PSRLDQIntrinsics()
static Value* UpgradeX86PSRLDQIntrinsics (IRBuilder<> & Builder, Value * Op, unsigned Shift) static
Definition at line 1143 of file AutoUpgrade.cpp.
References Builder, llvm::FixedVectorType::get(), llvm::Constant::getNullValue(), i, l, llvm::makeArrayRef(), and Shift.
upgradeX86Rotate()
static Value* upgradeX86Rotate (IRBuilder<> & Builder, CallBase & CI, bool IsRotateRight) static
Definition at line 1347 of file AutoUpgrade.cpp.
References llvm::CallBase::arg_size(), Builder, EmitX86Select(), llvm::CallBase::getArgOperand(), llvm::Intrinsic::getDeclaration(), llvm::Instruction::getModule(), llvm::User::getOperand(), llvm::Type::getScalarType(), llvm::Value::getType(), and llvm::BitmaskEnumDetail::Mask().
upgradeX86vpcom()
static Value* upgradeX86vpcom (IRBuilder<> & Builder, CallBase & CI, unsigned Imm, bool IsSigned) static
Definition at line 1374 of file AutoUpgrade.cpp.
References Builder, llvm::MipsISD::Ext, llvm::Constant::getAllOnesValue(), llvm::CallBase::getArgOperand(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::RISCVMatInt::Imm, LHS, llvm_unreachable, and RHS.
UpgradeX86VPERMT2Intrinsics()
static Value* UpgradeX86VPERMT2Intrinsics (IRBuilder<> & Builder, CallBase & CI, bool ZeroMask, bool IndexForm) static
Definition at line 1270 of file AutoUpgrade.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, Builder, EmitX86Select(), llvm::ConstantAggregateZero::get(), llvm::CallBase::getArgOperand(), llvm::Intrinsic::getDeclaration(), llvm::Instruction::getModule(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::Type::isFPOrFPVectorTy(), llvm_unreachable, and std::swap().