LLVM: lib/CodeGen/GlobalISel/CallLowering.cpp File Reference
CallLowering.cpp File Reference
#include "llvm/CodeGen/GlobalISel/CallLowering.h"
#include "llvm/CodeGen/Analysis.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
#include "llvm/CodeGen/GlobalISel/Utils.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/Target/TargetMachine.h"
Macros
#define DEBUG_TYPE "call-lowering"
Functions
static void addFlagsUsingAttrFn (ISD::ArgFlagsTy &Flags, const std::function< bool(Attribute::AttrKind)> &AttrFn)
Helper function which updates Flags when AttrFn returns true.
static MachineInstrBuilder mergeVectorRegsToResultRegs (MachineIRBuilder &B, ArrayRef< Register > DstRegs, ArrayRef< Register > SrcRegs)
Pack values SrcRegs to cover the vector type result DstRegs.
static void buildCopyFromRegs (MachineIRBuilder &B, ArrayRef< Register > OrigRegs, ArrayRef< Register > Regs, LLT LLTy, LLT PartLLT, const ISD::ArgFlagsTy Flags)
Create a sequence of instructions to combine pieces split into register typed values to the original IR value.
static void buildCopyToRegs (MachineIRBuilder &B, ArrayRef< Register > DstRegs, Register SrcReg, LLT SrcTy, LLT PartTy, unsigned ExtendOp=TargetOpcode::G_ANYEXT)
Create a sequence of instructions to expand the value in SrcReg (of type SrcTy) to the types in DstRegs (of type PartTy).
static unsigned extendOpFromFlags (llvm::ISD::ArgFlagsTy Flags)
static bool isCopyCompatibleType (LLT SrcTy, LLT DstTy)
Check if we can use a basic COPY instruction between the two types.
Detailed Description
This file implements some simple delegations needed for call lowering.
Definition in file CallLowering.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "call-lowering"
Definition at line 28 of file CallLowering.cpp.
Function Documentation
addFlagsUsingAttrFn()
static void addFlagsUsingAttrFn (ISD::ArgFlagsTy & Flags, const std::function< bool(Attribute::AttrKind)> & AttrFn) static
Helper function which updates Flags when AttrFn returns true.
Definition at line 36 of file CallLowering.cpp.
References llvm::ISD::ArgFlagsTy::setByVal(), llvm::ISD::ArgFlagsTy::setInAlloca(), llvm::ISD::ArgFlagsTy::setInReg(), llvm::ISD::ArgFlagsTy::setNest(), llvm::ISD::ArgFlagsTy::setPreallocated(), llvm::ISD::ArgFlagsTy::setReturned(), llvm::ISD::ArgFlagsTy::setSExt(), llvm::ISD::ArgFlagsTy::setSRet(), llvm::ISD::ArgFlagsTy::setSwiftAsync(), llvm::ISD::ArgFlagsTy::setSwiftError(), llvm::ISD::ArgFlagsTy::setSwiftSelf(), and llvm::ISD::ArgFlagsTy::setZExt().
Referenced by llvm::CallLowering::addArgFlagsFromAttributes(), and llvm::CallLowering::getAttributesForArgIdx().
buildCopyFromRegs()
static void buildCopyFromRegs (MachineIRBuilder & B, ArrayRef< Register > OrigRegs, ArrayRef< Register > Regs, LLT LLTy, LLT PartLLT, const ISD::ArgFlagsTy Flags) static
Create a sequence of instructions to combine pieces split into register typed values to the original IR value.
OrigRegs contains the destination value registers of type LLTy, and Regs contains the legalized pieces with type PartLLT. This is used for incoming values (physregs to vregs).
Definition at line 321 of file CallLowering.cpp.
References assert(), B, llvm::ArrayRef< T >::begin(), llvm::LLT::changeElementCount(), llvm::LLT::changeElementType(), llvm::ArrayRef< T >::drop_front(), llvm::ArrayRef< T >::end(), llvm::LLT::fixed_vector(), llvm::LLT::getElementCount(), llvm::LLT::getElementType(), llvm::TypeSize::getFixedSize(), llvm::getGCDType(), llvm::LLT::getNumElements(), llvm::LLT::getScalarSizeInBits(), llvm::LLT::getScalarType(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), I, llvm::LLT::isPointer(), llvm::ISD::ArgFlagsTy::isSExt(), llvm::LLT::isVector(), llvm::ISD::ArgFlagsTy::isZExt(), Merge, mergeVectorRegsToResultRegs(), MRI, llvm::LLT::scalar(), llvm::MachineRegisterInfo::setType(), llvm::ArrayRef< T >::size(), and llvm::ArrayRef< T >::take_front().
Referenced by llvm::CallLowering::handleAssignments().
buildCopyToRegs()
static void buildCopyToRegs (MachineIRBuilder & B, ArrayRef< Register > DstRegs, Register SrcReg, LLT SrcTy, LLT PartTy, unsigned ExtendOp = TargetOpcode::G_ANYEXT) static
Create a sequence of instructions to expand the value in SrcReg (of type SrcTy) to the types in DstRegs (of type PartTy).
ExtendOp should contain the type of scalar value extension if necessary.
This is used for outgoing values (vregs to physregs)
Definition at line 468 of file CallLowering.cpp.
References llvm::alignTo(), assert(), B, llvm::numbers::e, llvm::getCoverTy(), llvm::LLT::getElementType(), llvm::getGCDType(), getReg(), llvm::LLT::getScalarSizeInBits(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), i, llvm::LLT::isScalar(), llvm::LLT::isVector(), MRI, llvm::LLT::scalar(), llvm::ArrayRef< T >::size(), and llvm::RegState::Undef.
Referenced by llvm::CallLowering::handleAssignments().
extendOpFromFlags()
static unsigned extendOpFromFlags (llvm::ISD::ArgFlagsTy Flags) static
Definition at line 555 of file CallLowering.cpp.
References llvm::ISD::ArgFlagsTy::isSExt(), and llvm::ISD::ArgFlagsTy::isZExt().
Referenced by llvm::CallLowering::handleAssignments().
isCopyCompatibleType()
static bool isCopyCompatibleType (LLT SrcTy, LLT DstTy) static
Check if we can use a basic COPY instruction between the two types.
We're currently building on top of the infrastructure using MVT, which loses pointer information in the CCValAssign. We accept copies from physical registers that have been reported as integers if it's to an equivalent sized pointer LLT.
Definition at line 1188 of file CallLowering.cpp.
References llvm::LLT::getScalarType(), llvm::LLT::getSizeInBits(), llvm::LLT::isPointer(), and llvm::LLT::isScalar().
Referenced by llvm::CallLowering::IncomingValueHandler::assignValueToReg().
mergeVectorRegsToResultRegs()
static MachineInstrBuilder mergeVectorRegsToResultRegs (MachineIRBuilder & B, ArrayRef< Register > DstRegs, ArrayRef< Register > SrcRegs) static
Pack values SrcRegs to cover the vector type result DstRegs.
Definition at line 275 of file CallLowering.cpp.
References assert(), B, llvm::ArrayRef< T >::begin(), copy, llvm::MachineRegisterInfo::createGenericVirtualRegister(), llvm::ArrayRef< T >::end(), llvm::getCoverTy(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), I, MRI, and llvm::ArrayRef< T >::size().
Referenced by buildCopyFromRegs().