LLVM: llvm::ThunkInserter< Derived > Class Template Reference
llvm::ThunkInserter< Derived > Class Template Reference
#include "llvm/CodeGen/IndirectThunks.h"
Public Member Functions
void init (Module &M)
bool run (MachineModuleInfo &MMI, MachineFunction &MF)
Protected Member Functions
void doInitialization (Module &M)
void createThunkFunction (MachineModuleInfo &MMI, StringRef Name, bool Comdat=true)
Protected Attributes
bool InsertedThunks
Detailed Description
template<typename Derived>
class llvm::ThunkInserter< Derived >
Definition at line 24 of file IndirectThunks.h.
Member Function Documentation
createThunkFunction()
template<typename Derived > void llvm::ThunkInserter< Derived >::createThunkFunction (MachineModuleInfo & MMI, StringRef Name, bool Comdat = true) protected
Definition at line 43 of file IndirectThunks.h.
References assert(), B, llvm::Function::Create(), F, llvm::FunctionType::get(), llvm::MachineModuleInfo::getModule(), llvm::Type::getVoidTy(), llvm::GlobalValue::HiddenVisibility, llvm::GlobalValue::InternalLinkage, llvm::GlobalValue::LinkOnceODRLinkage, and M.
doInitialization()
template<typename Derived > void llvm::ThunkInserter< Derived >::doInitialization (Module & M) inline protected
Definition at line 29 of file IndirectThunks.h.
init()
template<typename Derived > void llvm::ThunkInserter< Derived >::init (Module & M) inline
Definition at line 34 of file IndirectThunks.h.
References llvm::ThunkInserter< Derived >::InsertedThunks, and M.
run()
template<typename Derived > bool llvm::ThunkInserter< Derived >::run (MachineModuleInfo & MMI, MachineFunction & MF)
Definition at line 86 of file IndirectThunks.h.
References llvm::MachineFunction::getName(), and llvm::StringRef::startswith().
Member Data Documentation
InsertedThunks
template<typename Derived > bool llvm::ThunkInserter< Derived >::InsertedThunks protected
Definition at line 28 of file IndirectThunks.h.
Referenced by llvm::ThunkInserter< Derived >::init().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/IndirectThunks.h