LLVM: llvm::GlobalsAAResult Class Reference
llvm::GlobalsAAResult Class Reference
An alias analysis result set for globals.
#include "llvm/Analysis/GlobalsModRef.h"
Classes
class FunctionInfo
The mod/ref information collected for a particular function.
Public Member Functions
GlobalsAAResult (GlobalsAAResult &&Arg)
~GlobalsAAResult ()
bool invalidate (Module &M, const PreservedAnalyses &PA, ModuleAnalysisManager::Invalidator &)
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI)
alias - If one of the pointers is to a global that we are tracking, and the other is some random pointer, we know there cannot be an alias, because the address of the global isn't taken.
ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
FunctionModRefBehavior getModRefBehavior (const Function *F)
getModRefBehavior - Return the behavior of the specified function if called from the specified call site.
ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
ModRefInfo getModRefInfo (const CallBase *Call1, const CallBase *Call2, AAQueryInfo &AAQI)
FunctionModRefBehavior getModRefBehavior (const CallBase *Call)
FunctionModRefBehavior getModRefBehavior (const Function *F)
Public Member Functions inherited from llvm::AAResultBase< GlobalsAAResult >
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI)
bool pointsToConstantMemory (const MemoryLocation &Loc, AAQueryInfo &AAQI, bool OrLocal)
ModRefInfo getArgModRefInfo (const CallBase *Call, unsigned ArgIdx)
FunctionModRefBehavior getModRefBehavior (const CallBase *Call)
FunctionModRefBehavior getModRefBehavior (const Function *F)
ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
ModRefInfo getModRefInfo (const CallBase *Call1, const CallBase *Call2, AAQueryInfo &AAQI)
Static Public Member Functions
static GlobalsAAResult analyzeModule (Module &M, std::function< const TargetLibraryInfo &(Function &F)> GetTLI, CallGraph &CG)
Friends
struct RecomputeGlobalsAAPass
Additional Inherited Members
Protected Member Functions inherited from llvm::AAResultBase< GlobalsAAResult >
AAResultBase ()=default
AAResultBase (const AAResultBase &Arg)
AAResultBase (AAResultBase &&Arg)
AAResultsProxy getBestAAResults ()
Get a proxy for the best AA result set to query at this time.
Detailed Description
An alias analysis result set for globals.
This focuses on handling aliasing properties of globals and interprocedural function call mod/ref information.
Definition at line 30 of file GlobalsModRef.h.
Constructor & Destructor Documentation
GlobalsAAResult()
GlobalsAAResult::GlobalsAAResult (GlobalsAAResult && Arg)
Definition at line 959 of file GlobalsModRef.cpp.
References Arg, assert(), and H.
~GlobalsAAResult()
GlobalsAAResult::~GlobalsAAResult () default
Member Function Documentation
alias()
AliasResult GlobalsAAResult::alias (const MemoryLocation & LocA, const MemoryLocation & LocB, AAQueryInfo & AAQI)
alias - If one of the pointers is to a global that we are tracking, and the other is some random pointer, we know there cannot be an alias, because the address of the global isn't taken.
Definition at line 817 of file GlobalsModRef.cpp.
References llvm::AAResultBase< DerivedT >::alias(), EnableUnsafeGlobalsModRefAliasResults, llvm::getUnderlyingObject(), llvm::AliasResult::NoAlias, llvm::MemoryLocation::Ptr, and llvm::Value::stripPointerCastsForAliasAnalysis().
analyzeModule()
GlobalsAAResult GlobalsAAResult::analyzeModule (Module & M, std::function< const TargetLibraryInfo &(Function &F)> GetTLI, CallGraph & CG) static
Definition at line 975 of file GlobalsModRef.cpp.
References M.
Referenced by llvm::GlobalsAA::run(), and llvm::GlobalsAAWrapperPass::runOnModule().
getModRefBehavior() [1/3]
FunctionModRefBehavior llvm::AAResultBase< DerivedT >::getModRefBehavior inline
Definition at line 1236 of file AliasAnalysis.h.
getModRefBehavior() [2/3]
FunctionModRefBehavior llvm::AAResultBase< DerivedT >::getModRefBehavior inline
Definition at line 1240 of file AliasAnalysis.h.
getModRefBehavior() [3/3]
FunctionModRefBehavior GlobalsAAResult::getModRefBehavior (const Function * F)
getModRefBehavior - Return the behavior of the specified function if called from the specified call site.
The call site may be null in which case the most generic behavior of this function should be returned.
Definition at line 246 of file GlobalsModRef.cpp.
References F, llvm::FMRB_DoesNotAccessMemory, llvm::FMRB_OnlyReadsMemory, llvm::FMRB_UnknownModRefBehavior, llvm::AAResultBase< DerivedT >::getModRefBehavior(), llvm::isModOrRefSet(), and llvm::isModSet().
getModRefInfo() [1/3]
ModRefInfo llvm::AAResultBase< DerivedT >::getModRefInfo inline
Definition at line 1244 of file AliasAnalysis.h.
getModRefInfo() [2/3]
ModRefInfo GlobalsAAResult::getModRefInfo (const CallBase * Call, const MemoryLocation & Loc, AAQueryInfo & AAQI)
Definition at line 931 of file GlobalsModRef.cpp.
References F, llvm::AAResultBase< DerivedT >::getModRefInfo(), llvm::getUnderlyingObject(), llvm::GlobalValue::hasLocalLinkage(), llvm::intersectModRef(), llvm::isModOrRefSet(), llvm::ModRef, llvm::NoModRef, llvm::MemoryLocation::Ptr, and llvm::unionModRef().
getModRefInfo() [3/3]
ModRefInfo llvm::AAResultBase< DerivedT >::getModRefInfo inline
Definition at line 1249 of file AliasAnalysis.h.
invalidate()
bool GlobalsAAResult::invalidate (Module & M, const PreservedAnalyses & PA, ModuleAnalysisManager::Invalidator &)
Definition at line 806 of file GlobalsModRef.cpp.
References llvm::PreservedAnalyses::getChecker().
Friends And Related Function Documentation
RecomputeGlobalsAAPass
friend struct RecomputeGlobalsAAPass friend
Definition at line 81 of file GlobalsModRef.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/GlobalsModRef.h
lib/Analysis/GlobalsModRef.cpp