LLVM: llvm::DebuginfodDIFetcher Class Reference
llvm::DebuginfodDIFetcher Class Reference
#include "llvm/Debuginfod/DIFetcher.h"
Public Member Functions
virtual ~DebuginfodDIFetcher ()=default
Optional< std::string > fetchBuildID (ArrayRef< uint8_t > BuildID) const override
Fetches the given Build ID using debuginfod and returns a local path to the resulting debug binary.
Public Member Functions inherited from llvm::symbolize::DIFetcher
virtual ~DIFetcher ()=default
Detailed Description
Definition at line 23 of file DIFetcher.h.
Constructor & Destructor Documentation
~DebuginfodDIFetcher()
virtual llvm::DebuginfodDIFetcher::~DebuginfodDIFetcher () virtual default
Member Function Documentation
fetchBuildID()
Optional< std::string > DebuginfodDIFetcher::fetchBuildID (ArrayRef< uint8_t > BuildID) const override virtual
Fetches the given Build ID using debuginfod and returns a local path to the resulting debug binary.
Implements llvm::symbolize::DIFetcher.
Definition at line 22 of file DIFetcher.cpp.
References llvm::consumeError(), llvm::getCachedOrDownloadDebuginfo(), llvm::None, and llvm::Expected< T >::takeError().
The documentation for this class was generated from the following files:
include/llvm/Debuginfod/DIFetcher.h
lib/Debuginfod/DIFetcher.cpp