LLVM: llvm::AMDGPUMachineFunction Class Reference
llvm::AMDGPUMachineFunction Class Reference
#include "Target/AMDGPU/AMDGPUMachineFunction.h"
Public Member Functions
AMDGPUMachineFunction (const MachineFunction &MF)
uint64_t getExplicitKernArgSize () const
Align getMaxKernArgAlign () const
uint32_t getLDSSize () const
uint32_t getGDSSize () const
AMDGPU::SIModeRegisterDefaults getMode () const
bool isEntryFunction () const
bool isModuleEntryFunction () const
bool hasNoSignedZerosFPMath () const
bool isMemoryBound () const
bool needsWaveLimiter () const
unsigned allocateLDSGlobal (const DataLayout &DL, const GlobalVariable &GV)
void allocateModuleLDSGlobal (const Function &F)
Align getDynLDSAlign () const
void setDynLDSAlign (const DataLayout &DL, const GlobalVariable &GV)
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
virtual MachineFunctionInfo * clone (BumpPtrAllocator &Allocator, MachineFunction &DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > &Src2DstMBB) const
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
Static Public Member Functions
static Optional< uint32_t > getLDSKernelIdMetadata (const Function &F)
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, MachineFunction &MF)
Factory function: default behavior is to call new using the supplied allocator.
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, const Ty &MFI)
Protected Attributes
uint64_t ExplicitKernArgSize = 0
Align MaxKernArgAlign
uint32_t LDSSize = 0
Number of bytes in the LDS that are being used.
uint32_t GDSSize = 0
uint32_t StaticLDSSize = 0
Number of bytes in the LDS allocated statically.
uint32_t StaticGDSSize = 0
Align DynLDSAlign
Align for dynamic shared memory if any.
AMDGPU::SIModeRegisterDefaults Mode
bool IsEntryFunction = false
bool IsModuleEntryFunction = false
bool NoSignedZerosFPMath = false
bool MemoryBound = false
bool WaveLimiter = false
Detailed Description
Definition at line 23 of file AMDGPUMachineFunction.h.
Constructor & Destructor Documentation
AMDGPUMachineFunction()
AMDGPUMachineFunction::AMDGPUMachineFunction (const MachineFunction & MF)
Definition at line 19 of file AMDGPUMachineFunction.cpp.
References llvm::CallingConv::AMDGPU_KERNEL, ExplicitKernArgSize, F, GDSSize, llvm::AMDGPUSubtarget::get(), llvm::MachineFunction::getFunction(), llvm::Attribute::getValueAsBool(), MaxKernArgAlign, MemoryBound, S, llvm::CallingConv::SPIR_KERNEL, llvm::ARM_MB::ST, StaticGDSSize, and WaveLimiter.
Member Function Documentation
allocateLDSGlobal()
unsigned AMDGPUMachineFunction::allocateLDSGlobal (const DataLayout & DL, const GlobalVariable & GV)
TODO: We should sort these to minimize wasted space due to alignment padding. Currently the padding is decided by the first encountered use during lowering.
Definition at line 51 of file AMDGPUMachineFunction.cpp.
Referenced by allocateModuleLDSGlobal(), llvm::AMDGPULegalizerInfo::legalizeGlobalValue(), and llvm::AMDGPUTargetLowering::LowerGlobalAddress().
allocateModuleLDSGlobal()
void AMDGPUMachineFunction::allocateModuleLDSGlobal (const Function & F)
Definition at line 92 of file AMDGPUMachineFunction.cpp.
References allocateLDSGlobal(), assert(), canElideModuleLDS(), F, isModuleEntryFunction(), and M.
getDynLDSAlign()
Align llvm::AMDGPUMachineFunction::getDynLDSAlign () const inline
Definition at line 110 of file AMDGPUMachineFunction.h.
References DynLDSAlign.
getExplicitKernArgSize()
uint64_t llvm::AMDGPUMachineFunction::getExplicitKernArgSize () const inline
Definition at line 69 of file AMDGPUMachineFunction.h.
References ExplicitKernArgSize.
Referenced by llvm::AMDGPUTargetLowering::getImplicitParameterOffset().
getGDSSize()
uint32_t llvm::AMDGPUMachineFunction::getGDSSize () const inline
Definition at line 79 of file AMDGPUMachineFunction.h.
References GDSSize.
getLDSKernelIdMetadata()
Optional< uint32_t > AMDGPUMachineFunction::getLDSKernelIdMetadata (const Function & F) static
Definition at line 106 of file AMDGPUMachineFunction.cpp.
References F, and llvm::ConstantInt::getZExtValue().
Referenced by llvm::AMDGPULegalizerInfo::getLDSKernelId(), llvm::AMDGPUCallLowering::passSpecialInputs(), and llvm::SITargetLowering::passSpecialInputs().
getLDSSize()
uint32_t llvm::AMDGPUMachineFunction::getLDSSize () const inline
Definition at line 75 of file AMDGPUMachineFunction.h.
References LDSSize.
Referenced by llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::SIRegisterInfo::getRegPressureLimit(), llvm::PreRARematStage::initGCNSchedStage(), llvm::SIMachineFunctionInfo::limitOccupancy(), llvm::GCNTargetMachine::parseMachineFunctionInfo(), and llvm::SIMachineFunctionInfo::SIMachineFunctionInfo().
getMaxKernArgAlign()
Align llvm::AMDGPUMachineFunction::getMaxKernArgAlign () const inline
Definition at line 73 of file AMDGPUMachineFunction.h.
References MaxKernArgAlign.
getMode()
AMDGPU::SIModeRegisterDefaults llvm::AMDGPUMachineFunction::getMode () const inline
Definition at line 83 of file AMDGPUMachineFunction.h.
References Mode.
Referenced by llvm::AMDGPULegalizerInfo::legalizeFDIV32(), llvm::AMDGPULegalizerInfo::legalizeFFloor(), llvm::AMDGPULegalizerInfo::legalizeFMad(), llvm::AMDGPULegalizerInfo::legalizeMinNumMaxNum(), llvm::AMDGPULegalizerInfo::legalizeRsqClampIntrinsic(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), and llvm::AMDGPUTargetLowering::LowerUDIVREM64().
hasNoSignedZerosFPMath()
bool llvm::AMDGPUMachineFunction::hasNoSignedZerosFPMath () const inline
Definition at line 93 of file AMDGPUMachineFunction.h.
References NoSignedZerosFPMath.
isEntryFunction()
bool llvm::AMDGPUMachineFunction::isEntryFunction () const inline
Definition at line 87 of file AMDGPUMachineFunction.h.
References IsEntryFunction.
Referenced by llvm::SIMachineFunctionInfo::allocateSGPRSpillToVGPR(), llvm::SIRegisterInfo::buildSpillLoadStore(), llvm::SIFrameLowering::determineCalleeSaves(), llvm::SIFrameLowering::determineCalleeSavesSGPR(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::SIFrameLowering::emitEpilogue(), llvm::AMDGPUAsmPrinter::emitFunctionBodyEnd(), llvm::AMDGPUAsmPrinter::emitFunctionBodyStart(), llvm::AMDGPUAsmPrinter::emitFunctionEntryLabel(), llvm::SIFrameLowering::emitPrologue(), llvm::SIRegisterInfo::getFrameRegister(), llvm::SIMachineFunctionInfo::getScavengeFI(), llvm::SIFrameLowering::hasFP(), llvm::AMDGPULegalizerInfo::legalizeImplicitArgPtr(), llvm::AMDGPULegalizerInfo::legalizeLDSKernelId(), llvm::SIFrameLowering::processFunctionBeforeFrameFinalized(), llvm::SIFrameLowering::requiresStackPointerReference(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), and llvm::SIMachineFunctionInfo::SIMachineFunctionInfo().
isMemoryBound()
bool llvm::AMDGPUMachineFunction::isMemoryBound () const inline
Definition at line 97 of file AMDGPUMachineFunction.h.
References MemoryBound.
Referenced by llvm::SIMachineFunctionInfo::getMinAllowedOccupancy().
isModuleEntryFunction()
bool llvm::AMDGPUMachineFunction::isModuleEntryFunction () const inline
Definition at line 91 of file AMDGPUMachineFunction.h.
References IsModuleEntryFunction.
Referenced by allocateModuleLDSGlobal(), llvm::AMDGPULegalizerInfo::legalizeGlobalValue(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), and llvm::AMDGPUAsmPrinter::runOnMachineFunction().
needsWaveLimiter()
bool llvm::AMDGPUMachineFunction::needsWaveLimiter () const inline
Definition at line 101 of file AMDGPUMachineFunction.h.
References WaveLimiter.
Referenced by llvm::SIMachineFunctionInfo::getMinAllowedOccupancy(), and llvm::AMDGPUAsmPrinter::runOnMachineFunction().
setDynLDSAlign()
void AMDGPUMachineFunction::setDynLDSAlign (const DataLayout & DL, const GlobalVariable & GV)
Definition at line 120 of file AMDGPUMachineFunction.cpp.
References llvm::alignTo(), assert(), DL, DynLDSAlign, llvm::GlobalObject::getAlign(), llvm::GlobalValue::getValueType(), LDSSize, and StaticLDSSize.
Referenced by llvm::AMDGPULegalizerInfo::legalizeGlobalValue().
Member Data Documentation
DynLDSAlign
Align llvm::AMDGPUMachineFunction::DynLDSAlign protected
Align for dynamic shared memory if any.
Dynamic shared memory is allocated directly after the static one, i.e., LDSSize. Need to pad LDSSize to ensure that dynamic one is aligned accordingly. The maximal alignment is updated during IR translation or lowering stages.
Definition at line 46 of file AMDGPUMachineFunction.h.
Referenced by getDynLDSAlign(), and setDynLDSAlign().
ExplicitKernArgSize
uint64_t llvm::AMDGPUMachineFunction::ExplicitKernArgSize = 0 protected
Definition at line 29 of file AMDGPUMachineFunction.h.
Referenced by AMDGPUMachineFunction(), and getExplicitKernArgSize().
GDSSize
uint32_t llvm::AMDGPUMachineFunction::GDSSize = 0 protected
Definition at line 34 of file AMDGPUMachineFunction.h.
Referenced by AMDGPUMachineFunction(), and getGDSSize().
IsEntryFunction
bool llvm::AMDGPUMachineFunction::IsEntryFunction = false protected
Definition at line 53 of file AMDGPUMachineFunction.h.
Referenced by isEntryFunction().
IsModuleEntryFunction
bool llvm::AMDGPUMachineFunction::IsModuleEntryFunction = false protected
Definition at line 56 of file AMDGPUMachineFunction.h.
Referenced by isModuleEntryFunction().
LDSSize
uint32_t llvm::AMDGPUMachineFunction::LDSSize = 0 protected
Number of bytes in the LDS that are being used.
Definition at line 33 of file AMDGPUMachineFunction.h.
Referenced by getLDSSize(), and setDynLDSAlign().
MaxKernArgAlign
Align llvm::AMDGPUMachineFunction::MaxKernArgAlign protected
Definition at line 30 of file AMDGPUMachineFunction.h.
Referenced by AMDGPUMachineFunction(), getMaxKernArgAlign(), and llvm::SIMachineFunctionInfo::SIMachineFunctionInfo().
MemoryBound
bool llvm::AMDGPUMachineFunction::MemoryBound = false protected
Definition at line 61 of file AMDGPUMachineFunction.h.
Referenced by AMDGPUMachineFunction(), and isMemoryBound().
Mode
AMDGPU::SIModeRegisterDefaults llvm::AMDGPUMachineFunction::Mode protected
Definition at line 49 of file AMDGPUMachineFunction.h.
Referenced by getMode(), and llvm::GCNTargetMachine::parseMachineFunctionInfo().
NoSignedZerosFPMath
bool llvm::AMDGPUMachineFunction::NoSignedZerosFPMath = false protected
Definition at line 58 of file AMDGPUMachineFunction.h.
Referenced by hasNoSignedZerosFPMath().
StaticGDSSize
uint32_t llvm::AMDGPUMachineFunction::StaticGDSSize = 0 protected
Definition at line 39 of file AMDGPUMachineFunction.h.
Referenced by AMDGPUMachineFunction().
StaticLDSSize
uint32_t llvm::AMDGPUMachineFunction::StaticLDSSize = 0 protected
Number of bytes in the LDS allocated statically.
This field is only used in the instruction selector and not part of the machine function info.
Definition at line 38 of file AMDGPUMachineFunction.h.
Referenced by setDynLDSAlign().
WaveLimiter
bool llvm::AMDGPUMachineFunction::WaveLimiter = false protected
Definition at line 64 of file AMDGPUMachineFunction.h.
Referenced by AMDGPUMachineFunction(), and needsWaveLimiter().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUMachineFunction.h
lib/Target/AMDGPU/AMDGPUMachineFunction.cpp