LLVM: llvm::VPScalarIVStepsRecipe Class Reference
llvm::VPScalarIVStepsRecipe Class Reference
A recipe for handling phi nodes of integer and floating-point inductions, producing their scalar values.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPScalarIVStepsRecipe (Type *Ty, const InductionDescriptor &IndDesc, VPValue *CanonicalIV, VPValue *Start, VPValue *Step, Type *TruncToTy)
~VPScalarIVStepsRecipe () override=default
void execute (VPTransformState &State) override
Generate the scalarized versions of the phi node as needed by their users.
void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const override
Print the recipe.
bool isCanonical () const
Returns true if the induction is canonical, i.e.
VPCanonicalIVPHIRecipe * getCanonicalIV () const
VPValue * getStartValue () const
VPValue * getStepValue () const
bool onlyFirstLaneUsed (const VPValue *Op) const override
Returns true if the recipe only uses the first lane of operand Op.
Public Member Functions inherited from llvm::VPRecipeBase
VPRecipeBase (const unsigned char SC, ArrayRef< VPValue * > Operands)
template<typename IterT >
VPRecipeBase (const unsigned char SC, iterator_range< IterT > Operands)
virtual ~VPRecipeBase ()=default
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
void insertBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator IP)
Insert an unlinked recipe into BB immediately before the insertion point IP;.
void insertAfter (VPRecipeBase *InsertPos)
Insert an unlinked Recipe into a basic block immediately after the specified Recipe.
void moveAfter (VPRecipeBase *MovePos)
Unlink this recipe from its current VPBasicBlock and insert it into the VPBasicBlock that MovePos lives in, right after MovePos.
void moveBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator I)
Unlink this recipe and insert into BB before I.
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
Instruction * getUnderlyingInstr ()
Returns the underlying instruction, if the recipe is a VPValue or nullptr otherwise.
const Instruction * getUnderlyingInstr () const
bool mayHaveSideEffects () const
Returns true if the recipe may have side-effects.
bool isPhi () const
Returns true for PHI-like recipes.
bool mayReadFromMemory () const
Returns true if the recipe may read from memory.
bool mayWriteToMemory () const
Returns true if the recipe may write to memory.
bool mayReadOrWriteMemory () const
Returns true if the recipe may read from or write to memory.
Public Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
VPRecipeBase * getPrevNode ()
const VPRecipeBase * getPrevNode () const
Get the previous node, or nullptr for the list head.
VPRecipeBase * getNextNode ()
Get the next node, or nullptr for the list tail.
const VPRecipeBase * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::VPDef
VPDef (const unsigned char SC)
virtual ~VPDef ()
VPValue * getVPSingleValue ()
Returns the only VPValue defined by the VPDef.
const VPValue * getVPSingleValue () const
VPValue * getVPValue (unsigned I)
Returns the VPValue with index I defined by the VPDef.
const VPValue * getVPValue (unsigned I) const
ArrayRef< VPValue * > definedValues ()
Returns an ArrayRef of the values defined by the VPDef.
ArrayRef< VPValue * > definedValues () const
Returns an ArrayRef of the values defined by the VPDef.
unsigned getNumDefinedValues () const
Returns the number of values defined by the VPDef.
unsigned getVPDefID () const
void dump () const
Dump the VPDef to stderr (for debugging).
Public Member Functions inherited from llvm::VPUser
VPUser ()=delete
VPUser (const VPUser &)=delete
VPUser & operator= (const VPUser &)=delete
virtual ~VPUser ()
VPUserID getVPUserID () const
void addOperand (VPValue *Operand)
unsigned getNumOperands () const
VPValue * getOperand (unsigned N) const
void setOperand (unsigned I, VPValue *New)
void removeLastOperand ()
operand_iterator op_begin ()
const_operand_iterator op_begin () const
operand_iterator op_end ()
const_operand_iterator op_end () const
operand_range operands ()
const_operand_range operands () const
virtual bool usesScalars (const VPValue *Op) const
Returns true if the VPUser uses scalars of operand Op.
Public Member Functions inherited from llvm::VPValue
Value * getUnderlyingValue ()
Return the underlying Value attached to this VPValue.
const Value * getUnderlyingValue () const
VPValue (Value *UV=nullptr, VPDef *Def=nullptr)
VPValue (const VPValue &)=delete
VPValue & operator= (const VPValue &)=delete
virtual ~VPValue ()
unsigned getVPValueID () const
void printAsOperand (raw_ostream &OS, VPSlotTracker &Tracker) const
void print (raw_ostream &OS, VPSlotTracker &Tracker) const
void dump () const
Dump the value to stderr (for debugging).
unsigned getNumUsers () const
void addUser (VPUser &User)
void removeUser (VPUser &User)
Remove a single User from the list of users.
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
user_range users ()
const_user_range users () const
bool hasMoreThanOneUniqueUser ()
Returns true if the value has more than one unique user.
void replaceAllUsesWith (VPValue *New)
VPDef * getDef ()
const VPDef * getDef () const
Value * getLiveInIRValue ()
Returns the underlying IR value, if this VPValue is defined outside the scope of VPlan.
const Value * getLiveInIRValue () const
Static Public Member Functions
static bool classof (const VPDef *D)
Method to support type inquiry through isa, cast, and dyn_cast.
static bool classof (const VPUser *U)
Extra classof implementations to allow directly casting from VPUser -> VPScalarIVStepsRecipe.
static bool classof (const VPRecipeBase *R)
Static Public Member Functions inherited from llvm::VPRecipeBase
static bool classof (const VPDef *D)
Method to support type inquiry through isa, cast, and dyn_cast.
static bool classof (const VPUser *U)
Static Public Member Functions inherited from llvm::VPUser
static bool classof (const VPDef *Recipe)
Method to support type inquiry through isa, cast, and dyn_cast.
Additional Inherited Members
Public Types inherited from llvm::VPDef
using VPRecipeTy = enum { VPBranchOnMaskSC, VPExpandSCEVSC, VPInstructionSC, VPInterleaveSC, VPReductionSC, VPReplicateSC, VPScalarIVStepsSC, VPWidenCallSC, VPWidenCanonicalIVSC, VPWidenGEPSC, VPWidenMemoryInstructionSC, VPWidenSC, VPWidenSelectSC, VPBlendSC, VPCanonicalIVPHISC, VPActiveLaneMaskPHISC, VPFirstOrderRecurrencePHISC, VPWidenPHISC, VPWidenIntOrFpInductionSC, VPWidenPointerInductionSC, VPPredInstPHISC, VPReductionPHISC, VPFirstPHISC=VPBlendSC, VPLastPHISC=VPReductionPHISC, }
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Public Types inherited from llvm::VPUser
enum VPUserID { VPUserID::Recipe, VPUserID::LiveOut }
Subclass identifier (for isa/dyn_cast).
typedef SmallVectorImpl< VPValue * >::iterator operand_iterator
typedef SmallVectorImpl< VPValue * >::const_iterator const_operand_iterator
typedef iterator_range< operand_iterator > operand_range
typedef iterator_range< const_operand_iterator > const_operand_range
Public Types inherited from llvm::VPValue
enum {
VPValueSC, VPVInstructionSC, VPVMemoryInstructionSC, VPVReductionSC,
VPVReplicateSC, VPVWidenSC, VPVWidenCallSC, VPVWidenCanonicalIVSC,
VPVWidenGEPSC, VPVWidenSelectSC, VPVBlendSC, VPVCanonicalIVPHISC,
VPVActiveLaneMaskPHISC, VPVFirstOrderRecurrencePHISC, VPVWidenPHISC, VPVWidenIntOrFpInductionSC,
VPVWidenPointerInductionSC, VPVPredInstPHI, VPVReductionPHISC
}
An enumeration for keeping track of the concrete subclass of VPValue that are actually instantiated.
typedef SmallVectorImpl< VPUser * >::iterator user_iterator
typedef SmallVectorImpl< VPUser * >::const_iterator const_user_iterator
typedef iterator_range< user_iterator > user_range
typedef iterator_range< const_user_iterator > const_user_range
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type, true, true >
Protected Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
ilist_node_impl ()=default
Protected Member Functions inherited from llvm::VPUser
void printOperands (raw_ostream &O, VPSlotTracker &SlotTracker) const
Print the operands to O.
VPUser (ArrayRef< VPValue * > Operands, VPUserID ID)
VPUser (std::initializer_list< VPValue * > Operands, VPUserID ID)
template<typename IterT >
VPUser (iterator_range< IterT > Operands, VPUserID ID)
Protected Member Functions inherited from llvm::VPValue
VPValue (const unsigned char SC, Value *UV=nullptr, VPDef *Def=nullptr)
void setUnderlyingValue (Value *Val)
Protected Attributes inherited from llvm::VPValue
Value * UnderlyingVal
VPDef * Def
Pointer to the VPDef that defines this VPValue.
Detailed Description
A recipe for handling phi nodes of integer and floating-point inductions, producing their scalar values.
Definition at line 1960 of file VPlan.h.
Constructor & Destructor Documentation
VPScalarIVStepsRecipe()
llvm::VPScalarIVStepsRecipe::VPScalarIVStepsRecipe (Type * Ty, const InductionDescriptor & IndDesc, VPValue * CanonicalIV, VPValue * Start, VPValue * Step, Type * TruncToTy) inline
Definition at line 1968 of file VPlan.h.
~VPScalarIVStepsRecipe()
llvm::VPScalarIVStepsRecipe::~VPScalarIVStepsRecipe () override default
Member Function Documentation
classof() [1/3]
static bool llvm::VPScalarIVStepsRecipe::classof (const VPDef * D) inline static
Method to support type inquiry through isa, cast, and dyn_cast.
Definition at line 1978 of file VPlan.h.
References D.
classof() [2/3]
static bool llvm::VPScalarIVStepsRecipe::classof (const VPRecipeBase * R) inline static
Definition at line 1987 of file VPlan.h.
classof() [3/3]
static bool llvm::VPScalarIVStepsRecipe::classof (const VPUser * U) inline static
Extra classof implementations to allow directly casting from VPUser -> VPScalarIVStepsRecipe.
Definition at line 1983 of file VPlan.h.
execute()
void VPScalarIVStepsRecipe::execute (VPTransformState & State) override virtual
Generate the scalarized versions of the phi node as needed by their users.
Implements llvm::VPRecipeBase.
Definition at line 9430 of file LoopVectorize.cpp.
References assert(), llvm::VPTransformState::Builder, buildScalarSteps(), llvm::IRBuilderBase::CreateAdd(), llvm::IRBuilderBase::CreateBinOp(), llvm::IRBuilderBase::CreateCast(), llvm::IRBuilderBase::CreateFMul(), llvm::IRBuilderBase::CreateMul(), llvm::IRBuilderBase::CreateSExtOrTrunc(), llvm::IRBuilderBase::CreateTrunc(), emitTransformedIndex(), llvm::VPTransformState::get(), getParent(), llvm::getRuntimeVF(), llvm::getRuntimeVFAsFloat(), llvm::Value::getType(), llvm::VPTransformState::Instance, isCanonical(), llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), llvm::LinearPolySize< LeafTy >::isScalable(), llvm::ElementCount::isVector(), llvm::VPTransformState::set(), llvm::IRBuilderBase::setFastMathFlags(), llvm::Value::setName(), llvm::VPTransformState::UF, and llvm::VPTransformState::VF.
getCanonicalIV()
VPCanonicalIVPHIRecipe * VPScalarIVStepsRecipe::getCanonicalIV () const
Definition at line 647 of file VPlanRecipes.cpp.
References llvm::VPUser::getOperand().
Referenced by isCanonical().
getStartValue()
VPValue* llvm::VPScalarIVStepsRecipe::getStartValue () const inline
Definition at line 2005 of file VPlan.h.
References llvm::VPUser::getOperand().
Referenced by isCanonical().
getStepValue()
VPValue* llvm::VPScalarIVStepsRecipe::getStepValue () const inline
Definition at line 2006 of file VPlan.h.
References llvm::VPUser::getOperand().
Referenced by isCanonical().
isCanonical()
bool VPScalarIVStepsRecipe::isCanonical () const
Returns true if the induction is canonical, i.e.
starting at 0 and incremented by UF * VF (= the original IV is incremented by 1).
Definition at line 651 of file VPlanRecipes.cpp.
References getCanonicalIV(), getStartValue(), and getStepValue().
onlyFirstLaneUsed()
bool llvm::VPScalarIVStepsRecipe::onlyFirstLaneUsed (const VPValue * Op) const inline override virtual
Returns true if the recipe only uses the first lane of operand Op.
Reimplemented from llvm::VPUser.
Definition at line 2009 of file VPlan.h.
References assert(), llvm::is_contained(), and llvm::VPUser::operands().
print()
void VPScalarIVStepsRecipe::print (raw_ostream & O, const Twine & Indent, VPSlotTracker & SlotTracker) const override virtual
Print the recipe.
Implements llvm::VPDef.
Definition at line 665 of file VPlanRecipes.cpp.
References llvm::RISCVFenceField::O, llvm::VPValue::printAsOperand(), and llvm::VPUser::printOperands().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/LoopVectorize.cpp
lib/Transforms/Vectorize/VPlanRecipes.cpp