LLVM: llvm::AMDGPUTargetELFStreamer Class Reference
llvm::AMDGPUTargetELFStreamer Class Reference final
#include "Target/AMDGPU/MCTargetDesc/AMDGPUTargetStreamer.h"
Public Member Functions
AMDGPUTargetELFStreamer (MCStreamer &S, const MCSubtargetInfo &STI)
MCELFStreamer & getStreamer ()
void finish () override
void EmitDirectiveAMDGCNTarget () override
void EmitDirectiveHSACodeObjectVersion (uint32_t Major, uint32_t Minor) override
void EmitDirectiveHSACodeObjectISAV2 (uint32_t Major, uint32_t Minor, uint32_t Stepping, StringRef VendorName, StringRef ArchName) override
void EmitAMDKernelCodeT (const amd_kernel_code_t &Header) override
void EmitAMDGPUSymbolType (StringRef SymbolName, unsigned Type) override
void emitAMDGPULDS (MCSymbol *Sym, unsigned Size, Align Alignment) override
bool EmitISAVersion () override
bool EmitHSAMetadata (msgpack::Document &HSAMetadata, bool Strict) override
bool EmitHSAMetadata (const AMDGPU::HSAMD::Metadata &HSAMetadata) override
bool EmitCodeEnd (const MCSubtargetInfo &STI) override
void EmitAmdhsaKernelDescriptor (const MCSubtargetInfo &STI, StringRef KernelName, const amdhsa::kernel_descriptor_t &KernelDescriptor, uint64_t NextVGPR, uint64_t NextSGPR, bool ReserveVCC, bool ReserveFlatScr) override
Public Member Functions inherited from llvm::AMDGPUTargetStreamer
AMDGPUTargetStreamer (MCStreamer &S)
AMDGPUPALMetadata * getPALMetadata ()
virtual bool EmitHSAMetadataV2 (StringRef HSAMetadataString)
virtual bool EmitHSAMetadataV3 (StringRef HSAMetadataString)
const Optional< AMDGPU::IsaInfo::AMDGPUTargetID > & getTargetID () const
Optional< AMDGPU::IsaInfo::AMDGPUTargetID > & getTargetID ()
void initializeTargetID (const MCSubtargetInfo &STI)
void initializeTargetID (const MCSubtargetInfo &STI, StringRef FeatureString)
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, const MCExpr *SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void emitConstantPools ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::AMDGPUTargetStreamer
static StringRef getArchNameFromElfMach (unsigned ElfMach)
static unsigned getElfMach (StringRef GPU)
Protected Member Functions inherited from llvm::AMDGPUTargetStreamer
MCContext & getContext () const
Protected Attributes inherited from llvm::AMDGPUTargetStreamer
Optional< AMDGPU::IsaInfo::AMDGPUTargetID > TargetID
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 155 of file AMDGPUTargetStreamer.h.
Constructor & Destructor Documentation
AMDGPUTargetELFStreamer()
AMDGPUTargetELFStreamer::AMDGPUTargetELFStreamer (MCStreamer & S, const MCSubtargetInfo & STI)
Definition at line 495 of file AMDGPUTargetStreamer.cpp.
Member Function Documentation
emitAMDGPULDS()
void AMDGPUTargetELFStreamer::emitAMDGPULDS (MCSymbol * Sym, unsigned Size, Align Alignment) override virtual
Implements llvm::AMDGPUTargetStreamer.
Definition at line 734 of file AMDGPUTargetStreamer.cpp.
References llvm::MCConstantExpr::create(), llvm::MCSymbol::declareCommon(), llvm::AMDGPUTargetStreamer::getContext(), llvm::MCSymbolELF::isBindingSet(), llvm::report_fatal_error(), llvm::MCSymbolELF::setBinding(), llvm::MCSymbol::setExternal(), llvm::MCSymbol::setIndex(), llvm::MCSymbolELF::setSize(), llvm::MCSymbolELF::setType(), llvm::ELF::SHN_AMDGPU_LDS, llvm::Check::Size, llvm::ELF::STB_GLOBAL, llvm::ELF::STT_OBJECT, and llvm::ARMBuildAttrs::Symbol.
EmitAMDGPUSymbolType()
void AMDGPUTargetELFStreamer::EmitAMDGPUSymbolType (StringRef SymbolName, unsigned Type) override virtual
Implements llvm::AMDGPUTargetStreamer.
Definition at line 727 of file AMDGPUTargetStreamer.cpp.
References llvm::AMDGPUTargetStreamer::getContext(), getStreamer(), llvm::ARMBuildAttrs::Symbol, and llvm::AMDGPU::HSAMD::Kernel::Key::SymbolName.
EmitAmdhsaKernelDescriptor()
void AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor (const MCSubtargetInfo & STI, StringRef KernelName, const amdhsa::kernel_descriptor_t & KernelDescriptor, uint64_t NextVGPR, uint64_t NextSGPR, bool ReserveVCC, bool ReserveFlatScr) override virtual
Implements llvm::AMDGPUTargetStreamer.
Definition at line 849 of file AMDGPUTargetStreamer.cpp.
References llvm::amdhsa::kernel_descriptor_t::compute_pgm_rsrc1, llvm::amdhsa::kernel_descriptor_t::compute_pgm_rsrc2, llvm::amdhsa::kernel_descriptor_t::compute_pgm_rsrc3, Context, llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), llvm::MCStreamer::emitInt16(), llvm::MCStreamer::emitInt32(), llvm::MCStreamer::emitInt8(), llvm::MCStreamer::emitLabel(), llvm::MCStreamer::emitValue(), llvm::MCSymbolELF::getBinding(), llvm::MCStreamer::getContext(), llvm::MCSymbolELF::getOther(), getStreamer(), llvm::MCSymbolELF::getVisibility(), llvm::amdhsa::kernel_descriptor_t::group_segment_fixed_size, llvm::amdhsa::kernel_descriptor_t::kernarg_size, llvm::amdhsa::kernel_descriptor_t::kernel_code_entry_byte_offset, llvm::amdhsa::kernel_descriptor_t::kernel_code_properties, llvm::amdhsa::kernel_descriptor_t::private_segment_fixed_size, llvm::amdhsa::kernel_descriptor_t::reserved0, llvm::amdhsa::kernel_descriptor_t::reserved1, llvm::amdhsa::kernel_descriptor_t::reserved2, llvm::MCSymbolELF::setBinding(), llvm::MCSymbolELF::setOther(), llvm::MCSymbolELF::setSize(), llvm::MCSymbolELF::setType(), llvm::MCSymbolELF::setVisibility(), llvm::ELF::STT_OBJECT, llvm::ELF::STV_DEFAULT, llvm::ELF::STV_PROTECTED, llvm::MCSymbolRefExpr::VK_AMDGPU_REL64, and llvm::MCSymbolRefExpr::VK_None.
EmitAMDKernelCodeT()
void AMDGPUTargetELFStreamer::EmitAMDKernelCodeT (const amd_kernel_code_t & Header) override virtual
Implements llvm::AMDGPUTargetStreamer.
Definition at line 719 of file AMDGPUTargetStreamer.cpp.
References llvm::MCStreamer::emitBytes(), getStreamer(), llvm::MCStreamer::popSection(), and llvm::MCStreamer::pushSection().
EmitCodeEnd()
bool AMDGPUTargetELFStreamer::EmitCodeEnd (const MCSubtargetInfo & STI) override virtual
Returns
True on success, false on failure.
Implements llvm::AMDGPUTargetStreamer.
Definition at line 823 of file AMDGPUTargetStreamer.cpp.
References CacheLineSize, llvm::MCStreamer::emitInt32(), llvm::MCStreamer::emitValueToAlignment(), getStreamer(), I, llvm::AMDGPU::isGFX11Plus(), llvm::AMDGPU::isGFX90A(), llvm::MCStreamer::popSection(), and llvm::MCStreamer::pushSection().
EmitDirectiveAMDGCNTarget()
void AMDGPUTargetELFStreamer::EmitDirectiveAMDGCNTarget () override virtual
Implements llvm::AMDGPUTargetStreamer.
Definition at line 678 of file AMDGPUTargetStreamer.cpp.
EmitDirectiveHSACodeObjectISAV2()
void AMDGPUTargetELFStreamer::EmitDirectiveHSACodeObjectISAV2 (uint32_t Major, uint32_t Minor, uint32_t Stepping, StringRef VendorName, StringRef ArchName) override virtual
Implements llvm::AMDGPUTargetStreamer.
Definition at line 691 of file AMDGPUTargetStreamer.cpp.
References convertIsaVersionV2(), llvm::MCConstantExpr::create(), llvm::MCObjectStreamer::emitBytes(), llvm::MCStreamer::emitInt16(), llvm::MCStreamer::emitInt32(), llvm::MCStreamer::emitInt8(), llvm::AMDGPUTargetStreamer::getContext(), llvm::AMDGPU::ElfNote::NoteNameV2, llvm::ELF::NT_AMD_HSA_ISA_VERSION, llvm::StringRef::size(), and llvm::AMDGPUTargetStreamer::TargetID.
EmitDirectiveHSACodeObjectVersion()
void AMDGPUTargetELFStreamer::EmitDirectiveHSACodeObjectVersion (uint32_t Major, uint32_t Minor) override virtual
Implements llvm::AMDGPUTargetStreamer.
Definition at line 680 of file AMDGPUTargetStreamer.cpp.
References llvm::MCConstantExpr::create(), llvm::MCStreamer::emitInt32(), llvm::AMDGPUTargetStreamer::getContext(), llvm::AMDGPU::ElfNote::NoteNameV2, and llvm::ELF::NT_AMD_HSA_CODE_OBJECT_VERSION.
EmitHSAMetadata() [1/2]
bool AMDGPUTargetELFStreamer::EmitHSAMetadata (const AMDGPU::HSAMD::Metadata & HSAMetadata) override virtual
Returns
True on success, false on failure.
Implements llvm::AMDGPUTargetStreamer.
Definition at line 799 of file AMDGPUTargetStreamer.cpp.
References Context, llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), llvm::MCObjectStreamer::emitBytes(), llvm::MCELFStreamer::emitLabel(), llvm::AMDGPUTargetStreamer::getContext(), llvm::AMDGPU::ElfNote::NoteNameV2, llvm::ELF::NT_AMD_HSA_METADATA, and llvm::wasm::toString().
EmitHSAMetadata() [2/2]
bool AMDGPUTargetELFStreamer::EmitHSAMetadata (msgpack::Document & HSAMetadata, bool Strict) override virtual
Returns
True on success, false on failure.
Implements llvm::AMDGPUTargetStreamer.
Definition at line 772 of file AMDGPUTargetStreamer.cpp.
References Context, llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), llvm::MCObjectStreamer::emitBytes(), llvm::MCELFStreamer::emitLabel(), llvm::AMDGPUTargetStreamer::getContext(), llvm::msgpack::Document::getRoot(), llvm::AMDGPU::ElfNote::NoteNameV3, llvm::ELF::NT_AMDGPU_METADATA, llvm::FPOpFusion::Strict, Verifier, and llvm::msgpack::Document::writeToBlob().
EmitISAVersion()
bool AMDGPUTargetELFStreamer::EmitISAVersion () override virtual
Returns
True on success, false on failure.
Implements llvm::AMDGPUTargetStreamer.
Definition at line 753 of file AMDGPUTargetStreamer.cpp.
References Context, llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), llvm::MCObjectStreamer::emitBytes(), llvm::MCELFStreamer::emitLabel(), llvm::AMDGPUTargetStreamer::getContext(), llvm::AMDGPUTargetStreamer::getTargetID(), llvm::AMDGPU::ElfNote::NoteNameV2, llvm::ELF::NT_AMD_HSA_ISA_NAME, and llvm::toString().
finish()
void AMDGPUTargetELFStreamer::finish () override virtual
Reimplemented from llvm::MCTargetStreamer.
Definition at line 506 of file AMDGPUTargetStreamer.cpp.
References llvm::MCConstantExpr::create(), llvm::MCObjectStreamer::emitBytes(), llvm::MCObjectStreamer::getAssembler(), llvm::AMDGPUTargetStreamer::getContext(), llvm::AMDGPUTargetStreamer::getPALMetadata(), getStreamer(), llvm::AMDGPUPALMetadata::getType(), llvm::AMDGPUPALMetadata::getVendor(), llvm::AMDGPUPALMetadata::reset(), llvm::MCAssembler::setELFHeaderEFlags(), and llvm::AMDGPUPALMetadata::toBlob().
getStreamer()
MCELFStreamer & AMDGPUTargetELFStreamer::getStreamer ()
Definition at line 499 of file AMDGPUTargetStreamer.cpp.
Referenced by EmitAMDGPUSymbolType(), EmitAmdhsaKernelDescriptor(), EmitAMDKernelCodeT(), EmitCodeEnd(), and finish().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/MCTargetDesc/AMDGPUTargetStreamer.h
lib/Target/AMDGPU/MCTargetDesc/AMDGPUTargetStreamer.cpp