LLVM: llvm::MCPseudoProbeSection Class Reference
llvm::MCPseudoProbeSection Class Reference
Instances of this class represent the pseudo probes inserted into a compile unit.
#include "llvm/MC/MCPseudoProbe.h"
Public Types
using MCProbeDivisionMap = std::map< MCSection *, MCPseudoProbeInlineTree >
Public Member Functions
void addPseudoProbe (MCSection *Sec, const MCPseudoProbe &Probe, const MCPseudoProbeInlineStack &InlineStack)
const MCProbeDivisionMap & getMCProbes () const
bool empty () const
void emit (MCObjectStreamer *MCOS)
Detailed Description
Instances of this class represent the pseudo probes inserted into a compile unit.
Definition at line 279 of file MCPseudoProbe.h.
Member Typedef Documentation
MCProbeDivisionMap
using llvm::MCPseudoProbeSection::MCProbeDivisionMap = std::map<MCSection *, MCPseudoProbeInlineTree>
Definition at line 287 of file MCPseudoProbe.h.
Member Function Documentation
addPseudoProbe()
void llvm::MCPseudoProbeSection::addPseudoProbe (MCSection * Sec, const MCPseudoProbe & Probe, const MCPseudoProbeInlineStack & InlineStack) inline
Definition at line 281 of file MCPseudoProbe.h.
emit()
void MCPseudoProbeSection::emit (MCObjectStreamer * MCOS)
Definition at line 179 of file MCPseudoProbe.cpp.
References llvm::MCStreamer::getContext(), llvm::MCContext::getObjectFileInfo(), llvm::MCObjectFileInfo::getPseudoProbeSection(), S, and llvm::MCStreamer::switchSection().
empty()
bool llvm::MCPseudoProbeSection::empty () const inline
Definition at line 301 of file MCPseudoProbe.h.
getMCProbes()
const MCProbeDivisionMap& llvm::MCPseudoProbeSection::getMCProbes () const inline
Definition at line 299 of file MCPseudoProbe.h.
The documentation for this class was generated from the following files:
include/llvm/MC/MCPseudoProbe.h
lib/MC/MCPseudoProbe.cpp