LLVM: llvm::SampleContextTracker::Iterator Class Reference
llvm::SampleContextTracker::Iterator Class Reference
#include "llvm/Transforms/IPO/SampleContextTracker.h"
Public Member Functions
Iterator ()=default
Iterator (ContextTrieNode *Node)
Iterator & operator++ ()
Iterator operator++ (int)
bool operator== (const Iterator &Other) const
bool operator!= (const Iterator &Other) const
ContextTrieNode * operator* () const
Detailed Description
Definition at line 146 of file SampleContextTracker.h.
Constructor & Destructor Documentation
Iterator() [1/2]
llvm::SampleContextTracker::Iterator::Iterator () explicit default
Iterator() [2/2]
llvm::SampleContextTracker::Iterator::Iterator (ContextTrieNode * Node) inline explicit
Definition at line 152 of file SampleContextTracker.h.
Member Function Documentation
operator!=()
bool llvm::SampleContextTracker::Iterator::operator!= (const Iterator & Other) const inline
Definition at line 175 of file SampleContextTracker.h.
References Other.
operator*()
ContextTrieNode* llvm::SampleContextTracker::Iterator::operator* () const inline
Definition at line 176 of file SampleContextTracker.h.
References assert().
operator++() [1/2]
Iterator& llvm::SampleContextTracker::Iterator::operator++ () inline
Definition at line 153 of file SampleContextTracker.h.
References assert().
operator++() [2/2]
Iterator llvm::SampleContextTracker::Iterator::operator++ (int) inline
Definition at line 162 of file SampleContextTracker.h.
References assert(), and llvm::MipsISD::Ret.
operator==()
bool llvm::SampleContextTracker::Iterator::operator== (const Iterator & Other) const inline
Definition at line 168 of file SampleContextTracker.h.
References Other.
The documentation for this class was generated from the following file:
include/llvm/Transforms/IPO/SampleContextTracker.h