LLVM: TailFoldingKind Class Reference
TailFoldingKind Class Reference
Public Types
enum TailFoldingOpts {
TFDisabled = 0x0, TFReductions = 0x01, TFRecurrences = 0x02, TFSimple = 0x80,
TFAll = TFReductions | TFRecurrences | TFSimple
}
Public Member Functions
void operator= (const std::string &Val)
operator uint8_t () const
void add (uint8_t Flag)
void remove (uint8_t Flag)
Detailed Description
Definition at line 41 of file AArch64TargetTransformInfo.cpp.
Member Enumeration Documentation
TailFoldingOpts
enum TailFoldingKind::TailFoldingOpts
Enumerator
TFDisabled
TFReductions
TFRecurrences
TFSimple
TFAll
Definition at line 46 of file AArch64TargetTransformInfo.cpp.
Member Function Documentation
add()
void TailFoldingKind::add (uint8_t Flag) inline
Definition at line 88 of file AArch64TargetTransformInfo.cpp.
References llvm::tgtok::Bits.
operator uint8_t()
TailFoldingKind::operator uint8_t () const inline
Definition at line 86 of file AArch64TargetTransformInfo.cpp.
References llvm::tgtok::Bits.
operator=()
void TailFoldingKind::operator= (const std::string & Val) inline
Definition at line 54 of file AArch64TargetTransformInfo.cpp.
References llvm::ARM_AM::add, llvm::tgtok::Bits, llvm::errs(), llvm::sys::fs::remove(), and llvm::StringRef::split().
remove()
void TailFoldingKind::remove (uint8_t Flag) inline
Definition at line 89 of file AArch64TargetTransformInfo.cpp.
References llvm::tgtok::Bits.
The documentation for this class was generated from the following file:
lib/Target/AArch64/AArch64TargetTransformInfo.cpp