LLVM: llvm::AMDGPU::HSAMD::MetadataStreamerV3 Class Reference
llvm::AMDGPU::HSAMD::MetadataStreamerV3 Class Reference
#include "Target/AMDGPU/AMDGPUHSAMetadataStreamer.h"
Public Member Functions
MetadataStreamerV3 ()=default
~MetadataStreamerV3 ()=default
bool emitTo (AMDGPUTargetStreamer &TargetStreamer) override
void begin (const Module &Mod, const IsaInfo::AMDGPUTargetID &TargetID) override
void end () override
void emitKernel (const MachineFunction &MF, const SIProgramInfo &ProgramInfo) override
Public Member Functions inherited from llvm::AMDGPU::HSAMD::MetadataStreamer
virtual ~MetadataStreamer ()=default
Protected Member Functions
void dump (StringRef HSAMetadataString) const
void verify (StringRef HSAMetadataString) const
Optional< StringRef > getAccessQualifier (StringRef AccQual) const
Optional< StringRef > getAddressSpaceQualifier (unsigned AddressSpace) const
StringRef getValueKind (Type *Ty, StringRef TypeQual, StringRef BaseTypeName) const
std::string getTypeName (Type *Ty, bool Signed) const
msgpack::ArrayDocNode getWorkGroupDimensions (MDNode *Node) const
msgpack::MapDocNode getHSAKernelProps (const MachineFunction &MF, const SIProgramInfo &ProgramInfo) const
void emitVersion () override
void emitPrintf (const Module &Mod)
void emitKernelLanguage (const Function &Func, msgpack::MapDocNode Kern)
void emitKernelAttrs (const Function &Func, msgpack::MapDocNode Kern)
void emitKernelArgs (const MachineFunction &MF, msgpack::MapDocNode Kern)
void emitKernelArg (const Argument &Arg, unsigned &Offset, msgpack::ArrayDocNode Args)
void emitKernelArg (const DataLayout &DL, Type *Ty, Align Alignment, StringRef ValueKind, unsigned &Offset, msgpack::ArrayDocNode Args, MaybeAlign PointeeAlign=None, StringRef Name="", StringRef TypeName="", StringRef BaseTypeName="", StringRef AccQual="", StringRef TypeQual="")
void emitHiddenKernelArgs (const MachineFunction &MF, unsigned &Offset, msgpack::ArrayDocNode Args) override
msgpack::DocNode & getRootMetadata (StringRef Key)
msgpack::DocNode & getHSAMetadataRoot ()
Protected Attributes
std::unique_ptr< msgpack::Document > HSAMetadataDoc
Detailed Description
Definition at line 64 of file AMDGPUHSAMetadataStreamer.h.
Constructor & Destructor Documentation
MetadataStreamerV3()
llvm::AMDGPU::HSAMD::MetadataStreamerV3::MetadataStreamerV3 () default
~MetadataStreamerV3()
llvm::AMDGPU::HSAMD::MetadataStreamerV3::~MetadataStreamerV3 () default
Member Function Documentation
begin()
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::begin (const Module & Mod, const IsaInfo::AMDGPUTargetID & TargetID) override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Reimplemented in llvm::AMDGPU::HSAMD::MetadataStreamerV4.
Definition at line 908 of file AMDGPUHSAMetadataStreamer.cpp.
References emitPrintf(), emitVersion(), getRootMetadata(), HSAMetadataDoc, and Mod.
dump()
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::dump (StringRef HSAMetadataString) const protected
Definition at line 483 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::errs().
Referenced by end().
emitHiddenKernelArgs()
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::emitHiddenKernelArgs (const MachineFunction & MF, unsigned & Offset, msgpack::ArrayDocNode Args) override protected virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Reimplemented in llvm::AMDGPU::HSAMD::MetadataStreamerV5.
Definition at line 794 of file AMDGPUHSAMetadataStreamer.cpp.
References Align, llvm::alignTo(), llvm::AMDGPU::HSAMD::Kernel::Key::Args, DL, emitKernelArg(), llvm::MachineFunction::getFunction(), llvm::Type::getInt64Ty(), llvm::Type::getInt8PtrTy(), llvm::MachineFunction::getSubtarget(), llvm::AMDGPUAS::GLOBAL_ADDRESS, M, and llvm::ARM_MB::ST.
Referenced by emitKernelArgs().
emitKernel()
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::emitKernel (const MachineFunction & MF, const SIProgramInfo & ProgramInfo) override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 926 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::CallingConv::AMDGPU_KERNEL, assert(), emitKernelArgs(), emitKernelAttrs(), emitKernelLanguage(), llvm::msgpack::DocNode::getArray(), llvm::msgpack::DocNode::getDocument(), llvm::MachineFunction::getFunction(), getHSAKernelProps(), llvm::msgpack::Document::getNode(), getRootMetadata(), llvm::AMDGPU::HSAMD::Key::Kernels, and llvm::CallingConv::SPIR_KERNEL.
emitKernelArg() [1/2]
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::emitKernelArg (const Argument & Arg, unsigned & Offset, msgpack::ArrayDocNode Args) protected
Definition at line 690 of file AMDGPUHSAMetadataStreamer.cpp.
References Arg.
Referenced by emitHiddenKernelArgs(), llvm::AMDGPU::HSAMD::MetadataStreamerV5::emitHiddenKernelArgs(), and emitKernelArgs().
emitKernelArg() [2/2]
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::emitKernelArg (const DataLayout & DL, Type * Ty, Align Alignment, StringRef ValueKind, unsigned & Offset, msgpack::ArrayDocNode Args, MaybeAlign PointeeAlign = None, StringRef Name = "", StringRef TypeName = "", StringRef BaseTypeName = "", StringRef AccQual = "", StringRef TypeQual = "") protected
Definition at line 749 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::AccQual, llvm::alignTo(), Arg, llvm::AMDGPU::HSAMD::Kernel::Key::Args, DL, getAccessQualifier(), getAddressSpaceQualifier(), llvm::AMDGPU::HSAMD::Kernel::Arg::Key::PointeeAlign, llvm::StringRef::split(), and llvm::AMDGPU::HSAMD::Kernel::Arg::Key::TypeName.
emitKernelArgs()
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::emitKernelArgs (const MachineFunction & MF, msgpack::MapDocNode Kern) protected
Definition at line 677 of file AMDGPUHSAMetadataStreamer.cpp.
References Arg, llvm::AMDGPU::HSAMD::Kernel::Key::Args, emitHiddenKernelArgs(), emitKernelArg(), llvm::MachineFunction::getFunction(), and HSAMetadataDoc.
Referenced by emitKernel().
emitKernelAttrs()
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::emitKernelAttrs (const Function & Func, msgpack::MapDocNode Kern) protected
Definition at line 652 of file AMDGPUHSAMetadataStreamer.cpp.
Referenced by emitKernel().
emitKernelLanguage()
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::emitKernelLanguage (const Function & Func, msgpack::MapDocNode Kern) protected
Definition at line 633 of file AMDGPUHSAMetadataStreamer.cpp.
Referenced by emitKernel().
emitPrintf()
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::emitPrintf (const Module & Mod) protected
Definition at line 620 of file AMDGPUHSAMetadataStreamer.cpp.
Referenced by begin(), and llvm::AMDGPU::HSAMD::MetadataStreamerV4::begin().
emitTo()
bool llvm::AMDGPU::HSAMD::MetadataStreamerV3::emitTo (AMDGPUTargetStreamer & TargetStreamer) override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 904 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::AMDGPUTargetStreamer::EmitHSAMetadata(), and HSAMetadataDoc.
emitVersion()
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::emitVersion () override protected virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Reimplemented in llvm::AMDGPU::HSAMD::MetadataStreamerV5, and llvm::AMDGPU::HSAMD::MetadataStreamerV4.
Definition at line 613 of file AMDGPUHSAMetadataStreamer.cpp.
References getRootMetadata(), HSAMetadataDoc, llvm::IndexedInstrProf::Version, llvm::AMDGPU::HSAMD::VersionMajorV3, and llvm::AMDGPU::HSAMD::VersionMinorV3.
Referenced by begin().
end()
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::end () override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 915 of file AMDGPUHSAMetadataStreamer.cpp.
References dump(), llvm::DumpHSAMetadata, HSAMetadataDoc, llvm::raw_string_ostream::str(), verify(), and llvm::VerifyHSAMetadata.
getAccessQualifier()
Optional< StringRef > llvm::AMDGPU::HSAMD::MetadataStreamerV3::getAccessQualifier (StringRef AccQual) const protected
Definition at line 509 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::AccQual, and llvm::None.
Referenced by emitKernelArg().
getAddressSpaceQualifier()
Optional< StringRef > llvm::AMDGPU::HSAMD::MetadataStreamerV3::getAddressSpaceQualifier (unsigned AddressSpace) const protected
Definition at line 518 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::AMDGPUAS::CONSTANT_ADDRESS, llvm::AMDGPUAS::FLAT_ADDRESS, llvm::AMDGPUAS::GLOBAL_ADDRESS, llvm::AMDGPUAS::LOCAL_ADDRESS, llvm::None, llvm::AMDGPUAS::PRIVATE_ADDRESS, and llvm::AMDGPUAS::REGION_ADDRESS.
Referenced by emitKernelArg().
getHSAKernelProps()
msgpack::MapDocNode llvm::AMDGPU::HSAMD::MetadataStreamerV3::getHSAKernelProps (const MachineFunction & MF, const SIProgramInfo & ProgramInfo) const protected
Definition at line 863 of file AMDGPUHSAMetadataStreamer.cpp.
References Align, llvm::SIProgramInfo::DynamicCallStack, F, llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::AMDGPUSubtarget::getKernArgSegmentSize(), llvm::MachineFunction::getSubtarget(), llvm::AMDGPUSubtarget::getWavefrontSize(), llvm::GCNSubtarget::hasMAIInsts(), HSAMetadataDoc, llvm::SIProgramInfo::LDSSize, llvm::max(), llvm::SIProgramInfo::NumAccVGPR, llvm::SIProgramInfo::NumSGPR, llvm::SIProgramInfo::NumVGPR, and llvm::SIProgramInfo::ScratchSize.
Referenced by emitKernel().
getHSAMetadataRoot()
msgpack::DocNode& llvm::AMDGPU::HSAMD::MetadataStreamerV3::getHSAMetadataRoot () inline protected
Definition at line 114 of file AMDGPUHSAMetadataStreamer.h.
References HSAMetadataDoc.
getRootMetadata()
msgpack::DocNode& llvm::AMDGPU::HSAMD::MetadataStreamerV3::getRootMetadata (StringRef Key) inline protected
Definition at line 110 of file AMDGPUHSAMetadataStreamer.h.
References HSAMetadataDoc.
Referenced by begin(), llvm::AMDGPU::HSAMD::MetadataStreamerV4::begin(), emitKernel(), llvm::AMDGPU::HSAMD::MetadataStreamerV4::emitTargetID(), emitVersion(), llvm::AMDGPU::HSAMD::MetadataStreamerV4::emitVersion(), and llvm::AMDGPU::HSAMD::MetadataStreamerV5::emitVersion().
getTypeName()
std::string llvm::AMDGPU::HSAMD::MetadataStreamerV3::getTypeName (Type * Ty, bool Signed) const protected
Definition at line 564 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::BitWidth, llvm::Type::DoubleTyID, llvm::Type::FixedVectorTyID, llvm::Type::FloatTyID, llvm::Type::getIntegerBitWidth(), llvm::Type::getTypeID(), llvm::Type::HalfTyID, llvm::Type::IntegerTyID, and Signed.
getValueKind()
StringRef llvm::AMDGPU::HSAMD::MetadataStreamerV3::getValueKind (Type * Ty, StringRef TypeQual, StringRef BaseTypeName) const protected
Definition at line 537 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringRef::contains(), llvm::StringSwitch< T, R >::Default(), llvm::Type::getPointerAddressSpace(), and llvm::AMDGPUAS::LOCAL_ADDRESS.
getWorkGroupDimensions()
msgpack::ArrayDocNode llvm::AMDGPU::HSAMD::MetadataStreamerV3::getWorkGroupDimensions (MDNode * Node) const protected
Definition at line 602 of file AMDGPUHSAMetadataStreamer.cpp.
verify()
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::verify (StringRef HSAMetadataString) const protected
Definition at line 487 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::errs(), llvm::msgpack::Document::fromYAML(), llvm::raw_string_ostream::str(), and llvm::msgpack::Document::toYAML().
Referenced by end().
Member Data Documentation
HSAMetadataDoc
std::unique_ptr<msgpack::Document> llvm::AMDGPU::HSAMD::MetadataStreamerV3::HSAMetadataDoc protected
Initial value:
=
      std::make_unique<msgpack::Document>()
Definition at line 66 of file AMDGPUHSAMetadataStreamer.h.
Referenced by begin(), llvm::AMDGPU::HSAMD::MetadataStreamerV4::begin(), emitKernelArgs(), llvm::AMDGPU::HSAMD::MetadataStreamerV4::emitTargetID(), emitTo(), emitVersion(), llvm::AMDGPU::HSAMD::MetadataStreamerV4::emitVersion(), llvm::AMDGPU::HSAMD::MetadataStreamerV5::emitVersion(), end(), getHSAKernelProps(), getHSAMetadataRoot(), and getRootMetadata().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUHSAMetadataStreamer.h
lib/Target/AMDGPU/AMDGPUHSAMetadataStreamer.cpp