LLVM: llvm::ConstraintSystem Class Reference
llvm::ConstraintSystem Class Reference
#include "llvm/Analysis/ConstraintSystem.h"
Public Member Functions
bool addVariableRow (ArrayRef< int64_t > R)
bool addVariableRowFill (ArrayRef< int64_t > R)
bool mayHaveSolution ()
Returns true if there may be a solution for the constraints in the system.
bool isConditionImplied (SmallVector< int64_t, 8 > R) const
ArrayRef< int64_t > getLastConstraint ()
void popLastConstraint ()
void popLastNVariables (unsigned N)
unsigned size () const
Returns the number of rows in the constraint system.
void dump (ArrayRef< std::string > Names) const
Print the constraints in the system, using Names as variable names.
Static Public Member Functions
static SmallVector< int64_t, 8 > negate (SmallVector< int64_t, 8 > R)
Detailed Description
Definition at line 20 of file ConstraintSystem.h.
Member Function Documentation
addVariableRow()
bool llvm::ConstraintSystem::addVariableRow (ArrayRef< int64_t > R) inline
Definition at line 39 of file ConstraintSystem.h.
References llvm::abs(), llvm::all_of(), assert(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::APIntOps::GreatestCommonDivisor(), and llvm::makeArrayRef().
Referenced by addVariableRowFill().
addVariableRowFill()
bool llvm::ConstraintSystem::addVariableRowFill (ArrayRef< int64_t > R) inline
Definition at line 55 of file ConstraintSystem.h.
References addVariableRow(), llvm::all_of(), and llvm::makeArrayRef().
Referenced by dumpWithNames().
dump()
void ConstraintSystem::dump (ArrayRef< std::string > Names) const
Print the constraints in the system, using Names as variable names.
Definition at line 109 of file ConstraintSystem.cpp.
References assert(), llvm::dbgs(), I, LLVM_DEBUG, S, and llvm::to_string().
getLastConstraint()
ArrayRef<int64_t> llvm::ConstraintSystem::getLastConstraint () inline
Definition at line 82 of file ConstraintSystem.h.
isConditionImplied()
bool ConstraintSystem::isConditionImplied (SmallVector< int64_t, 8 > R) const
Definition at line 144 of file ConstraintSystem.cpp.
References llvm::all_of(), llvm::makeArrayRef(), and negate().
mayHaveSolution()
bool ConstraintSystem::mayHaveSolution ()
Returns true if there may be a solution for the constraints in the system.
Definition at line 137 of file ConstraintSystem.cpp.
References llvm::dbgs(), and LLVM_DEBUG.
negate()
static SmallVector<int64_t, 8> llvm::ConstraintSystem::negate (SmallVector< int64_t, 8 > R) inline static
Definition at line 71 of file ConstraintSystem.h.
Referenced by eliminateConstraints(), and isConditionImplied().
popLastConstraint()
void llvm::ConstraintSystem::popLastConstraint () inline
Definition at line 83 of file ConstraintSystem.h.
popLastNVariables()
void llvm::ConstraintSystem::popLastNVariables (unsigned N) inline
Definition at line 84 of file ConstraintSystem.h.
References i, and N.
size()
unsigned llvm::ConstraintSystem::size () const inline
Returns the number of rows in the constraint system.
Definition at line 92 of file ConstraintSystem.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/ConstraintSystem.h
lib/Analysis/ConstraintSystem.cpp