LLVM: llvm::PriorityInlineOrder Class Reference
llvm::PriorityInlineOrder Class Reference
#include "llvm/Analysis/InlineOrder.h"
Public Member Functions
PriorityInlineOrder (std::unique_ptr< InlinePriority > PriorityPtr)
size_t size () override
void push (const T &Elt) override
T pop () override
const_reference front () override
void erase_if (function_ref< bool(T)> Pred) override
Public Member Functions inherited from llvm::InlineOrder< std::pair< CallBase *, int > >
virtual ~InlineOrder ()=default
virtual void push (const std::pair< CallBase *, int > &Elt)=0
virtual void erase_if (function_ref< bool(std::pair< CallBase *, int >)> Pred)=0
bool empty ()
Additional Inherited Members
Public Types inherited from llvm::InlineOrder< std::pair< CallBase *, int > >
using reference = std::pair< CallBase *, int > &
using const_reference = const std::pair< CallBase *, int > &
Detailed Description
Definition at line 114 of file InlineOrder.h.
Constructor & Destructor Documentation
PriorityInlineOrder()
llvm::PriorityInlineOrder::PriorityInlineOrder (std::unique_ptr< InlinePriority > PriorityPtr) inline
Definition at line 134 of file InlineOrder.h.
Member Function Documentation
erase_if()
void llvm::PriorityInlineOrder::erase_if (function_ref< bool(T)> Pred) inline override
Definition at line 173 of file InlineOrder.h.
References llvm::erase_if().
front()
const_reference llvm::PriorityInlineOrder::front () inline override virtual
Implements llvm::InlineOrder< std::pair< CallBase *, int > >.
Definition at line 165 of file InlineOrder.h.
References assert(), and size().
pop()
T llvm::PriorityInlineOrder::pop () inline override virtual
Implements llvm::InlineOrder< std::pair< CallBase *, int > >.
Definition at line 153 of file InlineOrder.h.
References assert(), and size().
push()
void llvm::PriorityInlineOrder::push (const T & Elt) inline override
Definition at line 143 of file InlineOrder.h.
size()
size_t llvm::PriorityInlineOrder::size () inline override virtual
Implements llvm::InlineOrder< std::pair< CallBase *, int > >.
Definition at line 141 of file InlineOrder.h.
Referenced by front(), and pop().
The documentation for this class was generated from the following file:
include/llvm/Analysis/InlineOrder.h