LLVM: llvm::AMDGPU::HSAMD::MetadataStreamerV5 Class Reference
llvm::AMDGPU::HSAMD::MetadataStreamerV5 Class Reference final
#include "Target/AMDGPU/AMDGPUHSAMetadataStreamer.h"
Public Member Functions
MetadataStreamerV5 ()=default
~MetadataStreamerV5 ()=default
Public Member Functions inherited from llvm::AMDGPU::HSAMD::MetadataStreamerV4
MetadataStreamerV4 ()=default
~MetadataStreamerV4 ()=default
void begin (const Module &Mod, const IsaInfo::AMDGPUTargetID &TargetID) override
Public Member Functions inherited from llvm::AMDGPU::HSAMD::MetadataStreamerV3
MetadataStreamerV3 ()=default
~MetadataStreamerV3 ()=default
bool emitTo (AMDGPUTargetStreamer &TargetStreamer) override
void end () override
void emitKernel (const MachineFunction &MF, const SIProgramInfo &ProgramInfo) override
Public Member Functions inherited from llvm::AMDGPU::HSAMD::MetadataStreamer
virtual ~MetadataStreamer ()=default
Protected Member Functions
void emitVersion () override
void emitHiddenKernelArgs (const MachineFunction &MF, unsigned &Offset, msgpack::ArrayDocNode Args) override
Protected Member Functions inherited from llvm::AMDGPU::HSAMD::MetadataStreamerV4
void emitTargetID (const IsaInfo::AMDGPUTargetID &TargetID)
Protected Member Functions inherited from llvm::AMDGPU::HSAMD::MetadataStreamerV3
void dump (StringRef HSAMetadataString) const
void verify (StringRef HSAMetadataString) const
Optional< StringRef > getAccessQualifier (StringRef AccQual) const
Optional< StringRef > getAddressSpaceQualifier (unsigned AddressSpace) const
StringRef getValueKind (Type *Ty, StringRef TypeQual, StringRef BaseTypeName) const
std::string getTypeName (Type *Ty, bool Signed) const
msgpack::ArrayDocNode getWorkGroupDimensions (MDNode *Node) const
msgpack::MapDocNode getHSAKernelProps (const MachineFunction &MF, const SIProgramInfo &ProgramInfo) const
void emitPrintf (const Module &Mod)
void emitKernelLanguage (const Function &Func, msgpack::MapDocNode Kern)
void emitKernelAttrs (const Function &Func, msgpack::MapDocNode Kern)
void emitKernelArgs (const MachineFunction &MF, msgpack::MapDocNode Kern)
void emitKernelArg (const Argument &Arg, unsigned &Offset, msgpack::ArrayDocNode Args)
void emitKernelArg (const DataLayout &DL, Type *Ty, Align Alignment, StringRef ValueKind, unsigned &Offset, msgpack::ArrayDocNode Args, MaybeAlign PointeeAlign=None, StringRef Name="", StringRef TypeName="", StringRef BaseTypeName="", StringRef AccQual="", StringRef TypeQual="")
msgpack::DocNode & getRootMetadata (StringRef Key)
msgpack::DocNode & getHSAMetadataRoot ()
Additional Inherited Members
Protected Attributes inherited from llvm::AMDGPU::HSAMD::MetadataStreamerV3
std::unique_ptr< msgpack::Document > HSAMetadataDoc
Detailed Description
Definition at line 148 of file AMDGPUHSAMetadataStreamer.h.
Constructor & Destructor Documentation
MetadataStreamerV5()
llvm::AMDGPU::HSAMD::MetadataStreamerV5::MetadataStreamerV5 () default
~MetadataStreamerV5()
llvm::AMDGPU::HSAMD::MetadataStreamerV5::~MetadataStreamerV5 () default
Member Function Documentation
emitHiddenKernelArgs()
void llvm::AMDGPU::HSAMD::MetadataStreamerV5::emitHiddenKernelArgs (const MachineFunction & MF, unsigned & Offset, msgpack::ArrayDocNode Args) override protected virtual
Reimplemented from llvm::AMDGPU::HSAMD::MetadataStreamerV3.
Definition at line 984 of file AMDGPUHSAMetadataStreamer.cpp.
References Align, llvm::alignTo(), llvm::AMDGPU::HSAMD::Kernel::Key::Args, DL, llvm::AMDGPU::HSAMD::MetadataStreamerV3::emitKernelArg(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::Type::getInt16Ty(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::Type::getInt8PtrTy(), llvm::MachineFunction::getSubtarget(), llvm::AMDGPUAS::GLOBAL_ADDRESS, llvm::SIMachineFunctionInfo::hasQueuePtr(), Int32Ty, M, and llvm::ARM_MB::ST.
emitVersion()
void llvm::AMDGPU::HSAMD::MetadataStreamerV5::emitVersion () override protected virtual
Reimplemented from llvm::AMDGPU::HSAMD::MetadataStreamerV4.
Definition at line 977 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::AMDGPU::HSAMD::MetadataStreamerV3::getRootMetadata(), llvm::AMDGPU::HSAMD::MetadataStreamerV3::HSAMetadataDoc, llvm::IndexedInstrProf::Version, llvm::AMDGPU::HSAMD::VersionMajorV5, and llvm::AMDGPU::HSAMD::VersionMinorV5.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUHSAMetadataStreamer.h
lib/Target/AMDGPU/AMDGPUHSAMetadataStreamer.cpp