LLVM: R600MCInstLower Class Reference
R600MCInstLower Class Reference
Public Member Functions
R600MCInstLower (MCContext &ctx, const R600Subtarget &ST, const AsmPrinter &AP)
void lower (const MachineInstr *MI, MCInst &OutMI) const
Lower a MachineInstr to an MCInst.
Public Member Functions inherited from AMDGPUMCInstLower
AMDGPUMCInstLower (MCContext &ctx, const TargetSubtargetInfo &ST, const AsmPrinter &AP)
bool lowerOperand (const MachineOperand &MO, MCOperand &MCOp) const
void lower (const MachineInstr *MI, MCInst &OutMI) const
Lower a MachineInstr to an MCInst.
Detailed Description
Definition at line 23 of file R600MCInstLower.cpp.
Constructor & Destructor Documentation
R600MCInstLower()
R600MCInstLower::R600MCInstLower (MCContext & ctx, const R600Subtarget & ST, const AsmPrinter & AP)
Definition at line 32 of file R600MCInstLower.cpp.
Member Function Documentation
lower()
void R600MCInstLower::lower (const MachineInstr * MI, MCInst & OutMI) const
Lower a MachineInstr to an MCInst.
Definition at line 36 of file R600MCInstLower.cpp.
References llvm::MCInst::addOperand(), AMDGPUMCInstLower::lowerOperand(), MI, and llvm::MCInst::setOpcode().
The documentation for this class was generated from the following file:
lib/Target/AMDGPU/R600MCInstLower.cpp