LLVM: llvm::UnclusteredRescheduleStage Class Reference
llvm::UnclusteredRescheduleStage Class Reference
#include "Target/AMDGPU/GCNSchedStrategy.h"
Public Member Functions
bool initGCNSchedStage () override
void finalizeGCNSchedStage () override
bool initGCNRegion () override
bool shouldRevertScheduling (unsigned WavesAfter) override
UnclusteredRescheduleStage (GCNSchedStageID StageID, GCNScheduleDAGMILive &DAG)
Public Member Functions inherited from llvm::GCNSchedStage
void setupNewBlock ()
virtual void finalizeGCNRegion ()
void checkScheduling ()
bool mayCauseSpilling (unsigned WavesAfter)
void revertScheduling ()
void advanceRegion ()
virtual ~GCNSchedStage ()=default
Additional Inherited Members
Protected Member Functions inherited from llvm::GCNSchedStage
GCNSchedStage (GCNSchedStageID StageID, GCNScheduleDAGMILive &DAG)
Protected Attributes inherited from llvm::GCNSchedStage
GCNScheduleDAGMILive & DAG
GCNMaxOccupancySchedStrategy & S
MachineFunction & MF
SIMachineFunctionInfo & MFI
const GCNSubtarget & ST
const GCNSchedStageID StageID
MachineBasicBlock * CurrentMBB = nullptr
unsigned RegionIdx = 0
std::vector< MachineInstr * > Unsched
GCNRegPressure PressureBefore
GCNRegPressure PressureAfter
Detailed Description
Definition at line 252 of file GCNSchedStrategy.h.
Constructor & Destructor Documentation
UnclusteredRescheduleStage()
llvm::UnclusteredRescheduleStage::UnclusteredRescheduleStage (GCNSchedStageID StageID, GCNScheduleDAGMILive & DAG) inline
Definition at line 265 of file GCNSchedStrategy.h.
Member Function Documentation
finalizeGCNSchedStage()
void UnclusteredRescheduleStage::finalizeGCNSchedStage () override virtual
Reimplemented from llvm::GCNSchedStage.
Definition at line 568 of file GCNSchedStrategy.cpp.
References llvm::GCNSchedStage::DAG, llvm::GCNSchedStage::finalizeGCNSchedStage(), and llvm::ScheduleDAGMI::Mutations.
initGCNRegion()
bool UnclusteredRescheduleStage::initGCNRegion () override virtual
Reimplemented from llvm::GCNSchedStage.
Definition at line 617 of file GCNSchedStrategy.cpp.
References llvm::GCNSchedStage::DAG, llvm::GCNSchedStage::initGCNRegion(), and llvm::GCNSchedStage::RegionIdx.
initGCNSchedStage()
bool UnclusteredRescheduleStage::initGCNSchedStage () override virtual
Reimplemented from llvm::GCNSchedStage.
Definition at line 506 of file GCNSchedStrategy.cpp.
References llvm::GCNSchedStage::DAG, llvm::dbgs(), llvm::GCNSchedStage::initGCNSchedStage(), LLVM_DEBUG, llvm::ScheduleDAGMI::Mutations, and llvm::BitVector::none().
shouldRevertScheduling()
bool UnclusteredRescheduleStage::shouldRevertScheduling (unsigned WavesAfter) override virtual
Reimplemented from llvm::GCNSchedStage.
Definition at line 769 of file GCNSchedStrategy.cpp.
References llvm::dbgs(), llvm::GCNRegPressure::less(), LLVM_DEBUG, llvm::GCNSchedStage::PressureAfter, llvm::GCNSchedStage::PressureBefore, llvm::GCNSchedStage::shouldRevertScheduling(), and llvm::GCNSchedStage::ST.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/GCNSchedStrategy.h
lib/Target/AMDGPU/GCNSchedStrategy.cpp