LLVM: llvm::TargetLibraryInfo Class Reference
llvm::TargetLibraryInfo Class Reference
Provides information about what library functions are available for the current target.
#include "llvm/Analysis/TargetLibraryInfo.h"
Public Member Functions
TargetLibraryInfo (const TargetLibraryInfoImpl &Impl, Optional< const Function * > F=None)
TargetLibraryInfo (const TargetLibraryInfo &TLI)=default
TargetLibraryInfo (TargetLibraryInfo &&TLI)
TargetLibraryInfo & operator= (const TargetLibraryInfo &TLI)=default
TargetLibraryInfo & operator= (TargetLibraryInfo &&TLI)
bool areInlineCompatible (const TargetLibraryInfo &CalleeTLI, bool AllowCallerSuperset) const
Determine whether a callee with the given TLI can be inlined into caller with this TLI, based on 'nobuiltin' attributes.
bool isValidProtoForLibFunc (const FunctionType &FTy, LibFunc F, const Module &M) const
Return true if the function type FTy is valid for the library function F, regardless of whether the function is available.
bool getLibFunc (StringRef funcName, LibFunc &F) const
Searches for a particular function name.
bool getLibFunc (const Function &FDecl, LibFunc &F) const
bool getLibFunc (const CallBase &CB, LibFunc &F) const
If a callbase does not have the 'nobuiltin' attribute, return if the called function is a known library function and set F to that function.
void disableAllFunctions () LLVM_ATTRIBUTE_UNUSED
Disables all builtins.
void setUnavailable (LibFunc F) LLVM_ATTRIBUTE_UNUSED
Forces a function to be marked as unavailable.
TargetLibraryInfoImpl::AvailabilityState getState (LibFunc F) const
bool has (LibFunc F) const
Tests whether a library function is available.
bool isFunctionVectorizable (StringRef F, const ElementCount &VF) const
bool isFunctionVectorizable (StringRef F) const
StringRef getVectorizedFunction (StringRef F, const ElementCount &VF) const
bool hasOptimizedCodeGen (LibFunc F) const
Tests if the function is both available and a candidate for optimized code generation.
StringRef getName (LibFunc F) const
Attribute::AttrKind getExtAttrForI32Param (bool Signed=true) const
Returns extension attribute kind to be used for i32 parameters corresponding to C-level int or unsigned int.
Attribute::AttrKind getExtAttrForI32Return (bool Signed=true) const
Returns extension attribute kind to be used for i32 return values corresponding to C-level int or unsigned int.
unsigned getWCharSize (const Module &M) const
Returns the size of the wchar_t type in bytes or 0 if the size is unknown.
unsigned getIntSize () const
Get size of a C-level int or unsigned int, in bits.
bool invalidate (Module &, const PreservedAnalyses &, ModuleAnalysisManager::Invalidator &)
Handle invalidation from the pass manager.
bool invalidate (Function &, const PreservedAnalyses &, FunctionAnalysisManager::Invalidator &)
void getWidestVF (StringRef ScalarF, ElementCount &FixedVF, ElementCount &ScalableVF) const
Returns the largest vectorization factor used in the list of vector functions.
bool isKnownVectorFunctionInLibrary (StringRef F) const
Check if the function "F" is listed in a library known to LLVM.
Friends
class TargetLibraryAnalysis
class TargetLibraryInfoWrapperPass
Detailed Description
Provides information about what library functions are available for the current target.
This both allows optimizations to handle them specially and frontends to disable such optimizations through -fno-builtin etc.
Definition at line 222 of file TargetLibraryInfo.h.
Constructor & Destructor Documentation
TargetLibraryInfo() [1/3]
llvm::TargetLibraryInfo::TargetLibraryInfo (const TargetLibraryInfoImpl & Impl, Optional< const Function * > F = None) inline explicit
Definition at line 234 of file TargetLibraryInfo.h.
References disableAllFunctions(), F, getLibFunc(), and setUnavailable().
TargetLibraryInfo() [2/3]
llvm::TargetLibraryInfo::TargetLibraryInfo (const TargetLibraryInfo & TLI) default
TargetLibraryInfo() [3/3]
llvm::TargetLibraryInfo::TargetLibraryInfo (TargetLibraryInfo && TLI) inline
Definition at line 259 of file TargetLibraryInfo.h.
Member Function Documentation
areInlineCompatible()
bool llvm::TargetLibraryInfo::areInlineCompatible (const TargetLibraryInfo & CalleeTLI, bool AllowCallerSuperset) const inline
Determine whether a callee with the given TLI can be inlined into caller with this TLI, based on 'nobuiltin' attributes.
When requested, allow inlining into a caller with a superset of the callee's nobuiltin attributes, which is conservatively correct.
Definition at line 272 of file TargetLibraryInfo.h.
References B.
disableAllFunctions()
void llvm::TargetLibraryInfo::disableAllFunctions () inline
Disables all builtins.
This can be used for options like -fno-builtin.
Definition at line 312 of file TargetLibraryInfo.h.
References llvm::BitVector::set().
Referenced by TargetLibraryInfo().
getExtAttrForI32Param()
Attribute::AttrKind llvm::TargetLibraryInfo::getExtAttrForI32Param (bool Signed = true) const inline
Returns extension attribute kind to be used for i32 parameters corresponding to C-level int or unsigned int.
May be zeroext, signext, or none.
Definition at line 387 of file TargetLibraryInfo.h.
References llvm::Attribute::None, and Signed.
Referenced by getOrInsertValueProfilingCall(), and setArgExtAttr().
getExtAttrForI32Return()
Attribute::AttrKind llvm::TargetLibraryInfo::getExtAttrForI32Return (bool Signed = true) const inline
Returns extension attribute kind to be used for i32 return values corresponding to C-level int or unsigned int.
May be zeroext, signext, or none.
Definition at line 398 of file TargetLibraryInfo.h.
References llvm::Attribute::None, and Signed.
getIntSize()
unsigned llvm::TargetLibraryInfo::getIntSize () const inline
Get size of a C-level int or unsigned int, in bits.
Definition at line 410 of file TargetLibraryInfo.h.
References llvm::TargetLibraryInfoImpl::getIntSize().
getLibFunc() [1/3]
bool llvm::TargetLibraryInfo::getLibFunc (const CallBase & CB, LibFunc & F) const inline
If a callbase does not have the 'nobuiltin' attribute, return if the called function is a known library function and set F to that function.
Definition at line 304 of file TargetLibraryInfo.h.
References F, llvm::CallBase::getCalledFunction(), getLibFunc(), and llvm::CallBase::isNoBuiltin().
getLibFunc() [2/3]
bool llvm::TargetLibraryInfo::getLibFunc (const Function & FDecl, LibFunc & F) const inline
Definition at line 298 of file TargetLibraryInfo.h.
References F, and llvm::TargetLibraryInfoImpl::getLibFunc().
getLibFunc() [3/3]
bool llvm::TargetLibraryInfo::getLibFunc (StringRef funcName, LibFunc & F) const inline
Searches for a particular function name.
If it is one of the known library functions, return true and set F to the corresponding value.
Definition at line 294 of file TargetLibraryInfo.h.
References F, and llvm::TargetLibraryInfoImpl::getLibFunc().
Referenced by llvm::callsGCLeafFunction(), llvm::MemoryOpRemark::canHandle(), llvm::ConstantFoldCall(), llvm::emitBinaryFloatFnCall(), llvm::emitUnaryFloatFnCall(), foldSqrt(), getAllocationDataForFunction(), llvm::getAllocationFamily(), llvm::MemoryLocation::getForArgument(), llvm::getFreedOperand(), llvm::getIntrinsicForCallSite(), getLibFunc(), llvm::inferNonMandatoryLibFuncAttrs(), insertSinCosCall(), isKnownLibFunction(), llvm::isLibFuncEmittable(), llvm::isMathLibCallNoop(), isWriteOnlyParam(), llvm::maybeMarkSanitizerLibraryCallNoBuiltin(), llvm::FortifiedLibCallSimplifier::optimizeCall(), optimizeCall(), runPartiallyInlineLibCalls(), and TargetLibraryInfo().
getName()
StringRef llvm::TargetLibraryInfo::getName (LibFunc F) const inline
Definition at line 374 of file TargetLibraryInfo.h.
References assert(), F, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and getState().
Referenced by llvm::emitCalloc(), llvm::emitFPutC(), llvm::emitFPutS(), llvm::emitFWrite(), emitLibCall(), llvm::emitMalloc(), llvm::emitPutChar(), llvm::emitPutS(), llvm::getFloatFn(), llvm::getOrInsertLibFunc(), and llvm::isLibFuncEmittable().
getState()
TargetLibraryInfoImpl::AvailabilityState llvm::TargetLibraryInfo::getState (LibFunc F) const inline
Definition at line 321 of file TargetLibraryInfo.h.
References F.
Referenced by getName(), has(), and hasOptimizedCodeGen().
getVectorizedFunction()
StringRef llvm::TargetLibraryInfo::getVectorizedFunction (StringRef F, const ElementCount & VF) const inline
Definition at line 337 of file TargetLibraryInfo.h.
References F, and llvm::TargetLibraryInfoImpl::getVectorizedFunction().
Referenced by addMappingsFromTLI(), and replaceWithCallToVeclib().
getWCharSize()
unsigned llvm::TargetLibraryInfo::getWCharSize (const Module & M) const inline
Returns the size of the wchar_t type in bytes or 0 if the size is unknown.
This queries the 'wchar_size' metadata.
Definition at line 405 of file TargetLibraryInfo.h.
References llvm::TargetLibraryInfoImpl::getWCharSize(), and M.
getWidestVF()
void llvm::TargetLibraryInfo::getWidestVF (StringRef ScalarF, ElementCount & FixedVF, ElementCount & ScalableVF) const inline
Returns the largest vectorization factor used in the list of vector functions.
Definition at line 428 of file TargetLibraryInfo.h.
References llvm::TargetLibraryInfoImpl::getWidestVF().
Referenced by addMappingsFromTLI(), and llvm::isTLIScalarize().
has()
bool llvm::TargetLibraryInfo::has (LibFunc F) const inline
Tests whether a library function is available.
Definition at line 328 of file TargetLibraryInfo.h.
References F, and getState().
Referenced by llvm::callsGCLeafFunction(), llvm::MemoryOpRemark::canHandle(), getAllocationDataForFunction(), llvm::getAllocationFamily(), llvm::MemoryLocation::getForArgument(), llvm::getFreedOperand(), llvm::getOrInsertLibFunc(), llvm::inferNonMandatoryLibFuncAttrs(), llvm::isLibFuncEmittable(), isWriteOnlyParam(), and runPartiallyInlineLibCalls().
hasOptimizedCodeGen()
bool llvm::TargetLibraryInfo::hasOptimizedCodeGen (LibFunc F) const inline
Tests if the function is both available and a candidate for optimized code generation.
Definition at line 343 of file TargetLibraryInfo.h.
References F, and getState().
Referenced by llvm::maybeMarkSanitizerLibraryCallNoBuiltin().
invalidate() [1/2]
bool llvm::TargetLibraryInfo::invalidate (Function & , const PreservedAnalyses & , FunctionAnalysisManager::Invalidator &) inline
Definition at line 422 of file TargetLibraryInfo.h.
invalidate() [2/2]
bool llvm::TargetLibraryInfo::invalidate (Module & , const PreservedAnalyses & , ModuleAnalysisManager::Invalidator &) inline
Handle invalidation from the pass manager.
If we try to invalidate this info, just return false. It cannot become invalid even if the module or function changes.
Definition at line 418 of file TargetLibraryInfo.h.
isFunctionVectorizable() [1/2]
bool llvm::TargetLibraryInfo::isFunctionVectorizable (StringRef F) const inline
Definition at line 334 of file TargetLibraryInfo.h.
References F, and llvm::TargetLibraryInfoImpl::isFunctionVectorizable().
isFunctionVectorizable() [2/2]
bool llvm::TargetLibraryInfo::isFunctionVectorizable (StringRef F, const ElementCount & VF) const inline
Definition at line 331 of file TargetLibraryInfo.h.
References F, and llvm::TargetLibraryInfoImpl::isFunctionVectorizable().
Referenced by addMappingsFromTLI(), isKnownVectorFunctionInLibrary(), llvm::isTLIScalarize(), and replaceWithCallToVeclib().
isKnownVectorFunctionInLibrary()
bool llvm::TargetLibraryInfo::isKnownVectorFunctionInLibrary (StringRef F) const inline
Check if the function "F" is listed in a library known to LLVM.
Definition at line 434 of file TargetLibraryInfo.h.
References isFunctionVectorizable().
Referenced by isKnownLibFunction().
isValidProtoForLibFunc()
bool llvm::TargetLibraryInfo::isValidProtoForLibFunc (const FunctionType & FTy, LibFunc F, const Module & M) const inline
Return true if the function type FTy is valid for the library function F, regardless of whether the function is available.
Definition at line 285 of file TargetLibraryInfo.h.
References F, and M.
Referenced by llvm::isLibFuncEmittable().
operator=() [1/2]
TargetLibraryInfo& llvm::TargetLibraryInfo::operator= (const TargetLibraryInfo & TLI) default
operator=() [2/2]
TargetLibraryInfo& llvm::TargetLibraryInfo::operator= (TargetLibraryInfo && TLI) inline
Definition at line 262 of file TargetLibraryInfo.h.
setUnavailable()
void llvm::TargetLibraryInfo::setUnavailable (LibFunc F) inline
Forces a function to be marked as unavailable.
Definition at line 317 of file TargetLibraryInfo.h.
References F, and llvm::BitVector::set().
Referenced by TargetLibraryInfo().
Friends And Related Function Documentation
TargetLibraryAnalysis
friend class TargetLibraryAnalysis friend
Definition at line 223 of file TargetLibraryInfo.h.
TargetLibraryInfoWrapperPass
friend class TargetLibraryInfoWrapperPass friend
Definition at line 224 of file TargetLibraryInfo.h.
The documentation for this class was generated from the following file:
include/llvm/Analysis/TargetLibraryInfo.h