LLVM: llvm::optional_detail::OptionalStorage< T, true > Class Template Reference
llvm::optional_detail::OptionalStorage< T, true > Class Template Reference
#include "llvm/ADT/Optional.h"
Public Member Functions
~OptionalStorage ()=default
constexpr OptionalStorage () noexcept
constexpr OptionalStorage (OptionalStorage const &other)=default
constexpr OptionalStorage (OptionalStorage &&other)=default
OptionalStorage & operator= (OptionalStorage const &other)=default
OptionalStorage & operator= (OptionalStorage &&other)=default
template<class... Args>
constexpr OptionalStorage (in_place_t, Args &&...args)
void reset () noexcept
constexpr bool has_value () const noexcept
constexpr bool hasValue () const noexcept
T & value () &noexcept
T & getValue () &noexcept
constexpr const T & value () const &noexcept
constexpr const T & getValue () const &noexcept
T && value () &&noexcept
T && getValue () &&noexcept
template<class... Args>
void emplace (Args &&...args)
OptionalStorage & operator= (T const &y)
OptionalStorage & operator= (T &&y)
Detailed Description
template<typename T>
class llvm::optional_detail::OptionalStorage< T, true >
Definition at line 176 of file Optional.h.
Constructor & Destructor Documentation
~OptionalStorage()
template<typename T > llvm::optional_detail::OptionalStorage< T, true >::~OptionalStorage () default
OptionalStorage() [1/4]
template<typename T > constexpr llvm::optional_detail::OptionalStorage< T, true >::OptionalStorage () inline constexpr noexcept
Definition at line 186 of file Optional.h.
OptionalStorage() [2/4]
template<typename T > constexpr llvm::optional_detail::OptionalStorage< T, true >::OptionalStorage (OptionalStorage< T, true > const & other) constexpr default
OptionalStorage() [3/4]
template<typename T > constexpr llvm::optional_detail::OptionalStorage< T, true >::OptionalStorage (OptionalStorage< T, true > && other) constexpr default
OptionalStorage() [4/4]
template<typename T > template<class... Args> constexpr llvm::optional_detail::OptionalStorage< T, true >::OptionalStorage (in_place_t , Args &&... args) inline explicit constexpr
Definition at line 195 of file Optional.h.
Member Function Documentation
emplace()
template<typename T > template<class... Args> void llvm::optional_detail::OptionalStorage< T, true >::emplace (Args &&... args) inline
Definition at line 233 of file Optional.h.
References new, llvm::optional_detail::OptionalStorage< T, bool >::reset(), T, and llvm::optional_detail::OptionalStorage< T, bool >::val.
getValue() [1/3]
template<typename T > T&& llvm::optional_detail::OptionalStorage< T, true >::getValue () && inline noexcept
Definition at line 228 of file Optional.h.
References assert(), move, T, and llvm::optional_detail::OptionalStorage< T, bool >::val.
getValue() [2/3]
template<typename T > T& llvm::optional_detail::OptionalStorage< T, true >::getValue () & inline noexcept
Definition at line 212 of file Optional.h.
References assert(), T, and llvm::optional_detail::OptionalStorage< T, bool >::val.
getValue() [3/3]
template<typename T > constexpr const T& llvm::optional_detail::OptionalStorage< T, true >::getValue () const & inline constexpr noexcept
Definition at line 220 of file Optional.h.
References assert(), T, and llvm::optional_detail::OptionalStorage< T, bool >::val.
has_value()
template<typename T > constexpr bool llvm::optional_detail::OptionalStorage< T, true >::has_value () const inline constexpr noexcept
Definition at line 205 of file Optional.h.
hasValue()
template<typename T > constexpr bool llvm::optional_detail::OptionalStorage< T, true >::hasValue () const inline constexpr noexcept
Definition at line 206 of file Optional.h.
operator=() [1/4]
template<typename T > OptionalStorage& llvm::optional_detail::OptionalStorage< T, true >::operator= (OptionalStorage< T, true > && other) default
operator=() [2/4]
template<typename T > OptionalStorage& llvm::optional_detail::OptionalStorage< T, true >::operator= (OptionalStorage< T, true > const & other) default
operator=() [3/4]
template<typename T > OptionalStorage& llvm::optional_detail::OptionalStorage< T, true >::operator= (T && y) inline
Definition at line 248 of file Optional.h.
References llvm::optional_detail::OptionalStorage< T, bool >::has_value(), move, new, T, llvm::optional_detail::OptionalStorage< T, bool >::val, and y.
operator=() [4/4]
template<typename T > OptionalStorage& llvm::optional_detail::OptionalStorage< T, true >::operator= (T const & y) inline
Definition at line 239 of file Optional.h.
References llvm::optional_detail::OptionalStorage< T, bool >::has_value(), new, T, llvm::optional_detail::OptionalStorage< T, bool >::val, and y.
reset()
template<typename T > void llvm::optional_detail::OptionalStorage< T, true >::reset () inline noexcept
Definition at line 198 of file Optional.h.
References llvm::optional_detail::OptionalStorage< T, bool >::val.
value() [1/3]
template<typename T > T&& llvm::optional_detail::OptionalStorage< T, true >::value () && inline noexcept
Definition at line 224 of file Optional.h.
References assert(), move, T, and llvm::optional_detail::OptionalStorage< T, bool >::val.
value() [2/3]
template<typename T > T& llvm::optional_detail::OptionalStorage< T, true >::value () & inline noexcept
Definition at line 208 of file Optional.h.
References assert(), T, and llvm::optional_detail::OptionalStorage< T, bool >::val.
value() [3/3]
template<typename T > constexpr const T& llvm::optional_detail::OptionalStorage< T, true >::value () const & inline constexpr noexcept
Definition at line 216 of file Optional.h.
References assert(), T, and llvm::optional_detail::OptionalStorage< T, bool >::val.
Member Data Documentation
empty
template<typename T > char llvm::optional_detail::OptionalStorage< T, true >::empty
Definition at line 178 of file Optional.h.
val
template<typename T > T llvm::optional_detail::OptionalStorage< T, true >::val
Definition at line 179 of file Optional.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/Optional.h