LLVM: lib/Target/DirectX/DXILTranslateMetadata.cpp File Reference
DXILTranslateMetadata.cpp File Reference
#include "DirectX.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/Triple.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
Functions
static uint32_t ConstMDToUint32 (const MDOperand &MDO)
static ConstantAsMetadata * Uint32ToConstMD (unsigned v, LLVMContext &Ctx)
static void emitDXILValidatorVersion (Module &M, VersionTuple &ValidatorVer)
static VersionTuple loadDXILValidatorVersion (MDNode *ValVerMD)
static void cleanModuleFlags (Module &M)
static void cleanModule (Module &M)
Variables
constexpr StringLiteral ValVerKey = "dx.valver"
constexpr unsigned DXILVersionNumFields = 2
Function Documentation
cleanModule()
static void cleanModule (Module & M) static
Definition at line 85 of file DXILTranslateMetadata.cpp.
References cleanModuleFlags(), and M.
cleanModuleFlags()
static void cleanModuleFlags (Module & M) static
Definition at line 61 of file DXILTranslateMetadata.cpp.
References llvm::StringSet< AllocatorTy >::contains(), llvm::StringMapImpl::empty(), llvm::NamedMDNode::eraseFromParent(), llvm::StringSet< AllocatorTy >::insert(), M, and ValVerKey.
Referenced by cleanModule().
ConstMDToUint32()
static uint32_t ConstMDToUint32 (const MDOperand & MDO) static
Definition at line 21 of file DXILTranslateMetadata.cpp.
References llvm::ConstantInt::getZExtValue().
Referenced by loadDXILValidatorVersion().
emitDXILValidatorVersion()
static void emitDXILValidatorVersion (Module & M, VersionTuple & ValidatorVer) static
Definition at line 34 of file DXILTranslateMetadata.cpp.
References llvm::NamedMDNode::addOperand(), DXILVersionNumFields, llvm::MDNode::get(), llvm::VersionTuple::getMajor(), llvm::VersionTuple::getMinor(), M, Uint32ToConstMD(), llvm::Optional< T >::value_or(), and ValVerKey.
loadDXILValidatorVersion()
static VersionTuple loadDXILValidatorVersion (MDNode * ValVerMD) static
Definition at line 52 of file DXILTranslateMetadata.cpp.
References ConstMDToUint32(), DXILVersionNumFields, llvm::MDNode::getNumOperands(), and llvm::MDNode::getOperand().
Uint32ToConstMD()
static ConstantAsMetadata* Uint32ToConstMD (unsigned v, LLVMContext & Ctx) static
Definition at line 26 of file DXILTranslateMetadata.cpp.
References llvm::IntegerType::get(), llvm::ConstantAsMetadata::get(), and llvm::Constant::getIntegerValue().
Referenced by emitDXILValidatorVersion().
Variable Documentation
DXILVersionNumFields
constexpr unsigned DXILVersionNumFields = 2 constexpr
Definition at line 32 of file DXILTranslateMetadata.cpp.
Referenced by emitDXILValidatorVersion(), and loadDXILValidatorVersion().
ValVerKey
constexpr StringLiteral ValVerKey = "dx.valver" constexpr
Definition at line 31 of file DXILTranslateMetadata.cpp.
Referenced by cleanModuleFlags(), and emitDXILValidatorVersion().