LLVM: include/llvm/Support/CMakeLists.txt File Reference
include/llvm/Support/CMakeLists.txt File Reference
Functions
find_first_existing_vc_file ("${LLVM_MAIN_SRC_DIR}" llvm_vc) set(version_inc "$
VCSRevision h set (generate_vcs_version_script "${LLVM_CMAKE_DIR}/GenerateVersionFromVCS.cmake") if(LLVM_APPEND_VC_REV) set(llvm_source_dir $
if (llvm_vc STREQUAL "") set(fake_version_inc "$
__FakeVCSRevision h endif () endif() set(generated_files "$
if (fake_version_inc) list(APPEND generated_files "$
Function Documentation
endif()
llvm DebugInfo PDB DIA endif ()
Definition at line 16 of file CMakeLists.txt.
Referenced by llvm::FilePermissionsApplier::apply(), llvm::EliminateDuplicatePHINodes(), and llvm::symbolize::LocalDIFetcher::fetchBuildID().
find_first_existing_vc_file()
find_first_existing_vc_file ("${LLVM_MAIN_SRC_DIR}" llvm_vc)
Definition at line 1 of file CMakeLists.txt.
if() [1/2]
if (fake_version_inc)
Definition at line 20 of file CMakeLists.txt.
if() [2/2]
if (llvm_vc STREQUAL "")
Definition at line 14 of file CMakeLists.txt.
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), llvm::orc::MapperJITLinkMemoryManager::allocate(), allocset(), llvm::SwitchCG::SwitchLowering::buildBitTests(), canLowerToLDG(), canVectorizeLoads(), llvm::GenericScheduler::checkAcyclicLatency(), llvm::IRSimilarity::IRSimilarityCandidate::compareNonCommutativeOperandMapping(), llvm::DebuginfodServer::DebuginfodServer(), llvm::DWARFLocationTable::dumpLocationList(), llvm::AsmPrinter::emitFunctionBody(), llvm::MCDwarfLineAddr::Encode(), llvm::SystemZPostRASchedStrategy::enterMBB(), llvm::gsym::GsymCreator::finalize(), llvm::InstCombinerImpl::foldIntegerTypedPHI(), llvm::gatherUnrollingPreferences(), llvm::DWARFFormValue::getAsSectionedAddress(), llvm::Clause::getFormattedParserClassName(), llvm::PPCTTIImpl::getMemoryOpCost(), llvm::objcopy::coff::handleArgs(), llvm::GCNSchedStage::initGCNRegion(), llvm::InformationCache::initializeModuleSlice(), isDereferenceableAndAlignedPointer(), llvm::isSafeToMoveBefore(), llvm::isSafeToUnrollAndJam(), lowerV4I32Shuffle(), llvm::AMDGPUSubtarget::makeLIDRangeMetadata(), llvm::MipsLegalizerInfo::MipsLegalizerInfo(), llvm::MLInlineAdvisor::onSuccessfulInlining(), llvm::AArch64FrameLowering::orderFrameObjects(), llvm::performOptimizedStructLayout(), llvm::CallGraph::print(), llvm::json::Path::Root::printErrorContext(), llvm::printRegClassOrBank(), registerPartialPipelineCallback(), llvm::slpvectorizer::BoUpSLP::reorderBottomToTop(), llvm::slpvectorizer::BoUpSLP::reorderTopToBottom(), llvm::SystemZPostRASchedStrategy::schedNode(), selectCallee(), llvm::LoopVectorizationCostModel::selectVectorizationFactor(), llvm::GenericSchedulerBase::setPolicy(), simplifyAMDGCNImageIntrinsic(), sortGlobalExprs(), translateImmediate(), translateRMMemory(), llvm::mca::RegisterFile::tryEliminateMoveOrSwap(), updateAndRemoveSymbols(), llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit(), llvm::DWARFLocationTable::visitAbsoluteLocationList(), and llvm::coverage::CoverageMappingWriter::write().
set()
VCSRevision h set (generate_vcs_version_script "${LLVM_CMAKE_DIR}/GenerateVersionFromVCS.cmake")
Definition at line 6 of file CMakeLists.txt.