LLVM: lib/Target/M68k/MCTargetDesc/M68kELFObjectWriter.cpp File Reference
M68kELFObjectWriter.cpp File Reference
#include "MCTargetDesc/M68kFixupKinds.h"
#include "MCTargetDesc/M68kMCTargetDesc.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCELFObjectWriter.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/ErrorHandling.h"
Enumerations
enum M68kRelType { RT_32, RT_16, RT_8 }
Functions
static M68kRelType getType (unsigned Kind, MCSymbolRefExpr::VariantKind &Modifier, bool &IsPCRel)
Detailed Description
This file contains definitions for M68k ELF Writers
Definition in file M68kELFObjectWriter.cpp.
Enumeration Type Documentation
M68kRelType
enum M68kRelType
Enumerator
RT_32
RT_16
RT_8
Definition at line 45 of file M68kELFObjectWriter.cpp.
Function Documentation
getType()
static M68kRelType getType (unsigned Kind, MCSymbolRefExpr::VariantKind & Modifier, bool & IsPCRel) static
Definition at line 48 of file M68kELFObjectWriter.cpp.
References llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_PCRel_1, llvm::FK_PCRel_2, llvm::FK_PCRel_4, llvm_unreachable, RT_16, RT_32, and RT_8.
Referenced by allSameType(), llvm::MachineIRBuilder::buildBlockAddress(), llvm::MachineIRBuilder::buildBoolExt(), llvm::MachineIRBuilder::buildBrIndirect(), llvm::MachineIRBuilder::buildBrJT(), llvm::ShuffleVectorInst::changesLength(), coerceArguments(), llvm::computeMinimumValueSizes(), llvm::slpvectorizer::BoUpSLP::computeMinimumValueSizes(), llvm::Constant::containsConstantExpression(), CreateGCStatepointCallCommon(), CreateGCStatepointInvokeCommon(), llvm::OpenMPIRBuilder::createOrderedDepend(), llvm::VPWidenPointerInductionRecipe::execute(), llvm::VPReplicateRecipe::execute(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), llvm::Constant::getAggregateElement(), llvm::AAPotentialConstantValues::getAssumedConstant(), llvm::Intrinsic::getDeclaration(), llvm::CastInst::getDestTy(), getFPSequenceIfElementsMatch(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicInstrCost(), llvm::ARMTTIImpl::getMemoryOpCost(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::ScalarEvolution::getMulExpr(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), llvm::ScalarEvolution::getSequentialMinMaxExpr(), llvm::MemTransferBase< AnyMemIntrinsic >::getSourceAddressSpace(), llvm::ConstantExpr::getWithOperands(), llvm::Constant::hasExactInverseFP(), llvm::ShuffleVectorInst::increasesLength(), llvm::IntrinsicCostAttributes::IntrinsicCostAttributes(), llvm::object::XCOFFObjectFile::is64Bit(), llvm::Constant::isAllOnesValue(), llvm::LandingPadInst::isCatch(), llvm::object::Elf_Sym_Impl< ELFT >::isCommon(), llvm::HexagonMCInstrInfo::isCompound(), llvm::Constant::isElementWiseEqual(), llvm::ShuffleVectorInst::isExtractSubvectorMask(), llvm::LandingPadInst::isFilter(), llvm::Constant::isFiniteNonZeroFP(), llvm::HexagonMCInstrInfo::isHVX(), llvm::ShuffleVectorInst::isIdentity(), llvm::ShuffleVectorInst::isInsertSubvectorMask(), llvm::Constant::isMinSignedValue(), llvm::Constant::isNaN(), llvm::Constant::isNegativeZeroValue(), llvm::Constant::isNormalFP(), llvm::Constant::isNotMinSignedValue(), llvm::Constant::isNotOneValue(), llvm::Constant::isOneValue(), isPointerValueDeadOnEntryToFunction(), llvm::Constant::isZeroValue(), LLVMBinaryGetType(), LLVMTypeOf(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::fuzzerop::matchFirstType(), matchScalarInAggregate(), llvm::fuzzerop::matchScalarOfFirstType(), llvm::MachineIRBuilder::materializePtrAdd(), performBlockTailMerging(), llvm::object::Elf_Sym_Impl< ELFT >::setBinding(), llvm::PHINode::setIncomingValue(), llvm::MemTransferBase< AnyMemIntrinsic >::setSource(), llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, false >, false >::setSymbol(), llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, true >, false >::setSymbol(), llvm::MemSetBase< AnyMemIntrinsic >::setValue(), simplifyFPOp(), simplifyGEPInst(), splitGlobal(), validExtractValueIndex(), validInsertValueIndex(), validShuffleVectorIndex(), llvm::InstCombinerImpl::visitLandingPadInst(), and llvm::InstCombinerImpl::visitLShr().