LLVM: lib/Analysis/MemoryBuiltins.cpp File Reference
MemoryBuiltins.cpp File Reference
#include "llvm/Analysis/MemoryBuiltins.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/TargetFolder.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/Utils/Local.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cstdint>
#include <iterator>
#include <numeric>
#include <type_traits>
#include <utility>
Classes
struct AllocFnsTy
struct FreeFnsTy
Macros
#define DEBUG_TYPE "memory-builtins"
Enumerations
enum AllocType : uint8_t {
OpNewLike = 1<<0, MallocLike = 1<<1, AlignedAllocLike = 1<<2, CallocLike = 1<<3,
ReallocLike = 1<<4, StrDupLike = 1<<5, MallocOrOpNewLike = MallocLike | OpNewLike, MallocOrCallocLike = MallocLike | OpNewLike | CallocLike | AlignedAllocLike,
AllocLike = MallocOrCallocLike | StrDupLike, AnyAlloc = AllocLike | ReallocLike
}
enum MallocFamily {
MallocFamily::Malloc, MallocFamily::CPPNew, MallocFamily::CPPNewAligned, MallocFamily::CPPNewArray,
MallocFamily::CPPNewArrayAligned, MallocFamily::MSVCNew, MallocFamily::MSVCArrayNew, MallocFamily::VecMalloc,
MallocFamily::KmpcAllocShared
}
Functions
StringRef mangledNameForMallocFamily (const MallocFamily &Family)
static const Function * getCalledFunction (const Value *V, bool &IsNoBuiltin)
static Optional< AllocFnsTy > getAllocationDataForFunction (const Function *Callee, AllocType AllocTy, const TargetLibraryInfo *TLI)
Returns the allocation data for the given value if it's a call to a known allocation function.
static Optional< AllocFnsTy > getAllocationData (const Value *V, AllocType AllocTy, const TargetLibraryInfo *TLI)
static Optional< AllocFnsTy > getAllocationData (const Value *V, AllocType AllocTy, function_ref< const TargetLibraryInfo &(Function &)> GetTLI)
static Optional< AllocFnsTy > getAllocationSize (const Value *V, const TargetLibraryInfo *TLI)
static AllocFnKind getAllocFnKind (const Value *V)
static AllocFnKind getAllocFnKind (const Function *F)
static bool checkFnAllocKind (const Value *V, AllocFnKind Wanted)
static bool checkFnAllocKind (const Function *F, AllocFnKind Wanted)
static bool isMallocLikeFn (const Value *V, const TargetLibraryInfo *TLI)
Tests if a value is a call or invoke to a library function that allocates uninitialized memory (such as malloc).
static bool isAlignedAllocLikeFn (const Value *V, const TargetLibraryInfo *TLI)
Tests if a value is a call or invoke to a library function that allocates uninitialized memory with alignment (such as aligned_alloc).
static bool isCallocLikeFn (const Value *V, const TargetLibraryInfo *TLI)
Tests if a value is a call or invoke to a library function that allocates zero-filled memory (such as calloc).
static bool CheckedZextOrTrunc (APInt &I, unsigned IntTyBits)
When we're compiling N-bit code, and the user uses parameters that are greater than N bits (e.g.
Optional< FreeFnsTy > getFreeFunctionDataForFunction (const Function *Callee, const LibFunc TLIFn)
static APInt getSizeWithOverflow (const SizeOffsetType &Data)
STATISTIC (ObjectVisitorArgument, "Number of arguments with unsolved size and offset")
STATISTIC (ObjectVisitorLoad, "Number of load instructions with unsolved size and offset")
Variables
static const std::pair< LibFunc, AllocFnsTy > AllocationFnData []
static const std::pair< LibFunc, FreeFnsTy > FreeFnData []
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "memory-builtins"
Definition at line 52 of file MemoryBuiltins.cpp.
Enumeration Type Documentation
AllocType
enum AllocType : uint8_t
Enumerator
OpNewLike
MallocLike
AlignedAllocLike
CallocLike
ReallocLike
StrDupLike
MallocOrOpNewLike
MallocOrCallocLike
AllocLike
AnyAlloc
Definition at line 54 of file MemoryBuiltins.cpp.
MallocFamily
enum MallocFamily strong
Enumerator
Malloc
CPPNew
CPPNewAligned
CPPNewArray
CPPNewArrayAligned
MSVCNew
MSVCArrayNew
VecMalloc
KmpcAllocShared
Definition at line 67 of file MemoryBuiltins.cpp.
Function Documentation
CheckedZextOrTrunc()
static bool CheckedZextOrTrunc (APInt & I, unsigned IntTyBits) static
When we're compiling N-bit code, and the user uses parameters that are greater than N bits (e.g.
uint64_t on a 32-bit build), we can run into trouble with APInt size issues. This function handles resizing + overflow checks for us. Check and zext or trunc I depending on IntTyBits and I's value.
Definition at line 380 of file MemoryBuiltins.cpp.
References I.
Referenced by llvm::getAllocSize().
checkFnAllocKind() [1/2]
static bool checkFnAllocKind (const Function * F, AllocFnKind Wanted) static
Definition at line 288 of file MemoryBuiltins.cpp.
References F, getAllocFnKind(), and llvm::Unknown.
checkFnAllocKind() [2/2]
static bool checkFnAllocKind (const Value * V, AllocFnKind Wanted) static
Definition at line 284 of file MemoryBuiltins.cpp.
References getAllocFnKind(), and llvm::Unknown.
Referenced by llvm::getAllocationFamily(), llvm::getFreedOperand(), llvm::getReallocatedOperand(), llvm::isAllocationFn(), llvm::isAllocLikeFn(), llvm::isLibFreeFunction(), and llvm::isReallocLikeFn().
getAllocationData() [1/2]
static Optional<AllocFnsTy> getAllocationData (const Value * V, AllocType AllocTy, const TargetLibraryInfo * TLI) static
Definition at line 215 of file MemoryBuiltins.cpp.
References Callee, getAllocationDataForFunction(), getCalledFunction(), and llvm::None.
Referenced by llvm::getAllocAlignment(), llvm::getReallocatedOperand(), isAlignedAllocLikeFn(), llvm::isAllocationFn(), llvm::isAllocLikeFn(), isCallocLikeFn(), isMallocLikeFn(), and llvm::isMallocOrCallocLikeFn().
getAllocationData() [2/2]
static Optional<AllocFnsTy> getAllocationData (const Value * V, AllocType AllocTy, function_ref< const TargetLibraryInfo &(Function &)> GetTLI) static
Definition at line 225 of file MemoryBuiltins.cpp.
References Callee, getAllocationDataForFunction(), getCalledFunction(), and llvm::None.
getAllocationDataForFunction()
static Optional<AllocFnsTy> getAllocationDataForFunction (const Function * Callee, AllocType AllocTy, const TargetLibraryInfo * TLI) static
Returns the allocation data for the given value if it's a call to a known allocation function.
Definition at line 174 of file MemoryBuiltins.cpp.
References AllocationFnData, AllocFnsTy::AllocTy, Callee, llvm::sys::path::end(), llvm::find_if(), AllocFnsTy::FstParam, llvm::Type::getContext(), llvm::FunctionCallee::getFunctionType(), llvm::Type::getInt8PtrTy(), llvm::TargetLibraryInfo::getLibFunc(), llvm::FunctionType::getNumParams(), llvm::FunctionType::getParamType(), llvm::FunctionType::getReturnType(), llvm::TargetLibraryInfo::has(), llvm::Type::isIntegerTy(), llvm::None, AllocFnsTy::NumParams, P, and AllocFnsTy::SndParam.
Referenced by getAllocationData(), llvm::getAllocationFamily(), getAllocationSize(), and llvm::isReallocLikeFn().
getAllocationSize()
static Optional<AllocFnsTy> getAllocationSize (const Value * V, const TargetLibraryInfo * TLI) static
Definition at line 235 of file MemoryBuiltins.cpp.
References AnyAlloc, llvm::AMDGPU::HSAMD::Kernel::Key::Args, Callee, llvm::Data, getAllocationDataForFunction(), llvm::Attribute::getAllocSizeArgs(), getCalledFunction(), MallocLike, and llvm::None.
Referenced by llvm::getAllocSize(), and llvm::ObjectSizeOffsetEvaluator::visitCallBase().
getAllocFnKind() [1/2]
static AllocFnKind getAllocFnKind (const Function * F) static
Definition at line 277 of file MemoryBuiltins.cpp.
References F, llvm::Attribute::getValueAsInt(), llvm::Attribute::isValid(), and llvm::Unknown.
getAllocFnKind() [2/2]
static AllocFnKind getAllocFnKind (const Value * V) static
Definition at line 268 of file MemoryBuiltins.cpp.
References llvm::Attribute::getValueAsInt(), llvm::Attribute::isValid(), and llvm::Unknown.
Referenced by checkFnAllocKind(), and llvm::getInitialValueOfAllocation().
getCalledFunction()
static const Function* getCalledFunction (const Value * V, bool & IsNoBuiltin) static
Definition at line 154 of file MemoryBuiltins.cpp.
References Callee.
Referenced by llvm::orc::SpeculateQuery::findCalles(), FindPreallocatedCall(), getAllocationData(), llvm::getAllocationFamily(), getAllocationSize(), llvm::getFreedOperand(), llvm::WebAssemblyTTIImpl::getUnrollingPreferences(), llvm::SystemZTTIImpl::getUnrollingPreferences(), llvm::RISCVTTIImpl::getUnrollingPreferences(), llvm::AArch64TTIImpl::getUnrollingPreferences(), llvm::ARMTTIImpl::getUnrollingPreferences(), and llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getUnrollingPreferences().
getFreeFunctionDataForFunction()
Optional<FreeFnsTy> getFreeFunctionDataForFunction (const Function * Callee, const LibFunc TLIFn)
Definition at line 518 of file MemoryBuiltins.cpp.
References llvm::sys::path::end(), llvm::find_if(), FreeFnData, llvm::None, and P.
Referenced by llvm::getAllocationFamily(), and llvm::isLibFreeFunction().
getSizeWithOverflow()
static APInt getSizeWithOverflow (const SizeOffsetType & Data) static
Definition at line 598 of file MemoryBuiltins.cpp.
References llvm::Data.
Referenced by llvm::getObjectSize().
isAlignedAllocLikeFn()
static bool isAlignedAllocLikeFn (const Value * V, const TargetLibraryInfo * TLI) static
Tests if a value is a call or invoke to a library function that allocates uninitialized memory with alignment (such as aligned_alloc).
Definition at line 314 of file MemoryBuiltins.cpp.
References AlignedAllocLike, and getAllocationData().
Referenced by llvm::getInitialValueOfAllocation().
isCallocLikeFn()
static bool isCallocLikeFn (const Value * V, const TargetLibraryInfo * TLI) static
Tests if a value is a call or invoke to a library function that allocates zero-filled memory (such as calloc).
Definition at line 320 of file MemoryBuiltins.cpp.
References CallocLike, and getAllocationData().
Referenced by llvm::getInitialValueOfAllocation().
isMallocLikeFn()
static bool isMallocLikeFn (const Value * V, const TargetLibraryInfo * TLI) static
Tests if a value is a call or invoke to a library function that allocates uninitialized memory (such as malloc).
Definition at line 308 of file MemoryBuiltins.cpp.
References getAllocationData(), and MallocOrOpNewLike.
Referenced by llvm::getInitialValueOfAllocation().
mangledNameForMallocFamily()
StringRef mangledNameForMallocFamily (const MallocFamily & Family)
Definition at line 79 of file MemoryBuiltins.cpp.
References CPPNew, CPPNewAligned, CPPNewArray, CPPNewArrayAligned, KmpcAllocShared, llvm_unreachable, Malloc, MSVCArrayNew, MSVCNew, and VecMalloc.
Referenced by llvm::getAllocationFamily().
STATISTIC() [1/2]
STATISTIC (ObjectVisitorArgument , "Number of arguments with unsolved size and offset")
STATISTIC() [2/2]
STATISTIC (ObjectVisitorLoad , "Number of load instructions with unsolved size and offset")
Variable Documentation
AllocationFnData
const std::pair<LibFunc, AllocFnsTy> AllocationFnData[] static
Definition at line 117 of file MemoryBuiltins.cpp.
Referenced by getAllocationDataForFunction().
FreeFnData
const std::pair<LibFunc, FreeFnsTy> FreeFnData[] static
Definition at line 484 of file MemoryBuiltins.cpp.
Referenced by getFreeFunctionDataForFunction().