LLVM: llvm::orc::tpctypes Namespace Reference
llvm::orc::tpctypes Namespace Reference
Classes
struct BufferWrite
Describes a write to a buffer.
struct FinalizeRequest
struct SegFinalizeRequest
struct SharedMemoryFinalizeRequest
struct SharedMemorySegFinalizeRequest
struct UIntWrite
Typedefs
using UInt8Write = UIntWrite< uint8_t >
Describes a write to a uint8_t.
using UInt16Write = UIntWrite< uint16_t >
Describes a write to a uint16_t.
using UInt32Write = UIntWrite< uint32_t >
Describes a write to a uint32_t.
using UInt64Write = UIntWrite< uint64_t >
Describes a write to a uint64_t.
using DylibHandle = JITTargetAddress
A handle used to represent a loaded dylib in the target process.
using LookupResult = std::vector< JITTargetAddress >
Enumerations
enum WireProtectionFlags : uint8_t { WPF_None = 0, WPF_Read = 1U << 0, WPF_Write = 1U << 1, WPF_Exec = 1U << 2 }
Functions
WireProtectionFlags toWireProtectionFlags (sys::Memory::ProtectionFlags PF)
Convert from sys::Memory::ProtectionFlags.
sys::Memory::ProtectionFlags fromWireProtectionFlags (WireProtectionFlags WPF)
std::string getWireProtectionFlagsStr (WireProtectionFlags WPF)
Typedef Documentation
DylibHandle
using llvm::orc::tpctypes::DylibHandle = typedef JITTargetAddress
A handle used to represent a loaded dylib in the target process.
Definition at line 128 of file TargetProcessControlTypes.h.
LookupResult
using llvm::orc::tpctypes::LookupResult = typedef std::vector<JITTargetAddress>
Definition at line 130 of file TargetProcessControlTypes.h.
UInt16Write
using llvm::orc::tpctypes::UInt16Write = typedef UIntWrite<uint16_t>
Describes a write to a uint16_t.
Definition at line 108 of file TargetProcessControlTypes.h.
UInt32Write
using llvm::orc::tpctypes::UInt32Write = typedef UIntWrite<uint32_t>
Describes a write to a uint32_t.
Definition at line 111 of file TargetProcessControlTypes.h.
UInt64Write
using llvm::orc::tpctypes::UInt64Write = typedef UIntWrite<uint64_t>
Describes a write to a uint64_t.
Definition at line 114 of file TargetProcessControlTypes.h.
UInt8Write
using llvm::orc::tpctypes::UInt8Write = typedef UIntWrite<uint8_t>
Describes a write to a uint8_t.
Definition at line 105 of file TargetProcessControlTypes.h.
Enumeration Type Documentation
WireProtectionFlags
enum llvm::orc::tpctypes::WireProtectionFlags : uint8_t
Enumerator
WPF_None
WPF_Read
WPF_Write
WPF_Exec
Definition at line 32 of file TargetProcessControlTypes.h.
Function Documentation
fromWireProtectionFlags()
sys::Memory::ProtectionFlags llvm::orc::tpctypes::fromWireProtectionFlags (WireProtectionFlags WPF) inline
Definition at line 54 of file TargetProcessControlTypes.h.
References llvm::sys::Memory::MF_EXEC, llvm::sys::Memory::MF_READ, llvm::sys::Memory::MF_WRITE, WPF_Exec, WPF_Read, and WPF_Write.
Referenced by llvm::orc::rt_bootstrap::ExecutorSharedMemoryMapperService::initialize().
getWireProtectionFlagsStr()
std::string llvm::orc::tpctypes::getWireProtectionFlagsStr (WireProtectionFlags WPF) inline
Definition at line 65 of file TargetProcessControlTypes.h.
References WPF_Exec, WPF_Read, and WPF_Write.
toWireProtectionFlags()
WireProtectionFlags llvm::orc::tpctypes::toWireProtectionFlags (sys::Memory::ProtectionFlags PF) inline
Convert from sys::Memory::ProtectionFlags.
Definition at line 42 of file TargetProcessControlTypes.h.
References llvm::sys::Memory::MF_EXEC, llvm::sys::Memory::MF_READ, llvm::sys::Memory::MF_WRITE, WPF_Exec, WPF_None, WPF_Read, and WPF_Write.
Referenced by llvm::orc::EPCGenericJITLinkMemoryManager::InFlightAlloc::finalize(), llvm::orc::EPCGenericRTDyldMemoryManager::finalizeMemory(), and llvm::orc::SharedMemoryMapper::initialize().