LLVM: llvm::jitlink::aarch64 Namespace Reference
llvm::jitlink::aarch64 Namespace Reference
Classes
class GOTTableManager
Global Offset Table Builder.
class PLTTableManager
Procedure Linkage Table Builder.
Enumerations
enum EdgeKind_aarch64 : Edge::Kind {
Branch26 = Edge::FirstRelocation, Pointer32, Pointer64, Pointer64Anon,
Page21, PageOffset12, MoveWide16, GOTPage21,
GOTPageOffset12, TLVPage21, TLVPageOffset12, TLSDescPage21,
TLSDescPageOffset12, Delta32ToGOT, PairedAddend, LDRLiteral19,
Delta32, Delta64, NegDelta32, NegDelta64
}
Functions
const char * getEdgeKindName (Edge::Kind K)
Returns a string name for the given aarch64 edge.
bool isLoadStoreImm12 (uint32_t Instr)
unsigned getPageOffset12Shift (uint32_t Instr)
bool isMoveWideImm16 (uint32_t Instr)
unsigned getMoveWide16Shift (uint32_t Instr)
Error applyFixup (LinkGraph &G, Block &B, const Edge &E)
Apply fixup expression for edge to block content.
Variables
const uint8_t NullGOTEntryContent [8]
AArch64 null pointer content.
const uint8_t StubContent [8]
AArch64 PLT stub content.
Enumeration Type Documentation
EdgeKind_aarch64
enum llvm::jitlink::aarch64::EdgeKind_aarch64 : Edge::Kind
Enumerator
Branch26
Pointer32
Pointer64
Pointer64Anon
Page21
PageOffset12
MoveWide16
GOTPage21
GOTPageOffset12
TLVPage21
TLVPageOffset12
TLSDescPage21
TLSDescPageOffset12
Delta32ToGOT
PairedAddend
LDRLiteral19
Delta32
Delta64
NegDelta32
NegDelta64
Definition at line 24 of file aarch64.h.
Function Documentation
applyFixup()
Error llvm::jitlink::aarch64::applyFixup (LinkGraph & G, Block & B, const Edge & E) inline
Apply fixup expression for edge to block content.
Definition at line 98 of file aarch64.h.
References assert(), B, Branch26, Delta32, Delta32ToGOT, Delta64, E, G, getEdgeKindName(), getMoveWide16Shift(), getPageOffset12Shift(), llvm::orc::ExecutorAddr::getValue(), GOTPage21, GOTPageOffset12, llvm::RISCVMatInt::Imm, llvm::X86II::ImmShift, isMoveWideImm16(), LDRLiteral19, llvm::jitlink::makeTargetOutOfRangeError(), llvm::max(), llvm::min(), MoveWide16, NegDelta32, NegDelta64, Page21, PageOffset12, Pointer32, Pointer64, Pointer64Anon, llvm::Error::success(), support(), TLSDescPage21, TLSDescPageOffset12, TLVPage21, TLVPageOffset12, and x3.
getEdgeKindName()
const char * llvm::jitlink::aarch64::getEdgeKindName (Edge::Kind K)
Returns a string name for the given aarch64 edge.
For debugging purposes only
Definition at line 29 of file aarch64.cpp.
References Branch26, Delta32, Delta32ToGOT, Delta64, llvm::jitlink::getGenericEdgeKindName(), GOTPage21, GOTPageOffset12, LDRLiteral19, MoveWide16, NegDelta32, NegDelta64, Page21, PageOffset12, PairedAddend, Pointer64, Pointer64Anon, TLSDescPage21, TLSDescPageOffset12, TLVPage21, and TLVPageOffset12.
Referenced by applyFixup().
getMoveWide16Shift()
unsigned llvm::jitlink::aarch64::getMoveWide16Shift (uint32_t Instr) inline
Definition at line 88 of file aarch64.h.
References isMoveWideImm16().
Referenced by applyFixup().
getPageOffset12Shift()
unsigned llvm::jitlink::aarch64::getPageOffset12Shift (uint32_t Instr) inline
Definition at line 63 of file aarch64.h.
References isLoadStoreImm12().
Referenced by applyFixup().
isLoadStoreImm12()
bool llvm::jitlink::aarch64::isLoadStoreImm12 (uint32_t Instr) inline
Definition at line 52 of file aarch64.h.
Referenced by getPageOffset12Shift().
isMoveWideImm16()
bool llvm::jitlink::aarch64::isMoveWideImm16 (uint32_t Instr) inline
Definition at line 79 of file aarch64.h.
Referenced by applyFixup(), and getMoveWide16Shift().
Variable Documentation
NullGOTEntryContent
const uint8_t llvm::jitlink::aarch64::NullGOTEntryContent
Initial value:
= {0x00, 0x00, 0x00, 0x00,
                                        0x00, 0x00, 0x00, 0x00}
AArch64 null pointer content.
Definition at line 21 of file aarch64.cpp.
StubContent
const uint8_t llvm::jitlink::aarch64::StubContent
Initial value:
= {
    0x10, 0x00, 0x00, 0x58,
    0x00, 0x02, 0x1f, 0xd6
}
AArch64 PLT stub content.
Definition at line 24 of file aarch64.cpp.
Referenced by llvm::jitlink::aarch64::PLTTableManager::getStubBlockContent().