LLVM: lib/Analysis/ObjCARCInstKind.cpp File Reference
ObjCARCInstKind.cpp File Reference
#include "llvm/Analysis/ObjCARCInstKind.h"
#include "llvm/Analysis/ObjCARCAnalysisUtils.h"
#include "llvm/IR/Intrinsics.h"
Functions
static bool isInertIntrinsic (unsigned ID)
static bool isUseOnlyIntrinsic (unsigned ID)
Detailed Description
This file defines several utility functions used by various ARC optimizations which are IMHO too big to be in a header file.
WARNING: This file knows about certain library functions. It recognizes them by name, and hardwires knowledge of their semantics.
WARNING: This file knows about how certain Objective-C library functions are used. Naive LLVM IR transformations which would otherwise be behavior-preserving may break these assumptions.
Definition in file ObjCARCInstKind.cpp.
Function Documentation
isInertIntrinsic()
static bool isInertIntrinsic (unsigned ID) static
Definition at line 158 of file ObjCARCInstKind.cpp.
References prefetch.
Referenced by llvm::objcarc::GetARCInstKind().
isUseOnlyIntrinsic()
static bool isUseOnlyIntrinsic (unsigned ID) static
Definition at line 197 of file ObjCARCInstKind.cpp.
References memcpy().
Referenced by llvm::objcarc::GetARCInstKind().