LLVM: lib/Target/RISCV/RISCVSExtWRemoval.cpp File Reference
RISCVSExtWRemoval.cpp File Reference
#include "RISCV.h"
#include "RISCVSubtarget.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
Macros
#define DEBUG_TYPE "riscv-sextw-removal"
Functions
STATISTIC (NumRemovedSExtW, "Number of removed sign-extensions")
STATISTIC (NumTransformedToWInstrs, "Number of instructions transformed to W-ops")
INITIALIZE_PASS (RISCVSExtWRemoval, DEBUG_TYPE, "RISCV sext.w Removal", false, false) FunctionPass *llvm
static void addUses (const MachineInstr &MI, SmallVectorImpl< const MachineInstr * > &Worklist, MachineRegisterInfo &MRI)
static bool isAllUsesReadW (const MachineInstr &OrigMI, MachineRegisterInfo &MRI)
static bool isSignExtendingOpW (MachineInstr &MI, MachineRegisterInfo &MRI, SmallPtrSetImpl< MachineInstr * > &FixableDef)
static bool isSignExtendedW (MachineInstr &OrigMI, MachineRegisterInfo &MRI, SmallPtrSetImpl< MachineInstr * > &FixableDef)
static unsigned getWOp (unsigned Opcode)
Variables
static cl::opt< bool > DisableSExtWRemoval ("riscv-disable-sextw-removal", cl::desc("Disable removal of sext.w"), cl::init(false), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "riscv-sextw-removal"
Definition at line 21 of file RISCVSExtWRemoval.cpp.
Function Documentation
addUses()
static void addUses (const MachineInstr & MI, SmallVectorImpl< const MachineInstr * > & Worklist, MachineRegisterInfo & MRI) static
Definition at line 61 of file RISCVSExtWRemoval.cpp.
References MI, MRI, and llvm::MachineRegisterInfo::reg_operands().
Referenced by isAllUsesReadW().
getWOp()
static unsigned getWOp (unsigned Opcode) static
Definition at line 407 of file RISCVSExtWRemoval.cpp.
References llvm::ISD::ADD, llvm::ARM_MB::LD, llvm_unreachable, llvm::ISD::MUL, and llvm::ISD::SUB.
INITIALIZE_PASS()
INITIALIZE_PASS (RISCVSExtWRemoval , DEBUG_TYPE , "RISCV sext.w Removal" , false , false)
Definition at line 53 of file RISCVSExtWRemoval.cpp.
isAllUsesReadW()
static bool isAllUsesReadW (const MachineInstr & OrigMI, MachineRegisterInfo & MRI) static
Definition at line 75 of file RISCVSExtWRemoval.cpp.
References llvm::ISD::ADD, addUses(), llvm::ISD::AND, llvm::RISCVISD::CLZW, llvm::RISCVISD::CTZW, llvm::RISCVISD::DIVUW, llvm::RISCVISD::DIVW, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::ARM_MB::LD, MI, MRI, llvm::ISD::MUL, llvm::ISD::OR, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::RISCVISD::REMUW, llvm::RISCVISD::ROLW, llvm::RISCVISD::RORW, llvm::RISCVISD::SLLW, llvm::RISCVISD::SRAW, llvm::RISCVISD::SRLW, llvm::ISD::SUB, and llvm::ISD::XOR.
Referenced by isSignExtendingOpW().
isSignExtendedW()
static bool isSignExtendedW (MachineInstr & OrigMI, MachineRegisterInfo & MRI, SmallPtrSetImpl< MachineInstr * > & FixableDef) static
Definition at line 293 of file RISCVSExtWRemoval.cpp.
References llvm::ISD::AND, D, E, llvm::MachineRegisterInfo::getVRegDef(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), isSignExtendingOpW(), llvm::Register::isVirtual(), LLVM_FALLTHROUGH, MI, MRI, llvm::ISD::OR, llvm::SmallVectorImpl< T >::pop_back_val(), and llvm::ISD::XOR.
isSignExtendingOpW()
static bool isSignExtendingOpW (MachineInstr & MI, MachineRegisterInfo & MRI, SmallPtrSetImpl< MachineInstr * > & FixableDef) static
Definition at line 195 of file RISCVSExtWRemoval.cpp.
References llvm::ISD::ADD, CLZ, llvm::RISCVISD::CLZW, llvm::RISCVISD::CTZW, llvm::RISCVISD::DIVUW, llvm::RISCVISD::DIVW, llvm::SmallPtrSetImpl< PtrType >::insert(), isAllUsesReadW(), llvm::ARM_MB::LD, LLVM_FALLTHROUGH, MI, MRI, llvm::ISD::MUL, llvm::RISCVISD::REMUW, llvm::RISCVISD::ROLW, llvm::RISCVISD::RORW, llvm::RISCVISD::SLLW, llvm::RISCVISD::SRAW, llvm::RISCVISD::SRLW, and llvm::ISD::SUB.
Referenced by isSignExtendedW().
STATISTIC() [1/2]
STATISTIC (NumRemovedSExtW , "Number of removed sign-extensions")
STATISTIC() [2/2]
STATISTIC (NumTransformedToWInstrs , "Number of instructions transformed to W-ops")
Variable Documentation
DisableSExtWRemoval
cl::opt<bool> DisableSExtWRemoval("riscv-disable-sextw-removal", cl::desc("Disable removal of sext.w"), cl::init(false), cl::Hidden) static