LLVM: lib/Target/SPIRV/SPIRVPreLegalizer.cpp File Reference
SPIRVPreLegalizer.cpp File Reference
#include "SPIRV.h"
#include "SPIRVGlobalRegistry.h"
#include "SPIRVSubtarget.h"
#include "SPIRVUtils.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/IntrinsicsSPIRV.h"
#include "llvm/Target/TargetIntrinsicInfo.h"
Macros
#define DEBUG_TYPE "spirv-prelegalizer"
Functions
static void addConstantsToTrack (MachineFunction &MF, SPIRVGlobalRegistry *GR)
static void foldConstantsIntoIntrinsics (MachineFunction &MF)
static void insertBitcasts (MachineFunction &MF, SPIRVGlobalRegistry *GR, MachineIRBuilder MIB)
static SPIRVType * propagateSPIRVType (MachineInstr *MI, SPIRVGlobalRegistry *GR, MachineRegisterInfo &MRI, MachineIRBuilder &MIB)
static Register insertAssignInstr (Register Reg, Type *Ty, SPIRVType *SpirvTy, SPIRVGlobalRegistry *GR, MachineIRBuilder &MIB, MachineRegisterInfo &MRI)
static void generateAssignInstrs (MachineFunction &MF, SPIRVGlobalRegistry *GR, MachineIRBuilder MIB)
static std::pair< Register, unsigned > createNewIdReg (Register ValReg, unsigned Opcode, MachineRegisterInfo &MRI, const SPIRVGlobalRegistry &GR)
static void processInstr (MachineInstr &MI, MachineIRBuilder &MIB, MachineRegisterInfo &MRI, SPIRVGlobalRegistry *GR)
bool isTypeFoldingSupported (unsigned Opcode)
static void processInstrsWithTypeFolding (MachineFunction &MF, SPIRVGlobalRegistry *GR, MachineIRBuilder MIB)
static void processSwitches (MachineFunction &MF, SPIRVGlobalRegistry *GR, MachineIRBuilder MIB)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "spirv-prelegalizer"
Definition at line 27 of file SPIRVPreLegalizer.cpp.
Function Documentation
addConstantsToTrack()
static void addConstantsToTrack (MachineFunction & MF, SPIRVGlobalRegistry * GR) static
Definition at line 42 of file SPIRVPreLegalizer.cpp.
References llvm::SPIRVGlobalRegistry::add(), assert(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), llvm::SPIRVGlobalRegistry::find(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), llvm::MachineFunction::getRegInfo(), llvm::MachineRegisterInfo::getVRegDef(), i, isSpvIntrinsic(), MBB, MI, MRI, and llvm::MachineRegisterInfo::replaceRegWith().
createNewIdReg()
static std::pair<Register, unsigned> createNewIdReg (Register ValReg, unsigned Opcode, MachineRegisterInfo & MRI, const SPIRVGlobalRegistry & GR) static
Definition at line 298 of file SPIRVPreLegalizer.cpp.
References assert(), llvm::MachineRegisterInfo::createGenericVirtualRegister(), llvm::LLT::fixed_vector(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::SPIRVGlobalRegistry::getSPIRVTypeForVReg(), llvm::MachineRegisterInfo::getType(), llvm::LLT::isPointer(), llvm::LLT::isVector(), MRI, llvm::LLT::pointer(), llvm::LLT::scalar(), and llvm::MachineRegisterInfo::setRegClass().
Referenced by processInstr().
foldConstantsIntoIntrinsics()
static void foldConstantsIntoIntrinsics (MachineFunction & MF) static
Definition at line 96 of file SPIRVPreLegalizer.cpp.
References assert(), llvm::MachineOperand::CreateImm(), llvm::MachineOperand::getCImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineRegisterInfo::getVRegDef(), llvm::ConstantInt::getZExtValue(), isSpvIntrinsic(), MBB, MI, MRI, and llvm::MachineRegisterInfo::use_empty().
generateAssignInstrs()
static void generateAssignInstrs (MachineFunction & MF, SPIRVGlobalRegistry * GR, MachineIRBuilder MIB) static
Definition at line 220 of file SPIRVPreLegalizer.cpp.
References assert(), llvm::MachineBasicBlock::begin(), llvm::tgtok::Def, llvm::MachineBasicBlock::empty(), llvm::MachineBasicBlock::end(), llvm::VectorType::get(), llvm::MachineOperand::getCImm(), llvm::MachineOperand::getFPImm(), getMDOperandAsType(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineFunction::getRegInfo(), llvm::ConstantInt::getType(), llvm::Value::getType(), llvm::MachineRegisterInfo::getVRegDef(), llvm::MachineRegisterInfo::hasOneUse(), insertAssignInstr(), isSpvIntrinsic(), llvm_unreachable, MBB, MI, MRI, llvm::post_order(), propagateSPIRVType(), llvm::MachineRegisterInfo::use_instr_begin(), and UseMI.
insertAssignInstr()
static Register insertAssignInstr (Register Reg, Type * Ty, SPIRVType * SpirvTy, SPIRVGlobalRegistry * GR, MachineIRBuilder & MIB, MachineRegisterInfo & MRI) static
Definition at line 194 of file SPIRVPreLegalizer.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addUse(), assert(), llvm::SPIRVGlobalRegistry::assignSPIRVTypeToVReg(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineRegisterInfo::createGenericVirtualRegister(), llvm::tgtok::Def, llvm::MachineIRBuilder::getMF(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVType(), llvm::MachineRegisterInfo::getRegClassOrNull(), llvm::SPIRVGlobalRegistry::getSPIRVTypeID(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), MRI, llvm::MachineIRBuilder::setInsertPt(), and llvm::MachineRegisterInfo::setRegClass().
Referenced by generateAssignInstrs().
insertBitcasts()
static void insertBitcasts (MachineFunction & MF, SPIRVGlobalRegistry * GR, MachineIRBuilder MIB) static
Definition at line 121 of file SPIRVPreLegalizer.cpp.
References assert(), llvm::MachineIRBuilder::buildBitcast(), isSpvIntrinsic(), MBB, MI, and llvm::MachineIRBuilder::setInsertPt().
isTypeFoldingSupported()
bool isTypeFoldingSupported (unsigned Opcode)
Definition at line 53 of file SPIRVLegalizerInfo.cpp.
References TypeFoldingSupportingOpcs.
Referenced by llvm::SPIRVLegalizerInfo::legalizeCustom(), and processInstrsWithTypeFolding().
processInstr()
static void processInstr (MachineInstr & MI, MachineIRBuilder & MIB, MachineRegisterInfo & MRI, SPIRVGlobalRegistry * GR) static
Definition at line 325 of file SPIRVPreLegalizer.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addUse(), assert(), llvm::MachineIRBuilder::buildInstr(), createNewIdReg(), llvm::MachineInstr::getOperand(), llvm::MachineRegisterInfo::hasOneUse(), MI, MRI, llvm::MachineIRBuilder::setInsertPt(), llvm::MachineOperand::setReg(), and llvm::MachineRegisterInfo::use_instr_begin().
Referenced by processInstrsWithTypeFolding().
processInstrsWithTypeFolding()
static void processInstrsWithTypeFolding (MachineFunction & MF, SPIRVGlobalRegistry * GR, MachineIRBuilder MIB) static
Definition at line 349 of file SPIRVPreLegalizer.cpp.
References llvm::MachineInstr::getOpcode(), llvm::MachineFunction::getRegInfo(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), isTypeFoldingSupported(), llvm::LLT::isVector(), MBB, MI, MRI, processInstr(), llvm::LLT::scalar(), llvm::MachineRegisterInfo::setRegClass(), and llvm::MachineRegisterInfo::setType().
processSwitches()
static void processSwitches (MachineFunction & MF, SPIRVGlobalRegistry * GR, MachineIRBuilder MIB) static
Definition at line 377 of file SPIRVPreLegalizer.cpp.
References assert(), llvm::SPIRVGlobalRegistry::assignSPIRVTypeToVReg(), llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::contains(), llvm::MachineOperand::CreateCImm(), llvm::MachineOperand::CreateMBB(), llvm::MachineBasicBlock::front(), llvm::IntegerType::get(), llvm::MachineOperand::getCImm(), getDefInstrMaybeConstant(), getIConstVal(), llvm::MachineOperand::getMBB(), llvm::MachineIRBuilder::getMF(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVType(), llvm::MachineOperand::getParent(), llvm::MachineOperand::getPredicate(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::SPIRVGlobalRegistry::getSPIRVTypeForVReg(), llvm::MachineRegisterInfo::hasOneDef(), llvm::MachineRegisterInfo::hasOneUse(), i, llvm::CmpInst::ICMP_EQ, llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::insert(), llvm::MachineOperand::isMBB(), llvm::MachineOperand::isReg(), isSpvIntrinsic(), MBB, MI, MRI, llvm::MachineIRBuilder::setInsertPt(), llvm::MachineRegisterInfo::setRegClass(), llvm::MachineBasicBlock::succ_begin(), and llvm::MachineRegisterInfo::use_begin().
Referenced by llvm::SPIRVModuleAnalysis::runOnModule().
propagateSPIRVType()
static SPIRVType* propagateSPIRVType (MachineInstr * MI, SPIRVGlobalRegistry * GR, MachineRegisterInfo & MRI, MachineIRBuilder & MIB) static
Definition at line 146 of file SPIRVPreLegalizer.cpp.
References assert(), llvm::SPIRVGlobalRegistry::assignSPIRVTypeToVReg(), llvm::tgtok::Def, llvm::MachineIRBuilder::getMF(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVType(), llvm::MachineRegisterInfo::getRegClassOrNull(), llvm::SPIRVGlobalRegistry::getSPIRVTypeForVReg(), llvm::MachineRegisterInfo::getVRegDef(), MI, MRI, llvm::MachineIRBuilder::setInsertPt(), and llvm::MachineRegisterInfo::setRegClass().
Referenced by generateAssignInstrs().