LLVM: lib/Target/SPIRV/SPIRVUtils.h File Reference
SPIRVUtils.h File Reference
#include "MCTargetDesc/SPIRVBaseInfo.h"
#include "llvm/IR/IRBuilder.h"
#include <string>
Namespaces
llvm
This is an optimization pass for GlobalISel generic memory operations.
Functions
void addStringImm (const llvm::StringRef &Str, llvm::MCInst &Inst)
void addStringImm (const llvm::StringRef &Str, llvm::MachineInstrBuilder &MIB)
void addStringImm (const llvm::StringRef &Str, llvm::IRBuilder<> &B, std::vector< llvm::Value * > &Args)
std::string getStringImm (const llvm::MachineInstr &MI, unsigned StartIndex)
void addNumImm (const llvm::APInt &Imm, llvm::MachineInstrBuilder &MIB)
void buildOpName (llvm::Register Target, const llvm::StringRef &Name, llvm::MachineIRBuilder &MIRBuilder)
void buildOpDecorate (llvm::Register Reg, llvm::MachineIRBuilder &MIRBuilder, llvm::SPIRV::Decoration Dec, const std::vector< uint32_t > &DecArgs, llvm::StringRef StrImm="")
void buildOpDecorate (llvm::Register Reg, llvm::MachineInstr &I, const llvm::SPIRVInstrInfo &TII, llvm::SPIRV::Decoration Dec, const std::vector< uint32_t > &DecArgs, llvm::StringRef StrImm="")
unsigned storageClassToAddressSpace (llvm::SPIRV::StorageClass SC)
llvm::SPIRV::StorageClass addressSpaceToStorageClass (unsigned AddrSpace)
llvm::SPIRV::MemorySemantics getMemSemanticsForStorageClass (llvm::SPIRV::StorageClass SC)
llvm::SPIRV::MemorySemantics getMemSemantics (llvm::AtomicOrdering Ord)
llvm::MachineInstr * getDefInstrMaybeConstant (llvm::Register &ConstReg, const llvm::MachineRegisterInfo *MRI)
uint64_t getIConstVal (llvm::Register ConstReg, const llvm::MachineRegisterInfo *MRI)
bool isSpvIntrinsic (llvm::MachineInstr &MI, llvm::Intrinsic::ID IntrinsicID)
llvm::Type * getMDOperandAsType (const llvm::MDNode *N, unsigned I)
Function Documentation
addNumImm()
void addNumImm (const llvm::APInt & Imm, llvm::MachineInstrBuilder & MIB)
Definition at line 77 of file SPIRVUtils.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::RISCVMatInt::Imm, and llvm::report_fatal_error().
Referenced by llvm::SPIRVGlobalRegistry::buildConstantInt(), and llvm::SPIRVGlobalRegistry::getOrCreateConstInt().
addressSpaceToStorageClass()
llvm::SPIRV::StorageClass addressSpaceToStorageClass (unsigned AddrSpace)
Definition at line 156 of file SPIRVUtils.cpp.
References llvm::SPIRV::CrossWorkgroup, llvm::SPIRV::Function, llvm::SPIRV::Generic, llvm::SPIRV::Input, llvm_unreachable, llvm::SPIRV::UniformConstant, and llvm::SPIRV::Workgroup.
addStringImm() [1/3]
void addStringImm (const llvm::StringRef & Str, llvm::IRBuilder<> & B, std::vector< llvm::Value * > & Args)
Definition at line 64 of file SPIRVUtils.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, B, convertCharsToWord(), getPaddedLen(), and i.
addStringImm() [2/3]
void addStringImm (const llvm::StringRef & Str, llvm::MachineInstrBuilder & MIB)
Definition at line 56 of file SPIRVUtils.cpp.
References llvm::MachineInstrBuilder::addImm(), convertCharsToWord(), getPaddedLen(), and i.
addStringImm() [3/3]
void addStringImm (const llvm::StringRef & Str, llvm::MCInst & Inst)
Definition at line 48 of file SPIRVUtils.cpp.
References llvm::MCInst::addOperand(), convertCharsToWord(), llvm::MCOperand::createImm(), getPaddedLen(), and i.
Referenced by buildOpName(), and finishBuildOpDecorate().
buildOpDecorate() [1/2]
void buildOpDecorate (llvm::Register Reg, llvm::MachineInstr & I, const llvm::SPIRVInstrInfo & TII, llvm::SPIRV::Decoration Dec, const std::vector< uint32_t > & DecArgs, llvm::StringRef StrImm = "")
Definition at line 125 of file SPIRVUtils.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addUse(), llvm::BuildMI(), finishBuildOpDecorate(), I, MBB, and TII.
buildOpDecorate() [2/2]
void buildOpDecorate (llvm::Register Reg, llvm::MachineIRBuilder & MIRBuilder, llvm::SPIRV::Decoration Dec, const std::vector< uint32_t > & DecArgs, llvm::StringRef StrImm = "")
Definition at line 116 of file SPIRVUtils.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addUse(), llvm::MachineIRBuilder::buildInstr(), and finishBuildOpDecorate().
Referenced by llvm::SPIRVGlobalRegistry::buildGlobalVariable().
buildOpName()
void buildOpName (llvm::Register Target, const llvm::StringRef & Name, llvm::MachineIRBuilder & MIRBuilder)
Definition at line 99 of file SPIRVUtils.cpp.
References addStringImm(), llvm::MachineInstrBuilder::addUse(), and llvm::MachineIRBuilder::buildInstr().
Referenced by llvm::SPIRVGlobalRegistry::buildGlobalVariable().
getDefInstrMaybeConstant()
llvm::MachineInstr* getDefInstrMaybeConstant (llvm::Register & ConstReg, const llvm::MachineRegisterInfo * MRI)
Definition at line 211 of file SPIRVUtils.cpp.
References llvm::MachineInstr::getIntrinsicID(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getVRegDef(), and MRI.
Referenced by getIConstVal(), and processSwitches().
getIConstVal()
uint64_t getIConstVal (llvm::Register ConstReg, const llvm::MachineRegisterInfo * MRI)
Definition at line 225 of file SPIRVUtils.cpp.
References assert(), getDefInstrMaybeConstant(), MI, and MRI.
Referenced by processSwitches().
getMDOperandAsType()
llvm::Type* getMDOperandAsType (const llvm::MDNode * N, unsigned I)
Definition at line 236 of file SPIRVUtils.cpp.
References I, and N.
Referenced by generateAssignInstrs().
getMemSemantics()
llvm::SPIRV::MemorySemantics getMemSemantics (llvm::AtomicOrdering Ord)
Definition at line 193 of file SPIRVUtils.cpp.
References llvm::Acquire, llvm::SPIRV::Acquire, llvm::AcquireRelease, llvm::SPIRV::AcquireRelease, llvm::Monotonic, llvm::SPIRV::None, llvm::NotAtomic, llvm::Release, llvm::SPIRV::Release, llvm::SequentiallyConsistent, llvm::SPIRV::SequentiallyConsistent, and llvm::Unordered.
getMemSemanticsForStorageClass()
llvm::SPIRV::MemorySemantics getMemSemanticsForStorageClass (llvm::SPIRV::StorageClass SC)
Definition at line 175 of file SPIRVUtils.cpp.
References llvm::SPIRV::AtomicCounter, llvm::SPIRV::AtomicCounterMemory, llvm::SPIRV::CrossWorkgroup, llvm::SPIRV::CrossWorkgroupMemory, llvm::SPIRV::Image, llvm::SPIRV::ImageMemory, llvm::SPIRV::None, llvm::PPCISD::SC, llvm::SPIRV::StorageBuffer, llvm::SPIRV::Uniform, llvm::SPIRV::UniformMemory, llvm::SPIRV::Workgroup, and llvm::SPIRV::WorkgroupMemory.
getStringImm()
std::string getStringImm (const llvm::MachineInstr & MI, unsigned StartIndex)
Definition at line 73 of file SPIRVUtils.cpp.
References getSPIRVStringOperand(), and MI.
isSpvIntrinsic()
bool isSpvIntrinsic (llvm::MachineInstr & MI, llvm::Intrinsic::ID IntrinsicID)
Definition at line 231 of file SPIRVUtils.cpp.
References MI.
Referenced by addConstantsToTrack(), foldConstantsIntoIntrinsics(), generateAssignInstrs(), insertBitcasts(), and processSwitches().
storageClassToAddressSpace()
unsigned storageClassToAddressSpace (llvm::SPIRV::StorageClass SC)
Definition at line 137 of file SPIRVUtils.cpp.
References llvm::SPIRV::CrossWorkgroup, llvm::SPIRV::Function, llvm::SPIRV::Generic, llvm::SPIRV::Input, llvm_unreachable, llvm::PPCISD::SC, llvm::SPIRV::UniformConstant, and llvm::SPIRV::Workgroup.
Referenced by llvm::SPIRVGlobalRegistry::getOrCreateSPIRVPointerType().