LLVM: lib/Target/SPIRV/SPIRVUtils.cpp File Reference
SPIRVUtils.cpp File Reference
#include "SPIRVUtils.h"
#include "MCTargetDesc/SPIRVBaseInfo.h"
#include "SPIRV.h"
#include "SPIRVInstrInfo.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/IR/IntrinsicsSPIRV.h"
Functions
static uint32_t convertCharsToWord (const StringRef &Str, unsigned i)
static size_t getPaddedLen (const StringRef &Str)
void addStringImm (const StringRef &Str, MCInst &Inst)
void addStringImm (const StringRef &Str, MachineInstrBuilder &MIB)
void addStringImm (const StringRef &Str, IRBuilder<> &B, std::vector< Value * > &Args)
std::string getStringImm (const MachineInstr &MI, unsigned StartIndex)
void addNumImm (const APInt &Imm, MachineInstrBuilder &MIB)
void buildOpName (Register Target, const StringRef &Name, MachineIRBuilder &MIRBuilder)
static void finishBuildOpDecorate (MachineInstrBuilder &MIB, const std::vector< uint32_t > &DecArgs, StringRef StrImm)
void buildOpDecorate (Register Reg, MachineIRBuilder &MIRBuilder, llvm::SPIRV::Decoration Dec, const std::vector< uint32_t > &DecArgs, StringRef StrImm)
void buildOpDecorate (Register Reg, MachineInstr &I, const SPIRVInstrInfo &TII, llvm::SPIRV::Decoration Dec, const std::vector< uint32_t > &DecArgs, StringRef StrImm)
unsigned storageClassToAddressSpace (SPIRV::StorageClass SC)
SPIRV::StorageClass addressSpaceToStorageClass (unsigned AddrSpace)
SPIRV::MemorySemantics getMemSemanticsForStorageClass (SPIRV::StorageClass SC)
SPIRV::MemorySemantics getMemSemantics (AtomicOrdering Ord)
MachineInstr * getDefInstrMaybeConstant (Register &ConstReg, const MachineRegisterInfo *MRI)
uint64_t getIConstVal (Register ConstReg, const MachineRegisterInfo *MRI)
bool isSpvIntrinsic (MachineInstr &MI, Intrinsic::ID IntrinsicID)
Type * getMDOperandAsType (const MDNode *N, unsigned I)
Function Documentation
addNumImm()
void addNumImm (const APInt & Imm, MachineInstrBuilder & MIB)
Definition at line 77 of file SPIRVUtils.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::RISCVMatInt::Imm, and llvm::report_fatal_error().
Referenced by llvm::SPIRVGlobalRegistry::buildConstantInt(), and llvm::SPIRVGlobalRegistry::getOrCreateConstInt().
addressSpaceToStorageClass()
SPIRV::StorageClass addressSpaceToStorageClass (unsigned AddrSpace)
Definition at line 156 of file SPIRVUtils.cpp.
References llvm::SPIRV::CrossWorkgroup, llvm::SPIRV::Function, llvm::SPIRV::Generic, llvm::SPIRV::Input, llvm_unreachable, llvm::SPIRV::UniformConstant, and llvm::SPIRV::Workgroup.
addStringImm() [1/3]
void addStringImm (const StringRef & Str, IRBuilder<> & B, std::vector< Value * > & Args)
Definition at line 64 of file SPIRVUtils.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, B, convertCharsToWord(), getPaddedLen(), and i.
addStringImm() [2/3]
void addStringImm (const StringRef & Str, MachineInstrBuilder & MIB)
Definition at line 56 of file SPIRVUtils.cpp.
References llvm::MachineInstrBuilder::addImm(), convertCharsToWord(), getPaddedLen(), and i.
addStringImm() [3/3]
void addStringImm (const StringRef & Str, MCInst & Inst)
Definition at line 48 of file SPIRVUtils.cpp.
References llvm::MCInst::addOperand(), convertCharsToWord(), llvm::MCOperand::createImm(), getPaddedLen(), and i.
Referenced by buildOpName(), and finishBuildOpDecorate().
buildOpDecorate() [1/2]
void buildOpDecorate (Register Reg, MachineInstr & I, const SPIRVInstrInfo & TII, llvm::SPIRV::Decoration Dec, const std::vector< uint32_t > & DecArgs, StringRef StrImm)
Definition at line 125 of file SPIRVUtils.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addUse(), llvm::BuildMI(), finishBuildOpDecorate(), I, MBB, and TII.
buildOpDecorate() [2/2]
void buildOpDecorate (Register Reg, MachineIRBuilder & MIRBuilder, llvm::SPIRV::Decoration Dec, const std::vector< uint32_t > & DecArgs, StringRef StrImm)
Definition at line 116 of file SPIRVUtils.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addUse(), llvm::MachineIRBuilder::buildInstr(), and finishBuildOpDecorate().
Referenced by llvm::SPIRVGlobalRegistry::buildGlobalVariable().
buildOpName()
void buildOpName (Register Target, const StringRef & Name, MachineIRBuilder & MIRBuilder)
Definition at line 99 of file SPIRVUtils.cpp.
References addStringImm(), llvm::MachineInstrBuilder::addUse(), and llvm::MachineIRBuilder::buildInstr().
Referenced by llvm::SPIRVGlobalRegistry::buildGlobalVariable().
convertCharsToWord()
static uint32_t convertCharsToWord (const StringRef & Str, unsigned i) static
Definition at line 29 of file SPIRVUtils.cpp.
References i.
Referenced by addStringImm().
finishBuildOpDecorate()
static void finishBuildOpDecorate (MachineInstrBuilder & MIB, const std::vector< uint32_t > & DecArgs, StringRef StrImm) static
Definition at line 107 of file SPIRVUtils.cpp.
References llvm::MachineInstrBuilder::addImm(), addStringImm(), and llvm::StringRef::empty().
Referenced by buildOpDecorate().
getDefInstrMaybeConstant()
MachineInstr* getDefInstrMaybeConstant (Register & ConstReg, const MachineRegisterInfo * MRI)
Definition at line 211 of file SPIRVUtils.cpp.
References llvm::MachineInstr::getIntrinsicID(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getVRegDef(), and MRI.
Referenced by getIConstVal(), and processSwitches().
getIConstVal()
uint64_t getIConstVal (Register ConstReg, const MachineRegisterInfo * MRI)
Definition at line 225 of file SPIRVUtils.cpp.
References assert(), getDefInstrMaybeConstant(), MI, and MRI.
Referenced by processSwitches().
getMDOperandAsType()
Type* getMDOperandAsType (const MDNode * N, unsigned I)
Definition at line 236 of file SPIRVUtils.cpp.
References I, and N.
Referenced by generateAssignInstrs().
getMemSemantics()
SPIRV::MemorySemantics getMemSemantics (AtomicOrdering Ord)
Definition at line 193 of file SPIRVUtils.cpp.
References llvm::Acquire, llvm::SPIRV::Acquire, llvm::AcquireRelease, llvm::SPIRV::AcquireRelease, llvm::Monotonic, llvm::SPIRV::None, llvm::NotAtomic, llvm::Release, llvm::SPIRV::Release, llvm::SequentiallyConsistent, llvm::SPIRV::SequentiallyConsistent, and llvm::Unordered.
getMemSemanticsForStorageClass()
SPIRV::MemorySemantics getMemSemanticsForStorageClass (SPIRV::StorageClass SC)
Definition at line 175 of file SPIRVUtils.cpp.
References llvm::SPIRV::AtomicCounter, llvm::SPIRV::AtomicCounterMemory, llvm::SPIRV::CrossWorkgroup, llvm::SPIRV::CrossWorkgroupMemory, llvm::SPIRV::Image, llvm::SPIRV::ImageMemory, llvm::SPIRV::None, llvm::PPCISD::SC, llvm::SPIRV::StorageBuffer, llvm::SPIRV::Uniform, llvm::SPIRV::UniformMemory, llvm::SPIRV::Workgroup, and llvm::SPIRV::WorkgroupMemory.
getPaddedLen()
static size_t getPaddedLen (const StringRef & Str) static
Definition at line 43 of file SPIRVUtils.cpp.
Referenced by addStringImm().
getStringImm()
std::string getStringImm (const MachineInstr & MI, unsigned StartIndex)
Definition at line 73 of file SPIRVUtils.cpp.
References getSPIRVStringOperand(), and MI.
isSpvIntrinsic()
bool isSpvIntrinsic (MachineInstr & MI, Intrinsic::ID IntrinsicID)
Definition at line 231 of file SPIRVUtils.cpp.
References MI.
Referenced by addConstantsToTrack(), foldConstantsIntoIntrinsics(), generateAssignInstrs(), insertBitcasts(), and processSwitches().
storageClassToAddressSpace()
unsigned storageClassToAddressSpace (SPIRV::StorageClass SC)
Definition at line 137 of file SPIRVUtils.cpp.
References llvm::SPIRV::CrossWorkgroup, llvm::SPIRV::Function, llvm::SPIRV::Generic, llvm::SPIRV::Input, llvm_unreachable, llvm::PPCISD::SC, llvm::SPIRV::UniformConstant, and llvm::SPIRV::Workgroup.
Referenced by llvm::SPIRVGlobalRegistry::getOrCreateSPIRVPointerType().