LLVM: llvm::LoongArchRegisterInfo Struct Reference
llvm::LoongArchRegisterInfo Struct Reference
#include "Target/LoongArch/LoongArchRegisterInfo.h"
Public Member Functions
LoongArchRegisterInfo (unsigned HwMode)
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID) const override
const uint32_t * getNoPreservedMask () const override
BitVector getReservedRegs (const MachineFunction &MF) const override
bool isConstantPhysReg (MCRegister PhysReg) const override
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind=0) const override
void eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
Register getFrameRegister (const MachineFunction &MF) const override
Detailed Description
Definition at line 24 of file LoongArchRegisterInfo.h.
Constructor & Destructor Documentation
LoongArchRegisterInfo()
LoongArchRegisterInfo::LoongArchRegisterInfo (unsigned HwMode)
Definition at line 30 of file LoongArchRegisterInfo.cpp.
Member Function Documentation
eliminateFrameIndex()
void LoongArchRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const override
Definition at line 109 of file LoongArchRegisterInfo.cpp.
References assert(), DL, llvm::ISD::FrameIndex, llvm::StackOffset::getFixed(), llvm::TargetFrameLowering::getFrameIndexReference(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFunction::getSubtarget(), MI, and llvm::report_fatal_error().
getCalleeSavedRegs()
const MCPhysReg * LoongArchRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const override
Definition at line 36 of file LoongArchRegisterInfo.cpp.
References llvm::LoongArchABI::ABI_ILP32D, llvm::LoongArchABI::ABI_ILP32F, llvm::LoongArchABI::ABI_ILP32S, llvm::LoongArchABI::ABI_LP64D, llvm::LoongArchABI::ABI_LP64F, llvm::LoongArchABI::ABI_LP64S, llvm::MachineFunction::getSubtarget(), and llvm_unreachable.
getCallPreservedMask()
const uint32_t * LoongArchRegisterInfo::getCallPreservedMask (const MachineFunction & MF, CallingConv::ID CC) const override
Definition at line 55 of file LoongArchRegisterInfo.cpp.
References llvm::LoongArchABI::ABI_ILP32D, llvm::LoongArchABI::ABI_ILP32F, llvm::LoongArchABI::ABI_ILP32S, llvm::LoongArchABI::ABI_LP64D, llvm::LoongArchABI::ABI_LP64F, llvm::LoongArchABI::ABI_LP64S, llvm::MachineFunction::getSubtarget(), and llvm_unreachable.
getFrameRegister()
Register LoongArchRegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 104 of file LoongArchRegisterInfo.cpp.
References llvm::TargetFrameLowering::hasFP().
getNoPreservedMask()
const uint32_t * LoongArchRegisterInfo::getNoPreservedMask () const override
Definition at line 74 of file LoongArchRegisterInfo.cpp.
getPointerRegClass()
const TargetRegisterClass* llvm::LoongArchRegisterInfo::getPointerRegClass (const MachineFunction & MF, unsigned Kind = 0) const inline override
Definition at line 37 of file LoongArchRegisterInfo.h.
getReservedRegs()
BitVector LoongArchRegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 79 of file LoongArchRegisterInfo.cpp.
References assert(), llvm::LoongArchABI::getBPReg(), llvm::LoongArchFrameLowering::hasBP(), llvm::LoongArchFrameLowering::hasFP(), and R2.
isConstantPhysReg()
bool LoongArchRegisterInfo::isConstantPhysReg (MCRegister PhysReg) const override
Definition at line 99 of file LoongArchRegisterInfo.cpp.
The documentation for this struct was generated from the following files:
lib/Target/LoongArch/LoongArchRegisterInfo.h
lib/Target/LoongArch/LoongArchRegisterInfo.cpp