LLVM: llvm::BitstreamEntry Struct Reference
llvm::BitstreamEntry Struct Reference
When advancing through a bitstream cursor, each advance can discover a few different kinds of entries:
#include "llvm/Bitstream/BitstreamReader.h"
Public Types
enum { Error, EndBlock, SubBlock, Record }
Static Public Member Functions
static BitstreamEntry getError ()
static BitstreamEntry getEndBlock ()
static BitstreamEntry getSubBlock (unsigned ID)
static BitstreamEntry getRecord (unsigned AbbrevID)
Public Attributes
enum llvm::BitstreamEntry:: { ... } Kind
unsigned ID
Detailed Description
When advancing through a bitstream cursor, each advance can discover a few different kinds of entries:
Definition at line 325 of file BitstreamReader.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Error
EndBlock
SubBlock
Record
Definition at line 326 of file BitstreamReader.h.
Member Function Documentation
getEndBlock()
static BitstreamEntry llvm::BitstreamEntry::getEndBlock () inline static
Definition at line 340 of file BitstreamReader.h.
References E, and EndBlock.
Referenced by llvm::BitstreamCursor::advance().
getError()
static BitstreamEntry llvm::BitstreamEntry::getError () inline static
Definition at line 336 of file BitstreamReader.h.
References E, and Error.
Referenced by llvm::BitstreamCursor::advance().
getRecord()
static BitstreamEntry llvm::BitstreamEntry::getRecord (unsigned AbbrevID) inline static
Definition at line 348 of file BitstreamReader.h.
References E, and Record.
getSubBlock()
static BitstreamEntry llvm::BitstreamEntry::getSubBlock (unsigned ID) inline static
Definition at line 344 of file BitstreamReader.h.
References E, ID, and SubBlock.
Referenced by llvm::BitstreamCursor::advance().
Member Data Documentation
ID
unsigned llvm::BitstreamEntry::ID
Definition at line 334 of file BitstreamReader.h.
Referenced by getSubBlock().
Kind
enum { ... } llvm::BitstreamEntry::Kind
The documentation for this struct was generated from the following file:
include/llvm/Bitstream/BitstreamReader.h