LLVM: AA::PointerInfo::State Struct Reference
AA::PointerInfo::State Struct Reference
A type to track pointer/struct usage and accesses for AAPointerInfo.
Classes
struct Accesses
We store accesses in a set with the instruction as key.
Public Types
using AccessBinsTy = DenseMap< AAPointerInfo::OffsetAndSize, Accesses * >
We store all accesses in bins denoted by their offset and size.
Public Member Functions
~State ()
State ()=default
State (State &&SIS)
const State & getAssumed () const
bool isValidState () const override
See AbstractState::isValidState().
bool isAtFixpoint () const override
See AbstractState::isAtFixpoint().
ChangeStatus indicateOptimisticFixpoint () override
See AbstractState::indicateOptimisticFixpoint().
ChangeStatus indicatePessimisticFixpoint () override
See AbstractState::indicatePessimisticFixpoint().
State & operator= (const State &R)
State & operator= (State &&R)
bool operator== (const State &R) const
bool operator!= (const State &R) const
AccessBinsTy::const_iterator begin () const
AccessBinsTy::const_iterator end () const
Public Member Functions inherited from llvm::AbstractState
virtual ~AbstractState ()=default
Static Public Member Functions
static State getBestState (const State &SIS)
Return the best possible representable state.
static State getWorstState (const State &SIS)
Return the worst possible representable state.
Protected Member Functions
ChangeStatus addAccess (Attributor &A, int64_t Offset, int64_t Size, Instruction &I, Optional< Value * > Content, AAPointerInfo::AccessKind Kind, Type *Ty, Instruction *RemoteI=nullptr, Accesses *BinPtr=nullptr)
Add a new access to the state at offset Offset and with size Size.
bool forallInterferingAccesses (AAPointerInfo::OffsetAndSize OAS, function_ref< bool(const AAPointerInfo::Access &, bool)> CB) const
See AAPointerInfo::forallInterferingAccesses.
bool forallInterferingAccesses (Instruction &I, function_ref< bool(const AAPointerInfo::Access &, bool)> CB) const
See AAPointerInfo::forallInterferingAccesses.
Protected Attributes
AccessBinsTy AccessBins
The bins with all the accesses for the associated pointer.
Detailed Description
A type to track pointer/struct usage and accesses for AAPointerInfo.
Definition at line 739 of file AttributorAttributes.cpp.
Member Typedef Documentation
AccessBinsTy
using AA::PointerInfo::State::AccessBinsTy = DenseMap<AAPointerInfo::OffsetAndSize, Accesses *>
We store all accesses in bins denoted by their offset and size.
Definition at line 849 of file AttributorAttributes.cpp.
Constructor & Destructor Documentation
~State()
AA::PointerInfo::State::~State () inline
Definition at line 741 of file AttributorAttributes.cpp.
State() [1/2]
AA::PointerInfo::State::State () default
State() [2/2]
AA::PointerInfo::State::State (State && SIS) inline
Definition at line 758 of file AttributorAttributes.cpp.
Member Function Documentation
addAccess()
ChangeStatus AA::PointerInfo::State::addAccess (Attributor & A, int64_t Offset, int64_t Size, Instruction & I, Optional< Value * > Content, AAPointerInfo::AccessKind Kind, Type * Ty, Instruction * RemoteI = nullptr, Accesses * BinPtr = nullptr) inline protected
Add a new access to the state at offset Offset and with size Size.
The access is associated with I, writes Content (if anything), and is of kind Kind. \Returns CHANGED, if the state changed, UNCHANGED otherwise.
Definition at line 862 of file AttributorAttributes.cpp.
References llvm::Bin, llvm::CHANGED, Content, I, and llvm::UNCHANGED.
begin()
AccessBinsTy::const_iterator AA::PointerInfo::State::begin () const inline
Definition at line 851 of file AttributorAttributes.cpp.
end()
AccessBinsTy::const_iterator AA::PointerInfo::State::end () const inline
Definition at line 852 of file AttributorAttributes.cpp.
forallInterferingAccesses() [1/2]
bool AA::PointerInfo::State::forallInterferingAccesses (AAPointerInfo::OffsetAndSize OAS, function_ref< bool(const AAPointerInfo::Access &, bool)> CB) const inline protected
See AAPointerInfo::forallInterferingAccesses.
Definition at line 888 of file AttributorAttributes.cpp.
References llvm::AAPointerInfo::OffsetAndSize::mayOverlap(), and llvm::AAPointerInfo::OffsetAndSize::offsetOrSizeAreUnknown().
forallInterferingAccesses() [2/2]
bool AA::PointerInfo::State::forallInterferingAccesses (Instruction & I, function_ref< bool(const AAPointerInfo::Access &, bool)> CB) const inline protected
See AAPointerInfo::forallInterferingAccesses.
Definition at line 907 of file AttributorAttributes.cpp.
References llvm::AAPointerInfo::OffsetAndSize::getSize(), and I.
getAssumed()
const State& AA::PointerInfo::State::getAssumed () const inline
Definition at line 762 of file AttributorAttributes.cpp.
getBestState()
static State AA::PointerInfo::State::getBestState (const State & SIS) inline static
Return the best possible representable state.
Definition at line 748 of file AttributorAttributes.cpp.
getWorstState()
static State AA::PointerInfo::State::getWorstState (const State & SIS) inline static
Return the worst possible representable state.
Definition at line 751 of file AttributorAttributes.cpp.
indicateOptimisticFixpoint()
ChangeStatus AA::PointerInfo::State::indicateOptimisticFixpoint () inline override virtual
See AbstractState::indicateOptimisticFixpoint().
Implements llvm::AbstractState.
Definition at line 771 of file AttributorAttributes.cpp.
References llvm::UNCHANGED.
indicatePessimisticFixpoint()
ChangeStatus AA::PointerInfo::State::indicatePessimisticFixpoint () inline override virtual
See AbstractState::indicatePessimisticFixpoint().
Implements llvm::AbstractState.
Definition at line 777 of file AttributorAttributes.cpp.
References llvm::CHANGED.
isAtFixpoint()
bool AA::PointerInfo::State::isAtFixpoint () const inline override virtual
See AbstractState::isAtFixpoint().
Implements llvm::AbstractState.
Definition at line 768 of file AttributorAttributes.cpp.
isValidState()
bool AA::PointerInfo::State::isValidState () const inline override virtual
See AbstractState::isValidState().
Implements llvm::AbstractState.
Definition at line 765 of file AttributorAttributes.cpp.
operator!=()
bool AA::PointerInfo::State::operator!= (const State & R) const inline
Definition at line 819 of file AttributorAttributes.cpp.
operator=() [1/2]
State& AA::PointerInfo::State::operator= (const State & R) inline
Definition at line 782 of file AttributorAttributes.cpp.
operator=() [2/2]
State& AA::PointerInfo::State::operator= (State && R) inline
Definition at line 790 of file AttributorAttributes.cpp.
References std::swap().
operator==()
bool AA::PointerInfo::State::operator== (const State & R) const inline
Definition at line 798 of file AttributorAttributes.cpp.
References llvm::sys::path::begin(), E, llvm::sys::path::end(), and llvm::zip().
Member Data Documentation
AccessBins
AccessBinsTy AA::PointerInfo::State::AccessBins protected
The bins with all the accesses for the associated pointer.
Definition at line 856 of file AttributorAttributes.cpp.
The documentation for this struct was generated from the following file:
lib/Transforms/IPO/AttributorAttributes.cpp