LLVM: VOPDPairingMutation Struct Reference
VOPDPairingMutation Struct Reference
Adapts design from MacroFusion Puts valid candidate instructions back-to-back so they can easily be turned into VOPD instructions Greedily pairs instruction candidates.
Public Member Functions
VOPDPairingMutation (ShouldSchedulePredTy shouldScheduleAdjacent)
void apply (ScheduleDAGInstrs *DAG) override
Public Member Functions inherited from llvm::ScheduleDAGMutation
virtual ~ScheduleDAGMutation ()=default
Public Attributes
ShouldSchedulePredTy shouldScheduleAdjacent
Detailed Description
Adapts design from MacroFusion Puts valid candidate instructions back-to-back so they can easily be turned into VOPD instructions Greedily pairs instruction candidates.
O(n^2) algorithm.
Definition at line 172 of file GCNVOPDUtils.cpp.
Constructor & Destructor Documentation
VOPDPairingMutation()
VOPDPairingMutation::VOPDPairingMutation (ShouldSchedulePredTy shouldScheduleAdjacent) inline
Definition at line 175 of file GCNVOPDUtils.cpp.
Member Function Documentation
apply()
void VOPDPairingMutation::apply (ScheduleDAGInstrs * DAG) inline override virtual
Implements llvm::ScheduleDAGMutation.
Definition at line 179 of file GCNVOPDUtils.cpp.
References llvm::dbgs(), llvm::fuseInstructionPair(), llvm::MachineFunction::getSubtarget(), llvm::hasLessThanNumFused(), llvm::AMDGPU::hasVOPD(), LLVM_DEBUG, llvm::ScheduleDAG::MF, llvm::shouldScheduleAdjacent(), llvm::ARM_MB::ST, llvm::ScheduleDAG::SUnits, TII, and llvm::ScheduleDAG::TII.
Member Data Documentation
shouldScheduleAdjacent
ShouldSchedulePredTy VOPDPairingMutation::shouldScheduleAdjacent
Definition at line 173 of file GCNVOPDUtils.cpp.
The documentation for this struct was generated from the following file:
lib/Target/AMDGPU/GCNVOPDUtils.cpp