LLVM: lib/Transforms/Vectorize/VPlan.cpp File Reference
VPlan.cpp File Reference
#include "VPlan.h"
#include "VPlanDominatorTree.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/GenericDomTreeConstruction.h"
#include "llvm/Support/GraphWriter.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/LoopVersioning.h"
#include "llvm/Transforms/Utils/ScalarEvolutionExpander.h"
#include <cassert>
#include <string>
#include <vector>
Macros
#define DEBUG_TYPE "vplan"
Functions
template<typename T >
static T * getPlanEntry (T *Start)
static bool hasConditionalTerminator (const VPBasicBlock *VPBB)
static bool canSimplifyBranchOnCond (VPInstruction *Term)
Variables
cl::opt< bool > EnableVPlanNativePath
Detailed Description
This is the LLVM vectorization plan. It represents a candidate for vectorization, allowing to plan and optimize how to vectorize a given loop before generating LLVM-IR. The vectorizer uses vectorization plans to estimate the costs of potential candidates and if profitable to execute the desired plan, generating vector LLVM-IR code.
Definition in file VPlan.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "vplan"
Definition at line 50 of file VPlan.cpp.
Function Documentation
canSimplifyBranchOnCond()
static bool canSimplifyBranchOnCond (VPInstruction * Term) static
Definition at line 580 of file VPlan.cpp.
References llvm::VPInstruction::ActiveLaneMask, llvm::VPInstruction::getOpcode(), llvm::VPUser::getOperand(), llvm::VPInstruction::Not, and llvm::M68kBeads::Term.
Referenced by llvm::VPlan::prepareToExecute().
getPlanEntry()
template<typename T > static T* getPlanEntry (T * Start) static
Definition at line 114 of file VPlan.cpp.
References i, llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::insert(), llvm_unreachable, and llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::size().
Referenced by llvm::VPBlockBase::getPlan().
hasConditionalTerminator()
static bool hasConditionalTerminator (const VPBasicBlock * VPBB) static
Definition at line 427 of file VPlan.cpp.
References assert(), llvm::VPBasicBlock::back(), llvm::VPInstruction::BranchOnCond, llvm::VPInstruction::BranchOnCount, llvm::VPBasicBlock::empty(), llvm::VPBlockBase::getNumSuccessors(), IsCondBranch(), and llvm::VPBasicBlock::isExiting().
Referenced by llvm::VPBasicBlock::getTerminator().
Variable Documentation
EnableVPlanNativePath
cl::opt<bool> EnableVPlanNativePath