LLVM: lib/Target/AMDGPU/AMDGPUTargetMachine.cpp File Reference
AMDGPUTargetMachine.cpp File Reference
The AMDGPU target machine contains all of the hardware specific information needed to emit code for SI+ GPUs.
#include "AMDGPUTargetMachine.h"
#include "AMDGPU.h"
#include "AMDGPUAliasAnalysis.h"
#include "AMDGPUExportClustering.h"
#include "AMDGPUMacroFusion.h"
#include "AMDGPUTargetObjectFile.h"
#include "AMDGPUTargetTransformInfo.h"
#include "GCNIterativeScheduler.h"
#include "GCNSchedStrategy.h"
#include "R600.h"
#include "R600TargetMachine.h"
#include "SIMachineFunctionInfo.h"
#include "SIMachineScheduler.h"
#include "TargetInfo/AMDGPUTargetInfo.h"
#include "llvm/Analysis/CGSCCPassManager.h"
#include "llvm/CodeGen/GlobalISel/IRTranslator.h"
#include "llvm/CodeGen/GlobalISel/InstructionSelect.h"
#include "llvm/CodeGen/GlobalISel/Legalizer.h"
#include "llvm/CodeGen/GlobalISel/Localizer.h"
#include "llvm/CodeGen/GlobalISel/RegBankSelect.h"
#include "llvm/CodeGen/MIRParser/MIParser.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/RegAllocRegistry.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/InitializePasses.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Passes/PassBuilder.h"
#include "llvm/Transforms/IPO.h"
#include "llvm/Transforms/IPO/AlwaysInliner.h"
#include "llvm/Transforms/IPO/GlobalDCE.h"
#include "llvm/Transforms/IPO/Internalize.h"
#include "llvm/Transforms/IPO/PassManagerBuilder.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Scalar/GVN.h"
#include "llvm/Transforms/Scalar/InferAddressSpaces.h"
#include "llvm/Transforms/Utils.h"
#include "llvm/Transforms/Utils/SimplifyLibCalls.h"
#include "llvm/Transforms/Vectorize.h"
Functions
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeAMDGPUTarget ()
static std::unique_ptr< TargetLoweringObjectFile > createTLOF (const Triple &TT)
static ScheduleDAGInstrs * createSIMachineScheduler (MachineSchedContext *C)
static ScheduleDAGInstrs * createGCNMaxOccupancyMachineScheduler (MachineSchedContext *C)
static ScheduleDAGInstrs * createIterativeGCNMaxOccupancyMachineScheduler (MachineSchedContext *C)
static ScheduleDAGInstrs * createMinRegScheduler (MachineSchedContext *C)
static ScheduleDAGInstrs * createIterativeILPMachineScheduler (MachineSchedContext *C)
static StringRef computeDataLayout (const Triple &TT)
static LLVM_READNONE StringRef getGPUOrDefault (const Triple &TT, StringRef GPU)
static Reloc::Model getEffectiveRelocModel (Optional< Reloc::Model > RM)
static bool mustPreserveGV (const GlobalValue &GV)
Predicate for Internalize pass.
Variables
static cl::opt< bool > EnableSROA ("amdgpu-sroa", cl::desc("Run SROA after promote alloca pass"), cl::ReallyHidden, cl::init(true))
static cl::opt< bool > EnableEarlyIfConversion ("amdgpu-early-ifcvt", cl::Hidden, cl::desc("Run early if-conversion"), cl::init(false))
static cl::opt< bool > OptExecMaskPreRA ("amdgpu-opt-exec-mask-pre-ra", cl::Hidden, cl::desc("Run pre-RA exec mask optimizations"), cl::init(true))
static cl::opt< bool > EnableLoadStoreVectorizer ("amdgpu-load-store-vectorizer", cl::desc("Enable load store vectorizer"), cl::init(true), cl::Hidden)
static cl::opt< bool > ScalarizeGlobal ("amdgpu-scalarize-global-loads", cl::desc("Enable global load scalarization"), cl::init(true), cl::Hidden)
static cl::opt< bool > InternalizeSymbols ("amdgpu-internalize-symbols", cl::desc("Enable elimination of non-kernel functions and unused globals"), cl::init(false), cl::Hidden)
static cl::opt< bool > EarlyInlineAll ("amdgpu-early-inline-all", cl::desc("Inline all functions early"), cl::init(false), cl::Hidden)
static cl::opt< bool > EnableSDWAPeephole ("amdgpu-sdwa-peephole", cl::desc("Enable SDWA peepholer"), cl::init(true))
static cl::opt< bool > EnableDPPCombine ("amdgpu-dpp-combine", cl::desc("Enable DPP combiner"), cl::init(true))
static cl::opt< bool > EnableAMDGPUAliasAnalysis ("enable-amdgpu-aa", cl::Hidden, cl::desc("Enable AMDGPU Alias Analysis"), cl::init(true))
static cl::opt< bool, true > LateCFGStructurize ("amdgpu-late-structurize", cl::desc("Enable late CFG structurization"), cl::location(AMDGPUTargetMachine::EnableLateStructurizeCFG), cl::Hidden)
static cl::opt< bool > EnableLibCallSimplify ("amdgpu-simplify-libcall", cl::desc("Enable amdgpu library simplifications"), cl::init(true), cl::Hidden)
static cl::opt< bool > EnableLowerKernelArguments ("amdgpu-ir-lower-kernel-arguments", cl::desc("Lower kernel argument loads in IR pass"), cl::init(true), cl::Hidden)
static cl::opt< bool > EnableRegReassign ("amdgpu-reassign-regs", cl::desc("Enable register reassign optimizations on gfx10+"), cl::init(true), cl::Hidden)
static cl::opt< bool > OptVGPRLiveRange ("amdgpu-opt-vgpr-liverange", cl::desc("Enable VGPR liverange optimizations for if-else structure"), cl::init(true), cl::Hidden)
static cl::opt< bool > EnableAtomicOptimizations ("amdgpu-atomic-optimizations", cl::desc("Enable atomic optimizations"), cl::init(false), cl::Hidden)
static cl::opt< bool > EnableSIModeRegisterPass ("amdgpu-mode-register", cl::desc("Enable mode register pass"), cl::init(true), cl::Hidden)
static cl::opt< bool > EnableDCEInRA ("amdgpu-dce-in-ra", cl::init(true), cl::Hidden, cl::desc("Enable machine DCE inside regalloc"))
static cl::opt< bool > EnableScalarIRPasses ("amdgpu-scalar-ir-passes", cl::desc("Enable scalar IR passes"), cl::init(true), cl::Hidden)
static cl::opt< bool > EnableStructurizerWorkarounds ("amdgpu-enable-structurizer-workarounds", cl::desc("Enable workarounds for the StructurizeCFG pass"), cl::init(true), cl::Hidden)
static cl::opt< bool > EnableLDSReplaceWithPointer ("amdgpu-enable-lds-replace-with-pointer", cl::desc("Enable LDS replace with pointer pass"), cl::init(false), cl::Hidden)
static cl::opt< bool, true > EnableLowerModuleLDS ("amdgpu-enable-lower-module-lds", cl::desc("Enable lower module lds pass"), cl::location(AMDGPUTargetMachine::EnableLowerModuleLDS), cl::init(true), cl::Hidden)
static cl::opt< bool > EnablePreRAOptimizations ("amdgpu-enable-pre-ra-optimizations", cl::desc("Enable Pre-RA optimizations pass"), cl::init(true), cl::Hidden)
static cl::opt< bool > EnablePromoteKernelArguments ("amdgpu-enable-promote-kernel-arguments", cl::desc("Enable promotion of flat kernel pointer arguments to global"), cl::Hidden, cl::init(true))
static MachineSchedRegistry SISchedRegistry ("si", "Run SI's custom scheduler", createSIMachineScheduler)
static MachineSchedRegistry GCNMaxOccupancySchedRegistry ("gcn-max-occupancy", "Run GCN scheduler to maximize occupancy", createGCNMaxOccupancyMachineScheduler)
static MachineSchedRegistry IterativeGCNMaxOccupancySchedRegistry ("gcn-max-occupancy-experimental", "Run GCN scheduler to maximize occupancy (experimental)", createIterativeGCNMaxOccupancyMachineScheduler)
static MachineSchedRegistry GCNMinRegSchedRegistry ("gcn-minreg", "Run GCN iterative scheduler for minimal register usage (experimental)", createMinRegScheduler)
static MachineSchedRegistry GCNILPSchedRegistry ("gcn-ilp", "Run GCN iterative scheduler for ILP scheduling (experimental)", createIterativeILPMachineScheduler)
static const char RegAllocOptNotSupportedMessage []
Detailed Description
The AMDGPU target machine contains all of the hardware specific information needed to emit code for SI+ GPUs.
Definition in file AMDGPUTargetMachine.cpp.
Function Documentation
computeDataLayout()
static StringRef computeDataLayout (const Triple & TT) static
Definition at line 447 of file AMDGPUTargetMachine.cpp.
References llvm::Triple::r600.
createGCNMaxOccupancyMachineScheduler()
static ScheduleDAGInstrs* createGCNMaxOccupancyMachineScheduler (MachineSchedContext * C) static
Definition at line 392 of file AMDGPUTargetMachine.cpp.
References llvm::ScheduleDAGMI::addMutation(), C, llvm::createAMDGPUExportClusteringDAGMutation(), llvm::createAMDGPUMacroFusionDAGMutation(), llvm::createLoadClusterDAGMutation(), llvm::ScheduleDAG::TII, and llvm::ScheduleDAG::TRI.
createIterativeGCNMaxOccupancyMachineScheduler()
static ScheduleDAGInstrs* createIterativeGCNMaxOccupancyMachineScheduler (MachineSchedContext * C) static
Definition at line 402 of file AMDGPUTargetMachine.cpp.
References C, llvm::createLoadClusterDAGMutation(), and llvm::GCNIterativeScheduler::SCHEDULE_LEGACYMAXOCCUPANCY.
createIterativeILPMachineScheduler()
static ScheduleDAGInstrs* createIterativeILPMachineScheduler (MachineSchedContext * C) static
Definition at line 415 of file AMDGPUTargetMachine.cpp.
References C, llvm::createAMDGPUMacroFusionDAGMutation(), llvm::createLoadClusterDAGMutation(), and llvm::GCNIterativeScheduler::SCHEDULE_ILP.
createMinRegScheduler()
static ScheduleDAGInstrs* createMinRegScheduler (MachineSchedContext * C) static
Definition at line 409 of file AMDGPUTargetMachine.cpp.
References C, and llvm::GCNIterativeScheduler::SCHEDULE_MINREGFORCED.
createSIMachineScheduler()
static ScheduleDAGInstrs* createSIMachineScheduler (MachineSchedContext * C) static
Definition at line 387 of file AMDGPUTargetMachine.cpp.
References C.
createTLOF()
static std::unique_ptr<TargetLoweringObjectFile> createTLOF (const Triple & TT) static
Definition at line 383 of file AMDGPUTargetMachine.cpp.
getEffectiveRelocModel()
static Reloc::Model getEffectiveRelocModel (Optional< Reloc::Model > RM) static
Definition at line 474 of file AMDGPUTargetMachine.cpp.
References llvm::Reloc::PIC_.
getGPUOrDefault()
static LLVM_READNONE StringRef getGPUOrDefault (const Triple & TT, StringRef GPU) static
Definition at line 463 of file AMDGPUTargetMachine.cpp.
References llvm::Triple::amdgcn, llvm::Triple::AMDHSA, and llvm::StringRef::empty().
LLVMInitializeAMDGPUTarget()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeAMDGPUTarget ()
Definition at line 309 of file AMDGPUTargetMachine.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::getTheAMDGPUTarget(), llvm::getTheGCNTarget(), llvm::initializeAMDGPUAAWrapperPassPass(), llvm::initializeAMDGPUAlwaysInlinePass(), llvm::initializeAMDGPUAnnotateKernelFeaturesPass(), llvm::initializeAMDGPUAnnotateUniformValuesPass(), llvm::initializeAMDGPUArgumentUsageInfoPass(), llvm::initializeAMDGPUAtomicOptimizerPass(), llvm::initializeAMDGPUAttributorPass(), llvm::initializeAMDGPUCodeGenPreparePass(), llvm::initializeAMDGPUCtorDtorLoweringPass(), llvm::initializeAMDGPUDAGToDAGISelPass(), llvm::initializeAMDGPUExternalAAWrapperPass(), llvm::initializeAMDGPUFixFunctionBitcastsPass(), llvm::initializeAMDGPULateCodeGenPreparePass(), llvm::initializeAMDGPULowerIntrinsicsPass(), llvm::initializeAMDGPULowerKernelArgumentsPass(), llvm::initializeAMDGPULowerKernelAttributesPass(), llvm::initializeAMDGPULowerModuleLDSPass(), llvm::initializeAMDGPUOpenCLEnqueuedBlockLoweringPass(), llvm::initializeAMDGPUPostLegalizerCombinerPass(), llvm::initializeAMDGPUPreLegalizerCombinerPass(), llvm::initializeAMDGPUPrintfRuntimeBindingPass(), llvm::initializeAMDGPUPromoteAllocaPass(), llvm::initializeAMDGPUPromoteAllocaToVectorPass(), llvm::initializeAMDGPUPromoteKernelArgumentsPass(), llvm::initializeAMDGPUPropagateAttributesEarlyPass(), llvm::initializeAMDGPUPropagateAttributesLatePass(), llvm::initializeAMDGPURegBankCombinerPass(), llvm::initializeAMDGPUReplaceLDSUseWithPointerPass(), llvm::initializeAMDGPUResourceUsageAnalysisPass(), llvm::initializeAMDGPURewriteOutArgumentsPass(), llvm::initializeAMDGPUSimplifyLibCallsPass(), llvm::initializeAMDGPUUnifyDivergentExitNodesPass(), llvm::initializeAMDGPUUnifyMetadataPass(), llvm::initializeAMDGPUUseNativeCallsPass(), llvm::initializeGCNDPPCombinePass(), llvm::initializeGCNNSAReassignPass(), llvm::initializeGCNPreRAOptimizationsPass(), llvm::initializeGlobalISel(), llvm::initializeR600ClauseMergePassPass(), llvm::initializeR600ControlFlowFinalizerPass(), llvm::initializeR600ExpandSpecialInstrsPassPass(), llvm::initializeR600PacketizerPass(), llvm::initializeR600VectorRegMergerPass(), llvm::initializeSIAnnotateControlFlowPass(), llvm::initializeSIFixSGPRCopiesPass(), llvm::initializeSIFixVGPRCopiesPass(), llvm::initializeSIFoldOperandsPass(), llvm::initializeSIFormMemoryClausesPass(), llvm::initializeSIInsertHardClausesPass(), llvm::initializeSIInsertWaitcntsPass(), llvm::initializeSILateBranchLoweringPass(), llvm::initializeSILoadStoreOptimizerPass(), llvm::initializeSILowerControlFlowPass(), llvm::initializeSILowerI1CopiesPass(), llvm::initializeSILowerSGPRSpillsPass(), llvm::initializeSIMemoryLegalizerPass(), llvm::initializeSIModeRegisterPass(), llvm::initializeSIOptimizeExecMaskingPass(), llvm::initializeSIOptimizeExecMaskingPreRAPass(), llvm::initializeSIOptimizeVGPRLiveRangePass(), llvm::initializeSIPeepholeSDWAPass(), llvm::initializeSIPostRABundlerPass(), llvm::initializeSIPreAllocateWWMRegsPass(), llvm::initializeSIPreEmitPeepholePass(), llvm::initializeSIShrinkInstructionsPass(), llvm::initializeSIWholeQuadModePass(), X, and Y.
mustPreserveGV()
static bool mustPreserveGV (const GlobalValue & GV) static
Predicate for Internalize pass.
Definition at line 518 of file AMDGPUTargetMachine.cpp.
References F, llvm::AMDGPU::isEntryFunctionCC(), llvm::Constant::removeDeadConstantUsers(), and llvm::Value::use_empty().
Referenced by llvm::AMDGPUTargetMachine::adjustPassManager(), and llvm::AMDGPUTargetMachine::registerPassBuilderCallbacks().
Variable Documentation
EarlyInlineAll
cl::opt<bool> EarlyInlineAll("amdgpu-early-inline-all", cl::desc("Inline all functions early"), cl::init(false), cl::Hidden) ("amdgpu-early-inline-all" , cl::desc("Inline all functions early") , cl::init(false) , cl::Hidden) static
Referenced by llvm::AMDGPUTargetMachine::adjustPassManager(), and llvm::AMDGPUTargetMachine::registerPassBuilderCallbacks().
EnableAMDGPUAliasAnalysis
cl::opt<bool> EnableAMDGPUAliasAnalysis("enable-amdgpu-aa", cl::Hidden, cl::desc("Enable AMDGPU Alias Analysis"), cl::init(true)) ("enable-amdgpu-aa" , cl::Hidden , cl::desc("Enable AMDGPU Alias Analysis") , cl::init(true)) static
Referenced by llvm::AMDGPUPassConfig::addIRPasses(), and llvm::AMDGPUTargetMachine::adjustPassManager().
EnableAtomicOptimizations
cl::opt<bool> EnableAtomicOptimizations("amdgpu-atomic-optimizations", cl::desc("Enable atomic optimizations"), cl::init(false), cl::Hidden) ("amdgpu-atomic-optimizations" , cl::desc("Enable atomic optimizations") , cl::init(false) , cl::Hidden) static
EnableDCEInRA
cl::opt<bool> EnableDCEInRA("amdgpu-dce-in-ra", cl::init(true), cl::Hidden, cl::desc("Enable machine DCE inside regalloc")) ("amdgpu-dce-in-ra" , cl::init(true) , cl::Hidden , cl::desc("Enable machine DCE inside regalloc")) static
EnableDPPCombine
cl::opt<bool> EnableDPPCombine("amdgpu-dpp-combine", cl::desc("Enable DPP combiner"), cl::init(true)) ("amdgpu-dpp-combine" , cl::desc("Enable DPP combiner") , cl::init(true)) static
EnableEarlyIfConversion
cl::opt<bool> EnableEarlyIfConversion("amdgpu-early-ifcvt", cl::Hidden, cl::desc("Run early if-conversion"), cl::init(false)) ("amdgpu-early-ifcvt" , cl::Hidden , cl::desc("Run early if-conversion") , cl::init(false)) static
EnableLDSReplaceWithPointer
cl::opt<bool> EnableLDSReplaceWithPointer("amdgpu-enable-lds-replace-with-pointer", cl::desc("Enable LDS replace with pointer pass"), cl::init(false), cl::Hidden) ("amdgpu-enable-lds-replace-with-pointer" , cl::desc("Enable LDS replace with pointer pass") , cl::init(false) , cl::Hidden) static
Referenced by llvm::AMDGPUPassConfig::addIRPasses().
EnableLibCallSimplify
cl::opt<bool> EnableLibCallSimplify("amdgpu-simplify-libcall", cl::desc("Enable amdgpu library simplifications"), cl::init(true), cl::Hidden) ("amdgpu-simplify-libcall" , cl::desc("Enable amdgpu library simplifications") , cl::init(true) , cl::Hidden) static
Referenced by llvm::AMDGPUTargetMachine::adjustPassManager(), and llvm::AMDGPUTargetMachine::registerPassBuilderCallbacks().
EnableLoadStoreVectorizer
cl::opt<bool> EnableLoadStoreVectorizer("amdgpu-load-store-vectorizer", cl::desc("Enable load store vectorizer"), cl::init(true), cl::Hidden) ("amdgpu-load-store-vectorizer" , cl::desc("Enable load store vectorizer") , cl::init(true) , cl::Hidden) static
Referenced by llvm::AMDGPUPassConfig::addCodeGenPrepare().
EnableLowerKernelArguments
cl::opt<bool> EnableLowerKernelArguments("amdgpu-ir-lower-kernel-arguments", cl::desc("Lower kernel argument loads in IR pass"), cl::init(true), cl::Hidden) ("amdgpu-ir-lower-kernel-arguments" , cl::desc("Lower kernel argument loads in IR pass") , cl::init(true) , cl::Hidden) static
Referenced by llvm::AMDGPUPassConfig::addCodeGenPrepare().
EnableLowerModuleLDS
cl::opt<bool, true> EnableLowerModuleLDS("amdgpu-enable-lower-module-lds", cl::desc("Enable lower module lds pass"), cl::location(AMDGPUTargetMachine::EnableLowerModuleLDS), cl::init(true), cl::Hidden) ("amdgpu-enable-lower-module-lds" , cl::desc("Enable lower module lds pass") , cl::location(AMDGPUTargetMachine::EnableLowerModuleLDS) , cl::init(true) , cl::Hidden) static
Referenced by llvm::AMDGPUPassConfig::addIRPasses().
EnablePreRAOptimizations
cl::opt<bool> EnablePreRAOptimizations("amdgpu-enable-pre-ra-optimizations", cl::desc("Enable Pre-RA optimizations pass"), cl::init(true), cl::Hidden) ("amdgpu-enable-pre-ra-optimizations" , cl::desc("Enable Pre-RA optimizations pass") , cl::init(true) , cl::Hidden) static
EnablePromoteKernelArguments
cl::opt<bool> EnablePromoteKernelArguments("amdgpu-enable-promote-kernel-arguments", cl::desc("Enable promotion of flat kernel pointer arguments to global"), cl::Hidden, cl::init(true)) ("amdgpu-enable-promote-kernel-arguments" , cl::desc("Enable promotion of flat kernel pointer arguments to global") , cl::Hidden , cl::init(true)) static
Referenced by llvm::AMDGPUTargetMachine::adjustPassManager(), and llvm::AMDGPUTargetMachine::registerPassBuilderCallbacks().
EnableRegReassign
cl::opt<bool> EnableRegReassign("amdgpu-reassign-regs", cl::desc("Enable register reassign optimizations on gfx10+"), cl::init(true), cl::Hidden) ("amdgpu-reassign-regs" , cl::desc("Enable register reassign optimizations on gfx10+") , cl::init(true) , cl::Hidden) static
EnableScalarIRPasses
cl::opt<bool> EnableScalarIRPasses("amdgpu-scalar-ir-passes", cl::desc("Enable scalar IR passes"), cl::init(true), cl::Hidden) ("amdgpu-scalar-ir-passes" , cl::desc("Enable scalar IR passes") , cl::init(true) , cl::Hidden) static
Referenced by llvm::AMDGPUPassConfig::addIRPasses().
EnableSDWAPeephole
cl::opt<bool> EnableSDWAPeephole("amdgpu-sdwa-peephole", cl::desc("Enable SDWA peepholer"), cl::init(true)) ("amdgpu-sdwa-peephole" , cl::desc("Enable SDWA peepholer") , cl::init(true)) static
EnableSIModeRegisterPass
cl::opt<bool> EnableSIModeRegisterPass("amdgpu-mode-register", cl::desc("Enable mode register pass"), cl::init(true), cl::Hidden) ("amdgpu-mode-register" , cl::desc("Enable mode register pass") , cl::init(true) , cl::Hidden) static
EnableSROA
cl::opt<bool> EnableSROA("amdgpu-sroa", cl::desc("Run SROA after promote alloca pass"), cl::ReallyHidden, cl::init(true)) ("amdgpu-sroa" , cl::desc("Run SROA after promote alloca pass") , cl::ReallyHidden , cl::init(true)) static
Referenced by llvm::AMDGPUPassConfig::addIRPasses().
EnableStructurizerWorkarounds
cl::opt<bool> EnableStructurizerWorkarounds("amdgpu-enable-structurizer-workarounds", cl::desc("Enable workarounds for the StructurizeCFG pass"), cl::init(true), cl::Hidden) ("amdgpu-enable-structurizer-workarounds" , cl::desc("Enable workarounds for the StructurizeCFG pass") , cl::init(true) , cl::Hidden) static
GCNILPSchedRegistry
MachineSchedRegistry GCNILPSchedRegistry("gcn-ilp", "Run GCN iterative scheduler for ILP scheduling (experimental)", createIterativeILPMachineScheduler) ("gcn-ilp" , "Run GCN iterative scheduler for ILP scheduling (experimental)" , createIterativeILPMachineScheduler) static
GCNMaxOccupancySchedRegistry
MachineSchedRegistry GCNMaxOccupancySchedRegistry("gcn-max-occupancy", "Run GCN scheduler to maximize occupancy", createGCNMaxOccupancyMachineScheduler) ("gcn-max-occupancy" , "Run GCN scheduler to maximize occupancy" , createGCNMaxOccupancyMachineScheduler) static
GCNMinRegSchedRegistry
MachineSchedRegistry GCNMinRegSchedRegistry("gcn-minreg", "Run GCN iterative scheduler for minimal register usage (experimental)", createMinRegScheduler) ("gcn-minreg" , "Run GCN iterative scheduler for minimal register usage (experimental)" , createMinRegScheduler) static
InternalizeSymbols
cl::opt<bool> InternalizeSymbols("amdgpu-internalize-symbols", cl::desc("Enable elimination of non-kernel functions and unused globals"), cl::init(false), cl::Hidden) ("amdgpu-internalize-symbols" , cl::desc("Enable elimination of non-kernel functions and unused globals") , cl::init(false) , cl::Hidden) static
Referenced by llvm::AMDGPUTargetMachine::adjustPassManager(), and llvm::AMDGPUTargetMachine::registerPassBuilderCallbacks().
IterativeGCNMaxOccupancySchedRegistry
MachineSchedRegistry IterativeGCNMaxOccupancySchedRegistry("gcn-max-occupancy-experimental", "Run GCN scheduler to maximize occupancy (experimental)", createIterativeGCNMaxOccupancyMachineScheduler) ("gcn-max-occupancy-experimental" , "Run GCN scheduler to maximize occupancy (experimental)" , createIterativeGCNMaxOccupancyMachineScheduler) static
LateCFGStructurize
cl::opt<bool, true> LateCFGStructurize("amdgpu-late-structurize", cl::desc("Enable late CFG structurization"), cl::location(AMDGPUTargetMachine::EnableLateStructurizeCFG), cl::Hidden) ("amdgpu-late-structurize" , cl::desc("Enable late CFG structurization") , cl::location(AMDGPUTargetMachine::EnableLateStructurizeCFG) , cl::Hidden) static
OptExecMaskPreRA
cl::opt<bool> OptExecMaskPreRA("amdgpu-opt-exec-mask-pre-ra", cl::Hidden, cl::desc("Run pre-RA exec mask optimizations"), cl::init(true)) ("amdgpu-opt-exec-mask-pre-ra" , cl::Hidden , cl::desc("Run pre-RA exec mask optimizations") , cl::init(true)) static
OptVGPRLiveRange
cl::opt<bool> OptVGPRLiveRange("amdgpu-opt-vgpr-liverange", cl::desc("Enable VGPR liverange optimizations for if-else structure"), cl::init(true), cl::Hidden) ("amdgpu-opt-vgpr-liverange" , cl::desc("Enable VGPR liverange optimizations for if-else structure") , cl::init(true) , cl::Hidden) static
RegAllocOptNotSupportedMessage
const char RegAllocOptNotSupportedMessage[] static
Initial value:
=
  "-regalloc not supported with amdgcn. Use -sgpr-regalloc and -vgpr-regalloc"
Definition at line 1304 of file AMDGPUTargetMachine.cpp.
ScalarizeGlobal
cl::opt<bool> ScalarizeGlobal("amdgpu-scalarize-global-loads", cl::desc("Enable global load scalarization"), cl::init(true), cl::Hidden) ("amdgpu-scalarize-global-loads" , cl::desc("Enable global load scalarization") , cl::init(true) , cl::Hidden) static
Referenced by llvm::GCNTargetMachine::getSubtargetImpl().
SISchedRegistry
MachineSchedRegistry SISchedRegistry("si", "Run SI's custom scheduler", createSIMachineScheduler) ("si" , "Run SI's custom scheduler" , createSIMachineScheduler) static