LLVM: lib/Target/AMDGPU/AMDGPULibFunc.cpp File Reference
AMDGPULibFunc.cpp File Reference
#include "AMDGPULibFunc.h"
#include "AMDGPU.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ValueSymbolTable.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/raw_ostream.h"
Functions
static int parseVecSize (StringRef &mangledName)
static AMDGPULibFunc::ENamePrefix parseNamePrefix (StringRef &mangledName)
static const char * getItaniumTypeName (AMDGPULibFunc::EType T)
static Type * getIntrinsicParamType (LLVMContext &C, const AMDGPULibFunc::Param &P, bool useAddrSpace)
Variables
static cl::opt< bool > EnableOCLManglingMismatchWA ("amdgpu-enable-ocl-mangling-mismatch-workaround", cl::init(true), cl::ReallyHidden, cl::desc("Enable the workaround for OCL name mangling mismatch."))
Function Documentation
getIntrinsicParamType()
static Type* getIntrinsicParamType (LLVMContext & C, const AMDGPULibFunc::Param & P, bool useAddrSpace) static
Definition at line 877 of file AMDGPULibFunc.cpp.
References llvm::AMDGPULibFuncBase::ADDR_SPACE, llvm::AMDGPULibFuncBase::BYVALUE, C, llvm::StructType::create(), llvm::AMDGPULibFuncBase::EVENT, llvm::AMDGPULibFuncBase::F16, llvm::AMDGPULibFuncBase::F32, llvm::AMDGPULibFuncBase::F64, llvm::FixedVectorType::get(), llvm::Type::getDoubleTy(), llvm::Type::getFloatTy(), llvm::Type::getHalfTy(), llvm::Type::getInt16Ty(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::Type::getInt8Ty(), llvm::Type::getPointerTo(), llvm::AMDGPULibFuncBase::I16, llvm::AMDGPULibFuncBase::I32, llvm::AMDGPULibFuncBase::I64, llvm::AMDGPULibFuncBase::I8, llvm::AMDGPULibFuncBase::IMG1D, llvm::AMDGPULibFuncBase::IMG1DA, llvm::AMDGPULibFuncBase::IMG1DB, llvm::AMDGPULibFuncBase::IMG2D, llvm::AMDGPULibFuncBase::IMG2DA, llvm::AMDGPULibFuncBase::IMG3D, llvm_unreachable, P, llvm::AMDGPULibFuncBase::SAMPLER, T, llvm::AMDGPULibFuncBase::U16, llvm::AMDGPULibFuncBase::U32, llvm::AMDGPULibFuncBase::U64, and llvm::AMDGPULibFuncBase::U8.
Referenced by llvm::AMDGPUMangledLibFunc::getFunctionType().
getItaniumTypeName()
static const char* getItaniumTypeName (AMDGPULibFunc::EType T) static
Definition at line 730 of file AMDGPULibFunc.cpp.
References llvm::AMDGPULibFuncBase::EVENT, llvm::AMDGPULibFuncBase::F16, llvm::AMDGPULibFuncBase::F32, llvm::AMDGPULibFuncBase::F64, llvm::AMDGPULibFuncBase::I16, llvm::AMDGPULibFuncBase::I32, llvm::AMDGPULibFuncBase::I64, llvm::AMDGPULibFuncBase::I8, llvm::AMDGPULibFuncBase::IMG1D, llvm::AMDGPULibFuncBase::IMG1DA, llvm::AMDGPULibFuncBase::IMG1DB, llvm::AMDGPULibFuncBase::IMG2D, llvm::AMDGPULibFuncBase::IMG2DA, llvm::AMDGPULibFuncBase::IMG3D, llvm_unreachable, llvm::AMDGPULibFuncBase::SAMPLER, T, llvm::AMDGPULibFuncBase::U16, llvm::AMDGPULibFuncBase::U32, llvm::AMDGPULibFuncBase::U64, and llvm::AMDGPULibFuncBase::U8.
parseNamePrefix()
static AMDGPULibFunc::ENamePrefix parseNamePrefix (StringRef & mangledName) static
Definition at line 543 of file AMDGPULibFunc.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), llvm::AMDGPULibFuncBase::HALF, llvm::AMDGPULibFuncBase::NATIVE, llvm::AMDGPULibFuncBase::NOPFX, P, and llvm::StringRef::split().
Referenced by llvm::AMDGPUMangledLibFunc::parseFuncName().
parseVecSize()
static int parseVecSize (StringRef & mangledName) static
Definition at line 532 of file AMDGPULibFunc.cpp.
Variable Documentation
EnableOCLManglingMismatchWA
cl::opt<bool> EnableOCLManglingMismatchWA("amdgpu-enable-ocl-mangling-mismatch-workaround", cl::init(true), cl::ReallyHidden, cl::desc("Enable the workaround for OCL name mangling mismatch.")) ("amdgpu-enable-ocl-mangling-mismatch-workaround" , cl::init(true) , cl::ReallyHidden , cl::desc("Enable the workaround for OCL name mangling mismatch.")) static