LLVM: lib/Target/ARC/Disassembler/ARCDisassembler.cpp File Reference
ARCDisassembler.cpp File Reference
This file is part of the ARC Disassembler.
#include "ARC.h"
#include "ARCRegisterInfo.h"
#include "MCTargetDesc/ARCMCTargetDesc.h"
#include "TargetInfo/ARCTargetInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDisassembler/MCDisassembler.h"
#include "llvm/MC/MCFixedLenDisassembler.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "ARCGenDisassemblerTables.inc"
Macros
#define DEBUG_TYPE "arc-disassembler"
Typedefs
using DecodeStatus = MCDisassembler::DecodeStatus
Functions
static bool readInstruction32 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t &Size, uint32_t &Insn)
static bool readInstruction64 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t &Size, uint64_t &Insn)
static bool readInstruction48 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t &Size, uint64_t &Insn)
static bool readInstruction16 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t &Size, uint32_t &Insn)
template<unsigned B>
static DecodeStatus DecodeSignedOperand (MCInst &Inst, unsigned InsnS, uint64_t Address=0, const void *Decoder=nullptr)
template<unsigned B>
static DecodeStatus DecodeFromCyclicRange (MCInst &Inst, unsigned InsnS, uint64_t Address=0, const void *Decoder=nullptr)
template<unsigned B>
static DecodeStatus DecodeBranchTargetS (MCInst &Inst, unsigned InsnS, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMEMrs9 (MCInst &, unsigned, uint64_t, const void *)
static DecodeStatus DecodeLdLImmInstruction (MCInst &, uint64_t, uint64_t, const void *)
static DecodeStatus DecodeStLImmInstruction (MCInst &, uint64_t, uint64_t, const void *)
static DecodeStatus DecodeLdRLImmInstruction (MCInst &, uint64_t, uint64_t, const void *)
static DecodeStatus DecodeSOPwithRS12 (MCInst &, uint64_t, uint64_t, const void *)
static DecodeStatus DecodeSOPwithRU6 (MCInst &, uint64_t, uint64_t, const void *)
static DecodeStatus DecodeCCRU6Instruction (MCInst &, uint64_t, uint64_t, const void *)
static DecodeStatus DecodeMoveHRegInstruction (MCInst &Inst, uint64_t, uint64_t, const void *)
static DecodeStatus DecodeGPR32RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeGBR32ShortRegister (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static unsigned decodeCField (unsigned Insn)
static unsigned decodeBField (unsigned Insn)
static unsigned decodeAField (unsigned Insn)
static bool DecodeSymbolicOperand (MCInst &Inst, uint64_t Address, uint64_t Value, const void *Decoder)
static void DecodeSymbolicOperandOff (MCInst &Inst, uint64_t Address, uint64_t Offset, const void *Decoder)
static MCDisassembler * createARCDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeARCDisassembler ()
Variables
static const uint16_t GPR32DecoderTable []
Detailed Description
This file is part of the ARC Disassembler.
Definition in file ARCDisassembler.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "arc-disassembler"
Definition at line 28 of file ARCDisassembler.cpp.
Typedef Documentation
DecodeStatus
using DecodeStatus = MCDisassembler::DecodeStatus
Definition at line 30 of file ARCDisassembler.cpp.
Function Documentation
createARCDisassembler()
static MCDisassembler* createARCDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 407 of file ARCDisassembler.cpp.
References T.
Referenced by LLVMInitializeARCDisassembler().
decodeAField()
static unsigned decodeAField (unsigned Insn) static
Definition at line 163 of file ARCDisassembler.cpp.
References Insn.
Referenced by DecodeLdLImmInstruction(), and DecodeLdRLImmInstruction().
decodeBField()
static unsigned decodeBField (unsigned Insn) static
Definition at line 158 of file ARCDisassembler.cpp.
References Insn.
Referenced by DecodeCCRU6Instruction(), DecodeLdLImmInstruction(), DecodeLdRLImmInstruction(), DecodeSOPwithRS12(), DecodeSOPwithRU6(), and DecodeStLImmInstruction().
DecodeBranchTargetS()
template<unsigned B> static DecodeStatus DecodeBranchTargetS (MCInst & Inst, unsigned InsnS, uint64_t Address, const void * Decoder) static
Definition at line 196 of file ARCDisassembler.cpp.
References llvm::Address, B, DecodeSymbolicOperandOff(), and llvm::MCDisassembler::Success.
DecodeCCRU6Instruction()
static DecodeStatus DecodeCCRU6Instruction (MCInst & Inst, uint64_t Insn, uint64_t Address, const void * Decoder) static
Definition at line 305 of file ARCDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::Address, llvm::MCOperand::createImm(), llvm::dbgs(), decodeBField(), DecodeGPR32RegisterClass(), Insn, LLVM_DEBUG, and llvm::MCDisassembler::Success.
decodeCField()
static unsigned decodeCField (unsigned Insn) static
Definition at line 154 of file ARCDisassembler.cpp.
References Insn.
Referenced by DecodeLdRLImmInstruction(), and DecodeStLImmInstruction().
DecodeFromCyclicRange()
template<unsigned B> static DecodeStatus DecodeFromCyclicRange (MCInst & Inst, unsigned InsnS, uint64_t Address = 0, const void * Decoder = nullptr) static
Definition at line 216 of file ARCDisassembler.cpp.
References llvm::MCInst::addOperand(), B, llvm::MCOperand::createImm(), llvm::max(), and llvm::MCDisassembler::Success.
DecodeGBR32ShortRegister()
static DecodeStatus DecodeGBR32ShortRegister (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 142 of file ARCDisassembler.cpp.
References llvm::Address, and DecodeGPR32RegisterClass().
DecodeGPR32RegisterClass()
static DecodeStatus DecodeGPR32RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 129 of file ARCDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::dbgs(), llvm::MCDisassembler::Fail, GPR32DecoderTable, LLVM_DEBUG, and llvm::MCDisassembler::Success.
Referenced by DecodeCCRU6Instruction(), DecodeGBR32ShortRegister(), DecodeLdLImmInstruction(), DecodeLdRLImmInstruction(), DecodeMEMrs9(), DecodeMoveHRegInstruction(), DecodeSOPwithRS12(), DecodeSOPwithRU6(), and DecodeStLImmInstruction().
DecodeLdLImmInstruction()
static DecodeStatus DecodeLdLImmInstruction (MCInst & Inst, uint64_t Insn, uint64_t Address, const void * Decoder) static
Definition at line 244 of file ARCDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::Address, llvm::MCOperand::createImm(), llvm::dbgs(), decodeAField(), decodeBField(), DecodeGPR32RegisterClass(), llvm::MCDisassembler::Fail, Insn, LLVM_DEBUG, and llvm::MCDisassembler::Success.
DecodeLdRLImmInstruction()
static DecodeStatus DecodeLdRLImmInstruction (MCInst & Inst, uint64_t Insn, uint64_t Address, const void * Decoder) static
Definition at line 262 of file ARCDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::Address, llvm::MCOperand::createImm(), llvm::dbgs(), decodeAField(), decodeBField(), decodeCField(), DecodeGPR32RegisterClass(), llvm::MCDisassembler::Fail, Insn, LLVM_DEBUG, and llvm::MCDisassembler::Success.
DecodeMEMrs9()
static DecodeStatus DecodeMEMrs9 (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Dec) static
Definition at line 167 of file ARCDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::Address, llvm::MCOperand::createImm(), DecodeGPR32RegisterClass(), Insn, and llvm::MCDisassembler::Success.
DecodeMoveHRegInstruction()
static DecodeStatus DecodeMoveHRegInstruction (MCInst & Inst, uint64_t Insn, uint64_t Address, const void * Decoder) static
Definition at line 279 of file ARCDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::Address, llvm::MCOperand::createImm(), llvm::dbgs(), DecodeGPR32RegisterClass(), llvm::MCDisassembler::Fail, G, H, Insn, LLVM_DEBUG, and llvm::MCDisassembler::Success.
DecodeSignedOperand()
template<unsigned B> static DecodeStatus DecodeSignedOperand (MCInst & Inst, unsigned InsnS, uint64_t Address = 0, const void * Decoder = nullptr) static
Definition at line 205 of file ARCDisassembler.cpp.
References llvm::MCInst::addOperand(), B, llvm::MCOperand::createImm(), llvm::maskTrailingOnes(), and llvm::MCDisassembler::Success.
DecodeSOPwithRS12()
static DecodeStatus DecodeSOPwithRS12 (MCInst & Inst, uint64_t Insn, uint64_t Address, const void * Decoder) static
Definition at line 330 of file ARCDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::Address, llvm::MCOperand::createImm(), decodeBField(), DecodeGPR32RegisterClass(), Insn, llvm::MCDisassembler::Success, and llvm::Upper.
DecodeSOPwithRU6()
static DecodeStatus DecodeSOPwithRU6 (MCInst & Inst, uint64_t Insn, uint64_t Address, const void * Decoder) static
Definition at line 320 of file ARCDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::Address, llvm::MCOperand::createImm(), decodeBField(), DecodeGPR32RegisterClass(), Insn, and llvm::MCDisassembler::Success.
DecodeStLImmInstruction()
static DecodeStatus DecodeStLImmInstruction (MCInst & Inst, uint64_t Insn, uint64_t Address, const void * Decoder) static
Definition at line 227 of file ARCDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::Address, llvm::MCOperand::createImm(), llvm::dbgs(), decodeBField(), decodeCField(), DecodeGPR32RegisterClass(), llvm::MCDisassembler::Fail, Insn, LLVM_DEBUG, and llvm::MCDisassembler::Success.
DecodeSymbolicOperand()
static bool DecodeSymbolicOperand (MCInst & Inst, uint64_t Address, uint64_t Value, const void * Decoder) static
Definition at line 177 of file ARCDisassembler.cpp.
References llvm::Address.
Referenced by DecodeSymbolicOperandOff().
DecodeSymbolicOperandOff()
static void DecodeSymbolicOperandOff (MCInst & Inst, uint64_t Address, uint64_t Offset, const void * Decoder) static
Definition at line 187 of file ARCDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::Address, llvm::MCOperand::createImm(), DecodeSymbolicOperand(), and Offset.
Referenced by DecodeBranchTargetS().
LLVMInitializeARCDisassembler()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeARCDisassembler ()
Definition at line 413 of file ARCDisassembler.cpp.
References createARCDisassembler(), llvm::getTheARCTarget(), and llvm::TargetRegistry::RegisterMCDisassembler().
readInstruction16()
static bool readInstruction16 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t & Size, uint32_t & Insn) static
Definition at line 78 of file ARCDisassembler.cpp.
References Insn, and llvm::Check::Size.
readInstruction32()
static bool readInstruction32 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t & Size, uint32_t & Insn) static
Definition at line 50 of file ARCDisassembler.cpp.
References Insn, and llvm::Check::Size.
readInstruction48()
static bool readInstruction48 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t & Size, uint64_t & Insn) static
Definition at line 69 of file ARCDisassembler.cpp.
References Insn, and llvm::Check::Size.
readInstruction64()
static bool readInstruction64 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t & Size, uint64_t & Insn) static
Definition at line 59 of file ARCDisassembler.cpp.
References Insn, and llvm::Check::Size.
Variable Documentation
GPR32DecoderTable
const uint16_t GPR32DecoderTable[] static
Initial value:
= {
    ARC::R0,  ARC::R1,    ARC::R2,  ARC::R3,   ARC::R4,  ARC::R5,  ARC::R6,
    ARC::R7,  ARC::R8,    ARC::R9,  ARC::R10,  ARC::R11, ARC::R12, ARC::R13,
    ARC::R14, ARC::R15,   ARC::R16, ARC::R17,  ARC::R18, ARC::R19, ARC::R20,
    ARC::R21, ARC::R22,   ARC::R23, ARC::R24,  ARC::R25, ARC::GP,  ARC::FP,
    ARC::SP,  ARC::ILINK, ARC::R30, ARC::BLINK}
Definition at line 122 of file ARCDisassembler.cpp.
Referenced by DecodeGPR32RegisterClass().