LLVM: lib/Target/ARM/MCTargetDesc/ARMMCTargetDesc.cpp File Reference
ARMMCTargetDesc.cpp File Reference
#include "ARMMCTargetDesc.h"
#include "ARMAddressingModes.h"
#include "ARMBaseInfo.h"
#include "ARMInstPrinter.h"
#include "ARMMCAsmInfo.h"
#include "TargetInfo/ARMTargetInfo.h"
#include "llvm/ADT/Triple.h"
#include "llvm/DebugInfo/CodeView/CodeView.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCELFStreamer.h"
#include "llvm/MC/MCInstrAnalysis.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/TargetParser.h"
#include "ARMGenRegisterInfo.inc"
#include "ARMGenInstrInfo.inc"
#include "ARMGenSubtargetInfo.inc"
Macros
#define GET_REGINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Functions
static bool getMCRDeprecationInfo (MCInst &MI, const MCSubtargetInfo &STI, std::string &Info)
static bool getMRCDeprecationInfo (MCInst &MI, const MCSubtargetInfo &STI, std::string &Info)
static bool getITDeprecationInfo (MCInst &MI, const MCSubtargetInfo &STI, std::string &Info)
static bool getARMStoreDeprecationInfo (MCInst &MI, const MCSubtargetInfo &STI, std::string &Info)
static bool getARMLoadDeprecationInfo (MCInst &MI, const MCSubtargetInfo &STI, std::string &Info)
static MCInstrInfo * createARMMCInstrInfo ()
static MCRegisterInfo * createARMMCRegisterInfo (const Triple &Triple)
static MCAsmInfo * createARMMCAsmInfo (const MCRegisterInfo &MRI, const Triple &TheTriple, const MCTargetOptions &Options)
static MCStreamer * createELFStreamer (const Triple &T, MCContext &Ctx, std::unique_ptr< MCAsmBackend > &&MAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, bool RelaxAll)
static MCStreamer * createARMMachOStreamer (MCContext &Ctx, std::unique_ptr< MCAsmBackend > &&MAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, bool RelaxAll, bool DWARFMustBeAtTheEnd)
static MCInstPrinter * createARMMCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
static MCRelocationInfo * createARMMCRelocationInfo (const Triple &TT, MCContext &Ctx)
static Optional< uint64_t > evaluateMemOpAddrForAddrMode_i12 (const MCInst &Inst, const MCInstrDesc &Desc, unsigned MemOpIndex, uint64_t Addr)
static Optional< uint64_t > evaluateMemOpAddrForAddrMode3 (const MCInst &Inst, const MCInstrDesc &Desc, unsigned MemOpIndex, uint64_t Addr)
static Optional< uint64_t > evaluateMemOpAddrForAddrMode5 (const MCInst &Inst, const MCInstrDesc &Desc, unsigned MemOpIndex, uint64_t Addr)
static Optional< uint64_t > evaluateMemOpAddrForAddrMode5FP16 (const MCInst &Inst, const MCInstrDesc &Desc, unsigned MemOpIndex, uint64_t Addr)
static Optional< uint64_t > evaluateMemOpAddrForAddrModeT2_i8s4 (const MCInst &Inst, const MCInstrDesc &Desc, unsigned MemOpIndex, uint64_t Addr)
static Optional< uint64_t > evaluateMemOpAddrForAddrModeT2_pc (const MCInst &Inst, const MCInstrDesc &Desc, unsigned MemOpIndex, uint64_t Addr)
static Optional< uint64_t > evaluateMemOpAddrForAddrModeT1_s (const MCInst &Inst, const MCInstrDesc &Desc, unsigned MemOpIndex, uint64_t Addr)
static MCInstrAnalysis * createARMMCInstrAnalysis (const MCInstrInfo *Info)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeARMTargetMC ()
Macro Definition Documentation
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 147 of file ARMMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 36 of file ARMMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 150 of file ARMMCTargetDesc.cpp.
Function Documentation
createARMMachOStreamer()
static MCStreamer* createARMMachOStreamer (MCContext & Ctx, std::unique_ptr< MCAsmBackend > && MAB, std::unique_ptr< MCObjectWriter > && OW, std::unique_ptr< MCCodeEmitter > && Emitter, bool RelaxAll, bool DWARFMustBeAtTheEnd) static
Definition at line 383 of file ARMMCTargetDesc.cpp.
References llvm::createMachOStreamer(), and llvm::move().
Referenced by LLVMInitializeARMTargetMC().
createARMMCAsmInfo()
static MCAsmInfo* createARMMCAsmInfo (const MCRegisterInfo & MRI, const Triple & TheTriple, const MCTargetOptions & Options) static
Definition at line 352 of file ARMMCTargetDesc.cpp.
References llvm::MCAsmInfo::addInitialFrameState(), llvm::MCCFIInstruction::cfiDefCfa(), llvm::Triple::isOSBinFormatMachO(), llvm::Triple::isOSDarwin(), llvm::Triple::isOSWindows(), llvm::Triple::isWindowsMSVCEnvironment(), and MRI.
Referenced by LLVMInitializeARMTargetMC().
createARMMCInstPrinter()
static MCInstPrinter* createARMMCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 391 of file ARMMCTargetDesc.cpp.
References MRI.
Referenced by LLVMInitializeARMTargetMC().
createARMMCInstrAnalysis()
static MCInstrAnalysis* createARMMCInstrAnalysis (const MCInstrInfo * Info) static
Definition at line 641 of file ARMMCTargetDesc.cpp.
References Info.
Referenced by LLVMInitializeARMTargetMC().
createARMMCInstrInfo()
static MCInstrInfo* createARMMCInstrInfo () static
Definition at line 229 of file ARMMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeARMTargetMC().
createARMMCRegisterInfo()
static MCRegisterInfo* createARMMCRegisterInfo (const Triple & Triple) static
Definition at line 345 of file ARMMCTargetDesc.cpp.
References llvm::ARM_MC::initLLVMToCVRegMapping(), and X.
Referenced by LLVMInitializeARMTargetMC().
createARMMCRelocationInfo()
static MCRelocationInfo* createARMMCRelocationInfo (const Triple & TT, MCContext & Ctx) static
Definition at line 401 of file ARMMCTargetDesc.cpp.
References llvm::createARMMachORelocationInfo(), and llvm::createMCRelocationInfo().
Referenced by LLVMInitializeARMTargetMC().
createELFStreamer()
static MCStreamer* createELFStreamer (const Triple & T, MCContext & Ctx, std::unique_ptr< MCAsmBackend > && MAB, std::unique_ptr< MCObjectWriter > && OW, std::unique_ptr< MCCodeEmitter > && Emitter, bool RelaxAll) static
Definition at line 371 of file ARMMCTargetDesc.cpp.
References llvm::createARMELFStreamer(), llvm::move(), T, llvm::Triple::thumb, and llvm::Triple::thumbeb.
evaluateMemOpAddrForAddrMode3()
static Optional<uint64_t> evaluateMemOpAddrForAddrMode3 (const MCInst & Inst, const MCInstrDesc & Desc, unsigned MemOpIndex, uint64_t Addr) static
Definition at line 472 of file ARMMCTargetDesc.cpp.
References Addr, llvm::ARM_AM::getAM3Offset(), llvm::ARM_AM::getAM3Op(), llvm::MCOperand::getImm(), llvm::MCInstrDesc::getNumOperands(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm::None, and llvm::ARM_AM::sub.
evaluateMemOpAddrForAddrMode5()
static Optional<uint64_t> evaluateMemOpAddrForAddrMode5 (const MCInst & Inst, const MCInstrDesc & Desc, unsigned MemOpIndex, uint64_t Addr) static
Definition at line 493 of file ARMMCTargetDesc.cpp.
References Addr, llvm::ARM_AM::getAM5Offset(), llvm::ARM_AM::getAM5Op(), llvm::MCOperand::getImm(), llvm::MCInstrDesc::getNumOperands(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm::None, and llvm::ARM_AM::sub.
evaluateMemOpAddrForAddrMode5FP16()
static Optional<uint64_t> evaluateMemOpAddrForAddrMode5FP16 (const MCInst & Inst, const MCInstrDesc & Desc, unsigned MemOpIndex, uint64_t Addr) static
Definition at line 514 of file ARMMCTargetDesc.cpp.
References Addr, llvm::ARM_AM::getAM5FP16Offset(), llvm::ARM_AM::getAM5FP16Op(), llvm::MCOperand::getImm(), llvm::MCInstrDesc::getNumOperands(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm::None, and llvm::ARM_AM::sub.
evaluateMemOpAddrForAddrMode_i12()
static Optional<uint64_t> evaluateMemOpAddrForAddrMode_i12 (const MCInst & Inst, const MCInstrDesc & Desc, unsigned MemOpIndex, uint64_t Addr) static
Definition at line 455 of file ARMMCTargetDesc.cpp.
References Addr, llvm::MCOperand::getImm(), llvm::MCInstrDesc::getNumOperands(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and llvm::None.
evaluateMemOpAddrForAddrModeT1_s()
static Optional<uint64_t> evaluateMemOpAddrForAddrModeT1_s (const MCInst & Inst, const MCInstrDesc & Desc, unsigned MemOpIndex, uint64_t Addr) static
Definition at line 571 of file ARMMCTargetDesc.cpp.
References Addr, and evaluateMemOpAddrForAddrModeT2_pc().
evaluateMemOpAddrForAddrModeT2_i8s4()
static Optional<uint64_t> evaluateMemOpAddrForAddrModeT2_i8s4 (const MCInst & Inst, const MCInstrDesc & Desc, unsigned MemOpIndex, uint64_t Addr) static
Definition at line 534 of file ARMMCTargetDesc.cpp.
References Addr, assert(), llvm::MCOperand::getImm(), llvm::MCInstrDesc::getNumOperands(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and llvm::None.
evaluateMemOpAddrForAddrModeT2_pc()
static Optional<uint64_t> evaluateMemOpAddrForAddrModeT2_pc (const MCInst & Inst, const MCInstrDesc & Desc, unsigned MemOpIndex, uint64_t Addr) static
Definition at line 555 of file ARMMCTargetDesc.cpp.
References Addr, llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isImm(), and llvm::None.
Referenced by evaluateMemOpAddrForAddrModeT1_s().
getARMLoadDeprecationInfo()
static bool getARMLoadDeprecationInfo (MCInst & MI, const MCSubtargetInfo & STI, std::string & Info) static
Definition at line 118 of file ARMMCTargetDesc.cpp.
References assert(), llvm::MCSubtargetInfo::getFeatureBits(), Info, and MI.
getARMStoreDeprecationInfo()
static bool getARMStoreDeprecationInfo (MCInst & MI, const MCSubtargetInfo & STI, std::string & Info) static
Definition at line 102 of file ARMMCTargetDesc.cpp.
References assert(), llvm::MCSubtargetInfo::getFeatureBits(), Info, and MI.
getITDeprecationInfo()
static bool getITDeprecationInfo (MCInst & MI, const MCSubtargetInfo & STI, std::string & Info) static
Definition at line 90 of file ARMMCTargetDesc.cpp.
References llvm::MCSubtargetInfo::getFeatureBits(), Info, and MI.
getMCRDeprecationInfo()
static bool getMCRDeprecationInfo (MCInst & MI, const MCSubtargetInfo & STI, std::string & Info) static
Definition at line 39 of file ARMMCTargetDesc.cpp.
References llvm::MCSubtargetInfo::getFeatureBits(), Info, and MI.
getMRCDeprecationInfo()
static bool getMRCDeprecationInfo (MCInst & MI, const MCSubtargetInfo & STI, std::string & Info) static
Definition at line 78 of file ARMMCTargetDesc.cpp.
References llvm::MCSubtargetInfo::getFeatureBits(), Info, and MI.
LLVMInitializeARMTargetMC()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeARMTargetMC ()
Definition at line 654 of file ARMMCTargetDesc.cpp.
References llvm::createARMBEAsmBackend(), llvm::createARMBEMCCodeEmitter(), llvm::createARMLEAsmBackend(), llvm::createARMLEMCCodeEmitter(), createARMMachOStreamer(), createARMMCAsmInfo(), createARMMCInstPrinter(), createARMMCInstrAnalysis(), createARMMCInstrInfo(), createARMMCRegisterInfo(), createARMMCRelocationInfo(), llvm::ARM_MC::createARMMCSubtargetInfo(), llvm::createARMNullTargetStreamer(), llvm::createARMObjectTargetStreamer(), llvm::createARMTargetAsmStreamer(), llvm::createARMWinCOFFStreamer(), llvm::createELFStreamer(), llvm::getTheARMBETarget(), llvm::getTheARMLETarget(), llvm::getTheThumbBETarget(), llvm::getTheThumbLETarget(), llvm::TargetRegistry::RegisterAsmTargetStreamer(), llvm::TargetRegistry::RegisterCOFFStreamer(), llvm::TargetRegistry::RegisterELFStreamer(), llvm::TargetRegistry::RegisterMachOStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrAnalysis(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCRelocationInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TargetRegistry::RegisterNullTargetStreamer(), llvm::TargetRegistry::RegisterObjectTargetStreamer(), T, and X.