LLVM: lib/CodeGen/AtomicExpandPass.cpp File Reference
AtomicExpandPass.cpp File Reference
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/CodeGen/AtomicExpandUtils.h"
#include "llvm/CodeGen/RuntimeLibcalls.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/AtomicOrdering.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include <cassert>
#include <cstdint>
#include <iterator>
Macros
#define DEBUG_TYPE "atomic-expand"
Functions
INITIALIZE_PASS (AtomicExpand, DEBUG_TYPE, "Expand Atomic instructions", false, false) FunctionPass *llvm
static unsigned getAtomicOpSize (LoadInst *LI)
static unsigned getAtomicOpSize (StoreInst *SI)
static unsigned getAtomicOpSize (AtomicRMWInst *RMWI)
static unsigned getAtomicOpSize (AtomicCmpXchgInst *CASI)
template<typename Inst >
static bool atomicSizeSupported (const TargetLowering *TLI, Inst *I)
static void createCmpXchgInstFun (IRBuilder<> &Builder, Value *Addr, Value *Loaded, Value *NewVal, Align AddrAlign, AtomicOrdering MemOpOrder, SyncScope::ID SSID, Value *&Success, Value *&NewLoaded)
static Value * performAtomicOp (AtomicRMWInst::BinOp Op, IRBuilder<> &Builder, Value *Loaded, Value *Inc)
Emit IR to implement the given atomicrmw operation on values in registers, returning the new value.
static PartwordMaskValues createMaskInstrs (IRBuilder<> &Builder, Instruction *I, Type *ValueType, Value *Addr, Align AddrAlign, unsigned MinWordSize)
This is a helper function which builds instructions to provide values necessary for partword atomic operations.
static Value * extractMaskedValue (IRBuilder<> &Builder, Value *WideWord, const PartwordMaskValues &PMV)
static Value * insertMaskedValue (IRBuilder<> &Builder, Value *WideWord, Value *Updated, const PartwordMaskValues &PMV)
static Value * performMaskedAtomicOp (AtomicRMWInst::BinOp Op, IRBuilder<> &Builder, Value *Loaded, Value *Shifted_Inc, Value *Inc, const PartwordMaskValues &PMV)
Emit IR to implement a masked version of a given atomicrmw operation.
static bool canUseSizedAtomicCall (unsigned Size, Align Alignment, const DataLayout &DL)
static ArrayRef< RTLIB::Libcall > GetRMWLibcall (AtomicRMWInst::BinOp Op)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "atomic-expand"
Definition at line 56 of file AtomicExpandPass.cpp.
Function Documentation
atomicSizeSupported()
template<typename Inst > static bool atomicSizeSupported (const TargetLowering * TLI, Inst * I) static
Definition at line 162 of file AtomicExpandPass.cpp.
References getAtomicOpSize(), llvm::TargetLoweringBase::getMaxAtomicSizeInBitsSupported(), I, and llvm::Check::Size.
canUseSizedAtomicCall()
static bool canUseSizedAtomicCall (unsigned Size, Align Alignment, const DataLayout & DL) static
Definition at line 1553 of file AtomicExpandPass.cpp.
References DL, and llvm::Check::Size.
createCmpXchgInstFun()
static void createCmpXchgInstFun (IRBuilder<> & Builder, Value * Addr, Value * Loaded, Value * NewVal, Align AddrAlign, AtomicOrdering MemOpOrder, SyncScope::ID SSID, Value *& Success, Value *& NewLoaded) static
Definition at line 504 of file AtomicExpandPass.cpp.
References Addr, Builder, llvm::Type::getPointerTo(), llvm::Type::getPrimitiveSizeInBits(), llvm::AtomicCmpXchgInst::getStrongestFailureOrdering(), llvm::Value::getType(), llvm::Type::isFloatingPointTy(), and Success.
createMaskInstrs()
static PartwordMaskValues createMaskInstrs (IRBuilder<> & Builder, Instruction * I, Type * ValueType, Value * Addr, Align AddrAlign, unsigned MinWordSize) static
This is a helper function which builds instructions to provide values necessary for partword atomic operations.
It takes an incoming address, Addr, and ValueType, and constructs the address, shift-amounts and masks needed to work with a larger value of size WordSize.
AlignedAddr: Addr rounded down to a multiple of WordSize
ShiftAmt: Number of bits to right-shift a WordSize value loaded from AlignAddr for it to have the same value as if ValueType was loaded from Addr.
Mask: Value to mask with the value loaded from AlignAddr to include only the part that would've been loaded from Addr.
Inv_Mask: The inverse of Mask.
Definition at line 688 of file AtomicExpandPass.cpp.
References Addr, Align, assert(), Builder, DL, llvm::ConstantInt::get(), llvm::Type::getIntNTy(), llvm::Type::getPointerTo(), and I.
extractMaskedValue()
static Value* extractMaskedValue (IRBuilder<> & Builder, Value * WideWord, const PartwordMaskValues & PMV) static
Definition at line 740 of file AtomicExpandPass.cpp.
References assert(), Builder, and llvm::Value::getType().
Referenced by performMaskedAtomicOp().
getAtomicOpSize() [1/4]
static unsigned getAtomicOpSize (AtomicCmpXchgInst * CASI) static
Definition at line 153 of file AtomicExpandPass.cpp.
References DL, llvm::AtomicCmpXchgInst::getCompareOperand(), llvm::Module::getDataLayout(), llvm::Instruction::getModule(), and llvm::Value::getType().
getAtomicOpSize() [2/4]
static unsigned getAtomicOpSize (AtomicRMWInst * RMWI) static
Definition at line 148 of file AtomicExpandPass.cpp.
References DL, llvm::Module::getDataLayout(), llvm::Instruction::getModule(), llvm::Value::getType(), and llvm::AtomicRMWInst::getValOperand().
getAtomicOpSize() [3/4]
static unsigned getAtomicOpSize (LoadInst * LI) static
Definition at line 138 of file AtomicExpandPass.cpp.
References DL, llvm::Module::getDataLayout(), llvm::Instruction::getModule(), and llvm::Value::getType().
Referenced by atomicSizeSupported().
getAtomicOpSize() [4/4]
static unsigned getAtomicOpSize (StoreInst * SI) static
Definition at line 143 of file AtomicExpandPass.cpp.
References DL, and SI.
GetRMWLibcall()
static ArrayRef<RTLIB::Libcall> GetRMWLibcall (AtomicRMWInst::BinOp Op) static
Definition at line 1609 of file AtomicExpandPass.cpp.
References llvm::AtomicRMWInst::Add, llvm::AtomicRMWInst::And, llvm::AtomicRMWInst::BAD_BINOP, llvm::AtomicRMWInst::FAdd, llvm::AtomicRMWInst::FSub, llvm_unreachable, llvm::makeArrayRef(), llvm::AtomicRMWInst::Max, llvm::AtomicRMWInst::Min, llvm::AtomicRMWInst::Nand, llvm::AtomicRMWInst::Or, llvm::AtomicRMWInst::Sub, llvm::AtomicRMWInst::UMax, llvm::AtomicRMWInst::UMin, llvm::AtomicRMWInst::Xchg, and llvm::AtomicRMWInst::Xor.
INITIALIZE_PASS()
INITIALIZE_PASS (AtomicExpand , DEBUG_TYPE , "Expand Atomic instructions" , false , false)
Definition at line 132 of file AtomicExpandPass.cpp.
insertMaskedValue()
static Value* insertMaskedValue (IRBuilder<> & Builder, Value * WideWord, Value * Updated, const PartwordMaskValues & PMV) static
Definition at line 751 of file AtomicExpandPass.cpp.
References llvm::And, assert(), Builder, llvm::Value::getType(), and llvm::Or.
Referenced by performMaskedAtomicOp().
performAtomicOp()
static Value* performAtomicOp (AtomicRMWInst::BinOp Op, IRBuilder<> & Builder, Value * Loaded, Value * Inc) static
Emit IR to implement the given atomicrmw operation on values in registers, returning the new value.
Definition at line 532 of file AtomicExpandPass.cpp.
References llvm::AtomicRMWInst::Add, llvm::AtomicRMWInst::And, Builder, llvm::AtomicRMWInst::FAdd, llvm::AtomicRMWInst::FSub, llvm_unreachable, llvm::AtomicRMWInst::Max, llvm::AtomicRMWInst::Min, llvm::AtomicRMWInst::Nand, llvm::AtomicRMWInst::Or, llvm::AtomicRMWInst::Sub, llvm::AtomicRMWInst::UMax, llvm::AtomicRMWInst::UMin, llvm::AtomicRMWInst::Xchg, and llvm::AtomicRMWInst::Xor.
Referenced by performMaskedAtomicOp().
performMaskedAtomicOp()
static Value* performMaskedAtomicOp (AtomicRMWInst::BinOp Op, IRBuilder<> & Builder, Value * Loaded, Value * Shifted_Inc, Value * Inc, const PartwordMaskValues & PMV) static
Emit IR to implement a masked version of a given atomicrmw operation.
(That is, only the bits under the Mask should be affected by the operation)
Definition at line 769 of file AtomicExpandPass.cpp.
References llvm::AtomicRMWInst::Add, llvm::AtomicRMWInst::And, Builder, extractMaskedValue(), insertMaskedValue(), llvm_unreachable, llvm::AtomicRMWInst::Max, llvm::AtomicRMWInst::Min, llvm::AtomicRMWInst::Nand, llvm::AtomicRMWInst::Or, performAtomicOp(), llvm::AtomicRMWInst::Sub, llvm::AtomicRMWInst::UMax, llvm::AtomicRMWInst::UMin, llvm::AtomicRMWInst::Xchg, and llvm::AtomicRMWInst::Xor.