LLVM: lib/Transforms/Instrumentation/CGProfile.cpp File Reference
CGProfile.cpp File Reference
#include "llvm/Transforms/Instrumentation/CGProfile.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/Analysis/BlockFrequencyInfo.h"
#include "llvm/Analysis/LazyBlockFrequencyInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/PassManager.h"
#include "llvm/InitializePasses.h"
#include "llvm/ProfileData/InstrProf.h"
#include "llvm/Transforms/Instrumentation.h"
#include <array>
Functions
static bool addModuleFlags (Module &M, MapVector< std::pair< Function *, Function * >, uint64_t > &Counts)
static bool runCGProfilePass (Module &M, function_ref< BlockFrequencyInfo &(Function &)> GetBFI, function_ref< TargetTransformInfo &(Function &)> GetTTI, bool LazyBFI)
INITIALIZE_PASS (CGProfileLegacyPass, "cg-profile", "Call Graph Profile", false, false) ModulePass *llvm
Function Documentation
addModuleFlags()
static bool addModuleFlags (Module & M, MapVector< std::pair< Function *, Function * >, uint64_t > & Counts) static
Definition at line 28 of file CGProfile.cpp.
References llvm::Module::Append, Context, llvm::MDBuilder::createConstant(), E, llvm::MDNode::get(), llvm::ConstantInt::get(), llvm::ValueAsMetadata::get(), and llvm::Type::getInt64Ty().
Referenced by runCGProfilePass().
INITIALIZE_PASS()
INITIALIZE_PASS (CGProfileLegacyPass , "cg-profile" , "Call Graph Profile" , false , false)
Definition at line 135 of file CGProfile.cpp.
runCGProfilePass()
static bool runCGProfilePass (Module & M, function_ref< BlockFrequencyInfo &(Function &)> GetBFI, function_ref< TargetTransformInfo &(Function &)> GetTTI, bool LazyBFI) static
Definition at line 49 of file CGProfile.cpp.
References addModuleFlags(), llvm::BB, llvm::AMDGPUISD::BFI, llvm::InstrProfSymtab::create(), F, llvm::CallBase::getCalledFunction(), llvm::InstrProfSymtab::getFunction(), llvm::getValueProfDataFromInst(), I, llvm::CallBase::isIndirectCall(), llvm::TargetTransformInfo::isLoweredToCall(), and llvm::SaturatingAdd().
Referenced by llvm::CGProfilePass::run().