LLVM: llvm::SystemZCallingConventionRegisters Class Reference
llvm::SystemZCallingConventionRegisters Class Reference abstract
A SystemZ-specific class detailing special use registers particular for calling conventions.
#include "Target/SystemZ/SystemZRegisterInfo.h"
Public Member Functions
virtual int getReturnFunctionAddressRegister ()=0
virtual int getStackPointerRegister ()=0
virtual int getFramePointerRegister ()=0
virtual const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const =0
virtual const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID CC) const =0
virtual int getCallFrameSize ()=0
virtual int getStackPointerBias ()=0
virtual ~SystemZCallingConventionRegisters ()
Destroys the object.
Detailed Description
A SystemZ-specific class detailing special use registers particular for calling conventions.
It is abstract, all calling conventions must override and define the pure virtual member function defined in this class.
Definition at line 47 of file SystemZRegisterInfo.h.
Constructor & Destructor Documentation
~SystemZCallingConventionRegisters()
virtual llvm::SystemZCallingConventionRegisters::~SystemZCallingConventionRegisters () inline virtual
Destroys the object.
Bogus destructor allowing derived classes to override it.
Definition at line 77 of file SystemZRegisterInfo.h.
Member Function Documentation
getCalleeSavedRegs()
virtual const MCPhysReg* llvm::SystemZCallingConventionRegisters::getCalleeSavedRegs (const MachineFunction * MF) const pure virtual
Returns
an array of all the callee saved registers.
Implemented in llvm::SystemZELFRegisters, and llvm::SystemZXPLINK64Registers.
Referenced by llvm::SystemZRegisterInfo::getCalleeSavedRegs().
getCallFrameSize()
virtual int llvm::SystemZCallingConventionRegisters::getCallFrameSize () pure virtual
Returns
the offset to the locals area.
Implemented in llvm::SystemZELFRegisters, and llvm::SystemZXPLINK64Registers.
Referenced by llvm::SystemZTargetLowering::LowerCall().
getCallPreservedMask()
virtual const uint32_t* llvm::SystemZCallingConventionRegisters::getCallPreservedMask (const MachineFunction & MF, CallingConv::ID CC) const pure virtual
Returns
the mask of all the call preserved registers.
Implemented in llvm::SystemZELFRegisters, and llvm::SystemZXPLINK64Registers.
Referenced by llvm::SystemZRegisterInfo::getCallPreservedMask().
getFramePointerRegister()
virtual int llvm::SystemZCallingConventionRegisters::getFramePointerRegister () pure virtual
Returns
the register that keeps the frame pointer address.
Implemented in llvm::SystemZELFRegisters, and llvm::SystemZXPLINK64Registers.
getReturnFunctionAddressRegister()
virtual int llvm::SystemZCallingConventionRegisters::getReturnFunctionAddressRegister () pure virtual
Returns
the register that keeps the return function address.
Implemented in llvm::SystemZELFRegisters, and llvm::SystemZXPLINK64Registers.
getStackPointerBias()
virtual int llvm::SystemZCallingConventionRegisters::getStackPointerBias () pure virtual
Returns
the stack pointer bias.
Implemented in llvm::SystemZELFRegisters, and llvm::SystemZXPLINK64Registers.
Referenced by llvm::SystemZTargetLowering::LowerCall().
getStackPointerRegister()
virtual int llvm::SystemZCallingConventionRegisters::getStackPointerRegister () pure virtual
Returns
the register that keeps the stack pointer address.
Implemented in llvm::SystemZELFRegisters, and llvm::SystemZXPLINK64Registers.
Referenced by llvm::SystemZTargetLowering::LowerCall().
The documentation for this class was generated from the following file:
lib/Target/SystemZ/SystemZRegisterInfo.h