LLVM: llvm::VECustomDAG Class Reference
llvm::VECustomDAG Class Reference
#include "Target/VE/VECustomDAG.h"
Public Member Functions
SelectionDAG * getDAG () const
VECustomDAG (SelectionDAG &DAG, SDLoc DL)
VECustomDAG (SelectionDAG &DAG, SDValue WhereOp)
VECustomDAG (SelectionDAG &DAG, const SDNode *WhereN)
SDValue getNode (unsigned OC, SDVTList VTL, ArrayRef< SDValue > OpV, Optional< SDNodeFlags > Flags=None) const
getNode {
SDValue getNode (unsigned OC, ArrayRef< EVT > ResVT, ArrayRef< SDValue > OpV, Optional< SDNodeFlags > Flags=None) const
SDValue getNode (unsigned OC, EVT ResVT, ArrayRef< SDValue > OpV, Optional< SDNodeFlags > Flags=None) const
SDValue getUNDEF (EVT VT) const
SDValue getConstant (uint64_t Val, EVT VT, bool IsTarget=false, bool IsOpaque=false) const
} getNode
SDValue getBroadcast (EVT ResultVT, SDValue Scalar, SDValue AVL) const
Detailed Description
Definition at line 30 of file VECustomDAG.h.
Constructor & Destructor Documentation
VECustomDAG() [1/3]
llvm::VECustomDAG::VECustomDAG (SelectionDAG & DAG, SDLoc DL) inline
Definition at line 37 of file VECustomDAG.h.
References DL.
VECustomDAG() [2/3]
llvm::VECustomDAG::VECustomDAG (SelectionDAG & DAG, SDValue WhereOp) inline
Definition at line 39 of file VECustomDAG.h.
References DL.
VECustomDAG() [3/3]
llvm::VECustomDAG::VECustomDAG (SelectionDAG & DAG, const SDNode * WhereN) inline
Definition at line 41 of file VECustomDAG.h.
References DL.
Member Function Documentation
getBroadcast()
SDValue llvm::VECustomDAG::getBroadcast (EVT ResultVT, SDValue Scalar, SDValue AVL) const
Definition at line 60 of file VECustomDAG.cpp.
References assert(), llvm::MVT::f32, getNode(), llvm::MVT::i1, llvm::MVT::i32, llvm::MVT::i64, llvm::isPackedVectorType(), llvm::EVT::isVector(), llvm::VEISD::REPL_F32, llvm::VEISD::REPL_I32, and llvm::VEISD::VEC_BROADCAST.
Referenced by llvm::VETargetLowering::lowerBUILD_VECTOR(), and llvm::VETargetLowering::lowerToVVP().
getConstant()
SDValue llvm::VECustomDAG::getConstant (uint64_t Val, EVT VT, bool IsTarget = false, bool IsOpaque = false) const
} getNode
Definition at line 55 of file VECustomDAG.cpp.
References llvm::SelectionDAG::getConstant().
Referenced by llvm::VETargetLowering::lowerBUILD_VECTOR(), and llvm::VETargetLowering::lowerToVVP().
getDAG()
SelectionDAG* llvm::VECustomDAG::getDAG () const inline
Definition at line 35 of file VECustomDAG.h.
getNode() [1/3]
SDValue llvm::VECustomDAG::getNode (unsigned OC, ArrayRef< EVT > ResVT, ArrayRef< SDValue > OpV, Optional< SDNodeFlags > Flags = None) const inline
Definition at line 52 of file VECustomDAG.h.
References DL, llvm::SelectionDAG::getNode(), N, and llvm::SystemZISD::OC.
getNode() [2/3]
SDValue llvm::VECustomDAG::getNode (unsigned OC, EVT ResVT, ArrayRef< SDValue > OpV, Optional< SDNodeFlags > Flags = None) const inline
Definition at line 60 of file VECustomDAG.h.
References DL, llvm::SelectionDAG::getNode(), N, and llvm::SystemZISD::OC.
getNode() [3/3]
SDValue llvm::VECustomDAG::getNode (unsigned OC, SDVTList VTL, ArrayRef< SDValue > OpV, Optional< SDNodeFlags > Flags = None) const inline
getNode {
Definition at line 44 of file VECustomDAG.h.
References DL, llvm::SelectionDAG::getNode(), N, and llvm::SystemZISD::OC.
Referenced by getBroadcast(), llvm::VETargetLowering::lowerBUILD_VECTOR(), and llvm::VETargetLowering::lowerToVVP().
getUNDEF()
SDValue llvm::VECustomDAG::getUNDEF (EVT VT) const inline
Definition at line 68 of file VECustomDAG.h.
References llvm::SelectionDAG::getUNDEF().
Referenced by llvm::VETargetLowering::lowerBUILD_VECTOR().
The documentation for this class was generated from the following files:
lib/Target/VE/VECustomDAG.h
lib/Target/VE/VECustomDAG.cpp