LLVM: llvm::coverage::CoverageFilenamesSectionWriter Class Reference
llvm::coverage::CoverageFilenamesSectionWriter Class Reference
Writer of the filenames section for the instrumentation based code coverage.
#include "llvm/ProfileData/Coverage/CoverageMappingWriter.h"
Public Member Functions
CoverageFilenamesSectionWriter (ArrayRef< std::string > Filenames)
void write (raw_ostream &OS, bool Compress=true)
Write encoded filenames to the given output stream.
Detailed Description
Writer of the filenames section for the instrumentation based code coverage.
Definition at line 29 of file CoverageMappingWriter.h.
Constructor & Destructor Documentation
CoverageFilenamesSectionWriter()
CoverageFilenamesSectionWriter::CoverageFilenamesSectionWriter (ArrayRef< std::string > Filenames)
Definition at line 29 of file CoverageMappingWriter.cpp.
References assert(), and llvm::StringSet< AllocatorTy >::insert().
Member Function Documentation
write()
void CoverageFilenamesSectionWriter::write (raw_ostream & OS, bool Compress = true)
Write encoded filenames to the given output stream.
If Compress is true, attempt to compress the filenames.
Definition at line 39 of file CoverageMappingWriter.cpp.
References llvm::zlib::BestSizeCompression, llvm::zlib::compress(), llvm::DoInstrProfNameCompression, E, llvm::encodeULEB128(), llvm::zlib::isAvailable(), llvm::report_bad_alloc_error(), llvm::ArrayRef< T >::size(), llvm::SmallVectorBase< Size_T >::size(), and llvm::SmallString< InternalLen >::str().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/Coverage/CoverageMappingWriter.h
lib/ProfileData/Coverage/CoverageMappingWriter.cpp