LLVM: llvm::jitlink::Addressable Class Reference
llvm::jitlink::Addressable Class Reference
Base class for Addressable entities (externals, absolutes, blocks).
#include "llvm/ExecutionEngine/JITLink/JITLink.h"
Public Member Functions
Addressable (const Addressable &)=delete
Addressable & operator= (const Addressable &)=default
Addressable (Addressable &&)=delete
Addressable & operator= (Addressable &&)=default
orc::ExecutorAddr getAddress () const
void setAddress (orc::ExecutorAddr Address)
bool isDefined () const
Returns true if this is a defined addressable, in which case you can downcast this to a Block.
bool isAbsolute () const
Protected Member Functions
Addressable (orc::ExecutorAddr Address, bool IsDefined)
Addressable (orc::ExecutorAddr Address)
Protected Attributes
uint64_t ContentMutable: 1
uint64_t P2Align: 5
uint64_t AlignmentOffset: 56
Friends
class LinkGraph
Detailed Description
Base class for Addressable entities (externals, absolutes, blocks).
Definition at line 103 of file JITLink.h.
Constructor & Destructor Documentation
Addressable() [1/4]
llvm::jitlink::Addressable::Addressable (orc::ExecutorAddr Address, bool IsDefined) inline protected
Definition at line 107 of file JITLink.h.
References llvm::Address.
Addressable() [2/4]
llvm::jitlink::Addressable::Addressable (orc::ExecutorAddr Address) inline protected
Definition at line 110 of file JITLink.h.
References llvm::Address, and assert().
Addressable() [3/4]
llvm::jitlink::Addressable::Addressable (const Addressable &) delete
Addressable() [4/4]
llvm::jitlink::Addressable::Addressable (Addressable &&) delete
Member Function Documentation
getAddress()
orc::ExecutorAddr llvm::jitlink::Addressable::getAddress () const inline
Definition at line 122 of file JITLink.h.
Referenced by llvm::jitlink::SectionRange::getEnd(), llvm::jitlink::Block::getFixupAddress(), llvm::jitlink::SectionRange::getStart(), and llvm::jitlink::SectionRange::SectionRange().
isAbsolute()
bool llvm::jitlink::Addressable::isAbsolute () const inline
Definition at line 128 of file JITLink.h.
isDefined()
bool llvm::jitlink::Addressable::isDefined () const inline
Returns true if this is a defined addressable, in which case you can downcast this to a Block.
Definition at line 127 of file JITLink.h.
operator=() [1/2]
Addressable& llvm::jitlink::Addressable::operator= (Addressable &&) default
operator=() [2/2]
Addressable& llvm::jitlink::Addressable::operator= (const Addressable &) default
setAddress()
void llvm::jitlink::Addressable::setAddress (orc::ExecutorAddr Address) inline
Definition at line 123 of file JITLink.h.
References llvm::Address.
Friends And Related Function Documentation
LinkGraph
friend class LinkGraph friend
Definition at line 104 of file JITLink.h.
Member Data Documentation
AlignmentOffset
uint64_t llvm::jitlink::Addressable::AlignmentOffset protected
Definition at line 144 of file JITLink.h.
Referenced by llvm::jitlink::Block::getAlignmentOffset(), and llvm::jitlink::Block::setAlignmentOffset().
ContentMutable
uint64_t llvm::jitlink::Addressable::ContentMutable protected
Definition at line 142 of file JITLink.h.
Referenced by llvm::jitlink::Block::getAlreadyMutableContent(), llvm::jitlink::Block::getMutableContent(), llvm::jitlink::Block::isContentMutable(), llvm::jitlink::Block::setContent(), and llvm::jitlink::Block::setMutableContent().
P2Align
uint64_t llvm::jitlink::Addressable::P2Align protected
Definition at line 143 of file JITLink.h.
Referenced by llvm::jitlink::Block::getAlignment(), llvm::jitlink::Block::setAlignment(), and llvm::jitlink::Block::setAlignmentOffset().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/JITLink/JITLink.h