LLVM: llvm::orc::shared::SPSInputBuffer Class Reference
llvm::orc::shared::SPSInputBuffer Class Reference
Input char buffer with underflow check.
#include "llvm/ExecutionEngine/Orc/Shared/SimplePackedSerialization.h"
Public Member Functions
SPSInputBuffer ()=default
SPSInputBuffer (const char *Buffer, size_t Remaining)
bool read (char *Data, size_t Size)
const char * data () const
bool skip (size_t Size)
Detailed Description
Input char buffer with underflow check.
Definition at line 73 of file SimplePackedSerialization.h.
Constructor & Destructor Documentation
SPSInputBuffer() [1/2]
llvm::orc::shared::SPSInputBuffer::SPSInputBuffer () default
SPSInputBuffer() [2/2]
llvm::orc::shared::SPSInputBuffer::SPSInputBuffer (const char * Buffer, size_t Remaining) inline
Definition at line 76 of file SimplePackedSerialization.h.
Member Function Documentation
data()
const char* llvm::orc::shared::SPSInputBuffer::data () const inline
Definition at line 87 of file SimplePackedSerialization.h.
Referenced by llvm::orc::shared::SPSSerializationTraits< SPSSequence< char >, ArrayRef< char > >::deserialize(), and llvm::orc::shared::SPSSerializationTraits< SPSString, StringRef >::deserialize().
read()
bool llvm::orc::shared::SPSInputBuffer::read (char * Data, size_t Size) inline
Definition at line 78 of file SimplePackedSerialization.h.
References llvm::Data, and llvm::Check::Size.
Referenced by llvm::orc::shared::SPSSerializationTraits< SPSTagT, SPSTagT, std::enable_if_t< std::is_same< SPSTagT, bool >::value||std::is_same< SPSTagT, char >::value||std::is_same< SPSTagT, int8_t >::value||std::is_same< SPSTagT, int16_t >::value||std::is_same< SPSTagT, int32_t >::value||std::is_same< SPSTagT, int64_t >::value||std::is_same< SPSTagT, uint8_t >::value||std::is_same< SPSTagT, uint16_t >::value||std::is_same< SPSTagT, uint32_t >::value||std::is_same< SPSTagT, uint64_t >::value > >::deserialize().
skip()
bool llvm::orc::shared::SPSInputBuffer::skip (size_t Size) inline
Definition at line 88 of file SimplePackedSerialization.h.
References llvm::Check::Size.
Referenced by llvm::orc::shared::SPSSerializationTraits< SPSSequence< char >, ArrayRef< char > >::deserialize(), and llvm::orc::shared::SPSSerializationTraits< SPSString, StringRef >::deserialize().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/SimplePackedSerialization.h