LLVM: llvm::symbolize::LocalDIFetcher Class Reference
llvm::symbolize::LocalDIFetcher Class Reference
LocalDIFetcher searches local cache directories for debug info.
#include "llvm/DebugInfo/Symbolize/DIFetcher.h"
Public Member Functions
LocalDIFetcher (ArrayRef< std::string > DebugFileDirectory)
virtual ~LocalDIFetcher ()=default
Optional< std::string > fetchBuildID (ArrayRef< uint8_t > BuildID) const override
Public Member Functions inherited from llvm::symbolize::DIFetcher
virtual ~DIFetcher ()=default
Detailed Description
LocalDIFetcher searches local cache directories for debug info.
Definition at line 36 of file DIFetcher.h.
Constructor & Destructor Documentation
LocalDIFetcher()
llvm::symbolize::LocalDIFetcher::LocalDIFetcher (ArrayRef< std::string > DebugFileDirectory) inline
Definition at line 38 of file DIFetcher.h.
~LocalDIFetcher()
virtual llvm::symbolize::LocalDIFetcher::~LocalDIFetcher () virtual default
Member Function Documentation
fetchBuildID()
Optional< std::string > llvm::symbolize::LocalDIFetcher::fetchBuildID (ArrayRef< uint8_t > BuildID) const override virtual
Implements llvm::symbolize::DIFetcher.
Definition at line 25 of file DIFetcher.cpp.
References llvm::sys::path::append(), llvm::ArrayRef< T >::empty(), llvm::sys::fs::exists(), llvm::None, and llvm::symbolize::toHex().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/Symbolize/DIFetcher.h
lib/DebugInfo/Symbolize/DIFetcher.cpp