LLVM: llvm::TargetFolder Class Reference
llvm::TargetFolder Class Reference final
TargetFolder - Create constants with target dependent folding.
#include "llvm/Analysis/TargetFolder.h"
Public Member Functions
TargetFolder (const DataLayout &DL)
Value * FoldAdd (Value *LHS, Value *RHS, bool HasNUW=false, bool HasNSW=false) const override
Value * FoldAnd (Value *LHS, Value *RHS) const override
Value * FoldOr (Value *LHS, Value *RHS) const override
Value * FoldICmp (CmpInst::Predicate P, Value *LHS, Value *RHS) const override
Value * FoldGEP (Type *Ty, Value *Ptr, ArrayRef< Value * > IdxList, bool IsInBounds=false) const override
Value * FoldSelect (Value *C, Value *True, Value *False) const override
Constant * CreateFAdd (Constant *LHS, Constant *RHS) const override
Constant * CreateSub (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const override
Constant * CreateFSub (Constant *LHS, Constant *RHS) const override
Constant * CreateMul (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const override
Constant * CreateFMul (Constant *LHS, Constant *RHS) const override
Constant * CreateUDiv (Constant *LHS, Constant *RHS, bool isExact=false) const override
Constant * CreateSDiv (Constant *LHS, Constant *RHS, bool isExact=false) const override
Constant * CreateFDiv (Constant *LHS, Constant *RHS) const override
Constant * CreateURem (Constant *LHS, Constant *RHS) const override
Constant * CreateSRem (Constant *LHS, Constant *RHS) const override
Constant * CreateFRem (Constant *LHS, Constant *RHS) const override
Constant * CreateShl (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const override
Constant * CreateLShr (Constant *LHS, Constant *RHS, bool isExact=false) const override
Constant * CreateAShr (Constant *LHS, Constant *RHS, bool isExact=false) const override
Constant * CreateXor (Constant *LHS, Constant *RHS) const override
Constant * CreateBinOp (Instruction::BinaryOps Opc, Constant *LHS, Constant *RHS) const override
Constant * CreateNeg (Constant *C, bool HasNUW=false, bool HasNSW=false) const override
Constant * CreateFNeg (Constant *C) const override
Constant * CreateNot (Constant *C) const override
Constant * CreateUnOp (Instruction::UnaryOps Opc, Constant *C) const override
Constant * CreateCast (Instruction::CastOps Op, Constant *C, Type *DestTy) const override
Constant * CreateIntCast (Constant *C, Type *DestTy, bool isSigned) const override
Constant * CreatePointerCast (Constant *C, Type *DestTy) const override
Constant * CreateFPCast (Constant *C, Type *DestTy) const override
Constant * CreateBitCast (Constant *C, Type *DestTy) const override
Constant * CreateIntToPtr (Constant *C, Type *DestTy) const override
Constant * CreatePtrToInt (Constant *C, Type *DestTy) const override
Constant * CreateZExtOrBitCast (Constant *C, Type *DestTy) const override
Constant * CreateSExtOrBitCast (Constant *C, Type *DestTy) const override
Constant * CreateTruncOrBitCast (Constant *C, Type *DestTy) const override
Constant * CreatePointerBitCastOrAddrSpaceCast (Constant *C, Type *DestTy) const override
Constant * CreateFCmp (CmpInst::Predicate P, Constant *LHS, Constant *RHS) const override
Constant * CreateExtractElement (Constant *Vec, Constant *Idx) const override
Constant * CreateInsertElement (Constant *Vec, Constant *NewElt, Constant *Idx) const override
Constant * CreateShuffleVector (Constant *V1, Constant *V2, ArrayRef< int > Mask) const override
Constant * CreateExtractValue (Constant *Agg, ArrayRef< unsigned > IdxList) const override
Constant * CreateInsertValue (Constant *Agg, Constant *Val, ArrayRef< unsigned > IdxList) const override
Public Member Functions inherited from llvm::IRBuilderFolder
virtual ~IRBuilderFolder ()
Detailed Description
TargetFolder - Create constants with target dependent folding.
Definition at line 32 of file TargetFolder.h.
Constructor & Destructor Documentation
TargetFolder()
llvm::TargetFolder::TargetFolder (const DataLayout & DL) inline explicit
Definition at line 43 of file TargetFolder.h.
References DL.
Member Function Documentation
CreateAShr()
Constant* llvm::TargetFolder::CreateAShr (Constant * LHS, Constant * RHS, bool isExact = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 157 of file TargetFolder.h.
References llvm::ConstantExpr::getAShr(), LHS, and RHS.
CreateBinOp()
Constant* llvm::TargetFolder::CreateBinOp (Instruction::BinaryOps Opc, Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 165 of file TargetFolder.h.
References llvm::ConstantExpr::get(), LHS, and RHS.
CreateBitCast()
Constant* llvm::TargetFolder::CreateBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 215 of file TargetFolder.h.
References C, and CreateCast().
CreateCast()
Constant* llvm::TargetFolder::CreateCast (Instruction::CastOps Op, Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 193 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getCast().
Referenced by CreateBitCast(), CreateIntToPtr(), and CreatePtrToInt().
CreateExtractElement()
Constant* llvm::TargetFolder::CreateExtractElement (Constant * Vec, Constant * Idx) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 260 of file TargetFolder.h.
References llvm::ConstantExpr::getExtractElement().
CreateExtractValue()
Constant* llvm::TargetFolder::CreateExtractValue (Constant * Agg, ArrayRef< unsigned > IdxList) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 274 of file TargetFolder.h.
References llvm::ConstantExpr::getExtractValue().
CreateFAdd()
Constant* llvm::TargetFolder::CreateFAdd (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 112 of file TargetFolder.h.
References llvm::ConstantExpr::getFAdd(), LHS, and RHS.
CreateFCmp()
Constant* llvm::TargetFolder::CreateFCmp (CmpInst::Predicate P, Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 251 of file TargetFolder.h.
References llvm::ConstantExpr::getCompare(), LHS, P, and RHS.
CreateFDiv()
Constant* llvm::TargetFolder::CreateFDiv (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 137 of file TargetFolder.h.
References llvm::ConstantExpr::getFDiv(), LHS, and RHS.
CreateFMul()
Constant* llvm::TargetFolder::CreateFMul (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 126 of file TargetFolder.h.
References llvm::ConstantExpr::getFMul(), LHS, and RHS.
CreateFNeg()
Constant* llvm::TargetFolder::CreateFNeg (Constant * C) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 178 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getFNeg().
CreateFPCast()
Constant* llvm::TargetFolder::CreateFPCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 210 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getFPCast().
CreateFRem()
Constant* llvm::TargetFolder::CreateFRem (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 146 of file TargetFolder.h.
References llvm::ConstantExpr::getFRem(), LHS, and RHS.
CreateFSub()
Constant* llvm::TargetFolder::CreateFSub (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 119 of file TargetFolder.h.
References llvm::ConstantExpr::getFSub(), LHS, and RHS.
CreateInsertElement()
Constant* llvm::TargetFolder::CreateInsertElement (Constant * Vec, Constant * NewElt, Constant * Idx) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 264 of file TargetFolder.h.
References llvm::ConstantExpr::getInsertElement().
CreateInsertValue()
Constant* llvm::TargetFolder::CreateInsertValue (Constant * Agg, Constant * Val, ArrayRef< unsigned > IdxList) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 279 of file TargetFolder.h.
References llvm::ConstantExpr::getInsertValue().
CreateIntCast()
Constant* llvm::TargetFolder::CreateIntCast (Constant * C, Type * DestTy, bool isSigned) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 199 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getIntegerCast().
CreateIntToPtr()
Constant* llvm::TargetFolder::CreateIntToPtr (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 218 of file TargetFolder.h.
References C, and CreateCast().
CreateLShr()
Constant* llvm::TargetFolder::CreateLShr (Constant * LHS, Constant * RHS, bool isExact = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 153 of file TargetFolder.h.
References llvm::ConstantExpr::getLShr(), LHS, and RHS.
CreateMul()
Constant* llvm::TargetFolder::CreateMul (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 122 of file TargetFolder.h.
References llvm::ConstantExpr::getMul(), LHS, and RHS.
CreateNeg()
Constant* llvm::TargetFolder::CreateNeg (Constant * C, bool HasNUW = false, bool HasNSW = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 174 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getNeg().
CreateNot()
Constant* llvm::TargetFolder::CreateNot (Constant * C) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 181 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getNot().
CreatePointerBitCastOrAddrSpaceCast()
Constant* llvm::TargetFolder::CreatePointerBitCastOrAddrSpaceCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 240 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast().
CreatePointerCast()
Constant* llvm::TargetFolder::CreatePointerCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 205 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getPointerCast().
CreatePtrToInt()
Constant* llvm::TargetFolder::CreatePtrToInt (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 221 of file TargetFolder.h.
References C, and CreateCast().
CreateSDiv()
Constant* llvm::TargetFolder::CreateSDiv (Constant * LHS, Constant * RHS, bool isExact = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 133 of file TargetFolder.h.
References llvm::ConstantExpr::getSDiv(), LHS, and RHS.
CreateSExtOrBitCast()
Constant* llvm::TargetFolder::CreateSExtOrBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 229 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getSExtOrBitCast().
CreateShl()
Constant* llvm::TargetFolder::CreateShl (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 149 of file TargetFolder.h.
References llvm::ConstantExpr::getShl(), LHS, and RHS.
CreateShuffleVector()
Constant* llvm::TargetFolder::CreateShuffleVector (Constant * V1, Constant * V2, ArrayRef< int > Mask) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 269 of file TargetFolder.h.
References llvm::ConstantExpr::getShuffleVector(), llvm::BitmaskEnumDetail::Mask(), and llvm::NVPTX::PTXLdStInstCode::V2.
CreateSRem()
Constant* llvm::TargetFolder::CreateSRem (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 143 of file TargetFolder.h.
References llvm::ConstantExpr::getSRem(), LHS, and RHS.
CreateSub()
Constant* llvm::TargetFolder::CreateSub (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 115 of file TargetFolder.h.
References llvm::ConstantExpr::getSub(), LHS, and RHS.
CreateTruncOrBitCast()
Constant* llvm::TargetFolder::CreateTruncOrBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 234 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getTruncOrBitCast().
CreateUDiv()
Constant* llvm::TargetFolder::CreateUDiv (Constant * LHS, Constant * RHS, bool isExact = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 129 of file TargetFolder.h.
References llvm::ConstantExpr::getUDiv(), LHS, and RHS.
CreateUnOp()
Constant* llvm::TargetFolder::CreateUnOp (Instruction::UnaryOps Opc, Constant * C) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 185 of file TargetFolder.h.
References C, and llvm::ConstantExpr::get().
CreateURem()
Constant* llvm::TargetFolder::CreateURem (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 140 of file TargetFolder.h.
References llvm::ConstantExpr::getURem(), LHS, and RHS.
CreateXor()
Constant* llvm::TargetFolder::CreateXor (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 161 of file TargetFolder.h.
References llvm::ConstantExpr::getXor(), LHS, and RHS.
CreateZExtOrBitCast()
Constant* llvm::TargetFolder::CreateZExtOrBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 224 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getZExtOrBitCast().
FoldAdd()
Value* llvm::TargetFolder::FoldAdd (Value * LHS, Value * RHS, bool HasNUW = false, bool HasNSW = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 51 of file TargetFolder.h.
References llvm::ConstantExpr::getAdd(), LHS, and RHS.
FoldAnd()
Value* llvm::TargetFolder::FoldAnd (Value * LHS, Value * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 60 of file TargetFolder.h.
References llvm::ConstantExpr::getAnd(), LHS, and RHS.
FoldGEP()
Value* llvm::TargetFolder::FoldGEP (Type * Ty, Value * Ptr, ArrayRef< Value * > IdxList, bool IsInBounds = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 84 of file TargetFolder.h.
References llvm::any_of(), llvm::ConstantExpr::getGetElementPtr(), and llvm::ConstantExpr::getInBoundsGetElementPtr().
FoldICmp()
Value* llvm::TargetFolder::FoldICmp (CmpInst::Predicate P, Value * LHS, Value * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 76 of file TargetFolder.h.
References llvm::ConstantExpr::getCompare(), LHS, P, and RHS.
FoldOr()
Value* llvm::TargetFolder::FoldOr (Value * LHS, Value * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 68 of file TargetFolder.h.
References llvm::ConstantExpr::getOr(), LHS, and RHS.
FoldSelect()
Value* llvm::TargetFolder::FoldSelect (Value * C, Value * True, Value * False) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 98 of file TargetFolder.h.
References C, R600_InstFlag::FC, and llvm::ConstantExpr::getSelect().
The documentation for this class was generated from the following files:
include/llvm/Analysis/TargetFolder.h
lib/Analysis/ConstantFolding.cpp