LLVM: llvm::VPInstruction Class Reference
llvm::VPInstruction Class Reference
This is a concrete Recipe that models a single VPlan-level instruction.
#include "Transforms/Vectorize/VPlan.h"
Public Types
enum {
FirstOrderRecurrenceSplice , Not , ICmpULE , SLPLoad ,
SLPStore , ActiveLaneMask , CanonicalIVIncrement , CanonicalIVIncrementNUW ,
BranchOnCount
}
VPlan opcodes, extending LLVM IR with idiomatics instructions.
Public Types inherited from llvm::VPDef
using VPRecipeTy = enum { VPBranchOnMaskSC, VPInstructionSC, VPInterleaveSC, VPReductionSC, VPReplicateSC, VPWidenCallSC, VPWidenCanonicalIVSC, VPWidenGEPSC, VPWidenMemoryInstructionSC, VPWidenSC, VPWidenSelectSC, VPBlendSC, VPCanonicalIVPHISC, VPFirstOrderRecurrencePHISC, VPWidenPHISC, VPWidenIntOrFpInductionSC, VPPredInstPHISC, VPReductionPHISC, VPFirstPHISC=VPBlendSC, VPLastPHISC=VPReductionPHISC, }
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Public Types inherited from llvm::VPUser
enum class VPUserID { Recipe , Block }
Subclass identifier (for isa/dyn_cast).
typedef SmallVectorImpl< VPValue * >::iterator operand_iterator
typedef SmallVectorImpl< VPValue * >::const_iterator const_operand_iterator
typedef iterator_range< operand_iterator > operand_range
typedef iterator_range< const_operand_iterator > const_operand_range
Public Types inherited from llvm::VPValue
enum {
VPValueSC , VPVInstructionSC , VPVMemoryInstructionSC , VPVReductionSC ,
VPVReplicateSC , VPVWidenSC , VPVWidenCallSC , VPVWidenCanonicalIVSC ,
VPVWidenGEPSC , VPVWidenSelectSC , VPVBlendSC , VPVCanonicalIVPHISC ,
VPVFirstOrderRecurrencePHISC , VPVWidenPHISC , VPVWidenIntOrFpInductionSC , VPVPredInstPHI ,
VPVReductionPHISC
}
An enumeration for keeping track of the concrete subclass of VPValue that are actually instantiated.
typedef SmallVectorImpl< VPUser * >::iterator user_iterator
typedef SmallVectorImpl< VPUser * >::const_iterator const_user_iterator
typedef iterator_range< user_iterator > user_range
typedef iterator_range< const_user_iterator > const_user_range
Public Member Functions
VPInstruction (unsigned Opcode, ArrayRef< VPValue * > Operands, DebugLoc DL)
VPInstruction (unsigned Opcode, std::initializer_list< VPValue * > Operands, DebugLoc DL={})
VPInstruction * clone () const
unsigned getOpcode () const
void execute (VPTransformState &State) override
Generate the instruction.
void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const override
Print the VPInstruction to O.
LLVM_DUMP_METHOD void dump () const
Print the VPInstruction to dbgs() (for debugging).
bool mayWriteToMemory () const
Return true if this instruction may modify memory.
bool hasResult () const
void setFastMathFlags (FastMathFlags FMFNew)
Set the fast-math flags.
bool onlyFirstLaneUsed (const VPValue *Op) const override
Returns true if the recipe only uses the first lane of operand Op.
Public Member Functions inherited from llvm::VPRecipeBase
VPRecipeBase (const unsigned char SC, ArrayRef< VPValue * > Operands)
template<typename IterT >
VPRecipeBase (const unsigned char SC, iterator_range< IterT > Operands)
virtual ~VPRecipeBase ()=default
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
void insertAfter (VPRecipeBase *InsertPos)
Insert an unlinked Recipe into a basic block immediately after the specified Recipe.
void moveAfter (VPRecipeBase *MovePos)
Unlink this recipe from its current VPBasicBlock and insert it into the VPBasicBlock that MovePos lives in, right after MovePos.
void moveBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator I)
Unlink this recipe and insert into BB before I.
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
Instruction * getUnderlyingInstr ()
Returns the underlying instruction, if the recipe is a VPValue or nullptr otherwise.
const Instruction * getUnderlyingInstr () const
bool mayHaveSideEffects () const
Returns true if the recipe may have side-effects.
bool isPhi () const
Returns true for PHI-like recipes.
bool mayReadFromMemory () const
Returns true if the recipe may read from memory.
bool mayWriteToMemory () const
Returns true if the recipe may write to memory.
bool mayReadOrWriteMemory () const
Returns true if the recipe may read from or write to memory.
Public Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
VPRecipeBase * getPrevNode ()
const VPRecipeBase * getPrevNode () const
Get the previous node, or nullptr for the list head.
VPRecipeBase * getNextNode ()
Get the next node, or nullptr for the list tail.
const VPRecipeBase * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::VPDef
VPDef (const unsigned char SC)
virtual ~VPDef ()
VPValue * getVPSingleValue ()
Returns the only VPValue defined by the VPDef.
const VPValue * getVPSingleValue () const
VPValue * getVPValue (unsigned I)
Returns the VPValue with index I defined by the VPDef.
const VPValue * getVPValue (unsigned I) const
ArrayRef< VPValue * > definedValues ()
Returns an ArrayRef of the values defined by the VPDef.
ArrayRef< VPValue * > definedValues () const
Returns an ArrayRef of the values defined by the VPDef.
unsigned getNumDefinedValues () const
Returns the number of values defined by the VPDef.
unsigned getVPDefID () const
void dump () const
Dump the VPDef to stderr (for debugging).
Public Member Functions inherited from llvm::VPUser
VPUser ()=delete
VPUser (const VPUser &)=delete
VPUser & operator= (const VPUser &)=delete
virtual ~VPUser ()
VPUserID getVPUserID () const
void addOperand (VPValue *Operand)
unsigned getNumOperands () const
VPValue * getOperand (unsigned N) const
void setOperand (unsigned I, VPValue *New)
void removeLastOperand ()
operand_iterator op_begin ()
const_operand_iterator op_begin () const
operand_iterator op_end ()
const_operand_iterator op_end () const
operand_range operands ()
const_operand_range operands () const
Public Member Functions inherited from llvm::VPValue
Value * getUnderlyingValue ()
Return the underlying Value attached to this VPValue.
const Value * getUnderlyingValue () const
VPValue (Value *UV=nullptr, VPDef *Def=nullptr)
VPValue (const VPValue &)=delete
VPValue & operator= (const VPValue &)=delete
virtual ~VPValue ()
unsigned getVPValueID () const
void printAsOperand (raw_ostream &OS, VPSlotTracker &Tracker) const
void print (raw_ostream &OS, VPSlotTracker &Tracker) const
void dump () const
Dump the value to stderr (for debugging).
unsigned getNumUsers () const
void addUser (VPUser &User)
void removeUser (VPUser &User)
Remove a single User from the list of users.
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
user_range users ()
const_user_range users () const
bool hasMoreThanOneUniqueUser ()
Returns true if the value has more than one unique user.
void replaceAllUsesWith (VPValue *New)
VPDef * getDef ()
const VPDef * getDef () const
Value * getLiveInIRValue ()
Returns the underlying IR value, if this VPValue is defined outside the scope of VPlan.
const Value * getLiveInIRValue () const
Static Public Member Functions
static bool classof (const VPValue *V)
Method to support type inquiry through isa, cast, and dyn_cast.
static bool classof (const VPDef *R)
Method to support type inquiry through isa, cast, and dyn_cast.
static bool classof (const VPUser *U)
Extra classof implementations to allow directly casting from VPUser -> VPInstruction.
static bool classof (const VPRecipeBase *R)
Static Public Member Functions inherited from llvm::VPRecipeBase
static bool classof (const VPDef *D)
Method to support type inquiry through isa, cast, and dyn_cast.
static bool classof (const VPUser *U)
Static Public Member Functions inherited from llvm::VPUser
static bool classof (const VPDef *Recipe)
Method to support type inquiry through isa, cast, and dyn_cast.
Protected Member Functions
void setUnderlyingInstr (Instruction *I)
Protected Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
ilist_node_impl ()=default
Protected Member Functions inherited from llvm::VPUser
void printOperands (raw_ostream &O, VPSlotTracker &SlotTracker) const
Print the operands to O.
VPUser (ArrayRef< VPValue * > Operands, VPUserID ID)
VPUser (std::initializer_list< VPValue * > Operands, VPUserID ID)
template<typename IterT >
VPUser (iterator_range< IterT > Operands, VPUserID ID)
Protected Member Functions inherited from llvm::VPValue
VPValue (const unsigned char SC, Value *UV=nullptr, VPDef *Def=nullptr)
void setUnderlyingValue (Value *Val)
Friends
class VPlanSlp
Additional Inherited Members
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, true, true >
Protected Attributes inherited from llvm::VPValue
Value * UnderlyingVal
VPDef * Def
Pointer to the VPDef that defines this VPValue.
Detailed Description
This is a concrete Recipe that models a single VPlan-level instruction.
While as any Recipe it may generate a sequence of IR instructions when executed, these instructions would always form a single-def expression as the VPInstruction is also a single def-use vertex.
Definition at line 790 of file VPlan.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
VPlan opcodes, extending LLVM IR with idiomatics instructions.
Enumerator
FirstOrderRecurrenceSplice
Not
ICmpULE
SLPLoad
SLPStore
ActiveLaneMask
CanonicalIVIncrement
CanonicalIVIncrementNUW
BranchOnCount
Definition at line 795 of file VPlan.h.
Constructor & Destructor Documentation
VPInstruction() [1/2]
llvm::VPInstruction::VPInstruction (unsigned Opcode, ArrayRef< VPValue * > Operands, DebugLoc DL) inline
Definition at line 823 of file VPlan.h.
VPInstruction() [2/2]
llvm::VPInstruction::VPInstruction (unsigned Opcode, std::initializer_list< VPValue * > Operands, DebugLoc DL = {}) inline
Definition at line 828 of file VPlan.h.
Member Function Documentation
classof() [1/4]
static bool llvm::VPInstruction::classof (const VPDef * R) inline static
Method to support type inquiry through isa, cast, and dyn_cast.
Definition at line 843 of file VPlan.h.
References llvm::RISCVFenceField::R.
classof() [2/4]
static bool llvm::VPInstruction::classof (const VPRecipeBase * R) inline static
Definition at line 853 of file VPlan.h.
References llvm::RISCVFenceField::R.
classof() [3/4]
static bool llvm::VPInstruction::classof (const VPUser * U) inline static
Extra classof implementations to allow directly casting from VPUser -> VPInstruction.
Definition at line 849 of file VPlan.h.
References llvm::RISCVFenceField::R.
classof() [4/4]
static bool llvm::VPInstruction::classof (const VPValue * V) inline static
Method to support type inquiry through isa, cast, and dyn_cast.
Definition at line 833 of file VPlan.h.
References llvm::VPValue::getVPValueID(), and llvm::VPValue::VPVInstructionSC.
clone()
VPInstruction* llvm::VPInstruction::clone () const inline
Definition at line 837 of file VPlan.h.
References DL, Operands, llvm::VPUser::operands(), and llvm::VPValue::VPInstruction.
dump()
void VPInstruction::dump () const
Print the VPInstruction to dbgs() (for debugging).
Definition at line 773 of file VPlan.cpp.
References llvm::dbgs(), llvm::VPRecipeBase::getParent(), and print().
execute()
void VPInstruction::execute (VPTransformState & State) override virtual
Generate the instruction.
TODO: We currently execute only per-part unless a specific instance is provided.
Implements llvm::VPRecipeBase.
Definition at line 764 of file VPlan.cpp.
References assert(), llvm::VPTransformState::Builder, llvm::VPTransformState::Instance, llvm::IRBuilderBase::setFastMathFlags(), and llvm::VPTransformState::UF.
getOpcode()
unsigned llvm::VPInstruction::getOpcode () const inline
Definition at line 857 of file VPlan.h.
Referenced by hasResult(), onlyFirstLaneUsed(), and print().
hasResult()
bool llvm::VPInstruction::hasResult () const inline
Definition at line 881 of file VPlan.h.
References BranchOnCount, getOpcode(), llvm::MipsISD::Ret, and llvm::SPII::Store.
Referenced by print().
mayWriteToMemory()
bool llvm::VPInstruction::mayWriteToMemory () const inline
Return true if this instruction may modify memory.
Definition at line 874 of file VPlan.h.
References llvm::MCID::Call, SLPStore, and llvm::SPII::Store.
onlyFirstLaneUsed()
bool llvm::VPInstruction::onlyFirstLaneUsed (const VPValue * Op) const inline override virtual
Returns true if the recipe only uses the first lane of operand Op.
Reimplemented from llvm::VPRecipeBase.
Definition at line 906 of file VPlan.h.
References ActiveLaneMask, assert(), BranchOnCount, CanonicalIVIncrement, CanonicalIVIncrementNUW, getOpcode(), llvm::VPUser::getOperand(), llvm::is_contained(), llvm_unreachable, and llvm::VPUser::operands().
print()
void VPInstruction::print (raw_ostream & O, const Twine & Indent, VPSlotTracker & SlotTracker) const override virtual
Print the VPInstruction to O.
Implements llvm::VPDef.
Definition at line 778 of file VPlan.cpp.
References ActiveLaneMask, BranchOnCount, CanonicalIVIncrement, CanonicalIVIncrementNUW, FirstOrderRecurrenceSplice, getOpcode(), llvm::Instruction::getOpcodeName(), hasResult(), ICmpULE, Not, llvm::RISCVFenceField::O, llvm::VPUser::operands(), llvm::DebugLoc::print(), llvm::VPValue::printAsOperand(), SLPLoad, and SLPStore.
Referenced by dump().
setFastMathFlags()
void VPInstruction::setFastMathFlags (FastMathFlags FMFNew)
Set the fast-math flags.
Definition at line 833 of file VPlan.cpp.
References assert().
setUnderlyingInstr()
void llvm::VPInstruction::setUnderlyingInstr (Instruction * I) inline protected
Definition at line 820 of file VPlan.h.
References I, and llvm::VPValue::setUnderlyingValue().
Friends And Related Function Documentation
VPlanSlp
friend class VPlanSlp friend
Definition at line 791 of file VPlan.h.
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlan.cpp