LLVM: llvm::MCDwarfDwoLineTable Class Reference
llvm::MCDwarfDwoLineTable Class Reference
#include "llvm/MC/MCDwarf.h"
Public Member Functions
void maybeSetRootFile (StringRef Directory, StringRef FileName, Optional< MD5::MD5Result > Checksum, Optional< StringRef > Source)
unsigned getFile (StringRef Directory, StringRef FileName, Optional< MD5::MD5Result > Checksum, uint16_t DwarfVersion, Optional< StringRef > Source)
void Emit (MCStreamer &MCOS, MCDwarfLineTableParams Params, MCSection *Section) const
Detailed Description
Definition at line 314 of file MCDwarf.h.
Member Function Documentation
Emit()
void MCDwarfDwoLineTable::Emit (MCStreamer & MCOS, MCDwarfLineTableParams Params, MCSection * Section) const
Definition at line 283 of file MCDwarf.cpp.
References llvm::MCDwarfLineTableHeader::Emit(), llvm::MCStreamer::emitLabel(), llvm::None, llvm::ARMBuildAttrs::Section, and llvm::MCStreamer::SwitchSection().
getFile()
unsigned llvm::MCDwarfDwoLineTable::getFile (StringRef Directory, StringRef FileName, Optional< MD5::MD5Result > Checksum, uint16_t DwarfVersion, Optional< StringRef > Source) inline
Definition at line 327 of file MCDwarf.h.
References llvm::cantFail(), llvm::Sched::Source, and llvm::MCDwarfLineTableHeader::tryGetFile().
maybeSetRootFile()
void llvm::MCDwarfDwoLineTable::maybeSetRootFile (StringRef Directory, StringRef FileName, Optional< MD5::MD5Result > Checksum, Optional< StringRef > Source) inline
Definition at line 319 of file MCDwarf.h.
References llvm::MCDwarfFile::Name, llvm::MCDwarfLineTableHeader::RootFile, llvm::MCDwarfLineTableHeader::setRootFile(), and llvm::Sched::Source.
The documentation for this class was generated from the following files:
include/llvm/MC/MCDwarf.h
lib/MC/MCDwarf.cpp