LLVM: llvm::MCWinCOFFStreamer Class Reference
llvm::MCWinCOFFStreamer Class Reference
#include "llvm/MC/MCWinCOFFStreamer.h"
Public Member Functions
MCWinCOFFStreamer (MCContext &Context, std::unique_ptr< MCAsmBackend > MAB, std::unique_ptr< MCCodeEmitter > CE, std::unique_ptr< MCObjectWriter > OW)
void reset () override
state management
MCStreamer interface
void initSections (bool NoExecStack, const MCSubtargetInfo &STI) override
Create the default sections and set the initial one.
void emitLabel (MCSymbol *Symbol, SMLoc Loc=SMLoc()) override
Emit a label for Symbol into the current section.
void emitAssemblerFlag (MCAssemblerFlag Flag) override
Note in the output the specified Flag.
void emitThumbFunc (MCSymbol *Func) override
Note in the output that the specified Func is a Thumb mode function (ARM target only).
bool emitSymbolAttribute (MCSymbol *Symbol, MCSymbolAttr Attribute) override
Add the given Attribute to Symbol.
void emitSymbolDesc (MCSymbol *Symbol, unsigned DescValue) override
Set the DescValue for the Symbol.
void BeginCOFFSymbolDef (MCSymbol const *Symbol) override
Start emitting COFF symbol definition.
void EmitCOFFSymbolStorageClass (int StorageClass) override
Emit the storage class of the symbol.
void EmitCOFFSymbolType (int Type) override
Emit the type of the symbol.
void EndCOFFSymbolDef () override
Marks the end of the symbol definition.
void EmitCOFFSafeSEH (MCSymbol const *Symbol) override
void EmitCOFFSymbolIndex (MCSymbol const *Symbol) override
Emits the symbol table index of a Symbol into the current section.
void EmitCOFFSectionIndex (MCSymbol const *Symbol) override
Emits a COFF section index.
void EmitCOFFSecRel32 (MCSymbol const *Symbol, uint64_t Offset) override
Emits a COFF section relative relocation.
void EmitCOFFImgRel32 (MCSymbol const *Symbol, int64_t Offset) override
Emits a COFF image relative relocation.
void emitCommonSymbol (MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment) override
Emit a common symbol.
void emitLocalCommonSymbol (MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment) override
Emit a local common (.lcomm) symbol.
void emitWeakReference (MCSymbol *Alias, const MCSymbol *Symbol) override
Emit an weak reference from Alias to Symbol.
void emitZerofill (MCSection *Section, MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment, SMLoc Loc=SMLoc()) override
Emit the zerofill section and an optional symbol.
void emitTBSSSymbol (MCSection *Section, MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment) override
Emit a thread local bss (.tbss) symbol.
void emitIdent (StringRef IdentString) override
Emit the "identifiers" directive.
void EmitWinEHHandlerData (SMLoc Loc) override
void emitCGProfileEntry (const MCSymbolRefExpr *From, const MCSymbolRefExpr *To, uint64_t Count) override
void finishImpl () override
Streamer specific finalization.
Public Member Functions inherited from llvm::MCObjectStreamer
bool isIntegratedAssemblerRequired () const override
Object streamers require the integrated assembler.
void emitFrames (MCAsmBackend *MAB)
void emitCFISections (bool EH, bool Debug) override
MCFragment * getCurrentFragment () const
void insert (MCFragment *F)
MCDataFragment * getOrCreateDataFragment (const MCSubtargetInfo *STI=nullptr)
Get a data fragment to write into, creating a new one if the current fragment is not a data fragment.
void visitUsedSymbol (const MCSymbol &Sym) override
void flushPendingLabels ()
Create a data fragment for any pending labels across all Sections and Subsections.
MCAssembler & getAssembler ()
MCAssembler * getAssemblerPtr () override
virtual void emitLabelAtPos (MCSymbol *Symbol, SMLoc Loc, MCFragment *F, uint64_t Offset)
void emitAssignment (MCSymbol *Symbol, const MCExpr *Value) override
Emit an assignment of Value to Symbol.
void emitConditionalAssignment (MCSymbol *Symbol, const MCExpr *Value) override
Emit an assignment of Value to Symbol, but only if Value is also emitted.
void emitValueImpl (const MCExpr *Value, unsigned Size, SMLoc Loc=SMLoc()) override
Emit the expression Value into the output as a native integer of the given Size bytes.
void emitULEB128Value (const MCExpr *Value) override
void emitSLEB128Value (const MCExpr *Value) override
void changeSection (MCSection *Section, const MCExpr *Subsection) override
Update streamer for a new active section.
void emitInstruction (const MCInst &Inst, const MCSubtargetInfo &STI) override
Emit the given Instruction into the current section.
virtual void emitInstToFragment (const MCInst &Inst, const MCSubtargetInfo &)
Emit an instruction to a special fragment, because this instruction can change its size during relaxation.
void emitBundleAlignMode (unsigned AlignPow2) override
Set the bundle alignment mode from now on in the section.
void emitBundleLock (bool AlignToEnd) override
The following instructions are a bundle-locked group.
void emitBundleUnlock () override
Ends a bundle-locked group.
void emitBytes (StringRef Data) override
Emit the bytes in Data into the output.
void emitValueToAlignment (unsigned ByteAlignment, int64_t Value=0, unsigned ValueSize=1, unsigned MaxBytesToEmit=0) override
Emit some number of copies of Value until the byte alignment ByteAlignment is reached.
void emitCodeAlignment (unsigned ByteAlignment, const MCSubtargetInfo *STI, unsigned MaxBytesToEmit=0) override
Emit nops until the byte alignment ByteAlignment is reached.
void emitValueToOffset (const MCExpr *Offset, unsigned char Value, SMLoc Loc) override
Emit some number of copies of Value until the byte offset Offset is reached.
void emitDwarfLocDirective (unsigned FileNo, unsigned Line, unsigned Column, unsigned Flags, unsigned Isa, unsigned Discriminator, StringRef FileName) override
This implements the DWARF2 '.loc fileno lineno ...' assembler directive.
void emitDwarfAdvanceLineAddr (int64_t LineDelta, const MCSymbol *LastLabel, const MCSymbol *Label, unsigned PointerSize) override
If targets does not support representing debug line section by .loc/.file directives in assembly output, we need to populate debug line section with raw debug line contents.
void emitDwarfLineEndEntry (MCSection *Section, MCSymbol *LastLabel) override
Emit the debug line end entry.
void emitDwarfAdvanceFrameAddr (const MCSymbol *LastLabel, const MCSymbol *Label)
void emitCVLocDirective (unsigned FunctionId, unsigned FileNo, unsigned Line, unsigned Column, bool PrologueEnd, bool IsStmt, StringRef FileName, SMLoc Loc) override
This implements the CodeView '.cv_loc' assembler directive.
void emitCVLinetableDirective (unsigned FunctionId, const MCSymbol *Begin, const MCSymbol *End) override
This implements the CodeView '.cv_linetable' assembler directive.
void emitCVInlineLinetableDirective (unsigned PrimaryFunctionId, unsigned SourceFileId, unsigned SourceLineNum, const MCSymbol *FnStartSym, const MCSymbol *FnEndSym) override
This implements the CodeView '.cv_inline_linetable' assembler directive.
void emitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol * >> Ranges, StringRef FixedSizePortion) override
This implements the CodeView '.cv_def_range' assembler directive.
void emitCVStringTableDirective () override
This implements the CodeView '.cv_stringtable' assembler directive.
void emitCVFileChecksumsDirective () override
This implements the CodeView '.cv_filechecksums' assembler directive.
void emitCVFileChecksumOffsetDirective (unsigned FileNo) override
This implements the CodeView '.cv_filechecksumoffset' assembler directive.
void emitDTPRel32Value (const MCExpr *Value) override
Emit the expression Value into the output as a dtprel (32-bit DTP relative) value.
void emitDTPRel64Value (const MCExpr *Value) override
Emit the expression Value into the output as a dtprel (64-bit DTP relative) value.
void emitTPRel32Value (const MCExpr *Value) override
Emit the expression Value into the output as a tprel (32-bit TP relative) value.
void emitTPRel64Value (const MCExpr *Value) override
Emit the expression Value into the output as a tprel (64-bit TP relative) value.
void emitGPRel32Value (const MCExpr *Value) override
Emit the expression Value into the output as a gprel32 (32-bit GP relative) value.
void emitGPRel64Value (const MCExpr *Value) override
Emit the expression Value into the output as a gprel64 (64-bit GP relative) value.
Optional< std::pair< bool, std::string > > emitRelocDirective (const MCExpr &Offset, StringRef Name, const MCExpr *Expr, SMLoc Loc, const MCSubtargetInfo &STI) override
Record a relocation described by the .reloc directive.
void emitFill (const MCExpr &NumBytes, uint64_t FillValue, SMLoc Loc=SMLoc()) override
Emit Size bytes worth of the value specified by FillValue.
void emitFill (const MCExpr &NumValues, int64_t Size, int64_t Expr, SMLoc Loc=SMLoc()) override
Emit NumValues copies of Size bytes.
void emitNops (int64_t NumBytes, int64_t ControlledNopLength, SMLoc Loc, const MCSubtargetInfo &STI) override
void emitFileDirective (StringRef Filename) override
Switch to a new logical file.
void emitFileDirective (StringRef Filename, StringRef CompilerVerion, StringRef TimeStamp, StringRef Description) override
Emit ".file assembler diretive with additioal info.
void emitAddrsig () override
void emitAddrsigSym (const MCSymbol *Sym) override
void emitAbsoluteSymbolDiff (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Size) override
Emit the absolute difference between two symbols if possible.
void emitAbsoluteSymbolDiffAsULEB128 (const MCSymbol *Hi, const MCSymbol *Lo) override
Emit the absolute difference between two symbols encoded with ULEB128.
bool mayHaveInstructions (MCSection &Sec) const override
void emitPendingAssignments (MCSymbol *Symbol)
Emits pending conditional assignments that depend on Symbol being emitted.
void emitFill (uint64_t NumBytes, uint8_t FillValue)
Emit NumBytes bytes worth of the value specified by FillValue.
virtual void emitFill (const MCExpr &NumBytes, uint64_t FillValue, SMLoc Loc=SMLoc())
Emit Size bytes worth of the value specified by FillValue.
virtual void emitFill (const MCExpr &NumValues, int64_t Size, int64_t Expr, SMLoc Loc=SMLoc())
Emit NumValues copies of Size bytes.
Public Member Functions inherited from llvm::MCStreamer
MCStreamer (const MCStreamer &)=delete
MCStreamer & operator= (const MCStreamer &)=delete
virtual ~MCStreamer ()
void visitUsedExpr (const MCExpr &Expr)
void setTargetStreamer (MCTargetStreamer *TS)
void setStartTokLocPtr (const SMLoc *Loc)
SMLoc getStartTokLoc () const
MCContext & getContext () const
void setUseAssemblerInfoForParsing (bool v)
bool getUseAssemblerInfoForParsing ()
MCTargetStreamer * getTargetStreamer ()
void setAllowAutoPadding (bool v)
bool getAllowAutoPadding () const
WinEH::FrameInfo * EnsureValidWinFrameInfo (SMLoc Loc)
Retrieve the current frame info if one is available and it is not yet closed.
unsigned getNumFrameInfos ()
ArrayRef< MCDwarfFrameInfo > getDwarfFrameInfos () const
bool hasUnfinishedDwarfFrameInfo ()
unsigned getNumWinFrameInfos ()
ArrayRef< std::unique_ptr< WinEH::FrameInfo > > getWinFrameInfos () const
void generateCompactUnwindEncodings (MCAsmBackend *MAB)
unsigned emitDwarfFileDirective (unsigned FileNo, StringRef Directory, StringRef Filename, Optional< MD5::MD5Result > Checksum=None, Optional< StringRef > Source=None, unsigned CUID=0)
Associate a filename with a specified logical file number.
virtual Expected< unsigned > tryEmitDwarfFileDirective (unsigned FileNo, StringRef Directory, StringRef Filename, Optional< MD5::MD5Result > Checksum=None, Optional< StringRef > Source=None, unsigned CUID=0)
Associate a filename with a specified logical file number.
virtual void emitDwarfFile0Directive (StringRef Directory, StringRef Filename, Optional< MD5::MD5Result > Checksum, Optional< StringRef > Source, unsigned CUID=0)
Specify the "root" file of the compilation, using the ".file 0" extension.
virtual void emitCFIBKeyFrame ()
virtual bool EmitCVFileDirective (unsigned FileNo, StringRef Filename, ArrayRef< uint8_t > Checksum, unsigned ChecksumKind)
Associate a filename with a specified logical file number, and also specify that file's checksum information.
virtual bool EmitCVFuncIdDirective (unsigned FunctionId)
Introduces a function id for use with .cv_loc.
virtual bool EmitCVInlineSiteIdDirective (unsigned FunctionId, unsigned IAFunc, unsigned IAFile, unsigned IALine, unsigned IACol, SMLoc Loc)
Introduces an inline call site id for use with .cv_loc.
virtual void emitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol * >> Ranges, codeview::DefRangeRegisterRelHeader DRHdr)
virtual void emitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol * >> Ranges, codeview::DefRangeSubfieldRegisterHeader DRHdr)
virtual void emitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol * >> Ranges, codeview::DefRangeRegisterHeader DRHdr)
virtual void emitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol * >> Ranges, codeview::DefRangeFramePointerRelHeader DRHdr)
virtual void EmitCVFPOData (const MCSymbol *ProcSym, SMLoc Loc={})
This implements the CodeView '.cv_fpo_data' assembler directive.
virtual MCSymbol * getDwarfLineTableSymbol (unsigned CUID)
void emitCFIStartProc (bool IsSimple, SMLoc Loc=SMLoc())
void emitCFIEndProc ()
virtual void emitCFIDefCfa (int64_t Register, int64_t Offset)
virtual void emitCFIDefCfaOffset (int64_t Offset)
virtual void emitCFIDefCfaRegister (int64_t Register)
virtual void emitCFILLVMDefAspaceCfa (int64_t Register, int64_t Offset, int64_t AddressSpace)
virtual void emitCFIOffset (int64_t Register, int64_t Offset)
virtual void emitCFIPersonality (const MCSymbol *Sym, unsigned Encoding)
virtual void emitCFILsda (const MCSymbol *Sym, unsigned Encoding)
virtual void emitCFIRememberState ()
virtual void emitCFIRestoreState ()
virtual void emitCFISameValue (int64_t Register)
virtual void emitCFIRestore (int64_t Register)
virtual void emitCFIRelOffset (int64_t Register, int64_t Offset)
virtual void emitCFIAdjustCfaOffset (int64_t Adjustment)
virtual void emitCFIEscape (StringRef Values)
virtual void emitCFIReturnColumn (int64_t Register)
virtual void emitCFIGnuArgsSize (int64_t Size)
virtual void emitCFISignalFrame ()
virtual void emitCFIUndefined (int64_t Register)
virtual void emitCFIRegister (int64_t Register1, int64_t Register2)
virtual void emitCFIWindowSave ()
virtual void emitCFINegateRAState ()
virtual void EmitWinCFIStartProc (const MCSymbol *Symbol, SMLoc Loc=SMLoc())
virtual void EmitWinCFIEndProc (SMLoc Loc=SMLoc())
virtual void EmitWinCFIFuncletOrFuncEnd (SMLoc Loc=SMLoc())
This is used on platforms, such as Windows on ARM64, that require function or funclet sizes to be emitted in .xdata before the End marker is emitted for the frame.
virtual void EmitWinCFIStartChained (SMLoc Loc=SMLoc())
virtual void EmitWinCFIEndChained (SMLoc Loc=SMLoc())
virtual void EmitWinCFIPushReg (MCRegister Register, SMLoc Loc=SMLoc())
virtual void EmitWinCFISetFrame (MCRegister Register, unsigned Offset, SMLoc Loc=SMLoc())
virtual void EmitWinCFIAllocStack (unsigned Size, SMLoc Loc=SMLoc())
virtual void EmitWinCFISaveReg (MCRegister Register, unsigned Offset, SMLoc Loc=SMLoc())
virtual void EmitWinCFISaveXMM (MCRegister Register, unsigned Offset, SMLoc Loc=SMLoc())
virtual void EmitWinCFIPushFrame (bool Code, SMLoc Loc=SMLoc())
virtual void EmitWinCFIEndProlog (SMLoc Loc=SMLoc())
virtual void EmitWinEHHandler (const MCSymbol *Sym, bool Unwind, bool Except, SMLoc Loc=SMLoc())
MCSection * getAssociatedPDataSection (const MCSection *TextSec)
Get the .pdata section used for the given section.
MCSection * getAssociatedXDataSection (const MCSection *TextSec)
Get the .xdata section used for the given section.
virtual void emitSyntaxDirective ()
virtual void emitPseudoProbe (uint64_t Guid, uint64_t Index, uint64_t Type, uint64_t Attr, const MCPseudoProbeInlineStack &InlineStack)
Emit the a pseudo probe into the current section.
void emitRawText (const Twine &String)
If this file is backed by a assembly streamer, this dumps the specified string in the output .s file.
void Finish (SMLoc EndLoc=SMLoc())
Finish emission of machine code.
void maybeEmitDwarf64Mark ()
Emit a special value of 0xffffffff if producing 64-bit debugging info.
virtual void emitDwarfUnitLength (uint64_t Length, const Twine &Comment)
Emit a unit length field.
virtual MCSymbol * emitDwarfUnitLength (const Twine &Prefix, const Twine &Comment)
Emit a unit length field.
virtual void emitDwarfLineStartLabel (MCSymbol *StartSym)
Emit the debug line start label.
virtual void doFinalizationAtSectionEnd (MCSection *Section)
Do finalization for the streamer at the end of a section.
virtual bool isVerboseAsm () const
Return true if this streamer supports verbose assembly and if it is enabled.
virtual bool hasRawTextSupport () const
Return true if this asm streamer supports emitting unformatted text to the .s file with EmitRawText.
virtual void AddComment (const Twine &T, bool EOL=true)
Add a textual comment.
virtual raw_ostream & GetCommentOS ()
Return a raw_ostream that comments can be written to.
virtual void emitRawComment (const Twine &T, bool TabPrefix=true)
Print T and prefix it with the comment string (normally #) and optionally a tab.
virtual void addExplicitComment (const Twine &T)
Add explicit comment T.
virtual void emitExplicitComments ()
Emit added explicit comments.
virtual void AddBlankLine ()
AddBlankLine - Emit a blank line to a .s file to pretty it up.
MCSectionSubPair getCurrentSection () const
Return the current section that the streamer is emitting code to.
MCSection * getCurrentSectionOnly () const
MCSectionSubPair getPreviousSection () const
Return the previous section that the streamer is emitting code to.
unsigned GetSymbolOrder (const MCSymbol *Sym) const
Returns an index to represent the order a symbol was emitted in.
void PushSection ()
Save the current and previous section on the section stack.
bool PopSection ()
Restore the current and previous section from the section stack.
bool SubSection (const MCExpr *Subsection)
virtual void SwitchSection (MCSection *Section, const MCExpr *Subsection=nullptr)
Set the current section where code is being emitted to Section.
void SwitchSectionNoChange (MCSection *Section, const MCExpr *Subsection=nullptr)
Set the current section where code is being emitted to Section.
MCSymbol * endSection (MCSection *Section)
void AssignFragment (MCSymbol *Symbol, MCFragment *Fragment)
Sets the symbol's section.
virtual StringRef getMnemonic (MCInst &MI)
Returns the mnemonic for MI, if the streamer has access to a instruction printer and returns an empty string otherwise.
virtual void emitEHSymAttributes (const MCSymbol *Symbol, MCSymbol *EHSymbol)
virtual void emitLinkerOptions (ArrayRef< std::string > Kind)
Emit the given list Options of strings as linker options into the output.
virtual void emitDataRegion (MCDataRegionType Kind)
Note in the output the specified region Kind.
virtual void emitVersionMin (MCVersionMinType Type, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion)
Specify the Mach-O minimum deployment target version.
virtual void emitBuildVersion (unsigned Platform, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion)
Emit/Specify Mach-O build version command.
virtual void emitDarwinTargetVariantBuildVersion (unsigned Platform, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion)
void emitVersionForTarget (const Triple &Target, const VersionTuple &SDKVersion, const Triple *DarwinTargetVariantTriple, const VersionTuple &DarwinTargetVariantSDKVersion)
virtual void emitXCOFFLocalCommonSymbol (MCSymbol *LabelSym, uint64_t Size, MCSymbol *CsectSym, unsigned ByteAlignment)
Emits an lcomm directive with XCOFF csect information.
virtual void emitXCOFFSymbolLinkageWithVisibility (MCSymbol *Symbol, MCSymbolAttr Linkage, MCSymbolAttr Visibility)
Emit a symbol's linkage and visibility with a linkage directive for XCOFF.
virtual void emitXCOFFRenameDirective (const MCSymbol *Name, StringRef Rename)
Emit a XCOFF .rename directive which creates a synonym for an illegal or undesirable name.
virtual void emitELFSize (MCSymbol *Symbol, const MCExpr *Value)
Emit an ELF .size directive.
virtual void emitELFSymverDirective (const MCSymbol *OriginalSym, StringRef Name, bool KeepOriginalSym)
Emit an ELF .symver directive.
virtual void emitLOHDirective (MCLOHType Kind, const MCLOHArgs &Args)
Emit a Linker Optimization Hint (LOH) directive.
virtual void emitGNUAttribute (unsigned Tag, unsigned Value)
Emit a .gnu_attribute directive.
virtual void emitBinaryData (StringRef Data)
Functionally identical to EmitBytes.
void emitValue (const MCExpr *Value, unsigned Size, SMLoc Loc=SMLoc())
virtual void emitIntValue (uint64_t Value, unsigned Size)
Special case of EmitValue that avoids the client having to pass in a MCExpr for constant integers.
virtual void emitIntValue (APInt Value)
virtual void emitIntValueInHex (uint64_t Value, unsigned Size)
Special case of EmitValue that avoids the client having to pass in a MCExpr for constant integers & prints in Hex format for certain modes.
void emitInt8 (uint64_t Value)
void emitInt16 (uint64_t Value)
void emitInt32 (uint64_t Value)
void emitInt64 (uint64_t Value)
virtual void emitIntValueInHexWithPadding (uint64_t Value, unsigned Size)
Special case of EmitValue that avoids the client having to pass in a MCExpr for constant integers & prints in Hex format for certain modes, pads the field with leading zeros to Size width.
void emitULEB128IntValue (uint64_t Value, unsigned PadTo=0)
Special case of EmitULEB128Value that avoids the client having to pass in a MCExpr for constant integers.
void emitSLEB128IntValue (int64_t Value)
Special case of EmitSLEB128Value that avoids the client having to pass in a MCExpr for constant integers.
void emitSymbolValue (const MCSymbol *Sym, unsigned Size, bool IsSectionRelative=false)
Special case of EmitValue that avoids the client having to pass in a MCExpr for MCSymbols.
void emitFill (uint64_t NumBytes, uint8_t FillValue)
Emit NumBytes bytes worth of the value specified by FillValue.
void emitZeros (uint64_t NumBytes)
Emit NumBytes worth of zeros.
Protected Member Functions
void emitInstToData (const MCInst &Inst, const MCSubtargetInfo &STI) override
void finalizeCGProfileEntry (const MCSymbolRefExpr *&S)
void finalizeCGProfile ()
Protected Member Functions inherited from llvm::MCObjectStreamer
MCObjectStreamer (MCContext &Context, std::unique_ptr< MCAsmBackend > TAB, std::unique_ptr< MCObjectWriter > OW, std::unique_ptr< MCCodeEmitter > Emitter)
~MCObjectStreamer ()
bool changeSectionImpl (MCSection *Section, const MCExpr *Subsection)
void addPendingLabel (MCSymbol *label)
Assign a label to the current Section and Subsection even though a fragment is not yet present.
void flushPendingLabels (MCFragment *F, uint64_t FOffset=0)
If any labels have been emitted but not assigned fragments in the current Section and Subsection, ensure that they get assigned, either to fragment F if possible or to a new data fragment.
Protected Member Functions inherited from llvm::MCStreamer
MCStreamer (MCContext &Ctx)
WinEH::FrameInfo * getCurrentWinFrameInfo ()
virtual void EmitWindowsUnwindTables (WinEH::FrameInfo *Frame)
virtual void EmitWindowsUnwindTables ()
virtual void emitRawTextImpl (StringRef String)
EmitRawText - If this file is backed by an assembly streamer, this dumps the specified string in the output .s file.
bool checkCVLocSection (unsigned FuncId, unsigned FileNo, SMLoc Loc)
Returns true if the the .cv_loc directive is in the right section.
Protected Attributes
const MCSymbol * CurSymbol
Detailed Description
Definition at line 27 of file MCWinCOFFStreamer.h.
Constructor & Destructor Documentation
MCWinCOFFStreamer()
MCWinCOFFStreamer::MCWinCOFFStreamer (MCContext & Context, std::unique_ptr< MCAsmBackend > MAB, std::unique_ptr< MCCodeEmitter > CE, std::unique_ptr< MCObjectWriter > OW)
Definition at line 44 of file MCWinCOFFStreamer.cpp.
Member Function Documentation
BeginCOFFSymbolDef()
void MCWinCOFFStreamer::BeginCOFFSymbolDef (MCSymbol const * Symbol) override virtual
Start emitting COFF symbol definition.
Parameters
Symbol - The symbol to have its External & Type fields set.
Reimplemented from llvm::MCStreamer.
Definition at line 137 of file MCWinCOFFStreamer.cpp.
References CurSymbol, and llvm::ARMBuildAttrs::Symbol.
emitAssemblerFlag()
void MCWinCOFFStreamer::emitAssemblerFlag (MCAssemblerFlag Flag) override virtual
Note in the output the specified Flag.
Reimplemented from llvm::MCStreamer.
Definition at line 91 of file MCWinCOFFStreamer.cpp.
References llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getBackend(), llvm::MCAsmBackend::handleAssemblerFlag(), llvm_unreachable, llvm::MCAF_Code16, llvm::MCAF_Code32, llvm::MCAF_Code64, llvm::MCAF_SubsectionsViaSymbols, and llvm::MCAF_SyntaxUnified.
emitCGProfileEntry()
void MCWinCOFFStreamer::emitCGProfileEntry (const MCSymbolRefExpr * From, const MCSymbolRefExpr * To, uint64_t Count) override virtual
Reimplemented from llvm::MCStreamer.
Definition at line 341 of file MCWinCOFFStreamer.cpp.
References llvm::MCAssembler::CGProfile, From, llvm::MCObjectStreamer::getAssembler(), llvm::MCSymbolRefExpr::getSymbol(), and llvm::MCSymbol::isTemporary().
EmitCOFFImgRel32()
void MCWinCOFFStreamer::EmitCOFFImgRel32 (MCSymbol const * Symbol, int64_t Offset) override virtual
Emits a COFF image relative relocation.
Parameters
Symbol - Symbol the image relative relocation should point to.
Reimplemented from llvm::MCStreamer.
Definition at line 246 of file MCWinCOFFStreamer.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::MCConstantExpr::create(), llvm::MCFixup::create(), llvm::MCBinaryExpr::createAdd(), DF, Fixup, llvm::FK_Data_4, llvm::MCStreamer::getContext(), llvm::MCObjectStreamer::getOrCreateDataFragment(), Offset, llvm::ARMBuildAttrs::Symbol, llvm::MCObjectStreamer::visitUsedSymbol(), and llvm::MCSymbolRefExpr::VK_COFF_IMGREL32.
EmitCOFFSafeSEH()
void MCWinCOFFStreamer::EmitCOFFSafeSEH (MCSymbol const * Symbol) override virtual
Reimplemented from llvm::MCStreamer.
Definition at line 182 of file MCWinCOFFStreamer.cpp.
References Align, llvm::MCSection::getAlignment(), llvm::MCObjectStreamer::getAssembler(), llvm::MCStreamer::getContext(), llvm::MCContext::getObjectFileInfo(), llvm::MCObjectFileInfo::getSXDataSection(), llvm::COFF::IMAGE_SYM_DTYPE_FUNCTION, llvm::MCSymbolCOFF::isSafeSEH(), llvm::MCAssembler::registerSection(), llvm::MCAssembler::registerSymbol(), llvm::COFF::SCT_COMPLEX_TYPE_SHIFT, llvm::MCSection::setAlignment(), llvm::MCSymbolCOFF::setIsSafeSEH(), llvm::MCSymbolCOFF::setType(), llvm::ARMBuildAttrs::Symbol, and llvm::Triple::x86.
EmitCOFFSecRel32()
void MCWinCOFFStreamer::EmitCOFFSecRel32 (MCSymbol const * Symbol, uint64_t Offset) override virtual
Emits a COFF section relative relocation.
Parameters
Symbol - Symbol the section relative relocation should point to.
Reimplemented from llvm::MCStreamer.
Definition at line 228 of file MCWinCOFFStreamer.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::MCConstantExpr::create(), llvm::MCFixup::create(), llvm::MCBinaryExpr::createAdd(), DF, Fixup, llvm::FK_SecRel_4, llvm::MCStreamer::getContext(), llvm::MCObjectStreamer::getOrCreateDataFragment(), Offset, llvm::ARMBuildAttrs::Symbol, and llvm::MCObjectStreamer::visitUsedSymbol().
EmitCOFFSectionIndex()
void MCWinCOFFStreamer::EmitCOFFSectionIndex (MCSymbol const * Symbol) override virtual
Emits a COFF section index.
Parameters
Symbol - Symbol the section number relocation should point to.
Reimplemented from llvm::MCStreamer.
Definition at line 219 of file MCWinCOFFStreamer.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::MCFixup::create(), DF, Fixup, llvm::FK_SecRel_2, llvm::MCStreamer::getContext(), llvm::MCObjectStreamer::getOrCreateDataFragment(), llvm::ARMBuildAttrs::Symbol, and llvm::MCObjectStreamer::visitUsedSymbol().
EmitCOFFSymbolIndex()
void MCWinCOFFStreamer::EmitCOFFSymbolIndex (MCSymbol const * Symbol) override virtual
Emits the symbol table index of a Symbol into the current section.
Reimplemented from llvm::MCStreamer.
Definition at line 208 of file MCWinCOFFStreamer.cpp.
References Align, llvm::MCSection::getAlignment(), llvm::MCObjectStreamer::getAssembler(), llvm::MCStreamer::getCurrentSectionOnly(), llvm::MCAssembler::registerSection(), llvm::MCAssembler::registerSymbol(), llvm::MCSection::setAlignment(), and llvm::ARMBuildAttrs::Symbol.
EmitCOFFSymbolStorageClass()
void MCWinCOFFStreamer::EmitCOFFSymbolStorageClass (int StorageClass) override virtual
Emit the storage class of the symbol.
Parameters
StorageClass - The storage class the symbol should have.
Reimplemented from llvm::MCStreamer.
Definition at line 145 of file MCWinCOFFStreamer.cpp.
References CurSymbol, llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::registerSymbol(), and llvm::COFF::SSC_Invalid.
EmitCOFFSymbolType()
void MCWinCOFFStreamer::EmitCOFFSymbolType (int Type) override virtual
Emit the type of the symbol.
Parameters
Type - A COFF type identifier (see COFF::SymbolType in X86COFF.h)
Reimplemented from llvm::MCStreamer.
Definition at line 161 of file MCWinCOFFStreamer.cpp.
References CurSymbol, llvm::MCObjectStreamer::getAssembler(), and llvm::MCAssembler::registerSymbol().
emitCommonSymbol()
void MCWinCOFFStreamer::emitCommonSymbol (MCSymbol * Symbol, uint64_t Size, unsigned ByteAlignment) override virtual
Emit a common symbol.
Parameters
Symbol - The common symbol to emit.
Size - The size of the common symbol.
ByteAlignment - The alignment of the symbol if non-zero. This must be a power of 2.
Implements llvm::MCStreamer.
Definition at line 265 of file MCWinCOFFStreamer.cpp.
References llvm::LCOMM::ByteAlignment, llvm::MCObjectStreamer::emitBytes(), llvm::MCObjectStreamer::getAssembler(), llvm::MCStreamer::getContext(), llvm::MCObjectFileInfo::getDrectveSection(), llvm::MCContext::getObjectFileInfo(), llvm::MCContext::getTargetTriple(), llvm::Log2_32_Ceil(), llvm::max(), llvm::MCStreamer::PopSection(), llvm::MCStreamer::PushSection(), llvm::MCAssembler::registerSymbol(), llvm::report_fatal_error(), llvm::Check::Size, llvm::MCStreamer::SwitchSection(), llvm::ARMBuildAttrs::Symbol, and T.
emitIdent()
void MCWinCOFFStreamer::emitIdent (StringRef IdentString) override virtual
Emit the "identifiers" directive.
This implements the '.ident "version foo"' assembler directive.
Reimplemented from llvm::MCStreamer.
Definition at line 333 of file MCWinCOFFStreamer.cpp.
References llvm_unreachable.
emitInstToData()
void MCWinCOFFStreamer::emitInstToData (const MCInst & Inst, const MCSubtargetInfo & STI) override protected virtual
Implements llvm::MCObjectStreamer.
Definition at line 51 of file MCWinCOFFStreamer.cpp.
References DF, llvm::numbers::e, llvm::MCCodeEmitter::encodeInstruction(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getEmitter(), llvm::getOffset(), and llvm::MCObjectStreamer::getOrCreateDataFragment().
emitLabel()
void MCWinCOFFStreamer::emitLabel (MCSymbol * Symbol, SMLoc Loc = SMLoc()) override virtual
Emit a label for Symbol into the current section.
This corresponds to an assembler statement such as: foo:
Parameters
Symbol - The symbol to emit. A given symbol should only be emitted as a label once, and symbols emitted as a label should never be used in an assignment.
Reimplemented from llvm::MCObjectStreamer.
Definition at line 86 of file MCWinCOFFStreamer.cpp.
References llvm::MCObjectStreamer::emitLabel(), and llvm::ARMBuildAttrs::Symbol.
Referenced by emitLocalCommonSymbol().
emitLocalCommonSymbol()
void MCWinCOFFStreamer::emitLocalCommonSymbol (MCSymbol * Symbol, uint64_t Size, unsigned ByteAlignment) override virtual
Emit a local common (.lcomm) symbol.
Parameters
Symbol - The common symbol to emit.
Size - The size of the common symbol.
ByteAlignment - The alignment of the common symbol in bytes.
Reimplemented from llvm::MCStreamer.
Definition at line 297 of file MCWinCOFFStreamer.cpp.
References llvm::LCOMM::ByteAlignment, emitLabel(), llvm::MCObjectStreamer::emitValueToAlignment(), llvm::MCStreamer::emitZeros(), llvm::MCObjectFileInfo::getBSSSection(), llvm::MCStreamer::getContext(), llvm::MCContext::getObjectFileInfo(), llvm::MCStreamer::PopSection(), llvm::MCStreamer::PushSection(), llvm::ARMBuildAttrs::Section, llvm::Check::Size, llvm::MCStreamer::SwitchSection(), and llvm::ARMBuildAttrs::Symbol.
emitSymbolAttribute()
bool MCWinCOFFStreamer::emitSymbolAttribute (MCSymbol * Symbol, MCSymbolAttr Attribute) override virtual
Add the given Attribute to Symbol.
Implements llvm::MCStreamer.
Definition at line 111 of file MCWinCOFFStreamer.cpp.
References llvm::MCObjectStreamer::getAssembler(), llvm_unreachable, llvm::MCSA_AltEntry, llvm::MCSA_Global, llvm::MCSA_Weak, llvm::MCSA_WeakReference, llvm::MCAssembler::registerSymbol(), and llvm::ARMBuildAttrs::Symbol.
Referenced by emitWeakReference().
emitSymbolDesc()
void MCWinCOFFStreamer::emitSymbolDesc (MCSymbol * Symbol, unsigned DescValue) override virtual
Set the DescValue for the Symbol.
Parameters
Symbol - The symbol to have its n_desc field set.
DescValue - The value to set into the n_desc field.
Reimplemented from llvm::MCStreamer.
Definition at line 133 of file MCWinCOFFStreamer.cpp.
References llvm_unreachable.
emitTBSSSymbol()
void MCWinCOFFStreamer::emitTBSSSymbol (MCSection * Section, MCSymbol * Symbol, uint64_t Size, unsigned ByteAlignment) override virtual
Emit a thread local bss (.tbss) symbol.
Parameters
Section - The thread local common section.
Symbol - The thread local common symbol to emit.
Size - The size of the symbol.
ByteAlignment - The alignment of the thread local common symbol if non-zero. This must be a power of 2 on some targets.
Reimplemented from llvm::MCStreamer.
Definition at line 327 of file MCWinCOFFStreamer.cpp.
References llvm_unreachable.
emitThumbFunc()
void MCWinCOFFStreamer::emitThumbFunc (MCSymbol * Func) override virtual
Note in the output that the specified Func is a Thumb mode function (ARM target only).
Reimplemented from llvm::MCStreamer.
Definition at line 107 of file MCWinCOFFStreamer.cpp.
References llvm_unreachable.
emitWeakReference()
void MCWinCOFFStreamer::emitWeakReference (MCSymbol * Alias, const MCSymbol * Symbol) override virtual
Emit an weak reference from Alias to Symbol.
This corresponds to an assembler statement such as: .weakref alias, symbol
Parameters
Alias - The alias that is being created.
Symbol - The symbol being aliased.
Reimplemented from llvm::MCObjectStreamer.
Definition at line 311 of file MCWinCOFFStreamer.cpp.
References llvm::MCSymbolRefExpr::create(), emitSymbolAttribute(), llvm::MCObjectStreamer::getAssembler(), llvm::MCStreamer::getContext(), llvm::MCSA_Weak, llvm::MCAssembler::registerSymbol(), llvm::ARMBuildAttrs::Symbol, and llvm::MCSymbolRefExpr::VK_WEAKREF.
EmitWinEHHandlerData()
void MCWinCOFFStreamer::EmitWinEHHandlerData (SMLoc Loc) override virtual
Reimplemented from llvm::MCStreamer.
Definition at line 337 of file MCWinCOFFStreamer.cpp.
References llvm_unreachable.
emitZerofill()
void MCWinCOFFStreamer::emitZerofill (MCSection * Section, MCSymbol * Symbol, uint64_t Size, unsigned ByteAlignment, SMLoc Loc = SMLoc()) override virtual
Emit the zerofill section and an optional symbol.
Parameters
Section - The zerofill section to create and or to put the symbol
Symbol - The zerofill symbol to emit, if non-NULL.
Size - The size of the zerofill symbol.
ByteAlignment - The alignment of the zerofill symbol if non-zero. This must be a power of 2 on some targets.
Implements llvm::MCStreamer.
Definition at line 321 of file MCWinCOFFStreamer.cpp.
References llvm_unreachable.
EndCOFFSymbolDef()
void MCWinCOFFStreamer::EndCOFFSymbolDef () override virtual
Marks the end of the symbol definition.
Reimplemented from llvm::MCStreamer.
Definition at line 176 of file MCWinCOFFStreamer.cpp.
References CurSymbol.
finalizeCGProfile()
void MCWinCOFFStreamer::finalizeCGProfile () protected
Definition at line 357 of file MCWinCOFFStreamer.cpp.
References E, finalizeCGProfileEntry(), and llvm::MCObjectStreamer::getAssembler().
Referenced by finishImpl().
finalizeCGProfileEntry()
void MCWinCOFFStreamer::finalizeCGProfileEntry (const MCSymbolRefExpr *& S) protected
Definition at line 349 of file MCWinCOFFStreamer.cpp.
References llvm::MCObjectStreamer::getAssembler(), llvm::MCSymbolRefExpr::getSymbol(), and llvm::MCAssembler::registerSymbol().
Referenced by finalizeCGProfile().
finishImpl()
void MCWinCOFFStreamer::finishImpl () override virtual
Streamer specific finalization.
Reimplemented from llvm::MCObjectStreamer.
Definition at line 364 of file MCWinCOFFStreamer.cpp.
References finalizeCGProfile(), and llvm::MCObjectStreamer::finishImpl().
initSections()
void MCWinCOFFStreamer::initSections (bool NoExecStack, const MCSubtargetInfo & STI) override virtual
Create the default sections and set the initial one.
Reimplemented from llvm::MCStreamer.
Definition at line 69 of file MCWinCOFFStreamer.cpp.
References llvm::MCObjectStreamer::emitCodeAlignment(), llvm::MCStreamer::getContext(), and llvm::MCStreamer::SwitchSection().
reset()
void llvm::MCWinCOFFStreamer::reset () inline override virtual
state management
Reimplemented from llvm::MCObjectStreamer.
Definition at line 34 of file MCWinCOFFStreamer.h.
References CurSymbol, and llvm::MCObjectStreamer::reset().
Member Data Documentation
CurSymbol
const MCSymbol* llvm::MCWinCOFFStreamer::CurSymbol protected
Definition at line 75 of file MCWinCOFFStreamer.h.
Referenced by BeginCOFFSymbolDef(), EmitCOFFSymbolStorageClass(), EmitCOFFSymbolType(), EndCOFFSymbolDef(), and reset().
The documentation for this class was generated from the following files:
include/llvm/MC/MCWinCOFFStreamer.h
lib/MC/MCWinCOFFStreamer.cpp