LLVM: llvm::Float2IntPass Class Reference
llvm::Float2IntPass Class Reference
#include "llvm/Transforms/Scalar/Float2Int.h"
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
bool runImpl (Function &F, const DominatorTree &DT)
Public Member Functions inherited from llvm::PassInfoMixin< Float2IntPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< Float2IntPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 26 of file Float2Int.h.
Member Function Documentation
run()
PreservedAnalyses llvm::Float2IntPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 541 of file Float2Int.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PreservedAnalyses::preserveSet(), and runImpl().
runImpl()
bool Float2IntPass::runImpl (Function & F, const DominatorTree & DT)
Definition at line 517 of file Float2Int.cpp.
References llvm::dbgs(), F, LLVM_DEBUG, and Modified.
Referenced by run().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/Float2Int.h
lib/Transforms/Scalar/Float2Int.cpp