LLVM: llvm::MCDecodedPseudoProbe Class Reference
llvm::MCDecodedPseudoProbe Class Reference
#include "llvm/MC/MCPseudoProbe.h"
Public Member Functions
MCDecodedPseudoProbe (uint64_t Ad, uint64_t G, uint32_t I, PseudoProbeType K, uint8_t At, MCDecodedPseudoProbeInlineTree *Tree)
uint64_t getAddress () const
void setAddress (uint64_t Addr)
MCDecodedPseudoProbeInlineTree * getInlineTreeNode () const
void getInlineContext (SmallVectorImpl< MCPseduoProbeFrameLocation > &ContextStack, const GUIDProbeFunctionMap &GUID2FuncMAP) const
std::string getInlineContextStr (const GUIDProbeFunctionMap &GUID2FuncMAP) const
void print (raw_ostream &OS, const GUIDProbeFunctionMap &GUID2FuncMAP, bool ShowName) const
Public Member Functions inherited from llvm::MCPseudoProbeBase
MCPseudoProbeBase (uint64_t G, uint64_t I, uint64_t At, uint8_t T)
bool isEntry () const
uint64_t getGuid () const
uint64_t getIndex () const
uint8_t getAttributes () const
uint8_t getType () const
bool isBlock () const
bool isIndirectCall () const
bool isDirectCall () const
bool isCall () const
void setAttributes (uint8_t Attr)
Additional Inherited Members
Protected Attributes inherited from llvm::MCPseudoProbeBase
uint64_t Guid
uint64_t Index
uint8_t Attributes
uint8_t Type
Static Protected Attributes inherited from llvm::MCPseudoProbeBase
static const uint32_t PseudoProbeFirstId = 1
Detailed Description
Definition at line 166 of file MCPseudoProbe.h.
Constructor & Destructor Documentation
MCDecodedPseudoProbe()
llvm::MCDecodedPseudoProbe::MCDecodedPseudoProbe (uint64_t Ad, uint64_t G, uint32_t I, PseudoProbeType K, uint8_t At, MCDecodedPseudoProbeInlineTree * Tree) inline
Definition at line 171 of file MCPseudoProbe.h.
References llvm::Address.
Member Function Documentation
getAddress()
uint64_t llvm::MCDecodedPseudoProbe::getAddress () const inline
Definition at line 176 of file MCPseudoProbe.h.
References llvm::Address.
getInlineContext()
void MCDecodedPseudoProbe::getInlineContext (SmallVectorImpl< MCPseduoProbeFrameLocation > & ContextStack, const GUIDProbeFunctionMap & GUID2FuncMAP) const
Definition at line 224 of file MCPseudoProbe.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorTemplateCommon< T, typename >::end(), getProbeFNameForGUID(), llvm::MCDecodedPseudoProbeInlineTree::hasInlineSite(), llvm::MCDecodedPseudoProbeInlineTree::ISite, llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::Parent, llvm::reverse(), and llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::MCPseudoProbeDecoder::getInlineContextForProbe().
getInlineContextStr()
std::string MCDecodedPseudoProbe::getInlineContextStr (const GUIDProbeFunctionMap & GUID2FuncMAP) const
Definition at line 242 of file MCPseudoProbe.cpp.
getInlineTreeNode()
MCDecodedPseudoProbeInlineTree* llvm::MCDecodedPseudoProbe::getInlineTreeNode () const inline
Definition at line 180 of file MCPseudoProbe.h.
Referenced by llvm::MCPseudoProbeDecoder::getInlinerDescForProbe().
print()
void MCDecodedPseudoProbe::print (raw_ostream & OS, const GUIDProbeFunctionMap & GUID2FuncMAP, bool ShowName) const
Definition at line 258 of file MCPseudoProbe.cpp.
References getProbeFNameForGUID(), Index, PseudoProbeTypeStr, and llvm::StringRef::str().
setAddress()
void llvm::MCDecodedPseudoProbe::setAddress (uint64_t Addr) inline
Definition at line 178 of file MCPseudoProbe.h.
References Addr, and llvm::Address.
The documentation for this class was generated from the following files:
include/llvm/MC/MCPseudoProbe.h
lib/MC/MCPseudoProbe.cpp