LLVM: llvm::TypeSize Class Reference
llvm::TypeSize Class Reference
#include "llvm/Support/TypeSize.h"
Public Member Functions
TypeSize (const LinearPolySize< TypeSize > &V)
TypeSize (ScalarTy MinVal, bool IsScalable)
ScalarTy getFixedSize () const
ScalarTy getKnownMinSize () const
operator ScalarTy () const
Public Member Functions inherited from llvm::LinearPolySize< TypeSize >
ScalarTy getKnownMinValue () const
Returns the minimum value this size can represent.
bool isScalable () const
Returns whether the size is scaled by a runtime quantity (vscale).
bool isKnownEven () const
A return value of true indicates we know at compile time that the number of elements (vscale * Min) is definitely even.
bool isKnownMultipleOf (ScalarTy RHS) const
This function tells the caller whether the element count is known at compile time to be a multiple of the scalar value RHS.
ScalarTy getFixedValue () const
TypeSize divideCoefficientBy (ScalarTy RHS) const
We do not provide the '/' operator here because division for polynomial types does not work in the same way as for normal integer types.
TypeSize coefficientNextPowerOf2 () const
void print (raw_ostream &OS) const
Printing function.
Public Member Functions inherited from llvm::UnivariateLinearPolyBase< LeafTy >
bool operator== (const UnivariateLinearPolyBase &RHS) const
bool operator!= (const UnivariateLinearPolyBase &RHS) const
bool isZero () const
bool isNonZero () const
operator bool () const
ScalarTy getValue (unsigned Dim) const
LeafTy getWithIncrement (ScalarTy RHS) const
Add RHS to the value at the univariate dimension.
LeafTy getWithDecrement (ScalarTy RHS) const
Subtract RHS from the value at the univariate dimension.
Static Public Member Functions
static TypeSize Fixed (ScalarTy MinVal)
static TypeSize Scalable (ScalarTy MinVal)
Static Public Member Functions inherited from llvm::LinearPolySize< TypeSize >
static TypeSize getFixed (ScalarTy MinVal)
static TypeSize getScalable (ScalarTy MinVal)
static TypeSize get (ScalarTy MinVal, bool Scalable)
static TypeSize getNull ()
static bool isKnownLT (const LinearPolySize &LHS, const LinearPolySize &RHS)
static bool isKnownGT (const LinearPolySize &LHS, const LinearPolySize &RHS)
static bool isKnownLE (const LinearPolySize &LHS, const LinearPolySize &RHS)
static bool isKnownGE (const LinearPolySize &LHS, const LinearPolySize &RHS)
Friends
TypeSize operator* (const TypeSize &LHS, const int RHS)
TypeSize operator* (const TypeSize &LHS, const unsigned RHS)
TypeSize operator* (const TypeSize &LHS, const int64_t RHS)
TypeSize operator* (const int LHS, const TypeSize &RHS)
TypeSize operator* (const unsigned LHS, const TypeSize &RHS)
TypeSize operator* (const int64_t LHS, const TypeSize &RHS)
TypeSize operator* (const uint64_t LHS, const TypeSize &RHS)
Additional Inherited Members
Public Types inherited from llvm::LinearPolySize< TypeSize >
enum Dims
using ScalarTy = typename UnivariateLinearPolyBase< TypeSize >::ScalarTy
Public Types inherited from llvm::UnivariateLinearPolyBase< LeafTy >
using ScalarTy = typename LinearPolyBaseTypeTraits< LeafTy >::ScalarTy
Static Public Attributes inherited from llvm::UnivariateLinearPolyBase< LeafTy >
static constexpr auto Dimensions = LinearPolyBaseTypeTraits<LeafTy>::Dimensions
Protected Member Functions inherited from llvm::LinearPolySize< TypeSize >
LinearPolySize (ScalarTy MinVal, Dims D)
LinearPolySize (const UnivariateLinearPolyBase< TypeSize > &V)
Protected Member Functions inherited from llvm::UnivariateLinearPolyBase< LeafTy >
UnivariateLinearPolyBase (ScalarTy Val, unsigned UnivariateDim)
Protected Attributes inherited from llvm::UnivariateLinearPolyBase< LeafTy >
ScalarTy Value
unsigned UnivariateDim
Detailed Description
Definition at line 416 of file TypeSize.h.
Constructor & Destructor Documentation
TypeSize() [1/2]
llvm::TypeSize::TypeSize (const LinearPolySize< TypeSize > & V) inline
Definition at line 418 of file TypeSize.h.
Referenced by Fixed(), and Scalable().
TypeSize() [2/2]
llvm::TypeSize::TypeSize (ScalarTy MinVal, bool IsScalable) inline
Definition at line 419 of file TypeSize.h.
Member Function Documentation
Fixed()
static TypeSize llvm::TypeSize::Fixed (ScalarTy MinVal) inline static
Definition at line 422 of file TypeSize.h.
References TypeSize().
Referenced by combineLoad(), combineStore(), combineTargetShuffle(), convertCalleeSaveRestoreToSPPrePostIncDec(), EmitUnrolledSetTag(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), getBROADCAST_LOAD(), llvm::DataLayout::getGEPIndexForOffset(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), llvm::AArch64InstrInfo::getMemOpInfo(), getMemsetStores(), getParamsForOneTrueMaskedElt(), llvm::LLT::getSizeInBits(), llvm::MVT::getSizeInBits(), llvm::DataLayout::getTypeSizeInBits(), llvm::LegalizerHelper::lowerExtractInsertVectorElt(), lowerShuffleAsBroadcast(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), lowerVECTOR_SHUFFLE(), llvm::ARMTargetLowering::PerformMVETruncCombine(), PerformSplittingMVEEXTToWideningLoad(), PerformSplittingMVETruncToNarrowingStores(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), llvm::AArch64TargetLowering::ReconstructShuffle(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), scalarizeVectorStore(), ShrinkLoadReplaceStoreWithStore(), llvm::TargetLowering::SimplifySetCC(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), and splitVectorStore().
getFixedSize()
ScalarTy llvm::TypeSize::getFixedSize () const inline
Definition at line 425 of file TypeSize.h.
References llvm::LinearPolySize< TypeSize >::getFixedValue().
Referenced by areExtractShuffleVectors(), llvm::slpvectorizer::BoUpSLP::BoUpSLP(), buildCopyFromRegs(), buildFrameDebugInfo(), llvm::ARMTargetLowering::canCombineStoreAndExtract(), evaluateGEPOffsetExpression(), llvm::InstCombinerImpl::foldCmpLoadFromIndexedGlobal(), llvm::InstCombinerImpl::foldGEPICmp(), llvm::TargetTransformInfoImplBase::getCastInstrCost(), getFauxShuffleMask(), llvm::EVT::getFixedSizeInBits(), llvm::MVT::getFixedSizeInBits(), llvm::DataLayout::getGEPIndexForOffset(), llvm::ARMTTIImpl::getInterleavedMemoryOpCost(), llvm::X86TTIImpl::getLoadStoreVecRegBitWidth(), llvm::HexagonTTIImpl::getMemoryOpCost(), llvm::getPtrStride(), llvm::EVT::getScalarSizeInBits(), llvm::MVT::getScalarSizeInBits(), llvm::DataLayout::getTypeSizeInBits(), llvm::SystemZTTIImpl::getVectorTruncCost(), AAPointerInfoFloating::handleAccess(), llvm::InlineFunction(), llvm::InductionDescriptor::isInductionPHI(), llvm::RISCVTTIImpl::isLegalMaskedGatherScatter(), llvm::RISCVTTIImpl::isLegalMaskedLoadStore(), isLoadInvariantInLoop(), llvm::SystemZTargetLowering::isTruncateFree(), llvm::AArch64TargetLowering::isTruncateFree(), llvm::MSP430TargetLowering::isTruncateFree(), llvm::LoopVectorizationPlanner::planInVPlanNativePath(), llvm::SCEVExpander::replaceCongruentIVs(), UpgradeMaskedLoad(), valueCoversEntireFragment(), llvm::LLT::vector(), and widenSubVector().
getKnownMinSize()
ScalarTy llvm::TypeSize::getKnownMinSize () const inline
Definition at line 426 of file TypeSize.h.
References llvm::LinearPolySize< TypeSize >::getKnownMinValue().
Referenced by computeKnownBitsFromOperator(), llvm::SelectionDAG::CreateStackTemporary(), extractSubReg(), findMemType(), llvm::AArch64TargetLowering::functionArgumentNeedsConsecutiveRegisters(), llvm::AArch64InstrInfo::getMemOperandWithOffsetWidth(), llvm::LLT::getSizeInBytes(), llvm::EVT::getStoreSize(), llvm::MVT::getStoreSize(), llvm::DataLayout::getTypeStoreSize(), llvm::TargetLoweringBase::getVectorTypeBreakdown(), llvm::TargetLowering::IncrementMemoryAddress(), insertSubReg(), llvm::isAArch64FrameOffsetLegal(), llvm::CastInst::isBitCastable(), isPackedVectorType(), llvm::RISCVTargetLowering::joinRegisterPartsIntoValue(), LowerSVEIntrinsicEXT(), llvm::PatternMatch::VScaleVal_match::match(), llvm::MemSDNode::MemSDNode(), performGatherLoadCombine(), performLD1Combine(), performScatterStoreCombine(), llvm::FunctionLoweringInfo::set(), and llvm::RISCVTargetLowering::splitValueIntoRegisterParts().
operator ScalarTy()
TypeSize::operator TypeSize::ScalarTy () const
Definition at line 50 of file TypeSize.cpp.
References llvm::LinearPolySize< TypeSize >::getFixedValue(), llvm::LinearPolySize< TypeSize >::getKnownMinValue(), llvm::LinearPolySize< TypeSize >::isScalable(), and llvm::reportInvalidSizeRequest().
Scalable()
static TypeSize llvm::TypeSize::Scalable (ScalarTy MinVal) inline static
Definition at line 423 of file TypeSize.h.
References TypeSize().
Referenced by llvm::AArch64InstrInfo::getMemOpInfo(), and llvm::MVT::getSizeInBits().
Friends And Related Function Documentation
operator* [1/7]
TypeSize operator* (const int LHS, const TypeSize & RHS) friend
Definition at line 465 of file TypeSize.h.
operator* [2/7]
TypeSize operator* (const int64_t LHS, const TypeSize & RHS) friend
Definition at line 471 of file TypeSize.h.
operator* [3/7]
TypeSize operator* (const TypeSize & LHS, const int RHS) friend
Definition at line 456 of file TypeSize.h.
operator* [4/7]
TypeSize operator* (const TypeSize & LHS, const int64_t RHS) friend
Definition at line 462 of file TypeSize.h.
operator* [5/7]
TypeSize operator* (const TypeSize & LHS, const unsigned RHS) friend
Definition at line 459 of file TypeSize.h.
operator* [6/7]
TypeSize operator* (const uint64_t LHS, const TypeSize & RHS) friend
Definition at line 474 of file TypeSize.h.
operator* [7/7]
TypeSize operator* (const unsigned LHS, const TypeSize & RHS) friend
Definition at line 468 of file TypeSize.h.
The documentation for this class was generated from the following files:
include/llvm/Support/TypeSize.h
lib/Support/TypeSize.cpp