LLVM: llvm::DotCfgChangeReporter Class Reference
llvm::DotCfgChangeReporter Class Reference
#include "llvm/Passes/StandardInstrumentations.h"
Public Member Functions
DotCfgChangeReporter (bool Verbose)
~DotCfgChangeReporter () override
void registerCallbacks (PassInstrumentationCallbacks &PIC)
Public Member Functions inherited from llvm::ChangeReporter< IRDataT< DCData > >
virtual ~ChangeReporter ()
void saveIRBeforePass (Any IR, StringRef PassID)
void handleIRAfterPass (Any IR, StringRef PassID)
void handleInvalidatedPass (StringRef PassID)
Protected Member Functions
bool initializeHTML ()
void handleInitialIR (Any IR) override
void generateIRRepresentation (Any IR, StringRef PassID, IRDataT< DCData > &Output) override
void omitAfter (StringRef PassID, std::string &Name) override
void handleAfter (StringRef PassID, std::string &Name, const IRDataT< DCData > &Before, const IRDataT< DCData > &After, Any) override
void handleInvalidated (StringRef PassID) override
void handleFiltered (StringRef PassID, std::string &Name) override
void handleIgnored (StringRef PassID, std::string &Name) override
void handleFunctionCompare (StringRef Name, StringRef Prefix, StringRef PassID, StringRef Divider, bool InModule, unsigned Minor, const FuncDataT< DCData > &Before, const FuncDataT< DCData > &After)
Protected Member Functions inherited from llvm::ChangeReporter< IRDataT< DCData > >
ChangeReporter (bool RunInVerboseMode)
void registerRequiredCallbacks (PassInstrumentationCallbacks &PIC)
bool isInterestingFunction (const Function &F)
bool isInterestingPass (StringRef PassID)
bool isInteresting (Any IR, StringRef PassID)
Static Protected Member Functions
static std::string genHTML (StringRef Text, StringRef DotFile, StringRef PDFFileName)
Protected Attributes
unsigned N = 0
std::unique_ptr< raw_fd_ostream > HTML
Protected Attributes inherited from llvm::ChangeReporter< IRDataT< DCData > >
std::vector< IRDataT< DCData > > BeforeStack
bool InitialIR
const bool VerboseMode
Detailed Description
Definition at line 452 of file StandardInstrumentations.h.
Constructor & Destructor Documentation
DotCfgChangeReporter()
llvm::DotCfgChangeReporter::DotCfgChangeReporter (bool Verbose)
Definition at line 1886 of file StandardInstrumentations.cpp.
References llvm::Verbose.
~DotCfgChangeReporter()
llvm::DotCfgChangeReporter::~DotCfgChangeReporter () override
Definition at line 2065 of file StandardInstrumentations.cpp.
References HTML.
Member Function Documentation
generateIRRepresentation()
void llvm::DotCfgChangeReporter::generateIRRepresentation (Any IR, StringRef PassID, IRDataT< DCData > & Output) override protected virtual
Implements llvm::ChangeReporter< IRDataT< DCData > >.
Definition at line 1974 of file StandardInstrumentations.cpp.
References llvm::IRComparer< T >::analyzeIR(), llvm::Data, and IR.
genHTML()
std::string llvm::DotCfgChangeReporter::genHTML (StringRef Text, StringRef DotFile, StringRef PDFFileName) static protected
Definition at line 1931 of file StandardInstrumentations.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::SmallString< InternalLen >::c_str(), DotBinary, DotCfgDir, llvm::sys::ExecuteAndWait(), llvm::sys::findProgramByName(), llvm::formatv(), and llvm::None.
Referenced by handleFunctionCompare().
handleAfter()
void llvm::DotCfgChangeReporter::handleAfter (StringRef PassID, std::string & Name, const IRDataT< DCData > & Before, const IRDataT< DCData > & After, Any IR) override protected virtual
Implements llvm::ChangeReporter< IRDataT< DCData > >.
Definition at line 1988 of file StandardInstrumentations.cpp.
References assert(), llvm::IRComparer< T >::compare(), handleFunctionCompare(), HTML, IR, and N.
handleFiltered()
void llvm::DotCfgChangeReporter::handleFiltered (StringRef PassID, std::string & Name) override protected virtual
Implements llvm::ChangeReporter< IRDataT< DCData > >.
Definition at line 2012 of file StandardInstrumentations.cpp.
References assert(), llvm::formatv(), HTML, and N.
handleFunctionCompare()
void llvm::DotCfgChangeReporter::handleFunctionCompare (StringRef Name, StringRef Prefix, StringRef PassID, StringRef Divider, bool InModule, unsigned Minor, const FuncDataT< DCData > & Before, const FuncDataT< DCData > & After) protected
Definition at line 1889 of file StandardInstrumentations.cpp.
References assert(), llvm::sys::fs::createUniquePath(), llvm::errs(), llvm::formatv(), genHTML(), llvm::FuncDataT< T >::getEntryBlockName(), HTML, N, Number, llvm::cl::Prefix, llvm::sys::fs::remove(), and llvm::Twine::str().
Referenced by handleAfter(), and handleInitialIR().
handleIgnored()
void llvm::DotCfgChangeReporter::handleIgnored (StringRef PassID, std::string & Name) override protected virtual
Implements llvm::ChangeReporter< IRDataT< DCData > >.
Definition at line 2021 of file StandardInstrumentations.cpp.
References assert(), llvm::formatv(), HTML, and N.
handleInitialIR()
void llvm::DotCfgChangeReporter::handleInitialIR (Any IR) override protected virtual
Implements llvm::ChangeReporter< IRDataT< DCData > >.
Definition at line 1950 of file StandardInstrumentations.cpp.
References llvm::IRComparer< T >::analyzeIR(), assert(), llvm::IRComparer< T >::compare(), llvm::Data, handleFunctionCompare(), HTML, IR, and N.
handleInvalidated()
void llvm::DotCfgChangeReporter::handleInvalidated (StringRef PassID) override protected virtual
Implements llvm::ChangeReporter< IRDataT< DCData > >.
Definition at line 2004 of file StandardInstrumentations.cpp.
References assert(), llvm::formatv(), HTML, and N.
initializeHTML()
bool llvm::DotCfgChangeReporter::initializeHTML () protected
Definition at line 2029 of file StandardInstrumentations.cpp.
References DotCfgDir, and HTML.
Referenced by registerCallbacks().
omitAfter()
void llvm::DotCfgChangeReporter::omitAfter (StringRef PassID, std::string & Name) override protected virtual
Implements llvm::ChangeReporter< IRDataT< DCData > >.
Definition at line 1979 of file StandardInstrumentations.cpp.
References assert(), llvm::formatv(), HTML, and N.
registerCallbacks()
void llvm::DotCfgChangeReporter::registerCallbacks (PassInstrumentationCallbacks & PIC)
Definition at line 2090 of file StandardInstrumentations.cpp.
References assert(), llvm::SmallString< InternalLen >::c_str(), llvm::dbgs(), DotCfgDir, llvm::SmallVectorBase< Size_T >::empty(), llvm::sys::fs::expand_tilde(), initializeHTML(), llvm::sys::fs::make_absolute(), PIC, PrintChanged, PrintChangedDotCfgQuiet, PrintChangedDotCfgVerbose, and llvm::ChangeReporter< IRDataT< DCData > >::registerRequiredCallbacks().
Referenced by llvm::StandardInstrumentations::registerCallbacks().
Member Data Documentation
HTML
std::unique_ptr<raw_fd_ostream> llvm::DotCfgChangeReporter::HTML protected
Definition at line 491 of file StandardInstrumentations.h.
Referenced by handleAfter(), handleFiltered(), handleFunctionCompare(), handleIgnored(), handleInitialIR(), handleInvalidated(), initializeHTML(), omitAfter(), and ~DotCfgChangeReporter().
N
unsigned llvm::DotCfgChangeReporter::N = 0 protected
Definition at line 490 of file StandardInstrumentations.h.
Referenced by handleAfter(), handleFiltered(), handleFunctionCompare(), handleIgnored(), handleInitialIR(), handleInvalidated(), and omitAfter().
The documentation for this class was generated from the following files:
include/llvm/Passes/StandardInstrumentations.h
lib/Passes/StandardInstrumentations.cpp