LLVM: llvm::MCPseudoProbe Class Reference
llvm::MCPseudoProbe Class Reference
Instances of this class represent a pseudo probe instance for a pseudo probe table entry, which is created during a machine instruction is assembled and uses an address from a temporary label created at the current address in the current section.
#include "llvm/MC/MCPseudoProbe.h"
Public Member Functions
MCPseudoProbe (MCSymbol *Label, uint64_t Guid, uint64_t Index, uint64_t Type, uint64_t Attributes)
MCSymbol * getLabel () const
void emit (MCObjectStreamer *MCOS, const MCPseudoProbe *LastProbe) const
Public Member Functions inherited from llvm::MCPseudoProbeBase
MCPseudoProbeBase (uint64_t G, uint64_t I, uint64_t At, uint8_t T)
bool isEntry () const
uint64_t getGuid () const
uint64_t getIndex () const
uint8_t getAttributes () const
uint8_t getType () const
bool isBlock () const
bool isIndirectCall () const
bool isDirectCall () const
bool isCall () const
void setAttributes (uint8_t Attr)
Additional Inherited Members
Protected Attributes inherited from llvm::MCPseudoProbeBase
uint64_t Guid
uint64_t Index
uint8_t Attributes
uint8_t Type
Static Protected Attributes inherited from llvm::MCPseudoProbeBase
static const uint32_t PseudoProbeFirstId = 1
Detailed Description
Instances of this class represent a pseudo probe instance for a pseudo probe table entry, which is created during a machine instruction is assembled and uses an address from a temporary label created at the current address in the current section.
Definition at line 147 of file MCPseudoProbe.h.
Constructor & Destructor Documentation
MCPseudoProbe()
llvm::MCPseudoProbe::MCPseudoProbe (MCSymbol * Label, uint64_t Guid, uint64_t Index, uint64_t Type, uint64_t Attributes) inline
Definition at line 151 of file MCPseudoProbe.h.
References assert(), and llvm::MCPseudoProbeBase::Attributes.
Member Function Documentation
emit()
void MCPseudoProbe::emit (MCObjectStreamer * MCOS, const MCPseudoProbe * LastProbe) const
Definition at line 42 of file MCPseudoProbe.cpp.
References llvm::AddressDelta, assert(), Attributes, buildSymbolDiff(), llvm::dbgs(), llvm::MCPseudoProbeTable::DdgPrintIndent, llvm::MCStreamer::emitInt8(), llvm::MCStreamer::emitSLEB128IntValue(), llvm::MCStreamer::emitSymbolValue(), llvm::MCStreamer::emitULEB128IntValue(), llvm::MCContext::getAsmInfo(), llvm::MCObjectStreamer::getAssemblerPtr(), llvm::MCAsmInfo::getCodePointerSize(), llvm::MCStreamer::getContext(), getLabel(), llvm::raw_ostream::indent(), Index, llvm::MCObjectStreamer::insert(), and LLVM_DEBUG.
getLabel()
MCSymbol* llvm::MCPseudoProbe::getLabel () const inline
Definition at line 159 of file MCPseudoProbe.h.
Referenced by emit().
The documentation for this class was generated from the following files:
include/llvm/MC/MCPseudoProbe.h
lib/MC/MCPseudoProbe.cpp