LLVM: llvm::orc::SymbolStringPtr Class Reference
llvm::orc::SymbolStringPtr Class Reference
Pointer to a pooled string representing a symbol name.
#include "llvm/ExecutionEngine/Orc/SymbolStringPool.h"
Public Member Functions
SymbolStringPtr ()=default
SymbolStringPtr (std::nullptr_t)
SymbolStringPtr (const SymbolStringPtr &Other)
SymbolStringPtr & operator= (const SymbolStringPtr &Other)
SymbolStringPtr (SymbolStringPtr &&Other)
SymbolStringPtr & operator= (SymbolStringPtr &&Other)
~SymbolStringPtr ()
operator bool () const
StringRef operator* () const
Friends
class OrcV2CAPIHelper
class SymbolStringPool
struct DenseMapInfo< SymbolStringPtr >
bool operator== (const SymbolStringPtr &LHS, const SymbolStringPtr &RHS)
bool operator!= (const SymbolStringPtr &LHS, const SymbolStringPtr &RHS)
bool operator< (const SymbolStringPtr &LHS, const SymbolStringPtr &RHS)
Detailed Description
Pointer to a pooled string representing a symbol name.
Definition at line 50 of file SymbolStringPool.h.
Constructor & Destructor Documentation
SymbolStringPtr() [1/4]
llvm::orc::SymbolStringPtr::SymbolStringPtr () default
SymbolStringPtr() [2/4]
llvm::orc::SymbolStringPtr::SymbolStringPtr (std::nullptr_t) inline
Definition at line 57 of file SymbolStringPool.h.
SymbolStringPtr() [3/4]
llvm::orc::SymbolStringPtr::SymbolStringPtr (const SymbolStringPtr & Other) inline
Definition at line 58 of file SymbolStringPool.h.
References llvm::StringMapEntryStorage< ValueTy >::getValue().
SymbolStringPtr() [4/4]
llvm::orc::SymbolStringPtr::SymbolStringPtr (SymbolStringPtr && Other) inline
Definition at line 75 of file SymbolStringPool.h.
References Other, and std::swap().
~SymbolStringPtr()
llvm::orc::SymbolStringPtr::~SymbolStringPtr () inline
Definition at line 89 of file SymbolStringPool.h.
References assert(), and llvm::StringMapEntryStorage< ValueTy >::getValue().
Member Function Documentation
operator bool()
llvm::orc::SymbolStringPtr::operator bool () const inline explicit
Definition at line 96 of file SymbolStringPool.h.
operator*()
StringRef llvm::orc::SymbolStringPtr::operator* () const inline
Definition at line 98 of file SymbolStringPool.h.
References llvm::StringMapEntry< ValueTy >::first().
operator=() [1/2]
SymbolStringPtr& llvm::orc::SymbolStringPtr::operator= (const SymbolStringPtr & Other) inline
Definition at line 64 of file SymbolStringPool.h.
References assert(), llvm::StringMapEntryStorage< ValueTy >::getValue(), and Other.
operator=() [2/2]
SymbolStringPtr& llvm::orc::SymbolStringPtr::operator= (SymbolStringPtr && Other) inline
Definition at line 79 of file SymbolStringPool.h.
References assert(), llvm::StringMapEntryStorage< ValueTy >::getValue(), Other, and std::swap().
Friends And Related Function Documentation
DenseMapInfo< SymbolStringPtr >
friend struct DenseMapInfo< SymbolStringPtr > friend
Definition at line 52 of file SymbolStringPool.h.
operator!=
bool operator!= (const SymbolStringPtr & LHS, const SymbolStringPtr & RHS) friend
Definition at line 105 of file SymbolStringPool.h.
operator<
bool operator< (const SymbolStringPtr & LHS, const SymbolStringPtr & RHS) friend
Definition at line 110 of file SymbolStringPool.h.
operator==
bool operator== (const SymbolStringPtr & LHS, const SymbolStringPtr & RHS) friend
Definition at line 100 of file SymbolStringPool.h.
OrcV2CAPIHelper
friend class OrcV2CAPIHelper friend
Definition at line 51 of file SymbolStringPool.h.
SymbolStringPool
friend class SymbolStringPool friend
Definition at line 52 of file SymbolStringPool.h.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/SymbolStringPool.h