LLVM: SwapAndRestore< T > Class Template Reference
SwapAndRestore< T > Class Template Reference
#include "llvm/Demangle/Utility.h"
Public Member Functions
SwapAndRestore (T &Restore_)
SwapAndRestore (T &Restore_, T NewVal)
~SwapAndRestore ()
void shouldRestore (bool ShouldRestore_)
void restoreNow (bool Force)
SwapAndRestore (const SwapAndRestore &)=delete
SwapAndRestore & operator= (const SwapAndRestore &)=delete
Detailed Description
template<class T>
class SwapAndRestore< T >
Definition at line 168 of file Utility.h.
Constructor & Destructor Documentation
SwapAndRestore() [1/3]
template<class T > SwapAndRestore< T >::SwapAndRestore (T & Restore_) inline
Definition at line 174 of file Utility.h.
SwapAndRestore() [2/3]
template<class T > SwapAndRestore< T >::SwapAndRestore (T & Restore_, T NewVal) inline
Definition at line 176 of file Utility.h.
References llvm::move().
~SwapAndRestore()
template<class T > SwapAndRestore< T >::~SwapAndRestore () inline
Definition at line 180 of file Utility.h.
References llvm::move().
SwapAndRestore() [3/3]
template<class T > SwapAndRestore< T >::SwapAndRestore (const SwapAndRestore< T > &) delete
Member Function Documentation
operator=()
template<class T > SwapAndRestore& SwapAndRestore< T >::operator= (const SwapAndRestore< T > &) delete
restoreNow()
template<class T > void SwapAndRestore< T >::restoreNow (bool Force) inline
Definition at line 187 of file Utility.h.
References llvm::move().
shouldRestore()
template<class T > void SwapAndRestore< T >::shouldRestore (bool ShouldRestore_) inline
Definition at line 185 of file Utility.h.
The documentation for this class was generated from the following file:
include/llvm/Demangle/Utility.h