LLVM: llvm::AMDGPU::HSAMD::MetadataStreamerV2 Class Reference
llvm::AMDGPU::HSAMD::MetadataStreamerV2 Class Reference final
#include "Target/AMDGPU/AMDGPUHSAMetadataStreamer.h"
Public Member Functions
MetadataStreamerV2 ()=default
~MetadataStreamerV2 ()=default
bool emitTo (AMDGPUTargetStreamer &TargetStreamer) override
void begin (const Module &Mod, const IsaInfo::AMDGPUTargetID &TargetID) override
void end () override
void emitKernel (const MachineFunction &MF, const SIProgramInfo &ProgramInfo) override
Public Member Functions inherited from llvm::AMDGPU::HSAMD::MetadataStreamer
virtual ~MetadataStreamer ()
Protected Member Functions
void emitVersion () override
void emitHiddenKernelArgs (const MachineFunction &MF, unsigned &Offset, msgpack::ArrayDocNode Args) override
Detailed Description
Definition at line 160 of file AMDGPUHSAMetadataStreamer.h.
Constructor & Destructor Documentation
MetadataStreamerV2()
llvm::AMDGPU::HSAMD::MetadataStreamerV2::MetadataStreamerV2 () default
~MetadataStreamerV2()
llvm::AMDGPU::HSAMD::MetadataStreamerV2::~MetadataStreamerV2 () default
Member Function Documentation
begin()
void llvm::AMDGPU::HSAMD::MetadataStreamerV2::begin (const Module & Mod, const IsaInfo::AMDGPUTargetID & TargetID) override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 438 of file AMDGPUHSAMetadataStreamer.cpp.
References emitVersion(), and Mod.
emitHiddenKernelArgs()
void llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitHiddenKernelArgs (const MachineFunction & MF, unsigned & Offset, msgpack::ArrayDocNode Args) inline override protected virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 210 of file AMDGPUHSAMetadataStreamer.h.
References llvm_unreachable.
emitKernel()
void llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitKernel (const MachineFunction & MF, const SIProgramInfo & ProgramInfo) override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 455 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::CallingConv::AMDGPU_KERNEL, llvm::AMDGPU::HSAMD::Kernel::Key::CodeProps, llvm::AMDGPU::HSAMD::Kernel::Key::DebugProps, llvm::MachineFunction::getFunction(), llvm::MachineFunction::getSubtarget(), llvm::AMDGPU::HSAMD::Metadata::mKernels, and llvm::ARM_MB::ST.
emitTo()
bool llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitTo (AMDGPUTargetStreamer & TargetStreamer) override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 434 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::AMDGPUTargetStreamer::EmitHSAMetadata().
emitVersion()
void llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitVersion () override protected virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 227 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::AMDGPU::HSAMD::Metadata::mVersion, Version, llvm::AMDGPU::HSAMD::VersionMajorV2, and llvm::AMDGPU::HSAMD::VersionMinorV2.
Referenced by begin().
end()
void llvm::AMDGPU::HSAMD::MetadataStreamerV2::end () override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 444 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::DumpHSAMetadata, llvm::AMDGPU::HSAMD::toString(), and llvm::VerifyHSAMetadata.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUHSAMetadataStreamer.h
lib/Target/AMDGPU/AMDGPUHSAMetadataStreamer.cpp