LLVM: llvm::CFLSteensAAResult::FunctionInfo Class Reference
llvm::CFLSteensAAResult::FunctionInfo Class Reference
Information we have about a function and would like to keep around.
Public Member Functions
FunctionInfo (Function &Fn, const SmallVectorImpl< Value * > &RetVals, StratifiedSets< InstantiatedValue > S)
const StratifiedSets< InstantiatedValue > & getStratifiedSets () const
const AliasSummary & getAliasSummary () const
Detailed Description
Information we have about a function and would like to keep around.
Definition at line 72 of file CFLSteensAliasAnalysis.cpp.
Constructor & Destructor Documentation
FunctionInfo()
llvm::CFLSteensAAResult::FunctionInfo::FunctionInfo (Function & Fn, const SmallVectorImpl< Value * > & RetVals, StratifiedSets< InstantiatedValue > S)
Definition at line 116 of file CFLSteensAliasAnalysis.cpp.
References llvm::Function::arg_size(), llvm::Function::args(), assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::cflaa::StratifiedSets< T >::find(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::cflaa::getExternallyVisibleAttrs(), llvm::cflaa::StratifiedSets< T >::getLink(), llvm::Value::getType(), I, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::Type::isPointerTy(), llvm::codeview::Link, llvm::cflaa::MaxSupportedArgsInSummary, Param, and llvm::cflaa::UnknownOffset.
Member Function Documentation
getAliasSummary()
const AliasSummary& llvm::CFLSteensAAResult::FunctionInfo::getAliasSummary () const inline
Definition at line 84 of file CFLSteensAliasAnalysis.cpp.
getStratifiedSets()
const StratifiedSets<InstantiatedValue>& llvm::CFLSteensAAResult::FunctionInfo::getStratifiedSets () const inline
Definition at line 80 of file CFLSteensAliasAnalysis.cpp.
The documentation for this class was generated from the following file:
lib/Analysis/CFLSteensAliasAnalysis.cpp