LLVM: llvm::SystemZELFRegisters Class Reference
llvm::SystemZELFRegisters Class Reference
ELF calling convention specific use registers Particular when on zLinux in 64 bit mode.
#include "Target/SystemZ/SystemZRegisterInfo.h"
Public Member Functions
int getReturnFunctionAddressRegister () override final
int getStackPointerRegister () override final
int getFramePointerRegister () override final
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override final
const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID CC) const override final
int getCallFrameSize () override final
int getStackPointerBias () override final
~SystemZELFRegisters ()
Destroys the object. Bogus destructor overriding base class destructor.
Public Member Functions inherited from llvm::SystemZCallingConventionRegisters
virtual ~SystemZCallingConventionRegisters ()
Destroys the object.
Detailed Description
ELF calling convention specific use registers Particular when on zLinux in 64 bit mode.
Definition at line 110 of file SystemZRegisterInfo.h.
Constructor & Destructor Documentation
~SystemZELFRegisters()
llvm::SystemZELFRegisters::~SystemZELFRegisters () inline
Destroys the object. Bogus destructor overriding base class destructor.
Definition at line 131 of file SystemZRegisterInfo.h.
Member Function Documentation
getCalleeSavedRegs()
const MCPhysReg * SystemZELFRegisters::getCalleeSavedRegs (const MachineFunction * MF) const final override virtual
Returns
an array of all the callee saved registers.
Implements llvm::SystemZCallingConventionRegisters.
Definition at line 199 of file SystemZRegisterInfo.cpp.
References llvm::CallingConv::AnyReg, llvm::Function::getAttributes(), llvm::Function::getCallingConv(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::CallingConv::GHC, llvm::AttributeList::hasAttrSomewhere(), llvm::SystemZSubtarget::hasVector(), and llvm::TargetLowering::supportSwiftError().
getCallFrameSize()
int llvm::SystemZELFRegisters::getCallFrameSize () inline final override virtual
Returns
the offset to the locals area.
Implements llvm::SystemZCallingConventionRegisters.
Definition at line 126 of file SystemZRegisterInfo.h.
References llvm::SystemZMC::ELFCallFrameSize.
getCallPreservedMask()
const uint32_t * SystemZELFRegisters::getCallPreservedMask (const MachineFunction & MF, CallingConv::ID CC) const final override virtual
Returns
the mask of all the call preserved registers.
Implements llvm::SystemZCallingConventionRegisters.
Definition at line 222 of file SystemZRegisterInfo.cpp.
References llvm::CallingConv::AnyReg, llvm::Function::getAttributes(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::CallingConv::GHC, llvm::AttributeList::hasAttrSomewhere(), llvm::SystemZSubtarget::hasVector(), and llvm::TargetLowering::supportSwiftError().
getFramePointerRegister()
int llvm::SystemZELFRegisters::getFramePointerRegister () inline final override virtual
Returns
the register that keeps the frame pointer address.
Implements llvm::SystemZCallingConventionRegisters.
Definition at line 118 of file SystemZRegisterInfo.h.
getReturnFunctionAddressRegister()
int llvm::SystemZELFRegisters::getReturnFunctionAddressRegister () inline final override virtual
Returns
the register that keeps the return function address.
Implements llvm::SystemZCallingConventionRegisters.
Definition at line 112 of file SystemZRegisterInfo.h.
getStackPointerBias()
int llvm::SystemZELFRegisters::getStackPointerBias () inline final override virtual
Returns
the stack pointer bias.
Implements llvm::SystemZCallingConventionRegisters.
Definition at line 128 of file SystemZRegisterInfo.h.
getStackPointerRegister()
int llvm::SystemZELFRegisters::getStackPointerRegister () inline final override virtual
Returns
the register that keeps the stack pointer address.
Implements llvm::SystemZCallingConventionRegisters.
Definition at line 116 of file SystemZRegisterInfo.h.
The documentation for this class was generated from the following files:
lib/Target/SystemZ/SystemZRegisterInfo.h
lib/Target/SystemZ/SystemZRegisterInfo.cpp