LLVM: llvm::Optional< T > Class Template Reference
llvm::Optional< T > Class Template Reference
#include "llvm/ADT/Optional.h"
Public Types
using value_type = T
Public Member Functions
constexpr Optional ()=default
constexpr Optional (NoneType)
constexpr Optional (const T &y)
constexpr Optional (const Optional &O)=default
constexpr Optional (T &&y)
constexpr Optional (Optional &&O)=default
template<typename... ArgTypes>
constexpr Optional (in_place_t, ArgTypes &&...Args)
Optional & operator= (T &&y)
Optional & operator= (Optional &&O)=default
template<typename... ArgTypes>
void emplace (ArgTypes &&... Args)
Create a new object by constructing it in place with the given arguments.
Optional & operator= (const T &y)
Optional & operator= (const Optional &O)=default
void reset ()
constexpr const T * getPointer () const
T * getPointer ()
constexpr const T & getValue () const LLVM_LVALUE_FUNCTION
T & getValue () LLVM_LVALUE_FUNCTION
constexpr operator bool () const
constexpr bool hasValue () const
constexpr const T * operator-> () const
T * operator-> ()
constexpr const T & operator* () const LLVM_LVALUE_FUNCTION
T & operator* () LLVM_LVALUE_FUNCTION
template<typename U >
constexpr T getValueOr (U &&value) const LLVM_LVALUE_FUNCTION
template<class Function >
auto map (const Function &F) const LLVM_LVALUE_FUNCTION -> Optional< decltype(F(getValue()))>
Apply a function to the value if present; otherwise return None.
Static Public Member Functions
static constexpr Optional create (const T *y)
Detailed Description
template<typename T>
class llvm::Optional< T >
Definition at line 239 of file Optional.h.
Member Typedef Documentation
value_type
template<typename T > using llvm::Optional< T >::value_type = T
Definition at line 243 of file Optional.h.
Constructor & Destructor Documentation
Optional() [1/7]
template<typename T > constexpr llvm::Optional< T >::Optional () constexpr default
Referenced by llvm::Optional< T >::create().
Optional() [2/7]
template<typename T > constexpr llvm::Optional< T >::Optional (NoneType) inline constexpr
Definition at line 246 of file Optional.h.
Optional() [3/7]
template<typename T > constexpr llvm::Optional< T >::Optional (const T & y) inline constexpr
Definition at line 248 of file Optional.h.
Optional() [4/7]
template<typename T > constexpr llvm::Optional< T >::Optional (const Optional< T > & O) constexpr default
Optional() [5/7]
template<typename T > constexpr llvm::Optional< T >::Optional (T && y) inline constexpr
Definition at line 251 of file Optional.h.
Optional() [6/7]
template<typename T > constexpr llvm::Optional< T >::Optional (Optional< T > && O) constexpr default
Optional() [7/7]
template<typename T > template<typename... ArgTypes> constexpr llvm::Optional< T >::Optional (in_place_t , ArgTypes &&... Args) inline constexpr
Definition at line 255 of file Optional.h.
Member Function Documentation
create()
template<typename T > static constexpr Optional llvm::Optional< T >::create (const T * y) inline static constexpr
Definition at line 269 of file Optional.h.
References llvm::Optional< T >::Optional().
emplace()
template<typename T > template<typename... ArgTypes> void llvm::Optional< T >::emplace (ArgTypes &&... Args) inline
Create a new object by constructing it in place with the given arguments.
Definition at line 265 of file Optional.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, and llvm::optional_detail::OptionalStorage< T, bool >::emplace().
Referenced by llvm::CloneFunctionInto(), lowerConstantIntrinsics(), llvm::ValueMap< KeyT, ValueT, Config >::MD(), llvm::LegacyAARGetter::operator()(), llvm::NamedMDNode::print(), runImpl(), and runPartiallyInlineLibCalls().
getPointer() [1/2]
template<typename T > T* llvm::Optional< T >::getPointer () inline
Definition at line 282 of file Optional.h.
References llvm::optional_detail::OptionalStorage< T, bool >::getValue(), and T.
getPointer() [2/2]
template<typename T > constexpr const T* llvm::Optional< T >::getPointer () const inline constexpr
Definition at line 281 of file Optional.h.
References llvm::optional_detail::OptionalStorage< T, bool >::getValue(), and T.
Referenced by llvm::MCObjectFileInfo::getDarwinTargetVariantTriple(), lowerConstantIntrinsics(), llvm::Optional< T >::operator->(), llvm::LoopInstSimplifyPass::run(), llvm::LoopRotatePass::run(), llvm::LoopSimplifyCFGPass::run(), llvm::SimpleLoopUnswitchPass::run(), llvm::LoopFlattenPass::run(), runImpl(), and runPartiallyInlineLibCalls().
getValue() [1/2]
template<typename T > constexpr const T& llvm::Optional< T >::getValue () const inline constexpr
Definition at line 283 of file Optional.h.
References llvm::optional_detail::OptionalStorage< T, bool >::getValue(), and T.
Referenced by AADereferenceableImpl::addAccessedBytesForUse(), alignOutputBlockWithAggFunc(), allocateRVVReg(), assignSections(), llvm::VPlanSlp::buildGraph(), CloneLoopBlocks(), collectRegionsConstants(), computeKnownBitsFromOperator(), dumpAttribute(), llvm::PPCELFStreamer::emitInstruction(), llvm::InstructionSelector::executeMatchTable(), llvm::LoopVectorizationPlanner::executePlan(), findExtractedInputToOverallInputMapping(), llvm::sys::Process::FindInEnvPath(), llvm::IRSimilarity::IRSimilarityIdentifier::findSimilarity(), llvm::SelectionDAG::FoldConstantArithmetic(), genericValueTraversal(), AAHeapToStackFunction::getAPInt(), llvm::IRPosition::getAssociatedArgument(), llvm::Attributor::getAssumedConstant(), getCopyFromPartsVector(), getCopyToPartsVector(), GetDeoptBundleOperands(), llvm::MCSymbolWasm::getExportName(), llvm::MCSymbolWasm::getGlobalType(), getGVNForPHINode(), llvm::MCSymbolWasm::getImportModule(), getISDForVPIntrinsic(), getKnownNonNullAndDerefBytesForUse(), llvm::SystemZTargetLowering::getNumRegisters(), getOrCreateCachedOptional(), llvm::VPIntrinsic::getPointerAlignment(), llvm::IRSimilarity::IRInstructionData::getPredicate(), llvm::MCSchedModel::getReciprocalThroughput(), llvm::AArch64TargetMachine::getSubtargetImpl(), llvm::SwitchInstProfUpdateWrapper::getSuccessorWeight(), llvm::MCSymbolWasm::getTableType(), llvm::Record::getValueAsString(), llvm::Optional< T >::getValueOr(), llvm::ProfileSummaryInfo::hasHugeWorkingSetSize(), llvm::ProfileSummaryInfo::hasLargeWorkingSetSize(), llvm::hasUnrollAndJamTransformation(), llvm::hasUnrollTransformation(), IntersectSignedRange(), IntersectUnsignedRange(), llvm::ProfileSummaryInfo::isColdCount(), llvm::ConstrainedFPIntrinsic::isDefaultFPEnvironment(), llvm::ProfileSummaryInfo::isHotCount(), llvm::FileError::log(), llvm::M68kMCInstLower::Lower(), llvm::VETargetLowering::lowerToVVP(), AAReturnedValuesImpl::manifest(), AAHeapToStackFunction::manifest(), llvm::Optional< T >::map(), llvm::detail::ValueIsMatcher< InnerMatcher >::Impl< T >::MatchAndExplain(), llvm::Optional< T >::operator*(), llvm::operator*(), llvm::operator/(), llvm::raw_ostream::operator<<(), llvm::ifs::overrideIFSTarget(), llvm::MachineBasicBlock::print(), llvm::LoopUnrollPass::printPipeline(), llvm::LoopVectorizePass::processLoop(), llvm::RegsForValue::RegsForValue(), llvm::slpvectorizer::BoUpSLP::VLOperands::reorder(), replaceCalledFunction(), llvm::object::ELFObjectFileBase::setARMSubArch(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), tryToUnrollAndJamLoop(), tryToUnrollLoop(), AAUndefinedBehaviorImpl::updateImpl(), AAValueSimplifyArgument::updateImpl(), llvm::ifs::validateIFSTarget(), llvm::InstCombinerImpl::visitCallInst(), llvm::wouldInstructionBeTriviallyDead(), and llvm::ifs::writeIFSToOutputStream().
getValue() [2/2]
template<typename T > T& llvm::Optional< T >::getValue () inline
Definition at line 286 of file Optional.h.
References llvm::optional_detail::OptionalStorage< T, bool >::getValue(), and T.
getValueOr()
template<typename T > template<typename U > constexpr T llvm::Optional< T >::getValueOr (U && value) const inline constexpr
Definition at line 298 of file Optional.h.
References llvm::Optional< T >::getValue(), llvm::Optional< T >::hasValue(), and T.
Referenced by llvm::OptimizationRemarkEmitter::emit(), llvm::DWARFYAML::emitDebugInfo(), llvm::DWARFYAML::emitDebugLine(), llvm::AMDGPUAsmPrinter::emitGlobalVariable(), llvm::OutlinableRegion::findCorrespondingValueIn(), llvm::InstCombinerImpl::foldAggregateConstructionIntoAggregateReuse(), llvm::DWARFYAML::Data::getAbbrevTableInfoByID(), getAlign(), llvm::Attribute::getAsString(), llvm::getBooleanLoopAttribute(), llvm::ProfileSummaryInfo::getColdCountThreshold(), getDefaultInlineAdvice(), llvm::LLVMContext::getDiagnosticsHotnessThreshold(), llvm::DebugVariable::getFragmentOrDefault(), llvm::ProfileSummaryInfo::getHotCountThreshold(), llvm::getIntLoopAttribute(), llvm::getOptionalElementCountLoopAttribute(), llvm::ProfileSummaryInfo::getOrCompColdCountThreshold(), llvm::ProfileSummaryInfo::getOrCompHotCountThreshold(), llvm::ScalarEvolution::getSmallConstantTripMultiple(), llvm::codegen::InitTargetOptionsFromCodeGenFlags(), llvm::AArch64InstrInfo::isFunctionSafeToOutlineFrom(), layout(), packAllocSizeArgs(), packVScaleRangeArgs(), simplifyICmpOfBools(), llvm::dwarf::toAddress(), llvm::dwarf::toReference(), llvm::dwarf::toSectionOffset(), llvm::dwarf::toSigned(), llvm::dwarf::toUnsigned(), warnAboutLeftoverTransformations(), and llvm::write_double().
hasValue()
template<typename T > constexpr bool llvm::Optional< T >::hasValue () const inline constexpr
Definition at line 289 of file Optional.h.
References llvm::optional_detail::OptionalStorage< T, bool >::hasValue().
Referenced by alignOutputBlockWithAggFunc(), allocateRVVReg(), llvm::DIExpression::appendToStack(), llvm::CombinerHelper::applyCombineConstantFoldFpUnary(), assignSections(), llvm::codeview::ContinuationRecordBuilder::begin(), CloneLoopBlocks(), collectRegionsConstants(), AAPrivatizablePtrImpl::combineTypes(), llvm::pdb::PDBFileBuilder::commit(), llvm::BaseIndexOffset::computeAliasing(), computeKnownBitsFromShiftOperator(), llvm::PPCELFStreamer::emitInstruction(), llvm::MCObjectStreamer::emitRelocDirective(), llvm::InstructionSelector::executeMatchTable(), llvm::LoopVectorizationPlanner::executePlan(), findCanonNumsForPHI(), llvm::OutlinableRegion::findCorrespondingValueIn(), findExtractedInputToOverallInputMapping(), findExtractedOutputToOverallOutputMapping(), llvm::sys::Process::FindInEnvPath(), findOutputValueInRegion(), findPreviousSpillSlot(), llvm::PeelingModuloScheduleExpander::fixupBranches(), llvm::codeview::TypeCollection::ForEachRecord(), llvm::format_provider< T, std::enable_if_t< detail::use_double_formatter< T >::value > >::format(), llvm::gatherPeelingPreferences(), llvm::gatherUnrollingPreferences(), genericValueTraversal(), llvm::dwarf::UnwindLocation::getAddressSpace(), llvm::getAllocAlignment(), AAHeapToStackFunction::getAPInt(), llvm::IRPosition::getAssociatedArgument(), llvm::Attributor::getAssumedConstant(), llvm::Attributor::getAssumedSimplified(), llvm::objcarc::getAttachedARCFunctionKind(), llvm::IRSimilarity::IRInstructionData::getCalleeName(), getCopyFromPartsVector(), getCopyToPartsVector(), GetDeoptBundleOperands(), llvm::ELFYAML::HashSection::getEntries(), llvm::ELFYAML::GnuHashSection::getEntries(), llvm::ELFYAML::AddrsigSection::getEntries(), llvm::ELFYAML::DependentLibrariesSection::getEntries(), llvm::ELFYAML::SymverSection::getEntries(), llvm::ELFYAML::RelrSection::getEntries(), llvm::ELFYAML::SymtabShndxSection::getEntries(), llvm::MCSymbolWasm::getGlobalType(), getGVNForPHINode(), llvm::MCSymbolWasm::getImportModule(), getISDForVPIntrinsic(), llvm::BinaryStreamRefBase< RefType, StreamType >::getLength(), llvm::SystemZTargetLowering::getNumRegisters(), llvm::LLVMContextImpl::getOpaquePointers(), getOrCreateCachedOptional(), llvm::VPIntrinsic::getPointerAlignment(), llvm::IRSimilarity::IRInstructionData::getPredicate(), llvm::MCSchedModel::getReciprocalThroughput(), getSearchPaths(), llvm::Record::getValueAsString(), llvm::Optional< T >::getValueOr(), llvm::MCContext::getXCOFFSection(), llvm::MCSymbolWasm::hasExportName(), llvm::MCSymbolWasm::hasImportModule(), llvm::MCSymbolWasm::hasTableType(), llvm::hasUnrollAndJamTransformation(), llvm::hasUnrollTransformation(), llvm::AArch64FunctionInfo::initializeBaseYamlFields(), llvm::IRSimilarity::IRInstructionData::initializeInstruction(), IntersectSignedRange(), IntersectUnsignedRange(), isColdBlock(), llvm::MCSectionXCOFF::isCsect(), llvm::LLVMContext::isDiagnosticsHotnessThresholdSetFromPSI(), llvm::RISCVTargetLowering::joinRegisterPartsIntoValue(), llvm::FileError::log(), llvm::M68kMCInstLower::Lower(), lowerConstantIntrinsics(), AAReturnedValuesImpl::manifest(), AAHeapToStackFunction::manifest(), llvm::CombinerHelper::matchCombineConstantFoldFpUnary(), llvm::CombinerHelper::matchLoadOrCombine(), llvm::codeview::CodeViewRecordIO::maxFieldLength(), llvm::Optional< T >::operator bool(), llvm::raw_ostream::operator<<(), packAllocSizeArgs(), llvm::LoopVectorizePass::processLoop(), replaceCalledFunction(), llvm::IRSimilarity::IRSimilarityIdentifier::resetSimilarityCandidates(), llvm::LoopInstSimplifyPass::run(), llvm::LoopRotatePass::run(), llvm::LoopSimplifyCFGPass::run(), llvm::SimpleLoopUnswitchPass::run(), llvm::LoopFlattenPass::run(), runImpl(), runPartiallyInlineLibCalls(), llvm::object::ELFObjectFileBase::setARMSubArch(), llvm::IRBuilderBase::setDefaultConstrainedExcept(), llvm::IRBuilderBase::setDefaultConstrainedRounding(), llvm::MCDwarfLineTableHeader::setRootFile(), llvm::MCDwarfLineTable::setRootFile(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), SolveQuadraticAddRecRange(), llvm::RISCVTargetLowering::splitValueIntoRegisterParts(), llvm::Attributor::translateArgumentToCallSiteContent(), llvm::MCDwarfLineTableHeader::tryGetFile(), tryToUnrollAndJamLoop(), tryToUnrollLoop(), AAUndefinedBehaviorImpl::updateImpl(), AAValueSimplifyArgument::updateImpl(), llvm::InstCombinerImpl::visitCallInst(), llvm::codeview::TypeRecordMapping::visitMemberBegin(), llvm::codeview::TypeRecordMapping::visitMemberEnd(), llvm::codeview::SymbolSerializer::visitSymbolBegin(), llvm::codeview::SymbolSerializer::visitSymbolEnd(), llvm::codeview::TypeRecordMapping::visitTypeBegin(), llvm::codeview::TypeRecordMapping::visitTypeEnd(), and llvm::codeview::ContinuationRecordBuilder::writeMemberType().
map()
template<typename T > template<class Function > auto llvm::Optional< T >::map (const Function & F) const -> Optional<decltype(F(getValue()))> inline
Apply a function to the value if present; otherwise return None.
Definition at line 304 of file Optional.h.
References F, llvm::Optional< T >::getValue(), and llvm::None.
operator bool()
template<typename T > constexpr llvm::Optional< T >::operator bool () const inline explicit constexpr
Definition at line 288 of file Optional.h.
References llvm::Optional< T >::hasValue().
operator*() [1/2]
template<typename T > constexpr const T& llvm::Optional< T >::operator* () const inline constexpr
Definition at line 292 of file Optional.h.
References llvm::Optional< T >::getValue(), and T.
operator*() [2/2]
template<typename T > T& llvm::Optional< T >::operator* () inline
Definition at line 295 of file Optional.h.
References llvm::Optional< T >::getValue(), and T.
operator->() [1/2]
template<typename T > T* llvm::Optional< T >::operator-> () inline
Definition at line 291 of file Optional.h.
References llvm::Optional< T >::getPointer(), and T.
operator->() [2/2]
template<typename T > constexpr const T* llvm::Optional< T >::operator-> () const inline constexpr
Definition at line 290 of file Optional.h.
References llvm::Optional< T >::getPointer(), and T.
operator=() [1/4]
template<typename T > Optional& llvm::Optional< T >::operator= (const Optional< T > & O) default
operator=() [2/4]
template<typename T > Optional& llvm::Optional< T >::operator= (const T & y) inline
Definition at line 273 of file Optional.h.
operator=() [3/4]
template<typename T > Optional& llvm::Optional< T >::operator= (Optional< T > && O) default
operator=() [4/4]
template<typename T > Optional& llvm::Optional< T >::operator= (T && y) inline
Definition at line 258 of file Optional.h.
References llvm::move().
reset()
template<typename T > void llvm::Optional< T >::reset () inline
Definition at line 279 of file Optional.h.
References llvm::optional_detail::OptionalStorage< T, bool >::reset().
Referenced by llvm::ValueMap< KeyT, ValueT, Config >::clear(), llvm::DWARFAbbreviationDeclaration::extract(), llvm::DbgVariableLocation::extractFromMachineInstruction(), llvm::DataLayout::reset(), llvm::ThinLTOCodeGenerator::setCachePruningInterval(), llvm::ifs::stripIFSTarget(), llvm::codeview::TypeRecordMapping::visitMemberEnd(), llvm::codeview::SymbolSerializer::visitSymbolEnd(), and llvm::codeview::TypeRecordMapping::visitTypeEnd().
The documentation for this class was generated from the following files:
include/llvm/ADT/APInt.h
include/llvm/ADT/Optional.h