LLVM: llvm::OpenMPOptPass Class Reference
llvm::OpenMPOptPass Class Reference
OpenMP optimizations pass.
#include "llvm/Transforms/IPO/OpenMPOpt.h"
Public Member Functions
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< OpenMPOptPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< OpenMPOptPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
OpenMP optimizations pass.
Definition at line 38 of file OpenMPOpt.h.
Member Function Documentation
run()
PreservedAnalyses OpenMPOptPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 4893 of file OpenMPOpt.cpp.
References llvm::PreservedAnalyses::all(), Allocator, AlwaysInlineDeviceFunctions, llvm::CallingConv::Cold, llvm::omp::containsOpenMP(), llvm::dbgs(), DEBUG_TYPE, DisableInternalization, DisableOpenMPOptimizations, F, FAM, llvm::omp::getDeviceKernels(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::Attributor::internalizeFunctions(), llvm::Attributor::isInternalizable(), llvm::omp::isOpenMPDevice(), llvm::AMDGPU::HSAMD::Key::Kernels, LLVM_DEBUG, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), llvm::PreservedAnalyses::none(), PrintModuleAfterOptimizations, llvm::AMDGPU::CPol::SCC, SetFixpointIterations, and TAG.
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/OpenMPOpt.h
lib/Transforms/IPO/OpenMPOpt.cpp