LLVM: llvm::InstSimplifyFolder Class Reference
llvm::InstSimplifyFolder Class Reference final
InstSimplifyFolder - Use InstructionSimplify to fold operations to existing values.
#include "llvm/Analysis/InstSimplifyFolder.h"
Public Member Functions
InstSimplifyFolder (const DataLayout &DL)
Value * FoldAdd (Value *LHS, Value *RHS, bool HasNUW=false, bool HasNSW=false) const override
Value * FoldAnd (Value *LHS, Value *RHS) const override
Value * FoldOr (Value *LHS, Value *RHS) const override
Value * FoldICmp (CmpInst::Predicate P, Value *LHS, Value *RHS) const override
Value * FoldGEP (Type *Ty, Value *Ptr, ArrayRef< Value * > IdxList, bool IsInBounds=false) const override
Value * FoldSelect (Value *C, Value *True, Value *False) const override
Value * CreateFAdd (Constant *LHS, Constant *RHS) const override
Value * CreateSub (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const override
Value * CreateFSub (Constant *LHS, Constant *RHS) const override
Value * CreateMul (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const override
Value * CreateFMul (Constant *LHS, Constant *RHS) const override
Value * CreateUDiv (Constant *LHS, Constant *RHS, bool isExact=false) const override
Value * CreateSDiv (Constant *LHS, Constant *RHS, bool isExact=false) const override
Value * CreateFDiv (Constant *LHS, Constant *RHS) const override
Value * CreateURem (Constant *LHS, Constant *RHS) const override
Value * CreateSRem (Constant *LHS, Constant *RHS) const override
Value * CreateFRem (Constant *LHS, Constant *RHS) const override
Value * CreateShl (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const override
Value * CreateLShr (Constant *LHS, Constant *RHS, bool isExact=false) const override
Value * CreateAShr (Constant *LHS, Constant *RHS, bool isExact=false) const override
Value * CreateXor (Constant *LHS, Constant *RHS) const override
Value * CreateBinOp (Instruction::BinaryOps Opc, Constant *LHS, Constant *RHS) const override
Value * CreateNeg (Constant *C, bool HasNUW=false, bool HasNSW=false) const override
Value * CreateFNeg (Constant *C) const override
Value * CreateNot (Constant *C) const override
Value * CreateUnOp (Instruction::UnaryOps Opc, Constant *C) const override
Value * CreateCast (Instruction::CastOps Op, Constant *C, Type *DestTy) const override
Value * CreateIntCast (Constant *C, Type *DestTy, bool isSigned) const override
Value * CreatePointerCast (Constant *C, Type *DestTy) const override
Value * CreateFPCast (Constant *C, Type *DestTy) const override
Value * CreateBitCast (Constant *C, Type *DestTy) const override
Value * CreateIntToPtr (Constant *C, Type *DestTy) const override
Value * CreatePtrToInt (Constant *C, Type *DestTy) const override
Value * CreateZExtOrBitCast (Constant *C, Type *DestTy) const override
Value * CreateSExtOrBitCast (Constant *C, Type *DestTy) const override
Value * CreateTruncOrBitCast (Constant *C, Type *DestTy) const override
Value * CreatePointerBitCastOrAddrSpaceCast (Constant *C, Type *DestTy) const override
Value * CreateFCmp (CmpInst::Predicate P, Constant *LHS, Constant *RHS) const override
Value * CreateExtractElement (Constant *Vec, Constant *Idx) const override
Value * CreateInsertElement (Constant *Vec, Constant *NewElt, Constant *Idx) const override
Value * CreateShuffleVector (Constant *V1, Constant *V2, ArrayRef< int > Mask) const override
Value * CreateExtractValue (Constant *Agg, ArrayRef< unsigned > IdxList) const override
Value * CreateInsertValue (Constant *Agg, Constant *Val, ArrayRef< unsigned > IdxList) const override
Public Member Functions inherited from llvm::IRBuilderFolder
virtual ~IRBuilderFolder ()
Detailed Description
InstSimplifyFolder - Use InstructionSimplify to fold operations to existing values.
Also applies target-specific constant folding when not using InstructionSimplify.
Definition at line 35 of file InstSimplifyFolder.h.
Constructor & Destructor Documentation
InstSimplifyFolder()
llvm::InstSimplifyFolder::InstSimplifyFolder (const DataLayout & DL) inline
Definition at line 42 of file InstSimplifyFolder.h.
Member Function Documentation
CreateAShr()
Value* llvm::InstSimplifyFolder::CreateAShr (Constant * LHS, Constant * RHS, bool isExact = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 125 of file InstSimplifyFolder.h.
References LHS, and RHS.
CreateBinOp()
Value* llvm::InstSimplifyFolder::CreateBinOp (Instruction::BinaryOps Opc, Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 133 of file InstSimplifyFolder.h.
References LHS, and RHS.
CreateBitCast()
Value* llvm::InstSimplifyFolder::CreateBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 183 of file InstSimplifyFolder.h.
References C.
CreateCast()
Value* llvm::InstSimplifyFolder::CreateCast (Instruction::CastOps Op, Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 161 of file InstSimplifyFolder.h.
References C.
CreateExtractElement()
Value* llvm::InstSimplifyFolder::CreateExtractElement (Constant * Vec, Constant * Idx) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 228 of file InstSimplifyFolder.h.
CreateExtractValue()
Value* llvm::InstSimplifyFolder::CreateExtractValue (Constant * Agg, ArrayRef< unsigned > IdxList) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 242 of file InstSimplifyFolder.h.
CreateFAdd()
Value* llvm::InstSimplifyFolder::CreateFAdd (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 80 of file InstSimplifyFolder.h.
References LHS, and RHS.
CreateFCmp()
Value* llvm::InstSimplifyFolder::CreateFCmp (CmpInst::Predicate P, Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 219 of file InstSimplifyFolder.h.
References LHS, P, and RHS.
CreateFDiv()
Value* llvm::InstSimplifyFolder::CreateFDiv (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 105 of file InstSimplifyFolder.h.
References LHS, and RHS.
CreateFMul()
Value* llvm::InstSimplifyFolder::CreateFMul (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 94 of file InstSimplifyFolder.h.
References LHS, and RHS.
CreateFNeg()
Value* llvm::InstSimplifyFolder::CreateFNeg (Constant * C) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 146 of file InstSimplifyFolder.h.
References C.
CreateFPCast()
Value* llvm::InstSimplifyFolder::CreateFPCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 178 of file InstSimplifyFolder.h.
References C.
CreateFRem()
Value* llvm::InstSimplifyFolder::CreateFRem (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 114 of file InstSimplifyFolder.h.
References LHS, and RHS.
CreateFSub()
Value* llvm::InstSimplifyFolder::CreateFSub (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 87 of file InstSimplifyFolder.h.
References LHS, and RHS.
CreateInsertElement()
Value* llvm::InstSimplifyFolder::CreateInsertElement (Constant * Vec, Constant * NewElt, Constant * Idx) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 232 of file InstSimplifyFolder.h.
CreateInsertValue()
Value* llvm::InstSimplifyFolder::CreateInsertValue (Constant * Agg, Constant * Val, ArrayRef< unsigned > IdxList) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 247 of file InstSimplifyFolder.h.
CreateIntCast()
Value* llvm::InstSimplifyFolder::CreateIntCast (Constant * C, Type * DestTy, bool isSigned) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 167 of file InstSimplifyFolder.h.
References C.
CreateIntToPtr()
Value* llvm::InstSimplifyFolder::CreateIntToPtr (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 186 of file InstSimplifyFolder.h.
References C.
CreateLShr()
Value* llvm::InstSimplifyFolder::CreateLShr (Constant * LHS, Constant * RHS, bool isExact = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 121 of file InstSimplifyFolder.h.
References LHS, and RHS.
CreateMul()
Value* llvm::InstSimplifyFolder::CreateMul (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 90 of file InstSimplifyFolder.h.
References LHS, and RHS.
CreateNeg()
Value* llvm::InstSimplifyFolder::CreateNeg (Constant * C, bool HasNUW = false, bool HasNSW = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 142 of file InstSimplifyFolder.h.
References C.
CreateNot()
Value* llvm::InstSimplifyFolder::CreateNot (Constant * C) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 149 of file InstSimplifyFolder.h.
References C.
CreatePointerBitCastOrAddrSpaceCast()
Value* llvm::InstSimplifyFolder::CreatePointerBitCastOrAddrSpaceCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 208 of file InstSimplifyFolder.h.
References C.
CreatePointerCast()
Value* llvm::InstSimplifyFolder::CreatePointerCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 173 of file InstSimplifyFolder.h.
References C.
CreatePtrToInt()
Value* llvm::InstSimplifyFolder::CreatePtrToInt (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 189 of file InstSimplifyFolder.h.
References C.
CreateSDiv()
Value* llvm::InstSimplifyFolder::CreateSDiv (Constant * LHS, Constant * RHS, bool isExact = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 101 of file InstSimplifyFolder.h.
References LHS, and RHS.
CreateSExtOrBitCast()
Value* llvm::InstSimplifyFolder::CreateSExtOrBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 197 of file InstSimplifyFolder.h.
References C.
CreateShl()
Value* llvm::InstSimplifyFolder::CreateShl (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 117 of file InstSimplifyFolder.h.
References LHS, and RHS.
CreateShuffleVector()
Value* llvm::InstSimplifyFolder::CreateShuffleVector (Constant * V1, Constant * V2, ArrayRef< int > Mask) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 237 of file InstSimplifyFolder.h.
References llvm::BitmaskEnumDetail::Mask(), and llvm::NVPTX::PTXLdStInstCode::V2.
CreateSRem()
Value* llvm::InstSimplifyFolder::CreateSRem (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 111 of file InstSimplifyFolder.h.
References LHS, and RHS.
CreateSub()
Value* llvm::InstSimplifyFolder::CreateSub (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 83 of file InstSimplifyFolder.h.
References LHS, and RHS.
CreateTruncOrBitCast()
Value* llvm::InstSimplifyFolder::CreateTruncOrBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 202 of file InstSimplifyFolder.h.
References C.
CreateUDiv()
Value* llvm::InstSimplifyFolder::CreateUDiv (Constant * LHS, Constant * RHS, bool isExact = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 97 of file InstSimplifyFolder.h.
References LHS, and RHS.
CreateUnOp()
Value* llvm::InstSimplifyFolder::CreateUnOp (Instruction::UnaryOps Opc, Constant * C) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 153 of file InstSimplifyFolder.h.
References C.
CreateURem()
Value* llvm::InstSimplifyFolder::CreateURem (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 108 of file InstSimplifyFolder.h.
References LHS, and RHS.
CreateXor()
Value* llvm::InstSimplifyFolder::CreateXor (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 129 of file InstSimplifyFolder.h.
References LHS, and RHS.
CreateZExtOrBitCast()
Value* llvm::InstSimplifyFolder::CreateZExtOrBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 192 of file InstSimplifyFolder.h.
References C.
FoldAdd()
Value* llvm::InstSimplifyFolder::FoldAdd (Value * LHS, Value * RHS, bool HasNUW = false, bool HasNSW = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 50 of file InstSimplifyFolder.h.
References LHS, RHS, and llvm::SimplifyAddInst().
FoldAnd()
Value* llvm::InstSimplifyFolder::FoldAnd (Value * LHS, Value * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 55 of file InstSimplifyFolder.h.
References LHS, RHS, and llvm::SimplifyAndInst().
FoldGEP()
Value* llvm::InstSimplifyFolder::FoldGEP (Type * Ty, Value * Ptr, ArrayRef< Value * > IdxList, bool IsInBounds = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 67 of file InstSimplifyFolder.h.
References llvm::SimplifyGEPInst().
FoldICmp()
Value* llvm::InstSimplifyFolder::FoldICmp (CmpInst::Predicate P, Value * LHS, Value * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 63 of file InstSimplifyFolder.h.
References LHS, P, RHS, and llvm::SimplifyICmpInst().
FoldOr()
Value* llvm::InstSimplifyFolder::FoldOr (Value * LHS, Value * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 59 of file InstSimplifyFolder.h.
References LHS, RHS, and llvm::SimplifyOrInst().
FoldSelect()
Value* llvm::InstSimplifyFolder::FoldSelect (Value * C, Value * True, Value * False) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 72 of file InstSimplifyFolder.h.
References C, and llvm::SimplifySelectInst().
The documentation for this class was generated from the following files:
include/llvm/Analysis/InstSimplifyFolder.h
lib/Analysis/InstructionSimplify.cpp