LLVM: llvm::CFLAndersAAResult::FunctionInfo Class Reference
llvm::CFLAndersAAResult::FunctionInfo Class Reference
Public Member Functions
FunctionInfo (const Function &, const SmallVectorImpl< Value * > &, const ReachabilitySet &, const AliasAttrMap &)
bool mayAlias (const Value *, LocationSize, const Value *, LocationSize) const
const AliasSummary & getAliasSummary () const
Detailed Description
Definition at line 323 of file CFLAndersAliasAnalysis.cpp.
Constructor & Destructor Documentation
FunctionInfo()
llvm::CFLAndersAAResult::FunctionInfo::FunctionInfo (const Function & Fn, const SmallVectorImpl< Value * > & RetVals, const ReachabilitySet & ReachSet, const AliasAttrMap & AMap)
Definition at line 501 of file CFLAndersAliasAnalysis.cpp.
References populateAliasMap(), populateAttrMap(), populateExternalAttributes(), and populateExternalRelations().
Member Function Documentation
getAliasSummary()
const AliasSummary& llvm::CFLAndersAAResult::FunctionInfo::getAliasSummary () const inline
Definition at line 343 of file CFLAndersAliasAnalysis.cpp.
mayAlias()
bool llvm::CFLAndersAAResult::FunctionInfo::mayAlias (const Value * LHS, LocationSize MaybeLHSSize, const Value * RHS, LocationSize MaybeRHSSize) const
Definition at line 520 of file CFLAndersAliasAnalysis.cpp.
References assert(), llvm::LocationSize::getValue(), llvm::cflaa::hasUnknownOrCallerAttr(), llvm::LocationSize::hasValue(), INT64_MAX, llvm::is_sorted(), llvm::cflaa::isGlobalOrArgAttr(), LHS, LLVM_UNLIKELY, llvm::make_range(), RHS, and llvm::cflaa::UnknownOffset.
The documentation for this class was generated from the following file:
lib/Analysis/CFLAndersAliasAnalysis.cpp