LLVM: llvm::jitlink::AllocGroupSmallMap< T > Class Template Reference
llvm::jitlink::AllocGroupSmallMap< T > Class Template Reference
A specialized small-map for AllocGroups.
#include "llvm/ExecutionEngine/JITLink/MemoryFlags.h"
Public Types
using iterator = typename VectorTy::iterator
Public Member Functions
AllocGroupSmallMap ()=default
AllocGroupSmallMap (std::initializer_list< std::pair< AllocGroup, T >> Inits)
iterator begin ()
iterator end ()
iterator find (AllocGroup G)
bool empty () const
size_t size () const
T & operator[] (AllocGroup G)
Detailed Description
template<typename T>
class llvm::jitlink::AllocGroupSmallMap< T >
A specialized small-map for AllocGroups.
Iteration order is guaranteed to match key ordering.
Definition at line 142 of file MemoryFlags.h.
Member Typedef Documentation
iterator
template<typename T > using llvm::jitlink::AllocGroupSmallMap< T >::iterator = typename VectorTy::iterator
Definition at line 152 of file MemoryFlags.h.
Constructor & Destructor Documentation
AllocGroupSmallMap() [1/2]
template<typename T > llvm::jitlink::AllocGroupSmallMap< T >::AllocGroupSmallMap () default
AllocGroupSmallMap() [2/2]
template<typename T > llvm::jitlink::AllocGroupSmallMap< T >::AllocGroupSmallMap (std::initializer_list< std::pair< AllocGroup, T >> Inits) inline
Definition at line 155 of file MemoryFlags.h.
References E, LHS, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorImpl< T >::reserve(), RHS, and llvm::sort().
Member Function Documentation
begin()
template<typename T > iterator llvm::jitlink::AllocGroupSmallMap< T >::begin () inline
Definition at line 164 of file MemoryFlags.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
Referenced by llvm::jitlink::BasicLayout::segments().
empty()
template<typename T > bool llvm::jitlink::AllocGroupSmallMap< T >::empty () const inline
Definition at line 171 of file MemoryFlags.h.
References llvm::SmallVectorBase< Size_T >::empty().
end()
template<typename T > iterator llvm::jitlink::AllocGroupSmallMap< T >::end () inline
Definition at line 165 of file MemoryFlags.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by llvm::jitlink::AllocGroupSmallMap< T >::find(), and llvm::jitlink::BasicLayout::segments().
find()
template<typename T > iterator llvm::jitlink::AllocGroupSmallMap< T >::find (AllocGroup G) inline
Definition at line 166 of file MemoryFlags.h.
References llvm::jitlink::AllocGroupSmallMap< T >::end(), G, I, and llvm::lower_bound().
operator[]()
template<typename T > T& llvm::jitlink::AllocGroupSmallMap< T >::operator[] (AllocGroup G) inline
Definition at line 174 of file MemoryFlags.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), G, I, llvm::SmallVectorImpl< T >::insert(), llvm::lower_bound(), and T.
size()
template<typename T > size_t llvm::jitlink::AllocGroupSmallMap< T >::size () const inline
Definition at line 172 of file MemoryFlags.h.
References llvm::SmallVectorBase< Size_T >::size().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/JITLink/MemoryFlags.h