LLVM: llvm::BufferedHTTPResponseHandler Class Reference
llvm::BufferedHTTPResponseHandler Class Reference final
A simple handler which writes returned data to an HTTPResponseBuffer.
#include "llvm/Debuginfod/HTTPClient.h"
Public Member Functions
Error handleHeaderLine (StringRef HeaderLine) override
These callbacks store the body and status code in an HTTPResponseBuffer allocated based on Content-Length.
Error handleBodyChunk (StringRef BodyChunk) override
Processes an additional chunk of bytes of the HTTP response body.
Error handleStatusCode (unsigned Code) override
Processes the HTTP response status code.
Public Attributes
HTTPResponseBuffer ResponseBuffer
Stores the data received from the HTTP server.
Additional Inherited Members
Protected Member Functions inherited from llvm::HTTPResponseHandler
~HTTPResponseHandler ()
Detailed Description
A simple handler which writes returned data to an HTTPResponseBuffer.
Ignores all headers except the Content-Length, which it uses to allocate an appropriately-sized Body buffer.
Definition at line 65 of file HTTPClient.h.
Member Function Documentation
handleBodyChunk()
Error BufferedHTTPResponseHandler::handleBodyChunk (StringRef BodyChunk) override virtual
Processes an additional chunk of bytes of the HTTP response body.
Implements llvm::HTTPResponseHandler.
Definition at line 56 of file HTTPClient.cpp.
References llvm::HTTPResponseBuffer::Body, llvm::createStringError(), llvm::StringRef::data(), llvm::io_error, ResponseBuffer, llvm::StringRef::size(), and llvm::Error::success().
handleHeaderLine()
Error BufferedHTTPResponseHandler::handleHeaderLine (StringRef HeaderLine) override virtual
These callbacks store the body and status code in an HTTPResponseBuffer allocated based on Content-Length.
The Content-Length header must be handled by handleHeaderLine before any calls to handleBodyChunk.
Implements llvm::HTTPResponseHandler.
Definition at line 44 of file HTTPClient.cpp.
References llvm::HTTPResponseBuffer::Body, llvm::WritableMemoryBuffer::getNewUninitMemBuffer(), parseContentLengthHeader(), ResponseBuffer, and llvm::Error::success().
handleStatusCode()
Error BufferedHTTPResponseHandler::handleStatusCode (unsigned Code) override virtual
Processes the HTTP response status code.
Implements llvm::HTTPResponseHandler.
Definition at line 70 of file HTTPClient.cpp.
References llvm::HTTPResponseBuffer::Code, ResponseBuffer, and llvm::Error::success().
Member Data Documentation
ResponseBuffer
HTTPResponseBuffer llvm::BufferedHTTPResponseHandler::ResponseBuffer
Stores the data received from the HTTP server.
Definition at line 70 of file HTTPClient.h.
Referenced by handleBodyChunk(), handleHeaderLine(), and handleStatusCode().
The documentation for this class was generated from the following files:
include/llvm/Debuginfod/HTTPClient.h
lib/Debuginfod/HTTPClient.cpp