LLVM: llvm::VPlanHCFGBuilder Class Reference
llvm::VPlanHCFGBuilder Class Reference
Main class to build the VPlan H-CFG for an incoming IR.
#include "Transforms/Vectorize/VPlanHCFGBuilder.h"
Public Member Functions
VPlanHCFGBuilder (Loop *Lp, LoopInfo *LI, VPlan &P)
void buildHierarchicalCFG ()
Build H-CFG for TheLoop and update Plan accordingly.
Detailed Description
Main class to build the VPlan H-CFG for an incoming IR.
Definition at line 37 of file VPlanHCFGBuilder.h.
Constructor & Destructor Documentation
VPlanHCFGBuilder()
llvm::VPlanHCFGBuilder::VPlanHCFGBuilder (Loop * Lp, LoopInfo * LI, VPlan & P) inline
Definition at line 63 of file VPlanHCFGBuilder.h.
Member Function Documentation
buildHierarchicalCFG()
void VPlanHCFGBuilder::buildHierarchicalCFG ()
Build H-CFG for TheLoop and update Plan accordingly.
Definition at line 344 of file VPlanHCFGBuilder.cpp.
References llvm::LoopInfoBase< BlockT, LoopT >::analyze(), llvm::dbgs(), llvm::VPlan::getVPLoopInfo(), LLVM_DEBUG, llvm::DominatorTreeBase< NodeT, IsPostDom >::print(), llvm::LoopInfoBase< BlockT, LoopT >::print(), llvm::DominatorTreeBase< NodeT, IsPostDom >::recalculate(), llvm::VPlan::setEntry(), llvm::VPlan::setName(), and llvm::VPlanVerifier::verifyHierarchicalCFG().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlanHCFGBuilder.h
lib/Transforms/Vectorize/VPlanHCFGBuilder.cpp