LLVM: llvm::DWARFUnit Class Reference
llvm::DWARFUnit Class Reference abstract
#include "llvm/DebugInfo/DWARF/DWARFUnit.h"
Public Member Functions
DWARFUnit (DWARFContext &Context, const DWARFSection &Section, const DWARFUnitHeader &Header, const DWARFDebugAbbrev *DA, const DWARFSection *RS, const DWARFSection *LocSection, StringRef SS, const DWARFSection &SOS, const DWARFSection *AOS, const DWARFSection &LS, bool LE, bool IsDWO, const DWARFUnitVector &UnitVector)
virtual ~DWARFUnit ()
bool isDWOUnit () const
DWARFContext & getContext () const
const DWARFSection & getInfoSection () const
uint64_t getOffset () const
const dwarf::FormParams & getFormParams () const
uint16_t getVersion () const
uint8_t getAddressByteSize () const
uint8_t getRefAddrByteSize () const
uint8_t getDwarfOffsetByteSize () const
uint32_t getHeaderSize () const
Size in bytes of the parsed unit header.
uint64_t getLength () const
dwarf::DwarfFormat getFormat () const
uint8_t getUnitType () const
bool isTypeUnit () const
uint64_t getAbbrOffset () const
uint64_t getNextUnitOffset () const
const DWARFSection & getLineSection () const
StringRef getStringSection () const
const DWARFSection & getStringOffsetSection () const
void setSkeletonUnit (DWARFUnit *SU)
DWARFUnit * getLinkedUnit ()
void setAddrOffsetSection (const DWARFSection *AOS, uint64_t Base)
Optional< uint64_t > getAddrOffsetSectionBase () const
void updateAddressDieMap (DWARFDie Die)
Recursively update address to Die map.
void setRangesSection (const DWARFSection *RS, uint64_t Base)
uint64_t getLocSectionBase () const
Optional< object::SectionedAddress > getAddrOffsetSectionItem (uint32_t Index) const
Expected< uint64_t > getStringOffsetSectionItem (uint32_t Index) const
DWARFDataExtractor getDebugInfoExtractor () const
DataExtractor getStringExtractor () const
const DWARFLocationTable & getLocationTable ()
Error extractRangeList (uint64_t RangeListOffset, DWARFDebugRangeList &RangeList) const
Extract the range list referenced by this compile unit from the .debug_ranges section.
void clear ()
const Optional< StrOffsetsContributionDescriptor > & getStringOffsetsTableContribution () const
uint8_t getDwarfStringOffsetsByteSize () const
uint64_t getStringOffsetsBase () const
uint64_t getAbbreviationsOffset () const
const DWARFAbbreviationDeclarationSet * getAbbreviations () const
llvm::Optional< object::SectionedAddress > getBaseAddress ()
DWARFDie getUnitDIE (bool ExtractUnitDIEOnly=true)
DWARFDie getNonSkeletonUnitDIE (bool ExtractUnitDIEOnly=true)
const char * getCompilationDir ()
Optional< uint64_t > getDWOId ()
void setDWOId (uint64_t NewID)
Expected< DWARFAddressRangesVector > findRnglistFromOffset (uint64_t Offset)
Return a vector of address ranges resulting from a (possibly encoded) range list starting at a given offset in the appropriate ranges section.
Expected< DWARFAddressRangesVector > findRnglistFromIndex (uint32_t Index)
Return a vector of address ranges retrieved from an encoded range list whose offset is found via a table lookup given an index (DWARF v5 and later).
Optional< uint64_t > getRnglistOffset (uint32_t Index)
Return a rangelist's offset based on an index.
Optional< uint64_t > getLoclistOffset (uint32_t Index)
Expected< DWARFAddressRangesVector > collectAddressRanges ()
Expected< DWARFLocationExpressionsVector > findLoclistFromOffset (uint64_t Offset)
DWARFDie getSubroutineForAddress (uint64_t Address)
Returns subprogram DIE with address range encompassing the provided address.
void getInlinedChainForAddress (uint64_t Address, SmallVectorImpl< DWARFDie > &InlinedChain)
getInlinedChainForAddress - fetches inlined chain for a given address.
const DWARFUnitVector & getUnitVector () const
Return the DWARFUnitVector containing this unit.
unsigned getNumDIEs ()
Returns the number of DIEs in the unit.
uint32_t getDIEIndex (const DWARFDie &D)
Return the index of a DIE inside the unit's DIE vector.
DWARFDie getDIEAtIndex (unsigned Index)
Return the DIE object at the given index.
DWARFDie getParent (const DWARFDebugInfoEntry *Die)
DWARFDie getSibling (const DWARFDebugInfoEntry *Die)
DWARFDie getPreviousSibling (const DWARFDebugInfoEntry *Die)
DWARFDie getFirstChild (const DWARFDebugInfoEntry *Die)
DWARFDie getLastChild (const DWARFDebugInfoEntry *Die)
DWARFDie getDIEForOffset (uint64_t Offset)
Return the DIE object for a given offset inside the unit's DIE vector.
uint32_t getLineTableOffset () const
die_iterator_range dies ()
virtual void dump (raw_ostream &OS, DIDumpOptions DumpOpts)=0
Error tryExtractDIEsIfNeeded (bool CUDieOnly)
Static Public Member Functions
static bool isMatchingUnitTypeAndTag (uint8_t UnitType, dwarf::Tag Tag)
Protected Member Functions
const DWARFUnitHeader & getHeader () const
Expected< Optional< StrOffsetsContributionDescriptor > > determineStringOffsetsTableContribution (DWARFDataExtractor &DA)
Find the unit's contribution to the string offsets table and determine its length and form.
Expected< Optional< StrOffsetsContributionDescriptor > > determineStringOffsetsTableContributionDWO (DWARFDataExtractor &DA)
Find the unit's contribution to the string offsets table and determine its length and form.
Detailed Description
Definition at line 203 of file DWARFUnit.h.
Constructor & Destructor Documentation
DWARFUnit()
DWARFUnit::DWARFUnit (DWARFContext & Context, const DWARFSection & Section, const DWARFUnitHeader & Header, const DWARFDebugAbbrev * DA, const DWARFSection * RS, const DWARFSection * LocSection, StringRef SS, const DWARFSection & SOS, const DWARFSection * AOS, const DWARFSection & LS, bool LE, bool IsDWO, const DWARFUnitVector & UnitVector)
Definition at line 173 of file DWARFUnit.cpp.
References clear().
~DWARFUnit()
DWARFUnit::~DWARFUnit () virtual default
Member Function Documentation
clear()
void DWARFUnit::clear ()
Definition at line 361 of file DWARFUnit.cpp.
References llvm::None.
Referenced by DWARFUnit().
collectAddressRanges()
Expected< DWARFAddressRangesVector > DWARFUnit::collectAddressRanges ()
Definition at line 655 of file DWARFUnit.cpp.
References llvm::createStringError(), llvm::DWARFDie::getAddressRanges(), getUnitDIE(), llvm::invalid_argument, and llvm::toString().
determineStringOffsetsTableContribution()
Expected< Optional< StrOffsetsContributionDescriptor > > DWARFUnit::determineStringOffsetsTableContribution (DWARFDataExtractor & DA) protected
Find the unit's contribution to the string offsets table and determine its length and form.
The given offset is expected to be derived from the unit DIE's DW_AT_str_offsets_base attribute.
Definition at line 964 of file DWARFUnit.cpp.
References assert(), llvm::M68kBeads::DA, llvm::find(), llvm::DWARFUnitHeader::getFormat(), getUnitDIE(), llvm::None, parseDWARFStringOffsetsTableHeader(), and llvm::dwarf::toSectionOffset().
Referenced by tryExtractDIEsIfNeeded().
determineStringOffsetsTableContributionDWO()
Expected< Optional< StrOffsetsContributionDescriptor > > DWARFUnit::determineStringOffsetsTableContributionDWO (DWARFDataExtractor & DA) protected
Find the unit's contribution to the string offsets table and determine its length and form.
The given offset is expected to be 0 in a dwo file or, in a dwp file, the start of the unit's contribution to the string offsets table section (as determined by the index table).
Definition at line 977 of file DWARFUnit.cpp.
References assert(), C, llvm::M68kBeads::DA, llvm::DWARFSection::Data, llvm::dwarf::DWARF32, llvm::StringRef::empty(), llvm::DWARFUnitHeader::getFormat(), llvm::DWARFUnitHeader::getIndexEntry(), getVersion(), llvm::None, Offset, parseDWARFStringOffsetsTableHeader(), llvm::StringRef::size(), and llvm::StrOffsetsContributionDescriptor::validateContributionSize().
Referenced by tryExtractDIEsIfNeeded().
dies()
die_iterator_range llvm::DWARFUnit::dies () inline
Definition at line 497 of file DWARFUnit.h.
dump()
virtual void llvm::DWARFUnit::dump (raw_ostream & OS, DIDumpOptions DumpOpts) pure virtual
Implemented in llvm::DWARFTypeUnit, and llvm::DWARFCompileUnit.
extractRangeList()
Error DWARFUnit::extractRangeList (uint64_t RangeListOffset, DWARFDebugRangeList & RangeList) const
Extract the range list referenced by this compile unit from the .debug_ranges section.
If the extraction is unsuccessful, an error is returned. Successful extraction requires that the compile unit has already been extracted.
Definition at line 351 of file DWARFUnit.cpp.
References assert(), Context, llvm::DWARFDebugRangeList::extract(), and getAddressByteSize().
Referenced by findRnglistFromOffset().
findLoclistFromOffset()
Expected< DWARFLocationExpressionsVector > DWARFUnit::findLoclistFromOffset (uint64_t Offset)
Definition at line 670 of file DWARFUnit.cpp.
References getAddrOffsetSectionItem(), getBaseAddress(), getLocationTable(), llvm::joinErrors(), llvm::move(), Offset, llvm::Error::success(), and llvm::DWARFLocationTable::visitAbsoluteLocationList().
findRnglistFromIndex()
Expected< DWARFAddressRangesVector > DWARFUnit::findRnglistFromIndex (uint32_t Index)
Return a vector of address ranges retrieved from an encoded range list whose offset is found via a table lookup given an index (DWARF v5 and later).
Definition at line 645 of file DWARFUnit.cpp.
References llvm::createStringError(), findRnglistFromOffset(), getRnglistOffset(), llvm::invalid_argument, and Offset.
findRnglistFromOffset()
Expected< DWARFAddressRangesVector > DWARFUnit::findRnglistFromOffset (uint64_t Offset)
Return a vector of address ranges resulting from a (possibly encoded) range list starting at a given offset in the appropriate ranges section.
Definition at line 628 of file DWARFUnit.cpp.
References Context, E, extractRangeList(), llvm::DWARFListTableBase< DWARFListType >::findList(), llvm::DWARFDebugRangeList::getAbsoluteRanges(), llvm::DWARFUnitHeader::getAddressByteSize(), getBaseAddress(), getVersion(), llvm::move(), and Offset.
Referenced by findRnglistFromIndex().
getAbbreviations()
const DWARFAbbreviationDeclarationSet * DWARFUnit::getAbbreviations () const
Definition at line 868 of file DWARFUnit.cpp.
References llvm::DWARFDebugAbbrev::getAbbreviationDeclarationSet(), and getAbbreviationsOffset().
Referenced by llvm::DWARFCompileUnit::dump(), llvm::DWARFTypeUnit::dump(), and llvm::DWARFDebugInfoEntry::extractFast().
getAbbreviationsOffset()
uint64_t llvm::DWARFUnit::getAbbreviationsOffset () const inline
Definition at line 367 of file DWARFUnit.h.
References llvm::DWARFUnitHeader::getAbbrOffset().
Referenced by llvm::DWARFDebugInfoEntry::extractFast(), and getAbbreviations().
getAbbrOffset()
uint64_t llvm::DWARFUnit::getAbbrOffset () const inline
Definition at line 297 of file DWARFUnit.h.
References llvm::DWARFUnitHeader::getAbbrOffset().
Referenced by llvm::DWARFCompileUnit::dump(), and llvm::DWARFTypeUnit::dump().
getAddressByteSize()
uint8_t llvm::DWARFUnit::getAddressByteSize () const inline
Definition at line 286 of file DWARFUnit.h.
References llvm::DWARFUnitHeader::getAddressByteSize().
Referenced by llvm::DWARFCompileUnit::dump(), llvm::DWARFTypeUnit::dump(), dumpAttribute(), dumpLocationExpr(), extractRangeList(), llvm::DWARFDebugRnglist::getAbsoluteRanges(), getAddrOffsetSectionItem(), getDebugInfoExtractor(), llvm::DWARFContext::getLineTableForUnit(), getRnglistOffset(), llvm::CompileUnit::markEverythingAsKept(), and tryExtractDIEsIfNeeded().
getAddrOffsetSectionBase()
Optional<uint64_t> llvm::DWARFUnit::getAddrOffsetSectionBase () const inline
Definition at line 316 of file DWARFUnit.h.
getAddrOffsetSectionItem()
Optional< object::SectionedAddress > DWARFUnit::getAddrOffsetSectionItem (uint32_t Index) const
Definition at line 194 of file DWARFUnit.cpp.
References llvm::Address, Context, llvm::M68kBeads::DA, llvm::DWARFSection::Data, getAddressByteSize(), llvm::hasSingleElement(), llvm::None, Offset, llvm::ARMBuildAttrs::Section, and llvm::StringRef::size().
Referenced by llvm::DWARFLocationTable::dumpLocationList(), and findLoclistFromOffset().
getBaseAddress()
llvm::Optional< object::SectionedAddress > DWARFUnit::getBaseAddress ()
Definition at line 874 of file DWARFUnit.cpp.
References llvm::DWARFDie::find(), getUnitDIE(), and llvm::dwarf::toSectionedAddress().
Referenced by dumpLocationList(), findLoclistFromOffset(), and findRnglistFromOffset().
getCompilationDir()
const char * DWARFUnit::getCompilationDir ()
Definition at line 372 of file DWARFUnit.cpp.
References llvm::find(), getUnitDIE(), and llvm::dwarf::toString().
Referenced by dumpAttribute(), and llvm::DWARFFormValue::getAsFile().
getContext()
DWARFContext& llvm::DWARFUnit::getContext () const inline
Definition at line 279 of file DWARFUnit.h.
References Context.
Referenced by dumpAttribute(), dumpLocationExpr(), dumpLocationList(), llvm::DWARFDebugInfoEntry::extractFast(), llvm::DWARFFormValue::getAsFile(), llvm::DeclContextTree::getChildDeclContext(), and llvm::DWARFDie::resolveTypeUnitReference().
getDebugInfoExtractor()
DWARFDataExtractor DWARFUnit::getDebugInfoExtractor () const
Definition at line 188 of file DWARFUnit.cpp.
References Context, and getAddressByteSize().
Referenced by llvm::DWARFFormValue::createFromUnit(), llvm::DWARFAbbreviationDeclaration::getAttributeOffsetFromIndex(), and llvm::DWARFAbbreviationDeclaration::getAttributeValueFromOffset().
getDIEAtIndex()
DWARFDie llvm::DWARFUnit::getDIEAtIndex (unsigned Index) inline
Return the DIE object at the given index.
Definition at line 464 of file DWARFUnit.h.
References assert(), and Index.
Referenced by llvm::inFunctionScope(), and llvm::CompileUnit::markEverythingAsKept().
getDIEForOffset()
DWARFDie llvm::DWARFUnit::getDIEForOffset (uint64_t Offset) inline
Return the DIE object for a given offset inside the unit's DIE vector.
The unit needs to have its DIEs extracted for this method to work.
Definition at line 479 of file DWARFUnit.h.
References llvm::DIE::getOffset(), Offset, and llvm::partition_point().
Referenced by llvm::DWARFTypeUnit::dump(), llvm::prettyPrintBaseTypeRef(), and llvm::DWARFExpression::Operation::verify().
getDIEIndex()
uint32_t llvm::DWARFUnit::getDIEIndex (const DWARFDie & D) inline
Return the index of a DIE inside the unit's DIE vector.
It is illegal to call this method with a DIE that hasn't be created by this unit. In other word, it's illegal to call this method on a DIE that isn't accessible by following children/sibling links starting from this unit's getUnitDIE().
Definition at line 459 of file DWARFUnit.h.
References D.
getDwarfOffsetByteSize()
uint8_t llvm::DWARFUnit::getDwarfOffsetByteSize () const inline
Definition at line 288 of file DWARFUnit.h.
References llvm::DWARFUnitHeader::getDwarfOffsetByteSize().
getDwarfStringOffsetsByteSize()
uint8_t llvm::DWARFUnit::getDwarfStringOffsetsByteSize () const inline
Definition at line 357 of file DWARFUnit.h.
References assert().
Referenced by getStringOffsetSectionItem().
getDWOId()
Optional<uint64_t> llvm::DWARFUnit::getDWOId () inline
Definition at line 405 of file DWARFUnit.h.
References llvm::DWARFUnitHeader::getDWOId(), and getHeader().
Referenced by llvm::DWARFCompileUnit::dump().
getFirstChild()
DWARFDie DWARFUnit::getFirstChild (const DWARFDebugInfoEntry * Die)
Definition at line 824 of file DWARFUnit.cpp.
References llvm::DWARFDebugInfoEntry::hasChildren(), and I.
getFormat()
dwarf::DwarfFormat llvm::DWARFUnit::getFormat () const inline
Definition at line 294 of file DWARFUnit.h.
References llvm::DWARFUnitHeader::getFormat().
Referenced by llvm::DWARFCompileUnit::dump(), llvm::DWARFTypeUnit::dump(), getLoclistOffset(), and getRnglistOffset().
getFormParams()
const dwarf::FormParams& llvm::DWARFUnit::getFormParams () const inline
Definition at line 282 of file DWARFUnit.h.
References llvm::DWARFUnitHeader::getFormParams().
Referenced by llvm::DWARFFormValue::createFromUnit(), dumpLocationExpr(), llvm::DWARFDebugInfoEntry::extractFast(), llvm::DWARFAbbreviationDeclaration::getAttributeOffsetFromIndex(), llvm::DWARFAbbreviationDeclaration::getAttributeValueFromOffset(), and llvm::DWARFAbbreviationDeclaration::AttributeSpec::getByteSize().
getHeader()
const DWARFUnitHeader& llvm::DWARFUnit::getHeader () const inline protected
Definition at line 253 of file DWARFUnit.h.
Referenced by getDWOId(), llvm::DWARFTypeUnit::getTypeHash(), and llvm::DWARFTypeUnit::getTypeOffset().
getHeaderSize()
uint32_t llvm::DWARFUnit::getHeaderSize () const inline
Size in bytes of the parsed unit header.
Definition at line 292 of file DWARFUnit.h.
References llvm::DWARFUnitHeader::getSize().
getInfoSection()
const DWARFSection& llvm::DWARFUnit::getInfoSection () const inline
Definition at line 280 of file DWARFUnit.h.
getInlinedChainForAddress()
void DWARFUnit::getInlinedChainForAddress (uint64_t Address, SmallVectorImpl< DWARFDie > & InlinedChain)
getInlinedChainForAddress - fetches inlined chain for a given address.
Returns empty chain if there is no subprogram containing address. The chain is valid as long as parsed compile unit DIEs are not cleared.
Definition at line 739 of file DWARFUnit.cpp.
References llvm::Address, assert(), llvm::SmallVectorBase< Size_T >::empty(), llvm::DWARFDie::getParent(), getSubroutineForAddress(), llvm::DWARFDie::getTag(), llvm::DWARFDie::isSubprogramDIE(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
getLastChild()
DWARFDie DWARFUnit::getLastChild (const DWARFDebugInfoEntry * Die)
Definition at line 837 of file DWARFUnit.cpp.
References assert(), llvm::DWARFDebugInfoEntry::getSiblingIdx(), getTag(), getUnitDIE(), and llvm::DWARFDebugInfoEntry::hasChildren().
getLength()
uint64_t llvm::DWARFUnit::getLength () const inline
Definition at line 293 of file DWARFUnit.h.
References llvm::DWARFUnitHeader::getLength().
Referenced by llvm::DWARFCompileUnit::dump(), and llvm::DWARFTypeUnit::dump().
getLineSection()
const DWARFSection& llvm::DWARFUnit::getLineSection () const inline
Definition at line 299 of file DWARFUnit.h.
Referenced by llvm::DWARFContext::getLineTableForUnit().
getLineTableOffset()
uint32_t llvm::DWARFUnit::getLineTableOffset () const inline
Definition at line 490 of file DWARFUnit.h.
References llvm::DWARFUnitHeader::getIndexEntry().
Referenced by llvm::DWARFContext::getLineTableForUnit().
getLinkedUnit()
DWARFUnit* llvm::DWARFUnit::getLinkedUnit () inline
Definition at line 309 of file DWARFUnit.h.
getLocationTable()
const DWARFLocationTable& llvm::DWARFUnit::getLocationTable () inline
Definition at line 342 of file DWARFUnit.h.
Referenced by dumpLocationList(), and findLoclistFromOffset().
getLoclistOffset()
Optional< uint64_t > DWARFUnit::getLoclistOffset (uint32_t Index)
Definition at line 1024 of file DWARFUnit.cpp.
References getFormat(), llvm::DWARFListTableHeader::getOffsetEntry(), and llvm::None.
Referenced by dumpLocationList().
getLocSectionBase()
uint64_t llvm::DWARFUnit::getLocSectionBase () const inline
Definition at line 328 of file DWARFUnit.h.
getNextUnitOffset()
uint64_t llvm::DWARFUnit::getNextUnitOffset () const inline
Definition at line 298 of file DWARFUnit.h.
References llvm::DWARFUnitHeader::getNextUnitOffset().
Referenced by llvm::DWARFCompileUnit::dump(), llvm::DWARFTypeUnit::dump(), and llvm::DWARFDebugInfoEntry::extractFast().
getNonSkeletonUnitDIE()
DWARFDie llvm::DWARFUnit::getNonSkeletonUnitDIE (bool ExtractUnitDIEOnly = true) inline
Definition at line 397 of file DWARFUnit.h.
References getUnitDIE().
getNumDIEs()
unsigned llvm::DWARFUnit::getNumDIEs () inline
Returns the number of DIEs in the unit.
Parses the unit if necessary.
Definition at line 448 of file DWARFUnit.h.
Referenced by llvm::CompileUnit::CompileUnit().
getOffset()
uint64_t llvm::DWARFUnit::getOffset () const inline
Definition at line 281 of file DWARFUnit.h.
References llvm::DWARFUnitHeader::getOffset().
Referenced by llvm::DWARFCompileUnit::dump(), llvm::DWARFTypeUnit::dump(), llvm::DWARFDebugInfoEntry::extractFast(), llvm::prettyPrintBaseTypeRef(), and llvm::DWARFExpression::Operation::verify().
getParent()
DWARFDie DWARFUnit::getParent (const DWARFDebugInfoEntry * Die)
Definition at line 768 of file DWARFUnit.cpp.
References assert(), and llvm::DWARFDebugInfoEntry::getParentIdx().
getPreviousSibling()
DWARFDie DWARFUnit::getPreviousSibling (const DWARFDebugInfoEntry * Die)
Definition at line 794 of file DWARFUnit.cpp.
References assert(), and llvm::DWARFDebugInfoEntry::getParentIdx().
getRefAddrByteSize()
uint8_t llvm::DWARFUnit::getRefAddrByteSize () const inline
Definition at line 287 of file DWARFUnit.h.
References llvm::DWARFUnitHeader::getRefAddrByteSize().
getRnglistOffset()
Optional< uint64_t > DWARFUnit::getRnglistOffset (uint32_t Index)
Return a rangelist's offset based on an index.
The index designates an entry in the rangelist table's offset array and is supplied by DW_FORM_rnglistx.
Definition at line 1013 of file DWARFUnit.cpp.
References Context, llvm::DWARFSection::Data, getAddressByteSize(), getFormat(), llvm::DWARFListTableHeader::getOffsetEntry(), and llvm::None.
Referenced by dumpAttribute(), and findRnglistFromIndex().
getSibling()
DWARFDie DWARFUnit::getSibling (const DWARFDebugInfoEntry * Die)
Definition at line 781 of file DWARFUnit.cpp.
References assert(), and llvm::DWARFDebugInfoEntry::getSiblingIdx().
getStringExtractor()
DataExtractor llvm::DWARFUnit::getStringExtractor () const inline
Definition at line 338 of file DWARFUnit.h.
getStringOffsetsBase()
uint64_t llvm::DWARFUnit::getStringOffsetsBase () const inline
Definition at line 362 of file DWARFUnit.h.
References assert().
Referenced by getStringOffsetSectionItem().
getStringOffsetSection()
const DWARFSection& llvm::DWARFUnit::getStringOffsetSection () const inline
Definition at line 301 of file DWARFUnit.h.
getStringOffsetSectionItem()
Expected< uint64_t > DWARFUnit::getStringOffsetSectionItem (uint32_t Index) const
Definition at line 217 of file DWARFUnit.cpp.
References Context, llvm::M68kBeads::DA, llvm::DWARFSection::Data, getDwarfStringOffsetsByteSize(), getStringOffsetsBase(), llvm::inconvertibleErrorCode(), Offset, and llvm::StringRef::size().
getStringOffsetsTableContribution()
const Optional<StrOffsetsContributionDescriptor>& llvm::DWARFUnit::getStringOffsetsTableContribution () const inline
Definition at line 353 of file DWARFUnit.h.
getStringSection()
StringRef llvm::DWARFUnit::getStringSection () const inline
Definition at line 300 of file DWARFUnit.h.
getSubroutineForAddress()
DWARFDie DWARFUnit::getSubroutineForAddress (uint64_t Address)
Returns subprogram DIE with address range encompassing the provided address.
The pointer is alive as long as parsed compile unit DIEs are not cleared.
Definition at line 724 of file DWARFUnit.cpp.
References llvm::Address, getUnitDIE(), and updateAddressDieMap().
Referenced by getInlinedChainForAddress().
getUnitDIE()
DWARFDie llvm::DWARFUnit::getUnitDIE (bool ExtractUnitDIEOnly = true) inline
Definition at line 390 of file DWARFUnit.h.
Referenced by buildLineToUnitMap(), collectAddressRanges(), llvm::CompileUnit::CompileUnit(), llvm::CompileUnit::createOutputDIE(), determineStringOffsetsTableContribution(), llvm::DWARFCompileUnit::dump(), llvm::DWARFTypeUnit::dump(), llvm::DwarfStreamer::emitLocationsForUnit(), getBaseAddress(), getCompilationDir(), llvm::CompileUnit::getLanguage(), getLastChild(), llvm::DWARFContext::getLineTableForUnit(), getNonSkeletonUnitDIE(), getSubroutineForAddress(), and llvm::CompileUnit::getSysRoot().
getUnitType()
uint8_t llvm::DWARFUnit::getUnitType () const inline
Definition at line 295 of file DWARFUnit.h.
References llvm::DWARFUnitHeader::getUnitType().
Referenced by llvm::DWARFCompileUnit::dump(), and llvm::DWARFTypeUnit::dump().
getUnitVector()
const DWARFUnitVector& llvm::DWARFUnit::getUnitVector () const inline
Return the DWARFUnitVector containing this unit.
Definition at line 444 of file DWARFUnit.h.
getVersion()
uint16_t llvm::DWARFUnit::getVersion () const inline
Definition at line 285 of file DWARFUnit.h.
References llvm::DWARFUnitHeader::getVersion().
Referenced by determineStringOffsetsTableContributionDWO(), llvm::DWARFCompileUnit::dump(), llvm::DWARFTypeUnit::dump(), findRnglistFromOffset(), and tryExtractDIEsIfNeeded().
isDWOUnit()
bool llvm::DWARFUnit::isDWOUnit () const inline
Definition at line 278 of file DWARFUnit.h.
isMatchingUnitTypeAndTag()
static bool llvm::DWARFUnit::isMatchingUnitTypeAndTag (uint8_t UnitType, dwarf::Tag Tag) inline static
Definition at line 371 of file DWARFUnit.h.
References llvm::dwarf::isUnitType().
isTypeUnit()
bool llvm::DWARFUnit::isTypeUnit () const inline
Definition at line 296 of file DWARFUnit.h.
References llvm::DWARFUnitHeader::isTypeUnit().
Referenced by llvm::DWARFCompileUnit::classof(), and llvm::DWARFTypeUnit::classof().
setAddrOffsetSection()
void llvm::DWARFUnit::setAddrOffsetSection (const DWARFSection * AOS, uint64_t Base) inline
Definition at line 311 of file DWARFUnit.h.
References llvm::sampleprof::Base.
setDWOId()
void llvm::DWARFUnit::setDWOId (uint64_t NewID) inline
Definition at line 409 of file DWARFUnit.h.
References llvm::DWARFUnitHeader::setDWOId().
setRangesSection()
void llvm::DWARFUnit::setRangesSection (const DWARFSection * RS, uint64_t Base) inline
Definition at line 323 of file DWARFUnit.h.
References llvm::sampleprof::Base.
Referenced by tryExtractDIEsIfNeeded().
setSkeletonUnit()
void llvm::DWARFUnit::setSkeletonUnit (DWARFUnit * SU) inline
Definition at line 305 of file DWARFUnit.h.
tryExtractDIEsIfNeeded()
Error DWARFUnit::tryExtractDIEsIfNeeded (bool CUDieOnly)
Definition at line 469 of file DWARFUnit.cpp.
References assert(), C, Context, llvm::createStringError(), llvm::M68kBeads::DA, llvm::Data, determineStringOffsetsTableContribution(), determineStringOffsetsTableContributionDWO(), llvm::DW_SECT_EXT_LOC, llvm::DWARFDie::find(), getAddressByteSize(), llvm::DWARFUnitHeader::getFormat(), llvm::DWARFListTableHeader::getHeaderSize(), llvm::DWARFUnitHeader::getIndexEntry(), llvm::DWARFUnitHeader::getVersion(), getVersion(), llvm::invalid_argument, llvm::None, llvm::DWARFUnitHeader::setDWOId(), setRangesSection(), llvm::Error::success(), llvm::dwarf::toSectionOffset(), llvm::toString(), and llvm::dwarf::toUnsigned().
updateAddressDieMap()
void DWARFUnit::updateAddressDieMap (DWARFDie Die)
Recursively update address to Die map.
Definition at line 693 of file DWARFUnit.cpp.
References B, llvm::consumeError(), llvm::DWARFDie::getAddressRanges(), llvm::DWARFDie::getFirstChild(), llvm::DWARFDie::getSibling(), and llvm::DWARFDie::isSubroutineDIE().
Referenced by getSubroutineForAddress().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFUnit.h
lib/DebugInfo/DWARF/DWARFUnit.cpp