LLVM: llvm::InlineSizePriority Class Reference
llvm::InlineSizePriority Class Reference
#include "llvm/Analysis/InlineOrder.h"
Public Member Functions
InlineSizePriority (int Size)
Static Public Member Functions
static bool isMoreDesirable (const InlineSizePriority &S1, const InlineSizePriority &S2)
static InlineSizePriority evaluate (CallBase *CB)
Public Attributes
int Size
Detailed Description
Definition at line 74 of file InlineOrder.h.
Constructor & Destructor Documentation
InlineSizePriority()
llvm::InlineSizePriority::InlineSizePriority (int Size) inline
Definition at line 76 of file InlineOrder.h.
Referenced by evaluate().
Member Function Documentation
evaluate()
static InlineSizePriority llvm::InlineSizePriority::evaluate (CallBase * CB) inline static
Definition at line 83 of file InlineOrder.h.
References Callee, llvm::CallBase::getCalledFunction(), and InlineSizePriority().
isMoreDesirable()
static bool llvm::InlineSizePriority::isMoreDesirable (const InlineSizePriority & S1, const InlineSizePriority & S2) inline static
Definition at line 78 of file InlineOrder.h.
References Size.
Member Data Documentation
Size
int llvm::InlineSizePriority::Size
Definition at line 88 of file InlineOrder.h.
Referenced by isMoreDesirable().
The documentation for this class was generated from the following file:
include/llvm/Analysis/InlineOrder.h