LLVM: llvm::DebugEpochBase Class Reference
llvm::DebugEpochBase Class Reference
#include "llvm/ADT/EpochTracker.h"
Classes
class HandleBase
Public Member Functions
void incrementEpoch ()
Detailed Description
Definition at line 82 of file EpochTracker.h.
Member Function Documentation
incrementEpoch()
void llvm::DebugEpochBase::incrementEpoch () inline
Definition at line 84 of file EpochTracker.h.
Referenced by llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::SmallPtrSetImplBase::clear(), llvm::SmallPtrSetImplBase::insert_imp(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::reserve(), and llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::swap().
The documentation for this class was generated from the following file:
include/llvm/ADT/EpochTracker.h