LLVM: include/llvm/Transforms/Utils/Debugify.h File Reference
Debugify.h File Reference
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Bitcode/BitcodeWriterPass.h"
#include "llvm/IR/IRPrintingPasses.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/Pass.h"
Classes
struct DebugInfoPerPass
Used to track the Debug Info Metadata information.
struct NewPMDebugifyPass
struct DebugifyStatistics
Track how much debugify information (in the synthetic mode only) has been lost.
struct NewPMCheckDebugifyPass
struct llvm::DebugifyEachInstrumentation
class llvm::DebugifyCustomPassManager
DebugifyCustomPassManager wraps each pass with the debugify passes if needed.
Namespaces
llvm
/file This file defines the SmallVector class.
Typedefs
using DebugFnMap = llvm::MapVector< llvm::StringRef, const llvm::DISubprogram * >
using DebugInstMap = llvm::MapVector< const llvm::Instruction *, bool >
using DebugVarMap = llvm::MapVector< const llvm::DILocalVariable *, unsigned >
using WeakInstValueMap = llvm::MapVector< const llvm::Instruction *, llvm::WeakVH >
using DebugInfoPerPassMap = llvm::MapVector< llvm::StringRef, DebugInfoPerPass >
Map pass names to a per-pass DebugInfoPerPass instance.
using DebugifyStatsMap = llvm::MapVector< llvm::StringRef, DebugifyStatistics >
Map pass names to a per-pass DebugifyStatistics instance.
Enumerations
enum class DebugifyMode { NoDebugify , SyntheticDebugInfo , OriginalDebugInfo }
Used to check whether we track synthetic or original debug info.
Functions
bool llvm::applyDebugifyMetadata (Module &M, iterator_range< Module::iterator > Functions, StringRef Banner, std::function< bool(DIBuilder &, Function &)> ApplyToMF)
Add synthesized debug information to a module.
bool llvm::stripDebugifyMetadata (Module &M)
Strip out all of the metadata and debug info inserted by debugify.
bool llvm::collectDebugInfoMetadata (Module &M, iterator_range< Module::iterator > Functions, DebugInfoPerPassMap &DIPreservationMap, StringRef Banner, StringRef NameOfWrappedPass)
Collect original debug information before a pass.
bool llvm::checkDebugInfoMetadata (Module &M, iterator_range< Module::iterator > Functions, DebugInfoPerPassMap &DIPreservationMap, StringRef Banner, StringRef NameOfWrappedPass, StringRef OrigDIVerifyBugsReportFilePath)
Check original debug information after a pass.
llvm::ModulePass * createDebugifyModulePass (enum DebugifyMode Mode=DebugifyMode::SyntheticDebugInfo, llvm::StringRef NameOfWrappedPass="", DebugInfoPerPassMap *DIPreservationMap=nullptr)
llvm::FunctionPass * createDebugifyFunctionPass (enum DebugifyMode Mode=DebugifyMode::SyntheticDebugInfo, llvm::StringRef NameOfWrappedPass="", DebugInfoPerPassMap *DIPreservationMap=nullptr)
llvm::ModulePass * createCheckDebugifyModulePass (bool Strip=false, llvm::StringRef NameOfWrappedPass="", DebugifyStatsMap *StatsMap=nullptr, enum DebugifyMode Mode=DebugifyMode::SyntheticDebugInfo, DebugInfoPerPassMap *DIPreservationMap=nullptr, llvm::StringRef OrigDIVerifyBugsReportFilePath="")
llvm::FunctionPass * createCheckDebugifyFunctionPass (bool Strip=false, llvm::StringRef NameOfWrappedPass="", DebugifyStatsMap *StatsMap=nullptr, enum DebugifyMode Mode=DebugifyMode::SyntheticDebugInfo, DebugInfoPerPassMap *DIPreservationMap=nullptr, llvm::StringRef OrigDIVerifyBugsReportFilePath="")
void llvm::exportDebugifyStats (StringRef Path, const DebugifyStatsMap &Map)
Typedef Documentation
DebugFnMap
using DebugFnMap = llvm::MapVector<llvm::StringRef, const llvm::DISubprogram *>
Definition at line 26 of file Debugify.h.
DebugifyStatsMap
using DebugifyStatsMap = llvm::MapVector<llvm::StringRef, DebugifyStatistics>
Map pass names to a per-pass DebugifyStatistics instance.
Definition at line 137 of file Debugify.h.
DebugInfoPerPassMap
using DebugInfoPerPassMap = llvm::MapVector<llvm::StringRef, DebugInfoPerPass>
Map pass names to a per-pass DebugInfoPerPass instance.
Definition at line 46 of file Debugify.h.
DebugInstMap
using DebugInstMap = llvm::MapVector<const llvm::Instruction *, bool>
Definition at line 27 of file Debugify.h.
DebugVarMap
using DebugVarMap = llvm::MapVector<const llvm::DILocalVariable *, unsigned>
Definition at line 28 of file Debugify.h.
WeakInstValueMap
using WeakInstValueMap = llvm::MapVector<const llvm::Instruction *, llvm::WeakVH>
Definition at line 29 of file Debugify.h.
Enumeration Type Documentation
DebugifyMode
enum DebugifyMode strong
Used to check whether we track synthetic or original debug info.
Enumerator
NoDebugify
SyntheticDebugInfo
OriginalDebugInfo
Definition at line 95 of file Debugify.h.
Function Documentation
createCheckDebugifyFunctionPass()
llvm::FunctionPass* createCheckDebugifyFunctionPass (bool Strip = false, llvm::StringRef NameOfWrappedPass = "", DebugifyStatsMap * StatsMap = nullptr, enum DebugifyMode Mode = DebugifyMode::SyntheticDebugInfo, DebugInfoPerPassMap * DIPreservationMap = nullptr, llvm::StringRef OrigDIVerifyBugsReportFilePath = "")
Definition at line 961 of file Debugify.cpp.
References assert(), Mode, OriginalDebugInfo, and SyntheticDebugInfo.
Referenced by llvm::DebugifyCustomPassManager::add().
createCheckDebugifyModulePass()
llvm::ModulePass* createCheckDebugifyModulePass (bool Strip = false, llvm::StringRef NameOfWrappedPass = "", DebugifyStatsMap * StatsMap = nullptr, enum DebugifyMode Mode = DebugifyMode::SyntheticDebugInfo, DebugInfoPerPassMap * DIPreservationMap = nullptr, llvm::StringRef OrigDIVerifyBugsReportFilePath = "")
Definition at line 949 of file Debugify.cpp.
References assert(), Mode, OriginalDebugInfo, and SyntheticDebugInfo.
Referenced by llvm::DebugifyCustomPassManager::add().
createDebugifyFunctionPass()
llvm::FunctionPass* createDebugifyFunctionPass (enum DebugifyMode Mode = DebugifyMode::SyntheticDebugInfo, llvm::StringRef NameOfWrappedPass = "", DebugInfoPerPassMap * DIPreservationMap = nullptr)
Definition at line 934 of file Debugify.cpp.
References assert(), Mode, OriginalDebugInfo, and SyntheticDebugInfo.
Referenced by llvm::DebugifyCustomPassManager::add().
createDebugifyModulePass()
llvm::ModulePass* createDebugifyModulePass (enum DebugifyMode Mode = DebugifyMode::SyntheticDebugInfo, llvm::StringRef NameOfWrappedPass = "", DebugInfoPerPassMap * DIPreservationMap = nullptr)
Definition at line 924 of file Debugify.cpp.
References assert(), Mode, OriginalDebugInfo, and SyntheticDebugInfo.
Referenced by llvm::DebugifyCustomPassManager::add().