LLVM: lib/CodeGen/AsmPrinter/DwarfUnit.cpp File Reference
DwarfUnit.cpp File Reference
#include "DwarfUnit.h"
#include "AddressPool.h"
#include "DwarfCompileUnit.h"
#include "DwarfExpression.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/Metadata.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MachineLocation.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include <cassert>
#include <cstdint>
#include <string>
#include <utility>
Macros
#define DEBUG_TYPE "dwarfdebug"
Functions
static bool hasVectorBeenPadded (const DICompositeType *CTy)
Returns true if the vector's size differs from the sum of sizes of elements the user specified.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "dwarfdebug"
Definition at line 46 of file DwarfUnit.cpp.
Function Documentation
hasVectorBeenPadded()
static bool hasVectorBeenPadded (const DICompositeType * CTy) static
Returns true if the vector's size differs from the sum of sizes of elements the user specified.
This can occur if the vector has been rounded up to fit memory alignment constraints.
Definition at line 1453 of file DwarfUnit.cpp.
References assert(), llvm::DICompositeType::getBaseType(), llvm::DICompositeType::getElements(), llvm::DIType::getSizeInBits(), and llvm::DIType::isVector().