LLVM: ExecutionEngine-based ORC Utils
ExecutionEngine-based ORC Utils
LLVM-C: C interface to LLVM » Execution Engine
Functions
LLVMOrcObjectLayerRef LLVMOrcCreateRTDyldObjectLinkingLayerWithSectionMemoryManager (LLVMOrcExecutionSessionRef ES)
Create a RTDyldObjectLinkingLayer instance using the standard SectionMemoryManager for memory management.
void LLVMOrcRTDyldObjectLinkingLayerRegisterJITEventListener (LLVMOrcObjectLayerRef RTDyldObjLinkingLayer, LLVMJITEventListenerRef Listener)
Add the given listener to the given RTDyldObjectLinkingLayer.
Detailed Description
Function Documentation
LLVMOrcCreateRTDyldObjectLinkingLayerWithSectionMemoryManager()
LLVMOrcObjectLayerRef LLVMOrcCreateRTDyldObjectLinkingLayerWithSectionMemoryManager (LLVMOrcExecutionSessionRef ES)
Create a RTDyldObjectLinkingLayer instance using the standard SectionMemoryManager for memory management.
Definition at line 968 of file OrcV2CBindings.cpp.
References assert(), llvm::unwrap(), and llvm::wrap().
LLVMOrcRTDyldObjectLinkingLayerRegisterJITEventListener()
void LLVMOrcRTDyldObjectLinkingLayerRegisterJITEventListener (LLVMOrcObjectLayerRef RTDyldObjLinkingLayer, LLVMJITEventListenerRef Listener)
Add the given listener to the given RTDyldObjectLinkingLayer.
Note: Layer must be an RTDyldObjectLinkingLayer instance or behavior is undefined.
Definition at line 975 of file OrcV2CBindings.cpp.
References assert(), and llvm::unwrap().