LLVM: lib/Debuginfod/HTTPClient.cpp File Reference
HTTPClient.cpp File Reference
This file defines the methods of the HTTPRequest, HTTPClient, and BufferedHTTPResponseHandler classes.
#include "llvm/Debuginfod/HTTPClient.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/MemoryBuffer.h"
Classes
class HTTPClientCleanup
Functions
bool operator== (const HTTPRequest &A, const HTTPRequest &B)
static bool parseContentLengthHeader (StringRef LineRef, size_t &ContentLength)
Variables
static const HTTPClientCleanup Cleanup
Detailed Description
This file defines the methods of the HTTPRequest, HTTPClient, and BufferedHTTPResponseHandler classes.
Definition in file HTTPClient.cpp.
Function Documentation
operator==()
bool operator== (const HTTPRequest & A, const HTTPRequest & B)
Definition at line 30 of file HTTPClient.cpp.
References B.
parseContentLengthHeader()
static bool parseContentLengthHeader (StringRef LineRef, size_t & ContentLength) inline static
Definition at line 37 of file HTTPClient.cpp.
References llvm::StringRef::consume_front(), and llvm::StringRef::trim().
Referenced by llvm::BufferedHTTPResponseHandler::handleHeaderLine().
Variable Documentation
Cleanup
const HTTPClientCleanup Cleanup static
Definition at line 81 of file HTTPClient.cpp.
Referenced by llvm::MachineFunction::addSEHCleanupHandler(), llvm::calculateClrEHStateNumbers(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitPrologue(), and llvm::formDedicatedExitBlocks().