LLVM: lib/Analysis/InlineAdvisor.cpp File Reference
InlineAdvisor.cpp File Reference
#include "llvm/Analysis/InlineAdvisor.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/InlineCost.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/Analysis/ProfileSummaryInfo.h"
#include "llvm/Analysis/ReplayInlineAdvisor.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/PassManager.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/raw_ostream.h"
Namespaces
llvm
/file This file defines the SmallVector class.
Macros
#define DEBUG_TYPE "inline"
Functions
STATISTIC (NumCallerCallersAnalyzed, "Number of caller-callers analyzed")
static llvm::Optional< llvm::InlineCost > getDefaultInlineAdvice (CallBase &CB, FunctionAnalysisManager &FAM, const InlineParams &Params)
static bool shouldBeDeferred (Function *Caller, InlineCost IC, int &TotalSecondaryCost, function_ref< InlineCost(CallBase &CB)> GetInlineCost)
Return true if inlining of CB can block the caller from being inlined which is proved to be more beneficial.
static raw_ostream & llvm::operator<< (raw_ostream &R, const ore::NV &Arg)
template<class RemarkT >
RemarkT & llvm::operator<< (RemarkT &&R, const InlineCost &IC)
Variables
static cl::opt< bool > InlineRemarkAttribute ("inline-remark-attribute", cl::init(false), cl::Hidden, cl::desc("Enable adding inline-remark attribute to" " callsites processed by inliner but decided" " to be not inlined"))
Flag to add inline messages as callsite attributes 'inline-remark'.
static cl::opt< bool > EnableInlineDeferral ("inline-deferral", cl::init(false), cl::Hidden, cl::desc("Enable deferred inlining"))
static cl::opt< int > InlineDeferralScale ("inline-deferral-scale", cl::desc("Scale to limit the cost of inline deferral"), cl::init(2), cl::Hidden)
cl::opt< InlinerFunctionImportStatsOpts > InlinerFunctionImportStats
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "inline"
Definition at line 29 of file InlineAdvisor.cpp.
Function Documentation
getDefaultInlineAdvice()
static llvm::Optional<llvm::InlineCost> getDefaultInlineAdvice (CallBase & CB, FunctionAnalysisManager & FAM, const InlineParams & Params) static
Definition at line 119 of file InlineAdvisor.cpp.
References llvm::InlineAdvice::Callee, llvm::InlineAdvice::Caller, DEBUG_TYPE, llvm::InlineParams::EnableDeferral, EnableInlineDeferral, F, FAM, llvm::CallBase::getCalledFunction(), llvm::CallBase::getCaller(), llvm::Function::getContext(), llvm::LLVMContext::getDiagHandlerPtr(), llvm::getInlineCost(), llvm::GlobalValue::getParent(), llvm::BasicBlock::getParent(), llvm::Instruction::getParent(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::Optional< T >::getValueOr(), llvm::DiagnosticHandler::isMissedOptRemarkEnabled(), llvm::InlineAdvice::ORE, and llvm::shouldInline().
Referenced by llvm::InlineAdvisorAnalysis::Result::tryCreate().
shouldBeDeferred()
static bool shouldBeDeferred (Function * Caller, InlineCost IC, int & TotalSecondaryCost, function_ref< InlineCost(CallBase &CB)> GetInlineCost) static
Return true if inlining of CB can block the caller from being inlined which is proved to be more beneficial.
IC is the estimated inline cost associated with callsite CB. TotalSecondaryCost will be set to the estimated cost of inlining the caller if CB is suppressed for inlining.
Definition at line 229 of file InlineAdvisor.cpp.
References llvm::CallBase::getCalledFunction(), llvm::InlineCost::getCost(), llvm::InlineCost::getCostDelta(), InlineDeferralScale, llvm::InlineCost::isAlways(), and llvm::InlineConstants::LastCallToStaticBonus.
Referenced by llvm::shouldInline().
STATISTIC()
STATISTIC (NumCallerCallersAnalyzed , "Number of caller-callers analyzed")
Variable Documentation
EnableInlineDeferral
cl::opt<bool> EnableInlineDeferral("inline-deferral", cl::init(false), cl::Hidden, cl::desc("Enable deferred inlining")) ("inline-deferral" , cl::init(false) , cl::Hidden , cl::desc("Enable deferred inlining")) static
Referenced by getDefaultInlineAdvice().
InlineDeferralScale
cl::opt<int> InlineDeferralScale("inline-deferral-scale", cl::desc("Scale to limit the cost of inline deferral"), cl::init(2), cl::Hidden) ("inline-deferral-scale" , cl::desc("Scale to limit the cost of inline deferral") , cl::init(2) , cl::Hidden) static
Referenced by shouldBeDeferred().
InlineRemarkAttribute
cl::opt<bool> InlineRemarkAttribute("inline-remark-attribute", cl::init(false), cl::Hidden, cl::desc("Enable adding inline-remark attribute to" " callsites processed by inliner but decided" " to be not inlined")) ("inline-remark-attribute" , cl::init(false) , cl::Hidden , cl::desc("Enable adding inline-remark attribute to" " callsites processed by inliner but decided" " to be not inlined")) static
Flag to add inline messages as callsite attributes 'inline-remark'.
Referenced by llvm::setInlineRemark().
InlinerFunctionImportStats
cl::opt<InlinerFunctionImportStatsOpts> InlinerFunctionImportStats extern
Referenced by llvm::InlineAdvisor::InlineAdvisor(), and llvm::InlineAdvisor::~InlineAdvisor().