LLVM: lib/IR/IntrinsicInst.cpp File Reference
IntrinsicInst.cpp File Reference
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/Statepoint.h"
#include "llvm/IR/ConstrainedOps.def"
#include "llvm/IR/VPIntrinsics.def"
Macros
#define INSTRUCTION(NAME, NARG, ROUND_MODE, INTRINSIC)
#define INSTRUCTION(NAME, NARG, ROUND_MODE, INTRINSIC)
#define INSTRUCTION(NAME, NARGS, ROUND_MODE, INTRINSIC) case Intrinsic::INTRINSIC:
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, MASKPOS, VLENPOS)
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, MASKPOS, VLENPOS)
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, ...) case Intrinsic::VPID:
#define VP_PROPERTY_MEMOP(POINTERPOS, ...) return POINTERPOS;
#define END_REGISTER_VP_INTRINSIC(VPID) break;
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, ...) case Intrinsic::VPID:
#define VP_PROPERTY_MEMOP(POINTERPOS, DATAPOS) return DATAPOS;
#define END_REGISTER_VP_INTRINSIC(VPID) break;
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, MASKPOS, VLENPOS)
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, ...) case Intrinsic::VPID:
#define VP_PROPERTY_FUNCTIONAL_OPC(OPC) return Instruction::OPC;
#define END_REGISTER_VP_INTRINSIC(VPID) break;
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, ...) break;
#define VP_PROPERTY_FUNCTIONAL_OPC(OPC) case Instruction::OPC:
#define END_REGISTER_VP_INTRINSIC(VPID) return Intrinsic::VPID;
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, ...) case Intrinsic::VPID:
#define VP_PROPERTY_REDUCTION(STARTPOS, ...) return true;
#define END_REGISTER_VP_INTRINSIC(VPID) break;
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, ...) case Intrinsic::VPID:
#define VP_PROPERTY_REDUCTION(STARTPOS, VECTORPOS) return VECTORPOS;
#define END_REGISTER_VP_INTRINSIC(VPID) break;
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, ...) case Intrinsic::VPID:
#define VP_PROPERTY_REDUCTION(STARTPOS, VECTORPOS) return STARTPOS;
#define END_REGISTER_VP_INTRINSIC(VPID) break;
Functions
static ValueAsMetadata * getAsMetadata (Value *V)
Macro Definition Documentation
BEGIN_REGISTER_VP_INTRINSIC [1/10]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, MASKPOS, VLENPOS)
Value:
  case Intrinsic::VPID:                                                        \
    return MASKPOS;
BEGIN_REGISTER_VP_INTRINSIC [2/10]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, MASKPOS, VLENPOS)
Value:
  case Intrinsic::VPID:                                                        \
    return VLENPOS;
BEGIN_REGISTER_VP_INTRINSIC [3/10]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, MASKPOS, VLENPOS)
Value:
  case Intrinsic::VPID:                                                        \
    return true;
BEGIN_REGISTER_VP_INTRINSIC [4/10]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, ...) case Intrinsic::VPID:
BEGIN_REGISTER_VP_INTRINSIC [5/10]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, ...) case Intrinsic::VPID:
BEGIN_REGISTER_VP_INTRINSIC [6/10]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, ...) case Intrinsic::VPID:
BEGIN_REGISTER_VP_INTRINSIC [7/10]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, ...) break;
BEGIN_REGISTER_VP_INTRINSIC [8/10]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, ...) case Intrinsic::VPID:
BEGIN_REGISTER_VP_INTRINSIC [9/10]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, ...) case Intrinsic::VPID:
BEGIN_REGISTER_VP_INTRINSIC [10/10]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, ...) case Intrinsic::VPID:
END_REGISTER_VP_INTRINSIC [1/7]
#define END_REGISTER_VP_INTRINSIC (VPID) break;
END_REGISTER_VP_INTRINSIC [2/7]
#define END_REGISTER_VP_INTRINSIC (VPID) break;
END_REGISTER_VP_INTRINSIC [3/7]
#define END_REGISTER_VP_INTRINSIC (VPID) break;
END_REGISTER_VP_INTRINSIC [4/7]
#define END_REGISTER_VP_INTRINSIC (VPID) return Intrinsic::VPID;
END_REGISTER_VP_INTRINSIC [5/7]
#define END_REGISTER_VP_INTRINSIC (VPID) break;
END_REGISTER_VP_INTRINSIC [6/7]
#define END_REGISTER_VP_INTRINSIC (VPID) break;
END_REGISTER_VP_INTRINSIC [7/7]
#define END_REGISTER_VP_INTRINSIC (VPID) break;
INSTRUCTION [1/3]
#define INSTRUCTION (NAME, NARG, ROUND_MODE, INTRINSIC)
Value:
  case Intrinsic::INTRINSIC:                                                   \
    return NARG == 1;
INSTRUCTION [2/3]
#define INSTRUCTION (NAME, NARG, ROUND_MODE, INTRINSIC)
Value:
  case Intrinsic::INTRINSIC:                                                   \
    return NARG == 3;
INSTRUCTION [3/3]
#define INSTRUCTION (NAME, NARGS, ROUND_MODE, INTRINSIC) case Intrinsic::INTRINSIC:
VP_PROPERTY_FUNCTIONAL_OPC [1/2]
#define VP_PROPERTY_FUNCTIONAL_OPC (OPC) return Instruction::OPC;
VP_PROPERTY_FUNCTIONAL_OPC [2/2]
#define VP_PROPERTY_FUNCTIONAL_OPC (OPC) case Instruction::OPC:
VP_PROPERTY_MEMOP [1/2]
#define VP_PROPERTY_MEMOP (POINTERPOS, DATAPOS) return DATAPOS;
VP_PROPERTY_MEMOP [2/2]
#define VP_PROPERTY_MEMOP (POINTERPOS, ...) return POINTERPOS;
VP_PROPERTY_REDUCTION [1/3]
#define VP_PROPERTY_REDUCTION (STARTPOS, VECTORPOS) return VECTORPOS;
VP_PROPERTY_REDUCTION [2/3]
#define VP_PROPERTY_REDUCTION (STARTPOS, VECTORPOS) return STARTPOS;
VP_PROPERTY_REDUCTION [3/3]
#define VP_PROPERTY_REDUCTION (STARTPOS, ...) return true;
Function Documentation
getAsMetadata()
static ValueAsMetadata* getAsMetadata (Value * V) static
Definition at line 74 of file IntrinsicInst.cpp.
References llvm::ValueAsMetadata::get().
Referenced by llvm::DbgVariableIntrinsic::addVariableLocationOps(), and llvm::DbgVariableIntrinsic::replaceVariableLocationOp().