LLVM: lib/CodeGen/SelectionDAG/LegalizeVectorOps.cpp File Reference
LegalizeVectorOps.cpp File Reference
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/CodeGen/ISDOpcodes.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/CodeGen/SelectionDAGNodes.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MachineValueType.h"
#include "llvm/Support/MathExtras.h"
#include <cassert>
#include <cstdint>
#include <iterator>
#include <utility>
#include "llvm/IR/ConstrainedOps.def"
#include "llvm/IR/VPIntrinsics.def"
Macros
#define DEBUG_TYPE "legalizevectorops"
#define DAG_INSTRUCTION(NAME, NARG, ROUND_MODE, INTRINSIC, DAGN) case ISD::STRICT_##DAGN:
#define BEGIN_REGISTER_VP_SDNODE(VPID, LEGALPOS, ...)
#define DAG_INSTRUCTION(NAME, NARG, ROUND_MODE, INTRINSIC, DAGN) case ISD::STRICT_##DAGN:
Functions
static void createBSWAPShuffleMask (EVT VT, SmallVectorImpl< int > &ShuffleMask)
Macro Definition Documentation
BEGIN_REGISTER_VP_SDNODE
#define BEGIN_REGISTER_VP_SDNODE (VPID, LEGALPOS, ...)
Value:
  case ISD::VPID: {                                                            \
    EVT LegalizeVT = LEGALPOS < 0 ? Node->getValueType(-(1 + LEGALPOS))        \
                                  : Node->getOperand(LEGALPOS).getValueType(); \
    Action = TLI.getOperationAction(Node->getOpcode(), LegalizeVT);            \
  } break;
DAG_INSTRUCTION [1/2]
#define DAG_INSTRUCTION (NAME, NARG, ROUND_MODE, INTRINSIC, DAGN) case ISD::STRICT_##DAGN:
DAG_INSTRUCTION [2/2]
#define DAG_INSTRUCTION (NAME, NARG, ROUND_MODE, INTRINSIC, DAGN) case ISD::STRICT_##DAGN:
DEBUG_TYPE
#define DEBUG_TYPE "legalizevectorops"
Definition at line 52 of file LegalizeVectorOps.cpp.
Function Documentation
createBSWAPShuffleMask()
static void createBSWAPShuffleMask (EVT VT, SmallVectorImpl< int > & ShuffleMask) static
Definition at line 1067 of file LegalizeVectorOps.cpp.
References E, llvm::EVT::getScalarSizeInBits(), llvm::EVT::getVectorNumElements(), I, and llvm::SmallVectorTemplateBase< T, bool >::push_back().