LLVM: lib/LTO/LTOBackend.cpp File Reference
LTOBackend.cpp File Reference
#include "llvm/LTO/LTOBackend.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/CGSCCPassManager.h"
#include "llvm/Analysis/ModuleSummaryAnalysis.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Bitcode/BitcodeReader.h"
#include "llvm/Bitcode/BitcodeWriter.h"
#include "llvm/IR/LLVMRemarkStreamer.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/Verifier.h"
#include "llvm/LTO/LTO.h"
#include "llvm/MC/SubtargetFeature.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Object/ModuleSymbolTable.h"
#include "llvm/Passes/PassBuilder.h"
#include "llvm/Passes/PassPlugin.h"
#include "llvm/Passes/StandardInstrumentations.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Program.h"
#include "llvm/Support/ThreadPool.h"
#include "llvm/Support/ToolOutputFile.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Transforms/IPO.h"
#include "llvm/Transforms/IPO/PassManagerBuilder.h"
#include "llvm/Transforms/Scalar/LoopPassManager.h"
#include "llvm/Transforms/Utils/FunctionImportUtils.h"
#include "llvm/Transforms/Utils/SplitModule.h"
#include "llvm/Support/Extension.def"
Namespaces
llvm
/file This file defines the SmallVector class.
Macros
#define DEBUG_TYPE "lto-backend"
#define HANDLE_EXTENSION(Ext) llvm::PassPluginLibraryInfo get##Ext##PluginInfo();
#define HANDLE_EXTENSION(Ext) get##Ext##PluginInfo().RegisterPassBuilderCallbacks(PB);
Enumerations
enum class LTOBitcodeEmbedding { DoNotEmbed = 0 , EmbedOptimized = 1 , EmbedPostMergePreOptimized = 2 }
Functions
static void reportOpenError (StringRef Path, Twine Msg)
static void RegisterPassPlugins (ArrayRef< std::string > PassPlugins, PassBuilder &PB)
static std::unique_ptr< TargetMachine > createTargetMachine (const Config &Conf, const Target *TheTarget, Module &M)
static void runNewPMPasses (const Config &Conf, Module &Mod, TargetMachine *TM, unsigned OptLevel, bool IsThinLTO, ModuleSummaryIndex *ExportSummary, const ModuleSummaryIndex *ImportSummary)
static void runOldPMPasses (const Config &Conf, Module &Mod, TargetMachine *TM, bool IsThinLTO, ModuleSummaryIndex *ExportSummary, const ModuleSummaryIndex *ImportSummary)
static void codegen (const Config &Conf, TargetMachine *TM, AddStreamFn AddStream, unsigned Task, Module &Mod, const ModuleSummaryIndex &CombinedIndex)
static void splitCodeGen (const Config &C, TargetMachine *TM, AddStreamFn AddStream, unsigned ParallelCodeGenParallelismLevel, Module &Mod, const ModuleSummaryIndex &CombinedIndex)
static Expected< const Target * > initAndLookupTarget (const Config &C, Module &Mod)
static void dropDeadSymbols (Module &Mod, const GVSummaryMapTy &DefinedGlobals, const ModuleSummaryIndex &Index)
Variables
static cl::opt< LTOBitcodeEmbedding > EmbedBitcode ("lto-embed-bitcode", cl::init(LTOBitcodeEmbedding::DoNotEmbed), cl::values(clEnumValN(LTOBitcodeEmbedding::DoNotEmbed, "none", "Do not embed"), clEnumValN(LTOBitcodeEmbedding::EmbedOptimized, "optimized", "Embed after all optimization passes"), clEnumValN(LTOBitcodeEmbedding::EmbedPostMergePreOptimized, "post-merge-pre-opt", "Embed post merge, but before optimizations")), cl::desc("Embed LLVM bitcode in object files produced by LTO"))
static cl::opt< bool > ThinLTOAssumeMerged ("thinlto-assume-merged", cl::init(false), cl::desc("Assume the input has already undergone ThinLTO function " "importing and the other pre-optimization pipeline changes."))
cl::opt< bool > llvm::NoPGOWarnMismatch
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "lto-backend"
Definition at line 53 of file LTOBackend.cpp.
HANDLE_EXTENSION [1/2]
#define HANDLE_EXTENSION (Ext) llvm::PassPluginLibraryInfo get##Ext##PluginInfo();
Definition at line 161 of file LTOBackend.cpp.
HANDLE_EXTENSION [2/2]
#define HANDLE_EXTENSION (Ext) get##Ext##PluginInfo().RegisterPassBuilderCallbacks(PB);
Definition at line 161 of file LTOBackend.cpp.
Enumeration Type Documentation
LTOBitcodeEmbedding
enum LTOBitcodeEmbedding strong
Enumerator
DoNotEmbed
EmbedOptimized
EmbedPostMergePreOptimized
Definition at line 55 of file LTOBackend.cpp.
Function Documentation
codegen()
static void codegen (const Config & Conf, TargetMachine * TM, AddStreamFn AddStream, unsigned Task, Module & Mod, const ModuleSummaryIndex & CombinedIndex) static
Definition at line 377 of file LTOBackend.cpp.
References llvm::sys::path::append(), llvm::sys::fs::create_directories(), llvm::lto::Config::DwoDir, EmbedBitcode, llvm::embedBitcodeInModule(), EmbedOptimized, llvm::SmallVectorBase< Size_T >::empty(), Mod, llvm::sys::fs::OF_None, llvm::lto::Config::PreCodeGenModuleHook, llvm::report_fatal_error(), llvm::lto::Config::SplitDwarfFile, llvm::lto::Config::SplitDwarfOutput, TM, and llvm::to_string().
Referenced by llvm::lto::backend(), splitCodeGen(), and llvm::lto::thinBackend().
createTargetMachine()
static std::unique_ptr<TargetMachine> createTargetMachine (const Config & Conf, const Target * TheTarget, Module & M) static
Definition at line 185 of file LTOBackend.cpp.
References llvm::SubtargetFeatures::AddFeature(), assert(), llvm::lto::Config::CGOptLevel, llvm::lto::Config::CodeModel, llvm::lto::Config::CPU, llvm::Target::createTargetMachine(), llvm::SubtargetFeatures::getDefaultSubtargetFeatures(), llvm::SubtargetFeatures::getString(), llvm::lto::Config::MAttrs, llvm::None, llvm::PICLevel::NotPIC, llvm::lto::Config::Options, llvm::Reloc::PIC_, llvm::lto::Config::RelocModel, llvm::Reloc::Static, and TM.
Referenced by llvm::lto::backend(), splitCodeGen(), and llvm::lto::thinBackend().
dropDeadSymbols()
static void dropDeadSymbols (Module & Mod, const GVSummaryMapTy & DefinedGlobals, const ModuleSummaryIndex & Index) static
Definition at line 535 of file LTOBackend.cpp.
References llvm::convertToDeclaration(), llvm::Module::global_values(), Index, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), and Mod.
Referenced by llvm::lto::thinBackend().
initAndLookupTarget()
static Expected<const Target *> initAndLookupTarget (const Config & C, Module & Mod) static
Definition at line 485 of file LTOBackend.cpp.
References C, llvm::Module::getTargetTriple(), llvm::inconvertibleErrorCode(), llvm::TargetRegistry::lookupTarget(), Mod, llvm::Module::setTargetTriple(), and T.
Referenced by llvm::lto::backend(), and llvm::lto::thinBackend().
RegisterPassPlugins()
static void RegisterPassPlugins (ArrayRef< std::string > PassPlugins, PassBuilder & PB) static
Definition at line 165 of file LTOBackend.cpp.
References llvm::errs(), llvm::PassPlugin::Load(), PB(), and llvm::PassPlugin::registerPassBuilderCallbacks().
Referenced by runNewPMPasses().
reportOpenError()
static void reportOpenError (StringRef Path, Twine Msg) static
Definition at line 81 of file LTOBackend.cpp.
References llvm::errs(), and llvm::raw_ostream::flush().
Referenced by llvm::lto::Config::addSaveTemps().
runNewPMPasses()
static void runNewPMPasses (const Config & Conf, Module & Mod, TargetMachine * TM, unsigned OptLevel, bool IsThinLTO, ModuleSummaryIndex * ExportSummary, const ModuleSummaryIndex * ImportSummary) static
Definition at line 212 of file LTOBackend.cpp.
References llvm::lto::Config::AAPipeline, llvm::lto::Config::AddFSDiscriminator, CGAM, llvm::PGOOptions::CSIRInstr, llvm::lto::Config::CSIRProfile, llvm::PGOOptions::CSIRUse, llvm::lto::Config::DebugPassManager, FAM, llvm::lto::Config::Freestanding, llvm::PGOOptions::IRUse, LAM, MAM, llvm::PGOOptions::NoAction, llvm::PGOOptions::NoCSAction, llvm::NoPGOWarnMismatch, llvm::lto::Config::PassPlugins, PB(), llvm::lto::Config::PGOWarnMismatch, PIC, llvm::lto::Config::ProfileRemapping, llvm::lto::Config::PTO, llvm::StandardInstrumentations::registerCallbacks(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::registerPass(), RegisterPassPlugins(), llvm::lto::Config::RunCSIRInstr, llvm::lto::Config::SampleProfile, llvm::PGOOptions::SampleUse, SI, and TM.
Referenced by llvm::lto::opt().
runOldPMPasses()
static void runOldPMPasses (const Config & Conf, Module & Mod, TargetMachine * TM, bool IsThinLTO, ModuleSummaryIndex * ExportSummary, const ModuleSummaryIndex * ImportSummary) static
Definition at line 313 of file LTOBackend.cpp.
References llvm::legacy::PassManager::add(), llvm::createFunctionInliningPass(), llvm::createTargetTransformInfoWrapperPass(), llvm::lto::Config::CSIRProfile, llvm::TargetLibraryInfoImpl::disableAllFunctions(), llvm::lto::Config::DisableVerify, llvm::PassManagerBuilder::EnablePGOCSInstrGen, llvm::PassManagerBuilder::EnablePGOCSInstrUse, llvm::PassManagerBuilder::ExportSummary, llvm::lto::Config::Freestanding, llvm::PassManagerBuilder::ImportSummary, llvm::PassManagerBuilder::Inliner, llvm::PassManagerBuilder::LibraryInfo, llvm::PassManagerBuilder::LoopVectorize, Mod, llvm::lto::Config::OptLevel, llvm::PassManagerBuilder::OptLevel, llvm::PassManagerBuilder::PGOInstrUse, llvm::PassManagerBuilder::PGOSampleUse, llvm::PassManagerBuilder::populateLTOPassManager(), llvm::PassManagerBuilder::populateThinLTOPassManager(), llvm::legacy::PassManager::run(), llvm::lto::Config::RunCSIRInstr, llvm::lto::Config::SampleProfile, llvm::PassManagerBuilder::SLPVectorize, TM, llvm::PassManagerBuilder::VerifyInput, and llvm::PassManagerBuilder::VerifyOutput.
Referenced by llvm::lto::opt().
splitCodeGen()
static void splitCodeGen (const Config & C, TargetMachine * TM, AddStreamFn AddStream, unsigned ParallelCodeGenParallelismLevel, Module & Mod, const ModuleSummaryIndex & CombinedIndex) static
Definition at line 434 of file LTOBackend.cpp.
References llvm::ThreadPool::async(), C, codegen(), createTargetMachine(), llvm::SmallVectorTemplateCommon< T, typename >::data(), llvm::Expected< T >::get(), llvm::heavyweight_hardware_concurrency(), Mod, llvm::move(), llvm::parseBitcodeFile(), llvm::report_fatal_error(), llvm::SmallVectorBase< Size_T >::size(), llvm::SplitModule(), T, TM, llvm::ThreadPool::wait(), and llvm::WriteBitcodeToFile().
Variable Documentation
EmbedBitcode
cl::opt<LTOBitcodeEmbedding> EmbedBitcode("lto-embed-bitcode", cl::init(LTOBitcodeEmbedding::DoNotEmbed), cl::values(clEnumValN(LTOBitcodeEmbedding::DoNotEmbed, "none", "Do not embed"), clEnumValN(LTOBitcodeEmbedding::EmbedOptimized, "optimized", "Embed after all optimization passes"), clEnumValN(LTOBitcodeEmbedding::EmbedPostMergePreOptimized, "post-merge-pre-opt", "Embed post merge, but before optimizations")), cl::desc("Embed LLVM bitcode in object files produced by LTO")) ("lto-embed-bitcode" , cl::init(LTOBitcodeEmbedding::DoNotEmbed) , cl::values(clEnumValN(LTOBitcodeEmbedding::DoNotEmbed, "none", "Do not embed"), clEnumValN(LTOBitcodeEmbedding::EmbedOptimized, "optimized", "Embed after all optimization passes"), clEnumValN(LTOBitcodeEmbedding::EmbedPostMergePreOptimized, "post-merge-pre-opt", "Embed post merge, but before optimizations")) , cl::desc("Embed LLVM bitcode in object files produced by LTO")) static
Referenced by codegen(), llvm::embedBitcodeInModule(), and llvm::lto::opt().
ThinLTOAssumeMerged
cl::opt<bool> ThinLTOAssumeMerged("thinlto-assume-merged", cl::init(false), cl::desc("Assume the input has already undergone ThinLTO function " "importing and the other pre-optimization pipeline changes.")) ("thinlto-assume-merged" , cl::init(false) , cl::desc("Assume the input has already undergone ThinLTO function " "importing and the other pre-optimization pipeline changes.")) static
Referenced by llvm::lto::findThinLTOModule(), llvm::lto::initImportList(), and llvm::lto::thinBackend().