LLVM: lib/MC/MCObjectStreamer.cpp File Reference
MCObjectStreamer.cpp File Reference
#include "llvm/MC/MCObjectStreamer.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCCodeView.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/SourceMgr.h"
Functions
static Optional< uint64_t > absoluteSymbolDiff (const MCSymbol *Hi, const MCSymbol *Lo)
static bool canReuseDataFragment (const MCDataFragment &F, const MCAssembler &Assembler, const MCSubtargetInfo *STI)
static const MCExpr * buildSymbolDiff (MCObjectStreamer &OS, const MCSymbol *A, const MCSymbol *B)
static void emitDwarfSetLineAddr (MCObjectStreamer &OS, MCDwarfLineTableParams Params, int64_t LineDelta, const MCSymbol *Label, int PointerSize)
static Optional< std::pair< bool, std::string > > getOffsetAndDataFragment (const MCSymbol &Symbol, uint32_t &RelocOffset, MCDataFragment *&DF)
Variables
static const char *const BundlingNotImplementedMsg
Function Documentation
absoluteSymbolDiff()
static Optional<uint64_t> absoluteSymbolDiff (const MCSymbol * Hi, const MCSymbol * Lo) static
Definition at line 153 of file MCObjectStreamer.cpp.
References assert(), llvm::MipsISD::Hi, llvm::MipsISD::Lo, and llvm::None.
Referenced by llvm::MCObjectStreamer::emitAbsoluteSymbolDiff(), and llvm::MCObjectStreamer::emitAbsoluteSymbolDiffAsULEB128().
buildSymbolDiff()
static const MCExpr* buildSymbolDiff (MCObjectStreamer & OS, const MCSymbol * A, const MCSymbol * B) static
Definition at line 509 of file MCObjectStreamer.cpp.
References B, Context, llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::create(), llvm::MCStreamer::getContext(), llvm::MCBinaryExpr::Sub, and llvm::MCSymbolRefExpr::VK_None.
Referenced by llvm::MCObjectStreamer::emitDwarfAdvanceFrameAddr(), and llvm::MCObjectStreamer::emitDwarfAdvanceLineAddr().
canReuseDataFragment()
static bool canReuseDataFragment (const MCDataFragment & F, const MCAssembler & Assembler, const MCSubtargetInfo * STI) static
Definition at line 211 of file MCObjectStreamer.cpp.
References F, llvm::MCAssembler::getRelaxAll(), and llvm::MCAssembler::isBundlingEnabled().
Referenced by llvm::MCObjectStreamer::getOrCreateDataFragment().
emitDwarfSetLineAddr()
static void emitDwarfSetLineAddr (MCObjectStreamer & OS, MCDwarfLineTableParams Params, int64_t LineDelta, const MCSymbol * Label, int PointerSize) static
Definition at line 520 of file MCObjectStreamer.cpp.
References llvm::MCDwarfLineAddr::Emit(), llvm::MCStreamer::emitIntValue(), llvm::MCStreamer::emitSymbolValue(), llvm::MCStreamer::emitULEB128IntValue(), and llvm::jitlink::x86_64::PointerSize.
Referenced by llvm::MCObjectStreamer::emitDwarfAdvanceLineAddr().
getOffsetAndDataFragment()
static Optional<std::pair<bool, std::string> > getOffsetAndDataFragment (const MCSymbol & Symbol, uint32_t & RelocOffset, MCDataFragment *& DF) static
Definition at line 733 of file MCObjectStreamer.cpp.
References DF, llvm::MCExpr::evaluateAsRelocatable(), llvm::MCFragment::FT_Data, llvm::MCValue::getConstant(), llvm::MCSymbol::getFragment(), llvm::MCFragment::getKind(), llvm::MCSymbol::getOffset(), llvm::MCValue::getSymA(), llvm::MCValue::getSymB(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCValue::isAbsolute(), llvm::MCSymbol::isDefined(), llvm::MCSymbol::isVariable(), llvm::None, and llvm::ARMBuildAttrs::Symbol.
Referenced by llvm::MCObjectStreamer::emitRelocDirective().
Variable Documentation
BundlingNotImplementedMsg
const char* const BundlingNotImplementedMsg static
Initial value:
=
  "Aligned bundling is not implemented for this object format"
Definition at line 480 of file MCObjectStreamer.cpp.
Referenced by llvm::MCObjectStreamer::emitBundleAlignMode(), llvm::MCObjectStreamer::emitBundleLock(), and llvm::MCObjectStreamer::emitBundleUnlock().