LLVM: lib/Target/Mips/MipsTargetObjectFile.cpp File Reference
MipsTargetObjectFile.cpp File Reference
#include "MipsTargetObjectFile.h"
#include "MipsSubtarget.h"
#include "MipsTargetMachine.h"
#include "MCTargetDesc/MipsMCExpr.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Target/TargetMachine.h"
Functions
static bool IsInSmallSection (uint64_t Size)
Variables
static cl::opt< unsigned > SSThreshold ("mips-ssection-threshold", cl::Hidden, cl::desc("Small data and bss section threshold size (default=8)"), cl::init(8))
static cl::opt< bool > LocalSData ("mlocal-sdata", cl::Hidden, cl::desc("MIPS: Use gp_rel for object-local data."), cl::init(true))
static cl::opt< bool > ExternSData ("mextern-sdata", cl::Hidden, cl::desc("MIPS: Use gp_rel for data that is not defined by the " "current object."), cl::init(true))
static cl::opt< bool > EmbeddedData ("membedded-data", cl::Hidden, cl::desc("MIPS: Try to allocate variables in the following" " sections if possible: .rodata, .sdata, .data ."), cl::init(false))
Function Documentation
IsInSmallSection()
static bool IsInSmallSection (uint64_t Size) static
Definition at line 61 of file MipsTargetObjectFile.cpp.
References llvm::Check::Size, and SSThreshold.
Referenced by llvm::MipsTargetObjectFile::IsConstantInSmallSection().
Variable Documentation
EmbeddedData
cl::opt<bool> EmbeddedData("membedded-data", cl::Hidden, cl::desc("MIPS: Try to allocate variables in the following" " sections if possible: .rodata, .sdata, .data ."), cl::init(false)) ("membedded-data" , cl::Hidden , cl::desc("MIPS: Try to allocate variables in the following" " sections if possible: .rodata, .sdata, .data .") , cl::init(false)) static
ExternSData
cl::opt<bool> ExternSData("mextern-sdata", cl::Hidden, cl::desc("MIPS: Use gp_rel for data that is not defined by the " "current object."), cl::init(true)) ("mextern-sdata" , cl::Hidden , cl::desc("MIPS: Use gp_rel for data that is not defined by the " "current object.") , cl::init(true)) static
LocalSData
cl::opt<bool> LocalSData("mlocal-sdata", cl::Hidden, cl::desc("MIPS: Use gp_rel for object-local data."), cl::init(true)) ("mlocal-sdata" , cl::Hidden , cl::desc("MIPS: Use gp_rel for object-local data.") , cl::init(true)) static
Referenced by llvm::MipsTargetObjectFile::IsConstantInSmallSection().
SSThreshold
cl::opt<unsigned> SSThreshold("mips-ssection-threshold", cl::Hidden, cl::desc("Small data and bss section threshold size (default=8)"), cl::init(8)) ("mips-ssection-threshold" , cl::Hidden , cl::desc("Small data and bss section threshold size (default=8)") , cl::init(8)) static
Referenced by IsInSmallSection().