LLVM: llvm::GISelAddressing Namespace Reference
llvm::GISelAddressing Namespace Reference
Classes
struct BaseIndexOffset
Helper struct to store a base, index and offset that forms an address.
Functions
BaseIndexOffset getPointerInfo (Register Ptr, MachineRegisterInfo &MRI)
Returns a BaseIndexOffset which describes the pointer in Ptr.
bool aliasIsKnownForLoadStore (const MachineInstr &MI1, const MachineInstr &MI2, bool &IsAlias, MachineRegisterInfo &MRI)
Compute whether or not a memory access at MI1 aliases with an access at MI2.
bool instMayAlias (const MachineInstr &MI, const MachineInstr &Other, MachineRegisterInfo &MRI, AliasAnalysis *AA)
Returns true if the instruction MI may alias Other.
Function Documentation
aliasIsKnownForLoadStore()
bool llvm::GISelAddressing::aliasIsKnownForLoadStore (const MachineInstr & MI1, const MachineInstr & MI2, bool & IsAlias, MachineRegisterInfo & MRI)
Compute whether or not a memory access at MI1 aliases with an access at MI2.
Returns
true if either alias/no-alias is known. Sets IsAlias accordingly.
Definition at line 102 of file LoadStoreOpt.cpp.
References llvm::GISelAddressing::BaseIndexOffset::BaseReg, llvm::getDefIgnoringCopies(), getPointerInfo(), llvm::MachineFrameInfo::isFixedObjectIndex(), llvm::Register::isValid(), MRI, llvm::GISelAddressing::BaseIndexOffset::Offset, and llvm::MemoryLocation::UnknownSize.
Referenced by instMayAlias().
getPointerInfo()
BaseIndexOffset llvm::GISelAddressing::getPointerInfo (Register Ptr, MachineRegisterInfo & MRI)
Returns a BaseIndexOffset which describes the pointer in Ptr.
Definition at line 80 of file LoadStoreOpt.cpp.
References llvm::getIConstantVRegValWithLookThrough(), Info, llvm::MIPatternMatch::m_GPtrAdd(), llvm::MIPatternMatch::m_Reg(), llvm::MIPatternMatch::mi_match(), and MRI.
Referenced by AddNodeIDCustom(), and aliasIsKnownForLoadStore().
instMayAlias()
bool llvm::GISelAddressing::instMayAlias (const MachineInstr & MI, const MachineInstr & Other, MachineRegisterInfo & MRI, AliasAnalysis * AA)
Returns true if the instruction MI may alias Other.
This function uses multiple strategies to detect aliasing, whereas aliasIsKnownForLoadStore just looks at the addresses of load/stores and is tries to reason about base/index/offsets.
Definition at line 187 of file LoadStoreOpt.cpp.
References aliasIsKnownForLoadStore(), llvm::MemoryLocation::getSizeOrUnknown(), llvm::AAResults::isNoAlias(), llvm::AMDGPU::HSAMD::Kernel::Arg::Key::IsVolatile, llvm::AArch64CC::LS, llvm::MIPatternMatch::m_GPtrAdd(), llvm::MIPatternMatch::m_ICst(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), llvm::min(), MRI, Offset, Other, llvm::Check::Size, and llvm::MemoryLocation::UnknownSize.