LLVM: llvm::RISCVMatInt Namespace Reference
llvm::RISCVMatInt Namespace Reference
Classes
struct Inst
Typedefs
using InstSeq = SmallVector< Inst, 8 >
Functions
InstSeq generateInstSeq (int64_t Val, const FeatureBitset &ActiveFeatures)
int getIntMatCost (const APInt &Val, unsigned Size, const FeatureBitset &ActiveFeatures, bool CompressionCost)
Typedef Documentation
InstSeq
using llvm::RISCVMatInt::InstSeq = typedef SmallVector<Inst, 8>
Definition at line 26 of file RISCVMatInt.h.
Function Documentation
generateInstSeq()
InstSeq llvm::RISCVMatInt::generateInstSeq (int64_t Val, const FeatureBitset & ActiveFeatures)
Definition at line 165 of file RISCVMatInt.cpp.
References assert(), llvm::tgtok::Bit, llvm::SmallVectorImpl< T >::clear(), llvm::countLeadingZeros(), llvm::countPopulation(), llvm::countTrailingZeros(), extractRotateInfo(), generateInstSeqImpl(), llvm::MipsISD::Hi, llvm::isInt< 32 >(), llvm::MipsISD::Lo, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorBase< Size_T >::size().
Referenced by getIntMatCost(), llvm::RISCVInstrInfo::movImm(), and selectImm().
getIntMatCost()
int llvm::RISCVMatInt::getIntMatCost (const APInt & Val, unsigned Size, const FeatureBitset & ActiveFeatures, bool CompressionCost)
Definition at line 349 of file RISCVMatInt.cpp.
References llvm::APInt::ashr(), generateInstSeq(), getInstSeqCost(), llvm::APInt::getSExtValue(), llvm::max(), llvm::APInt::sextOrTrunc(), and llvm::Check::Size.
Referenced by llvm::RISCVTTIImpl::getIntImmCost(), and llvm::RISCVTargetLowering::isDesirableToCommuteWithShift().