LLVM: gen-regalloc-eviction-test-model Namespace Reference
gen-regalloc-eviction-test-model Namespace Reference
Functions
def get_input_signature ()
def get_output_spec_path (path)
def build_mock_model (path)
def main (argv)
Variables
string POLICY_DECISION_LABEL = 'index_to_evict'
string POLICY_OUTPUT_SPEC
list PER_REGISTER_INT64_FEATURE_LIST
list PER_REGISTER_FLOAT32_FEATURE_LIST
list PER_REGISTER_FEATURE_LIST = PER_REGISTER_FLOAT32_FEATURE_LIST + \
tuple CONTEXT_FEATURE_LIST = ('progress', 'discount', 'reward', 'step_type')
int NUM_REGISTERS = 33
Function Documentation
build_mock_model()
def gen-regalloc-eviction-test-model.build_mock_model (path)
Build and save the mock model with the given signature.
Definition at line 65 of file gen-regalloc-eviction-test-model.py.
References get_input_signature(), get_output_spec_path(), and print().
Referenced by main().
get_input_signature()
def gen-regalloc-eviction-test-model.get_input_signature ()
Returns (time_step_spec, action_spec) for LLVM register allocation.
Definition at line 41 of file gen-regalloc-eviction-test-model.py.
Referenced by build_mock_model().
get_output_spec_path()
def gen-regalloc-eviction-test-model.get_output_spec_path (path)
Definition at line 61 of file gen-regalloc-eviction-test-model.py.
Referenced by build_mock_model().
main()
def gen-regalloc-eviction-test-model.main (argv)
Definition at line 96 of file gen-regalloc-eviction-test-model.py.
References build_mock_model().
Variable Documentation
CONTEXT_FEATURE_LIST
tuple gen-regalloc-eviction-test-model.CONTEXT_FEATURE_LIST = ('progress', 'discount', 'reward', 'step_type')
Definition at line 37 of file gen-regalloc-eviction-test-model.py.
NUM_REGISTERS
int gen-regalloc-eviction-test-model.NUM_REGISTERS = 33
Definition at line 38 of file gen-regalloc-eviction-test-model.py.
PER_REGISTER_FEATURE_LIST
list gen-regalloc-eviction-test-model.PER_REGISTER_FEATURE_LIST = PER_REGISTER_FLOAT32_FEATURE_LIST + \
Definition at line 35 of file gen-regalloc-eviction-test-model.py.
PER_REGISTER_FLOAT32_FEATURE_LIST
list gen-regalloc-eviction-test-model.PER_REGISTER_FLOAT32_FEATURE_LIST
Initial value:
 =  ['nr_urgent',
     'weighed_reads_by_max', 'weighed_writes_by_max',
     'weighed_read_writes_by_max', 'weighed_indvars_by_max',
     'hint_weights_by_max', 'start_bb_freq_by_max', 'end_bb_freq_by_max',
     'hottest_bb_freq_by_max', 'liverange_size', 'use_def_density',
     'nr_defs_and_uses', 'nr_broken_hints', 'nr_rematerializable'
 ]
Definition at line 28 of file gen-regalloc-eviction-test-model.py.
PER_REGISTER_INT64_FEATURE_LIST
list gen-regalloc-eviction-test-model.PER_REGISTER_INT64_FEATURE_LIST
Initial value:
 =  [
     'mask', 'is_hint', 'is_local', 'is_free', 'max_stage', 'min_stage'
 ]
Definition at line 25 of file gen-regalloc-eviction-test-model.py.
POLICY_DECISION_LABEL
string gen-regalloc-eviction-test-model.POLICY_DECISION_LABEL = 'index_to_evict'
Definition at line 9 of file gen-regalloc-eviction-test-model.py.
POLICY_OUTPUT_SPEC
string gen-regalloc-eviction-test-model.POLICY_OUTPUT_SPEC
Initial value:
 =  """
 [
     {
         "logging_name": "index_to_evict",
         "tensor_spec": {
             "name": "StatefulPartitionedCall",
             "port": 0,
             "type": "int64_t",
             "shape": [
                 1
             ]
         }
     }
 ]
 """
Definition at line 10 of file gen-regalloc-eviction-test-model.py.