LLVM: llvm::IndexedInstrProf Namespace Reference
llvm::IndexedInstrProf Namespace Reference
Classes
struct Header
struct Summary
Enumerations
enum class HashT : uint32_t { MD5 , Last = MD5 }
enum ProfVersion {
Version1 = 1 , Version2 = 2 , Version3 = 3 , Version4 = 4 ,
Version5 = 5 , Version6 = 6 , Version7 = 7 , CurrentVersion = INSTR_PROF_INDEX_VERSION
}
Functions
uint64_t ComputeHash (StringRef K)
uint64_t ComputeHash (HashT Type, StringRef K)
std::unique_ptr< Summary > allocSummary (uint32_t TotalSize)
Variables
const uint64_t Magic = 0x8169666f72706cff
const uint64_t Version = ProfVersion::CurrentVersion
const HashT HashType = HashT::MD5
Enumeration Type Documentation
HashT
enum llvm::IndexedInstrProf::HashT : uint32_t strong
Enumerator
MD5
Last
Definition at line 975 of file InstrProf.h.
ProfVersion
enum llvm::IndexedInstrProf::ProfVersion
Enumerator
Version1
Version2
Version3
Version4
Version5
Version6
Version7
CurrentVersion
Definition at line 990 of file InstrProf.h.
Function Documentation
allocSummary()
std::unique_ptr<Summary> llvm::IndexedInstrProf::allocSummary (uint32_t TotalSize) inline
Definition at line 1114 of file InstrProf.h.
ComputeHash() [1/2]
uint64_t llvm::IndexedInstrProf::ComputeHash (HashT Type, StringRef K) inline
Definition at line 980 of file InstrProf.h.
References llvm_unreachable, MD5, and llvm::MD5Hash().
ComputeHash() [2/2]
uint64_t llvm::IndexedInstrProf::ComputeHash (StringRef K) inline
Definition at line 1021 of file InstrProf.h.
References HashType.
Referenced by llvm::InstrProfSymtab::addFuncName(), llvm::InstrProfCorrelatorImpl< IntPtrT >::addProbe(), llvm::InstrProfRecordWriterTrait::ComputeHash(), and llvm::InstrProfLookupTrait::ComputeHash().
Variable Documentation
HashType
const HashT llvm::IndexedInstrProf::HashType = HashT::MD5
Definition at line 1019 of file InstrProf.h.
Referenced by ComputeHash().
Magic
const uint64_t llvm::IndexedInstrProf::Magic = 0x8169666f72706cff
Definition at line 988 of file InstrProf.h.
Referenced by llvm::IndexedInstrProfReader::hasFormat().
Version
const uint64_t llvm::IndexedInstrProf::Version = ProfVersion::CurrentVersion
Definition at line 1017 of file InstrProf.h.