LLVM: llvm::AA Namespace Reference
llvm::AA Namespace Reference
Abstract Attribute helper functions.
Namespaces
PointerInfo
Functions
bool isNoSyncInst (Attributor &A, const Instruction &I, const AbstractAttribute &QueryingAA)
Return true if I is a nosync instruction.
bool isDynamicallyUnique (Attributor &A, const AbstractAttribute &QueryingAA, const Value &V)
Return true if V is dynamically unique, that is, there are no two "instances" of V at runtime with different values.
bool isValidInScope (const Value &V, const Function *Scope)
Return true if V is a valid value in Scope, that is a constant or an instruction/argument of Scope.
bool isValidAtPosition (const Value &V, const Instruction &CtxI, InformationCache &InfoCache)
Return true if V is a valid value at position CtxI, that is a constant, an argument of the same function as CtxI, or an instruction in that function that dominates CtxI.
Value * getWithType (Value &V, Type &Ty)
Try to convert V to type Ty without introducing new instructions.
Optional< Value * > combineOptionalValuesInAAValueLatice (const Optional< Value * > &A, const Optional< Value * > &B, Type *Ty)
Return the combination of A and B such that the result is a possible value of both.
Constant * getInitialValueForObj (Value &Obj, Type &Ty, const TargetLibraryInfo *TLI)
Return the initial value of Obj with type Ty if that is a constant.
bool getAssumedUnderlyingObjects (Attributor &A, const Value &Ptr, SmallVectorImpl< Value * > &Objects, const AbstractAttribute &QueryingAA, const Instruction *CtxI, bool &UsedAssumedInformation, bool Intraprocedural=false)
Collect all potential underlying objects of Ptr at position CtxI in Objects.
bool getPotentialCopiesOfStoredValue (Attributor &A, StoreInst &SI, SmallSetVector< Value *, 4 > &PotentialCopies, const AbstractAttribute &QueryingAA, bool &UsedAssumedInformation)
Collect all potential values of the one stored by SI into PotentialCopies.
bool isAssumedReadOnly (Attributor &A, const IRPosition &IRP, const AbstractAttribute &QueryingAA, bool &IsKnown)
Return true if IRP is readonly.
bool isAssumedReadNone (Attributor &A, const IRPosition &IRP, const AbstractAttribute &QueryingAA, bool &IsKnown)
Return true if IRP is readnone.
bool isPotentiallyReachable (Attributor &A, const Instruction &FromI, const Instruction &ToI, const AbstractAttribute &QueryingAA, std::function< bool(const Function &F)> GoBackwardsCB=nullptr)
Return true if ToI is potentially reachable from FromI.
bool isPotentiallyReachable (Attributor &A, const Instruction &FromI, const Function &ToFn, const AbstractAttribute &QueryingAA, std::function< bool(const Function &F)> GoBackwardsCB)
Same as above but it is sufficient to reach any instruction in ToFn.
Detailed Description
Abstract Attribute helper functions.
Function Documentation
combineOptionalValuesInAAValueLatice()
Optional< Value * > llvm::AA::combineOptionalValuesInAAValueLatice (const Optional< Value * > & A, const Optional< Value * > & B, Type * Ty)
Return the combination of A and B such that the result is a possible value of both.
B is potentially casted to match the type Ty or the type of A if Ty is null.
Examples: X + none => X not_none + undef => not_none V1 + V2 => nullptr
Definition at line 294 of file Attributor.cpp.
References B, and getWithType().
Referenced by AAReturnedValuesImpl::getAssumedUniqueReturnValue(), AAValueSimplifyFloating::handleCmp(), AAValueSimplifyFloating::handleGenericInst(), llvm::AAPointerInfo::Access::operator&=(), llvm::ValueSimplifyStateType::unionAssumed(), AAValueSimplifyCallSiteReturned::updateImpl(), and AAValueSimplifyFloating::updateWithLoad().
getAssumedUnderlyingObjects()
bool llvm::AA::getAssumedUnderlyingObjects (Attributor & A, const Value & Ptr, SmallVectorImpl< Value * > & Objects, const AbstractAttribute & QueryingAA, const Instruction * CtxI, bool & UsedAssumedInformation, bool Intraprocedural = false)
Collect all potential underlying objects of Ptr at position CtxI in Objects.
Assumed information is used and dependences onto QueryingAA are added appropriately.
Returns
True if Objects contains all assumed underlying objects, and false if something went wrong and the objects could not be determined.
Definition at line 418 of file AttributorAttributes.cpp.
References A, genericValueTraversal(), llvm::getUnderlyingObject(), llvm::SmallPtrSetImpl< PtrType >::insert(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by AAMemoryLocationImpl::categorizePtrValue(), getPotentialCopiesOfStoredValue(), AAValueSimplifyImpl::handleLoad(), and AAHeapToStackFunction::updateImpl().
getInitialValueForObj()
Constant * llvm::AA::getInitialValueForObj (Value & Obj, Type & Ty, const TargetLibraryInfo * TLI)
Return the initial value of Obj with type Ty if that is a constant.
Definition at line 231 of file Attributor.cpp.
References llvm::UndefValue::get(), llvm::getInitialValueOfAllocation(), getWithType(), and llvm::isAllocationFn().
Referenced by AAValueSimplifyImpl::handleLoad().
getPotentialCopiesOfStoredValue()
bool llvm::AA::getPotentialCopiesOfStoredValue (Attributor & A, StoreInst & SI, SmallSetVector< Value *, 4 > & PotentialCopies, const AbstractAttribute & QueryingAA, bool & UsedAssumedInformation)
Collect all potential values of the one stored by SI into PotentialCopies.
That is, the only copies that were made via the store are assumed to be known and all in PotentialCopies. Dependences onto QueryingAA are properly tracked, UsedAssumedInformation will inform the caller if assumed information was used.
Returns
True if the assumed potential copies are all in PotentialCopies, false if something went wrong and the copies could not be determined.
Definition at line 317 of file Attributor.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::dbgs(), llvm::SmallVectorTemplateCommon< T, typename >::end(), getAssumedUnderlyingObjects(), llvm::Type::getPointerAddressSpace(), llvm::AAPointerInfo::Access::getRemoteInst(), llvm::Value::getType(), llvm::SetVector< T, Vector, Set >::insert(), llvm::isNoAliasCall(), llvm::AAPointerInfo::Access::isRead(), LLVM_DEBUG, llvm::NONE, llvm::NullPointerIsDefined(), llvm::OPTIONAL, llvm::SmallVectorTemplateBase< T, bool >::push_back(), SI, and llvm::IRPosition::value().
Referenced by AACaptureUseTracker::captured(), llvm::Attributor::checkForAllUses(), and AAIsDeadFloating::isDeadStore().
getWithType()
Value * llvm::AA::getWithType (Value & V, Type & Ty)
Try to convert V to type Ty without introducing new instructions.
If this is not possible return nullptr. Note: this function basically knows how to cast various constants.
Definition at line 271 of file Attributor.cpp.
References C, llvm::UndefValue::get(), llvm::PoisonValue::get(), llvm::ConstantExpr::getFPTrunc(), llvm::Constant::getNullValue(), llvm::ConstantExpr::getPointerCast(), llvm::Type::getPrimitiveSizeInBits(), llvm::ConstantExpr::getTrunc(), llvm::Value::getType(), llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), and llvm::Type::isPointerTy().
Referenced by combineOptionalValuesInAAValueLatice(), llvm::Attributor::getAssumedConstant(), llvm::Attributor::getAssumedSimplified(), getInitialValueForObj(), AAValueSimplifyImpl::getReplacementValue(), and AAValueSimplifyImpl::handleLoad().
isAssumedReadNone()
bool llvm::AA::isAssumedReadNone (Attributor & A, const IRPosition & IRP, const AbstractAttribute & QueryingAA, bool & IsKnown)
Return true if IRP is readnone.
This will query respective AAs that deduce the information and introduce dependences for QueryingAA.
Definition at line 434 of file Attributor.cpp.
References isAssumedReadOnlyOrReadNone().
Referenced by AAMemoryBehaviorImpl::getAsStr(), AAMemoryBehaviorImpl::getDeducedAttributes(), AAMemoryLocationImpl::getDeducedAttributes(), AAMemoryBehaviorFunction::manifest(), AAMemoryLocationImpl::manifest(), AAMemoryBehaviorFloating::trackStatistics(), AAMemoryBehaviorArgument::trackStatistics(), AAMemoryBehaviorCallSiteArgument::trackStatistics(), AAMemoryBehaviorFunction::trackStatistics(), AAMemoryBehaviorCallSite::trackStatistics(), AAMemoryLocationFunction::trackStatistics(), AAMemoryLocationCallSite::trackStatistics(), and AAMemoryLocationFunction::updateImpl().
isAssumedReadOnly()
bool llvm::AA::isAssumedReadOnly (Attributor & A, const IRPosition & IRP, const AbstractAttribute & QueryingAA, bool & IsKnown)
Return true if IRP is readonly.
This will query respective AAs that deduce the information and introduce dependences for QueryingAA.
Definition at line 429 of file Attributor.cpp.
References isAssumedReadOnlyOrReadNone().
Referenced by AAMemoryBehaviorImpl::getAsStr(), AAMemoryBehaviorImpl::getDeducedAttributes(), AAIsDeadValueImpl::isAssumedSideEffectFree(), AAWillReturnImpl::isImpliedByMustprogressAndReadonly(), AAMemoryBehaviorFloating::trackStatistics(), AAMemoryBehaviorArgument::trackStatistics(), AAMemoryBehaviorCallSiteArgument::trackStatistics(), AAMemoryBehaviorFunction::trackStatistics(), AAMemoryBehaviorCallSite::trackStatistics(), AANoAliasArgument::updateImpl(), AANoCaptureImpl::updateImpl(), AAValueSimplifyArgument::updateImpl(), and AAPrivatizablePtrCallSiteArgument::updateImpl().
isDynamicallyUnique()
bool llvm::AA::isDynamicallyUnique (Attributor & A, const AbstractAttribute & QueryingAA, const Value & V)
Return true if V is dynamically unique, that is, there are no two "instances" of V at runtime with different values.
Definition at line 211 of file Attributor.cpp.
References C, llvm::IRPosition::function(), I, llvm::AANoRecurse::isAssumedNoRecurse(), and llvm::OPTIONAL.
Referenced by AAValueSimplifyImpl::handleLoad(), and AAValueSimplifyArgument::updateImpl().
isNoSyncInst()
bool llvm::AA::isNoSyncInst (Attributor & A, const Instruction & I, const AbstractAttribute & QueryingAA)
Return true if I is a nosync instruction.
}
Use generic reasoning and potentially the corresponding AANoSync.
Definition at line 186 of file Attributor.cpp.
References llvm::IRPosition::callsite_function(), I, llvm::AANoSync::isAssumedNoSync(), llvm::AANoSync::isNonRelaxedAtomic(), llvm::AANoSync::isNoSyncIntrinsic(), and llvm::OPTIONAL.
Referenced by AANoSyncImpl::updateImpl().
isPotentiallyReachable() [1/2]
bool llvm::AA::isPotentiallyReachable (Attributor & A, const Instruction & FromI, const Function & ToFn, const AbstractAttribute & QueryingAA, std::function< bool(const Function &F)> GoBackwardsCB)
Same as above but it is sufficient to reach any instruction in ToFn.
Definition at line 547 of file Attributor.cpp.
References isPotentiallyReachable().
isPotentiallyReachable() [2/2]
bool llvm::AA::isPotentiallyReachable (Attributor & A, const Instruction & FromI, const Instruction & ToI, const AbstractAttribute & QueryingAA, std::function< bool(const Function &F)> GoBackwardsCB = nullptr)
Return true if ToI is potentially reachable from FromI.
The two instructions do not need to be in the same function. GoBackwardsCB can be provided to convey domain knowledge about the "lifespan" the user is interested in. By default, the callers of FromI are checked as well to determine if ToI can be reached. If the query is not interested in callers beyond a certain point, e.g., a GPU kernel entry or the function containing an alloca, the GoBackwardsCB should return false.
Definition at line 536 of file Attributor.cpp.
References llvm::dbgs(), llvm::Instruction::getFunction(), isPotentiallyReachable(), and LLVM_DEBUG.
Referenced by AAPointerInfoImpl::forallInterferingWrites(), and AAFunctionReachabilityFunction::instructionCanReach().
isValidAtPosition()
bool llvm::AA::isValidAtPosition (const Value & V, const Instruction & CtxI, InformationCache & InfoCache)
Return true if V is a valid value at position CtxI, that is a constant, an argument of the same function as CtxI, or an instruction in that function that dominates CtxI.
Definition at line 255 of file Attributor.cpp.
References llvm::DominatorTree::dominates(), llvm::InformationCache::getAnalysisResultForFunction(), llvm::Instruction::getFunction(), and I.
Referenced by AAValueSimplifyImpl::getReplacementValue(), and AAValueSimplifyImpl::handleLoad().
isValidInScope()
bool llvm::AA::isValidInScope (const Value & V, const Function * Scope)
Return true if V is a valid value in Scope, that is a constant or an instruction/argument of Scope.
Definition at line 245 of file Attributor.cpp.
References I.
Referenced by genericValueTraversal(), AAValueSimplifyImpl::getReplacementValue(), AAValueConstantRangeImpl::isValidCtxInstructionForOutsideAnalysis(), and AAReturnedValuesImpl::updateImpl().