LLVM: llvm::RISCV Namespace Reference
llvm::RISCV Namespace Reference
Classes
struct CPUInfo
struct VLSEGPseudo
struct VLXSEGPseudo
struct VSSEGPseudo
struct VSXSEGPseudo
struct VLEPseudo
struct VSEPseudo
struct VLX_VSXPseudo
Enumerations
enum CPUKind : unsigned
enum FeatureKind : unsigned { FK_INVALID = 0 , FK_NONE = 1 , FK_64BIT = 1 << 2 }
enum Fixups {
fixup_riscv_hi20 = FirstTargetFixupKind , fixup_riscv_lo12_i , fixup_riscv_lo12_s , fixup_riscv_pcrel_hi20 ,
fixup_riscv_pcrel_lo12_i , fixup_riscv_pcrel_lo12_s , fixup_riscv_got_hi20 , fixup_riscv_tprel_hi20 ,
fixup_riscv_tprel_lo12_i , fixup_riscv_tprel_lo12_s , fixup_riscv_tprel_add , fixup_riscv_tls_got_hi20 ,
fixup_riscv_tls_gd_hi20 , fixup_riscv_jal , fixup_riscv_branch , fixup_riscv_rvc_jump ,
fixup_riscv_rvc_branch , fixup_riscv_call , fixup_riscv_call_plt , fixup_riscv_relax ,
fixup_riscv_align , fixup_riscv_set_8 , fixup_riscv_add_8 , fixup_riscv_sub_8 ,
fixup_riscv_set_16 , fixup_riscv_add_16 , fixup_riscv_sub_16 , fixup_riscv_set_32 ,
fixup_riscv_add_32 , fixup_riscv_sub_32 , fixup_riscv_add_64 , fixup_riscv_sub_64 ,
fixup_riscv_set_6b , fixup_riscv_sub_6b , fixup_riscv_invalid , NumTargetFixupKinds = fixup_riscv_invalid - FirstTargetFixupKind
}
Functions
bool checkCPUKind (CPUKind Kind, bool IsRV64)
bool checkTuneCPUKind (CPUKind Kind, bool IsRV64)
CPUKind parseCPUKind (StringRef CPU)
CPUKind parseTuneCPUKind (StringRef CPU, bool IsRV64)
StringRef getMArchFromMcpu (StringRef CPU)
void fillValidCPUArchList (SmallVectorImpl< StringRef > &Values, bool IsRV64)
void fillValidTuneCPUArchList (SmallVectorImpl< StringRef > &Values, bool IsRV64)
bool getCPUFeaturesExceptStdExt (CPUKind Kind, std::vector< StringRef > &Features)
StringRef resolveTuneCPUAlias (StringRef TuneCPU, bool IsRV64)
StringRef computeDefaultABIFromArch (const llvm::RISCVISAInfo &ISAInfo)
int16_t getNamedOperandIdx (uint16_t Opcode, uint16_t NamedIndex)
Variables
constexpr CPUInfo RISCVCPUInfo []
static constexpr int64_t VLMaxSentinel = -1LL
static constexpr unsigned RVVBitsPerBlock = 64
Enumeration Type Documentation
CPUKind
enum llvm::RISCV::CPUKind : unsigned
Definition at line 153 of file TargetParser.h.
FeatureKind
enum llvm::RISCV::FeatureKind : unsigned
Enumerator
FK_INVALID
FK_NONE
FK_64BIT
Definition at line 158 of file TargetParser.h.
Fixups
enum llvm::RISCV::Fixups
Enumerator
fixup_riscv_hi20
fixup_riscv_lo12_i
fixup_riscv_lo12_s
fixup_riscv_pcrel_hi20
fixup_riscv_pcrel_lo12_i
fixup_riscv_pcrel_lo12_s
fixup_riscv_got_hi20
fixup_riscv_tprel_hi20
fixup_riscv_tprel_lo12_i
fixup_riscv_tprel_lo12_s
fixup_riscv_tprel_add
fixup_riscv_tls_got_hi20
fixup_riscv_tls_gd_hi20
fixup_riscv_jal
fixup_riscv_branch
fixup_riscv_rvc_jump
fixup_riscv_rvc_branch
fixup_riscv_call
fixup_riscv_call_plt
fixup_riscv_relax
fixup_riscv_align
fixup_riscv_set_8
fixup_riscv_add_8
fixup_riscv_sub_8
fixup_riscv_set_16
fixup_riscv_add_16
fixup_riscv_sub_16
fixup_riscv_set_32
fixup_riscv_add_32
fixup_riscv_sub_32
fixup_riscv_add_64
fixup_riscv_sub_64
fixup_riscv_set_6b
fixup_riscv_sub_6b
fixup_riscv_invalid
NumTargetFixupKinds
Definition at line 18 of file RISCVFixupKinds.h.
Function Documentation
checkCPUKind()
bool llvm::RISCV::checkCPUKind (CPUKind Kind, bool IsRV64)
Definition at line 260 of file TargetParser.cpp.
References is64Bit(), and RISCVCPUInfo.
checkTuneCPUKind()
bool llvm::RISCV::checkTuneCPUKind (CPUKind Kind, bool IsRV64)
Definition at line 266 of file TargetParser.cpp.
References is64Bit(), and RISCVCPUInfo.
computeDefaultABIFromArch()
StringRef llvm::RISCV::computeDefaultABIFromArch (const llvm::RISCVISAInfo & ISAInfo)
Definition at line 332 of file TargetParser.cpp.
References llvm::RISCVISAInfo::getXLen(), llvm::RISCVISAInfo::hasExtension(), and llvm_unreachable.
fillValidCPUArchList()
void llvm::RISCV::fillValidCPUArchList (SmallVectorImpl< StringRef > & Values, bool IsRV64)
Definition at line 300 of file TargetParser.cpp.
References C, llvm::SmallVectorImpl< T >::emplace_back(), and RISCVCPUInfo.
fillValidTuneCPUArchList()
void llvm::RISCV::fillValidTuneCPUArchList (SmallVectorImpl< StringRef > & Values, bool IsRV64)
Definition at line 307 of file TargetParser.cpp.
References C, llvm::SmallVectorImpl< T >::emplace_back(), and RISCVCPUInfo.
getCPUFeaturesExceptStdExt()
bool llvm::RISCV::getCPUFeaturesExceptStdExt (CPUKind Kind, std::vector< StringRef > & Features)
Definition at line 317 of file TargetParser.cpp.
References FK_64BIT, FK_INVALID, and RISCVCPUInfo.
getMArchFromMcpu()
StringRef llvm::RISCV::getMArchFromMcpu (StringRef CPU)
Definition at line 295 of file TargetParser.cpp.
References parseCPUKind(), and RISCVCPUInfo.
getNamedOperandIdx()
int16_t llvm::RISCV::getNamedOperandIdx (uint16_t Opcode, uint16_t NamedIndex)
parseCPUKind()
CPUKind llvm::RISCV::parseCPUKind (StringRef CPU)
Definition at line 272 of file TargetParser.cpp.
References llvm::StringSwitch< T, R >::Default().
Referenced by getMArchFromMcpu().
parseTuneCPUKind()
CPUKind llvm::RISCV::parseTuneCPUKind (StringRef CPU, bool IsRV64)
Definition at line 286 of file TargetParser.cpp.
References llvm::StringSwitch< T, R >::Default(), and resolveTuneCPUAlias().
resolveTuneCPUAlias()
StringRef llvm::RISCV::resolveTuneCPUAlias (StringRef TuneCPU, bool IsRV64)
Definition at line 279 of file TargetParser.cpp.
References llvm::StringSwitch< T, R >::Default().
Referenced by parseTuneCPUKind().
Variable Documentation
RISCVCPUInfo
constexpr CPUInfo llvm::RISCV::RISCVCPUInfo[] constexpr
Initial value:
= {
#define PROC(ENUM, NAME, FEATURES, DEFAULT_MARCH)
}
Definition at line 254 of file TargetParser.cpp.
Referenced by checkCPUKind(), checkTuneCPUKind(), fillValidCPUArchList(), fillValidTuneCPUArchList(), getCPUFeaturesExceptStdExt(), and getMArchFromMcpu().
RVVBitsPerBlock
constexpr unsigned llvm::RISCV::RVVBitsPerBlock = 64 static constexpr
Definition at line 671 of file RISCVISelLowering.h.
Referenced by getContainerForFixedLengthVector(), getLMUL1VT(), llvm::RISCVTTIImpl::getMaxVScale(), llvm::RISCVTTIImpl::getRegisterBitWidth(), llvm::RISCVTTIImpl::getRegUsageForType(), and llvm::RISCVTargetLowering::LowerOperation().
VLMaxSentinel
constexpr int64_t llvm::RISCV::VLMaxSentinel = -1LL static constexpr
Definition at line 190 of file RISCVInstrInfo.h.
Referenced by getDefaultVLOps(), llvm::RISCVDAGToDAGISel::selectVLOp(), and splatPartsI64WithVL().