LLVM: lib/Passes/PassBuilderBindings.cpp File Reference
PassBuilderBindings.cpp File Reference
This file defines the C bindings to the new pass manager.
#include "llvm-c/Transforms/PassBuilder.h"
#include "llvm/IR/Verifier.h"
#include "llvm/Passes/PassBuilder.h"
#include "llvm/Passes/StandardInstrumentations.h"
#include "llvm/Support/CBindingWrapping.h"
Classes
class llvm::LLVMPassBuilderOptions
Helper struct for holding a set of builder options for LLVMRunPasses.
Namespaces
llvm
/file This file defines the SmallVector class.
Functions
static TargetMachine * unwrap (LLVMTargetMachineRef P)
DEFINE_SIMPLE_CONVERSION_FUNCTIONS (LLVMPassBuilderOptions, LLVMPassBuilderOptionsRef) LLVMErrorRef LLVMRunPasses(LLVMModuleRef M
PassBuilder PB (Machine, PassOpts->PTO, None, &PIC)
PB registerLoopAnalyses (LAM)
PB registerFunctionAnalyses (FAM)
PB registerCGSCCAnalyses (CGAM)
PB registerModuleAnalyses (MAM)
PB crossRegisterProxies (LAM, FAM, CGAM, MAM)
SI registerCallbacks (PIC, &FAM)
if (VerifyEach)
if (auto Err=PB.parsePassPipeline(MPM, Passes))
LLVMPassBuilderOptionsRef LLVMCreatePassBuilderOptions ()
Create a new set of options for a PassBuilder.
void LLVMPassBuilderOptionsSetVerifyEach (LLVMPassBuilderOptionsRef Options, LLVMBool VerifyEach)
Toggle adding the VerifierPass for the PassBuilder, ensuring all functions inside the module is valid.
void LLVMPassBuilderOptionsSetDebugLogging (LLVMPassBuilderOptionsRef Options, LLVMBool DebugLogging)
Toggle debug logging when running the PassBuilder.
void LLVMPassBuilderOptionsSetLoopInterleaving (LLVMPassBuilderOptionsRef Options, LLVMBool LoopInterleaving)
void LLVMPassBuilderOptionsSetLoopVectorization (LLVMPassBuilderOptionsRef Options, LLVMBool LoopVectorization)
void LLVMPassBuilderOptionsSetSLPVectorization (LLVMPassBuilderOptionsRef Options, LLVMBool SLPVectorization)
void LLVMPassBuilderOptionsSetLoopUnrolling (LLVMPassBuilderOptionsRef Options, LLVMBool LoopUnrolling)
void LLVMPassBuilderOptionsSetForgetAllSCEVInLoopUnroll (LLVMPassBuilderOptionsRef Options, LLVMBool ForgetAllSCEVInLoopUnroll)
void LLVMPassBuilderOptionsSetLicmMssaOptCap (LLVMPassBuilderOptionsRef Options, unsigned LicmMssaOptCap)
void LLVMPassBuilderOptionsSetLicmMssaNoAccForPromotionCap (LLVMPassBuilderOptionsRef Options, unsigned LicmMssaNoAccForPromotionCap)
void LLVMPassBuilderOptionsSetCallGraphProfile (LLVMPassBuilderOptionsRef Options, LLVMBool CallGraphProfile)
void LLVMPassBuilderOptionsSetMergeFunctions (LLVMPassBuilderOptionsRef Options, LLVMBool MergeFunctions)
void LLVMDisposePassBuilderOptions (LLVMPassBuilderOptionsRef Options)
Dispose of a heap-allocated PassBuilderOptions instance.
Variables
const char * Passes
const char LLVMTargetMachineRef TM
const char LLVMTargetMachineRef LLVMPassBuilderOptionsRef Options
LLVMPassBuilderOptions * PassOpts = unwrap(Options)
bool Debug = PassOpts->DebugLogging
bool VerifyEach = PassOpts->VerifyEach
Module * Mod = unwrap(M)
PassInstrumentationCallbacks PIC
LoopAnalysisManager LAM
FunctionAnalysisManager FAM
CGSCCAnalysisManager CGAM
ModuleAnalysisManager MAM
StandardInstrumentations SI (Debug, VerifyEach)
ModulePassManager MPM
return LLVMErrorSuccess
Detailed Description
This file defines the C bindings to the new pass manager.
Definition in file PassBuilderBindings.cpp.
Function Documentation
crossRegisterProxies()
PB crossRegisterProxies (LAM , FAM , CGAM , MAM)
DEFINE_SIMPLE_CONVERSION_FUNCTIONS()
DEFINE_SIMPLE_CONVERSION_FUNCTIONS (LLVMPassBuilderOptions , LLVMPassBuilderOptionsRef)
if() [1/2]
if (auto Err = PB.parsePassPipeline(MPM, Passes))
Definition at line 74 of file PassBuilderBindings.cpp.
if() [2/2]
if (VerifyEach)
Definition at line 71 of file PassBuilderBindings.cpp.
References llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass(), and MPM.
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), allocset(), llvm::SwitchCG::SwitchLowering::buildBitTests(), canLowerToLDG(), llvm::GenericScheduler::checkAcyclicLatency(), llvm::pdb::DbiStreamBuilder::commit(), llvm::IRSimilarity::IRSimilarityCandidate::compareNonCommutativeOperandMapping(), computePointerICmp(), llvm::DWARFLocationTable::dumpLocationList(), llvm::AsmPrinter::emitFunctionBody(), llvm::MCDwarfLineAddr::Encode(), llvm::SystemZPostRASchedStrategy::enterMBB(), llvm::gsym::GsymCreator::finalize(), llvm::InstCombinerImpl::foldIntegerTypedPHI(), llvm::gatherUnrollingPreferences(), llvm::DWARFFormValue::getAsSectionedAddress(), llvm::Clause::getFormattedParserClassName(), llvm::PPCTTIImpl::getMemoryOpCost(), llvm::InformationCache::initializeModuleSlice(), isDereferenceableAndAlignedPointer(), llvm::isSafeToMoveBefore(), llvm::isSafeToUnrollAndJam(), lowerV4I32Shuffle(), llvm::AMDGPUSubtarget::makeLIDRangeMetadata(), llvm::MipsLegalizerInfo::MipsLegalizerInfo(), llvm::AArch64FrameLowering::orderFrameObjects(), llvm::performOptimizedStructLayout(), llvm::CallGraph::print(), llvm::json::Path::Root::printErrorContext(), llvm::printRegClassOrBank(), registerPartialPipelineCallback(), llvm::slpvectorizer::BoUpSLP::reorderBottomToTop(), llvm::slpvectorizer::BoUpSLP::reorderTopToBottom(), llvm::SystemZPostRASchedStrategy::schedNode(), selectCallee(), llvm::LoopVectorizationCostModel::selectVectorizationFactor(), llvm::GenericSchedulerBase::setPolicy(), simplifyAMDGCNImageIntrinsic(), sortGlobalExprs(), translateImmediate(), llvm::mca::RegisterFile::tryEliminateMoveOrSwap(), llvm::DWARFLocationTable::visitAbsoluteLocationList(), and llvm::coverage::CoverageMappingWriter::write().
PB()
PassBuilder PB (Machine , PassOpts-> PTO, None , & PIC)
Referenced by llvm::rdf::DataFlowGraph::build(), llvm::PredicateBase::classof(), llvm::PredicateAssume::classof(), llvm::PredicateWithEdge::classof(), llvm::PredicateBranch::classof(), llvm::PredicateSwitch::classof(), llvm::PredicateInfoAnnotatedWriter::emitInstructionAnnot(), llvm::HexagonInstrInfo::findLoopInstr(), llvm::MachineLoopInfo::findLoopPreheader(), GetSymbolRef(), INITIALIZE_PASS(), llvm::orc::BlockFreqQuery::operator()(), llvm::PassPlugin::registerPassBuilderCallbacks(), llvm::AMDGPUTargetMachine::registerPassBuilderCallbacks(), llvm::BPFTargetMachine::registerPassBuilderCallbacks(), llvm::HexagonTargetMachine::registerPassBuilderCallbacks(), llvm::NVPTXTargetMachine::registerPassBuilderCallbacks(), RegisterPassPlugins(), runNewPMPasses(), SimplifyCondBranchToCondBranch(), and llvm::JumpThreadingPass::simplifyPartiallyRedundantLoad().
registerCallbacks()
SI registerCallbacks (PIC , & FAM)
registerCGSCCAnalyses()
PB registerCGSCCAnalyses (CGAM)
registerFunctionAnalyses()
PB registerFunctionAnalyses (FAM)
registerLoopAnalyses()
PB registerLoopAnalyses (LAM)
registerModuleAnalyses()
PB registerModuleAnalyses (MAM)
unwrap()
static TargetMachine* unwrap (LLVMTargetMachineRef P) static
Definition at line 39 of file PassBuilderBindings.cpp.
References P.
Variable Documentation
CGAM
CGSCCAnalysisManager CGAM
Definition at line 60 of file PassBuilderBindings.cpp.
Referenced by llvm::PassBuilder::crossRegisterProxies(), llvm::PassBuilder::registerCGSCCAnalyses(), llvm::ModuleToPostOrderCGSCCPassAdaptor::run(), and runNewPMPasses().
Debug
bool Debug = PassOpts->DebugLogging
Definition at line 51 of file PassBuilderBindings.cpp.
Referenced by llvm::MCObjectStreamer::emitCFISections(), and llvm::LTOCodeGenerator::setDebugInfo().
FAM
FunctionAnalysisManager FAM
Definition at line 59 of file PassBuilderBindings.cpp.
Referenced by llvm::AnalysisGetter::AnalysisGetter(), llvm::OpenMPIRBuilder::applySimd(), computeHeuristicUnrollFactor(), llvm::PassBuilder::crossRegisterProxies(), eliminateDeadCode(), llvm::CallGraphUpdater::finalize(), llvm::MachineFunctionAnalysisManager::getCachedResult(), getDefaultInlineAdvice(), llvm::getReplayInlineAdvisor(), llvm::MachineFunctionAnalysisManager::getResult(), incorporateNewSCCRange(), llvm::CallGraphUpdater::initialize(), llvm::FunctionAnalysisManagerCGSCCProxy::Result::invalidate(), llvm::orc::BlockFreqQuery::operator()(), promoteIndirectCalls(), llvm::PreservedCFGCheckerInstrumentation::registerCallbacks(), llvm::StandardInstrumentations::registerCallbacks(), llvm::CodeGenPassBuilder< DerivedT >::registerFunctionAnalyses(), llvm::PassBuilder::registerFunctionAnalyses(), llvm::AMDGPUTargetMachine::registerPassBuilderCallbacks(), llvm::FunctionAnalysisManagerCGSCCProxy::Result::Result(), llvm::AssumptionAnalysis::run(), llvm::ADCEPass::run(), llvm::DivRemPairsPass::run(), llvm::VectorCombinePass::run(), llvm::PGOMemOPSizeOpt::run(), llvm::DependenceAnalysis::run(), llvm::DependenceAnalysisPrinterPass::run(), llvm::DivergenceAnalysisPrinterPass::run(), llvm::FunctionPropertiesAnalysis::run(), llvm::InlineCostAnnotationPrinterPass::run(), llvm::LazyValueAnalysis::run(), llvm::ControlHeightReductionPass::run(), llvm::MemorySanitizerPass::run(), llvm::ThreadSanitizerPass::run(), llvm::LoopSinkPass::run(), llvm::LibCallsShrinkWrapPass::run(), llvm::CGSCCToFunctionPassAdaptor::run(), llvm::CoroSplitPass::run(), llvm::ArgumentPromotionPass::run(), llvm::AttributorCGSCCPass::run(), llvm::PostOrderFunctionAttrsPass::run(), llvm::InlinerPass::run(), llvm::OpenMPOptCGSCCPass::run(), llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::run(), llvm::ModuleInlinerPass::run(), llvm::MetaRenamerPass::run(), llvm::AlwaysInlinerPass::run(), llvm::PartialInlinerPass::run(), llvm::WholeProgramDevirtPass::run(), llvm::ModuleToPostOrderCGSCCPassAdaptor::run(), llvm::GlobalsAA::run(), llvm::LazyCallGraphAnalysis::run(), llvm::ModuleSummaryIndexAnalysis::run(), llvm::MustBeExecutedContextPrinterPass::run(), llvm::StackSafetyGlobalAnalysis::run(), llvm::ModuleToFunctionPassAdaptor::run(), llvm::ModuleAddressSanitizerPass::run(), llvm::CGProfilePass::run(), llvm::GCOVProfilerPass::run(), llvm::InstrProfiling::run(), llvm::PGOInstrumentationGen::run(), llvm::PGOInstrumentationUse::run(), llvm::ModuleSanitizerCoveragePass::run(), llvm::AttributorPass::run(), llvm::GlobalOptPass::run(), llvm::HotColdSplittingPass::run(), llvm::InferFunctionAttrsPass::run(), llvm::IROutlinerPass::run(), llvm::LoopExtractorPass::run(), llvm::OpenMPOptPass::run(), llvm::SampleProfileLoaderPass::run(), llvm::PseudoProbeUpdatePass::run(), llvm::IPSCCPPass::run(), llvm::FunctionSpecializationPass::run(), llvm::ThinLTOBitcodeWriterPass::run(), llvm::RewriteStatepointsForGC::run(), llvm::RelLookupTableConverterPass::run(), llvm::AMDGPUPrintfRuntimeBindingPass::run(), llvm::HWAddressSanitizerPass::run(), llvm::SyntheticCountsPropagation::run(), runNewPMPasses(), llvm::InlineAdvisorAnalysis::Result::tryCreate(), llvm::updateCGAndAnalysisManagerForCGSCCPass(), llvm::updateCGAndAnalysisManagerForFunctionPass(), llvm::FunctionAnalysisManagerCGSCCProxy::Result::updateFAM(), and updateNewSCCFunctionAnalyses().
LAM
LoopAnalysisManager LAM
Definition at line 58 of file PassBuilderBindings.cpp.
Referenced by llvm::PassBuilder::crossRegisterProxies(), llvm::PassBuilder::registerLoopAnalyses(), llvm::LoopDistributePass::run(), llvm::LoopLoadEliminationPass::run(), llvm::FunctionToLoopPassAdaptor::run(), llvm::LoopUnrollPass::run(), llvm::LoopVectorizePass::run(), llvm::LoopVersioningPass::run(), and runNewPMPasses().
LLVMErrorSuccess
return LLVMErrorSuccess
Definition at line 79 of file PassBuilderBindings.cpp.
Referenced by LLVMOrcCreateDynamicLibrarySearchGeneratorForPath(), LLVMOrcCreateDynamicLibrarySearchGeneratorForProcess(), LLVMOrcCreateLLJIT(), LLVMOrcCreateLocalLazyCallThroughManager(), LLVMOrcCreateStaticLibrarySearchGeneratorForPath(), LLVMOrcDisposeLLJIT(), LLVMOrcDumpObjects_CallOperator(), LLVMOrcExecutionSessionCreateJITDylib(), LLVMOrcJITTargetMachineBuilderDetectHost(), LLVMOrcLLJITLookup(), and LLVMOrcMaterializationResponsibilityDelegate().
MAM
ModuleAnalysisManager MAM
Definition at line 61 of file PassBuilderBindings.cpp.
Referenced by llvm::PassBuilder::crossRegisterProxies(), llvm::MachineFunctionAnalysisManager::getCachedResult(), llvm::MachineFunctionAnalysisManager::getResult(), llvm::CodeGenPassBuilder< DerivedT >::registerModuleAnalyses(), llvm::PassBuilder::registerModuleAnalyses(), llvm::InlineAdvisorAnalysis::Result::Result(), llvm::ModuleInlinerWrapperPass::run(), llvm::ModuleInlinerPass::run(), llvm::AlwaysInlinerPass::run(), llvm::ModuleAddressSanitizerPass::run(), llvm::CGProfilePass::run(), llvm::ModuleSanitizerCoveragePass::run(), llvm::InlineAdvisorAnalysis::run(), llvm::InlineAdvisorAnalysisPrinterPass::run(), llvm::HWAddressSanitizerPass::run(), llvm::SyntheticCountsPropagation::run(), and runNewPMPasses().
Mod
MPM run * Mod = unwrap(M)
Definition at line 54 of file PassBuilderBindings.cpp.
Referenced by llvm::LTOCodeGenerator::addModule(), allOpsDefaultValue(), llvm::lto::backend(), llvm::AMDGPU::HSAMD::MetadataStreamerV3::begin(), llvm::AMDGPU::HSAMD::MetadataStreamerV4::begin(), llvm::AMDGPU::HSAMD::MetadataStreamerV2::begin(), BinomialCoefficient(), calculateCXXStateNumbers(), llvm::clearAnnotationCache(), codegen(), dropDeadSymbols(), factorizeMinMaxTree(), getDarwinBinOpPrecedence(), getGNUBinOpPrecedence(), llvm::AVRMCExpr::getKindByName(), llvm::LTOModule::getModule(), llvm::AVRMCExpr::getName(), handlePromoteAllocaToVector(), llvm::objcarc::ARCMDKindCache::init(), initAndLookupTarget(), inlineRetainOrClaimRVCalls(), llvm::ThinLTOCodeGenerator::linkCombinedIndex(), LLVMCreateMCJITCompilerForModule(), LLVMGetFirstFunction(), LLVMGetFirstGlobal(), LLVMGetFirstGlobalAlias(), LLVMGetFirstGlobalIFunc(), LLVMGetFirstNamedMetadata(), LLVMGetIntrinsicDeclaration(), LLVMGetLastFunction(), LLVMGetLastGlobal(), LLVMGetLastGlobalAlias(), LLVMGetLastGlobalIFunc(), LLVMGetLastNamedMetadata(), LLVMIntrinsicCopyOverloadedName2(), LLVMRemoveModule(), LLVMTargetMachineEmit(), llvm::VETargetLowering::LowerCall(), maybePrintCallAddrSpace(), modRMByte(), llvm::lto::opt(), optimizeWithFDivFast(), optimizeWithRcp(), llvm::yaml::BlockScalarTraits< Module >::output(), llvm::ThinLTOCodeGenerator::run(), llvm::LintPass::run(), runOldPMPasses(), llvm::LTOCodeGenerator::setAsmUndefinedRefs(), llvm::sampleprof::SampleProfileReader::setModule(), llvm::LTOCodeGenerator::setModule(), SolveLinEquationWithOverflow(), splitCodeGen(), SwitchToLookupTable(), llvm::LTOModule::takeModule(), llvm::lto::thinBackend(), transformCallee(), updateOperand(), and llvm::InstCombinerImpl::visitCallInst().
MPM
ModulePassManager MPM
Definition at line 70 of file PassBuilderBindings.cpp.
Referenced by addAnnotationRemarksPass(), llvm::CodeGenPassBuilder< DerivedT >::AddIRPass::AddIRPass(), llvm::PassBuilder::addPGOInstrPassesForO0(), llvm::PassBuilder::buildLTODefaultPipeline(), llvm::PassBuilder::buildModuleInlinerPipeline(), llvm::PassBuilder::buildModuleOptimizationPipeline(), llvm::PassBuilder::buildModuleSimplificationPipeline(), llvm::PassBuilder::buildO0DefaultPipeline(), llvm::PassBuilder::buildPerModuleDefaultPipeline(), llvm::CodeGenPassBuilder< DerivedT >::buildPipeline(), llvm::PassBuilder::buildThinLTODefaultPipeline(), llvm::PassBuilder::buildThinLTOPreLinkDefaultPipeline(), if(), LLVMPassManagerBuilderPopulateModulePassManager(), llvm::PassBuilder::parsePassPipeline(), llvm::PassManagerBuilder::populateModulePassManager(), and llvm::BPFTargetMachine::registerPassBuilderCallbacks().
Options
const char LLVMTargetMachineRef LLVMPassBuilderOptionsRef Options
Initial value:
{
  TargetMachine *Machine = unwrap(TM)
Examples
/home/fedora/llvm-project/llvm/utils/release/llvm-project/llvm/include/llvm/ADT/ilist_node.h, and /home/fedora/llvm-project/llvm/utils/release/llvm-project/llvm/include/llvm/Transforms/Utils/Local.h.
Definition at line 48 of file PassBuilderBindings.cpp.
Referenced by llvm::LLVMDisasmContext::addOptions(), llvm::PassBuilder::addPGOInstrPassesForO0(), llvm::AddressSanitizerPass::AddressSanitizerPass(), applyCommandLineOverridesToOptions(), llvm::rdf::DataFlowGraph::build(), llvm::CombinerHelper::canCombineFMadOrFMA(), computeDataLayout(), ComputeLinkerOptionsLoadCommandSize(), llvm::MipsABIInfo::computeTargetABI(), computeTargetABI(), llvm::createARMBEAsmBackend(), llvm::createARMLEAsmBackend(), llvm::createCFGSimplificationPass(), llvm::createCSKYAsmBackend(), llvm::createGCOVProfilerPass(), llvm::createInstrProfilingLegacyPass(), llvm::Target::createMCAsmBackend(), createMCAsmInfo(), llvm::Target::createMCAsmInfo(), llvm::Target::createMCAsmParser(), llvm::createMemorySanitizerLegacyPassPass(), llvm::createMipsAsmBackend(), createMipsMCAsmInfo(), llvm::createModuleSanitizerCoverageLegacyPassPass(), llvm::createRISCVAsmBackend(), createTargetMachine(), llvm::Target::createTargetMachine(), createX86MCAsmInfo(), llvm::ehAwareSplitEdge(), llvm::AArch64TTIImpl::enableMemCmpExpansion(), llvm::PPCTTIImpl::enableMemCmpExpansion(), llvm::X86TTIImpl::enableMemCmpExpansion(), llvm::format_provider< llvm::json::Value >::format(), llvm::detail::provider_format_adapter< T >::format(), llvm::FmtAlign::format(), llvm::GCNTTIImpl::getArithmeticInstrCost(), llvm::codegen::getBBSectionsMode(), llvm::GCOVOptions::getDefault(), llvm::NVPTXTargetLowering::getDivF32Level(), llvm::TargetLowering::getNegatedExpression(), llvm::PPCTargetLowering::getNegatedExpression(), llvm::orc::JITTargetMachineBuilder::getOptions(), llvm::LLVMDisasmContext::getOptions(), hasNoInfs(), llvm::HWAddressSanitizerPass::HWAddressSanitizerPass(), llvm::mc::InitMCTargetOptionsFromFlags(), llvm::codegen::InitTargetOptionsFromCodeGenFlags(), llvm::InstrProfiling::InstrProfiling(), isCombineInstrCandidateFP(), isContractableFMUL(), llvm::pdb::NativeTypeFunctionSig::isCxxReturnUdt(), isFMAddSubOrFMSubAdd(), IsInterestingCmp(), llvm::SelectionDAG::isKnownNeverNaN(), isLegalToCombineMinNumMaxNum(), llvm::GVNPass::isLoadInLoopPREEnabled(), llvm::GVNPass::isLoadPREEnabled(), llvm::GVNPass::isLoadPRESplitBackedgeEnabled(), llvm::GVNPass::isMemDepEnabled(), llvm::GVNPass::isPREEnabled(), llvm::AArch64TargetLowering::isProfitableToHoist(), llvm::PPCTargetLowering::isProfitableToHoist(), iterativelySimplifyCFG(), llvm::LLVMDisasmContext::LLVMDisasmContext(), LLVMDisposePassBuilderOptions(), LLVMPassBuilderOptionsSetCallGraphProfile(), LLVMPassBuilderOptionsSetDebugLogging(), LLVMPassBuilderOptionsSetForgetAllSCEVInLoopUnroll(), LLVMPassBuilderOptionsSetLicmMssaNoAccForPromotionCap(), LLVMPassBuilderOptionsSetLicmMssaOptCap(), LLVMPassBuilderOptionsSetLoopInterleaving(), LLVMPassBuilderOptionsSetLoopUnrolling(), LLVMPassBuilderOptionsSetLoopVectorization(), LLVMPassBuilderOptionsSetMergeFunctions(), LLVMPassBuilderOptionsSetSLPVectorization(), LLVMPassBuilderOptionsSetVerifyEach(), LLVMSetDisasmOptions(), llvm::AMDGPUTargetLowering::LowerFP_TO_FP16(), mayIgnoreSignedZero(), llvm::AMDGPUTargetLowering::mayIgnoreSignedZero(), llvm::MemorySanitizerPass::MemorySanitizerPass(), llvm::MergedLoadStoreMotionPass::MergedLoadStoreMotionPass(), llvm::MipsMCAsmInfo::MipsMCAsmInfo(), llvm::ModuleMemorySanitizerPass::ModuleMemorySanitizerPass(), llvm::parseCommandLineOptions(), llvm::formatv_object_base::parseReplacementItem(), llvm::GVNPass::printPipeline(), llvm::RISCVAsmBackend::RISCVAsmBackend(), llvm::MergedLoadStoreMotionPass::run(), llvm::ModuleSanitizerCoveragePass::run(), llvm::LTOCodeGenerator::setCodeGenDebugOptions(), llvm::orc::JITTargetMachineBuilder::setOptions(), llvm::LTOCodeGenerator::setTargetOptions(), llvm::EngineBuilder::setTargetOptions(), llvm::ThinLTOCodeGenerator::setTargetOptions(), shouldInstrumentBlock(), llvm::simplifyCFG(), simplifyFunctionCFG(), simplifyFunctionCFGImpl(), llvm::SplitAllCriticalEdges(), llvm::SplitCriticalEdge(), llvm::SplitEdge(), llvm::SplitKnownCriticalEdge(), llvm::cl::values(), and llvm::MachObjectWriter::writeLinkerOptionsLoadCommand().
Passes
const char* Passes
Definition at line 46 of file PassBuilderBindings.cpp.
Referenced by llvm::MachineFunctionPassManager::addPass(), llvm::jitlink::JITLinkerBase::JITLinkerBase(), llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::run(), and simplifySetCCWithCTPOP().
PassOpts
LLVMPassBuilderOptions* PassOpts = unwrap(Options)
Definition at line 50 of file PassBuilderBindings.cpp.
PIC
PassInstrumentationCallbacks PIC
Definition at line 55 of file PassBuilderBindings.cpp.
Referenced by llvm::Target::createMCObjectFileInfo(), createRISCVMCObjectFileInfo(), llvm::PassBuilder::getPassInstrumentationCallbacks(), llvm::MCObjectFileInfo::initMCObjectFileInfo(), llvm::PassBuilder::PassBuilder(), llvm::promoteLoopAccessesToScalars(), llvm::TimePassesHandler::registerCallbacks(), llvm::PrintIRInstrumentation::registerCallbacks(), llvm::OptNoneInstrumentation::registerCallbacks(), llvm::OptBisectInstrumentation::registerCallbacks(), llvm::PrintPassInstrumentation::registerCallbacks(), llvm::IRChangedPrinter::registerCallbacks(), llvm::InLineChangePrinter::registerCallbacks(), llvm::VerifyInstrumentation::registerCallbacks(), llvm::DotCfgChangeReporter::registerCallbacks(), llvm::PseudoProbeVerifier::registerCallbacks(), llvm::DebugifyEachInstrumentation::registerCallbacks(), llvm::PreservedCFGCheckerInstrumentation::registerCallbacks(), llvm::StandardInstrumentations::registerCallbacks(), llvm::registerCodeGenCallback(), registerPartialPipelineCallback(), llvm::ChangeReporter< IRUnitT >::registerRequiredCallbacks(), and runNewPMPasses().
SI
StandardInstrumentations SI(Debug, VerifyEach) (Debug , VerifyEach)
Examples
/home/fedora/llvm-project/llvm/utils/release/llvm-project/llvm/include/llvm/Transforms/Utils/Local.h.
Referenced by llvm::AliasSetTracker::add(), llvm::MemoryDepChecker::addAccess(), AddAliasScopeMetadata(), addBoundsChecking(), llvm::SwitchInstProfUpdateWrapper::addCase(), llvm::object::BindRebaseSegInfo::address(), llvm::MCRegAliasIterator::advance(), llvm::GCNDownwardRPTracker::advanceBeforeNext(), allUsesOfLoadedValueWillTrapIfNull(), AllUsesOfValueWillTrapIfNull(), analyzeGlobalAux(), analyzeLoopUnrollCost(), llvm::HexagonSubtarget::HVXMemLatencyMutation::apply(), assertBranchOrSelectConditionHoisted(), assertCHRRegionsHaveBiasedBranchOrSelect(), llvm::sroa::Partition::begin(), llvm::SwitchCG::SwitchLowering::buildBitTests(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), buildClonedLoopBlocks(), llvm::coro::Shape::buildFrom(), llvm::SwitchCG::SwitchLowering::buildJumpTable(), llvm::PredicateInfoBuilder::buildPredicateInfo(), llvm::SwitchInstProfUpdateWrapper::buildProfBranchWeightsMD(), calculateFileAlignment(), canEvaluateShifted(), canEvaluateTruncated(), canSimplifyNullStoreOrGEP(), llvm::canSinkOrHoistInst(), llvm::objcarc::CanUse(), canVectorizeInst(), AACaptureUseTracker::captured(), CheckBaseRegAndIndexRegAndScale(), checkBiasedSelect(), llvm::Attributor::checkForAllUses(), checkFunctionMemoryAccess(), CleanupConstantGlobalUsers(), CleanupPointerRootUsers(), llvm::FunctionComparator::cmpOperations(), collectPromotionCandidates(), collectValuesToDemote(), combineStoreToNewValue(), combineStoreToValueType(), llvm::InstCombinerImpl::commonIRemTransforms(), llvm::InstCombinerImpl::commonShiftTransforms(), llvm::computeConstantRange(), llvm::RuntimeDyldImpl::computeGOTSize(), computePath(), llvm::RuntimeDyldImpl::computeSectionStubBufSize(), llvm::RuntimeDyldImpl::computeTotalAllocSize(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::ConstantFoldTerminator(), llvm::ConvertDebugDeclareToDebugValue(), llvm::FastISel::createMachineMemOperandFor(), llvm::createSelectCmpTargetReduction(), llvm::DependenceInfo::depends(), llvm::orc::shared::SPSSerializationTraits< SPSSimpleRemoteEPCExecutorInfo, SimpleRemoteEPCExecutorInfo >::deserialize(), directlyImpliesPoison(), eliminateDeadSwitchCases(), emitRepmovs(), llvm::sroa::Partition::empty(), equalityPropUnSafe(), llvm::SwitchInstProfUpdateWrapper::eraseFromParent(), EraseTerminatorAndDCECond(), llvm::VPWidenMemoryInstructionRecipe::execute(), ExtractEquivalentCondition(), llvm::RuntimeDyldELF::finalizeLoad(), FindAllMemoryUses(), llvm::findAllocaForValue(), findArgumentCopyElisionCandidates(), llvm::findAvailablePtrLoadStore(), llvm::SwitchCG::SwitchLowering::findBitTestClusters(), findCommonType(), llvm::SwitchCG::SwitchLowering::findJumpTables(), findUniqueStoreInBlocks(), llvm::InstCombinerImpl::foldAllocaCmp(), llvm::InstCombinerImpl::foldICmpInstWithConstant(), foldICmpWithDominatingICmp(), llvm::InstCombinerImpl::foldIntegerTypedPHI(), llvm::InstCombinerImpl::foldOpIntoPhi(), llvm::InstCombinerImpl::FoldOpIntoSelect(), foldSelectInst(), llvm::InstCombinerImpl::foldSelectIntoOp(), llvm::InstCombinerImpl::foldSelectOpOp(), foldSelectZeroOrMul(), AAPointerInfoImpl::forallInterferingAccesses(), ForwardSwitchConditionToPHI(), llvm::SwitchInst::CaseIteratorImpl< CaseHandleT >::fromSuccessorIndex(), llvm::fuseInstructionPair(), genericValueTraversal(), llvm::MemoryLocation::get(), getAccessType(), getAtomicOpSize(), getAvailableLoadStore(), getBranchInsertPoint(), GetCaseResults(), llvm::SwitchInst::CaseHandleImpl< SwitchInstT, ConstantIntT, BasicBlockT >::getCaseSuccessor(), llvm::SwitchInst::CaseHandleImpl< SwitchInstT, ConstantIntT, BasicBlockT >::getCaseValue(), llvm::GCNTTIImpl::getCFInstrCost(), getCHRConditionValuesForRegion(), llvm::CoroSuspendInst::getCoroSave(), llvm::DOTGraphTraits< DOTFuncInfo * >::getEdgeSourceLabel(), getEdgeValueLocal(), llvm::StructLayout::getElementContainingOffset(), llvm::TargetTransformInfo::getEstimatedNumberOfCaseClusters(), llvm::TargetTransformInfoImplBase::getEstimatedNumberOfCaseClusters(), llvm::BasicTTIImplBase< T >::getEstimatedNumberOfCaseClusters(), llvm::FunctionPropertiesInfo::getFunctionPropertiesInfo(), getKnownAlignForUse(), llvm::getLiveLaneMask(), llvm::getLiveRegMap(), llvm::getLiveRegs(), GetLocation(), getLocation(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), getMappedReg(), llvm::SystemZTTIImpl::getMemoryOpCost(), llvm::X86TTIImpl::getMemoryOpCost(), llvm::MemoryDependenceResults::getNonLocalPointerDependency(), llvm::LiveIntervalUnion::getOneVReg(), getOnlyLiveSuccessor(), getPointerOperand(), getPointerOperandIndex(), llvm::AA::getPotentialCopiesOfStoredValue(), getPredClusterSU(), llvm::SwitchInstProfUpdateWrapper::getProfBranchWeightsMD(), llvm::RuntimeDyldMachO::getRelocationValueRef(), llvm::ARMBaseRegisterInfo::getReservedRegs(), llvm::RuntimeDyldMachO::getSectionByAddress(), getSelectsInScope(), llvm::MemoryDependenceResults::getSimplePointerDependencyFrom(), getSingleLiveInSuccBB(), llvm::BasicBlock::getSingleSuccessor(), llvm::DependenceInfo::getSplitIteration(), llvm::TargetLoweringBase::getStoreMemOperandFlags(), GetStringLengthH(), llvm::SwitchInstProfUpdateWrapper::getSuccessorWeight(), getTrueOrFalseValue(), llvm::getUnderlyingObjects(), llvm::BasicBlock::getUniqueSuccessor(), getUsedRegMask(), llvm::TargetTransformInfoImplCRTPBase< T >::getUserCost(), llvm::Record::getValueAsOptionalString(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::getX86SubSuperRegisterOrZero(), llvm::SelectionDAGBuilder::handleDebugValue(), handleSwitchExpect(), hasZeroSignBit(), haveSameSpecialState(), hoistScopeConditions(), identifyAliveSuccessors(), llvm::SwitchInstProfUpdateWrapper::init(), INITIALIZE_PASS(), InitializeUniqueCases(), llvm::X86_MC::initLLVMToSEHAndCVRegMapping(), InsertRootInitializers(), InTreeUserNeedToExtract(), isAddressUse(), llvm::isAllocaPromotable(), isAllocSiteRemovable(), isAtomic(), isChainSelectCmpBranch(), llvm::RecurrenceDescriptor::isConditionalRdxPattern(), AAIsDeadFloating::isDeadStore(), isFormingBranchFromSelectProfitable(), llvm::object::XCOFFSymbolRef::isFunction(), isFunctionMallocLike(), isGuaranteedNotToBeUndefOrPoison(), isIntegerWideningViableForSlice(), isKnownNonZero(), isKnownToBeAPowerOfTwo(), llvm::LoopVectorizationCostModel::isLegalGatherOrScatter(), llvm::TargetTransformInfo::isLegalToVectorizeStore(), isLoadOrStore(), llvm::SwingSchedulerDAG::isLoopCarriedDep(), isNonEscapingGlobalNoAliasWithLoad(), isNonVolatileStore(), isObjectSizeLessThanOrEq(), llvm::AArch64TargetLowering::isOpSuitableForLDPSTP(), isOrdered(), isOrderedAtomic(), isPointerValueDeadOnEntryToFunction(), isReturnNonNull(), isSafeAndProfitableToSinkLoad(), isSafeSelectToSpeculate(), llvm::isSafeToLoadUnconditionally(), isSafeToSpeculateStore(), llvm::RecurrenceDescriptor::isSelectCmpPattern(), isSimple(), isSimplePointerUseValidToReplace(), llvm::X86Operand::isSrcIdx(), llvm::Record::isSubClassOf(), isSuccOrder(), llvm::TargetLoweringBase::isSuitableForJumpTable(), isUnorderedLoadStore(), llvm::GCNUpwardRPTracker::isValid(), llvm::SMSchedule::isValidSchedule(), isVectorPromotionViable(), isVectorPromotionViableForSlice(), llvm::SMSchedule::latestCycleInChain(), LLVMDisposeRelocationIterator(), LLVMDisposeSectionIterator(), LLVMDisposeSymbolIterator(), LLVMGetAlignment(), LLVMGetOrdering(), LLVMGetRelocations(), LLVMGetSectionAddress(), LLVMGetSectionContainsSymbol(), LLVMGetSectionContents(), LLVMGetSectionName(), LLVMGetSections(), LLVMGetSectionSize(), LLVMGetSymbolAddress(), LLVMGetSymbolName(), LLVMGetSymbols(), LLVMGetSymbolSize(), LLVMGetVolatile(), LLVMIsRelocationIteratorAtEnd(), LLVMIsSectionIteratorAtEnd(), LLVMIsSymbolIteratorAtEnd(), LLVMMoveToNextRelocation(), LLVMMoveToNextSection(), LLVMMoveToNextSymbol(), LLVMObjectFileIsSectionIteratorAtEnd(), LLVMObjectFileIsSymbolIteratorAtEnd(), LLVMSetAlignment(), LLVMSetVolatile(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), llvm::TargetLowering::lowerAtomicStoreAsStoreSDNode(), lowerCallFromStatepointLoweringInfo(), llvm::SelectionDAGBuilder::LowerCallSiteWithDeoptBundleImpl(), llvm::LowerDbgDeclare(), lowerExpectIntrinsic(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), llvm::X86TargetLowering::lowerInterleavedStore(), llvm::SelectionDAGBuilder::LowerStatepoint(), lowerStatepointMetaArgs(), LowerStoreInst(), AAAlignImpl::manifest(), markAliveBlocks(), llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t, Commutable >::match(), llvm::matchSelectPattern(), llvm::InstCombinerImpl::matchThreeWayIntCompare(), llvm::MCRegAliasIterator::MCRegAliasIterator(), mergeConditionalStores(), mergeConditionalStoreToAddress(), llvm::InstCombinerImpl::mergeStoreIntoSuccessor(), negateICmpIfUsedByBranchOrSelectOnly(), llvm::orc::EHFrameRegistrationPlugin::notifyTransferringResources(), llvm::SwitchInstProfUpdateWrapper::operator SwitchInst *(), llvm::SwitchInstProfUpdateWrapper::operator*(), llvm::MCRegAliasIterator::operator*(), llvm::MCRegAliasIterator::operator++(), llvm::SwitchInstProfUpdateWrapper::operator->(), llvm::SwitchInst::CaseHandleImpl< SwitchInstT, ConstantIntT, BasicBlockT >::operator==(), OptimizeAwayTrappingUsesOfValue(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), OptimizeGlobalAddressOfAllocation(), llvm::ms_demangle::Demangler::parse(), passingValueIsAlwaysUndefined(), llvm::BasicAAResult::pointsToConstantMemory(), llvm::RuntimeDyldMachO::populateIndirectSymbolPointersSection(), prepareICWorklistFromFunction(), llvm::LiveIntervalUnion::print(), llvm::sampleprof::FunctionSamples::print(), llvm::printLivesAt(), llvm::AlignmentFromAssumptionsPass::processAssumption(), llvm::JumpThreadingPass::processBlock(), processCallSite(), processDbgDeclares(), processPHI(), processSaturatingInst(), processSwitch(), llvm::JumpThreadingPass::processThreadableEdges(), processUse(), promoteSingleBlockAlloca(), ReduceSwitchRange(), llvm::TrackingStatistic::RegisterStatistic(), regJustKilledBefore(), removeBitcastsFromLoadStoreOnMinMax(), llvm::SwitchInstProfUpdateWrapper::removeCase(), removeExternalCFGEdges(), removeMapRegEntry(), removeNonFeasibleEdges(), RemoveSwitchAfterSelectConversion(), removeUndefIntroducingPredecessor(), replaceArgumentUses(), llvm::InstCombinerImpl::replacedSelectWithOperand(), llvm::replaceSymbolicStrideSCEV(), llvm::LiveRangeCalc::reset(), llvm::rdf::Liveness::resetKills(), llvm::SCCPInstVisitor::resolvedUndefsIn(), llvm::LoadAndStorePromoter::run(), llvm::runIPSCCP(), runNewPMPasses(), runOnBasicBlock(), llvm::RegScavenger::scavengeRegister(), llvm::ConvergingVLIWScheduler::SchedulingCost(), llvm::object::BindRebaseSegInfo::segmentName(), llvm::orc::shared::SPSSerializationTraits< SPSSimpleRemoteEPCExecutorInfo, SimpleRemoteEPCExecutorInfo >::serialize(), llvm::set_difference(), llvm::SetVector< T, Vector, Set >::set_subtract(), llvm::set_subtract(), llvm::SetVector< T, Vector, Set >::set_union(), llvm::set_union(), llvm::MIRProfileLoader::setBranchProbs(), setBranchWeights(), setLimitsForSelectPattern(), llvm::Module::setSemanticInterposition(), llvm::SwitchInst::CaseHandle::setSuccessor(), llvm::SwitchInstProfUpdateWrapper::setSuccessorWeight(), llvm::SwitchInst::CaseHandle::setValue(), llvm::InstCombiner::shouldAvoidAbsorbingNotIntoSelect(), ShouldBuildLookupTable(), llvm::SystemZRegisterInfo::shouldCoalesce(), llvm::AArch64TargetLowering::shouldExpandAtomicStoreInIR(), llvm::ARMTargetLowering::shouldExpandAtomicStoreInIR(), llvm::HexagonTargetLowering::shouldExpandAtomicStoreInIR(), llvm::InstCombinerImpl::simplifyDivRemOfSelectWithZeroOp(), llvm::InstCombinerImpl::SimplifySelectsFeedingBinaryOp(), simplifySuspendPoints(), simplifyTerminatorLeadingToRet(), llvm::orc::shared::SPSSerializationTraits< SPSSimpleRemoteEPCExecutorInfo, SimpleRemoteEPCExecutorInfo >::size(), speculateSelectInstLoads(), splitMergedValStore(), SRAGlobal(), llvm::SwitchInstProfUpdateWrapper::SwitchInstProfUpdateWrapper(), SwitchToLookupTable(), switchToSelect(), ThreadBinOpOverSelect(), ThreadCmpOverSelect(), translateRMMemory(), translateSrcIndex(), llvm::InnerLoopVectorizer::truncateToMinimalBitwidths(), tryPromoteAllocaToVector(), tryToElideArgumentCopy(), TryToShrinkGlobalToBoolean(), llvm::JumpThreadingPass::tryToUnfoldSelect(), llvm::JumpThreadingPass::tryToUnfoldSelectInCurrBB(), llvm::JumpThreadingPass::unfoldSelectInstr(), unpackStoreToAggregate(), unswitchAllTrivialConditions(), unswitchBestCondition(), unswitchNontrivialInvariants(), unswitchTrivialSwitch(), unwrap(), AAIsDeadFloating::updateImpl(), AAHeapToStackFunction::updateImpl(), AAPotentialValuesFloating::updateImpl(), AAPotentialValuesFloating::updateWithSelectInst(), valueIsOnlyUsedLocallyOrStoredToOneGlobal(), llvm::LiveIntervalUnion::verify(), llvm::MemoryOpRemark::visit(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAllocSite(), llvm::InstCombinerImpl::visitAtomicRMWInst(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitFDiv(), llvm::InstCombinerImpl::visitFreeze(), llvm::InstCombinerImpl::visitFSub(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitLoadInst(), llvm::PtrUseVisitor< DerivedT >::visitStoreInst(), llvm::InstCombinerImpl::visitStoreInst(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitSwitchInst(), visitUDivOperand(), llvm::InstCombinerImpl::visitUnconditionalBranchInst(), llvm::Instruction::willReturn(), wrap(), and llvm::SwitchInstProfUpdateWrapper::~SwitchInstProfUpdateWrapper().
TM
const char LLVMTargetMachineRef TM
Definition at line 47 of file PassBuilderBindings.cpp.
Referenced by llvm::AArch64LegalizerInfo::AArch64LegalizerInfo(), llvm::AArch64Subtarget::AArch64Subtarget(), llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::CodeGenPassBuilder< DerivedT >::addCoreISelPasses(), llvm::CodeGenPassBuilder< DerivedT >::addISelPasses(), llvm::CodeGenPassBuilder< DerivedT >::addMachineLateOptimization(), llvm::CodeGenPassBuilder< DerivedT >::addMachinePasses(), addPassesToGenerateCode(), llvm::CodeGenPassBuilder< DerivedT >::addPassesToHandleExceptions(), llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo(), llvm::AMDGPULibCalls::AMDGPULibCalls(), llvm::AMDGPUPromoteAllocaPass::AMDGPUPromoteAllocaPass(), llvm::AMDGPUPromoteAllocaToVectorPass::AMDGPUPromoteAllocaToVectorPass(), llvm::AMDGPUPropagateAttributesEarlyPass::AMDGPUPropagateAttributesEarlyPass(), llvm::AMDGPUPropagateAttributesLatePass::AMDGPUPropagateAttributesLatePass(), llvm::AMDGPUSimplifyLibCallsPass::AMDGPUSimplifyLibCallsPass(), llvm::AArch64TTIImpl::areInlineCompatible(), llvm::GCNTTIImpl::areInlineCompatible(), llvm::ARMTTIImpl::areInlineCompatible(), llvm::WebAssemblyTTIImpl::areInlineCompatible(), llvm::X86TTIImpl::areInlineCompatible(), llvm::X86TTIImpl::areTypesABICompatible(), llvm::ARMTargetLowering::ARMTargetLowering(), assureFPCallStub(), llvm::lto::backend(), basicCheckForEHAndSjLj(), llvm::BPFAbstractMemberAccessPass::BPFAbstractMemberAccessPass(), calcUniqueIDUpdateFlagsAndSize(), callsShareTOCBase(), llvm::AArch64Subtarget::classifyGlobalFunctionReference(), llvm::AArch64Subtarget::ClassifyGlobalReference(), codegen(), computeHeuristicUnrollFactor(), llvm::computeLegalValueVTs(), llvm::rdf::Liveness::computeLiveIns(), llvm::computeSignatureVTs(), llvm::TargetMachineBuilder::create(), llvm::MipsTargetLowering::create(), llvm::EngineBuilder::create(), llvm::createAArch64InstructionSelector(), llvm::createAArch64ISelDag(), llvm::createAMDGPUISelDag(), llvm::createAMDGPUPropagateAttributesEarlyPass(), llvm::createAMDGPUPropagateAttributesLatePass(), llvm::createAMDGPUSimplifyLibCallsPass(), llvm::createARCISelDag(), llvm::createARMInstructionSelector(), llvm::createARMISelDag(), llvm::Target::createAsmPrinter(), llvm::createAVRISelDag(), llvm::createBPFISelDag(), llvm::orc::LLJIT::createCompileFunction(), llvm::createCSKYISelDag(), llvm::MipsTargetLowering::createFastISel(), createFPFnStub(), llvm::createGlobalMergePass(), llvm::createHexagonISelDag(), llvm::MCJIT::createJIT(), llvm::createLanaiISelDag(), llvm::createM68kInstructionSelector(), llvm::createM68kISelDag(), llvm::createMCMasmParser(), llvm::createMips16ISelDag(), llvm::createMips16TargetLowering(), llvm::createMipsInstructionSelector(), llvm::createMipsSETargetLowering(), llvm::createMSP430ISelDag(), llvm::createNVPTXISelDag(), llvm::createNVPTXLowerArgsPass(), llvm::createPPCInstructionSelector(), llvm::createPPCISelDag(), llvm::createPPCLoopInstrFormPrepPass(), llvm::createR600AsmPrinterPass(), llvm::createR600ISelDag(), llvm::createRISCVInstructionSelector(), llvm::createRISCVISelDag(), llvm::createSparcISelDag(), llvm::createSystemZISelDag(), llvm::orc::JITTargetMachineBuilder::createTargetMachine(), createTargetMachine(), llvm::createVEISelDag(), llvm::createWebAssemblyISelDag(), llvm::createX86InstructionSelector(), llvm::createX86ISelDag(), llvm::createXCoreISelDag(), llvm::AVRRegisterInfo::eliminateFrameIndex(), emitDirectiveRelocJalr(), llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), llvm::MCJIT::emitObject(), llvm::ARMFrameLowering::emitPrologue(), llvm::AArch64InstrInfo::expandPostRAPseudo(), llvm::SwitchCG::SwitchLowering::findBitTestClusters(), llvm::SwitchCG::SwitchLowering::findJumpTables(), fixupFPReturnAndCall(), llvm::GCNSubtarget::GCNSubtarget(), llvm::AMDGPUSubtarget::get(), getCallOpcode(), llvm::TargetLoweringObjectFileELF::getCFIPersonalitySymbol(), llvm::TargetLoweringObjectFileMachO::getCFIPersonalitySymbol(), llvm::AArch64_MachoTargetObjectFile::getCFIPersonalitySymbol(), llvm::X86_64MachoTargetObjectFile::getCFIPersonalitySymbol(), getCOFFSectionFlags(), llvm::orc::JITTargetMachineBuilder::getDefaultDataLayoutForTarget(), getELFSectionNameForGlobal(), llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileWasm::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileGOFF::getExplicitSectionGlobal(), llvm::ARMElfTargetObjectFile::getExplicitSectionGlobal(), llvm::NVPTXRegisterInfo::getFrameLocalRegister(), llvm::NVPTXRegisterInfo::getFrameRegister(), getFSProfileFile(), getFSRemappingFile(), llvm::TargetLoweringObjectFileXCOFF::getFunctionEntryPointSymbol(), getFunctionReturns(), getGlobalBaseRegClass(), getGlobalVariable(), llvm::AVRInstrInfo::getInstSizeInBytes(), llvm::RISCVInstrInfo::getInstSizeInBytes(), llvm::ARMAsmPrinter::getISAEncoding(), getLinkedToSymbol(), llvm::TargetLoweringObjectFileMachO::getNameWithPrefix(), llvm::TargetLoweringObjectFileCOFF::getNameWithPrefix(), llvm::MCJIT::getPointerToFunction(), llvm::PPCTargetLowering::getRegForInlineAsmConstraint(), llvm::MipsTargetObjectFile::getSectionForConstant(), llvm::TargetLoweringObjectFileXCOFF::getSectionForExternalReference(), llvm::TargetLoweringObjectFileXCOFF::getSectionForFunctionDescriptor(), llvm::TargetLoweringObjectFileELF::getSectionForJumpTable(), llvm::TargetLoweringObjectFileCOFF::getSectionForJumpTable(), llvm::TargetLoweringObjectFileXCOFF::getSectionForJumpTable(), llvm::TargetLoweringObjectFileELF::getSectionForLSDA(), llvm::TargetLoweringObjectFileELF::getSectionForMachineBasicBlock(), llvm::TargetLoweringObjectFileXCOFF::getSectionForTOCEntry(), GetSymbolFromOperand(), GetSymbolRef(), llvm::MachineModuleInfo::getTarget(), llvm::SelectionDAG::getTarget(), llvm::MCJIT::getTargetMachine(), llvm::SystemZTargetLowering::getTargetNodeName(), llvm::TargetLoweringObjectFileXCOFF::getTargetSymbol(), llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference(), llvm::AArch64_MachoTargetObjectFile::getTTypeGlobalReference(), llvm::ARMElfTargetObjectFile::getTTypeGlobalReference(), llvm::X86_64MachoTargetObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileELF::getUniqueSectionForFunction(), llvm::HexagonFrameLowering::hasFP(), llvm::TargetLoweringObjectFileMachO::Initialize(), llvm::TargetLoweringObjectFileCOFF::Initialize(), llvm::ARMElfTargetObjectFile::Initialize(), llvm::M68kELFTargetObjectFile::Initialize(), llvm::MipsTargetObjectFile::Initialize(), INITIALIZE_PASS(), llvm::MIRParserImpl::initializeCallSiteInfo(), llvm::MIRParserImpl::initializeMachineFunction(), llvm::MipsSubtarget::initializeSubtargetDependencies(), llvm::SampleProfileProber::instrumentOneFunc(), llvm::MipsTargetObjectFile::IsConstantInSmallSection(), isExecuteOnlyFunction(), llvm::SITargetLowering::isFreeAddrSpaceCast(), llvm::MipsTargetObjectFile::IsGlobalInSmallSection(), llvm::PPCTTIImpl::isHardwareLoopProfitable(), llvm::isInTailCallPosition(), llvm::isKnownNeverNaN(), isKnownNonNull(), llvm::TargetLowering::isOffsetFoldingLegal(), llvm::AMDGPULegalizerInfo::legalizeAddrSpaceCast(), LLVMOrcJITTargetMachineBuilderCreateFromTargetMachine(), LLVMTargetMachineEmit(), llvm::MipsCallLowering::lowerCall(), llvm::VETargetLowering::LowerCall(), llvm::TargetLoweringObjectFileELF::lowerDSOLocalEquivalent(), llvm::MipsCallLowering::lowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::VETargetLowering::lowerINTRINSIC_WO_CHAIN(), llvm::TargetLoweringObjectFileELF::lowerRelativeReference(), llvm::TargetLoweringObjectFileCOFF::lowerRelativeReference(), llvm::TargetLoweringObjectFileWasm::lowerRelativeReference(), llvm::M68kAsmPrinter::M68kAsmPrinter(), llvm::MachineModuleAnalysis::MachineModuleAnalysis(), llvm::MachineModuleInfo::MachineModuleInfo(), memAddrUsesCTR(), llvm::MipsSubtarget::MipsSubtarget(), llvm::MipsTargetLowering::MipsTargetLowering(), needsPrologueENDBR(), llvm::orc::ConcurrentIRCompiler::operator()(), llvm::lto::opt(), llvm::MIRParserImpl::parseMachineFunction(), llvm::PassBuilder::PassBuilder(), performGlobalAddressCombine(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::MIRPrinter::print(), promoteAllocasToVector(), reservePrivateMemoryRegs(), llvm::GCNTTIImpl::rewriteIntrinsicWithAddressSpace(), llvm::RISCVSubtarget::RISCVSubtarget(), llvm::AMDGPUPropagateAttributesEarlyPass::run(), llvm::AMDGPUPropagateAttributesLatePass::run(), runNewPMPasses(), runOldPMPasses(), llvm::IRTranslator::runOnMachineFunction(), llvm::AMDGPUPerfHintAnalysis::runOnSCC(), llvm::AMDGPUResourceUsageAnalysis::runOnSCC(), selectELFSectionForGlobal(), selectExplicitSectionGlobal(), llvm::SelectionDAGBuilder::SelectionDAGBuilder(), llvm::FastISel::selectOperator(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileWasm::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileXCOFF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileGOFF::SelectSectionForGlobal(), llvm::ARMElfTargetObjectFile::SelectSectionForGlobal(), llvm::MipsTargetObjectFile::SelectSectionForGlobal(), selectWasmSectionForGlobal(), llvm::FastISel::selectXRayCustomEvent(), llvm::FastISel::selectXRayTypedEvent(), llvm::BasicTTIImplBase< T >::shouldBuildRelLookupTables(), llvm::PPCTTIImpl::shouldBuildRelLookupTables(), llvm::orc::SimpleCompiler::SimpleCompiler(), llvm::SparcTargetLowering::SparcTargetLowering(), splitCodeGen(), llvm::SystemZTargetLowering::SystemZTargetLowering(), llvm::lto::thinBackend(), llvm::orc::TMOwningSimpleCompiler::TMOwningSimpleCompiler(), TransferTracker::TransferTracker(), transformCallee(), tryToUnrollLoop(), llvm::updateCompilerUsed(), llvm::X86Subtarget::X86Subtarget(), and llvm::X86TargetLowering::X86TargetLowering().
VerifyEach
bool VerifyEach = PassOpts->VerifyEach
Definition at line 52 of file PassBuilderBindings.cpp.
Referenced by LLVMPassBuilderOptionsSetVerifyEach().