LLVM: lib/ProfileData/ProfileSummaryBuilder.cpp File Reference
ProfileSummaryBuilder.cpp File Reference
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Type.h"
#include "llvm/ProfileData/InstrProf.h"
#include "llvm/ProfileData/ProfileCommon.h"
#include "llvm/ProfileData/SampleProf.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
Variables
cl::opt< bool > UseContextLessSummary ("profile-summary-contextless", cl::Hidden, cl::init(false), cl::ZeroOrMore, cl::desc("Merge context profiles before calculating thresholds."))
cl::opt< int > ProfileSummaryCutoffHot ("profile-summary-cutoff-hot", cl::Hidden, cl::init(990000), cl::ZeroOrMore, cl::desc("A count is hot if it exceeds the minimum count to" " reach this percentile of total counts."))
cl::opt< int > ProfileSummaryCutoffCold ("profile-summary-cutoff-cold", cl::Hidden, cl::init(999999), cl::ZeroOrMore, cl::desc("A count is cold if it is below the minimum count" " to reach this percentile of total counts."))
cl::opt< unsigned > ProfileSummaryHugeWorkingSetSizeThreshold ("profile-summary-huge-working-set-size-threshold", cl::Hidden, cl::init(15000), cl::ZeroOrMore, cl::desc("The code working set size is considered huge if the number of" " blocks required to reach the -profile-summary-cutoff-hot" " percentile exceeds this count."))
cl::opt< unsigned > ProfileSummaryLargeWorkingSetSizeThreshold ("profile-summary-large-working-set-size-threshold", cl::Hidden, cl::init(12500), cl::ZeroOrMore, cl::desc("The code working set size is considered large if the number of" " blocks required to reach the -profile-summary-cutoff-hot" " percentile exceeds this count."))
cl::opt< int > ProfileSummaryHotCount ("profile-summary-hot-count", cl::ReallyHidden, cl::ZeroOrMore, cl::desc("A fixed hot count that overrides the count derived from" " profile-summary-cutoff-hot"))
cl::opt< int > ProfileSummaryColdCount ("profile-summary-cold-count", cl::ReallyHidden, cl::ZeroOrMore, cl::desc("A fixed cold count that overrides the count derived from" " profile-summary-cutoff-cold"))
static const uint32_t DefaultCutoffsData []
Variable Documentation
DefaultCutoffsData
const uint32_t DefaultCutoffsData[] static
Initial value:
= {
    10000,
    100000,
    200000, 300000, 400000, 500000, 600000, 700000, 800000,
    900000, 950000, 990000, 999000, 999900, 999990, 999999}
Definition at line 74 of file ProfileSummaryBuilder.cpp.
ProfileSummaryColdCount
cl::opt<int> ProfileSummaryColdCount("profile-summary-cold-count", cl::ReallyHidden, cl::ZeroOrMore, cl::desc("A fixed cold count that overrides the count derived from" " profile-summary-cutoff-cold")) ("profile-summary-cold-count" , cl::ReallyHidden , cl::ZeroOrMore , cl::desc("A fixed cold count that overrides the count derived from" " profile-summary-cutoff-cold"))
Referenced by llvm::ProfileSummaryBuilder::getColdCountThreshold().
ProfileSummaryCutoffCold
cl::opt<int> ProfileSummaryCutoffCold("profile-summary-cutoff-cold", cl::Hidden, cl::init(999999), cl::ZeroOrMore, cl::desc("A count is cold if it is below the minimum count" " to reach this percentile of total counts.")) ("profile-summary-cutoff-cold" , cl::Hidden , cl::init(999999) , cl::ZeroOrMore , cl::desc("A count is cold if it is below the minimum count" " to reach this percentile of total counts."))
Referenced by llvm::ProfileSummaryBuilder::getColdCountThreshold().
ProfileSummaryCutoffHot
cl::opt<int> ProfileSummaryCutoffHot("profile-summary-cutoff-hot", cl::Hidden, cl::init(990000), cl::ZeroOrMore, cl::desc("A count is hot if it exceeds the minimum count to" " reach this percentile of total counts.")) ("profile-summary-cutoff-hot" , cl::Hidden , cl::init(990000) , cl::ZeroOrMore , cl::desc("A count is hot if it exceeds the minimum count to" " reach this percentile of total counts."))
Referenced by llvm::ProfileSummaryBuilder::getHotCountThreshold().
ProfileSummaryHotCount
cl::opt<int> ProfileSummaryHotCount("profile-summary-hot-count", cl::ReallyHidden, cl::ZeroOrMore, cl::desc("A fixed hot count that overrides the count derived from" " profile-summary-cutoff-hot")) ("profile-summary-hot-count" , cl::ReallyHidden , cl::ZeroOrMore , cl::desc("A fixed hot count that overrides the count derived from" " profile-summary-cutoff-hot"))
Referenced by llvm::ProfileSummaryBuilder::getHotCountThreshold().
ProfileSummaryHugeWorkingSetSizeThreshold
cl::opt<unsigned> ProfileSummaryHugeWorkingSetSizeThreshold("profile-summary-huge-working-set-size-threshold", cl::Hidden, cl::init(15000), cl::ZeroOrMore, cl::desc("The code working set size is considered huge if the number of" " blocks required to reach the -profile-summary-cutoff-hot" " percentile exceeds this count.")) ("profile-summary-huge-working-set-size-threshold" , cl::Hidden , cl::init(15000) , cl::ZeroOrMore , cl::desc("The code working set size is considered huge if the number of" " blocks required to reach the -profile-summary-cutoff-hot" " percentile exceeds this count."))
ProfileSummaryLargeWorkingSetSizeThreshold
cl::opt<unsigned> ProfileSummaryLargeWorkingSetSizeThreshold("profile-summary-large-working-set-size-threshold", cl::Hidden, cl::init(12500), cl::ZeroOrMore, cl::desc("The code working set size is considered large if the number of" " blocks required to reach the -profile-summary-cutoff-hot" " percentile exceeds this count.")) ("profile-summary-large-working-set-size-threshold" , cl::Hidden , cl::init(12500) , cl::ZeroOrMore , cl::desc("The code working set size is considered large if the number of" " blocks required to reach the -profile-summary-cutoff-hot" " percentile exceeds this count."))
UseContextLessSummary
cl::opt<bool> UseContextLessSummary("profile-summary-contextless", cl::Hidden, cl::init(false), cl::ZeroOrMore, cl::desc("Merge context profiles before calculating thresholds.")) ("profile-summary-contextless" , cl::Hidden , cl::init(false) , cl::ZeroOrMore , cl::desc("Merge context profiles before calculating thresholds."))
Referenced by llvm::SampleProfileSummaryBuilder::computeSummaryForProfiles().