LLVM: llvm::ConstantExprKeyType Struct Reference
llvm::ConstantExprKeyType Struct Reference
#include "IR/ConstantsContext.h"
Public Types
using TypeClass = ConstantInfo< ConstantExpr >::TypeClass
Public Member Functions
ConstantExprKeyType (unsigned Opcode, ArrayRef< Constant * > Ops, unsigned short SubclassData=0, unsigned short SubclassOptionalData=0, ArrayRef< unsigned > Indexes=None, ArrayRef< int > ShuffleMask=None, Type *ExplicitTy=nullptr)
ConstantExprKeyType (ArrayRef< Constant * > Operands, const ConstantExpr *CE)
ConstantExprKeyType (const ConstantExpr *CE, SmallVectorImpl< Constant * > &Storage)
bool operator== (const ConstantExprKeyType &X) const
bool operator== (const ConstantExpr *CE) const
unsigned getHash () const
ConstantExpr * create (TypeClass *Ty) const
Detailed Description
Definition at line 504 of file ConstantsContext.h.
Member Typedef Documentation
TypeClass
using llvm::ConstantExprKeyType::TypeClass = ConstantInfo<ConstantExpr>::TypeClass
Definition at line 599 of file ConstantsContext.h.
Constructor & Destructor Documentation
ConstantExprKeyType() [1/3]
llvm::ConstantExprKeyType::ConstantExprKeyType (unsigned Opcode, ArrayRef< Constant * > Ops, unsigned short SubclassData = 0, unsigned short SubclassOptionalData = 0, ArrayRef< unsigned > Indexes = None, ArrayRef< int > ShuffleMask = None, Type * ExplicitTy = nullptr) inline
Definition at line 533 of file ConstantsContext.h.
ConstantExprKeyType() [2/3]
llvm::ConstantExprKeyType::ConstantExprKeyType (ArrayRef< Constant * > Operands, const ConstantExpr * CE) inline
Definition at line 543 of file ConstantsContext.h.
ConstantExprKeyType() [3/3]
llvm::ConstantExprKeyType::ConstantExprKeyType (const ConstantExpr * CE, SmallVectorImpl< Constant * > & Storage) inline
Definition at line 550 of file ConstantsContext.h.
References assert(), E, llvm::SmallVectorBase< Size_T >::empty(), I, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Member Function Documentation
create()
ConstantExpr* llvm::ConstantExprKeyType::create (TypeClass * Ty) const inline
Definition at line 601 of file ConstantsContext.h.
References llvm::GetElementPtrConstantExpr::Create(), llvm::Instruction::isCast(), llvm_unreachable, llvm::MCID::Select, and llvm::ArrayRef< T >::slice().
getHash()
unsigned llvm::ConstantExprKeyType::getHash () const inline
Definition at line 591 of file ConstantsContext.h.
References llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), llvm::hash_combine(), and llvm::hash_combine_range().
operator==() [1/2]
bool llvm::ConstantExprKeyType::operator== (const ConstantExpr * CE) const inline
Definition at line 570 of file ConstantsContext.h.
References E, I, and llvm::ArrayRef< T >::size().
operator==() [2/2]
bool llvm::ConstantExprKeyType::operator== (const ConstantExprKeyType & X) const inline
Definition at line 563 of file ConstantsContext.h.
References X.
The documentation for this struct was generated from the following file:
lib/IR/ConstantsContext.h