LLVM: llvm::UnsignedDivisonByConstantInfo Struct Reference
llvm::UnsignedDivisonByConstantInfo Struct Reference
Magic data for optimising unsigned division by a constant.
#include "llvm/Support/DivisionByConstantInfo.h"
Static Public Member Functions
static UnsignedDivisonByConstantInfo get (const APInt &D, unsigned LeadingZeros=0)
Calculate the magic numbers required to implement an unsigned integer division by a constant as a sequence of multiplies, adds and shifts.
Public Attributes
APInt Magic
magic number
bool IsAdd
add indicator
unsigned ShiftAmount
shift amount
Detailed Description
Magic data for optimising unsigned division by a constant.
Definition at line 28 of file DivisionByConstantInfo.h.
Member Function Documentation
get()
UnsignedDivisonByConstantInfo UnsignedDivisonByConstantInfo::get (const APInt & D, unsigned LeadingZeros = 0) static
Calculate the magic numbers required to implement an unsigned integer division by a constant as a sequence of multiplies, adds and shifts.
Requires that the divisor not be 0. Taken from "Hacker's Delight", Henry S. Warren, Jr., chapter 10. LeadingZeros can be used to simplify the calculation if the upper bits of the divided value are known zero.
Definition at line 66 of file DivisionByConstantInfo.cpp.
References D, llvm::APInt::getAllOnes(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), IsAdd, llvm::APInt::lshr(), Magic, NC, P, R2, ShiftAmount, llvm::APInt::udiv(), llvm::APInt::uge(), and llvm::APInt::ult().
Referenced by llvm::TargetLowering::BuildUDIV(), and llvm::CombinerHelper::buildUDivUsingMul().
Member Data Documentation
IsAdd
bool llvm::UnsignedDivisonByConstantInfo::IsAdd
add indicator
Definition at line 32 of file DivisionByConstantInfo.h.
Referenced by llvm::TargetLowering::BuildUDIV(), llvm::CombinerHelper::buildUDivUsingMul(), and get().
Magic
APInt llvm::UnsignedDivisonByConstantInfo::Magic
magic number
Definition at line 31 of file DivisionByConstantInfo.h.
Referenced by llvm::TargetLowering::BuildUDIV(), llvm::CombinerHelper::buildUDivUsingMul(), and get().
ShiftAmount
unsigned llvm::UnsignedDivisonByConstantInfo::ShiftAmount
shift amount
Definition at line 33 of file DivisionByConstantInfo.h.
Referenced by llvm::TargetLowering::BuildUDIV(), llvm::CombinerHelper::buildUDivUsingMul(), and get().
The documentation for this struct was generated from the following files:
include/llvm/Support/DivisionByConstantInfo.h
lib/Support/DivisionByConstantInfo.cpp