LLVM: AAIsDeadFloating Struct Reference
AAIsDeadFloating Struct Reference
Public Member Functions
AAIsDeadFloating (const IRPosition &IRP, Attributor &A)
void initialize (Attributor &A) override
See AbstractAttribute::initialize(...).
bool isDeadStore (Attributor &A, StoreInst &SI)
ChangeStatus updateImpl (Attributor &A) override
See AbstractAttribute::updateImpl(...).
ChangeStatus manifest (Attributor &A) override
See AbstractAttribute::manifest(...).
void trackStatistics () const override
See AbstractAttribute::trackStatistics()
Public Member Functions inherited from AAIsDeadValueImpl
AAIsDeadValueImpl (const IRPosition &IRP, Attributor &A)
bool isAssumedDead () const override
See AAIsDead::isAssumedDead().
bool isKnownDead () const override
See AAIsDead::isKnownDead().
bool isAssumedDead (const BasicBlock *BB) const override
See AAIsDead::isAssumedDead(BasicBlock *).
bool isKnownDead (const BasicBlock *BB) const override
See AAIsDead::isKnownDead(BasicBlock *).
bool isAssumedDead (const Instruction *I) const override
See AAIsDead::isAssumedDead(Instruction *I).
bool isKnownDead (const Instruction *I) const override
See AAIsDead::isKnownDead(Instruction *I).
const std::string getAsStr () const override
See AbstractAttribute::getAsStr().
bool areAllUsesAssumedDead (Attributor &A, Value &V)
Check if all uses are assumed dead.
bool isAssumedSideEffectFree (Attributor &A, Instruction *I)
Determine if I is assumed to be side-effect free.
Public Member Functions inherited from llvm::AAIsDead
AAIsDead (const IRPosition &IRP, Attributor &A)
virtual bool isEdgeDead (const BasicBlock *From, const BasicBlock *To) const
Return if the edge from From BB to To BB is assumed dead.
const std::string getName () const override
See AbstractAttribute::getName()
const char * getIdAddr () const override
See AbstractAttribute::getIdAddr()
Public Member Functions inherited from llvm::StateWrapper< BitIntegerState< uint8_t, 3, 0 >, AbstractAttribute >
StateWrapper (const IRPosition &IRP, Ts... Args)
StateType & getState () override
See AbstractAttribute::getState(...).
const StateType & getState () const override
See AbstractAttribute::getState(...).
Public Member Functions inherited from llvm::AbstractAttribute
AbstractAttribute (const IRPosition &IRP)
virtual ~AbstractAttribute ()=default
Virtual destructor.
virtual bool isQueryAA () const
A query AA is always scheduled as long as we do updates because it does lazy computation that cannot be determined to be done from the outside.
const IRPosition & getIRPosition () const
Return an IR position, see struct IRPosition.
IRPosition & getIRPosition ()
void print (raw_ostream &OS) const override
Helper functions, for debug purposes only.
virtual void printWithDeps (raw_ostream &OS) const
void dump () const
Public Member Functions inherited from llvm::IRPosition
IRPosition ()
Default constructor available to create invalid positions implicitly.
bool operator== (const IRPosition &RHS) const
bool operator!= (const IRPosition &RHS) const
Value & getAnchorValue () const
Return the value this abstract attribute is anchored with.
Function * getAssociatedFunction () const
Return the associated function, if any.
Argument * getAssociatedArgument () const
Return the associated argument, if any.
bool isFnInterfaceKind () const
Return true if the position refers to a function interface, that is the function scope, the function return, or an argument.
Function * getAnchorScope () const
Return the Function surrounding the anchor value.
Instruction * getCtxI () const
Return the context instruction, if any.
Value & getAssociatedValue () const
Return the value this abstract attribute is associated with.
Type * getAssociatedType () const
Return the type this abstract attribute is associated with.
int getCalleeArgNo () const
Return the callee argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
int getCallSiteArgNo () const
Return the call site argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
unsigned getAttrIdx () const
Return the index in the attribute list for this position.
Kind getPositionKind () const
Return the associated position kind.
bool hasAttr (ArrayRef< Attribute::AttrKind > AKs, bool IgnoreSubsumingPositions=false, Attributor *A=nullptr) const
TODO: Figure out if the attribute related helper functions should live here or somewhere else.
void getAttrs (ArrayRef< Attribute::AttrKind > AKs, SmallVectorImpl< Attribute > &Attrs, bool IgnoreSubsumingPositions=false, Attributor *A=nullptr) const
Return the attributes of any kind in AKs existing in the IR at a position that will affect this one.
void removeAttrs (ArrayRef< Attribute::AttrKind > AKs) const
Remove the attribute of kind AKs existing in the IR at this position.
bool isAnyCallSitePosition () const
bool isArgumentPosition () const
Return true if the position is an argument or call site argument.
IRPosition stripCallBaseContext () const
Return the same position without the call base context.
const CallBaseContext * getCallBaseContext () const
Get the call base context from the position.
bool hasCallBaseContext () const
Check if the position has any call base context.
operator void * () const
}
Public Member Functions inherited from llvm::AADepGraphNode
virtual ~AADepGraphNode ()=default
aaiterator begin ()
aaiterator end ()
iterator child_begin ()
iterator child_end ()
TinyPtrVector< DepTy > & getDeps ()
Public Member Functions inherited from llvm::BitIntegerState< base_ty, BestState, WorstState >
bool isKnown (base_t BitsEncoding) const
Return true if the bits set in BitsEncoding are "known bits".
bool isAssumed (base_t BitsEncoding) const
Return true if the bits set in BitsEncoding are "assumed bits".
BitIntegerState & addKnownBits (base_t Bits)
Add the bits in BitsEncoding to the "known bits".
BitIntegerState & removeAssumedBits (base_t BitsEncoding)
Remove the bits in BitsEncoding from the "assumed bits" if not known.
BitIntegerState & removeKnownBits (base_t BitsEncoding)
Remove the bits in BitsEncoding from the "known bits".
BitIntegerState & intersectAssumedBits (base_t BitsEncoding)
Keep only "assumed bits" also set in BitsEncoding but all known ones.
Public Member Functions inherited from llvm::IntegerStateBase< uint32_t, ~uint32_t(0), 0 >
IntegerStateBase ()=default
IntegerStateBase (base_t Assumed)
bool isValidState () const override
See AbstractState::isValidState() NOTE: For now we simply pretend that the worst possible state is invalid.
bool isAtFixpoint () const override
See AbstractState::isAtFixpoint()
ChangeStatus indicateOptimisticFixpoint () override
See AbstractState::indicateOptimisticFixpoint(...)
ChangeStatus indicatePessimisticFixpoint () override
See AbstractState::indicatePessimisticFixpoint(...)
base_t getKnown () const
Return the known state encoding.
base_t getAssumed () const
Return the assumed state encoding.
bool operator== (const IntegerStateBase< base_t, BestState, WorstState > &R) const
Equality for IntegerStateBase.
bool operator!= (const IntegerStateBase< base_t, BestState, WorstState > &R) const
Inequality for IntegerStateBase.
void operator^= (const IntegerStateBase< base_t, BestState, WorstState > &R)
"Clamp" this state with R.
void operator+= (const IntegerStateBase< base_t, BestState, WorstState > &R)
"Clamp" this state with R.
void operator|= (const IntegerStateBase< base_t, BestState, WorstState > &R)
void operator&= (const IntegerStateBase< base_t, BestState, WorstState > &R)
Public Member Functions inherited from llvm::AbstractState
virtual ~AbstractState ()=default
Additional Inherited Members
Public Types inherited from llvm::AAIsDead
enum { HAS_NO_EFFECT = 1 << 0 , IS_REMOVABLE = 1 << 1 , IS_DEAD = HAS_NO_EFFECT | IS_REMOVABLE }
State encoding bits. A set bit in the state means the property holds.
using Base = StateWrapper< BitIntegerState< uint8_t, 3, 0 >, AbstractAttribute >
Public Types inherited from llvm::StateWrapper< BitIntegerState< uint8_t, 3, 0 >, AbstractAttribute >
using StateType = BitIntegerState< uint8_t, 3, 0 >
Provide static access to the type of the state.
Public Types inherited from llvm::AbstractAttribute
using StateType = AbstractState
Public Types inherited from llvm::IRPosition
enum Kind : char {
IRP_INVALID , IRP_FLOAT , IRP_RETURNED , IRP_CALL_SITE_RETURNED ,
IRP_FUNCTION , IRP_CALL_SITE , IRP_ARGUMENT , IRP_CALL_SITE_ARGUMENT
}
The positions we distinguish in the IR.
using CallBaseContext = CallBase
Public Types inherited from llvm::AADepGraphNode
using DepTy = PointerIntPair< AADepGraphNode *, 1 >
using iterator = mapped_iterator< TinyPtrVector< DepTy >::iterator, decltype(&DepGetVal)>
using aaiterator = mapped_iterator< TinyPtrVector< DepTy >::iterator, decltype(&DepGetValAA)>
Public Types inherited from llvm::BitIntegerState< base_ty, BestState, WorstState >
using base_t = base_ty
Public Types inherited from llvm::IntegerStateBase< uint32_t, ~uint32_t(0), 0 >
using base_t = uint32_t
Static Public Member Functions inherited from llvm::AAIsDead
static AAIsDead & createForPosition (const IRPosition &IRP, Attributor &A)
Create an abstract attribute view for the position IRP.
static bool mayCatchAsynchronousExceptions (const Function &F)
Determine if F might catch asynchronous exceptions.
static bool classof (const AbstractAttribute *AA)
This function should return true if the type of the AA is AAIsDead.
Static Public Member Functions inherited from llvm::AbstractAttribute
static bool classof (const AADepGraphNode *DGN)
This function is used to identify if an DGN is of type AbstractAttribute so that the dyn_cast and cast can use such information to cast an AADepGraphNode to an AbstractAttribute.
Static Public Member Functions inherited from llvm::IRPosition
static const IRPosition value (const Value &V, const CallBaseContext *CBContext=nullptr)
Create a position describing the value of V.
static const IRPosition inst (const Instruction &I, const CallBaseContext *CBContext=nullptr)
Create a position describing the instruction I.
static const IRPosition function (const Function &F, const CallBaseContext *CBContext=nullptr)
Create a position describing the function scope of F.
static const IRPosition returned (const Function &F, const CallBaseContext *CBContext=nullptr)
Create a position describing the returned value of F.
static const IRPosition argument (const Argument &Arg, const CallBaseContext *CBContext=nullptr)
Create a position describing the argument Arg.
static const IRPosition callsite_function (const CallBase &CB)
Create a position describing the function scope of CB.
static const IRPosition callsite_returned (const CallBase &CB)
Create a position describing the returned value of CB.
static const IRPosition callsite_argument (const CallBase &CB, unsigned ArgNo)
Create a position describing the argument of CB at position ArgNo.
static const IRPosition callsite_argument (AbstractCallSite ACS, unsigned ArgNo)
Create a position describing the argument of ACS at position ArgNo.
static const IRPosition function_scope (const IRPosition &IRP, const CallBaseContext *CBContext=nullptr)
Create a position with function scope matching the "context" of IRP.
Static Public Member Functions inherited from llvm::IntegerStateBase< uint32_t, ~uint32_t(0), 0 >
static constexpr base_t getBestState ()
Return the best possible representable state.
static constexpr base_t getBestState (const IntegerStateBase &)
static constexpr base_t getWorstState ()
Return the worst possible representable state.
static constexpr base_t getWorstState (const IntegerStateBase &)
Static Public Attributes inherited from llvm::AAIsDead
static const char ID = 0
Unique ID (due to the unique address)
Static Public Attributes inherited from llvm::IRPosition
static const IRPosition EmptyKey
Special DenseMap key values.
static const IRPosition TombstoneKey
Protected Member Functions inherited from llvm::AAIsDead
template<typename T >
bool isLiveInstSet (T begin, T end) const
This method is used to check if at least one instruction in a collection of instructions is live.
Protected Member Functions inherited from llvm::AbstractAttribute
ChangeStatus update (Attributor &A)
Hook for the Attributor to trigger an update of the internal state.
Protected Member Functions inherited from llvm::AADepGraphNode
operator AbstractAttribute * ()
Protected Member Functions inherited from llvm::IntegerStateBase< uint32_t, ~uint32_t(0), 0 >
virtual void handleNewAssumedValue (base_t Value)=0
Handle a new assumed value Value. Subtype dependent.
virtual void handleNewKnownValue (base_t Value)=0
Handle a new known value Value. Subtype dependent.
virtual void joinOR (base_t AssumedValue, base_t KnownValue)=0
Handle a value Value. Subtype dependent.
virtual void joinAND (base_t AssumedValue, base_t KnownValue)=0
Handle a new assumed value Value. Subtype dependent.
Static Protected Member Functions inherited from llvm::AADepGraphNode
static AADepGraphNode * DepGetVal (DepTy &DT)
static AbstractAttribute * DepGetValAA (DepTy &DT)
Protected Attributes inherited from llvm::AADepGraphNode
TinyPtrVector< DepTy > Deps
Set of dependency graph nodes which should be updated if this one is updated.
Protected Attributes inherited from llvm::IntegerStateBase< uint32_t, ~uint32_t(0), 0 >
base_t Known
The known state encoding in an integer of type base_t.
base_t Assumed
The assumed state encoding in an integer of type base_t.
Detailed Description
Definition at line 3519 of file AttributorAttributes.cpp.
Constructor & Destructor Documentation
AAIsDeadFloating()
AAIsDeadFloating::AAIsDeadFloating (const IRPosition & IRP, Attributor & A) inline
Definition at line 3520 of file AttributorAttributes.cpp.
Member Function Documentation
initialize()
void AAIsDeadFloating::initialize (Attributor & A) inline override virtual
See AbstractAttribute::initialize(...).
Reimplemented from llvm::AbstractAttribute.
Reimplemented in AAIsDeadCallSiteReturned, and AAIsDeadArgument.
Definition at line 3524 of file AttributorAttributes.cpp.
References I.
isDeadStore()
bool AAIsDeadFloating::isDeadStore (Attributor & A, StoreInst & SI) inline
Definition at line 3539 of file AttributorAttributes.cpp.
References llvm::all_of(), llvm::AA::getPotentialCopiesOfStoredValue(), SI, and llvm::IRPosition::value().
manifest()
ChangeStatus AAIsDeadFloating::manifest (Attributor & A) inline override virtual
See AbstractAttribute::manifest(...).
Reimplemented from llvm::AbstractAttribute.
Reimplemented in AAIsDeadArgument.
Definition at line 3571 of file AttributorAttributes.cpp.
References C, llvm::CHANGED, llvm::UndefValue::get(), llvm::Value::getType(), I, llvm::UNCHANGED, and llvm::Value::use_empty().
Referenced by AAIsDeadArgument::manifest().
trackStatistics()
void AAIsDeadFloating::trackStatistics () const inline override virtual
See AbstractAttribute::trackStatistics()
Implements llvm::AbstractAttribute.
Reimplemented in AAIsDeadCallSiteReturned, and AAIsDeadArgument.
Definition at line 3602 of file AttributorAttributes.cpp.
References IsDead, and STATS_DECLTRACK_FLOATING_ATTR.
updateImpl()
ChangeStatus AAIsDeadFloating::updateImpl (Attributor & A) inline override virtual
See AbstractAttribute::updateImpl(...).
Implements llvm::AbstractAttribute.
Reimplemented in AAIsDeadCallSiteReturned.
Definition at line 3556 of file AttributorAttributes.cpp.
References I, SI, and llvm::UNCHANGED.
The documentation for this struct was generated from the following file:
lib/Transforms/IPO/AttributorAttributes.cpp