LLVM: llvm::PotentialValuesState< MemberTy, KeyInfo > Struct Template Reference
llvm::PotentialValuesState< MemberTy, KeyInfo > Struct Template Reference
A class for a set state.
#include "llvm/Transforms/IPO/Attributor.h"
Public Types
using SetTy = DenseSet< MemberTy, KeyInfo >
Public Member Functions
PotentialValuesState ()
PotentialValuesState (bool IsValid)
bool isValidState () const override
See AbstractState::isValidState(...)
bool isAtFixpoint () const override
See AbstractState::isAtFixpoint(...)
ChangeStatus indicatePessimisticFixpoint () override
See AbstractState::indicatePessimisticFixpoint(...)
ChangeStatus indicateOptimisticFixpoint () override
See AbstractState::indicateOptimisticFixpoint(...)
PotentialValuesState & getAssumed ()
Return the assumed state.
const PotentialValuesState & getAssumed () const
const SetTy & getAssumedSet () const
Return this set.
bool undefIsContained () const
Returns whether this state contains an undef value or not.
bool operator== (const PotentialValuesState &RHS) const
void unionAssumed (const MemberTy &C)
Union assumed set with the passed value.
void unionAssumed (const PotentialValuesState &PVS)
Union assumed set with assumed set of the passed state PVS.
void unionAssumedWithUndef ()
Union assumed set with an undef value.
PotentialValuesState operator^= (const PotentialValuesState &PVS)
"Clamp" this state with PVS.
PotentialValuesState operator&= (const PotentialValuesState &PVS)
Public Member Functions inherited from llvm::AbstractState
virtual ~AbstractState ()=default
Static Public Member Functions
static PotentialValuesState getBestState ()
Return empty set as the best state of potential values.
static PotentialValuesState getBestState (PotentialValuesState &PVS)
static PotentialValuesState getWorstState ()
Return full set as the worst state of potential values.
Static Public Attributes
static unsigned MaxPotentialValues = 0
Maximum number of potential values to be tracked.
Detailed Description
template<typename MemberTy, typename KeyInfo = DenseMapInfo<MemberTy>>
struct llvm::PotentialValuesState< MemberTy, KeyInfo >
A class for a set state.
The assumed boolean state indicates whether the corresponding set is full set or not. If the assumed state is false, this is the worst state. The worst state (invalid state) of set of potential values is when the set contains every possible value (i.e. we cannot in any way limit the value that the target position can take). That never happens naturally, we only force it. As for the conditions under which we force it, see AAPotentialValues.
Definition at line 4192 of file Attributor.h.
Member Typedef Documentation
SetTy
template<typename MemberTy , typename KeyInfo = DenseMapInfo<MemberTy>> using llvm::PotentialValuesState< MemberTy, KeyInfo >::SetTy = DenseSet<MemberTy, KeyInfo>
Definition at line 4193 of file Attributor.h.
Constructor & Destructor Documentation
PotentialValuesState() [1/2]
template<typename MemberTy , typename KeyInfo = DenseMapInfo<MemberTy>> llvm::PotentialValuesState< MemberTy, KeyInfo >::PotentialValuesState () inline
Definition at line 4195 of file Attributor.h.
Referenced by llvm::PotentialValuesState< MemberTy, KeyInfo >::getBestState(), and llvm::PotentialValuesState< MemberTy, KeyInfo >::getWorstState().
PotentialValuesState() [2/2]
template<typename MemberTy , typename KeyInfo = DenseMapInfo<MemberTy>> llvm::PotentialValuesState< MemberTy, KeyInfo >::PotentialValuesState (bool IsValid) inline
Definition at line 4197 of file Attributor.h.
Member Function Documentation
getAssumed() [1/2]
template<typename MemberTy , typename KeyInfo = DenseMapInfo<MemberTy>> PotentialValuesState& llvm::PotentialValuesState< MemberTy, KeyInfo >::getAssumed () inline
Return the assumed state.
Definition at line 4217 of file Attributor.h.
Referenced by AAPotentialValuesCallSiteArgument::updateImpl().
getAssumed() [2/2]
template<typename MemberTy , typename KeyInfo = DenseMapInfo<MemberTy>> const PotentialValuesState& llvm::PotentialValuesState< MemberTy, KeyInfo >::getAssumed () const inline
Definition at line 4218 of file Attributor.h.
getAssumedSet()
template<typename MemberTy , typename KeyInfo = DenseMapInfo<MemberTy>> const SetTy& llvm::PotentialValuesState< MemberTy, KeyInfo >::getAssumedSet () const inline
Return this set.
We should check whether this set is valid or not by isValidState() before calling this function.
Definition at line 4222 of file Attributor.h.
References assert(), and llvm::PotentialValuesState< MemberTy, KeyInfo >::isValidState().
Referenced by llvm::AAPotentialValues::getAssumedConstantInt(), and llvm::operator<<().
getBestState() [1/2]
template<typename MemberTy , typename KeyInfo = DenseMapInfo<MemberTy>> static PotentialValuesState llvm::PotentialValuesState< MemberTy, KeyInfo >::getBestState () inline static
Return empty set as the best state of potential values.
Definition at line 4248 of file Attributor.h.
References llvm::PotentialValuesState< MemberTy, KeyInfo >::PotentialValuesState().
Referenced by llvm::PotentialValuesState< MemberTy, KeyInfo >::getBestState().
getBestState() [2/2]
template<typename MemberTy , typename KeyInfo = DenseMapInfo<MemberTy>> static PotentialValuesState llvm::PotentialValuesState< MemberTy, KeyInfo >::getBestState (PotentialValuesState< MemberTy, KeyInfo > & PVS) inline static
Definition at line 4252 of file Attributor.h.
References llvm::PotentialValuesState< MemberTy, KeyInfo >::getBestState().
getWorstState()
template<typename MemberTy , typename KeyInfo = DenseMapInfo<MemberTy>> static PotentialValuesState llvm::PotentialValuesState< MemberTy, KeyInfo >::getWorstState () inline static
Return full set as the worst state of potential values.
Definition at line 4257 of file Attributor.h.
References llvm::PotentialValuesState< MemberTy, KeyInfo >::PotentialValuesState().
indicateOptimisticFixpoint()
template<typename MemberTy , typename KeyInfo = DenseMapInfo<MemberTy>> ChangeStatus llvm::PotentialValuesState< MemberTy, KeyInfo >::indicateOptimisticFixpoint () inline override virtual
See AbstractState::indicateOptimisticFixpoint(...)
Implements llvm::AbstractState.
Definition at line 4212 of file Attributor.h.
References llvm::IntegerStateBase< base_ty, BestState, WorstState >::indicateOptimisticFixpoint().
indicatePessimisticFixpoint()
template<typename MemberTy , typename KeyInfo = DenseMapInfo<MemberTy>> ChangeStatus llvm::PotentialValuesState< MemberTy, KeyInfo >::indicatePessimisticFixpoint () inline override virtual
See AbstractState::indicatePessimisticFixpoint(...)
Implements llvm::AbstractState.
Definition at line 4207 of file Attributor.h.
References llvm::IntegerStateBase< base_ty, BestState, WorstState >::indicatePessimisticFixpoint().
isAtFixpoint()
template<typename MemberTy , typename KeyInfo = DenseMapInfo<MemberTy>> bool llvm::PotentialValuesState< MemberTy, KeyInfo >::isAtFixpoint () const inline override virtual
See AbstractState::isAtFixpoint(...)
Implements llvm::AbstractState.
Definition at line 4204 of file Attributor.h.
References llvm::IntegerStateBase< base_ty, BestState, WorstState >::isAtFixpoint().
isValidState()
template<typename MemberTy , typename KeyInfo = DenseMapInfo<MemberTy>> bool llvm::PotentialValuesState< MemberTy, KeyInfo >::isValidState () const inline override virtual
See AbstractState::isValidState(...)
Implements llvm::AbstractState.
Definition at line 4201 of file Attributor.h.
References llvm::IntegerStateBase< base_ty, BestState, WorstState >::isValidState().
Referenced by llvm::AAPotentialValues::getAssumedConstantInt(), llvm::PotentialValuesState< MemberTy, KeyInfo >::getAssumedSet(), llvm::operator<<(), llvm::PotentialValuesState< MemberTy, KeyInfo >::operator==(), llvm::PotentialValuesState< MemberTy, KeyInfo >::undefIsContained(), and AAPotentialValuesFloating::updateWithSelectInst().
operator&=()
template<typename MemberTy , typename KeyInfo = DenseMapInfo<MemberTy>> PotentialValuesState llvm::PotentialValuesState< MemberTy, KeyInfo >::operator&= (const PotentialValuesState< MemberTy, KeyInfo > & PVS) inline
Definition at line 4277 of file Attributor.h.
References llvm::PotentialValuesState< MemberTy, KeyInfo >::unionAssumed().
operator==()
template<typename MemberTy , typename KeyInfo = DenseMapInfo<MemberTy>> bool llvm::PotentialValuesState< MemberTy, KeyInfo >::operator== (const PotentialValuesState< MemberTy, KeyInfo > & RHS) const inline
Definition at line 4233 of file Attributor.h.
References llvm::PotentialValuesState< MemberTy, KeyInfo >::isValidState(), RHS, and llvm::PotentialValuesState< MemberTy, KeyInfo >::undefIsContained().
operator^=()
template<typename MemberTy , typename KeyInfo = DenseMapInfo<MemberTy>> PotentialValuesState llvm::PotentialValuesState< MemberTy, KeyInfo >::operator^= (const PotentialValuesState< MemberTy, KeyInfo > & PVS) inline
"Clamp" this state with PVS.
Definition at line 4271 of file Attributor.h.
References llvm::PotentialValuesState< MemberTy, KeyInfo >::unionAssumed().
undefIsContained()
template<typename MemberTy , typename KeyInfo = DenseMapInfo<MemberTy>> bool llvm::PotentialValuesState< MemberTy, KeyInfo >::undefIsContained () const inline
Returns whether this state contains an undef value or not.
Definition at line 4228 of file Attributor.h.
References assert(), and llvm::PotentialValuesState< MemberTy, KeyInfo >::isValidState().
Referenced by llvm::AAPotentialValues::getAssumedConstantInt(), llvm::operator<<(), llvm::PotentialValuesState< MemberTy, KeyInfo >::operator==(), and AAPotentialValuesFloating::updateWithSelectInst().
unionAssumed() [1/2]
template<typename MemberTy , typename KeyInfo = DenseMapInfo<MemberTy>> void llvm::PotentialValuesState< MemberTy, KeyInfo >::unionAssumed (const MemberTy & C) inline
Union assumed set with the passed value.
Definition at line 4262 of file Attributor.h.
References C.
Referenced by llvm::PotentialValuesState< MemberTy, KeyInfo >::operator&=(), and llvm::PotentialValuesState< MemberTy, KeyInfo >::operator^=().
unionAssumed() [2/2]
template<typename MemberTy , typename KeyInfo = DenseMapInfo<MemberTy>> void llvm::PotentialValuesState< MemberTy, KeyInfo >::unionAssumed (const PotentialValuesState< MemberTy, KeyInfo > & PVS) inline
Union assumed set with assumed set of the passed state PVS.
Definition at line 4265 of file Attributor.h.
unionAssumedWithUndef()
template<typename MemberTy , typename KeyInfo = DenseMapInfo<MemberTy>> void llvm::PotentialValuesState< MemberTy, KeyInfo >::unionAssumedWithUndef () inline
Union assumed set with an undef value.
Definition at line 4268 of file Attributor.h.
Member Data Documentation
MaxPotentialValues
unsigned llvm::PotentialConstantIntValuesState::MaxPotentialValues = 0 static
Maximum number of potential values to be tracked.
This is set by -attributor-max-potential-values command line option
Definition at line 4245 of file Attributor.h.
The documentation for this struct was generated from the following files:
include/llvm/Transforms/IPO/Attributor.h
lib/Transforms/IPO/AttributorAttributes.cpp