LLVM: AAMemoryLocationCallSite Struct Reference
AAMemoryLocationCallSite Struct Reference final
AAMemoryLocation attribute for call sites.
Public Member Functions
AAMemoryLocationCallSite (const IRPosition &IRP, Attributor &A)
void initialize (Attributor &A) override
See AbstractAttribute::initialize(...).
ChangeStatus updateImpl (Attributor &A) override
See AbstractAttribute::updateImpl(...).
void trackStatistics () const override
See AbstractAttribute::trackStatistics()
Public Member Functions inherited from AAMemoryLocationImpl
AAMemoryLocationImpl (const IRPosition &IRP, Attributor &A)
~AAMemoryLocationImpl ()
void getDeducedAttributes (LLVMContext &Ctx, SmallVectorImpl< Attribute > &Attrs) const override
See AbstractAttribute::getDeducedAttributes(...).
ChangeStatus manifest (Attributor &A) override
See AbstractAttribute::manifest(...).
bool checkForAllAccessesToMemoryKind (function_ref< bool(const Instruction *, const Value *, AccessKind, MemoryLocationsKind)> Pred, MemoryLocationsKind RequestedMLK) const override
See AAMemoryLocation::checkForAllAccessesToMemoryKind(...).
ChangeStatus indicatePessimisticFixpoint () override
Public Member Functions inherited from llvm::AAMemoryLocation
AAMemoryLocation (const IRPosition &IRP, Attributor &A)
bool isKnownReadNone () const
Return true if we know that the associated functions has no observable accesses.
bool isAssumedReadNone () const
Return true if we assume that the associated functions has no observable accesses.
bool isKnowStackOnly () const
Return true if we know that the associated functions has at most local/stack accesses.
bool isAssumedStackOnly () const
Return true if we assume that the associated functions has at most local/stack accesses.
bool isKnownInaccessibleMemOnly () const
Return true if we know that the underlying value will only access inaccesible memory only (see Attribute::InaccessibleMemOnly).
bool isAssumedInaccessibleMemOnly () const
Return true if we assume that the underlying value will only access inaccesible memory only (see Attribute::InaccessibleMemOnly).
bool isKnownArgMemOnly () const
Return true if we know that the underlying value will only access argument pointees (see Attribute::ArgMemOnly).
bool isAssumedArgMemOnly () const
Return true if we assume that the underlying value will only access argument pointees (see Attribute::ArgMemOnly).
bool isKnownInaccessibleOrArgMemOnly () const
Return true if we know that the underlying value will only access inaccesible memory or argument pointees (see Attribute::InaccessibleOrArgMemOnly).
bool isAssumedInaccessibleOrArgMemOnly () const
Return true if we assume that the underlying value will only access inaccesible memory or argument pointees (see Attribute::InaccessibleOrArgMemOnly).
bool mayAccessArgMem () const
Return true if the underlying value may access memory through arguement pointers of the associated function, if any.
bool isAssumedSpecifiedMemOnly (MemoryLocationsKind MLK) const
Return true if only the memory locations specififed by MLK are assumed to be accessed by the associated function.
MemoryLocationsKind getAssumedNotAccessedLocation () const
Return the locations that are assumed to be not accessed by the associated function, if any.
const std::string getAsStr () const override
See AbstractState::getAsStr().
const std::string getName () const override
See AbstractAttribute::getName()
const char * getIdAddr () const override
See AbstractAttribute::getIdAddr()
Public Member Functions inherited from llvm::IRAttribute< Attribute::ReadNone, StateWrapper< BitIntegerState< uint32_t, 511 >, AbstractAttribute > >
IRAttribute (const IRPosition &IRP)
ChangeStatus manifest (Attributor &A) override
See AbstractAttribute::manifest(...).
Attribute::AttrKind getAttrKind () const
Return the kind that identifies the abstract attribute implementation.
Public Member Functions inherited from llvm::StateWrapper< StateTy, BaseType, Ts >
StateWrapper (const IRPosition &IRP, Ts... Args)
StateType & getState () override
See AbstractAttribute::getState(...).
const StateType & getState () const override
See AbstractAttribute::getState(...).
Additional Inherited Members
Public Types inherited from llvm::AAMemoryLocation
enum {
ALL_LOCATIONS = 0 , NO_LOCAL_MEM = 1 << 0 , NO_CONST_MEM = 1 << 1 , NO_GLOBAL_INTERNAL_MEM = 1 << 2 ,
NO_GLOBAL_EXTERNAL_MEM = 1 << 3 , NO_GLOBAL_MEM = NO_GLOBAL_INTERNAL_MEM | NO_GLOBAL_EXTERNAL_MEM , NO_ARGUMENT_MEM = 1 << 4 , NO_INACCESSIBLE_MEM = 1 << 5 ,
NO_MALLOCED_MEM = 1 << 6 , NO_UNKOWN_MEM = 1 << 7 , NO_LOCATIONS , VALID_STATE = NO_LOCATIONS + 1 ,
BEST_STATE = NO_LOCATIONS | VALID_STATE
}
Encoding of different locations that could be accessed by a memory access.
enum AccessKind { NONE = 0 , READ = 1 << 0 , WRITE = 1 << 1 , READ_WRITE = READ | WRITE }
Simple enum to distinguish read/write/read-write accesses.
using MemoryLocationsKind = StateType::base_t
Public Types inherited from llvm::StateWrapper< StateTy, BaseType, Ts >
using StateType = StateTy
Provide static access to the type of the state.
Static Public Member Functions inherited from AAMemoryLocationImpl
static void getKnownStateFromValue (Attributor &A, const IRPosition &IRP, BitIntegerState &State, bool IgnoreSubsumingPositions=false)
Return the memory behavior information encoded in the IR for IRP.
Static Public Member Functions inherited from llvm::AAMemoryLocation
static MemoryLocationsKind inverseLocation (MemoryLocationsKind Loc, bool AndLocalMem, bool AndConstMem)
Return the inverse of location Loc, thus for NO_XXX the return describes ONLY_XXX.
static std::string getMemoryLocationsAsStr (MemoryLocationsKind MLK)
Return the locations encoded by MLK as a readable string.
static AAMemoryLocation & createForPosition (const IRPosition &IRP, Attributor &A)
Create an abstract attribute view for the position IRP.
static bool classof (const AbstractAttribute *AA)
This function should return true if the type of the AA is AAMemoryLocation.
Static Public Attributes inherited from llvm::AAMemoryLocation
static const char ID = 0
Unique ID (due to the unique address)
Protected Types inherited from AAMemoryLocationImpl
using AccessSet = SmallSet< AccessInfo, 2, AccessInfo >
Mapping from single memory location kinds, e.g., LOCAL_MEM with the value of NO_LOCAL_MEM, to the accesses encountered for this memory kind.
Protected Member Functions inherited from AAMemoryLocationImpl
void categorizeArgumentPointerLocations (Attributor &A, CallBase &CB, AAMemoryLocation::StateType &AccessedLocs, bool &Changed)
Categorize the pointer arguments of CB that might access memory in AccessedLoc and update the state and access map accordingly.
AAMemoryLocation::MemoryLocationsKind categorizeAccessedLocations (Attributor &A, Instruction &I, bool &Changed)
Return the kind(s) of location that may be accessed by V.
AccessKind getAccessKindFromInst (const Instruction *I)
Return the access kind as determined by I.
void updateStateAndAccessesMap (AAMemoryLocation::StateType &State, MemoryLocationsKind MLK, const Instruction *I, const Value *Ptr, bool &Changed, AccessKind AK=READ_WRITE)
Update the state State and the AccessKind2Accesses given that I is an access of kind AK to a MLK memory location with the access pointer Ptr.
void categorizePtrValue (Attributor &A, const Instruction &I, const Value &Ptr, AAMemoryLocation::StateType &State, bool &Changed)
Determine the underlying locations kinds for Ptr, e.g., globals or arguments, and update the state and access map accordingly.
Protected Attributes inherited from AAMemoryLocationImpl
AccessSet * AccessKind2Accesses [llvm::CTLog2< VALID_STATE >()]
BumpPtrAllocator & Allocator
Used to allocate access sets.
Static Protected Attributes inherited from AAMemoryLocationImpl
static const Attribute::AttrKind AttrKinds [4]
The set of IR attributes AAMemoryLocation deals with.
Detailed Description
AAMemoryLocation attribute for call sites.
Definition at line 8034 of file AttributorAttributes.cpp.
Constructor & Destructor Documentation
AAMemoryLocationCallSite()
AAMemoryLocationCallSite::AAMemoryLocationCallSite (const IRPosition & IRP, Attributor & A) inline
Definition at line 8035 of file AttributorAttributes.cpp.
Member Function Documentation
initialize()
void AAMemoryLocationCallSite::initialize (Attributor & A) inline override virtual
See AbstractAttribute::initialize(...).
Reimplemented from AAMemoryLocationImpl.
Definition at line 8039 of file AttributorAttributes.cpp.
References F, and AAMemoryLocationImpl::initialize().
trackStatistics()
void AAMemoryLocationCallSite::trackStatistics () const inline override
See AbstractAttribute::trackStatistics()
Definition at line 8069 of file AttributorAttributes.cpp.
References llvm::AA::isAssumedReadNone(), and STATS_DECLTRACK_CS_ATTR.
updateImpl()
ChangeStatus AAMemoryLocationCallSite::updateImpl (Attributor & A) inline override
See AbstractAttribute::updateImpl(...).
Definition at line 8047 of file AttributorAttributes.cpp.
References llvm::CHANGED, F, llvm::IRPosition::function(), I, llvm::REQUIRED, and llvm::UNCHANGED.
The documentation for this struct was generated from the following file:
lib/Transforms/IPO/AttributorAttributes.cpp