LLVM: AAMemoryLocationImpl Struct Reference
AAMemoryLocationImpl Struct Reference
Classes
struct AccessInfo
Helper struct to tie together an instruction that has a read or write effect with the pointer it accesses (if any).
Public Member Functions
AAMemoryLocationImpl (const IRPosition &IRP, Attributor &A)
~AAMemoryLocationImpl ()
void initialize (Attributor &A) override
See AbstractAttribute::initialize(...).
void getDeducedAttributes (LLVMContext &Ctx, SmallVectorImpl< Attribute > &Attrs) const override
See AbstractAttribute::getDeducedAttributes(...).
ChangeStatus manifest (Attributor &A) override
See AbstractAttribute::manifest(...).
bool checkForAllAccessesToMemoryKind (function_ref< bool(const Instruction *, const Value *, AccessKind, MemoryLocationsKind)> Pred, MemoryLocationsKind RequestedMLK) const override
See AAMemoryLocation::checkForAllAccessesToMemoryKind(...).
ChangeStatus indicatePessimisticFixpoint () override
Public Member Functions inherited from llvm::AAMemoryLocation
AAMemoryLocation (const IRPosition &IRP, Attributor &A)
bool isKnownReadNone () const
Return true if we know that the associated functions has no observable accesses.
bool isAssumedReadNone () const
Return true if we assume that the associated functions has no observable accesses.
bool isKnowStackOnly () const
Return true if we know that the associated functions has at most local/stack accesses.
bool isAssumedStackOnly () const
Return true if we assume that the associated functions has at most local/stack accesses.
bool isKnownInaccessibleMemOnly () const
Return true if we know that the underlying value will only access inaccesible memory only (see Attribute::InaccessibleMemOnly).
bool isAssumedInaccessibleMemOnly () const
Return true if we assume that the underlying value will only access inaccesible memory only (see Attribute::InaccessibleMemOnly).
bool isKnownArgMemOnly () const
Return true if we know that the underlying value will only access argument pointees (see Attribute::ArgMemOnly).
bool isAssumedArgMemOnly () const
Return true if we assume that the underlying value will only access argument pointees (see Attribute::ArgMemOnly).
bool isKnownInaccessibleOrArgMemOnly () const
Return true if we know that the underlying value will only access inaccesible memory or argument pointees (see Attribute::InaccessibleOrArgMemOnly).
bool isAssumedInaccessibleOrArgMemOnly () const
Return true if we assume that the underlying value will only access inaccesible memory or argument pointees (see Attribute::InaccessibleOrArgMemOnly).
bool mayAccessArgMem () const
Return true if the underlying value may access memory through arguement pointers of the associated function, if any.
bool isAssumedSpecifiedMemOnly (MemoryLocationsKind MLK) const
Return true if only the memory locations specififed by MLK are assumed to be accessed by the associated function.
MemoryLocationsKind getAssumedNotAccessedLocation () const
Return the locations that are assumed to be not accessed by the associated function, if any.
const std::string getAsStr () const override
See AbstractState::getAsStr().
const std::string getName () const override
See AbstractAttribute::getName()
const char * getIdAddr () const override
See AbstractAttribute::getIdAddr()
Public Member Functions inherited from llvm::IRAttribute< Attribute::ReadNone, StateWrapper< BitIntegerState< uint32_t, 511 >, AbstractAttribute > >
IRAttribute (const IRPosition &IRP)
ChangeStatus manifest (Attributor &A) override
See AbstractAttribute::manifest(...).
Attribute::AttrKind getAttrKind () const
Return the kind that identifies the abstract attribute implementation.
Public Member Functions inherited from llvm::StateWrapper< StateTy, BaseType, Ts >
StateWrapper (const IRPosition &IRP, Ts... Args)
StateType & getState () override
See AbstractAttribute::getState(...).
const StateType & getState () const override
See AbstractAttribute::getState(...).
Static Public Member Functions
static void getKnownStateFromValue (Attributor &A, const IRPosition &IRP, BitIntegerState &State, bool IgnoreSubsumingPositions=false)
Return the memory behavior information encoded in the IR for IRP.
Static Public Member Functions inherited from llvm::AAMemoryLocation
static MemoryLocationsKind inverseLocation (MemoryLocationsKind Loc, bool AndLocalMem, bool AndConstMem)
Return the inverse of location Loc, thus for NO_XXX the return describes ONLY_XXX.
static std::string getMemoryLocationsAsStr (MemoryLocationsKind MLK)
Return the locations encoded by MLK as a readable string.
static AAMemoryLocation & createForPosition (const IRPosition &IRP, Attributor &A)
Create an abstract attribute view for the position IRP.
static bool classof (const AbstractAttribute *AA)
This function should return true if the type of the AA is AAMemoryLocation.
Protected Types
using AccessSet = SmallSet< AccessInfo, 2, AccessInfo >
Mapping from single memory location kinds, e.g., LOCAL_MEM with the value of NO_LOCAL_MEM, to the accesses encountered for this memory kind.
Protected Member Functions
void categorizeArgumentPointerLocations (Attributor &A, CallBase &CB, AAMemoryLocation::StateType &AccessedLocs, bool &Changed)
Categorize the pointer arguments of CB that might access memory in AccessedLoc and update the state and access map accordingly.
AAMemoryLocation::MemoryLocationsKind categorizeAccessedLocations (Attributor &A, Instruction &I, bool &Changed)
Return the kind(s) of location that may be accessed by V.
AccessKind getAccessKindFromInst (const Instruction *I)
Return the access kind as determined by I.
void updateStateAndAccessesMap (AAMemoryLocation::StateType &State, MemoryLocationsKind MLK, const Instruction *I, const Value *Ptr, bool &Changed, AccessKind AK=READ_WRITE)
Update the state State and the AccessKind2Accesses given that I is an access of kind AK to a MLK memory location with the access pointer Ptr.
void categorizePtrValue (Attributor &A, const Instruction &I, const Value &Ptr, AAMemoryLocation::StateType &State, bool &Changed)
Determine the underlying locations kinds for Ptr, e.g., globals or arguments, and update the state and access map accordingly.
Protected Attributes
AccessSet * AccessKind2Accesses [llvm::CTLog2< VALID_STATE >()]
BumpPtrAllocator & Allocator
Used to allocate access sets.
Static Protected Attributes
static const Attribute::AttrKind AttrKinds [4]
The set of IR attributes AAMemoryLocation deals with.
Additional Inherited Members
Public Types inherited from llvm::AAMemoryLocation
enum {
ALL_LOCATIONS = 0 , NO_LOCAL_MEM = 1 << 0 , NO_CONST_MEM = 1 << 1 , NO_GLOBAL_INTERNAL_MEM = 1 << 2 ,
NO_GLOBAL_EXTERNAL_MEM = 1 << 3 , NO_GLOBAL_MEM = NO_GLOBAL_INTERNAL_MEM | NO_GLOBAL_EXTERNAL_MEM , NO_ARGUMENT_MEM = 1 << 4 , NO_INACCESSIBLE_MEM = 1 << 5 ,
NO_MALLOCED_MEM = 1 << 6 , NO_UNKOWN_MEM = 1 << 7 , NO_LOCATIONS , VALID_STATE = NO_LOCATIONS + 1 ,
BEST_STATE = NO_LOCATIONS | VALID_STATE
}
Encoding of different locations that could be accessed by a memory access.
enum AccessKind { NONE = 0 , READ = 1 << 0 , WRITE = 1 << 1 , READ_WRITE = READ | WRITE }
Simple enum to distinguish read/write/read-write accesses.
using MemoryLocationsKind = StateType::base_t
Public Types inherited from llvm::StateWrapper< StateTy, BaseType, Ts >
using StateType = StateTy
Provide static access to the type of the state.
Static Public Attributes inherited from llvm::AAMemoryLocation
static const char ID = 0
Unique ID (due to the unique address)
Detailed Description
Definition at line 7558 of file AttributorAttributes.cpp.
Member Typedef Documentation
AccessSet
using AAMemoryLocationImpl::AccessSet = SmallSet<AccessInfo, 2, AccessInfo> protected
Mapping from single memory location kinds, e.g., LOCAL_MEM with the value of NO_LOCAL_MEM, to the accesses encountered for this memory kind.
Definition at line 7738 of file AttributorAttributes.cpp.
Constructor & Destructor Documentation
AAMemoryLocationImpl()
AAMemoryLocationImpl::AAMemoryLocationImpl (const IRPosition & IRP, Attributor & A) inline
Definition at line 7560 of file AttributorAttributes.cpp.
~AAMemoryLocationImpl()
AAMemoryLocationImpl::~AAMemoryLocationImpl () inline
Definition at line 7566 of file AttributorAttributes.cpp.
Member Function Documentation
categorizeAccessedLocations()
AAMemoryLocation::MemoryLocationsKind AAMemoryLocationImpl::categorizeAccessedLocations (Attributor & A, Instruction & I, bool & Changed) protected
Return the kind(s) of location that may be accessed by V.
Definition at line 7893 of file AttributorAttributes.cpp.
References llvm::IRPosition::callsite_function(), llvm::dbgs(), llvm::getPointerOperand(), I, LLVM_DEBUG, and llvm::OPTIONAL.
categorizeArgumentPointerLocations()
void AAMemoryLocationImpl::categorizeArgumentPointerLocations (Attributor & A, CallBase & CB, AAMemoryLocation::StateType & AccessedLocs, bool & Changed) protected
Categorize the pointer arguments of CB that might access memory in AccessedLoc and update the state and access map accordingly.
Definition at line 7868 of file AttributorAttributes.cpp.
References llvm::CallBase::arg_size(), llvm::IRPosition::callsite_argument(), E, llvm::CallBase::getArgOperand(), llvm::Value::getType(), llvm::Type::isPtrOrPtrVectorTy(), and llvm::OPTIONAL.
categorizePtrValue()
void AAMemoryLocationImpl::categorizePtrValue (Attributor & A, const Instruction & I, const Value & Ptr, AAMemoryLocation::StateType & State, bool & Changed) protected
Determine the underlying locations kinds for Ptr, e.g., globals or arguments, and update the state and access map accordingly.
Definition at line 7794 of file AttributorAttributes.cpp.
References assert(), llvm::IRPosition::callsite_returned(), llvm::dbgs(), llvm::AA::getAssumedUnderlyingObjects(), llvm::Type::getPointerAddressSpace(), llvm::Value::getType(), I, LLVM_DEBUG, llvm::NullPointerIsDefined(), and llvm::OPTIONAL.
checkForAllAccessesToMemoryKind()
bool AAMemoryLocationImpl::checkForAllAccessesToMemoryKind (function_ref< bool(const Instruction *, const Value *, AccessKind, MemoryLocationsKind)> Pred, MemoryLocationsKind RequestedMLK) const inline override virtual
See AAMemoryLocation::checkForAllAccessesToMemoryKind(...).
Implements llvm::AAMemoryLocation.
Definition at line 7666 of file AttributorAttributes.cpp.
getAccessKindFromInst()
AccessKind AAMemoryLocationImpl::getAccessKindFromInst (const Instruction * I) inline protected
Return the access kind as determined by I.
Definition at line 7753 of file AttributorAttributes.cpp.
References I, and llvm::NONE.
getDeducedAttributes()
void AAMemoryLocationImpl::getDeducedAttributes (LLVMContext & Ctx, SmallVectorImpl< Attribute > & Attrs) const inline override virtual
See AbstractAttribute::getDeducedAttributes(...).
Reimplemented from llvm::IRAttribute< Attribute::ReadNone, StateWrapper< BitIntegerState< uint32_t, 511 >, AbstractAttribute > >.
Definition at line 7626 of file AttributorAttributes.cpp.
References assert(), llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, llvm::Attribute::get(), llvm::IRPosition::IRP_FUNCTION, and llvm::AA::isAssumedReadNone().
getKnownStateFromValue()
static void AAMemoryLocationImpl::getKnownStateFromValue (Attributor & A, const IRPosition & IRP, BitIntegerState & State, bool IgnoreSubsumingPositions = false) inline static
Return the memory behavior information encoded in the IR for IRP.
Definition at line 7582 of file AttributorAttributes.cpp.
References llvm::BitIntegerState< base_ty, BestState, WorstState >::addKnownBits(), llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, llvm::IRPosition::getAnchorScope(), llvm::IRPosition::getAttrs(), llvm::GlobalValue::hasLocalLinkage(), llvm_unreachable, and llvm::IRPosition::removeAttrs().
indicatePessimisticFixpoint()
ChangeStatus AAMemoryLocationImpl::indicatePessimisticFixpoint () inline override
Definition at line 7693 of file AttributorAttributes.cpp.
References I.
initialize()
void AAMemoryLocationImpl::initialize (Attributor & A) inline override virtual
See AbstractAttribute::initialize(...).
Reimplemented from llvm::IRAttribute< Attribute::ReadNone, StateWrapper< BitIntegerState< uint32_t, 511 >, AbstractAttribute > >.
Reimplemented in AAMemoryLocationCallSite.
Definition at line 7575 of file AttributorAttributes.cpp.
References llvm::IRAttribute< Attribute::ReadNone, StateWrapper< BitIntegerState< uint32_t, 511 >, AbstractAttribute > >::initialize().
Referenced by AAMemoryLocationCallSite::initialize().
manifest()
ChangeStatus AAMemoryLocationImpl::manifest (Attributor & A) inline override
See AbstractAttribute::manifest(...).
Definition at line 7644 of file AttributorAttributes.cpp.
References llvm::all_of(), AAMemoryBehaviorImpl::AttrKinds, llvm::IRPosition::getAnchorValue(), llvm::Value::getContext(), llvm::Attribute::getKindAsEnum(), llvm::IRPosition::hasAttr(), llvm::AA::isAssumedReadNone(), llvm::IRAttribute< AK, BaseType >::manifest(), llvm::IRPosition::removeAttrs(), and llvm::UNCHANGED.
updateStateAndAccessesMap()
void AAMemoryLocationImpl::updateStateAndAccessesMap (AAMemoryLocation::StateType & State, MemoryLocationsKind MLK, const Instruction * I, const Value * Ptr, bool & Changed, AccessKind AK = READ_WRITE) inline protected
Update the state State and the AccessKind2Accesses given that I is an access of kind AK to a MLK memory location with the access pointer Ptr.
Definition at line 7765 of file AttributorAttributes.cpp.
References Allocator, assert(), I, llvm::isPowerOf2_32(), and llvm::Log2_32().
Member Data Documentation
AccessKind2Accesses
AccessSet* AAMemoryLocationImpl::AccessKind2Accesses[llvm::CTLog2< VALID_STATE >()] protected
Definition at line 7739 of file AttributorAttributes.cpp.
Allocator
BumpPtrAllocator& AAMemoryLocationImpl::Allocator protected
Used to allocate access sets.
Definition at line 7784 of file AttributorAttributes.cpp.
AttrKinds
const Attribute::AttrKind AAMemoryLocationImpl::AttrKinds static protected
Initial value:
= {
    Attribute::ReadNone, Attribute::InaccessibleMemOnly, Attribute::ArgMemOnly,
    Attribute::InaccessibleMemOrArgMemOnly}
The set of IR attributes AAMemoryLocation deals with.
Definition at line 7787 of file AttributorAttributes.cpp.
The documentation for this struct was generated from the following file:
lib/Transforms/IPO/AttributorAttributes.cpp