LLVM: AADereferenceableFloating Struct Reference
AADereferenceableFloating Struct Reference
Dereferenceable attribute for a floating value.
Public Member Functions
AADereferenceableFloating (const IRPosition &IRP, Attributor &A)
ChangeStatus updateImpl (Attributor &A) override
See AbstractAttribute::updateImpl(...).
void trackStatistics () const override
See AbstractAttribute::trackStatistics()
Public Member Functions inherited from AADereferenceableImpl
AADereferenceableImpl (const IRPosition &IRP, Attributor &A)
void initialize (Attributor &A) override
See AbstractAttribute::initialize(...).
StateType & getState () override
See AbstractAttribute::getState() {.
const StateType & getState () const override
void addAccessedBytesForUse (Attributor &A, const Use *U, const Instruction *I, DerefState &State)
}
bool followUseInMBEC (Attributor &A, const Use *U, const Instruction *I, AADereferenceable::StateType &State)
See followUsesInMBEC.
ChangeStatus manifest (Attributor &A) override
See AbstractAttribute::manifest(...).
void getDeducedAttributes (LLVMContext &Ctx, SmallVectorImpl< Attribute > &Attrs) const override
Return the deduced attributes in Attrs.
const std::string getAsStr () const override
See AbstractAttribute::getAsStr().
Public Member Functions inherited from llvm::AADereferenceable
AADereferenceable (const IRPosition &IRP, Attributor &A)
bool isAssumedNonNull () const
Return true if we assume that the underlying value is nonnull.
bool isKnownNonNull () const
Return true if we know that the underlying value is nonnull.
bool isAssumedGlobal () const
Return true if we assume that underlying value is dereferenceable(_or_null) globally.
bool isKnownGlobal () const
Return true if we know that underlying value is dereferenceable(_or_null) globally.
uint32_t getAssumedDereferenceableBytes () const
Return assumed dereferenceable bytes.
uint32_t getKnownDereferenceableBytes () const
Return known dereferenceable bytes.
const std::string getName () const override
See AbstractAttribute::getName()
const char * getIdAddr () const override
See AbstractAttribute::getIdAddr()
Public Member Functions inherited from llvm::IRAttribute< Attribute::Dereferenceable, StateWrapper< DerefState, AbstractAttribute > >
IRAttribute (const IRPosition &IRP)
ChangeStatus manifest (Attributor &A) override
See AbstractAttribute::manifest(...).
Attribute::AttrKind getAttrKind () const
Return the kind that identifies the abstract attribute implementation.
Public Member Functions inherited from llvm::StateWrapper< StateTy, BaseType, Ts >
StateWrapper (const IRPosition &IRP, Ts... Args)
StateType & getState () override
See AbstractAttribute::getState(...).
const StateType & getState () const override
See AbstractAttribute::getState(...).
Additional Inherited Members
Public Types inherited from AADereferenceableImpl
using StateType = DerefState
Public Types inherited from llvm::StateWrapper< StateTy, BaseType, Ts >
using StateType = StateTy
Provide static access to the type of the state.
Static Public Member Functions inherited from llvm::AADereferenceable
static AADereferenceable & createForPosition (const IRPosition &IRP, Attributor &A)
Create an abstract attribute view for the position IRP.
static bool classof (const AbstractAttribute *AA)
This function should return true if the type of the AA is AADereferenceable.
Static Public Attributes inherited from llvm::AADereferenceable
static const char ID = 0
Unique ID (due to the unique address)
Detailed Description
Dereferenceable attribute for a floating value.
Definition at line 4269 of file AttributorAttributes.cpp.
Constructor & Destructor Documentation
AADereferenceableFloating()
AADereferenceableFloating::AADereferenceableFloating (const IRPosition & IRP, Attributor & A) inline
Definition at line 4270 of file AttributorAttributes.cpp.
Member Function Documentation
trackStatistics()
void AADereferenceableFloating::trackStatistics () const inline override
See AbstractAttribute::trackStatistics()
Definition at line 4341 of file AttributorAttributes.cpp.
References STATS_DECLTRACK_FLOATING_ATTR.
updateImpl()
ChangeStatus AADereferenceableFloating::updateImpl (Attributor & A) inline override
See AbstractAttribute::updateImpl(...).
Definition at line 4274 of file AttributorAttributes.cpp.
References llvm::sampleprof::Base, llvm::clampStateAndIndicateChange(), DL, llvm::SIInstrFlags::DS, llvm::Type::getPointerAddressSpace(), llvm::Value::getType(), llvm::max(), Offset, llvm::REQUIRED, stripAndAccumulateMinimalOffsets(), T, and llvm::IRPosition::value().
The documentation for this struct was generated from the following file:
lib/Transforms/IPO/AttributorAttributes.cpp