LLVM: AADereferenceableImpl Struct Reference
AADereferenceableImpl Struct Reference
-----------------— Dereferenceable Argument Attribute -----------------—
Public Types
using StateType = DerefState
Public Types inherited from llvm::StateWrapper< StateTy, BaseType, Ts >
using StateType = StateTy
Provide static access to the type of the state.
Public Member Functions
AADereferenceableImpl (const IRPosition &IRP, Attributor &A)
void initialize (Attributor &A) override
See AbstractAttribute::initialize(...).
StateType & getState () override
See AbstractAttribute::getState() {.
const StateType & getState () const override
void addAccessedBytesForUse (Attributor &A, const Use *U, const Instruction *I, DerefState &State)
}
bool followUseInMBEC (Attributor &A, const Use *U, const Instruction *I, AADereferenceable::StateType &State)
See followUsesInMBEC.
ChangeStatus manifest (Attributor &A) override
See AbstractAttribute::manifest(...).
void getDeducedAttributes (LLVMContext &Ctx, SmallVectorImpl< Attribute > &Attrs) const override
Return the deduced attributes in Attrs.
const std::string getAsStr () const override
See AbstractAttribute::getAsStr().
Public Member Functions inherited from llvm::AADereferenceable
AADereferenceable (const IRPosition &IRP, Attributor &A)
bool isAssumedNonNull () const
Return true if we assume that the underlying value is nonnull.
bool isKnownNonNull () const
Return true if we know that the underlying value is nonnull.
bool isAssumedGlobal () const
Return true if we assume that underlying value is dereferenceable(_or_null) globally.
bool isKnownGlobal () const
Return true if we know that underlying value is dereferenceable(_or_null) globally.
uint32_t getAssumedDereferenceableBytes () const
Return assumed dereferenceable bytes.
uint32_t getKnownDereferenceableBytes () const
Return known dereferenceable bytes.
const std::string getName () const override
See AbstractAttribute::getName()
const char * getIdAddr () const override
See AbstractAttribute::getIdAddr()
Public Member Functions inherited from llvm::IRAttribute< Attribute::Dereferenceable, StateWrapper< DerefState, AbstractAttribute > >
IRAttribute (const IRPosition &IRP)
ChangeStatus manifest (Attributor &A) override
See AbstractAttribute::manifest(...).
Attribute::AttrKind getAttrKind () const
Return the kind that identifies the abstract attribute implementation.
Public Member Functions inherited from llvm::StateWrapper< StateTy, BaseType, Ts >
StateWrapper (const IRPosition &IRP, Ts... Args)
StateType & getState () override
See AbstractAttribute::getState(...).
const StateType & getState () const override
See AbstractAttribute::getState(...).
Additional Inherited Members
Static Public Member Functions inherited from llvm::AADereferenceable
static AADereferenceable & createForPosition (const IRPosition &IRP, Attributor &A)
Create an abstract attribute view for the position IRP.
static bool classof (const AbstractAttribute *AA)
This function should return true if the type of the AA is AADereferenceable.
Static Public Attributes inherited from llvm::AADereferenceable
static const char ID = 0
Unique ID (due to the unique address)
Detailed Description
-----------------— Dereferenceable Argument Attribute -----------------—
Definition at line 4164 of file AttributorAttributes.cpp.
Member Typedef Documentation
StateType
using AADereferenceableImpl::StateType = DerefState
Definition at line 4167 of file AttributorAttributes.cpp.
Constructor & Destructor Documentation
AADereferenceableImpl()
AADereferenceableImpl::AADereferenceableImpl (const IRPosition & IRP, Attributor & A) inline
Definition at line 4165 of file AttributorAttributes.cpp.
Member Function Documentation
addAccessedBytesForUse()
void AADereferenceableImpl::addAccessedBytesForUse (Attributor & A, const Use * U, const Instruction * I, DerefState & State) inline
}
Helper function for collecting accessed bytes in must-be-executed-context
Definition at line 4203 of file AttributorAttributes.cpp.
References llvm::sampleprof::Base, llvm::MemoryLocation::getOrNone(), llvm::GetPointerBaseWithConstantOffset(), llvm::Value::getType(), llvm::Optional< T >::getValue(), I, llvm::Type::isPointerTy(), and Offset.
followUseInMBEC()
bool AADereferenceableImpl::followUseInMBEC (Attributor & A, const Use * U, const Instruction * I, AADereferenceable::StateType & State) inline
See followUsesInMBEC.
Definition at line 4221 of file AttributorAttributes.cpp.
References llvm::dbgs(), getKnownNonNullAndDerefBytesForUse(), I, and LLVM_DEBUG.
getAsStr()
const std::string AADereferenceableImpl::getAsStr () const inline override
See AbstractAttribute::getAsStr().
Definition at line 4257 of file AttributorAttributes.cpp.
References llvm::to_string().
getDeducedAttributes()
void AADereferenceableImpl::getDeducedAttributes (LLVMContext & Ctx, SmallVectorImpl< Attribute > & Attrs) const inline override virtual
Return the deduced attributes in Attrs.
Reimplemented from llvm::IRAttribute< Attribute::Dereferenceable, StateWrapper< DerefState, AbstractAttribute > >.
Definition at line 4245 of file AttributorAttributes.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, llvm::Attribute::getWithDereferenceableBytes(), and llvm::Attribute::getWithDereferenceableOrNullBytes().
getState() [1/2]
const StateType& AADereferenceableImpl::getState () const inline override
Definition at line 4199 of file AttributorAttributes.cpp.
getState() [2/2]
StateType& AADereferenceableImpl::getState () inline override
See AbstractAttribute::getState() {.
Definition at line 4198 of file AttributorAttributes.cpp.
initialize()
void AADereferenceableImpl::initialize (Attributor & A) inline override virtual
See AbstractAttribute::initialize(...).
Reimplemented from llvm::IRAttribute< Attribute::Dereferenceable, StateWrapper< DerefState, AbstractAttribute > >.
Definition at line 4170 of file AttributorAttributes.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, followUsesInMBEC(), llvm::IRPosition::getAnchorScope(), llvm::IRPosition::getAssociatedValue(), llvm::Value::getPointerDereferenceableBytes(), llvm::IRPosition::isFnInterfaceKind(), and llvm::NONE.
manifest()
ChangeStatus AADereferenceableImpl::manifest (Attributor & A) inline override
See AbstractAttribute::manifest(...).
Definition at line 4236 of file AttributorAttributes.cpp.
References llvm::CHANGED, and llvm::IRAttribute< Attribute::Dereferenceable, StateWrapper< DerefState, AbstractAttribute > >::manifest().
The documentation for this struct was generated from the following file:
lib/Transforms/IPO/AttributorAttributes.cpp