LLVM: llvm::DivergencePropagator Struct Reference
llvm::DivergencePropagator Struct Reference
Public Types
using BlockLabelVec = std::vector< const BasicBlock * >
Public Member Functions
DivergencePropagator (const ModifiedPO &LoopPOT, const DominatorTree &DT, const PostDominatorTree &PDT, const LoopInfo &LI, const BasicBlock &DivTermBlock)
void printDefs (raw_ostream &Out)
bool computeJoin (const BasicBlock &SuccBlock, const BasicBlock &PushedLabel)
bool visitLoopExitEdge (const BasicBlock &ExitBlock, const BasicBlock &DefBlock, bool FromParentLoop)
bool visitEdge (const BasicBlock &SuccBlock, const BasicBlock &DefBlock)
std::unique_ptr< ControlDivergenceDesc > computeJoinPoints ()
Public Attributes
const ModifiedPO & LoopPOT
const DominatorTree & DT
const PostDominatorTree & PDT
const LoopInfo & LI
const BasicBlock & DivTermBlock
BlockLabelVec BlockLabels
std::unique_ptr< ControlDivergenceDesc > DivDesc
Detailed Description
Definition at line 263 of file SyncDependenceAnalysis.cpp.
Member Typedef Documentation
BlockLabelVec
using llvm::DivergencePropagator::BlockLabelVec = std::vector<const BasicBlock *>
Definition at line 275 of file SyncDependenceAnalysis.cpp.
Constructor & Destructor Documentation
DivergencePropagator()
llvm::DivergencePropagator::DivergencePropagator (const ModifiedPO & LoopPOT, const DominatorTree & DT, const PostDominatorTree & PDT, const LoopInfo & LI, const BasicBlock & DivTermBlock) inline
Definition at line 280 of file SyncDependenceAnalysis.cpp.
Member Function Documentation
computeJoin()
bool llvm::DivergencePropagator::computeJoin (const BasicBlock & SuccBlock, const BasicBlock & PushedLabel) inline
Definition at line 304 of file SyncDependenceAnalysis.cpp.
References BlockLabels, llvm::ModifiedPO::getIndexOf(), and LoopPOT.
Referenced by visitEdge(), and visitLoopExitEdge().
computeJoinPoints()
std::unique_ptr<ControlDivergenceDesc> llvm::DivergencePropagator::computeJoinPoints () inline
Definition at line 348 of file SyncDependenceAnalysis.cpp.
References assert(), BlockLabels, llvm::dbgs(), DivDesc, DivTermBlock, llvm::ModifiedPO::getBlockAt(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::ModifiedPO::getIndexOf(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::Value::getName(), LI, LLVM_DEBUG, LoopPOT, llvm::move(), printDefs(), llvm::ModifiedPO::size(), llvm::successors(), visitEdge(), and visitLoopExitEdge().
Referenced by llvm::SyncDependenceAnalysis::getJoinBlocks().
printDefs()
void llvm::DivergencePropagator::printDefs (raw_ostream & Out) inline
Definition at line 287 of file SyncDependenceAnalysis.cpp.
References BlockLabels, llvm::ModifiedPO::getBlockAt(), llvm::Value::getName(), LoopPOT, and llvm::StringRef::str().
Referenced by computeJoinPoints().
visitEdge()
bool llvm::DivergencePropagator::visitEdge (const BasicBlock & SuccBlock, const BasicBlock & DefBlock) inline
Definition at line 338 of file SyncDependenceAnalysis.cpp.
References computeJoin(), llvm::dbgs(), DivDesc, llvm::Value::getName(), and LLVM_DEBUG.
Referenced by computeJoinPoints(), and visitLoopExitEdge().
visitLoopExitEdge()
bool llvm::DivergencePropagator::visitLoopExitEdge (const BasicBlock & ExitBlock, const BasicBlock & DefBlock, bool FromParentLoop) inline
Definition at line 321 of file SyncDependenceAnalysis.cpp.
References computeJoin(), llvm::dbgs(), DivDesc, llvm::Value::getName(), LLVM_DEBUG, and visitEdge().
Referenced by computeJoinPoints().
Member Data Documentation
BlockLabels
BlockLabelVec llvm::DivergencePropagator::BlockLabels
Definition at line 276 of file SyncDependenceAnalysis.cpp.
Referenced by computeJoin(), computeJoinPoints(), and printDefs().
DivDesc
std::unique_ptr<ControlDivergenceDesc> llvm::DivergencePropagator::DivDesc
Definition at line 278 of file SyncDependenceAnalysis.cpp.
Referenced by computeJoinPoints(), visitEdge(), and visitLoopExitEdge().
DivTermBlock
const BasicBlock& llvm::DivergencePropagator::DivTermBlock
Definition at line 268 of file SyncDependenceAnalysis.cpp.
Referenced by computeJoinPoints().
DT
const DominatorTree& llvm::DivergencePropagator::DT
Definition at line 265 of file SyncDependenceAnalysis.cpp.
LI
const LoopInfo& llvm::DivergencePropagator::LI
Definition at line 267 of file SyncDependenceAnalysis.cpp.
Referenced by computeJoinPoints().
LoopPOT
const ModifiedPO& llvm::DivergencePropagator::LoopPOT
Definition at line 264 of file SyncDependenceAnalysis.cpp.
Referenced by computeJoin(), computeJoinPoints(), and printDefs().
PDT
const PostDominatorTree& llvm::DivergencePropagator::PDT
Definition at line 266 of file SyncDependenceAnalysis.cpp.
The documentation for this struct was generated from the following file:
lib/Analysis/SyncDependenceAnalysis.cpp