LLVM: AAValueSimplifyFloating Struct Reference
AAValueSimplifyFloating Struct Reference
Public Member Functions
AAValueSimplifyFloating (const IRPosition &IRP, Attributor &A)
void initialize (Attributor &A) override
See AbstractAttribute::initialize(...).
bool handleCmp (Attributor &A, CmpInst &Cmp)
Check if Cmp is a comparison we can simplify.
bool updateWithLoad (Attributor &A, LoadInst &L)
bool handleGenericInst (Attributor &A, Instruction &I)
Use the generic, non-optimistic InstSimplfy functionality if we managed to simplify any operand of the instruction I.
ChangeStatus updateImpl (Attributor &A) override
See AbstractAttribute::updateImpl(...).
void trackStatistics () const override
See AbstractAttribute::trackStatistics()
Public Member Functions inherited from AAValueSimplifyImpl
AAValueSimplifyImpl (const IRPosition &IRP, Attributor &A)
const std::string getAsStr () const override
See AbstractAttribute::getAsStr().
Optional< Value * > getAssumedSimplifiedValue (Attributor &A) const override
See AAValueSimplify::getAssumedSimplifiedValue()
Value * getReplacementValue (Attributor &A) const
Return a value we can use as replacement for the associated one, or nullptr if we don't have one that makes sense.
bool checkAndUpdate (Attributor &A, const AbstractAttribute &QueryingAA, const IRPosition &IRP, bool Simplify=true)
Helper function for querying AAValueSimplify and updating candicate.
template<typename AAType >
bool askSimplifiedValueFor (Attributor &A)
Returns a candidate is found or not.
bool askSimplifiedValueForOtherAAs (Attributor &A)
ChangeStatus manifest (Attributor &A) override
See AbstractAttribute::manifest(...).
ChangeStatus indicatePessimisticFixpoint () override
See AbstractState::indicatePessimisticFixpoint(...).
Public Member Functions inherited from llvm::AAValueSimplify
AAValueSimplify (const IRPosition &IRP, Attributor &A)
const std::string getName () const override
See AbstractAttribute::getName()
const char * getIdAddr () const override
See AbstractAttribute::getIdAddr()
Public Member Functions inherited from llvm::StateWrapper< ValueSimplifyStateType, AbstractAttribute, Type * >
StateWrapper (const IRPosition &IRP, Ts... Args)
StateType & getState () override
See AbstractAttribute::getState(...).
const StateType & getState () const override
See AbstractAttribute::getState(...).
Public Member Functions inherited from llvm::AbstractAttribute
AbstractAttribute (const IRPosition &IRP)
virtual ~AbstractAttribute ()=default
Virtual destructor.
virtual bool isQueryAA () const
A query AA is always scheduled as long as we do updates because it does lazy computation that cannot be determined to be done from the outside.
const IRPosition & getIRPosition () const
Return an IR position, see struct IRPosition.
IRPosition & getIRPosition ()
void print (raw_ostream &OS) const override
Helper functions, for debug purposes only.
virtual void printWithDeps (raw_ostream &OS) const
void dump () const
Public Member Functions inherited from llvm::IRPosition
IRPosition ()
Default constructor available to create invalid positions implicitly.
bool operator== (const IRPosition &RHS) const
bool operator!= (const IRPosition &RHS) const
Value & getAnchorValue () const
Return the value this abstract attribute is anchored with.
Function * getAssociatedFunction () const
Return the associated function, if any.
Argument * getAssociatedArgument () const
Return the associated argument, if any.
bool isFnInterfaceKind () const
Return true if the position refers to a function interface, that is the function scope, the function return, or an argument.
Function * getAnchorScope () const
Return the Function surrounding the anchor value.
Instruction * getCtxI () const
Return the context instruction, if any.
Value & getAssociatedValue () const
Return the value this abstract attribute is associated with.
Type * getAssociatedType () const
Return the type this abstract attribute is associated with.
int getCalleeArgNo () const
Return the callee argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
int getCallSiteArgNo () const
Return the call site argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
unsigned getAttrIdx () const
Return the index in the attribute list for this position.
Kind getPositionKind () const
Return the associated position kind.
bool hasAttr (ArrayRef< Attribute::AttrKind > AKs, bool IgnoreSubsumingPositions=false, Attributor *A=nullptr) const
TODO: Figure out if the attribute related helper functions should live here or somewhere else.
void getAttrs (ArrayRef< Attribute::AttrKind > AKs, SmallVectorImpl< Attribute > &Attrs, bool IgnoreSubsumingPositions=false, Attributor *A=nullptr) const
Return the attributes of any kind in AKs existing in the IR at a position that will affect this one.
void removeAttrs (ArrayRef< Attribute::AttrKind > AKs) const
Remove the attribute of kind AKs existing in the IR at this position.
bool isAnyCallSitePosition () const
bool isArgumentPosition () const
Return true if the position is an argument or call site argument.
IRPosition stripCallBaseContext () const
Return the same position without the call base context.
const CallBaseContext * getCallBaseContext () const
Get the call base context from the position.
bool hasCallBaseContext () const
Check if the position has any call base context.
operator void * () const
}
Public Member Functions inherited from llvm::AADepGraphNode
virtual ~AADepGraphNode ()=default
aaiterator begin ()
aaiterator end ()
iterator child_begin ()
iterator child_end ()
TinyPtrVector< DepTy > & getDeps ()
Public Member Functions inherited from llvm::ValueSimplifyStateType
ValueSimplifyStateType (Type *Ty)
bool isValidState () const override
See AbstractState::isValidState(...)
bool isAtFixpoint () const override
See AbstractState::isAtFixpoint(...)
ValueSimplifyStateType getAssumed ()
Return the assumed state encoding.
const ValueSimplifyStateType & getAssumed () const
ChangeStatus indicateOptimisticFixpoint () override
See AbstractState::indicateOptimisticFixpoint(...)
ValueSimplifyStateType operator^= (const ValueSimplifyStateType &VS)
"Clamp" this state with PVS.
bool operator== (const ValueSimplifyStateType &RHS) const
Public Member Functions inherited from llvm::AbstractState
virtual ~AbstractState ()=default
Additional Inherited Members
Public Types inherited from llvm::AAValueSimplify
using Base = StateWrapper< ValueSimplifyStateType, AbstractAttribute, Type * >
Public Types inherited from llvm::StateWrapper< ValueSimplifyStateType, AbstractAttribute, Type * >
using StateType = ValueSimplifyStateType
Provide static access to the type of the state.
Public Types inherited from llvm::AbstractAttribute
using StateType = AbstractState
Public Types inherited from llvm::IRPosition
enum Kind : char {
IRP_INVALID , IRP_FLOAT , IRP_RETURNED , IRP_CALL_SITE_RETURNED ,
IRP_FUNCTION , IRP_CALL_SITE , IRP_ARGUMENT , IRP_CALL_SITE_ARGUMENT
}
The positions we distinguish in the IR.
using CallBaseContext = CallBase
Public Types inherited from llvm::AADepGraphNode
using DepTy = PointerIntPair< AADepGraphNode *, 1 >
using iterator = mapped_iterator< TinyPtrVector< DepTy >::iterator, decltype(&DepGetVal)>
using aaiterator = mapped_iterator< TinyPtrVector< DepTy >::iterator, decltype(&DepGetValAA)>
Static Public Member Functions inherited from AAValueSimplifyImpl
static bool handleLoad (Attributor &A, const AbstractAttribute &AA, LoadInst &L, function_ref< bool(Value &)> Union)
Static Public Member Functions inherited from llvm::AAValueSimplify
static AAValueSimplify & createForPosition (const IRPosition &IRP, Attributor &A)
Create an abstract attribute view for the position IRP.
static bool classof (const AbstractAttribute *AA)
This function should return true if the type of the AA is AAValueSimplify.
Static Public Member Functions inherited from llvm::AbstractAttribute
static bool classof (const AADepGraphNode *DGN)
This function is used to identify if an DGN is of type AbstractAttribute so that the dyn_cast and cast can use such information to cast an AADepGraphNode to an AbstractAttribute.
Static Public Member Functions inherited from llvm::IRPosition
static const IRPosition value (const Value &V, const CallBaseContext *CBContext=nullptr)
Create a position describing the value of V.
static const IRPosition inst (const Instruction &I, const CallBaseContext *CBContext=nullptr)
Create a position describing the instruction I.
static const IRPosition function (const Function &F, const CallBaseContext *CBContext=nullptr)
Create a position describing the function scope of F.
static const IRPosition returned (const Function &F, const CallBaseContext *CBContext=nullptr)
Create a position describing the returned value of F.
static const IRPosition argument (const Argument &Arg, const CallBaseContext *CBContext=nullptr)
Create a position describing the argument Arg.
static const IRPosition callsite_function (const CallBase &CB)
Create a position describing the function scope of CB.
static const IRPosition callsite_returned (const CallBase &CB)
Create a position describing the returned value of CB.
static const IRPosition callsite_argument (const CallBase &CB, unsigned ArgNo)
Create a position describing the argument of CB at position ArgNo.
static const IRPosition callsite_argument (AbstractCallSite ACS, unsigned ArgNo)
Create a position describing the argument of ACS at position ArgNo.
static const IRPosition function_scope (const IRPosition &IRP, const CallBaseContext *CBContext=nullptr)
Create a position with function scope matching the "context" of IRP.
Static Public Member Functions inherited from llvm::ValueSimplifyStateType
static ValueSimplifyStateType getBestState (Type *Ty)
static ValueSimplifyStateType getBestState (const ValueSimplifyStateType &VS)
static ValueSimplifyStateType getWorstState (Type *Ty)
Return the worst possible representable state.
static ValueSimplifyStateType getWorstState (const ValueSimplifyStateType &VS)
Static Public Attributes inherited from llvm::AAValueSimplify
static const char ID = 0
Unique ID (due to the unique address)
Static Public Attributes inherited from llvm::IRPosition
static const IRPosition EmptyKey
Special DenseMap key values.
static const IRPosition TombstoneKey
Protected Member Functions inherited from llvm::AbstractAttribute
ChangeStatus update (Attributor &A)
Hook for the Attributor to trigger an update of the internal state.
Protected Member Functions inherited from llvm::AADepGraphNode
operator AbstractAttribute * ()
Protected Member Functions inherited from llvm::ValueSimplifyStateType
bool unionAssumed (Optional< Value * > Other)
Merge Other into the currently assumed simplified value.
Static Protected Member Functions inherited from llvm::AADepGraphNode
static AADepGraphNode * DepGetVal (DepTy &DT)
static AbstractAttribute * DepGetValAA (DepTy &DT)
Protected Attributes inherited from llvm::AADepGraphNode
TinyPtrVector< DepTy > Deps
Set of dependency graph nodes which should be updated if this one is updated.
Protected Attributes inherited from llvm::ValueSimplifyStateType
Type * Ty
The type of the original value.
BooleanState BS
Helper to track validity and fixpoint.
Optional< Value * > SimplifiedAssociatedValue
An assumed simplified value.
Detailed Description
Definition at line 5586 of file AttributorAttributes.cpp.
Constructor & Destructor Documentation
AAValueSimplifyFloating()
AAValueSimplifyFloating::AAValueSimplifyFloating (const IRPosition & IRP, Attributor & A) inline
Definition at line 5587 of file AttributorAttributes.cpp.
Member Function Documentation
handleCmp()
bool AAValueSimplifyFloating::handleCmp (Attributor & A, CmpInst & Cmp) inline
Check if Cmp is a comparison we can simplify.
We handle multiple cases, one in which at least one operand is an (assumed) nullptr. If so, try to simplify it using AANonNull on the other operand. Return true if successful, in that case SimplifiedAssociatedValue will be updated.
Definition at line 5606 of file AttributorAttributes.cpp.
References assert(), llvm::AA::combineOptionalValuesInAAValueLatice(), llvm::ConstantInt::get(), llvm::Type::getInt1Ty(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::CmpInst::ICMP_NE, llvm::ICmpInst::isEquality(), LHS, llvm::REQUIRED, RHS, and llvm::IRPosition::value().
handleGenericInst()
bool AAValueSimplifyFloating::handleGenericInst (Attributor & A, Instruction & I) inline
Use the generic, non-optimistic InstSimplfy functionality if we managed to simplify any operand of the instruction I.
Return true if successful, in that case SimplifiedAssociatedValue will be updated.
Definition at line 5698 of file AttributorAttributes.cpp.
References llvm::AA::combineOptionalValuesInAAValueLatice(), DL, F, llvm::InformationCache::getAnalysisResultForFunction(), I, llvm::SimplifyInstructionWithOperands(), and llvm::IRPosition::value().
initialize()
void AAValueSimplifyFloating::initialize (Attributor & A) inline override virtual
See AbstractAttribute::initialize(...).
Reimplemented from AAValueSimplifyImpl.
Definition at line 5591 of file AttributorAttributes.cpp.
References AAValueSimplifyImpl::initialize().
trackStatistics()
void AAValueSimplifyFloating::trackStatistics () const inline override virtual
See AbstractAttribute::trackStatistics()
Reimplemented from AAValueSimplifyImpl.
Reimplemented in AAValueSimplifyCallSiteArgument.
Definition at line 5792 of file AttributorAttributes.cpp.
References STATS_DECLTRACK_FLOATING_ATTR.
updateImpl()
ChangeStatus AAValueSimplifyFloating::updateImpl (Attributor & A) inline override virtual
See AbstractAttribute::updateImpl(...).
Implements llvm::AbstractAttribute.
Definition at line 5747 of file AttributorAttributes.cpp.
References llvm::dbgs(), llvm::NVPTXISD::Dummy, I, LLVM_DEBUG, llvm::REQUIRED, llvm::UNCHANGED, and llvm::IRPosition::value().
updateWithLoad()
bool AAValueSimplifyFloating::updateWithLoad (Attributor & A, LoadInst & L) inline
Definition at line 5686 of file AttributorAttributes.cpp.
References llvm::AA::combineOptionalValuesInAAValueLatice(), and llvm::Value::getType().
The documentation for this struct was generated from the following file:
lib/Transforms/IPO/AttributorAttributes.cpp