LLVM: llvm::KnownBits Struct Reference
llvm::KnownBits Struct Reference
#include "llvm/Support/KnownBits.h"
Public Member Functions
KnownBits ()=default
KnownBits (unsigned BitWidth)
Create a known bits object of BitWidth bits initialized to unknown.
unsigned getBitWidth () const
Get the bit width of this value.
bool hasConflict () const
Returns true if there is conflicting information.
bool isConstant () const
Returns true if we know the value of all bits.
const APInt & getConstant () const
Returns the value when all bits have a known value.
bool isUnknown () const
Returns true if we don't know any bits.
void resetAll ()
Resets the known state of all bits.
bool isZero () const
Returns true if value is all zero.
bool isAllOnes () const
Returns true if value is all one bits.
void setAllZero ()
Make all bits known to be zero and discard any previous information.
void setAllOnes ()
Make all bits known to be one and discard any previous information.
bool isNegative () const
Returns true if this value is known to be negative.
bool isNonNegative () const
Returns true if this value is known to be non-negative.
bool isNonZero () const
Returns true if this value is known to be non-zero.
bool isStrictlyPositive () const
Returns true if this value is known to be positive.
void makeNegative ()
Make this value negative.
void makeNonNegative ()
Make this value non-negative.
APInt getMinValue () const
Return the minimal unsigned value possible given these KnownBits.
APInt getSignedMinValue () const
Return the minimal signed value possible given these KnownBits.
APInt getMaxValue () const
Return the maximal unsigned value possible given these KnownBits.
APInt getSignedMaxValue () const
Return the maximal signed value possible given these KnownBits.
KnownBits trunc (unsigned BitWidth) const
Return known bits for a truncation of the value we're tracking.
KnownBits anyext (unsigned BitWidth) const
Return known bits for an "any" extension of the value we're tracking, where we don't know anything about the extended bits.
KnownBits zext (unsigned BitWidth) const
Return known bits for a zero extension of the value we're tracking.
KnownBits sext (unsigned BitWidth) const
Return known bits for a sign extension of the value we're tracking.
KnownBits anyextOrTrunc (unsigned BitWidth) const
Return known bits for an "any" extension or truncation of the value we're tracking.
KnownBits zextOrTrunc (unsigned BitWidth) const
Return known bits for a zero extension or truncation of the value we're tracking.
KnownBits sextOrTrunc (unsigned BitWidth) const
Return known bits for a sign extension or truncation of the value we're tracking.
KnownBits sextInReg (unsigned SrcBitWidth) const
Return known bits for a in-register sign extension of the value we're tracking.
void insertBits (const KnownBits &SubBits, unsigned BitPosition)
Insert the bits from a smaller known bits starting at bitPosition.
KnownBits extractBits (unsigned NumBits, unsigned BitPosition) const
Return a subset of the known bits from [bitPosition,bitPosition+numBits).
KnownBits makeGE (const APInt &Val) const
Return KnownBits based on this, but updated given that the underlying value is known to be greater than or equal to Val.
unsigned countMinTrailingZeros () const
Returns the minimum number of trailing zero bits.
unsigned countMinTrailingOnes () const
Returns the minimum number of trailing one bits.
unsigned countMinLeadingZeros () const
Returns the minimum number of leading zero bits.
unsigned countMinLeadingOnes () const
Returns the minimum number of leading one bits.
unsigned countMinSignBits () const
Returns the number of times the sign bit is replicated into the other bits.
unsigned countMaxSignificantBits () const
Returns the maximum number of bits needed to represent all possible signed values with these known bits.
unsigned countMaxTrailingZeros () const
Returns the maximum number of trailing zero bits possible.
unsigned countMaxTrailingOnes () const
Returns the maximum number of trailing one bits possible.
unsigned countMaxLeadingZeros () const
Returns the maximum number of leading zero bits possible.
unsigned countMaxLeadingOnes () const
Returns the maximum number of leading one bits possible.
unsigned countMinPopulation () const
Returns the number of bits known to be one.
unsigned countMaxPopulation () const
Returns the maximum number of bits that could be one.
unsigned countMaxActiveBits () const
Returns the maximum number of bits needed to represent all possible unsigned values with these known bits.
KnownBits & operator&= (const KnownBits &RHS)
Update known bits based on ANDing with RHS.
KnownBits & operator|= (const KnownBits &RHS)
Update known bits based on ORing with RHS.
KnownBits & operator^= (const KnownBits &RHS)
Update known bits based on XORing with RHS.
KnownBits abs (bool IntMinIsPoison=false) const
Compute known bits for the absolute value.
KnownBits byteSwap ()
KnownBits reverseBits ()
void print (raw_ostream &OS) const
void dump () const
Static Public Member Functions
static KnownBits makeConstant (const APInt &C)
Create known bits from a known constant.
static KnownBits commonBits (const KnownBits &LHS, const KnownBits &RHS)
Compute known bits common to LHS and RHS.
static bool haveNoCommonBitsSet (const KnownBits &LHS, const KnownBits &RHS)
Return true if LHS and RHS have no common bits set.
static KnownBits computeForAddCarry (const KnownBits &LHS, const KnownBits &RHS, const KnownBits &Carry)
Compute known bits resulting from adding LHS, RHS and a 1-bit Carry.
static KnownBits computeForAddSub (bool Add, bool NSW, const KnownBits &LHS, KnownBits RHS)
Compute known bits resulting from adding LHS and RHS.
static KnownBits mul (const KnownBits &LHS, const KnownBits &RHS, bool SelfMultiply=false)
Compute known bits resulting from multiplying LHS and RHS.
static KnownBits mulhs (const KnownBits &LHS, const KnownBits &RHS)
Compute known bits from sign-extended multiply-hi.
static KnownBits mulhu (const KnownBits &LHS, const KnownBits &RHS)
Compute known bits from zero-extended multiply-hi.
static KnownBits udiv (const KnownBits &LHS, const KnownBits &RHS)
Compute known bits for udiv(LHS, RHS).
static KnownBits urem (const KnownBits &LHS, const KnownBits &RHS)
Compute known bits for urem(LHS, RHS).
static KnownBits srem (const KnownBits &LHS, const KnownBits &RHS)
Compute known bits for srem(LHS, RHS).
static KnownBits umax (const KnownBits &LHS, const KnownBits &RHS)
Compute known bits for umax(LHS, RHS).
static KnownBits umin (const KnownBits &LHS, const KnownBits &RHS)
Compute known bits for umin(LHS, RHS).
static KnownBits smax (const KnownBits &LHS, const KnownBits &RHS)
Compute known bits for smax(LHS, RHS).
static KnownBits smin (const KnownBits &LHS, const KnownBits &RHS)
Compute known bits for smin(LHS, RHS).
static KnownBits shl (const KnownBits &LHS, const KnownBits &RHS)
Compute known bits for shl(LHS, RHS).
static KnownBits lshr (const KnownBits &LHS, const KnownBits &RHS)
Compute known bits for lshr(LHS, RHS).
static KnownBits ashr (const KnownBits &LHS, const KnownBits &RHS)
Compute known bits for ashr(LHS, RHS).
static Optional< bool > eq (const KnownBits &LHS, const KnownBits &RHS)
Determine if these known bits always give the same ICMP_EQ result.
static Optional< bool > ne (const KnownBits &LHS, const KnownBits &RHS)
Determine if these known bits always give the same ICMP_NE result.
static Optional< bool > ugt (const KnownBits &LHS, const KnownBits &RHS)
Determine if these known bits always give the same ICMP_UGT result.
static Optional< bool > uge (const KnownBits &LHS, const KnownBits &RHS)
Determine if these known bits always give the same ICMP_UGE result.
static Optional< bool > ult (const KnownBits &LHS, const KnownBits &RHS)
Determine if these known bits always give the same ICMP_ULT result.
static Optional< bool > ule (const KnownBits &LHS, const KnownBits &RHS)
Determine if these known bits always give the same ICMP_ULE result.
static Optional< bool > sgt (const KnownBits &LHS, const KnownBits &RHS)
Determine if these known bits always give the same ICMP_SGT result.
static Optional< bool > sge (const KnownBits &LHS, const KnownBits &RHS)
Determine if these known bits always give the same ICMP_SGE result.
static Optional< bool > slt (const KnownBits &LHS, const KnownBits &RHS)
Determine if these known bits always give the same ICMP_SLT result.
static Optional< bool > sle (const KnownBits &LHS, const KnownBits &RHS)
Determine if these known bits always give the same ICMP_SLE result.
Public Attributes
APInt Zero
APInt One
Detailed Description
Definition at line 23 of file KnownBits.h.
Constructor & Destructor Documentation
KnownBits() [1/2]
llvm::KnownBits::KnownBits () default
Referenced by anyext(), byteSwap(), commonBits(), extractBits(), makeConstant(), makeGE(), reverseBits(), sext(), smax(), smin(), trunc(), umin(), and zext().
KnownBits() [2/2]
llvm::KnownBits::KnownBits (unsigned BitWidth) inline
Create a known bits object of BitWidth bits initialized to unknown.
Definition at line 37 of file KnownBits.h.
Member Function Documentation
abs()
KnownBits KnownBits::abs (bool IntMinIsPoison = false) const
Compute known bits for the absolute value.
Definition at line 395 of file KnownBits.cpp.
References countMinTrailingZeros(), getBitWidth(), llvm::APInt::isMinSignedValue(), isNonNegative(), llvm::APInt::isZero(), One, llvm::APInt::setLowBits(), llvm::APInt::setSignBit(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), and computeKnownBitsFromOperator().
anyext()
KnownBits llvm::KnownBits::anyext (unsigned BitWidth) const inline
Return known bits for an "any" extension of the value we're tracking, where we don't know anything about the extended bits.
Definition at line 158 of file KnownBits.h.
References llvm::BitWidth, KnownBits(), One, Zero, and llvm::APInt::zext().
Referenced by anyextOrTrunc(), llvm::SelectionDAG::computeKnownBits(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::FunctionLoweringInfo::GetLiveOutRegInfo(), and llvm::TargetLowering::SimplifyDemandedBits().
anyextOrTrunc()
KnownBits llvm::KnownBits::anyextOrTrunc (unsigned BitWidth) const inline
Return known bits for an "any" extension or truncation of the value we're tracking.
Definition at line 177 of file KnownBits.h.
References anyext(), llvm::BitWidth, getBitWidth(), and trunc().
Referenced by llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), and llvm::TargetLowering::SimplifyDemandedBits().
ashr()
KnownBits KnownBits::ashr (const KnownBits & LHS, const KnownBits & RHS) static
Compute known bits for ashr(LHS, RHS).
NOTE: RHS (shift amount) bitwidth doesn't need to be the same as LHS.
Definition at line 274 of file KnownBits.cpp.
References llvm::APInt::ashrInPlace(), assert(), llvm::BitWidth, commonBits(), llvm::APInt::getZExtValue(), isUnknown(), LHS, llvm::min(), One, RHS, llvm::APInt::setAllBits(), llvm::APInt::setHighBits(), llvm::APInt::ult(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), and llvm::GISelKnownBits::computeKnownBitsImpl().
byteSwap()
KnownBits llvm::KnownBits::byteSwap () inline
Definition at line 410 of file KnownBits.h.
References llvm::APInt::byteSwap(), KnownBits(), One, and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), and llvm::GISelKnownBits::computeKnownBitsImpl().
commonBits()
static KnownBits llvm::KnownBits::commonBits (const KnownBits & LHS, const KnownBits & RHS) inline static
Compute known bits common to LHS and RHS.
Definition at line 308 of file KnownBits.h.
References KnownBits(), LHS, and RHS.
Referenced by ashr(), llvm::SelectionDAG::computeKnownBits(), computeKnownBitsBinOp(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::LanaiTargetLowering::computeKnownBitsForTargetNode(), llvm::SparcTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), computeKnownBitsFromShiftOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), lshr(), shl(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), and umax().
computeForAddCarry()
KnownBits KnownBits::computeForAddCarry (const KnownBits & LHS, const KnownBits & RHS, const KnownBits & Carry) static
Compute known bits resulting from adding LHS, RHS and a 1-bit Carry.
Definition at line 50 of file KnownBits.cpp.
References assert(), computeForAddCarry(), getBitWidth(), llvm::APInt::getBoolValue(), LHS, One, RHS, and Zero.
Referenced by computeForAddSub(), and llvm::SelectionDAG::computeKnownBits().
computeForAddSub()
KnownBits KnownBits::computeForAddSub (bool Add, bool NSW, const KnownBits & LHS, KnownBits RHS) static
Compute known bits resulting from adding LHS and RHS.
Definition at line 57 of file KnownBits.cpp.
References computeForAddCarry(), isNegative(), isNonNegative(), LHS, makeNegative(), makeNonNegative(), RHS, and std::swap().
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsAddSub(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), and llvm::InstCombinerImpl::SimplifyDemandedUseBits().
countMaxActiveBits()
unsigned llvm::KnownBits::countMaxActiveBits () const inline
Returns the maximum number of bits needed to represent all possible unsigned values with these known bits.
This is the inverse of the minimum number of leading zeros.
Definition at line 298 of file KnownBits.h.
References countMinLeadingZeros(), and getBitWidth().
Referenced by combinePMULH(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), detectAVGPattern(), detectExtMul(), getPack(), llvm::CombinerHelper::matchCombineTruncOfShl(), llvm::AMDGPUTargetLowering::numBitsUnsigned(), llvm::AMDGPUTargetLowering::performTruncateCombine(), SimplifyAndInst(), and SimplifyLShrInst().
countMaxLeadingOnes()
unsigned llvm::KnownBits::countMaxLeadingOnes () const inline
Returns the maximum number of leading one bits possible.
Definition at line 281 of file KnownBits.h.
References llvm::APInt::countLeadingZeros(), and Zero.
countMaxLeadingZeros()
unsigned llvm::KnownBits::countMaxLeadingZeros () const inline
Returns the maximum number of leading zero bits possible.
Definition at line 276 of file KnownBits.h.
References llvm::APInt::countLeadingZeros(), and One.
Referenced by llvm::SelectionDAG::computeKnownBits(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), foldCttzCtlz(), and isKnownNonZero().
countMaxPopulation()
unsigned llvm::KnownBits::countMaxPopulation () const inline
Returns the maximum number of bits that could be one.
Definition at line 291 of file KnownBits.h.
References llvm::APInt::countPopulation(), getBitWidth(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), foldCtpop(), llvm::InstCombinerImpl::foldICmpWithZero(), llvm::isKnownToBeAPowerOfTwo(), llvm::SelectionDAG::isKnownToBeAPowerOfTwo(), and llvm::TargetLowering::SimplifySetCC().
countMaxSignificantBits()
unsigned llvm::KnownBits::countMaxSignificantBits () const inline
Returns the maximum number of bits needed to represent all possible signed values with these known bits.
This is the inverse of the minimum number of known sign bits. Examples for bitwidth 5: 110?? --> 4 0000? --> 2
Definition at line 261 of file KnownBits.h.
References countMinSignBits(), and getBitWidth().
Referenced by llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode().
countMaxTrailingOnes()
unsigned llvm::KnownBits::countMaxTrailingOnes () const inline
Returns the maximum number of trailing one bits possible.
Definition at line 271 of file KnownBits.h.
References llvm::APInt::countTrailingZeros(), and Zero.
countMaxTrailingZeros()
unsigned llvm::KnownBits::countMaxTrailingZeros () const inline
Returns the maximum number of trailing zero bits possible.
Definition at line 266 of file KnownBits.h.
References llvm::APInt::countTrailingZeros(), and One.
Referenced by llvm::SelectionDAG::computeKnownBits(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), and foldCttzCtlz().
countMinLeadingOnes()
unsigned llvm::KnownBits::countMinLeadingOnes () const inline
Returns the minimum number of leading one bits.
Definition at line 241 of file KnownBits.h.
References llvm::APInt::countLeadingOnes(), and One.
Referenced by computeKnownBitsFromOperator(), countMinSignBits(), llvm::GCNTTIImpl::rewriteIntrinsicWithAddressSpace(), and llvm::InstCombinerImpl::visitSwitchInst().
countMinLeadingZeros()
unsigned llvm::KnownBits::countMinLeadingZeros () const inline
Returns the minimum number of leading zero bits.
Definition at line 236 of file KnownBits.h.
References llvm::APInt::countLeadingOnes(), and Zero.
Referenced by combineVectorSignBitsTruncation(), llvm::SelectionDAG::computeKnownBits(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromAssume(), computeKnownBitsFromOperator(), countMaxActiveBits(), countMinSignBits(), llvm::TargetLowering::expandFixedPointDiv(), foldCttzCtlz(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), llvm::RegsForValue::getCopyFromRegs(), LowerAndToBT(), llvm::CombinerHelper::matchCombineZextTrunc(), llvm::AMDGPUTargetLowering::performShlCombine(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), llvm::InstCombinerImpl::visitCallInst(), and llvm::InstCombinerImpl::visitSwitchInst().
countMinPopulation()
unsigned llvm::KnownBits::countMinPopulation () const inline
Returns the number of bits known to be one.
Definition at line 286 of file KnownBits.h.
References llvm::APInt::countPopulation(), and One.
Referenced by foldCtpop(), llvm::InstCombinerImpl::foldICmpWithZero(), llvm::isKnownToBeAPowerOfTwo(), llvm::SelectionDAG::isKnownToBeAPowerOfTwo(), and llvm::TargetLowering::SimplifySetCC().
countMinSignBits()
unsigned llvm::KnownBits::countMinSignBits () const inline
Returns the number of times the sign bit is replicated into the other bits.
Definition at line 247 of file KnownBits.h.
References countMinLeadingOnes(), countMinLeadingZeros(), isNegative(), and isNonNegative().
Referenced by llvm::SelectionDAG::ComputeNumSignBits(), ComputeNumSignBitsImpl(), and countMaxSignificantBits().
countMinTrailingOnes()
unsigned llvm::KnownBits::countMinTrailingOnes () const inline
Returns the minimum number of trailing one bits.
Definition at line 231 of file KnownBits.h.
References llvm::APInt::countTrailingOnes(), and One.
Referenced by computeKnownBitsFromOperator().
countMinTrailingZeros()
unsigned llvm::KnownBits::countMinTrailingZeros () const inline
Returns the minimum number of trailing zero bits.
Definition at line 226 of file KnownBits.h.
References llvm::APInt::countTrailingOnes(), and Zero.
Referenced by abs(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), llvm::TargetLowering::expandFixedPointDiv(), foldCttzCtlz(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), llvm::getOrEnforceKnownAlignment(), llvm::SelectionDAG::InferPtrAlign(), isKnownNonZero(), isWordAligned(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), SimplifyShift(), and llvm::InstCombinerImpl::visitCallInst().
dump()
void KnownBits::dump () const
Definition at line 629 of file KnownBits.cpp.
References llvm::dbgs(), and print().
eq()
Optional< bool > KnownBits::eq (const KnownBits & LHS, const KnownBits & RHS) static
Determine if these known bits always give the same ICMP_EQ result.
Definition at line 333 of file KnownBits.cpp.
References LHS, llvm::None, and RHS.
Referenced by llvm::CombinerHelper::matchICmpToTrueFalseKnownBits(), and ne().
extractBits()
KnownBits llvm::KnownBits::extractBits (unsigned NumBits, unsigned BitPosition) const inline
Return a subset of the known bits from [bitPosition,bitPosition+numBits).
Definition at line 216 of file KnownBits.h.
References llvm::APInt::extractBits(), KnownBits(), One, and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), llvm::GISelKnownBits::computeKnownBitsImpl(), mulhs(), mulhu(), and llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode().
getBitWidth()
unsigned llvm::KnownBits::getBitWidth () const inline
Get the bit width of this value.
Definition at line 40 of file KnownBits.h.
References assert(), llvm::APInt::getBitWidth(), One, and Zero.
Referenced by abs(), anyextOrTrunc(), computeForAddCarry(), computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::LanaiTargetLowering::computeKnownBitsForTargetNode(), llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromAssume(), computeKnownBitsFromOperator(), llvm::computeKnownBitsFromRangeMetadata(), computeKnownBitsFromShiftOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), countMaxActiveBits(), countMaxPopulation(), countMaxSignificantBits(), eliminateDeadSwitchCases(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), llvm::ConstantRange::fromKnownBits(), llvm::FunctionLoweringInfo::GetLiveOutRegInfo(), llvm::getOrEnforceKnownAlignment(), isConstant(), makeGE(), sextInReg(), sextOrTrunc(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), SimplifyShift(), smax(), smin(), tryBitfieldInsertOpFromOr(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitSwitchInst(), zext(), and zextOrTrunc().
getConstant()
const APInt& llvm::KnownBits::getConstant () const inline
Returns the value when all bits have a known value.
This just returns One with a protective assertion.
Definition at line 57 of file KnownBits.h.
References assert(), isConstant(), and One.
Referenced by combineMOVMSK(), computeKnownBitsFromOperator(), llvm::AMDGPUTargetLowering::performTruncateCombine(), and llvm::InstCombinerImpl::visitReturnInst().
getMaxValue()
APInt llvm::KnownBits::getMaxValue () const inline
Return the maximal unsigned value possible given these KnownBits.
Definition at line 136 of file KnownBits.h.
References Zero.
Referenced by canEvaluateTruncated(), computeKnownBitsFromShiftOperator(), llvm::SelectionDAG::computeOverflowKind(), extractBits(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), llvm::ConstantRange::fromKnownBits(), matchFunnelShift(), and simplifyX86immShift().
getMinValue()
APInt llvm::KnownBits::getMinValue () const inline
Return the minimal unsigned value possible given these KnownBits.
Definition at line 120 of file KnownBits.h.
References One.
Referenced by extractBits(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), llvm::ConstantRange::fromKnownBits(), SimplifyShift(), and simplifyX86immShift().
getSignedMaxValue()
APInt llvm::KnownBits::getSignedMaxValue () const inline
Return the maximal signed value possible given these KnownBits.
Definition at line 142 of file KnownBits.h.
References llvm::APInt::isSignBitClear(), One, and Zero.
Referenced by llvm::InstCombinerImpl::foldICmpUsingKnownBits().
getSignedMinValue()
APInt llvm::KnownBits::getSignedMinValue () const inline
Return the minimal signed value possible given these KnownBits.
Definition at line 126 of file KnownBits.h.
References llvm::APInt::isSignBitClear(), One, llvm::APInt::setSignBit(), and Zero.
Referenced by llvm::InstCombinerImpl::foldICmpUsingKnownBits().
hasConflict()
bool llvm::KnownBits::hasConflict () const inline
Returns true if there is conflicting information.
Definition at line 47 of file KnownBits.h.
References llvm::APInt::intersects(), One, and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromShiftOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::ConstantRange::fromKnownBits(), isAllOnes(), isConstant(), isZero(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), and SimplifyShift().
haveNoCommonBitsSet()
static bool llvm::KnownBits::haveNoCommonBitsSet (const KnownBits & LHS, const KnownBits & RHS) inline static
Return true if LHS and RHS have no common bits set.
Definition at line 313 of file KnownBits.h.
References LHS, and RHS.
Referenced by llvm::haveNoCommonBitsSet(), and llvm::SelectionDAG::haveNoCommonBitsSet().
insertBits()
void llvm::KnownBits::insertBits (const KnownBits & SubBits, unsigned BitPosition) inline
Insert the bits from a smaller known bits starting at bitPosition.
Definition at line 210 of file KnownBits.h.
References llvm::APInt::insertBits(), One, and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromOperator(), and llvm::GISelKnownBits::computeKnownBitsImpl().
isAllOnes()
bool llvm::KnownBits::isAllOnes () const inline
Returns true if value is all one bits.
Definition at line 78 of file KnownBits.h.
References assert(), hasConflict(), llvm::APInt::isAllOnes(), and One.
Referenced by computeKnownBitsFromAssume(), isTruncateOf(), matchBinaryShuffle(), and llvm::InstCombinerImpl::visitCallInst().
isConstant()
bool llvm::KnownBits::isConstant () const inline
Returns true if we know the value of all bits.
Definition at line 50 of file KnownBits.h.
References assert(), llvm::APInt::countPopulation(), getBitWidth(), hasConflict(), One, and Zero.
Referenced by combineMOVMSK(), computeKnownBitsFromOperator(), computeKnownBitsFromShiftOperator(), getConstant(), llvm::AMDGPUTargetLowering::performTruncateCombine(), and llvm::InstCombinerImpl::visitReturnInst().
isNegative()
bool llvm::KnownBits::isNegative () const inline
Returns true if this value is known to be negative.
Definition at line 96 of file KnownBits.h.
References llvm::APInt::isSignBitSet(), and One.
Referenced by computeForAddSub(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromAssume(), computeKnownBitsFromOperator(), computeKnownBitsMul(), llvm::GISelKnownBits::computeNumSignBits(), computeOverflowForSignedAdd(), countMinSignBits(), llvm::ConstantRange::fromKnownBits(), getKnownSign(), getSign32(), llvm::isKnownNegative(), isKnownNonZero(), simplifyICmpWithBinOpOnLHS(), and simplifyICmpWithZero().
isNonNegative()
bool llvm::KnownBits::isNonNegative () const inline
Returns true if this value is known to be non-negative.
Definition at line 99 of file KnownBits.h.
References llvm::APInt::isSignBitSet(), and Zero.
Referenced by abs(), canReplaceGEPIdxWithZero(), computeForAddSub(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromAssume(), computeKnownBitsFromOperator(), computeKnownBitsMul(), llvm::slpvectorizer::BoUpSLP::computeMinimumValueSizes(), llvm::GISelKnownBits::computeNumSignBits(), llvm::SelectionDAG::ComputeNumSignBits(), ComputeNumSignBitsImpl(), computeOverflowForSignedAdd(), llvm::computeOverflowForSignedMul(), countMinSignBits(), llvm::ConstantRange::fromKnownBits(), getKnownSign(), getSign32(), llvm::isKnownNonNegative(), isKnownNonZero(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), simplifyICmpWithBinOpOnLHS(), simplifyICmpWithZero(), llvm::InstCombinerImpl::simplifyRangeCheck(), and llvm::InstCombinerImpl::visitSExt().
isNonZero()
bool llvm::KnownBits::isNonZero () const inline
Returns true if this value is known to be non-zero.
Definition at line 102 of file KnownBits.h.
References llvm::APInt::isZero(), and One.
Referenced by computeKnownBitsMul().
isStrictlyPositive()
bool llvm::KnownBits::isStrictlyPositive () const inline
Returns true if this value is known to be positive.
Definition at line 105 of file KnownBits.h.
References llvm::APInt::isSignBitSet(), llvm::APInt::isZero(), One, and Zero.
Referenced by llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode().
isUnknown()
bool llvm::KnownBits::isUnknown () const inline
Returns true if we don't know any bits.
Definition at line 63 of file KnownBits.h.
References llvm::APInt::isZero(), One, and Zero.
Referenced by llvm::FunctionLoweringInfo::AddLiveOutRegInfo(), ashr(), llvm::SelectionDAG::computeKnownBits(), computeKnownBitsAddSub(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::ConstantRange::fromKnownBits(), lshr(), and shl().
isZero()
bool llvm::KnownBits::isZero () const inline
Returns true if value is all zero.
Definition at line 72 of file KnownBits.h.
References assert(), hasConflict(), llvm::APInt::isAllOnes(), and Zero.
Referenced by computeKnownBitsFromAssume(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), isZero(), matchBinaryShuffle(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), and simplifyX86immShift().
lshr()
KnownBits KnownBits::lshr (const KnownBits & LHS, const KnownBits & RHS) static
Compute known bits for lshr(LHS, RHS).
NOTE: RHS (shift amount) bitwidth doesn't need to be the same as LHS.
Definition at line 221 of file KnownBits.cpp.
References assert(), llvm::BitWidth, commonBits(), llvm::APInt::getZExtValue(), isUnknown(), LHS, llvm::APInt::lshrInPlace(), llvm::min(), One, RHS, llvm::APInt::setAllBits(), llvm::APInt::setHighBits(), llvm::APInt::ult(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), and extractBits().
makeConstant()
static KnownBits llvm::KnownBits::makeConstant (const APInt & C) inline static
Create known bits from a known constant.
Definition at line 303 of file KnownBits.h.
References C, and KnownBits().
Referenced by computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), computeKnownBitsFromShiftOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), and llvm::TargetLowering::SimplifyDemandedBits().
makeGE()
KnownBits KnownBits::makeGE (const APInt & Val) const
Return KnownBits based on this, but updated given that the underlying value is known to be greater than or equal to Val.
Definition at line 105 of file KnownBits.cpp.
References llvm::APInt::clearLowBits(), llvm::countLeadingOnes(), getBitWidth(), KnownBits(), N, One, and Zero.
makeNegative()
void llvm::KnownBits::makeNegative () inline
Make this value negative.
Definition at line 110 of file KnownBits.h.
References One, and llvm::APInt::setSignBit().
Referenced by computeForAddSub(), computeKnownBitsFromAssume(), computeKnownBitsFromOperator(), and computeKnownBitsMul().
makeNonNegative()
void llvm::KnownBits::makeNonNegative () inline
Make this value non-negative.
Definition at line 115 of file KnownBits.h.
References llvm::APInt::setSignBit(), and Zero.
Referenced by computeForAddSub(), computeKnownBitsFromAssume(), computeKnownBitsFromOperator(), computeKnownBitsMul(), and llvm::InstCombinerImpl::SimplifyDemandedUseBits().
mul()
KnownBits KnownBits::mul (const KnownBits & LHS, const KnownBits & RHS, bool SelfMultiply = false) static
Compute known bits resulting from multiplying LHS and RHS.
Definition at line 415 of file KnownBits.cpp.
References assert(), llvm::BitWidth, llvm::APInt::countLeadingZeros(), llvm::countTrailingOnes(), llvm::APInt::getLoBits(), LHS, llvm::min(), One, RHS, llvm::APInt::setBit(), llvm::APInt::setHighBits(), llvm::APInt::umul_ov(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), computeKnownBitsMul(), mulhs(), and mulhu().
mulhs()
KnownBits KnownBits::mulhs (const KnownBits & LHS, const KnownBits & RHS) static
Compute known bits from sign-extended multiply-hi.
Definition at line 513 of file KnownBits.cpp.
References assert(), llvm::BitWidth, extractBits(), LHS, mul(), and RHS.
Referenced by llvm::SelectionDAG::computeKnownBits().
mulhu()
KnownBits KnownBits::mulhu (const KnownBits & LHS, const KnownBits & RHS) static
Compute known bits from zero-extended multiply-hi.
Definition at line 522 of file KnownBits.cpp.
References assert(), llvm::BitWidth, extractBits(), LHS, mul(), and RHS.
Referenced by llvm::SelectionDAG::computeKnownBits().
ne()
Optional< bool > KnownBits::ne (const KnownBits & LHS, const KnownBits & RHS) static
Determine if these known bits always give the same ICMP_NE result.
Definition at line 341 of file KnownBits.cpp.
References eq(), LHS, llvm::None, and RHS.
Referenced by llvm::CombinerHelper::matchICmpToTrueFalseKnownBits().
operator&=()
KnownBits & KnownBits::operator&= (const KnownBits & RHS)
Update known bits based on ANDing with RHS.
Definition at line 601 of file KnownBits.cpp.
References One, RHS, and Zero.
operator^=()
KnownBits & KnownBits::operator^= (const KnownBits & RHS)
Update known bits based on XORing with RHS.
Definition at line 617 of file KnownBits.cpp.
References llvm::move(), One, RHS, and Zero.
operator|=()
KnownBits & KnownBits::operator|= (const KnownBits & RHS)
Update known bits based on ORing with RHS.
Definition at line 609 of file KnownBits.cpp.
References One, RHS, and Zero.
print()
void KnownBits::print (raw_ostream & OS) const
Definition at line 626 of file KnownBits.cpp.
References One, and Zero.
Referenced by dump().
resetAll()
void llvm::KnownBits::resetAll () inline
Resets the known state of all bits.
Definition at line 66 of file KnownBits.h.
References llvm::APInt::clearAllBits(), One, and Zero.
Referenced by computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), llvm::TargetLowering::computeKnownBitsForTargetInstr(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), llvm::TargetLowering::computeKnownBitsForTargetNode(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::PPCTargetLowering::computeKnownBitsForTargetNode(), llvm::SparcTargetLowering::computeKnownBitsForTargetNode(), llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromAssume(), computeKnownBitsFromOperator(), computeKnownBitsFromShiftOperator(), and llvm::InstCombinerImpl::SimplifyDemandedUseBits().
reverseBits()
KnownBits llvm::KnownBits::reverseBits () inline
Definition at line 414 of file KnownBits.h.
References KnownBits(), One, llvm::APInt::reverseBits(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), and llvm::GISelKnownBits::computeKnownBitsImpl().
setAllOnes()
void llvm::KnownBits::setAllOnes () inline
Make all bits known to be one and discard any previous information.
Definition at line 90 of file KnownBits.h.
References llvm::APInt::clearAllBits(), One, llvm::APInt::setAllBits(), and Zero.
Referenced by computeKnownBitsFromAssume().
setAllZero()
void llvm::KnownBits::setAllZero () inline
Make all bits known to be zero and discard any previous information.
Definition at line 84 of file KnownBits.h.
References llvm::APInt::clearAllBits(), One, llvm::APInt::setAllBits(), and Zero.
Referenced by computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromAssume(), computeKnownBitsFromShiftOperator(), and llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode().
sext()
KnownBits llvm::KnownBits::sext (unsigned BitWidth) const inline
Return known bits for a sign extension of the value we're tracking.
Definition at line 171 of file KnownBits.h.
References llvm::BitWidth, KnownBits(), One, llvm::APInt::sext(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), sextOrTrunc(), llvm::TargetLowering::SimplifyDemandedBits(), and llvm::InstCombinerImpl::SimplifyDemandedUseBits().
sextInReg()
KnownBits KnownBits::sextInReg (unsigned SrcBitWidth) const
Return known bits for a in-register sign extension of the value we're tracking.
Definition at line 88 of file KnownBits.cpp.
References assert(), llvm::BitWidth, getBitWidth(), One, and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), and llvm::GISelKnownBits::computeKnownBitsImpl().
sextOrTrunc()
KnownBits llvm::KnownBits::sextOrTrunc (unsigned BitWidth) const inline
Return known bits for a sign extension or truncation of the value we're tracking.
Definition at line 197 of file KnownBits.h.
References llvm::BitWidth, getBitWidth(), sext(), and trunc().
Referenced by computeKnownBitsFromOperator().
sge()
Optional< bool > KnownBits::sge (const KnownBits & LHS, const KnownBits & RHS) static
Determine if these known bits always give the same ICMP_SGE result.
Definition at line 381 of file KnownBits.cpp.
References LHS, llvm::None, RHS, and sgt().
Referenced by llvm::CombinerHelper::matchICmpToTrueFalseKnownBits(), and sle().
sgt()
Optional< bool > KnownBits::sgt (const KnownBits & LHS, const KnownBits & RHS) static
Determine if these known bits always give the same ICMP_SGT result.
Definition at line 371 of file KnownBits.cpp.
References LHS, llvm::None, and RHS.
Referenced by llvm::CombinerHelper::matchICmpToTrueFalseKnownBits(), sge(), and slt().
shl()
KnownBits KnownBits::shl (const KnownBits & LHS, const KnownBits & RHS) static
Compute known bits for shl(LHS, RHS).
NOTE: RHS (shift amount) bitwidth doesn't need to be the same as LHS.
Definition at line 167 of file KnownBits.cpp.
References assert(), llvm::BitWidth, commonBits(), llvm::APInt::getZExtValue(), isUnknown(), LHS, llvm::min(), One, RHS, llvm::APInt::setAllBits(), llvm::APInt::setLowBits(), llvm::APInt::ult(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), and SimplifyShift().
sle()
Optional< bool > KnownBits::sle (const KnownBits & LHS, const KnownBits & RHS) static
Determine if these known bits always give the same ICMP_SLE result.
Definition at line 391 of file KnownBits.cpp.
References LHS, RHS, and sge().
Referenced by llvm::CombinerHelper::matchICmpToTrueFalseKnownBits().
slt()
Optional< bool > KnownBits::slt (const KnownBits & LHS, const KnownBits & RHS) static
Determine if these known bits always give the same ICMP_SLT result.
Definition at line 387 of file KnownBits.cpp.
References LHS, RHS, and sgt().
Referenced by llvm::CombinerHelper::matchICmpToTrueFalseKnownBits().
smax()
KnownBits KnownBits::smax (const KnownBits & LHS, const KnownBits & RHS) static
Compute known bits for smax(LHS, RHS).
Definition at line 141 of file KnownBits.cpp.
References getBitWidth(), KnownBits(), LHS, One, RHS, llvm::APInt::setBitVal(), umax(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromOperator(), and llvm::GISelKnownBits::computeKnownBitsImpl().
smin()
KnownBits KnownBits::smin (const KnownBits & LHS, const KnownBits & RHS) static
Compute known bits for smin(LHS, RHS).
Definition at line 154 of file KnownBits.cpp.
References getBitWidth(), KnownBits(), LHS, One, RHS, llvm::APInt::setBitVal(), umax(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromOperator(), and llvm::GISelKnownBits::computeKnownBitsImpl().
srem()
KnownBits KnownBits::srem (const KnownBits & LHS, const KnownBits & RHS) static
Compute known bits for srem(LHS, RHS).
Definition at line 570 of file KnownBits.cpp.
References assert(), llvm::BitWidth, llvm::APInt::intersects(), llvm::APInt::isSubsetOf(), LHS, One, RHS, llvm::APInt::setHighBits(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), and computeKnownBitsFromOperator().
trunc()
KnownBits llvm::KnownBits::trunc (unsigned BitWidth) const inline
Return known bits for a truncation of the value we're tracking.
Definition at line 152 of file KnownBits.h.
References llvm::BitWidth, KnownBits(), One, llvm::APInt::trunc(), and Zero.
Referenced by anyextOrTrunc(), llvm::SelectionDAG::computeKnownBits(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), sextOrTrunc(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), and zextOrTrunc().
udiv()
KnownBits KnownBits::udiv (const KnownBits & LHS, const KnownBits & RHS) static
Compute known bits for udiv(LHS, RHS).
Definition at line 531 of file KnownBits.cpp.
References assert(), llvm::BitWidth, LHS, llvm::min(), RHS, llvm::APInt::setHighBits(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), and computeKnownBitsFromOperator().
uge()
Optional< bool > KnownBits::uge (const KnownBits & LHS, const KnownBits & RHS) static
Determine if these known bits always give the same ICMP_UGE result.
Definition at line 357 of file KnownBits.cpp.
References LHS, llvm::None, RHS, and ugt().
Referenced by llvm::CombinerHelper::matchICmpToTrueFalseKnownBits(), llvm::TargetLowering::SimplifyDemandedBits(), and ule().
ugt()
Optional< bool > KnownBits::ugt (const KnownBits & LHS, const KnownBits & RHS) static
Determine if these known bits always give the same ICMP_UGT result.
Definition at line 347 of file KnownBits.cpp.
References LHS, llvm::None, and RHS.
Referenced by llvm::CombinerHelper::matchICmpToTrueFalseKnownBits(), llvm::TargetLowering::SimplifyDemandedBits(), uge(), and ult().
ule()
Optional< bool > KnownBits::ule (const KnownBits & LHS, const KnownBits & RHS) static
Determine if these known bits always give the same ICMP_ULE result.
Definition at line 367 of file KnownBits.cpp.
References LHS, RHS, and uge().
Referenced by llvm::CombinerHelper::matchICmpToTrueFalseKnownBits(), and llvm::TargetLowering::SimplifyDemandedBits().
ult()
Optional< bool > KnownBits::ult (const KnownBits & LHS, const KnownBits & RHS) static
Determine if these known bits always give the same ICMP_ULT result.
Definition at line 363 of file KnownBits.cpp.
References LHS, RHS, and ugt().
Referenced by llvm::CombinerHelper::matchICmpToTrueFalseKnownBits(), and llvm::TargetLowering::SimplifyDemandedBits().
umax()
KnownBits KnownBits::umax (const KnownBits & LHS, const KnownBits & RHS) static
Compute known bits for umax(LHS, RHS).
Definition at line 117 of file KnownBits.cpp.
References commonBits(), LHS, and RHS.
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::TargetLowering::SimplifyDemandedBits(), smax(), smin(), and umin().
umin()
KnownBits KnownBits::umin (const KnownBits & LHS, const KnownBits & RHS) static
Compute known bits for umin(LHS, RHS).
Definition at line 135 of file KnownBits.cpp.
References KnownBits(), LHS, RHS, and umax().
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), and llvm::TargetLowering::SimplifyDemandedBits().
urem()
KnownBits KnownBits::urem (const KnownBits & LHS, const KnownBits & RHS) static
Compute known bits for urem(LHS, RHS).
Definition at line 549 of file KnownBits.cpp.
References assert(), llvm::BitWidth, LHS, llvm::max(), One, RHS, llvm::APInt::setHighBits(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), and computeKnownBitsFromOperator().
zext()
KnownBits llvm::KnownBits::zext (unsigned BitWidth) const inline
Return known bits for a zero extension of the value we're tracking.
Definition at line 163 of file KnownBits.h.
References llvm::BitWidth, getBitWidth(), KnownBits(), One, llvm::APInt::setBitsFrom(), Zero, and llvm::APInt::zext().
Referenced by llvm::SelectionDAG::computeKnownBits(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), and zextOrTrunc().
zextOrTrunc()
KnownBits llvm::KnownBits::zextOrTrunc (unsigned BitWidth) const inline
Return known bits for a zero extension or truncation of the value we're tracking.
Definition at line 187 of file KnownBits.h.
References llvm::BitWidth, getBitWidth(), trunc(), and zext().
Referenced by llvm::SelectionDAG::computeKnownBits(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), and llvm::InstCombinerImpl::SimplifyDemandedUseBits().
Member Data Documentation
One
APInt llvm::KnownBits::One
Definition at line 25 of file KnownBits.h.
Referenced by abs(), llvm::FunctionLoweringInfo::AddLiveOutRegInfo(), anyext(), ashr(), byteSwap(), llvm::SelectionDAGISel::CheckOrMask(), computeForAddCarry(), computeForAddCarry(), computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromAssume(), computeKnownBitsFromOperator(), llvm::computeKnownBitsFromRangeMetadata(), computeKnownBitsFromShiftOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::GISelKnownBits::computeNumSignBits(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), countMaxLeadingZeros(), countMaxTrailingZeros(), countMinLeadingOnes(), countMinPopulation(), countMinTrailingOnes(), llvm::DemandedBits::determineLiveOperandBitsSub(), dumpResult(), eliminateDeadSwitchCases(), extractBits(), foldCttzCtlz(), llvm::InstCombinerImpl::foldICmpTruncConstant(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), getBitWidth(), getConstant(), llvm::GISelKnownBits::getKnownOnes(), getMinValue(), getSignedMaxValue(), getSignedMinValue(), getValueFromICmpCondition(), hasConflict(), insertBits(), isAllOnes(), isConstant(), isKnownNonEqual(), isKnownNonZero(), isKnownToBeAPowerOfTwo(), isNegative(), isNonZero(), isStrictlyPositive(), isUnknown(), lshr(), makeGE(), makeNegative(), matchBinaryShuffle(), llvm::CombinerHelper::matchRedundantAnd(), llvm::CombinerHelper::matchRedundantOr(), mul(), operator&=(), operator^=(), operator|=(), print(), resetAll(), reverseBits(), setAllOnes(), setAllZero(), sext(), sextInReg(), shl(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), llvm::InstCombinerImpl::SimplifyMultipleUseDemandedBits(), llvm::TargetLowering::SimplifyMultipleUseDemandedBits(), SimplifyRightShift(), SimplifyShift(), llvm::InstCombinerImpl::simplifyShrShlDemandedBits(), smax(), smin(), srem(), trunc(), urem(), and zext().
Zero
APInt llvm::KnownBits::Zero
Definition at line 24 of file KnownBits.h.
Referenced by abs(), llvm::FunctionLoweringInfo::AddLiveOutRegInfo(), adjustForRedundantAnd(), anyext(), ashr(), byteSwap(), computeForAddCarry(), computeForAddCarry(), computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), llvm::GISelKnownBits::computeKnownBitsForAlignment(), llvm::TargetLowering::computeKnownBitsForFrameIndex(), llvm::SITargetLowering::computeKnownBitsForFrameIndex(), llvm::SITargetLowering::computeKnownBitsForTargetInstr(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::LanaiTargetLowering::computeKnownBitsForTargetNode(), llvm::PPCTargetLowering::computeKnownBitsForTargetNode(), llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromAssume(), computeKnownBitsFromOperator(), llvm::computeKnownBitsFromRangeMetadata(), computeKnownBitsFromShiftOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::GISelKnownBits::computeNumSignBits(), llvm::SelectionDAG::ComputeNumSignBits(), ComputeNumSignBitsImpl(), llvm::SelectionDAG::computeOverflowKind(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), countMaxLeadingOnes(), countMaxPopulation(), countMaxTrailingOnes(), countMinLeadingZeros(), countMinTrailingZeros(), llvm::DemandedBits::determineLiveOperandBitsSub(), dumpResult(), eliminateDeadSwitchCases(), extractBits(), llvm::InstCombinerImpl::foldAddWithConstant(), foldCtpop(), llvm::InstCombinerImpl::foldICmpTruncConstant(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), foldMaskAndShiftToScale(), getBitWidth(), llvm::GISelKnownBits::getKnownZeroes(), getMaxValue(), getSignedMaxValue(), getSignedMinValue(), getValueFromICmpCondition(), hasConflict(), insertBits(), isBitfieldPositioningOp(), isConstant(), isKnownNonEqual(), isKnownToBeAPowerOfTwo(), isNonNegative(), isStrictlyPositive(), isTruePredicate(), isTruncateOf(), isUnknown(), isZero(), knownBitsForWorkitemID(), LowerMUL(), lshr(), makeGE(), makeNonNegative(), MaskedValueIsZero(), matchBinaryShuffle(), llvm::CombinerHelper::matchRedundantAnd(), llvm::CombinerHelper::matchRedundantOr(), matchRotateSub(), mul(), operator&=(), operator^=(), operator|=(), llvm::ARMTargetLowering::PerformCMOVCombine(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), print(), provablyDisjointOr(), resetAll(), reverseBits(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::PPCTargetLowering::SelectAddressRegImm34(), llvm::PPCTargetLowering::SelectAddressRegReg(), llvm::RISCVDAGToDAGISel::selectShiftMask(), setAllOnes(), setAllZero(), sext(), sextInReg(), shl(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), llvm::X86TTIImpl::simplifyDemandedUseBitsIntrinsic(), llvm::InstCombinerImpl::SimplifyMultipleUseDemandedBits(), llvm::TargetLowering::SimplifyMultipleUseDemandedBits(), SimplifyShift(), llvm::InstCombinerImpl::simplifyShrShlDemandedBits(), SimplifySubInst(), smax(), smin(), srem(), trunc(), tryBitfieldInsertOpFromOr(), tryBitfieldInsertOpFromOrAndImm(), udiv(), urem(), llvm::InstCombinerImpl::visitSub(), and zext().
The documentation for this struct was generated from the following files:
include/llvm/Support/KnownBits.h
lib/Support/KnownBits.cpp