LLVM: AANoCaptureImpl Struct Reference
AANoCaptureImpl Struct Reference
--------------------— Variable Capturing ------------------------------—
Public Member Functions
AANoCaptureImpl (const IRPosition &IRP, Attributor &A)
void initialize (Attributor &A) override
See AbstractAttribute::initialize(...).
ChangeStatus updateImpl (Attributor &A) override
See AbstractAttribute::updateImpl(...).
virtual void getDeducedAttributes (LLVMContext &Ctx, SmallVectorImpl< Attribute > &Attrs) const override
see AbstractAttribute::isAssumedNoCaptureMaybeReturned(...).
const std::string getAsStr () const override
See AbstractState::getAsStr().
Public Member Functions inherited from llvm::AANoCapture
AANoCapture (const IRPosition &IRP, Attributor &A)
bool isKnownNoCapture () const
Return true if we know that the underlying value is not captured in its respective scope.
bool isAssumedNoCapture () const
Return true if we assume that the underlying value is not captured in its respective scope.
bool isKnownNoCaptureMaybeReturned () const
Return true if we know that the underlying value is not captured in its respective scope but we allow it to escape through a "return".
bool isAssumedNoCaptureMaybeReturned () const
Return true if we assume that the underlying value is not captured in its respective scope but we allow it to escape through a "return".
const std::string getName () const override
See AbstractAttribute::getName()
const char * getIdAddr () const override
See AbstractAttribute::getIdAddr()
Public Member Functions inherited from llvm::IRAttribute< Attribute::NoCapture, StateWrapper< BitIntegerState< uint16_t, 7, 0 >, AbstractAttribute > >
IRAttribute (const IRPosition &IRP)
ChangeStatus manifest (Attributor &A) override
See AbstractAttribute::manifest(...).
Attribute::AttrKind getAttrKind () const
Return the kind that identifies the abstract attribute implementation.
Public Member Functions inherited from llvm::StateWrapper< StateTy, BaseType, Ts >
StateWrapper (const IRPosition &IRP, Ts... Args)
StateType & getState () override
See AbstractAttribute::getState(...).
const StateType & getState () const override
See AbstractAttribute::getState(...).
Static Public Member Functions
static void determineFunctionCaptureCapabilities (const IRPosition &IRP, const Function &F, BitIntegerState &State)
Set the NOT_CAPTURED_IN_MEM and NOT_CAPTURED_IN_RET bits in Known depending on the ability of the function associated with IRP to capture state in memory and through "returning/throwing", respectively.
Static Public Member Functions inherited from llvm::AANoCapture
static AANoCapture & createForPosition (const IRPosition &IRP, Attributor &A)
Create an abstract attribute view for the position IRP.
static bool classof (const AbstractAttribute *AA)
This function should return true if the type of the AA is AANoCapture.
Additional Inherited Members
Public Types inherited from llvm::AANoCapture
enum {
NOT_CAPTURED_IN_MEM = 1 << 0 , NOT_CAPTURED_IN_INT = 1 << 1 , NOT_CAPTURED_IN_RET = 1 << 2 , NO_CAPTURE_MAYBE_RETURNED = NOT_CAPTURED_IN_MEM | NOT_CAPTURED_IN_INT ,
NO_CAPTURE
}
State encoding bits.
Public Types inherited from llvm::StateWrapper< StateTy, BaseType, Ts >
using StateType = StateTy
Provide static access to the type of the state.
Static Public Attributes inherited from llvm::AANoCapture
static const char ID = 0
Unique ID (due to the unique address)
Detailed Description
--------------------— Variable Capturing ------------------------------—
A class to hold the state of for no-capture attributes.
Definition at line 4780 of file AttributorAttributes.cpp.
Constructor & Destructor Documentation
AANoCaptureImpl()
AANoCaptureImpl::AANoCaptureImpl (const IRPosition & IRP, Attributor & A) inline
Definition at line 4781 of file AttributorAttributes.cpp.
Member Function Documentation
determineFunctionCaptureCapabilities()
static void AANoCaptureImpl::determineFunctionCaptureCapabilities (const IRPosition & IRP, const Function & F, BitIntegerState & State) inline static
Set the NOT_CAPTURED_IN_MEM and NOT_CAPTURED_IN_RET bits in Known depending on the ability of the function associated with IRP to capture state in memory and through "returning/throwing", respectively.
Definition at line 4834 of file AttributorAttributes.cpp.
References llvm::BitIntegerState< base_ty, BestState, WorstState >::addKnownBits(), llvm::numbers::e, F, llvm::IRPosition::getCalleeArgNo(), and llvm::BitIntegerState< base_ty, BestState, WorstState >::removeAssumedBits().
getAsStr()
const std::string AANoCaptureImpl::getAsStr () const inline override
See AbstractState::getAsStr().
Definition at line 4875 of file AttributorAttributes.cpp.
getDeducedAttributes()
virtual void AANoCaptureImpl::getDeducedAttributes (LLVMContext & Ctx, SmallVectorImpl< Attribute > & Attrs) const inline override virtual
see AbstractAttribute::isAssumedNoCaptureMaybeReturned(...).
Reimplemented from llvm::IRAttribute< Attribute::NoCapture, StateWrapper< BitIntegerState< uint16_t, 7, 0 >, AbstractAttribute > >.
Definition at line 4818 of file AttributorAttributes.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, llvm::Attribute::get(), and ManifestInternal.
initialize()
void AANoCaptureImpl::initialize (Attributor & A) inline override virtual
See AbstractAttribute::initialize(...).
Reimplemented from llvm::IRAttribute< Attribute::NoCapture, StateWrapper< BitIntegerState< uint16_t, 7, 0 >, AbstractAttribute > >.
Reimplemented in AANoCaptureCallSiteReturned, AANoCaptureReturned, and AANoCaptureCallSiteArgument.
Definition at line 4784 of file AttributorAttributes.cpp.
References F, and llvm::Intrinsic::getType().
Referenced by AANoCaptureCallSiteArgument::initialize().
updateImpl()
ChangeStatus AANoCaptureImpl::updateImpl (Attributor & A) override
See AbstractAttribute::updateImpl(...).
Definition at line 5054 of file AttributorAttributes.cpp.
References assert(), llvm::CHANGED, F, llvm::IRPosition::function(), llvm::IRPosition::getAnchorScope(), llvm::IRPosition::getAssociatedArgument(), llvm::IRPosition::getAssociatedFunction(), llvm::IRPosition::getAssociatedValue(), llvm::getDefaultMaxUsesToExploreForCaptureTracking(), llvm::AbstractAttribute::getState(), llvm::SetVector< T, Vector, Set >::insert(), llvm::AA::isAssumedReadOnly(), llvm::AbstractState::isAtFixpoint(), llvm::NONE, llvm::OPTIONAL, llvm::SetVector< T, Vector, Set >::size(), T, llvm::UNCHANGED, and AACaptureUseTracker::valueMayBeCaptured().
The documentation for this struct was generated from the following file:
lib/Transforms/IPO/AttributorAttributes.cpp