LLVM: AAMemoryBehaviorCallSite Struct Reference
AAMemoryBehaviorCallSite Struct Reference final
AAMemoryBehavior attribute for call sites.
Public Member Functions
AAMemoryBehaviorCallSite (const IRPosition &IRP, Attributor &A)
void initialize (Attributor &A) override
See AbstractAttribute::initialize(...).
ChangeStatus updateImpl (Attributor &A) override
See AbstractAttribute::updateImpl(...).
void trackStatistics () const override
See AbstractAttribute::trackStatistics()
Public Member Functions inherited from AAMemoryBehaviorImpl
AAMemoryBehaviorImpl (const IRPosition &IRP, Attributor &A)
void getDeducedAttributes (LLVMContext &Ctx, SmallVectorImpl< Attribute > &Attrs) const override
See AbstractAttribute::getDeducedAttributes(...).
ChangeStatus manifest (Attributor &A) override
See AbstractAttribute::manifest(...).
const std::string getAsStr () const override
See AbstractState::getAsStr().
Public Member Functions inherited from llvm::AAMemoryBehavior
AAMemoryBehavior (const IRPosition &IRP, Attributor &A)
bool isKnownReadNone () const
Return true if we know that the underlying value is not read or accessed in its respective scope.
bool isAssumedReadNone () const
Return true if we assume that the underlying value is not read or accessed in its respective scope.
bool isKnownReadOnly () const
Return true if we know that the underlying value is not accessed (=written) in its respective scope.
bool isAssumedReadOnly () const
Return true if we assume that the underlying value is not accessed (=written) in its respective scope.
bool isKnownWriteOnly () const
Return true if we know that the underlying value is not read in its respective scope.
bool isAssumedWriteOnly () const
Return true if we assume that the underlying value is not read in its respective scope.
const std::string getName () const override
See AbstractAttribute::getName()
const char * getIdAddr () const override
See AbstractAttribute::getIdAddr()
Public Member Functions inherited from llvm::IRAttribute< Attribute::ReadNone, StateWrapper< BitIntegerState< uint8_t, 3 >, AbstractAttribute > >
IRAttribute (const IRPosition &IRP)
ChangeStatus manifest (Attributor &A) override
See AbstractAttribute::manifest(...).
Attribute::AttrKind getAttrKind () const
Return the kind that identifies the abstract attribute implementation.
Public Member Functions inherited from llvm::StateWrapper< StateTy, BaseType, Ts >
StateWrapper (const IRPosition &IRP, Ts... Args)
StateType & getState () override
See AbstractAttribute::getState(...).
const StateType & getState () const override
See AbstractAttribute::getState(...).
Additional Inherited Members
Public Types inherited from llvm::AAMemoryBehavior
enum { NO_READS = 1 << 0 , NO_WRITES = 1 << 1 , NO_ACCESSES = NO_READS | NO_WRITES , BEST_STATE = NO_ACCESSES }
State encoding bits.
Public Types inherited from llvm::StateWrapper< StateTy, BaseType, Ts >
using StateType = StateTy
Provide static access to the type of the state.
Static Public Member Functions inherited from AAMemoryBehaviorImpl
static void getKnownStateFromValue (const IRPosition &IRP, BitIntegerState &State, bool IgnoreSubsumingPositions=false)
Return the memory behavior information encoded in the IR for IRP.
Static Public Member Functions inherited from llvm::AAMemoryBehavior
static AAMemoryBehavior & createForPosition (const IRPosition &IRP, Attributor &A)
Create an abstract attribute view for the position IRP.
static bool classof (const AbstractAttribute *AA)
This function should return true if the type of the AA is AAMemoryBehavior.
Static Public Attributes inherited from AAMemoryBehaviorImpl
static const Attribute::AttrKind AttrKinds [3]
The set of IR attributes AAMemoryBehavior deals with.
Static Public Attributes inherited from llvm::AAMemoryBehavior
static const char ID = 0
Unique ID (due to the unique address)
Detailed Description
AAMemoryBehavior attribute for call sites.
Definition at line 7298 of file AttributorAttributes.cpp.
Constructor & Destructor Documentation
AAMemoryBehaviorCallSite()
AAMemoryBehaviorCallSite::AAMemoryBehaviorCallSite (const IRPosition & IRP, Attributor & A) inline
Definition at line 7299 of file AttributorAttributes.cpp.
Member Function Documentation
initialize()
void AAMemoryBehaviorCallSite::initialize (Attributor & A) inline override virtual
See AbstractAttribute::initialize(...).
Reimplemented from AAMemoryBehaviorImpl.
Definition at line 7303 of file AttributorAttributes.cpp.
References F, and AAMemoryBehaviorImpl::initialize().
trackStatistics()
void AAMemoryBehaviorCallSite::trackStatistics () const inline override
See AbstractAttribute::trackStatistics()
Definition at line 7324 of file AttributorAttributes.cpp.
References llvm::AA::isAssumedReadNone(), llvm::AA::isAssumedReadOnly(), and STATS_DECLTRACK_CS_ATTR.
updateImpl()
ChangeStatus AAMemoryBehaviorCallSite::updateImpl (Attributor & A) inline override
See AbstractAttribute::updateImpl(...).
Definition at line 7311 of file AttributorAttributes.cpp.
References llvm::clampStateAndIndicateChange(), F, llvm::IRPosition::function(), and llvm::REQUIRED.
The documentation for this struct was generated from the following file:
lib/Transforms/IPO/AttributorAttributes.cpp