LLVM: AbstractManglingParser< Derived, Alloc > Struct Template Reference
AbstractManglingParser< Derived, Alloc > Struct Template Reference
#include "llvm/Demangle/ItaniumDemangle.h"
Classes
struct NameState
Holds some extra information about a <name> that is being parsed.
class ScopedTemplateParamList
Public Types
using TemplateParamList = PODSmallVector< Node *, 8 >
Public Member Functions
AbstractManglingParser (const char *First_, const char *Last_)
Derived & getDerived ()
void reset (const char *First_, const char *Last_)
template<class T , class... Args>
Node * make (Args &&... args)
template<class It >
NodeArray makeNodeArray (It begin, It end)
NodeArray popTrailingNodeArray (size_t FromPosition)
bool consumeIf (StringView S)
bool consumeIf (char C)
char consume ()
char look (unsigned Lookahead=0) const
size_t numLeft () const
StringView parseNumber (bool AllowNegative=false)
Qualifiers parseCVQualifiers ()
bool parsePositiveInteger (size_t *Out)
StringView parseBareSourceName ()
bool parseSeqId (size_t *Out)
Node * parseSubstitution ()
Node * parseTemplateParam ()
Node * parseTemplateParamDecl ()
Node * parseTemplateArgs (bool TagTemplates=false)
Node * parseTemplateArg ()
Node * parseExpr ()
Parse the <expr> production.
Node * parsePrefixExpr (StringView Kind)
Node * parseBinaryExpr (StringView Kind)
Node * parseIntegerLiteral (StringView Lit)
Node * parseExprPrimary ()
template<class Float >
Node * parseFloatingLiteral ()
Node * parseFunctionParam ()
Node * parseNewExpr ()
Node * parseConversionExpr ()
Node * parseBracedExpr ()
Node * parseFoldExpr ()
Node * parsePointerToMemberConversionExpr ()
Node * parseSubobjectExpr ()
Node * parseType ()
Parse the <type> production.
Node * parseFunctionType ()
Node * parseVectorType ()
Node * parseDecltype ()
Node * parseArrayType ()
Node * parsePointerToMemberType ()
Node * parseClassEnumType ()
Node * parseQualifiedType ()
Node * parseEncoding ()
bool parseCallOffset ()
Node * parseSpecialName ()
bool resolveForwardTemplateRefs (NameState &State)
Node * parseName (NameState *State=nullptr)
Parse the <name> production>
Node * parseLocalName (NameState *State)
Node * parseOperatorName (NameState *State)
Node * parseUnqualifiedName (NameState *State)
Node * parseUnnamedTypeName (NameState *State)
Node * parseSourceName (NameState *State)
Node * parseUnscopedName (NameState *State)
Node * parseNestedName (NameState *State)
Node * parseCtorDtorName (Node *&SoFar, NameState *State)
Node * parseAbiTags (Node *N)
Node * parseUnresolvedName ()
Parse the <unresolved-name> production.
Node * parseSimpleId ()
Node * parseBaseUnresolvedName ()
Node * parseUnresolvedType ()
Node * parseDestructorName ()
Node * parse ()
Top-level entry point into the parser.
Public Attributes
const char * First
const char * Last
PODSmallVector< Node *, 32 > Names
PODSmallVector< Node *, 32 > Subs
TemplateParamList OuterTemplateParams
PODSmallVector< TemplateParamList *, 4 > TemplateParams
PODSmallVector< ForwardTemplateReference *, 4 > ForwardTemplateRefs
bool TryToParseTemplateArgs = true
bool PermitForwardTemplateReferences = false
size_t ParsingLambdaParamsAtLevel = (size_t)-1
unsigned NumSyntheticTemplateParameters [3] = {}
Alloc ASTAllocator
Detailed Description
template<typename Derived, typename Alloc>
struct AbstractManglingParser< Derived, Alloc >
Definition at line 2366 of file ItaniumDemangle.h.
Member Typedef Documentation
TemplateParamList
template<typename Derived , typename Alloc > using AbstractManglingParser< Derived, Alloc >::TemplateParamList = PODSmallVector<Node *, 8>
Definition at line 2380 of file ItaniumDemangle.h.
Constructor & Destructor Documentation
AbstractManglingParser()
template<typename Derived , typename Alloc > AbstractManglingParser< Derived, Alloc >::AbstractManglingParser (const char * First_, const char * Last_) inline
Definition at line 2423 of file ItaniumDemangle.h.
Member Function Documentation
consume()
template<typename Derived , typename Alloc > char AbstractManglingParser< Derived, Alloc >::consume () inline
Definition at line 2478 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::First, and AbstractManglingParser< Derived, Alloc >::Last.
consumeIf() [1/2]
template<typename Derived , typename Alloc > bool AbstractManglingParser< Derived, Alloc >::consumeIf (char C) inline
Definition at line 2470 of file ItaniumDemangle.h.
References C, AbstractManglingParser< Derived, Alloc >::First, and AbstractManglingParser< Derived, Alloc >::Last.
consumeIf() [2/2]
template<typename Derived , typename Alloc > bool AbstractManglingParser< Derived, Alloc >::consumeIf (StringView S) inline
Definition at line 2462 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::First, AbstractManglingParser< Derived, Alloc >::Last, and StringView::size().
getDerived()
template<typename Derived , typename Alloc > Derived& AbstractManglingParser< Derived, Alloc >::getDerived () inline
Definition at line 2426 of file ItaniumDemangle.h.
look()
template<typename Derived , typename Alloc > char AbstractManglingParser< Derived, Alloc >::look (unsigned Lookahead = 0) const inline
Definition at line 2480 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::First, and AbstractManglingParser< Derived, Alloc >::Last.
make()
template<typename Derived , typename Alloc > template<class T , class... Args> Node* AbstractManglingParser< Derived, Alloc >::make (Args &&... args) inline
Definition at line 2442 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::ASTAllocator.
makeNodeArray()
template<typename Derived , typename Alloc > template<class It > NodeArray AbstractManglingParser< Derived, Alloc >::makeNodeArray (It begin, It end) inline
Definition at line 2446 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::ASTAllocator, llvm::sys::path::begin(), llvm::copy(), and llvm::sys::path::end().
Referenced by AbstractManglingParser< Derived, Alloc >::popTrailingNodeArray().
numLeft()
template<typename Derived , typename Alloc > size_t AbstractManglingParser< Derived, Alloc >::numLeft () const inline
Definition at line 2486 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::First, and AbstractManglingParser< Derived, Alloc >::Last.
parse()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parse
Top-level entry point into the parser.
Definition at line 5717 of file ItaniumDemangle.h.
References llvm::empty().
parseAbiTags()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseAbiTags (Node * N)
Definition at line 3465 of file ItaniumDemangle.h.
References StringView::empty(), and N.
parseArrayType()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseArrayType
Definition at line 3646 of file ItaniumDemangle.h.
parseBareSourceName()
template<typename Alloc , typename Derived > StringView AbstractManglingParser< Alloc, Derived >::parseBareSourceName
Definition at line 3505 of file ItaniumDemangle.h.
References llvm::RISCVFenceField::R.
parseBaseUnresolvedName()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseBaseUnresolvedName
Definition at line 3342 of file ItaniumDemangle.h.
References llvm::X86II::TA.
parseBinaryExpr()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseBinaryExpr (StringView Kind)
Definition at line 4132 of file ItaniumDemangle.h.
References LHS, and RHS.
parseBracedExpr()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseBracedExpr
Definition at line 4392 of file ItaniumDemangle.h.
References Index.
parseCallOffset()
template<typename Alloc , typename Derived > bool AbstractManglingParser< Alloc, Derived >::parseCallOffset
Definition at line 5113 of file ItaniumDemangle.h.
parseClassEnumType()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseClassEnumType
Definition at line 3692 of file ItaniumDemangle.h.
References StringView::empty().
parseConversionExpr()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseConversionExpr
Definition at line 4234 of file ItaniumDemangle.h.
References E.
parseCtorDtorName()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseCtorDtorName (Node *& SoFar, NameState * State)
Definition at line 3116 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::NameState::CtorDtorConversion, Node::getKind(), iostream, istream, ostream, and string.
parseCVQualifiers()
template<typename Alloc , typename Derived > Qualifiers AbstractManglingParser< Alloc, Derived >::parseCVQualifiers
Definition at line 4153 of file ItaniumDemangle.h.
References QualConst, QualNone, QualRestrict, and QualVolatile.
parseDecltype()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseDecltype
Definition at line 3630 of file ItaniumDemangle.h.
References E.
parseDestructorName()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseDestructorName
Definition at line 3301 of file ItaniumDemangle.h.
parseEncoding()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseEncoding
Definition at line 5277 of file ItaniumDemangle.h.
References Arg, llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, PODSmallVector< T, N >::clear(), AbstractManglingParser< Derived, Alloc >::NameState::CtorDtorConversion, AbstractManglingParser< Derived, Alloc >::NameState::CVQualifiers, AbstractManglingParser< Derived, Alloc >::NameState::EndsWithTemplateArgs, llvm::move(), AbstractManglingParser< Derived, Alloc >::OuterTemplateParams, AbstractManglingParser< Derived, Alloc >::NameState::ReferenceQualifier, and AbstractManglingParser< Derived, Alloc >::TemplateParams.
parseExpr()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseExpr
Parse the <expr> production.
Definition at line 4593 of file ItaniumDemangle.h.
References Arg, llvm::sampleprof::Base, Callee, Cond, E, FP, Index, LHS, llvm::RISCVFenceField::R, RHS, and T.
parseExprPrimary()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseExprPrimary
Definition at line 4272 of file ItaniumDemangle.h.
References N, llvm::RISCVFenceField::R, and T.
parseFloatingLiteral()
template<typename Alloc , typename Derived > template<class Float > Node * AbstractManglingParser< Alloc, Derived >::parseFloatingLiteral
Definition at line 5400 of file ItaniumDemangle.h.
References C, llvm::Data, and N.
parseFoldExpr()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseFoldExpr
Definition at line 4439 of file ItaniumDemangle.h.
References std::swap().
parseFunctionParam()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseFunctionParam
Definition at line 4170 of file ItaniumDemangle.h.
References llvm::empty().
parseFunctionType()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseFunctionType
Definition at line 3523 of file ItaniumDemangle.h.
References E, FrefQualLValue, FrefQualNone, FrefQualRValue, and T.
parseIntegerLiteral()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseIntegerLiteral (StringView Lit)
Definition at line 4144 of file ItaniumDemangle.h.
References StringView::empty().
parseLocalName()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseLocalName (NameState * State)
Definition at line 2636 of file ItaniumDemangle.h.
References N, and parse_discriminator().
parseName()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseName (NameState * State = nullptr)
Parse the <name> production>
Definition at line 2590 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::NameState::EndsWithTemplateArgs, and llvm::X86II::TA.
parseNestedName()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseNestedName (NameState * State)
Definition at line 3179 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::NameState::CVQualifiers, AbstractManglingParser< Derived, Alloc >::NameState::EndsWithTemplateArgs, FrefQualLValue, FrefQualNone, FrefQualRValue, AbstractManglingParser< Derived, Alloc >::NameState::ReferenceQualifier, and llvm::X86II::TA.
parseNewExpr()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseNewExpr
Definition at line 4200 of file ItaniumDemangle.h.
parseNumber()
template<typename Alloc , typename Derived > StringView AbstractManglingParser< Alloc, Derived >::parseNumber (bool AllowNegative = false)
Definition at line 3480 of file ItaniumDemangle.h.
parseOperatorName()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseOperatorName (NameState * State)
Definition at line 2869 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::NameState::CtorDtorConversion.
parsePointerToMemberConversionExpr()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parsePointerToMemberConversionExpr
Definition at line 4508 of file ItaniumDemangle.h.
References Offset.
parsePointerToMemberType()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parsePointerToMemberType
Definition at line 3675 of file ItaniumDemangle.h.
parsePositiveInteger()
template<typename Alloc , typename Derived > bool AbstractManglingParser< Alloc, Derived >::parsePositiveInteger (size_t * Out)
Definition at line 3493 of file ItaniumDemangle.h.
References consume().
parsePrefixExpr()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parsePrefixExpr (StringView Kind)
Definition at line 4124 of file ItaniumDemangle.h.
References E.
parseQualifiedType()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseQualifiedType
Definition at line 3715 of file ItaniumDemangle.h.
References StringView::begin(), StringView::dropFront(), StringView::empty(), StringView::end(), QualNone, StringView::startsWith(), and llvm::X86II::TA.
parseSeqId()
template<typename Alloc , typename Derived > bool AbstractManglingParser< Alloc, Derived >::parseSeqId (size_t * Out)
Definition at line 5416 of file ItaniumDemangle.h.
parseSimpleId()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseSimpleId
Definition at line 3285 of file ItaniumDemangle.h.
References llvm::X86II::TA.
parseSourceName()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseSourceName (NameState * State)
Definition at line 2803 of file ItaniumDemangle.h.
parseSpecialName()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseSpecialName
Definition at line 5143 of file ItaniumDemangle.h.
References Arg, and llvm::empty().
parseSubobjectExpr()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseSubobjectExpr
Definition at line 4526 of file ItaniumDemangle.h.
References Offset.
parseSubstitution()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseSubstitution
Definition at line 5448 of file ItaniumDemangle.h.
References allocator, basic_string, Index, iostream, istream, ostream, and string.
parseTemplateArg()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseTemplateArg
Definition at line 5630 of file ItaniumDemangle.h.
References Arg, and llvm::AMDGPU::HSAMD::Kernel::Key::Args.
parseTemplateArgs()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseTemplateArgs (bool TagTemplates = false)
Definition at line 5672 of file ItaniumDemangle.h.
References Arg, and llvm::move().
parseTemplateParam()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseTemplateParam
Definition at line 5514 of file ItaniumDemangle.h.
References assert(), Node::getKind(), and Index.
parseTemplateParamDecl()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseTemplateParamDecl
Definition at line 5573 of file ItaniumDemangle.h.
References Index, N, NonType, P, llvm::parseType(), Template, and Type.
parseType()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseType
Parse the <type> production.
Definition at line 3781 of file ItaniumDemangle.h.
References DEMANGLE_FALLTHROUGH, StringView::empty(), LValue, P, RValue, and llvm::X86II::TA.
parseUnnamedTypeName()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseUnnamedTypeName (NameState * State)
Definition at line 2725 of file ItaniumDemangle.h.
References NodeArray::empty(), llvm::find(), StringView::npos, P, and T.
parseUnqualifiedName()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseUnqualifiedName (NameState * State)
Definition at line 2694 of file ItaniumDemangle.h.
parseUnresolvedName()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseUnresolvedName
Parse the <unresolved-name> production.
Definition at line 3375 of file ItaniumDemangle.h.
References assert(), llvm::sampleprof::Base, and llvm::X86II::TA.
parseUnresolvedType()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseUnresolvedType
Definition at line 3316 of file ItaniumDemangle.h.
parseUnscopedName()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseUnscopedName (NameState * State)
Definition at line 2673 of file ItaniumDemangle.h.
parseVectorType()
template<typename Derived , typename Alloc > Node * AbstractManglingParser< Derived, Alloc >::parseVectorType
Definition at line 3593 of file ItaniumDemangle.h.
popTrailingNodeArray()
template<typename Derived , typename Alloc > NodeArray AbstractManglingParser< Derived, Alloc >::popTrailingNodeArray (size_t FromPosition) inline
Definition at line 2454 of file ItaniumDemangle.h.
References assert(), PODSmallVector< T, N >::begin(), PODSmallVector< T, N >::dropBack(), PODSmallVector< T, N >::end(), AbstractManglingParser< Derived, Alloc >::makeNodeArray(), AbstractManglingParser< Derived, Alloc >::Names, and PODSmallVector< T, N >::size().
reset()
template<typename Derived , typename Alloc > void AbstractManglingParser< Derived, Alloc >::reset (const char * First_, const char * Last_) inline
Definition at line 2428 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::ASTAllocator, PODSmallVector< T, N >::clear(), AbstractManglingParser< Derived, Alloc >::First, I, AbstractManglingParser< Derived, Alloc >::Last, AbstractManglingParser< Derived, Alloc >::Names, AbstractManglingParser< Derived, Alloc >::NumSyntheticTemplateParameters, AbstractManglingParser< Derived, Alloc >::ParsingLambdaParamsAtLevel, AbstractManglingParser< Derived, Alloc >::PermitForwardTemplateReferences, AbstractManglingParser< Derived, Alloc >::Subs, AbstractManglingParser< Derived, Alloc >::TemplateParams, and AbstractManglingParser< Derived, Alloc >::TryToParseTemplateArgs.
resolveForwardTemplateRefs()
template<typename Derived , typename Alloc > bool AbstractManglingParser< Derived, Alloc >::resolveForwardTemplateRefs (NameState & State) inline
Definition at line 2542 of file ItaniumDemangle.h.
References PODSmallVector< T, N >::dropBack(), E, AbstractManglingParser< Derived, Alloc >::ForwardTemplateRefs, AbstractManglingParser< Derived, Alloc >::NameState::ForwardTemplateRefsBegin, I, PODSmallVector< T, N >::size(), and AbstractManglingParser< Derived, Alloc >::TemplateParams.
Member Data Documentation
ASTAllocator
template<typename Derived , typename Alloc > Alloc AbstractManglingParser< Derived, Alloc >::ASTAllocator
Definition at line 2421 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::make(), AbstractManglingParser< Derived, Alloc >::makeNodeArray(), and AbstractManglingParser< Derived, Alloc >::reset().
First
template<typename Derived , typename Alloc > const char* AbstractManglingParser< Derived, Alloc >::First
Definition at line 2367 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::consume(), AbstractManglingParser< Derived, Alloc >::consumeIf(), AbstractManglingParser< Derived, Alloc >::look(), AbstractManglingParser< Derived, Alloc >::numLeft(), and AbstractManglingParser< Derived, Alloc >::reset().
ForwardTemplateRefs
template<typename Derived , typename Alloc > PODSmallVector<ForwardTemplateReference *, 4> AbstractManglingParser< Derived, Alloc >::ForwardTemplateRefs
Definition at line 2413 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::resolveForwardTemplateRefs().
Last
template<typename Derived , typename Alloc > const char* AbstractManglingParser< Derived, Alloc >::Last
Definition at line 2368 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::consume(), AbstractManglingParser< Derived, Alloc >::consumeIf(), AbstractManglingParser< Derived, Alloc >::look(), AbstractManglingParser< Derived, Alloc >::numLeft(), and AbstractManglingParser< Derived, Alloc >::reset().
Names
template<typename Derived , typename Alloc > PODSmallVector<Node *, 32> AbstractManglingParser< Derived, Alloc >::Names
Definition at line 2373 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::popTrailingNodeArray(), and AbstractManglingParser< Derived, Alloc >::reset().
NumSyntheticTemplateParameters
template<typename Derived , typename Alloc > unsigned AbstractManglingParser< Derived, Alloc >::NumSyntheticTemplateParameters[3] = {}
Definition at line 2419 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::reset().
OuterTemplateParams
template<typename Derived , typename Alloc > TemplateParamList AbstractManglingParser< Derived, Alloc >::OuterTemplateParams
Definition at line 2402 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::parseEncoding().
ParsingLambdaParamsAtLevel
template<typename Derived , typename Alloc > size_t AbstractManglingParser< Derived, Alloc >::ParsingLambdaParamsAtLevel = (size_t)-1
Definition at line 2417 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::reset().
PermitForwardTemplateReferences
template<typename Derived , typename Alloc > bool AbstractManglingParser< Derived, Alloc >::PermitForwardTemplateReferences = false
Definition at line 2416 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::reset().
Subs
template<typename Derived , typename Alloc > PODSmallVector<Node *, 32> AbstractManglingParser< Derived, Alloc >::Subs
Definition at line 2378 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::reset().
TemplateParams
template<typename Derived , typename Alloc > PODSmallVector<TemplateParamList *, 4> AbstractManglingParser< Derived, Alloc >::TemplateParams
Definition at line 2409 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::parseEncoding(), AbstractManglingParser< Derived, Alloc >::reset(), AbstractManglingParser< Derived, Alloc >::resolveForwardTemplateRefs(), AbstractManglingParser< Derived, Alloc >::ScopedTemplateParamList::ScopedTemplateParamList(), and AbstractManglingParser< Derived, Alloc >::ScopedTemplateParamList::~ScopedTemplateParamList().
TryToParseTemplateArgs
template<typename Derived , typename Alloc > bool AbstractManglingParser< Derived, Alloc >::TryToParseTemplateArgs = true
Definition at line 2415 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::reset().
The documentation for this struct was generated from the following file:
include/llvm/Demangle/ItaniumDemangle.h