LLVM: llvm::IRPosition Struct Reference
llvm::IRPosition Struct Reference
Helper to describe and deal with positions in the LLVM-IR.
#include "llvm/Transforms/IPO/Attributor.h"
Public Types
enum Kind : char {
IRP_INVALID , IRP_FLOAT , IRP_RETURNED , IRP_CALL_SITE_RETURNED ,
IRP_FUNCTION , IRP_CALL_SITE , IRP_ARGUMENT , IRP_CALL_SITE_ARGUMENT
}
The positions we distinguish in the IR.
using CallBaseContext = CallBase
Public Member Functions
IRPosition ()
Default constructor available to create invalid positions implicitly.
bool operator== (const IRPosition &RHS) const
bool operator!= (const IRPosition &RHS) const
Value & getAnchorValue () const
Return the value this abstract attribute is anchored with.
Function * getAssociatedFunction () const
Return the associated function, if any.
Argument * getAssociatedArgument () const
Return the associated argument, if any.
bool isFnInterfaceKind () const
Return true if the position refers to a function interface, that is the function scope, the function return, or an argument.
Function * getAnchorScope () const
Return the Function surrounding the anchor value.
Instruction * getCtxI () const
Return the context instruction, if any.
Value & getAssociatedValue () const
Return the value this abstract attribute is associated with.
Type * getAssociatedType () const
Return the type this abstract attribute is associated with.
int getCalleeArgNo () const
Return the callee argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
int getCallSiteArgNo () const
Return the call site argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
unsigned getAttrIdx () const
Return the index in the attribute list for this position.
Kind getPositionKind () const
Return the associated position kind.
bool hasAttr (ArrayRef< Attribute::AttrKind > AKs, bool IgnoreSubsumingPositions=false, Attributor *A=nullptr) const
TODO: Figure out if the attribute related helper functions should live here or somewhere else.
void getAttrs (ArrayRef< Attribute::AttrKind > AKs, SmallVectorImpl< Attribute > &Attrs, bool IgnoreSubsumingPositions=false, Attributor *A=nullptr) const
Return the attributes of any kind in AKs existing in the IR at a position that will affect this one.
void removeAttrs (ArrayRef< Attribute::AttrKind > AKs) const
Remove the attribute of kind AKs existing in the IR at this position.
bool isAnyCallSitePosition () const
bool isArgumentPosition () const
Return true if the position is an argument or call site argument.
IRPosition stripCallBaseContext () const
Return the same position without the call base context.
const CallBaseContext * getCallBaseContext () const
Get the call base context from the position.
bool hasCallBaseContext () const
Check if the position has any call base context.
operator void * () const
}
Static Public Member Functions
static const IRPosition value (const Value &V, const CallBaseContext *CBContext=nullptr)
Create a position describing the value of V.
static const IRPosition inst (const Instruction &I, const CallBaseContext *CBContext=nullptr)
Create a position describing the instruction I.
static const IRPosition function (const Function &F, const CallBaseContext *CBContext=nullptr)
Create a position describing the function scope of F.
static const IRPosition returned (const Function &F, const CallBaseContext *CBContext=nullptr)
Create a position describing the returned value of F.
static const IRPosition argument (const Argument &Arg, const CallBaseContext *CBContext=nullptr)
Create a position describing the argument Arg.
static const IRPosition callsite_function (const CallBase &CB)
Create a position describing the function scope of CB.
static const IRPosition callsite_returned (const CallBase &CB)
Create a position describing the returned value of CB.
static const IRPosition callsite_argument (const CallBase &CB, unsigned ArgNo)
Create a position describing the argument of CB at position ArgNo.
static const IRPosition callsite_argument (AbstractCallSite ACS, unsigned ArgNo)
Create a position describing the argument of ACS at position ArgNo.
static const IRPosition function_scope (const IRPosition &IRP, const CallBaseContext *CBContext=nullptr)
Create a position with function scope matching the "context" of IRP.
Static Public Attributes
static const IRPosition EmptyKey
Special DenseMap key values.
static const IRPosition TombstoneKey
Detailed Description
Helper to describe and deal with positions in the LLVM-IR.
A position in the IR is described by an anchor value and an "offset" that could be the argument number, for call sites and arguments, or an indicator of the "position kind". The kinds, specified in the Kind enum below, include the locations in the attribute list, i.a., function scope and return value, as well as a distinction between call sites and functions. Finally, there are floating values that do not have a corresponding attribute list position.
Definition at line 340 of file Attributor.h.
Member Typedef Documentation
CallBaseContext
using llvm::IRPosition::CallBaseContext = CallBase
Definition at line 343 of file Attributor.h.
Member Enumeration Documentation
Kind
enum llvm::IRPosition::Kind : char
The positions we distinguish in the IR.
Enumerator
IRP_INVALID
An invalid position.
IRP_FLOAT
A position that is not associated with a spot suitable for attributes.
This could be any value or instruction.
IRP_RETURNED
An attribute for the function return value.
IRP_CALL_SITE_RETURNED
An attribute for a call site return value.
IRP_FUNCTION
An attribute for a function (scope).
IRP_CALL_SITE
An attribute for a call site (function scope).
IRP_ARGUMENT
An attribute for a function argument.
IRP_CALL_SITE_ARGUMENT
An attribute for a call site argument.
Definition at line 346 of file Attributor.h.
Constructor & Destructor Documentation
IRPosition()
llvm::IRPosition::IRPosition () inline
Default constructor available to create invalid positions implicitly.
All other positions need to be created explicitly through the appropriate static member function.
Definition at line 361 of file Attributor.h.
Referenced by argument(), callsite_argument(), callsite_function(), callsite_returned(), function(), inst(), returned(), and value().
Member Function Documentation
argument()
static const IRPosition llvm::IRPosition::argument (const Argument & Arg, const CallBaseContext * CBContext = nullptr) inline static
Create a position describing the argument Arg.
CBContext is used for call base specific analysis.
Definition at line 397 of file Attributor.h.
References Arg, IRP_ARGUMENT, and IRPosition().
Referenced by llvm::Attributor::identifyDefaultAbstractAttributes(), AAPrivatizablePtrFloating::identifyPrivatizableType(), AAReturnedValuesImpl::manifest(), llvm::SubsumingPositionIterator::SubsumingPositionIterator(), AAPointerInfoCallSiteArgument::updateImpl(), AANoFreeCallSiteArgument::updateImpl(), AAIsDeadCallSiteArgument::updateImpl(), AAAlignCallSiteArgument::updateImpl(), AANoCaptureCallSiteArgument::updateImpl(), AAPrivatizablePtrArgument::updateImpl(), AAMemoryBehaviorCallSiteArgument::updateImpl(), and value().
callsite_argument() [1/2]
static const IRPosition llvm::IRPosition::callsite_argument (AbstractCallSite ACS, unsigned ArgNo) inline static
Create a position describing the argument of ACS at position ArgNo.
Definition at line 420 of file Attributor.h.
References callsite_argument(), llvm::AbstractCallSite::getCallArgOperandNo(), llvm::AbstractCallSite::getInstruction(), llvm::AbstractCallSite::getNumArgOperands(), and IRPosition().
callsite_argument() [2/2]
static const IRPosition llvm::IRPosition::callsite_argument (const CallBase & CB, unsigned ArgNo) inline static
Create a position describing the argument of CB at position ArgNo.
Definition at line 413 of file Attributor.h.
References llvm::CallBase::getArgOperandUse(), IRP_CALL_SITE_ARGUMENT, and IRPosition().
Referenced by callsite_argument(), AACaptureUseTracker::captured(), AAMemoryLocationImpl::categorizeArgumentPointerLocations(), getKnownAlignForUse(), getKnownNonNullAndDerefBytesForUse(), llvm::Attributor::identifyDefaultAbstractAttributes(), AAPrivatizablePtrArgument::identifyPrivatizableType(), llvm::Attributor::isAssumedDead(), AANoAliasCallSiteArgument::isKnownNoAliasDueToNoAliasPreservation(), AANoAliasCallSiteArgument::mayAliasWithArgument(), llvm::SubsumingPositionIterator::SubsumingPositionIterator(), llvm::Attributor::translateArgumentToCallSiteContent(), AAPointerInfoFloating::updateImpl(), AANoFreeFloating::updateImpl(), AAUndefinedBehaviorImpl::updateImpl(), AAValueSimplifyArgument::updateImpl(), and AAHeapToStackFunction::updateImpl().
callsite_function()
static const IRPosition llvm::IRPosition::callsite_function (const CallBase & CB) inline static
Create a position describing the function scope of CB.
Definition at line 403 of file Attributor.h.
References IRP_CALL_SITE, and IRPosition().
Referenced by AAFunctionReachabilityFunction::canReach(), AAMemoryLocationImpl::categorizeAccessedLocations(), function_scope(), identifyAliveSuccessors(), llvm::Attributor::identifyDefaultAbstractAttributes(), AAIsDeadValueImpl::isAssumedSideEffectFree(), llvm::AA::isNoSyncInst(), AAIsDeadFunction::manifest(), llvm::SubsumingPositionIterator::SubsumingPositionIterator(), AANoUnwindImpl::updateImpl(), AANoFreeImpl::updateImpl(), AAWillReturnImpl::updateImpl(), AAMemoryBehaviorFunction::updateImpl(), AACallEdgesFunction::updateImpl(), AAFunctionReachabilityFunction::updateImpl(), and AAAssumptionInfoFunction::updateImpl().
callsite_returned()
static const IRPosition llvm::IRPosition::callsite_returned (const CallBase & CB) inline static
Create a position describing the returned value of CB.
Definition at line 408 of file Attributor.h.
References IRP_CALL_SITE_RETURNED, and IRPosition().
Referenced by AAMemoryLocationImpl::categorizePtrValue(), llvm::Attributor::identifyDefaultAbstractAttributes(), llvm::Attributor::isAssumedDead(), and value().
function()
static const IRPosition llvm::IRPosition::function (const Function & F, const CallBaseContext * CBContext = nullptr) inline static
Create a position describing the function scope of F.
CBContext is used for call base specific analysis.
Definition at line 383 of file Attributor.h.
References F, IRP_FUNCTION, and IRPosition().
Referenced by llvm::Attributor::checkForAllInstructions(), llvm::Attributor::checkForAllReadWriteInstructions(), llvm::Attributor::checkForAllReturnedValues(), llvm::Attributor::checkForAllReturnedValuesAndReturnInsts(), llvm::Attributor::checkForAllUses(), AAPointerInfoImpl::forallInterferingWrites(), function_scope(), genericValueTraversal(), llvm::Attributor::identifyDefaultAbstractAttributes(), AANoReturnCallSite::initialize(), AAAssumptionInfoCallSite::initialize(), AAFunctionReachabilityFunction::instructionCanReach(), llvm::Attributor::isAssumedDead(), llvm::AA::isDynamicallyUnique(), AANoAliasCallSiteArgument::isKnownNoAliasDueToNoAliasPreservation(), isPotentiallyReachable(), llvm::AACallEdgeIterator::operator*(), llvm::SubsumingPositionIterator::SubsumingPositionIterator(), AANoUnwindCallSite::updateImpl(), AANoSyncCallSite::updateImpl(), AANoFreeCallSite::updateImpl(), AANoRecurseFunction::updateImpl(), AANoRecurseCallSite::updateImpl(), AAWillReturnCallSite::updateImpl(), AAReachabilityImpl::updateImpl(), AANoReturnCallSite::updateImpl(), AANoCaptureImpl::updateImpl(), AAValueSimplifyCallSiteReturned::updateImpl(), AAHeapToStackFunction::updateImpl(), AAMemoryBehaviorCallSite::updateImpl(), AAMemoryLocationCallSite::updateImpl(), AAFunctionReachabilityFunction::updateImpl(), and AAAssumptionInfoCallSite::updateImpl().
function_scope()
static const IRPosition llvm::IRPosition::function_scope (const IRPosition & IRP, const CallBaseContext * CBContext = nullptr) inline static
Create a position with function scope matching the "context" of IRP.
If IRP is a call site (see isAnyCallSitePosition()) then the result will be a call site position, otherwise the function position of the associated function.
Definition at line 436 of file Attributor.h.
References assert(), callsite_function(), function(), getAnchorValue(), getAssociatedFunction(), and isAnyCallSitePosition().
Referenced by AANoFreeFloating::updateImpl(), AANoAliasArgument::updateImpl(), and AAMemoryBehaviorFloating::updateImpl().
getAnchorScope()
Function* llvm::IRPosition::getAnchorScope () const inline
Return the Function surrounding the anchor value.
Definition at line 500 of file Attributor.h.
References getAnchorValue().
Referenced by llvm::Attributor::checkForAllUses(), getAssociatedFunction(), AAMemoryLocationImpl::getKnownStateFromValue(), llvm::Attributor::getOrCreateAAFor(), llvm::IRAttribute< AK, BaseType >::initialize(), AADereferenceableImpl::initialize(), llvm::Attributor::isAssumedDead(), AANoAliasCallSiteArgument::isKnownNoAliasDueToNoAliasPreservation(), llvm::IRAttributeManifest::manifestAttrs(), llvm::SubsumingPositionIterator::SubsumingPositionIterator(), and AANoCaptureImpl::updateImpl().
getAnchorValue()
Value& llvm::IRPosition::getAnchorValue () const inline
Return the value this abstract attribute is anchored with.
The anchor value might not be the associated value if the latter is not sufficient to determine where arguments will be manifested. This is, so far, only the case for call site arguments as the value is not sufficient to pinpoint them. Instead, we can use the call site as an anchor.
Definition at line 457 of file Attributor.h.
References llvm_unreachable.
Referenced by function_scope(), getAnchorScope(), getAssociatedArgument(), getAssociatedFunction(), getAssociatedValue(), getCtxI(), AAMemoryBehaviorImpl::getKnownStateFromValue(), AAMemoryBehaviorImpl::manifest(), AAMemoryLocationImpl::manifest(), llvm::IRAttributeManifest::manifestAttrs(), llvm::operator<<(), removeAttrs(), and llvm::SubsumingPositionIterator::SubsumingPositionIterator().
getAssociatedArgument()
Argument * IRPosition::getAssociatedArgument () const
Return the associated argument, if any.
Definition at line 602 of file Attributor.cpp.
References llvm::Function::arg_size(), assert(), Callee, llvm::numbers::e, getAnchorValue(), llvm::Function::getArg(), llvm::AbstractCallSite::getCallArgOperandNo(), llvm::AbstractCallSite::getCallbackUses(), llvm::AbstractCallSite::getCalledFunction(), getCallSiteArgNo(), llvm::AbstractCallSite::getNumArgOperands(), getPositionKind(), llvm::Optional< T >::getValue(), llvm::Optional< T >::hasValue(), IRP_ARGUMENT, and llvm::AbstractCallSite::isCallbackCall().
Referenced by getAssociatedFunction(), llvm::SubsumingPositionIterator::SubsumingPositionIterator(), AAPointerInfoImpl::translateAndAddCalleeState(), AANoCaptureImpl::updateImpl(), and AAMemoryBehaviorFloating::updateImpl().
getAssociatedFunction()
Function* llvm::IRPosition::getAssociatedFunction () const inline
Return the associated function, if any.
Definition at line 471 of file Attributor.h.
References Arg, getAnchorScope(), getAnchorValue(), and getAssociatedArgument().
Referenced by llvm::Attributor::checkForAllCallSites(), llvm::Attributor::checkForAllInstructions(), llvm::Attributor::checkForAllReadWriteInstructions(), llvm::Attributor::checkForAllReturnedValues(), llvm::Attributor::checkForAllReturnedValuesAndReturnInsts(), function_scope(), getAssociatedType(), llvm::AAIsDead::isLiveInstSet(), removeAttrs(), and AANoCaptureImpl::updateImpl().
getAssociatedType()
Type* llvm::IRPosition::getAssociatedType () const inline
Return the type this abstract attribute is associated with.
Definition at line 535 of file Attributor.h.
References getAssociatedFunction(), getAssociatedValue(), getPositionKind(), llvm::Function::getReturnType(), llvm::Value::getType(), and IRP_RETURNED.
Referenced by llvm::Attributor::getAssumedConstant(), llvm::Attributor::getAssumedSimplified(), and AAValueSimplifyImpl::handleLoad().
getAssociatedValue()
Value& llvm::IRPosition::getAssociatedValue () const inline
Return the value this abstract attribute is associated with.
Definition at line 526 of file Attributor.h.
References assert(), getAnchorValue(), and getCallSiteArgNo().
Referenced by AAValueSimplifyImpl::checkAndUpdate(), genericValueTraversal(), getAssociatedType(), llvm::AAValueConstantRange::getAssumedConstantInt(), llvm::AAPotentialValues::getAssumedConstantInt(), llvm::Attributor::getAssumedSimplified(), llvm::IRAttribute< AK, BaseType >::initialize(), AADereferenceableImpl::initialize(), llvm::Attributor::isAssumedDead(), llvm::operator<<(), llvm::SubsumingPositionIterator::SubsumingPositionIterator(), and AANoCaptureImpl::updateImpl().
getAttrIdx()
unsigned llvm::IRPosition::getAttrIdx () const inline
Return the index in the attribute list for this position.
Definition at line 560 of file Attributor.h.
References llvm::AttributeList::FirstArgIndex, llvm::AttributeList::FunctionIndex, getCallSiteArgNo(), getPositionKind(), IRP_ARGUMENT, IRP_CALL_SITE, IRP_CALL_SITE_ARGUMENT, IRP_CALL_SITE_RETURNED, IRP_FLOAT, IRP_FUNCTION, IRP_INVALID, IRP_RETURNED, llvm_unreachable, and llvm::AttributeList::ReturnIndex.
Referenced by llvm::IRAttributeManifest::manifestAttrs(), and removeAttrs().
getAttrs()
void IRPosition::getAttrs (ArrayRef< Attribute::AttrKind > AKs, SmallVectorImpl< Attribute > & Attrs, bool IgnoreSubsumingPositions = false, Attributor * A = nullptr) const
Return the attributes of any kind in AKs existing in the IR at a position that will affect this one.
While each position can only have a single attribute of any kind in AKs, there are "subsuming" positions that could have an attribute as well. This method returns all attributes found in Attrs.
Parameters
IgnoreSubsumingPositions Flag to determine if subsuming positions, e.g., the function position if this is an argument position, should be ignored.
Definition at line 820 of file Attributor.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs.
Referenced by AAMemoryLocationImpl::getKnownStateFromValue(), and AAMemoryBehaviorImpl::getKnownStateFromValue().
getCallBaseContext()
const CallBaseContext* llvm::IRPosition::getCallBaseContext () const inline
Get the call base context from the position.
Definition at line 677 of file Attributor.h.
Referenced by llvm::Attributor::checkForAllReturnedValues(), llvm::DenseMapInfo< IRPosition >::getHashValue(), llvm::Attributor::isAssumedDead(), and llvm::operator<<().
getCalleeArgNo()
int llvm::IRPosition::getCalleeArgNo () const inline
Return the callee argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
In contrast to getCallSiteArgNo this method will always return the "argument number" from the perspective of the callee. This may not the same as the call site if this is a callback call.
Definition at line 546 of file Attributor.h.
Referenced by AANoCaptureImpl::determineFunctionCaptureCapabilities().
getCallSiteArgNo()
int llvm::IRPosition::getCallSiteArgNo () const inline
Return the call site argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
In contrast to getCalleArgNo this method will always return the "operand number" from the perspective of the call site. This may not the same as the callee perspective if this is a callback call.
Definition at line 555 of file Attributor.h.
Referenced by getAssociatedArgument(), getAssociatedValue(), getAttrIdx(), and llvm::operator<<().
getCtxI()
Instruction* llvm::IRPosition::getCtxI () const inline
Return the context instruction, if any.
Definition at line 512 of file Attributor.h.
References Arg, F, getAnchorValue(), and I.
Referenced by llvm::Attributor::isAssumedDead(), and llvm::AbstractAttribute::print().
getPositionKind()
Kind llvm::IRPosition::getPositionKind () const inline
Return the associated position kind.
Definition at line 580 of file Attributor.h.
References IRP_ARGUMENT, IRP_CALL_SITE, IRP_CALL_SITE_ARGUMENT, IRP_CALL_SITE_RETURNED, IRP_FLOAT, IRP_FUNCTION, IRP_INVALID, and IRP_RETURNED.
Referenced by llvm::AAExecutionDomain::createForPosition(), getAssociatedArgument(), getAssociatedType(), getAttrIdx(), AAPrivatizablePtrArgument::identifyPrivatizableType(), isAnyCallSitePosition(), isArgumentPosition(), llvm::Attributor::isAssumedDead(), isAssumedReadOnlyOrReadNone(), isFnInterfaceKind(), llvm::IRAttributeManifest::manifestAttrs(), llvm::operator<<(), removeAttrs(), llvm::SubsumingPositionIterator::SubsumingPositionIterator(), and AAValueSimplifyArgument::updateImpl().
hasAttr()
bool IRPosition::hasAttr (ArrayRef< Attribute::AttrKind > AKs, bool IgnoreSubsumingPositions = false, Attributor * A = nullptr) const
TODO: Figure out if the attribute related helper functions should live here or somewhere else.
Return true if any kind in AKs existing in the IR at a position that will affect this one. See also getAttrs(...).
Parameters
IgnoreSubsumingPositions Flag to determine if subsuming positions, e.g., the function position if this is an argument position, should be ignored.
Definition at line 800 of file Attributor.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs.
Referenced by AAMemoryBehaviorArgument::initialize(), AAMemoryBehaviorImpl::manifest(), and AAMemoryLocationImpl::manifest().
hasCallBaseContext()
bool llvm::IRPosition::hasCallBaseContext () const inline
Check if the position has any call base context.
Definition at line 680 of file Attributor.h.
Referenced by llvm::operator<<().
inst()
static const IRPosition llvm::IRPosition::inst (const Instruction & I, const CallBaseContext * CBContext = nullptr) inline static
Create a position describing the instruction I.
This is different from the value version because call sites are treated as intrusctions rather than their return value in this function.
Definition at line 376 of file Attributor.h.
References I, IRP_FLOAT, and IRPosition().
Referenced by checkForAllInstructionsImpl(), llvm::Attributor::checkForAllReadWriteInstructions(), llvm::Attributor::identifyDefaultAbstractAttributes(), and llvm::Attributor::isAssumedDead().
isAnyCallSitePosition()
bool llvm::IRPosition::isAnyCallSitePosition () const inline
Definition at line 647 of file Attributor.h.
References getPositionKind(), IRP_CALL_SITE, IRP_CALL_SITE_ARGUMENT, and IRP_CALL_SITE_RETURNED.
Referenced by function_scope().
isArgumentPosition()
bool llvm::IRPosition::isArgumentPosition () const inline
Return true if the position is an argument or call site argument.
Definition at line 659 of file Attributor.h.
References getPositionKind(), IRP_ARGUMENT, and IRP_CALL_SITE_ARGUMENT.
isFnInterfaceKind()
bool llvm::IRPosition::isFnInterfaceKind () const inline
Return true if the position refers to a function interface, that is the function scope, the function return, or an argument.
Definition at line 488 of file Attributor.h.
References getPositionKind(), IRP_ARGUMENT, IRP_FUNCTION, and IRP_RETURNED.
Referenced by llvm::IRAttribute< AK, BaseType >::initialize(), and AADereferenceableImpl::initialize().
operator void *()
llvm::IRPosition::operator void * () const inline
}
Conversion into a void * to allow reuse of pointer hashing.
Definition at line 690 of file Attributor.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getOpaqueValue().
operator!=()
bool llvm::IRPosition::operator!= (const IRPosition & RHS) const inline
Definition at line 449 of file Attributor.h.
References RHS.
operator==()
bool llvm::IRPosition::operator== (const IRPosition & RHS) const inline
Definition at line 446 of file Attributor.h.
References RHS.
removeAttrs()
void llvm::IRPosition::removeAttrs (ArrayRef< Attribute::AttrKind > AKs) const inline
Remove the attribute of kind AKs existing in the IR at this position.
Definition at line 626 of file Attributor.h.
References getAnchorValue(), getAssociatedFunction(), llvm::Function::getAttributes(), llvm::AttributeList::getAttributes(), getAttrIdx(), llvm::Value::getContext(), getPositionKind(), IRP_FLOAT, IRP_INVALID, llvm::AttributeList::removeAttributeAtIndex(), and llvm::Function::setAttributes().
Referenced by AAMemoryLocationImpl::getKnownStateFromValue(), AAMemoryBehaviorImpl::manifest(), and AAMemoryLocationImpl::manifest().
returned()
static const IRPosition llvm::IRPosition::returned (const Function & F, const CallBaseContext * CBContext = nullptr) inline static
Create a position describing the returned value of F.
CBContext is used for call base specific analysis.
Definition at line 390 of file Attributor.h.
References F, IRP_RETURNED, and IRPosition().
Referenced by llvm::Attributor::identifyDefaultAbstractAttributes(), llvm::Attributor::isAssumedDead(), llvm::SubsumingPositionIterator::SubsumingPositionIterator(), AAUndefinedBehaviorImpl::updateImpl(), and AANoAliasCallSiteReturned::updateImpl().
stripCallBaseContext()
IRPosition llvm::IRPosition::stripCallBaseContext () const inline
Return the same position without the call base context.
Definition at line 670 of file Attributor.h.
Referenced by llvm::Attributor::getOrCreateAAFor().
value()
static const IRPosition llvm::IRPosition::value (const Value & V, const CallBaseContext * CBContext = nullptr) inline static
Create a position describing the value of V.
Definition at line 364 of file Attributor.h.
References Arg, argument(), callsite_returned(), IRP_FLOAT, and IRPosition().
Referenced by AAValueConstantRangeFloating::calculateBinaryOperator(), AAValueConstantRangeFloating::calculateCastInst(), AAValueConstantRangeFloating::calculateCmpInst(), llvm::Attributor::getAssumedConstant(), llvm::Attributor::getAssumedSimplified(), llvm::AA::getPotentialCopiesOfStoredValue(), AAValueSimplifyFloating::handleCmp(), AAValueSimplifyFloating::handleGenericInst(), AAValueSimplifyImpl::handleLoad(), llvm::Attributor::identifyDefaultAbstractAttributes(), AANoAliasFloating::initialize(), llvm::Attributor::isAssumedDead(), AAIsDeadFloating::isDeadStore(), AACaptureUseTracker::isDereferenceableOrNull(), AANoAliasCallSiteArgument::isKnownNoAliasDueToNoAliasPreservation(), AAPrivatizablePtrArgument::manifest(), llvm::SubsumingPositionIterator::SubsumingPositionIterator(), AAReturnedValuesImpl::updateImpl(), AANonNullFloating::updateImpl(), AAUndefinedBehaviorImpl::updateImpl(), AANoAliasCallSiteArgument::updateImpl(), AANoAliasReturned::updateImpl(), AADereferenceableFloating::updateImpl(), AAAlignFloating::updateImpl(), AAValueSimplifyReturned::updateImpl(), AAValueSimplifyFloating::updateImpl(), AAPrivatizablePtrArgument::updateImpl(), AAValueConstantRangeFloating::updateImpl(), AAPotentialValuesCallSiteArgument::updateImpl(), AANoUndefFloating::updateImpl(), AACallEdgesCallSite::updateImpl(), AAPotentialValuesFloating::updateWithBinaryOperator(), AAPotentialValuesFloating::updateWithCastInst(), AAPotentialValuesFloating::updateWithICmpInst(), AAPotentialValuesFloating::updateWithPHINode(), and AAPotentialValuesFloating::updateWithSelectInst().
Member Data Documentation
EmptyKey
const IRPosition IRPosition::EmptyKey static
Special DenseMap key values.
{
Definition at line 685 of file Attributor.h.
Referenced by llvm::DenseMapInfo< IRPosition >::getEmptyKey().
TombstoneKey
const IRPosition IRPosition::TombstoneKey static
Definition at line 686 of file Attributor.h.
Referenced by llvm::DenseMapInfo< IRPosition >::getTombstoneKey().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/IPO/Attributor.h
lib/Transforms/IPO/Attributor.cpp