LLVM: AAAlignFloating Struct Reference
AAAlignFloating Struct Reference
Align attribute for a floating value.
Public Member Functions
AAAlignFloating (const IRPosition &IRP, Attributor &A)
ChangeStatus updateImpl (Attributor &A) override
See AbstractAttribute::updateImpl(...).
void trackStatistics () const override
See AbstractAttribute::trackStatistics()
Public Member Functions inherited from AAAlignImpl
AAAlignImpl (const IRPosition &IRP, Attributor &A)
void initialize (Attributor &A) override
See AbstractAttribute::initialize(...).
ChangeStatus manifest (Attributor &A) override
See AbstractAttribute::manifest(...).
virtual void getDeducedAttributes (LLVMContext &Ctx, SmallVectorImpl< Attribute > &Attrs) const override
See AbstractAttribute::getDeducedAttributes.
bool followUseInMBEC (Attributor &A, const Use *U, const Instruction *I, AAAlign::StateType &State)
See followUsesInMBEC.
const std::string getAsStr () const override
See AbstractAttribute::getAsStr().
Public Member Functions inherited from llvm::AAAlign
AAAlign (const IRPosition &IRP, Attributor &A)
uint64_t getAssumedAlign () const
Return assumed alignment.
uint64_t getKnownAlign () const
Return known alignment.
const std::string getName () const override
See AbstractAttribute::getName()
const char * getIdAddr () const override
See AbstractAttribute::getIdAddr()
Public Member Functions inherited from llvm::IRAttribute< Attribute::Alignment, StateWrapper< AAAlignmentStateType, AbstractAttribute > >
IRAttribute (const IRPosition &IRP)
ChangeStatus manifest (Attributor &A) override
See AbstractAttribute::manifest(...).
Attribute::AttrKind getAttrKind () const
Return the kind that identifies the abstract attribute implementation.
Public Member Functions inherited from llvm::StateWrapper< StateTy, BaseType, Ts >
StateWrapper (const IRPosition &IRP, Ts... Args)
StateType & getState () override
See AbstractAttribute::getState(...).
const StateType & getState () const override
See AbstractAttribute::getState(...).
Additional Inherited Members
Public Types inherited from llvm::StateWrapper< StateTy, BaseType, Ts >
using StateType = StateTy
Provide static access to the type of the state.
Static Public Member Functions inherited from llvm::AAAlign
static bool classof (const AbstractAttribute *AA)
This function should return true if the type of the AA is AAAlign.
static AAAlign & createForPosition (const IRPosition &IRP, Attributor &A)
Create an abstract attribute view for the position IRP.
Static Public Attributes inherited from llvm::AAAlign
static const char ID = 0
Unique ID (due to the unique address)
Detailed Description
Align attribute for a floating value.
Definition at line 4560 of file AttributorAttributes.cpp.
Constructor & Destructor Documentation
AAAlignFloating()
AAAlignFloating::AAAlignFloating (const IRPosition & IRP, Attributor & A) inline
Definition at line 4561 of file AttributorAttributes.cpp.
Member Function Documentation
trackStatistics()
void AAAlignFloating::trackStatistics () const inline override
See AbstractAttribute::trackStatistics()
Definition at line 4611 of file AttributorAttributes.cpp.
References STATS_DECLTRACK_FLOATING_ATTR.
updateImpl()
ChangeStatus AAAlignFloating::updateImpl (Attributor & A) inline override
See AbstractAttribute::updateImpl(...).
Definition at line 4564 of file AttributorAttributes.cpp.
References llvm::abs(), llvm::sampleprof::Base, llvm::clampStateAndIndicateChange(), DL, llvm::SIInstrFlags::DS, gcd(), llvm::Value::getPointerAlignment(), llvm::GetPointerBaseWithConstantOffset(), llvm::greatestCommonDivisor(), Offset, llvm::PowerOf2Floor(), llvm::REQUIRED, T, llvm::Align::value(), and llvm::IRPosition::value().
Referenced by AAAlignCallSiteArgument::updateImpl().
The documentation for this struct was generated from the following file:
lib/Transforms/IPO/AttributorAttributes.cpp