LLVM: lib/CodeGen/SelectionDAG/TargetLowering.cpp File Reference
TargetLowering.cpp File Reference
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/Support/DivisionByConstantInfo.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Target/TargetMachine.h"
#include <cctype>
Functions
static APInt getKnownUndefForVectorBinop (SDValue BO, SelectionDAG &DAG, const APInt &UndefOp0, const APInt &UndefOp1)
Given a vector binary operation and known undefined elements for each input operand, compute whether each element of the output is undefined.
static SDValue simplifySetCCWithCTPOP (const TargetLowering &TLI, EVT VT, SDValue N0, const APInt &C1, ISD::CondCode Cond, const SDLoc &dl, SelectionDAG &DAG)
static unsigned getConstraintGenerality (TargetLowering::ConstraintType CT)
Return an integer indicating how general CT is.
static void ChooseConstraint (TargetLowering::AsmOperandInfo &OpInfo, const TargetLowering &TLI, SDValue Op, SelectionDAG *DAG)
If there are multiple different constraints that we could pick for this operand (e.g.
static SDValue BuildExactSDIV (const TargetLowering &TLI, SDNode *N, const SDLoc &dl, SelectionDAG &DAG, SmallVectorImpl< SDNode * > &Created)
Given an exact SDIV by a constant, create a multiplication with the multiplicative inverse of the constant.
static void turnVectorIntoSplatVector (MutableArrayRef< SDValue > Values, std::function< bool(SDValue)> Predicate, SDValue AlternativeReplacement=SDValue())
If all values in Values that don't match the predicate are same 'splat' value, then replace all values with that splat value.
static bool isNonZeroModBitWidthOrUndef (SDValue Z, unsigned BW)
static bool canExpandVectorCTPOP (const TargetLowering &TLI, EVT VT)
static SDValue clampDynamicVectorIndex (SelectionDAG &DAG, SDValue Idx, EVT VecVT, const SDLoc &dl, ElementCount SubEC)
Function Documentation
BuildExactSDIV()
static SDValue BuildExactSDIV (const TargetLowering & TLI, SDNode * N, const SDLoc & dl, SelectionDAG & DAG, SmallVectorImpl< SDNode * > & Created) static
Given an exact SDIV by a constant, create a multiplication with the multiplicative inverse of the constant.
Definition at line 5159 of file TargetLowering.cpp.
References llvm::APInt::ashrInPlace(), assert(), llvm::ISD::BUILD_VECTOR, C, llvm::APInt::countTrailingZeros(), llvm::APInt::getBitWidth(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getDataLayout(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::EVT::getScalarType(), llvm::TargetLoweringBase::getShiftAmountTy(), llvm::SelectionDAG::getSplatVector(), llvm::ISD::matchUnaryPredicate(), llvm::ISD::MUL, N, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SDNodeFlags::setExact(), llvm::SmallVectorBase< Size_T >::size(), llvm::ISD::SPLAT_VECTOR, and llvm::ISD::SRA.
Referenced by llvm::TargetLowering::BuildSDIV().
canExpandVectorCTPOP()
static bool canExpandVectorCTPOP (const TargetLowering & TLI, EVT VT) static
Definition at line 7085 of file TargetLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, assert(), llvm::EVT::getScalarSizeInBits(), llvm::TargetLoweringBase::isOperationLegalOrCustom(), llvm::TargetLoweringBase::isOperationLegalOrCustomOrPromote(), llvm::EVT::isVector(), llvm::ISD::MUL, llvm::ISD::SRL, and llvm::ISD::SUB.
ChooseConstraint()
static void ChooseConstraint (TargetLowering::AsmOperandInfo & OpInfo, const TargetLowering & TLI, SDValue Op, SelectionDAG * DAG) static
If there are multiple different constraints that we could pick for this operand (e.g.
"imr") try to pick the 'best' one. This is somewhat tricky: constraints fall into four classes: Other -> immediates and magic values Register -> one specific register RegisterClass -> a group of regs Memory -> memory Ideally, we would pick the most specific constraint possible: if we have something that fits into a register, we would pick it. The problem here is that if we have something that could either be in a register or in memory that use of the register could cause selection of other operands to fail: they might only succeed if we pick memory. Because of this the heuristic we use is:
1) If there is an 'other' constraint, and if the operand is valid for that constraint, use it. This makes us take advantage of 'i' constraints when available. 2) Otherwise, pick the most general constraint present. This prefers 'm' over 'r', for example.
Definition at line 5063 of file TargetLowering.cpp.
References assert(), llvm::TargetLowering::C_Immediate, llvm::TargetLowering::C_Memory, llvm::TargetLowering::C_Other, llvm::TargetLowering::C_Register, llvm::TargetLowering::C_RegisterClass, llvm::TargetLowering::C_Unknown, llvm::InlineAsm::ConstraintInfo::Codes, llvm::TargetLowering::AsmOperandInfo::ConstraintCode, llvm::TargetLowering::AsmOperandInfo::ConstraintType, llvm::numbers::e, getConstraintGenerality(), llvm::TargetLowering::getConstraintType(), llvm::InlineAsm::ConstraintInfo::hasMatchingInput(), llvm::InlineAsm::ConstraintInfo::isIndirect, and llvm::TargetLowering::LowerAsmOperandForConstraint().
Referenced by llvm::TargetLowering::ComputeConstraintToUse().
clampDynamicVectorIndex()
static SDValue clampDynamicVectorIndex (SelectionDAG & DAG, SDValue Idx, EVT VecVT, const SDLoc & dl, ElementCount SubEC) static
Definition at line 7905 of file TargetLowering.cpp.
References llvm::ISD::AND, assert(), llvm::SelectionDAG::getConstant(), llvm::EVT::getFixedSizeInBits(), llvm::LinearPolySize< LeafTy >::getKnownMinValue(), llvm::APInt::getLowBitsSet(), llvm::SelectionDAG::getNode(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorMinNumElements(), llvm::SelectionDAG::getVScale(), llvm::EVT::isFixedLengthVector(), llvm::isPowerOf2_32(), llvm::LinearPolySize< LeafTy >::isScalable(), llvm::EVT::isScalableVector(), llvm::Log2_32(), llvm::ISD::SUB, llvm::ISD::UMIN, llvm::ISD::USUBSAT, and llvm::AArch64CC::VS.
Referenced by llvm::TargetLowering::getVectorSubVecPointer().
getConstraintGenerality()
static unsigned getConstraintGenerality (TargetLowering::ConstraintType CT) static
Return an integer indicating how general CT is.
Definition at line 4954 of file TargetLowering.cpp.
References llvm::TargetLowering::C_Immediate, llvm::TargetLowering::C_Memory, llvm::TargetLowering::C_Other, llvm::TargetLowering::C_Register, llvm::TargetLowering::C_RegisterClass, llvm::TargetLowering::C_Unknown, and llvm_unreachable.
Referenced by ChooseConstraint().
getKnownUndefForVectorBinop()
static APInt getKnownUndefForVectorBinop (SDValue BO, SelectionDAG & DAG, const APInt & UndefOp0, const APInt & UndefOp1) static
Given a vector binary operation and known undefined elements for each input operand, compute whether each element of the output is undefined.
Definition at line 2392 of file TargetLowering.cpp.
References assert(), C, llvm::APInt::getBitWidth(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::APInt::getZero(), Index, llvm::TargetLoweringBase::isBinOp(), llvm::SDValue::isUndef(), isUndef(), llvm::EVT::isVector(), and llvm::APInt::setBit().
Referenced by llvm::TargetLowering::SimplifyDemandedVectorElts().
isNonZeroModBitWidthOrUndef()
static bool isNonZeroModBitWidthOrUndef (SDValue Z, unsigned BW) static
Definition at line 6595 of file TargetLowering.cpp.
References C, and llvm::ISD::matchUnaryPredicate().
simplifySetCCWithCTPOP()
static SDValue simplifySetCCWithCTPOP (const TargetLowering & TLI, EVT VT, SDValue N0, const APInt & C1, ISD::CondCode Cond, const SDLoc & dl, SelectionDAG & DAG) static
Definition at line 3553 of file TargetLowering.cpp.
References llvm::ISD::ADD, llvm::And, llvm::ISD::AND, assert(), Cond, llvm::ISD::CTPOP, llvm::SelectionDAG::getAllOnesConstant(), llvm::SelectionDAG::getConstant(), llvm::TargetLoweringBase::getCustomCtpopCost(), llvm::APInt::getLimitedValue(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getScalarValueSizeInBits(), llvm::SelectionDAG::getSetCC(), llvm::ISD::getSetCCInverse(), llvm::SDValue::hasOneUse(), llvm::EVT::isInteger(), llvm::TargetLoweringBase::isOperationLegal(), llvm::TargetLoweringBase::isOperationLegalOrCustom(), llvm::EVT::isVector(), LHS, llvm::Log2_32(), llvm::ISD::OR, Passes, RHS, llvm::ISD::SETEQ, llvm::ISD::SETNE, llvm::ISD::SETUGT, llvm::ISD::SETULT, llvm::ISD::TRUNCATE, and llvm::APInt::ugt().
Referenced by llvm::TargetLowering::SimplifySetCC().
turnVectorIntoSplatVector()
static void turnVectorIntoSplatVector (MutableArrayRef< SDValue > Values, std::function< bool(SDValue)> Predicate, SDValue AlternativeReplacement = SDValue()) static
If all values in Values that don't match the predicate are same 'splat' value, then replace all values with that splat value.
Else, if AlternativeReplacement was provided, then replace all values that do match predicate with AlternativeReplacement value.
Definition at line 5555 of file TargetLowering.cpp.
References llvm::all_of(), llvm::MutableArrayRef< T >::begin(), llvm::MutableArrayRef< T >::end(), and llvm::find_if_not().