LLVM: lib/Target/AArch64/AArch64Subtarget.cpp File Reference
AArch64Subtarget.cpp File Reference
#include "AArch64Subtarget.h"
#include "AArch64.h"
#include "AArch64InstrInfo.h"
#include "AArch64PBQPRegAlloc.h"
#include "AArch64TargetMachine.h"
#include "GISel/AArch64CallLowering.h"
#include "GISel/AArch64LegalizerInfo.h"
#include "GISel/AArch64RegisterBankInfo.h"
#include "MCTargetDesc/AArch64AddressingModes.h"
#include "llvm/CodeGen/GlobalISel/InstructionSelect.h"
#include "llvm/CodeGen/MachineScheduler.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/Support/TargetParser.h"
#include "AArch64GenSubtargetInfo.inc"
Macros
#define DEBUG_TYPE "aarch64-subtarget"
#define GET_SUBTARGETINFO_CTOR
#define GET_SUBTARGETINFO_TARGET_DESC
Variables
static cl::opt< bool > EnableEarlyIfConvert ("aarch64-early-ifcvt", cl::desc("Enable the early if " "converter pass"), cl::init(true), cl::Hidden)
static cl::opt< bool > UseAddressTopByteIgnored ("aarch64-use-tbi", cl::desc("Assume that top byte of " "an address is ignored"), cl::init(false), cl::Hidden)
static cl::opt< bool > UseNonLazyBind ("aarch64-enable-nonlazybind", cl::desc("Call nonlazybind functions via direct GOT load"), cl::init(false), cl::Hidden)
static cl::opt< unsigned > SVEVectorBitsMax ("aarch64-sve-vector-bits-max", cl::desc("Assume SVE vector registers are at most this big, " "with zero meaning no maximum size is assumed."), cl::init(0), cl::Hidden)
static cl::opt< unsigned > SVEVectorBitsMin ("aarch64-sve-vector-bits-min", cl::desc("Assume SVE vector registers are at least this big, " "with zero meaning no minimum size is assumed."), cl::init(0), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "aarch64-subtarget"
Definition at line 30 of file AArch64Subtarget.cpp.
GET_SUBTARGETINFO_CTOR
#define GET_SUBTARGETINFO_CTOR
Definition at line 32 of file AArch64Subtarget.cpp.
GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_TARGET_DESC
Definition at line 33 of file AArch64Subtarget.cpp.
Variable Documentation
EnableEarlyIfConvert
cl::opt<bool> EnableEarlyIfConvert("aarch64-early-ifcvt", cl::desc("Enable the early if " "converter pass"), cl::init(true), cl::Hidden) ("aarch64-early-ifcvt" , cl::desc("Enable the early if " "converter pass") , cl::init(true) , cl::Hidden) static
Referenced by llvm::AArch64Subtarget::enableEarlyIfConversion().
SVEVectorBitsMax
cl::opt<unsigned> SVEVectorBitsMax("aarch64-sve-vector-bits-max", cl::desc("Assume SVE vector registers are at most this big, " "with zero meaning no maximum size is assumed."), cl::init(0), cl::Hidden) ("aarch64-sve-vector-bits-max" , cl::desc("Assume SVE vector registers are at most this big, " "with zero meaning no maximum size is assumed.") , cl::init(0) , cl::Hidden) static
Referenced by llvm::AArch64Subtarget::getMaxSVEVectorSizeInBits(), and llvm::AArch64Subtarget::getMinSVEVectorSizeInBits().
SVEVectorBitsMin
cl::opt<unsigned> SVEVectorBitsMin("aarch64-sve-vector-bits-min", cl::desc("Assume SVE vector registers are at least this big, " "with zero meaning no minimum size is assumed."), cl::init(0), cl::Hidden) ("aarch64-sve-vector-bits-min" , cl::desc("Assume SVE vector registers are at least this big, " "with zero meaning no minimum size is assumed.") , cl::init(0) , cl::Hidden) static
Referenced by llvm::AArch64Subtarget::getMaxSVEVectorSizeInBits(), and llvm::AArch64Subtarget::getMinSVEVectorSizeInBits().
UseAddressTopByteIgnored
cl::opt<bool> UseAddressTopByteIgnored("aarch64-use-tbi", cl::desc("Assume that top byte of " "an address is ignored"), cl::init(false), cl::Hidden) ("aarch64-use-tbi" , cl::desc("Assume that top byte of " "an address is ignored") , cl::init(false) , cl::Hidden) static
Referenced by llvm::AArch64Subtarget::supportsAddressTopByteIgnored().
UseNonLazyBind
cl::opt<bool> UseNonLazyBind("aarch64-enable-nonlazybind", cl::desc("Call nonlazybind functions via direct GOT load"), cl::init(false), cl::Hidden) ("aarch64-enable-nonlazybind" , cl::desc("Call nonlazybind functions via direct GOT load") , cl::init(false) , cl::Hidden) static
Referenced by llvm::AArch64Subtarget::classifyGlobalFunctionReference().