LLVM: lib/Target/AArch64/AArch64MachineFunctionInfo.cpp File Reference
AArch64MachineFunctionInfo.cpp File Reference
This file implements AArch64-specific per-machine-function information.
#include "AArch64MachineFunctionInfo.h"
#include "AArch64InstrInfo.h"
#include <llvm/IR/Metadata.h>
#include <llvm/IR/Module.h>
Functions
static std::pair< bool, bool > GetSignReturnAddress (const Function &F)
static bool ShouldSignWithBKey (const Function &F)
Detailed Description
This file implements AArch64-specific per-machine-function information.
Definition in file AArch64MachineFunctionInfo.cpp.
Function Documentation
GetSignReturnAddress()
static std::pair<bool, bool> GetSignReturnAddress (const Function & F) static
Definition at line 37 of file AArch64MachineFunctionInfo.cpp.
References assert(), and F.
Referenced by llvm::AArch64FunctionInfo::AArch64FunctionInfo().
ShouldSignWithBKey()
static bool ShouldSignWithBKey (const Function & F) static
Definition at line 66 of file AArch64MachineFunctionInfo.cpp.
References assert(), and F.
Referenced by llvm::AArch64FunctionInfo::AArch64FunctionInfo().