LLVM: lib/Target/AMDGPU/AMDGPURegisterBankInfo.cpp File Reference
AMDGPURegisterBankInfo.cpp File Reference
This file implements the targeting of the RegisterBankInfo class for AMDGPU.
#include "AMDGPURegisterBankInfo.h"
#include "AMDGPU.h"
#include "AMDGPUGlobalISelUtils.h"
#include "AMDGPUInstrInfo.h"
#include "GCNSubtarget.h"
#include "SIMachineFunctionInfo.h"
#include "SIRegisterInfo.h"
#include "llvm/CodeGen/GlobalISel/LegalizerHelper.h"
#include "llvm/CodeGen/GlobalISel/MIPatternMatch.h"
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
#include "llvm/CodeGen/GlobalISel/RegisterBank.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
#include "AMDGPUGenRegisterBank.inc"
#include "AMDGPUGenRegisterBankInfo.def"
Macros
#define GET_TARGET_REGBANK_IMPL
Functions
static bool isVectorRegisterBank (const RegisterBank &Bank)
static bool memOpHasNoClobbered (const MachineMemOperand *MMO)
static bool isScalarLoadLegal (const MachineInstr &MI)
static void setRegsToType (MachineRegisterInfo &MRI, ArrayRef< Register > Regs, LLT NewTy)
Replace the current type each register in Regs has with NewTy.
static LLT getHalfSizedType (LLT Ty)
static std::pair< LLT, LLT > splitUnequalType (LLT Ty, unsigned FirstSize)
Split Ty into 2 pieces.
static LLT widen96To128 (LLT Ty)
static Register getSrcRegIgnoringCopies (const MachineRegisterInfo &MRI, Register Reg)
static unsigned setBufferOffsets (MachineIRBuilder &B, const AMDGPURegisterBankInfo &RBI, Register CombinedOffset, Register &VOffsetReg, Register &SOffsetReg, int64_t &InstOffsetVal, Align Alignment)
static CmpInst::Predicate minMaxToCompare (unsigned Opc)
static unsigned minMaxToExtend (unsigned Opc)
static std::pair< Register, Register > unpackV2S16ToS32 (MachineIRBuilder &B, Register Src, unsigned ExtOpcode)
static MachineInstr * buildExpandedScalarMinMax (MachineIRBuilder &B, CmpInst::Predicate Pred, Register Dst, Register Src0, Register Src1)
static bool substituteSimpleCopyRegs (const AMDGPURegisterBankInfo::OperandsMapper &OpdMapper, unsigned OpIdx)
static std::pair< Register, unsigned > getBaseWithConstantOffset (MachineRegisterInfo &MRI, Register Reg)
static bool isZero (Register Reg, MachineRegisterInfo &MRI)
static unsigned extractGLC (unsigned CachePolicy)
static unsigned extractSLC (unsigned CachePolicy)
static unsigned extractDLC (unsigned CachePolicy)
static void reinsertVectorIndexAdd (MachineIRBuilder &B, MachineInstr &IdxUseInstr, unsigned OpIdx, unsigned ConstOffset)
Utility function for pushing dynamic vector indexes with a constant offset into waterwall loops.
static void extendLow32IntoHigh32 (MachineIRBuilder &B, Register Hi32Reg, Register Lo32Reg, unsigned ExtOpc, const RegisterBank &RegBank, bool IsBooleanSrc=false)
Implement extending a 32-bit value to a 64-bit value.
static unsigned regBankUnion (unsigned RB0, unsigned RB1)
static unsigned regBankBoolUnion (unsigned RB0, unsigned RB1)
Detailed Description
This file implements the targeting of the RegisterBankInfo class for AMDGPU.
AMDGPU has unique register bank constraints that require special high level strategies to deal with. There are two main true physical register banks VGPR (vector), and SGPR (scalar). Additionally the VCC register bank is a sort of pseudo-register bank needed to represent SGPRs used in a vector boolean context. There is also the AGPR bank, which is a special purpose physical register bank present on some subtargets.
Copying from VGPR to SGPR is generally illegal, unless the value is known to be uniform. It is generally not valid to legalize operands by inserting copies as on other targets. Operations which require uniform, SGPR operands generally require scalarization by repeatedly executing the instruction, activating each set of lanes using a unique set of input values. This is referred to as a waterfall loop.
Booleans
Booleans (s1 values) requires special consideration. A vector compare result is naturally a bitmask with one bit per lane, in a 32 or 64-bit register. These are represented with the VCC bank. During selection, we need to be able to unambiguously go back from a register class to a register bank. To distinguish whether an SGPR should use the SGPR or VCC register bank, we need to know the use context type. An SGPR s1 value always means a VCC bank value, otherwise it will be the SGPR bank. A scalar compare sets SCC, which is a 1-bit unaddressable register. This will need to be copied to a 32-bit virtual register. Taken together, this means we need to adjust the type of boolean operations to be regbank legal. All SALU booleans need to be widened to 32-bits, and all VALU booleans need to be s1 values.
A noteworthy exception to the s1-means-vcc rule is for legalization artifact casts. G_TRUNC s1 results, and G_SEXT/G_ZEXT/G_ANYEXT sources are never vcc bank. A non-boolean source (such as a truncate from a 1-bit load from memory) will require a copy to the VCC bank which will require clearing the high bits and inserting a compare.
Constant bus restriction
VALU instructions have a limitation known as the constant bus restriction. Most VALU instructions can use SGPR operands, but may read at most 1 SGPR or constant literal value (this to 2 in gfx10 for most instructions). This is one unique SGPR, so the same SGPR may be used for multiple operands. From a register bank perspective, any combination of operands should be legal as an SGPR, but this is contextually dependent on the SGPR operands all being the same register. There is therefore optimal to choose the SGPR with the most uses to minimize the number of copies.
We avoid trying to solve this problem in RegBankSelect. Any VALU G_* operation should have its source operands all mapped to VGPRs (except for VCC), inserting copies from any SGPR operands. This the most trival legal mapping. Anything beyond the simplest 1:1 instruction selection would be too complicated to solve here. Every optimization pattern or instruction selected to multiple outputs would have to enforce this rule, and there would be additional complexity in tracking this rule for every G_* operation. By forcing all inputs to VGPRs, it also simplifies the task of picking the optimal operand combination from a post-isel optimization pass.
Definition in file AMDGPURegisterBankInfo.cpp.
Macro Definition Documentation
GET_TARGET_REGBANK_IMPL
#define GET_TARGET_REGBANK_IMPL
Definition at line 85 of file AMDGPURegisterBankInfo.cpp.
Function Documentation
buildExpandedScalarMinMax()
static MachineInstr* buildExpandedScalarMinMax (MachineIRBuilder & B, CmpInst::Predicate Pred, Register Dst, Register Src0, Register Src1) static
Definition at line 1631 of file AMDGPURegisterBankInfo.cpp.
References B, and llvm::LLT::scalar().
Referenced by llvm::AMDGPURegisterBankInfo::applyMappingImpl(), and llvm::AMDGPURegisterBankInfo::lowerScalarMinMax().
extendLow32IntoHigh32()
static void extendLow32IntoHigh32 (MachineIRBuilder & B, Register Hi32Reg, Register Lo32Reg, unsigned ExtOpc, const RegisterBank & RegBank, bool IsBooleanSrc = false) static
Implement extending a 32-bit value to a 64-bit value.
Lo32Reg is the original 32-bit source value (to be inserted in the low part of the combined 64-bit result), and Hi32Reg is the high half of the combined 64-bit value.
Definition at line 1903 of file AMDGPURegisterBankInfo.cpp.
References assert(), B, and llvm::LLT::scalar().
Referenced by llvm::AMDGPURegisterBankInfo::applyMappingImpl().
extractDLC()
static unsigned extractDLC (unsigned CachePolicy) static
Definition at line 1765 of file AMDGPURegisterBankInfo.cpp.
Referenced by llvm::AMDGPURegisterBankInfo::selectStoreIntrinsic().
extractGLC()
static unsigned extractGLC (unsigned CachePolicy) static
Definition at line 1757 of file AMDGPURegisterBankInfo.cpp.
Referenced by llvm::AMDGPURegisterBankInfo::selectStoreIntrinsic().
extractSLC()
static unsigned extractSLC (unsigned CachePolicy) static
Definition at line 1761 of file AMDGPURegisterBankInfo.cpp.
Referenced by llvm::AMDGPURegisterBankInfo::selectStoreIntrinsic().
getBaseWithConstantOffset()
static std::pair<Register, unsigned> getBaseWithConstantOffset (MachineRegisterInfo & MRI, Register Reg) static
Definition at line 1695 of file AMDGPURegisterBankInfo.cpp.
References llvm::MIPatternMatch::m_GAdd(), llvm::MIPatternMatch::m_ICst(), llvm::MIPatternMatch::m_Reg(), llvm::MIPatternMatch::mi_match(), MRI, and Reg.
Referenced by llvm::AMDGPURegisterBankInfo::splitBufferOffsets().
getHalfSizedType()
static LLT getHalfSizedType (LLT Ty) static
Definition at line 692 of file AMDGPURegisterBankInfo.cpp.
References assert(), llvm::LLT::getElementType(), llvm::LLT::getNumElements(), llvm::LLT::getSizeInBits(), llvm::LLT::isVector(), llvm::LLT::scalar(), and llvm::LLT::scalarOrVector().
Referenced by llvm::AMDGPURegisterBankInfo::applyMappingImpl().
getSrcRegIgnoringCopies()
static Register getSrcRegIgnoringCopies (const MachineRegisterInfo & MRI, Register Reg) static
Definition at line 1307 of file AMDGPURegisterBankInfo.cpp.
References llvm::tgtok::Def, llvm::getDefIgnoringCopies(), MRI, and Reg.
isScalarLoadLegal()
static bool isScalarLoadLegal (const MachineInstr & MI) static
Definition at line 438 of file AMDGPURegisterBankInfo.cpp.
References Align, llvm::AMDGPUAS::CONSTANT_ADDRESS, llvm::AMDGPUAS::CONSTANT_ADDRESS_32BIT, llvm::MachineMemOperand::getAddrSpace(), llvm::MachineMemOperand::getAlign(), llvm::MachineMemOperand::getSize(), llvm::MachineMemOperand::isAtomic(), llvm::AMDGPU::HSAMD::Kernel::Arg::Key::IsConst, llvm::MachineMemOperand::isInvariant(), llvm::AMDGPUInstrInfo::isUniformMMO(), llvm::MachineMemOperand::isVolatile(), memOpHasNoClobbered(), and MI.
Referenced by llvm::AMDGPURegisterBankInfo::getInstrAlternativeMappings(), and llvm::AMDGPURegisterBankInfo::getInstrMappingForLoad().
isVectorRegisterBank()
static bool isVectorRegisterBank (const RegisterBank & Bank) static
Definition at line 214 of file AMDGPURegisterBankInfo.cpp.
References llvm::RegisterBank::getID().
Referenced by llvm::AMDGPURegisterBankInfo::copyCost().
isZero()
static bool isZero (Register Reg, MachineRegisterInfo & MRI) static
Definition at line 1752 of file AMDGPURegisterBankInfo.cpp.
References C, llvm::MIPatternMatch::m_ICst(), llvm::MIPatternMatch::mi_match(), MRI, and Reg.
Referenced by llvm::AMDGPURegisterBankInfo::selectStoreIntrinsic().
memOpHasNoClobbered()
static bool memOpHasNoClobbered (const MachineMemOperand * MMO) static
Definition at line 431 of file AMDGPURegisterBankInfo.cpp.
References llvm::MachineMemOperand::getValue(), and I.
Referenced by isScalarLoadLegal().
minMaxToCompare()
static CmpInst::Predicate minMaxToCompare (unsigned Opc) static
Definition at line 1580 of file AMDGPURegisterBankInfo.cpp.
References llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, and llvm_unreachable.
Referenced by llvm::AMDGPURegisterBankInfo::applyMappingImpl(), and llvm::AMDGPURegisterBankInfo::lowerScalarMinMax().
minMaxToExtend()
static unsigned minMaxToExtend (unsigned Opc) static
Definition at line 1595 of file AMDGPURegisterBankInfo.cpp.
References llvm_unreachable.
Referenced by llvm::AMDGPURegisterBankInfo::applyMappingImpl().
regBankBoolUnion()
static unsigned regBankBoolUnion (unsigned RB0, unsigned RB1) static
Definition at line 3136 of file AMDGPURegisterBankInfo.cpp.
References regBankUnion().
Referenced by llvm::AMDGPURegisterBankInfo::getInstrMapping().
regBankUnion()
static unsigned regBankUnion (unsigned RB0, unsigned RB1) static
Definition at line 3121 of file AMDGPURegisterBankInfo.cpp.
Referenced by llvm::AMDGPURegisterBankInfo::getInstrMapping(), llvm::AMDGPURegisterBankInfo::getMappingType(), and regBankBoolUnion().
reinsertVectorIndexAdd()
static void reinsertVectorIndexAdd (MachineIRBuilder & B, MachineInstr & IdxUseInstr, unsigned OpIdx, unsigned ConstOffset) static
Utility function for pushing dynamic vector indexes with a constant offset into waterwall loops.
Definition at line 1882 of file AMDGPURegisterBankInfo.cpp.
References B, llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), MRI, llvm::LLT::scalar(), and llvm::MachineOperand::setReg().
Referenced by llvm::AMDGPURegisterBankInfo::applyMappingImpl().
setBufferOffsets()
static unsigned setBufferOffsets (MachineIRBuilder & B, const AMDGPURegisterBankInfo & RBI, Register CombinedOffset, Register & VOffsetReg, Register & SOffsetReg, int64_t & InstOffsetVal, Align Alignment) static
Definition at line 1319 of file AMDGPURegisterBankInfo.cpp.
References B, llvm::AMDGPU::getBaseWithConstantOffset(), llvm::getConstantVRegSExtVal(), llvm::getOpcodeDef(), llvm::RegisterBankInfo::getRegBank(), llvm::getSrcRegIgnoringCopies(), MRI, Offset, llvm::LLT::scalar(), llvm::AMDGPU::splitMUBUFOffset(), llvm::AMDGPURegisterBankInfo::Subtarget, and llvm::AMDGPURegisterBankInfo::TRI.
Referenced by llvm::AMDGPURegisterBankInfo::applyMappingSBufferLoad().
setRegsToType()
static void setRegsToType (MachineRegisterInfo & MRI, ArrayRef< Register > Regs, LLT NewTy) static
Replace the current type each register in Regs has with NewTy.
Definition at line 684 of file AMDGPURegisterBankInfo.cpp.
References assert(), llvm::LLT::getSizeInBits(), MRI, and Reg.
Referenced by llvm::AMDGPURegisterBankInfo::applyMappingImpl().
splitUnequalType()
static std::pair<LLT, LLT> splitUnequalType (LLT Ty, unsigned FirstSize) static
Split Ty into 2 pieces.
The first will have FirstSize bits, and the rest will be in the remainder.
Definition at line 1130 of file AMDGPURegisterBankInfo.cpp.
References assert(), llvm::LLT::getElementType(), llvm::LLT::getSizeInBits(), llvm::LLT::isVector(), llvm::LLT::scalar(), and llvm::LLT::scalarOrVector().
Referenced by llvm::AMDGPURegisterBankInfo::applyMappingLoad().
substituteSimpleCopyRegs()
static bool substituteSimpleCopyRegs (const AMDGPURegisterBankInfo::OperandsMapper & OpdMapper, unsigned OpIdx) static
Definition at line 1657 of file AMDGPURegisterBankInfo.cpp.
References assert(), llvm::SmallVectorBase< Size_T >::empty(), and llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::AMDGPURegisterBankInfo::applyMappingImpl().
unpackV2S16ToS32()
static std::pair<Register, Register> unpackV2S16ToS32 (MachineIRBuilder & B, Register Src, unsigned ExtOpcode) static
Definition at line 1611 of file AMDGPURegisterBankInfo.cpp.
References assert(), B, llvm::LegalizeActions::Bitcast, and llvm::LLT::scalar().
Referenced by llvm::AMDGPURegisterBankInfo::applyMappingImpl().
widen96To128()
static LLT widen96To128 (LLT Ty) static
Definition at line 1146 of file AMDGPURegisterBankInfo.cpp.
References assert(), llvm::LLT::getElementType(), llvm::LLT::getSizeInBits(), llvm::LLT::isVector(), llvm::LLT::scalar(), and llvm::LLT::vector().
Referenced by llvm::AMDGPURegisterBankInfo::applyMappingLoad().