LLVM: llvm::SCEVUDivExpr Class Reference
llvm::SCEVUDivExpr Class Reference
This class represents a binary unsigned division operation.
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
Public Types
using op_iterator = std::array< const SCEV *, 2 >::const_iterator
using op_range = iterator_range< op_iterator >
Public Types inherited from llvm::SCEV
enum NoWrapFlags {
FlagAnyWrap = 0 , FlagNW = (1 << 0) , FlagNUW = (1 << 1) , FlagNSW = (1 << 2) ,
NoWrapMask = (1 << 3) - 1
}
NoWrapFlags are bitfield indices into SubclassData.
Public Member Functions
const SCEV * getLHS () const
const SCEV * getRHS () const
size_t getNumOperands () const
const SCEV * getOperand (unsigned i) const
op_range operands () const
Type * getType () const
Public Member Functions inherited from llvm::SCEV
SCEV (const FoldingSetNodeIDRef ID, SCEVTypes SCEVTy, unsigned short ExpressionSize)
SCEV (const SCEV &)=delete
SCEV & operator= (const SCEV &)=delete
SCEVTypes getSCEVType () const
Type * getType () const
Return the LLVM type of this SCEV expression.
bool isZero () const
Return true if the expression is a constant zero.
bool isOne () const
Return true if the expression is a constant one.
bool isAllOnesValue () const
Return true if the expression is a constant all-ones value.
bool isNonConstantNegative () const
Return true if the specified scev is negated, but not a constant.
unsigned short getExpressionSize () const
void print (raw_ostream &OS) const
Print out the internal representation of this scalar to the specified stream.
void dump () const
This method is used for debugging.
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static bool classof (const SCEV *S)
Methods for support type inquiry through isa, cast, and dyn_cast:
Friends
class ScalarEvolution
Additional Inherited Members
Protected Attributes inherited from llvm::SCEV
const unsigned short ExpressionSize
unsigned short SubclassData = 0
This field is initialized to zero and may be used in subclasses to store miscellaneous information.
Detailed Description
This class represents a binary unsigned division operation.
Definition at line 303 of file ScalarEvolutionExpressions.h.
Member Typedef Documentation
op_iterator
using llvm::SCEVUDivExpr::op_iterator = std::array<const SCEV *, 2>::const_iterator
Definition at line 323 of file ScalarEvolutionExpressions.h.
op_range
using llvm::SCEVUDivExpr::op_range = iterator_range<op_iterator>
Definition at line 324 of file ScalarEvolutionExpressions.h.
Member Function Documentation
classof()
static bool llvm::SCEVUDivExpr::classof (const SCEV * S) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 339 of file ScalarEvolutionExpressions.h.
References llvm::SCEV::getSCEVType(), and llvm::scUDivExpr.
getLHS()
const SCEV* llvm::SCEVUDivExpr::getLHS () const inline
Definition at line 315 of file ScalarEvolutionExpressions.h.
References Operands.
Referenced by BuildConstantFromSCEV(), CompareSCEVComplexity(), getOperand(), llvm::SCEV::print(), llvm::SCEVTraversal< SV >::visitAll(), and llvm::SCEVRewriteVisitor< SC >::visitUDivExpr().
getNumOperands()
size_t llvm::SCEVUDivExpr::getNumOperands () const inline
Definition at line 317 of file ScalarEvolutionExpressions.h.
getOperand()
const SCEV* llvm::SCEVUDivExpr::getOperand (unsigned i) const inline
Definition at line 318 of file ScalarEvolutionExpressions.h.
References assert(), getLHS(), and getRHS().
getRHS()
const SCEV* llvm::SCEVUDivExpr::getRHS () const inline
Definition at line 316 of file ScalarEvolutionExpressions.h.
References Operands.
Referenced by BuildConstantFromSCEV(), CompareSCEVComplexity(), getOperand(), getType(), llvm::SCEV::print(), llvm::SCEVTraversal< SV >::visitAll(), and llvm::SCEVRewriteVisitor< SC >::visitUDivExpr().
getType()
Type* llvm::SCEVUDivExpr::getType () const inline
Definition at line 329 of file ScalarEvolutionExpressions.h.
References getRHS(), and llvm::SCEV::getType().
operands()
op_range llvm::SCEVUDivExpr::operands () const inline
Definition at line 325 of file ScalarEvolutionExpressions.h.
References llvm::make_range(), and Operands.
Friends And Related Function Documentation
ScalarEvolution
friend class ScalarEvolution friend
Definition at line 304 of file ScalarEvolutionExpressions.h.
The documentation for this class was generated from the following file:
include/llvm/Analysis/ScalarEvolutionExpressions.h