LLVM: llvm::SetVector< T, Vector, Set > Class Template Reference
llvm::SetVector< T, Vector, Set > Class Template Reference
A vector that has set insertion semantics.
#include "llvm/ADT/SetVector.h"
Public Types
using value_type = T
using key_type = T
using reference = T &
using const_reference = const T &
using set_type = Set
using vector_type = Vector
using iterator = typename vector_type::const_iterator
using const_iterator = typename vector_type::const_iterator
using reverse_iterator = typename vector_type::const_reverse_iterator
using const_reverse_iterator = typename vector_type::const_reverse_iterator
using size_type = typename vector_type::size_type
Public Member Functions
SetVector ()=default
Construct an empty SetVector.
template<typename It >
SetVector (It Start, It End)
Initialize a SetVector with a range of elements.
ArrayRef< T > getArrayRef () const
Vector takeVector ()
Clear the SetVector and return the underlying vector.
bool empty () const
Determine if the SetVector is empty or not.
size_type size () const
Determine the number of elements in the SetVector.
iterator begin ()
Get an iterator to the beginning of the SetVector.
const_iterator begin () const
Get a const_iterator to the beginning of the SetVector.
iterator end ()
Get an iterator to the end of the SetVector.
const_iterator end () const
Get a const_iterator to the end of the SetVector.
reverse_iterator rbegin ()
Get an reverse_iterator to the end of the SetVector.
const_reverse_iterator rbegin () const
Get a const_reverse_iterator to the end of the SetVector.
reverse_iterator rend ()
Get a reverse_iterator to the beginning of the SetVector.
const_reverse_iterator rend () const
Get a const_reverse_iterator to the beginning of the SetVector.
const T & front () const
Return the first element of the SetVector.
const T & back () const
Return the last element of the SetVector.
const_reference operator[] (size_type n) const
Index into the SetVector.
bool insert (const value_type &X)
Insert a new element into the SetVector.
template<typename It >
void insert (It Start, It End)
Insert a range of elements into the SetVector.
bool remove (const value_type &X)
Remove an item from the set vector.
iterator erase (iterator I)
Erase a single element from the set vector.
template<typename UnaryPredicate >
bool remove_if (UnaryPredicate P)
Remove items from the set vector based on a predicate function.
bool contains (const key_type &key) const
Check if the SetVector contains the given key.
size_type count (const key_type &key) const
Count the number of elements of a given key in the SetVector.
void clear ()
Completely clear the SetVector.
void pop_back ()
Remove the last element of the SetVector.
LLVM_NODISCARD T pop_back_val ()
bool operator== (const SetVector &that) const
bool operator!= (const SetVector &that) const
template<class STy >
bool set_union (const STy &S)
Compute This := This u S, return whether 'This' changed.
template<class STy >
void set_subtract (const STy &S)
Compute This := This - B TODO: We should be able to use set_subtract from SetOperations.h, but SetVector interface is inconsistent with DenseSet.
void swap (SetVector< T, Vector, Set > &RHS)
Detailed Description
template<typename T, typename Vector = std::vector<T>, typename Set = DenseSet<T>>
class llvm::SetVector< T, Vector, Set >
A vector that has set insertion semantics.
This adapter class provides a way to keep a set of things that also has the property of a deterministic iteration order. The order of iteration is the order of insertion.
Definition at line 40 of file SetVector.h.
Member Typedef Documentation
const_iterator
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> using llvm::SetVector< T, Vector, Set >::const_iterator = typename vector_type::const_iterator
Definition at line 49 of file SetVector.h.
const_reference
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> using llvm::SetVector< T, Vector, Set >::const_reference = const T&
Definition at line 45 of file SetVector.h.
const_reverse_iterator
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> using llvm::SetVector< T, Vector, Set >::const_reverse_iterator = typename vector_type::const_reverse_iterator
Definition at line 51 of file SetVector.h.
iterator
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> using llvm::SetVector< T, Vector, Set >::iterator = typename vector_type::const_iterator
Definition at line 48 of file SetVector.h.
key_type
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> using llvm::SetVector< T, Vector, Set >::key_type = T
Definition at line 43 of file SetVector.h.
reference
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> using llvm::SetVector< T, Vector, Set >::reference = T&
Definition at line 44 of file SetVector.h.
reverse_iterator
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> using llvm::SetVector< T, Vector, Set >::reverse_iterator = typename vector_type::const_reverse_iterator
Definition at line 50 of file SetVector.h.
set_type
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> using llvm::SetVector< T, Vector, Set >::set_type = Set
Definition at line 46 of file SetVector.h.
size_type
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> using llvm::SetVector< T, Vector, Set >::size_type = typename vector_type::size_type
Definition at line 52 of file SetVector.h.
value_type
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> using llvm::SetVector< T, Vector, Set >::value_type = T
Definition at line 42 of file SetVector.h.
vector_type
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> using llvm::SetVector< T, Vector, Set >::vector_type = Vector
Definition at line 47 of file SetVector.h.
Constructor & Destructor Documentation
SetVector() [1/2]
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> llvm::SetVector< T, Vector, Set >::SetVector () default
Construct an empty SetVector.
SetVector() [2/2]
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> template<typename It > llvm::SetVector< T, Vector, Set >::SetVector (It Start, It End) inline
Initialize a SetVector with a range of elements.
Definition at line 59 of file SetVector.h.
Member Function Documentation
back()
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> const T& llvm::SetVector< T, Vector, Set >::back () const inline
Return the last element of the SetVector.
Definition at line 128 of file SetVector.h.
References assert(), llvm::SetVector< T, Vector, Set >::empty(), and T.
Referenced by llvm::DGNode< NodeType, EdgeType >::back(), createGuardBlocks(), llvm::LiveRangeEdit::eliminateDeadDefs(), llvm::SetVector< T, Vector, Set >::pop_back(), llvm::SetVector< T, Vector, Set >::pop_back_val(), llvm::AttributorCGSCCPass::run(), and llvm::OpenMPOptPass::run().
begin() [1/2]
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> iterator llvm::SetVector< T, Vector, Set >::begin () inline
Get an iterator to the beginning of the SetVector.
Definition at line 82 of file SetVector.h.
Referenced by AssignProtectedObjSet(), llvm::NodeSet::begin(), llvm::DGNode< NodeType, EdgeType >::begin(), llvm::rdf::Liveness::computeLiveIns(), llvm::SetTheory::expand(), findLiveSetAtInst(), llvm::formLCSSAForInstructions(), llvm::InformationCache::initializeModuleSlice(), llvm::promoteLoopAccessesToScalars(), llvm::MemorySSAUpdater::removeMemoryAccess(), sinkSpillUsesAfterCoroBegin(), splitPredecessorsOfLoopExit(), and unswitchNontrivialInvariants().
begin() [2/2]
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> const_iterator llvm::SetVector< T, Vector, Set >::begin () const inline
Get a const_iterator to the beginning of the SetVector.
Definition at line 87 of file SetVector.h.
clear()
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> void llvm::SetVector< T, Vector, Set >::clear () inline
Completely clear the SetVector.
Definition at line 220 of file SetVector.h.
Referenced by analyzeLoopUnrollCost(), llvm::DGNode< NodeType, EdgeType >::clear(), llvm::NodeSet::clear(), pred_L(), llvm::MemorySSAUpdater::removeMemoryAccess(), and succ_L().
contains()
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> bool llvm::SetVector< T, Vector, Set >::contains (const key_type & key) const inline
Check if the SetVector contains the given key.
Definition at line 209 of file SetVector.h.
Referenced by computePath(), and runImpl().
count()
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> size_type llvm::SetVector< T, Vector, Set >::count (const key_type & key) const inline
Count the number of elements of a given key in the SetVector.
Returns
0 if the element is not in the SetVector, 1 if it is.
Definition at line 215 of file SetVector.h.
Referenced by addMappingsFromTLI(), buildClonedLoops(), llvm::NodeSet::count(), createNaturalLoopInternal(), definedInCaller(), definedInRegion(), deleteDeadBlocksFromLoop(), eliminateDeadCode(), findExtractedInputToOverallInputMapping(), llvm::CodeExtractor::findInputsOutputs(), getCommonExitBlock(), getLeastCommonType(), llvm::VPlan::hasVF(), insertTrivialPHIs(), makeReducible(), llvm::NodeSet::NodeSet(), redirectToHub(), llvm::MemorySSAUpdater::removeBlocks(), shouldEmitDWARF(), llvm::SimplifyInstructionsInBlock(), and unswitchNontrivialInvariants().
empty()
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> bool llvm::SetVector< T, Vector, Set >::empty () const inline
Determine if the SetVector is empty or not.
Definition at line 72 of file SetVector.h.
Referenced by analyzeLoopUnrollCost(), llvm::SetVector< T, Vector, Set >::back(), computeLiveInValues(), llvm::OpenMPIRBuilder::createParallel(), llvm::LLVMContextImpl::dropTriviallyDeadConstantArrays(), eliminateDeadCode(), llvm::LiveRangeEdit::eliminateDeadDefs(), llvm::NodeSet::empty(), llvm::rdf::DeadCodeElimination::erase(), llvm::SetVector< T, Vector, Set >::front(), llvm::MDNode::getMostGenericAliasScope(), interpretValues(), llvm::InstCombineWorklist::isEmpty(), llvm::SIInstrInfo::moveToVALU(), llvm::SetVector< T, Vector, Set >::pop_back(), llvm::InstCombineWorklist::popDeferred(), pred_L(), llvm::MemorySSAUpdater::removeMemoryAccess(), llvm::removeUnreachableBlocks(), llvm::AttributorCGSCCPass::run(), runAttributorOnFunctions(), llvm::SimplifyInstructionsInBlock(), llvm::InnerLoopVectorizer::sinkScalarOperands(), llvm::SplitIndirectBrCriticalEdges(), splitPredecessorsOfLoopExit(), succ_L(), and llvm::InstCombineWorklist::zap().
end() [1/2]
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> iterator llvm::SetVector< T, Vector, Set >::end () inline
Get an iterator to the end of the SetVector.
Definition at line 92 of file SetVector.h.
Referenced by AssignProtectedObjSet(), llvm::rdf::Liveness::computeLiveIns(), llvm::NodeSet::end(), llvm::DGNode< NodeType, EdgeType >::end(), llvm::SetTheory::expand(), findLiveSetAtInst(), llvm::formLCSSAForInstructions(), llvm::DGNode< NodeType, EdgeType >::hasEdgeTo(), llvm::InformationCache::initializeModuleSlice(), llvm::MemorySSAUpdater::removeMemoryAccess(), and sinkSpillUsesAfterCoroBegin().
end() [2/2]
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> const_iterator llvm::SetVector< T, Vector, Set >::end () const inline
Get a const_iterator to the end of the SetVector.
Definition at line 97 of file SetVector.h.
erase()
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> iterator llvm::SetVector< T, Vector, Set >::erase (iterator I) inline
Erase a single element from the set vector.
Returns
an iterator pointing to the next element that followed the element erased. This is the end of the SetVector if the last element is erased.
Definition at line 171 of file SetVector.h.
References assert(), and I.
front()
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> const T& llvm::SetVector< T, Vector, Set >::front () const inline
Return the first element of the SetVector.
Definition at line 122 of file SetVector.h.
References assert(), llvm::SetVector< T, Vector, Set >::empty(), and T.
Referenced by convertToGuardPredicates(), llvm::DGNode< NodeType, EdgeType >::front(), and makeReducible().
getArrayRef()
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> ArrayRef<T> llvm::SetVector< T, Vector, Set >::getArrayRef () const inline
Definition at line 63 of file SetVector.h.
Referenced by llvm::MDNode::concatenate(), getCodeExtractorArguments(), llvm::MDNode::getMostGenericAliasScope(), and llvm::MDNode::intersect().
insert() [1/2]
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> bool llvm::SetVector< T, Vector, Set >::insert (const value_type & X) inline
Insert a new element into the SetVector.
Returns
true if the element was inserted into the SetVector.
Definition at line 141 of file SetVector.h.
References X.
Referenced by llvm::InstCombineWorklist::add(), llvm::DGNode< NodeType, EdgeType >::addEdge(), llvm::MCContext::addGenDwarfSection(), addIntrinsicToSummary(), addVCallToSet(), llvm::VPlan::addVF(), llvm::InterleavedAccessInfo::analyzeInterleaving(), analyzeLoopUnrollCost(), buildClonedLoops(), llvm::changeToUnreachable(), llvm::CloneAndPruneIntoFromInst(), computeBlocksDominatingExits(), computeFunctionSummary(), computeKillSet(), llvm::rdf::Liveness::computeLiveIns(), computeLiveInValues(), computeLiveOutSeed(), computePath(), llvm::rdf::Liveness::computePhiInfo(), llvm::MDNode::concatenate(), llvm::ConstantFoldTerminator(), createNaturalLoopInternal(), DCEInstruction(), deleteDeadBlocksFromLoop(), llvm::HexagonFrameLowering::determineCalleeSaves(), DFS(), llvm::DGNode< NodeType, EdgeType >::DGNode(), llvm::LLVMContextImpl::dropTriviallyDeadConstantArrays(), llvm::HexagonEvaluator::evaluate(), llvm::SetTheory::evaluate(), llvm::CodeExtractor::findAllocas(), llvm::CodeExtractor::findInputsOutputs(), findRefEdges(), llvm::formLCSSAForInstructions(), getLeastCommonType(), llvm::MDNode::getMostGenericAliasScope(), llvm::DWARFYAML::Data::getNonEmptySectionNames(), llvm::NodeSet::insert(), insertIfNamed(), insertTrivialPHIs(), isFunctionMallocLike(), llvm::LiveRangeCalc::isJointlyDominated(), isReturnNonNull(), lowerStatepointMetaArgs(), makeReducible(), llvm::SIInstrInfo::moveToVALU(), pred_L(), remapExtractedInputs(), llvm::MemorySSAUpdater::removeMemoryAccess(), llvm::removeUnreachableBlocks(), replaceAndRecursivelySimplifyImpl(), llvm::AttributorCGSCCPass::run(), llvm::AttributorPass::run(), runAttributorOnFunctions(), llvm::runIPSCCP(), llvm::SetVector< T, Vector, Set >::set_union(), simplifyAndDCEInstruction(), llvm::InnerLoopVectorizer::sinkScalarOperands(), sinkSpillUsesAfterCoroBegin(), llvm::SplitIndirectBrCriticalEdges(), succ_L(), SwitchToLookupTable(), tryToSpeculatePHIs(), unifyLoopExits(), llvm::UnrollLoop(), unswitchNontrivialInvariants(), and llvm::slpvectorizer::BoUpSLP::vectorizeTree().
insert() [2/2]
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> template<typename It > void llvm::SetVector< T, Vector, Set >::insert (It Start, It End) inline
Insert a range of elements into the SetVector.
Definition at line 150 of file SetVector.h.
operator!=()
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> bool llvm::SetVector< T, Vector, Set >::operator!= (const SetVector< T, Vector, Set > & that) const inline
Definition at line 242 of file SetVector.h.
operator==()
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> bool llvm::SetVector< T, Vector, Set >::operator== (const SetVector< T, Vector, Set > & that) const inline
Definition at line 238 of file SetVector.h.
operator[]()
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> const_reference llvm::SetVector< T, Vector, Set >::operator[] (size_type n) const inline
Index into the SetVector.
Definition at line 134 of file SetVector.h.
References assert().
pop_back()
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> void llvm::SetVector< T, Vector, Set >::pop_back () inline
Remove the last element of the SetVector.
Definition at line 226 of file SetVector.h.
References assert(), llvm::SetVector< T, Vector, Set >::back(), and llvm::SetVector< T, Vector, Set >::empty().
Referenced by llvm::LiveRangeEdit::eliminateDeadDefs(), and llvm::SetVector< T, Vector, Set >::pop_back_val().
pop_back_val()
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> LLVM_NODISCARD T llvm::SetVector< T, Vector, Set >::pop_back_val () inline
Definition at line 232 of file SetVector.h.
References llvm::SetVector< T, Vector, Set >::back(), llvm::SetVector< T, Vector, Set >::pop_back(), llvm::MipsISD::Ret, and T.
Referenced by analyzeLoopUnrollCost(), computeLiveInValues(), llvm::LLVMContextImpl::dropTriviallyDeadConstantArrays(), eliminateDeadCode(), llvm::SIInstrInfo::moveToVALU(), llvm::InstCombineWorklist::popDeferred(), llvm::SimplifyInstructionsInBlock(), and llvm::InnerLoopVectorizer::sinkScalarOperands().
rbegin() [1/2]
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> reverse_iterator llvm::SetVector< T, Vector, Set >::rbegin () inline
Get an reverse_iterator to the end of the SetVector.
Definition at line 102 of file SetVector.h.
Referenced by containsNewBackedge().
rbegin() [2/2]
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> const_reverse_iterator llvm::SetVector< T, Vector, Set >::rbegin () const inline
Get a const_reverse_iterator to the end of the SetVector.
Definition at line 107 of file SetVector.h.
remove()
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> bool llvm::SetVector< T, Vector, Set >::remove (const value_type & X) inline
Remove an item from the set vector.
Definition at line 157 of file SetVector.h.
References assert(), llvm::find(), I, and X.
Referenced by llvm::InterleavedAccessInfo::analyzeInterleaving(), computeFunctionSummary(), findLiveSetAtInst(), llvm::InstCombineWorklist::remove(), removeAccessedObjects(), llvm::DGNode< NodeType, EdgeType >::removeEdge(), llvm::SetVector< T, Vector, Set >::set_subtract(), and splitPredecessorsOfLoopExit().
remove_if()
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> template<typename UnaryPredicate > bool llvm::SetVector< T, Vector, Set >::remove_if (UnaryPredicate P) inline
Remove items from the set vector based on a predicate function.
This is intended to be equivalent to the following code, if we could write it:
V.erase(remove_if(V, P), V.end());
However, SetVector doesn't expose non-const iterators, making any algorithm like remove_if impossible to use.
Returns
true if any element is removed.
Definition at line 199 of file SetVector.h.
References I, P, and llvm::remove_if().
Referenced by llvm::MDNode::intersect(), llvm::NodeSet::remove_if(), and removeAccessedObjects().
rend() [1/2]
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> reverse_iterator llvm::SetVector< T, Vector, Set >::rend () inline
Get a reverse_iterator to the beginning of the SetVector.
Definition at line 112 of file SetVector.h.
Referenced by containsNewBackedge().
rend() [2/2]
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> const_reverse_iterator llvm::SetVector< T, Vector, Set >::rend () const inline
Get a const_reverse_iterator to the beginning of the SetVector.
Definition at line 117 of file SetVector.h.
set_subtract()
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> template<class STy > void llvm::SetVector< T, Vector, Set >::set_subtract (const STy & S) inline
Compute This := This - B TODO: We should be able to use set_subtract from SetOperations.h, but SetVector interface is inconsistent with DenseSet.
Definition at line 265 of file SetVector.h.
References llvm::SetVector< T, Vector, Set >::remove(), and SI.
Referenced by computeLiveInValues().
set_union()
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> template<class STy > bool llvm::SetVector< T, Vector, Set >::set_union (const STy & S) inline
Compute This := This u S, return whether 'This' changed.
TODO: We should be able to use set_union from SetOperations.h, but SetVector interface is inconsistent with DenseSet.
Definition at line 250 of file SetVector.h.
References llvm::SetVector< T, Vector, Set >::insert(), and SI.
Referenced by computeLiveInValues().
size()
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> size_type llvm::SetVector< T, Vector, Set >::size () const inline
Determine the number of elements in the SetVector.
Definition at line 77 of file SetVector.h.
Referenced by analyzeLoopUnrollCost(), llvm::changeToUnreachable(), llvm::CloneAndPruneIntoFromInst(), computeFunctionSummary(), llvm::rdf::Liveness::computeLiveIns(), computeLiveInValues(), llvm::rdf::Liveness::computePhiInfo(), llvm::ConstantFoldTerminator(), convertToGuardPredicates(), createGuardBlocks(), getCodeExtractorArguments(), getLeastCommonType(), isFunctionMallocLike(), isIntersect(), llvm::LiveRangeCalc::isJointlyDominated(), isReturnNonNull(), lowerStatepointMetaArgs(), makeReducible(), llvm::MergeBlockIntoPredecessor(), llvm::NodeSet::NodeSet(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), reconnectPhis(), llvm::removeUnreachableBlocks(), replaceAndRecursivelySimplifyImpl(), runAttributorOnFunctions(), llvm::NodeSet::size(), speculatePHIs(), SplitBlockAndInsertIfThenImpl(), llvm::splitBlockBefore(), SplitBlockImpl(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), tryToSpeculatePHIs(), unifyLoopExits(), unswitchNontrivialInvariants(), and UpdateAnalysisInformation().
swap()
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> void llvm::SetVector< T, Vector, Set >::swap (SetVector< T, Vector, Set > & RHS) inline
Definition at line 271 of file SetVector.h.
Referenced by std::swap().
takeVector()
template<typename T , typename Vector = std::vector<T>, typename Set = DenseSet<T>> Vector llvm::SetVector< T, Vector, Set >::takeVector () inline
Clear the SetVector and return the underlying vector.
Definition at line 66 of file SetVector.h.
References llvm::move(), and llvm::Vector.
Referenced by computeFunctionSummary(), computeVariableSummary(), and lowerStatepointMetaArgs().
The documentation for this class was generated from the following file:
include/llvm/ADT/SetVector.h