LLVM: llvm::PPCMCCodeEmitter Class Reference
llvm::PPCMCCodeEmitter Class Reference
#include "Target/PowerPC/MCTargetDesc/PPCMCCodeEmitter.h"
Public Member Functions
PPCMCCodeEmitter (const MCInstrInfo &mcii, MCContext &ctx)
PPCMCCodeEmitter (const PPCMCCodeEmitter &)=delete
void operator= (const PPCMCCodeEmitter &)=delete
~PPCMCCodeEmitter () override=default
unsigned getDirectBrEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getCondBrEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getAbsDirectBrEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getAbsCondBrEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getImm16Encoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
uint64_t getImm34Encoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI, MCFixupKind Fixup) const
uint64_t getImm34EncodingNoPCRel (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
uint64_t getImm34EncodingPCRel (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getMemRIEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getMemRIXEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getMemRIX16Encoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
uint64_t getMemRI34PCRelEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
uint64_t getMemRI34Encoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getSPE8DisEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getSPE4DisEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getSPE2DisEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getTLSRegEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getTLSCallEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned get_crbitm_encoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getVSRpEvenEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
uint64_t getMachineOpValue (const MCInst &MI, const MCOperand &MO, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
getMachineOpValue - Return binary encoding of operand.
uint64_t getBinaryCodeForInstr (const MCInst &MI, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
void encodeInstruction (const MCInst &MI, raw_ostream &OS, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const override
EncodeInstruction - Encode the given Inst to bytes on the output stream OS.
unsigned getInstSizeInBytes (const MCInst &MI) const
bool isPrefixedInstruction (const MCInst &MI) const
Public Member Functions inherited from llvm::MCCodeEmitter
MCCodeEmitter (const MCCodeEmitter &)=delete
MCCodeEmitter & operator= (const MCCodeEmitter &)=delete
virtual ~MCCodeEmitter ()
virtual void reset ()
Lifetime management.
virtual void emitPrefix (const MCInst &Inst, raw_ostream &OS, const MCSubtargetInfo &STI) const
Emit the prefixes of given instruction on the output stream.
Additional Inherited Members
Protected Member Functions inherited from llvm::MCCodeEmitter
MCCodeEmitter ()
Detailed Description
Definition at line 25 of file PPCMCCodeEmitter.h.
Constructor & Destructor Documentation
PPCMCCodeEmitter() [1/2]
llvm::PPCMCCodeEmitter::PPCMCCodeEmitter (const MCInstrInfo & mcii, MCContext & ctx) inline
Definition at line 31 of file PPCMCCodeEmitter.h.
PPCMCCodeEmitter() [2/2]
llvm::PPCMCCodeEmitter::PPCMCCodeEmitter (const PPCMCCodeEmitter &) delete
~PPCMCCodeEmitter()
llvm::PPCMCCodeEmitter::~PPCMCCodeEmitter () override default
Member Function Documentation
encodeInstruction()
void PPCMCCodeEmitter::encodeInstruction (const MCInst & Inst, raw_ostream & OS, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const override virtual
EncodeInstruction - Encode the given Inst to bytes on the output stream OS.
Implements llvm::MCCodeEmitter.
Definition at line 433 of file PPCMCCodeEmitter.cpp.
References llvm::support::big, llvm::tgtok::Bits, E, getBinaryCodeForInstr(), llvm::MCSubtargetInfo::getFeatureBits(), getInstSizeInBytes(), llvm::support::little, llvm_unreachable, MI, and llvm::Check::Size.
get_crbitm_encoding()
unsigned PPCMCCodeEmitter::get_crbitm_encoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 386 of file PPCMCCodeEmitter.cpp.
References assert(), llvm::MCRegisterInfo::getEncodingValue(), llvm::MCOperand::getReg(), llvm::MCContext::getRegisterInfo(), llvm::PPCISD::MFOCRF, and MI.
getAbsCondBrEncoding()
unsigned PPCMCCodeEmitter::getAbsCondBrEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 84 of file PPCMCCodeEmitter.cpp.
References llvm::MCFixup::create(), llvm::PPC::fixup_ppc_brcond14abs, llvm::MCOperand::getExpr(), getMachineOpValue(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and MI.
getAbsDirectBrEncoding()
unsigned PPCMCCodeEmitter::getAbsDirectBrEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 71 of file PPCMCCodeEmitter.cpp.
References llvm::MCFixup::create(), llvm::PPC::fixup_ppc_br24abs, llvm::MCOperand::getExpr(), getMachineOpValue(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and MI.
getBinaryCodeForInstr()
uint64_t llvm::PPCMCCodeEmitter::getBinaryCodeForInstr (const MCInst & MI, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Referenced by encodeInstruction().
getCondBrEncoding()
unsigned PPCMCCodeEmitter::getCondBrEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 59 of file PPCMCCodeEmitter.cpp.
References llvm::MCFixup::create(), llvm::PPC::fixup_ppc_brcond14, llvm::MCOperand::getExpr(), getMachineOpValue(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and MI.
getDirectBrEncoding()
unsigned PPCMCCodeEmitter::getDirectBrEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 42 of file PPCMCCodeEmitter.cpp.
References llvm::MCFixup::create(), llvm::PPC::fixup_ppc_br24, llvm::PPC::fixup_ppc_br24_notoc, llvm::MCOperand::getExpr(), getMachineOpValue(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and MI.
Referenced by getTLSCallEncoding().
getImm16Encoding()
unsigned PPCMCCodeEmitter::getImm16Encoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 107 of file PPCMCCodeEmitter.cpp.
References llvm::MCFixup::create(), llvm::PPC::fixup_ppc_half16, llvm::MCOperand::getExpr(), getMachineOpValue(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and MI.
getImm34Encoding()
uint64_t PPCMCCodeEmitter::getImm34Encoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI, MCFixupKind Fixup) const
Definition at line 119 of file PPCMCCodeEmitter.cpp.
References assert(), llvm::MCFixup::create(), Fixup, llvm::MCOperand::getExpr(), getMachineOpValue(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and MI.
Referenced by getImm34EncodingNoPCRel(), and getImm34EncodingPCRel().
getImm34EncodingNoPCRel()
uint64_t PPCMCCodeEmitter::getImm34EncodingNoPCRel (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 134 of file PPCMCCodeEmitter.cpp.
References llvm::PPC::fixup_ppc_imm34, getImm34Encoding(), and MI.
getImm34EncodingPCRel()
uint64_t PPCMCCodeEmitter::getImm34EncodingPCRel (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 142 of file PPCMCCodeEmitter.cpp.
References llvm::PPC::fixup_ppc_pcrel34, getImm34Encoding(), and MI.
getInstSizeInBytes()
unsigned PPCMCCodeEmitter::getInstSizeInBytes (const MCInst & MI) const
Definition at line 464 of file PPCMCCodeEmitter.cpp.
References llvm::MCInstrInfo::get(), llvm::MCInstrDesc::getSize(), and MI.
Referenced by encodeInstruction().
getMachineOpValue()
uint64_t PPCMCCodeEmitter::getMachineOpValue (const MCInst & MI, const MCOperand & MO, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
getMachineOpValue - Return binary encoding of operand.
If the machine operand requires relocation, record the relocation and return zero.
Definition at line 411 of file PPCMCCodeEmitter.cpp.
References assert(), llvm::MCInstrInfo::get(), llvm::MCRegisterInfo::getEncodingValue(), llvm::MCOperand::getImm(), getOpIdxForMO(), llvm::MCOperand::getReg(), llvm::MCContext::getRegisterInfo(), llvm::PPCInstrInfo::getRegNumForOperand(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm::PPCISD::MFOCRF, MI, and Reg.
Referenced by getAbsCondBrEncoding(), getAbsDirectBrEncoding(), getCondBrEncoding(), getDirectBrEncoding(), getImm16Encoding(), getImm34Encoding(), getMemRI34Encoding(), getMemRI34PCRelEncoding(), getMemRIEncoding(), getMemRIX16Encoding(), getMemRIXEncoding(), getSPE2DisEncoding(), getSPE4DisEncoding(), getSPE8DisEncoding(), getTLSRegEncoding(), and getVSRpEvenEncoding().
getMemRI34Encoding()
uint64_t PPCMCCodeEmitter::getMemRI34Encoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 297 of file PPCMCCodeEmitter.cpp.
References assert(), getMachineOpValue(), and MI.
getMemRI34PCRelEncoding()
uint64_t PPCMCCodeEmitter::getMemRI34PCRelEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 207 of file PPCMCCodeEmitter.cpp.
References llvm::MCBinaryExpr::Add, assert(), llvm::MCExpr::Binary, llvm::MCExpr::Constant, llvm::MCFixup::create(), llvm::PPC::fixup_ppc_pcrel34, llvm::MCOperand::getExpr(), llvm::MCExpr::getKind(), llvm::MCSymbolRefExpr::getKind(), llvm::MCBinaryExpr::getLHS(), getMachineOpValue(), llvm::MCBinaryExpr::getOpcode(), llvm::MCBinaryExpr::getRHS(), llvm::MCOperand::isExpr(), llvm_unreachable, MI, std::swap(), llvm::MCExpr::SymbolRef, llvm::MCSymbolRefExpr::VK_PCREL, llvm::MCSymbolRefExpr::VK_PPC_GOT_PCREL, llvm::MCSymbolRefExpr::VK_PPC_GOT_TLSGD_PCREL, llvm::MCSymbolRefExpr::VK_PPC_GOT_TLSLD_PCREL, and llvm::MCSymbolRefExpr::VK_PPC_GOT_TPREL_PCREL.
getMemRIEncoding()
unsigned PPCMCCodeEmitter::getMemRIEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 149 of file PPCMCCodeEmitter.cpp.
References assert(), llvm::MCFixup::create(), llvm::PPC::fixup_ppc_half16, llvm::MCOperand::getExpr(), getMachineOpValue(), llvm::MCOperand::isImm(), and MI.
getMemRIX16Encoding()
unsigned PPCMCCodeEmitter::getMemRIX16Encoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 185 of file PPCMCCodeEmitter.cpp.
References assert(), llvm::MCFixup::create(), llvm::PPC::fixup_ppc_half16ds, llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), getMachineOpValue(), llvm::MCOperand::isImm(), and MI.
getMemRIXEncoding()
unsigned PPCMCCodeEmitter::getMemRIXEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 167 of file PPCMCCodeEmitter.cpp.
References assert(), llvm::MCFixup::create(), llvm::PPC::fixup_ppc_half16ds, llvm::MCOperand::getExpr(), getMachineOpValue(), llvm::MCOperand::isImm(), and MI.
getSPE2DisEncoding()
unsigned PPCMCCodeEmitter::getSPE2DisEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 339 of file PPCMCCodeEmitter.cpp.
References assert(), getMachineOpValue(), llvm::MCOperand::isImm(), MI, and llvm::reverseBits().
getSPE4DisEncoding()
unsigned PPCMCCodeEmitter::getSPE4DisEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 324 of file PPCMCCodeEmitter.cpp.
References assert(), getMachineOpValue(), llvm::MCOperand::isImm(), MI, and llvm::reverseBits().
getSPE8DisEncoding()
unsigned PPCMCCodeEmitter::getSPE8DisEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 309 of file PPCMCCodeEmitter.cpp.
References assert(), getMachineOpValue(), llvm::MCOperand::isImm(), MI, and llvm::reverseBits().
getTLSCallEncoding()
unsigned PPCMCCodeEmitter::getTLSCallEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 374 of file PPCMCCodeEmitter.cpp.
References llvm::MCFixup::create(), llvm::PPC::fixup_ppc_nofixup, getDirectBrEncoding(), llvm::MCOperand::getExpr(), and MI.
getTLSRegEncoding()
unsigned PPCMCCodeEmitter::getTLSRegEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 354 of file PPCMCCodeEmitter.cpp.
References llvm::MCFixup::create(), llvm::PPC::fixup_ppc_nofixup, llvm::MCRegisterInfo::getEncodingValue(), llvm::MCOperand::getExpr(), llvm::MCSymbolRefExpr::getKind(), getMachineOpValue(), llvm::MCContext::getRegisterInfo(), llvm::MCSubtargetInfo::getTargetTriple(), llvm::MCOperand::isReg(), MI, R2, and llvm::MCSymbolRefExpr::VK_PPC_TLS_PCREL.
getVSRpEvenEncoding()
unsigned PPCMCCodeEmitter::getVSRpEvenEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 98 of file PPCMCCodeEmitter.cpp.
References assert(), getMachineOpValue(), and MI.
isPrefixedInstruction()
bool PPCMCCodeEmitter::isPrefixedInstruction (const MCInst & MI) const
Definition at line 470 of file PPCMCCodeEmitter.cpp.
References llvm::PPCInstrInfo::isPrefixed(), and MI.
Referenced by llvm::PPCELFStreamer::emitInstruction().
operator=()
void llvm::PPCMCCodeEmitter::operator= (const PPCMCCodeEmitter &) delete
The documentation for this class was generated from the following files:
lib/Target/PowerPC/MCTargetDesc/PPCMCCodeEmitter.h
lib/Target/PowerPC/MCTargetDesc/PPCMCCodeEmitter.cpp