LLVM: llvm::BasicTTIImplBase< T > Class Template Reference
llvm::BasicTTIImplBase< T > Class Template Reference
Base class which can be used to help build a TTI implementation.
#include "llvm/CodeGen/BasicTTIImpl.h"
Public Member Functions
Scalar TTI Implementations
bool allowsMisalignedMemoryAccesses (LLVMContext &Context, unsigned BitWidth, unsigned AddressSpace, unsigned Alignment, bool *Fast) const
bool hasBranchDivergence ()
bool useGPUDivergenceAnalysis ()
bool isSourceOfDivergence (const Value *V)
bool isAlwaysUniform (const Value *V)
unsigned getFlatAddressSpace ()
bool collectFlatAddressOperands (SmallVectorImpl< int > &OpIndexes, Intrinsic::ID IID) const
bool isNoopAddrSpaceCast (unsigned FromAS, unsigned ToAS) const
unsigned getAssumedAddrSpace (const Value *V) const
Value * rewriteIntrinsicWithAddressSpace (IntrinsicInst *II, Value *OldV, Value *NewV) const
bool isLegalAddImmediate (int64_t imm)
bool isLegalICmpImmediate (int64_t imm)
bool isLegalAddressingMode (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction *I=nullptr)
bool isIndexedLoadLegal (TTI::MemIndexedMode M, Type *Ty, const DataLayout &DL) const
bool isIndexedStoreLegal (TTI::MemIndexedMode M, Type *Ty, const DataLayout &DL) const
bool isLSRCostLess (TTI::LSRCost C1, TTI::LSRCost C2)
bool isNumRegsMajorCostOfLSR ()
bool isProfitableLSRChainElement (Instruction *I)
int getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace)
bool isTruncateFree (Type *Ty1, Type *Ty2)
bool isProfitableToHoist (Instruction *I)
bool useAA () const
bool isTypeLegal (Type *Ty)
unsigned getRegUsageForType (Type *Ty)
int getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands)
unsigned getEstimatedNumberOfCaseClusters (const SwitchInst &SI, unsigned &JumpTableSize, ProfileSummaryInfo *PSI, BlockFrequencyInfo *BFI)
bool shouldBuildLookupTables ()
bool haveFastSqrt (Type *Ty)
bool isFCmpOrdCheaperThanFCmpZero (Type *Ty)
unsigned getFPOpCost (Type *Ty)
unsigned getInliningThresholdMultiplier ()
unsigned adjustInliningThreshold (const CallBase *CB)
int getInlinerVectorBonusPercent ()
void getUnrollingPreferences (Loop *L, ScalarEvolution &SE, TTI::UnrollingPreferences &UP)
void getPeelingPreferences (Loop *L, ScalarEvolution &SE, TTI::PeelingPreferences &PP)
bool isHardwareLoopProfitable (Loop *L, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *LibInfo, HardwareLoopInfo &HWLoopInfo)
bool preferPredicateOverEpilogue (Loop *L, LoopInfo *LI, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *TLI, DominatorTree *DT, const LoopAccessInfo *LAI)
bool emitGetActiveLaneMask ()
Optional< Instruction * > instCombineIntrinsic (InstCombiner &IC, IntrinsicInst &II)
Optional< Value * > simplifyDemandedUseBitsIntrinsic (InstCombiner &IC, IntrinsicInst &II, APInt DemandedMask, KnownBits &Known, bool &KnownBitsComputed)
Optional< Value * > simplifyDemandedVectorEltsIntrinsic (InstCombiner &IC, IntrinsicInst &II, APInt DemandedElts, APInt &UndefElts, APInt &UndefElts2, APInt &UndefElts3, std::function< void(Instruction *, unsigned, APInt, APInt &)> SimplifyAndSetOp)
int getInstructionLatency (const Instruction *I)
virtual Optional< unsigned > getCacheSize (TargetTransformInfo::CacheLevel Level) const
virtual Optional< unsigned > getCacheAssociativity (TargetTransformInfo::CacheLevel Level) const
virtual unsigned getCacheLineSize () const
virtual unsigned getPrefetchDistance () const
virtual unsigned getMinPrefetchStride (unsigned NumMemAccesses, unsigned NumStridedMemAccesses, unsigned NumPrefetches, bool HasCall) const
virtual unsigned getMaxPrefetchIterationsAhead () const
virtual bool enableWritePrefetching () const
Vector TTI Implementations
unsigned getRegisterBitWidth (bool Vector) const
Optional< unsigned > getMaxVScale () const
unsigned getScalarizationOverhead (VectorType *InTy, const APInt &DemandedElts, bool Insert, bool Extract)
Estimate the overhead of scalarizing an instruction.
unsigned getScalarizationOverhead (VectorType *InTy, bool Insert, bool Extract)
Helper wrapper for the DemandedElts variant of getScalarizationOverhead.
unsigned getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, unsigned VF)
Estimate the overhead of scalarizing an instruction's unique non-constant operands.
unsigned getScalarizationOverhead (VectorType *InTy, ArrayRef< const Value * > Args)
unsigned getMaxInterleaveFactor (unsigned VF)
unsigned getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::TargetCostKind CostKind=TTI::TCK_RecipThroughput, TTI::OperandValueKind Opd1Info=TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info=TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo=TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo=TTI::OP_None, ArrayRef< const Value * > Args=ArrayRef< const Value * >(), const Instruction *CxtI=nullptr)
unsigned getShuffleCost (TTI::ShuffleKind Kind, VectorType *Tp, int Index, VectorType *SubTp)
unsigned getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, TTI::CastContextHint CCH, TTI::TargetCostKind CostKind, const Instruction *I=nullptr)
unsigned getExtractWithExtendCost (unsigned Opcode, Type *Dst, VectorType *VecTy, unsigned Index)
unsigned getCFInstrCost (unsigned Opcode, TTI::TargetCostKind CostKind)
unsigned getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, CmpInst::Predicate VecPred, TTI::TargetCostKind CostKind, const Instruction *I=nullptr)
unsigned getVectorInstrCost (unsigned Opcode, Type *Val, unsigned Index)
unsigned getMemoryOpCost (unsigned Opcode, Type *Src, MaybeAlign Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, const Instruction *I=nullptr)
unsigned getGatherScatterOpCost (unsigned Opcode, Type *DataTy, const Value *Ptr, bool VariableMask, Align Alignment, TTI::TargetCostKind CostKind, const Instruction *I=nullptr)
unsigned getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, bool UseMaskForCond=false, bool UseMaskForGaps=false)
unsigned getIntrinsicInstrCost (const IntrinsicCostAttributes &ICA, TTI::TargetCostKind CostKind)
Get intrinsic cost based on arguments.
unsigned getTypeBasedIntrinsicInstrCost (const IntrinsicCostAttributes &ICA, TTI::TargetCostKind CostKind)
Get intrinsic cost based on argument types.
unsigned getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind=TTI::TCK_SizeAndLatency)
Compute a cost of the given call instruction.
unsigned getNumberOfParts (Type *Tp)
unsigned getAddressComputationCost (Type *Ty, ScalarEvolution *, const SCEV *)
unsigned getArithmeticReductionCost (unsigned Opcode, VectorType *Ty, bool IsPairwise, TTI::TargetCostKind CostKind)
Try to calculate arithmetic and shuffle op costs for reduction operations.
unsigned getMinMaxReductionCost (VectorType *Ty, VectorType *CondTy, bool IsPairwise, bool IsUnsigned, TTI::TargetCostKind CostKind)
Try to calculate op costs for min/max reduction operations.
InstructionCost getExtendedAddReductionCost (bool IsMLA, bool IsUnsigned, Type *ResTy, VectorType *Ty, TTI::TargetCostKind CostKind)
unsigned getVectorSplitCost ()
Public Member Functions inherited from llvm::TargetTransformInfoImplCRTPBase< T >
int getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands, TTI::TargetCostKind CostKind=TTI::TCK_SizeAndLatency)
int getUserCost (const User *U, ArrayRef< const Value * > Operands, TTI::TargetCostKind CostKind)
int getInstructionLatency (const Instruction *I)
int getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands, TTI::TargetCostKind CostKind=TTI::TCK_SizeAndLatency) const
Public Member Functions inherited from llvm::TargetTransformInfoImplBase
TargetTransformInfoImplBase (const TargetTransformInfoImplBase &Arg)
TargetTransformInfoImplBase (TargetTransformInfoImplBase &&Arg)
const DataLayout & getDataLayout () const
int getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands, TTI::TargetCostKind CostKind=TTI::TCK_SizeAndLatency) const
unsigned getEstimatedNumberOfCaseClusters (const SwitchInst &SI, unsigned &JTSize, ProfileSummaryInfo *PSI, BlockFrequencyInfo *BFI) const
unsigned getInliningThresholdMultiplier () const
unsigned adjustInliningThreshold (const CallBase *CB) const
int getInlinerVectorBonusPercent () const
unsigned getMemcpyCost (const Instruction *I) const
bool hasBranchDivergence () const
bool useGPUDivergenceAnalysis () const
bool isSourceOfDivergence (const Value *V) const
bool isAlwaysUniform (const Value *V) const
unsigned getFlatAddressSpace () const
bool collectFlatAddressOperands (SmallVectorImpl< int > &OpIndexes, Intrinsic::ID IID) const
bool isNoopAddrSpaceCast (unsigned, unsigned) const
unsigned getAssumedAddrSpace (const Value *V) const
Value * rewriteIntrinsicWithAddressSpace (IntrinsicInst *II, Value *OldV, Value *NewV) const
bool isLoweredToCall (const Function *F) const
bool isHardwareLoopProfitable (Loop *L, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *LibInfo, HardwareLoopInfo &HWLoopInfo) const
bool preferPredicateOverEpilogue (Loop *L, LoopInfo *LI, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *TLI, DominatorTree *DT, const LoopAccessInfo *LAI) const
bool emitGetActiveLaneMask () const
Optional< Instruction * > instCombineIntrinsic (InstCombiner &IC, IntrinsicInst &II) const
Optional< Value * > simplifyDemandedUseBitsIntrinsic (InstCombiner &IC, IntrinsicInst &II, APInt DemandedMask, KnownBits &Known, bool &KnownBitsComputed) const
Optional< Value * > simplifyDemandedVectorEltsIntrinsic (InstCombiner &IC, IntrinsicInst &II, APInt DemandedElts, APInt &UndefElts, APInt &UndefElts2, APInt &UndefElts3, std::function< void(Instruction *, unsigned, APInt, APInt &)> SimplifyAndSetOp) const
void getUnrollingPreferences (Loop *, ScalarEvolution &, TTI::UnrollingPreferences &) const
void getPeelingPreferences (Loop *, ScalarEvolution &, TTI::PeelingPreferences &) const
bool isLegalAddImmediate (int64_t Imm) const
bool isLegalICmpImmediate (int64_t Imm) const
bool isLegalAddressingMode (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction *I=nullptr) const
bool isLSRCostLess (TTI::LSRCost &C1, TTI::LSRCost &C2) const
bool isNumRegsMajorCostOfLSR () const
bool isProfitableLSRChainElement (Instruction *I) const
bool canMacroFuseCmp () const
bool canSaveCmp (Loop *L, BranchInst **BI, ScalarEvolution *SE, LoopInfo *LI, DominatorTree *DT, AssumptionCache *AC, TargetLibraryInfo *LibInfo) const
bool shouldFavorPostInc () const
bool shouldFavorBackedgeIndex (const Loop *L) const
bool isLegalMaskedStore (Type *DataType, Align Alignment) const
bool isLegalMaskedLoad (Type *DataType, Align Alignment) const
bool isLegalNTStore (Type *DataType, Align Alignment) const
bool isLegalNTLoad (Type *DataType, Align Alignment) const
bool isLegalMaskedScatter (Type *DataType, Align Alignment) const
bool isLegalMaskedGather (Type *DataType, Align Alignment) const
bool isLegalMaskedCompressStore (Type *DataType) const
bool isLegalMaskedExpandLoad (Type *DataType) const
bool hasDivRemOp (Type *DataType, bool IsSigned) const
bool hasVolatileVariant (Instruction *I, unsigned AddrSpace) const
bool prefersVectorizedAddressing () const
int getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) const
bool LSRWithInstrQueries () const
bool isTruncateFree (Type *Ty1, Type *Ty2) const
bool isProfitableToHoist (Instruction *I) const
bool useAA () const
bool isTypeLegal (Type *Ty) const
unsigned getRegUsageForType (Type *Ty) const
bool shouldBuildLookupTables () const
bool shouldBuildLookupTablesForConstant (Constant *C) const
bool useColdCCForColdCall (Function &F) const
unsigned getScalarizationOverhead (VectorType *Ty, const APInt &DemandedElts, bool Insert, bool Extract) const
unsigned getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, unsigned VF) const
bool supportsEfficientVectorElementLoadStore () const
bool enableAggressiveInterleaving (bool LoopHasReductions) const
TTI::MemCmpExpansionOptions enableMemCmpExpansion (bool OptSize, bool IsZeroCmp) const
bool enableInterleavedAccessVectorization () const
bool enableMaskedInterleavedAccessVectorization () const
bool isFPVectorizationPotentiallyUnsafe () const
bool allowsMisalignedMemoryAccesses (LLVMContext &Context, unsigned BitWidth, unsigned AddressSpace, unsigned Alignment, bool *Fast) const
TTI::PopcntSupportKind getPopcntSupport (unsigned IntTyWidthInBit) const
bool haveFastSqrt (Type *Ty) const
bool isFCmpOrdCheaperThanFCmpZero (Type *Ty) const
unsigned getFPOpCost (Type *Ty) const
int getIntImmCodeSizeCost (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty) const
unsigned getIntImmCost (const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind) const
unsigned getIntImmCostInst (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind, Instruction *Inst=nullptr) const
unsigned getIntImmCostIntrin (Intrinsic::ID IID, unsigned Idx, const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind) const
unsigned getNumberOfRegisters (unsigned ClassID) const
unsigned getRegisterClassForType (bool Vector, Type *Ty=nullptr) const
const char * getRegisterClassName (unsigned ClassID) const
unsigned getRegisterBitWidth (bool Vector) const
unsigned getMinVectorRegisterBitWidth () const
Optional< unsigned > getMaxVScale () const
bool shouldMaximizeVectorBandwidth (bool OptSize) const
unsigned getMinimumVF (unsigned ElemWidth) const
unsigned getMaximumVF (unsigned ElemWidth, unsigned Opcode) const
bool shouldConsiderAddressTypePromotion (const Instruction &I, bool &AllowPromotionWithoutCommonHeader) const
unsigned getCacheLineSize () const
llvm::Optional< unsigned > getCacheSize (TargetTransformInfo::CacheLevel Level) const
llvm::Optional< unsigned > getCacheAssociativity (TargetTransformInfo::CacheLevel Level) const
unsigned getPrefetchDistance () const
unsigned getMinPrefetchStride (unsigned NumMemAccesses, unsigned NumStridedMemAccesses, unsigned NumPrefetches, bool HasCall) const
unsigned getMaxPrefetchIterationsAhead () const
bool enableWritePrefetching () const
unsigned getMaxInterleaveFactor (unsigned VF) const
unsigned getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::TargetCostKind CostKind, TTI::OperandValueKind Opd1Info, TTI::OperandValueKind Opd2Info, TTI::OperandValueProperties Opd1PropInfo, TTI::OperandValueProperties Opd2PropInfo, ArrayRef< const Value * > Args, const Instruction *CxtI=nullptr) const
unsigned getShuffleCost (TTI::ShuffleKind Kind, VectorType *Ty, int Index, VectorType *SubTp) const
unsigned getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, TTI::CastContextHint CCH, TTI::TargetCostKind CostKind, const Instruction *I) const
unsigned getExtractWithExtendCost (unsigned Opcode, Type *Dst, VectorType *VecTy, unsigned Index) const
unsigned getCFInstrCost (unsigned Opcode, TTI::TargetCostKind CostKind) const
unsigned getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, CmpInst::Predicate VecPred, TTI::TargetCostKind CostKind, const Instruction *I) const
unsigned getVectorInstrCost (unsigned Opcode, Type *Val, unsigned Index) const
unsigned getMemoryOpCost (unsigned Opcode, Type *Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, const Instruction *I) const
unsigned getMaskedMemoryOpCost (unsigned Opcode, Type *Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind) const
unsigned getGatherScatterOpCost (unsigned Opcode, Type *DataTy, const Value *Ptr, bool VariableMask, Align Alignment, TTI::TargetCostKind CostKind, const Instruction *I=nullptr) const
unsigned getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, bool UseMaskForCond, bool UseMaskForGaps) const
unsigned getIntrinsicInstrCost (const IntrinsicCostAttributes &ICA, TTI::TargetCostKind CostKind) const
unsigned getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const
unsigned getNumberOfParts (Type *Tp) const
unsigned getAddressComputationCost (Type *Tp, ScalarEvolution *, const SCEV *) const
unsigned getArithmeticReductionCost (unsigned, VectorType *, bool, TTI::TargetCostKind) const
unsigned getMinMaxReductionCost (VectorType *, VectorType *, bool, bool, TTI::TargetCostKind) const
InstructionCost getExtendedAddReductionCost (bool IsMLA, bool IsUnsigned, Type *ResTy, VectorType *Ty, TTI::TargetCostKind CostKind=TTI::TCK_RecipThroughput) const
unsigned getCostOfKeepingLiveOverCall (ArrayRef< Type * > Tys) const
bool getTgtMemIntrinsic (IntrinsicInst *Inst, MemIntrinsicInfo &Info) const
unsigned getAtomicMemIntrinsicMaxElementSize () const
Value * getOrCreateResultFromMemIntrinsic (IntrinsicInst *Inst, Type *ExpectedType) const
Type * getMemcpyLoopLoweringType (LLVMContext &Context, Value *Length, unsigned SrcAddrSpace, unsigned DestAddrSpace, unsigned SrcAlign, unsigned DestAlign) const
void getMemcpyLoopResidualLoweringType (SmallVectorImpl< Type * > &OpsOut, LLVMContext &Context, unsigned RemainingBytes, unsigned SrcAddrSpace, unsigned DestAddrSpace, unsigned SrcAlign, unsigned DestAlign) const
bool areInlineCompatible (const Function *Caller, const Function *Callee) const
bool areFunctionArgsABICompatible (const Function *Caller, const Function *Callee, SmallPtrSetImpl< Argument * > &Args) const
bool isIndexedLoadLegal (TTI::MemIndexedMode Mode, Type *Ty, const DataLayout &DL) const
bool isIndexedStoreLegal (TTI::MemIndexedMode Mode, Type *Ty, const DataLayout &DL) const
unsigned getLoadStoreVecRegBitWidth (unsigned AddrSpace) const
bool isLegalToVectorizeLoad (LoadInst *LI) const
bool isLegalToVectorizeStore (StoreInst *SI) const
bool isLegalToVectorizeLoadChain (unsigned ChainSizeInBytes, Align Alignment, unsigned AddrSpace) const
bool isLegalToVectorizeStoreChain (unsigned ChainSizeInBytes, Align Alignment, unsigned AddrSpace) const
unsigned getLoadVectorFactor (unsigned VF, unsigned LoadSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
unsigned getStoreVectorFactor (unsigned VF, unsigned StoreSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
bool useReductionIntrinsic (unsigned Opcode, Type *Ty, TTI::ReductionFlags Flags) const
bool preferInLoopReduction (unsigned Opcode, Type *Ty, TTI::ReductionFlags Flags) const
bool preferPredicatedReductionSelect (unsigned Opcode, Type *Ty, TTI::ReductionFlags Flags) const
bool shouldExpandReduction (const IntrinsicInst *II) const
unsigned getGISelRematGlobalCost () const
bool supportsScalableVectors () const
bool hasActiveVectorLength () const
Protected Member Functions
BasicTTIImplBase (const TargetMachine *TM, const DataLayout &DL)
virtual ~BasicTTIImplBase ()=default
Protected Member Functions inherited from llvm::TargetTransformInfoImplCRTPBase< T >
TargetTransformInfoImplCRTPBase (const DataLayout &DL)
Protected Member Functions inherited from llvm::TargetTransformInfoImplBase
TargetTransformInfoImplBase (const DataLayout &DL)
unsigned minRequiredElementSize (const Value *Val, bool &isSigned) const
bool isStridedAccess (const SCEV *Ptr) const
const SCEVConstant * getConstantStrideStep (ScalarEvolution *SE, const SCEV *Ptr) const
bool isConstantStridedAccessLessThan (ScalarEvolution *SE, const SCEV *Ptr, int64_t MergeDistance) const
Protected Attributes
const DataLayout & DL
Protected Attributes inherited from llvm::TargetTransformInfoImplBase
const DataLayout & DL
Additional Inherited Members
Protected Types inherited from llvm::TargetTransformInfoImplBase
typedef TargetTransformInfo TTI
Detailed Description
template<typename T>
class llvm::BasicTTIImplBase< T >
Base class which can be used to help build a TTI implementation.
This class provides as much implementation of the TTI interface as is possible using the target independent parts of the code generator.
In order to subclass it, your class must implement a getST() method to return the subtarget, and a getTLI() method to return the target lowering. We need these methods implemented in the derived class so that this class doesn't have to duplicate storage for them.
Definition at line 75 of file BasicTTIImpl.h.
Constructor & Destructor Documentation
BasicTTIImplBase()
template<typename T > llvm::BasicTTIImplBase< T >::BasicTTIImplBase (const TargetMachine * TM, const DataLayout & DL) inline explicit protected
Definition at line 192 of file BasicTTIImpl.h.
~BasicTTIImplBase()
template<typename T > virtual llvm::BasicTTIImplBase< T >::~BasicTTIImplBase () protected virtual default
Member Function Documentation
adjustInliningThreshold()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::adjustInliningThreshold (const CallBase * CB) inline
Definition at line 404 of file BasicTTIImpl.h.
allowsMisalignedMemoryAccesses()
template<typename T > bool llvm::BasicTTIImplBase< T >::allowsMisalignedMemoryAccesses (LLVMContext & Context, unsigned BitWidth, unsigned AddressSpace, unsigned Alignment, bool * Fast) const inline
Definition at line 201 of file BasicTTIImpl.h.
References llvm::TargetLoweringBase::allowsMisalignedMemoryAccesses(), llvm::BitWidth, Context, E, llvm::EVT::getIntegerVT(), and llvm::MachineMemOperand::MONone.
collectFlatAddressOperands()
template<typename T > bool llvm::BasicTTIImplBase< T >::collectFlatAddressOperands (SmallVectorImpl< int > & OpIndexes, Intrinsic::ID IID) const inline
Definition at line 222 of file BasicTTIImpl.h.
emitGetActiveLaneMask()
template<typename T > bool llvm::BasicTTIImplBase< T >::emitGetActiveLaneMask () inline
Definition at line 492 of file BasicTTIImpl.h.
References llvm::TargetTransformInfoImplBase::emitGetActiveLaneMask().
enableWritePrefetching()
template<typename T > virtual bool llvm::BasicTTIImplBase< T >::enableWritePrefetching () const inline virtual
Reimplemented in llvm::SystemZTTIImpl.
Definition at line 564 of file BasicTTIImpl.h.
References llvm::MCSubtargetInfo::enableWritePrefetching().
getAddressComputationCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getAddressComputationCost (Type * Ty, ScalarEvolution * , const SCEV *) inline
Definition at line 1869 of file BasicTTIImpl.h.
getArithmeticInstrCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getArithmeticInstrCost (unsigned Opcode, Type * Ty, TTI::TargetCostKind CostKind = TTI::TCK_RecipThroughput, TTI::OperandValueKind Opd1Info = TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info = TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo = TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo = TTI::OP_None, ArrayRef< const Value * > Args = ArrayRef<const Value *>(), const Instruction * CxtI = nullptr) inline
Definition at line 663 of file BasicTTIImpl.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), CostKind, llvm::BasicTTIImplBase< T >::DL, llvm::TargetTransformInfoImplBase::getArithmeticInstrCost(), llvm::BasicTTIImplBase< T >::getScalarizationOverhead(), llvm::Type::getScalarType(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::Type::isFPOrFPVectorTy(), llvm::TargetLoweringBase::isOperationExpand(), llvm::TargetLoweringBase::isOperationLegalOrPromote(), llvm::AArch64CC::LT, and llvm::TargetTransformInfo::TCK_RecipThroughput.
Referenced by llvm::WebAssemblyTTIImpl::getArithmeticInstrCost().
getArithmeticReductionCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getArithmeticReductionCost (unsigned Opcode, VectorType * Ty, bool IsPairwise, TTI::TargetCostKind CostKind) inline
Try to calculate arithmetic and shuffle op costs for reduction operations.
We're assuming that reduction operation are performing the following way:
Non-pairwise reduction val1 = shufflevector<n x t> val, <n x t> undef, <n x i32> <i32 n/2, i32 n/2 + 1, ..., i32 n, i32 undef, ..., i32 undef> -------------—v----------—/ -------—v---------—/ n/2 elements n/2 elements red1 = op <n x t> val, <n x t> val1 After this operation we have a vector red1 where only the first n/2 elements are meaningful, the second n/2 elements are undefined and can be dropped. All other operations are actually working with the vector of length n/2, not n, though the real vector length is still n. val2 = shufflevector<n x t> red1, <n x t> undef, <n x i32> <i32 n/4, i32 n/4 + 1, ..., i32 n/2, i32 undef, ..., i32 undef> -------------—v----------—/ -------—v---------—/ n/4 elements 3*n/4 elements red2 = op <n x t> red1, <n x t> val2 - working with the vector of length n/2, the resulting vector has length n/4 etc.
Pairwise reduction: Everything is the same except for an additional shuffle operation which is used to produce operands for pairwise kind of reductions. val1 = shufflevector<n x t> val, <n x t> undef, <n x i32> <i32 0, i32 2, ..., i32 n-2, i32 undef, ..., i32 undef> ----------—v-------—/ -------—v---------—/ n/2 elements n/2 elements val2 = shufflevector<n x t> val, <n x t> undef, <n x i32> <i32 1, i32 3, ..., i32 n-1, i32 undef, ..., i32 undef> ----------—v-------—/ -------—v---------—/ n/2 elements n/2 elements red1 = op <n x t> val1, <n x t> val2 Again, the operation is performed on <n x t> vector, but the resulting vector red1 is <n/2 x t> vector.
The cost model should take into account that the actual length of the vector is reduced on each iteration.
Definition at line 1909 of file BasicTTIImpl.h.
References CostKind, llvm::BasicTTIImplBase< T >::DL, llvm::FixedVectorType::get(), llvm::VectorType::getElementType(), llvm::Log2_32(), llvm::AArch64CC::LT, llvm::TargetTransformInfo::SK_ExtractSubvector, and llvm::TargetTransformInfo::SK_PermuteSingleSrc.
getAssumedAddrSpace()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getAssumedAddrSpace (const Value * V) const inline
Definition at line 231 of file BasicTTIImpl.h.
References llvm::TargetMachine::getAssumedAddrSpace(), and llvm::TargetLoweringBase::getTargetMachine().
getCacheAssociativity()
template<typename T > virtual Optional<unsigned> llvm::BasicTTIImplBase< T >::getCacheAssociativity (TargetTransformInfo::CacheLevel Level) const inline virtual
Reimplemented in llvm::X86TTIImpl.
Definition at line 534 of file BasicTTIImpl.h.
References llvm::TargetTransformInfoImplBase::getCacheAssociativity(), and llvm::MCSubtargetInfo::getCacheAssociativity().
getCacheLineSize()
template<typename T > virtual unsigned llvm::BasicTTIImplBase< T >::getCacheLineSize () const inline virtual
Reimplemented in llvm::SystemZTTIImpl, llvm::PPCTTIImpl, and llvm::HexagonTTIImpl.
Definition at line 544 of file BasicTTIImpl.h.
References llvm::MCSubtargetInfo::getCacheLineSize().
getCacheSize()
template<typename T > virtual Optional<unsigned> llvm::BasicTTIImplBase< T >::getCacheSize (TargetTransformInfo::CacheLevel Level) const inline virtual
Reimplemented in llvm::X86TTIImpl.
Definition at line 528 of file BasicTTIImpl.h.
getCallInstrCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getCallInstrCost (Function * F, Type * RetTy, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind = TTI::TCK_SizeAndLatency) inline
Compute a cost of the given call instruction.
Compute the cost of calling function F with return type RetTy and argument types Tys. F might be nullptr, in this case the cost of an arbitrary call with the specified signature will be returned. This is used, for instance, when we estimate call of a vector counterpart of the given function.
Parameters
F Called function, might be nullptr.
RetTy Return value types.
Tys Argument types.
Returns
The cost of Call instruction.
Definition at line 1859 of file BasicTTIImpl.h.
getCastInstrCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getCastInstrCost (unsigned Opcode, Type * Dst, Type * Src, TTI::CastContextHint CCH, TTI::TargetCostKind CostKind, const Instruction * I = nullptr) inline
Definition at line 742 of file BasicTTIImpl.h.
References assert(), CostKind, llvm::BasicTTIImplBase< T >::DL, llvm::TargetTransformInfoImplBase::getCastInstrCost(), llvm::TargetTransformInfo::getCastInstrCost(), llvm::Type::getContext(), llvm::EVT::getEVT(), llvm::VectorType::getHalfElementsVectorType(), llvm::Type::getPointerAddressSpace(), llvm::BasicTTIImplBase< T >::getScalarizationOverhead(), llvm::Type::getScalarType(), llvm::TargetLoweringBase::getTypeAction(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::TargetLoweringBase::getValueType(), I, llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::TargetLoweringBase::isFreeAddrSpaceCast(), llvm::Type::isIntegerTy(), llvm::TargetLoweringBase::isLoadExtLegal(), llvm::TargetLoweringBase::isOperationExpand(), llvm::TargetLoweringBase::isOperationLegalOrPromote(), llvm::Type::isPointerTy(), llvm::TargetLoweringBase::isTruncateFree(), llvm::TargetLoweringBase::isZExtFree(), LLVM_FALLTHROUGH, llvm_unreachable, llvm::TargetTransformInfo::Normal, llvm::ISD::SEXTLOAD, T, llvm::TargetLoweringBase::TypeSplitVector, and llvm::ISD::ZEXTLOAD.
getCFInstrCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getCFInstrCost (unsigned Opcode, TTI::TargetCostKind CostKind) inline
Definition at line 900 of file BasicTTIImpl.h.
References CostKind, and llvm::TargetTransformInfoImplBase::getCFInstrCost().
Referenced by llvm::BasicTTIImplBase< T >::getGatherScatterOpCost().
getCmpSelInstrCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getCmpSelInstrCost (unsigned Opcode, Type * ValTy, Type * CondTy, CmpInst::Predicate VecPred, TTI::TargetCostKind CostKind, const Instruction * I = nullptr) inline
Definition at line 904 of file BasicTTIImpl.h.
References assert(), CostKind, llvm::BasicTTIImplBase< T >::DL, llvm::TargetTransformInfoImplBase::getCmpSelInstrCost(), llvm::BasicTTIImplBase< T >::getScalarizationOverhead(), llvm::Type::getScalarType(), llvm::TargetLoweringBase::getTypeLegalizationCost(), I, llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::TargetLoweringBase::isOperationExpand(), llvm::Type::isVectorTy(), llvm::AArch64CC::LT, llvm::ISD::SELECT, llvm::TargetTransformInfo::TCK_RecipThroughput, and llvm::ISD::VSELECT.
getEstimatedNumberOfCaseClusters()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getEstimatedNumberOfCaseClusters (const SwitchInst & SI, unsigned & JumpTableSize, ProfileSummaryInfo * PSI, BlockFrequencyInfo * BFI) inline
Try to find the estimated number of clusters. Note that the number of clusters identified in this function could be different from the actual numbers found in lowering. This function ignore switches that are lowered with a mix of jump table / bit test / BTree. This function was initially intended to be used when estimating the cost of switch in inline cost heuristic, but it's a generic cost model to be used in other places (e.g., in loop unrolling).
Definition at line 317 of file BasicTTIImpl.h.
References llvm::TargetLoweringBase::areJTsAllowed(), llvm::AMDGPUISD::BFI, llvm::BasicTTIImplBase< T >::DL, llvm::TargetTransformInfoImplBase::getDataLayout(), llvm::DataLayout::getIndexSizeInBits(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::TargetLoweringBase::isSuitableForBitTests(), llvm::TargetLoweringBase::isSuitableForJumpTable(), llvm::max(), N, llvm::APInt::sgt(), SI, llvm::SmallPtrSetImplBase::size(), and llvm::APInt::slt().
getExtendedAddReductionCost()
template<typename T > InstructionCost llvm::BasicTTIImplBase< T >::getExtendedAddReductionCost (bool IsMLA, bool IsUnsigned, Type * ResTy, VectorType * Ty, TTI::TargetCostKind CostKind) inline
Definition at line 2023 of file BasicTTIImpl.h.
References llvm::MCID::Add, CostKind, llvm::VectorType::get(), and llvm::TargetTransformInfo::None.
getExtractWithExtendCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getExtractWithExtendCost (unsigned Opcode, Type * Dst, VectorType * VecTy, unsigned Index) inline
Definition at line 892 of file BasicTTIImpl.h.
References llvm::VectorType::getElementType(), Index, llvm::TargetTransformInfo::None, and llvm::TargetTransformInfo::TCK_RecipThroughput.
getFlatAddressSpace()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getFlatAddressSpace () inline
Definition at line 217 of file BasicTTIImpl.h.
getFPOpCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getFPOpCost (Type * Ty) inline
Definition at line 393 of file BasicTTIImpl.h.
References llvm::BasicTTIImplBase< T >::DL, llvm::ISD::FADD, llvm::TargetLoweringBase::getValueType(), llvm::TargetLoweringBase::isOperationLegalOrCustomOrPromote(), llvm::TargetTransformInfo::TCC_Basic, and llvm::TargetTransformInfo::TCC_Expensive.
getGatherScatterOpCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getGatherScatterOpCost (unsigned Opcode, Type * DataTy, const Value * Ptr, bool VariableMask, Align Alignment, TTI::TargetCostKind CostKind, const Instruction * I = nullptr) inline
Definition at line 1001 of file BasicTTIImpl.h.
References CostKind, llvm::PointerType::get(), llvm::FixedVectorType::get(), llvm::BasicTTIImplBase< T >::getCFInstrCost(), llvm::Type::getContext(), llvm::Type::getInt1Ty(), llvm::BasicTTIImplBase< T >::getMemoryOpCost(), llvm::BasicTTIImplBase< T >::getScalarizationOverhead(), llvm::BasicTTIImplBase< T >::getVectorInstrCost(), and llvm::SPII::Store.
getGEPCost()
template<typename T > int llvm::BasicTTIImplBase< T >::getGEPCost (Type * PointeeType, const Value * Ptr, ArrayRef< const Value * > Operands) inline
Definition at line 312 of file BasicTTIImpl.h.
References llvm::TargetTransformInfoImplCRTPBase< T >::getGEPCost(), and Operands.
getInlinerVectorBonusPercent()
template<typename T > int llvm::BasicTTIImplBase< T >::getInlinerVectorBonusPercent () inline
Definition at line 406 of file BasicTTIImpl.h.
getInliningThresholdMultiplier()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getInliningThresholdMultiplier () inline
Definition at line 403 of file BasicTTIImpl.h.
getInstructionLatency()
template<typename T > int llvm::BasicTTIImplBase< T >::getInstructionLatency (const Instruction * I) inline
Definition at line 520 of file BasicTTIImpl.h.
References llvm::MCSchedModel::DefaultLoadLatency, llvm::TargetTransformInfoImplCRTPBase< T >::getInstructionLatency(), llvm::MCSubtargetInfo::getSchedModel(), and I.
getInterleavedMemoryOpCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getInterleavedMemoryOpCost (unsigned Opcode, Type * VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, bool UseMaskForCond = false, bool UseMaskForGaps = false) inline
Definition at line 1046 of file BasicTTIImpl.h.
References assert(), B, CostKind, llvm::BitVector::count(), llvm::BasicTTIImplBase< T >::DL, llvm::FixedVectorType::get(), llvm::Type::getInt8Ty(), llvm::MVT::getStoreSize(), llvm::TargetLoweringBase::getTypeLegalizationCost(), Index, llvm::SPII::Load, llvm::BitVector::set(), llvm::ArrayRef< T >::size(), and T.
getIntrinsicInstrCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost (const IntrinsicCostAttributes & ICA, TTI::TargetCostKind CostKind) inline
Get intrinsic cost based on arguments.
Definition at line 1198 of file BasicTTIImpl.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, llvm::CmpInst::BAD_ICMP_PREDICATE, CostKind, llvm::FixedVectorType::get(), llvm::IntrinsicCostAttributes::getArgs(), llvm::LinearPolySize< ElementCount >::getFixed(), llvm::IntrinsicCostAttributes::getFlags(), llvm::IntrinsicCostAttributes::getID(), llvm::IntrinsicCostAttributes::getInst(), llvm::TargetTransformInfoImplBase::getIntrinsicInstrCost(), llvm::LinearPolySize< LeafTy >::getKnownMinValue(), llvm::TargetTransformInfo::getOperandInfo(), llvm::BasicTTIImplBase< T >::getOperandsScalarizationOverhead(), llvm::IntrinsicCostAttributes::getReturnType(), llvm::BasicTTIImplBase< T >::getScalarizationOverhead(), llvm::Type::getScalarSizeInBits(), getType(), llvm::BasicTTIImplBase< T >::getTypeBasedIntrinsicInstrCost(), llvm::IntrinsicCostAttributes::getVectorFactor(), llvm::Type::getWithNewBitWidth(), I, Index, llvm::isPowerOf2_32(), llvm::ElementCount::isScalar(), llvm::Function::isTargetIntrinsic(), llvm::IntrinsicCostAttributes::isTypeBasedOnly(), llvm::ElementCount::isVector(), llvm::Type::isVectorTy(), llvm::Type::isVoidTy(), llvm::SPII::Load, llvm::BitmaskEnumDetail::Mask(), llvm::max(), llvm::TargetTransformInfo::OK_NonUniformConstantValue, llvm::TargetTransformInfo::OK_UniformConstantValue, llvm::TargetTransformInfo::OP_None, llvm::TargetTransformInfo::OP_PowerOf2, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::MCID::Select, llvm::TargetTransformInfo::SK_ExtractSubvector, llvm::TargetTransformInfo::SK_InsertSubvector, llvm::SPII::Store, llvm::TargetTransformInfo::TCC_Basic, X, and Y.
getMaxInterleaveFactor()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getMaxInterleaveFactor (unsigned VF) inline
Definition at line 661 of file BasicTTIImpl.h.
getMaxPrefetchIterationsAhead()
template<typename T > virtual unsigned llvm::BasicTTIImplBase< T >::getMaxPrefetchIterationsAhead () const inline virtual
Definition at line 560 of file BasicTTIImpl.h.
References llvm::MCSubtargetInfo::getMaxPrefetchIterationsAhead().
getMaxVScale()
template<typename T > Optional<unsigned> llvm::BasicTTIImplBase< T >::getMaxVScale () const inline
Definition at line 575 of file BasicTTIImpl.h.
References llvm::None.
getMemoryOpCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getMemoryOpCost (unsigned Opcode, Type * Src, MaybeAlign Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, const Instruction * I = nullptr) inline
Definition at line 958 of file BasicTTIImpl.h.
References assert(), CostKind, llvm::TargetLoweringBase::Custom, llvm::BasicTTIImplBase< T >::DL, llvm::TargetLoweringBase::Expand, llvm::ISD::EXTLOAD, llvm::TargetLoweringBase::getLoadExtAction(), llvm::Type::getPrimitiveSizeInBits(), llvm::BasicTTIImplBase< T >::getScalarizationOverhead(), llvm::TargetLoweringBase::getTruncStoreAction(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::TargetLoweringBase::getValueType(), llvm::LinearPolySize< TypeSize >::isKnownLT(), llvm::Type::isVectorTy(), llvm::Type::isVoidTy(), llvm::TargetLoweringBase::Legal, llvm::AArch64CC::LT, llvm::MVT::Other, llvm::SPII::Store, and llvm::TargetTransformInfo::TCK_RecipThroughput.
Referenced by llvm::BasicTTIImplBase< T >::getGatherScatterOpCost().
getMinMaxReductionCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getMinMaxReductionCost (VectorType * Ty, VectorType * CondTy, bool IsPairwise, bool IsUnsigned, TTI::TargetCostKind CostKind) inline
Try to calculate op costs for min/max reduction operations.
Parameters
CondTy Conditional type for the Select instruction.
Definition at line 1956 of file BasicTTIImpl.h.
References assert(), llvm::CmpInst::BAD_ICMP_PREDICATE, CostKind, llvm::BasicTTIImplBase< T >::DL, llvm::FixedVectorType::get(), llvm::VectorType::getElementType(), llvm::Type::isFPOrFPVectorTy(), llvm::Type::isIntOrIntVectorTy(), llvm::Log2_32(), llvm::AArch64CC::LT, llvm::MCID::Select, llvm::TargetTransformInfo::SK_ExtractSubvector, and llvm::TargetTransformInfo::SK_PermuteSingleSrc.
getMinPrefetchStride()
template<typename T > virtual unsigned llvm::BasicTTIImplBase< T >::getMinPrefetchStride (unsigned NumMemAccesses, unsigned NumStridedMemAccesses, unsigned NumPrefetches, bool HasCall) const inline virtual
Reimplemented in llvm::SystemZTTIImpl.
Definition at line 552 of file BasicTTIImpl.h.
References llvm::MCSubtargetInfo::getMinPrefetchStride().
getNumberOfParts()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getNumberOfParts (Type * Tp) inline
Definition at line 1864 of file BasicTTIImpl.h.
References llvm::BasicTTIImplBase< T >::DL, llvm::TargetLoweringBase::getTypeLegalizationCost(), and llvm::AArch64CC::LT.
getOperandsScalarizationOverhead()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, unsigned VF) inline
Estimate the overhead of scalarizing an instruction's unique non-constant operands.
The types of the arguments are ordinarily scalar, in which case the costs are multiplied with VF.
Definition at line 615 of file BasicTTIImpl.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), llvm::FixedVectorType::get(), llvm::BasicTTIImplBase< T >::getScalarizationOverhead(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::Type::isFPOrFPVectorTy(), llvm::Type::isIntOrIntVectorTy(), and llvm::Type::isPtrOrPtrVectorTy().
Referenced by llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), and llvm::BasicTTIImplBase< T >::getScalarizationOverhead().
getPeelingPreferences()
template<typename T > void llvm::BasicTTIImplBase< T >::getPeelingPreferences (Loop * L, ScalarEvolution & SE, TTI::PeelingPreferences & PP) inline
Definition at line 470 of file BasicTTIImpl.h.
References llvm::TargetTransformInfo::PeelingPreferences::AllowLoopNestsPeeling, llvm::TargetTransformInfo::PeelingPreferences::AllowPeeling, llvm::TargetTransformInfo::PeelingPreferences::PeelCount, and llvm::TargetTransformInfo::PeelingPreferences::PeelProfiledIterations.
getPrefetchDistance()
template<typename T > virtual unsigned llvm::BasicTTIImplBase< T >::getPrefetchDistance () const inline virtual
Reimplemented in llvm::SystemZTTIImpl, llvm::PPCTTIImpl, and llvm::HexagonTTIImpl.
Definition at line 548 of file BasicTTIImpl.h.
References llvm::MCSubtargetInfo::getPrefetchDistance().
getRegisterBitWidth()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getRegisterBitWidth (bool Vector) const inline
Definition at line 573 of file BasicTTIImpl.h.
getRegUsageForType()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getRegUsageForType (Type * Ty) inline
Definition at line 308 of file BasicTTIImpl.h.
References llvm::BasicTTIImplBase< T >::DL, and llvm::TargetLoweringBase::getTypeLegalizationCost().
getScalarizationOverhead() [1/3]
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getScalarizationOverhead (VectorType * InTy, ArrayRef< const Value * > Args) inline
Definition at line 644 of file BasicTTIImpl.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::BasicTTIImplBase< T >::getOperandsScalarizationOverhead(), and llvm::BasicTTIImplBase< T >::getScalarizationOverhead().
getScalarizationOverhead() [2/3]
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getScalarizationOverhead (VectorType * InTy, bool Insert, bool Extract) inline
Helper wrapper for the DemandedElts variant of getScalarizationOverhead.
Definition at line 604 of file BasicTTIImpl.h.
References llvm::APInt::getAllOnesValue().
getScalarizationOverhead() [3/3]
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getScalarizationOverhead (VectorType * InTy, const APInt & DemandedElts, bool Insert, bool Extract) inline
Estimate the overhead of scalarizing an instruction.
Insert and Extract are set if the demanded result elements need to be inserted and/or extracted from vectors.
FIXME: a bitfield is not a reasonable abstraction for talking about which elements are needed from a scalable vector
Definition at line 580 of file BasicTTIImpl.h.
References assert(), llvm::numbers::e, and llvm::APInt::getBitWidth().
Referenced by llvm::BasicTTIImplBase< T >::getArithmeticInstrCost(), llvm::BasicTTIImplBase< T >::getCastInstrCost(), llvm::BasicTTIImplBase< T >::getCmpSelInstrCost(), llvm::BasicTTIImplBase< T >::getGatherScatterOpCost(), llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), llvm::BasicTTIImplBase< T >::getMemoryOpCost(), llvm::BasicTTIImplBase< T >::getOperandsScalarizationOverhead(), llvm::BasicTTIImplBase< T >::getScalarizationOverhead(), and llvm::BasicTTIImplBase< T >::getTypeBasedIntrinsicInstrCost().
getScalingFactorCost()
template<typename T > int llvm::BasicTTIImplBase< T >::getScalingFactorCost (Type * Ty, GlobalValue * BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) inline
Definition at line 283 of file BasicTTIImpl.h.
References llvm::TargetLoweringBase::AddrMode::BaseGV, llvm::TargetLoweringBase::AddrMode::BaseOffs, llvm::BasicTTIImplBase< T >::DL, llvm::TargetLoweringBase::getScalingFactorCost(), llvm::TargetLoweringBase::AddrMode::HasBaseReg, and llvm::TargetLoweringBase::AddrMode::Scale.
getShuffleCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getShuffleCost (TTI::ShuffleKind Kind, VectorType * Tp, int Index, VectorType * SubTp) inline
Definition at line 720 of file BasicTTIImpl.h.
References Index, llvm_unreachable, llvm::TargetTransformInfo::SK_Broadcast, llvm::TargetTransformInfo::SK_ExtractSubvector, llvm::TargetTransformInfo::SK_InsertSubvector, llvm::TargetTransformInfo::SK_PermuteSingleSrc, llvm::TargetTransformInfo::SK_PermuteTwoSrc, llvm::TargetTransformInfo::SK_Reverse, llvm::TargetTransformInfo::SK_Select, and llvm::TargetTransformInfo::SK_Transpose.
getTypeBasedIntrinsicInstrCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getTypeBasedIntrinsicInstrCost (const IntrinsicCostAttributes & ICA, TTI::TargetCostKind CostKind) inline
Get intrinsic cost based on argument types.
If ScalarizationCostPassed is std::numeric_limits<unsigned>::max(), the cost of scalarizing the arguments and the return value will be computed based on types.
Definition at line 1383 of file BasicTTIImpl.h.
References llvm::abs(), llvm::MCID::Add, assert(), llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, llvm::CmpInst::BAD_ICMP_PREDICATE, llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::ISD::BITREVERSE, llvm::ISD::BSWAP, CostKind, llvm::StructType::create(), llvm::ISD::CTLZ, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::BasicTTIImplBase< T >::DL, llvm::SmallVectorBase< Size_T >::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::ISD::FABS, llvm::ISD::FCANONICALIZE, llvm::ISD::FCEIL, llvm::ISD::FCOPYSIGN, llvm::ISD::FCOS, llvm::ISD::FEXP, llvm::ISD::FEXP2, llvm::ISD::FFLOOR, llvm::ISD::FLOG, llvm::ISD::FLOG10, llvm::ISD::FLOG2, llvm::ISD::FMA, llvm::ISD::FMAXIMUM, llvm::ISD::FMAXNUM, llvm::ISD::FMINIMUM, llvm::ISD::FMINNUM, llvm::ISD::FNEARBYINT, llvm::ISD::FPOW, llvm::ISD::FRINT, llvm::ISD::FROUND, llvm::ISD::FROUNDEVEN, llvm::ISD::FSIN, llvm::ISD::FSQRT, llvm::ISD::FTRUNC, llvm::IntrinsicCostAttributes::getArgTypes(), llvm::Type::getContainedType(), llvm::IntrinsicCostAttributes::getFlags(), llvm::IntrinsicCostAttributes::getID(), llvm::IntrinsicCostAttributes::getReturnType(), llvm::IntrinsicCostAttributes::getScalarizationCost(), llvm::BasicTTIImplBase< T >::getScalarizationOverhead(), llvm::Type::getScalarSizeInBits(), llvm::Type::getScalarType(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::Type::getWithNewBitWidth(), llvm::TargetLoweringBase::isFAbsFree(), llvm::TargetLoweringBase::isOperationExpand(), llvm::TargetLoweringBase::isOperationLegalOrPromote(), llvm::Type::isVectorTy(), llvm::SPII::Load, llvm::log2(), llvm::AArch64CC::LT, llvm::CmpInst::makeCmpResultType(), llvm::max(), llvm::maximum(), llvm::maxnum(), llvm::minimum(), llvm::minnum(), llvm::TargetTransformInfo::None, llvm::TargetTransformInfo::OK_AnyValue, llvm::TargetTransformInfo::OK_UniformConstantValue, llvm::SmallVectorTemplateBase< T, bool >::push_back(), round(), llvm::MCID::Select, llvm::SmallVectorBase< Size_T >::size(), llvm::IntrinsicCostAttributes::skipScalarizationCost(), llvm::APIntOps::smax(), llvm::APIntOps::smin(), llvm::SPII::Store, llvm::ISD::STRICT_FMA, llvm::TargetTransformInfo::TCC_Expensive, llvm::TargetTransformInfo::TCK_CodeSize, llvm::APIntOps::umax(), and llvm::APIntOps::umin().
Referenced by llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost().
getUnrollingPreferences()
template<typename T > void llvm::BasicTTIImplBase< T >::getUnrollingPreferences (Loop * L, ScalarEvolution & SE, TTI::UnrollingPreferences & UP) inline
Definition at line 408 of file BasicTTIImpl.h.
References llvm::TargetTransformInfo::UnrollingPreferences::BEInsns, llvm::LoopBase< BlockT, LoopT >::blocks(), F, getCalledFunction(), I, llvm::TargetTransformInfoImplBase::isLoweredToCall(), llvm::TargetTransformInfo::UnrollingPreferences::OptSizeThreshold, llvm::TargetTransformInfo::UnrollingPreferences::Partial, llvm::TargetTransformInfo::UnrollingPreferences::PartialOptSizeThreshold, llvm::TargetTransformInfo::UnrollingPreferences::PartialThreshold, llvm::PartialUnrollingThreshold, llvm::TargetTransformInfo::UnrollingPreferences::Runtime, llvm::ARM_MB::ST, and llvm::TargetTransformInfo::UnrollingPreferences::UpperBound.
Referenced by llvm::ARMTTIImpl::getUnrollingPreferences().
getVectorInstrCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getVectorInstrCost (unsigned Opcode, Type * Val, unsigned Index) inline
Definition at line 951 of file BasicTTIImpl.h.
References llvm::BasicTTIImplBase< T >::DL, llvm::Type::getScalarType(), llvm::TargetLoweringBase::getTypeLegalizationCost(), and llvm::AArch64CC::LT.
Referenced by llvm::BasicTTIImplBase< T >::getGatherScatterOpCost(), and llvm::WebAssemblyTTIImpl::getVectorInstrCost().
getVectorSplitCost()
template<typename T > unsigned llvm::BasicTTIImplBase< T >::getVectorSplitCost () inline
Definition at line 2044 of file BasicTTIImpl.h.
hasBranchDivergence()
template<typename T > bool llvm::BasicTTIImplBase< T >::hasBranchDivergence () inline
Definition at line 209 of file BasicTTIImpl.h.
haveFastSqrt()
template<typename T > bool llvm::BasicTTIImplBase< T >::haveFastSqrt (Type * Ty) inline
Definition at line 382 of file BasicTTIImpl.h.
References llvm::BasicTTIImplBase< T >::DL, llvm::ISD::FSQRT, llvm::TargetLoweringBase::getValueType(), llvm::TargetLoweringBase::isOperationLegalOrCustom(), and llvm::TargetLoweringBase::isTypeLegal().
instCombineIntrinsic()
template<typename T > Optional<Instruction *> llvm::BasicTTIImplBase< T >::instCombineIntrinsic (InstCombiner & IC, IntrinsicInst & II) inline
Definition at line 496 of file BasicTTIImpl.h.
References llvm::TargetTransformInfoImplBase::instCombineIntrinsic().
isAlwaysUniform()
template<typename T > bool llvm::BasicTTIImplBase< T >::isAlwaysUniform (const Value * V) inline
Definition at line 215 of file BasicTTIImpl.h.
isFCmpOrdCheaperThanFCmpZero()
template<typename T > bool llvm::BasicTTIImplBase< T >::isFCmpOrdCheaperThanFCmpZero (Type * Ty) inline
Definition at line 389 of file BasicTTIImpl.h.
isHardwareLoopProfitable()
template<typename T > bool llvm::BasicTTIImplBase< T >::isHardwareLoopProfitable (Loop * L, ScalarEvolution & SE, AssumptionCache & AC, TargetLibraryInfo * LibInfo, HardwareLoopInfo & HWLoopInfo) inline
Definition at line 478 of file BasicTTIImpl.h.
References llvm::TargetTransformInfoImplBase::isHardwareLoopProfitable().
isIndexedLoadLegal()
template<typename T > bool llvm::BasicTTIImplBase< T >::isIndexedLoadLegal (TTI::MemIndexedMode M, Type * Ty, const DataLayout & DL) const inline
Definition at line 259 of file BasicTTIImpl.h.
References llvm::BasicTTIImplBase< T >::DL, llvm::TargetLoweringBase::getValueType(), and llvm::TargetLoweringBase::isIndexedLoadLegal().
isIndexedStoreLegal()
template<typename T > bool llvm::BasicTTIImplBase< T >::isIndexedStoreLegal (TTI::MemIndexedMode M, Type * Ty, const DataLayout & DL) const inline
Definition at line 265 of file BasicTTIImpl.h.
References llvm::BasicTTIImplBase< T >::DL, llvm::TargetLoweringBase::getValueType(), and llvm::TargetLoweringBase::isIndexedStoreLegal().
isLegalAddImmediate()
template<typename T > bool llvm::BasicTTIImplBase< T >::isLegalAddImmediate (int64_t imm) inline
Definition at line 240 of file BasicTTIImpl.h.
References llvm::TargetLoweringBase::isLegalAddImmediate().
isLegalAddressingMode()
template<typename T > bool llvm::BasicTTIImplBase< T >::isLegalAddressingMode (Type * Ty, GlobalValue * BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction * I = nullptr) inline
Definition at line 248 of file BasicTTIImpl.h.
References llvm::TargetLoweringBase::AddrMode::BaseGV, llvm::TargetLoweringBase::AddrMode::BaseOffs, llvm::BasicTTIImplBase< T >::DL, llvm::TargetLoweringBase::AddrMode::HasBaseReg, I, llvm::TargetLoweringBase::isLegalAddressingMode(), and llvm::TargetLoweringBase::AddrMode::Scale.
isLegalICmpImmediate()
template<typename T > bool llvm::BasicTTIImplBase< T >::isLegalICmpImmediate (int64_t imm) inline
Definition at line 244 of file BasicTTIImpl.h.
References llvm::TargetLoweringBase::isLegalICmpImmediate().
isLSRCostLess()
template<typename T > bool llvm::BasicTTIImplBase< T >::isLSRCostLess (TTI::LSRCost C1, TTI::LSRCost C2) inline
Definition at line 271 of file BasicTTIImpl.h.
References llvm::TargetTransformInfoImplBase::isLSRCostLess().
isNoopAddrSpaceCast()
template<typename T > bool llvm::BasicTTIImplBase< T >::isNoopAddrSpaceCast (unsigned FromAS, unsigned ToAS) const inline
Definition at line 227 of file BasicTTIImpl.h.
References llvm::TargetLoweringBase::getTargetMachine(), and llvm::TargetMachine::isNoopAddrSpaceCast().
isNumRegsMajorCostOfLSR()
template<typename T > bool llvm::BasicTTIImplBase< T >::isNumRegsMajorCostOfLSR () inline
Definition at line 275 of file BasicTTIImpl.h.
References llvm::TargetTransformInfoImplBase::isNumRegsMajorCostOfLSR().
isProfitableLSRChainElement()
template<typename T > bool llvm::BasicTTIImplBase< T >::isProfitableLSRChainElement (Instruction * I) inline
Definition at line 279 of file BasicTTIImpl.h.
References I, and llvm::TargetTransformInfoImplBase::isProfitableLSRChainElement().
isProfitableToHoist()
template<typename T > bool llvm::BasicTTIImplBase< T >::isProfitableToHoist (Instruction * I) inline
Definition at line 297 of file BasicTTIImpl.h.
References I, and llvm::TargetLoweringBase::isProfitableToHoist().
isSourceOfDivergence()
template<typename T > bool llvm::BasicTTIImplBase< T >::isSourceOfDivergence (const Value * V) inline
Definition at line 213 of file BasicTTIImpl.h.
isTruncateFree()
template<typename T > bool llvm::BasicTTIImplBase< T >::isTruncateFree (Type * Ty1, Type * Ty2) inline
Definition at line 293 of file BasicTTIImpl.h.
References llvm::TargetLoweringBase::isTruncateFree().
isTypeLegal()
template<typename T > bool llvm::BasicTTIImplBase< T >::isTypeLegal (Type * Ty) inline
Definition at line 303 of file BasicTTIImpl.h.
References llvm::BasicTTIImplBase< T >::DL, llvm::TargetLoweringBase::getValueType(), and llvm::TargetLoweringBase::isTypeLegal().
preferPredicateOverEpilogue()
template<typename T > bool llvm::BasicTTIImplBase< T >::preferPredicateOverEpilogue (Loop * L, LoopInfo * LI, ScalarEvolution & SE, AssumptionCache & AC, TargetLibraryInfo * TLI, DominatorTree * DT, const LoopAccessInfo * LAI) inline
Definition at line 485 of file BasicTTIImpl.h.
References llvm::TargetTransformInfoImplBase::preferPredicateOverEpilogue().
rewriteIntrinsicWithAddressSpace()
template<typename T > Value* llvm::BasicTTIImplBase< T >::rewriteIntrinsicWithAddressSpace (IntrinsicInst * II, Value * OldV, Value * NewV) const inline
Definition at line 235 of file BasicTTIImpl.h.
shouldBuildLookupTables()
template<typename T > bool llvm::BasicTTIImplBase< T >::shouldBuildLookupTables () inline
Definition at line 376 of file BasicTTIImpl.h.
References llvm::ISD::BR_JT, llvm::ISD::BRIND, llvm::TargetLoweringBase::isOperationLegalOrCustom(), and llvm::MVT::Other.
simplifyDemandedUseBitsIntrinsic()
template<typename T > Optional<Value *> llvm::BasicTTIImplBase< T >::simplifyDemandedUseBitsIntrinsic (InstCombiner & IC, IntrinsicInst & II, APInt DemandedMask, KnownBits & Known, bool & KnownBitsComputed) inline
Definition at line 501 of file BasicTTIImpl.h.
References llvm::TargetTransformInfoImplBase::simplifyDemandedUseBitsIntrinsic().
simplifyDemandedVectorEltsIntrinsic()
template<typename T > Optional<Value *> llvm::BasicTTIImplBase< T >::simplifyDemandedVectorEltsIntrinsic (InstCombiner & IC, IntrinsicInst & II, APInt DemandedElts, APInt & UndefElts, APInt & UndefElts2, APInt & UndefElts3, std::function< void(Instruction *, unsigned, APInt, APInt &)> SimplifyAndSetOp) inline
Definition at line 510 of file BasicTTIImpl.h.
References llvm::TargetTransformInfoImplBase::simplifyDemandedVectorEltsIntrinsic().
useAA()
template<typename T > bool llvm::BasicTTIImplBase< T >::useAA () const inline
Definition at line 301 of file BasicTTIImpl.h.
References llvm::TargetSubtargetInfo::useAA().
useGPUDivergenceAnalysis()
template<typename T > bool llvm::BasicTTIImplBase< T >::useGPUDivergenceAnalysis () inline
Definition at line 211 of file BasicTTIImpl.h.
Member Data Documentation
DL
template<typename T > const DataLayout& llvm::TargetTransformInfoImplBase::DL protected
Definition at line 35 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< T >::getArithmeticInstrCost(), llvm::BasicTTIImplBase< T >::getArithmeticReductionCost(), llvm::BasicTTIImplBase< T >::getCastInstrCost(), llvm::BasicTTIImplBase< T >::getCmpSelInstrCost(), llvm::BasicTTIImplBase< T >::getEstimatedNumberOfCaseClusters(), llvm::BasicTTIImplBase< T >::getFPOpCost(), llvm::BasicTTIImplBase< T >::getInterleavedMemoryOpCost(), llvm::BasicTTIImplBase< T >::getMemoryOpCost(), llvm::BasicTTIImplBase< T >::getMinMaxReductionCost(), llvm::BasicTTIImplBase< T >::getNumberOfParts(), llvm::BasicTTIImplBase< T >::getRegUsageForType(), llvm::BasicTTIImplBase< T >::getScalingFactorCost(), llvm::BasicTTIImplBase< T >::getTypeBasedIntrinsicInstrCost(), llvm::BasicTTIImplBase< T >::getVectorInstrCost(), llvm::BasicTTIImplBase< T >::haveFastSqrt(), llvm::BasicTTIImplBase< T >::isIndexedLoadLegal(), llvm::BasicTTIImplBase< T >::isIndexedStoreLegal(), llvm::BasicTTIImplBase< T >::isLegalAddressingMode(), and llvm::BasicTTIImplBase< T >::isTypeLegal().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/BasicTTIImpl.h