LLVM: llvm::IPSCCPPass Class Reference
llvm::IPSCCPPass Class Reference
Pass to perform interprocedural constant propagation.
#include "llvm/Transforms/IPO/SCCP.h"
Public Member Functions
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< IPSCCPPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Pass to perform interprocedural constant propagation.
Definition at line 30 of file SCCP.h.
Member Function Documentation
run()
PreservedAnalyses IPSCCPPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 11 of file SCCP.cpp.
References llvm::PreservedAnalyses::all(), DL, F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PreservedAnalyses::preserve(), and llvm::runIPSCCP().
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/SCCP.h
lib/Transforms/IPO/SCCP.cpp