LLVM: WidenIV Class Reference
WidenIV Class Reference
Classes
struct NarrowIVDefUse
Record a link in the Narrow IV def-use chain along with the WideIV that computes the same value as the Narrow IV def.
Public Member Functions
WidenIV (const WideIVInfo &WI, LoopInfo *LInfo, ScalarEvolution *SEv, DominatorTree *DTree, SmallVectorImpl< WeakTrackingVH > &DI, bool HasGuards, bool UsePostIncrementRanges=true)
PHINode * createWideIV (SCEVExpander &Rewriter)
Process a single induction variable.
unsigned getNumElimExt ()
unsigned getNumWidened ()
Protected Types
using WidenedRecTy = std::pair< const SCEVAddRecExpr *, ExtendKind >
Protected Member Functions
Value * createExtendInst (Value *NarrowOper, Type *WideType, bool IsSigned, Instruction *Use)
Instruction * cloneIVUser (NarrowIVDefUse DU, const SCEVAddRecExpr *WideAR)
Instantiate a wide operation to replace a narrow operation.
Instruction * cloneArithmeticIVUser (NarrowIVDefUse DU, const SCEVAddRecExpr *WideAR)
Instruction * cloneBitwiseIVUser (NarrowIVDefUse DU)
ExtendKind getExtendKind (Instruction *I)
WidenedRecTy getWideRecurrence (NarrowIVDefUse DU)
Is this instruction potentially interesting for further simplification after widening it's type? In other words, can the extend be safely hoisted out of the loop with SCEV reducing the value to a recurrence on the same loop.
WidenedRecTy getExtendedOperandRecurrence (NarrowIVDefUse DU)
No-wrap operations can transfer sign extension of their result to their operands.
const SCEV * getSCEVByOpCode (const SCEV *LHS, const SCEV *RHS, unsigned OpCode) const
Instruction * widenIVUse (NarrowIVDefUse DU, SCEVExpander &Rewriter)
Determine whether an individual user of the narrow IV can be widened.
bool widenLoopCompare (NarrowIVDefUse DU)
If the narrow use is a compare instruction, then widen the compare.
bool widenWithVariantUse (NarrowIVDefUse DU)
void pushNarrowIVUsers (Instruction *NarrowDef, Instruction *WideDef)
Add eligible users of NarrowDef to NarrowIVUsers.
Detailed Description
Definition at line 977 of file SimplifyIndVar.cpp.
Member Typedef Documentation
WidenedRecTy
using WidenIV::WidenedRecTy = std::pair<const SCEVAddRecExpr *, ExtendKind> protected
Definition at line 1083 of file SimplifyIndVar.cpp.
Constructor & Destructor Documentation
WidenIV()
WidenIV::WidenIV (const WideIVInfo & WI, LoopInfo * LInfo, ScalarEvolution * SEv, DominatorTree * DTree, SmallVectorImpl< WeakTrackingVH > & DI, bool HasGuards, bool UsePostIncrementRanges = true)
Definition at line 1155 of file SimplifyIndVar.cpp.
References assert(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::Instruction::getParent(), and llvm::WideIVInfo::IsSigned.
Member Function Documentation
cloneArithmeticIVUser()
Instruction * WidenIV::cloneArithmeticIVUser (WidenIV::NarrowIVDefUse DU, const SCEVAddRecExpr * WideAR) protected
Definition at line 1235 of file SimplifyIndVar.cpp.
References Builder, createExtendInst(), llvm::dbgs(), getExtendKind(), llvm::Value::getName(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::ScalarEvolution::getSCEV(), getSCEVByOpCode(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::ScalarEvolution::getZeroExtendExpr(), LLVM_DEBUG, WidenIV::NarrowIVDefUse::NarrowDef, WidenIV::NarrowIVDefUse::NarrowUse, and WidenIV::NarrowIVDefUse::WideDef.
Referenced by cloneIVUser().
cloneBitwiseIVUser()
Instruction * WidenIV::cloneBitwiseIVUser (WidenIV::NarrowIVDefUse DU) protected
Definition at line 1205 of file SimplifyIndVar.cpp.
References Builder, createExtendInst(), llvm::dbgs(), getExtendKind(), llvm::Value::getName(), llvm::User::getOperand(), LLVM_DEBUG, WidenIV::NarrowIVDefUse::NarrowDef, WidenIV::NarrowIVDefUse::NarrowUse, and WidenIV::NarrowIVDefUse::WideDef.
Referenced by cloneIVUser().
cloneIVUser()
Instruction * WidenIV::cloneIVUser (WidenIV::NarrowIVDefUse DU, const SCEVAddRecExpr * WideAR) protected
Instantiate a wide operation to replace a narrow operation.
This only needs to handle operations that can evaluation to SCEVAddRec. It can safely return 0 for any operation we decide not to clone.
Definition at line 1183 of file SimplifyIndVar.cpp.
References llvm::MCID::Add, cloneArithmeticIVUser(), cloneBitwiseIVUser(), llvm::Instruction::getOpcode(), and WidenIV::NarrowIVDefUse::NarrowUse.
Referenced by widenIVUse().
createExtendInst()
Value * WidenIV::createExtendInst (Value * NarrowOper, Type * WideType, bool IsSigned, Instruction * Use) protected
Definition at line 1166 of file SimplifyIndVar.cpp.
References Builder, llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), llvm::BasicBlock::getTerminator(), and llvm::Loop::isLoopInvariant().
Referenced by cloneArithmeticIVUser(), cloneBitwiseIVUser(), widenLoopCompare(), and widenWithVariantUse().
createWideIV()
PHINode * WidenIV::createWideIV (SCEVExpander & Rewriter)
Process a single induction variable.
First use the SCEVExpander to create a wide induction variable that evaluates to the same recurrence as the original narrow IV. Then use a worklist to forward traverse the narrow IV's def-use chain. After widenIVUse has processed all interesting IV users, the narrow IV will be isolated for removal by DeleteDeadPHIs.
It would be simpler to delete uses as they are processed, but we must avoid invalidating SCEV expressions.
Definition at line 1867 of file SimplifyIndVar.cpp.
References assert(), llvm::dbgs(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallPtrSetImplBase::empty(), llvm::ScalarEvolution::getEffectiveSCEVType(), getExtendKind(), llvm::BasicBlock::getFirstInsertionPt(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::PHINode::getIncomingValueForBlock(), llvm::SCEVAddRecExpr::getLoop(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::ScalarEvolution::getSCEV(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::SCEVAddRecExpr::getStart(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::SCEV::getType(), llvm::ScalarEvolution::getZeroExtendExpr(), llvm::Value::hasNUses(), llvm::SmallPtrSetImpl< PtrType >::insert(), LLVM_DEBUG, WidenIV::NarrowIVDefUse::NarrowDef, WidenIV::NarrowIVDefUse::NarrowUse, llvm::ScalarEvolution::properlyDominates(), pushNarrowIVUsers(), llvm::replaceAllDbgUsesWith(), Rewriter, llvm::Instruction::setDebugLoc(), llvm::Value::use_empty(), and widenIVUse().
Referenced by llvm::createWideIV().
getExtendedOperandRecurrence()
WidenIV::WidenedRecTy WidenIV::getExtendedOperandRecurrence (WidenIV::NarrowIVDefUse DU) protected
No-wrap operations can transfer sign extension of their result to their operands.
Generate the SCEV value for the widened operation without actually modifying the IR yet. If the expression after extending the operands is an AddRec for this loop, return the AddRec and the kind of extension used.
Definition at line 1335 of file SimplifyIndVar.cpp.
References llvm::MCID::Add, assert(), getExtendKind(), llvm::SCEVAddRecExpr::getLoop(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::ScalarEvolution::getSCEV(), getSCEVByOpCode(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::ScalarEvolution::getZeroExtendExpr(), llvm::OverflowingBinaryOperator::hasNoSignedWrap(), llvm::OverflowingBinaryOperator::hasNoUnsignedWrap(), WidenIV::NarrowIVDefUse::NarrowDef, WidenIV::NarrowIVDefUse::NarrowUse, std::swap(), and WidenIV::NarrowIVDefUse::WideDef.
Referenced by widenIVUse().
getExtendKind()
WidenIV::ExtendKind WidenIV::getExtendKind (Instruction * I) protected
Definition at line 1307 of file SimplifyIndVar.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and I.
Referenced by cloneArithmeticIVUser(), cloneBitwiseIVUser(), createWideIV(), getExtendedOperandRecurrence(), getWideRecurrence(), widenIVUse(), widenLoopCompare(), and widenWithVariantUse().
getNumElimExt()
unsigned WidenIV::getNumElimExt () inline
Definition at line 1069 of file SimplifyIndVar.cpp.
Referenced by llvm::createWideIV().
getNumWidened()
unsigned WidenIV::getNumWidened () inline
Definition at line 1070 of file SimplifyIndVar.cpp.
Referenced by llvm::createWideIV().
getSCEVByOpCode()
const SCEV * WidenIV::getSCEVByOpCode (const SCEV * LHS, const SCEV * RHS, unsigned OpCode) const protected
Definition at line 1313 of file SimplifyIndVar.cpp.
References llvm::MCID::Add, llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getMinusSCEV(), llvm::ScalarEvolution::getMulExpr(), llvm::ScalarEvolution::getUDivExpr(), and llvm_unreachable.
Referenced by cloneArithmeticIVUser(), and getExtendedOperandRecurrence().
getWideRecurrence()
WidenIV::WidenedRecTy WidenIV::getWideRecurrence (WidenIV::NarrowIVDefUse DU) protected
Is this instruction potentially interesting for further simplification after widening it's type? In other words, can the extend be safely hoisted out of the loop with SCEV reducing the value to a recurrence on the same loop.
If so, return the extended recurrence and the kind of extension used. Otherwise return {nullptr, Unknown}.
Definition at line 1388 of file SimplifyIndVar.cpp.
References getExtendKind(), llvm::SCEVAddRecExpr::getLoop(), llvm::ScalarEvolution::getSCEV(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::SCEV::getType(), llvm::Value::getType(), llvm::ScalarEvolution::getTypeSizeInBits(), llvm::ScalarEvolution::getZeroExtendExpr(), llvm::ScalarEvolution::isSCEVable(), WidenIV::NarrowIVDefUse::NarrowDef, WidenIV::NarrowIVDefUse::NarrowUse, and WidenIV::NarrowIVDefUse::NeverNegative.
Referenced by widenIVUse().
pushNarrowIVUsers()
void WidenIV::pushNarrowIVUsers (Instruction * NarrowDef, Instruction * WideDef) protected
Add eligible users of NarrowDef to NarrowIVUsers.
Definition at line 1835 of file SimplifyIndVar.cpp.
References llvm::ScalarEvolution::getSCEV(), llvm::SCEV::getType(), llvm::ScalarEvolution::getZero(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::ScalarEvolution::isKnownPredicate(), and llvm::Value::users().
Referenced by createWideIV().
widenIVUse()
Instruction * WidenIV::widenIVUse (WidenIV::NarrowIVDefUse DU, SCEVExpander & Rewriter) protected
Determine whether an individual user of the narrow IV can be widened.
If so, return the wide clone of the user.
Definition at line 1687 of file SimplifyIndVar.cpp.
References llvm::PHINode::addIncoming(), assert(), Builder, cloneIVUser(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), llvm::dbgs(), llvm::SmallVectorImpl< T >::emplace_back(), getExtendedOperandRecurrence(), getExtendKind(), llvm::BasicBlock::getFirstInsertionPt(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::Instruction::getParent(), llvm::ScalarEvolution::getSCEV(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::ScalarEvolution::getTypeSizeInBits(), getWideRecurrence(), LLVM_DEBUG, WidenIV::NarrowIVDefUse::NarrowDef, WidenIV::NarrowIVDefUse::NarrowUse, WidenIV::NarrowIVDefUse::NeverNegative, llvm::replaceAllDbgUsesWith(), llvm::Value::replaceAllUsesWith(), llvm::User::replaceUsesOfWith(), Rewriter, truncateIVUse(), WidenIV::NarrowIVDefUse::WideDef, widenLoopCompare(), and widenWithVariantUse().
Referenced by createWideIV().
widenLoopCompare()
bool WidenIV::widenLoopCompare (WidenIV::NarrowIVDefUse DU) protected
If the narrow use is a compare instruction, then widen the compare.
Definition at line 1440 of file SimplifyIndVar.cpp.
References assert(), Builder, createExtendInst(), getExtendKind(), getInsertPointForUses(), llvm::ScalarEvolution::getTypeSizeInBits(), WidenIV::NarrowIVDefUse::NarrowDef, WidenIV::NarrowIVDefUse::NarrowUse, WidenIV::NarrowIVDefUse::NeverNegative, llvm::User::replaceUsesOfWith(), and WidenIV::NarrowIVDefUse::WideDef.
Referenced by widenIVUse().
widenWithVariantUse()
bool WidenIV::widenWithVariantUse (WidenIV::NarrowIVDefUse DU) protected
Definition at line 1503 of file SimplifyIndVar.cpp.
References llvm::MCID::Add, assert(), Builder, llvm::LoopBase< BlockT, LoopT >::contains(), Context, createExtendInst(), llvm::dbgs(), llvm::DominatorTree::dominates(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorBase< Size_T >::empty(), llvm::MipsISD::Ext, llvm::DominatorTreeBase< NodeT, IsPostDom >::findNearestCommonDominator(), getExtendKind(), llvm::SCEVAddRecExpr::getLoop(), llvm::Value::getName(), llvm::ScalarEvolution::getNegativeSCEV(), llvm::User::getNumOperands(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::ScalarEvolution::getSCEV(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::OverflowingBinaryOperator::hasNoSignedWrap(), llvm::OverflowingBinaryOperator::hasNoUnsignedWrap(), llvm::ScalarEvolution::isKnownNegative(), llvm::ScalarEvolution::isKnownPredicateAt(), LLVM_DEBUG, WidenIV::NarrowIVDefUse::NarrowDef, WidenIV::NarrowIVDefUse::NarrowUse, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::Value::uses(), and WidenIV::NarrowIVDefUse::WideDef.
Referenced by widenIVUse().
The documentation for this class was generated from the following file:
lib/Transforms/Utils/SimplifyIndVar.cpp