LLVM: llvm::IRBuilderDefaultInserter Class Reference
llvm::IRBuilderDefaultInserter Class Reference
This provides the default implementation of the IRBuilder 'InsertHelper' method that is called whenever an instruction is created by IRBuilder and needs to be inserted.
#include "llvm/IR/IRBuilder.h"
Public Member Functions
virtual ~IRBuilderDefaultInserter ()
virtual void InsertHelper (Instruction *I, const Twine &Name, BasicBlock *BB, BasicBlock::iterator InsertPt) const
Detailed Description
This provides the default implementation of the IRBuilder 'InsertHelper' method that is called whenever an instruction is created by IRBuilder and needs to be inserted.
By default, this inserts the instruction at the insertion point.
Definition at line 63 of file IRBuilder.h.
Constructor & Destructor Documentation
~IRBuilderDefaultInserter()
IRBuilderDefaultInserter::~IRBuilderDefaultInserter () virtual
Definition at line 1146 of file IRBuilder.cpp.
Member Function Documentation
InsertHelper()
virtual void llvm::IRBuilderDefaultInserter::InsertHelper (Instruction * I, const Twine & Name, BasicBlock * BB, BasicBlock::iterator InsertPt) const inline virtual
Reimplemented in llvm::IRBuilderCallbackInserter.
Definition at line 67 of file IRBuilder.h.
References llvm::BasicBlock::getInstList(), I, and llvm::iplist_impl< IntrusiveListT, TraitsT >::insert().
Referenced by llvm::IRBuilderBase::Insert(), and llvm::IRBuilderCallbackInserter::InsertHelper().
The documentation for this class was generated from the following files:
include/llvm/IR/IRBuilder.h
lib/IR/IRBuilder.cpp