LLVM: llvm::IntrinsicCostAttributes Class Reference
llvm::IntrinsicCostAttributes Class Reference
#include "llvm/Analysis/TargetTransformInfo.h"
Public Member Functions
IntrinsicCostAttributes (const IntrinsicInst &I)
IntrinsicCostAttributes (Intrinsic::ID Id, const CallBase &CI)
IntrinsicCostAttributes (Intrinsic::ID Id, const CallBase &CI, ElementCount Factor)
IntrinsicCostAttributes (Intrinsic::ID Id, const CallBase &CI, ElementCount Factor, unsigned ScalarCost)
IntrinsicCostAttributes (Intrinsic::ID Id, Type *RTy, ArrayRef< Type * > Tys, FastMathFlags Flags)
IntrinsicCostAttributes (Intrinsic::ID Id, Type *RTy, ArrayRef< Type * > Tys, FastMathFlags Flags, unsigned ScalarCost)
IntrinsicCostAttributes (Intrinsic::ID Id, Type *RTy, ArrayRef< Type * > Tys, FastMathFlags Flags, unsigned ScalarCost, const IntrinsicInst *I)
IntrinsicCostAttributes (Intrinsic::ID Id, Type *RTy, ArrayRef< Type * > Tys)
IntrinsicCostAttributes (Intrinsic::ID Id, Type *RTy, ArrayRef< const Value * > Args)
Intrinsic::ID getID () const
const IntrinsicInst * getInst () const
Type * getReturnType () const
ElementCount getVectorFactor () const
FastMathFlags getFlags () const
unsigned getScalarizationCost () const
const SmallVectorImpl< const Value * > & getArgs () const
const SmallVectorImpl< Type * > & getArgTypes () const
bool isTypeBasedOnly () const
bool skipScalarizationCost () const
Detailed Description
Definition at line 114 of file TargetTransformInfo.h.
Constructor & Destructor Documentation
IntrinsicCostAttributes() [1/9]
IntrinsicCostAttributes::IntrinsicCostAttributes (const IntrinsicInst & I)
Definition at line 57 of file TargetTransformInfo.cpp.
References I, llvm::FunctionType::param_begin(), and llvm::FunctionType::param_end().
IntrinsicCostAttributes() [2/9]
IntrinsicCostAttributes::IntrinsicCostAttributes (Intrinsic::ID Id, const CallBase & CI)
Definition at line 67 of file TargetTransformInfo.cpp.
References llvm::CallBase::arg_begin(), llvm::CallBase::arg_end(), llvm::CallBase::getCalledFunction(), llvm::Function::getFunctionType(), llvm::FunctionType::param_begin(), and llvm::FunctionType::param_end().
IntrinsicCostAttributes() [3/9]
IntrinsicCostAttributes::IntrinsicCostAttributes (Intrinsic::ID Id, const CallBase & CI, ElementCount Factor)
Definition at line 80 of file TargetTransformInfo.cpp.
References llvm::CallBase::arg_begin(), llvm::CallBase::arg_end(), assert(), llvm::CallBase::getCalledFunction(), llvm::Function::getFunctionType(), llvm::LinearPolySize< LeafTy >::isScalable(), llvm::FunctionType::param_begin(), and llvm::FunctionType::param_end().
IntrinsicCostAttributes() [4/9]
IntrinsicCostAttributes::IntrinsicCostAttributes (Intrinsic::ID Id, const CallBase & CI, ElementCount Factor, unsigned ScalarCost)
Definition at line 95 of file TargetTransformInfo.cpp.
References llvm::CallBase::arg_begin(), llvm::CallBase::arg_end(), llvm::CallBase::getCalledFunction(), llvm::Function::getFunctionType(), llvm::FunctionType::param_begin(), and llvm::FunctionType::param_end().
IntrinsicCostAttributes() [5/9]
IntrinsicCostAttributes::IntrinsicCostAttributes (Intrinsic::ID Id, Type * RTy, ArrayRef< Type * > Tys, FastMathFlags Flags)
Definition at line 110 of file TargetTransformInfo.cpp.
References llvm::ArrayRef< T >::begin(), and llvm::ArrayRef< T >::end().
IntrinsicCostAttributes() [6/9]
IntrinsicCostAttributes::IntrinsicCostAttributes (Intrinsic::ID Id, Type * RTy, ArrayRef< Type * > Tys, FastMathFlags Flags, unsigned ScalarCost)
Definition at line 117 of file TargetTransformInfo.cpp.
References llvm::ArrayRef< T >::begin(), and llvm::ArrayRef< T >::end().
IntrinsicCostAttributes() [7/9]
IntrinsicCostAttributes::IntrinsicCostAttributes (Intrinsic::ID Id, Type * RTy, ArrayRef< Type * > Tys, FastMathFlags Flags, unsigned ScalarCost, const IntrinsicInst * I)
Definition at line 125 of file TargetTransformInfo.cpp.
References llvm::ArrayRef< T >::begin(), and llvm::ArrayRef< T >::end().
IntrinsicCostAttributes() [8/9]
IntrinsicCostAttributes::IntrinsicCostAttributes (Intrinsic::ID Id, Type * RTy, ArrayRef< Type * > Tys)
Definition at line 134 of file TargetTransformInfo.cpp.
References llvm::ArrayRef< T >::begin(), and llvm::ArrayRef< T >::end().
IntrinsicCostAttributes() [9/9]
IntrinsicCostAttributes::IntrinsicCostAttributes (Intrinsic::ID Id, Type * RTy, ArrayRef< const Value * > Args)
Definition at line 140 of file TargetTransformInfo.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, getType(), and llvm::Check::Size.
Member Function Documentation
getArgs()
const SmallVectorImpl<const Value *>& llvm::IntrinsicCostAttributes::getArgs () const inline
Definition at line 161 of file TargetTransformInfo.h.
References Arguments.
Referenced by llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), llvm::GCNTTIImpl::getIntrinsicInstrCost(), and llvm::X86TTIImpl::getIntrinsicInstrCost().
getArgTypes()
const SmallVectorImpl<Type *>& llvm::IntrinsicCostAttributes::getArgTypes () const inline
Definition at line 162 of file TargetTransformInfo.h.
Referenced by llvm::BasicTTIImplBase< T >::getTypeBasedIntrinsicInstrCost().
getFlags()
FastMathFlags llvm::IntrinsicCostAttributes::getFlags () const inline
Definition at line 159 of file TargetTransformInfo.h.
Referenced by llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), llvm::GCNTTIImpl::getIntrinsicInstrCost(), and llvm::BasicTTIImplBase< T >::getTypeBasedIntrinsicInstrCost().
getID()
Intrinsic::ID llvm::IntrinsicCostAttributes::getID () const inline
Definition at line 155 of file TargetTransformInfo.h.
Referenced by llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), llvm::AArch64TTIImpl::getIntrinsicInstrCost(), llvm::GCNTTIImpl::getIntrinsicInstrCost(), llvm::ARMTTIImpl::getIntrinsicInstrCost(), llvm::HexagonTTIImpl::getIntrinsicInstrCost(), llvm::SystemZTTIImpl::getIntrinsicInstrCost(), llvm::X86TTIImpl::getIntrinsicInstrCost(), llvm::TargetTransformInfoImplBase::getIntrinsicInstrCost(), llvm::BasicTTIImplBase< T >::getTypeBasedIntrinsicInstrCost(), and llvm::X86TTIImpl::getTypeBasedIntrinsicInstrCost().
getInst()
const IntrinsicInst* llvm::IntrinsicCostAttributes::getInst () const inline
Definition at line 156 of file TargetTransformInfo.h.
Referenced by llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), and llvm::GCNTTIImpl::getIntrinsicInstrCost().
getReturnType()
Type* llvm::IntrinsicCostAttributes::getReturnType () const inline
Definition at line 157 of file TargetTransformInfo.h.
Referenced by llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), llvm::AArch64TTIImpl::getIntrinsicInstrCost(), llvm::GCNTTIImpl::getIntrinsicInstrCost(), llvm::ARMTTIImpl::getIntrinsicInstrCost(), llvm::HexagonTTIImpl::getIntrinsicInstrCost(), llvm::SystemZTTIImpl::getIntrinsicInstrCost(), llvm::X86TTIImpl::getIntrinsicInstrCost(), llvm::BasicTTIImplBase< T >::getTypeBasedIntrinsicInstrCost(), and llvm::X86TTIImpl::getTypeBasedIntrinsicInstrCost().
getScalarizationCost()
unsigned llvm::IntrinsicCostAttributes::getScalarizationCost () const inline
Definition at line 160 of file TargetTransformInfo.h.
Referenced by llvm::BasicTTIImplBase< T >::getTypeBasedIntrinsicInstrCost().
getVectorFactor()
ElementCount llvm::IntrinsicCostAttributes::getVectorFactor () const inline
Definition at line 158 of file TargetTransformInfo.h.
Referenced by llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), llvm::GCNTTIImpl::getIntrinsicInstrCost(), and llvm::ARMTTIImpl::getIntrinsicInstrCost().
isTypeBasedOnly()
bool llvm::IntrinsicCostAttributes::isTypeBasedOnly () const inline
Definition at line 164 of file TargetTransformInfo.h.
References Arguments.
Referenced by llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), llvm::GCNTTIImpl::getIntrinsicInstrCost(), and llvm::X86TTIImpl::getIntrinsicInstrCost().
skipScalarizationCost()
bool llvm::IntrinsicCostAttributes::skipScalarizationCost () const inline
Definition at line 168 of file TargetTransformInfo.h.
References llvm::max().
Referenced by llvm::BasicTTIImplBase< T >::getTypeBasedIntrinsicInstrCost().
The documentation for this class was generated from the following files:
include/llvm/Analysis/TargetTransformInfo.h
lib/Analysis/TargetTransformInfo.cpp