LLVM: llvm::orc::MachOJITDylibInitializers Class Reference
llvm::orc::MachOJITDylibInitializers Class Reference
#include "llvm/ExecutionEngine/Orc/MachOPlatform.h"
Classes
struct SectionExtent
Public Types
using RawPointerSectionList = std::vector< SectionExtent >
Public Member Functions
void setObjCImageInfoAddr (JITTargetAddress ObjCImageInfoAddr)
void addModInitsSection (SectionExtent ModInit)
const RawPointerSectionList & getModInitsSections () const
void addObjCSelRefsSection (SectionExtent ObjCSelRefs)
const RawPointerSectionList & getObjCSelRefsSections () const
void addObjCClassListSection (SectionExtent ObjCClassList)
const RawPointerSectionList & getObjCClassListSections () const
void runModInits () const
void registerObjCSelectors () const
Error registerObjCClasses () const
Detailed Description
Definition at line 32 of file MachOPlatform.h.
Member Typedef Documentation
RawPointerSectionList
using llvm::orc::MachOJITDylibInitializers::RawPointerSectionList = std::vector<SectionExtent>
Definition at line 42 of file MachOPlatform.h.
Member Function Documentation
addModInitsSection()
void llvm::orc::MachOJITDylibInitializers::addModInitsSection (SectionExtent ModInit) inline
Definition at line 48 of file MachOPlatform.h.
References llvm::move().
addObjCClassListSection()
void llvm::orc::MachOJITDylibInitializers::addObjCClassListSection (SectionExtent ObjCClassList) inline
Definition at line 64 of file MachOPlatform.h.
References llvm::move().
addObjCSelRefsSection()
void llvm::orc::MachOJITDylibInitializers::addObjCSelRefsSection (SectionExtent ObjCSelRefs) inline
Definition at line 56 of file MachOPlatform.h.
References llvm::move().
getModInitsSections()
const RawPointerSectionList& llvm::orc::MachOJITDylibInitializers::getModInitsSections () const inline
Definition at line 52 of file MachOPlatform.h.
getObjCClassListSections()
const RawPointerSectionList& llvm::orc::MachOJITDylibInitializers::getObjCClassListSections () const inline
Definition at line 68 of file MachOPlatform.h.
getObjCSelRefsSections()
const RawPointerSectionList& llvm::orc::MachOJITDylibInitializers::getObjCSelRefsSections () const inline
Definition at line 60 of file MachOPlatform.h.
registerObjCClasses()
Error llvm::orc::MachOJITDylibInitializers::registerObjCClasses () const
Definition at line 115 of file MachOPlatform.cpp.
References assert(), llvm::Data, I, llvm::inconvertibleErrorCode(), llvm::orc::objCRegistrationEnabled(), and llvm::Error::success().
registerObjCSelectors()
void llvm::orc::MachOJITDylibInitializers::registerObjCSelectors () const
Definition at line 101 of file MachOPlatform.cpp.
References assert(), I, and llvm::orc::objCRegistrationEnabled().
runModInits()
void llvm::orc::MachOJITDylibInitializers::runModInits () const
Definition at line 89 of file MachOPlatform.cpp.
References I.
setObjCImageInfoAddr()
void llvm::orc::MachOJITDylibInitializers::setObjCImageInfoAddr (JITTargetAddress ObjCImageInfoAddr) inline
Definition at line 44 of file MachOPlatform.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/MachOPlatform.h
lib/ExecutionEngine/Orc/MachOPlatform.cpp