LLVM: llvm::InnerLoopVectorizer Class Reference
llvm::InnerLoopVectorizer Class Reference
InnerLoopVectorizer vectorizes loops which contain only one basic block to a specified vectorization factor (VF).
Public Types
using VectorParts = SmallVector< Value *, 2 >
A type for vectorized values in the new loop.
Public Member Functions
InnerLoopVectorizer (Loop *OrigLoop, PredicatedScalarEvolution &PSE, LoopInfo *LI, DominatorTree *DT, const TargetLibraryInfo *TLI, const TargetTransformInfo *TTI, AssumptionCache *AC, OptimizationRemarkEmitter *ORE, ElementCount VecWidth, unsigned UnrollFactor, LoopVectorizationLegality *LVL, LoopVectorizationCostModel *CM, BlockFrequencyInfo *BFI, ProfileSummaryInfo *PSI)
virtual ~InnerLoopVectorizer ()=default
virtual BasicBlock * createVectorizedLoopSkeleton ()
Create a new empty loop that will contain vectorized instructions later on, while the old loop will be used as the scalar remainder.
void widenInstruction (Instruction &I, VPValue *Def, VPUser &Operands, VPTransformState &State)
Widen a single instruction within the innermost loop.
void widenCallInstruction (CallInst &I, VPValue *Def, VPUser &ArgOperands, VPTransformState &State)
Widen a single call instruction within the innermost loop.
void widenSelectInstruction (SelectInst &I, VPValue *VPDef, VPUser &Operands, bool InvariantCond, VPTransformState &State)
Widen a single select instruction within the innermost loop.
void fixVectorizedLoop ()
Fix the vectorized code, taking care of header phi's, live-outs, and more.
bool areSafetyChecksAdded ()
void widenGEP (GetElementPtrInst *GEP, VPValue *VPDef, VPUser &Indices, unsigned UF, ElementCount VF, bool IsPtrLoopInvariant, SmallBitVector &IsIndexLoopInvariant, VPTransformState &State)
Vectorize a single GetElementPtrInst based on information gathered and decisions taken during planning.
void widenPHIInstruction (Instruction *PN, RecurrenceDescriptor *RdxDesc, Value *StartV, unsigned UF, ElementCount VF)
Vectorize a single PHINode in a block.
void scalarizeInstruction (Instruction *Instr, VPUser &Operands, const VPIteration &Instance, bool IfPredicateInstr, VPTransformState &State)
A helper function to scalarize a single Instruction in the innermost loop.
void widenIntOrFpInduction (PHINode *IV, Value *Start, TruncInst *Trunc=nullptr)
Widen an integer or floating-point induction variable IV.
Value * getOrCreateVectorValue (Value *V, unsigned Part)
getOrCreateVectorValue and getOrCreateScalarValue coordinate to generate a vector or scalar value on-demand if one is not yet available.
void setVectorValue (Value *Scalar, unsigned Part, Value *Vector)
Value * getOrCreateScalarValue (Value *V, const VPIteration &Instance)
Return a value in the new loop corresponding to V from the original loop at unroll and vector indices Instance.
void packScalarIntoVectorValue (Value *V, const VPIteration &Instance)
Construct the vector value of a scalarized value V one lane at a time.
void vectorizeInterleaveGroup (const InterleaveGroup< Instruction > *Group, ArrayRef< VPValue * > VPDefs, VPTransformState &State, VPValue *Addr, ArrayRef< VPValue * > StoredValues, VPValue *BlockInMask=nullptr)
Try to vectorize interleaved access group Group with the base address given in Addr, optionally masking the vector operations if BlockInMask is non-null.
void vectorizeMemoryInstruction (Instruction *Instr, VPTransformState &State, VPValue *Def, VPValue *Addr, VPValue *StoredValue, VPValue *BlockInMask)
Vectorize Load and Store instructions with the base address given in Addr, optionally masking the vector operations if BlockInMask is non-null.
void setDebugLocFromInst (IRBuilder<> &B, const Value *Ptr)
Set the debug location in the builder using the debug location in the instruction.
void fixNonInductionPHIs (void)
Fix the non-induction PHIs in the OrigPHIsToFix vector.
Protected Types
using PhiVector = SmallVector< PHINode *, 4 >
A small list of PHINodes.
using ScalarParts = SmallVector< SmallVector< Value *, 4 >, 2 >
A type for scalarized values in the new loop.
Protected Member Functions
void fixupIVUsers (PHINode *OrigPhi, const InductionDescriptor &II, Value *CountRoundDown, Value *EndValue, BasicBlock *MiddleBlock)
Set up the values of the IVs correctly when exiting the vector loop.
PHINode * createInductionVariable (Loop *L, Value *Start, Value *End, Value *Step, Instruction *DL)
Create a new induction variable inside L.
void fixCrossIterationPHIs ()
Handle all cross-iteration phis in the header.
void fixFirstOrderRecurrence (PHINode *Phi)
Fix a first-order recurrence.
void fixReduction (PHINode *Phi)
Fix a reduction cross-iteration phi.
void clearReductionWrapFlags (RecurrenceDescriptor &RdxDesc)
Clear NSW/NUW flags from reduction instructions if necessary.
void fixLCSSAPHIs ()
Fixup the LCSSA phi nodes in the unique exit block.
void sinkScalarOperands (Instruction *PredInst)
Iteratively sink the scalarized operands of a predicated instruction into the block that was created for it.
void truncateToMinimalBitwidths ()
Shrinks vector element sizes to the smallest bitwidth they can be legally represented as.
virtual Value * getBroadcastInstrs (Value *V)
Create a broadcast instruction.
virtual Value * getStepVector (Value *Val, int StartIdx, Value *Step, Instruction::BinaryOps Opcode=Instruction::BinaryOpsEnd)
This function adds (StartIdx, StartIdx + Step, StartIdx + 2*Step, ...) to each vector element of Val.
void buildScalarSteps (Value *ScalarIV, Value *Step, Instruction *EntryVal, const InductionDescriptor &ID)
Compute scalar induction steps.
void createVectorIntOrFpInductionPHI (const InductionDescriptor &II, Value *Step, Value *Start, Instruction *EntryVal)
Create a vector induction phi node based on an existing scalar one.
bool shouldScalarizeInstruction (Instruction *I) const
Returns true if an instruction I should be scalarized instead of vectorized for the chosen vectorization factor.
bool needsScalarInduction (Instruction *IV) const
Returns true if we should generate a scalar version of IV.
void recordVectorLoopValueForInductionCast (const InductionDescriptor &ID, const Instruction *EntryVal, Value *VectorLoopValue, unsigned Part, unsigned Lane=UINT_MAX)
If there is a cast involved in the induction variable ID, which should be ignored in the vectorized loop body, this function records the VectorLoopValue of the respective Phi also as the VectorLoopValue of the cast.
virtual Value * reverseVector (Value *Vec)
Generate a shuffle sequence that will reverse the vector Vec.
Value * getOrCreateTripCount (Loop *NewLoop)
Returns (and creates if needed) the original loop trip count.
Value * getOrCreateVectorTripCount (Loop *NewLoop)
Returns (and creates if needed) the trip count of the widened loop.
Value * createBitOrPointerCast (Value *V, VectorType *DstVTy, const DataLayout &DL)
Returns a bitcasted value to the requested vector type.
void emitMinimumIterationCountCheck (Loop *L, BasicBlock *Bypass)
Emit a bypass check to see if the vector trip count is zero, including if it overflows.
void emitSCEVChecks (Loop *L, BasicBlock *Bypass)
Emit a bypass check to see if all of the SCEV assumptions we've had to make are correct.
void emitMemRuntimeChecks (Loop *L, BasicBlock *Bypass)
Emit bypass checks to check any memory assumptions we may have made.
Value * emitTransformedIndex (IRBuilder<> &B, Value *Index, ScalarEvolution *SE, const DataLayout &DL, const InductionDescriptor &ID) const
Compute the transformed value of Index at offset StartValue using step StepValue.
Loop * createVectorLoopSkeleton (StringRef Prefix)
Emit basic blocks (prefixed with Prefix) for the iteration check, vector loop preheader, middle block and scalar preheader.
void createInductionResumeValues (Loop *L, Value *VectorTripCount, std::pair< BasicBlock *, Value * > AdditionalBypass={nullptr, nullptr})
Create new phi nodes for the induction variables to resume iteration count in the scalar epilogue, from where the vectorized loop left off (given by VectorTripCount).
BasicBlock * completeLoopSkeleton (Loop *L, MDNode *OrigLoopID)
Complete the loop skeleton by adding debug MDs, creating appropriate conditional branches in the middle block, preparing the builder and running the verifier.
void addNewMetadata (Instruction *To, const Instruction *Orig)
Add additional metadata to To that was not present on Orig.
void addMetadata (Instruction *To, Instruction *From)
Add metadata from one instruction to another.
void addMetadata (ArrayRef< Value * > To, Instruction *From)
Similar to the previous function but it adds the metadata to a vector of instructions.
virtual void printDebugTracesAtStart ()
Allow subclasses to override and print debug traces before/after vplan execution, when trace information is requested.
virtual void printDebugTracesAtEnd ()
Protected Attributes
Loop * OrigLoop
The original loop.
PredicatedScalarEvolution & PSE
A wrapper around ScalarEvolution used to add runtime SCEV checks.
LoopInfo * LI
Loop Info.
DominatorTree * DT
Dominator Tree.
AAResults * AA
Alias Analysis.
const TargetLibraryInfo * TLI
Target Library Info.
const TargetTransformInfo * TTI
Target Transform Info.
AssumptionCache * AC
Assumption Cache.
OptimizationRemarkEmitter * ORE
Interface to emit optimization remarks.
std::unique_ptr< LoopVersioning > LVer
LoopVersioning.
ElementCount VF
The vectorization SIMD factor to use.
unsigned UF
The vectorization unroll factor to use.
IRBuilder Builder
The builder that we use.
BasicBlock * LoopVectorPreHeader
The vector-loop preheader.
BasicBlock * LoopScalarPreHeader
The scalar-loop preheader.
BasicBlock * LoopMiddleBlock
Middle Block between the vector and the scalar.
BasicBlock * LoopExitBlock
The (unique) ExitBlock of the scalar loop.
BasicBlock * LoopVectorBody
The vector loop body.
BasicBlock * LoopScalarBody
The scalar loop body.
SmallVector< BasicBlock *, 4 > LoopBypassBlocks
A list of all bypass blocks. The first block is the entry of the loop.
PHINode * Induction = nullptr
The new Induction variable which was added to the new block.
PHINode * OldInduction = nullptr
The induction variable of the old basic block.
VectorizerValueMap VectorLoopValueMap
Maps values from the original loop to their corresponding values in the vectorized loop.
SmallVector< Instruction *, 4 > PredicatedInstructions
Store instructions that were predicated.
Value * TripCount = nullptr
Trip count of the original loop.
Value * VectorTripCount = nullptr
Trip count of the widened loop (TripCount - TripCount % (VF*UF))
LoopVectorizationLegality * Legal
The legality analysis.
LoopVectorizationCostModel * Cost
The profitablity analysis.
bool AddedSafetyChecks = false
DenseMap< PHINode *, Value * > IVEndValues
SmallVector< PHINode *, 8 > OrigPHIsToFix
BlockFrequencyInfo * BFI
BFI and PSI are used to check for profile guided size optimizations.
ProfileSummaryInfo * PSI
bool OptForSizeBasedOnProfile
Friends
class LoopVectorizationPlanner
Detailed Description
InnerLoopVectorizer vectorizes loops which contain only one basic block to a specified vectorization factor (VF).
This class performs the widening of scalars into vectors, or multiple scalars. This class also implements the following features:
It inserts an epilogue loop for handling loops that don't have iteration counts that are known to be a multiple of the vectorization factor.
It handles the code generation for reduction variables.
Scalarization (implementation using scalars) of un-vectorizable instructions. InnerLoopVectorizer does not perform any vectorization-legality checks, and relies on the caller to check for the different legality aspects. The InnerLoopVectorizer relies on the LoopVectorizationLegality class to provide information about the induction and reduction variables that were found to a given vectorization factor.
Definition at line 450 of file LoopVectorize.cpp.
Member Typedef Documentation
PhiVector
using llvm::InnerLoopVectorizer::PhiVector = SmallVector<PHINode *, 4> protected
A small list of PHINodes.
Definition at line 597 of file LoopVectorize.cpp.
ScalarParts
using llvm::InnerLoopVectorizer::ScalarParts = SmallVector<SmallVector<Value *, 4>, 2> protected
A type for scalarized values in the new loop.
Each value from the original loop, when scalarized, is represented by UF x VF scalar values in the new unrolled loop, where UF is the unroll factor and VF is the vectorization factor.
Definition at line 603 of file LoopVectorize.cpp.
VectorParts
using llvm::InnerLoopVectorizer::VectorParts = SmallVector<Value *, 2>
A type for vectorized values in the new loop.
Each value from the original loop, when vectorized, is represented by UF vector values in the new unrolled loop, where UF is the unroll factor.
Definition at line 503 of file LoopVectorize.cpp.
Constructor & Destructor Documentation
InnerLoopVectorizer()
llvm::InnerLoopVectorizer::InnerLoopVectorizer (Loop * OrigLoop, PredicatedScalarEvolution & PSE, LoopInfo * LI, DominatorTree * DT, const TargetLibraryInfo * TLI, const TargetTransformInfo * TTI, AssumptionCache * AC, OptimizationRemarkEmitter * ORE, ElementCount VecWidth, unsigned UnrollFactor, LoopVectorizationLegality * LVL, LoopVectorizationCostModel * CM, BlockFrequencyInfo * BFI, ProfileSummaryInfo * PSI) inline
Definition at line 452 of file LoopVectorize.cpp.
References BFI, llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::IRPass, OptForSizeBasedOnProfile, OrigLoop, PSI, and llvm::shouldOptimizeForSize().
~InnerLoopVectorizer()
virtual llvm::InnerLoopVectorizer::~InnerLoopVectorizer () virtual default
Member Function Documentation
addMetadata() [1/2]
void InnerLoopVectorizer::addMetadata (ArrayRef< Value * > To, Instruction * From) protected
Similar to the previous function but it adds the metadata to a vector of instructions.
Definition at line 1182 of file LoopVectorize.cpp.
References addMetadata(), From, and I.
addMetadata() [2/2]
void InnerLoopVectorizer::addMetadata (Instruction * To, Instruction * From) protected
Add metadata from one instruction to another.
This includes both the original MDs from From and additional ones (
See also
addNewMetadata). Use this for newly created instructions in the vector loop.
Definition at line 1176 of file LoopVectorize.cpp.
References addNewMetadata(), From, and llvm::propagateMetadata().
Referenced by addMetadata(), vectorizeMemoryInstruction(), widenCallInstruction(), widenGEP(), widenInstruction(), and widenSelectInstruction().
addNewMetadata()
void InnerLoopVectorizer::addNewMetadata (Instruction * To, const Instruction * Orig) protected
Add additional metadata to To that was not present on Orig.
Currently this is used to add the noalias annotations based on the inserted memchecks. Use this for instructions that are cloned into the vector loop.
Definition at line 1168 of file LoopVectorize.cpp.
References LVer.
Referenced by addMetadata(), and scalarizeInstruction().
areSafetyChecksAdded()
bool llvm::InnerLoopVectorizer::areSafetyChecksAdded () inline
Definition at line 498 of file LoopVectorize.cpp.
References AddedSafetyChecks.
Referenced by llvm::LoopVectorizePass::processLoop().
buildScalarSteps()
void InnerLoopVectorizer::buildScalarSteps (Value * ScalarIV, Value * Step, Instruction * EntryVal, const InductionDescriptor & ID) protected
Compute scalar induction steps.
ScalarIV is the scalar induction variable on which to base the steps, Step is the size of the step, and EntryVal is the value from the original loop that maps to the steps. Note that EntryVal doesn't have to be an induction variable - it can also be a truncate instruction.
Definition at line 2312 of file LoopVectorize.cpp.
References llvm::MCID::Add, addFastMathFlag(), assert(), Builder, Cost, llvm::IRBuilderBase::CreateBinOp(), llvm::IRBuilderBase::CreateSIToFP(), createStepForVF(), llvm::IntegerType::get(), llvm::ConstantInt::get(), llvm::Type::getContext(), llvm::LinearPolySize< LeafTy >::getKnownMinValue(), llvm::Type::getScalarSizeInBits(), llvm::Type::getScalarType(), getSignedIntOrFpConstant(), llvm::Value::getType(), llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), llvm::LinearPolySize< LeafTy >::isScalable(), llvm::LoopVectorizationCostModel::isUniformAfterVectorization(), llvm::ElementCount::isVector(), llvm::Mul, recordVectorLoopValueForInductionCast(), llvm::VectorizerValueMap::setScalarValue(), UF, VectorLoopValueMap, and VF.
clearReductionWrapFlags()
void InnerLoopVectorizer::clearReductionWrapFlags (RecurrenceDescriptor & RdxDesc) protected
Clear NSW/NUW flags from reduction instructions if necessary.
Definition at line 4351 of file LoopVectorize.cpp.
References llvm::Add, assert(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::SmallVectorBase< Size_T >::empty(), llvm::RecurrenceDescriptor::getLoopExitInstr(), getOrCreateVectorValue(), llvm::Instruction::getParent(), llvm::RecurrenceDescriptor::getRecurrenceKind(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::Mul, OrigLoop, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), UF, and llvm::Value::users().
Referenced by fixReduction().
completeLoopSkeleton()
BasicBlock * InnerLoopVectorizer::completeLoopSkeleton (Loop * L, MDNode * OrigLoopID) protected
Complete the loop skeleton by adding debug MDs, creating appropriate conditional branches in the middle block, preparing the builder and running the verifier.
Take in the vector loop L as argument, and return the preheader of the completed vector loop.
Definition at line 3452 of file LoopVectorize.cpp.
References assert(), Builder, Cost, llvm::CmpInst::Create(), DT, llvm::CallingConv::Fast, llvm::LoopVectorizationCostModel::foldTailByMasking(), llvm::BasicBlock::getFirstInsertionPt(), llvm::Loop::getLoopID(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), getOrCreateTripCount(), getOrCreateVectorTripCount(), llvm::BasicBlock::getTerminator(), llvm::Optional< T >::getValue(), llvm::Optional< T >::hasValue(), llvm::CmpInst::ICMP_EQ, LI, LLVMLoopVectorizeFollowupAll, LLVMLoopVectorizeFollowupVectorized, LoopMiddleBlock, LoopVectorBody, LoopVectorPreHeader, llvm::makeFollowupLoopID(), ORE, OrigLoop, llvm::LoopVectorizeHints::setAlreadyVectorized(), llvm::Instruction::setDebugLoc(), llvm::IRBuilderBase::SetInsertPoint(), llvm::Loop::setLoopID(), VectorTripCount, llvm::LoopInfoBase< BlockT, LoopT >::verify(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::verify().
Referenced by llvm::EpilogueVectorizerMainLoop::createEpilogueVectorizedLoopSkeleton(), llvm::EpilogueVectorizerEpilogueLoop::createEpilogueVectorizedLoopSkeleton(), and createVectorizedLoopSkeleton().
createBitOrPointerCast()
Value * InnerLoopVectorizer::createBitOrPointerCast (Value * V, VectorType * DstVTy, const DataLayout & DL) protected
Returns a bitcasted value to the requested vector type.
Also handles bitcasts of vector<float> <-> vector<pointer> types.
Definition at line 3054 of file LoopVectorize.cpp.
References assert(), Builder, llvm::IRBuilderBase::CreateBitOrPointerCast(), DL, llvm::FixedVectorType::get(), llvm::Value::getContext(), llvm::Type::getIntNTy(), llvm::Value::getType(), llvm::CastInst::isBitOrNoopPointerCastable(), llvm::Type::isFloatingPointTy(), llvm::Type::isPointerTy(), and VF.
Referenced by vectorizeInterleaveGroup().
createInductionResumeValues()
void InnerLoopVectorizer::createInductionResumeValues (Loop * L, Value * VectorTripCount, std::pair< BasicBlock *, Value * > AdditionalBypass = {nullptr, nullptr}) protected
Create new phi nodes for the induction variables to resume iteration count in the scalar epilogue, from where the vectorized loop left off (given by VectorTripCount).
In cases where the loop skeleton is more complicated (eg. epilogue vectorization) and the resume values can come from an additional bypass block, the AdditionalBypass pair provides information about the bypass block and the end value on the edge from bypass to this loop.
Definition at line 3383 of file LoopVectorize.cpp.
References llvm::PHINode::addIncoming(), assert(), B, llvm::PHINode::Create(), DL, emitTransformedIndex(), llvm::CastInst::getCastOpcode(), llvm::Module::getDataLayout(), llvm::Instruction::getDebugLoc(), llvm::LoopVectorizationLegality::getInductionVars(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::BasicBlock::getModule(), llvm::PredicatedScalarEvolution::getSE(), llvm::InductionDescriptor::getStartValue(), llvm::InductionDescriptor::getStep(), llvm::BasicBlock::getTerminator(), llvm::SCEV::getType(), llvm::Value::getType(), IVEndValues, Legal, LoopBypassBlocks, LoopMiddleBlock, LoopScalarBody, LoopScalarPreHeader, OldInduction, PSE, llvm::Instruction::setDebugLoc(), llvm::PHINode::setIncomingValueForBlock(), llvm::Value::setName(), and VectorTripCount.
Referenced by llvm::EpilogueVectorizerEpilogueLoop::createEpilogueVectorizedLoopSkeleton(), and createVectorizedLoopSkeleton().
createInductionVariable()
PHINode * InnerLoopVectorizer::createInductionVariable (Loop * L, Value * Start, Value * End, Value * Step, Instruction * DL) protected
Create a new induction variable inside L.
Definition at line 2921 of file LoopVectorize.cpp.
Referenced by llvm::EpilogueVectorizerMainLoop::createEpilogueVectorizedLoopSkeleton(), llvm::EpilogueVectorizerEpilogueLoop::createEpilogueVectorizedLoopSkeleton(), and createVectorizedLoopSkeleton().
createVectorIntOrFpInductionPHI()
void InnerLoopVectorizer::createVectorIntOrFpInductionPHI (const InductionDescriptor & II, Value * Step, Value * Start, Instruction * EntryVal) protected
Create a vector induction phi node based on an existing scalar one.
EntryVal is the value from the original loop that maps to the vector phi node, and Step is the loop-invariant step. If EntryVal is a truncate instruction, instead of widening the original IV, we widen a version of the IV truncated to EntryVal's type.
Definition at line 2024 of file LoopVectorize.cpp.
createVectorizedLoopSkeleton()
BasicBlock * InnerLoopVectorizer::createVectorizedLoopSkeleton () virtual
Create a new empty loop that will contain vectorized instructions later on, while the old loop will be used as the scalar remainder.
Control flow is generated around the vectorized (and scalar epilogue) loops consisting of various checks and bypasses. Return the pre-header block of the new loop. In the case of epilogue vectorization, this function is overriden to handle the more complex control flow around the loops.
Reimplemented in llvm::InnerLoopAndEpilogueVectorizer.
Definition at line 3511 of file LoopVectorize.cpp.
References Builder, completeLoopSkeleton(), createInductionResumeValues(), createInductionVariable(), createStepForVF(), createVectorLoopSkeleton(), emitMemRuntimeChecks(), llvm::EpilogueVectorizerMainLoop::emitMinimumIterationCountCheck(), emitSCEVChecks(), llvm::ConstantInt::get(), getDebugLocFromInstOrOperands(), llvm::BasicBlock::getFirstInsertionPt(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::Loop::getLoopID(), getOrCreateVectorTripCount(), llvm::LoopVectorizationLegality::getPrimaryInduction(), llvm::LoopVectorizationLegality::getWidestInductionType(), Induction, Legal, LoopScalarPreHeader, OldInduction, OrigLoop, llvm::IRBuilderBase::SetInsertPoint(), UF, and VF.
Referenced by llvm::LoopVectorizationPlanner::executePlan().
createVectorLoopSkeleton()
Loop * InnerLoopVectorizer::createVectorLoopSkeleton (StringRef Prefix) protected
Emit basic blocks (prefixed with Prefix) for the iteration check, vector loop preheader, middle block and scalar preheader.
Also allocate a loop object for the new vector loop and return it.
Definition at line 3335 of file LoopVectorize.cpp.
References llvm::LoopBase< BlockT, LoopT >::addBasicBlockToLoop(), llvm::LoopBase< BlockT, LoopT >::addChildLoop(), llvm::LoopInfoBase< BlockT, LoopT >::addTopLevelLoop(), llvm::LoopInfoBase< BlockT, LoopT >::AllocateLoop(), assert(), Builder, llvm::DominatorTreeBase< NodeT, IsPostDom >::changeImmediateDominator(), llvm::BranchInst::Create(), DT, llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), llvm::BasicBlock::getTerminator(), llvm::IRBuilderBase::getTrue(), llvm::LoopBase< BlockT, LoopT >::getUniqueExitBlock(), LI, LoopExitBlock, LoopMiddleBlock, LoopScalarBody, LoopScalarPreHeader, LoopVectorBody, LoopVectorPreHeader, OrigLoop, llvm::cl::Prefix, llvm::ReplaceInstWithInst(), llvm::Instruction::setDebugLoc(), and llvm::SplitBlock().
Referenced by llvm::EpilogueVectorizerMainLoop::createEpilogueVectorizedLoopSkeleton(), llvm::EpilogueVectorizerEpilogueLoop::createEpilogueVectorizedLoopSkeleton(), and createVectorizedLoopSkeleton().
emitMemRuntimeChecks()
void InnerLoopVectorizer::emitMemRuntimeChecks (Loop * L, BasicBlock * Bypass) protected
Emit bypass checks to check any memory assumptions we may have made.
Definition at line 3168 of file LoopVectorize.cpp.
References AddedSafetyChecks, llvm::addRuntimeChecks(), assert(), Builder, llvm::DominatorTreeBase< NodeT, IsPostDom >::changeImmediateDominator(), Cost, llvm::IRBuilderBase::CreateCondBr(), DEBUG_TYPE, DT, llvm::OptimizationRemarkEmitter::emit(), EnableVPlanNativePath, llvm::LoopVectorizeHints::FK_Enabled, llvm::RuntimePointerChecking::getChecks(), llvm::LoopVectorizeHints::getForce(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopVectorizationLegality::getLAI(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::BasicBlock::getParent(), llvm::LoopAccessInfo::getRuntimePointerChecking(), llvm::PredicatedScalarEvolution::getSE(), llvm::Loop::getStartLoc(), llvm::BasicBlock::getTerminator(), llvm::IRBuilderBase::getTrue(), llvm::Function::hasOptSize(), llvm::LoopVectorizationCostModel::Hints, Legal, LI, LoopBypassBlocks, LoopExitBlock, LoopVectorPreHeader, LVer, OptForSizeBasedOnProfile, ORE, OrigLoop, PSE, llvm::ReplaceInstWithInst(), llvm::Value::setName(), and llvm::SplitBlock().
Referenced by llvm::EpilogueVectorizerMainLoop::createEpilogueVectorizedLoopSkeleton(), and createVectorizedLoopSkeleton().
emitMinimumIterationCountCheck()
void InnerLoopVectorizer::emitMinimumIterationCountCheck (Loop * L, BasicBlock * Bypass) protected
Emit a bypass check to see if the vector trip count is zero, including if it overflows.
Definition at line 3085 of file LoopVectorize.cpp.
References assert(), Builder, llvm::DominatorTreeBase< NodeT, IsPostDom >::changeImmediateDominator(), Cost, llvm::BranchInst::Create(), llvm::IRBuilderBase::CreateICmp(), createStepForVF(), DT, llvm::LoopVectorizationCostModel::foldTailByMasking(), llvm::ConstantInt::get(), llvm::IRBuilderBase::getFalse(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode(), getOrCreateTripCount(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, LI, LoopBypassBlocks, LoopExitBlock, LoopVectorPreHeader, P, llvm::DominatorTreeBase< NodeT, IsPostDom >::properlyDominates(), llvm::ReplaceInstWithInst(), llvm::LoopVectorizationCostModel::requiresScalarEpilogue(), llvm::SplitBlock(), UF, and VF.
emitSCEVChecks()
void InnerLoopVectorizer::emitSCEVChecks (Loop * L, BasicBlock * Bypass) protected
Emit a bypass check to see if all of the SCEV assumptions we've had to make are correct.
Definition at line 3127 of file LoopVectorize.cpp.
References AddedSafetyChecks, assert(), C, llvm::DominatorTreeBase< NodeT, IsPostDom >::changeImmediateDominator(), Cost, llvm::BranchInst::Create(), DT, llvm::LoopVectorizeHints::FK_Enabled, llvm::Module::getDataLayout(), llvm::LoopVectorizeHints::getForce(), llvm::BasicBlock::getModule(), llvm::BasicBlock::getParent(), llvm::PredicatedScalarEvolution::getSE(), llvm::BasicBlock::getTerminator(), llvm::PredicatedScalarEvolution::getUnionPredicate(), llvm::Function::hasOptSize(), llvm::LoopVectorizationCostModel::Hints, LI, LoopBypassBlocks, LoopExitBlock, LoopVectorPreHeader, OptForSizeBasedOnProfile, PSE, llvm::ReplaceInstWithInst(), llvm::Value::setName(), and llvm::SplitBlock().
Referenced by llvm::EpilogueVectorizerMainLoop::createEpilogueVectorizedLoopSkeleton(), and createVectorizedLoopSkeleton().
emitTransformedIndex()
Value * InnerLoopVectorizer::emitTransformedIndex (IRBuilder<> & B, Value * Index, ScalarEvolution * SE, const DataLayout & DL, const InductionDescriptor & ID) const protected
Compute the transformed value of Index at offset StartValue using step StepValue.
For integer induction, returns StartValue + Index * StepValue. For pointer induction, returns StartValue[Index * StepValue]. FIXME: The newly created binary instructions should contain nsw/nuw flags, which can be found from the original scalar operations.
Definition at line 3235 of file LoopVectorize.cpp.
References assert(), B, CreateAdd(), CreateMul(), DL, llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::BasicBlock::getTerminator(), llvm::InductionDescriptor::IK_FpInduction, llvm::InductionDescriptor::IK_IntInduction, llvm::InductionDescriptor::IK_NoInduction, llvm::InductionDescriptor::IK_PtrInduction, Index, LI, llvm_unreachable, LoopVectorBody, Offset, llvm::FastMathFlags::setFast(), X, and Y.
Referenced by createInductionResumeValues(), fixupIVUsers(), and widenPHIInstruction().
fixCrossIterationPHIs()
void InnerLoopVectorizer::fixCrossIterationPHIs () protected
Handle all cross-iteration phis in the header.
Definition at line 3975 of file LoopVectorize.cpp.
References fixFirstOrderRecurrence(), fixReduction(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopVectorizationLegality::isFirstOrderRecurrence(), llvm::LoopVectorizationLegality::isReductionVariable(), Legal, OrigLoop, and llvm::BasicBlock::phis().
Referenced by fixVectorizedLoop().
fixFirstOrderRecurrence()
void InnerLoopVectorizer::fixFirstOrderRecurrence (PHINode * Phi) protected
Fix a first-order recurrence.
This is the second phase of vectorizing this phi node.
Definition at line 3991 of file LoopVectorize.cpp.
References llvm::PHINode::addIncoming(), assert(), llvm::BasicBlock::begin(), Builder, llvm::IRBuilderBase::CreateExtractElement(), llvm::IRBuilderBase::CreateInsertElement(), llvm::IRBuilderBase::CreatePHI(), llvm::IRBuilderBase::CreateShuffleVector(), llvm::VectorType::get(), llvm::PoisonValue::get(), llvm::BasicBlock::getFirstInsertionPt(), llvm::PHINode::getIncomingValueForBlock(), llvm::IRBuilderBase::getInt32(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::LinearPolySize< LeafTy >::getKnownMinValue(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), getOrCreateVectorValue(), llvm::Instruction::getParent(), llvm::BasicBlock::getTerminator(), llvm::VectorizerValueMap::getVectorValue(), I, llvm::Loop::isLoopInvariant(), llvm::LinearPolySize< LeafTy >::isScalable(), llvm::ElementCount::isVector(), LI, LoopMiddleBlock, LoopScalarPreHeader, LoopVectorBody, LoopVectorPreHeader, OrigLoop, llvm::Value::replaceAllUsesWith(), llvm::VectorizerValueMap::resetVectorValue(), llvm::IRBuilderBase::SetInsertPoint(), UF, VectorLoopValueMap, and VF.
Referenced by fixCrossIterationPHIs().
fixLCSSAPHIs()
void InnerLoopVectorizer::fixLCSSAPHIs () protected
Fixup the LCSSA phi nodes in the unique exit block.
This simply means we need to add the appropriate incoming value from the middle block as exiting edges from the scalar epilogue loop (if present) are already in place, and we exit the vector loop exclusively to the middle block.
Definition at line 4381 of file LoopVectorize.cpp.
References assert(), Builder, Cost, llvm::LinearPolySize< LeafTy >::getKnownMinValue(), getOrCreateScalarValue(), llvm::BasicBlock::getTerminator(), llvm::LinearPolySize< LeafTy >::isScalable(), llvm::LoopVectorizationCostModel::isUniformAfterVectorization(), LoopExitBlock, LoopMiddleBlock, llvm::BasicBlock::phis(), llvm::IRBuilderBase::SetInsertPoint(), UF, and VF.
fixNonInductionPHIs()
void InnerLoopVectorizer::fixNonInductionPHIs (void)
Fix the non-induction PHIs in the OrigPHIsToFix vector.
Definition at line 4471 of file LoopVectorize.cpp.
References llvm::PHINode::addIncoming(), assert(), Builder, getOrCreateVectorValue(), llvm::Instruction::getParent(), llvm::VectorizerValueMap::getVectorValue(), OrigPHIsToFix, llvm::predecessors(), llvm::IRBuilderBase::SetInsertPoint(), llvm::SmallVectorBase< Size_T >::size(), and VectorLoopValueMap.
Referenced by fixVectorizedLoop().
fixReduction()
void InnerLoopVectorizer::fixReduction (PHINode * Phi) protected
Fix a reduction cross-iteration phi.
This is the second phase of vectorizing this phi node.
Definition at line 4176 of file LoopVectorize.cpp.
References addFastMathFlag(), llvm::PHINode::addIncoming(), llvm::any_of(), assert(), Builder, clearReductionWrapFlags(), Cost, llvm::PHINode::Create(), llvm::IRBuilderBase::CreateBinOp(), llvm::createMinMaxOp(), llvm::IRBuilderBase::CreateSExt(), llvm::createTargetReduction(), llvm::IRBuilderBase::CreateTrunc(), llvm::IRBuilderBase::CreateZExt(), E, llvm::LoopVectorizationCostModel::foldTailByMasking(), llvm::VectorType::get(), llvm::PHINode::getBasicBlockIndex(), llvm::RecurrenceDescriptor::getFastMathFlags(), llvm::BasicBlock::getFirstInsertionPt(), llvm::PHINode::getIncomingValueForBlock(), llvm::RecurrenceDescriptor::getLoopExitInstr(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::RecurrenceDescriptor::getOpcode(), getOrCreateVectorValue(), llvm::RecurrenceDescriptor::getRecurrenceKind(), llvm::RecurrenceDescriptor::getRecurrenceStartValue(), llvm::RecurrenceDescriptor::getRecurrenceType(), llvm::LoopVectorizationLegality::getReductionVars(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::VectorizerValueMap::getVectorValue(), I, llvm::LoopVectorizationCostModel::isInLoopReduction(), llvm::LoopVectorizationLegality::isReductionVariable(), llvm::LinearPolySize< LeafTy >::isScalable(), llvm::RecurrenceDescriptor::isSigned(), llvm::ElementCount::isVector(), Legal, LI, LoopBypassBlocks, LoopExitBlock, LoopMiddleBlock, LoopScalarPreHeader, LoopVectorBody, OrigLoop, llvm::BasicBlock::phis(), PreferPredicatedReductionSelect, llvm::TargetTransformInfo::preferPredicatedReductionSelect(), replaceUsesOfWith(), llvm::VectorizerValueMap::resetVectorValue(), setDebugLocFromInst(), llvm::PHINode::setIncomingValue(), llvm::IRBuilderBase::SetInsertPoint(), UF, llvm::Value::users(), VectorLoopValueMap, and VF.
Referenced by fixCrossIterationPHIs().
fixupIVUsers()
void InnerLoopVectorizer::fixupIVUsers (PHINode * OrigPhi, const InductionDescriptor & II, Value * CountRoundDown, Value * EndValue, BasicBlock * MiddleBlock) protected
Set up the values of the IVs correctly when exiting the vector loop.
Definition at line 3600 of file LoopVectorize.cpp.
References llvm::PHINode::addIncoming(), assert(), B, llvm::LoopBase< BlockT, LoopT >::contains(), DL, emitTransformedIndex(), llvm::ConstantInt::get(), llvm::PHINode::getBasicBlockIndex(), llvm::Module::getDataLayout(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::PHINode::getIncomingValueForBlock(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::BasicBlock::getModule(), llvm::PredicatedScalarEvolution::getSE(), llvm::InductionDescriptor::getStep(), llvm::BasicBlock::getTerminator(), llvm::SCEV::getType(), llvm::Value::getType(), llvm::LoopBase< BlockT, LoopT >::getUniqueExitBlock(), I, llvm::Type::isIntegerTy(), OrigLoop, PostInc, PSE, llvm::Value::setName(), and llvm::Value::users().
fixVectorizedLoop()
void InnerLoopVectorizer::fixVectorizedLoop ()
Fix the vectorized code, taking care of header phi's, live-outs, and more.
Definition at line 3922 of file LoopVectorize.cpp.
References assert(), EnableVPlanNativePath, fixCrossIterationPHIs(), fixNonInductionPHIs(), llvm::ScalarEvolution::forgetLoop(), llvm::PredicatedScalarEvolution::getSE(), llvm::ElementCount::isVector(), OrigLoop, OrigPHIsToFix, PSE, truncateToMinimalBitwidths(), and VF.
Referenced by llvm::LoopVectorizationPlanner::executePlan().
getBroadcastInstrs()
Value * InnerLoopVectorizer::getBroadcastInstrs (Value * V) protected virtual
Create a broadcast instruction.
This method generates a broadcast instruction (shuffle) for loop invariant values and for the induction value. If this is the induction variable then we extend it to N, N+1, ... this is needed because each iteration in the loop corresponds to a SIMD element.
Definition at line 2005 of file LoopVectorize.cpp.
References Builder, llvm::IRBuilderBase::CreateVectorSplat(), llvm::DominatorTree::dominates(), DT, llvm::Instruction::getParent(), llvm::BasicBlock::getTerminator(), llvm::Loop::isLoopInvariant(), LoopVectorPreHeader, OrigLoop, llvm::IRBuilderBase::SetInsertPoint(), and VF.
Referenced by getOrCreateVectorValue().
getOrCreateScalarValue()
Value * InnerLoopVectorizer::getOrCreateScalarValue (Value * V, const VPIteration & Instance)
Return a value in the new loop corresponding to V from the original loop at unroll and vector indices Instance.
If the value has been vectorized but not scalarized, the necessary extractelement instruction will be generated.
Definition at line 2446 of file LoopVectorize.cpp.
References assert(), Builder, Cost, llvm::IRBuilderBase::CreateExtractElement(), llvm::IRBuilderBase::getInt32(), getOrCreateVectorValue(), llvm::VectorizerValueMap::getScalarValue(), llvm::VectorizerValueMap::hasScalarValue(), llvm::Loop::isLoopInvariant(), llvm::ElementCount::isScalar(), llvm::LoopVectorizationCostModel::isUniformAfterVectorization(), llvm::VPIteration::Lane, OrigLoop, llvm::VPIteration::Part, VectorLoopValueMap, and VF.
Referenced by fixLCSSAPHIs().
getOrCreateTripCount()
Value * InnerLoopVectorizer::getOrCreateTripCount (Loop * NewLoop) protected
Returns (and creates if needed) the original loop trip count.
Definition at line 2953 of file LoopVectorize.cpp.
References assert(), Builder, llvm::CastInst::CreatePointerCast(), DL, llvm::ScalarEvolution::getAddExpr(), llvm::PredicatedScalarEvolution::getBackedgeTakenCount(), llvm::Module::getDataLayout(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::BasicBlock::getModule(), llvm::ScalarEvolution::getNoopOrZeroExtend(), llvm::ScalarEvolution::getOne(), llvm::Type::getPrimitiveSizeInBits(), llvm::PredicatedScalarEvolution::getSE(), llvm::BasicBlock::getTerminator(), llvm::ScalarEvolution::getTruncateOrNoop(), llvm::SCEV::getType(), llvm::Value::getType(), llvm::ScalarEvolution::getTypeSizeInBits(), llvm::LoopVectorizationLegality::getWidestInductionType(), llvm::Type::isPointerTy(), Legal, PSE, and TripCount.
Referenced by completeLoopSkeleton(), emitMinimumIterationCountCheck(), llvm::EpilogueVectorizerMainLoop::emitMinimumIterationCountCheck(), llvm::LoopVectorizationPlanner::executePlan(), and getOrCreateVectorTripCount().
getOrCreateVectorTripCount()
Value * InnerLoopVectorizer::getOrCreateVectorTripCount (Loop * NewLoop) protected
Returns (and creates if needed) the trip count of the widened loop.
Definition at line 3000 of file LoopVectorize.cpp.
References assert(), Builder, Cost, llvm::IRBuilderBase::CreateAdd(), llvm::IRBuilderBase::CreateICmpEQ(), llvm::IRBuilderBase::CreateSelect(), createStepForVF(), llvm::IRBuilderBase::CreateSub(), llvm::IRBuilderBase::CreateURem(), llvm::LoopVectorizationCostModel::foldTailByMasking(), llvm::ConstantInt::get(), llvm::LinearPolySize< LeafTy >::getKnownMinValue(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), getOrCreateTripCount(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::isPowerOf2_32(), llvm::LinearPolySize< LeafTy >::isScalable(), llvm::ElementCount::isVector(), llvm::LoopVectorizationCostModel::requiresScalarEpilogue(), UF, VectorTripCount, and VF.
Referenced by completeLoopSkeleton(), llvm::EpilogueVectorizerMainLoop::createEpilogueVectorizedLoopSkeleton(), llvm::EpilogueVectorizerEpilogueLoop::createEpilogueVectorizedLoopSkeleton(), and createVectorizedLoopSkeleton().
getOrCreateVectorValue()
Value * InnerLoopVectorizer::getOrCreateVectorValue (Value * V, unsigned Part)
getOrCreateVectorValue and getOrCreateScalarValue coordinate to generate a vector or scalar value on-demand if one is not yet available.
When vectorizing a loop, we visit the definition of an instruction before its uses. When visiting the definition, we either vectorize or scalarize the instruction, creating an entry for it in the corresponding map. (In some cases, such as induction variables, we will create both vector and scalar entries.) Then, as we encounter uses of the definition, we derive values for each scalar or vector use unless such a value is already available. For example, if we scalarize a definition and one of its uses is vector, we build the required vector on-demand with an insertelement sequence when visiting the use. Otherwise, if the use is scalar, we can use the existing scalar definition.
Return a value in the new loop corresponding to V from the original loop at unroll index Part. If the value has already been vectorized, the corresponding vector entry in VectorLoopValueMap is returned. If, however, the value has a scalar entry in VectorLoopValueMap, we construct a new vector value on-demand by inserting the scalar values into a vector with an insertelement sequence. If the value has been neither vectorized nor scalarized, it must be loop invariant, so we simply broadcast the value into a vector.
Definition at line 2367 of file LoopVectorize.cpp.
References assert(), B, Builder, Cost, EnableVPlanNativePath, llvm::VectorType::get(), llvm::PoisonValue::get(), llvm::ConstantInt::get(), getBroadcastInstrs(), llvm::LinearPolySize< LeafTy >::getKnownMinValue(), llvm::VectorizerValueMap::getScalarValue(), llvm::Value::getType(), llvm::VectorizerValueMap::getVectorValue(), llvm::VectorizerValueMap::hasAnyScalarValue(), llvm::LoopVectorizationLegality::hasStride(), llvm::VectorizerValueMap::hasVectorValue(), I, Induction, llvm::LinearPolySize< LeafTy >::isScalable(), llvm::ElementCount::isScalar(), llvm::LoopVectorizationCostModel::isUniformAfterVectorization(), llvm::Type::isVectorTy(), llvm::Type::isVoidTy(), Legal, packScalarIntoVectorValue(), llvm::IRBuilderBase::restoreIP(), llvm::IRBuilderBase::saveIP(), llvm::IRBuilderBase::SetInsertPoint(), llvm::VectorizerValueMap::setVectorValue(), VectorLoopValueMap, and VF.
Referenced by clearReductionWrapFlags(), fixFirstOrderRecurrence(), fixNonInductionPHIs(), fixReduction(), getOrCreateScalarValue(), and truncateToMinimalBitwidths().
getStepVector()
Value * InnerLoopVectorizer::getStepVector (Value * Val, int StartIdx, Value * Step, Instruction::BinaryOps Opcode = Instruction::BinaryOpsEnd) protected virtual
This function adds (StartIdx, StartIdx + Step, StartIdx + 2*Step, ...) to each vector element of Val.
The sequence starts at StartIndex. Opcode is relevant for FP induction variable.
Definition at line 2256 of file LoopVectorize.cpp.
References assert(), Builder, llvm::IRBuilderBase::CreateAdd(), llvm::IRBuilderBase::CreateBinOp(), llvm::IRBuilderBase::CreateFMul(), llvm::IRBuilderBase::CreateMul(), llvm::IRBuilderBase::CreateVectorSplat(), llvm::ConstantVector::get(), llvm::ConstantFP::get(), llvm::ConstantInt::get(), llvm::Type::getScalarType(), llvm::Value::getType(), llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::FastMathFlags::setFast().
needsScalarInduction()
bool InnerLoopVectorizer::needsScalarInduction (Instruction * IV) const protected
Returns true if we should generate a scalar version of IV.
Definition at line 2108 of file LoopVectorize.cpp.
References llvm::any_of(), llvm::LoopBase< BlockT, LoopT >::contains(), I, OrigLoop, shouldScalarizeInstruction(), and llvm::Value::users().
packScalarIntoVectorValue()
void InnerLoopVectorizer::packScalarIntoVectorValue (Value * V, const VPIteration & Instance)
Construct the vector value of a scalarized value V one lane at a time.
Definition at line 2479 of file LoopVectorize.cpp.
References assert(), Builder, llvm::IRBuilderBase::CreateInsertElement(), llvm::IRBuilderBase::getInt32(), llvm::VectorizerValueMap::getScalarValue(), llvm::Value::getType(), llvm::VectorizerValueMap::getVectorValue(), Induction, llvm::Type::isVectorTy(), llvm::Type::isVoidTy(), llvm::VPIteration::Lane, llvm::VPIteration::Part, llvm::VectorizerValueMap::resetVectorValue(), and VectorLoopValueMap.
Referenced by llvm::VPReplicateRecipe::execute(), and getOrCreateVectorValue().
printDebugTracesAtEnd()
virtual void llvm::InnerLoopVectorizer::printDebugTracesAtEnd () inline protected virtual
Reimplemented in llvm::EpilogueVectorizerEpilogueLoop, and llvm::EpilogueVectorizerMainLoop.
Definition at line 783 of file LoopVectorize.cpp.
Referenced by llvm::LoopVectorizationPlanner::executePlan().
printDebugTracesAtStart()
virtual void llvm::InnerLoopVectorizer::printDebugTracesAtStart () inline protected virtual
Allow subclasses to override and print debug traces before/after vplan execution, when trace information is requested.
Reimplemented in llvm::EpilogueVectorizerEpilogueLoop, and llvm::EpilogueVectorizerMainLoop.
Definition at line 782 of file LoopVectorize.cpp.
Referenced by llvm::LoopVectorizationPlanner::executePlan().
recordVectorLoopValueForInductionCast()
void InnerLoopVectorizer::recordVectorLoopValueForInductionCast (const InductionDescriptor & ID, const Instruction * EntryVal, Value * VectorLoopValue, unsigned Part, unsigned Lane = UINT_MAX) protected
If there is a cast involved in the induction variable ID, which should be ignored in the vectorized loop body, this function records the VectorLoopValue of the respective Phi also as the VectorLoopValue of the cast.
We had already proved that the casted Phi is equal to the uncasted Phi in the vectorized loop (under a runtime guard), and therefore there is no need to vectorize the cast - the same value can be used in the vector loop for both the Phi and the cast. If VectorLoopValue is a scalarized value, Lane is also specified, Otherwise, VectorLoopValue is a widened/vectorized value.
EntryVal is the value from the original loop that maps to the vector phi node and is used to distinguish what is the IV currently being processed - original one (if EntryVal is a phi corresponding to the original IV) or the "newly-created" one based on the proof mentioned above (see also buildScalarSteps() and createVectorIntOrFPInductionPHI()). In the latter case EntryVal is a TruncInst and we must not record anything for that IV, but it's error-prone to expect callers of this routine to care about that, hence this explicit parameter.
Definition at line 2118 of file LoopVectorize.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorBase< Size_T >::empty(), llvm::VectorizerValueMap::setScalarValue(), llvm::VectorizerValueMap::setVectorValue(), and VectorLoopValueMap.
Referenced by buildScalarSteps().
reverseVector()
Value * InnerLoopVectorizer::reverseVector (Value * Vec) protected virtual
Generate a shuffle sequence that will reverse the vector Vec.
Definition at line 2492 of file LoopVectorize.cpp.
References assert(), Builder, llvm::IRBuilderBase::CreateShuffleVector(), llvm::LinearPolySize< LeafTy >::getKnownMinValue(), llvm::Value::getType(), llvm::LinearPolySize< LeafTy >::isScalable(), llvm::Type::isVectorTy(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and VF.
Referenced by vectorizeInterleaveGroup(), and vectorizeMemoryInstruction().
scalarizeInstruction()
void InnerLoopVectorizer::scalarizeInstruction (Instruction * Instr, VPUser & Operands, const VPIteration & Instance, bool IfPredicateInstr, VPTransformState & State)
A helper function to scalarize a single Instruction in the innermost loop.
Generates a sequence of scalar instances for each lane between MinLane and MaxLane, times each part between MinPart and MaxPart, inclusive. Uses the VPValue operands from Operands instead of Instr's operands.
Definition at line 2869 of file LoopVectorize.cpp.
References AC, addNewMetadata(), assert(), Builder, llvm::Instruction::clone(), llvm::LoopBase< BlockT, LoopT >::contains(), Cost, llvm::numbers::e, llvm::VPTransformState::get(), llvm::Value::getName(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::Value::getType(), llvm::IRBuilderBase::Insert(), llvm::Type::isAggregateType(), llvm::LoopVectorizationCostModel::isUniformAfterVectorization(), llvm::Type::isVoidTy(), llvm::VPIteration::Lane, op, OrigLoop, llvm::VPIteration::Part, PredicatedInstructions, llvm::AssumptionCache::registerAssumption(), setDebugLocFromInst(), llvm::Value::setName(), llvm::User::setOperand(), llvm::VectorizerValueMap::setScalarValue(), VectorLoopValueMap, and llvm::VPTransformState::VF.
Referenced by llvm::VPReplicateRecipe::execute().
setDebugLocFromInst()
void InnerLoopVectorizer::setDebugLocFromInst (IRBuilder<> & B, const Value * Ptr)
Set the debug location in the builder using the debug location in the instruction.
Definition at line 1068 of file LoopVectorize.cpp.
References assert(), B, llvm::DILocation::cloneByMultiplyingDuplicationFactor(), llvm::dbgs(), llvm::LinearPolySize< LeafTy >::getKnownMinValue(), llvm::LinearPolySize< LeafTy >::isScalable(), LLVM_DEBUG, UF, and VF.
Referenced by llvm::VPBlendRecipe::execute(), fixReduction(), scalarizeInstruction(), vectorizeInterleaveGroup(), vectorizeMemoryInstruction(), widenCallInstruction(), widenInstruction(), widenPHIInstruction(), and widenSelectInstruction().
setVectorValue()
void llvm::InnerLoopVectorizer::setVectorValue (Value * Scalar, unsigned Part, Value * Vector) inline
Definition at line 555 of file LoopVectorize.cpp.
References llvm::VectorizerValueMap::setVectorValue(), llvm::Vector, and VectorLoopValueMap.
shouldScalarizeInstruction()
bool InnerLoopVectorizer::shouldScalarizeInstruction (Instruction * I) const protected
Returns true if an instruction I should be scalarized instead of vectorized for the chosen vectorization factor.
Definition at line 2103 of file LoopVectorize.cpp.
References Cost, I, llvm::LoopVectorizationCostModel::isProfitableToScalarize(), llvm::LoopVectorizationCostModel::isScalarAfterVectorization(), and VF.
Referenced by needsScalarInduction().
sinkScalarOperands()
void InnerLoopVectorizer::sinkScalarOperands (Instruction * PredInst) protected
Iteratively sink the scalarized operands of a predicated instruction into the block that was created for it.
Definition at line 4407 of file LoopVectorize.cpp.
References llvm::all_of(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::SetVector< T, Vector, Set >::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::PHINode::getIncomingValueNumForOperand(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::Instruction::getParent(), I, llvm::SetVector< T, Vector, Set >::insert(), LI, llvm::User::op_begin(), llvm::User::op_end(), llvm::SetVector< T, Vector, Set >::pop_back_val(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
truncateToMinimalBitwidths()
void InnerLoopVectorizer::truncateToMinimalBitwidths () protected
Shrinks vector element sizes to the smallest bitwidth they can be legally represented as.
Definition at line 3788 of file LoopVectorize.cpp.
References B, Cost, llvm::SmallPtrSetImpl< PtrType >::count(), llvm::Instruction::eraseFromParent(), llvm::IntegerType::get(), llvm::FixedVectorType::get(), llvm::Type::getContext(), llvm::LoopVectorizationCostModel::getMinimalBitwidths(), llvm::User::getOperand(), getOrCreateVectorValue(), llvm::VectorizerValueMap::hasAnyVectorValue(), I, llvm::ARM_PROC::IE, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm_unreachable, llvm::VectorizerValueMap::resetVectorValue(), SI, smallestIntegerVectorType(), llvm::Value::takeName(), UF, llvm::Value::use_empty(), and VectorLoopValueMap.
Referenced by fixVectorizedLoop().
vectorizeInterleaveGroup()
void InnerLoopVectorizer::vectorizeInterleaveGroup (const InterleaveGroup< Instruction > * Group, ArrayRef< VPValue * > VPDefs, VPTransformState & State, VPValue * Addr, ArrayRef< VPValue * > StoredValues, VPValue * BlockInMask = nullptr)
Try to vectorize interleaved access group Group with the base address given in Addr, optionally masking the vector operations if BlockInMask is non-null.
Use State to translate given VPValues to IR values in the vectorized loop.
Definition at line 2541 of file LoopVectorize.cpp.
References llvm::InterleaveGroup< InstTy >::addMetadata(), Addr, assert(), Builder, llvm::concatenateVectors(), Cost, llvm::IRBuilderBase::CreateAlignedLoad(), llvm::IRBuilderBase::CreateAlignedStore(), llvm::IRBuilderBase::CreateBinOp(), llvm::IRBuilderBase::CreateBitCast(), llvm::createBitMaskForGaps(), createBitOrPointerCast(), llvm::IRBuilderBase::CreateGEP(), llvm::createInterleaveMask(), llvm::IRBuilderBase::CreateMaskedLoad(), llvm::IRBuilderBase::CreateMaskedStore(), llvm::createReplicatedMask(), llvm::IRBuilderBase::CreateShuffleVector(), llvm::createStrideMask(), DL, gep, llvm::VectorType::get(), llvm::PoisonValue::get(), llvm::VPTransformState::get(), llvm::InterleaveGroup< InstTy >::getAlign(), llvm::Module::getDataLayout(), llvm::InterleaveGroup< InstTy >::getFactor(), llvm::InterleaveGroup< InstTy >::getIndex(), llvm::InterleaveGroup< InstTy >::getInsertPos(), llvm::IRBuilderBase::getInt32(), llvm::LinearPolySize< LeafTy >::getKnownMinValue(), llvm::InterleaveGroup< InstTy >::getMember(), getMemInstValueType(), llvm::Instruction::getModule(), llvm::Type::getPointerAddressSpace(), llvm::Type::getPointerTo(), llvm::Value::getType(), I, Index, llvm::InterleaveGroup< InstTy >::isReverse(), llvm::LinearPolySize< LeafTy >::isScalable(), llvm::LoopVectorizationCostModel::isScalarEpilogueAllowed(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::InterleaveGroup< InstTy >::requiresScalarEpilogue(), reverseVector(), llvm::VPTransformState::set(), setDebugLocFromInst(), llvm::Value::stripPointerCasts(), UF, useMaskedInterleavedAccesses(), and VF.
Referenced by llvm::VPInterleaveRecipe::execute().
vectorizeMemoryInstruction()
void InnerLoopVectorizer::vectorizeMemoryInstruction (Instruction * Instr, VPTransformState & State, VPValue * Def, VPValue * Addr, VPValue * StoredValue, VPValue * BlockInMask)
Vectorize Load and Store instructions with the base address given in Addr, optionally masking the vector operations if BlockInMask is non-null.
Use State to translate given VPValues to IR values in the vectorized loop.
Definition at line 2730 of file LoopVectorize.cpp.
References addMetadata(), Addr, assert(), Builder, llvm::LoopVectorizationCostModel::CM_GatherScatter, llvm::LoopVectorizationCostModel::CM_Widen, llvm::LoopVectorizationCostModel::CM_Widen_Reverse, Cost, llvm::IRBuilderBase::CreateAlignedLoad(), llvm::IRBuilderBase::CreateAlignedStore(), llvm::IRBuilderBase::CreateBitCast(), llvm::IRBuilderBase::CreateGEP(), llvm::IRBuilderBase::CreateMaskedGather(), llvm::IRBuilderBase::CreateMaskedLoad(), llvm::IRBuilderBase::CreateMaskedScatter(), llvm::IRBuilderBase::CreateMaskedStore(), createStepForVF(), llvm::tgtok::Def, gep, llvm::VectorType::get(), llvm::PoisonValue::get(), llvm::VPTransformState::get(), llvm::IRBuilderBase::getInt32(), llvm::LinearPolySize< LeafTy >::getKnownMinValue(), llvm::getLoadStoreAlignment(), getMemInstValueType(), llvm::LoopVectorizationCostModel::getWideningDecision(), llvm::LinearPolySize< LeafTy >::isScalable(), LI, reverseVector(), llvm::VPTransformState::set(), setDebugLocFromInst(), llvm::GetElementPtrInst::setIsInBounds(), SI, UF, and VF.
Referenced by llvm::VPWidenMemoryInstructionRecipe::execute().
widenCallInstruction()
void InnerLoopVectorizer::widenCallInstruction (CallInst & I, VPValue * Def, VPUser & ArgOperands, VPTransformState & State)
Widen a single call instruction within the innermost loop.
Definition at line 4876 of file LoopVectorize.cpp.
References addMetadata(), Arg, llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), Builder, llvm::Instruction::copyFastMathFlags(), Cost, llvm::IRBuilderBase::CreateCall(), llvm::tgtok::Def, llvm::enumerate(), llvm::VFShape::get(), llvm::VectorType::get(), llvm::VPTransformState::get(), llvm::Intrinsic::getDeclaration(), llvm::LinearPolySize< LeafTy >::getKnownMinValue(), llvm::LoopVectorizationCostModel::getVectorCallCost(), llvm::LoopVectorizationCostModel::getVectorIntrinsicCost(), llvm::getVectorIntrinsicIDForCall(), llvm::VFDatabase::getVectorizedFunction(), llvm::hasVectorInstrinsicScalarOpd(), I, llvm::LinearPolySize< LeafTy >::isScalable(), llvm::InstructionCost::isValid(), llvm::ElementCount::isVector(), llvm::VPUser::operands(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::VPTransformState::set(), setDebugLocFromInst(), TLI, llvm::ToVectorTy(), UF, and VF.
Referenced by llvm::VPWidenCallRecipe::execute().
widenGEP()
void InnerLoopVectorizer::widenGEP (GetElementPtrInst * GEP, VPValue * VPDef, VPUser & Indices, unsigned UF, ElementCount VF, bool IsPtrLoopInvariant, SmallBitVector & IsIndexLoopInvariant, VPTransformState & State)
Vectorize a single GetElementPtrInst based on information gathered and decisions taken during planning.
Definition at line 4507 of file LoopVectorize.cpp.
References addMetadata(), llvm::SmallBitVector::all(), assert(), Builder, llvm::IRBuilderBase::CreateGEP(), llvm::IRBuilderBase::CreateInBoundsGEP(), llvm::IRBuilderBase::CreateVectorSplat(), E, GEP, llvm::VPTransformState::get(), I, llvm::IRBuilderBase::Insert(), llvm::ElementCount::isScalar(), llvm::ElementCount::isVector(), Operands, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::VPTransformState::set(), UF, and VF.
Referenced by llvm::VPWidenGEPRecipe::execute().
widenInstruction()
void InnerLoopVectorizer::widenInstruction (Instruction & I, VPValue * Def, VPUser & Operands, VPTransformState & State)
Widen a single instruction within the innermost loop.
Vectorize casts.
Definition at line 4768 of file LoopVectorize.cpp.
References llvm::MCID::Add, addMetadata(), B, Builder, C, llvm::MCID::Call, llvm::IRBuilderBase::CreateCast(), llvm::IRBuilderBase::CreateFCmp(), llvm::IRBuilderBase::CreateICmp(), llvm::IRBuilderBase::CreateNAryOp(), llvm::dbgs(), llvm::tgtok::Def, llvm::VectorType::get(), llvm::VPTransformState::get(), llvm::User::getOperand(), I, llvm::ElementCount::isScalar(), LLVM_DEBUG, llvm_unreachable, llvm::User::operands(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::MCID::Select, llvm::VPTransformState::set(), setDebugLocFromInst(), llvm::IRBuilderBase::setFastMathFlags(), UF, and VF.
Referenced by llvm::VPWidenRecipe::execute().
widenIntOrFpInduction()
void InnerLoopVectorizer::widenIntOrFpInduction (PHINode * IV, Value * Start, TruncInst * Trunc = nullptr)
Widen an integer or floating-point induction variable IV.
If Trunc is provided, the integer induction variable will first be truncated to the corresponding type.
Definition at line 2146 of file LoopVectorize.cpp.
Referenced by llvm::VPWidenIntOrFpInductionRecipe::execute().
widenPHIInstruction()
void InnerLoopVectorizer::widenPHIInstruction (Instruction * PN, RecurrenceDescriptor * RdxDesc, Value * StartV, unsigned UF, ElementCount VF)
Vectorize a single PHINode in a block.
This method handles the induction variable canonicalization. It supports both VF = 1 for unrolled loops and arbitrary length vectors.
Definition at line 4577 of file LoopVectorize.cpp.
References llvm::PHINode::addIncoming(), assert(), Builder, Cost, llvm::MapVector< KeyT, ValueT, MapType, VectorType >::count(), llvm::GetElementPtrInst::Create(), llvm::PHINode::Create(), llvm::IRBuilderBase::CreateAdd(), llvm::IRBuilderBase::CreateGEP(), llvm::IRBuilderBase::CreateInsertElement(), llvm::IRBuilderBase::CreateMul(), llvm::IRBuilderBase::CreatePHI(), llvm::IRBuilderBase::CreateSExtOrTrunc(), llvm::IRBuilderBase::CreateVectorSplat(), DL, emitTransformedIndex(), EnableVPlanNativePath, GEP, llvm::ConstantVector::get(), llvm::VectorType::get(), llvm::ConstantInt::get(), llvm::Module::getDataLayout(), llvm::BasicBlock::getFirstInsertionPt(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopVectorizationLegality::getInductionVars(), llvm::IRBuilderBase::getInt32(), llvm::InductionDescriptor::getKind(), llvm::LinearPolySize< LeafTy >::getKnownMinValue(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::BasicBlock::getModule(), llvm::User::getNumOperands(), llvm::Instruction::getParent(), llvm::Type::getPointerElementType(), llvm::RecurrenceDescriptor::getRecurrenceIdentity(), llvm::RecurrenceDescriptor::getRecurrenceKind(), llvm::Type::getScalarType(), llvm::PredicatedScalarEvolution::getSE(), llvm::ConstantVector::getSplat(), llvm::InductionDescriptor::getStartValue(), llvm::InductionDescriptor::getStep(), llvm::BasicBlock::getTerminator(), llvm::SCEV::getType(), llvm::Value::getType(), llvm::InductionDescriptor::IK_FpInduction, llvm::InductionDescriptor::IK_IntInduction, llvm::InductionDescriptor::IK_NoInduction, llvm::InductionDescriptor::IK_PtrInduction, Induction, llvm::LoopVectorizationLegality::isFirstOrderRecurrence(), llvm::LoopVectorizationCostModel::isInLoopReduction(), llvm::RecurrenceDescriptor::isMinMaxRecurrenceKind(), llvm::LoopVectorizationLegality::isReductionVariable(), llvm::LinearPolySize< LeafTy >::isScalable(), llvm::ElementCount::isScalar(), llvm::LoopVectorizationCostModel::isScalarAfterVectorization(), llvm::LoopVectorizationCostModel::isUniformAfterVectorization(), Legal, LI, llvm_unreachable, llvm::MapVector< KeyT, ValueT, MapType, VectorType >::lookup(), LoopVectorBody, LoopVectorPreHeader, OrigLoop, OrigPHIsToFix, P, PSE, llvm::SmallVectorTemplateBase< T, bool >::push_back(), setDebugLocFromInst(), llvm::IRBuilderBase::SetInsertPoint(), llvm::Value::setName(), llvm::VectorizerValueMap::setScalarValue(), llvm::VectorizerValueMap::setVectorValue(), UF, VectorLoopValueMap, and VF.
Referenced by llvm::VPWidenPHIRecipe::execute().
widenSelectInstruction()
void InnerLoopVectorizer::widenSelectInstruction (SelectInst & I, VPValue * VPDef, VPUser & Operands, bool InvariantCond, VPTransformState & State)
Widen a single select instruction within the innermost loop.
Definition at line 4948 of file LoopVectorize.cpp.
References addMetadata(), Builder, Cond, llvm::IRBuilderBase::CreateSelect(), llvm::VPTransformState::get(), I, Operands, llvm::VPTransformState::set(), setDebugLocFromInst(), and UF.
Referenced by llvm::VPWidenSelectRecipe::execute().
Friends And Related Function Documentation
LoopVectorizationPlanner
friend class LoopVectorizationPlanner friend
Definition at line 594 of file LoopVectorize.cpp.
Member Data Documentation
AA
AAResults* llvm::InnerLoopVectorizer::AA protected
Alias Analysis.
Definition at line 800 of file LoopVectorize.cpp.
AC
AssumptionCache* llvm::InnerLoopVectorizer::AC protected
Assumption Cache.
Definition at line 809 of file LoopVectorize.cpp.
Referenced by llvm::LoopVectorizationCostModel::collectValuesToIgnore(), getScalarEpilogueLowering(), processLoopInVPlanNativePath(), and scalarizeInstruction().
AddedSafetyChecks
bool llvm::InnerLoopVectorizer::AddedSafetyChecks = false protected
Definition at line 884 of file LoopVectorize.cpp.
Referenced by areSafetyChecksAdded(), emitMemRuntimeChecks(), and emitSCEVChecks().
BFI
BlockFrequencyInfo* llvm::InnerLoopVectorizer::BFI protected
BFI and PSI are used to check for profile guided size optimizations.
Definition at line 895 of file LoopVectorize.cpp.
Referenced by getScalarEpilogueLowering(), InnerLoopVectorizer(), and processLoopInVPlanNativePath().
Builder
IRBuilder llvm::InnerLoopVectorizer::Builder protected
The builder that we use.
Definition at line 830 of file LoopVectorize.cpp.
Referenced by buildScalarSteps(), completeLoopSkeleton(), createBitOrPointerCast(), llvm::VPRecipeBuilder::createBlockInMask(), llvm::VPRecipeBuilder::createEdgeMask(), createVectorizedLoopSkeleton(), createVectorLoopSkeleton(), emitMemRuntimeChecks(), emitMinimumIterationCountCheck(), llvm::EpilogueVectorizerMainLoop::emitMinimumIterationCountCheck(), llvm::EpilogueVectorizerEpilogueLoop::emitMinimumVectorEpilogueIterCountCheck(), llvm::LoopVectorizationPlanner::executePlan(), fixFirstOrderRecurrence(), fixLCSSAPHIs(), fixNonInductionPHIs(), fixReduction(), getBroadcastInstrs(), getOrCreateScalarValue(), getOrCreateTripCount(), getOrCreateVectorTripCount(), getOrCreateVectorValue(), getStepVector(), packScalarIntoVectorValue(), reverseVector(), scalarizeInstruction(), vectorizeInterleaveGroup(), vectorizeMemoryInstruction(), widenCallInstruction(), widenGEP(), widenInstruction(), widenPHIInstruction(), and widenSelectInstruction().
Cost
LoopVectorizationCostModel* llvm::InnerLoopVectorizer::Cost protected
The profitablity analysis.
Definition at line 881 of file LoopVectorize.cpp.
Referenced by buildScalarSteps(), completeLoopSkeleton(), emitMemRuntimeChecks(), emitMinimumIterationCountCheck(), llvm::EpilogueVectorizerMainLoop::emitMinimumIterationCountCheck(), llvm::EpilogueVectorizerEpilogueLoop::emitMinimumVectorEpilogueIterCountCheck(), emitSCEVChecks(), fixLCSSAPHIs(), fixReduction(), getOrCreateScalarValue(), getOrCreateVectorTripCount(), getOrCreateVectorValue(), llvm::LoopVectorizationCostModel::getVectorCallCost(), scalarizeInstruction(), llvm::LoopVectorizationCostModel::selectVectorizationFactor(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), llvm::LoopVectorizationCostModel::setWideningDecision(), shouldScalarizeInstruction(), truncateToMinimalBitwidths(), vectorizeInterleaveGroup(), vectorizeMemoryInstruction(), widenCallInstruction(), and widenPHIInstruction().
DT
DominatorTree* llvm::InnerLoopVectorizer::DT protected
Dominator Tree.
Definition at line 797 of file LoopVectorize.cpp.
Referenced by completeLoopSkeleton(), llvm::EpilogueVectorizerEpilogueLoop::createEpilogueVectorizedLoopSkeleton(), createVectorLoopSkeleton(), emitMemRuntimeChecks(), emitMinimumIterationCountCheck(), llvm::EpilogueVectorizerMainLoop::emitMinimumIterationCountCheck(), llvm::EpilogueVectorizerEpilogueLoop::emitMinimumVectorEpilogueIterCountCheck(), emitSCEVChecks(), llvm::LoopVectorizationPlanner::executePlan(), getBroadcastInstrs(), getScalarEpilogueLowering(), and processLoopInVPlanNativePath().
Induction
PHINode* llvm::InnerLoopVectorizer::Induction = nullptr protected
The new Induction variable which was added to the new block.
Definition at line 857 of file LoopVectorize.cpp.
Referenced by llvm::LoopVectorizationPlanner::collectTriviallyDeadInstructions(), llvm::LoopVectorizationCostModel::collectValuesToIgnore(), llvm::EpilogueVectorizerMainLoop::createEpilogueVectorizedLoopSkeleton(), llvm::EpilogueVectorizerEpilogueLoop::createEpilogueVectorizedLoopSkeleton(), createVectorizedLoopSkeleton(), llvm::LoopVectorizationPlanner::executePlan(), getOrCreateVectorValue(), packScalarIntoVectorValue(), llvm::EpilogueVectorizerMainLoop::printDebugTracesAtEnd(), llvm::EpilogueVectorizerEpilogueLoop::printDebugTracesAtEnd(), and widenPHIInstruction().
IVEndValues
DenseMap<PHINode *, Value *> llvm::InnerLoopVectorizer::IVEndValues protected
Definition at line 888 of file LoopVectorize.cpp.
Referenced by createInductionResumeValues().
Legal
LoopVectorizationLegality* llvm::InnerLoopVectorizer::Legal protected
The legality analysis.
Definition at line 878 of file LoopVectorize.cpp.
Referenced by llvm::LoopVectorizationCostModel::blockNeedsPredication(), llvm::LoopVectorizationCostModel::collectInLoopReductions(), llvm::LoopVectorizationPlanner::collectTriviallyDeadInstructions(), llvm::LoopVectorizationCostModel::collectValuesToIgnore(), llvm::LoopVectorizationCostModel::computeMaxVF(), llvm::VPRecipeBuilder::createBlockInMask(), llvm::EpilogueVectorizerMainLoop::createEpilogueVectorizedLoopSkeleton(), llvm::EpilogueVectorizerEpilogueLoop::createEpilogueVectorizedLoopSkeleton(), createInductionResumeValues(), createVectorizedLoopSkeleton(), emitMemRuntimeChecks(), fixCrossIterationPHIs(), fixReduction(), getAddressAccessSCEV(), getOrCreateTripCount(), getOrCreateVectorValue(), llvm::LoopVectorizationCostModel::getSmallestAndWidestTypes(), llvm::LoopVectorizationCostModel::interleavedAccessCanBeWidened(), llvm::LoopVectorizationCostModel::isLegalMaskedLoad(), llvm::LoopVectorizationCostModel::isLegalMaskedStore(), llvm::LoopVectorizationCostModel::isOptimizableIVTruncate(), llvm::LoopVectorizationCostModel::isPredicatedInst(), llvm::LoopVectorizationCostModel::isScalarWithPredication(), isStrideMul(), llvm::LoopVectorizationCostModel::memoryInstructionCanBeWidened(), llvm::LoopVectorizationCostModel::runtimeChecksRequired(), llvm::LoopVectorizationCostModel::selectInterleaveCount(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), llvm::VPRecipeBuilder::tryToCreateWidenRecipe(), and widenPHIInstruction().
LI
LoopInfo* llvm::InnerLoopVectorizer::LI protected
Loop Info.
Definition at line 794 of file LoopVectorize.cpp.
Referenced by llvm::LoopVectorizationCostModel::calculateRegisterUsage(), collectSupportedLoops(), completeLoopSkeleton(), llvm::EpilogueVectorizerEpilogueLoop::createEpilogueVectorizedLoopSkeleton(), createVectorLoopSkeleton(), emitMemRuntimeChecks(), emitMinimumIterationCountCheck(), llvm::EpilogueVectorizerMainLoop::emitMinimumIterationCountCheck(), emitSCEVChecks(), emitTransformedIndex(), llvm::LoopVectorizationPlanner::executePlan(), fixFirstOrderRecurrence(), fixReduction(), getScalarEpilogueLowering(), llvm::LoopVectorizationCostModel::isLegalGatherOrScatter(), llvm::LoopVectorizationCostModel::memoryInstructionCanBeWidened(), processLoopInVPlanNativePath(), sinkScalarOperands(), vectorizeMemoryInstruction(), and widenPHIInstruction().
LoopBypassBlocks
SmallVector<BasicBlock *, 4> llvm::InnerLoopVectorizer::LoopBypassBlocks protected
A list of all bypass blocks. The first block is the entry of the loop.
Definition at line 854 of file LoopVectorize.cpp.
Referenced by llvm::EpilogueVectorizerEpilogueLoop::createEpilogueVectorizedLoopSkeleton(), createInductionResumeValues(), emitMemRuntimeChecks(), emitMinimumIterationCountCheck(), llvm::EpilogueVectorizerMainLoop::emitMinimumIterationCountCheck(), llvm::EpilogueVectorizerEpilogueLoop::emitMinimumVectorEpilogueIterCountCheck(), emitSCEVChecks(), and fixReduction().
LoopExitBlock
BasicBlock* llvm::InnerLoopVectorizer::LoopExitBlock protected
The (unique) ExitBlock of the scalar loop.
Note that there can be multiple exiting edges reaching this block.
Definition at line 845 of file LoopVectorize.cpp.
Referenced by llvm::EpilogueVectorizerEpilogueLoop::createEpilogueVectorizedLoopSkeleton(), createVectorLoopSkeleton(), emitMemRuntimeChecks(), emitMinimumIterationCountCheck(), llvm::EpilogueVectorizerMainLoop::emitMinimumIterationCountCheck(), emitSCEVChecks(), fixLCSSAPHIs(), and fixReduction().
LoopMiddleBlock
BasicBlock* llvm::InnerLoopVectorizer::LoopMiddleBlock protected
Middle Block between the vector and the scalar.
Definition at line 841 of file LoopVectorize.cpp.
Referenced by completeLoopSkeleton(), createInductionResumeValues(), createVectorLoopSkeleton(), fixFirstOrderRecurrence(), fixLCSSAPHIs(), and fixReduction().
LoopScalarBody
BasicBlock* llvm::InnerLoopVectorizer::LoopScalarBody protected
The scalar loop body.
Definition at line 851 of file LoopVectorize.cpp.
Referenced by createInductionResumeValues(), and createVectorLoopSkeleton().
LoopScalarPreHeader
BasicBlock* llvm::InnerLoopVectorizer::LoopScalarPreHeader protected
The scalar-loop preheader.
Definition at line 838 of file LoopVectorize.cpp.
Referenced by llvm::EpilogueVectorizerMainLoop::createEpilogueVectorizedLoopSkeleton(), llvm::EpilogueVectorizerEpilogueLoop::createEpilogueVectorizedLoopSkeleton(), createInductionResumeValues(), createVectorizedLoopSkeleton(), createVectorLoopSkeleton(), fixFirstOrderRecurrence(), and fixReduction().
LoopVectorBody
BasicBlock* llvm::InnerLoopVectorizer::LoopVectorBody protected
The vector loop body.
Definition at line 848 of file LoopVectorize.cpp.
Referenced by completeLoopSkeleton(), createVectorLoopSkeleton(), emitTransformedIndex(), fixFirstOrderRecurrence(), fixReduction(), and widenPHIInstruction().
LoopVectorPreHeader
BasicBlock* llvm::InnerLoopVectorizer::LoopVectorPreHeader protected
The vector-loop preheader.
Definition at line 835 of file LoopVectorize.cpp.
Referenced by completeLoopSkeleton(), llvm::EpilogueVectorizerMainLoop::createEpilogueVectorizedLoopSkeleton(), llvm::EpilogueVectorizerEpilogueLoop::createEpilogueVectorizedLoopSkeleton(), createVectorLoopSkeleton(), emitMemRuntimeChecks(), emitMinimumIterationCountCheck(), llvm::EpilogueVectorizerMainLoop::emitMinimumIterationCountCheck(), llvm::EpilogueVectorizerEpilogueLoop::emitMinimumVectorEpilogueIterCountCheck(), emitSCEVChecks(), fixFirstOrderRecurrence(), getBroadcastInstrs(), and widenPHIInstruction().
LVer
std::unique_ptr<LoopVersioning> llvm::InnerLoopVectorizer::LVer protected
LoopVersioning.
It's only set up (non-null) if memchecks were used.
This is currently only used to add no-alias metadata based on the memchecks. The actually versioning is performed manually.
Definition at line 819 of file LoopVectorize.cpp.
Referenced by addNewMetadata(), and emitMemRuntimeChecks().
OldInduction
PHINode* llvm::InnerLoopVectorizer::OldInduction = nullptr protected
The induction variable of the old basic block.
Definition at line 860 of file LoopVectorize.cpp.
Referenced by llvm::EpilogueVectorizerMainLoop::createEpilogueVectorizedLoopSkeleton(), llvm::EpilogueVectorizerEpilogueLoop::createEpilogueVectorizedLoopSkeleton(), createInductionResumeValues(), and createVectorizedLoopSkeleton().
OptForSizeBasedOnProfile
bool llvm::InnerLoopVectorizer::OptForSizeBasedOnProfile protected
Definition at line 900 of file LoopVectorize.cpp.
Referenced by emitMemRuntimeChecks(), emitSCEVChecks(), and InnerLoopVectorizer().
ORE
OptimizationRemarkEmitter* llvm::InnerLoopVectorizer::ORE protected
Interface to emit optimization remarks.
Definition at line 812 of file LoopVectorize.cpp.
Referenced by collectSupportedLoops(), completeLoopSkeleton(), llvm::LoopVectorizationCostModel::computeMaxVF(), emitMemRuntimeChecks(), isExplicitVecOuterLoop(), processLoopInVPlanNativePath(), llvm::reportVectorizationFailure(), llvm::LoopVectorizationCostModel::runtimeChecksRequired(), and llvm::LoopVectorizationCostModel::selectVectorizationFactor().
OrigLoop
Loop* llvm::InnerLoopVectorizer::OrigLoop protected
The original loop.
Definition at line 786 of file LoopVectorize.cpp.
Referenced by clearReductionWrapFlags(), llvm::LoopVectorizationPlanner::collectTriviallyDeadInstructions(), completeLoopSkeleton(), llvm::VPRecipeBuilder::createBlockInMask(), llvm::VPRecipeBuilder::createEdgeMask(), llvm::EpilogueVectorizerMainLoop::createEpilogueVectorizedLoopSkeleton(), llvm::EpilogueVectorizerEpilogueLoop::createEpilogueVectorizedLoopSkeleton(), createVectorizedLoopSkeleton(), createVectorLoopSkeleton(), emitMemRuntimeChecks(), llvm::LoopVectorizationPlanner::executePlan(), fixCrossIterationPHIs(), fixFirstOrderRecurrence(), fixReduction(), fixupIVUsers(), fixVectorizedLoop(), getBroadcastInstrs(), getOrCreateScalarValue(), InnerLoopVectorizer(), needsScalarInduction(), llvm::LoopVectorizationPlanner::plan(), llvm::LoopVectorizationPlanner::planInVPlanNativePath(), scalarizeInstruction(), llvm::VPRecipeBuilder::tryToCreateWidenRecipe(), and widenPHIInstruction().
OrigPHIsToFix
SmallVector<PHINode *, 8> llvm::InnerLoopVectorizer::OrigPHIsToFix protected
Definition at line 892 of file LoopVectorize.cpp.
Referenced by fixNonInductionPHIs(), fixVectorizedLoop(), and widenPHIInstruction().
PredicatedInstructions
SmallVector<Instruction *, 4> llvm::InnerLoopVectorizer::PredicatedInstructions protected
Store instructions that were predicated.
Definition at line 869 of file LoopVectorize.cpp.
Referenced by scalarizeInstruction().
PSE
PredicatedScalarEvolution& llvm::InnerLoopVectorizer::PSE protected
A wrapper around ScalarEvolution used to add runtime SCEV checks.
Applies dynamic knowledge to simplify SCEV expressions and converts them to a more usable form.
Definition at line 791 of file LoopVectorize.cpp.
Referenced by llvm::LoopVectorizationCostModel::computeMaxVF(), createInductionResumeValues(), emitMemRuntimeChecks(), emitSCEVChecks(), fixupIVUsers(), fixVectorizedLoop(), getAddressAccessSCEV(), getOrCreateTripCount(), processLoopInVPlanNativePath(), llvm::LoopVectorizationCostModel::runtimeChecksRequired(), llvm::LoopVectorizationCostModel::selectInterleaveCount(), llvm::VPRecipeBuilder::tryToCreateWidenRecipe(), and widenPHIInstruction().
PSI
ProfileSummaryInfo* llvm::InnerLoopVectorizer::PSI protected
Definition at line 896 of file LoopVectorize.cpp.
Referenced by getScalarEpilogueLowering(), InnerLoopVectorizer(), and processLoopInVPlanNativePath().
TLI
const TargetLibraryInfo* llvm::InnerLoopVectorizer::TLI protected
Target Library Info.
Definition at line 803 of file LoopVectorize.cpp.
Referenced by getScalarEpilogueLowering(), llvm::LoopVectorizationCostModel::getVectorCallCost(), llvm::LoopVectorizationCostModel::getVectorIntrinsicCost(), processLoopInVPlanNativePath(), and widenCallInstruction().
TripCount
Value* llvm::InnerLoopVectorizer::TripCount = nullptr protected
Trip count of the original loop.
Definition at line 872 of file LoopVectorize.cpp.
Referenced by getOrCreateTripCount().
TTI
const TargetTransformInfo* llvm::InnerLoopVectorizer::TTI protected
Target Transform Info.
Definition at line 806 of file LoopVectorize.cpp.
Referenced by llvm::LoopVectorizationCostModel::calculateRegisterUsage().
UF
unsigned llvm::InnerLoopVectorizer::UF protected
The vectorization unroll factor to use.
Each scalar is vectorized to this many different vector instructions.
Definition at line 827 of file LoopVectorize.cpp.
Referenced by buildScalarSteps(), clearReductionWrapFlags(), llvm::EpilogueVectorizerMainLoop::createEpilogueVectorizedLoopSkeleton(), llvm::EpilogueVectorizerEpilogueLoop::createEpilogueVectorizedLoopSkeleton(), createVectorizedLoopSkeleton(), emitMinimumIterationCountCheck(), llvm::EpilogueVectorizerMainLoop::emitMinimumIterationCountCheck(), fixFirstOrderRecurrence(), fixLCSSAPHIs(), fixReduction(), getOrCreateVectorTripCount(), llvm::LoopVectorizationPlanner::setBestPlan(), setDebugLocFromInst(), truncateToMinimalBitwidths(), vectorizeInterleaveGroup(), vectorizeMemoryInstruction(), widenCallInstruction(), widenGEP(), widenInstruction(), widenPHIInstruction(), and widenSelectInstruction().
VectorLoopValueMap
VectorizerValueMap llvm::InnerLoopVectorizer::VectorLoopValueMap protected
Maps values from the original loop to their corresponding values in the vectorized loop.
A key value can map to either vector values, scalar values or both kinds of values, depending on whether the key was vectorized and scalarized.
Definition at line 866 of file LoopVectorize.cpp.
Referenced by buildScalarSteps(), llvm::LoopVectorizationPlanner::executePlan(), fixFirstOrderRecurrence(), fixNonInductionPHIs(), fixReduction(), getOrCreateScalarValue(), getOrCreateVectorValue(), packScalarIntoVectorValue(), recordVectorLoopValueForInductionCast(), scalarizeInstruction(), setVectorValue(), truncateToMinimalBitwidths(), and widenPHIInstruction().
VectorTripCount
Value* llvm::InnerLoopVectorizer::VectorTripCount = nullptr protected
Trip count of the widened loop (TripCount - TripCount % (VF*UF))
Definition at line 875 of file LoopVectorize.cpp.
Referenced by completeLoopSkeleton(), createInductionResumeValues(), and getOrCreateVectorTripCount().
VF
ElementCount llvm::InnerLoopVectorizer::VF protected
The vectorization SIMD factor to use.
Each vector will have this many vector elements.
Definition at line 823 of file LoopVectorize.cpp.
Referenced by buildScalarSteps(), llvm::LoopVectorizationPlanner::buildVPlans(), llvm::LoopVectorizationCostModel::calculateRegisterUsage(), llvm::LoopVectorizationCostModel::canTruncateToMinimalBitwidth(), llvm::LoopVectorizationCostModel::collectInstsToScalarize(), llvm::LoopVectorizationCostModel::collectUniformsAndScalars(), createBitOrPointerCast(), llvm::EpilogueVectorizerMainLoop::createEpilogueVectorizedLoopSkeleton(), llvm::EpilogueVectorizerEpilogueLoop::createEpilogueVectorizedLoopSkeleton(), createStepForVF(), createVectorizedLoopSkeleton(), emitMinimumIterationCountCheck(), llvm::EpilogueVectorizerMainLoop::emitMinimumIterationCountCheck(), fixFirstOrderRecurrence(), fixLCSSAPHIs(), fixReduction(), fixVectorizedLoop(), getBroadcastInstrs(), getOrCreateScalarValue(), getOrCreateVectorTripCount(), getOrCreateVectorValue(), llvm::LoopVectorizationCostModel::getVectorCallCost(), llvm::LoopVectorizationCostModel::getVectorIntrinsicCost(), llvm::LoopVectorizationCostModel::getWideningCost(), llvm::LoopVectorizationCostModel::getWideningDecision(), llvm::VPRecipeBuilder::handleReplication(), llvm::LoopVectorizationCostModel::interleavedAccessCanBeWidened(), llvm::LoopVectorizationCostModel::isOptimizableIVTruncate(), llvm::LoopVectorizationCostModel::isProfitableToScalarize(), llvm::LoopVectorizationCostModel::isScalarAfterVectorization(), llvm::LoopVectorizationCostModel::isScalarWithPredication(), llvm::LoopVectorizationCostModel::isUniformAfterVectorization(), llvm::LoopVectorizationPlanner::plan(), llvm::LoopVectorizationPlanner::planInVPlanNativePath(), processLoopInVPlanNativePath(), reverseVector(), llvm::LoopVectorizationCostModel::selectInterleaveCount(), llvm::LoopVectorizationPlanner::setBestPlan(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), setDebugLocFromInst(), llvm::LoopVectorizationCostModel::setWideningDecision(), shouldScalarizeInstruction(), vectorizeInterleaveGroup(), vectorizeMemoryInstruction(), widenCallInstruction(), widenGEP(), widenInstruction(), and widenPHIInstruction().
The documentation for this class was generated from the following file:
lib/Transforms/Vectorize/LoopVectorize.cpp