LLVM: llvm::ThreadPoolStrategy Class Reference
llvm::ThreadPoolStrategy Class Reference
This tells how a thread pool will be used.
#include "llvm/Support/Threading.h"
Public Member Functions
unsigned compute_thread_count () const
Retrieves the max available threads for the current strategy.
void apply_thread_strategy (unsigned ThreadPoolNum) const
Assign the current thread to an ideal hardware CPU or NUMA node.
Optional< unsigned > compute_cpu_socket (unsigned ThreadPoolNum) const
Finds the CPU socket where a thread should go.
Public Attributes
unsigned ThreadsRequested = 0
bool UseHyperThreads = true
bool Limit = false
Detailed Description
This tells how a thread pool will be used.
Definition at line 148 of file Threading.h.
Member Function Documentation
apply_thread_strategy()
void llvm::ThreadPoolStrategy::apply_thread_strategy (unsigned ThreadPoolNum) const
Assign the current thread to an ideal hardware CPU or NUMA node.
In a multi-socket system, this ensures threads are assigned to all CPU sockets. ThreadPoolNum represents a number bounded by [0, compute_thread_count()).
Referenced by llvm::ThreadPool::ThreadPool().
compute_cpu_socket()
Optional<unsigned> llvm::ThreadPoolStrategy::compute_cpu_socket (unsigned ThreadPoolNum) const
Finds the CPU socket where a thread should go.
Returns 'None' if the thread shall remain on the actual CPU socket.
compute_thread_count()
unsigned llvm::ThreadPoolStrategy::compute_thread_count () const
Retrieves the max available threads for the current strategy.
This accounts for affinity masks and takes advantage of all CPU sockets.
Definition at line 86 of file Threading.cpp.
References computeHostNumHardwareThreads(), llvm::sys::getHostNumPhysicalCores(), and llvm::min().
Member Data Documentation
Limit
bool llvm::ThreadPoolStrategy::Limit = false
Definition at line 162 of file Threading.h.
Referenced by llvm::optimal_concurrency().
ThreadsRequested
unsigned llvm::ThreadPoolStrategy::ThreadsRequested = 0
Definition at line 154 of file Threading.h.
Referenced by llvm::get_threadpool_strategy(), llvm::hardware_concurrency(), llvm::heavyweight_hardware_concurrency(), and llvm::optimal_concurrency().
UseHyperThreads
bool llvm::ThreadPoolStrategy::UseHyperThreads = true
Definition at line 158 of file Threading.h.
Referenced by llvm::heavyweight_hardware_concurrency().
The documentation for this class was generated from the following files:
include/llvm/Support/Threading.h
lib/Support/Threading.cpp