LLVM: llvm::orc::TargetProcessControl::MemoryAccess Class Reference
llvm::orc::TargetProcessControl::MemoryAccess Class Reference abstract
APIs for manipulating memory in the target process.
#include "llvm/ExecutionEngine/Orc/TargetProcessControl.h"
Public Types
using WriteResultFn = unique_function< void(Error)>
Callback function for asynchronous writes.
Public Member Functions
virtual ~MemoryAccess ()
virtual void writeUInt8s (ArrayRef< tpctypes::UInt8Write > Ws, WriteResultFn OnWriteComplete)=0
virtual void writeUInt16s (ArrayRef< tpctypes::UInt16Write > Ws, WriteResultFn OnWriteComplete)=0
virtual void writeUInt32s (ArrayRef< tpctypes::UInt32Write > Ws, WriteResultFn OnWriteComplete)=0
virtual void writeUInt64s (ArrayRef< tpctypes::UInt64Write > Ws, WriteResultFn OnWriteComplete)=0
virtual void writeBuffers (ArrayRef< tpctypes::BufferWrite > Ws, WriteResultFn OnWriteComplete)=0
Error writeUInt8s (ArrayRef< tpctypes::UInt8Write > Ws)
Error writeUInt16s (ArrayRef< tpctypes::UInt16Write > Ws)
Error writeUInt32s (ArrayRef< tpctypes::UInt32Write > Ws)
Error writeUInt64s (ArrayRef< tpctypes::UInt64Write > Ws)
Error writeBuffers (ArrayRef< tpctypes::BufferWrite > Ws)
Detailed Description
APIs for manipulating memory in the target process.
Definition at line 35 of file TargetProcessControl.h.
Member Typedef Documentation
WriteResultFn
using llvm::orc::TargetProcessControl::MemoryAccess::WriteResultFn = unique_function<void(Error)>
Callback function for asynchronous writes.
Definition at line 38 of file TargetProcessControl.h.
Constructor & Destructor Documentation
~MemoryAccess()
llvm::orc::TargetProcessControl::MemoryAccess::~MemoryAccess () virtual
Definition at line 21 of file TargetProcessControl.cpp.
Member Function Documentation
writeBuffers() [1/2]
Error llvm::orc::TargetProcessControl::MemoryAccess::writeBuffers (ArrayRef< tpctypes::BufferWrite > Ws) inline
Definition at line 85 of file TargetProcessControl.h.
References writeBuffers().
writeBuffers() [2/2]
virtual void llvm::orc::TargetProcessControl::MemoryAccess::writeBuffers (ArrayRef< tpctypes::BufferWrite > Ws, WriteResultFn OnWriteComplete) pure virtual
Implemented in llvm::orc::OrcRPCTPCMemoryAccess< OrcRPCTPCImplT >.
Referenced by writeBuffers().
writeUInt16s() [1/2]
Error llvm::orc::TargetProcessControl::MemoryAccess::writeUInt16s (ArrayRef< tpctypes::UInt16Write > Ws) inline
Definition at line 64 of file TargetProcessControl.h.
References writeUInt16s().
writeUInt16s() [2/2]
virtual void llvm::orc::TargetProcessControl::MemoryAccess::writeUInt16s (ArrayRef< tpctypes::UInt16Write > Ws, WriteResultFn OnWriteComplete) pure virtual
Implemented in llvm::orc::OrcRPCTPCMemoryAccess< OrcRPCTPCImplT >.
Referenced by writeUInt16s().
writeUInt32s() [1/2]
Error llvm::orc::TargetProcessControl::MemoryAccess::writeUInt32s (ArrayRef< tpctypes::UInt32Write > Ws) inline
Definition at line 71 of file TargetProcessControl.h.
References writeUInt32s().
writeUInt32s() [2/2]
virtual void llvm::orc::TargetProcessControl::MemoryAccess::writeUInt32s (ArrayRef< tpctypes::UInt32Write > Ws, WriteResultFn OnWriteComplete) pure virtual
Implemented in llvm::orc::OrcRPCTPCMemoryAccess< OrcRPCTPCImplT >.
Referenced by writeUInt32s().
writeUInt64s() [1/2]
Error llvm::orc::TargetProcessControl::MemoryAccess::writeUInt64s (ArrayRef< tpctypes::UInt64Write > Ws) inline
Definition at line 78 of file TargetProcessControl.h.
References writeUInt64s().
writeUInt64s() [2/2]
virtual void llvm::orc::TargetProcessControl::MemoryAccess::writeUInt64s (ArrayRef< tpctypes::UInt64Write > Ws, WriteResultFn OnWriteComplete) pure virtual
Implemented in llvm::orc::OrcRPCTPCMemoryAccess< OrcRPCTPCImplT >.
Referenced by writeUInt64s().
writeUInt8s() [1/2]
Error llvm::orc::TargetProcessControl::MemoryAccess::writeUInt8s (ArrayRef< tpctypes::UInt8Write > Ws) inline
Definition at line 57 of file TargetProcessControl.h.
References writeUInt8s().
writeUInt8s() [2/2]
virtual void llvm::orc::TargetProcessControl::MemoryAccess::writeUInt8s (ArrayRef< tpctypes::UInt8Write > Ws, WriteResultFn OnWriteComplete) pure virtual
Implemented in llvm::orc::OrcRPCTPCMemoryAccess< OrcRPCTPCImplT >.
Referenced by writeUInt8s().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/TargetProcessControl.h
lib/ExecutionEngine/Orc/TargetProcessControl.cpp