LLVM: llvm::VerifierAnalysis Class Reference
llvm::VerifierAnalysis Class Reference
Check a module for errors, and report separate error states for IR and debug info errors.
#include "llvm/IR/Verifier.h"
Classes
struct Result
Public Member Functions
Result run (Module &M, ModuleAnalysisManager &)
Result run (Function &F, FunctionAnalysisManager &)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::AnalysisInfoMixin< VerifierAnalysis >
static AnalysisKey * ID ()
Returns an opaque, unique ID for this analysis type.
Static Public Member Functions inherited from llvm::PassInfoMixin< DerivedT >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Check a module for errors, and report separate error states for IR and debug info errors.
Definition at line 107 of file Verifier.h.
Member Function Documentation
isRequired()
static bool llvm::VerifierAnalysis::isRequired () inline static
Definition at line 119 of file Verifier.h.
run() [1/2]
VerifierAnalysis::Result VerifierAnalysis::run (Function & F, FunctionAnalysisManager &)
Definition at line 6043 of file Verifier.cpp.
References llvm::dbgs(), F, and llvm::verifyFunction().
run() [2/2]
VerifierAnalysis::Result VerifierAnalysis::run (Module & M, ModuleAnalysisManager &)
Definition at line 6036 of file Verifier.cpp.
References llvm::dbgs(), llvm::VerifierAnalysis::Result::DebugInfoBroken, llvm::VerifierAnalysis::Result::IRBroken, and llvm::verifyModule().
The documentation for this class was generated from the following files:
include/llvm/IR/Verifier.h
lib/IR/Verifier.cpp