LLVM: llvm::orc::OrcRPCTPCMemoryAccess< OrcRPCTPCImplT > Class Template Reference
llvm::orc::OrcRPCTPCMemoryAccess< OrcRPCTPCImplT > Class Template Reference
TargetProcessControl::MemoryAccess implementation for a process connected via an ORC RPC endpoint.
#include "llvm/ExecutionEngine/Orc/OrcRPCTargetProcessControl.h"
Public Member Functions
OrcRPCTPCMemoryAccess (OrcRPCTPCImplT &Parent)
void writeUInt8s (ArrayRef< tpctypes::UInt8Write > Ws, WriteResultFn OnWriteComplete) override
void writeUInt16s (ArrayRef< tpctypes::UInt16Write > Ws, WriteResultFn OnWriteComplete) override
void writeUInt32s (ArrayRef< tpctypes::UInt32Write > Ws, WriteResultFn OnWriteComplete) override
void writeUInt64s (ArrayRef< tpctypes::UInt64Write > Ws, WriteResultFn OnWriteComplete) override
void writeBuffers (ArrayRef< tpctypes::BufferWrite > Ws, WriteResultFn OnWriteComplete) override
Public Member Functions inherited from llvm::orc::TargetProcessControl::MemoryAccess
virtual ~MemoryAccess ()
Error writeUInt8s (ArrayRef< tpctypes::UInt8Write > Ws)
Error writeUInt16s (ArrayRef< tpctypes::UInt16Write > Ws)
Error writeUInt32s (ArrayRef< tpctypes::UInt32Write > Ws)
Error writeUInt64s (ArrayRef< tpctypes::UInt64Write > Ws)
Error writeBuffers (ArrayRef< tpctypes::BufferWrite > Ws)
Additional Inherited Members
Public Types inherited from llvm::orc::TargetProcessControl::MemoryAccess
using WriteResultFn = unique_function< void(Error)>
Callback function for asynchronous writes.
Detailed Description
template<typename OrcRPCTPCImplT>
class llvm::orc::OrcRPCTPCMemoryAccess< OrcRPCTPCImplT >
TargetProcessControl::MemoryAccess implementation for a process connected via an ORC RPC endpoint.
Definition at line 229 of file OrcRPCTargetProcessControl.h.
Constructor & Destructor Documentation
OrcRPCTPCMemoryAccess()
template<typename OrcRPCTPCImplT > llvm::orc::OrcRPCTPCMemoryAccess< OrcRPCTPCImplT >::OrcRPCTPCMemoryAccess (OrcRPCTPCImplT & Parent) inline
Definition at line 231 of file OrcRPCTargetProcessControl.h.
Member Function Documentation
writeBuffers()
template<typename OrcRPCTPCImplT > void llvm::orc::OrcRPCTPCMemoryAccess< OrcRPCTPCImplT >::writeBuffers (ArrayRef< tpctypes::BufferWrite > Ws, WriteResultFn OnWriteComplete) inline override virtual
Implements llvm::orc::TargetProcessControl::MemoryAccess.
Definition at line 253 of file OrcRPCTargetProcessControl.h.
References llvm::move().
writeUInt16s()
template<typename OrcRPCTPCImplT > void llvm::orc::OrcRPCTPCMemoryAccess< OrcRPCTPCImplT >::writeUInt16s (ArrayRef< tpctypes::UInt16Write > Ws, WriteResultFn OnWriteComplete) inline override virtual
Implements llvm::orc::TargetProcessControl::MemoryAccess.
Definition at line 238 of file OrcRPCTargetProcessControl.h.
References llvm::move().
writeUInt32s()
template<typename OrcRPCTPCImplT > void llvm::orc::OrcRPCTPCMemoryAccess< OrcRPCTPCImplT >::writeUInt32s (ArrayRef< tpctypes::UInt32Write > Ws, WriteResultFn OnWriteComplete) inline override virtual
Implements llvm::orc::TargetProcessControl::MemoryAccess.
Definition at line 243 of file OrcRPCTargetProcessControl.h.
References llvm::move().
writeUInt64s()
template<typename OrcRPCTPCImplT > void llvm::orc::OrcRPCTPCMemoryAccess< OrcRPCTPCImplT >::writeUInt64s (ArrayRef< tpctypes::UInt64Write > Ws, WriteResultFn OnWriteComplete) inline override virtual
Implements llvm::orc::TargetProcessControl::MemoryAccess.
Definition at line 248 of file OrcRPCTargetProcessControl.h.
References llvm::move().
writeUInt8s()
template<typename OrcRPCTPCImplT > void llvm::orc::OrcRPCTPCMemoryAccess< OrcRPCTPCImplT >::writeUInt8s (ArrayRef< tpctypes::UInt8Write > Ws, WriteResultFn OnWriteComplete) inline override virtual
Implements llvm::orc::TargetProcessControl::MemoryAccess.
Definition at line 233 of file OrcRPCTargetProcessControl.h.
References llvm::move().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/OrcRPCTargetProcessControl.h