LLVM: llvm::DIEEntry Class Reference
llvm::DIEEntry Class Reference
A pointer to another debug information entry.
#include "llvm/CodeGen/DIE.h"
Public Member Functions
DIEEntry ()=delete
DIEEntry (DIE &E)
DIE & getEntry () const
void emitValue (const AsmPrinter *AP, dwarf::Form Form) const
EmitValue - Emit debug information entry offset.
unsigned SizeOf (const AsmPrinter *AP, dwarf::Form Form) const
void print (raw_ostream &O) const
Detailed Description
A pointer to another debug information entry.
An instance of this class can also be used as a proxy for a debug information entry not yet defined (ie. types.)
Definition at line 314 of file DIE.h.
Constructor & Destructor Documentation
DIEEntry() [1/2]
llvm::DIEEntry::DIEEntry () delete
DIEEntry() [2/2]
llvm::DIEEntry::DIEEntry (DIE & E) inline explicit
Definition at line 319 of file DIE.h.
Member Function Documentation
emitValue()
void DIEEntry::emitValue (const AsmPrinter * AP, dwarf::Form Form) const
EmitValue - Emit debug information entry offset.
Definition at line 649 of file DIE.cpp.
References Addr, llvm::AsmPrinter::emitLabelPlusOffset(), llvm::AsmPrinter::emitULEB128(), llvm::DIEUnit::getCrossSectionRelativeBaseAddress(), llvm::DIE::getDebugSectionOffset(), llvm::DIE::getOffset(), llvm::DIE::getUnit(), llvm_unreachable, llvm::AsmPrinter::OutStreamer, and SizeOf().
getEntry()
DIE& llvm::DIEEntry::getEntry () const inline
Definition at line 321 of file DIE.h.
print()
LLVM_DUMP_METHOD void DIEEntry::print (raw_ostream & O) const
Definition at line 709 of file DIE.cpp.
References llvm::format(), and llvm::RISCVFenceField::O.
SizeOf()
unsigned DIEEntry::SizeOf (const AsmPrinter * AP, dwarf::Form Form) const
Definition at line 680 of file DIE.cpp.
References llvm::dwarf::DWARF32, llvm::dwarf::DWARF64, llvm::MCAsmInfo::getCodePointerSize(), llvm::AsmPrinter::getDwarfVersion(), llvm::DIE::getOffset(), llvm::getULEB128Size(), llvm_unreachable, llvm::AsmPrinter::MAI, and llvm::AsmPrinter::OutStreamer.
Referenced by emitValue().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/DIE.h
lib/CodeGen/AsmPrinter/DIE.cpp