LLVM: llvm::PrintPassInstrumentation Class Reference
llvm::PrintPassInstrumentation Class Reference
#include "llvm/Passes/StandardInstrumentations.h"
Public Member Functions
PrintPassInstrumentation (bool DebugLogging)
void registerCallbacks (PassInstrumentationCallbacks &PIC)
Detailed Description
Definition at line 83 of file StandardInstrumentations.h.
Constructor & Destructor Documentation
PrintPassInstrumentation()
llvm::PrintPassInstrumentation::PrintPassInstrumentation (bool DebugLogging) inline
Definition at line 85 of file StandardInstrumentations.h.
Member Function Documentation
registerCallbacks()
void PrintPassInstrumentation::registerCallbacks (PassInstrumentationCallbacks & PIC)
Definition at line 646 of file StandardInstrumentations.cpp.
References assert(), llvm::dbgs(), DebugPMVerbose, IR, llvm::isSpecialPass(), llvm::PassInstrumentationCallbacks::registerBeforeAnalysisCallback(), llvm::PassInstrumentationCallbacks::registerBeforeNonSkippedPassCallback(), and llvm::PassInstrumentationCallbacks::registerBeforeSkippedPassCallback().
Referenced by llvm::StandardInstrumentations::registerCallbacks().
The documentation for this class was generated from the following files:
include/llvm/Passes/StandardInstrumentations.h
lib/Passes/StandardInstrumentations.cpp