LLVM: llvm::EpilogueVectorizerMainLoop Class Reference
llvm::EpilogueVectorizerMainLoop Class Reference
A specialized derived class of inner loop vectorizer that performs vectorization of main loops in the process of vectorizing loops and their epilogues.
Public Member Functions
EpilogueVectorizerMainLoop (Loop *OrigLoop, PredicatedScalarEvolution &PSE, LoopInfo *LI, DominatorTree *DT, const TargetLibraryInfo *TLI, const TargetTransformInfo *TTI, AssumptionCache *AC, OptimizationRemarkEmitter *ORE, EpilogueLoopVectorizationInfo &EPI, LoopVectorizationLegality *LVL, llvm::LoopVectorizationCostModel *CM, BlockFrequencyInfo *BFI, ProfileSummaryInfo *PSI)
BasicBlock * createEpilogueVectorizedLoopSkeleton () final override
Implements the interface for creating a vectorized skeleton using the main loop strategy (ie the first pass of vplan execution).
Public Member Functions inherited from llvm::InnerLoopAndEpilogueVectorizer
InnerLoopAndEpilogueVectorizer (Loop *OrigLoop, PredicatedScalarEvolution &PSE, LoopInfo *LI, DominatorTree *DT, const TargetLibraryInfo *TLI, const TargetTransformInfo *TTI, AssumptionCache *AC, OptimizationRemarkEmitter *ORE, EpilogueLoopVectorizationInfo &EPI, LoopVectorizationLegality *LVL, llvm::LoopVectorizationCostModel *CM, BlockFrequencyInfo *BFI, ProfileSummaryInfo *PSI)
BasicBlock * createVectorizedLoopSkeleton () final override
Create a new empty loop that will contain vectorized instructions later on, while the old loop will be used as the scalar remainder.
Public Member Functions inherited from llvm::InnerLoopVectorizer
InnerLoopVectorizer (Loop *OrigLoop, PredicatedScalarEvolution &PSE, LoopInfo *LI, DominatorTree *DT, const TargetLibraryInfo *TLI, const TargetTransformInfo *TTI, AssumptionCache *AC, OptimizationRemarkEmitter *ORE, ElementCount VecWidth, unsigned UnrollFactor, LoopVectorizationLegality *LVL, LoopVectorizationCostModel *CM, BlockFrequencyInfo *BFI, ProfileSummaryInfo *PSI)
virtual ~InnerLoopVectorizer ()=default
void widenInstruction (Instruction &I, VPValue *Def, VPUser &Operands, VPTransformState &State)
Widen a single instruction within the innermost loop.
void widenCallInstruction (CallInst &I, VPValue *Def, VPUser &ArgOperands, VPTransformState &State)
Widen a single call instruction within the innermost loop.
void widenSelectInstruction (SelectInst &I, VPValue *VPDef, VPUser &Operands, bool InvariantCond, VPTransformState &State)
Widen a single select instruction within the innermost loop.
void fixVectorizedLoop ()
Fix the vectorized code, taking care of header phi's, live-outs, and more.
bool areSafetyChecksAdded ()
void widenGEP (GetElementPtrInst *GEP, VPValue *VPDef, VPUser &Indices, unsigned UF, ElementCount VF, bool IsPtrLoopInvariant, SmallBitVector &IsIndexLoopInvariant, VPTransformState &State)
Vectorize a single GetElementPtrInst based on information gathered and decisions taken during planning.
void widenPHIInstruction (Instruction *PN, RecurrenceDescriptor *RdxDesc, Value *StartV, unsigned UF, ElementCount VF)
Vectorize a single PHINode in a block.
void scalarizeInstruction (Instruction *Instr, VPUser &Operands, const VPIteration &Instance, bool IfPredicateInstr, VPTransformState &State)
A helper function to scalarize a single Instruction in the innermost loop.
void widenIntOrFpInduction (PHINode *IV, Value *Start, TruncInst *Trunc=nullptr)
Widen an integer or floating-point induction variable IV.
Value * getOrCreateVectorValue (Value *V, unsigned Part)
getOrCreateVectorValue and getOrCreateScalarValue coordinate to generate a vector or scalar value on-demand if one is not yet available.
void setVectorValue (Value *Scalar, unsigned Part, Value *Vector)
Value * getOrCreateScalarValue (Value *V, const VPIteration &Instance)
Return a value in the new loop corresponding to V from the original loop at unroll and vector indices Instance.
void packScalarIntoVectorValue (Value *V, const VPIteration &Instance)
Construct the vector value of a scalarized value V one lane at a time.
void vectorizeInterleaveGroup (const InterleaveGroup< Instruction > *Group, ArrayRef< VPValue * > VPDefs, VPTransformState &State, VPValue *Addr, ArrayRef< VPValue * > StoredValues, VPValue *BlockInMask=nullptr)
Try to vectorize interleaved access group Group with the base address given in Addr, optionally masking the vector operations if BlockInMask is non-null.
void vectorizeMemoryInstruction (Instruction *Instr, VPTransformState &State, VPValue *Def, VPValue *Addr, VPValue *StoredValue, VPValue *BlockInMask)
Vectorize Load and Store instructions with the base address given in Addr, optionally masking the vector operations if BlockInMask is non-null.
void setDebugLocFromInst (IRBuilder<> &B, const Value *Ptr)
Set the debug location in the builder using the debug location in the instruction.
void fixNonInductionPHIs (void)
Fix the non-induction PHIs in the OrigPHIsToFix vector.
Protected Member Functions
BasicBlock * emitMinimumIterationCountCheck (Loop *L, BasicBlock *Bypass, bool ForEpilogue)
Emits an iteration count bypass check once for the main loop (when ForEpilogue is false) and once for the epilogue loop (when ForEpilogue is true).
void printDebugTracesAtStart () override
Allow subclasses to override and print debug traces before/after vplan execution, when trace information is requested.
void printDebugTracesAtEnd () override
Protected Member Functions inherited from llvm::InnerLoopVectorizer
void fixupIVUsers (PHINode *OrigPhi, const InductionDescriptor &II, Value *CountRoundDown, Value *EndValue, BasicBlock *MiddleBlock)
Set up the values of the IVs correctly when exiting the vector loop.
PHINode * createInductionVariable (Loop *L, Value *Start, Value *End, Value *Step, Instruction *DL)
Create a new induction variable inside L.
void fixCrossIterationPHIs ()
Handle all cross-iteration phis in the header.
void fixFirstOrderRecurrence (PHINode *Phi)
Fix a first-order recurrence.
void fixReduction (PHINode *Phi)
Fix a reduction cross-iteration phi.
void clearReductionWrapFlags (RecurrenceDescriptor &RdxDesc)
Clear NSW/NUW flags from reduction instructions if necessary.
void fixLCSSAPHIs ()
Fixup the LCSSA phi nodes in the unique exit block.
void sinkScalarOperands (Instruction *PredInst)
Iteratively sink the scalarized operands of a predicated instruction into the block that was created for it.
void truncateToMinimalBitwidths ()
Shrinks vector element sizes to the smallest bitwidth they can be legally represented as.
virtual Value * getBroadcastInstrs (Value *V)
Create a broadcast instruction.
virtual Value * getStepVector (Value *Val, int StartIdx, Value *Step, Instruction::BinaryOps Opcode=Instruction::BinaryOpsEnd)
This function adds (StartIdx, StartIdx + Step, StartIdx + 2*Step, ...) to each vector element of Val.
void buildScalarSteps (Value *ScalarIV, Value *Step, Instruction *EntryVal, const InductionDescriptor &ID)
Compute scalar induction steps.
void createVectorIntOrFpInductionPHI (const InductionDescriptor &II, Value *Step, Value *Start, Instruction *EntryVal)
Create a vector induction phi node based on an existing scalar one.
bool shouldScalarizeInstruction (Instruction *I) const
Returns true if an instruction I should be scalarized instead of vectorized for the chosen vectorization factor.
bool needsScalarInduction (Instruction *IV) const
Returns true if we should generate a scalar version of IV.
void recordVectorLoopValueForInductionCast (const InductionDescriptor &ID, const Instruction *EntryVal, Value *VectorLoopValue, unsigned Part, unsigned Lane=UINT_MAX)
If there is a cast involved in the induction variable ID, which should be ignored in the vectorized loop body, this function records the VectorLoopValue of the respective Phi also as the VectorLoopValue of the cast.
virtual Value * reverseVector (Value *Vec)
Generate a shuffle sequence that will reverse the vector Vec.
Value * getOrCreateTripCount (Loop *NewLoop)
Returns (and creates if needed) the original loop trip count.
Value * getOrCreateVectorTripCount (Loop *NewLoop)
Returns (and creates if needed) the trip count of the widened loop.
Value * createBitOrPointerCast (Value *V, VectorType *DstVTy, const DataLayout &DL)
Returns a bitcasted value to the requested vector type.
void emitMinimumIterationCountCheck (Loop *L, BasicBlock *Bypass)
Emit a bypass check to see if the vector trip count is zero, including if it overflows.
void emitSCEVChecks (Loop *L, BasicBlock *Bypass)
Emit a bypass check to see if all of the SCEV assumptions we've had to make are correct.
void emitMemRuntimeChecks (Loop *L, BasicBlock *Bypass)
Emit bypass checks to check any memory assumptions we may have made.
Value * emitTransformedIndex (IRBuilder<> &B, Value *Index, ScalarEvolution *SE, const DataLayout &DL, const InductionDescriptor &ID) const
Compute the transformed value of Index at offset StartValue using step StepValue.
Loop * createVectorLoopSkeleton (StringRef Prefix)
Emit basic blocks (prefixed with Prefix) for the iteration check, vector loop preheader, middle block and scalar preheader.
void createInductionResumeValues (Loop *L, Value *VectorTripCount, std::pair< BasicBlock *, Value * > AdditionalBypass={nullptr, nullptr})
Create new phi nodes for the induction variables to resume iteration count in the scalar epilogue, from where the vectorized loop left off (given by VectorTripCount).
BasicBlock * completeLoopSkeleton (Loop *L, MDNode *OrigLoopID)
Complete the loop skeleton by adding debug MDs, creating appropriate conditional branches in the middle block, preparing the builder and running the verifier.
void addNewMetadata (Instruction *To, const Instruction *Orig)
Add additional metadata to To that was not present on Orig.
void addMetadata (Instruction *To, Instruction *From)
Add metadata from one instruction to another.
void addMetadata (ArrayRef< Value * > To, Instruction *From)
Similar to the previous function but it adds the metadata to a vector of instructions.
Additional Inherited Members
Public Types inherited from llvm::InnerLoopVectorizer
using VectorParts = SmallVector< Value *, 2 >
A type for vectorized values in the new loop.
Public Attributes inherited from llvm::InnerLoopAndEpilogueVectorizer
EpilogueLoopVectorizationInfo & EPI
Holds and updates state information required to vectorize the main loop and its epilogue in two separate passes.
Protected Types inherited from llvm::InnerLoopVectorizer
using PhiVector = SmallVector< PHINode *, 4 >
A small list of PHINodes.
using ScalarParts = SmallVector< SmallVector< Value *, 4 >, 2 >
A type for scalarized values in the new loop.
Protected Attributes inherited from llvm::InnerLoopVectorizer
Loop * OrigLoop
The original loop.
PredicatedScalarEvolution & PSE
A wrapper around ScalarEvolution used to add runtime SCEV checks.
LoopInfo * LI
Loop Info.
DominatorTree * DT
Dominator Tree.
AAResults * AA
Alias Analysis.
const TargetLibraryInfo * TLI
Target Library Info.
const TargetTransformInfo * TTI
Target Transform Info.
AssumptionCache * AC
Assumption Cache.
OptimizationRemarkEmitter * ORE
Interface to emit optimization remarks.
std::unique_ptr< LoopVersioning > LVer
LoopVersioning.
ElementCount VF
The vectorization SIMD factor to use.
unsigned UF
The vectorization unroll factor to use.
IRBuilder Builder
The builder that we use.
BasicBlock * LoopVectorPreHeader
The vector-loop preheader.
BasicBlock * LoopScalarPreHeader
The scalar-loop preheader.
BasicBlock * LoopMiddleBlock
Middle Block between the vector and the scalar.
BasicBlock * LoopExitBlock
The (unique) ExitBlock of the scalar loop.
BasicBlock * LoopVectorBody
The vector loop body.
BasicBlock * LoopScalarBody
The scalar loop body.
SmallVector< BasicBlock *, 4 > LoopBypassBlocks
A list of all bypass blocks. The first block is the entry of the loop.
PHINode * Induction = nullptr
The new Induction variable which was added to the new block.
PHINode * OldInduction = nullptr
The induction variable of the old basic block.
VectorizerValueMap VectorLoopValueMap
Maps values from the original loop to their corresponding values in the vectorized loop.
SmallVector< Instruction *, 4 > PredicatedInstructions
Store instructions that were predicated.
Value * TripCount = nullptr
Trip count of the original loop.
Value * VectorTripCount = nullptr
Trip count of the widened loop (TripCount - TripCount % (VF*UF))
LoopVectorizationLegality * Legal
The legality analysis.
LoopVectorizationCostModel * Cost
The profitablity analysis.
bool AddedSafetyChecks = false
DenseMap< PHINode *, Value * > IVEndValues
SmallVector< PHINode *, 8 > OrigPHIsToFix
BlockFrequencyInfo * BFI
BFI and PSI are used to check for profile guided size optimizations.
ProfileSummaryInfo * PSI
bool OptForSizeBasedOnProfile
Detailed Description
A specialized derived class of inner loop vectorizer that performs vectorization of main loops in the process of vectorizing loops and their epilogues.
Definition at line 992 of file LoopVectorize.cpp.
Constructor & Destructor Documentation
EpilogueVectorizerMainLoop()
llvm::EpilogueVectorizerMainLoop::EpilogueVectorizerMainLoop (Loop * OrigLoop, PredicatedScalarEvolution & PSE, LoopInfo * LI, DominatorTree * DT, const TargetLibraryInfo * TLI, const TargetTransformInfo * TTI, AssumptionCache * AC, OptimizationRemarkEmitter * ORE, EpilogueLoopVectorizationInfo & EPI, LoopVectorizationLegality * LVL, llvm::LoopVectorizationCostModel * CM, BlockFrequencyInfo * BFI, ProfileSummaryInfo * PSI) inline
Definition at line 994 of file LoopVectorize.cpp.
Member Function Documentation
createEpilogueVectorizedLoopSkeleton()
BasicBlock * EpilogueVectorizerMainLoop::createEpilogueVectorizedLoopSkeleton () final override virtual
Implements the interface for creating a vectorized skeleton using the main loop strategy (ie the first pass of vplan execution).
This function is partially responsible for generating the control flow depicted in https://llvm.org/docs/Vectorizers.html#epilogue-vectorization.
Implements llvm::InnerLoopAndEpilogueVectorizer.
Definition at line 7864 of file LoopVectorize.cpp.
References llvm::InnerLoopVectorizer::completeLoopSkeleton(), llvm::InnerLoopVectorizer::createInductionVariable(), llvm::InnerLoopVectorizer::createVectorLoopSkeleton(), llvm::InnerLoopVectorizer::emitMemRuntimeChecks(), emitMinimumIterationCountCheck(), llvm::InnerLoopVectorizer::emitSCEVChecks(), llvm::InnerLoopAndEpilogueVectorizer::EPI, llvm::EpilogueLoopVectorizationInfo::EpilogueIterationCountCheck, llvm::ConstantInt::get(), getDebugLocFromInstOrOperands(), llvm::LinearPolySize< LeafTy >::getKnownMinValue(), llvm::Loop::getLoopID(), llvm::InnerLoopVectorizer::getOrCreateVectorTripCount(), llvm::LoopVectorizationLegality::getPrimaryInduction(), llvm::LoopVectorizationLegality::getWidestInductionType(), llvm::InnerLoopVectorizer::Induction, llvm::InnerLoopVectorizer::Legal, llvm::InnerLoopVectorizer::LoopScalarPreHeader, llvm::InnerLoopVectorizer::LoopVectorPreHeader, llvm::EpilogueLoopVectorizationInfo::MainLoopIterationCountCheck, llvm::EpilogueLoopVectorizationInfo::MemSafetyCheck, llvm::InnerLoopVectorizer::OldInduction, llvm::InnerLoopVectorizer::OrigLoop, llvm::EpilogueLoopVectorizationInfo::SCEVSafetyCheck, llvm::Value::setName(), llvm::InnerLoopVectorizer::UF, llvm::EpilogueLoopVectorizationInfo::VectorTripCount, and llvm::InnerLoopVectorizer::VF.
emitMinimumIterationCountCheck()
BasicBlock * EpilogueVectorizerMainLoop::emitMinimumIterationCountCheck (Loop * L, BasicBlock * Bypass, bool ForEpilogue) protected
Emits an iteration count bypass check once for the main loop (when ForEpilogue is false) and once for the epilogue loop (when ForEpilogue is true).
Definition at line 7937 of file LoopVectorize.cpp.
References assert(), llvm::InnerLoopVectorizer::Builder, llvm::DominatorTreeBase< NodeT, IsPostDom >::changeImmediateDominator(), llvm::InnerLoopVectorizer::Cost, llvm::BranchInst::Create(), llvm::IRBuilderBase::CreateICmp(), llvm::InnerLoopVectorizer::DT, llvm::InnerLoopAndEpilogueVectorizer::EPI, llvm::EpilogueLoopVectorizationInfo::EpilogueUF, llvm::EpilogueLoopVectorizationInfo::EpilogueVF, llvm::ConstantInt::get(), llvm::LinearPolySize< LeafTy >::getKnownMinValue(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode(), llvm::InnerLoopVectorizer::getOrCreateTripCount(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::InnerLoopVectorizer::LI, llvm::InnerLoopVectorizer::LoopBypassBlocks, llvm::InnerLoopVectorizer::LoopExitBlock, llvm::InnerLoopVectorizer::LoopVectorPreHeader, P, llvm::DominatorTreeBase< NodeT, IsPostDom >::properlyDominates(), llvm::ReplaceInstWithInst(), llvm::LoopVectorizationCostModel::requiresScalarEpilogue(), llvm::Value::setName(), llvm::SplitBlock(), llvm::EpilogueLoopVectorizationInfo::TripCount, llvm::InnerLoopVectorizer::UF, and llvm::InnerLoopVectorizer::VF.
Referenced by createEpilogueVectorizedLoopSkeleton(), and llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton().
printDebugTracesAtEnd()
void EpilogueVectorizerMainLoop::printDebugTracesAtEnd () override protected virtual
Reimplemented from llvm::InnerLoopVectorizer.
Definition at line 7931 of file LoopVectorize.cpp.
References llvm::dbgs(), DEBUG_WITH_TYPE, llvm::Instruction::getFunction(), llvm::InnerLoopVectorizer::Induction, and VerboseDebug.
printDebugTracesAtStart()
void EpilogueVectorizerMainLoop::printDebugTracesAtStart () override protected virtual
Allow subclasses to override and print debug traces before/after vplan execution, when trace information is requested.
Reimplemented from llvm::InnerLoopVectorizer.
Definition at line 7921 of file LoopVectorize.cpp.
References llvm::dbgs(), llvm::InnerLoopAndEpilogueVectorizer::EPI, llvm::EpilogueLoopVectorizationInfo::EpilogueUF, llvm::EpilogueLoopVectorizationInfo::EpilogueVF, llvm::LinearPolySize< LeafTy >::getKnownMinValue(), LLVM_DEBUG, llvm::EpilogueLoopVectorizationInfo::MainLoopUF, and llvm::EpilogueLoopVectorizationInfo::MainLoopVF.
The documentation for this class was generated from the following file:
lib/Transforms/Vectorize/LoopVectorize.cpp