LLVM: llvm::ELFAttributeParser Class Reference
llvm::ELFAttributeParser Class Reference abstract
#include "llvm/Support/ELFAttributeParser.h"
Public Member Functions
virtual ~ELFAttributeParser ()
Error integerAttribute (unsigned tag)
Error stringAttribute (unsigned tag)
ELFAttributeParser (ScopedPrinter *sw, TagNameMap tagNameMap, StringRef vendor)
ELFAttributeParser (TagNameMap tagNameMap, StringRef vendor)
Error parse (ArrayRef< uint8_t > section, support::endianness endian)
Optional< unsigned > getAttributeValue (unsigned tag) const
Optional< StringRef > getAttributeString (unsigned tag) const
Protected Member Functions
void printAttribute (unsigned tag, unsigned value, StringRef valueDesc)
Error parseStringAttribute (const char *name, unsigned tag, ArrayRef< const char * > strings)
Error parseAttributeList (uint32_t length)
void parseIndexList (SmallVectorImpl< uint8_t > &indexList)
Error parseSubsection (uint32_t length)
Protected Attributes
ScopedPrinter * sw
TagNameMap tagToStringMap
DataExtractor de {ArrayRef<uint8_t>{}, true, 0}
DataExtractor::Cursor cursor {0}
Detailed Description
Definition at line 23 of file ELFAttributeParser.h.
Constructor & Destructor Documentation
~ELFAttributeParser()
virtual llvm::ELFAttributeParser::~ELFAttributeParser () inline virtual
Definition at line 45 of file ELFAttributeParser.h.
References cursor, and llvm::DataExtractor::Cursor::takeError().
ELFAttributeParser() [1/2]
llvm::ELFAttributeParser::ELFAttributeParser (ScopedPrinter * sw, TagNameMap tagNameMap, StringRef vendor) inline
Definition at line 49 of file ELFAttributeParser.h.
ELFAttributeParser() [2/2]
llvm::ELFAttributeParser::ELFAttributeParser (TagNameMap tagNameMap, StringRef vendor) inline
Definition at line 52 of file ELFAttributeParser.h.
Member Function Documentation
getAttributeString()
Optional<StringRef> llvm::ELFAttributeParser::getAttributeString (unsigned tag) const inline
Definition at line 63 of file ELFAttributeParser.h.
References I, and llvm::None.
getAttributeValue()
Optional<unsigned> llvm::ELFAttributeParser::getAttributeValue (unsigned tag) const inline
Definition at line 57 of file ELFAttributeParser.h.
References attributes, I, and llvm::None.
Referenced by llvm::object::ELFObjectFileBase::setARMSubArch().
integerAttribute()
Error ELFAttributeParser::integerAttribute (unsigned tag)
Definition at line 38 of file ELFAttributeParser.cpp.
References attributes, llvm::ELFAttrs::attrTypeAsString(), llvm::StringRef::empty(), and llvm::Error::success().
parse()
Error ELFAttributeParser::parse (ArrayRef< uint8_t > section, support::endianness endian)
Definition at line 189 of file ELFAttributeParser.cpp.
References clear(), llvm::consumeError(), llvm::createStringError(), llvm::numbers::e, llvm::ELFAttrs::Format_Version, llvm::invalid_argument, llvm::support::little, llvm::ArrayRef< T >::size(), and llvm::DataExtractor::Cursor::takeError().
Referenced by llvm::object::ELFObjectFile< ELFT >::getBuildAttributes().
parseAttributeList()
Error ELFAttributeParser::parseAttributeList (uint32_t length) protected
Definition at line 96 of file ELFAttributeParser.cpp.
References llvm::createStringError(), llvm::numbers::e, llvm::sys::path::end(), llvm::invalid_argument, llvm::Error::success(), and llvm::Twine::utohexstr().
parseIndexList()
void ELFAttributeParser::parseIndexList (SmallVectorImpl< uint8_t > & indexList) protected
Definition at line 87 of file ELFAttributeParser.cpp.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
parseStringAttribute()
Error ELFAttributeParser::parseStringAttribute (const char * name, unsigned tag, ArrayRef< const char * > strings) protected
Definition at line 25 of file ELFAttributeParser.cpp.
References llvm::createStringError(), llvm::invalid_argument, name, llvm::ArrayRef< T >::size(), and llvm::Error::success().
parseSubsection()
Error ELFAttributeParser::parseSubsection (uint32_t length) protected
Tag_File | Tag_Section | Tag_Symbol uleb128:byte-size
Definition at line 124 of file ELFAttributeParser.cpp.
References llvm::createStringError(), llvm::numbers::e, llvm::SmallVectorBase< Size_T >::empty(), llvm::sys::path::end(), llvm::ELFAttrs::File, llvm::invalid_argument, llvm::StringRef::lower(), llvm::makeArrayRef(), llvm::ELFAttrs::Section, llvm::size(), llvm::Error::success(), llvm::ELFAttrs::Symbol, tagNames, and llvm::Twine::utohexstr().
printAttribute()
void ELFAttributeParser::printAttribute (unsigned tag, unsigned value, StringRef valueDesc) protected
Definition at line 70 of file ELFAttributeParser.cpp.
References attributes, llvm::ELFAttrs::attrTypeAsString(), and llvm::StringRef::empty().
stringAttribute()
Error ELFAttributeParser::stringAttribute (unsigned tag)
Definition at line 54 of file ELFAttributeParser.cpp.
References llvm::ELFAttrs::attrTypeAsString(), llvm::StringRef::empty(), and llvm::Error::success().
Member Data Documentation
cursor
DataExtractor::Cursor llvm::ELFAttributeParser::cursor {0} protected
Definition at line 34 of file ELFAttributeParser.h.
Referenced by ~ELFAttributeParser().
de
DataExtractor llvm::ELFAttributeParser::de {ArrayRef<uint8_t>{}, true, 0} protected
Definition at line 33 of file ELFAttributeParser.h.
sw
ScopedPrinter* llvm::ELFAttributeParser::sw protected
Definition at line 31 of file ELFAttributeParser.h.
tagToStringMap
TagNameMap llvm::ELFAttributeParser::tagToStringMap protected
Definition at line 32 of file ELFAttributeParser.h.
The documentation for this class was generated from the following files:
include/llvm/Support/ELFAttributeParser.h
lib/Support/ELFAttributeParser.cpp