LLVM: llvm::VPWidenCanonicalIVRecipe Class Reference
llvm::VPWidenCanonicalIVRecipe Class Reference
A Recipe for widening the canonical induction variable of the vector loop.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPWidenCanonicalIVRecipe ()
~VPWidenCanonicalIVRecipe () override=default
void execute (VPTransformState &State) override
Generate a canonical vector induction variable of the vector loop, with start = {<Part*VF, Part*VF+1, ..., Part*VF+VF-1> for 0 <= Part < UF}, and step = <VF*UF, VF*UF, ..., VF*UF>.
void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const override
Print the recipe.
Public Member Functions inherited from llvm::VPRecipeBase
VPRecipeBase (const unsigned char SC)
virtual ~VPRecipeBase ()=default
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
void insertAfter (VPRecipeBase *InsertPos)
Insert an unlinked Recipe into a basic block immediately after the specified Recipe.
void moveAfter (VPRecipeBase *MovePos)
Unlink this recipe from its current VPBasicBlock and insert it into the VPBasicBlock that MovePos lives in, right after MovePos.
void moveBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator I)
Unlink this recipe and insert into BB before I.
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
VPUser * toVPUser ()
Returns a pointer to a VPUser, if the recipe inherits from VPUser or nullptr otherwise.
Instruction * getUnderlyingInstr ()
Returns the underlying instruction, if the recipe is a VPValue or nullptr otherwise.
const Instruction * getUnderlyingInstr () const
Public Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
VPRecipeBase * getPrevNode ()
const VPRecipeBase * getPrevNode () const
Get the previous node, or nullptr for the list head.
VPRecipeBase * getNextNode ()
Get the next node, or nullptr for the list tail.
const VPRecipeBase * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::VPDef
VPDef (const unsigned char SC)
virtual ~VPDef ()
VPValue * getVPValue (unsigned I=0)
Returns the VPValue with index I defined by the VPDef.
const VPValue * getVPValue (unsigned I=0) const
ArrayRef< VPValue * > definedValues ()
Returns an ArrayRef of the values defined by the VPDef.
ArrayRef< VPValue * > definedValues () const
Returns an ArrayRef of the values defined by the VPDef.
unsigned getNumDefinedValues () const
Returns the number of values defined by the VPDef.
unsigned getVPDefID () const
void dump () const
Dump the VPDef to stderr (for debugging).
Static Public Member Functions
static bool classof (const VPDef *D)
Method to support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::VPRecipeBase
static bool classof (const VPDef *D)
Method to support type inquiry through isa, cast, and dyn_cast.
Additional Inherited Members
Public Types inherited from llvm::VPDef
using VPRecipeTy = enum { VPBlendSC, VPBranchOnMaskSC, VPInstructionSC, VPInterleaveSC, VPPredInstPHISC, VPReductionSC, VPReplicateSC, VPWidenCallSC, VPWidenCanonicalIVSC, VPWidenGEPSC, VPWidenIntOrFpInductionSC, VPWidenMemoryInstructionSC, VPWidenPHISC, VPWidenSC, VPWidenSelectSC }
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< T, Options... >::type, true, true >
Protected Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
ilist_node_impl ()=default
Detailed Description
A Recipe for widening the canonical induction variable of the vector loop.
Definition at line 1367 of file VPlan.h.
Constructor & Destructor Documentation
VPWidenCanonicalIVRecipe()
llvm::VPWidenCanonicalIVRecipe::VPWidenCanonicalIVRecipe () inline
Definition at line 1369 of file VPlan.h.
References llvm::VPDef::VPValue.
~VPWidenCanonicalIVRecipe()
llvm::VPWidenCanonicalIVRecipe::~VPWidenCanonicalIVRecipe () override default
Member Function Documentation
classof()
static bool llvm::VPWidenCanonicalIVRecipe::classof (const VPDef * D) inline static
Method to support type inquiry through isa, cast, and dyn_cast.
Definition at line 1376 of file VPlan.h.
References D.
execute()
void VPWidenCanonicalIVRecipe::execute (VPTransformState & State) override virtual
Generate a canonical vector induction variable of the vector loop, with start = {<Part*VF, Part*VF+1, ..., Part*VF+VF-1> for 0 <= Part < UF}, and step = <VF*UF, VF*UF, ..., VF*UF>.
Implements llvm::VPRecipeBase.
Definition at line 989 of file VPlan.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), Builder, llvm::VPTransformState::CanonicalIV, llvm::VPTransformState::CFG, llvm::ConstantVector::get(), llvm::ConstantInt::get(), llvm::LinearPolySize< LeafTy >::getKnownMinValue(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::VPDef::getVPValue(), llvm::LinearPolySize< LeafTy >::isScalable(), llvm::ElementCount::isScalar(), llvm::VPTransformState::CFGState::PrevBB, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::VPTransformState::set(), llvm::VPTransformState::UF, and llvm::VPTransformState::VF.
print()
void VPWidenCanonicalIVRecipe::print (raw_ostream & O, const Twine & Indent, VPSlotTracker & SlotTracker) const override virtual
Print the recipe.
Implements llvm::VPDef.
Definition at line 1014 of file VPlan.cpp.
References llvm::VPDef::getVPValue(), llvm::RISCVFenceField::O, and llvm::VPValue::printAsOperand().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlan.cpp