LLVM: llvm::orc::SelfTargetProcessControl Class Reference
llvm::orc::SelfTargetProcessControl Class Reference
A TargetProcessControl implementation targeting the current process.
#include "llvm/ExecutionEngine/Orc/TargetProcessControl.h"
Public Member Functions
SelfTargetProcessControl (std::shared_ptr< SymbolStringPool > SSP, Triple TargetTriple, unsigned PageSize, std::unique_ptr< jitlink::JITLinkMemoryManager > MemMgr)
Expected< tpctypes::DylibHandle > loadDylib (const char *DylibPath) override
Load the dynamic library at the given path and return a handle to it.
Expected< std::vector< tpctypes::LookupResult > > lookupSymbols (ArrayRef< LookupRequest > Request) override
Search for symbols in the target process.
Expected< int32_t > runAsMain (JITTargetAddress MainFnAddr, ArrayRef< std::string > Args) override
Run function with a main-like signature.
Expected< tpctypes::WrapperFunctionResult > runWrapper (JITTargetAddress WrapperFnAddr, ArrayRef< uint8_t > ArgBuffer) override
Run a wrapper function with signature:
Error disconnect () override
Disconnect from the target process.
Public Member Functions inherited from llvm::orc::TargetProcessControl
virtual ~TargetProcessControl ()
SymbolStringPtr intern (StringRef SymName)
Intern a symbol name in the SymbolStringPool.
std::shared_ptr< SymbolStringPool > getSymbolStringPool () const
Return a shared pointer to the SymbolStringPool for this instance.
const Triple & getTargetTriple () const
Return the Triple for the target process.
unsigned getPageSize () const
Get the page size for the target process.
MemoryAccess & getMemoryAccess () const
Return a MemoryAccess object for the target process.
jitlink::JITLinkMemoryManager & getMemMgr () const
Return a JITLinkMemoryManager for the target process.
Static Public Member Functions
static Expected< std::unique_ptr< SelfTargetProcessControl > > Create (std::shared_ptr< SymbolStringPool > SSP, std::unique_ptr< jitlink::JITLinkMemoryManager > MemMgr=nullptr)
Create a SelfTargetProcessControl with the given memory manager.
Additional Inherited Members
Protected Member Functions inherited from llvm::orc::TargetProcessControl
TargetProcessControl (std::shared_ptr< SymbolStringPool > SSP)
Protected Attributes inherited from llvm::orc::TargetProcessControl
std::shared_ptr< SymbolStringPool > SSP
Triple TargetTriple
unsigned PageSize = 0
MemoryAccess * MemAccess = nullptr
jitlink::JITLinkMemoryManager * MemMgr = nullptr
Detailed Description
A TargetProcessControl implementation targeting the current process.
Definition at line 166 of file TargetProcessControl.h.
Constructor & Destructor Documentation
SelfTargetProcessControl()
llvm::orc::SelfTargetProcessControl::SelfTargetProcessControl (std::shared_ptr< SymbolStringPool > SSP, Triple TargetTriple, unsigned PageSize, std::unique_ptr< jitlink::JITLinkMemoryManager > MemMgr)
Definition at line 25 of file TargetProcessControl.cpp.
References llvm::Triple::isOSBinFormatMachO(), llvm::orc::TargetProcessControl::MemAccess, llvm::orc::TargetProcessControl::MemMgr, llvm::move(), llvm::orc::TargetProcessControl::PageSize, and llvm::orc::TargetProcessControl::TargetTriple.
Member Function Documentation
Create()
Expected< std::unique_ptr< SelfTargetProcessControl > > llvm::orc::SelfTargetProcessControl::Create (std::shared_ptr< SymbolStringPool > SSP, std::unique_ptr< jitlink::JITLinkMemoryManager > MemMgr = nullptr) static
Create a SelfTargetProcessControl with the given memory manager.
If no memory manager is given a jitlink::InProcessMemoryManager will be used by default.
Definition at line 43 of file TargetProcessControl.cpp.
References llvm::sys::Process::getPageSize(), llvm::sys::getProcessTriple(), llvm::orc::TargetProcessControl::MemMgr, llvm::move(), llvm::orc::TargetProcessControl::PageSize, and llvm::orc::TargetProcessControl::SSP.
disconnect()
Error llvm::orc::SelfTargetProcessControl::disconnect () override virtual
Disconnect from the target process.
This should be called after the JIT session is shut down.
Implements llvm::orc::TargetProcessControl.
Definition at line 114 of file TargetProcessControl.cpp.
References llvm::Error::success().
loadDylib()
Expected< tpctypes::DylibHandle > llvm::orc::SelfTargetProcessControl::loadDylib (const char * DylibPath) override virtual
Load the dynamic library at the given path and return a handle to it.
If LibraryPath is null this function will return the global handle for the target process.
Implements llvm::orc::TargetProcessControl.
Definition at line 57 of file TargetProcessControl.cpp.
References llvm::sys::DynamicLibrary::getPermanentLibrary(), llvm::inconvertibleErrorCode(), llvm::move(), and llvm::pointerToJITTargetAddress().
lookupSymbols()
Expected< std::vector< tpctypes::LookupResult > > llvm::orc::SelfTargetProcessControl::lookupSymbols (ArrayRef< LookupRequest > Request) override virtual
Search for symbols in the target process.
The result of the lookup is a 2-dimentional array of target addresses that correspond to the lookup order. If a required symbol is not found then this method will return an error. If a weakly referenced symbol is not found then it be assigned a '0' value in the result. that correspond to the lookup order.
Implements llvm::orc::TargetProcessControl.
Definition at line 68 of file TargetProcessControl.cpp.
References Addr, llvm::any_of(), assert(), DL, llvm::move(), llvm::pointerToJITTargetAddress(), and llvm::orc::RequiredSymbol.
runAsMain()
Expected< int32_t > llvm::orc::SelfTargetProcessControl::runAsMain (JITTargetAddress MainFnAddr, ArrayRef< std::string > Args) override virtual
Run function with a main-like signature.
Implements llvm::orc::TargetProcessControl.
Definition at line 99 of file TargetProcessControl.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, and llvm::orc::runAsMain().
runWrapper()
Expected< tpctypes::WrapperFunctionResult > llvm::orc::SelfTargetProcessControl::runWrapper (JITTargetAddress WrapperFnAddr, ArrayRef< uint8_t > ArgBuffer) override virtual
Run a wrapper function with signature:
CWrapperFunctionResult fn(uint8_t *Data, uint64_t Size);
{.cpp}
Implements llvm::orc::TargetProcessControl.
Definition at line 106 of file TargetProcessControl.cpp.
References llvm::ArrayRef< T >::data(), llvm::Data, llvm::ArrayRef< T >::size(), and llvm::Check::Size.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/TargetProcessControl.h
lib/ExecutionEngine/Orc/TargetProcessControl.cpp