LLVM: llvm::orc::MachOPlatform Class Reference
llvm::orc::MachOPlatform Class Reference
Mediates between MachO initialization and ExecutionSession state.
#include "llvm/ExecutionEngine/Orc/MachOPlatform.h"
Public Types
using InitializerSequence = std::vector< std::pair< JITDylib *, MachOJITDylibInitializers > >
using DeinitializerSequence = std::vector< std::pair< JITDylib *, MachOJITDylibDeinitializers > >
Public Member Functions
MachOPlatform (ExecutionSession &ES, ObjectLinkingLayer &ObjLinkingLayer, std::unique_ptr< MemoryBuffer > StandardSymbolsObject)
ExecutionSession & getExecutionSession () const
Error setupJITDylib (JITDylib &JD) override
This method will be called outside the session lock each time a JITDylib is created (unless it is created with EmptyJITDylib set) to allow the Platform to install any JITDylib specific standard symbols (e.g __dso_handle).
Error notifyAdding (ResourceTracker &RT, const MaterializationUnit &MU) override
This method will be called under the ExecutionSession lock each time a MaterializationUnit is added to a JITDylib.
Error notifyRemoving (ResourceTracker &RT) override
This method will be called under the ExecutionSession lock when a ResourceTracker is removed.
Expected< InitializerSequence > getInitializerSequence (JITDylib &JD)
Expected< DeinitializerSequence > getDeinitializerSequence (JITDylib &JD)
Public Member Functions inherited from llvm::orc::Platform
virtual ~Platform ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::orc::Platform
static Expected< DenseMap< JITDylib *, SymbolMap > > lookupInitSymbols (ExecutionSession &ES, const DenseMap< JITDylib *, SymbolLookupSet > &InitSyms)
A utility function for looking up initializer symbols.
Detailed Description
Mediates between MachO initialization and ExecutionSession state.
Definition at line 87 of file MachOPlatform.h.
Member Typedef Documentation
DeinitializerSequence
using llvm::orc::MachOPlatform::DeinitializerSequence = std::vector<std::pair<JITDylib *, MachOJITDylibDeinitializers> >
Definition at line 92 of file MachOPlatform.h.
InitializerSequence
using llvm::orc::MachOPlatform::InitializerSequence = std::vector<std::pair<JITDylib *, MachOJITDylibInitializers> >
Definition at line 89 of file MachOPlatform.h.
Constructor & Destructor Documentation
MachOPlatform()
llvm::orc::MachOPlatform::MachOPlatform (ExecutionSession & ES, ObjectLinkingLayer & ObjLinkingLayer, std::unique_ptr< MemoryBuffer > StandardSymbolsObject)
Definition at line 148 of file MachOPlatform.cpp.
References llvm::orc::ObjectLinkingLayer::addPlugin().
Member Function Documentation
getDeinitializerSequence()
Expected< MachOPlatform::DeinitializerSequence > llvm::orc::MachOPlatform::getDeinitializerSequence (JITDylib & JD)
Definition at line 251 of file MachOPlatform.cpp.
References llvm::orc::JITDylib::getDFSLinkOrder(), and llvm::Lock.
getExecutionSession()
ExecutionSession& llvm::orc::MachOPlatform::getExecutionSession () const inline
Definition at line 98 of file MachOPlatform.h.
getInitializerSequence()
Expected< MachOPlatform::InitializerSequence > llvm::orc::MachOPlatform::getInitializerSequence (JITDylib & JD)
Definition at line 183 of file MachOPlatform.cpp.
References llvm::dbgs(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty(), llvm::orc::JITDylib::getDFSLinkOrder(), llvm::orc::JITDylib::getExecutionSession(), llvm::orc::JITDylib::getName(), LLVM_DEBUG, llvm::Lock, llvm::orc::Platform::lookupInitSymbols(), llvm::move(), llvm::reverse(), and llvm::orc::ExecutionSession::runSessionLocked().
notifyAdding()
Error llvm::orc::MachOPlatform::notifyAdding (ResourceTracker & RT, const MaterializationUnit & MU) override virtual
This method will be called under the ExecutionSession lock each time a MaterializationUnit is added to a JITDylib.
Implements llvm::orc::Platform.
Definition at line 162 of file MachOPlatform.cpp.
References llvm::dbgs(), llvm::orc::MaterializationUnit::getInitializerSymbol(), llvm::orc::ResourceTracker::getJITDylib(), llvm::orc::MaterializationUnit::getName(), LLVM_DEBUG, llvm::Error::success(), and llvm::orc::WeaklyReferencedSymbol.
notifyRemoving()
Error llvm::orc::MachOPlatform::notifyRemoving (ResourceTracker & RT) override virtual
This method will be called under the ExecutionSession lock when a ResourceTracker is removed.
Implements llvm::orc::Platform.
Definition at line 178 of file MachOPlatform.cpp.
References llvm_unreachable.
setupJITDylib()
Error llvm::orc::MachOPlatform::setupJITDylib (JITDylib & JD) override virtual
This method will be called outside the session lock each time a JITDylib is created (unless it is created with EmptyJITDylib set) to allow the Platform to install any JITDylib specific standard symbols (e.g __dso_handle).
Implements llvm::orc::Platform.
Definition at line 156 of file MachOPlatform.cpp.
References llvm::orc::ObjectLayer::add(), llvm::MemoryBuffer::getMemBuffer(), and llvm::move().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/MachOPlatform.h
lib/ExecutionEngine/Orc/MachOPlatform.cpp