LLVM: llvm::IRSimilarity::IRSimilarityCandidate Class Reference
llvm::IRSimilarity::IRSimilarityCandidate Class Reference
This is a class that wraps a range of IRInstructionData from one point to another in the vector of IRInstructionData, which is a region of the program.
#include "llvm/Analysis/IRSimilarityIdentifier.h"
Classes
struct OperandMapping
Public Types
using iterator = IRInstructionDataList::iterator
Public Member Functions
IRSimilarityCandidate (unsigned StartIdx, unsigned Len, IRInstructionData *FirstInstIt, IRInstructionData *LastInstIt)
unsigned getLength () const
unsigned getStartIdx () const
unsigned getEndIdx () const
IRInstructionData * front () const
IRInstructionData * back () const
Instruction * frontInstruction ()
Instruction * backInstruction ()
BasicBlock * getStartBB ()
BasicBlock * getEndBB ()
Function * getFunction ()
Optional< unsigned > getGVN (Value *V)
Finds the positive number associated with V if it has been mapped.
Optional< Value * > fromGVN (unsigned Num)
Finds the Value associate with Num if it exists.
bool operator< (const IRSimilarityCandidate &RHS) const
iterator begin () const
iterator end () const
Static Public Member Functions
static bool isSimilar (const IRSimilarityCandidate &A, const IRSimilarityCandidate &B)
static bool compareStructure (const IRSimilarityCandidate &A, const IRSimilarityCandidate &B)
static bool compareNonCommutativeOperandMapping (OperandMapping A, OperandMapping B)
Compare the operands in A and B and check that the current mapping of global value numbers from A to B and B to \A is consistent.
static bool compareCommutativeOperandMapping (OperandMapping A, OperandMapping B)
Compare the operands in A and B and check that the current mapping of global value numbers from A to B and B to \A is consistent given that the operands are commutative.
static bool overlap (const IRSimilarityCandidate &A, const IRSimilarityCandidate &B)
Compare the start and end indices of the two IRSimilarityCandidates for whether they overlap.
Detailed Description
This is a class that wraps a range of IRInstructionData from one point to another in the vector of IRInstructionData, which is a region of the program.
It is also responsible for defining the structure within this region of instructions.
The structure of a region is defined through a value numbering system assigned to each unique value in a region at the creation of the IRSimilarityCandidate.
For example, for each Instruction we add a mapping for each new value seen in that Instruction. IR: Mapping Added: add1 = add i32 a, c1 add1 -> 3, a -> 1, c1 -> 2 add2 = add i32 a, %1 add2 -> 4 add3 = add i32 c2, c1 add3 -> 6, c2 -> 5
We can compare IRSimilarityCandidates against one another. The isSimilar function compares each IRInstructionData against one another and if we have the same sequences of IRInstructionData that would create the same hash, we have similar IRSimilarityCandidates.
We can also compare the structure of IRSimilarityCandidates. If we can create a mapping of registers in the region contained by one IRSimilarityCandidate to the region contained by different IRSimilarityCandidate, they can be considered structurally similar.
IRSimilarityCandidate1: IRSimilarityCandidate2: add1 = add i32 a, b add1 = add i32 d, e add2 = add i32 a, c add2 = add i32 d, f add3 = add i32 c1, c2 add3 = add i32 c3, c4
Can have the following mapping from candidate to candidate of: a -> d, b -> e, c -> f, c1 -> c3, c2 -> c4 and can be considered similar.
IRSimilarityCandidate1: IRSimilarityCandidate2: add1 = add i32 a, b add1 = add i32 d, c4 add2 = add i32 a, c add2 = add i32 d, f add3 = add i32 c1, c2 add3 = add i32 c3, c4
We cannot create the same mapping since the use of c4 is not used in the same way as b or c2.
Definition at line 470 of file IRSimilarityIdentifier.h.
Member Typedef Documentation
iterator
using llvm::IRSimilarity::IRSimilarityCandidate::iterator = IRInstructionDataList::iterator
Definition at line 621 of file IRSimilarityIdentifier.h.
Constructor & Destructor Documentation
IRSimilarityCandidate()
IRSimilarityCandidate::IRSimilarityCandidate (unsigned StartIdx, unsigned Len, IRInstructionData * FirstInstIt, IRInstructionData * LastInstIt)
Parameters
StartIdx - The starting location of the region.
Len - The length of the region.
FirstInstIt - The starting IRInstructionData of the region.
LastInstIt - The ending IRInstructionData of the region.
Definition at line 277 of file IRSimilarityIdentifier.cpp.
References Arg, and assert().
Member Function Documentation
back()
IRInstructionData* llvm::IRSimilarity::IRSimilarityCandidate::back () const inline
Returns
The last IRInstructionData.
Definition at line 575 of file IRSimilarityIdentifier.h.
Referenced by end().
backInstruction()
Instruction* llvm::IRSimilarity::IRSimilarityCandidate::backInstruction () inline
Returns
The last Instruction
Definition at line 580 of file IRSimilarityIdentifier.h.
References llvm::IRSimilarity::IRInstructionData::Inst.
begin()
iterator llvm::IRSimilarity::IRSimilarityCandidate::begin () const inline
Definition at line 622 of file IRSimilarityIdentifier.h.
References front().
compareCommutativeOperandMapping()
bool IRSimilarityCandidate::compareCommutativeOperandMapping (OperandMapping A, OperandMapping B) static
Compare the operands in A and B and check that the current mapping of global value numbers from A to B and B to \A is consistent given that the operands are commutative.
Parameters
A - The first IRInstructionCandidate, operand values, and current operand mappings to compare.
B - The second IRInstructionCandidate, operand values, and current operand mappings to compare.
Returns
true if the IRSimilarityCandidates operands are compatible.
Definition at line 531 of file IRSimilarityIdentifier.cpp.
References B, checkNumberingAndReplaceCommutative(), and llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert().
Referenced by compareStructure().
compareNonCommutativeOperandMapping()
bool IRSimilarityCandidate::compareNonCommutativeOperandMapping (OperandMapping A, OperandMapping B) static
Compare the operands in A and B and check that the current mapping of global value numbers from A to B and B to \A is consistent.
Parameters
A - The first IRInstructionCandidate, operand values, and current operand mappings to compare.
B - The second IRInstructionCandidate, operand values, and current operand mappings to compare.
Returns
true if the IRSimilarityCandidates operands are compatible.
Definition at line 497 of file IRSimilarityIdentifier.cpp.
References B, checkNumberingAndReplace(), and if().
Referenced by compareStructure().
compareStructure()
bool IRSimilarityCandidate::compareStructure (const IRSimilarityCandidate & A, const IRSimilarityCandidate & B) static
Parameters
A - The first IRInstructionCandidate to compare.
B - The second IRInstructionCandidate to compare.
Returns
True when every IRInstructionData in A is structurally similar to B.
Definition at line 566 of file IRSimilarityIdentifier.cpp.
References B, compareCommutativeOperandMapping(), compareNonCommutativeOperandMapping(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::IRSimilarity::isClose(), and llvm::Instruction::isCommutative().
Referenced by findCandidateStructures().
end()
iterator llvm::IRSimilarity::IRSimilarityCandidate::end () const inline
Definition at line 623 of file IRSimilarityIdentifier.h.
References back().
fromGVN()
Optional<Value *> llvm::IRSimilarity::IRSimilarityCandidate::fromGVN (unsigned Num) inline
Finds the Value associate with Num if it exists.
Parameters
[in] Num - the number to find.
Returns
The Value associated with the number.
None if not present.
Definition at line 606 of file IRSimilarityIdentifier.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and llvm::None.
Referenced by findCostForOutputBlocks().
front()
IRInstructionData* llvm::IRSimilarity::IRSimilarityCandidate::front () const inline
Returns
The first IRInstructionData.
Definition at line 573 of file IRSimilarityIdentifier.h.
Referenced by begin().
frontInstruction()
Instruction* llvm::IRSimilarity::IRSimilarityCandidate::frontInstruction () inline
Returns
The first Instruction.
Definition at line 578 of file IRSimilarityIdentifier.h.
References llvm::IRSimilarity::IRInstructionData::Inst.
getEndBB()
BasicBlock* llvm::IRSimilarity::IRSimilarityCandidate::getEndBB () inline
Returns
The BasicBlock the IRSimilarityCandidate ends in.
Definition at line 585 of file IRSimilarityIdentifier.h.
References llvm::Instruction::getParent(), and llvm::IRSimilarity::IRInstructionData::Inst.
getEndIdx()
unsigned llvm::IRSimilarity::IRSimilarityCandidate::getEndIdx () const inline
Returns
the end index of this IRSimilarityCandidate.
Definition at line 570 of file IRSimilarityIdentifier.h.
getFunction()
Function* llvm::IRSimilarity::IRSimilarityCandidate::getFunction () inline
Returns
The Function that the IRSimilarityCandidate is located in.
Definition at line 588 of file IRSimilarityIdentifier.h.
References llvm::BasicBlock::getParent(), and getStartBB().
getGVN()
Optional<unsigned> llvm::IRSimilarity::IRSimilarityCandidate::getGVN (Value * V) inline
Finds the positive number associated with V if it has been mapped.
Parameters
[in] V - the Value to find.
Returns
The positive number corresponding to the value.
None if not present.
Definition at line 594 of file IRSimilarityIdentifier.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and llvm::None.
getLength()
unsigned llvm::IRSimilarity::IRSimilarityCandidate::getLength () const inline
Returns
the number of instructions in this Candidate.
Definition at line 564 of file IRSimilarityIdentifier.h.
getStartBB()
BasicBlock* llvm::IRSimilarity::IRSimilarityCandidate::getStartBB () inline
Returns
The BasicBlock the IRSimilarityCandidate starts in.
Definition at line 583 of file IRSimilarityIdentifier.h.
References llvm::Instruction::getParent(), and llvm::IRSimilarity::IRInstructionData::Inst.
Referenced by getFunction().
getStartIdx()
unsigned llvm::IRSimilarity::IRSimilarityCandidate::getStartIdx () const inline
Returns
the start index of this IRSimilarityCandidate.
Definition at line 567 of file IRSimilarityIdentifier.h.
Referenced by operator<().
isSimilar()
bool IRSimilarityCandidate::isSimilar (const IRSimilarityCandidate & A, const IRSimilarityCandidate & B) static
Parameters
A - The first IRInstructionCandidate to compare.
B - The second IRInstructionCandidate to compare.
Returns
True when every IRInstructionData in A is similar to every IRInstructionData in B.
Definition at line 334 of file IRSimilarityIdentifier.cpp.
References llvm::all_of(), B, llvm::IRSimilarity::isClose(), llvm::make_range(), and llvm::zip().
operator<()
bool llvm::IRSimilarity::IRSimilarityCandidate::operator< (const IRSimilarityCandidate & RHS) const inline
Parameters
RHS -The IRSimilarityCandidate to compare against
Returns
true if the IRSimilarityCandidate is occurs after the IRSimilarityCandidate in the program.
Definition at line 617 of file IRSimilarityIdentifier.h.
References getStartIdx().
overlap()
bool IRSimilarityCandidate::overlap (const IRSimilarityCandidate & A, const IRSimilarityCandidate & B) static
Compare the start and end indices of the two IRSimilarityCandidates for whether they overlap.
If the start instruction of one IRSimilarityCandidate is less than the end instruction of the other, and the start instruction of one is greater than the start instruction of the other, they overlap.
Returns
true if the IRSimilarityCandidates do not have overlapping instructions.
Definition at line 639 of file IRSimilarityIdentifier.cpp.
References B, X, and Y.
The documentation for this class was generated from the following files:
include/llvm/Analysis/IRSimilarityIdentifier.h
lib/Analysis/IRSimilarityIdentifier.cpp