LLVM: llvm::InstCombineWorklist Class Reference
llvm::InstCombineWorklist Class Reference
InstCombineWorklist - This is the worklist management logic for InstCombine.
#include "llvm/Transforms/InstCombine/InstCombineWorklist.h"
Public Member Functions
InstCombineWorklist ()=default
InstCombineWorklist (InstCombineWorklist &&)=default
InstCombineWorklist & operator= (InstCombineWorklist &&)=default
bool isEmpty () const
void add (Instruction *I)
Add instruction to the worklist.
void addValue (Value *V)
Add value to the worklist if it is an instruction.
void push (Instruction *I)
Push the instruction onto the worklist stack.
void pushValue (Value *V)
Instruction * popDeferred ()
void reserve (size_t Size)
void remove (Instruction *I)
Remove I from the worklist if it exists.
Instruction * removeOne ()
void pushUsersToWorkList (Instruction &I)
When an instruction is simplified, add all users of the instruction to the work lists because they might get more simplified now.
void zap ()
Check that the worklist is empty and nuke the backing store for the map.
Detailed Description
InstCombineWorklist - This is the worklist management logic for InstCombine.
Definition at line 27 of file InstCombineWorklist.h.
Constructor & Destructor Documentation
InstCombineWorklist() [1/2]
llvm::InstCombineWorklist::InstCombineWorklist () default
InstCombineWorklist() [2/2]
llvm::InstCombineWorklist::InstCombineWorklist (InstCombineWorklist &&) default
Member Function Documentation
add()
void llvm::InstCombineWorklist::add (Instruction * I) inline
Add instruction to the worklist.
Instructions will be visited in the order they are added. You likely want to use this method.
Definition at line 46 of file InstCombineWorklist.h.
References llvm::dbgs(), I, llvm::SetVector< T, Vector, Set >::insert(), and LLVM_DEBUG.
Referenced by addValue(), and combineInstructionsOverFunction().
addValue()
void llvm::InstCombineWorklist::addValue (Value * V) inline
Add value to the worklist if it is an instruction.
Instructions will be visited in the order they are added.
Definition at line 53 of file InstCombineWorklist.h.
References add(), and I.
Referenced by llvm::InstCombiner::replaceOperand(), and llvm::InstCombiner::replaceUse().
isEmpty()
bool llvm::InstCombineWorklist::isEmpty () const inline
Definition at line 41 of file InstCombineWorklist.h.
References llvm::SetVector< T, Vector, Set >::empty(), and llvm::SmallVectorBase< Size_T >::empty().
operator=()
InstCombineWorklist& llvm::InstCombineWorklist::operator= (InstCombineWorklist &&) default
popDeferred()
Instruction* llvm::InstCombineWorklist::popDeferred () inline
Definition at line 75 of file InstCombineWorklist.h.
References llvm::SetVector< T, Vector, Set >::empty(), and llvm::SetVector< T, Vector, Set >::pop_back_val().
push()
void llvm::InstCombineWorklist::push (Instruction * I) inline
Push the instruction onto the worklist stack.
Instructions that have been added first will be visited last.
Definition at line 60 of file InstCombineWorklist.h.
References assert(), llvm::dbgs(), I, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), LLVM_DEBUG, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::InstCombiner::addToWorklist(), llvm::InstCombiner::InsertNewInstBefore(), prepareICWorklistFromFunction(), pushUsersToWorkList(), and pushValue().
pushUsersToWorkList()
void llvm::InstCombineWorklist::pushUsersToWorkList (Instruction & I) inline
When an instruction is simplified, add all users of the instruction to the work lists because they might get more simplified now.
Definition at line 108 of file InstCombineWorklist.h.
References I, and push().
Referenced by llvm::InstCombiner::replaceInstUsesWith().
pushValue()
void llvm::InstCombineWorklist::pushValue (Value * V) inline
Definition at line 70 of file InstCombineWorklist.h.
References I, and push().
remove()
void llvm::InstCombineWorklist::remove (Instruction * I) inline
Remove I from the worklist if it exists.
Definition at line 87 of file InstCombineWorklist.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), I, and llvm::SetVector< T, Vector, Set >::remove().
removeOne()
Instruction* llvm::InstCombineWorklist::removeOne () inline
Definition at line 98 of file InstCombineWorklist.h.
References llvm::SmallVectorBase< Size_T >::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), I, and llvm::SmallVectorImpl< T >::pop_back_val().
reserve()
void llvm::InstCombineWorklist::reserve (size_t Size) inline
Definition at line 81 of file InstCombineWorklist.h.
References llvm::SmallVectorImpl< T >::reserve(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::reserve(), and llvm::Check::Size.
Referenced by prepareICWorklistFromFunction().
zap()
void llvm::InstCombineWorklist::zap () inline
Check that the worklist is empty and nuke the backing store for the map.
Definition at line 115 of file InstCombineWorklist.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty(), and llvm::SetVector< T, Vector, Set >::empty().
The documentation for this class was generated from the following file:
include/llvm/Transforms/InstCombine/InstCombineWorklist.h