LLVM: llvm::UnivariateLinearPolyBase< LeafTy > Class Template Reference
llvm::UnivariateLinearPolyBase< LeafTy > Class Template Reference
UnivariateLinearPolyBase is a base class for ElementCount and TypeSize.
#include "llvm/Support/TypeSize.h"
Public Types
using ScalarTy = typename LinearPolyBaseTypeTraits< LeafTy >::ScalarTy
Public Member Functions
bool operator== (const UnivariateLinearPolyBase &RHS) const
bool operator!= (const UnivariateLinearPolyBase &RHS) const
bool isZero () const
bool isNonZero () const
operator bool () const
ScalarTy getValue () const
ScalarTy getValue (unsigned Dim) const
LeafTy getWithIncrement (ScalarTy RHS)
Add RHS to the value at the univariate dimension.
LeafTy getWithDecrement (ScalarTy RHS)
Subtract RHS from the value at the univariate dimension.
Static Public Attributes
static constexpr auto Dimensions = LinearPolyBaseTypeTraits<LeafTy>::Dimensions
Protected Member Functions
UnivariateLinearPolyBase (ScalarTy Val, unsigned UnivariateDim)
Protected Attributes
ScalarTy Value
unsigned UnivariateDim
Friends
LeafTy & operator+= (LeafTy &LHS, const LeafTy &RHS)
LeafTy & operator-= (LeafTy &LHS, const LeafTy &RHS)
LeafTy & operator*= (LeafTy &LHS, ScalarTy RHS)
LeafTy operator+ (const LeafTy &LHS, const LeafTy &RHS)
LeafTy operator- (const LeafTy &LHS, const LeafTy &RHS)
LeafTy operator* (const LeafTy &LHS, ScalarTy RHS)
template<typename U = ScalarTy>
std::enable_if< std::is_signed< U >::value, LeafTy >::type operator- (const LeafTy &LHS)
Detailed Description
template<typename LeafTy>
class llvm::UnivariateLinearPolyBase< LeafTy >
UnivariateLinearPolyBase is a base class for ElementCount and TypeSize.
Like LinearPolyBase it tries to represent a linear polynomial where only one dimension can be set at any time, e.g. 0 * scale0 + 0 * scale1 + ... + cJ * scaleJ + ... + 0 * scaleK The dimension that is set is the univariate dimension.
Definition at line 161 of file TypeSize.h.
Member Typedef Documentation
ScalarTy
template<typename LeafTy > using llvm::UnivariateLinearPolyBase< LeafTy >::ScalarTy = typename LinearPolyBaseTypeTraits<LeafTy>::ScalarTy
Definition at line 163 of file TypeSize.h.
Constructor & Destructor Documentation
UnivariateLinearPolyBase()
template<typename LeafTy > llvm::UnivariateLinearPolyBase< LeafTy >::UnivariateLinearPolyBase (ScalarTy Val, unsigned UnivariateDim) inline protected
Definition at line 172 of file TypeSize.h.
References assert(), llvm::UnivariateLinearPolyBase< LeafTy >::Dimensions, and llvm::UnivariateLinearPolyBase< LeafTy >::UnivariateDim.
Referenced by llvm::UnivariateLinearPolyBase< LeafTy >::getWithDecrement(), and llvm::UnivariateLinearPolyBase< LeafTy >::getWithIncrement().
Member Function Documentation
getValue() [1/2]
template<typename LeafTy > ScalarTy llvm::UnivariateLinearPolyBase< LeafTy >::getValue () const inline
Definition at line 228 of file TypeSize.h.
References llvm::UnivariateLinearPolyBase< LeafTy >::Value.
Referenced by llvm::LinearPolySize< LeafTy >::getKnownMinValue(), and performCommonVectorExtendCombine().
getValue() [2/2]
template<typename LeafTy > ScalarTy llvm::UnivariateLinearPolyBase< LeafTy >::getValue (unsigned Dim) const inline
Definition at line 229 of file TypeSize.h.
References llvm::UnivariateLinearPolyBase< LeafTy >::UnivariateDim, and llvm::UnivariateLinearPolyBase< LeafTy >::Value.
getWithDecrement()
template<typename LeafTy > LeafTy llvm::UnivariateLinearPolyBase< LeafTy >::getWithDecrement (ScalarTy RHS) inline
Subtract RHS from the value at the univariate dimension.
Definition at line 240 of file TypeSize.h.
References llvm::UnivariateLinearPolyBase< LeafTy >::UnivariateDim, and llvm::UnivariateLinearPolyBase< LeafTy >::UnivariateLinearPolyBase().
getWithIncrement()
template<typename LeafTy > LeafTy llvm::UnivariateLinearPolyBase< LeafTy >::getWithIncrement (ScalarTy RHS) inline
Add RHS to the value at the univariate dimension.
Definition at line 234 of file TypeSize.h.
References llvm::UnivariateLinearPolyBase< LeafTy >::UnivariateDim, and llvm::UnivariateLinearPolyBase< LeafTy >::UnivariateLinearPolyBase().
Referenced by llvm::LoopVectorizationPlanner::buildVPlans().
isNonZero()
template<typename LeafTy > bool llvm::UnivariateLinearPolyBase< LeafTy >::isNonZero () const inline
Definition at line 226 of file TypeSize.h.
References llvm::UnivariateLinearPolyBase< LeafTy >::isZero().
Referenced by llvm::LoopVectorizationCostModel::computeMaxVF(), llvm::LLT::LLT(), llvm::UnivariateLinearPolyBase< LeafTy >::operator bool(), and llvm::LoopVectorizationPlanner::plan().
isZero()
template<typename LeafTy > bool llvm::UnivariateLinearPolyBase< LeafTy >::isZero () const inline
Definition at line 225 of file TypeSize.h.
References llvm::UnivariateLinearPolyBase< LeafTy >::Value.
Referenced by llvm::LoopVectorizationCostModel::collectInstsToScalarize(), llvm::UnivariateLinearPolyBase< LeafTy >::isNonZero(), llvm::LoopVectorizationPlanner::plan(), and llvm::LoopVectorizationPlanner::planInVPlanNativePath().
operator bool()
template<typename LeafTy > llvm::UnivariateLinearPolyBase< LeafTy >::operator bool () const inline explicit
Definition at line 227 of file TypeSize.h.
References llvm::UnivariateLinearPolyBase< LeafTy >::isNonZero().
operator!=()
template<typename LeafTy > bool llvm::UnivariateLinearPolyBase< LeafTy >::operator!= (const UnivariateLinearPolyBase< LeafTy > & RHS) const inline
Definition at line 221 of file TypeSize.h.
operator==()
template<typename LeafTy > bool llvm::UnivariateLinearPolyBase< LeafTy >::operator== (const UnivariateLinearPolyBase< LeafTy > & RHS) const inline
Definition at line 217 of file TypeSize.h.
References llvm::UnivariateLinearPolyBase< LeafTy >::UnivariateDim, and llvm::UnivariateLinearPolyBase< LeafTy >::Value.
Friends And Related Function Documentation
operator*
template<typename LeafTy > LeafTy operator* (const LeafTy & LHS, ScalarTy RHS) friend
Definition at line 204 of file TypeSize.h.
operator*=
template<typename LeafTy > LeafTy& operator*= (LeafTy & LHS, ScalarTy RHS) friend
Definition at line 189 of file TypeSize.h.
operator+
template<typename LeafTy > LeafTy operator+ (const LeafTy & LHS, const LeafTy & RHS) friend
Definition at line 194 of file TypeSize.h.
operator+=
template<typename LeafTy > LeafTy& operator+= (LeafTy & LHS, const LeafTy & RHS) friend
Definition at line 177 of file TypeSize.h.
operator- [1/2]
template<typename LeafTy > template<typename U = ScalarTy> std::enable_if<std::is_signed<U>::value, LeafTy>::type operator- (const LeafTy & LHS) friend
Definition at line 211 of file TypeSize.h.
operator- [2/2]
template<typename LeafTy > LeafTy operator- (const LeafTy & LHS, const LeafTy & RHS) friend
Definition at line 199 of file TypeSize.h.
operator-=
template<typename LeafTy > LeafTy& operator-= (LeafTy & LHS, const LeafTy & RHS) friend
Definition at line 183 of file TypeSize.h.
Member Data Documentation
Dimensions
template<typename LeafTy > constexpr auto llvm::UnivariateLinearPolyBase< LeafTy >::Dimensions = LinearPolyBaseTypeTraits<LeafTy>::Dimensions static constexpr
Definition at line 164 of file TypeSize.h.
Referenced by llvm::UnivariateLinearPolyBase< LeafTy >::UnivariateLinearPolyBase().
UnivariateDim
template<typename LeafTy > unsigned llvm::UnivariateLinearPolyBase< LeafTy >::UnivariateDim protected
Definition at line 170 of file TypeSize.h.
Referenced by llvm::UnivariateLinearPolyBase< LeafTy >::getValue(), llvm::UnivariateLinearPolyBase< LeafTy >::getWithDecrement(), llvm::UnivariateLinearPolyBase< LeafTy >::getWithIncrement(), llvm::LinearPolySize< LeafTy >::isScalable(), llvm::UnivariateLinearPolyBase< LeafTy >::operator==(), and llvm::UnivariateLinearPolyBase< LeafTy >::UnivariateLinearPolyBase().
Value
template<typename LeafTy > ScalarTy llvm::UnivariateLinearPolyBase< LeafTy >::Value protected
Definition at line 169 of file TypeSize.h.
Referenced by llvm::UnivariateLinearPolyBase< LeafTy >::getValue(), llvm::UnivariateLinearPolyBase< LeafTy >::isZero(), and llvm::UnivariateLinearPolyBase< LeafTy >::operator==().
The documentation for this class was generated from the following file:
include/llvm/Support/TypeSize.h