LLVM: llvm::Evaluator Class Reference
llvm::Evaluator Class Reference
This class evaluates LLVM IR, producing the Constant representing each SSA instruction.
#include "llvm/Transforms/Utils/Evaluator.h"
Public Member Functions
Evaluator (const DataLayout &DL, const TargetLibraryInfo *TLI)
~Evaluator ()
bool EvaluateFunction (Function *F, Constant *&RetVal, const SmallVectorImpl< Constant * > &ActualArgs)
Evaluate a call to function F, returning true if successful, false if we can't evaluate it.
bool EvaluateBlock (BasicBlock::iterator CurInst, BasicBlock *&NextBB)
Evaluate all instructions in block BB, returning true if successful, false if we can't evaluate it.
Constant * getVal (Value *V)
void setVal (Value *V, Constant *C)
Constant * castCallResultIfNeeded (Value *CallExpr, Constant *RV)
Casts call result to a type of bitcast call expression.
const DenseMap< Constant *, Constant * > & getMutatedMemory () const
const SmallPtrSetImpl< GlobalVariable * > & getInvariants () const
Detailed Description
This class evaluates LLVM IR, producing the Constant representing each SSA instruction.
Changes to global variables are stored in a mapping that can be iterated over after the evaluation is complete. Once an evaluation call fails, the evaluation object should not be reused.
Definition at line 38 of file Evaluator.h.
Constructor & Destructor Documentation
Evaluator()
llvm::Evaluator::Evaluator (const DataLayout & DL, const TargetLibraryInfo * TLI) inline
Definition at line 40 of file Evaluator.h.
References DL.
~Evaluator()
llvm::Evaluator::~Evaluator () inline
Definition at line 45 of file Evaluator.h.
References llvm::Constant::getNullValue().
Member Function Documentation
castCallResultIfNeeded()
Constant * Evaluator::castCallResultIfNeeded (Value * CallExpr, Constant * RV)
Casts call result to a type of bitcast call expression.
If call expression contains bitcast then we may need to cast evaluated return value to a type of the call expression.
Definition at line 305 of file Evaluator.cpp.
References llvm::ConstantFoldLoadThroughBitcast(), llvm::dbgs(), DL, and LLVM_DEBUG.
Referenced by EvaluateBlock().
EvaluateBlock()
bool Evaluator::EvaluateBlock (BasicBlock::iterator CurInst, BasicBlock *& NextBB)
Evaluate all instructions in block BB, returning true if successful, false if we can't evaluate it.
NewBB returns the next BB that control flows into, or null upon return.
Definition at line 322 of file Evaluator.cpp.
References C, Callee, castCallResultIfNeeded(), Cond, llvm::ConstantFoldCall(), llvm::ConstantFoldConstant(), llvm::ConstantFoldLoadThroughBitcast(), llvm::dbgs(), DL, llvm::numbers::e, evaluateBitcastFromPtr(), EvaluateFunction(), GEP, llvm::UndefValue::get(), llvm::ConstantExpr::get(), llvm::CallBase::getCalledOperand(), llvm::ConstantExpr::getCast(), llvm::ConstantExpr::getCompare(), llvm::ConstantExpr::getExtractValue(), llvm::FunctionCallee::getFunctionType(), llvm::ConstantExpr::getGetElementPtr(), llvm::ConstantExpr::getInsertValue(), llvm::Value::getName(), llvm::ConstantExpr::getSelect(), llvm::Value::getType(), getVal(), llvm::GlobalValue::InternalLinkage, llvm::CallBase::isInlineAsm(), llvm::Constant::isNullValue(), isSimpleEnoughPointerToCommit(), isSimpleEnoughValueToCommit(), llvm::FunctionType::isVarArg(), LLVM_DEBUG, llvm::GlobalValue::NotThreadLocal, P, llvm::SmallVectorTemplateBase< T, bool >::push_back(), setVal(), SI, llvm::Check::Size, llvm::Constant::stripPointerCasts(), and llvm::Value::stripPointerCasts().
Referenced by EvaluateFunction().
EvaluateFunction()
bool Evaluator::EvaluateFunction (Function * F, Constant *& RetVal, const SmallVectorImpl< Constant * > & ActualArgs)
Evaluate a call to function F, returning true if successful, false if we can't evaluate it.
ActualArgs contains the formal arguments for the function.
Definition at line 669 of file Evaluator.cpp.
References llvm::BasicBlock::begin(), llvm::dbgs(), E, EvaluateBlock(), F, llvm::PHINode::getIncomingValueForBlock(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::BasicBlock::getTerminator(), getVal(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::is_contained(), LLVM_DEBUG, and setVal().
Referenced by EvaluateBlock(), and EvaluateStaticConstructor().
getInvariants()
const SmallPtrSetImpl<GlobalVariable*>& llvm::Evaluator::getInvariants () const inline
Definition at line 83 of file Evaluator.h.
Referenced by EvaluateStaticConstructor().
getMutatedMemory()
const DenseMap<Constant*, Constant*>& llvm::Evaluator::getMutatedMemory () const inline
Definition at line 79 of file Evaluator.h.
Referenced by EvaluateStaticConstructor().
getVal()
Constant* llvm::Evaluator::getVal (Value * V) inline
Definition at line 65 of file Evaluator.h.
References assert().
Referenced by EvaluateBlock(), and EvaluateFunction().
setVal()
void llvm::Evaluator::setVal (Value * V, Constant * C) inline
Definition at line 72 of file Evaluator.h.
References C.
Referenced by EvaluateBlock(), and EvaluateFunction().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/Evaluator.h
lib/Transforms/Utils/Evaluator.cpp