LLVM: llvm::MipsLegalizerInfo Class Reference
llvm::MipsLegalizerInfo Class Reference
This class provides legalization strategies.
#include "Target/Mips/MipsLegalizerInfo.h"
Public Member Functions
MipsLegalizerInfo (const MipsSubtarget &ST)
bool legalizeCustom (LegalizerHelper &Helper, MachineInstr &MI) const override
Called for instructions with the Custom LegalizationAction.
bool legalizeIntrinsic (LegalizerHelper &Helper, MachineInstr &MI) const override
Public Member Functions inherited from llvm::LegalizerInfo
LegalizerInfo ()
virtual ~LegalizerInfo ()=default
unsigned getOpcodeIdxForOpcode (unsigned Opcode) const
unsigned getActionDefinitionsIdx (unsigned Opcode) const
void computeTables ()
Compute any ancillary tables needed to quickly decide how an operation should be handled.
void verify (const MCInstrInfo &MII) const
Perform simple self-diagnostic and assert if there is anything obviously wrong with the actions set up.
void setAction (const InstrAspect &Aspect, LegalizeAction Action)
More friendly way to set an action for common types that have an LLT representation.
void setLegalizeScalarToDifferentSizeStrategy (const unsigned Opcode, const unsigned TypeIdx, SizeChangeStrategy S)
The setAction calls record the non-size-changing legalization actions to take on specificly-sized types.
void setLegalizeVectorElementToDifferentSizeStrategy (const unsigned Opcode, const unsigned TypeIdx, SizeChangeStrategy S)
See also setLegalizeScalarToDifferentSizeStrategy.
const LegalizeRuleSet & getActionDefinitions (unsigned Opcode) const
Get the action definitions for the given opcode.
LegalizeRuleSet & getActionDefinitionsBuilder (unsigned Opcode)
Get the action definition builder for the given opcode.
LegalizeRuleSet & getActionDefinitionsBuilder (std::initializer_list< unsigned > Opcodes)
Get the action definition builder for the given set of opcodes.
void aliasActionDefinitions (unsigned OpcodeTo, unsigned OpcodeFrom)
LegalizeActionStep getAction (const LegalityQuery &Query) const
Determine what action should be taken to legalize the described instruction.
LegalizeActionStep getAction (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
Determine what action should be taken to legalize the given generic instruction.
bool isLegal (const LegalityQuery &Query) const
bool isLegalOrCustom (const LegalityQuery &Query) const
bool isLegal (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
bool isLegalOrCustom (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
virtual unsigned getExtOpcodeForWideningConstant (LLT SmallTy) const
Return the opcode (SEXT/ZEXT/ANYEXT) that should be performed while widening a constant of type SmallTy which targets can override.
Additional Inherited Members
Public Types inherited from llvm::LegalizerInfo
using SizeAndAction = std::pair< uint16_t, LegalizeAction >
using SizeAndActionsVec = std::vector< SizeAndAction >
using SizeChangeStrategy = std::function< SizeAndActionsVec(const SizeAndActionsVec &v)>
Static Public Member Functions inherited from llvm::LegalizerInfo
static bool needsLegalizingToDifferentSize (const LegalizeAction Action)
static SizeAndActionsVec unsupportedForDifferentSizes (const SizeAndActionsVec &v)
A SizeChangeStrategy for the common case where legalization for a particular operation consists of only supporting a specific set of type sizes.
static SizeAndActionsVec widenToLargerTypesAndNarrowToLargest (const SizeAndActionsVec &v)
A SizeChangeStrategy for the common case where legalization for a particular operation consists of widening the type to a large legal type, unless there is no such type and then instead it should be narrowed to the largest legal type.
static SizeAndActionsVec widenToLargerTypesUnsupportedOtherwise (const SizeAndActionsVec &v)
static SizeAndActionsVec narrowToSmallerAndUnsupportedIfTooSmall (const SizeAndActionsVec &v)
static SizeAndActionsVec narrowToSmallerAndWidenToSmallest (const SizeAndActionsVec &v)
static SizeAndActionsVec moreToWiderTypesAndLessToWidest (const SizeAndActionsVec &v)
A SizeChangeStrategy for the common case where legalization for a particular vector operation consists of having more elements in the vector, to a type that is legal.
static SizeAndActionsVec increaseToLargerTypesAndDecreaseToLargest (const SizeAndActionsVec &v, LegalizeAction IncreaseAction, LegalizeAction DecreaseAction)
Helper function to implement many typical SizeChangeStrategy functions.
static SizeAndActionsVec decreaseToSmallerTypesAndIncreaseToSmallest (const SizeAndActionsVec &v, LegalizeAction DecreaseAction, LegalizeAction IncreaseAction)
Helper function to implement many typical SizeChangeStrategy functions.
Detailed Description
This class provides legalization strategies.
Definition at line 24 of file MipsLegalizerInfo.h.
Constructor & Destructor Documentation
MipsLegalizerInfo()
MipsLegalizerInfo::MipsLegalizerInfo (const MipsSubtarget & ST)
Definition at line 69 of file MipsLegalizerInfo.cpp.
References assert(), CheckTy0Ty1MemSizeAlign(), CheckTyN(), llvm::LegalizeRuleSet::clampScalar(), llvm::LegalizerInfo::computeTables(), llvm::LegalizerInfo::getActionDefinitionsBuilder(), if(), llvm::isPowerOf2_64(), isUnalignedMemmoryAccess(), llvm::LegalizeRuleSet::legalFor(), llvm::LegalizeRuleSet::legalForCartesianProduct(), llvm::LegalizeRuleSet::legalIf(), llvm::LegalizeRuleSet::libcallFor(), llvm::LegalizeRuleSet::libcallForCartesianProduct(), llvm::LegalizeRuleSet::lower(), llvm::LegalizeRuleSet::lowerFor(), llvm::LegalizeRuleSet::maxScalar(), llvm::LegalizeRuleSet::minScalar(), llvm::LegalityQuery::MMODescrs, llvm::LLT::pointer(), llvm::LLT::scalar(), llvm::Check::Size, llvm::ARM_MB::ST, llvm::LegalityQuery::Types, llvm::LLT::vector(), and llvm::LegalizerInfo::verify().
Member Function Documentation
legalizeCustom()
bool MipsLegalizerInfo::legalizeCustom (LegalizerHelper & Helper, MachineInstr & MI) const override virtual
Called for instructions with the Custom LegalizationAction.
Reimplemented from llvm::LegalizerInfo.
Definition at line 331 of file MipsLegalizerInfo.cpp.
References Addr, assert(), llvm::LegalizeActions::Bitcast, llvm::BitsToDouble(), llvm::MachineIRBuilder::buildAnyExt(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildFConstant(), llvm::MachineIRBuilder::buildFPTrunc(), llvm::MachineIRBuilder::buildFSub(), llvm::MachineIRBuilder::buildLoad(), llvm::MachineIRBuilder::buildLShr(), llvm::MachineIRBuilder::buildMerge(), llvm::MachineIRBuilder::buildPtrAdd(), llvm::MachineIRBuilder::buildStore(), llvm::MachineIRBuilder::buildTrunc(), llvm::MachineIRBuilder::buildUnmerge(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineIRBuilder::getMF(), llvm::MachineIRBuilder::getMRI(), llvm::MachineInstrBuilder::getReg(), llvm::isPowerOf2_64(), llvm::SPII::Load, llvm::Log2_32(), Merge, MI, llvm::LegalizerHelper::MIRBuilder, MRI, llvm::LLT::scalar(), and llvm::Check::Size.
legalizeIntrinsic()
bool MipsLegalizerInfo::legalizeIntrinsic (LegalizerHelper & Helper, MachineInstr & MI) const override virtual
Returns
true if MI is either legal or has been legalized and false if not legal. Return true if MI is either legal or has been legalized and false if not legal.
Reimplemented from llvm::LegalizerInfo.
Definition at line 502 of file MipsLegalizerInfo.cpp.
References llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildLoad(), llvm::MachineIRBuilder::buildStore(), llvm::constrainSelectedInstRegOperands(), MI, llvm::LegalizerHelper::MIRBuilder, llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, MSA2OpIntrinsicToGeneric(), MSA3OpIntrinsicToGeneric(), llvm::LLT::pointer(), SelectMSA3OpIntrinsic(), llvm::ARM_MB::ST, TII, llvm::ISD::TRAP, and TRI.
The documentation for this class was generated from the following files:
lib/Target/Mips/MipsLegalizerInfo.h
lib/Target/Mips/MipsLegalizerInfo.cpp