LLVM: llvm::SmallVector< T, N > Class Template Reference
llvm::SmallVector< T, N > Class Template Reference
This is a 'vector' (really, a variable-sized array), optimized for the case when the array is small.
#include "llvm/ADT/SmallVector.h"
Inherits llvm::SmallVectorImpl< T >, and llvm::SmallVectorStorage< T, CalculateSmallVectorDefaultInlinedElements< T >::value >.
Public Member Functions
SmallVector ()
~SmallVector ()
SmallVector (size_t Size, const T &Value=T())
template<typename ItTy , typename = std::enable_if_t<std::is_convertible< typename std::iterator_traits<ItTy>::iterator_category, std::input_iterator_tag>::value>>
SmallVector (ItTy S, ItTy E)
template<typename RangeTy >
SmallVector (const iterator_range< RangeTy > &R)
SmallVector (std::initializer_list< T > IL)
SmallVector (const SmallVector &RHS)
SmallVector & operator= (const SmallVector &RHS)
SmallVector (SmallVector &&RHS)
SmallVector (SmallVectorImpl< T > &&RHS)
SmallVector & operator= (SmallVector &&RHS)
SmallVector & operator= (SmallVectorImpl< T > &&RHS)
SmallVector & operator= (std::initializer_list< T > IL)
Public Member Functions inherited from llvm::SmallVectorImpl< T >
SmallVectorImpl (const SmallVectorImpl &)=delete
~SmallVectorImpl ()
void clear ()
void resize (size_type N)
void resize_for_overwrite (size_type N)
Like resize, but T is POD, the new values won't be initialized.
void resize (size_type N, ValueParamT NV)
void reserve (size_type N)
void pop_back_n (size_type NumItems)
LLVM_NODISCARD T pop_back_val ()
void swap (SmallVectorImpl &RHS)
template<typename in_iter , typename = std::enable_if_t<std::is_convertible< typename std::iterator_traits<in_iter>::iterator_category, std::input_iterator_tag>::value>>
void append (in_iter in_start, in_iter in_end)
Add the specified range to the end of the SmallVector.
void append (size_type NumInputs, ValueParamT Elt)
Append NumInputs copies of Elt to the end.
void append (std::initializer_list< T > IL)
void append (const SmallVectorImpl &RHS)
void assign (size_type NumElts, ValueParamT Elt)
template<typename in_iter , typename = std::enable_if_t<std::is_convertible< typename std::iterator_traits<in_iter>::iterator_category, std::input_iterator_tag>::value>>
void assign (in_iter in_start, in_iter in_end)
void assign (std::initializer_list< T > IL)
void assign (const SmallVectorImpl &RHS)
iterator erase (const_iterator CI)
iterator erase (const_iterator CS, const_iterator CE)
iterator insert (iterator I, T &&Elt)
iterator insert (iterator I, const T &Elt)
iterator insert (iterator I, size_type NumToInsert, ValueParamT Elt)
template<typename ItTy , typename = std::enable_if_t<std::is_convertible< typename std::iterator_traits<ItTy>::iterator_category, std::input_iterator_tag>::value>>
iterator insert (iterator I, ItTy From, ItTy To)
void insert (iterator I, std::initializer_list< T > IL)
template<typename... ArgTypes>
reference emplace_back (ArgTypes &&... Args)
SmallVectorImpl & operator= (const SmallVectorImpl &RHS)
SmallVectorImpl & operator= (SmallVectorImpl &&RHS)
bool operator== (const SmallVectorImpl &RHS) const
bool operator!= (const SmallVectorImpl &RHS) const
bool operator< (const SmallVectorImpl &RHS) const
Public Member Functions inherited from llvm::SmallVectorTemplateBase< T, bool >
void push_back (const T &Elt)
void push_back (T &&Elt)
void pop_back ()
Public Member Functions inherited from llvm::SmallVectorTemplateCommon< T, typename >
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type size_in_bytes () const
size_type max_size () const
size_t capacity_in_bytes () const
pointer data ()
Return a pointer to the vector's buffer, even if empty().
const_pointer data () const
Return a pointer to the vector's buffer, even if empty().
reference operator[] (size_type idx)
const_reference operator[] (size_type idx) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
Public Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
size_t size () const
size_t capacity () const
LLVM_NODISCARD bool empty () const
void set_size (size_t N)
Set the array size to N, which the current array must have enough capacity for.
Additional Inherited Members
Public Types inherited from llvm::SmallVectorImpl< T >
using iterator = typename SuperClass::iterator
using const_iterator = typename SuperClass::const_iterator
using reference = typename SuperClass::reference
using size_type = typename SuperClass::size_type
Public Types inherited from llvm::SmallVectorTemplateCommon< T, typename >
using size_type = size_t
using difference_type = ptrdiff_t
using value_type = T
using iterator = T *
using const_iterator = const T *
using const_reverse_iterator = std::reverse_iterator< const_iterator >
using reverse_iterator = std::reverse_iterator< iterator >
using reference = T &
using const_reference = const T &
using pointer = T *
using const_pointer = const T *
Protected Types inherited from llvm::SmallVectorImpl< T >
using ValueParamT = typename SuperClass::ValueParamT
Protected Types inherited from llvm::SmallVectorTemplateBase< T, bool >
using ValueParamT = const T &
Protected Member Functions inherited from llvm::SmallVectorImpl< T >
SmallVectorImpl (unsigned N)
Protected Member Functions inherited from llvm::SmallVectorTemplateBase< T, bool >
SmallVectorTemplateBase (size_t Size)
void grow (size_t MinSize=0)
Grow the allocated memory (without initializing new elements), doubling the size of the allocated memory.
T * mallocForGrow (size_t MinSize, size_t &NewCapacity)
Create a new allocation big enough for MinSize and pass back its size in NewCapacity.
void moveElementsForGrow (T *NewElts)
Move existing elements over to the new allocation NewElts, the middle section of grow().
void takeAllocationForGrow (T *NewElts, size_t NewCapacity)
Transfer ownership of the allocation, finishing up grow().
const T * reserveForParamAndGetAddress (const T &Elt, size_t N=1)
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
T * reserveForParamAndGetAddress (T &Elt, size_t N=1)
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
void growAndAssign (size_t NumElts, const T &Elt)
template<typename... ArgTypes>
T & growAndEmplaceBack (ArgTypes &&... Args)
Protected Member Functions inherited from llvm::SmallVectorTemplateCommon< T, typename >
SmallVectorTemplateCommon (size_t Size)
void grow_pod (size_t MinSize, size_t TSize)
bool isSmall () const
Return true if this is a smallvector which has not had dynamic memory allocated for it.
void resetToSmall ()
Put this vector in a state of being small.
bool isReferenceToRange (const void *V, const void *First, const void *Last) const
Return true if V is an internal reference to the given range.
bool isReferenceToStorage (const void *V) const
Return true if V is an internal reference to this vector.
bool isRangeInStorage (const void *First, const void *Last) const
Return true if First and Last form a valid (possibly empty) range in this vector's storage.
bool isSafeToReferenceAfterResize (const void *Elt, size_t NewSize)
Return true unless Elt will be invalidated by resizing the vector to NewSize.
void assertSafeToReferenceAfterResize (const void *Elt, size_t NewSize)
Check whether Elt will be invalidated by resizing the vector to NewSize.
void assertSafeToAdd (const void *Elt, size_t N=1)
Check whether Elt will be invalidated by increasing the size of the vector by N.
void assertSafeToReferenceAfterClear (const T *From, const T *To)
Check whether any part of the range will be invalidated by clearing.
template<class ItTy , std::enable_if_t<!std::is_same< std::remove_const_t< ItTy >, T * >::value, bool > = false>
void assertSafeToReferenceAfterClear (ItTy, ItTy)
void assertSafeToAddRange (const T *From, const T *To)
Check whether any part of the range will be invalidated by growing.
template<class ItTy , std::enable_if_t<!std::is_same< std::remove_const_t< ItTy >, T * >::value, bool > = false>
void assertSafeToAddRange (ItTy, ItTy)
Protected Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
SmallVectorBase ()=delete
SmallVectorBase (void *FirstEl, size_t TotalCapacity)
void * mallocForGrow (size_t MinSize, size_t TSize, size_t &NewCapacity)
This is a helper for grow() that's out of line to reduce code duplication.
void grow_pod (void *FirstEl, size_t MinSize, size_t TSize)
This is an implementation of the grow() method which only works on POD-like data types and is out of line to reduce code duplication.
Static Protected Member Functions inherited from llvm::SmallVectorTemplateBase< T, bool >
static void destroy_range (T *S, T *E)
template<typename It1 , typename It2 >
static void uninitialized_move (It1 I, It1 E, It2 Dest)
Move the range [I, E) into the uninitialized memory starting with "Dest", constructing elements as needed.
template<typename It1 , typename It2 >
static void uninitialized_copy (It1 I, It1 E, It2 Dest)
Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements as needed.
static T && forward_value_param (T &&V)
static const T & forward_value_param (const T &V)
Static Protected Member Functions inherited from llvm::SmallVectorTemplateCommon< T, typename >
template<class U >
static const T * reserveForParamAndGetAddressImpl (U *This, const T &Elt, size_t N)
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
Static Protected Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
static constexpr size_t SizeTypeMax ()
The maximum value of the Size_T used.
Protected Attributes inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
void * BeginX
SmallVectorSizeType< T > Size
SmallVectorSizeType< T > Capacity
Static Protected Attributes inherited from llvm::SmallVectorTemplateBase< T, bool >
static constexpr bool TakesParamByValue = false
Detailed Description
template<typename T, unsigned N = CalculateSmallVectorDefaultInlinedElements<T>::value>
class llvm::SmallVector< T, N >
This is a 'vector' (really, a variable-sized array), optimized for the case when the array is small.
It contains some number of elements in-place, which allows it to avoid heap allocation when the actual number of elements is below that threshold. This allows normal "small" cases to be fast without losing generality for large inputs.
Note
In the absence of a well-motivated choice for the number of inlined elements N, it is recommended to use SmallVector<T> (that is, omitting the N). This will choose a default number of inlined elements reasonable for allocation on the stack (for example, trying to keep sizeof(SmallVector<T>) around 64 bytes).
Warning
This does not attempt to be exception safe.
See also
https://llvm.org/docs/ProgrammersManual.html#llvm-adt-smallvector-h
Definition at line 1168 of file SmallVector.h.
Constructor & Destructor Documentation
SmallVector() [1/8]
template<typename T , unsigned N = CalculateSmallVectorDefaultInlinedElements<T>::value> llvm::SmallVector< T, N >::SmallVector () inline
Definition at line 1171 of file SmallVector.h.
References T.
~SmallVector()
template<typename T , unsigned N = CalculateSmallVectorDefaultInlinedElements<T>::value> llvm::SmallVector< T, N >::~SmallVector () inline
Definition at line 1173 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateBase< T, bool >::destroy_range(), and llvm::SmallVectorTemplateCommon< T, typename >::end().
SmallVector() [2/8]
template<typename T , unsigned N = CalculateSmallVectorDefaultInlinedElements<T>::value> llvm::SmallVector< T, N >::SmallVector (size_t Size, const T & Value = T()) inline explicit
Definition at line 1178 of file SmallVector.h.
References llvm::SmallVectorImpl< T >::assign(), and T.
SmallVector() [3/8]
template<typename T , unsigned N = CalculateSmallVectorDefaultInlinedElements<T>::value> template<typename ItTy , typename = std::enable_if_t<std::is_convertible< typename std::iterator_traits<ItTy>::iterator_category, std::input_iterator_tag>::value>> llvm::SmallVector< T, N >::SmallVector (ItTy S, ItTy E) inline
Definition at line 1187 of file SmallVector.h.
References llvm::SmallVectorImpl< T >::append(), E, and T.
SmallVector() [4/8]
template<typename T , unsigned N = CalculateSmallVectorDefaultInlinedElements<T>::value> template<typename RangeTy > llvm::SmallVector< T, N >::SmallVector (const iterator_range< RangeTy > & R) inline explicit
Definition at line 1192 of file SmallVector.h.
References llvm::SmallVectorImpl< T >::append(), llvm::iterator_range< IteratorT >::begin(), and T.
SmallVector() [5/8]
template<typename T , unsigned N = CalculateSmallVectorDefaultInlinedElements<T>::value> llvm::SmallVector< T, N >::SmallVector (std::initializer_list< T > IL) inline
Definition at line 1197 of file SmallVector.h.
References llvm::SmallVectorImpl< T >::assign(), and T.
SmallVector() [6/8]
template<typename T , unsigned N = CalculateSmallVectorDefaultInlinedElements<T>::value> llvm::SmallVector< T, N >::SmallVector (const SmallVector< T, N > & RHS) inline
Definition at line 1201 of file SmallVector.h.
References llvm::SmallVectorBase< Size_T >::empty(), llvm::SmallVectorImpl< T >::operator=(), and T.
SmallVector() [7/8]
template<typename T , unsigned N = CalculateSmallVectorDefaultInlinedElements<T>::value> llvm::SmallVector< T, N >::SmallVector (SmallVector< T, N > && RHS) inline
Definition at line 1211 of file SmallVector.h.
References llvm::move(), llvm::SmallVectorImpl< T >::operator=(), and T.
SmallVector() [8/8]
template<typename T , unsigned N = CalculateSmallVectorDefaultInlinedElements<T>::value> llvm::SmallVector< T, N >::SmallVector (SmallVectorImpl< T > && RHS) inline
Definition at line 1216 of file SmallVector.h.
References llvm::move(), llvm::SmallVectorImpl< T >::operator=(), and T.
Member Function Documentation
operator=() [1/4]
template<typename T , unsigned N = CalculateSmallVectorDefaultInlinedElements<T>::value> SmallVector& llvm::SmallVector< T, N >::operator= (const SmallVector< T, N > & RHS) inline
Definition at line 1206 of file SmallVector.h.
References llvm::SmallVectorImpl< T >::operator=().
operator=() [2/4]
template<typename T , unsigned N = CalculateSmallVectorDefaultInlinedElements<T>::value> SmallVector& llvm::SmallVector< T, N >::operator= (SmallVector< T, N > && RHS) inline
Definition at line 1221 of file SmallVector.h.
References llvm::move(), and llvm::SmallVectorImpl< T >::operator=().
operator=() [3/4]
template<typename T , unsigned N = CalculateSmallVectorDefaultInlinedElements<T>::value> SmallVector& llvm::SmallVector< T, N >::operator= (SmallVectorImpl< T > && RHS) inline
Definition at line 1226 of file SmallVector.h.
References llvm::move(), and llvm::SmallVectorImpl< T >::operator=().
operator=() [4/4]
template<typename T , unsigned N = CalculateSmallVectorDefaultInlinedElements<T>::value> SmallVector& llvm::SmallVector< T, N >::operator= (std::initializer_list< T > IL) inline
Definition at line 1231 of file SmallVector.h.
References llvm::SmallVectorImpl< T >::assign().
The documentation for this class was generated from the following file:
include/llvm/ADT/SmallVector.h