LLVM: llvm::orc::OrcRPCTargetProcessControlBase< RPCEndpointT > Class Template Reference
llvm::orc::OrcRPCTargetProcessControlBase< RPCEndpointT > Class Template Reference
#include "llvm/ExecutionEngine/Orc/OrcRPCTargetProcessControl.h"
Public Types
using ErrorReporter = unique_function< void(Error)>
using OnCloseConnectionFunction = unique_function< Error(Error)>
Public Member Functions
OrcRPCTargetProcessControlBase (std::shared_ptr< SymbolStringPool > SSP, RPCEndpointT &EP, ErrorReporter ReportError)
void reportError (Error Err)
RPCEndpointT & getEndpoint ()
Expected< tpctypes::DylibHandle > loadDylib (const char *DylibPath) override
Load the dynamic library at the given path and return a handle to it.
Expected< std::vector< tpctypes::LookupResult > > lookupSymbols (ArrayRef< LookupRequest > Request) override
Search for symbols in the target process.
Expected< int32_t > runAsMain (JITTargetAddress MainFnAddr, ArrayRef< std::string > Args) override
Run function with a main-like signature.
Expected< tpctypes::WrapperFunctionResult > runWrapper (JITTargetAddress WrapperFnAddr, ArrayRef< uint8_t > ArgBuffer) override
Run a wrapper function with signature:
Error closeConnection (OnCloseConnectionFunction OnCloseConnection)
Error closeConnectionAndWait ()
Public Member Functions inherited from llvm::orc::TargetProcessControl
virtual ~TargetProcessControl ()
SymbolStringPtr intern (StringRef SymName)
Intern a symbol name in the SymbolStringPool.
std::shared_ptr< SymbolStringPool > getSymbolStringPool () const
Return a shared pointer to the SymbolStringPool for this instance.
const Triple & getTargetTriple () const
Return the Triple for the target process.
unsigned getPageSize () const
Get the page size for the target process.
MemoryAccess & getMemoryAccess () const
Return a MemoryAccess object for the target process.
jitlink::JITLinkMemoryManager & getMemMgr () const
Return a JITLinkMemoryManager for the target process.
virtual Error disconnect ()=0
Disconnect from the target process.
Protected Member Functions
Error initializeORCRPCTPCBase ()
Subclasses must call this during construction to initialize the TargetTriple and PageSize members.
Protected Member Functions inherited from llvm::orc::TargetProcessControl
TargetProcessControl (std::shared_ptr< SymbolStringPool > SSP)
Additional Inherited Members
Protected Attributes inherited from llvm::orc::TargetProcessControl
std::shared_ptr< SymbolStringPool > SSP
Triple TargetTriple
unsigned PageSize = 0
MemoryAccess * MemAccess = nullptr
jitlink::JITLinkMemoryManager * MemMgr = nullptr
Detailed Description
template<typename RPCEndpointT>
class llvm::orc::OrcRPCTargetProcessControlBase< RPCEndpointT >
Definition at line 277 of file OrcRPCTargetProcessControl.h.
Member Typedef Documentation
ErrorReporter
template<typename RPCEndpointT > using llvm::orc::OrcRPCTargetProcessControlBase< RPCEndpointT >::ErrorReporter = unique_function<void(Error)>
Definition at line 279 of file OrcRPCTargetProcessControl.h.
OnCloseConnectionFunction
template<typename RPCEndpointT > using llvm::orc::OrcRPCTargetProcessControlBase< RPCEndpointT >::OnCloseConnectionFunction = unique_function<Error(Error)>
Definition at line 281 of file OrcRPCTargetProcessControl.h.
Constructor & Destructor Documentation
OrcRPCTargetProcessControlBase()
template<typename RPCEndpointT > llvm::orc::OrcRPCTargetProcessControlBase< RPCEndpointT >::OrcRPCTargetProcessControlBase (std::shared_ptr< SymbolStringPool > SSP, RPCEndpointT & EP, ErrorReporter ReportError) inline
Definition at line 283 of file OrcRPCTargetProcessControl.h.
Member Function Documentation
closeConnection()
template<typename RPCEndpointT > Error llvm::orc::OrcRPCTargetProcessControlBase< RPCEndpointT >::closeConnection (OnCloseConnectionFunction OnCloseConnection) inline
Definition at line 371 of file OrcRPCTargetProcessControl.h.
References llvm::dbgs(), DEBUG_WITH_TYPE, and llvm::move().
closeConnectionAndWait()
template<typename RPCEndpointT > Error llvm::orc::OrcRPCTargetProcessControlBase< RPCEndpointT >::closeConnectionAndWait () inline
Definition at line 377 of file OrcRPCTargetProcessControl.h.
References F, and P.
getEndpoint()
template<typename RPCEndpointT > RPCEndpointT& llvm::orc::OrcRPCTargetProcessControlBase< RPCEndpointT >::getEndpoint () inline
Definition at line 290 of file OrcRPCTargetProcessControl.h.
initializeORCRPCTPCBase()
template<typename RPCEndpointT > Error llvm::orc::OrcRPCTargetProcessControlBase< RPCEndpointT >::initializeORCRPCTPCBase () inline protected
Subclasses must call this during construction to initialize the TargetTriple and PageSize members.
Definition at line 393 of file OrcRPCTargetProcessControl.h.
References PageSize, and llvm::Error::success().
loadDylib()
template<typename RPCEndpointT > Expected<tpctypes::DylibHandle> llvm::orc::OrcRPCTargetProcessControlBase< RPCEndpointT >::loadDylib (const char * DylibPath) inline override virtual
Load the dynamic library at the given path and return a handle to it.
If LibraryPath is null this function will return the global handle for the target process.
Implements llvm::orc::TargetProcessControl.
Definition at line 292 of file OrcRPCTargetProcessControl.h.
References llvm::dbgs(), DEBUG_WITH_TYPE, llvm::formatv(), and H.
lookupSymbols()
template<typename RPCEndpointT > Expected<std::vector<tpctypes::LookupResult> > llvm::orc::OrcRPCTargetProcessControlBase< RPCEndpointT >::lookupSymbols (ArrayRef< LookupRequest > Request) inline override virtual
Search for symbols in the target process.
The result of the lookup is a 2-dimentional array of target addresses that correspond to the lookup order. If a required symbol is not found then this method will return an error. If a weakly referenced symbol is not found then it be assigned a '0' value in the result. that correspond to the lookup order.
Implements llvm::orc::TargetProcessControl.
Definition at line 312 of file OrcRPCTargetProcessControl.h.
References llvm::dbgs(), DEBUG_WITH_TYPE, E, and llvm::formatv().
reportError()
template<typename RPCEndpointT > void llvm::orc::OrcRPCTargetProcessControlBase< RPCEndpointT >::reportError (Error Err) inline
Definition at line 288 of file OrcRPCTargetProcessControl.h.
runAsMain()
template<typename RPCEndpointT > Expected<int32_t> llvm::orc::OrcRPCTargetProcessControlBase< RPCEndpointT >::runAsMain (JITTargetAddress MainFnAddr, ArrayRef< std::string > Args) inline override virtual
Run function with a main-like signature.
Implements llvm::orc::TargetProcessControl.
Definition at line 337 of file OrcRPCTargetProcessControl.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::dbgs(), DEBUG_WITH_TYPE, llvm::formatv(), and I.
runWrapper()
template<typename RPCEndpointT > Expected<tpctypes::WrapperFunctionResult> llvm::orc::OrcRPCTargetProcessControlBase< RPCEndpointT >::runWrapper (JITTargetAddress WrapperFnAddr, ArrayRef< uint8_t > ArgBuffer) inline override virtual
Run a wrapper function with signature:
CWrapperFunctionResult fn(uint8_t *Data, uint64_t Size);
{.cpp}
Implements llvm::orc::TargetProcessControl.
Definition at line 358 of file OrcRPCTargetProcessControl.h.
References llvm::dbgs(), DEBUG_WITH_TYPE, llvm::formatv(), and llvm::ArrayRef< T >::size().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/OrcRPCTargetProcessControl.h