LLVM: llvm::AArch64TargetWinCOFFStreamer Class Reference
llvm::AArch64TargetWinCOFFStreamer Class Reference
#include "Target/AArch64/MCTargetDesc/AArch64TargetStreamer.h"
Public Member Functions
AArch64TargetWinCOFFStreamer (llvm::MCStreamer &S)
void EmitARM64WinCFIAllocStack (unsigned Size) override
void EmitARM64WinCFISaveR19R20X (int Offset) override
void EmitARM64WinCFISaveFPLR (int Offset) override
void EmitARM64WinCFISaveFPLRX (int Offset) override
void EmitARM64WinCFISaveReg (unsigned Reg, int Offset) override
void EmitARM64WinCFISaveRegX (unsigned Reg, int Offset) override
void EmitARM64WinCFISaveRegP (unsigned Reg, int Offset) override
void EmitARM64WinCFISaveRegPX (unsigned Reg, int Offset) override
void EmitARM64WinCFISaveLRPair (unsigned Reg, int Offset) override
void EmitARM64WinCFISaveFReg (unsigned Reg, int Offset) override
void EmitARM64WinCFISaveFRegX (unsigned Reg, int Offset) override
void EmitARM64WinCFISaveFRegP (unsigned Reg, int Offset) override
void EmitARM64WinCFISaveFRegPX (unsigned Reg, int Offset) override
void EmitARM64WinCFISetFP () override
void EmitARM64WinCFIAddFP (unsigned Size) override
void EmitARM64WinCFINop () override
void EmitARM64WinCFISaveNext () override
void EmitARM64WinCFIPrologEnd () override
void EmitARM64WinCFIEpilogStart () override
void EmitARM64WinCFIEpilogEnd () override
void EmitARM64WinCFITrapFrame () override
void EmitARM64WinCFIMachineFrame () override
void EmitARM64WinCFIContext () override
void EmitARM64WinCFIClearUnwoundToCall () override
Public Member Functions inherited from llvm::AArch64TargetStreamer
AArch64TargetStreamer (MCStreamer &S)
~AArch64TargetStreamer () override
void finish () override
const MCExpr * addConstantPoolEntry (const MCExpr *, unsigned Size, SMLoc Loc)
Callback used to implement the ldr= pseudo.
void emitCurrentConstantPool ()
Callback used to implemnt the .ltorg directive.
void emitNoteSection (unsigned Flags)
Callback used to implement the .note.gnu.property section.
virtual void emitInst (uint32_t Inst)
Callback used to implement the .inst directive.
virtual void emitDirectiveVariantPCS (MCSymbol *Symbol)
Callback used to implement the .variant_pcs directive.
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, const MCExpr *SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 85 of file AArch64TargetStreamer.h.
Constructor & Destructor Documentation
AArch64TargetWinCOFFStreamer()
llvm::AArch64TargetWinCOFFStreamer::AArch64TargetWinCOFFStreamer (llvm::MCStreamer & S) inline
Definition at line 93 of file AArch64TargetStreamer.h.
Member Function Documentation
EmitARM64WinCFIAddFP()
void llvm::AArch64TargetWinCOFFStreamer::EmitARM64WinCFIAddFP (unsigned Size) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 159 of file AArch64WinCOFFStreamer.cpp.
References assert(), Offset, and llvm::Win64EH::UOP_AddFP.
EmitARM64WinCFIAllocStack()
void llvm::AArch64TargetWinCOFFStreamer::EmitARM64WinCFIAllocStack (unsigned Size) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 85 of file AArch64WinCOFFStreamer.cpp.
References llvm::Check::Size, llvm::Win64EH::UOP_AllocLarge, llvm::Win64EH::UOP_AllocMedium, and llvm::Win64EH::UOP_AllocSmall.
EmitARM64WinCFIClearUnwoundToCall()
void llvm::AArch64TargetWinCOFFStreamer::EmitARM64WinCFIClearUnwoundToCall () override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 222 of file AArch64WinCOFFStreamer.cpp.
References llvm::Win64EH::UOP_ClearUnwoundToCall.
EmitARM64WinCFIContext()
void llvm::AArch64TargetWinCOFFStreamer::EmitARM64WinCFIContext () override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 218 of file AArch64WinCOFFStreamer.cpp.
References llvm::Win64EH::UOP_Context.
EmitARM64WinCFIEpilogEnd()
void llvm::AArch64TargetWinCOFFStreamer::EmitARM64WinCFIEpilogEnd () override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 197 of file AArch64WinCOFFStreamer.cpp.
References llvm::WinEH::FrameInfo::EpilogMap, llvm::MCTargetStreamer::getStreamer(), and llvm::Win64EH::UOP_End.
EmitARM64WinCFIEpilogStart()
void llvm::AArch64TargetWinCOFFStreamer::EmitARM64WinCFIEpilogStart () override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 187 of file AArch64WinCOFFStreamer.cpp.
References llvm::MCTargetStreamer::getStreamer().
EmitARM64WinCFIMachineFrame()
void llvm::AArch64TargetWinCOFFStreamer::EmitARM64WinCFIMachineFrame () override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 214 of file AArch64WinCOFFStreamer.cpp.
References llvm::Win64EH::UOP_PushMachFrame.
EmitARM64WinCFINop()
void llvm::AArch64TargetWinCOFFStreamer::EmitARM64WinCFINop () override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 164 of file AArch64WinCOFFStreamer.cpp.
References llvm::Win64EH::UOP_Nop.
EmitARM64WinCFIPrologEnd()
void llvm::AArch64TargetWinCOFFStreamer::EmitARM64WinCFIPrologEnd () override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 174 of file AArch64WinCOFFStreamer.cpp.
References llvm::MCTargetStreamer::getStreamer(), llvm::WinEH::FrameInfo::Instructions, llvm::WinEH::FrameInfo::PrologEnd, and llvm::Win64EH::UOP_End.
EmitARM64WinCFISaveFPLR()
void llvm::AArch64TargetWinCOFFStreamer::EmitARM64WinCFISaveFPLR (int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 98 of file AArch64WinCOFFStreamer.cpp.
References Offset, and llvm::Win64EH::UOP_SaveFPLR.
EmitARM64WinCFISaveFPLRX()
void llvm::AArch64TargetWinCOFFStreamer::EmitARM64WinCFISaveFPLRX (int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 102 of file AArch64WinCOFFStreamer.cpp.
References Offset, and llvm::Win64EH::UOP_SaveFPLRX.
EmitARM64WinCFISaveFReg()
void llvm::AArch64TargetWinCOFFStreamer::EmitARM64WinCFISaveFReg (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 133 of file AArch64WinCOFFStreamer.cpp.
References assert(), Offset, Reg, and llvm::Win64EH::UOP_SaveFReg.
EmitARM64WinCFISaveFRegP()
void llvm::AArch64TargetWinCOFFStreamer::EmitARM64WinCFISaveFRegP (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 145 of file AArch64WinCOFFStreamer.cpp.
References Offset, Reg, and llvm::Win64EH::UOP_SaveFRegP.
EmitARM64WinCFISaveFRegPX()
void llvm::AArch64TargetWinCOFFStreamer::EmitARM64WinCFISaveFRegPX (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 150 of file AArch64WinCOFFStreamer.cpp.
References Offset, Reg, and llvm::Win64EH::UOP_SaveFRegPX.
EmitARM64WinCFISaveFRegX()
void llvm::AArch64TargetWinCOFFStreamer::EmitARM64WinCFISaveFRegX (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 140 of file AArch64WinCOFFStreamer.cpp.
References Offset, Reg, and llvm::Win64EH::UOP_SaveFRegX.
EmitARM64WinCFISaveLRPair()
void llvm::AArch64TargetWinCOFFStreamer::EmitARM64WinCFISaveLRPair (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 128 of file AArch64WinCOFFStreamer.cpp.
References Offset, Reg, and llvm::Win64EH::UOP_SaveLRPair.
EmitARM64WinCFISaveNext()
void llvm::AArch64TargetWinCOFFStreamer::EmitARM64WinCFISaveNext () override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 168 of file AArch64WinCOFFStreamer.cpp.
References llvm::Win64EH::UOP_SaveNext.
EmitARM64WinCFISaveR19R20X()
void llvm::AArch64TargetWinCOFFStreamer::EmitARM64WinCFISaveR19R20X (int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 94 of file AArch64WinCOFFStreamer.cpp.
References Offset, and llvm::Win64EH::UOP_SaveR19R20X.
EmitARM64WinCFISaveReg()
void llvm::AArch64TargetWinCOFFStreamer::EmitARM64WinCFISaveReg (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 106 of file AArch64WinCOFFStreamer.cpp.
References assert(), Offset, Reg, and llvm::Win64EH::UOP_SaveReg.
EmitARM64WinCFISaveRegP()
void llvm::AArch64TargetWinCOFFStreamer::EmitARM64WinCFISaveRegP (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 118 of file AArch64WinCOFFStreamer.cpp.
References Offset, Reg, and llvm::Win64EH::UOP_SaveRegP.
EmitARM64WinCFISaveRegPX()
void llvm::AArch64TargetWinCOFFStreamer::EmitARM64WinCFISaveRegPX (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 123 of file AArch64WinCOFFStreamer.cpp.
References Offset, Reg, and llvm::Win64EH::UOP_SaveRegPX.
EmitARM64WinCFISaveRegX()
void llvm::AArch64TargetWinCOFFStreamer::EmitARM64WinCFISaveRegX (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 113 of file AArch64WinCOFFStreamer.cpp.
References Offset, Reg, and llvm::Win64EH::UOP_SaveRegX.
EmitARM64WinCFISetFP()
void llvm::AArch64TargetWinCOFFStreamer::EmitARM64WinCFISetFP () override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 155 of file AArch64WinCOFFStreamer.cpp.
References llvm::Win64EH::UOP_SetFP.
EmitARM64WinCFITrapFrame()
void llvm::AArch64TargetWinCOFFStreamer::EmitARM64WinCFITrapFrame () override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 210 of file AArch64WinCOFFStreamer.cpp.
References llvm::Win64EH::UOP_TrapFrame.
The documentation for this class was generated from the following files:
lib/Target/AArch64/MCTargetDesc/AArch64TargetStreamer.h
lib/Target/AArch64/MCTargetDesc/AArch64WinCOFFStreamer.cpp