LLVM: llvm::RISCVTargetELFStreamer Class Reference
llvm::RISCVTargetELFStreamer Class Reference
#include "Target/RISCV/MCTargetDesc/RISCVELFStreamer.h"
Public Member Functions
MCELFStreamer & getStreamer ()
RISCVTargetELFStreamer (MCStreamer &S, const MCSubtargetInfo &STI)
void emitDirectiveOptionPush () override
void emitDirectiveOptionPop () override
void emitDirectiveOptionPIC () override
void emitDirectiveOptionNoPIC () override
void emitDirectiveOptionRVC () override
void emitDirectiveOptionNoRVC () override
void emitDirectiveOptionRelax () override
void emitDirectiveOptionNoRelax () override
Public Member Functions inherited from llvm::RISCVTargetStreamer
RISCVTargetStreamer (MCStreamer &S)
void finish () override
void emitTargetAttributes (const MCSubtargetInfo &STI)
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, const MCExpr *SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 17 of file RISCVELFStreamer.h.
Constructor & Destructor Documentation
RISCVTargetELFStreamer()
RISCVTargetELFStreamer::RISCVTargetELFStreamer (MCStreamer & S, const MCSubtargetInfo & STI)
Definition at line 27 of file RISCVELFStreamer.cpp.
References llvm::RISCVABI::ABI_ILP32, llvm::RISCVABI::ABI_ILP32D, llvm::RISCVABI::ABI_ILP32E, llvm::RISCVABI::ABI_ILP32F, llvm::RISCVABI::ABI_LP64, llvm::RISCVABI::ABI_LP64D, llvm::RISCVABI::ABI_LP64F, llvm::RISCVABI::ABI_Unknown, assert(), llvm::ELF::EF_RISCV_FLOAT_ABI_DOUBLE, llvm::ELF::EF_RISCV_FLOAT_ABI_SINGLE, llvm::ELF::EF_RISCV_RVC, llvm::ELF::EF_RISCV_RVE, llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getBackend(), llvm::MCAssembler::getELFHeaderEFlags(), llvm::MCSubtargetInfo::getFeatureBits(), getStreamer(), llvm_unreachable, and llvm::MCAssembler::setELFHeaderEFlags().
Member Function Documentation
emitDirectiveOptionNoPIC()
void RISCVTargetELFStreamer::emitDirectiveOptionNoPIC () override virtual
Reimplemented from llvm::RISCVTargetStreamer.
Definition at line 70 of file RISCVELFStreamer.cpp.
emitDirectiveOptionNoRelax()
void RISCVTargetELFStreamer::emitDirectiveOptionNoRelax () override virtual
Reimplemented from llvm::RISCVTargetStreamer.
Definition at line 74 of file RISCVELFStreamer.cpp.
emitDirectiveOptionNoRVC()
void RISCVTargetELFStreamer::emitDirectiveOptionNoRVC () override virtual
Reimplemented from llvm::RISCVTargetStreamer.
Definition at line 72 of file RISCVELFStreamer.cpp.
emitDirectiveOptionPIC()
void RISCVTargetELFStreamer::emitDirectiveOptionPIC () override virtual
Reimplemented from llvm::RISCVTargetStreamer.
Definition at line 69 of file RISCVELFStreamer.cpp.
emitDirectiveOptionPop()
void RISCVTargetELFStreamer::emitDirectiveOptionPop () override virtual
Reimplemented from llvm::RISCVTargetStreamer.
Definition at line 68 of file RISCVELFStreamer.cpp.
emitDirectiveOptionPush()
void RISCVTargetELFStreamer::emitDirectiveOptionPush () override virtual
Reimplemented from llvm::RISCVTargetStreamer.
Definition at line 67 of file RISCVELFStreamer.cpp.
emitDirectiveOptionRelax()
void RISCVTargetELFStreamer::emitDirectiveOptionRelax () override virtual
Reimplemented from llvm::RISCVTargetStreamer.
Definition at line 73 of file RISCVELFStreamer.cpp.
emitDirectiveOptionRVC()
void RISCVTargetELFStreamer::emitDirectiveOptionRVC () override virtual
Reimplemented from llvm::RISCVTargetStreamer.
Definition at line 71 of file RISCVELFStreamer.cpp.
getStreamer()
MCELFStreamer & RISCVTargetELFStreamer::getStreamer ()
Definition at line 63 of file RISCVELFStreamer.cpp.
References llvm::MCTargetStreamer::Streamer.
Referenced by RISCVTargetELFStreamer().
The documentation for this class was generated from the following files:
lib/Target/RISCV/MCTargetDesc/RISCVELFStreamer.h
lib/Target/RISCV/MCTargetDesc/RISCVELFStreamer.cpp