LLVM: llvm::DDGDotPrinterPass Class Reference
llvm::DDGDotPrinterPass Class Reference
#include "llvm/Analysis/DDGPrinter.h"
Public Member Functions
PreservedAnalyses run (Loop &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< DDGDotPrinterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 27 of file DDGPrinter.h.
Member Function Documentation
run()
PreservedAnalyses DDGDotPrinterPass::run (Loop & L, LoopAnalysisManager & AM, LoopStandardAnalysisResults & AR, LPMUpdater & U)
Definition at line 32 of file DDGPrinter.cpp.
References llvm::PreservedAnalyses::all(), DotOnly, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and writeDDGToDotFile().
The documentation for this class was generated from the following files:
include/llvm/Analysis/DDGPrinter.h
lib/Analysis/DDGPrinter.cpp