LLVM: llvm::LiveIntervals Class Reference
llvm::LiveIntervals Class Reference
#include "llvm/CodeGen/LiveIntervals.h"
Classes
class HMEditor
Toolkit used by handleMove to trim or extend live intervals.
Public Member Functions
LiveIntervals ()
~LiveIntervals () override
LiveInterval & getInterval (Register Reg)
const LiveInterval & getInterval (Register Reg) const
bool hasInterval (Register Reg) const
LiveInterval & createEmptyInterval (Register Reg)
Interval creation.
LiveInterval & createAndComputeVirtRegInterval (Register Reg)
void removeInterval (Register Reg)
Interval removal.
LiveInterval::Segment addSegmentToEndOfBlock (Register Reg, MachineInstr &startInst)
Given a register and an instruction, adds a live segment from that instruction to the end of its MBB.
bool shrinkToUses (LiveInterval *li, SmallVectorImpl< MachineInstr * > *dead=nullptr)
After removing some uses of a register, shrink its live range to just the remaining uses.
void shrinkToUses (LiveInterval::SubRange &SR, Register Reg)
Specialized version of shrinkToUses(LiveInterval li, SmallVectorImpl<MachineInstr> *dead) that works on a subregister live range and only looks at uses matching the lane mask of the subregister range.
void extendToIndices (LiveRange &LR, ArrayRef< SlotIndex > Indices, ArrayRef< SlotIndex > Undefs)
Extend the live range LR to reach all points in Indices.
void extendToIndices (LiveRange &LR, ArrayRef< SlotIndex > Indices)
void pruneValue (LiveRange &LR, SlotIndex Kill, SmallVectorImpl< SlotIndex > *EndPoints)
If LR has a live value at Kill, prune its live range by removing any liveness reachable from Kill.
LLVM_ATTRIBUTE_UNUSED void pruneValue (LiveInterval &, SlotIndex, SmallVectorImpl< SlotIndex > *)
This function should not be used.
SlotIndexes * getSlotIndexes () const
AAResults * getAliasAnalysis () const
bool isNotInMIMap (const MachineInstr &Instr) const
Returns true if the specified machine instr has been removed or was never entered in the map.
SlotIndex getInstructionIndex (const MachineInstr &Instr) const
Returns the base index of the given instruction.
MachineInstr * getInstructionFromIndex (SlotIndex index) const
Returns the instruction associated with the given index.
SlotIndex getMBBStartIdx (const MachineBasicBlock *mbb) const
Return the first index in the given basic block.
SlotIndex getMBBEndIdx (const MachineBasicBlock *mbb) const
Return the last index in the given basic block.
bool isLiveInToMBB (const LiveRange &LR, const MachineBasicBlock *mbb) const
bool isLiveOutOfMBB (const LiveRange &LR, const MachineBasicBlock *mbb) const
MachineBasicBlock * getMBBFromIndex (SlotIndex index) const
void insertMBBInMaps (MachineBasicBlock *MBB)
SlotIndex InsertMachineInstrInMaps (MachineInstr &MI)
void InsertMachineInstrRangeInMaps (MachineBasicBlock::iterator B, MachineBasicBlock::iterator E)
void RemoveMachineInstrFromMaps (MachineInstr &MI)
SlotIndex ReplaceMachineInstrInMaps (MachineInstr &MI, MachineInstr &NewMI)
VNInfo::Allocator & getVNInfoAllocator ()
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
void releaseMemory () override
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
bool runOnMachineFunction (MachineFunction &) override
Pass entry point; Calculates LiveIntervals.
void print (raw_ostream &O, const Module *=nullptr) const override
Implement the dump method.
MachineBasicBlock * intervalIsInOneMBB (const LiveInterval &LI) const
If LI is confined to a single basic block, return a pointer to that block.
bool hasPHIKill (const LiveInterval &LI, const VNInfo *VNI) const
Returns true if VNI is killed by any PHI-def values in LI.
void addKillFlags (const VirtRegMap *)
Add kill flags to any instruction that kills a virtual register.
void handleMove (MachineInstr &MI, bool UpdateFlags=false)
Call this method to notify LiveIntervals that instruction MI has been moved within a basic block.
void handleMoveIntoNewBundle (MachineInstr &BundleStart, bool UpdateFlags=false)
Update intervals of operands of all instructions in the newly created bundle specified by BundleStart.
void repairIntervalsInRange (MachineBasicBlock *MBB, MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, ArrayRef< Register > OrigRegs)
Update live intervals for instructions in a range of iterators.
ArrayRef< SlotIndex > getRegMaskSlots () const
Returns a sorted array of slot indices of all instructions with register mask operands.
ArrayRef< SlotIndex > getRegMaskSlotsInBlock (unsigned MBBNum) const
Returns a sorted array of slot indices of all instructions with register mask operands in the basic block numbered MBBNum.
ArrayRef< const uint32_t * > getRegMaskBits () const
Returns an array of register mask pointers corresponding to getRegMaskSlots().
ArrayRef< const uint32_t * > getRegMaskBitsInBlock (unsigned MBBNum) const
Returns an array of mask pointers corresponding to getRegMaskSlotsInBlock(MBBNum).
bool checkRegMaskInterference (LiveInterval &LI, BitVector &UsableRegs)
Test if LI is live across any register mask instructions, and compute a bit mask of physical registers that are not clobbered by any of them.
LiveRange & getRegUnit (unsigned Unit)
Return the live range for register unit Unit.
LiveRange * getCachedRegUnit (unsigned Unit)
Return the live range for register unit Unit if it has already been computed, or nullptr if it hasn't been computed yet.
const LiveRange * getCachedRegUnit (unsigned Unit) const
void removeRegUnit (unsigned Unit)
Remove computed live range for register unit Unit.
void removeAllRegUnitsForPhysReg (MCRegister Reg)
Remove associated live ranges for the register units associated with Reg.
void removePhysRegDefAt (MCRegister Reg, SlotIndex Pos)
Remove value numbers and related live segments starting at position Pos that are part of any liverange of physical register Reg or one of its subregisters.
void removeVRegDefAt (LiveInterval &LI, SlotIndex Pos)
Remove value number and related live segments of LI and its subranges that start at position Pos.
void splitSeparateComponents (LiveInterval &LI, SmallVectorImpl< LiveInterval * > &SplitLIs)
Split separate components in LiveInterval LI into separate intervals.
void constructMainRangeFromSubranges (LiveInterval &LI)
For live interval LI with correct SubRanges construct matching information for the main live range.
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Static Public Member Functions
static float getSpillWeight (bool isDef, bool isUse, const MachineBlockFrequencyInfo *MBFI, const MachineInstr &MI)
Calculate the spill weight to assign to a single instruction.
static float getSpillWeight (bool isDef, bool isUse, const MachineBlockFrequencyInfo *MBFI, const MachineBasicBlock *MBB)
Calculate the spill weight to assign to a single instruction.
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
Definition at line 54 of file LiveIntervals.h.
Constructor & Destructor Documentation
LiveIntervals()
LiveIntervals::LiveIntervals ()
Definition at line 101 of file LiveIntervals.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeLiveIntervalsPass().
~LiveIntervals()
LiveIntervals::~LiveIntervals () override
Definition at line 105 of file LiveIntervals.cpp.
Member Function Documentation
addKillFlags()
void LiveIntervals::addKillFlags (const VirtRegMap * VRM)
Add kill flags to any instruction that kills a virtual register.
Definition at line 702 of file LiveIntervals.cpp.
References llvm::LiveRange::advanceTo(), llvm::LegalityPredicates::any(), assert(), llvm::LiveRange::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::numbers::e, llvm::LiveRange::empty(), llvm::LiveRange::end(), llvm::LiveRange::find(), llvm::LaneBitmask::getAll(), getInstructionFromIndex(), getInterval(), llvm::LaneBitmask::getNone(), llvm::MachineRegisterInfo::getNumVirtRegs(), llvm::VirtRegMap::getPhys(), getRegUnit(), llvm::TargetRegisterInfo::getSubRegIndexLaneMask(), I, llvm::Register::index2VirtReg(), llvm::LiveInterval::SubRange::LaneMask, MI, N, llvm::SmallVectorTemplateBase< T, bool >::push_back(), Reg, llvm::MachineRegisterInfo::reg_nodbg_empty(), llvm::RISCVFPRndMode::RUP, llvm::LiveInterval::subranges(), and llvm::MachineRegisterInfo::subRegLivenessEnabled().
addSegmentToEndOfBlock()
LiveRange::Segment LiveIntervals::addSegmentToEndOfBlock (Register Reg, MachineInstr & startInst)
Given a register and an instruction, adds a live segment from that instruction to the end of its MBB.
Definition at line 885 of file LiveIntervals.cpp.
References createEmptyInterval(), getInstructionIndex(), getMBBEndIdx(), llvm::MachineInstr::getParent(), getVNInfoAllocator(), and Reg.
checkRegMaskInterference()
bool LiveIntervals::checkRegMaskInterference (LiveInterval & LI, BitVector & UsableRegs)
Test if LI is live across any register mask instructions, and compute a bit mask of physical registers that are not clobbered by any of them.
Returns false if LI doesn't cross any register mask instructions. In that case, the bit vector is not filled in.
Definition at line 901 of file LiveIntervals.cpp.
References llvm::LiveRange::advanceTo(), assert(), llvm::LiveRange::begin(), llvm::ArrayRef< T >::begin(), llvm::tgtok::Bits, llvm::BitVector::clear(), llvm::BitVector::clearBitsNotInMask(), llvm::LiveRange::empty(), llvm::LiveRange::end(), llvm::ArrayRef< T >::end(), llvm::sys::path::end(), llvm::MachineBasicBlock::getNumber(), llvm::MCRegisterInfo::getNumRegs(), getRegMaskBits(), getRegMaskBitsInBlock(), getRegMaskSlots(), getRegMaskSlotsInBlock(), intervalIsInOneMBB(), llvm::lower_bound(), MBB, and llvm::BitVector::resize().
Referenced by llvm::LiveRegMatrix::checkRegMaskInterference().
constructMainRangeFromSubranges()
void LiveIntervals::constructMainRangeFromSubranges (LiveInterval & LI)
For live interval LI with correct SubRanges construct matching information for the main live range.
Expects the main live range to not have any segments or value numbers.
Definition at line 1731 of file LiveIntervals.cpp.
References assert(), llvm::LiveIntervalCalc::constructMainRangeFromSubranges(), getSlotIndexes(), getVNInfoAllocator(), and llvm::LiveRangeCalc::reset().
Referenced by llvm::LiveIntervals::HMEditor::updateAllRanges().
createAndComputeVirtRegInterval()
LiveInterval& llvm::LiveIntervals::createAndComputeVirtRegInterval (Register Reg) inline
Definition at line 138 of file LiveIntervals.h.
References createEmptyInterval(), and Reg.
Referenced by getInterval(), moveAndTeeForMultiUse(), moveForSingleUse(), and rematerializeCheapDef().
createEmptyInterval()
LiveInterval& llvm::LiveIntervals::createEmptyInterval (Register Reg) inline
Interval creation.
Definition at line 131 of file LiveIntervals.h.
References assert(), llvm::IndexedMap< T, ToIndexT >::grow(), hasInterval(), and Reg.
Referenced by addSegmentToEndOfBlock(), createAndComputeVirtRegInterval(), replaceRegUsesAfterLoop(), and splitSeparateComponents().
extendToIndices() [1/2]
void llvm::LiveIntervals::extendToIndices (LiveRange & LR, ArrayRef< SlotIndex > Indices) inline
Definition at line 187 of file LiveIntervals.h.
References extendToIndices().
extendToIndices() [2/2]
void LiveIntervals::extendToIndices (LiveRange & LR, ArrayRef< SlotIndex > Indices, ArrayRef< SlotIndex > Undefs)
Extend the live range LR to reach all points in Indices.
The points in the Indices array must be jointly dominated by the union of the existing defs in LR and points in Undefs.
PHI-defs are added as needed to maintain SSA form.
If a SlotIndex in Indices is the end index of a basic block, LR will be extended to be live out of the basic block. If a SlotIndex in Indices is jointy dominated only by points in Undefs, the live range will not be extended to that point.
See also LiveRangeCalc::extend().
Definition at line 631 of file LiveIntervals.cpp.
References assert(), llvm::LiveRangeCalc::extend(), getSlotIndexes(), getVNInfoAllocator(), and llvm::LiveRangeCalc::reset().
Referenced by extendToIndices(), and replaceDominatedUses().
getAliasAnalysis()
AAResults* llvm::LiveIntervals::getAliasAnalysis () const inline
Definition at line 215 of file LiveIntervals.h.
Referenced by isRematerializable().
getAnalysisUsage()
void LiveIntervals::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 88 of file LiveIntervals.cpp.
References llvm::AnalysisUsage::addPreserved(), llvm::AnalysisUsage::addPreservedID(), llvm::AnalysisUsage::addRequired(), llvm::AnalysisUsage::addRequiredTransitive(), llvm::AnalysisUsage::addRequiredTransitiveID(), llvm::MachineFunctionPass::getAnalysisUsage(), llvm::MachineDominatorsID, llvm::MachineLoopInfoID, and llvm::AnalysisUsage::setPreservesCFG().
getCachedRegUnit() [1/2]
LiveRange* llvm::LiveIntervals::getCachedRegUnit (unsigned Unit) inline
Return the live range for register unit Unit if it has already been computed, or nullptr if it hasn't been computed yet.
Definition at line 406 of file LiveIntervals.h.
Referenced by getLanesWithProperty(), getLiveRange(), llvm::LiveIntervals::HMEditor::getRegUnitLI(), and removePhysRegDefAt().
getCachedRegUnit() [2/2]
const LiveRange* llvm::LiveIntervals::getCachedRegUnit (unsigned Unit) const inline
Definition at line 410 of file LiveIntervals.h.
getInstructionFromIndex()
MachineInstr* llvm::LiveIntervals::getInstructionFromIndex (SlotIndex index) const inline
Returns the instruction associated with the given index.
Definition at line 231 of file LiveIntervals.h.
References llvm::SlotIndexes::getInstructionFromIndex().
Referenced by addKillFlags(), llvm::ScheduleDAGMILive::computeCyclicCriticalPath(), llvm::SplitEditor::enterIntvAfter(), llvm::SplitEditor::enterIntvBefore(), llvm::SIRegisterInfo::findReachingDef(), llvm::InsertPointAnalysis::getLastInsertPointIter(), getVRegDef(), isRematerializable(), llvm::SplitEditor::leaveIntvAfter(), llvm::SplitEditor::leaveIntvBefore(), llvm::printLivesAt(), llvm::SystemZRegisterInfo::shouldCoalesce(), and llvm::SplitAnalysis::shouldSplitSingleBlock().
getInstructionIndex()
SlotIndex llvm::LiveIntervals::getInstructionIndex (const MachineInstr & Instr) const inline
Returns the base index of the given instruction.
Definition at line 226 of file LiveIntervals.h.
References llvm::SlotIndexes::getInstructionIndex().
Referenced by addSegmentToEndOfBlock(), llvm::GCNDownwardRPTracker::advanceBeforeNext(), llvm::ScheduleDAGInstrs::buildSchedGraph(), llvm::RegPressureTracker::bumpDownwardPressure(), llvm::RegPressureTracker::bumpUpwardPressure(), llvm::LiveRangeEdit::canRematerializeAt(), llvm::ScheduleDAGMILive::computeCyclicCriticalPath(), llvm::RegisterOperands::detectDeadDefs(), dumpMachineInstrRangeWithSlotIndex(), findNextInsertLocation(), llvm::SIRegisterInfo::findReachingDef(), findUseBetween(), llvm::RegPressureTracker::getCurrSlot(), llvm::InsertPointAnalysis::getFirstInsertPoint(), llvm::getLiveRegsAfter(), llvm::getLiveRegsBefore(), getUsedRegMask(), getVRegDef(), handleMoveIntoNewBundle(), hasOneUse(), isDefBetween(), isPlainlyKilled(), llvm::GCNUpwardRPTracker::isValid(), moveAndTeeForMultiUse(), moveForSingleUse(), oneUseDominatesOtherUses(), llvm::RegPressureTracker::recede(), llvm::RegPressureTracker::recedeSkipDebugValues(), regJustKilledBefore(), rematerializeCheapDef(), replaceDominatedUses(), llvm::GCNScheduleDAGMILive::schedule(), llvm::ScheduleDAGMILive::scheduleMI(), llvm::GCNIterativeScheduler::scheduleRegion(), shrinkToUses(), and llvm::ScheduleDAGMILive::updatePressureDiffs().
getInterval() [1/2]
LiveInterval& llvm::LiveIntervals::getInterval (Register Reg) inline
Definition at line 114 of file LiveIntervals.h.
References createAndComputeVirtRegInterval(), hasInterval(), and Reg.
Referenced by addKillFlags(), llvm::GCNDownwardRPTracker::advanceBeforeNext(), llvm::RegAllocBase::allocatePhysRegs(), llvm::LiveRangeEdit::calculateRegClassAndHint(), llvm::VirtRegAuxInfo::calculateSpillWeightsAndHints(), llvm::ScheduleDAGMILive::computeCyclicCriticalPath(), llvm::LiveRangeEdit::createFrom(), llvm::SIRegisterInfo::findReachingDef(), llvm::SplitEditor::finish(), getInterval(), getLanesWithProperty(), llvm::getLiveLaneMask(), getLiveRange(), llvm::getLiveRegMap(), getVDefInterval(), getVRegDef(), handleMoveIntoNewBundle(), hasOneUse(), isDefBetween(), isLocalCopy(), llvm::SplitAnalysis::isOriginalEndpoint(), isPlainlyKilled(), isRematerializable(), moveAndTeeForMultiUse(), moveForSingleUse(), oneUseDominatesOtherUses(), print(), llvm::printLivesAt(), regJustKilledBefore(), rematerializeCheapDef(), replaceDominatedUses(), llvm::HexagonRegisterInfo::shouldCoalesce(), llvm::SystemZRegisterInfo::shouldCoalesce(), llvm::MachineBasicBlock::SplitCriticalEdge(), llvm::LiveIntervals::HMEditor::updateAllRanges(), and llvm::ScheduleDAGMILive::updatePressureDiffs().
getInterval() [2/2]
const LiveInterval& llvm::LiveIntervals::getInterval (Register Reg) const inline
Definition at line 121 of file LiveIntervals.h.
References getInterval(), and Reg.
getMBBEndIdx()
SlotIndex llvm::LiveIntervals::getMBBEndIdx (const MachineBasicBlock * mbb) const inline
Return the last index in the given basic block.
Definition at line 241 of file LiveIntervals.h.
References llvm::SlotIndexes::getMBBEndIdx().
Referenced by addSegmentToEndOfBlock(), llvm::ScheduleDAGMILive::computeCyclicCriticalPath(), llvm::RegPressureTracker::getCurrSlot(), llvm::InsertPointAnalysis::getLastInsertPointIter(), handleMove(), isLiveOutOfMBB(), llvm::ScheduleDAGMILive::updatePressureDiffs(), and llvm::SplitEditor::useIntv().
getMBBFromIndex()
MachineBasicBlock* llvm::LiveIntervals::getMBBFromIndex (SlotIndex index) const inline
Definition at line 255 of file LiveIntervals.h.
References llvm::SlotIndexes::getMBBFromIndex().
Referenced by llvm::SplitAnalysis::countLiveBlocks(), and hasPHIKill().
getMBBStartIdx()
SlotIndex llvm::LiveIntervals::getMBBStartIdx (const MachineBasicBlock * mbb) const inline
Return the first index in the given basic block.
Definition at line 236 of file LiveIntervals.h.
References llvm::SlotIndexes::getMBBStartIdx().
Referenced by llvm::InsertPointAnalysis::getFirstInsertPoint(), handleMove(), isLiveInToMBB(), llvm::MachineBasicBlock::SplitCriticalEdge(), and llvm::SplitEditor::useIntv().
getRegMaskBits()
ArrayRef<const uint32_t*> llvm::LiveIntervals::getRegMaskBits () const inline
Returns an array of register mask pointers corresponding to getRegMaskSlots().
Definition at line 362 of file LiveIntervals.h.
Referenced by checkRegMaskInterference(), and getRegMaskBitsInBlock().
getRegMaskBitsInBlock()
ArrayRef<const uint32_t*> llvm::LiveIntervals::getRegMaskBitsInBlock (unsigned MBBNum) const inline
Returns an array of mask pointers corresponding to getRegMaskSlotsInBlock(MBBNum).
Definition at line 366 of file LiveIntervals.h.
References getRegMaskBits(), and P.
Referenced by checkRegMaskInterference().
getRegMaskSlots()
ArrayRef<SlotIndex> llvm::LiveIntervals::getRegMaskSlots () const inline
Returns a sorted array of slot indices of all instructions with register mask operands.
Definition at line 351 of file LiveIntervals.h.
Referenced by checkRegMaskInterference(), and getRegMaskSlotsInBlock().
getRegMaskSlotsInBlock()
ArrayRef<SlotIndex> llvm::LiveIntervals::getRegMaskSlotsInBlock (unsigned MBBNum) const inline
Returns a sorted array of slot indices of all instructions with register mask operands in the basic block numbered MBBNum.
Definition at line 355 of file LiveIntervals.h.
References getRegMaskSlots(), and P.
Referenced by checkRegMaskInterference().
getRegUnit()
LiveRange& llvm::LiveIntervals::getRegUnit (unsigned Unit) inline
Return the live range for register unit Unit.
It will be computed if it doesn't exist.
Definition at line 393 of file LiveIntervals.h.
References llvm::UseSegmentSetForPhysRegs.
Referenced by addKillFlags(), llvm::LiveRegMatrix::checkRegUnitInterference(), llvm::SIRegisterInfo::findReachingDef(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::LiveIntervals::HMEditor::getRegUnitLI(), isDefBetween(), and runOnMachineFunction().
getSlotIndexes()
SlotIndexes* llvm::LiveIntervals::getSlotIndexes () const inline
Definition at line 211 of file LiveIntervals.h.
Referenced by llvm::LiveRegMatrix::checkRegUnitInterference(), constructMainRangeFromSubranges(), extendToIndices(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::getLiveRegMap(), llvm::LiveRangeEdit::rematerializeAt(), llvm::SplitEditor::reset(), and llvm::HexagonRegisterInfo::shouldCoalesce().
getSpillWeight() [1/2]
float LiveIntervals::getSpillWeight (bool isDef, bool isUse, const MachineBlockFrequencyInfo * MBFI, const MachineBasicBlock * MBB) static
Calculate the spill weight to assign to a single instruction.
Definition at line 878 of file LiveIntervals.cpp.
References llvm::MachineBlockFrequencyInfo::getBlockFreqRelativeToEntryBlock(), and MBB.
getSpillWeight() [2/2]
float LiveIntervals::getSpillWeight (bool isDef, bool isUse, const MachineBlockFrequencyInfo * MBFI, const MachineInstr & MI) static
Calculate the spill weight to assign to a single instruction.
Definition at line 872 of file LiveIntervals.cpp.
References MI.
Referenced by computeWeight().
getVNInfoAllocator()
VNInfo::Allocator& llvm::LiveIntervals::getVNInfoAllocator () inline
Definition at line 284 of file LiveIntervals.h.
Referenced by addSegmentToEndOfBlock(), constructMainRangeFromSubranges(), extendToIndices(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), and llvm::SplitEditor::reset().
handleMove()
void LiveIntervals::handleMove (MachineInstr & MI, bool UpdateFlags = false)
Call this method to notify LiveIntervals that instruction MI has been moved within a basic block.
This will update the live intervals for all operands of MI. Moves between basic blocks are not supported.
Parameters
UpdateFlags Update live intervals for nonallocatable physregs.
Definition at line 1488 of file LiveIntervals.cpp.
References assert(), llvm::SlotIndexes::getInstructionIndex(), getMBBEndIdx(), getMBBStartIdx(), llvm::SlotIndexes::insertMachineInstrInMaps(), MI, MRI, llvm::SlotIndexes::removeMachineInstrFromMaps(), TRI, and llvm::LiveIntervals::HMEditor::updateAllRanges().
Referenced by moveAndTeeForMultiUse(), moveForSingleUse(), llvm::ScheduleDAGMI::moveInstruction(), llvm::GCNScheduleDAGMILive::schedule(), and llvm::GCNIterativeScheduler::scheduleRegion().
handleMoveIntoNewBundle()
void LiveIntervals::handleMoveIntoNewBundle (MachineInstr & BundleStart, bool UpdateFlags = false)
Update intervals of operands of all instructions in the newly created bundle specified by BundleStart.
Parameters
UpdateFlags Update live intervals for nonallocatable physregs.
Assumes existing liveness is accurate.
Precondition
BundleStart should be the first instruction in the Bundle.
BundleStart should not have a have SlotIndex as one will be assigned.
Definition at line 1504 of file LiveIntervals.cpp.
References assert(), E, llvm::getBundleEnd(), getInstructionIndex(), llvm::SlotIndexes::getInstructionIndex(), getInterval(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::SlotIndexes::hasIndex(), hasInterval(), I, Index, llvm::SlotIndexes::insertMachineInstrInMaps(), llvm::LiveQueryResult::isDeadDef(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isUndef(), MRI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::LiveRange::Query(), Reg, llvm::SlotIndexes::removeMachineInstrFromMaps(), llvm::MachineOperand::setIsDead(), TRI, and llvm::LiveIntervals::HMEditor::updateAllRanges().
hasInterval()
bool llvm::LiveIntervals::hasInterval (Register Reg) const inline
Definition at line 125 of file LiveIntervals.h.
References llvm::IndexedMap< T, ToIndexT >::inBounds(), and Reg.
Referenced by llvm::RegAllocBase::allocatePhysRegs(), createEmptyInterval(), llvm::SIRegisterInfo::findReachingDef(), getInterval(), llvm::getLiveRegMap(), llvm::getLiveRegs(), handleMoveIntoNewBundle(), print(), llvm::printLivesAt(), replaceRegUsesAfterLoop(), and llvm::MachineBasicBlock::SplitCriticalEdge().
hasPHIKill()
bool LiveIntervals::hasPHIKill (const LiveInterval & LI, const VNInfo * VNI) const
Returns true if VNI is killed by any PHI-def values in LI.
This may conservatively return true to avoid expensive computations.
Definition at line 857 of file LiveIntervals.cpp.
References llvm::VNInfo::def, llvm::SlotIndexes::getMBBEndIdx(), getMBBFromIndex(), llvm::LiveRange::getVNInfoBefore(), llvm::VNInfo::isPHIDef(), llvm::VNInfo::isUnused(), llvm::MachineBasicBlock::pred_size(), llvm::MachineBasicBlock::predecessors(), and llvm::LiveRange::valnos.
InsertMachineInstrInMaps()
SlotIndex llvm::LiveIntervals::InsertMachineInstrInMaps (MachineInstr & MI) inline
Definition at line 266 of file LiveIntervals.h.
References llvm::SlotIndexes::insertMachineInstrInMaps(), and MI.
Referenced by convertImplicitDefToConstZero(), insertCSRRestores(), moveAndTeeForMultiUse(), and rematerializeCheapDef().
InsertMachineInstrRangeInMaps()
void llvm::LiveIntervals::InsertMachineInstrRangeInMaps (MachineBasicBlock::iterator B, MachineBasicBlock::iterator E) inline
Definition at line 270 of file LiveIntervals.h.
References B, E, I, and llvm::SlotIndexes::insertMachineInstrInMaps().
insertMBBInMaps()
void llvm::LiveIntervals::insertMBBInMaps (MachineBasicBlock * MBB) inline
Definition at line 259 of file LiveIntervals.h.
References assert(), llvm::SlotIndexes::insertMBBInMaps(), MBB, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::MachineBasicBlock::splitAt(), and llvm::MachineBasicBlock::SplitCriticalEdge().
intervalIsInOneMBB()
MachineBasicBlock * LiveIntervals::intervalIsInOneMBB (const LiveInterval & LI) const
If LI is confined to a single basic block, return a pointer to that block.
If LI is live in to or out of any block, return NULL.
Definition at line 833 of file LiveIntervals.cpp.
Referenced by checkRegMaskInterference(), and isLocalCopy().
isLiveInToMBB()
bool llvm::LiveIntervals::isLiveInToMBB (const LiveRange & LR, const MachineBasicBlock * mbb) const inline
Definition at line 245 of file LiveIntervals.h.
References getMBBStartIdx(), and llvm::LiveRange::liveAt().
isLiveOutOfMBB()
bool llvm::LiveIntervals::isLiveOutOfMBB (const LiveRange & LR, const MachineBasicBlock * mbb) const inline
Definition at line 250 of file LiveIntervals.h.
References getMBBEndIdx(), and llvm::LiveRange::liveAt().
isNotInMIMap()
bool llvm::LiveIntervals::isNotInMIMap (const MachineInstr & Instr) const inline
Returns true if the specified machine instr has been removed or was never entered in the map.
Definition at line 221 of file LiveIntervals.h.
References llvm::SlotIndexes::hasIndex().
Referenced by findNextInsertLocation(), and isPlainlyKilled().
print()
void LiveIntervals::print (raw_ostream & O, const Module * = nullptr) const override virtual
Implement the dump method.
Reimplemented from llvm::Pass.
Definition at line 153 of file LiveIntervals.cpp.
References llvm::numbers::e, getInterval(), llvm::MachineRegisterInfo::getNumVirtRegs(), hasInterval(), llvm::Register::index2VirtReg(), llvm::printRegUnit(), and Reg.
pruneValue() [1/2]
LLVM_ATTRIBUTE_UNUSED void llvm::LiveIntervals::pruneValue (LiveInterval & , SlotIndex , SmallVectorImpl< SlotIndex > *) inline
This function should not be used.
Its intent is to tell you that you are doing something wrong if you call pruneValue directly on a LiveInterval. Indeed, you are supposed to call pruneValue on the main LiveRange and all the LiveRanges of the subranges if any.
Definition at line 205 of file LiveIntervals.h.
References llvm_unreachable.
pruneValue() [2/2]
void LiveIntervals::pruneValue (LiveRange & LR, SlotIndex Kill, SmallVectorImpl< SlotIndex > * EndPoints)
If LR has a live value at Kill, prune its live range by removing any liveness reachable from Kill.
Add live range end points to EndPoints such that extendToIndices(LI, EndPoints) will reconstruct the value's live range.
Calling pruneValue() and extendToIndices() can be used to reconstruct SSA form after adding defs to a virtual register.
Definition at line 640 of file LiveIntervals.cpp.
References llvm::df_ext_begin(), llvm::df_ext_end(), E, llvm::LiveQueryResult::endPoint(), llvm::SlotIndexes::getMBBEndIdx(), llvm::SlotIndexes::getMBBFromIndex(), llvm::SlotIndexes::getMBBRange(), I, llvm::RegState::Kill, MBB, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::LiveRange::Query(), llvm::LiveRange::removeSegment(), llvm::MachineBasicBlock::successors(), llvm::LiveQueryResult::valueIn(), and llvm::LiveQueryResult::valueOutOrDead().
releaseMemory()
void LiveIntervals::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 107 of file LiveIntervals.cpp.
References llvm::SmallVectorImpl< T >::clear(), llvm::numbers::e, llvm::Register::index2VirtReg(), and llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Reset().
removeAllRegUnitsForPhysReg()
void llvm::LiveIntervals::removeAllRegUnitsForPhysReg (MCRegister Reg) inline
Remove associated live ranges for the register units associated with Reg.
Subsequent uses should rely on on-demand recomputation.
Note
This method can result in inconsistent liveness tracking if multiple phyical registers share a regunit, and should be used cautiously.
Definition at line 425 of file LiveIntervals.h.
References llvm::MCRegisterInfo::DiffListIterator::isValid(), Reg, removeRegUnit(), and TRI.
Referenced by insertCSRRestores().
removeInterval()
void llvm::LiveIntervals::removeInterval (Register Reg) inline
Interval removal.
Definition at line 145 of file LiveIntervals.h.
References Reg.
Referenced by llvm::RegAllocBase::allocatePhysRegs(), llvm::LiveRangeEdit::eraseVirtReg(), and rematerializeCheapDef().
RemoveMachineInstrFromMaps()
void llvm::LiveIntervals::RemoveMachineInstrFromMaps (MachineInstr & MI) inline
Definition at line 276 of file LiveIntervals.h.
References MI, and llvm::SlotIndexes::removeMachineInstrFromMaps().
Referenced by llvm::ModuloScheduleExpander::cleanup(), llvm::PeelingModuloScheduleExpander::filterInstructions(), llvm::PeelingModuloScheduleExpander::peelPrologAndEpilogs(), llvm::RegAllocBase::postOptimization(), rematerializeCheapDef(), and llvm::PeelingModuloScheduleExpander::rewriteUsesOf().
removePhysRegDefAt()
void LiveIntervals::removePhysRegDefAt (MCRegister Reg, SlotIndex Pos)
Remove value numbers and related live segments starting at position Pos that are part of any liverange of physical register Reg or one of its subregisters.
Definition at line 1688 of file LiveIntervals.cpp.
References getCachedRegUnit(), llvm::LiveRange::getVNInfoAt(), Reg, llvm::LiveRange::removeValNo(), and TRI.
Referenced by rematerializeCheapDef().
removeRegUnit()
void llvm::LiveIntervals::removeRegUnit (unsigned Unit) inline
Remove computed live range for register unit Unit.
Subsequent uses should rely on on-demand recomputation.
Definition at line 416 of file LiveIntervals.h.
Referenced by removeAllRegUnitsForPhysReg().
removeVRegDefAt()
void LiveIntervals::removeVRegDefAt (LiveInterval & LI, SlotIndex Pos)
Remove value number and related live segments of LI and its subranges that start at position Pos.
Definition at line 1696 of file LiveIntervals.cpp.
References assert(), llvm::VNInfo::def, llvm::SlotIndex::getBaseIndex(), llvm::LiveRange::getVNInfoAt(), llvm::LiveInterval::removeEmptySubRanges(), llvm::LiveRange::removeValNo(), and llvm::LiveInterval::subranges().
repairIntervalsInRange()
void LiveIntervals::repairIntervalsInRange (MachineBasicBlock * MBB, MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, ArrayRef< Register > OrigRegs)
Update live intervals for instructions in a range of iterators.
It is intended for use after target hooks that may insert or remove instructions, and is only efficient for a small number of instructions.
OrigRegs is a vector of registers that were originally used by the instructions in the range between the two iterators.
Currently, the only only changes that are supported are simple removal and addition of uses.
Definition at line 1638 of file LiveIntervals.cpp.
Referenced by llvm::MachineBasicBlock::SplitCriticalEdge().
ReplaceMachineInstrInMaps()
SlotIndex llvm::LiveIntervals::ReplaceMachineInstrInMaps (MachineInstr & MI, MachineInstr & NewMI) inline
Definition at line 280 of file LiveIntervals.h.
References MI, and llvm::SlotIndexes::replaceMachineInstrInMaps().
runOnMachineFunction()
bool LiveIntervals::runOnMachineFunction (MachineFunction & fn) override virtual
Pass entry point; Calculates LiveIntervals.
Implements llvm::MachineFunctionPass.
Definition at line 124 of file LiveIntervals.cpp.
References llvm::Pass::dump(), llvm::numbers::e, EnablePrecomputePhysRegs(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MCRegisterInfo::getNumRegUnits(), llvm::MachineRegisterInfo::getNumVirtRegs(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), getRegUnit(), llvm::MachineFunction::getSubtarget(), and LLVM_DEBUG.
shrinkToUses() [1/2]
bool LiveIntervals::shrinkToUses (LiveInterval * li, SmallVectorImpl< MachineInstr * > * dead = nullptr)
After removing some uses of a register, shrink its live range to just the remaining uses.
This method does not compute reaching defs for new uses, and it doesn't remove dead defs. Dead PHIDef values are marked as unused. New dead machine instructions are added to the dead vector. Returns true if the interval may have been separated into multiple connected components.
Definition at line 454 of file LiveIntervals.cpp.
References assert(), createSegmentsForValues(), llvm::dbgs(), getInstructionIndex(), llvm::LaneBitmask::getNone(), llvm::SlotIndex::getRegSlot(), llvm::Register::isVirtualRegister(), LLVM_DEBUG, llvm::make_range(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::LiveRange::Query(), llvm::LiveInterval::reg(), Reg, llvm::MachineRegisterInfo::reg_instructions(), llvm::LiveInterval::removeEmptySubRanges(), llvm::LiveRange::segments, llvm::LiveInterval::subranges(), llvm::SmallVectorImpl< T >::swap(), UseMI, llvm::LiveQueryResult::valueDefined(), llvm::LiveQueryResult::valueIn(), llvm::LiveRange::vni_begin(), and llvm::LiveRange::vni_end().
Referenced by llvm::LiveRangeEdit::eliminateDeadDefs(), replaceDominatedUses(), and shrinkToUses().
shrinkToUses() [2/2]
void LiveIntervals::shrinkToUses (LiveInterval::SubRange & SR, Register Reg)
Specialized version of shrinkToUses(LiveInterval li, SmallVectorImpl<MachineInstr> *dead) that works on a subregister live range and only looks at uses matching the lane mask of the subregister range.
This may leave the subrange empty which needs to be cleaned up with LiveInterval::removeEmptySubranges() afterwards.
Definition at line 561 of file LiveIntervals.cpp.
References assert(), createSegmentsForValues(), llvm::dbgs(), llvm::VNInfo::def, llvm::LiveRange::Segment::end, llvm::SlotIndex::getDeadSlot(), getInstructionIndex(), llvm::SlotIndex::getRegSlot(), llvm::LiveRange::getSegmentContaining(), llvm::TargetRegisterInfo::getSubRegIndexLaneMask(), llvm::VNInfo::isPHIDef(), llvm::VNInfo::isUnused(), llvm::Register::isVirtualRegister(), llvm::LiveInterval::SubRange::LaneMask, LLVM_DEBUG, llvm::make_range(), llvm::VNInfo::markUnused(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::LiveRange::Query(), Reg, llvm::LiveRange::removeSegment(), llvm::LiveRange::segments, SubReg, llvm::SmallVectorImpl< T >::swap(), llvm::MachineRegisterInfo::use_nodbg_operands(), UseMI, llvm::LiveRange::valnos, llvm::LiveQueryResult::valueDefined(), llvm::LiveQueryResult::valueIn(), llvm::LiveRange::vni_begin(), and llvm::LiveRange::vni_end().
splitSeparateComponents()
void LiveIntervals::splitSeparateComponents (LiveInterval & LI, SmallVectorImpl< LiveInterval * > & SplitLIs)
Split separate components in LiveInterval LI into separate intervals.
Definition at line 1714 of file LiveIntervals.cpp.
References llvm::ConnectedVNInfoEqClasses::Classify(), createEmptyInterval(), llvm::SmallVectorTemplateCommon< T, typename >::data(), llvm::dbgs(), llvm::ConnectedVNInfoEqClasses::Distribute(), I, LLVM_DEBUG, MRI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::LiveInterval::reg(), and Reg.
Referenced by llvm::LiveRangeEdit::eliminateDeadDefs(), llvm::SplitEditor::finish(), and shrinkToUses().
Member Data Documentation
ID
char LiveIntervals::ID = 0 static
Definition at line 99 of file LiveIntervals.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/LiveIntervals.h
lib/CodeGen/LiveIntervals.cpp