LLVM: llvm::SelectionDAG Class Reference
llvm::SelectionDAG Class Reference
This is used to represent a portion of an LLVM function in a low-level Data Dependence DAG representation suitable for instruction selection.
#include "llvm/CodeGen/SelectionDAG.h"
Classes
struct DAGNodeDeletedListener
struct DAGUpdateListener
Clients of various APIs that cause global effects on the DAG can optionally implement this interface.
class FlagInserter
Help to insert SDNodeFlags automatically in transforming.
Public Types
enum OverflowKind { OFK_Never , OFK_Sometime , OFK_Always }
Used to represent the possible overflow behavior of an operation.
using allnodes_const_iterator = ilist< SDNode >::const_iterator
using allnodes_iterator = ilist< SDNode >::iterator
Public Member Functions
SelectionDAG (const TargetMachine &TM, CodeGenOpt::Level)
SelectionDAG (const SelectionDAG &)=delete
SelectionDAG & operator= (const SelectionDAG &)=delete
~SelectionDAG ()
void init (MachineFunction &NewMF, OptimizationRemarkEmitter &NewORE, Pass *PassPtr, const TargetLibraryInfo *LibraryInfo, LegacyDivergenceAnalysis *Divergence, ProfileSummaryInfo *PSIin, BlockFrequencyInfo *BFIin)
Prepare this SelectionDAG to process code in the given MachineFunction.
void setFunctionLoweringInfo (FunctionLoweringInfo *FuncInfo)
void clear ()
Clear state and free memory necessary to make this SelectionDAG ready to process a new block.
MachineFunction & getMachineFunction () const
const Pass * getPass () const
const DataLayout & getDataLayout () const
const TargetMachine & getTarget () const
const TargetSubtargetInfo & getSubtarget () const
const TargetLowering & getTargetLoweringInfo () const
const TargetLibraryInfo & getLibInfo () const
const SelectionDAGTargetInfo & getSelectionDAGInfo () const
const LegacyDivergenceAnalysis * getDivergenceAnalysis () const
LLVMContext * getContext () const
OptimizationRemarkEmitter & getORE () const
ProfileSummaryInfo * getPSI () const
BlockFrequencyInfo * getBFI () const
FlagInserter * getFlagInserter ()
void setFlagInserter (FlagInserter *FI)
LLVM_DUMP_METHOD void dumpDotGraph (const Twine &FileName, const Twine &Title)
Just dump dot graph to a user-provided path and title.
void viewGraph (const std::string &Title)
Pop up a GraphViz/gv window with the DAG rendered using 'dot'.
void viewGraph ()
void clearGraphAttrs ()
Clear all previously defined node graph attributes.
void setGraphAttrs (const SDNode *N, const char *Attrs)
Set graph attributes for a node. (eg. "color=red".)
const std::string getGraphAttrs (const SDNode *N) const
Get graph attributes for a node.
void setGraphColor (const SDNode *N, const char *Color)
Convenience for setting node color attribute.
void setSubgraphColor (SDNode *N, const char *Color)
Convenience for setting subgraph color attribute.
allnodes_const_iterator allnodes_begin () const
allnodes_const_iterator allnodes_end () const
allnodes_iterator allnodes_begin ()
allnodes_iterator allnodes_end ()
ilist< SDNode >::size_type allnodes_size () const
iterator_range< allnodes_iterator > allnodes ()
iterator_range< allnodes_const_iterator > allnodes () const
const SDValue & getRoot () const
Return the root tag of the SelectionDAG.
SDValue getEntryNode () const
Return the token chain corresponding to the entry of the function.
const SDValue & setRoot (SDValue N)
Set the current root tag of the SelectionDAG.
void VerifyDAGDiverence ()
void Combine (CombineLevel Level, AAResults *AA, CodeGenOpt::Level OptLevel)
This iterates over the nodes in the SelectionDAG, folding certain types of nodes together, or eliminating superfluous nodes.
bool LegalizeTypes ()
This transforms the SelectionDAG into a SelectionDAG that only uses types natively supported by the target.
void Legalize ()
This transforms the SelectionDAG into a SelectionDAG that is compatible with the target instruction selector, as indicated by the TargetLowering object.
bool LegalizeOp (SDNode *N, SmallSetVector< SDNode *, 16 > &UpdatedNodes)
Transforms a SelectionDAG node and any operands to it into a node that is compatible with the target instruction selector, as indicated by the TargetLowering object.
bool LegalizeVectors ()
This transforms the SelectionDAG into a SelectionDAG that only uses vector math operations supported by the target.
void RemoveDeadNodes ()
This method deletes all unreachable nodes in the SelectionDAG.
void DeleteNode (SDNode *N)
Remove the specified node from the system.
SDVTList getVTList (EVT VT)
Return an SDVTList that represents the list of values specified.
SDVTList getVTList (EVT VT1, EVT VT2)
SDVTList getVTList (EVT VT1, EVT VT2, EVT VT3)
SDVTList getVTList (EVT VT1, EVT VT2, EVT VT3, EVT VT4)
SDVTList getVTList (ArrayRef< EVT > VTs)
SDValue getGlobalAddress (const GlobalValue *GV, const SDLoc &DL, EVT VT, int64_t offset=0, bool isTargetGA=false, unsigned TargetFlags=0)
SDValue getTargetGlobalAddress (const GlobalValue *GV, const SDLoc &DL, EVT VT, int64_t offset=0, unsigned TargetFlags=0)
SDValue getFrameIndex (int FI, EVT VT, bool isTarget=false)
SDValue getTargetFrameIndex (int FI, EVT VT)
SDValue getJumpTable (int JTI, EVT VT, bool isTarget=false, unsigned TargetFlags=0)
SDValue getTargetJumpTable (int JTI, EVT VT, unsigned TargetFlags=0)
SDValue getConstantPool (const Constant *C, EVT VT, MaybeAlign Align=None, int Offs=0, bool isT=false, unsigned TargetFlags=0)
SDValue getTargetConstantPool (const Constant *C, EVT VT, MaybeAlign Align=None, int Offset=0, unsigned TargetFlags=0)
SDValue getConstantPool (MachineConstantPoolValue *C, EVT VT, MaybeAlign Align=None, int Offs=0, bool isT=false, unsigned TargetFlags=0)
SDValue getTargetConstantPool (MachineConstantPoolValue *C, EVT VT, MaybeAlign Align=None, int Offset=0, unsigned TargetFlags=0)
SDValue getTargetIndex (int Index, EVT VT, int64_t Offset=0, unsigned TargetFlags=0)
SDValue getBasicBlock (MachineBasicBlock *MBB)
SDValue getExternalSymbol (const char *Sym, EVT VT)
SDValue getTargetExternalSymbol (const char *Sym, EVT VT, unsigned TargetFlags=0)
SDValue getMCSymbol (MCSymbol *Sym, EVT VT)
SDValue getValueType (EVT)
SDValue getRegister (unsigned Reg, EVT VT)
SDValue getRegisterMask (const uint32_t *RegMask)
SDValue getEHLabel (const SDLoc &dl, SDValue Root, MCSymbol *Label)
SDValue getLabelNode (unsigned Opcode, const SDLoc &dl, SDValue Root, MCSymbol *Label)
SDValue getBlockAddress (const BlockAddress *BA, EVT VT, int64_t Offset=0, bool isTarget=false, unsigned TargetFlags=0)
SDValue getTargetBlockAddress (const BlockAddress *BA, EVT VT, int64_t Offset=0, unsigned TargetFlags=0)
SDValue getCopyToReg (SDValue Chain, const SDLoc &dl, unsigned Reg, SDValue N)
SDValue getCopyToReg (SDValue Chain, const SDLoc &dl, unsigned Reg, SDValue N, SDValue Glue)
SDValue getCopyToReg (SDValue Chain, const SDLoc &dl, SDValue Reg, SDValue N, SDValue Glue)
SDValue getCopyFromReg (SDValue Chain, const SDLoc &dl, unsigned Reg, EVT VT)
SDValue getCopyFromReg (SDValue Chain, const SDLoc &dl, unsigned Reg, EVT VT, SDValue Glue)
SDValue getCondCode (ISD::CondCode Cond)
SDValue getVectorShuffle (EVT VT, const SDLoc &dl, SDValue N1, SDValue N2, ArrayRef< int > Mask)
Return an ISD::VECTOR_SHUFFLE node.
SDValue getBuildVector (EVT VT, const SDLoc &DL, ArrayRef< SDValue > Ops)
Return an ISD::BUILD_VECTOR node.
SDValue getBuildVector (EVT VT, const SDLoc &DL, ArrayRef< SDUse > Ops)
Return an ISD::BUILD_VECTOR node.
SDValue getSplatBuildVector (EVT VT, const SDLoc &DL, SDValue Op)
Return a splat ISD::BUILD_VECTOR node, consisting of Op splatted to all elements.
SDValue getSplatVector (EVT VT, const SDLoc &DL, SDValue Op)
SDValue getCommutedVectorShuffle (const ShuffleVectorSDNode &SV)
Returns an ISD::VECTOR_SHUFFLE node semantically equivalent to the shuffle node in input but with swapped operands.
SDValue getFPExtendOrRound (SDValue Op, const SDLoc &DL, EVT VT)
Convert Op, which must be of float type, to the float type VT, by either extending or rounding (by truncation).
std::pair< SDValue, SDValue > getStrictFPExtendOrRound (SDValue Op, SDValue Chain, const SDLoc &DL, EVT VT)
Convert Op, which must be a STRICT operation of float type, to the float type VT, by either extending or rounding (by truncation).
SDValue getAnyExtOrTrunc (SDValue Op, const SDLoc &DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either any-extending or truncating it.
SDValue getSExtOrTrunc (SDValue Op, const SDLoc &DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either sign-extending or truncating it.
SDValue getZExtOrTrunc (SDValue Op, const SDLoc &DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either zero-extending or truncating it.
SDValue getZeroExtendInReg (SDValue Op, const SDLoc &DL, EVT VT)
Return the expression required to zero extend the Op value assuming it was the smaller SrcTy value.
SDValue getPtrExtOrTrunc (SDValue Op, const SDLoc &DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either truncating it or performing either zero or sign extension as appropriate extension for the pointer's semantics.
SDValue getPtrExtendInReg (SDValue Op, const SDLoc &DL, EVT VT)
Return the expression required to extend the Op as a pointer value assuming it was the smaller SrcTy value.
SDValue getBoolExtOrTrunc (SDValue Op, const SDLoc &SL, EVT VT, EVT OpVT)
Convert Op, which must be of integer type, to the integer type VT, by using an extension appropriate for the target's BooleanContent for type OpVT or truncating it.
SDValue getNOT (const SDLoc &DL, SDValue Val, EVT VT)
Create a bitwise NOT operation as (XOR Val, -1).
SDValue getLogicalNOT (const SDLoc &DL, SDValue Val, EVT VT)
Create a logical NOT operation as (XOR Val, BooleanOne).
SDValue getMemBasePlusOffset (SDValue Base, TypeSize Offset, const SDLoc &DL, const SDNodeFlags Flags=SDNodeFlags())
Returns sum of the base pointer and offset.
SDValue getMemBasePlusOffset (SDValue Base, SDValue Offset, const SDLoc &DL, const SDNodeFlags Flags=SDNodeFlags())
SDValue getObjectPtrOffset (const SDLoc &SL, SDValue Ptr, TypeSize Offset)
Create an add instruction with appropriate flags when used for addressing some offset of an object.
SDValue getObjectPtrOffset (const SDLoc &SL, SDValue Ptr, SDValue Offset)
SDValue getCALLSEQ_START (SDValue Chain, uint64_t InSize, uint64_t OutSize, const SDLoc &DL)
Return a new CALLSEQ_START node, that starts new call frame, in which InSize bytes are set up inside CALLSEQ_START..CALLSEQ_END sequence and OutSize specifies part of the frame set up prior to the sequence.
SDValue getCALLSEQ_END (SDValue Chain, SDValue Op1, SDValue Op2, SDValue InGlue, const SDLoc &DL)
Return a new CALLSEQ_END node, which always must have a glue result (to ensure it's not CSE'd).
bool isUndef (unsigned Opcode, ArrayRef< SDValue > Ops)
Return true if the result of this operation is always undefined.
SDValue getUNDEF (EVT VT)
Return an UNDEF node. UNDEF does not have a useful SDLoc.
SDValue getVScale (const SDLoc &DL, EVT VT, APInt MulImm)
Return a node that represents the runtime scaling 'MulImm * RuntimeVL'.
SDValue getGLOBAL_OFFSET_TABLE (EVT VT)
Return a GLOBAL_OFFSET_TABLE node. This does not have a useful SDLoc.
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, ArrayRef< SDUse > Ops)
Gets or creates the specified node.
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, ArrayRef< SDValue > Ops, const SDNodeFlags Flags)
SDValue getNode (unsigned Opcode, const SDLoc &DL, ArrayRef< EVT > ResultTys, ArrayRef< SDValue > Ops)
SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, ArrayRef< SDValue > Ops, const SDNodeFlags Flags)
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, ArrayRef< SDValue > Ops)
SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, ArrayRef< SDValue > Ops)
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue Operand)
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2)
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2, SDValue N3)
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT)
Gets or creates the specified node.
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue Operand, const SDNodeFlags Flags)
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2, const SDNodeFlags Flags)
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, const SDNodeFlags Flags)
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, SDValue N4)
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, SDValue N4, SDValue N5)
SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList)
SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, SDValue N)
SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, SDValue N1, SDValue N2)
SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, SDValue N1, SDValue N2, SDValue N3)
SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, SDValue N1, SDValue N2, SDValue N3, SDValue N4)
SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, SDValue N1, SDValue N2, SDValue N3, SDValue N4, SDValue N5)
SDValue getStackArgumentTokenFactor (SDValue Chain)
Compute a TokenFactor to force all the incoming stack arguments to be loaded from the stack.
LLVM_ATTRIBUTE_DEPRECATED (SDValue getMemcpy(SDValue Chain, const SDLoc &dl, SDValue Dst, SDValue Src, SDValue Size, unsigned Align, bool isVol, bool AlwaysInline, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo), "Use the version that takes Align instead")
SDValue getMemcpy (SDValue Chain, const SDLoc &dl, SDValue Dst, SDValue Src, SDValue Size, Align Alignment, bool isVol, bool AlwaysInline, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo)
LLVM_ATTRIBUTE_DEPRECATED (SDValue getMemmove(SDValue Chain, const SDLoc &dl, SDValue Dst, SDValue Src, SDValue Size, unsigned Align, bool isVol, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo), "Use the version that takes Align instead")
SDValue getMemmove (SDValue Chain, const SDLoc &dl, SDValue Dst, SDValue Src, SDValue Size, Align Alignment, bool isVol, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo)
LLVM_ATTRIBUTE_DEPRECATED (SDValue getMemset(SDValue Chain, const SDLoc &dl, SDValue Dst, SDValue Src, SDValue Size, unsigned Align, bool isVol, bool isTailCall, MachinePointerInfo DstPtrInfo), "Use the version that takes Align instead")
SDValue getMemset (SDValue Chain, const SDLoc &dl, SDValue Dst, SDValue Src, SDValue Size, Align Alignment, bool isVol, bool isTailCall, MachinePointerInfo DstPtrInfo)
SDValue getAtomicMemcpy (SDValue Chain, const SDLoc &dl, SDValue Dst, unsigned DstAlign, SDValue Src, unsigned SrcAlign, SDValue Size, Type *SizeTy, unsigned ElemSz, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo)
SDValue getAtomicMemmove (SDValue Chain, const SDLoc &dl, SDValue Dst, unsigned DstAlign, SDValue Src, unsigned SrcAlign, SDValue Size, Type *SizeTy, unsigned ElemSz, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo)
SDValue getAtomicMemset (SDValue Chain, const SDLoc &dl, SDValue Dst, unsigned DstAlign, SDValue Value, SDValue Size, Type *SizeTy, unsigned ElemSz, bool isTailCall, MachinePointerInfo DstPtrInfo)
SDValue getSetCC (const SDLoc &DL, EVT VT, SDValue LHS, SDValue RHS, ISD::CondCode Cond, SDValue Chain=SDValue(), bool IsSignaling=false)
Helper function to make it easier to build SetCC's if you just have an ISD::CondCode instead of an SDValue.
SDValue getSelect (const SDLoc &DL, EVT VT, SDValue Cond, SDValue LHS, SDValue RHS)
Helper function to make it easier to build Select's if you just have operands and don't want to check for vector.
SDValue getSelectCC (const SDLoc &DL, SDValue LHS, SDValue RHS, SDValue True, SDValue False, ISD::CondCode Cond)
Helper function to make it easier to build SelectCC's if you just have an ISD::CondCode instead of an SDValue.
SDValue simplifySelect (SDValue Cond, SDValue TVal, SDValue FVal)
Try to simplify a select/vselect into 1 of its operands or a constant.
SDValue simplifyShift (SDValue X, SDValue Y)
Try to simplify a shift into 1 of its operands or a constant.
SDValue simplifyFPBinop (unsigned Opcode, SDValue X, SDValue Y, SDNodeFlags Flags)
Try to simplify a floating-point binary operation into 1 of its operands or a constant.
SDValue getVAArg (EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue SV, unsigned Align)
VAArg produces a result and token chain, and takes a pointer and a source value as input.
SDValue getAtomicCmpSwap (unsigned Opcode, const SDLoc &dl, EVT MemVT, SDVTList VTs, SDValue Chain, SDValue Ptr, SDValue Cmp, SDValue Swp, MachineMemOperand *MMO)
Gets a node for an atomic cmpxchg op.
SDValue getAtomic (unsigned Opcode, const SDLoc &dl, EVT MemVT, SDValue Chain, SDValue Ptr, SDValue Val, MachineMemOperand *MMO)
Gets a node for an atomic op, produces result (if relevant) and chain and takes 2 operands.
SDValue getAtomic (unsigned Opcode, const SDLoc &dl, EVT MemVT, EVT VT, SDValue Chain, SDValue Ptr, MachineMemOperand *MMO)
Gets a node for an atomic op, produces result and chain and takes 1 operand.
SDValue getAtomic (unsigned Opcode, const SDLoc &dl, EVT MemVT, SDVTList VTList, ArrayRef< SDValue > Ops, MachineMemOperand *MMO)
Gets a node for an atomic op, produces result and chain and takes N operands.
SDValue getMemIntrinsicNode (unsigned Opcode, const SDLoc &dl, SDVTList VTList, ArrayRef< SDValue > Ops, EVT MemVT, MachinePointerInfo PtrInfo, Align Alignment, MachineMemOperand::Flags Flags=MachineMemOperand::MOLoad|MachineMemOperand::MOStore, uint64_t Size=0, const AAMDNodes &AAInfo=AAMDNodes())
Creates a MemIntrinsicNode that may produce a result and takes a list of operands.
SDValue getMemIntrinsicNode (unsigned Opcode, const SDLoc &dl, SDVTList VTList, ArrayRef< SDValue > Ops, EVT MemVT, MachinePointerInfo PtrInfo, MaybeAlign Alignment=None, MachineMemOperand::Flags Flags=MachineMemOperand::MOLoad|MachineMemOperand::MOStore, uint64_t Size=0, const AAMDNodes &AAInfo=AAMDNodes())
LLVM_ATTRIBUTE_DEPRECATED (inline SDValue getMemIntrinsicNode(unsigned Opcode, const SDLoc &dl, SDVTList VTList, ArrayRef< SDValue > Ops, EVT MemVT, MachinePointerInfo PtrInfo, unsigned Alignment, MachineMemOperand::Flags Flags=MachineMemOperand::MOLoad|MachineMemOperand::MOStore, uint64_t Size=0, const AAMDNodes &AAInfo=AAMDNodes()), "")
SDValue getMemIntrinsicNode (unsigned Opcode, const SDLoc &dl, SDVTList VTList, ArrayRef< SDValue > Ops, EVT MemVT, MachineMemOperand *MMO)
SDValue getLifetimeNode (bool IsStart, const SDLoc &dl, SDValue Chain, int FrameIndex, int64_t Size, int64_t Offset=-1)
Creates a LifetimeSDNode that starts (IsStart==true) or ends (IsStart==false) the lifetime of the portion of FrameIndex between offsets Offset and Offset + Size.
SDValue getPseudoProbeNode (const SDLoc &Dl, SDValue Chain, uint64_t Guid, uint64_t Index, uint32_t Attr)
Creates a PseudoProbeSDNode with function GUID Guid and the index of the block Index it is probing, as well as the attributes attr of the probe.
SDValue getMergeValues (ArrayRef< SDValue > Ops, const SDLoc &dl)
Create a MERGE_VALUES node from the given operands.
SDValue getLoad (EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, MachinePointerInfo PtrInfo, MaybeAlign Alignment=MaybeAlign(), MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes(), const MDNode *Ranges=nullptr)
Loads are not normal binary operators: their result type is not determined by their operands, and they produce a value AND a token chain.
SDValue getLoad (EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, MachinePointerInfo PtrInfo, unsigned Alignment, MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes(), const MDNode *Ranges=nullptr)
FIXME: Remove once transition to Align is over.
SDValue getLoad (EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, MachineMemOperand *MMO)
SDValue getExtLoad (ISD::LoadExtType ExtType, const SDLoc &dl, EVT VT, SDValue Chain, SDValue Ptr, MachinePointerInfo PtrInfo, EVT MemVT, MaybeAlign Alignment=MaybeAlign(), MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes())
SDValue getExtLoad (ISD::LoadExtType ExtType, const SDLoc &dl, EVT VT, SDValue Chain, SDValue Ptr, MachinePointerInfo PtrInfo, EVT MemVT, unsigned Alignment, MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes())
FIXME: Remove once transition to Align is over.
SDValue getExtLoad (ISD::LoadExtType ExtType, const SDLoc &dl, EVT VT, SDValue Chain, SDValue Ptr, EVT MemVT, MachineMemOperand *MMO)
SDValue getIndexedLoad (SDValue OrigLoad, const SDLoc &dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
SDValue getLoad (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue Offset, MachinePointerInfo PtrInfo, EVT MemVT, Align Alignment, MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes(), const MDNode *Ranges=nullptr)
SDValue getLoad (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue Offset, MachinePointerInfo PtrInfo, EVT MemVT, MaybeAlign Alignment=MaybeAlign(), MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes(), const MDNode *Ranges=nullptr)
SDValue getLoad (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue Offset, MachinePointerInfo PtrInfo, EVT MemVT, unsigned Alignment, MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes(), const MDNode *Ranges=nullptr)
FIXME: Remove once transition to Align is over.
SDValue getLoad (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue Offset, EVT MemVT, MachineMemOperand *MMO)
SDValue getStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, Align Alignment, MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes())
Helper function to build ISD::STORE nodes.
SDValue getStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, MaybeAlign Alignment=MaybeAlign(), MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes())
SDValue getStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, unsigned Alignment, MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes())
FIXME: Remove once transition to Align is over.
SDValue getStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, MachineMemOperand *MMO)
SDValue getTruncStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, EVT SVT, Align Alignment, MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes())
SDValue getTruncStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, EVT SVT, MaybeAlign Alignment=MaybeAlign(), MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes())
SDValue getTruncStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, EVT SVT, unsigned Alignment, MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes())
FIXME: Remove once transition to Align is over.
SDValue getTruncStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, EVT SVT, MachineMemOperand *MMO)
SDValue getIndexedStore (SDValue OrigStore, const SDLoc &dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
SDValue getMaskedLoad (EVT VT, const SDLoc &dl, SDValue Chain, SDValue Base, SDValue Offset, SDValue Mask, SDValue Src0, EVT MemVT, MachineMemOperand *MMO, ISD::MemIndexedMode AM, ISD::LoadExtType, bool IsExpanding=false)
SDValue getIndexedMaskedLoad (SDValue OrigLoad, const SDLoc &dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
SDValue getMaskedStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Base, SDValue Offset, SDValue Mask, EVT MemVT, MachineMemOperand *MMO, ISD::MemIndexedMode AM, bool IsTruncating=false, bool IsCompressing=false)
SDValue getIndexedMaskedStore (SDValue OrigStore, const SDLoc &dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
SDValue getMaskedGather (SDVTList VTs, EVT VT, const SDLoc &dl, ArrayRef< SDValue > Ops, MachineMemOperand *MMO, ISD::MemIndexType IndexType, ISD::LoadExtType ExtTy)
SDValue getMaskedScatter (SDVTList VTs, EVT VT, const SDLoc &dl, ArrayRef< SDValue > Ops, MachineMemOperand *MMO, ISD::MemIndexType IndexType, bool IsTruncating=false)
SDValue getSrcValue (const Value *v)
Construct a node to track a Value* through the backend.
SDValue getMDNode (const MDNode *MD)
Return an MDNodeSDNode which holds an MDNode.
SDValue getBitcast (EVT VT, SDValue V)
Return a bitcast using the SDLoc of the value operand, and casting to the provided type.
SDValue getAddrSpaceCast (const SDLoc &dl, EVT VT, SDValue Ptr, unsigned SrcAS, unsigned DestAS)
Return an AddrSpaceCastSDNode.
SDValue getFreeze (SDValue V)
Return a freeze using the SDLoc of the value operand.
SDValue getAssertAlign (const SDLoc &DL, SDValue V, Align A)
Return an AssertAlignSDNode.
SDValue getShiftAmountOperand (EVT LHSTy, SDValue Op)
Return the specified value casted to the target's desired shift amount type.
SDValue expandVAArg (SDNode *Node)
Expand the specified ISD::VAARG node as the Legalize pass would.
SDValue expandVACopy (SDNode *Node)
Expand the specified ISD::VACOPY node as the Legalize pass would.
SDValue getSymbolFunctionGlobalAddress (SDValue Op, Function **TargetFunction=nullptr)
Returs an GlobalAddress of the function from the current module with name matching the given ExternalSymbol.
SDNode * UpdateNodeOperands (SDNode *N, SDValue Op)
Mutate the specified node in-place to have the specified operands.
SDNode * UpdateNodeOperands (SDNode *N, SDValue Op1, SDValue Op2)
SDNode * UpdateNodeOperands (SDNode *N, SDValue Op1, SDValue Op2, SDValue Op3)
SDNode * UpdateNodeOperands (SDNode *N, SDValue Op1, SDValue Op2, SDValue Op3, SDValue Op4)
SDNode * UpdateNodeOperands (SDNode *N, SDValue Op1, SDValue Op2, SDValue Op3, SDValue Op4, SDValue Op5)
SDNode * UpdateNodeOperands (SDNode *N, ArrayRef< SDValue > Ops)
SDValue getTokenFactor (const SDLoc &DL, SmallVectorImpl< SDValue > &Vals)
Creates a new TokenFactor containing Vals.
void setNodeMemRefs (MachineSDNode *N, ArrayRef< MachineMemOperand * > NewMemRefs)
Mutate the specified machine node's memory references to the provided list.
bool calculateDivergence (SDNode *N)
void updateDivergence (SDNode *N)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT)
These are used for target selectors to mutate the specified node to have the specified return type, Target opcode, and operands.
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT, SDValue Op1)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT, SDValue Op1, SDValue Op2)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT, SDValue Op1, SDValue Op2, SDValue Op3)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT, ArrayRef< SDValue > Ops)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT1, EVT VT2)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT1, EVT VT2, ArrayRef< SDValue > Ops)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT1, EVT VT2, EVT VT3, ArrayRef< SDValue > Ops)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT1, EVT VT2, SDValue Op1, SDValue Op2)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, SDVTList VTs, ArrayRef< SDValue > Ops)
SDNode * MorphNodeTo (SDNode *N, unsigned Opc, SDVTList VTs, ArrayRef< SDValue > Ops)
This mutates the specified node to have the specified return type, opcode, and operands.
SDNode * mutateStrictFPToFP (SDNode *Node)
Mutate the specified strict FP node to its non-strict equivalent, unlinking the node from its chain and dropping the metadata arguments.
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT)
These are used for target selectors to create a new node with specified return type(s), MachineInstr opcode, and operands.
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT, SDValue Op1)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT, SDValue Op1, SDValue Op2)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT, SDValue Op1, SDValue Op2, SDValue Op3)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT, ArrayRef< SDValue > Ops)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT1, EVT VT2, SDValue Op1, SDValue Op2)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT1, EVT VT2, SDValue Op1, SDValue Op2, SDValue Op3)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT1, EVT VT2, ArrayRef< SDValue > Ops)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT1, EVT VT2, EVT VT3, SDValue Op1, SDValue Op2)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT1, EVT VT2, EVT VT3, SDValue Op1, SDValue Op2, SDValue Op3)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT1, EVT VT2, EVT VT3, ArrayRef< SDValue > Ops)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, ArrayRef< EVT > ResultTys, ArrayRef< SDValue > Ops)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, SDVTList VTs, ArrayRef< SDValue > Ops)
SDValue getTargetExtractSubreg (int SRIdx, const SDLoc &DL, EVT VT, SDValue Operand)
A convenience function for creating TargetInstrInfo::EXTRACT_SUBREG nodes.
SDValue getTargetInsertSubreg (int SRIdx, const SDLoc &DL, EVT VT, SDValue Operand, SDValue Subreg)
A convenience function for creating TargetInstrInfo::INSERT_SUBREG nodes.
SDNode * getNodeIfExists (unsigned Opcode, SDVTList VTList, ArrayRef< SDValue > Ops, const SDNodeFlags Flags)
Get the specified node if it's already available, or else return NULL.
SDNode * getNodeIfExists (unsigned Opcode, SDVTList VTList, ArrayRef< SDValue > Ops)
getNodeIfExists - Get the specified node if it's already available, or else return NULL.
bool doesNodeExist (unsigned Opcode, SDVTList VTList, ArrayRef< SDValue > Ops)
Check if a node exists without modifying its flags.
SDDbgValue * getDbgValue (DIVariable *Var, DIExpression *Expr, SDNode *N, unsigned R, bool IsIndirect, const DebugLoc &DL, unsigned O)
Creates a SDDbgValue node.
SDDbgValue * getConstantDbgValue (DIVariable *Var, DIExpression *Expr, const Value *C, const DebugLoc &DL, unsigned O)
Creates a constant SDDbgValue node.
SDDbgValue * getFrameIndexDbgValue (DIVariable *Var, DIExpression *Expr, unsigned FI, bool IsIndirect, const DebugLoc &DL, unsigned O)
Creates a FrameIndex SDDbgValue node.
SDDbgValue * getVRegDbgValue (DIVariable *Var, DIExpression *Expr, unsigned VReg, bool IsIndirect, const DebugLoc &DL, unsigned O)
Creates a VReg SDDbgValue node.
SDDbgLabel * getDbgLabel (DILabel *Label, const DebugLoc &DL, unsigned O)
Creates a SDDbgLabel node.
void transferDbgValues (SDValue From, SDValue To, unsigned OffsetInBits=0, unsigned SizeInBits=0, bool InvalidateDbg=true)
Transfer debug values from one node to another, while optionally generating fragment expressions for split-up values.
void RemoveDeadNode (SDNode *N)
Remove the specified node from the system.
void RemoveDeadNodes (SmallVectorImpl< SDNode * > &DeadNodes)
This method deletes the unreachable nodes in the given list, and any nodes that become unreachable as a result.
void ReplaceAllUsesWith (SDValue From, SDValue To)
Modify anything using 'From' to use 'To' instead.
void ReplaceAllUsesWith (SDNode *From, SDNode *To)
ReplaceAllUsesWith - Modify anything using 'From' to use 'To' instead.
void ReplaceAllUsesWith (SDNode *From, const SDValue *To)
ReplaceAllUsesWith - Modify anything using 'From' to use 'To' instead.
void ReplaceAllUsesOfValueWith (SDValue From, SDValue To)
Replace any uses of From with To, leaving uses of other values produced by From.getNode() alone.
void ReplaceAllUsesOfValuesWith (const SDValue *From, const SDValue *To, unsigned Num)
Like ReplaceAllUsesOfValueWith, but for multiple values at once.
SDValue makeEquivalentMemoryOrdering (SDValue OldChain, SDValue NewMemOpChain)
If an existing load has uses of its chain, create a token factor node with that chain and the new memory node's chain and update users of the old chain to the token factor.
SDValue makeEquivalentMemoryOrdering (LoadSDNode *OldLoad, SDValue NewMemOp)
If an existing load has uses of its chain, create a token factor node with that chain and the new memory node's chain and update users of the old chain to the token factor.
unsigned AssignTopologicalOrder ()
Topological-sort the AllNodes list and a assign a unique node id for each node in the DAG based on their topological order.
void RepositionNode (allnodes_iterator Position, SDNode *N)
Move node N in the AllNodes list to be immediately before the given iterator Position.
void AddDbgValue (SDDbgValue *DB, SDNode *SD, bool isParameter)
Add a dbg_value SDNode.
void AddDbgLabel (SDDbgLabel *DB)
Add a dbg_label SDNode.
ArrayRef< SDDbgValue * > GetDbgValues (const SDNode *SD) const
Get the debug values which reference the given SDNode.
bool hasDebugValues () const
Return true if there are any SDDbgValue nodes associated with this SelectionDAG.
SDDbgInfo::DbgIterator DbgBegin () const
SDDbgInfo::DbgIterator DbgEnd () const
SDDbgInfo::DbgIterator ByvalParmDbgBegin () const
SDDbgInfo::DbgIterator ByvalParmDbgEnd () const
SDDbgInfo::DbgLabelIterator DbgLabelBegin () const
SDDbgInfo::DbgLabelIterator DbgLabelEnd () const
void salvageDebugInfo (SDNode &N)
To be invoked on an SDNode that is slated to be erased.
void dump () const
Align getReducedAlign (EVT VT, bool UseABI)
In most cases this function returns the ABI alignment for a given type, except for illegal vector types where the alignment exceeds that of the stack.
SDValue CreateStackTemporary (TypeSize Bytes, Align Alignment)
Create a stack temporary based on the size in bytes and the alignment.
SDValue CreateStackTemporary (EVT VT, unsigned minAlign=1)
Create a stack temporary, suitable for holding the specified value type.
SDValue CreateStackTemporary (EVT VT1, EVT VT2)
Create a stack temporary suitable for holding either of the specified value types.
SDValue FoldSymbolOffset (unsigned Opcode, EVT VT, const GlobalAddressSDNode *GA, const SDNode *N2)
SDValue FoldConstantArithmetic (unsigned Opcode, const SDLoc &DL, EVT VT, ArrayRef< SDValue > Ops)
SDValue FoldConstantVectorArithmetic (unsigned Opcode, const SDLoc &DL, EVT VT, ArrayRef< SDValue > Ops, const SDNodeFlags Flags=SDNodeFlags())
SDValue foldConstantFPMath (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2)
Fold floating-point operations with 2 operands when both operands are constants and/or undefined.
SDValue FoldSetCC (EVT VT, SDValue N1, SDValue N2, ISD::CondCode Cond, const SDLoc &dl)
Constant fold a setcc to true or false.
SDValue GetDemandedBits (SDValue V, const APInt &DemandedBits)
See if the specified operand can be simplified with the knowledge that only the bits specified by DemandedBits are used.
SDValue GetDemandedBits (SDValue V, const APInt &DemandedBits, const APInt &DemandedElts)
See if the specified operand can be simplified with the knowledge that only the bits specified by DemandedBits are used in the elements specified by DemandedElts.
bool SignBitIsZero (SDValue Op, unsigned Depth=0) const
Return true if the sign bit of Op is known to be zero.
bool MaskedValueIsZero (SDValue Op, const APInt &Mask, unsigned Depth=0) const
Return true if 'Op & Mask' is known to be zero.
bool MaskedValueIsZero (SDValue Op, const APInt &Mask, const APInt &DemandedElts, unsigned Depth=0) const
Return true if 'Op & Mask' is known to be zero in DemandedElts.
bool MaskedValueIsAllOnes (SDValue Op, const APInt &Mask, unsigned Depth=0) const
Return true if '(Op & Mask) == Mask'.
KnownBits computeKnownBits (SDValue Op, unsigned Depth=0) const
Determine which bits of Op are known to be either zero or one and return them in Known.
KnownBits computeKnownBits (SDValue Op, const APInt &DemandedElts, unsigned Depth=0) const
Determine which bits of Op are known to be either zero or one and return them in Known.
OverflowKind computeOverflowKind (SDValue N0, SDValue N1) const
Determine if the result of the addition of 2 node can overflow.
bool isKnownToBeAPowerOfTwo (SDValue Val) const
Test if the given value is known to have exactly one bit set.
unsigned ComputeNumSignBits (SDValue Op, unsigned Depth=0) const
Return the number of times the sign bit of the register is replicated into the other bits.
unsigned ComputeNumSignBits (SDValue Op, const APInt &DemandedElts, unsigned Depth=0) const
Return the number of times the sign bit of the register is replicated into the other bits.
bool isBaseWithConstantOffset (SDValue Op) const
Return true if the specified operand is an ISD::ADD with a ConstantSDNode on the right-hand side, or if it is an ISD::OR with a ConstantSDNode that is guaranteed to have the same semantics as an ADD.
bool isKnownNeverNaN (SDValue Op, bool SNaN=false, unsigned Depth=0) const
Test whether the given SDValue is known to never be NaN.
bool isKnownNeverSNaN (SDValue Op, unsigned Depth=0) const
bool isKnownNeverZeroFloat (SDValue Op) const
Test whether the given floating point SDValue is known to never be positive or negative zero.
bool isKnownNeverZero (SDValue Op) const
Test whether the given SDValue is known to contain non-zero value(s).
bool isEqualTo (SDValue A, SDValue B) const
Test whether two SDValues are known to compare equal.
bool haveNoCommonBitsSet (SDValue A, SDValue B) const
Return true if A and B have no common bits set.
bool isSplatValue (SDValue V, const APInt &DemandedElts, APInt &UndefElts, unsigned Depth=0)
Test whether V has a splatted value for all the demanded elements.
bool isSplatValue (SDValue V, bool AllowUndefs=false)
Test whether V has a splatted value.
SDValue getSplatSourceVector (SDValue V, int &SplatIndex)
If V is a splatted value, return the source vector and its splat index.
SDValue getSplatValue (SDValue V)
If V is a splat vector, return its scalar source operand by extracting that element from the source vector.
const APInt * getValidShiftAmountConstant (SDValue V, const APInt &DemandedElts) const
If a SHL/SRA/SRL node V has a constant or splat constant shift amount that is less than the element bit-width of the shift node, return it.
const APInt * getValidMinimumShiftAmountConstant (SDValue V, const APInt &DemandedElts) const
If a SHL/SRA/SRL node V has constant shift amounts that are all less than the element bit-width of the shift node, return the minimum value.
const APInt * getValidMaximumShiftAmountConstant (SDValue V, const APInt &DemandedElts) const
If a SHL/SRA/SRL node V has constant shift amounts that are all less than the element bit-width of the shift node, return the maximum value.
SDValue matchBinOpReduction (SDNode *Extract, ISD::NodeType &BinOp, ArrayRef< ISD::NodeType > CandidateBinOps, bool AllowPartials=false)
Match a binop + shuffle pyramid that represents a horizontal reduction over the elements of a vector starting from the EXTRACT_VECTOR_ELT node /p Extract.
SDValue UnrollVectorOp (SDNode *N, unsigned ResNE=0)
Utility function used by legalize and lowering to "unroll" a vector operation by splitting out the scalars and operating on each element individually.
std::pair< SDValue, SDValue > UnrollVectorOverflowOp (SDNode *N, unsigned ResNE=0)
Like UnrollVectorOp(), but for the [US](ADD|SUB|MUL)O family of opcodes.
bool areNonVolatileConsecutiveLoads (LoadSDNode *LD, LoadSDNode *Base, unsigned Bytes, int Dist) const
Return true if loads are next to each other and can be merged.
MaybeAlign InferPtrAlign (SDValue Ptr) const
Infer alignment of a load / store address.
std::pair< EVT, EVT > GetSplitDestVTs (const EVT &VT) const
Compute the VTs needed for the low/hi parts of a type which is split (or expanded) into two not necessarily identical pieces.
std::pair< EVT, EVT > GetDependentSplitDestVTs (const EVT &VT, const EVT &EnvVT, bool *HiIsEmpty) const
Compute the VTs needed for the low/hi parts of a type, dependent on an enveloping VT that has been split into two identical pieces.
std::pair< SDValue, SDValue > SplitVector (const SDValue &N, const SDLoc &DL, const EVT &LoVT, const EVT &HiVT)
Split the vector with EXTRACT_SUBVECTOR using the provides VTs and return the low/high part.
std::pair< SDValue, SDValue > SplitVector (const SDValue &N, const SDLoc &DL)
Split the vector with EXTRACT_SUBVECTOR and return the low/high part.
std::pair< SDValue, SDValue > SplitVectorOperand (const SDNode *N, unsigned OpNo)
Split the node's operand with EXTRACT_SUBVECTOR and return the low/high part.
SDValue WidenVector (const SDValue &N, const SDLoc &DL)
Widen the vector up to the next power of two using INSERT_SUBVECTOR.
void ExtractVectorElements (SDValue Op, SmallVectorImpl< SDValue > &Args, unsigned Start=0, unsigned Count=0, EVT EltVT=EVT())
Append the extracted elements from Start to Count out of the vector Op in Args.
Align getEVTAlign (EVT MemoryVT) const
Compute the default alignment value for the given type.
unsigned getEVTAlignment (EVT MemoryVT) const
Compute the default alignment value for the given type.
SDNode * isConstantIntBuildVectorOrConstantInt (SDValue N) const
Test whether the given value is a constant int or similar node.
SDNode * isConstantFPBuildVectorOrConstantFP (SDValue N) const
Test whether the given value is a constant FP or similar node.
bool isConstantValueOfAnyType (SDValue N) const
void addCallSiteInfo (const SDNode *CallNode, CallSiteInfoImpl &&CallInfo)
CallSiteInfo getSDCallSiteInfo (const SDNode *CallNode)
void addHeapAllocSite (const SDNode *Node, MDNode *MD)
MDNode * getHeapAllocSite (const SDNode *Node)
Return the HeapAllocSite type associated with the SDNode, if it exists.
void addNoMergeSiteInfo (const SDNode *Node, bool NoMerge)
bool getNoMergeSiteInfo (const SDNode *Node)
DenormalMode getDenormalMode (EVT VT) const
Return the current function's default denormal handling kind for the given floating point type.
bool shouldOptForSize () const
SDValue getNeutralElement (unsigned Opcode, const SDLoc &DL, EVT VT, SDNodeFlags Flags)
Get the (commutative) neutral element for the given opcode, if it exists.
SDValue getConstant (uint64_t Val, const SDLoc &DL, EVT VT, bool isTarget=false, bool isOpaque=false)
Create a ConstantSDNode wrapping a constant value.
SDValue getConstant (const APInt &Val, const SDLoc &DL, EVT VT, bool isTarget=false, bool isOpaque=false)
SDValue getAllOnesConstant (const SDLoc &DL, EVT VT, bool IsTarget=false, bool IsOpaque=false)
SDValue getConstant (const ConstantInt &Val, const SDLoc &DL, EVT VT, bool isTarget=false, bool isOpaque=false)
SDValue getIntPtrConstant (uint64_t Val, const SDLoc &DL, bool isTarget=false)
SDValue getShiftAmountConstant (uint64_t Val, EVT VT, const SDLoc &DL, bool LegalTypes=true)
SDValue getVectorIdxConstant (uint64_t Val, const SDLoc &DL, bool isTarget=false)
SDValue getTargetConstant (uint64_t Val, const SDLoc &DL, EVT VT, bool isOpaque=false)
SDValue getTargetConstant (const APInt &Val, const SDLoc &DL, EVT VT, bool isOpaque=false)
SDValue getTargetConstant (const ConstantInt &Val, const SDLoc &DL, EVT VT, bool isOpaque=false)
SDValue getBoolConstant (bool V, const SDLoc &DL, EVT VT, EVT OpVT)
Create a true or false constant of type VT using the target's BooleanContent for type OpVT.
SDValue getConstantFP (double Val, const SDLoc &DL, EVT VT, bool isTarget=false)
Create a ConstantFPSDNode wrapping a constant value.
SDValue getConstantFP (const APFloat &Val, const SDLoc &DL, EVT VT, bool isTarget=false)
SDValue getConstantFP (const ConstantFP &V, const SDLoc &DL, EVT VT, bool isTarget=false)
SDValue getTargetConstantFP (double Val, const SDLoc &DL, EVT VT)
SDValue getTargetConstantFP (const APFloat &Val, const SDLoc &DL, EVT VT)
SDValue getTargetConstantFP (const ConstantFP &Val, const SDLoc &DL, EVT VT)
Static Public Member Functions
static const fltSemantics & EVTToAPFloatSemantics (EVT VT)
Returns an APFloat semantics tag appropriate for the given type.
Public Attributes
bool NewNodesMustHaveLegalTypes = false
When true, additional steps are taken to ensure that getConstant() and similar functions return DAG nodes that have legal types.
std::map< const SDNode *, std::string > NodeGraphAttrs
const
Use InferPtrAlign instead
return
Static Public Attributes
static constexpr unsigned MaxRecursionDepth = 6
Friends
struct DAGUpdateListener
DAGUpdateListener is a friend so it can manipulate the listener stack.
Detailed Description
This is used to represent a portion of an LLVM function in a low-level Data Dependence DAG representation suitable for instruction selection.
This DAG is constructed as the first step of instruction selection in order to allow implementation of machine specific optimizations and code simplifications.
The representation used by the SelectionDAG is a target-independent representation, which has some similarities to the GCC RTL representation, but is significantly more simple, powerful, and is a graph form instead of a linear form.
Definition at line 223 of file SelectionDAG.h.
Member Typedef Documentation
allnodes_const_iterator
using llvm::SelectionDAG::allnodes_const_iterator = ilist<SDNode>::const_iterator
Definition at line 498 of file SelectionDAG.h.
allnodes_iterator
using llvm::SelectionDAG::allnodes_iterator = ilist<SDNode>::iterator
Definition at line 503 of file SelectionDAG.h.
Member Enumeration Documentation
OverflowKind
enum llvm::SelectionDAG::OverflowKind
Used to represent the possible overflow behavior of an operation.
Never: the operation cannot overflow. Always: the operation will always overflow. Sometime: the operation may or may not overflow.
Enumerator
OFK_Never
OFK_Sometime
OFK_Always
Definition at line 1765 of file SelectionDAG.h.
Constructor & Destructor Documentation
SelectionDAG() [1/2]
SelectionDAG::SelectionDAG (const TargetMachine & TM, CodeGenOpt::Level OL) explicit
Definition at line 1117 of file SelectionDAG.cpp.
References Other.
SelectionDAG() [2/2]
llvm::SelectionDAG::SelectionDAG (const SelectionDAG &) delete
~SelectionDAG()
SelectionDAG::~SelectionDAG ()
Definition at line 1143 of file SelectionDAG.cpp.
References assert().
Member Function Documentation
addCallSiteInfo()
void llvm::SelectionDAG::addCallSiteInfo (const SDNode * CallNode, CallSiteInfoImpl && CallInfo) inline
Definition at line 1974 of file SelectionDAG.h.
References llvm::move().
AddDbgLabel()
void SelectionDAG::AddDbgLabel (SDDbgLabel * DB)
Add a dbg_label SDNode.
Definition at line 9025 of file SelectionDAG.cpp.
References llvm::SDDbgInfo::add().
AddDbgValue()
void SelectionDAG::AddDbgValue (SDDbgValue * DB, SDNode * SD, bool isParameter)
Add a dbg_value SDNode.
AddDbgValue - Add a dbg_value SDNode.
If SD is non-null that means the value is produced by SD.
Definition at line 9017 of file SelectionDAG.cpp.
References llvm::SDDbgInfo::add(), assert(), llvm::SDNode::getHasDebugValue(), llvm::SDDbgInfo::getSDDbgValues(), and llvm::SDNode::setHasDebugValue().
Referenced by llvm::SelectionDAGBuilder::handleDebugValue(), llvm::SelectionDAGBuilder::resolveDanglingDebugInfo(), salvageDebugInfo(), llvm::SelectionDAGBuilder::salvageUnresolvedDbgValue(), and transferDbgValues().
addHeapAllocSite()
void llvm::SelectionDAG::addHeapAllocSite (const SDNode * Node, MDNode * MD) inline
Definition at line 1985 of file SelectionDAG.h.
addNoMergeSiteInfo()
void llvm::SelectionDAG::addNoMergeSiteInfo (const SDNode * Node, bool NoMerge) inline
Definition at line 1997 of file SelectionDAG.h.
Referenced by llvm::SystemZTargetLowering::LowerCall(), and llvm::RISCVTargetLowering::LowerCall().
allnodes() [1/2]
iterator_range<allnodes_iterator> llvm::SelectionDAG::allnodes () inline
Definition at line 512 of file SelectionDAG.h.
References allnodes_begin(), allnodes_end(), and llvm::make_range().
Referenced by llvm::HexagonDAGToDAGISel::PreprocessISelDAG().
allnodes() [2/2]
iterator_range<allnodes_const_iterator> llvm::SelectionDAG::allnodes () const inline
Definition at line 515 of file SelectionDAG.h.
References allnodes_begin(), allnodes_end(), and llvm::make_range().
allnodes_begin() [1/2]
allnodes_iterator llvm::SelectionDAG::allnodes_begin () inline
Definition at line 505 of file SelectionDAG.h.
allnodes_begin() [2/2]
allnodes_const_iterator llvm::SelectionDAG::allnodes_begin () const inline
Definition at line 500 of file SelectionDAG.h.
Referenced by allnodes(), AssignTopologicalOrder(), and Legalize().
allnodes_end() [1/2]
allnodes_iterator llvm::SelectionDAG::allnodes_end () inline
Definition at line 506 of file SelectionDAG.h.
allnodes_end() [2/2]
allnodes_const_iterator llvm::SelectionDAG::allnodes_end () const inline
Definition at line 501 of file SelectionDAG.h.
Referenced by allnodes(), AssignTopologicalOrder(), and Legalize().
allnodes_size()
ilist<SDNode>::size_type llvm::SelectionDAG::allnodes_size () const inline
Definition at line 508 of file SelectionDAG.h.
Referenced by llvm::HexagonDAGToDAGISel::PreprocessISelDAG().
areNonVolatileConsecutiveLoads()
bool SelectionDAG::areNonVolatileConsecutiveLoads (LoadSDNode * LD, LoadSDNode * Base, unsigned Bytes, int Dist) const
Return true if loads are next to each other and can be merged.
Check that both are nonvolatile and if LD is loading 'Bytes' bytes from a location that is 'Dist' units away from the location that the 'Base' load is loading from.
Definition at line 9681 of file SelectionDAG.cpp.
References llvm::MemSDNode::getChain(), llvm::EVT::getSizeInBits(), llvm::LSBaseSDNode::isIndexed(), llvm::MemSDNode::isVolatile(), llvm::ARM_MB::LD, llvm::BaseIndexOffset::match(), and Offset.
Referenced by EltsFromConsecutiveLoads().
AssignTopologicalOrder()
unsigned SelectionDAG::AssignTopologicalOrder ()
Topological-sort the AllNodes list and a assign a unique node id for each node in the DAG based on their topological order.
AssignTopologicalOrder - Assign a unique node id for each node in the DAG based on their topological order.
Returns the number of nodes.
It returns the maximum id and a vector of the SDNodes* in assigned order by reference.
Definition at line 8928 of file SelectionDAG.cpp.
References allnodes_begin(), allnodes_end(), assert(), llvm::checkForCycles(), E, I, and N.
Referenced by Legalize().
ByvalParmDbgBegin()
SDDbgInfo::DbgIterator llvm::SelectionDAG::ByvalParmDbgBegin () const inline
Definition at line 1650 of file SelectionDAG.h.
References llvm::SDDbgInfo::ByvalParmDbgBegin().
ByvalParmDbgEnd()
SDDbgInfo::DbgIterator llvm::SelectionDAG::ByvalParmDbgEnd () const inline
Definition at line 1653 of file SelectionDAG.h.
References llvm::SDDbgInfo::ByvalParmDbgEnd().
calculateDivergence()
bool SelectionDAG::calculateDivergence (SDNode * N)
Definition at line 8808 of file SelectionDAG.cpp.
References assert(), llvm::TargetLowering::isSDNodeAlwaysUniform(), llvm::TargetLowering::isSDNodeSourceOfDivergence(), N, and llvm::MVT::Other.
Referenced by updateDivergence(), and VerifyDAGDiverence().
clear()
void SelectionDAG::clear ()
Clear state and free memory necessary to make this SelectionDAG ready to process a new block.
Definition at line 1205 of file SelectionDAG.cpp.
References llvm::SDDbgInfo::clear(), getEntryNode(), and llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Reset().
clearGraphAttrs()
void SelectionDAG::clearGraphAttrs ()
Clear all previously defined node graph attributes.
clearGraphAttrs - Clear all previously defined node graph attributes.
Intended to be used from a debugging tool (eg. gdb).
Definition at line 183 of file SelectionDAGPrinter.cpp.
References llvm::errs(), and NodeGraphAttrs.
Combine()
void SelectionDAG::Combine (CombineLevel Level, AAResults * AA, CodeGenOpt::Level OptLevel)
This iterates over the nodes in the SelectionDAG, folding certain types of nodes together, or eliminating superfluous nodes.
This is the entry point for the file.
The Level argument controls whether Combine is allowed to produce nodes and types that are illegal on the target.
This is the main entry point to this class.
Definition at line 22750 of file DAGCombiner.cpp.
computeKnownBits() [1/2]
KnownBits SelectionDAG::computeKnownBits (SDValue Op, const APInt & DemandedElts, unsigned Depth = 0) const
Determine which bits of Op are known to be either zero or one and return them in Known.
The DemandedElts argument allows us to only collect the known bits that are shared by the requested vector elements. Targets can implement the computeKnownBitsForTargetNode method in the TargetLowering class to allow target nodes to be understood.
The DemandedElts argument allows us to only collect the known bits that are shared by the requested vector elements.
Definition at line 2686 of file SelectionDAG.cpp.
References llvm::ISD::ABS, llvm::KnownBits::abs(), llvm::ISD::ADD, llvm::ISD::ADDC, llvm::ISD::ADDCARRY, llvm::ISD::ADDE, llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::ISD::ANY_EXTEND_VECTOR_INREG, llvm::KnownBits::anyext(), llvm::KnownBits::ashr(), assert(), llvm::ISD::AssertAlign, llvm::ISD::AssertZext, llvm::ISD::ATOMIC_CMP_SWAP_WITH_SUCCESS, llvm::ISD::BITCAST, llvm::ISD::BITREVERSE, llvm::BitWidth, llvm::ISD::BSWAP, llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, llvm::KnownBits::byteSwap(), C, llvm::APInt::clearAllBits(), llvm::APInt::clearBit(), llvm::APInt::clearLowBits(), llvm::KnownBits::commonBits(), llvm::KnownBits::computeForAddCarry(), llvm::KnownBits::computeForAddSub(), llvm::KnownBits::computeForMul(), computeKnownBits(), llvm::TargetLowering::computeKnownBitsForFrameIndex(), llvm::TargetLowering::computeKnownBitsForTargetNode(), llvm::computeKnownBitsFromRangeMetadata(), llvm::ISD::CONCAT_VECTORS, llvm::KnownBits::countMaxLeadingZeros(), llvm::KnownBits::countMaxPopulation(), llvm::KnownBits::countMaxTrailingZeros(), llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::Depth, llvm::numbers::e, llvm::ISD::EXTRACT_ELEMENT, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::APInt::extractBits(), llvm::ISD::FGETSIGN, llvm::ISD::FrameIndex, llvm::ISD::FSHL, llvm::ISD::FSHR, llvm::Constant::getAggregateElement(), llvm::getAlign(), llvm::APInt::getAllOnesValue(), llvm::ConstantSDNode::getAPIntValue(), llvm::APInt::getBitWidth(), llvm::KnownBits::getBitWidth(), llvm::TargetLoweringBase::getBooleanContents(), getDataLayout(), llvm::APInt::getHiBits(), llvm::APInt::getLowBitsSet(), getMachineFunction(), llvm::ShuffleVectorSDNode::getMask(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::APInt::getNullValue(), llvm::APInt::getNumSignBits(), llvm::APInt::getOneBitSet(), llvm::Type::getPrimitiveSizeInBits(), llvm::EVT::getScalarSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::EVT::getSizeInBits(), llvm::Constant::getSplatValue(), llvm::TargetLowering::getTargetConstantFromLoad(), llvm::Value::getType(), getValidMinimumShiftAmountConstant(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::KnownBits::hasConflict(), Index, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::APInt::insertBits(), llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::isConstOrConstSplat(), llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::DataLayout::isLittleEndian(), llvm::APInt::isNegative(), llvm::ISD::isNON_EXTLoad(), llvm::APInt::isNonNegative(), llvm::EVT::isScalableVector(), llvm::KnownBits::isUnknown(), llvm::EVT::isVector(), llvm::Type::isVectorTy(), llvm::ISD::isZEXTLoad(), llvm::ARM_MB::LD, LLVM_FALLTHROUGH, llvm::ISD::LOAD, llvm::Log2(), llvm::Log2_32(), llvm::KnownBits::lshr(), llvm::APInt::lshr(), llvm::APInt::lshrInPlace(), llvm::KnownBits::makeConstant(), MaxRecursionDepth, llvm::min(), llvm::ISD::MUL, llvm::ISD::NON_EXTLOAD, Offset, llvm::KnownBits::One, llvm::ISD::OR, llvm::ISD::PARITY, llvm::KnownBits::resetAll(), llvm::KnownBits::reverseBits(), llvm::ISD::SADDO, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::APInt::setAllBits(), llvm::KnownBits::setAllZero(), llvm::APInt::setBit(), llvm::APInt::setBitsFrom(), llvm::ISD::SETCC, llvm::APInt::setHighBits(), llvm::APInt::setLowBits(), llvm::KnownBits::sext(), llvm::KnownBits::sextInReg(), llvm::ISD::SHL, llvm::KnownBits::shl(), llvm::APInt::shl(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::ArrayRef< T >::size(), llvm::APInt::sle(), llvm::ISD::SMAX, llvm::KnownBits::smax(), llvm::ISD::SMIN, llvm::KnownBits::smin(), llvm::ISD::SMULO, llvm::ISD::SRA, llvm::ISD::SREM, llvm::KnownBits::srem(), llvm::ISD::SRL, llvm::ISD::SSUBO, llvm::ISD::STRICT_FSETCC, llvm::ISD::STRICT_FSETCCS, llvm::ISD::SUB, llvm::ISD::SUBC, std::swap(), llvm::ISD::TargetFrameIndex, llvm::KnownBits::trunc(), llvm::APInt::trunc(), llvm::ISD::TRUNCATE, llvm::ISD::UADDO, llvm::ISD::UDIV, llvm::KnownBits::udiv(), llvm::ISD::UMAX, llvm::KnownBits::umax(), llvm::ISD::UMIN, llvm::KnownBits::umin(), llvm::ISD::UMULO, llvm::ISD::UREM, llvm::KnownBits::urem(), llvm::ISD::USUBO, llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::VSELECT, llvm::ISD::XOR, llvm::KnownBits::Zero, llvm::ISD::ZERO_EXTEND, llvm::ISD::ZERO_EXTEND_VECTOR_INREG, llvm::TargetLoweringBase::ZeroOrOneBooleanContent, llvm::KnownBits::zext(), llvm::APInt::zext(), llvm::APInt::zextOrSelf(), and llvm::KnownBits::zextOrTrunc().
computeKnownBits() [2/2]
KnownBits SelectionDAG::computeKnownBits (SDValue Op, unsigned Depth = 0) const
Determine which bits of Op are known to be either zero or one and return them in Known.
For vectors, the known bits are those that are shared by every vector element. Targets can implement the computeKnownBitsForTargetNode method in the TargetLowering class to allow target nodes to be understood.
For vectors, the known bits are those that are shared by every vector element.
Definition at line 2667 of file SelectionDAG.cpp.
References llvm::BitWidth, llvm::Depth, llvm::APInt::getAllOnesValue(), llvm::EVT::getVectorNumElements(), and llvm::EVT::isVector().
Referenced by adjustForRedundantAnd(), llvm::SelectionDAGISel::CheckOrMask(), combineSubToSubus(), combineVectorSignBitsTruncation(), computeKnownBits(), computeKnownBitsBinOp(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::LanaiTargetLowering::computeKnownBitsForTargetNode(), llvm::SparcTargetLowering::computeKnownBitsForTargetNode(), llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), ComputeNumSignBits(), computeOverflowKind(), llvm::TargetLowering::expandFixedPointDiv(), foldMaskAndShiftToScale(), haveNoCommonBitsSet(), isBitfieldPositioningOp(), isKnownToBeAPowerOfTwo(), isTruncateOf(), isWordAligned(), LowerAndToBT(), LowerMUL(), MaskedValueIsAllOnes(), MaskedValueIsZero(), matchBinaryShuffle(), matchRotateSub(), llvm::AMDGPUTargetLowering::numBitsUnsigned(), llvm::ARMTargetLowering::PerformCMOVCombine(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), llvm::AMDGPUTargetLowering::performShlCombine(), llvm::AMDGPUTargetLowering::performTruncateCombine(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::PPCTargetLowering::SelectAddressRegImm34(), llvm::PPCTargetLowering::SelectAddressRegReg(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), llvm::TargetLowering::SimplifyMultipleUseDemandedBits(), llvm::TargetLowering::SimplifySetCC(), tryBitfieldInsertOpFromOr(), and tryBitfieldInsertOpFromOrAndImm().
ComputeNumSignBits() [1/2]
unsigned SelectionDAG::ComputeNumSignBits (SDValue Op, const APInt & DemandedElts, unsigned Depth = 0) const
Return the number of times the sign bit of the register is replicated into the other bits.
We know that at least 1 bit is always equal to the sign bit (itself), but other cases can give us information. For example, immediately after an "SRA X, 2", we know that the top 3 bits are all equal to each other, so we return 3. The DemandedElts argument allows us to only collect the minimum sign bits of the requested vector elements. Targets can implement the ComputeNumSignBitsForTarget method in the TargetLowering class to allow target nodes to be understood.
Definition at line 3534 of file SelectionDAG.cpp.
References llvm::ISD::ADD, llvm::ISD::ADDC, llvm::ISD::AND, assert(), llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::ISD::BITCAST, llvm::BitWidth, llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, C, llvm::APInt::clearBit(), computeKnownBits(), ComputeNumSignBits(), llvm::TargetLowering::ComputeNumSignBitsForTargetNode(), llvm::ISD::CONCAT_VECTORS, llvm::Depth, llvm::numbers::e, llvm::ISD::EXTRACT_ELEMENT, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::APInt::extractBits(), llvm::Constant::getAggregateElement(), llvm::APInt::getAllOnesValue(), llvm::ConstantSDNode::getAPIntValue(), llvm::APInt::getBitWidth(), llvm::TargetLoweringBase::getBooleanContents(), getDataLayout(), llvm::ShuffleVectorSDNode::getMask(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::APInt::getNullValue(), llvm::APInt::getNumSignBits(), llvm::APInt::getOneBitSet(), llvm::Type::getPrimitiveSizeInBits(), llvm::EVT::getScalarSizeInBits(), llvm::SDValue::getScalarValueSizeInBits(), llvm::TargetLowering::getTargetConstantFromLoad(), getValidMaximumShiftAmountConstant(), getValidMinimumShiftAmountConstant(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::APInt::insertBits(), llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::isConstOrConstSplat(), llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::DataLayout::isLittleEndian(), llvm::KnownBits::isNegative(), llvm::KnownBits::isNonNegative(), llvm::EVT::isScalableVector(), llvm::EVT::isVector(), llvm::Type::isVectorTy(), llvm::ARM_MB::LD, llvm::APInt::lshr(), llvm::BitmaskEnumDetail::Mask(), llvm::max(), MaxRecursionDepth, llvm::min(), llvm::ISD::MUL, llvm::ISD::NON_EXTLOAD, llvm::KnownBits::One, llvm::ISD::OR, llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SADDO, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::APInt::setBit(), llvm::ISD::SETCC, llvm::ISD::SEXTLOAD, llvm::APInt::shl(), llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::ArrayRef< T >::size(), llvm::APInt::sle(), llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::SMULO, llvm::ISD::SRA, llvm::ISD::SSUBO, llvm::ISD::STRICT_FSETCC, llvm::ISD::STRICT_FSETCCS, llvm::ISD::SUB, std::swap(), llvm::APInt::trunc(), llvm::ISD::TRUNCATE, llvm::ISD::UADDO, llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::ISD::UMULO, llvm::ISD::USUBO, llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::VSELECT, llvm::ISD::XOR, llvm::KnownBits::Zero, llvm::TargetLoweringBase::ZeroOrNegativeOneBooleanContent, llvm::ISD::ZEXTLOAD, and llvm::APInt::zextOrSelf().
ComputeNumSignBits() [2/2]
unsigned SelectionDAG::ComputeNumSignBits (SDValue Op, unsigned Depth = 0) const
Return the number of times the sign bit of the register is replicated into the other bits.
We know that at least 1 bit is always equal to the sign bit (itself), but other cases can give us information. For example, immediately after an "SRA X, 2", we know that the top 3 bits are all equal to each other, so we return 3. Targets can implement the ComputeNumSignBitsForTarget method in the TargetLowering class to allow target nodes to be understood.
Definition at line 3521 of file SelectionDAG.cpp.
References llvm::Depth, llvm::APInt::getAllOnesValue(), llvm::EVT::getVectorNumElements(), llvm::EVT::isScalableVector(), and llvm::EVT::isVector().
Referenced by canReduceVMulWidth(), combineAndMaskToShift(), combineGatherScatter(), combineLogicBlendIntoConditionalNegate(), combineLogicBlendIntoPBLENDV(), combineMulToPMULDQ(), combinePredicateReduction(), combinePTESTCC(), combineSelect(), combineSetCCMOVMSK(), combineSIntToFP(), combineVectorCompareAndMaskUnaryOp(), combineVectorPack(), combineVectorSignBitsTruncation(), combineVSelectWithAllOnesOrZeros(), ComputeNumSignBits(), computeNumSignBitsBinOp(), llvm::SystemZTargetLowering::ComputeNumSignBitsForTargetNode(), llvm::X86TargetLowering::ComputeNumSignBitsForTargetNode(), llvm::AMDGPUTargetLowering::ComputeNumSignBitsForTargetNode(), EmitCmp(), llvm::TargetLowering::expandFixedPointDiv(), llvm::TargetLowering::expandMUL_LOHI(), foldAddSubMasked1(), getFauxShuffleMask(), isS16(), LowerADDSAT_SUBSAT(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), LowerTruncateVecI1(), matchShuffleWithPACK(), llvm::AMDGPUTargetLowering::numBitsSigned(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::TargetLowering::SimplifyMultipleUseDemandedBits(), and llvm::X86TargetLowering::SimplifyMultipleUseDemandedBitsForTargetNode().
computeOverflowKind()
SelectionDAG::OverflowKind SelectionDAG::computeOverflowKind (SDValue N0, SDValue N1) const
Determine if the result of the addition of 2 node can overflow.
Definition at line 3449 of file SelectionDAG.cpp.
References computeKnownBits(), llvm::APInt::getBoolValue(), llvm::KnownBits::getMaxValue(), llvm::SDValue::getOpcode(), llvm::SDValue::getResNo(), llvm::isNullConstant(), OFK_Never, OFK_Sometime, llvm::APInt::uadd_ov(), llvm::ISD::UMUL_LOHI, and llvm::KnownBits::Zero.
CreateStackTemporary() [1/3]
SDValue SelectionDAG::CreateStackTemporary (EVT VT, unsigned minAlign = 1)
Create a stack temporary, suitable for holding the specified value type.
If minAlign is specified, the slot size will have at least that alignment.
Definition at line 2144 of file SelectionDAG.cpp.
References Align, CreateStackTemporary(), getContext(), getDataLayout(), llvm::EVT::getStoreSize(), llvm::EVT::getTypeForEVT(), and llvm::max().
CreateStackTemporary() [2/3]
SDValue SelectionDAG::CreateStackTemporary (EVT VT1, EVT VT2)
Create a stack temporary suitable for holding either of the specified value types.
Definition at line 2151 of file SelectionDAG.cpp.
References assert(), CreateStackTemporary(), DL, getContext(), getDataLayout(), llvm::TypeSize::getKnownMinSize(), llvm::EVT::getStoreSize(), llvm::EVT::getTypeForEVT(), llvm::LinearPolySize< LeafTy >::isScalable(), and llvm::max().
CreateStackTemporary() [3/3]
SDValue SelectionDAG::CreateStackTemporary (TypeSize Bytes, Align Alignment)
Create a stack temporary based on the size in bytes and the alignment.
Definition at line 2131 of file SelectionDAG.cpp.
References llvm::MachineFrameInfo::CreateStackObject(), getDataLayout(), getFrameIndex(), llvm::TargetLoweringBase::getFrameIndexTy(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::TypeSize::getKnownMinSize(), llvm::TargetFrameLowering::getStackIDForScalableVectors(), llvm::MachineFunction::getSubtarget(), and llvm::LinearPolySize< LeafTy >::isScalable().
Referenced by CreateStackTemporary(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), llvm::SystemZTargetLowering::LowerCall(), and llvm::RISCVTargetLowering::LowerCall().
DbgBegin()
SDDbgInfo::DbgIterator llvm::SelectionDAG::DbgBegin () const inline
Definition at line 1647 of file SelectionDAG.h.
References llvm::SDDbgInfo::DbgBegin().
DbgEnd()
SDDbgInfo::DbgIterator llvm::SelectionDAG::DbgEnd () const inline
Definition at line 1648 of file SelectionDAG.h.
References llvm::SDDbgInfo::DbgEnd().
DbgLabelBegin()
SDDbgInfo::DbgLabelIterator llvm::SelectionDAG::DbgLabelBegin () const inline
Definition at line 1657 of file SelectionDAG.h.
References llvm::SDDbgInfo::DbgLabelBegin().
DbgLabelEnd()
SDDbgInfo::DbgLabelIterator llvm::SelectionDAG::DbgLabelEnd () const inline
Definition at line 1660 of file SelectionDAG.h.
References llvm::SDDbgInfo::DbgLabelEnd().
DeleteNode()
void SelectionDAG::DeleteNode (SDNode * N)
Remove the specified node from the system.
This node must have no referrers.
Definition at line 862 of file SelectionDAG.cpp.
References N.
Referenced by Legalize(), and llvm::SelectionDAGBuilder::LowerAsSTATEPOINT().
doesNodeExist()
bool SelectionDAG::doesNodeExist (unsigned Opcode, SDVTList VTList, ArrayRef< SDValue > Ops)
Check if a node exists without modifying its flags.
doesNodeExist - Check if a node exists without modifying its flags.
Definition at line 8379 of file SelectionDAG.cpp.
References AddNodeIDNode(), llvm::MVT::Glue, llvm::SDVTList::NumVTs, and llvm::SDVTList::VTs.
Referenced by llvm::TargetLowering::SimplifySetCC().
dump()
LLVM_DUMP_METHOD void SelectionDAG::dump () const
Definition at line 892 of file SelectionDAGDumper.cpp.
Referenced by NewSDValueDbgMsg(), and llvm::HexagonDAGToDAGISel::PreprocessISelDAG().
dumpDotGraph()
LLVM_DUMP_METHOD void SelectionDAG::dumpDotGraph (const Twine & FileName, const Twine & Title)
Just dump dot graph to a user-provided path and title.
This doesn't open the dot viewer program and helps visualization when outside debugging session. FileName expects absolute path. If provided without any path separators then the file will be created in the current directory. Error will be emitted if the path is insane.
Definition at line 175 of file SelectionDAGPrinter.cpp.
References dumpDotGraphToFile().
EVTToAPFloatSemantics()
static const fltSemantics& llvm::SelectionDAG::EVTToAPFloatSemantics (EVT VT) inline static
Returns an APFloat semantics tag appropriate for the given type.
If VT is a vector type, the element semantics are returned.
Definition at line 1617 of file SelectionDAG.h.
References llvm::MVT::bf16, llvm::APFloatBase::BFloat(), llvm::MVT::f128, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, llvm::EVT::getScalarType(), llvm::EVT::getSimpleVT(), llvm::APFloatBase::IEEEdouble(), llvm::APFloatBase::IEEEhalf(), llvm::APFloatBase::IEEEquad(), llvm::APFloatBase::IEEEsingle(), llvm_unreachable, llvm::APFloatBase::PPCDoubleDouble(), llvm::MVT::ppcf128, llvm::MVT::SimpleTy, and llvm::APFloatBase::x87DoubleExtended().
Referenced by foldConstantFPMath(), FoldIntToFPToInt(), getConstantFP(), getDenormalMode(), getMemsetValue(), getNeutralElement(), getNode(), llvm::TargetLowering::getSqrtInputTest(), llvm::ConstantFPSDNode::isValueValidForType(), LowerFABSorFNEG(), LowerFCOPYSIGN(), LowerFROUND(), lowerShuffleAsBitMask(), and llvm::TargetLowering::SimplifyDemandedBits().
expandVAArg()
SDValue SelectionDAG::expandVAArg (SDNode * Node)
Expand the specified ISD::VAARG node as the Legalize pass would.
Definition at line 2055 of file SelectionDAG.cpp.
expandVACopy()
SDValue SelectionDAG::expandVACopy (SDNode * Node)
Expand the specified ISD::VACOPY node as the Legalize pass would.
Definition at line 2089 of file SelectionDAG.cpp.
Referenced by LowerVACOPY().
ExtractVectorElements()
void SelectionDAG::ExtractVectorElements (SDValue Op, SmallVectorImpl< SDValue > & Args, unsigned Start = 0, unsigned Count = 0, EVT EltVT = EVT())
Append the extracted elements from Start to Count out of the vector Op in Args.
If Count is 0, all of the elements will be extracted. The extracted elements will have type EVT if it is provided, and otherwise their type will be Op's element type.
Definition at line 9820 of file SelectionDAG.cpp.
Referenced by adjustLoadValueTypeImpl(), llvm::AMDGPUTargetLowering::LowerCONCAT_VECTORS(), llvm::AMDGPUTargetLowering::LowerSIGN_EXTEND_INREG(), padEltsToUndef(), UnrollVectorOverflowOp(), unrollVectorShift(), and widenVectorToPartType().
FoldConstantArithmetic()
SDValue SelectionDAG::FoldConstantArithmetic (unsigned Opcode, const SDLoc & DL, EVT VT, ArrayRef< SDValue > Ops)
Definition at line 4931 of file SelectionDAG.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::EVT::bitsGT(), llvm::EVT::bitsLT(), llvm::ISD::BUILTIN_OP_END, llvm::ISD::Constant, llvm::ISD::ConstantFP, DL, FoldSymbolOffset(), FoldValue(), getBuildVector(), getConstant(), getContext(), getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::EVT::getScalarType(), llvm::TargetLoweringBase::getTypeToTransformTo(), getUNDEF(), llvm::Optional< T >::getValue(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), I, llvm::TargetLoweringBase::isCommutativeBinOp(), llvm::EVT::isInteger(), llvm::EVT::isScalableVector(), llvm::SDValue::isUndef(), llvm::SDNode::isUndef(), isUndef(), llvm::EVT::isVector(), NewNodesMustHaveLegalTypes, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorImpl< T >::resize(), llvm::ISD::SIGN_EXTEND, llvm::ArrayRef< T >::size(), llvm::SmallVectorBase< Size_T >::size(), llvm::ISD::TRUNCATE, and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by foldAddSubOfSignBit(), and getNode().
foldConstantFPMath()
SDValue SelectionDAG::foldConstantFPMath (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2)
Fold floating-point operations with 2 operands when both operands are constants and/or undefined.
Definition at line 5145 of file SelectionDAG.cpp.
References llvm::APFloat::add(), llvm::APFloat::convert(), llvm::APFloat::copySign(), llvm::APFloat::divide(), DL, EVTToAPFloatSemantics(), llvm::ISD::FADD, llvm::ISD::FCOPYSIGN, llvm::ISD::FDIV, llvm::ISD::FMUL, llvm::ISD::FP_ROUND, llvm::ISD::FREM, llvm::ISD::FSUB, getConstantFP(), llvm::APFloat::getNaN(), llvm::SDValue::getNode(), getUNDEF(), llvm::SDValue::isUndef(), LLVM_FALLTHROUGH, llvm::APFloat::mod(), llvm::APFloat::multiply(), llvm::APFloatBase::rmNearestTiesToEven, and llvm::APFloat::subtract().
Referenced by getNode().
FoldConstantVectorArithmetic()
SDValue SelectionDAG::FoldConstantVectorArithmetic (unsigned Opcode, const SDLoc & DL, EVT VT, ArrayRef< SDValue > Ops, const SDNodeFlags Flags = SDNodeFlags())
Definition at line 5042 of file SelectionDAG.cpp.
References llvm::all_of(), llvm::EVT::bitsGT(), llvm::EVT::bitsLT(), llvm::ISD::BUILTIN_OP_END, llvm::ISD::CONDCODE, llvm::ISD::Constant, llvm::ISD::ConstantFP, DL, getBuildVector(), getContext(), getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::EVT::getScalarType(), llvm::TargetLoweringBase::getTypeToTransformTo(), getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::MVT::i1, llvm::BuildVectorSDNode::isConstant(), llvm::EVT::isInteger(), llvm::EVT::isScalableVector(), llvm::SDValue::isUndef(), isUndef(), llvm::EVT::isVector(), NewNodesMustHaveLegalTypes, NewSDValueDbgMsg(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::ISD::SETCC, llvm::ISD::SIGN_EXTEND, and llvm::ISD::TRUNCATE.
Referenced by getNode().
FoldSetCC()
SDValue SelectionDAG::FoldSetCC (EVT VT, SDValue N1, SDValue N2, ISD::CondCode Cond, const SDLoc & dl)
Constant fold a setcc to true or false.
Definition at line 2167 of file SelectionDAG.cpp.
References assert(), llvm::APFloatBase::cmpEqual, llvm::APFloatBase::cmpGreaterThan, llvm::APFloatBase::cmpLessThan, llvm::APFloatBase::cmpUnordered, Cond, getBoolConstant(), getSetCC(), llvm::ISD::getSetCCSwappedOperands(), llvm::EVT::getSimpleVT(), getUNDEF(), llvm::ISD::getUnorderedFlavor(), llvm::SDValue::getValueType(), llvm::TargetLoweringBase::isCondCodeLegal(), llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::EVT::isSimple(), llvm::ISD::isTrueWhenEqual(), llvm::SDValue::isUndef(), LLVM_FALLTHROUGH, llvm_unreachable, llvm::ISD::SETEQ, llvm::ISD::SETFALSE, llvm::ISD::SETFALSE2, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETO, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETONE, llvm::ISD::SETTRUE, llvm::ISD::SETTRUE2, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, llvm::ISD::SETUO, llvm::APInt::sge(), llvm::APInt::sgt(), llvm::APInt::sle(), llvm::APInt::slt(), llvm::APInt::uge(), llvm::APInt::ugt(), llvm::APInt::ule(), and llvm::APInt::ult().
Referenced by getNode(), and llvm::TargetLowering::SimplifySetCC().
FoldSymbolOffset()
SDValue SelectionDAG::FoldSymbolOffset (unsigned Opcode, EVT VT, const GlobalAddressSDNode * GA, const SDNode * N2)
Definition at line 4886 of file SelectionDAG.cpp.
References llvm::ISD::ADD, llvm::GlobalAddressSDNode::getGlobal(), getGlobalAddress(), llvm::GlobalAddressSDNode::getOffset(), llvm::SDNode::getOpcode(), llvm::ISD::GlobalAddress, llvm::TargetLowering::isOffsetFoldingLegal(), Offset, and llvm::ISD::SUB.
Referenced by FoldConstantArithmetic().
getAddrSpaceCast()
SDValue SelectionDAG::getAddrSpaceCast (const SDLoc & dl, EVT VT, SDValue Ptr, unsigned SrcAS, unsigned DestAS)
Return an AddrSpaceCastSDNode.
Definition at line 2020 of file SelectionDAG.cpp.
References AddNodeIDNode(), llvm::ISD::ADDRSPACECAST, E, llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), getVTList(), and N.
Referenced by combineLoad(), combineStore(), and llvm::SITargetLowering::LowerFormalArguments().
getAllOnesConstant()
SDValue llvm::SelectionDAG::getAllOnesConstant (const SDLoc & DL, EVT VT, bool IsTarget = false, bool IsOpaque = false) inline
Definition at line 629 of file SelectionDAG.h.
References DL, llvm::APInt::getAllOnesValue(), getConstant(), and llvm::EVT::getScalarSizeInBits().
Referenced by getBoolConstant(), getNeutralElement(), getNode(), LowerADDSUBCARRY(), LowerBUILD_VECTORvXi1(), lowerShuffleAsBitBlend(), lowerShuffleAsBitMask(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifySetCC(), and simplifySetCCWithCTPOP().
getAnyExtOrTrunc()
SDValue SelectionDAG::getAnyExtOrTrunc (SDValue Op, const SDLoc & DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either any-extending or truncating it.
Definition at line 1247 of file SelectionDAG.cpp.
References llvm::ISD::ANY_EXTEND, llvm::EVT::bitsGT(), DL, getNode(), and llvm::ISD::TRUNCATE.
Referenced by combineBitcast(), combineScalarToVector(), combineToExtendBoolVectorInReg(), createGPRPairNode(), createMMXBuildVector(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemset(), getCopyFromPartsVector(), getCopyToPartsVector(), getNode(), LowerBuildVectorAsInsert(), LowerBuildVectorv16i8(), LowerFunnelShift(), LowerMUL(), performCommonVectorExtendCombine(), and llvm::HexagonTargetLowering::ReplaceNodeResults().
getAssertAlign()
SDValue SelectionDAG::getAssertAlign (const SDLoc & DL, SDValue V, Align A)
Return an AssertAlignSDNode.
Definition at line 5208 of file SelectionDAG.cpp.
References AddNodeIDNode(), Align, assert(), llvm::ISD::AssertAlign, DL, E, llvm::SDValue::getValueType(), getVTList(), llvm::EVT::isInteger(), N, and NewSDValueDbgMsg().
getAtomic() [1/3]
SDValue SelectionDAG::getAtomic (unsigned Opcode, const SDLoc & dl, EVT MemVT, EVT VT, SDValue Chain, SDValue Ptr, MachineMemOperand * MMO)
Gets a node for an atomic op, produces result and chain and takes 1 operand.
Definition at line 6825 of file SelectionDAG.cpp.
References assert(), llvm::ISD::ATOMIC_LOAD, getAtomic(), getVTList(), and llvm::MVT::Other.
getAtomic() [2/3]
SDValue SelectionDAG::getAtomic (unsigned Opcode, const SDLoc & dl, EVT MemVT, SDValue Chain, SDValue Ptr, SDValue Val, MachineMemOperand * MMO)
Gets a node for an atomic op, produces result (if relevant) and chain and takes 2 operands.
Definition at line 6797 of file SelectionDAG.cpp.
References assert(), llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_CLR, llvm::ISD::ATOMIC_LOAD_FADD, llvm::ISD::ATOMIC_LOAD_FSUB, llvm::ISD::ATOMIC_LOAD_MAX, llvm::ISD::ATOMIC_LOAD_MIN, llvm::ISD::ATOMIC_LOAD_NAND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, llvm::ISD::ATOMIC_LOAD_UMAX, llvm::ISD::ATOMIC_LOAD_UMIN, llvm::ISD::ATOMIC_LOAD_XOR, llvm::ISD::ATOMIC_STORE, llvm::ISD::ATOMIC_SWAP, llvm::SDValue::getValueType(), getVTList(), and llvm::MVT::Other.
Referenced by combineSetCCAtomicArith(), getAtomic(), getAtomicCmpSwap(), llvm::VETargetLowering::lowerATOMIC_SWAP(), and lowerAtomicArith().
getAtomic() [3/3]
SDValue SelectionDAG::getAtomic (unsigned Opcode, const SDLoc & dl, EVT MemVT, SDVTList VTList, ArrayRef< SDValue > Ops, MachineMemOperand * MMO)
Gets a node for an atomic op, produces result and chain and takes N operands.
Definition at line 6763 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), and N.
getAtomicCmpSwap()
SDValue SelectionDAG::getAtomicCmpSwap (unsigned Opcode, const SDLoc & dl, EVT MemVT, SDVTList VTs, SDValue Chain, SDValue Ptr, SDValue Cmp, SDValue Swp, MachineMemOperand * MMO)
Gets a node for an atomic cmpxchg op.
There are two valid Opcodes. ISD::ATOMIC_CMO_SWAP produces the value loaded and a chain result. ISD::ATOMIC_CMP_SWAP_WITH_SUCCESS produces the value loaded, a success flag (initially i1), and a chain.
Definition at line 6785 of file SelectionDAG.cpp.
References assert(), llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_CMP_SWAP_WITH_SUCCESS, getAtomic(), and llvm::SDValue::getValueType().
getAtomicMemcpy()
SDValue SelectionDAG::getAtomicMemcpy (SDValue Chain, const SDLoc & dl, SDValue Dst, unsigned DstAlign, SDValue Src, unsigned SrcAlign, SDValue Size, Type * SizeTy, unsigned ElemSz, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo)
Definition at line 6521 of file SelectionDAG.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args.
getAtomicMemmove()
SDValue SelectionDAG::getAtomicMemmove (SDValue Chain, const SDLoc & dl, SDValue Dst, unsigned DstAlign, SDValue Src, unsigned SrcAlign, SDValue Size, Type * SizeTy, unsigned ElemSz, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo)
Definition at line 6623 of file SelectionDAG.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args.
getAtomicMemset()
SDValue SelectionDAG::getAtomicMemset (SDValue Chain, const SDLoc & dl, SDValue Dst, unsigned DstAlign, SDValue Value, SDValue Size, Type * SizeTy, unsigned ElemSz, bool isTailCall, MachinePointerInfo DstPtrInfo)
Definition at line 6723 of file SelectionDAG.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args.
getBasicBlock()
SDValue SelectionDAG::getBasicBlock (MachineBasicBlock * MBB)
Definition at line 1652 of file SelectionDAG.cpp.
References AddNodeIDNode(), llvm::ISD::BasicBlock, E, getVTList(), MBB, N, llvm::None, and llvm::MVT::Other.
Referenced by AddNodeIDCustom(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), and llvm::SelectionDAGBuilder::visitSwitchCase().
getBFI()
BlockFrequencyInfo* llvm::SelectionDAG::getBFI () const inline
Definition at line 457 of file SelectionDAG.h.
References llvm::AMDGPUISD::BFI.
getBitcast()
SDValue SelectionDAG::getBitcast (EVT VT, SDValue V)
Return a bitcast using the SDLoc of the value operand, and casting to the provided type.
Use getNode to set a custom SDLoc.
Definition at line 2013 of file SelectionDAG.cpp.
References llvm::ISD::BITCAST, getNode(), and llvm::SDValue::getValueType().
Referenced by addShuffleForVecExtend(), adjustBitcastSrcVectorSSE1(), canonicalizeBitSelect(), canonicalizeLaneShuffleWithRepeatedOps(), combineAnd(), combineAndMaskToShift(), combineAndnp(), combineANDXORWithAllOnesIntoANDNP(), combineArithReduction(), combineBasicSADPattern(), combineBitcast(), combineBitcastToBoolVector(), combineBitcastvxi1(), combineBitOpWithMOVMSK(), combineBROADCAST_LOAD(), combineCastedMaskArithmetic(), combineCompareEqual(), combineConcatVectorOfExtracts(), combineConcatVectorOfScalars(), combineConcatVectorOps(), combineCVTP2I_CVTTP2I(), combineCVTPH2PS(), combineExtractSubvector(), combineExtractVectorElt(), combineExtractWithShuffle(), combineFneg(), combineFP_EXTEND(), combineFP_ROUND(), combineHorizOpWithShuffle(), combineLoad(), combineLogicBlendIntoConditionalNegate(), combineLogicBlendIntoPBLENDV(), combineMinMaxReduction(), combineMOVMSK(), combineMulToPMADDWD(), combineOr(), combinePMULDQ(), combinePredicateReduction(), combinePTESTCC(), combineRedundantDWordShuffle(), combineScalarAndWithMaskSetcc(), combineScalarToVector(), combineSelect(), combineSetCCMOVMSK(), combineShuffleToVectorExtend(), combineSIntToFP(), combineStore(), combineTargetShuffle(), combineToExtendBoolVectorInReg(), combineToFPTruncExtElt(), combineTruncationShuffle(), combineVectorCompareAndMaskUnaryOp(), combineVectorSizedSetCCEquality(), combineVSelectWithAllOnesOrZeros(), combineX86INT_TO_FP(), combineX86ShuffleChain(), combineX86ShuffleChainWithExtract(), combineX86ShufflesConstants(), combineX86ShufflesRecursively(), combineXor(), constructDup(), convertIntLogicToFPLogic(), convertShiftLeftToScale(), createMMXBuildVector(), EltsFromConsecutiveLoads(), FoldIntToFPToInt(), foldShuffleOfHorizOp(), getAVX2GatherNode(), getBuildDwordsVector(), getCanonicalConstSplat(), getConstVector(), getCopyFromPartsVector(), getCopyToPartsVector(), getMaskNode(), getMemsetValue(), llvm::X86TargetLowering::getNegatedExpression(), getOnesVector(), getScalarMaskingNode(), getScalarValueForVectorElement(), getTargetVShiftByConstNode(), getTargetVShiftNode(), getv64i1Argument(), getVShift(), getZeroVector(), llvm::TargetLowering::IncrementMemoryAddress(), isHorizontalBinOp(), IsNOT(), lower256BitShuffle(), LowerAVXExtend(), LowerBITCAST(), llvm::HexagonTargetLowering::LowerBITCAST(), LowerBITREVERSE(), LowerBITREVERSE_XOP(), LowerBUILD_VECTORvXi1(), lowerBuildVectorAsBroadcast(), LowerBuildVectorAsInsert(), LowerBuildVectorv16i8(), LowerBuildVectorv4x32(), llvm::HexagonTargetLowering::LowerCall(), LowerCTPOP(), LowerEXTEND_VECTOR_INREG(), llvm::VETargetLowering::lowerEXTRACT_VECTOR_ELT(), LowerEXTRACT_VECTOR_ELT_SSE4(), LowerHorizontalByteSum(), llvm::VETargetLowering::lowerINSERT_VECTOR_ELT(), LowerLoad(), lowerMasksToReg(), LowerMUL(), LowerMULH(), lowerRegToMasks(), LowerRotate(), LowerSCALAR_TO_VECTOR(), LowerScalarImmediateShift(), LowerScalarVariableShift(), LowerShift(), lowerShuffleAsBitMask(), lowerShuffleAsBitRotate(), lowerShuffleAsBlend(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotate(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsByteShiftMask(), lowerShuffleAsElementInsertion(), lowerShuffleAsLanePermuteAndShuffle(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsShift(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleAsVTRUNC(), lowerShuffleAsVTRUNCAndUnpack(), lowerShuffleAsZeroOrAnyExtend(), lowerShuffleWithPACK(), lowerShuffleWithPSHUFB(), lowerShuffleWithUNPCK256(), LowerStore(), LowerTruncateVecI1(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), LowerUINT_TO_FP_i32(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), lowerV16I32Shuffle(), lowerV16I8Shuffle(), lowerV2I64Shuffle(), lowerV4I32Shuffle(), lowerV4I64Shuffle(), lowerV8I16GeneralSingleInputShuffle(), lowerV8I16Shuffle(), lowerV8I32Shuffle(), lowerV8I64Shuffle(), lowerVECTOR_SHUFFLE(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), LowerVectorAllZero(), LowerVectorCTLZInRegLUT(), LowerVectorCTPOP(), LowerVSETCC(), lowerX86FPLogicOp(), matchShuffleWithPACK(), narrowExtractedVectorBinOp(), narrowExtractedVectorSelect(), packImageA16AddressToDwords(), Passv64i1ArgInRegs(), performVECTOR_SHUFFLECombine(), reduceBuildVecToShuffleWithZero(), reduceMaskedLoadToScalarLoad(), reduceMaskedStoreToScalarStore(), reduceVMULWidth(), llvm::X86TargetLowering::ReplaceNodeResults(), scalarizeVectorStore(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetShuffle(), llvm::TargetLowering::SimplifyMultipleUseDemandedBits(), llvm::X86TargetLowering::SimplifyMultipleUseDemandedBitsForTargetNode(), splitAndLowerShuffle(), and truncateVectorWithPACK().
getBlockAddress()
SDValue SelectionDAG::getBlockAddress (const BlockAddress * BA, EVT VT, int64_t Offset = 0, bool isTarget = false, unsigned TargetFlags = 0)
Definition at line 1963 of file SelectionDAG.cpp.
References AddNodeIDNode(), llvm::ISD::BlockAddress, E, getVTList(), N, llvm::None, Offset, and llvm::ISD::TargetBlockAddress.
Referenced by getTargetBlockAddress(), llvm::SelectionDAGBuilder::getValueImpl(), and llvm::LanaiTargetLowering::LowerBlockAddress().
getBoolConstant()
SDValue SelectionDAG::getBoolConstant (bool V, const SDLoc & DL, EVT VT, EVT OpVT)
Create a true or false constant of type VT using the target's BooleanContent for type OpVT.
Definition at line 1317 of file SelectionDAG.cpp.
References DL, getAllOnesConstant(), llvm::TargetLoweringBase::getBooleanContents(), getConstant(), llvm_unreachable, llvm::TargetLoweringBase::UndefinedBooleanContent, llvm::TargetLoweringBase::ZeroOrNegativeOneBooleanContent, and llvm::TargetLoweringBase::ZeroOrOneBooleanContent.
Referenced by FoldSetCC(), getLogicalNOT(), llvm::TargetLowering::SimplifySetCC(), and UnrollVectorOverflowOp().
getBoolExtOrTrunc()
SDValue SelectionDAG::getBoolExtOrTrunc (SDValue Op, const SDLoc & SL, EVT VT, EVT OpVT)
Convert Op, which must be of integer type, to the integer type VT, by using an extension appropriate for the target's BooleanContent for type OpVT or truncating it.
Definition at line 1265 of file SelectionDAG.cpp.
References llvm::EVT::bitsLE(), llvm::TargetLoweringBase::getBooleanContents(), llvm::TargetLoweringBase::getExtendForContent(), getNode(), and llvm::ISD::TRUNCATE.
Referenced by llvm::TargetLowering::SimplifySetCC().
getBuildVector() [1/2]
SDValue llvm::SelectionDAG::getBuildVector (EVT VT, const SDLoc & DL, ArrayRef< SDUse > Ops) inline
Return an ISD::BUILD_VECTOR node.
The number of elements in VT, which must be a vector type, must match the number of operands in Ops. The operands must have the same type as (or, for integers, a type wider than) VT's element type.
Definition at line 806 of file SelectionDAG.h.
References llvm::ISD::BUILD_VECTOR, DL, and getNode().
getBuildVector() [2/2]
SDValue llvm::SelectionDAG::getBuildVector (EVT VT, const SDLoc & DL, ArrayRef< SDValue > Ops) inline
Return an ISD::BUILD_VECTOR node.
The number of elements in VT, which must be a vector type, must match the number of operands in Ops. The operands must have the same type as (or, for integers, a type wider than) VT's element type.
Definition at line 797 of file SelectionDAG.h.
References llvm::ISD::BUILD_VECTOR, DL, and getNode().
Referenced by adjustLoadValueTypeImpl(), llvm::SparcTargetLowering::bitcastConstantFPToInt(), BuildExactSDIV(), buildScalarToVector(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), combineConcatVectorOfScalars(), combineExtractSubvector(), combineShuffleOfScalars(), combineStore(), combineToExtendBoolVectorInReg(), combineX86ShuffleChain(), CompactSwizzlableVector(), convertLocVTToValVT(), convertShiftLeftToScale(), detectAVGPattern(), ExtendToType(), extractSubVector(), foldCONCAT_VECTORS(), FoldConstantArithmetic(), FoldConstantVectorArithmetic(), GenerateTBL(), getBuildDwordsVector(), getBuildVectorSplat(), getConstant(), getConstVector(), getCopyFromPartsVector(), getGeneralPermuteNode(), llvm::TargetLowering::getNegatedExpression(), getNode(), getTargetVShiftByConstNode(), getTargetVShiftNode(), llvm::SelectionDAGBuilder::getValueImpl(), incDecVectorConstant(), LowerBITREVERSE(), LowerBITREVERSE_XOP(), lowerBuildVectorToBitOp(), LowerBuildVectorv4x32(), llvm::AMDGPUTargetLowering::LowerCONCAT_VECTORS(), llvm::AMDGPUTargetLowering::LowerFP64_TO_INT(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), lowerINT_TO_FP_vXi64(), lowerMSABinaryBitImmIntr(), lowerMSASplatZExt(), LowerMUL(), LowerMULH(), LowerShift(), lowerShuffleAsBitBlend(), lowerShuffleAsBitMask(), lowerShuffleAsBlend(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleWithPSHUFB(), llvm::AMDGPUTargetLowering::LowerSIGN_EXTEND_INREG(), LowerTruncateVectorStore(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), lowerV16I8Shuffle(), lowerV8I16Shuffle(), lowerVECTOR_SHUFFLE_VSHF(), LowerVECTOR_SHUFFLEv8i8(), LowerVectorCTLZInRegLUT(), LowerVectorCTPOPInRegLUT(), NormalizeBuildVector(), packImageA16AddressToDwords(), padEltsToUndef(), PerformBUILD_VECTORCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::AMDGPUTargetLowering::performShlCombine(), llvm::AMDGPUTargetLowering::performSraCombine(), llvm::AMDGPUTargetLowering::performSrlCombine(), ReorganizeVector(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::X86TargetLowering::ReplaceNodeResults(), scalarizeBinOpOfSplats(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::SimplifyDemandedVectorElts(), skipExtensionForVectorMULL(), SkipExtensionForVMULL(), llvm::AMDGPUTargetLowering::splitBinaryBitConstantOpImpl(), tryBuildVectorShuffle(), tryToFoldExtendOfConstant(), UnrollVectorOp(), UnrollVectorOverflowOp(), unrollVectorShift(), and widenVectorToPartType().
getCALLSEQ_END()
SDValue llvm::SelectionDAG::getCALLSEQ_END (SDValue Chain, SDValue Op1, SDValue Op2, SDValue InGlue, const SDLoc & DL) inline
Return a new CALLSEQ_END node, which always must have a glue result (to ensure it's not CSE'd).
CALLSEQ_END does not have a useful SDLoc.
Definition at line 934 of file SelectionDAG.h.
References llvm::ISD::CALLSEQ_END, DL, llvm::SDValue::getNode(), getNode(), getVTList(), llvm::MVT::Glue, llvm::MVT::Other, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::SITargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SITargetLowering::lowerDYNAMIC_STACKALLOCImpl(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::VETargetLowering::lowerToTLSGeneralDynamicModel(), and PrepareTailCall().
getCALLSEQ_START()
SDValue llvm::SelectionDAG::getCALLSEQ_START (SDValue Chain, uint64_t InSize, uint64_t OutSize, const SDLoc & DL) inline
Return a new CALLSEQ_START node, that starts new call frame, in which InSize bytes are set up inside CALLSEQ_START..CALLSEQ_END sequence and OutSize specifies part of the frame set up prior to the sequence.
Definition at line 922 of file SelectionDAG.h.
References llvm::ISD::CALLSEQ_START, DL, getIntPtrConstant(), getNode(), getVTList(), llvm::MVT::Glue, and llvm::MVT::Other.
Referenced by llvm::SITargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SITargetLowering::lowerDYNAMIC_STACKALLOCImpl(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), and llvm::VETargetLowering::lowerToTLSGeneralDynamicModel().
getCommutedVectorShuffle()
SDValue SelectionDAG::getCommutedVectorShuffle (const ShuffleVectorSDNode & SV)
Returns an ISD::VECTOR_SHUFFLE node semantically equivalent to the shuffle node in input but with swapped operands.
Example: shuffle A, B, <0,5,2,7> -> shuffle B, A, <4,1,6,3>
Definition at line 1900 of file SelectionDAG.cpp.
References llvm::ArrayRef< T >::begin(), llvm::ShuffleVectorSDNode::commuteMask(), llvm::ArrayRef< T >::end(), llvm::ShuffleVectorSDNode::getMask(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), and getVectorShuffle().
Referenced by lowerVECTOR_SHUFFLE().
getCondCode()
SDValue SelectionDAG::getCondCode (ISD::CondCode Cond)
Definition at line 1707 of file SelectionDAG.cpp.
References Cond, and N.
Referenced by getSelectCC(), getSetCC(), lowerBALLOTIntrinsic(), lowerFCMPIntrinsic(), lowerICMPIntrinsic(), LowerTruncatei1(), LowerVSETCC(), performIntrinsicCombine(), and tryConvertSVEWideCompare().
getConstant() [1/3]
SDValue SelectionDAG::getConstant (const APInt & Val, const SDLoc & DL, EVT VT, bool isTarget = false, bool isOpaque = false)
Definition at line 1341 of file SelectionDAG.cpp.
References DL, llvm::ConstantInt::get(), and getConstant().
getConstant() [2/3]
SDValue SelectionDAG::getConstant (const ConstantInt & Val, const SDLoc & DL, EVT VT, bool isTarget = false, bool isOpaque = false)
Definition at line 1346 of file SelectionDAG.cpp.
References AddNodeIDNode(), llvm::append_range(), assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::ISD::BITCAST, llvm::ISD::Constant, DL, llvm::numbers::e, llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::ConstantInt::get(), llvm::ConstantInt::getBitWidth(), getBuildVector(), getConstant(), getContext(), getDataLayout(), getNode(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), getSplatBuildVector(), getSplatVector(), llvm::TargetLoweringBase::getTypeAction(), llvm::TargetLoweringBase::getTypeToTransformTo(), llvm::ConstantInt::getValue(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), getVTList(), isBigEndian(), llvm::EVT::isInteger(), llvm::EVT::isScalableVector(), llvm::EVT::isVector(), llvm::APInt::lshr(), N, NewNodesMustHaveLegalTypes, NewSDValueDbgMsg(), llvm::None, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::reverse(), llvm::ISD::TargetConstant, llvm::TargetLoweringBase::TypeExpandInteger, llvm::TargetLoweringBase::TypePromoteInteger, and llvm::APInt::zextOrTrunc().
getConstant() [3/3]
SDValue SelectionDAG::getConstant (uint64_t Val, const SDLoc & DL, EVT VT, bool isTarget = false, bool isOpaque = false)
Create a ConstantSDNode wrapping a constant value.
If VT is a vector type, the constant is splatted into a BUILD_VECTOR.
If only legal types can be produced, this does the necessary transformations (e.g., if the vector element type is illegal).
Definition at line 1332 of file SelectionDAG.cpp.
References assert(), DL, llvm::EVT::getScalarType(), and llvm::EVT::getSizeInBits().
Referenced by AddCombineBUILD_VECTORToVPADDL(), AddCombineToVPADD(), AddCombineVUZPToVPADDL(), addIPMSequence(), adjustForSubtraction(), adjustForTestUnderMask(), adjustICmpTruncate(), adjustSubwordCmp(), adjustZeroCmp(), llvm::SparcTargetLowering::bitcastConstantFPToInt(), bitcastf32Toi32(), buildCallOperands(), BuildExactSDIV(), BuildIntrinsicOp(), llvm::SITargetLowering::buildRSRC(), llvm::TargetLowering::BuildSDIV(), llvm::PPCTargetLowering::BuildSDIVPow2(), llvm::TargetLowering::BuildUDIV(), clampDynamicVectorIndex(), combineAcrossLanesIntrinsic(), combineADC(), combineADDCARRYDiamond(), combineAddOrSubToADCOrSBB(), combineADDToADDZE(), combineAnd(), combineAndnp(), CombineANDShift(), combineArithReduction(), CombineBaseUpdate(), combineBitcast(), combineBitcastToBoolVector(), combineCarryDiamond(), combineCMov(), combineCMP(), combineCompareEqual(), combineExtractSubvector(), combineExtractVectorElt(), combineExtractWithShuffle(), combineFP_EXTEND(), combineKSHIFT(), combineMinMaxReduction(), combineMOVMSK(), combineMul(), combineMulSpecial(), combineOr(), combinePMULDQ(), combinePredicateReduction(), combinePTESTCC(), combineScalarAndWithMaskSetcc(), combineSelect(), combineSelectOfTwoConstants(), combineSetCC(), combineSetCCAtomicArith(), combineSetCCMOVMSK(), combineShiftAnd1ToBitTest(), combineShiftLeft(), combineShiftOfShiftedLogic(), combineShiftRightArithmetic(), combineShiftRightLogical(), combineStore(), combineSub(), combineSubToSubus(), combineSVEPrefetchVecBaseImmOff(), combineSVEReductionFP(), combineSVEReductionInt(), combineSVEReductionOrderedFP(), combineTargetShuffle(), combineToExtendBoolVectorInReg(), combineVectorCompare(), combineVectorShiftImm(), combineVectorShiftVar(), combineVectorSizedSetCCEquality(), combineVectorTruncationWithPACKUS(), CombineVMOVDRRCandidateWithVecOp(), combineVSelectWithAllOnesOrZeros(), combinevXi1ConstantToInteger(), combineX86AddSub(), combineX86ShuffleChain(), constantFoldBFE(), constructDup(), constructRetValue(), ConvertBooleanCarryToCarryFlag(), ConvertCarryFlagToBooleanCarry(), convertFromScalableVector(), convertShiftLeftToScale(), convertToScalableVector(), convertValVTToLocVT(), CreateCopyOfByValArgument(), createFPCmp(), createGPRPairNode(), createLoadLR(), createPSADBW(), createStoreLR(), createVariablePermute(), detectAVGPattern(), EltsFromConsecutiveLoads(), emitCLC(), EmitCMP(), emitConditionalComparison(), emitConstantSizeRepmov(), emitMemMem(), emitSETCC(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemchr(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::BPFSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcmp(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcpy(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrlen(), EmitTest(), Expand64BitShift(), llvm::TargetLowering::expandABS(), expandDivFix(), expandf64Toi32(), llvm::TargetLowering::expandFixedPointDiv(), expandIntrinsicWChainHelper(), llvm::TargetLowering::expandMUL_LOHI(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), ExtendToType(), extractF64Exponent(), extractShiftForRotate(), finalizeTS1AM(), foldAddSubBoolOfMaskedVal(), FoldConstantArithmetic(), foldExtendedSignBitTest(), foldMaskAndShiftToExtract(), foldMaskAndShiftToScale(), foldMaskedShiftToBEXTR(), foldMaskedShiftToScaledMask(), foldSelectOfConstantsUsingSra(), foldXorTruncShiftIntoCmp(), genConstMult(), generateEquivalentSub(), GeneratePerfectShuffle(), GenerateTBL(), getAArch64Cmp(), getAArch64XALUOOp(), getAbsolute(), llvm::MipsTargetLowering::getAddrNonPICSym64(), getAllOnesConstant(), getARMIndexedAddressParts(), getBoolConstant(), getBuildVectorSplat(), getCanonicalConstSplat(), getCCResult(), getConstant(), getConstVector(), getCopyFromParts(), llvm::RegsForValue::getCopyFromRegs(), GetDemandedBits(), GetExponent(), getGeneralPermuteNode(), llvm::AMDGPUTargetLowering::getHiHalf64(), getIntPtrConstant(), getLimitedPrecisionExp2(), llvm::AMDGPUTargetLowering::getLoHalf64(), getMaskNode(), getMemBasePlusOffset(), getMemsetStringVal(), getMemsetValue(), getMVEIndexedAddressParts(), getNeutralElement(), getNode(), getNOT(), getOnesVector(), getPMOVMSKB(), llvm::AVRTargetLowering::getPostIndexedAddressParts(), llvm::AVRTargetLowering::getPreIndexedAddressParts(), getPTest(), getReductionSDNode(), getScaledOffsetForBitWidth(), getShiftAmountConstant(), getShuffleScalarElt(), GetSignificand(), llvm::NVPTXTargetLowering::getSqrtEstimate(), getT2IndexedAddressParts(), getTargetConstant(), getTargetVShiftByConstNode(), getTargetVShiftNode(), getUniformBase(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::TargetLowering::getVectorElementPointer(), getVectorIdxConstant(), getVScale(), getZeroExtendInReg(), getZeroVector(), incDecVectorConstant(), llvm::TargetLowering::IncrementMemoryAddress(), initAccumulator(), insert1BitVector(), IntCondCCodeToICC(), isBLACompatibleAddress(), isConditionalZeroOrAllOnes(), IsSingleInstrConstant(), llvm::AMDGPUTargetLowering::loadInputValue(), lower1BitShuffle(), LowerABS(), LowerADDC_ADDE_SUBC_SUBE(), LowerADDSAT_SUBSAT(), LowerADDSUBCARRY(), LowerAndToBT(), LowerAsSplatVectorLoad(), LowerATOMIC_FENCE(), lowerAtomicArith(), LowerAVXExtend(), lowerBALLOTIntrinsic(), LowerBITREVERSE(), LowerBITREVERSE_XOP(), llvm::LanaiTargetLowering::LowerBR_CC(), LowerBR_CC(), llvm::HexagonTargetLowering::LowerBUILD_VECTOR(), llvm::VETargetLowering::lowerBUILD_VECTOR(), LowerBUILD_VECTOR_i1(), LowerBUILD_VECTORvXi1(), LowerBuildVectorOfFPExt(), LowerBuildVectorOfFPTrunc(), LowerBuildVectorv16i8(), llvm::SITargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), LowerCallResult(), llvm::TargetLowering::lowerCmpEqZeroToCtlzSrl(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), LowerCONCAT_VECTORS_i1(), LowerCONCAT_VECTORSvXi1(), LowerCTLZ(), llvm::AMDGPUTargetLowering::LowerCTLZ_CTTZ(), LowerCTPOP(), LowerCTTZ(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::AMDGPUTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::HexagonTargetLowering::LowerDYNAMIC_STACKALLOC(), LowerDYNAMIC_STACKALLOC(), llvm::SITargetLowering::lowerDYNAMIC_STACKALLOCImpl(), LowerEXTEND_VECTOR_INREG(), LowerEXTRACT_SUBVECTOR(), llvm::VETargetLowering::lowerEXTRACT_VECTOR_ELT(), LowerEXTRACT_VECTOR_ELT_i1(), llvm::SparcTargetLowering::LowerF128Compare(), LowerF128Load(), LowerF128Store(), lowerFABS32(), lowerFABS64(), lowerFCOPYSIGN32(), lowerFCOPYSIGN64(), LowerFGETSIGN(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerFP16_TO_FP(), llvm::AMDGPUTargetLowering::LowerFP_TO_FP16(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), LowerFunnelShift(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::HexagonTargetLowering::LowerGLOBALADDRESS(), LowerHorizontalByteSum(), llvm::VETargetLowering::lowerINSERT_VECTOR_ELT(), LowerINSERT_VECTOR_ELT_i1(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP32(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP64(), lowerINT_TO_FP_vXi64(), LowerInterruptReturn(), llvm::HexagonTargetLowering::LowerINTRINSIC_VOID(), LowerINTRINSIC_W_CHAIN(), LowerLabelRef(), llvm::MipsTargetLowering::lowerLOAD(), lowerLoadF128(), LowerMemOpCallTo(), lowerMSABinaryBitImmIntr(), lowerMSABitClear(), lowerMSABitClearImm(), lowerMSASplatImm(), lowerMSASplatZExt(), LowerMUL(), llvm::LanaiTargetLowering::LowerMUL(), lowerMUL_LOHI32(), LowerMULH(), llvm::R600TargetLowering::LowerOperation(), llvm::RISCVTargetLowering::LowerOperation(), LowerPARITY(), LowerPredicateLoad(), LowerPredicateStore(), LowerPREFETCH(), llvm::HexagonTargetLowering::LowerPREFETCH(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), llvm::HexagonTargetLowering::LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerRETURNADDR(), lowerRETURNADDR(), LowerReverse_VECTOR_SHUFFLEv16i8_v8i16(), LowerRotate(), LowerSaturatingConditional(), LowerScalarImmediateShift(), LowerScalarVariableShift(), LowerSDIV_v4i16(), LowerSDIV_v4i8(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), llvm::LanaiTargetLowering::LowerSELECT_CC(), LowerSELECT_CC(), llvm::LanaiTargetLowering::LowerSETCC(), llvm::MSP430TargetLowering::LowerSETCC(), LowerSETCCCARRY(), LowerShift(), LowerShiftParts(), llvm::LanaiTargetLowering::LowerSHL_PARTS(), lowerShuffleAsBitBlend(), lowerShuffleAsBitMask(), lowerShuffleAsBlend(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleAsTruncBroadcast(), lowerShuffleAsVTRUNCAndUnpack(), lowerShuffleToEXPAND(), lowerShuffleWithPSHUFB(), LowerSIGN_EXTEND_Mask(), llvm::LanaiTargetLowering::LowerSRL_PARTS(), lowerStoreF128(), LowerSVEIntrinsicEXT(), llvm::VETargetLowering::lowerToVVP(), LowerTruncatei1(), LowerTruncateVecI1(), LowerTruncateVectorStore(), llvm::HexagonTargetLowering::LowerUAddSubO(), LowerUDIV(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), LowerUMULO_SMULO(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), lowerV16I8Shuffle(), lowerV8I16Shuffle(), LowerVecReduce(), LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE_i1(), LowerVECTOR_SHUFFLEv8i8(), LowerVectorAllZero(), LowerVectorCTLZ_AVX512CDI(), LowerVectorCTLZInRegLUT(), LowerVectorCTPOPInRegLUT(), LowerVSETCC(), LowerVSETCCWithSUBUS(), LowerWRITE_REGISTER(), lowerX86CmpEqZeroToCtlzSrl(), LowerXALUO(), LowerZERO_EXTEND_Mask(), llvm::SparcTargetLowering::makeAddress(), matchBSwapHWordOrAndAnd(), memsetStore(), NormalizeBuildVector(), optimizeLogicalImm(), Passv64i1ArgInRegs(), PerformAddcSubcCombine(), PerformAddeSubeCombine(), PerformADDVecReduce(), performANDCombine(), PerformARMBUILD_VECTORCombine(), PerformBFICombine(), llvm::ARMTargetLowering::PerformCMOVCombine(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), performCommonVectorExtendCombine(), performConcatVectorsCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::HexagonTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performDSPShiftCombine(), performExtendCombine(), performExtractVectorEltCombine(), llvm::AMDGPUTargetLowering::performFAbsCombine(), performFDivCombine(), llvm::AMDGPUTargetLowering::performFNegCombine(), performFpToIntCombine(), performGlobalAddressCombine(), llvm::ARMTargetLowering::PerformIntrinsicCombine(), performLDNT1Combine(), PerformLongShiftCombine(), PerformMinMaxCombine(), performMulCombine(), PerformMULCombine(), performORCombine(), PerformORCombineToBFI(), PerformPREDICATE_CASTCombine(), performSetccAddFolding(), PerformShiftCombine(), llvm::AMDGPUTargetLowering::performShlCombine(), performSHLCombine(), PerformSHLSimplify(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), llvm::AMDGPUTargetLowering::performSraCombine(), llvm::AMDGPUTargetLowering::performSrlCombine(), PerformSTORECombine(), PerformSUBCombine(), performSVEAndCombine(), performTBZCombine(), PerformTruncatingStoreCombine(), performUADDVCombine(), PerformVCMPCombine(), PerformVCVTCombine(), PerformVDIVCombine(), PerformVDUPCombine(), performVecReduceAddCombine(), PerformVMOVrhCombine(), PerformVMOVRRDCombine(), PerformXORCombine(), prepareTS1AM(), promoteExtBeforeAdd(), llvm::AArch64TargetLowering::ReconstructShuffle(), recoverFramePointer(), reduceBuildVecToShuffleWithZero(), ReplaceLongIntrinsic(), llvm::SITargetLowering::ReplaceNodeResults(), llvm::AVRTargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), ReplaceREADCYCLECOUNTER(), SaturateWidenedDIVFIX(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), selectGatherScatterAddrMode(), llvm::TargetLowering::ShrinkDemandedConstant(), ShrinkLoadReplaceStoreWithStore(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::ARMTargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::TargetLowering::SimplifyDemandedVectorElts(), simplifyDivRem(), llvm::TargetLowering::SimplifySetCC(), simplifySetCCWithCTPOP(), simplifyShift(), skipExtensionForVectorMULL(), SkipExtensionForVMULL(), llvm::TargetLowering::softenSetCCOperands(), llvm::AMDGPUTargetLowering::split64BitValue(), llvm::AMDGPUTargetLowering::splitBinaryBitConstantOpImpl(), splitInt128(), splitStores(), splitStoreSplat(), llvm::AMDGPUTargetLowering::storeStackInputValue(), llvm::ARMTargetLowering::targetShrinkDemandedConstant(), llvm::RISCVTargetLowering::targetShrinkDemandedConstant(), llvm::X86TargetLowering::targetShrinkDemandedConstant(), TranslateX86CC(), truncateVecElts(), tryAdvSIMDModImm16(), tryAdvSIMDModImm32(), tryAdvSIMDModImm321s(), tryAdvSIMDModImm64(), tryAdvSIMDModImm8(), tryAdvSIMDModImmFP(), tryCombineShiftImm(), tryCombineToEXTR(), tryConvertSVEWideCompare(), tryExtendDUPToExtractHigh(), tryFoldToZero(), tryFormConcatFromShuffle(), TryMULWIDECombine(), tryToFoldExtendOfConstant(), UnpackFromArgumentSlot(), UnrollVectorOverflowOp(), unrollVectorShift(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), llvm::SelectionDAGBuilder::visitSwitchCase(), WidenVector(), and WinDBZCheckDenominator().
getConstantDbgValue()
SDDbgValue * SelectionDAG::getConstantDbgValue (DIVariable * Var, DIExpression * Expr, const Value * C, const DebugLoc & DL, unsigned O)
Creates a constant SDDbgValue node.
Constant.
Definition at line 8404 of file SelectionDAG.cpp.
References assert(), C, DL, llvm::SDDbgInfo::getAlloc(), and llvm::RISCVFenceField::O.
Referenced by llvm::SelectionDAGBuilder::handleDebugValue(), llvm::SelectionDAGBuilder::resolveDanglingDebugInfo(), and llvm::SelectionDAGBuilder::salvageUnresolvedDbgValue().
getConstantFP() [1/3]
SDValue SelectionDAG::getConstantFP (const APFloat & Val, const SDLoc & DL, EVT VT, bool isTarget = false)
Definition at line 1457 of file SelectionDAG.cpp.
References DL, llvm::ConstantFP::get(), getConstantFP(), and getContext().
getConstantFP() [2/3]
SDValue SelectionDAG::getConstantFP (const ConstantFP & V, const SDLoc & DL, EVT VT, bool isTarget = false)
Definition at line 1462 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::ISD::ConstantFP, DL, llvm::EVT::getScalarType(), getSplatBuildVector(), getSplatVector(), getVTList(), llvm::EVT::isFloatingPoint(), llvm::EVT::isScalableVector(), llvm::EVT::isVector(), N, NewSDValueDbgMsg(), llvm::None, and llvm::ISD::TargetConstantFP.
getConstantFP() [3/3]
SDValue SelectionDAG::getConstantFP (double Val, const SDLoc & DL, EVT VT, bool isTarget = false)
Create a ConstantFPSDNode wrapping a constant value.
If VT is a vector type, the constant is splatted into a BUILD_VECTOR.
If only legal types can be produced, this does the necessary transformations (e.g., if the vector element type is illegal). The forms that take a double should only be used for simple constants that can be exactly represented in VT. No checks are made.
Definition at line 1496 of file SelectionDAG.cpp.
References llvm::lltok::APFloat, llvm::MVT::bf16, llvm::APFloat::convert(), DL, EVTToAPFloatSemantics(), llvm::MVT::f128, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, llvm::EVT::getScalarType(), llvm_unreachable, llvm::MVT::ppcf128, and llvm::APFloatBase::rmNearestTiesToEven.
Referenced by combineBitcast(), combineExtractWithShuffle(), combineFneg(), combineFP_ROUND(), combineVSelectWithAllOnesOrZeros(), EltsFromConsecutiveLoads(), expandExp(), expandLog(), ExpandPowI(), foldConstantFPMath(), getConstantFP(), getConstVector(), getF32Constant(), getMemsetStringVal(), getMemsetValue(), llvm::TargetLowering::getNegatedExpression(), getNeutralElement(), getNode(), getShuffleScalarElt(), llvm::TargetLowering::getSqrtInputTest(), llvm::TargetLowering::getSqrtResultForDenormInput(), getTargetConstantFP(), llvm::SelectionDAGBuilder::getValueImpl(), getZeroVector(), LowerFABSorFNEG(), llvm::AMDGPUTargetLowering::LowerFCEIL(), LowerFCOPYSIGN(), llvm::AMDGPUTargetLowering::lowerFEXP(), llvm::AMDGPUTargetLowering::LowerFFLOOR(), llvm::AMDGPUTargetLowering::LowerFLOG(), llvm::AMDGPUTargetLowering::LowerFP64_TO_INT(), LowerFP_TO_FP16(), llvm::AMDGPUTargetLowering::LowerFRINT(), LowerFROUND(), llvm::AMDGPUTargetLowering::LowerFROUND(), lowerShuffleAsBitMask(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), LowerUINT_TO_FP_i32(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), llvm::AMDGPUTargetLowering::performRcpCombine(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::TargetLowering::SimplifyDemandedBits(), simplifyFPBinop(), and visitFMinMax().
getConstantPool() [1/2]
SDValue SelectionDAG::getConstantPool (const Constant * C, EVT VT, MaybeAlign Align = None, int Offs = 0, bool isT = false, unsigned TargetFlags = 0)
Definition at line 1581 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), C, llvm::ISD::ConstantPool, E, llvm::DataLayout::getABITypeAlign(), getDataLayout(), llvm::DataLayout::getPrefTypeAlign(), llvm::Value::getType(), getVTList(), N, NewSDValueDbgMsg(), llvm::None, Offset, shouldOptForSize(), and llvm::ISD::TargetConstantPool.
Referenced by combineTargetShuffle(), getAddressForMemoryInput(), getTargetConstantPool(), lowerBuildVectorAsBroadcast(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_vXi32(), and llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetShuffle().
getConstantPool() [2/2]
SDValue SelectionDAG::getConstantPool (MachineConstantPoolValue * C, EVT VT, MaybeAlign Align = None, int Offs = 0, bool isT = false, unsigned TargetFlags = 0)
Definition at line 1610 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), C, llvm::ISD::ConstantPool, E, getDataLayout(), llvm::DataLayout::getPrefTypeAlign(), llvm::Value::getType(), getVTList(), N, llvm::None, Offset, and llvm::ISD::TargetConstantPool.
getContext()
LLVMContext* llvm::SelectionDAG::getContext () const inline
Definition at line 454 of file SelectionDAG.h.
References Context.
Referenced by AddCombineVUZPToVPADDL(), llvm::RegsForValue::AddInlineAsmOperands(), addShuffleForVecExtend(), adjustLoadValueTypeImpl(), llvm::TargetLowering::BuildUDIV(), canFoldInAddressingMode(), CollectOpsToWiden(), combineAnd(), combineArithReduction(), combineBasicSADPattern(), combineBitcastToBoolVector(), combineBitcastvxi1(), combineConcatVectorOfCasts(), combineConcatVectorOfScalars(), combineConcatVectorOps(), combineEXTEND_VECTOR_INREG(), combineExtractVectorElt(), combineFMinNumFMaxNum(), combineFP_EXTEND(), combineFP_ROUND(), combineGatherScatter(), combineLoad(), combineMinNumMaxNum(), combineOr(), combinePredicateReduction(), combineSelect(), combineShiftAnd1ToBitTest(), combineShuffleToVectorExtend(), combineSIntToFP(), combineStore(), combineTargetShuffle(), combineToExtendBoolVectorInReg(), combineToFPTruncExtElt(), combineTruncateWithSat(), combineUIntToFP(), CombineVMOVDRRCandidateWithVecOp(), combineVSelectWithAllOnesOrZeros(), combinevXi1ConstantToInteger(), concatSubVectors(), constructRetValue(), CreateStackTemporary(), detectAVGPattern(), detectPMADDUBSW(), earlyExpandDIVFIX(), EltsFromConsecutiveLoads(), llvm::SelectionDAGBuilder::EmitBranchForMergedCondition(), emitNonHSAIntrinsicError(), emitRemovedIntrinsicError(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), errorUnsupported(), expandDivFix(), llvm::TargetLowering::expandFixedPointDiv(), llvm::TargetLowering::expandMUL_LOHI(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), extractSubVector(), fail(), FindMemType(), FoldConstantArithmetic(), FoldConstantVectorArithmetic(), foldShuffleOfConcatUndefs(), foldXorTruncShiftIntoCmp(), getConstant(), getConstantFP(), getCopyFromParts(), getCopyFromPartsVector(), llvm::SelectionDAGBuilder::getCopyFromRegs(), llvm::RegsForValue::getCopyFromRegs(), getCopyToParts(), getCopyToPartsVector(), llvm::RegsForValue::getCopyToRegs(), GetDependentSplitDestVTs(), getEVTAlign(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), getMemsetStringVal(), getMemsetValue(), getPTest(), getReducedAlign(), GetRegistersForValue(), GetSplitDestVTs(), llvm::AMDGPUTargetLowering::getSplitDestVTs(), llvm::TargetLowering::getSqrtInputTest(), getUniformBase(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::TargetLowering::IncrementMemoryAddress(), llvm::SelectionDAGBuilder::init(), llvm::SITargetLowering::isEligibleForTailCallOptimization(), llvm::TargetLoweringBase::isLoadBitCastBeneficial(), llvm::AMDGPUTargetLowering::isLoadBitCastBeneficial(), LowerADDSAT_SUBSAT(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), LowerAsSplatVectorLoad(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), lowerBuildVectorAsBroadcast(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SITargetLowering::LowerCallResult(), llvm::HexagonTargetLowering::LowerCallResult(), llvm::SelectionDAGBuilder::LowerCallSiteWithDeoptBundleImpl(), llvm::AMDGPUTargetLowering::LowerCTLZ_CTTZ(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::AMDGPUTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::SparcTargetLowering::LowerF128_LibCallArg(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SparcTargetLowering::LowerF128Op(), llvm::AMDGPUTargetLowering::LowerFCEIL(), lowerFCMPIntrinsic(), llvm::AMDGPUTargetLowering::LowerFFLOOR(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::AMDGPUTargetLowering::LowerFRINT(), llvm::AMDGPUTargetLowering::LowerFROUND(), LowerFSINCOS(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), lowerICMPIntrinsic(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP32(), LowerMSCATTER(), llvm::RISCVTargetLowering::LowerOperation(), LowerPredicateLoad(), LowerPredicateStore(), llvm::SelectionDAGBuilder::lowerRangeToAssertZExt(), llvm::SITargetLowering::LowerReturn(), llvm::HexagonTargetLowering::LowerReturn(), llvm::RISCVTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::VETargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), llvm::SelectionDAGBuilder::LowerStatepoint(), LowerStore(), LowerSVEIntrinsicEXT(), llvm::TargetLowering::LowerToTLSEmulatedModel(), LowerToTLSExecModel(), llvm::VETargetLowering::lowerToVVP(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_vXi32(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), LowerVECTOR_SHUFFLE(), LowerVectorAllZero(), LowerVSETCC(), matchBinOpReduction(), matchPMADDWD(), matchPMADDWD_2(), narrowExtractedVectorBinOp(), PerformARMBUILD_VECTORCombine(), PerformBUILD_VECTORCombine(), llvm::AArch64TargetLowering::PerformDAGCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performExtendCombine(), PerformInsertEltCombine(), llvm::AMDGPUTargetLowering::performLoadCombine(), performSelectCombine(), performSignExtendInRegCombine(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), llvm::AMDGPUTargetLowering::performStoreCombine(), PerformSTORECombine(), llvm::AMDGPUTargetLowering::performTruncateCombine(), PerformTruncatingStoreCombine(), promoteToConstantPool(), llvm::AArch64TargetLowering::ReconstructShuffle(), reduceMaskedLoadToScalarLoad(), reduceMaskedStoreToScalarStore(), reduceVMULWidth(), ReplaceLoadVector(), llvm::SITargetLowering::ReplaceNodeResults(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), llvm::TargetLowering::ShrinkDemandedOp(), ShrinkLoadReplaceStoreWithStore(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), llvm::TargetLowering::SimplifySetCC(), llvm::TargetLowering::softenSetCCOperands(), splitStores(), llvm::X86TargetLowering::targetShrinkDemandedConstant(), truncateVectorWithPACK(), tryFormConcatFromShuffle(), UnrollVectorOp(), UnrollVectorOverflowOp(), llvm::TargetLowering::verifyReturnAddressArgumentIsConstant(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), llvm::SelectionDAGBuilder::visitSwitchCase(), llvm::AMDGPUTargetLowering::WidenOrSplitVectorLoad(), widenVec(), and WidenVector().
getCopyFromReg() [1/2]
SDValue llvm::SelectionDAG::getCopyFromReg (SDValue Chain, const SDLoc & dl, unsigned Reg, EVT VT) inline
Definition at line 768 of file SelectionDAG.h.
References llvm::ISD::CopyFromReg, getNode(), getRegister(), getVTList(), llvm::MVT::Other, and Reg.
Referenced by llvm::AMDGPUTargetLowering::CreateLiveInRegister(), expandIntrinsicWChainHelper(), llvm::RegsForValue::getCopyFromRegs(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), getFRAMEADDR(), getReadTimeStampCounter(), GetTLSADDR(), getv64i1Argument(), llvm::X86TargetLowering::LowerAsmOutputForConstraint(), lowerBALLOTIntrinsic(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), llvm::SITargetLowering::LowerCallResult(), llvm::HexagonTargetLowering::LowerCallResult(), LowerCallResult(), LowerCMP_SWAP(), llvm::LanaiTargetLowering::LowerDYNAMIC_STACKALLOC(), LowerDYNAMIC_STACKALLOC(), llvm::SITargetLowering::lowerDYNAMIC_STACKALLOCImpl(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::HexagonTargetLowering::LowerFRAMEADDR(), llvm::LanaiTargetLowering::LowerFRAMEADDR(), llvm::MSP430TargetLowering::LowerFRAMEADDR(), lowerFRAMEADDR(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::HexagonTargetLowering::LowerRETURNADDR(), llvm::LanaiTargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerSETCC(), llvm::VETargetLowering::lowerToTLSGeneralDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSInitialExecModel(), llvm::HexagonTargetLowering::LowerToTLSLocalExecModel(), performDivRemCombine(), llvm::SparcTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), replaceZeroVectorStore(), llvm::HexagonDAGToDAGISel::SelectFrameIndex(), llvm::AVRDAGToDAGISel::SelectInlineAsmMemoryOperand(), unpackF64OnRV32DSoftABI(), unpackFromRegLoc(), llvm::SelectionDAGBuilder::visitBitTestCase(), and llvm::SelectionDAGBuilder::visitJumpTable().
getCopyFromReg() [2/2]
SDValue llvm::SelectionDAG::getCopyFromReg (SDValue Chain, const SDLoc & dl, unsigned Reg, EVT VT, SDValue Glue) inline
Definition at line 777 of file SelectionDAG.h.
References llvm::ISD::CopyFromReg, llvm::SDValue::getNode(), getNode(), getRegister(), getVTList(), llvm::MVT::Glue, llvm::makeArrayRef(), llvm::MVT::Other, and Reg.
getCopyToReg() [1/3]
SDValue llvm::SelectionDAG::getCopyToReg (SDValue Chain, const SDLoc & dl, SDValue Reg, SDValue N, SDValue Glue) inline
Definition at line 760 of file SelectionDAG.h.
References llvm::ISD::CopyToReg, llvm::SDValue::getNode(), getNode(), getVTList(), llvm::MVT::Glue, llvm::makeArrayRef(), N, llvm::MVT::Other, and Reg.
getCopyToReg() [2/3]
SDValue llvm::SelectionDAG::getCopyToReg (SDValue Chain, const SDLoc & dl, unsigned Reg, SDValue N) inline
Definition at line 742 of file SelectionDAG.h.
References llvm::ISD::CopyToReg, getNode(), getRegister(), N, llvm::MVT::Other, and Reg.
Referenced by emitRepmovs(), expandIntrinsicWChainHelper(), llvm::RegsForValue::getCopyToRegs(), llvm::MipsTargetLowering::getOpndList(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::HexagonTargetLowering::LowerCallResult(), LowerCMP_SWAP(), llvm::LanaiTargetLowering::LowerDYNAMIC_STACKALLOC(), LowerDYNAMIC_STACKALLOC(), llvm::SITargetLowering::lowerDYNAMIC_STACKALLOCImpl(), llvm::HexagonTargetLowering::LowerEH_RETURN(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::SITargetLowering::LowerReturn(), llvm::HexagonTargetLowering::LowerReturn(), llvm::RISCVTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::VETargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), LowerSETCCCARRY(), llvm::HexagonTargetLowering::LowerToTLSGeneralDynamicModel(), LowerToTLSGeneralDynamicModel32(), LowerToTLSLocalDynamicModel(), llvm::ARMTargetLowering::PerformCMOVCombine(), prepareDescriptorIndirectCall(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::AVRDAGToDAGISel::SelectInlineAsmMemoryOperand(), llvm::SelectionDAGBuilder::visitBitTestHeader(), and llvm::SelectionDAGBuilder::visitJumpTableHeader().
getCopyToReg() [3/3]
SDValue llvm::SelectionDAG::getCopyToReg (SDValue Chain, const SDLoc & dl, unsigned Reg, SDValue N, SDValue Glue) inline
Definition at line 751 of file SelectionDAG.h.
References llvm::ISD::CopyToReg, llvm::SDValue::getNode(), getNode(), getRegister(), getVTList(), llvm::MVT::Glue, llvm::makeArrayRef(), N, llvm::MVT::Other, and Reg.
getDataLayout()
const DataLayout& llvm::SelectionDAG::getDataLayout () const inline
Definition at line 447 of file SelectionDAG.h.
References llvm::MachineFunction::getDataLayout().
Referenced by AddCombineBUILD_VECTORToVPADDL(), AddCombineToVPADD(), AddCombineVUZPToVPADDL(), addShuffleForVecExtend(), llvm::SparcTargetLowering::bitcastConstantFPToInt(), BuildExactSDIV(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), canFoldInAddressingMode(), combineBVOfVecSExt(), combineConcatVectorOps(), combineFMinNumFMaxNum(), combineLoad(), combinePredicateReduction(), combineShiftAnd1ToBitTest(), combineShuffleToVectorExtend(), combineStore(), combineTargetShuffle(), combineTruncationShuffle(), combineVSelectWithAllOnesOrZeros(), computeKnownBits(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), ComputeNumSignBits(), llvm::SelectionDAGBuilder::CopyValueToVirtualRegister(), createGPRPairNode(), createMMXBuildVector(), CreateStackTemporary(), EltsFromConsecutiveLoads(), llvm::X86TargetLowering::emitStackGuardXorFP(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::TargetLowering::expandABS(), expandDivFix(), llvm::TargetLowering::expandFixedPointDiv(), llvm::TargetLowering::expandMUL_LOHI(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), foldXorTruncShiftIntoCmp(), getAddressForMemoryInput(), getAVX2GatherNode(), getConstant(), getConstantPool(), getCopyFromParts(), llvm::SelectionDAGBuilder::getCopyFromRegs(), getCopyToParts(), getCppExceptionSymNode(), getEVTAlign(), GetExponent(), llvm::SelectionDAGBuilder::getFrameIndexTy(), getGatherNode(), getGlobalAddress(), llvm::MipsDAGToDAGISel::getGlobalBaseReg(), getIntPtrConstant(), getLifetimeNode(), getLimitedPrecisionExp2(), getLoadStackGuard(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), getMemsetStringVal(), getNode(), llvm::TargetLowering::getPICJumpTableRelocBase(), llvm::PPCTargetLowering::getPICJumpTableRelocBase(), llvm::VETargetLowering::getPICJumpTableRelocBase(), llvm::X86TargetLowering::getPICJumpTableRelocBase(), getPPCf128HiElementSelector(), getPrefetchNode(), getReducedAlign(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), getScatterNode(), getShiftAmountConstant(), getShiftAmountOperand(), getShiftAmountTyForConstant(), llvm::PPC::getSplatIdxForPPCMnemonics(), llvm::TargetLowering::getSqrtInputTest(), getSymbolFunctionGlobalAddress(), getUniformBase(), llvm::SelectionDAGBuilder::getValueImpl(), getVectorIdxConstant(), llvm::SelectionDAGBuilder::handleDebugValue(), InferPtrAlign(), llvm::SelectionDAGBuilder::init(), isBLACompatibleAddress(), isExtendedBUILD_VECTOR(), llvm::TargetLoweringBase::isLoadBitCastBeneficial(), llvm::AMDGPUTargetLowering::isLoadBitCastBeneficial(), IsPredicateKnownToFail(), isVMOVModifiedImm(), llvm::PPC::isVMRGEOShuffleMask(), llvm::PPC::isVMRGHShuffleMask(), llvm::PPC::isVMRGLShuffleMask(), llvm::PPC::isVPKUDUMShuffleMask(), llvm::PPC::isVPKUHUMShuffleMask(), llvm::PPC::isVPKUWUMShuffleMask(), llvm::PPC::isVSLDOIShuffleMask(), LowerADDSAT_SUBSAT(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), llvm::HexagonTargetLowering::LowerBlockAddress(), llvm::MSP430TargetLowering::LowerBlockAddress(), lowerBuildVectorAsBroadcast(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::LanaiTargetLowering::LowerConstantPool(), llvm::AMDGPUTargetLowering::LowerCTLZ_CTTZ(), LowerCTPOP(), llvm::SelectionDAGBuilder::LowerDeoptimizeCall(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::HexagonTargetLowering::LowerEH_RETURN(), llvm::MSP430TargetLowering::LowerExternalSymbol(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SparcTargetLowering::LowerF128Op(), LowerF64Op(), llvm::AMDGPUTargetLowering::LowerFCEIL(), llvm::AMDGPUTargetLowering::LowerFFLOOR(), LowerFNEGorFABS(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::AMDGPUTargetLowering::LowerFRINT(), llvm::AMDGPUTargetLowering::LowerFROUND(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), llvm::HexagonTargetLowering::LowerGLOBAL_OFFSET_TABLE(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::HexagonTargetLowering::LowerGLOBALADDRESS(), llvm::LanaiTargetLowering::LowerGlobalAddress(), llvm::MSP430TargetLowering::LowerGlobalAddress(), llvm::NVPTXTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP32(), llvm::SparcTargetLowering::LowerINTRINSIC_WO_CHAIN(), llvm::LanaiTargetLowering::LowerJumpTable(), llvm::MSP430TargetLowering::LowerJumpTable(), LowerMemOpCallTo(), llvm::R600TargetLowering::LowerOperation(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::MSP430TargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), llvm::SelectionDAGBuilder::LowerStatepoint(), LowerSTORE(), llvm::TargetLowering::LowerToTLSEmulatedModel(), llvm::HexagonTargetLowering::LowerToTLSGeneralDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSInitialExecModel(), llvm::HexagonTargetLowering::LowerToTLSLocalExecModel(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_vXi32(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), LowerVASTART(), llvm::HexagonTargetLowering::LowerVASTART(), llvm::LanaiTargetLowering::LowerVASTART(), llvm::MSP430TargetLowering::LowerVASTART(), llvm::VETargetLowering::lowerVASTART(), llvm::SparcTargetLowering::makeAddress(), narrowExtractedVectorLoad(), PerformBITCASTCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performMULCombine(), PerformSTORECombine(), llvm::AMDGPUTargetLowering::performTruncateCombine(), PerformTruncatingStoreCombine(), PerformVMOVRRDCombine(), promoteToConstantPool(), recoverFramePointer(), ReplaceCMP_SWAP_128Results(), ReplaceCMP_SWAP_64Results(), ReplaceLoadVector(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), llvm::AVRDAGToDAGISel::SelectAddr(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::AVRDAGToDAGISel::selectIndexedLoad(), llvm::AVRDAGToDAGISel::SelectInlineAsmMemoryOperand(), ShrinkLoadReplaceStoreWithStore(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::TargetLowering::SimplifyMultipleUseDemandedBits(), llvm::TargetLowering::SimplifySetCC(), SkipExtensionForVMULL(), llvm::TargetLowering::softenSetCCOperands(), transformCallee(), unpackFromMemLoc(), UnrollVectorOverflowOp(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTable(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), llvm::SelectionDAGBuilder::visitSPDescriptorParent(), llvm::SelectionDAGBuilder::visitSwitchCase(), and llvm::AMDGPUTargetLowering::WidenOrSplitVectorLoad().
getDbgLabel()
SDDbgLabel * SelectionDAG::getDbgLabel (DILabel * Label, const DebugLoc & DL, unsigned O)
Creates a SDDbgLabel node.
Definition at line 8538 of file SelectionDAG.cpp.
References assert(), DL, llvm::SDDbgInfo::getAlloc(), and llvm::RISCVFenceField::O.
getDbgValue()
SDDbgValue * SelectionDAG::getDbgValue (DIVariable * Var, DIExpression * Expr, SDNode * N, unsigned R, bool IsIndirect, const DebugLoc & DL, unsigned O)
Creates a SDDbgValue node.
getDbgValue - Creates a SDDbgValue node.
SDNode
Definition at line 8394 of file SelectionDAG.cpp.
References assert(), DL, llvm::SDDbgInfo::getAlloc(), N, and llvm::RISCVFenceField::O.
Referenced by salvageDebugInfo(), and transferDbgValues().
GetDbgValues()
ArrayRef<SDDbgValue*> llvm::SelectionDAG::GetDbgValues (const SDNode * SD) const inline
Get the debug values which reference the given SDNode.
Definition at line 1638 of file SelectionDAG.h.
References llvm::SDDbgInfo::getSDDbgValues().
Referenced by ProcessSDDbgValues(), salvageDebugInfo(), and transferDbgValues().
GetDemandedBits() [1/2]
SDValue SelectionDAG::GetDemandedBits (SDValue V, const APInt & DemandedBits)
See if the specified operand can be simplified with the knowledge that only the bits specified by DemandedBits are used.
If so, return the simpler operand, otherwise return a null SDValue.
(This exists alongside SimplifyDemandedBits because GetDemandedBits can simplify nodes with multiple uses more aggressively.)
TODO: really we should be making this into the DAG equivalent of SimplifyMultipleUseDemandedBits and not generate any new nodes.
Definition at line 2326 of file SelectionDAG.cpp.
References llvm::APInt::getAllOnesValue(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::EVT::isScalableVector(), and llvm::EVT::isVector().
Referenced by GetDemandedBits().
GetDemandedBits() [2/2]
SDValue SelectionDAG::GetDemandedBits (SDValue V, const APInt & DemandedBits, const APInt & DemandedElts)
See if the specified operand can be simplified with the knowledge that only the bits specified by DemandedBits are used in the elements specified by DemandedElts.
If so, return the simpler operand, otherwise return a null SDValue.
(This exists alongside SimplifyDemandedBits because GetDemandedBits can simplify nodes with multiple uses more aggressively.)
TODO: really we should be making this into the DAG equivalent of SimplifyMultipleUseDemandedBits and not generate any new nodes.
Definition at line 2343 of file SelectionDAG.cpp.
References llvm::ISD::Constant, getConstant(), GetDemandedBits(), llvm::SDValue::getNode(), getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::hasOneUse(), llvm::TargetLowering::SimplifyMultipleUseDemandedBits(), and llvm::ISD::SRL.
getDenormalMode()
DenormalMode llvm::SelectionDAG::getDenormalMode (EVT VT) const inline
Return the current function's default denormal handling kind for the given floating point type.
Definition at line 2011 of file SelectionDAG.h.
References EVTToAPFloatSemantics(), and llvm::MachineFunction::getDenormalMode().
GetDependentSplitDestVTs()
std::pair< EVT, EVT > SelectionDAG::GetDependentSplitDestVTs (const EVT & VT, const EVT & EnvVT, bool * HiIsEmpty) const
Compute the VTs needed for the low/hi parts of a type, dependent on an enveloping VT that has been split into two identical pieces.
GetDependentSplitDestVTs - Compute the VTs needed for the low/hi parts of a type, dependent on an enveloping VT that has been split into two identical pieces.
Sets the HisIsEmpty flag when hi type has zero storage size.
Sets the HiIsEmpty flag when hi type has zero storage size.
Definition at line 9760 of file SelectionDAG.cpp.
References assert(), getContext(), llvm::LinearPolySize< LeafTy >::getKnownMinValue(), llvm::EVT::getVectorElementCount(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorVT(), and llvm::LinearPolySize< LeafTy >::isScalable().
getDivergenceAnalysis()
const LegacyDivergenceAnalysis* llvm::SelectionDAG::getDivergenceAnalysis () const inline
Definition at line 453 of file SelectionDAG.h.
Referenced by llvm::FunctionLoweringInfo::set().
getEHLabel()
SDValue SelectionDAG::getEHLabel (const SDLoc & dl, SDValue Root, MCSymbol * Label)
Definition at line 1939 of file SelectionDAG.cpp.
References llvm::ISD::EH_LABEL, and getLabelNode().
Referenced by llvm::SelectionDAGBuilder::lowerInvokable().
getEntryNode()
SDValue llvm::SelectionDAG::getEntryNode () const inline
Return the token chain corresponding to the entry of the function.
Definition at line 523 of file SelectionDAG.h.
Referenced by llvm::AMDGPUTargetLowering::addTokenForArgument(), clear(), combineTargetShuffle(), llvm::SelectionDAGBuilder::CopyValueToVirtualRegister(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), llvm::AMDGPUTargetLowering::CreateLiveInRegisterRaw(), llvm::MipsTargetLowering::getAddrLocal(), llvm::SelectionDAGBuilder::getCopyFromRegs(), getFLUSHW(), getFRAMEADDR(), getStackArgumentTokenFactor(), llvm::SelectionDAGBuilder::getValueImpl(), HandleMergeInputChains(), llvm::AMDGPUTargetLowering::loadStackInputValue(), lowerBALLOTIntrinsic(), lowerBuildVectorAsBroadcast(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SparcTargetLowering::LowerF128Op(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::HexagonTargetLowering::LowerFRAMEADDR(), llvm::LanaiTargetLowering::LowerFRAMEADDR(), llvm::MSP430TargetLowering::LowerFRAMEADDR(), lowerFRAMEADDR(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::HexagonTargetLowering::LowerRETURNADDR(), llvm::LanaiTargetLowering::LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), lowerRETURNADDR(), llvm::MSP430TargetLowering::LowerSETCC(), LowerSETCCCARRY(), llvm::SelectionDAGBuilder::LowerStatepoint(), LowerToTLSExecModel(), llvm::HexagonTargetLowering::LowerToTLSGeneralDynamicModel(), llvm::VETargetLowering::lowerToTLSGeneralDynamicModel(), LowerToTLSGeneralDynamicModel32(), LowerToTLSGeneralDynamicModel64(), LowerToTLSGeneralDynamicModelX32(), llvm::HexagonTargetLowering::LowerToTLSInitialExecModel(), LowerToTLSLocalDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSLocalExecModel(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_vXi32(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), llvm::SparcTargetLowering::makeAddress(), llvm::VETargetLowering::makeAddress(), llvm::TargetLowering::makeLibCall(), llvm::ARMTargetLowering::PerformCMOVCombine(), performDivRemCombine(), replaceZeroVectorStore(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::HexagonDAGToDAGISel::SelectFrameIndex(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetShuffle(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getEVTAlign()
Align SelectionDAG::getEVTAlign (EVT MemoryVT) const
Compute the default alignment value for the given type.
Definition at line 1108 of file SelectionDAG.cpp.
References llvm::PointerType::get(), llvm::DataLayout::getABITypeAlign(), getContext(), getDataLayout(), llvm::Type::getInt8Ty(), llvm::EVT::getTypeForEVT(), and llvm::MVT::iPTR.
Referenced by getEVTAlignment(), getLoad(), getMemIntrinsicNode(), getStore(), and getTruncStore().
getEVTAlignment()
unsigned llvm::SelectionDAG::getEVTAlignment (EVT MemoryVT) const inline
Compute the default alignment value for the given type.
FIXME: Remove once transition to Align is over.
Definition at line 1957 of file SelectionDAG.h.
References getEVTAlign(), and llvm::Align::value().
getExternalSymbol()
SDValue SelectionDAG::getExternalSymbol (const char * Sym, EVT VT)
Definition at line 1680 of file SelectionDAG.cpp.
References N.
Referenced by llvm::SelectionDAGBuilder::LowerDeoptimizeCall(), llvm::SparcTargetLowering::LowerF128Compare(), and llvm::SparcTargetLowering::LowerF128Op().
getExtLoad() [1/3]
SDValue SelectionDAG::getExtLoad (ISD::LoadExtType ExtType, const SDLoc & dl, EVT VT, SDValue Chain, SDValue Ptr, EVT MemVT, MachineMemOperand * MMO)
Definition at line 7098 of file SelectionDAG.cpp.
References getLoad(), getUNDEF(), llvm::SDValue::getValueType(), llvm::RegState::Undef, and llvm::ISD::UNINDEXED.
getExtLoad() [2/3]
SDValue SelectionDAG::getExtLoad (ISD::LoadExtType ExtType, const SDLoc & dl, EVT VT, SDValue Chain, SDValue Ptr, MachinePointerInfo PtrInfo, EVT MemVT, MaybeAlign Alignment = MaybeAlign(), MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes())
Definition at line 7087 of file SelectionDAG.cpp.
References getLoad(), getUNDEF(), llvm::SDValue::getValueType(), llvm::RegState::Undef, and llvm::ISD::UNINDEXED.
Referenced by adjustSubwordCmp(), combineEXTEND_VECTOR_INREG(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), getExtLoad(), getMemcpyLoadsAndStores(), LowerPredicateLoad(), PerformVMOVrhCombine(), llvm::SparcTargetLowering::ReplaceNodeResults(), llvm::TargetLowering::scalarizeVectorLoad(), SkipLoadExtensionForVMULL(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), tryToFoldExtOfExtload(), tryToFoldExtOfLoad(), unpackFromMemLoc(), and llvm::AMDGPUTargetLowering::WidenOrSplitVectorLoad().
getExtLoad() [3/3]
SDValue llvm::SelectionDAG::getExtLoad (ISD::LoadExtType ExtType, const SDLoc & dl, EVT VT, SDValue Chain, SDValue Ptr, MachinePointerInfo PtrInfo, EVT MemVT, unsigned Alignment, MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes()) inline
FIXME: Remove once transition to Align is over.
Definition at line 1246 of file SelectionDAG.h.
References getExtLoad().
getFlagInserter()
FlagInserter* llvm::SelectionDAG::getFlagInserter () inline
Definition at line 459 of file SelectionDAG.h.
getFPExtendOrRound()
SDValue SelectionDAG::getFPExtendOrRound (SDValue Op, const SDLoc & DL, EVT VT)
Convert Op, which must be of float type, to the float type VT, by either extending or rounding (by truncation).
Definition at line 1227 of file SelectionDAG.cpp.
References llvm::EVT::bitsGT(), DL, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, getIntPtrConstant(), and getNode().
Referenced by getCopyFromPartsVector(), and LowerUINT_TO_FP_i32().
getFrameIndex()
SDValue SelectionDAG::getFrameIndex (int FI, EVT VT, bool isTarget = false)
Definition at line 1547 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, llvm::ISD::FrameIndex, getVTList(), N, llvm::None, and llvm::ISD::TargetFrameIndex.
Referenced by llvm::X86TargetLowering::BuildFILD(), CalculateTailCallArgDest(), CreateStackTemporary(), EmitTailCallStoreFPAndRetAddr(), EmitTailCallStoreRetAddr(), getAddressForMemoryInput(), getLifetimeNode(), llvm::MSP430TargetLowering::getReturnAddressFrameIndex(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), getTargetFrameIndex(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::AMDGPUTargetLowering::loadStackInputValue(), llvm::SITargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::TargetLowering::LowerCallTo(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerVASTART(), llvm::HexagonTargetLowering::LowerVASTART(), llvm::LanaiTargetLowering::LowerVASTART(), llvm::MSP430TargetLowering::LowerVASTART(), unpackF64OnRV32DSoftABI(), unpackFromMemLoc(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getFrameIndexDbgValue()
SDDbgValue * SelectionDAG::getFrameIndexDbgValue (DIVariable * Var, DIExpression * Expr, unsigned FI, bool IsIndirect, const DebugLoc & DL, unsigned O)
Creates a FrameIndex SDDbgValue node.
FrameIndex.
Definition at line 8414 of file SelectionDAG.cpp.
References assert(), DL, llvm::SDDbgValue::FRAMEIX, llvm::SDDbgInfo::getAlloc(), and llvm::RISCVFenceField::O.
Referenced by llvm::SelectionDAGBuilder::handleDebugValue().
getFreeze()
SDValue SelectionDAG::getFreeze (SDValue V)
Return a freeze using the SDLoc of the value operand.
Definition at line 2041 of file SelectionDAG.cpp.
References llvm::ISD::FREEZE, getNode(), and llvm::SDValue::getValueType().
getGLOBAL_OFFSET_TABLE()
SDValue llvm::SelectionDAG::getGLOBAL_OFFSET_TABLE (EVT VT) inline
Return a GLOBAL_OFFSET_TABLE node. This does not have a useful SDLoc.
Definition at line 963 of file SelectionDAG.h.
References getNode(), and llvm::ISD::GLOBAL_OFFSET_TABLE.
Referenced by llvm::TargetLowering::getPICJumpTableRelocBase(), and llvm::HexagonTargetLowering::LowerGLOBALADDRESS().
getGlobalAddress()
SDValue SelectionDAG::getGlobalAddress (const GlobalValue * GV, const SDLoc & DL, EVT VT, int64_t offset = 0, bool isTargetGA = false, unsigned TargetFlags = 0)
Definition at line 1514 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::BitWidth, DL, E, getDataLayout(), llvm::DataLayout::getPointerTypeSizeInBits(), llvm::GlobalValue::getType(), getVTList(), llvm::ISD::GlobalAddress, llvm::ISD::GlobalTLSAddress, llvm::GlobalValue::isThreadLocal(), N, llvm::None, Offset, llvm::SignExtend64(), llvm::ISD::TargetGlobalAddress, and llvm::ISD::TargetGlobalTLSAddress.
Referenced by FoldSymbolOffset(), llvm::VETargetLowering::getPICJumpTableRelocBase(), getSymbolFunctionGlobalAddress(), getTargetGlobalAddress(), llvm::SelectionDAGBuilder::getValueImpl(), and performGlobalAddressCombine().
getGraphAttrs()
const std::string SelectionDAG::getGraphAttrs (const SDNode * N) const
Get graph attributes for a node.
getGraphAttrs - Get graph attributes for a node.
(eg. "color=red".) Used from getNodeAttributes.
Definition at line 207 of file SelectionDAGPrinter.cpp.
References llvm::errs(), I, N, and NodeGraphAttrs.
Referenced by llvm::DOTGraphTraits< SelectionDAG * >::getNodeAttributes().
getHeapAllocSite()
MDNode* llvm::SelectionDAG::getHeapAllocSite (const SDNode * Node) inline
Return the HeapAllocSite type associated with the SDNode, if it exists.
Definition at line 1990 of file SelectionDAG.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find().
getIndexedLoad()
SDValue SelectionDAG::getIndexedLoad (SDValue OrigLoad, const SDLoc & dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
Definition at line 7106 of file SelectionDAG.cpp.
References assert(), getLoad(), llvm::SDValue::getValueType(), llvm::ARM_MB::LD, llvm::MachineMemOperand::MODereferenceable, llvm::MachineMemOperand::MOInvariant, and Offset.
getIndexedMaskedLoad()
SDValue SelectionDAG::getIndexedMaskedLoad (SDValue OrigLoad, const SDLoc & dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
Definition at line 7299 of file SelectionDAG.cpp.
References assert(), getMaskedLoad(), llvm::SDValue::getValueType(), llvm::ARM_MB::LD, and Offset.
getIndexedMaskedStore()
SDValue SelectionDAG::getIndexedMaskedStore (SDValue OrigStore, const SDLoc & dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
Definition at line 7347 of file SelectionDAG.cpp.
References assert(), getMaskedStore(), Offset, and llvm::ARM_MB::ST.
getIndexedStore()
SDValue SelectionDAG::getIndexedStore (SDValue OrigStore, const SDLoc & dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
Definition at line 7237 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), E, llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), llvm::SDValue::getValueType(), getVTList(), N, NewSDValueDbgMsg(), Offset, llvm::MVT::Other, llvm::ARM_MB::ST, and llvm::ISD::STORE.
getIntPtrConstant()
SDValue SelectionDAG::getIntPtrConstant (uint64_t Val, const SDLoc & DL, bool isTarget = false)
Definition at line 1440 of file SelectionDAG.cpp.
References DL, getConstant(), getDataLayout(), and llvm::TargetLoweringBase::getPointerTy().
Referenced by buildCallOperands(), buildFromShuffleMostly(), combineArithReduction(), combineBitcast(), combineBitcastToBoolVector(), combineBVZEXTLOAD(), combineCompareEqual(), combineConcatVectorOps(), combineExtractWithShuffle(), combineFP16_TO_FP(), combineFP_EXTEND(), combineFP_ROUND(), combineInsertSubvector(), combineMinMaxReduction(), combineSelect(), combineTargetShuffle(), combineTruncateWithSat(), CompactSwizzlableVector(), CreateCopyOfByValArgument(), detectAVGPattern(), EltsFromConsecutiveLoads(), emitConstantSizeRepmov(), emitRepmovsB(), ExtendToType(), ExtractBitFromMaskVector(), extractSubVector(), getCALLSEQ_START(), getCopyToParts(), getFPExtendOrRound(), getFRAMEADDR(), getMaskNode(), getParamsForOneTrueMaskedElt(), getScalarMaskingNode(), getShuffleHalfVectors(), getStrictFPExtendOrRound(), insert1BitVector(), insertSubVector(), lower1BitShuffle(), lower1BitShuffleAsKSHIFTR(), lowerAddSubToHorizontalOp(), LowerAVXCONCAT_VECTORS(), LowerBITCAST(), LowerBITREVERSE_XOP(), LowerBUILD_VECTORvXi1(), LowerBuildVectorAsInsert(), LowerBuildVectorv16i8(), LowerBuildVectorv4x32(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), LowerCONCAT_VECTORS(), LowerCONCAT_VECTORS_i1(), LowerCONCAT_VECTORSvXi1(), llvm::SITargetLowering::lowerDYNAMIC_STACKALLOCImpl(), llvm::HexagonTargetLowering::LowerEH_RETURN(), LowerEXTRACT_SUBVECTOR(), LowerFABSorFNEG(), LowerFCOPYSIGN(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), LowerFP16_TO_FP(), LowerFP_TO_FP16(), lowerFPToIntToFP(), llvm::LanaiTargetLowering::LowerFRAMEADDR(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), lowerI128ToGR128(), LowerI64IntToFP_AVX512DQ(), lowerINT_TO_FP_vXi64(), LowerLoad(), lowerMasksToReg(), LowerMGATHER(), LowerMLOAD(), llvm::LanaiTargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), LowerSDIV(), lowerShuffleAsVTRUNCAndUnpack(), lowerShuffleOfExtractsAsVperm(), lowerShuffleWithUndefHalf(), LowerSIGN_EXTEND_Mask(), llvm::AMDGPUTargetLowering::LowerSINT_TO_FP(), llvm::SelectionDAGBuilder::LowerStatepoint(), LowerStore(), LowerToTLSExecModel(), llvm::VETargetLowering::lowerToTLSGeneralDynamicModel(), LowerUDIV(), llvm::AMDGPUTargetLowering::LowerUINT_TO_FP(), LowerUINT_TO_FP_i32(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), LowerUMULO_SMULO(), lowerV2X128Shuffle(), lowerV4X128Shuffle(), LowerVACOPY(), llvm::HexagonTargetLowering::LowerVACOPY(), llvm::HexagonTargetLowering::LowerVASTART(), llvm::VETargetLowering::lowerVASTART(), LowerVASTART(), LowerZERO_EXTEND_Mask(), llvm::PPCTargetLowering::PerformDAGCombine(), performMADD_MSUBCombine(), PerformTruncatingStoreCombine(), prepareDescriptorIndirectCall(), PrepareTailCall(), ReorganizeVector(), ReplaceLoadVector(), llvm::X86TargetLowering::ReplaceNodeResults(), scalarizeVectorStore(), SplitAndExtendv16i1(), vectorizeExtractedCast(), and widenSubVector().
getJumpTable()
SDValue SelectionDAG::getJumpTable (int JTI, EVT VT, bool isTarget = false, unsigned TargetFlags = 0)
Definition at line 1562 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), E, getVTList(), llvm::ISD::JumpTable, N, llvm::None, and llvm::ISD::TargetJumpTable.
Referenced by getTargetJumpTable(), and llvm::SelectionDAGBuilder::visitJumpTable().
getLabelNode()
SDValue SelectionDAG::getLabelNode (unsigned Opcode, const SDLoc & dl, SDValue Root, MCSymbol * Label)
Definition at line 1944 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), getVTList(), N, and llvm::MVT::Other.
Referenced by getEHLabel().
getLibInfo()
const TargetLibraryInfo& llvm::SelectionDAG::getLibInfo () const inline
Definition at line 451 of file SelectionDAG.h.
getLifetimeNode()
SDValue SelectionDAG::getLifetimeNode (bool IsStart, const SDLoc & dl, SDValue Chain, int FrameIndex, int64_t Size, int64_t Offset = -1)
Creates a LifetimeSDNode that starts (IsStart==true) or ends (IsStart==false) the lifetime of the portion of FrameIndex between offsets Offset and Offset + Size.
Definition at line 6904 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, llvm::ISD::FrameIndex, getDataLayout(), llvm::SDLoc::getDebugLoc(), getFrameIndex(), llvm::SDLoc::getIROrder(), getTargetLoweringInfo(), getVTList(), llvm::ISD::LIFETIME_END, llvm::ISD::LIFETIME_START, N, NewSDValueDbgMsg(), Offset, llvm::MVT::Other, and llvm::Check::Size.
getLoad() [1/7]
SDValue SelectionDAG::getLoad (EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, MachineMemOperand * MMO)
Definition at line 7080 of file SelectionDAG.cpp.
References getLoad(), getUNDEF(), llvm::SDValue::getValueType(), llvm::ISD::NON_EXTLOAD, llvm::RegState::Undef, and llvm::ISD::UNINDEXED.
getLoad() [2/7]
SDValue SelectionDAG::getLoad (EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, MachinePointerInfo PtrInfo, MaybeAlign Alignment = MaybeAlign(), MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes(), const MDNode * Ranges = nullptr)
Loads are not normal binary operators: their result type is not determined by their operands, and they produce a value AND a token chain.
This function will set the MOLoad flag on MMOFlags, but you can set it if you want. The MOStore flag must not be set.
Definition at line 7070 of file SelectionDAG.cpp.
References getUNDEF(), llvm::SDValue::getValueType(), llvm::ISD::NON_EXTLOAD, llvm::RegState::Undef, and llvm::ISD::UNINDEXED.
Referenced by bitcastf32Toi32(), llvm::X86TargetLowering::BuildFILD(), combineBVOfConsecutiveLoads(), combineExtractWithShuffle(), combineLoad(), combineMaskedLoadConstantMask(), combineMOVDQ2Q(), combineStore(), combineTargetShuffle(), EltsFromConsecutiveLoads(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), expandf64Toi32(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), llvm::MipsTargetLowering::getAddrGlobal(), llvm::MipsTargetLowering::getAddrGlobalLargeGOT(), llvm::MipsTargetLowering::getAddrLocal(), getExtLoad(), getFRAMEADDR(), getIndexedLoad(), getLoad(), getMemmoveLoadsAndStores(), llvm::AMDGPUTargetLowering::loadStackInputValue(), LowerAsSplatVectorLoad(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), LowerF128Load(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::HexagonTargetLowering::LowerFRAMEADDR(), llvm::LanaiTargetLowering::LowerFRAMEADDR(), llvm::MSP430TargetLowering::LowerFRAMEADDR(), lowerFRAMEADDR(), LowerLoad(), lowerLoadF128(), lowerMSALoadIntr(), llvm::HexagonTargetLowering::LowerRETURNADDR(), llvm::LanaiTargetLowering::LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), lowerRETURNADDR(), lowerShuffleAsBroadcast(), LowerToTLSExecModel(), llvm::HexagonTargetLowering::LowerToTLSInitialExecModel(), LowerUINT_TO_FP_i64(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), llvm::SparcTargetLowering::makeAddress(), llvm::VETargetLowering::makeAddress(), narrowExtractedVectorLoad(), llvm::PPCTargetLowering::PerformDAGCombine(), performIntToFpCombine(), llvm::AMDGPUTargetLowering::performLoadCombine(), PerformSplittingToWideningLoad(), PerformVMOVhrCombine(), PerformVMOVRRDCombine(), prepareDescriptorIndirectCall(), reduceMaskedLoadToScalarLoad(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetShuffle(), llvm::TargetLowering::SimplifySetCC(), SkipLoadExtensionForVMULL(), unpackF64OnRV32DSoftABI(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getLoad() [3/7]
SDValue llvm::SelectionDAG::getLoad (EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, MachinePointerInfo PtrInfo, unsigned Alignment, MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes(), const MDNode * Ranges = nullptr) inline
FIXME: Remove once transition to Align is over.
Definition at line 1228 of file SelectionDAG.h.
References getLoad().
getLoad() [4/7]
SDValue SelectionDAG::getLoad (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue Offset, EVT MemVT, MachineMemOperand * MMO)
Definition at line 7021 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::EVT::bitsLT(), E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::EVT::getScalarType(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementCount(), getVTList(), Indexed, llvm::EVT::isInteger(), llvm::EVT::isVector(), llvm::ISD::LOAD, N, NewSDValueDbgMsg(), llvm::ISD::NON_EXTLOAD, Offset, llvm::MVT::Other, and llvm::ISD::UNINDEXED.
getLoad() [5/7]
SDValue SelectionDAG::getLoad (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue Offset, MachinePointerInfo PtrInfo, EVT MemVT, Align Alignment, MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes(), const MDNode * Ranges = nullptr)
Definition at line 6997 of file SelectionDAG.cpp.
References assert(), getLoad(), getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::MemoryLocation::getSizeOrUnknown(), llvm::EVT::getStoreSize(), llvm::SDValue::getValueType(), InferPointerInfo(), llvm::PointerUnion< PTs >::isNull(), llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, Offset, llvm::MVT::Other, llvm::Check::Size, and llvm::MachinePointerInfo::V.
getLoad() [6/7]
SDValue llvm::SelectionDAG::getLoad (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue Offset, MachinePointerInfo PtrInfo, EVT MemVT, MaybeAlign Alignment = MaybeAlign(), MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes(), const MDNode * Ranges = nullptr) inline
Definition at line 1265 of file SelectionDAG.h.
References getEVTAlign(), getLoad(), and Offset.
getLoad() [7/7]
SDValue llvm::SelectionDAG::getLoad (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue Offset, MachinePointerInfo PtrInfo, EVT MemVT, unsigned Alignment, MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes(), const MDNode * Ranges = nullptr) inline
FIXME: Remove once transition to Align is over.
Definition at line 1278 of file SelectionDAG.h.
References getLoad(), and Offset.
getLogicalNOT()
SDValue SelectionDAG::getLogicalNOT (const SDLoc & DL, SDValue Val, EVT VT)
Create a logical NOT operation as (XOR Val, BooleanOne).
Definition at line 1312 of file SelectionDAG.cpp.
References DL, getBoolConstant(), getNode(), and llvm::ISD::XOR.
Referenced by extractBooleanFlip(), llvm::HexagonTargetLowering::LowerAddSubCarry(), and PerformORCombine_i1().
getMachineFunction()
MachineFunction& llvm::SelectionDAG::getMachineFunction () const inline
Definition at line 444 of file SelectionDAG.h.
Referenced by llvm::RegsForValue::AddInlineAsmOperands(), buildCallOperands(), llvm::X86TargetLowering::BuildFILD(), llvm::TargetLowering::BuildSDIVPow2(), CalculateTailCallSPDiff(), llvm::AArch64TargetLowering::canMergeStoresTo(), llvm::X86TargetLowering::canMergeStoresTo(), combineFMA(), combineFMADDSUB(), combineFMinNumFMaxNum(), combineFneg(), combineMul(), combineStore(), combineTargetShuffle(), llvm::BaseIndexOffset::computeAliasing(), computeKnownBits(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), llvm::SITargetLowering::denormalsEnabledForType(), EmitCmp(), emitConstantSizeRepmov(), emitLockedStackOp(), emitNonHSAIntrinsicError(), emitRemovedIntrinsicError(), llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), EmitTailCallStoreFPAndRetAddr(), EmitTailCallStoreRetAddr(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemset(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForSetTag(), EmitUnrolledSetTag(), llvm::BaseIndexOffset::equalBaseIndex(), errorUnsupported(), llvm::X86TargetLowering::expandIndirectJTBranch(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), fail(), llvm::SelectionDAGBuilder::FindMergedConditions(), fixupFuncForFI(), foldFPToIntToFP(), getAddressForMemoryInput(), llvm::MipsTargetLowering::getAddrLocal(), getCppExceptionSymNode(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), getFRAMEADDR(), llvm::MipsTargetLowering::getGlobalReg(), getLoad(), getLoadStackGuard(), getMemcpyLoadsAndStores(), getMemIntrinsicNode(), getMemmoveLoadsAndStores(), getMemsetStores(), llvm::MipsTargetLowering::getOpndList(), llvm::VETargetLowering::getPICJumpTableRelocBase(), GetRegistersForValue(), llvm::MSP430TargetLowering::getReturnAddressFrameIndex(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), getSPDenormModeValue(), llvm::NVPTXTargetLowering::getSqrtEstimate(), getStore(), GetTLSADDR(), getTruncStore(), getv64i1Argument(), hasReturnsTwiceAttr(), InferPointerInfo(), InferPtrAlign(), isConsecutiveLSLoc(), llvm::HexagonTargetLowering::IsEligibleForTailCallOptimization(), llvm::SITargetLowering::isEligibleForTailCallOptimization(), llvm::SITargetLowering::isFMADLegal(), llvm::SITargetLowering::isFPExtFoldable(), llvm::SITargetLowering::isKnownNeverNaNForTargetNode(), llvm::AMDGPUTargetLowering::loadStackInputValue(), LowerAsSplatVectorLoad(), lowerBuildVectorAsBroadcast(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SITargetLowering::LowerCallResult(), llvm::HexagonTargetLowering::LowerCallResult(), llvm::TargetLowering::LowerCallTo(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::AMDGPUTargetLowering::LowerDYNAMIC_STACKALLOC(), LowerDYNAMIC_STACKALLOC(), llvm::SITargetLowering::lowerDYNAMIC_STACKALLOCImpl(), llvm::HexagonTargetLowering::LowerEH_RETURN(), llvm::SparcTargetLowering::LowerF128_LibCallArg(), llvm::SparcTargetLowering::LowerF128Op(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::HexagonTargetLowering::LowerFRAMEADDR(), llvm::LanaiTargetLowering::LowerFRAMEADDR(), llvm::MSP430TargetLowering::LowerFRAMEADDR(), lowerFRAMEADDR(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::HexagonTargetLowering::LowerINLINEASM(), LowerInterruptReturn(), LowerINTRINSIC_W_CHAIN(), llvm::VETargetLowering::lowerINTRINSIC_WO_CHAIN(), llvm::SelectionDAGBuilder::lowerInvokable(), llvm::R600TargetLowering::LowerOperation(), llvm::SITargetLowering::LowerOperation(), llvm::SITargetLowering::LowerReturn(), llvm::HexagonTargetLowering::LowerReturn(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::RISCVTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::VETargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), llvm::HexagonTargetLowering::LowerRETURNADDR(), llvm::LanaiTargetLowering::LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), lowerRETURNADDR(), lowerShuffleAsBroadcast(), LowerToTLSExecModel(), llvm::VETargetLowering::lowerToTLSGeneralDynamicModel(), LowerToTLSLocalDynamicModel(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_vXi32(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), LowerVACOPY(), LowerVASTART(), llvm::HexagonTargetLowering::LowerVASTART(), llvm::LanaiTargetLowering::LowerVASTART(), llvm::MSP430TargetLowering::LowerVASTART(), llvm::VETargetLowering::lowerVASTART(), llvm::SparcTargetLowering::makeAddress(), llvm::VETargetLowering::makeAddress(), MarkEHGuard(), MarkEHRegistrationNode(), narrowExtractedVectorLoad(), PerformADDCombineWithOperands(), performBRCONDCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), promoteToConstantPool(), recoverFramePointer(), reduceVMULWidth(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::TargetLowering::CallLoweringInfo::setLibCallee(), setUsesTOCBasePtr(), llvm::AArch64TargetLowering::shouldExpandShift(), llvm::RISCVTargetLowering::shouldExpandShift(), llvm::X86TargetLowering::shouldExpandShift(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetShuffle(), llvm::TargetLowering::SimplifySetCC(), splitStores(), llvm::AMDGPUTargetLowering::storeStackInputValue(), StoreTailCallArgumentsToStackSlot(), transformCallee(), llvm::X86InstrInfo::unfoldMemoryOperand(), unpackF64OnRV32DSoftABI(), unpackFromMemLoc(), unpackFromRegLoc(), viewGraph(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getMachineNode() [1/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, ArrayRef< EVT > ResultTys, ArrayRef< SDValue > Ops)
Definition at line 8298 of file SelectionDAG.cpp.
References getMachineNode(), and getVTList().
getMachineNode() [2/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT)
These are used for target selectors to create a new node with specified return type(s), MachineInstr opcode, and operands.
getMachineNode - These are used for target selectors to create a new node with specified return type(s), MachineInstr opcode, and operands.
Note that getMachineNode returns the resultant node. If there is already a node of the specified opcode and operands, it returns that node instead of the current one.
Definition at line 8217 of file SelectionDAG.cpp.
References getVTList(), and llvm::None.
Referenced by llvm::SITargetLowering::buildRSRC(), buildSMovImm32(), llvm::VETargetLowering::combineTRUNCATE(), llvm::SITargetLowering::copyToM0(), createGPRPairNode(), createTupleImpl(), llvm::HexagonDAGToDAGISel::DetectUseSxtw(), emitLockedStackOp(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForSetTag(), expandIntrinsicWChainHelper(), extractSubReg(), getLeftShift(), getMachineNode(), getPrefetchNode(), getTargetExtractSubreg(), getTargetInsertSubreg(), insertSubReg(), llvm::HexagonDAGToDAGISel::LoadInstrForLoadIntrinsic(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), llvm::VETargetLowering::lowerATOMIC_FENCE(), LowerBITCAST(), llvm::VETargetLowering::LowerCall(), llvm::VETargetLowering::lowerEXTRACT_VECTOR_ELT(), LowerF128Load(), LowerF128Store(), LowerF64Op(), LowerFNEGorFABS(), llvm::VETargetLowering::LowerFormalArguments(), lowerI128ToGR128(), llvm::VETargetLowering::lowerINSERT_VECTOR_ELT(), lowerLoadF128(), llvm::SystemZTargetLowering::LowerOperationWrapper(), llvm::VETargetLowering::LowerReturn(), lowerStoreF128(), optimizeLogicalImm(), ReplaceBITCASTResults(), ReplaceCMP_SWAP_128Results(), ReplaceCMP_SWAP_64Results(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::HexagonDAGToDAGISel::SelectAddSubCarry(), llvm::HexagonDAGToDAGISel::SelectBrevLdIntrinsic(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::HexagonDAGToDAGISel::SelectConstant(), llvm::HexagonDAGToDAGISel::SelectConstantFP(), llvm::HexagonDAGToDAGISel::SelectD2P(), llvm::HexagonDAGToDAGISel::SelectFrameIndex(), selectI64Imm(), selectI64ImmDirect(), selectImm(), llvm::HexagonDAGToDAGISel::SelectIndexedLoad(), llvm::AVRDAGToDAGISel::selectIndexedLoad(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), llvm::HexagonDAGToDAGISel::SelectNewCircIntrinsic(), llvm::HexagonDAGToDAGISel::SelectP2D(), llvm::HexagonDAGToDAGISel::SelectQ2V(), llvm::HvxSelector::selectRor(), llvm::HexagonDAGToDAGISel::SelectSHL(), llvm::HexagonDAGToDAGISel::SelectV2Q(), llvm::HexagonDAGToDAGISel::SelectVAlign(), llvm::HvxSelector::selectVAlign(), llvm::HexagonDAGToDAGISel::SelectVAlignAddr(), tryBitfieldInsertOpFromOr(), tryBitfieldInsertOpFromOrAndImm(), llvm::X86InstrInfo::unfoldMemoryOperand(), Widen(), and llvm::SITargetLowering::wrapAddr64Rsrc().
getMachineNode() [3/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT, ArrayRef< SDValue > Ops)
Definition at line 8245 of file SelectionDAG.cpp.
References getMachineNode(), and getVTList().
getMachineNode() [4/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT, SDValue Op1)
Definition at line 8223 of file SelectionDAG.cpp.
References getMachineNode(), and getVTList().
getMachineNode() [5/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT, SDValue Op1, SDValue Op2)
Definition at line 8230 of file SelectionDAG.cpp.
References getMachineNode(), and getVTList().
getMachineNode() [6/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT, SDValue Op1, SDValue Op2, SDValue Op3)
Definition at line 8237 of file SelectionDAG.cpp.
References getMachineNode(), and getVTList().
getMachineNode() [7/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT1, EVT VT2, ArrayRef< SDValue > Ops)
Definition at line 8267 of file SelectionDAG.cpp.
References getMachineNode(), and getVTList().
getMachineNode() [8/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT1, EVT VT2, EVT VT3, ArrayRef< SDValue > Ops)
Definition at line 8291 of file SelectionDAG.cpp.
References getMachineNode(), and getVTList().
getMachineNode() [9/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT1, EVT VT2, EVT VT3, SDValue Op1, SDValue Op2)
Definition at line 8274 of file SelectionDAG.cpp.
References getMachineNode(), and getVTList().
getMachineNode() [10/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT1, EVT VT2, EVT VT3, SDValue Op1, SDValue Op2, SDValue Op3)
Definition at line 8282 of file SelectionDAG.cpp.
References getMachineNode(), and getVTList().
getMachineNode() [11/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT1, EVT VT2, SDValue Op1, SDValue Op2)
Definition at line 8251 of file SelectionDAG.cpp.
References getMachineNode(), and getVTList().
getMachineNode() [12/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT1, EVT VT2, SDValue Op1, SDValue Op2, SDValue Op3)
Definition at line 8259 of file SelectionDAG.cpp.
References getMachineNode(), and getVTList().
getMachineNode() [13/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, SDVTList VTs, ArrayRef< SDValue > Ops)
Definition at line 8305 of file SelectionDAG.cpp.
References AddNodeIDNode(), DL, E, llvm::MVT::Glue, N, NewSDValueDbgMsg(), llvm::SDVTList::NumVTs, and llvm::SDVTList::VTs.
getMaskedGather()
SDValue SelectionDAG::getMaskedGather (SDVTList VTs, EVT VT, const SDLoc & dl, ArrayRef< SDValue > Ops, MachineMemOperand * MMO, ISD::MemIndexType IndexType, ISD::LoadExtType ExtTy)
Definition at line 7358 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), E, llvm::MachinePointerInfo::getAddrSpace(), llvm::TargetLowering::getCanonicalIndexType(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::LinearPolySize< ElementCount >::isKnownGE(), llvm::ISD::MGATHER, N, NewSDValueDbgMsg(), and llvm::ArrayRef< T >::size().
Referenced by performMaskedGatherScatterCombine(), and rebuildGatherScatter().
getMaskedLoad()
SDValue SelectionDAG::getMaskedLoad (EVT VT, const SDLoc & dl, SDValue Chain, SDValue Base, SDValue Offset, SDValue Mask, SDValue Src0, EVT MemVT, MachineMemOperand * MMO, ISD::MemIndexedMode AM, ISD::LoadExtType ExtTy, bool IsExpanding = false)
Definition at line 7265 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::SDValue::getValueType(), getVTList(), Indexed, llvm::BitmaskEnumDetail::Mask(), llvm::ISD::MLOAD, N, NewSDValueDbgMsg(), Offset, llvm::MVT::Other, and llvm::ISD::UNINDEXED.
Referenced by combineMaskedLoad(), combineMaskedLoadConstantMask(), getIndexedMaskedLoad(), LowerMLOAD(), performLDNT1Combine(), and tryToFoldExtOfMaskedLoad().
getMaskedScatter()
SDValue SelectionDAG::getMaskedScatter (SDVTList VTs, EVT VT, const SDLoc & dl, ArrayRef< SDValue > Ops, MachineMemOperand * MMO, ISD::MemIndexType IndexType, bool IsTruncating = false)
Definition at line 7405 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), E, llvm::MachinePointerInfo::getAddrSpace(), llvm::TargetLowering::getCanonicalIndexType(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::LinearPolySize< ElementCount >::isKnownGE(), llvm::ISD::MSCATTER, N, NewSDValueDbgMsg(), and llvm::ArrayRef< T >::size().
Referenced by performMaskedGatherScatterCombine(), and rebuildGatherScatter().
getMaskedStore()
SDValue SelectionDAG::getMaskedStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Base, SDValue Offset, SDValue Mask, EVT MemVT, MachineMemOperand * MMO, ISD::MemIndexedMode AM, bool IsTruncating = false, bool IsCompressing = false)
Definition at line 7310 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::SDValue::getValueType(), getVTList(), Indexed, llvm::BitmaskEnumDetail::Mask(), llvm::ISD::MSTORE, N, NewSDValueDbgMsg(), Offset, llvm::MVT::Other, and llvm::ISD::UNINDEXED.
Referenced by combineMaskedStore(), getIndexedMaskedStore(), LowerINTRINSIC_W_CHAIN(), LowerMSTORE(), and performSTNT1Combine().
getMCSymbol()
SDValue SelectionDAG::getMCSymbol (MCSymbol * Sym, EVT VT)
Definition at line 1688 of file SelectionDAG.cpp.
References N.
Referenced by recoverFramePointer(), and transformCallee().
getMDNode()
SDValue SelectionDAG::getMDNode (const MDNode * MD)
Return an MDNodeSDNode which holds an MDNode.
Definition at line 1998 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, getVTList(), llvm::ISD::MDNODE_SDNODE, N, llvm::None, and llvm::MVT::Other.
Referenced by llvm::SelectionDAGBuilder::getValueImpl().
getMemBasePlusOffset() [1/2]
SDValue SelectionDAG::getMemBasePlusOffset (SDValue Base, SDValue Offset, const SDLoc & DL, const SDNodeFlags Flags = SDNodeFlags())
Definition at line 5993 of file SelectionDAG.cpp.
References llvm::ISD::ADD, assert(), DL, getNode(), llvm::SDValue::getValueType(), and Offset.
getMemBasePlusOffset() [2/2]
SDValue SelectionDAG::getMemBasePlusOffset (SDValue Base, TypeSize Offset, const SDLoc & DL, const SDNodeFlags Flags = SDNodeFlags())
Returns sum of the base pointer and offset.
Unlike getObjectPtrOffset this does not set NoUnsignedWrap by default.
Definition at line 5977 of file SelectionDAG.cpp.
References DL, getConstant(), llvm::TypeSize::getFixedSize(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), getVScale(), Index, and Offset.
Referenced by combineLoad(), combineStore(), combineTargetShuffle(), EmitUnrolledSetTag(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), getObjectPtrOffset(), getParamsForOneTrueMaskedElt(), llvm::TargetLowering::getVectorElementPointer(), lowerShuffleAsBroadcast(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), narrowExtractedVectorLoad(), scalarizeVectorStore(), ShrinkLoadReplaceStoreWithStore(), llvm::TargetLowering::SimplifySetCC(), and splitVectorStore().
getMemcpy()
SDValue SelectionDAG::getMemcpy (SDValue Chain, const SDLoc & dl, SDValue Dst, SDValue Src, SDValue Size, Align Alignment, bool isVol, bool AlwaysInline, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo)
Definition at line 6448 of file SelectionDAG.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), checkAddrSpaceIsValidForLibcall(), llvm::SelectionDAGTargetInfo::EmitTargetCodeForMemcpy(), llvm::MachinePointerInfo::getAddrSpace(), getMemcpyLoadsAndStores(), llvm::ConstantSDNode::getZExtValue(), llvm::ConstantSDNode::isNullValue(), and llvm::Check::Size.
Referenced by CreateCopyOfByValArgument(), emitConstantSizeRepmov(), LLVM_ATTRIBUTE_DEPRECATED(), llvm::SITargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), LowerVACOPY(), and llvm::HexagonTargetLowering::LowerVACOPY().
getMemIntrinsicNode() [1/3]
SDValue SelectionDAG::getMemIntrinsicNode (unsigned Opcode, const SDLoc & dl, SDVTList VTList, ArrayRef< SDValue > Ops, EVT MemVT, MachineMemOperand * MMO)
Definition at line 6863 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), E, llvm::ISD::FIRST_TARGET_MEMORY_OPCODE, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::MVT::Glue, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::max(), N, NewSDValueDbgMsg(), llvm::SDVTList::NumVTs, llvm::ISD::PREFETCH, and llvm::SDVTList::VTs.
getMemIntrinsicNode() [2/3]
SDValue SelectionDAG::getMemIntrinsicNode (unsigned Opcode, const SDLoc & dl, SDVTList VTList, ArrayRef< SDValue > Ops, EVT MemVT, MachinePointerInfo PtrInfo, Align Alignment, MachineMemOperand::Flags Flags = MachineMemOperand::MOLoad | MachineMemOperand::MOStore, uint64_t Size = 0, const AAMDNodes & AAInfo = AAMDNodes())
Creates a MemIntrinsicNode that may produce a result and takes a list of operands.
Opcode may be INTRINSIC_VOID, INTRINSIC_W_CHAIN, or a target-specific opcode with a value not less than FIRST_TARGET_MEMORY_OPCODE.
Definition at line 6847 of file SelectionDAG.cpp.
References getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::EVT::getStoreSize(), llvm::EVT::isScalableVector(), llvm::Check::Size, and llvm::MemoryLocation::UnknownSize.
Referenced by llvm::X86TargetLowering::BuildFILD(), CombineBaseUpdate(), combineBitcast(), combineBVZEXTLOAD(), combineConcatVectorOps(), combineInsertSubvector(), combineTargetShuffle(), CombineVLDDUP(), createLoadLR(), createStoreLR(), EltsFromConsecutiveLoads(), EmitMaskedTruncSStore(), EmitTruncSStore(), EmitUnrolledSetTag(), llvm::PPCTargetLowering::expandVSXLoadForLE(), llvm::PPCTargetLowering::expandVSXStoreForLE(), getAVX2GatherNode(), getGatherNode(), getMemIntrinsicNode(), getScatterNode(), LLVM_ATTRIBUTE_DEPRECATED(), lowerAtomicArithWithLOCK(), lowerBuildVectorAsBroadcast(), llvm::NVPTXTargetLowering::LowerCall(), LowerCMP_SWAP(), LowerINTRINSIC_W_CHAIN(), LowerMGATHER(), LowerMSCATTER(), llvm::SystemZTargetLowering::LowerOperationWrapper(), llvm::NVPTXTargetLowering::LowerReturn(), lowerShuffleAsBroadcast(), LowerStore(), LowerSTORE(), lowerUINT_TO_FP_vXi32(), narrowLoadToVZLoad(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformMVEVLDCombine(), performNEONPostLDSTCombine(), performPostLD1Combine(), PerformVDUPCombine(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::X86TargetLowering::ReplaceNodeResults(), and llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode().
getMemIntrinsicNode() [3/3]
SDValue llvm::SelectionDAG::getMemIntrinsicNode (unsigned Opcode, const SDLoc & dl, SDVTList VTList, ArrayRef< SDValue > Ops, EVT MemVT, MachinePointerInfo PtrInfo, MaybeAlign Alignment = None, MachineMemOperand::Flags Flags = MachineMemOperand::MOLoad | MachineMemOperand::MOStore, uint64_t Size = 0, const AAMDNodes & AAInfo = AAMDNodes()) inline
Definition at line 1171 of file SelectionDAG.h.
References getEVTAlign(), getMemIntrinsicNode(), and llvm::Check::Size.
getMemmove()
SDValue SelectionDAG::getMemmove (SDValue Chain, const SDLoc & dl, SDValue Dst, SDValue Src, SDValue Size, Align Alignment, bool isVol, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo)
Definition at line 6562 of file SelectionDAG.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, checkAddrSpaceIsValidForLibcall(), llvm::SelectionDAGTargetInfo::EmitTargetCodeForMemmove(), llvm::MachinePointerInfo::getAddrSpace(), getMemmoveLoadsAndStores(), llvm::ConstantSDNode::getZExtValue(), llvm::ConstantSDNode::isNullValue(), and llvm::Check::Size.
Referenced by LLVM_ATTRIBUTE_DEPRECATED().
getMemset()
SDValue SelectionDAG::getMemset (SDValue Chain, const SDLoc & dl, SDValue Dst, SDValue Src, SDValue Size, Align Alignment, bool isVol, bool isTailCall, MachinePointerInfo DstPtrInfo)
Definition at line 6664 of file SelectionDAG.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, checkAddrSpaceIsValidForLibcall(), llvm::SelectionDAGTargetInfo::EmitTargetCodeForMemset(), llvm::MachinePointerInfo::getAddrSpace(), getMemsetStores(), llvm::ConstantSDNode::getZExtValue(), llvm::ConstantSDNode::isNullValue(), and llvm::Check::Size.
Referenced by LLVM_ATTRIBUTE_DEPRECATED().
getMergeValues()
SDValue SelectionDAG::getMergeValues (ArrayRef< SDValue > Ops, const SDLoc & dl)
Create a MERGE_VALUES node from the given operands.
getMergeValues - Create a MERGE_VALUES node from the given operands.
Definition at line 6836 of file SelectionDAG.cpp.
References getNode(), getVTList(), llvm::ISD::MERGE_VALUES, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorImpl< T >::reserve(), and llvm::ArrayRef< T >::size().
Referenced by combineFP_EXTEND(), combineVectorCompareAndMaskUnaryOp(), combineX86AddSub(), constructRetValue(), getAVX2GatherNode(), getGatherNode(), llvm::SelectionDAGBuilder::getValueImpl(), LowerADDC_ADDE_SUBC_SUBE(), llvm::HexagonTargetLowering::LowerAddSubCarry(), llvm::VETargetLowering::lowerATOMIC_SWAP(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), lowerDSPIntr(), llvm::AMDGPUTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::LanaiTargetLowering::LowerDYNAMIC_STACKALLOC(), LowerDYNAMIC_STACKALLOC(), llvm::SITargetLowering::lowerDYNAMIC_STACKALLOCImpl(), LowerF128Load(), LowerFP16_TO_FP(), LowerFP_TO_FP16(), LowerI64IntToFP_AVX512DQ(), lowerINT_TO_FP_vXi64(), LowerINTRINSIC_W_CHAIN(), LowerLoad(), llvm::MipsTargetLowering::lowerLOAD(), lowerLoadF128(), LowerMGATHER(), LowerMLOAD(), LowerPredicateLoad(), llvm::SelectionDAGBuilder::lowerRangeToAssertZExt(), LowerREADCYCLECOUNTER(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), LowerShiftParts(), llvm::LanaiTargetLowering::LowerSHL_PARTS(), llvm::LanaiTargetLowering::LowerSRL_PARTS(), llvm::HexagonTargetLowering::LowerUAddSubO(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), LowerUINT_TO_FP_i32(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), LowerUMULO_SMULO(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), LowerVSETCC(), llvm::AArch64TargetLowering::PerformDAGCombine(), performGatherLoadCombine(), performLD1Combine(), performLD1ReplicateCombine(), performLDNT1Combine(), llvm::AMDGPUTargetLowering::performLoadCombine(), PerformLongShiftCombine(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), and llvm::AMDGPUTargetLowering::WidenOrSplitVectorLoad().
getNeutralElement()
SDValue SelectionDAG::getNeutralElement (unsigned Opcode, const SDLoc & DL, EVT VT, SDNodeFlags Flags)
Get the (commutative) neutral element for the given opcode, if it exists.
Definition at line 10142 of file SelectionDAG.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::APFloat::changeSign(), DL, EVTToAPFloatSemantics(), llvm::ISD::FADD, llvm::ISD::FMAXNUM, llvm::ISD::FMINNUM, llvm::ISD::FMUL, getAllOnesConstant(), getConstant(), getConstantFP(), llvm::APFloat::getInf(), llvm::APFloat::getLargest(), llvm::APFloat::getQNaN(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::EVT::getSizeInBits(), llvm::SDNodeFlags::hasNoInfs(), llvm::SDNodeFlags::hasNoNaNs(), llvm::ISD::MUL, llvm::ISD::OR, llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::UMAX, llvm::ISD::UMIN, and llvm::ISD::XOR.
getNode() [1/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, ArrayRef< EVT > ResultTys, ArrayRef< SDValue > Ops)
Definition at line 7646 of file SelectionDAG.cpp.
References DL, getNode(), and getVTList().
getNode() [2/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT)
Gets or creates the specified node.
Definition at line 4384 of file SelectionDAG.cpp.
References AddNodeIDNode(), DL, E, getVTList(), N, NewSDValueDbgMsg(), and llvm::None.
getNode() [3/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, ArrayRef< SDUse > Ops)
Gets or creates the specified node.
Definition at line 7556 of file SelectionDAG.cpp.
References llvm::ArrayRef< T >::begin(), DL, llvm::ArrayRef< T >::end(), and llvm::ArrayRef< T >::size().
Referenced by AddCombineBUILD_VECTORToVPADDL(), AddCombineTo64bitMLAL(), AddCombineTo64BitSMLAL16(), AddCombineTo64bitUMAAL(), AddCombineToVPADD(), AddCombineVUZPToVPADDL(), addIPMSequence(), addRequiredExtensionForVectorMULL(), AddRequiredExtensionForVMULL(), addShuffleForVecExtend(), llvm::AMDGPUTargetLowering::addTokenForArgument(), adjustBitcastSrcVectorSSE1(), adjustLoadValueTypeImpl(), buildCallOperands(), BuildExactSDIV(), buildFromShuffleMostly(), BuildIntrinsicOp(), buildMergeScalars(), buildPCRelGlobalAddress(), buildScalarToVector(), llvm::TargetLowering::BuildSDIV(), llvm::PPCTargetLowering::BuildSDIVPow2(), llvm::TargetLowering::BuildUDIV(), BuildVSLDOI(), canonicalizeBitSelect(), canonicalizeLaneShuffleWithRepeatedOps(), canonicalizeShuffleMaskWithHorizOp(), chainLoadsAndStoresForMemcpy(), clampDynamicVectorIndex(), CollectOpsToWiden(), combineAcrossLanesIntrinsic(), combineADC(), combineAdd(), combineADDCARRYDiamond(), combineAddOrSubToADCOrSBB(), combineAddOrSubToHADDorHSUB(), combineADDToADDZE(), combineADDToMAT_PCREL_ADDR(), combineAnd(), combineAndMaskToShift(), combineAndnp(), CombineANDShift(), combineANDXORWithAllOnesIntoANDNP(), combineArithReduction(), CombineBaseUpdate(), combineBasicSADPattern(), combineBitcast(), combineBitcastToBoolVector(), combineBitcastvxi1(), combineBitOpWithMOVMSK(), combineBrCond(), combineCarryDiamond(), combineCarryThroughADD(), combineCastedMaskArithmetic(), combineCMov(), combineCMP(), combineCommutableSHUFP(), combineCompareEqual(), combineConcatVectorOfCasts(), combineConcatVectorOfScalars(), combineConcatVectorOps(), combineCVTP2I_CVTTP2I(), combineCVTPH2PS(), combineEXTEND_VECTOR_INREG(), combineExtractSubvector(), combineExtractVectorElt(), combineExtractWithShuffle(), combineFaddFsub(), combineFAndFNotToFAndn(), combineFMA(), combineFMADDSUB(), combineFMinFMax(), llvm::AMDGPUTargetLowering::combineFMinMaxLegacy(), combineFMinNumFMaxNum(), combineFneg(), combineFP16_TO_FP(), combineFP_EXTEND(), combineFP_ROUND(), combineGatherScatter(), combineGREVI_GORCI(), combineHorizOpWithShuffle(), combineInsertSubvector(), combineLoad(), combineLogicBlendIntoConditionalNegate(), combineMinMaxReduction(), combineMinNumMaxNum(), combineMOVMSK(), combineMul(), combineMulSpecial(), combineMulToPMADDWD(), combineMulToPMULDQ(), combineOr(), combineOrCmpEqZeroToCtlzSrl(), combineORToGORC(), combineORToGREV(), combinePMULDQ(), combinePMULH(), combinePredicateReduction(), combinePTESTCC(), combineRedundantDWordShuffle(), combineSBB(), combineScalarAndWithMaskSetcc(), combineScalarToVector(), combineSelect(), combineSelectAndUse(), combineSelectOfTwoConstants(), combineSetCC(), combineSetCCMOVMSK(), combineSext(), combineSextInRegCmov(), combineShiftAnd1ToBitTest(), combineShiftLeft(), combineShiftOfShiftedLogic(), combineShiftRightArithmetic(), combineShiftRightLogical(), combineShiftToMULH(), combineShiftToPMULH(), combineShuffle(), combineShuffleOfConcatUndef(), combineShuffleToAddSubOrFMAddSub(), combineShuffleToFMAddSub(), combineShuffleToVectorExtend(), combineSignExtendInReg(), combineSIntToFP(), combineStore(), combineSub(), combineSubToSubus(), combineSVEPrefetchVecBaseImmOff(), combineSVEReductionFP(), combineSVEReductionInt(), combineSVEReductionOrderedFP(), combineTargetShuffle(), combineToExtendBoolVectorInReg(), combineToExtendCMOV(), combineToFPTruncExtElt(), combineTruncate(), combineTruncatedArithmetic(), combineTruncateWithSat(), combineUIntToFP(), combineVectorCompareAndMaskUnaryOp(), combineVectorPack(), combineVectorShiftImm(), combineVectorSignBitsTruncation(), combineVectorSizedSetCCEquality(), combineVectorTruncationWithPACKSS(), combineVectorTruncationWithPACKUS(), CombineVMOVDRRCandidateWithVecOp(), combineVSelectToBLENDV(), combineVSelectWithAllOnesOrZeros(), combineVTRUNC(), combineX86AddSub(), combineX86INT_TO_FP(), combineX86ShuffleChain(), combineXor(), combineZext(), CompactSwizzlableVector(), constructDup(), constructRetValue(), ConvertBooleanCarryToCarryFlag(), ConvertCarryFlagToBooleanCarry(), convertFPToInt(), convertFromScalableVector(), convertIntLogicToFPLogic(), convertIntToFP(), convertLocVTToValVT(), convertMergedOpToPredOp(), ConvertSelectToConcatVector(), convertShiftLeftToScale(), convertToScalableVector(), convertValVTToLocVT(), createCMovFP(), createFPCmp(), createGPRPairNode(), createLoadLR(), createMMXBuildVector(), createPSADBW(), createStoreLR(), createVariablePermute(), customLegalizeToWOp(), customLegalizeToWOpWithSExt(), detectAVGPattern(), detectPMADDUBSW(), detectUSatPattern(), distributeOpThroughSelect(), EltsFromConsecutiveLoads(), EmitAVX512Test(), emitCLC(), EmitCMP(), EmitCmp(), emitComparison(), emitConditionalComparison(), emitConstantSizeRepmov(), emitIntrinsicWithCC(), emitIntrinsicWithCCAndChain(), emitMemMem(), emitOrXorXorTree(), emitRepmovs(), emitSETCC(), emitStrictFPComparison(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemchr(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::BPFSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcmp(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcpy(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrnlen(), EmitTest(), EmitUnrolledSetTag(), EmitVectorComparison(), Expand64BitShift(), llvm::TargetLowering::expandABS(), expandDivFix(), expandExp(), expandExp2(), expandf64Toi32(), llvm::TargetLowering::expandFixedPointDiv(), ExpandHorizontalBinOp(), llvm::TargetLowering::expandIndirectJTBranch(), llvm::X86TargetLowering::expandIndirectJTBranch(), expandIntrinsicWChainHelper(), expandLog(), expandLog10(), expandLog2(), llvm::TargetLowering::expandMUL_LOHI(), expandPow(), ExpandPowI(), ExpandREAD_REGISTER(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), llvm::PPCTargetLowering::expandVSXLoadForLE(), llvm::PPCTargetLowering::expandVSXStoreForLE(), ExtendToType(), ExtractBitFromMaskVector(), extractF64Exponent(), extractLOHI(), extractShiftForRotate(), extractSubVector(), finalizeTS1AM(), foldAddSubBoolOfMaskedVal(), foldAddSubMasked1(), foldAddSubOfSignBit(), foldBitcastedFPLogic(), FoldConstantArithmetic(), FoldConstantVectorArithmetic(), foldExtendedSignBitTest(), foldFPToIntToFP(), foldFreeOpFromSelect(), FoldIntToFPToInt(), foldMaskAndShiftToExtract(), foldMaskAndShiftToScale(), foldMaskedShiftToBEXTR(), foldMaskedShiftToScaledMask(), foldSelectOfConstantsUsingSra(), foldShuffleOfConcatUndefs(), foldShuffleOfHorizOp(), foldVectorXorShiftIntoCmp(), foldXorTruncShiftIntoCmp(), genConstMult(), generateEquivalentSub(), GeneratePerfectShuffle(), GenerateTBL(), getAArch64Cmp(), getAArch64XALUOOp(), getAbsolute(), llvm::MipsTargetLowering::getAddrGlobal(), llvm::MipsTargetLowering::getAddrGlobalLargeGOT(), llvm::MipsTargetLowering::getAddrGPRel(), llvm::MipsTargetLowering::getAddrLocal(), llvm::MipsTargetLowering::getAddrNonPIC(), llvm::MipsTargetLowering::getAddrNonPICSym64(), getAnyExtOrTrunc(), getAVX512TruncNode(), getBitcast(), getBoolExtOrTrunc(), getBuildVector(), getBuildVectorSplat(), getCALLSEQ_END(), getCALLSEQ_START(), getCCResult(), getConstant(), getCopyFromParts(), getCopyFromPartsVector(), getCopyFromReg(), llvm::RegsForValue::getCopyFromRegs(), getCopyToParts(), getCopyToPartsVector(), getCopyToReg(), llvm::RegsForValue::getCopyToRegs(), getCppExceptionSymNode(), GetDemandedBits(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), getEstimate(), GetExponent(), getEXTEND_VECTOR_INREG(), getFLUSHW(), getFPBinOp(), getFPExtendOrRound(), getFPTernOp(), getFRAMEADDR(), getFreeze(), getGeneralPermuteNode(), getGLOBAL_OFFSET_TABLE(), llvm::AMDGPUTargetLowering::getHiHalf64(), getHopForBuildVector(), getKnownUndefForVectorBinop(), getLimitedPrecisionExp2(), getLoadExtOrTrunc(), getLogicalNOT(), llvm::AMDGPUTargetLowering::getLoHalf64(), getMad64_32(), getMaskNode(), getMemBasePlusOffset(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), getMemsetStringVal(), getMemsetValue(), getMergeValues(), getMul24(), llvm::X86TargetLowering::getNegatedExpression(), llvm::TargetLowering::getNegatedExpression(), llvm::PPCTargetLowering::getNegatedExpression(), getNode(), getNOT(), getPermuteNode(), llvm::HexagonTargetLowering::getPICJumpTableRelocBase(), llvm::PPCTargetLowering::getPICJumpTableRelocBase(), llvm::VETargetLowering::getPICJumpTableRelocBase(), llvm::X86TargetLowering::getPICJumpTableRelocBase(), getPMOVMSKB(), getPredicateForFixedLengthVector(), getPTest(), getPTrue(), llvm::AMDGPUTargetLowering::getRecipEstimate(), getReductionSDNode(), GetRegistersForValue(), getScalarMaskingNode(), getScaledOffsetForBitWidth(), getSelect(), getSelectCC(), getSetCC(), getSETCC(), getSExtOrTrunc(), getShuffleHalfVectors(), GetSignificand(), getSplatBuildVector(), getSplatValue(), getSplatVector(), llvm::NVPTXTargetLowering::getSqrtEstimate(), llvm::AMDGPUTargetLowering::getSqrtEstimate(), llvm::TargetLowering::getSqrtInputTest(), getStackArgumentTokenFactor(), getSToVPermuted(), getStrictFPExtendOrRound(), getTargetVShiftByConstNode(), getTargetVShiftNode(), GetTLSADDR(), getTokenFactor(), getUNDEF(), getv64i1Argument(), getVAArg(), llvm::TargetLowering::getVectorElementPointer(), getVectorMaskingNode(), getVectorShuffle(), getVScale(), getVShift(), getX86XALUOOp(), getZeroExtendInReg(), getZeroVector(), getZExtOrTrunc(), HandleMergeInputChains(), llvm::TargetLowering::IncrementMemoryAddress(), initAccumulator(), insert1BitVector(), InsertBitToMaskVector(), insertSubVector(), isFNEG(), isFusableLoadOpStorePattern(), IsNOT(), joinDwords(), Legalize(), legalizeSVEGatherPrefetchOffsVec(), llvm::AMDGPUTargetLowering::loadInputValue(), lower1BitShuffle(), lower1BitShuffleAsKSHIFTR(), LowerABS(), LowerADDC_ADDE_SUBC_SUBE(), LowerADDRSPACECAST(), LowerADDSAT_SUBSAT(), lowerAddSub(), LowerADDSUBCARRY(), llvm::HexagonTargetLowering::LowerAddSubCarry(), lowerAddSubToHorizontalOp(), LowerAndToBT(), llvm::X86TargetLowering::LowerAsmOutputForConstraint(), LowerAsSplatVectorLoad(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), llvm::HexagonTargetLowering::LowerATOMIC_FENCE(), llvm::VETargetLowering::lowerATOMIC_FENCE(), LowerATOMIC_FENCE(), llvm::VETargetLowering::lowerATOMIC_SWAP(), lowerAtomicArith(), LowerAVXCONCAT_VECTORS(), LowerAVXExtend(), lowerBALLOTIntrinsic(), LowerBITCAST(), LowerBITREVERSE(), LowerBITREVERSE_XOP(), llvm::HexagonTargetLowering::LowerBlockAddress(), llvm::LanaiTargetLowering::LowerBlockAddress(), llvm::MSP430TargetLowering::LowerBlockAddress(), llvm::LanaiTargetLowering::LowerBR_CC(), llvm::MSP430TargetLowering::LowerBR_CC(), LowerBR_CC(), llvm::HexagonTargetLowering::LowerBUILD_VECTOR(), llvm::VETargetLowering::lowerBUILD_VECTOR(), LowerBUILD_VECTOR_i1(), LowerBUILD_VECTORvXi1(), lowerBuildVectorAsBroadcast(), LowerBuildVectorAsInsert(), LowerBuildVectorOfFPExt(), LowerBuildVectorOfFPTrunc(), lowerBuildVectorToBitOp(), LowerBuildVectorv16i8(), LowerBuildVectorv4x32(), llvm::SITargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), llvm::SITargetLowering::LowerCallResult(), LowerCallResult(), LowerCMP_SWAP(), llvm::TargetLowering::lowerCmpEqZeroToCtlzSrl(), llvm::AMDGPUTargetLowering::LowerCONCAT_VECTORS(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), LowerCONCAT_VECTORS(), LowerCONCAT_VECTORS_i1(), LowerCONCAT_VECTORSvXi1(), llvm::HexagonTargetLowering::LowerConstantPool(), llvm::LanaiTargetLowering::LowerConstantPool(), LowerCTLZ(), llvm::AMDGPUTargetLowering::LowerCTLZ_CTTZ(), LowerCTPOP(), LowerCTTZ(), LowerCVTPS2PH(), llvm::SelectionDAGBuilder::LowerDeoptimizingReturn(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), lowerDSPIntr(), llvm::HexagonTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::LanaiTargetLowering::LowerDYNAMIC_STACKALLOC(), LowerDYNAMIC_STACKALLOC(), llvm::SITargetLowering::lowerDYNAMIC_STACKALLOCImpl(), llvm::HexagonTargetLowering::LowerEH_RETURN(), llvm::VETargetLowering::lowerEH_SJLJ_LONGJMP(), llvm::VETargetLowering::lowerEH_SJLJ_SETJMP(), llvm::VETargetLowering::lowerEH_SJLJ_SETUP_DISPATCH(), LowerEXTEND_VECTOR_INREG(), llvm::MSP430TargetLowering::LowerExternalSymbol(), LowerEXTRACT_SUBVECTOR(), llvm::VETargetLowering::lowerEXTRACT_VECTOR_ELT(), LowerEXTRACT_VECTOR_ELT(), LowerEXTRACT_VECTOR_ELT_i1(), LowerEXTRACT_VECTOR_ELT_SSE4(), llvm::SparcTargetLowering::LowerF128Compare(), LowerF128Load(), LowerF128Store(), LowerF64Op(), lowerFABS32(), lowerFABS64(), LowerFABSorFNEG(), llvm::AMDGPUTargetLowering::LowerFCEIL(), lowerFCMPIntrinsic(), LowerFCOPYSIGN(), lowerFCOPYSIGN32(), lowerFCOPYSIGN64(), llvm::AMDGPUTargetLowering::lowerFEXP(), llvm::AMDGPUTargetLowering::LowerFFLOOR(), LowerFGETSIGN(), llvm::AMDGPUTargetLowering::LowerFLOG(), llvm::AMDGPUTargetLowering::LowerFNEARBYINT(), LowerFNEGorFABS(), llvm::SITargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerFP16_TO_FP(), llvm::AMDGPUTargetLowering::LowerFP64_TO_INT(), LowerFP_TO_FP16(), llvm::AMDGPUTargetLowering::LowerFP_TO_FP16(), llvm::AMDGPUTargetLowering::LowerFP_TO_SINT(), LowerFP_TO_SINT(), lowerFP_TO_SINT_STORE(), llvm::AMDGPUTargetLowering::LowerFP_TO_UINT(), lowerFPToIntToFP(), llvm::LanaiTargetLowering::LowerFRAMEADDR(), llvm::AMDGPUTargetLowering::LowerFREM(), llvm::AMDGPUTargetLowering::LowerFRINT(), LowerFROUND(), llvm::AMDGPUTargetLowering::LowerFROUND(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), LowerFunnelShift(), llvm::HexagonTargetLowering::LowerGLOBAL_OFFSET_TABLE(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::HexagonTargetLowering::LowerGLOBALADDRESS(), llvm::LanaiTargetLowering::LowerGlobalAddress(), llvm::MSP430TargetLowering::LowerGlobalAddress(), llvm::NVPTXTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), lowerGR128Binary(), lowerGR128ToI128(), LowerHorizontalByteSum(), lowerI128ToGR128(), LowerI64IntToFP_AVX512DQ(), lowerICMPIntrinsic(), llvm::VETargetLowering::lowerINSERT_VECTOR_ELT(), LowerINSERT_VECTOR_ELT_i1(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP32(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP64(), lowerINT_TO_FP_vXi64(), LowerInterruptReturn(), llvm::HexagonTargetLowering::LowerINTRINSIC_VOID(), LowerINTRINSIC_W_CHAIN(), llvm::VETargetLowering::lowerINTRINSIC_WO_CHAIN(), llvm::HexagonTargetLowering::LowerJumpTable(), llvm::LanaiTargetLowering::LowerJumpTable(), llvm::MSP430TargetLowering::LowerJumpTable(), LowerLabelRef(), LowerLoad(), llvm::MipsTargetLowering::lowerLOAD(), lowerLoadF128(), lowerMasksToReg(), LowerMemOpCallTo(), LowerMGATHER(), LowerMLOAD(), lowerMSABinaryBitImmIntr(), lowerMSABitClear(), lowerMSABitClearImm(), lowerMSACopyIntr(), lowerMSALoadIntr(), lowerMSASplatZExt(), lowerMSAStoreIntr(), LowerMSCATTER(), LowerMUL(), llvm::LanaiTargetLowering::LowerMUL(), lowerMUL_LOHI32(), LowerMULH(), llvm::R600TargetLowering::LowerOperation(), llvm::RISCVTargetLowering::LowerOperation(), LowerPARITY(), LowerPredicateLoad(), LowerPredicateStore(), LowerPREFETCH(), llvm::HexagonTargetLowering::LowerPREFETCH(), llvm::SelectionDAGBuilder::lowerRangeToAssertZExt(), llvm::HexagonTargetLowering::LowerREADCYCLECOUNTER(), lowerRegToMasks(), llvm::AMDGPUTargetLowering::LowerReturn(), llvm::SITargetLowering::LowerReturn(), llvm::HexagonTargetLowering::LowerReturn(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::RISCVTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::VETargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), llvm::HexagonTargetLowering::LowerRETURNADDR(), llvm::LanaiTargetLowering::LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), lowerRETURNADDR(), LowerReverse_VECTOR_SHUFFLEv16i8_v8i16(), LowerRotate(), LowerSADDSUBSAT(), LowerSaturatingConditional(), LowerSCALAR_TO_VECTOR(), LowerScalarImmediateShift(), LowerScalarVariableShift(), LowerSDIV(), LowerSDIV_v4i16(), LowerSDIV_v4i8(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), llvm::LanaiTargetLowering::LowerSELECT_CC(), llvm::MSP430TargetLowering::LowerSELECT_CC(), LowerSELECT_CC(), llvm::LanaiTargetLowering::LowerSETCC(), llvm::MSP430TargetLowering::LowerSETCC(), LowerSETCCCARRY(), LowerShift(), LowerShiftParts(), llvm::MSP430TargetLowering::LowerShifts(), llvm::LanaiTargetLowering::LowerSHL_PARTS(), lowerShuffleAsBitBlend(), lowerShuffleAsBitMask(), lowerShuffleAsBitRotate(), lowerShuffleAsBlend(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotate(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsByteShiftMask(), lowerShuffleAsElementInsertion(), lowerShuffleAsInsertPS(), lowerShuffleAsLanePermuteAndSHUFP(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsShift(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleAsTruncBroadcast(), lowerShuffleAsUNPCKAndPermute(), lowerShuffleAsVALIGN(), lowerShuffleAsVTRUNC(), lowerShuffleAsVTRUNCAndUnpack(), lowerShuffleAsZeroOrAnyExtend(), lowerShuffleOfExtractsAsVperm(), lowerShuffleToEXPAND(), lowerShuffleWithPACK(), lowerShuffleWithPERMV(), lowerShuffleWithPSHUFB(), lowerShuffleWithSHUFPD(), lowerShuffleWithSHUFPS(), lowerShuffleWithSSE4A(), lowerShuffleWithUndefHalf(), lowerShuffleWithUNPCK(), lowerShuffleWithUNPCK256(), LowerSIGN_EXTEND(), llvm::MSP430TargetLowering::LowerSIGN_EXTEND(), llvm::AMDGPUTargetLowering::LowerSIGN_EXTEND_INREG(), LowerSIGN_EXTEND_Mask(), llvm::AMDGPUTargetLowering::LowerSINT_TO_FP(), LowerSINT_TO_FP(), llvm::LanaiTargetLowering::LowerSRL_PARTS(), LowerStore(), LowerSTORE(), lowerStoreF128(), LowerSVEIntrinsicDUP(), LowerSVEIntrinsicEXT(), LowerSVEIntrinsicIndex(), lowerToAddSubOrFMAddSub(), LowerToTLSExecModel(), llvm::HexagonTargetLowering::LowerToTLSGeneralDynamicModel(), llvm::VETargetLowering::lowerToTLSGeneralDynamicModel(), LowerToTLSGeneralDynamicModel32(), llvm::HexagonTargetLowering::LowerToTLSInitialExecModel(), LowerToTLSLocalDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSLocalExecModel(), llvm::VETargetLowering::lowerToVVP(), LowerTruncatei1(), LowerTruncateVecI1(), LowerTruncateVectorStore(), llvm::HexagonTargetLowering::LowerUAddSubO(), LowerUDIV(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), llvm::AMDGPUTargetLowering::LowerUINT_TO_FP(), LowerUINT_TO_FP_i32(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), LowerUMULO_SMULO(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), lowerV16F32Shuffle(), lowerV16I32Shuffle(), lowerV16I8Shuffle(), lowerV2F64Shuffle(), lowerV2I64Shuffle(), lowerV2X128Shuffle(), lowerV4F32Shuffle(), lowerV4F64Shuffle(), lowerV4I32Shuffle(), lowerV4I64Shuffle(), lowerV4X128Shuffle(), lowerV8F32Shuffle(), lowerV8F64Shuffle(), lowerV8I16GeneralSingleInputShuffle(), lowerV8I16Shuffle(), lowerV8I32Shuffle(), lowerV8I64Shuffle(), llvm::HexagonTargetLowering::LowerVASTART(), llvm::VETargetLowering::lowerVASTART(), LowerVASTART(), LowerVecReduce(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE_i1(), lowerVECTOR_SHUFFLE_SHF(), lowerVECTOR_SHUFFLE_VSHF(), LowerVECTOR_SHUFFLEv8i8(), LowerVectorAllZero(), LowerVectorCTLZ_AVX512CDI(), LowerVectorCTLZInRegLUT(), LowerVectorCTPOP(), LowerVectorCTPOPInRegLUT(), LowerVectorFP_TO_INT(), LowerVectorINT_TO_FP(), LowerVSETCC(), LowerVSETCCWithSUBUS(), LowerWRITE_REGISTER(), lowerX86CmpEqZeroToCtlzSrl(), lowerX86FPLogicOp(), LowerXALUO(), LowerZERO_EXTEND_Mask(), llvm::SparcTargetLowering::makeAddress(), llvm::VETargetLowering::makeAddress(), makeEquivalentMemoryOrdering(), llvm::SparcTargetLowering::makeHiLoPair(), llvm::VETargetLowering::makeHiLoPair(), matchBinOpReduction(), matchBSwapHWordOrAndAnd(), matchPMADDWD(), matchPMADDWD_2(), MatchVectorAllZeroTest(), moveBelowOrigChain(), narrowExtractedVectorBinOp(), narrowInsertExtractVectorBinOp(), narrowVectorSelect(), optimizeLogicalImm(), packImageA16AddressToDwords(), partitionShuffleOfConcats(), llvm::SITargetLowering::passSpecialInputs(), Passv64i1ArgInRegs(), performABSCombine(), performADDCombine(), PerformADDCombineWithOperands(), PerformAddcSubcCombine(), PerformAddeSubeCombine(), performAddSubLongCombine(), PerformADDVecReduce(), performANDCombine(), PerformANDCombine(), PerformARMBUILD_VECTORCombine(), llvm::AMDGPUTargetLowering::performAssertSZExtCombine(), PerformBFICombine(), PerformBITCASTCombine(), llvm::ARMTargetLowering::PerformBRCONDCombine(), performBRCONDCombine(), PerformBUILD_VECTORCombine(), llvm::ARMTargetLowering::PerformCMOVCombine(), performCMovFPCombine(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), performCommonVectorExtendCombine(), performConcatVectorsCombine(), performCONDCombine(), llvm::AArch64TargetLowering::PerformDAGCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PerformDAGCombine(), llvm::HexagonTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performDivRemCombine(), performDSPShiftCombine(), PerformExtendCombine(), performExtendCombine(), PerformExtractEltCombine(), performExtractVectorEltCombine(), llvm::AMDGPUTargetLowering::performFAbsCombine(), performFDivCombine(), llvm::AMDGPUTargetLowering::performFNegCombine(), performFpToIntCombine(), performGatherLoadCombine(), performGlobalAddressCombine(), PerformHWLoopCombine(), PerformInsertEltCombine(), llvm::ARMTargetLowering::PerformIntrinsicCombine(), performIntrinsicCombine(), performIntToFpCombine(), performLD1Combine(), performLD1ReplicateCombine(), performLDNT1Combine(), llvm::AMDGPUTargetLowering::performLoadCombine(), PerformLongShiftCombine(), performMADD_MSUBCombine(), performMaskedGatherScatterCombine(), PerformMinMaxCombine(), performMulCombine(), PerformMULCombine(), llvm::AMDGPUTargetLowering::performMulhsCombine(), llvm::AMDGPUTargetLowering::performMulhuCombine(), performMulVectorExtendCombine(), PerformMVEVMULLCombine(), performORCombine(), PerformORCombine(), PerformORCombine_i1(), PerformORCombineToBFI(), PerformORCombineToSMULWBT(), PerformPREDICATE_CASTCombine(), PerformREMCombine(), performScatterStoreCombine(), llvm::AMDGPUTargetLowering::performSelectCombine(), performSELECTCombine(), performSelectCombine(), PerformSELECTCombine(), performSetccAddFolding(), performSETCCCombine(), PerformSETCCCombine(), PerformShiftCombine(), llvm::AMDGPUTargetLowering::performShlCombine(), performSHLCombine(), PerformSHLSimplify(), performSignExtendInRegCombine(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), llvm::AMDGPUTargetLowering::performSraCombine(), performSRACombine(), llvm::AMDGPUTargetLowering::performSrlCombine(), performSRLCombine(), performST1Combine(), performSTNT1Combine(), llvm::AMDGPUTargetLowering::performStoreCombine(), PerformSTORECombine(), PerformSUBCombine(), performSVEAndCombine(), performTBZCombine(), llvm::AMDGPUTargetLowering::performTruncateCombine(), PerformTruncatingStoreCombine(), performUADDVCombine(), PerformUMLALCombine(), performUzpCombine(), PerformVCMPCombine(), PerformVCVTCombine(), PerformVDIVCombine(), PerformVDUPCombine(), PerformVDUPLANECombine(), PerformVECREDUCE_ADDCombine(), performVecReduceAddCombine(), PerformVECTOR_REG_CASTCombine(), PerformVECTOR_SHUFFLECombine(), performVectorCompareAndMaskUnaryOpCombine(), performVectorTruncateCombine(), performVectorWidenCombine(), PerformVMOVDRRCombine(), PerformVMOVhrCombine(), PerformVMOVNCombine(), PerformVMOVrhCombine(), PerformVMOVRRDCombine(), PerformVMULCombine(), PerformVQDMULHCombine(), performVSelectCombine(), performVSELECTCombine(), PerformVSELECTCombine(), performXORCombine(), PerformXORCombine(), prepareDescriptorIndirectCall(), prepareIndirectCall(), PrepareTailCall(), prepareTS1AM(), promoteExtBeforeAdd(), PromoteMaskArithmetic(), PromoteMVEPredVector(), promoteToConstantPool(), llvm::AArch64TargetLowering::ReconstructShuffle(), recoverFramePointer(), reduceMaskedLoadToScalarLoad(), reduceMaskedStoreToScalarStore(), reduceVMULWidth(), ReorganizeVector(), ReplaceAllUsesWith(), ReplaceBITCASTResults(), ReplaceCMP_SWAP_128Results(), ReplaceCMP_SWAP_64Results(), replaceInChain(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), ReplaceLongIntrinsic(), llvm::SITargetLowering::ReplaceNodeResults(), llvm::AVRTargetLowering::ReplaceNodeResults(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::SparcTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), ReplaceREADCYCLECOUNTER(), ReplaceReductionResults(), replaceShuffleOfInsert(), SaturateWidenedDIVFIX(), scalarizeBinOpOfSplats(), scalarizeExtEltFP(), scalarizeExtractedBinop(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), scalarizeVectorStore(), llvm::HexagonDAGToDAGISel::SelectIntrinsicWOChain(), llvm::TargetLowering::ShrinkDemandedConstant(), llvm::TargetLowering::ShrinkDemandedOp(), ShrinkLoadReplaceStoreWithStore(), signExtendBitcastSrcVector(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::ARMTargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), simplifyI24(), llvm::TargetLowering::SimplifySetCC(), simplifySetCCWithCTPOP(), SkipExtensionForVMULL(), llvm::TargetLowering::softenSetCCOperands(), llvm::AMDGPUTargetLowering::split64BitValue(), SplitAndExtendv16i1(), splitAndLowerShuffle(), llvm::AMDGPUTargetLowering::splitBinaryBitConstantOpImpl(), llvm::SITargetLowering::splitBinaryVectorOp(), splitInt128(), splitIntVSETCC(), SplitOpsAndApply(), splitStores(), splitStoreSplat(), llvm::SITargetLowering::splitTernaryVectorOp(), llvm::SITargetLowering::splitUnaryVectorOp(), llvm::AMDGPUTargetLowering::splitVector(), SplitVector(), splitVectorIntBinary(), splitVectorIntUnary(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), llvm::AMDGPUTargetLowering::SplitVectorStore(), splitVectorStore(), stripModuloOnShift(), llvm::ARMTargetLowering::targetShrinkDemandedConstant(), llvm::RISCVTargetLowering::targetShrinkDemandedConstant(), llvm::X86TargetLowering::targetShrinkDemandedConstant(), truncateScalarIntegerArg(), truncateVecElts(), truncateVectorWithPACK(), tryAdvSIMDModImm16(), tryAdvSIMDModImm32(), tryAdvSIMDModImm321s(), tryAdvSIMDModImm64(), tryAdvSIMDModImm8(), tryAdvSIMDModImmFP(), tryCombineCRC32(), tryCombineFixedPointConvert(), tryCombineLongOpWithDup(), tryCombineShiftImm(), tryCombineToBSL(), tryCombineToEXTR(), tryConvertSVEWideCompare(), tryExtendDUPToExtractHigh(), tryFormConcatFromShuffle(), tryLowerToSLI(), TryMULWIDECombine(), tryToFoldExtendOfConstant(), tryToFoldExtOfLoad(), tryToFoldExtOfMaskedLoad(), unpackF64OnRV32DSoftABI(), UnpackFromArgumentSlot(), UnrollVectorOp(), UnrollVectorOverflowOp(), unrollVectorShift(), vectorizeExtractedCast(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), visitFMinMax(), llvm::SelectionDAGBuilder::visitJumpTable(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), visitORCommutative(), llvm::SelectionDAGBuilder::visitSPDescriptorFailure(), llvm::SelectionDAGBuilder::visitSwitchCase(), widenCtPop(), llvm::AMDGPUTargetLowering::WidenOrSplitVectorLoad(), widenSubVector(), widenVec(), WidenVector(), WidenVector(), and WinDBZCheckDenominator().
getNode() [4/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, ArrayRef< SDValue > Ops)
Definition at line 7572 of file SelectionDAG.cpp.
References DL, llvm::SelectionDAG::FlagInserter::getFlags(), and getNode().
getNode() [5/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, ArrayRef< SDValue > Ops, const SDNodeFlags Flags)
Definition at line 7580 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::ISD::BR_CC, llvm::ISD::BUILD_VECTOR, llvm::ISD::CONCAT_VECTORS, DL, E, FoldBUILD_VECTOR(), foldCONCAT_VECTORS(), getNode(), getValueType(), getVTList(), llvm::MVT::Glue, N, NewSDValueDbgMsg(), llvm::ISD::SELECT_CC, and llvm::ArrayRef< T >::size().
getNode() [6/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2)
Definition at line 5236 of file SelectionDAG.cpp.
References DL, llvm::SelectionDAG::FlagInserter::getFlags(), and getNode().
getNode() [7/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2, const SDNodeFlags Flags)
Definition at line 5244 of file SelectionDAG.cpp.
References llvm::ISD::ADD, AddNodeIDNode(), llvm::ISD::AND, llvm::APInt::ashrInPlace(), assert(), llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::EVT::bitsLE(), llvm::ISD::BUILD_PAIR, llvm::ISD::BUILD_VECTOR, C, llvm::ISD::CONCAT_VECTORS, DL, llvm::numbers::e, E, llvm::ISD::EntryToken, llvm::ISD::EXTRACT_ELEMENT, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FADD, llvm::ISD::FCOPYSIGN, llvm::ISD::FDIV, llvm::ISD::FMUL, FoldBUILD_VECTOR(), foldCONCAT_VECTORS(), FoldConstantArithmetic(), foldConstantFPMath(), llvm::ISD::FP_ROUND, llvm::ISD::FREM, llvm::ISD::FSUB, getAllOnesConstant(), getAnyExtOrTrunc(), llvm::ConstantSDNode::getAPIntValue(), llvm::APInt::getBitWidth(), getBuildVector(), getConstant(), getDataLayout(), llvm::SDValue::getNode(), getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), getSExtOrTrunc(), llvm::EVT::getSizeInBits(), getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementCount(), llvm::EVT::getVectorElementType(), getVectorIdxConstant(), llvm::TargetLoweringBase::getVectorIdxTy(), llvm::EVT::getVectorMinNumElements(), llvm::EVT::getVectorNumElements(), getVScale(), getVTList(), llvm::ConstantSDNode::getZExtValue(), llvm::MVT::Glue, llvm::SDNodeFlags::hasNoSignedWrap(), llvm::MVT::i1, Index, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::ConstantSDNode::isAllOnesValue(), llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::TargetLoweringBase::isCommutativeBinOp(), llvm::EVT::isFixedLengthVector(), llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::ConstantSDNode::isNullValue(), llvm::EVT::isScalableVector(), llvm::SDValue::isUndef(), llvm::EVT::isVector(), LLVM_FALLTHROUGH, llvm::Log2_32_Ceil(), llvm::APInt::lshr(), llvm::ISD::MUL, llvm::ISD::MULHS, llvm::ISD::MULHU, N, NewSDValueDbgMsg(), llvm::ISD::OR, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SADDSAT, llvm::ISD::SDIV, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND_INREG, simplifyFPBinop(), simplifyShift(), llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::SPLAT_VECTOR, llvm::ISD::SRA, llvm::ISD::SREM, llvm::ISD::SRL, llvm::ISD::SSUBSAT, llvm::ISD::SUB, std::swap(), llvm::ISD::TokenFactor, llvm::APInt::trunc(), llvm::ISD::UADDSAT, llvm::ISD::UDIV, llvm::APInt::uge(), llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::ISD::UREM, llvm::ISD::USUBSAT, llvm::ISD::VSCALE, and llvm::ISD::XOR.
getNode() [8/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2, SDValue N3)
Definition at line 5699 of file SelectionDAG.cpp.
References DL, llvm::SelectionDAG::FlagInserter::getFlags(), and getNode().
getNode() [9/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, const SDNodeFlags Flags)
Definition at line 5707 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::ISD::CONCAT_VECTORS, DL, E, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::FMA, FoldBUILD_VECTOR(), foldCONCAT_VECTORS(), FoldConstantVectorArithmetic(), FoldSetCC(), llvm::APFloat::fusedMultiplyAdd(), getConstantFP(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), getUNDEF(), llvm::ConstantFPSDNode::getValueAPF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementCount(), llvm::EVT::getVectorMinNumElements(), llvm::EVT::getVectorNumElements(), getVTList(), llvm::ConstantSDNode::getZExtValue(), llvm::MVT::Glue, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::EVT::isFixedLengthVector(), llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::EVT::isScalableVector(), llvm::SDValue::isUndef(), llvm::EVT::isVector(), llvm_unreachable, N, NewSDValueDbgMsg(), llvm::APFloatBase::rmNearestTiesToEven, llvm::ISD::SELECT, llvm::ISD::SETCC, simplifySelect(), llvm::NVPTX::PTXLdStInstCode::V2, llvm::ISD::VECTOR_SHUFFLE, and llvm::ISD::VSELECT.
getNode() [10/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, SDValue N4)
Definition at line 5856 of file SelectionDAG.cpp.
References DL, and getNode().
getNode() [11/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, SDValue N4, SDValue N5)
Definition at line 5862 of file SelectionDAG.cpp.
References DL, and getNode().
getNode() [12/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue Operand)
Definition at line 4401 of file SelectionDAG.cpp.
References DL, llvm::SelectionDAG::FlagInserter::getFlags(), and getNode().
getNode() [13/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue Operand, const SDNodeFlags Flags)
Definition at line 4409 of file SelectionDAG.cpp.
References llvm::APInt::abs(), llvm::ISD::ABS, AddNodeIDNode(), llvm::ISD::ANY_EXTEND, llvm::ISD::ANY_EXTEND_VECTOR_INREG, llvm::lltok::APFloat, assert(), llvm::ISD::BITCAST, llvm::APFloat::bitcastToAPInt(), llvm::ISD::BITREVERSE, llvm::EVT::bitsGT(), llvm::EVT::bitsLE(), llvm::EVT::bitsLT(), llvm::ISD::BSWAP, llvm::ISD::BUILD_VECTOR, llvm::APInt::byteSwap(), C, llvm::APFloat::changeSign(), llvm::APFloat::clearSign(), llvm::ISD::CONCAT_VECTORS, llvm::APFloat::convert(), llvm::APFloat::convertFromAPInt(), llvm::APFloat::convertToInteger(), llvm::APInt::countLeadingZeros(), llvm::APInt::countPopulation(), llvm::APInt::countTrailingZeros(), llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, DL, E, EVTToAPFloatSemantics(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f128, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FABS, llvm::ISD::FCEIL, llvm::ISD::FFLOOR, llvm::ISD::FNEG, FoldBUILD_VECTOR(), FoldConstantVectorArithmetic(), llvm::ISD::FP16_TO_FP, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_FP16, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FREEZE, llvm::ISD::FTRUNC, llvm::APInt::getBitWidth(), getConstant(), getConstantFP(), llvm::SDValue::getConstantOperandVal(), llvm::SDValue::getNode(), getNode(), getNOT(), llvm::APInt::getNullValue(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), getUNDEF(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementCount(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), getVTList(), llvm::APInt::getZExtValue(), llvm::MVT::Glue, llvm::MVT::i1, llvm::MVT::i128, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::APFloatBase::IEEEdouble(), llvm::APFloatBase::IEEEhalf(), llvm::APFloatBase::IEEEquad(), llvm::APFloatBase::IEEEsingle(), llvm::tgtok::IntVal, llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::SDValue::isUndef(), llvm::EVT::isVector(), LLVM_FALLTHROUGH, llvm_unreachable, llvm::ISD::MERGE_VALUES, N, NewSDValueDbgMsg(), llvm::APFloatBase::opInexact, llvm::APFloatBase::opInvalidOp, llvm::APFloatBase::opOK, llvm::APInt::reverseBits(), llvm::APFloatBase::rmNearestTiesToEven, llvm::APFloatBase::rmTowardNegative, llvm::APFloatBase::rmTowardPositive, llvm::APFloatBase::rmTowardZero, llvm::APFloat::roundToIntegral(), llvm::ISD::SCALAR_TO_VECTOR, llvm::APInt::sextOrTrunc(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::ISD::SINT_TO_FP, llvm::ISD::TokenFactor, transferDbgValues(), llvm::APInt::trunc(), llvm::ISD::TRUNCATE, llvm::ISD::UINT_TO_FP, llvm::ISD::UNDEF, llvm::ISD::VECREDUCE_AND, llvm::ISD::VECREDUCE_OR, llvm::ISD::VECREDUCE_SMAX, llvm::ISD::VECREDUCE_SMIN, llvm::ISD::VECREDUCE_UMAX, llvm::ISD::VECREDUCE_UMIN, llvm::ISD::VSCALE, llvm::ISD::ZERO_EXTEND, llvm::ISD::ZERO_EXTEND_VECTOR_INREG, and llvm::APInt::zextOrTrunc().
getNode() [14/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList)
Definition at line 7743 of file SelectionDAG.cpp.
References DL, getNode(), and llvm::None.
getNode() [15/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, ArrayRef< SDValue > Ops)
Definition at line 7651 of file SelectionDAG.cpp.
References DL, llvm::SelectionDAG::FlagInserter::getFlags(), and getNode().
getNode() [16/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, ArrayRef< SDValue > Ops, const SDNodeFlags Flags)
Definition at line 7659 of file SelectionDAG.cpp.
References AddNodeIDNode(), llvm::ISD::AND, assert(), llvm::EVT::bitsLT(), DL, E, getNode(), llvm::EVT::getScalarSizeInBits(), getValueType(), llvm::EVT::getVectorNumElements(), llvm::MVT::Glue, llvm::MVT::i1, llvm::EVT::isFloatingPoint(), llvm::EVT::isVector(), N, NewSDValueDbgMsg(), llvm::SDVTList::NumVTs, llvm::ISD::SHL_PARTS, llvm::ISD::SIGN_EXTEND_INREG, llvm::ArrayRef< T >::size(), llvm::ISD::SRA_PARTS, llvm::ISD::SRL_PARTS, llvm::ISD::STRICT_FP_EXTEND, llvm::ISD::STRICT_FP_ROUND, and llvm::SDVTList::VTs.
getNode() [17/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, SDValue N)
Definition at line 7748 of file SelectionDAG.cpp.
References DL, and getNode().
getNode() [18/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, SDValue N1, SDValue N2)
Definition at line 7754 of file SelectionDAG.cpp.
References DL, and getNode().
getNode() [19/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, SDValue N1, SDValue N2, SDValue N3)
Definition at line 7760 of file SelectionDAG.cpp.
References DL, and getNode().
getNode() [20/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, SDValue N1, SDValue N2, SDValue N3, SDValue N4)
Definition at line 7766 of file SelectionDAG.cpp.
References DL, and getNode().
getNode() [21/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, SDValue N1, SDValue N2, SDValue N3, SDValue N4, SDValue N5)
Definition at line 7772 of file SelectionDAG.cpp.
References DL, and getNode().
getNodeIfExists() [1/2]
SDNode * SelectionDAG::getNodeIfExists (unsigned Opcode, SDVTList VTList, ArrayRef< SDValue > Ops)
getNodeIfExists - Get the specified node if it's already available, or else return NULL.
Definition at line 8355 of file SelectionDAG.cpp.
References llvm::SelectionDAG::FlagInserter::getFlags(), and getNodeIfExists().
getNodeIfExists() [2/2]
SDNode * SelectionDAG::getNodeIfExists (unsigned Opcode, SDVTList VTList, ArrayRef< SDValue > Ops, const SDNodeFlags Flags)
Get the specified node if it's already available, or else return NULL.
Definition at line 8363 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, llvm::MVT::Glue, llvm::SDVTList::NumVTs, and llvm::SDVTList::VTs.
Referenced by combineX86AddSub(), and getNodeIfExists().
getNoMergeSiteInfo()
bool llvm::SelectionDAG::getNoMergeSiteInfo (const SDNode * Node) inline
Definition at line 2002 of file SelectionDAG.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and I.
getNOT()
SDValue SelectionDAG::getNOT (const SDLoc & DL, SDValue Val, EVT VT)
Create a bitwise NOT operation as (XOR Val, -1).
getNOT - Create a bitwise NOT operation as (XOR Val, -1).
Definition at line 1305 of file SelectionDAG.cpp.
References DL, llvm::APInt::getAllOnesValue(), getConstant(), getNode(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), and llvm::ISD::XOR.
Referenced by combineSelect(), combineSelectOfTwoConstants(), combineSetCC(), combineVSelectWithAllOnesOrZeros(), EmitVectorComparison(), foldExtendedSignBitTest(), getNode(), LowerADDSAT_SUBSAT(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), lowerMSABitClear(), LowerVSETCC(), llvm::TargetLowering::SimplifyDemandedBits(), and llvm::TargetLowering::SimplifySetCC().
getObjectPtrOffset() [1/2]
SDValue llvm::SelectionDAG::getObjectPtrOffset (const SDLoc & SL, SDValue Ptr, SDValue Offset) inline
Definition at line 911 of file SelectionDAG.h.
References getMemBasePlusOffset(), Offset, and llvm::SDNodeFlags::setNoUnsignedWrap().
getObjectPtrOffset() [2/2]
SDValue llvm::SelectionDAG::getObjectPtrOffset (const SDLoc & SL, SDValue Ptr, TypeSize Offset) inline
Create an add instruction with appropriate flags when used for addressing some offset of an object.
i.e. if a load is split into multiple components, create an add nuw from the base pointer to the offset.
Definition at line 905 of file SelectionDAG.h.
References getMemBasePlusOffset(), Offset, and llvm::SDNodeFlags::setNoUnsignedWrap().
Referenced by llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), and llvm::AMDGPUTargetLowering::SplitVectorStore().
getORE()
OptimizationRemarkEmitter& llvm::SelectionDAG::getORE () const inline
Definition at line 455 of file SelectionDAG.h.
getPass()
const Pass* llvm::SelectionDAG::getPass () const inline
Definition at line 445 of file SelectionDAG.h.
Referenced by llvm::SITargetLowering::LowerFormalArguments(), and llvm::SITargetLowering::passSpecialInputs().
getPseudoProbeNode()
SDValue SelectionDAG::getPseudoProbeNode (const SDLoc & Dl, SDValue Chain, uint64_t Guid, uint64_t Index, uint32_t Attr)
Creates a PseudoProbeSDNode with function GUID Guid and the index of the block Index it is probing, as well as the attributes attr of the probe.
Definition at line 6934 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), getVTList(), Index, N, NewSDValueDbgMsg(), llvm::MVT::Other, and llvm::ISD::PSEUDO_PROBE.
getPSI()
ProfileSummaryInfo* llvm::SelectionDAG::getPSI () const inline
Definition at line 456 of file SelectionDAG.h.
getPtrExtendInReg()
SDValue SelectionDAG::getPtrExtendInReg (SDValue Op, const SDLoc & DL, EVT VT)
Return the expression required to extend the Op as a pointer value assuming it was the smaller SrcTy value.
This may be either a zero extend or a sign extend.
Definition at line 1298 of file SelectionDAG.cpp.
References DL, and getZeroExtendInReg().
getPtrExtOrTrunc()
SDValue SelectionDAG::getPtrExtOrTrunc (SDValue Op, const SDLoc & DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either truncating it or performing either zero or sign extension as appropriate extension for the pointer's semantics.
Definition at line 1292 of file SelectionDAG.cpp.
References DL, and getZExtOrTrunc().
Referenced by llvm::SelectionDAGBuilder::visitSwitchCase().
getReducedAlign()
Align SelectionDAG::getReducedAlign (EVT VT, bool UseABI)
In most cases this function returns the ABI alignment for a given type, except for illegal vector types where the alignment exceeds that of the stack.
In such cases we attempt to break the vector down to a legal type and return the ABI alignment for that instead.
Definition at line 2103 of file SelectionDAG.cpp.
References DL, getContext(), getDataLayout(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::TargetFrameLowering::getStackAlign(), llvm::MachineFunction::getSubtarget(), llvm::EVT::getTypeForEVT(), llvm::TargetLoweringBase::getVectorTypeBreakdown(), llvm::TargetLoweringBase::isTypeLegal(), and llvm::EVT::isVector().
getRegister()
SDValue SelectionDAG::getRegister (unsigned Reg, EVT VT)
Definition at line 1910 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, getVTList(), llvm::TargetLowering::isSDNodeSourceOfDivergence(), N, llvm::None, and llvm::ISD::Register.
Referenced by llvm::RegsForValue::AddInlineAsmOperands(), buildCallOperands(), createCMovFP(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), emitLockedStackOp(), EmitUnrolledSetTag(), llvm::MipsTargetLowering::getAddrGPRel(), getCopyFromReg(), getCopyToReg(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), llvm::MipsDAGToDAGISel::getGlobalBaseReg(), llvm::MipsTargetLowering::getGlobalReg(), llvm::MipsTargetLowering::getOpndList(), getPrefetchNode(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), llvm::LanaiTargetLowering::LowerConstantPool(), llvm::HexagonTargetLowering::LowerEH_RETURN(), lowerFABS32(), lowerFABS64(), llvm::LanaiTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::SparcTargetLowering::LowerINTRINSIC_WO_CHAIN(), llvm::LanaiTargetLowering::LowerJumpTable(), LowerMemOpCallTo(), llvm::SITargetLowering::LowerReturn(), llvm::HexagonTargetLowering::LowerReturn(), llvm::RISCVTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::VETargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), LowerSETCCCARRY(), llvm::VETargetLowering::lowerVASTART(), LowerVASTART(), llvm::PPCTargetLowering::PerformDAGCombine(), performNEONPostLDSTCombine(), performPostLD1Combine(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::PPCTargetLowering::SelectAddressRegImm34(), llvm::PPCTargetLowering::SelectAddressRegRegOnly(), llvm::SelectionDAGISel::SelectCodeCommon(), and selectImm().
getRegisterMask()
SDValue SelectionDAG::getRegisterMask (const uint32_t * RegMask)
Definition at line 1925 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, getVTList(), N, llvm::None, llvm::ISD::RegisterMask, and llvm::MVT::Untyped.
Referenced by buildCallOperands(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), llvm::MipsTargetLowering::getOpndList(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), and llvm::VETargetLowering::lowerToTLSGeneralDynamicModel().
getRoot()
const SDValue& llvm::SelectionDAG::getRoot () const inline
Return the root tag of the SelectionDAG.
Definition at line 520 of file SelectionDAG.h.
Referenced by llvm::checkForCycles(), llvm::ScheduleDAGSDNodes::getCustomGraphFeatures(), Legalize(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), llvm::SelectionDAGBuilder::LowerDeoptimizingReturn(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), RemoveDeadNode(), RemoveDeadNodes(), ReplaceAllUsesOfValueWith(), ReplaceAllUsesWith(), and llvm::DAGTypeLegalizer::run().
getSDCallSiteInfo()
CallSiteInfo llvm::SelectionDAG::getSDCallSiteInfo (const SDNode * CallNode) inline
Definition at line 1978 of file SelectionDAG.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), I, and llvm::move().
getSelect()
SDValue llvm::SelectionDAG::getSelect (const SDLoc & DL, EVT VT, SDValue Cond, SDValue LHS, SDValue RHS) inline
Helper function to make it easier to build Select's if you just have operands and don't want to check for vector.
Definition at line 1102 of file SelectionDAG.h.
References assert(), Cond, DL, getNode(), llvm::SDValue::getValueType(), llvm::EVT::isVector(), llvm::ISD::SELECT, and llvm::ISD::VSELECT.
Referenced by llvm::TargetLowering::BuildUDIV(), combineFMinNumFMaxNum(), combineLogicBlendIntoPBLENDV(), combineMaskedLoadConstantMask(), combineSelect(), llvm::TargetLowering::expandFixedPointDiv(), LowerADDSAT_SUBSAT(), llvm::HexagonTargetLowering::LowerBUILD_VECTOR(), LowerBUILD_VECTORvXi1(), llvm::AMDGPUTargetLowering::LowerFRINT(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP32(), lowerINT_TO_FP_vXi64(), LowerRotate(), LowerShift(), llvm::LanaiTargetLowering::LowerSHL_PARTS(), lowerShuffleAsBlend(), LowerSIGN_EXTEND_Mask(), llvm::LanaiTargetLowering::LowerSRL_PARTS(), llvm::HexagonTargetLowering::LowerVSELECT(), LowerZERO_EXTEND_Mask(), narrowExtractedVectorSelect(), performSelectCombine(), llvm::X86TargetLowering::ReplaceNodeResults(), tryToFoldExtendOfConstant(), and UnrollVectorOverflowOp().
getSelectCC()
SDValue llvm::SelectionDAG::getSelectCC (const SDLoc & DL, SDValue LHS, SDValue RHS, SDValue True, SDValue False, ISD::CondCode Cond) inline
Helper function to make it easier to build SelectCC's if you just have an ISD::CondCode instead of an SDValue.
Definition at line 1114 of file SelectionDAG.h.
References Cond, DL, getCondCode(), getNode(), llvm::SDValue::getValueType(), and llvm::ISD::SELECT_CC.
Referenced by createVariablePermute(), llvm::TargetLowering::expandMUL_LOHI(), llvm::AMDGPUTargetLowering::LowerFP_TO_FP16(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), and llvm::R600TargetLowering::PerformDAGCombine().
getSelectionDAGInfo()
const SelectionDAGTargetInfo& llvm::SelectionDAG::getSelectionDAGInfo () const inline
Definition at line 452 of file SelectionDAG.h.
getSetCC()
SDValue llvm::SelectionDAG::getSetCC (const SDLoc & DL, EVT VT, SDValue LHS, SDValue RHS, ISD::CondCode Cond, SDValue Chain = SDValue(), bool IsSignaling = false) inline
Helper function to make it easier to build SetCC's if you just have an ISD::CondCode instead of an SDValue.
Definition at line 1085 of file SelectionDAG.h.
References assert(), Cond, DL, getCondCode(), getNode(), llvm::SDValue::getValueType(), llvm::EVT::isVector(), llvm::MVT::Other, llvm::ISD::SETCC, llvm::ISD::SETCC_INVALID, llvm::ISD::STRICT_FSETCC, and llvm::ISD::STRICT_FSETCCS.
Referenced by llvm::TargetLowering::BuildUDIV(), combineAnd(), combineBitcast(), combineExtractVectorElt(), combineExtSetcc(), combineFMinNumFMaxNum(), combineOr(), combinePredicateReduction(), combineSelect(), combineSetCC(), combineShiftAnd1ToBitTest(), combineToExtendBoolVectorInReg(), combineVectorSizedSetCCEquality(), combineVSelectWithAllOnesOrZeros(), emitOrXorXorTree(), llvm::TargetLowering::expandFixedPointDiv(), FoldSetCC(), foldVectorXorShiftIntoCmp(), foldXorTruncShiftIntoCmp(), llvm::TargetLowering::getSqrtInputTest(), lower1BitShuffle(), LowerADDSAT_SUBSAT(), llvm::AMDGPUTargetLowering::LowerCTLZ_CTTZ(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), LowerEXTEND_VECTOR_INREG(), llvm::AMDGPUTargetLowering::LowerFCEIL(), llvm::AMDGPUTargetLowering::LowerFFLOOR(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::AMDGPUTargetLowering::LowerFRINT(), llvm::AMDGPUTargetLowering::LowerFROUND(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP32(), lowerINT_TO_FP_vXi64(), LowerIntVSETCC_AVX512(), LowerMULH(), LowerScalarImmediateShift(), llvm::HexagonTargetLowering::LowerSETCC(), LowerShift(), LowerShiftParts(), llvm::LanaiTargetLowering::LowerSHL_PARTS(), llvm::LanaiTargetLowering::LowerSRL_PARTS(), LowerTruncateVecI1(), llvm::HexagonTargetLowering::LowerUAddSubO(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), LowerUMULO_SMULO(), LowerVectorCTLZInRegLUT(), LowerVSETCC(), llvm::RISCVTargetLowering::PerformDAGCombine(), llvm::AMDGPUTargetLowering::performSelectCombine(), performSELECTCombine(), performVSelectCombine(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::TargetLowering::SimplifySetCC(), simplifySetCCWithCTPOP(), llvm::TargetLowering::softenSetCCOperands(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), and llvm::SelectionDAGBuilder::visitSwitchCase().
getSExtOrTrunc()
SDValue SelectionDAG::getSExtOrTrunc (SDValue Op, const SDLoc & DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either sign-extending or truncating it.
Definition at line 1253 of file SelectionDAG.cpp.
References llvm::EVT::bitsGT(), DL, getNode(), llvm::ISD::SIGN_EXTEND, and llvm::ISD::TRUNCATE.
Referenced by combineGatherScatter(), combineShiftToMULH(), combineShuffleOfScalars(), combineToExtendBoolVectorInReg(), earlyExpandDIVFIX(), expandDivFix(), foldCONCAT_VECTORS(), getNode(), LowerBITCAST(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP32(), LowerMULH(), LowerSADDSUBSAT(), llvm::HexagonTargetLowering::LowerSETCC(), LowerShift(), llvm::HexagonTargetLowering::LowerVSELECT(), LowerVSETCC(), llvm::AMDGPUTargetLowering::performMulCombine(), and llvm::AMDGPUTargetLowering::performMulhsCombine().
getShiftAmountConstant()
SDValue SelectionDAG::getShiftAmountConstant (uint64_t Val, EVT VT, const SDLoc & DL, bool LegalTypes = true)
Definition at line 1445 of file SelectionDAG.cpp.
References assert(), DL, getConstant(), getDataLayout(), llvm::TargetLoweringBase::getShiftAmountTy(), and llvm::EVT::isInteger().
Referenced by combineExtractWithShuffle(), extractShiftForRotate(), getCopyToParts(), llvm::AMDGPUTargetLowering::loadInputValue(), llvm::SITargetLowering::passSpecialInputs(), and llvm::TargetLowering::scalarizeVectorLoad().
getShiftAmountOperand()
SDValue SelectionDAG::getShiftAmountOperand (EVT LHSTy, SDValue Op)
Return the specified value casted to the target's desired shift amount type.
getShiftAmountOperand - Return the specified value casted to the target's desired shift amount type.
Definition at line 2047 of file SelectionDAG.cpp.
References getDataLayout(), llvm::TargetLoweringBase::getShiftAmountTy(), getZExtOrTrunc(), and llvm::EVT::isVector().
Referenced by UnrollVectorOp().
getSplatBuildVector()
SDValue llvm::SelectionDAG::getSplatBuildVector (EVT VT, const SDLoc & DL, SDValue Op) inline
Return a splat ISD::BUILD_VECTOR node, consisting of Op splatted to all elements.
VT must be a vector type. Op's type must be the same as (or, for integers, a type wider than) VT's element type.
Definition at line 814 of file SelectionDAG.h.
References assert(), llvm::EVT::bitsLE(), llvm::ISD::BUILD_VECTOR, DL, getNode(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::isInteger(), and llvm::ISD::UNDEF.
Referenced by getConstant(), getConstantFP(), getMemsetValue(), and getVectorShuffle().
getSplatSourceVector()
SDValue SelectionDAG::getSplatSourceVector (SDValue V, int & SplatIndex)
If V is a splatted value, return the source vector and its splat index.
Definition at line 2528 of file SelectionDAG.cpp.
References llvm::countTrailingOnes(), llvm::APInt::getAllOnesValue(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::EVT::isScalableVector(), isSplatValue(), llvm::APInt::isSubsetOf(), llvm::peekThroughExtractSubvectors(), llvm::ISD::SPLAT_VECTOR, and llvm::ISD::VECTOR_SHUFFLE.
Referenced by getSplatValue(), and scalarizeBinOpOfSplats().
getSplatValue()
SDValue SelectionDAG::getSplatValue (SDValue V)
If V is a splat vector, return its scalar source operand by extracting that element from the source vector.
Definition at line 2581 of file SelectionDAG.cpp.
References llvm::ISD::EXTRACT_VECTOR_ELT, getNode(), getSplatSourceVector(), and getVectorIdxConstant().
Referenced by LowerScalarVariableShift(), refineUniformBase(), and selectGatherScatterAddrMode().
getSplatVector()
SDValue llvm::SelectionDAG::getSplatVector (EVT VT, const SDLoc & DL, SDValue Op) inline
Definition at line 831 of file SelectionDAG.h.
References assert(), llvm::EVT::bitsLE(), DL, getNode(), llvm::EVT::getVectorElementType(), llvm::EVT::isInteger(), llvm::ISD::SPLAT_VECTOR, and llvm::ISD::UNDEF.
Referenced by BuildExactSDIV(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), getConstant(), getConstantFP(), and llvm::SelectionDAGBuilder::getValueImpl().
GetSplitDestVTs()
std::pair< EVT, EVT > SelectionDAG::GetSplitDestVTs (const EVT & VT) const
Compute the VTs needed for the low/hi parts of a type which is split (or expanded) into two not necessarily identical pieces.
GetSplitDestVTs - Compute the VTs needed for the low/hi parts of a type which is split (or expanded) into two not necessarily identical pieces.
Definition at line 9745 of file SelectionDAG.cpp.
References getContext(), llvm::EVT::getHalfNumVectorElementsVT(), llvm::TargetLoweringBase::getTypeToTransformTo(), and llvm::EVT::isVector().
Referenced by LowerCVTPS2PH(), llvm::X86TargetLowering::ReplaceNodeResults(), ReplaceReductionResults(), splitIntVSETCC(), SplitVector(), splitVectorIntBinary(), and splitVectorIntUnary().
getSrcValue()
SDValue SelectionDAG::getSrcValue (const Value * v)
Construct a node to track a Value* through the backend.
Definition at line 1983 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, getVTList(), N, llvm::None, llvm::MVT::Other, and llvm::ISD::SRCVALUE.
Referenced by llvm::SelectionDAGBuilder::LowerAsSTATEPOINT().
getStackArgumentTokenFactor()
SDValue SelectionDAG::getStackArgumentTokenFactor (SDValue Chain)
Compute a TokenFactor to force all the incoming stack arguments to be loaded from the stack.
getStackArgumentTokenFactor - Compute a TokenFactor to force all the incoming stack arguments to be loaded from the stack.
This is used in tail call lowering to protect stack arguments from being clobbered.
Definition at line 5871 of file SelectionDAG.cpp.
References getEntryNode(), getNode(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::ISD::TokenFactor.
getStore() [1/4]
SDValue SelectionDAG::getStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, MachineMemOperand * MMO)
Definition at line 7141 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), getUNDEF(), llvm::SDValue::getValueType(), getVTList(), N, NewSDValueDbgMsg(), llvm::MVT::Other, llvm::ISD::STORE, llvm::RegState::Undef, and llvm::ISD::UNINDEXED.
getStore() [2/4]
SDValue SelectionDAG::getStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, Align Alignment, MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes())
Helper function to build ISD::STORE nodes.
This function will set the MOStore flag on MMOFlags, but you can set it if you want. The MOLoad and MOInvariant flags must not be set.
Definition at line 7120 of file SelectionDAG.cpp.
References assert(), getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::MemoryLocation::getSizeOrUnknown(), llvm::EVT::getStoreSize(), llvm::SDValue::getValueType(), InferPointerInfo(), llvm::PointerUnion< PTs >::isNull(), llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, llvm::MVT::Other, llvm::Check::Size, and llvm::MachinePointerInfo::V.
Referenced by combineStore(), EmitTailCallStoreFPAndRetAddr(), EmitTailCallStoreRetAddr(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), getStore(), getTruncStore(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::HexagonTargetLowering::LowerEH_RETURN(), LowerF128Store(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), lowerFP_TO_SINT_STORE(), LowerMemOpCallTo(), lowerMSAStoreIntr(), LowerStore(), LowerSTORE(), lowerStoreF128(), LowerTruncateVectorStore(), LowerVASTART(), llvm::HexagonTargetLowering::LowerVASTART(), llvm::LanaiTargetLowering::LowerVASTART(), llvm::MSP430TargetLowering::LowerVASTART(), llvm::VETargetLowering::lowerVASTART(), memsetStore(), llvm::AMDGPUTargetLowering::performStoreCombine(), PerformSTORECombine(), PerformTruncatingStoreCombine(), reduceMaskedStoreToScalarStore(), llvm::TargetLowering::scalarizeVectorStore(), scalarizeVectorStore(), ShrinkLoadReplaceStoreWithStore(), splitStores(), splitStoreSplat(), splitVectorStore(), llvm::HexagonDAGToDAGISel::StoreInstrForLoadIntrinsic(), llvm::AMDGPUTargetLowering::storeStackInputValue(), and StoreTailCallArgumentsToStackSlot().
getStore() [3/4]
SDValue llvm::SelectionDAG::getStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, MaybeAlign Alignment = MaybeAlign(), MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes()) inline
Definition at line 1302 of file SelectionDAG.h.
References getEVTAlign(), getStore(), and llvm::SDValue::getValueType().
getStore() [4/4]
SDValue llvm::SelectionDAG::getStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, unsigned Alignment, MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes()) inline
FIXME: Remove once transition to Align is over.
Definition at line 1312 of file SelectionDAG.h.
References getStore().
getStrictFPExtendOrRound()
std::pair< SDValue, SDValue > SelectionDAG::getStrictFPExtendOrRound (SDValue Op, SDValue Chain, const SDLoc & DL, EVT VT)
Convert Op, which must be a STRICT operation of float type, to the float type VT, by either extending or rounding (by truncation).
Definition at line 1234 of file SelectionDAG.cpp.
References assert(), llvm::EVT::bitsEq(), llvm::EVT::bitsGT(), DL, getIntPtrConstant(), llvm::SDValue::getNode(), getNode(), llvm::MVT::Other, llvm::ISD::STRICT_FP_EXTEND, and llvm::ISD::STRICT_FP_ROUND.
Referenced by LowerUINT_TO_FP_i32().
getSubtarget()
const TargetSubtargetInfo& llvm::SelectionDAG::getSubtarget () const inline
Definition at line 449 of file SelectionDAG.h.
References llvm::MachineFunction::getSubtarget().
Referenced by emitComparison(), emitConditionalComparison(), llvm::HexagonSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), init(), llvm::PPC::isVPKUDUMShuffleMask(), lowerMSASplatZExt(), llvm::HexagonTargetLowering::LowerToTLSGeneralDynamicModel(), LowerVectorFP_TO_INT(), LowerVectorINT_TO_FP(), patchMatchingInput(), performExtractVectorEltCombine(), performLD1ReplicateCombine(), performLDNT1Combine(), performST1Combine(), performSTNT1Combine(), recoverFramePointer(), and truncateVecElts().
getSymbolFunctionGlobalAddress()
SDValue SelectionDAG::getSymbolFunctionGlobalAddress (SDValue Op, Function ** TargetFunction = nullptr)
Returs an GlobalAddress of the function from the current module with name matching the given ExternalSymbol.
Additionally can provide the matched function. Panics the function doesn't exists.
Definition at line 9055 of file SelectionDAG.cpp.
References assert(), llvm::raw_ostream::flush(), llvm::GlobalValue::getAddressSpace(), getDataLayout(), llvm::MachineFunction::getFunction(), llvm::Module::getFunction(), getGlobalAddress(), llvm::GlobalValue::getParent(), llvm::TargetLoweringBase::getPointerTy(), llvm::report_fatal_error(), and llvm::ARMBuildAttrs::Symbol.
Referenced by llvm::NVPTXTargetLowering::LowerCall().
getTarget()
const TargetMachine& llvm::SelectionDAG::getTarget () const inline
Definition at line 448 of file SelectionDAG.h.
References llvm::SystemZISD::TM.
Referenced by combineFMinFMax(), combineFMinNumFMaxNum(), combineSelect(), llvm::ScheduleDAGSDNodes::EmitSchedule(), foldFPToIntToFP(), llvm::TargetLowering::getNegatedExpression(), llvm::SITargetLowering::isEligibleForTailCallOptimization(), isFMAddSubOrFMSubAdd(), isKnownNeverNaN(), isLegalToCombineMinNumMaxNum(), llvm::VETargetLowering::LowerCall(), llvm::SelectionDAGBuilder::LowerDeoptimizingReturn(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::VETargetLowering::lowerINTRINSIC_WO_CHAIN(), and transformCallee().
getTargetBlockAddress()
SDValue llvm::SelectionDAG::getTargetBlockAddress (const BlockAddress * BA, EVT VT, int64_t Offset = 0, unsigned TargetFlags = 0) inline
Definition at line 737 of file SelectionDAG.h.
References getBlockAddress(), and Offset.
Referenced by getTargetNode(), llvm::TargetLowering::LowerAsmOperandForConstraint(), llvm::HexagonTargetLowering::LowerBlockAddress(), llvm::MSP430TargetLowering::LowerBlockAddress(), llvm::SparcTargetLowering::withTargetFlags(), and llvm::VETargetLowering::withTargetFlags().
getTargetConstant() [1/3]
SDValue llvm::SelectionDAG::getTargetConstant (const APInt & Val, const SDLoc & DL, EVT VT, bool isOpaque = false) inline
Definition at line 648 of file SelectionDAG.h.
References DL, and getConstant().
getTargetConstant() [2/3]
SDValue llvm::SelectionDAG::getTargetConstant (const ConstantInt & Val, const SDLoc & DL, EVT VT, bool isOpaque = false) inline
Definition at line 652 of file SelectionDAG.h.
References DL, and getConstant().
getTargetConstant() [3/3]
SDValue llvm::SelectionDAG::getTargetConstant (uint64_t Val, const SDLoc & DL, EVT VT, bool isOpaque = false) inline
Definition at line 644 of file SelectionDAG.h.
References DL, and getConstant().
Referenced by llvm::RegsForValue::AddInlineAsmOperands(), buildPCRelGlobalAddress(), llvm::SITargetLowering::buildRSRC(), buildSMovImm32(), canonicalizeBitSelect(), combineADC(), combineAddOrSubToADCOrSBB(), combineAndMaskToShift(), combineBitcastToBoolVector(), combineBrCond(), combineCMov(), combineCommutableSHUFP(), combineCompareEqual(), combineExtractWithShuffle(), combineFP16_TO_FP(), combineFP_ROUND(), combineGREVI_GORCI(), combineORToGORC(), combineORToGREV(), combineTargetShuffle(), llvm::VETargetLowering::combineTRUNCATE(), combineVectorShiftImm(), combineX86ShuffleChain(), createGPRPairNode(), createMMXBuildVector(), createTupleImpl(), llvm::HexagonDAGToDAGISel::DetectUseSxtw(), EmitAVX512Test(), emitLockedStackOp(), emitSETCC(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForSetTag(), ExtractBitFromMaskVector(), extractSubReg(), llvm::PPC::get_VSPLTI_elt(), getAL(), getAVX2GatherNode(), getCopyFromParts(), getGatherNode(), getGeneralPermuteNode(), getIntOperandsFromRegisterString(), getLeftShift(), getPermuteNode(), getPredicateForFixedLengthVector(), getPrefetchNode(), getPTrue(), getScatterNode(), getSETCC(), getSPDenormModeValue(), getTargetExtractSubreg(), getTargetInsertSubreg(), getTargetVShiftByConstNode(), getTargetVShiftNode(), getUniformBase(), getV4X86ShuffleImm8ForMask(), getVAArg(), getVShift(), getZeroVector(), insert1BitVector(), insertSubReg(), isVMOVModifiedImm(), llvm::HexagonDAGToDAGISel::LoadInstrForLoadIntrinsic(), lower1BitShuffle(), lower1BitShuffleAsKSHIFTR(), LowerABS(), LowerAndToBT(), llvm::TargetLowering::LowerAsmOperandForConstraint(), llvm::SITargetLowering::LowerAsmOperandForConstraint(), llvm::ARMTargetLowering::LowerAsmOperandForConstraint(), llvm::AVRTargetLowering::LowerAsmOperandForConstraint(), llvm::LanaiTargetLowering::LowerAsmOperandForConstraint(), llvm::PPCTargetLowering::LowerAsmOperandForConstraint(), llvm::RISCVTargetLowering::LowerAsmOperandForConstraint(), llvm::SparcTargetLowering::LowerAsmOperandForConstraint(), llvm::SystemZTargetLowering::LowerAsmOperandForConstraint(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), llvm::VETargetLowering::lowerATOMIC_FENCE(), LowerBITCAST(), LowerBITREVERSE(), llvm::SITargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), LowerCMP_SWAP(), LowerCONCAT_VECTORSvXi1(), LowerCTLZ(), LowerCTTZ(), LowerEXTEND_VECTOR_INREG(), LowerEXTRACT_SUBVECTOR(), llvm::VETargetLowering::lowerEXTRACT_VECTOR_ELT(), LowerEXTRACT_VECTOR_ELT_SSE4(), LowerF128Load(), LowerF128Store(), llvm::VETargetLowering::LowerFormalArguments(), LowerFP_TO_FP16(), LowerFunnelShift(), LowerINTRINSIC_W_CHAIN(), lowerLoadF128(), LowerMLOAD(), llvm::RISCVTargetLowering::LowerOperation(), llvm::VETargetLowering::LowerReturn(), LowerRotate(), LowerShift(), lowerShuffleAsBitRotate(), lowerShuffleAsBlend(), lowerShuffleAsByteRotate(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsByteShiftMask(), lowerShuffleAsElementInsertion(), lowerShuffleAsInsertPS(), lowerShuffleAsLanePermuteAndSHUFP(), lowerShuffleAsShift(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleAsVALIGN(), lowerShuffleWithSHUFPD(), lowerShuffleWithSSE4A(), LowerSTORE(), lowerStoreF128(), lowerUINT_TO_FP_vXi32(), lowerV2F64Shuffle(), lowerV2X128Shuffle(), lowerV4F64Shuffle(), lowerV4X128Shuffle(), lowerV8F64Shuffle(), lowerVECTOR_SHUFFLE_SHF(), lowerVECTOR_SHUFFLE_VSHF(), LowerVSETCC(), MatchVectorAllZeroTest(), narrowIfNeeded(), optimizeLogicalImm(), parseCachePolicy(), parseTexFail(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformHWLoopCombine(), PromoteMVEPredVector(), ReplaceBITCASTResults(), llvm::RISCVTargetLowering::ReplaceNodeResults(), ReplaceREADCYCLECOUNTER(), llvm::AVRDAGToDAGISel::SelectAddr(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::PPCTargetLowering::SelectAddressRegImm34(), llvm::HexagonDAGToDAGISel::SelectAnyImmediate(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::HexagonDAGToDAGISel::SelectConstantFP(), llvm::HexagonDAGToDAGISel::SelectD2P(), llvm::HexagonDAGToDAGISel::SelectFrameIndex(), selectI64Imm(), selectI64ImmDirect(), selectImm(), llvm::HexagonDAGToDAGISel::SelectIndexedLoad(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), llvm::AVRDAGToDAGISel::SelectInlineAsmMemoryOperand(), llvm::HexagonDAGToDAGISel::SelectInlineAsmMemoryOperand(), llvm::NVPTXDAGToDAGISel::SelectInlineAsmMemoryOperand(), llvm::SelectionDAGISel::SelectInlineAsmMemoryOperands(), llvm::HexagonDAGToDAGISel::SelectNewCircIntrinsic(), llvm::HexagonDAGToDAGISel::SelectQ2V(), llvm::HvxSelector::selectRor(), llvm::HexagonDAGToDAGISel::SelectSHL(), llvm::HexagonDAGToDAGISel::SelectV2Q(), llvm::HexagonDAGToDAGISel::SelectVAlign(), llvm::HexagonDAGToDAGISel::SelectVAlignAddr(), llvm::RISCVDAGToDAGISel::selectVSplatSimm5(), llvm::RISCVDAGToDAGISel::selectVSplatUimm5(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), tryBitfieldInsertOpFromOr(), tryBitfieldInsertOpFromOrAndImm(), Widen(), and llvm::SITargetLowering::wrapAddr64Rsrc().
getTargetConstantFP() [1/3]
SDValue llvm::SelectionDAG::getTargetConstantFP (const APFloat & Val, const SDLoc & DL, EVT VT) inline
Definition at line 679 of file SelectionDAG.h.
References DL, and getConstantFP().
getTargetConstantFP() [2/3]
SDValue llvm::SelectionDAG::getTargetConstantFP (const ConstantFP & Val, const SDLoc & DL, EVT VT) inline
Definition at line 682 of file SelectionDAG.h.
References DL, and getConstantFP().
getTargetConstantFP() [3/3]
SDValue llvm::SelectionDAG::getTargetConstantFP (double Val, const SDLoc & DL, EVT VT) inline
Definition at line 676 of file SelectionDAG.h.
References DL, and getConstantFP().
Referenced by llvm::SelectionDAGISel::SelectCodeCommon().
getTargetConstantPool() [1/2]
SDValue llvm::SelectionDAG::getTargetConstantPool (const Constant * C, EVT VT, MaybeAlign Align = None, int Offset = 0, unsigned TargetFlags = 0) inline
Definition at line 706 of file SelectionDAG.h.
References C, getConstantPool(), and Offset.
Referenced by getTargetNode(), llvm::HexagonTargetLowering::LowerConstantPool(), llvm::LanaiTargetLowering::LowerConstantPool(), promoteToConstantPool(), llvm::SparcTargetLowering::withTargetFlags(), and llvm::VETargetLowering::withTargetFlags().
getTargetConstantPool() [2/2]
SDValue llvm::SelectionDAG::getTargetConstantPool (MachineConstantPoolValue * C, EVT VT, MaybeAlign Align = None, int Offset = 0, unsigned TargetFlags = 0) inline
Definition at line 714 of file SelectionDAG.h.
References C, getConstantPool(), and Offset.
getTargetExternalSymbol()
SDValue SelectionDAG::getTargetExternalSymbol (const char * Sym, EVT VT, unsigned TargetFlags = 0)
Definition at line 1697 of file SelectionDAG.cpp.
References N.
Referenced by getCppExceptionSymNode(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::MSP430TargetLowering::LowerExternalSymbol(), llvm::HexagonTargetLowering::LowerGLOBAL_OFFSET_TABLE(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::VETargetLowering::lowerINTRINSIC_WO_CHAIN(), transformCallee(), llvm::SparcTargetLowering::withTargetFlags(), and llvm::VETargetLowering::withTargetFlags().
getTargetExtractSubreg()
SDValue SelectionDAG::getTargetExtractSubreg (int SRIdx, const SDLoc & DL, EVT VT, SDValue Operand)
A convenience function for creating TargetInstrInfo::EXTRACT_SUBREG nodes.
getTargetExtractSubreg - A convenience function for creating TargetOpcode::EXTRACT_SUBREG nodes.
Definition at line 8335 of file SelectionDAG.cpp.
References DL, getMachineNode(), getTargetConstant(), and llvm::MVT::i32.
Referenced by llvm::SITargetLowering::buildRSRC(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), LowerF64Op(), LowerFNEGorFABS(), lowerGR128Binary(), lowerGR128ToI128(), NarrowVector(), ReplaceCMP_SWAP_128Results(), ReplaceCMP_SWAP_64Results(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), and llvm::HexagonDAGToDAGISel::SelectVAlign().
getTargetFrameIndex()
SDValue llvm::SelectionDAG::getTargetFrameIndex (int FI, EVT VT) inline
Definition at line 695 of file SelectionDAG.h.
References getFrameIndex().
Referenced by llvm::AArch64SelectionDAGInfo::EmitTargetCodeForSetTag(), EmitUnrolledSetTag(), llvm::AVRDAGToDAGISel::SelectAddr(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::PPCTargetLowering::SelectAddressRegImm34(), llvm::HexagonDAGToDAGISel::SelectAddrFI(), llvm::RISCVDAGToDAGISel::SelectAddrFI(), and llvm::HexagonDAGToDAGISel::SelectFrameIndex().
getTargetGlobalAddress()
SDValue llvm::SelectionDAG::getTargetGlobalAddress (const GlobalValue * GV, const SDLoc & DL, EVT VT, int64_t offset = 0, unsigned TargetFlags = 0) inline
Definition at line 690 of file SelectionDAG.h.
References DL, and getGlobalAddress().
Referenced by buildPCRelGlobalAddress(), combineADDToMAT_PCREL_ADDR(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), getTargetNode(), GetTLSADDR(), llvm::TargetLowering::LowerAsmOperandForConstraint(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::HexagonTargetLowering::LowerGLOBALADDRESS(), llvm::LanaiTargetLowering::LowerGlobalAddress(), llvm::MSP430TargetLowering::LowerGlobalAddress(), llvm::NVPTXTargetLowering::LowerGlobalAddress(), LowerToTLSExecModel(), llvm::HexagonTargetLowering::LowerToTLSGeneralDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSInitialExecModel(), LowerToTLSLocalDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSLocalExecModel(), llvm::HexagonDAGToDAGISel::SelectGlobalAddress(), transformCallee(), llvm::SparcTargetLowering::withTargetFlags(), and llvm::VETargetLowering::withTargetFlags().
getTargetIndex()
SDValue SelectionDAG::getTargetIndex (int Index, EVT VT, int64_t Offset = 0, unsigned TargetFlags = 0)
Definition at line 1635 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, getVTList(), Index, N, llvm::None, Offset, and llvm::ISD::TargetIndex.
getTargetInsertSubreg()
SDValue SelectionDAG::getTargetInsertSubreg (int SRIdx, const SDLoc & DL, EVT VT, SDValue Operand, SDValue Subreg)
A convenience function for creating TargetInstrInfo::INSERT_SUBREG nodes.
getTargetInsertSubreg - A convenience function for creating TargetOpcode::INSERT_SUBREG nodes.
Definition at line 8345 of file SelectionDAG.cpp.
References DL, getMachineNode(), getTargetConstant(), and llvm::MVT::i32.
Referenced by LowerF64Op(), and LowerFNEGorFABS().
getTargetJumpTable()
SDValue llvm::SelectionDAG::getTargetJumpTable (int JTI, EVT VT, unsigned TargetFlags = 0) inline
Definition at line 700 of file SelectionDAG.h.
References getJumpTable().
Referenced by llvm::HexagonTargetLowering::getPICJumpTableRelocBase(), getTargetNode(), llvm::HexagonTargetLowering::LowerJumpTable(), llvm::LanaiTargetLowering::LowerJumpTable(), llvm::MSP430TargetLowering::LowerJumpTable(), and llvm::VETargetLowering::withTargetFlags().
getTargetLoweringInfo()
const TargetLowering& llvm::SelectionDAG::getTargetLoweringInfo () const inline
Definition at line 450 of file SelectionDAG.h.
Referenced by AddCombineBUILD_VECTORToVPADDL(), AddCombineToVPADD(), AddCombineVUZPToVPADDL(), llvm::RegsForValue::AddInlineAsmOperands(), buildFromShuffleMostly(), llvm::TargetLowering::BuildSDIVPow2(), combineAdd(), combineAnd(), combineBEXTR(), combineBitcast(), combineBitcastToBoolVector(), combineBT(), combineConcatVectorOfCasts(), combineConcatVectorOfExtracts(), combineConcatVectorOfScalars(), combineConcatVectors(), combineCVTPH2PS(), combineEXTEND_VECTOR_INREG(), combineExtractSubvector(), combineExtractVectorElt(), combineFMA(), combineFMADDSUB(), combineFMinNumFMaxNum(), combineFneg(), combineGatherScatter(), combineKSHIFT(), combineLoad(), combineLogicBlendIntoConditionalNegate(), combineMaskedLoad(), combineMaskedStore(), combineMOVMSK(), combineMulToPMADDWD(), combineOr(), combinePDEP(), combinePMULDQ(), combinePredicateReduction(), combinePTESTCC(), combineScalarAndWithMaskSetcc(), combineSelect(), combineSelectOfTwoConstants(), combineShiftAnd1ToBitTest(), combineShuffle(), combineShuffleToFMAddSub(), combineStore(), combineTargetShuffle(), combineTruncatedArithmetic(), combineTruncateWithSat(), combineVectorInsert(), combineVectorShiftImm(), combineVectorShiftVar(), combineVEXTRACT_STORE(), combineVSelectToBLENDV(), combineVSelectWithAllOnesOrZeros(), combineVTRUNC(), combineX86GatherScatter(), combineX86INT_TO_FP(), combineX86ShuffleChain(), combineX86ShuffleChainWithExtract(), combineX86ShufflesConstants(), llvm::SelectionDAGBuilder::CopyValueToVirtualRegister(), createMMXBuildVector(), EltsFromConsecutiveLoads(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), foldCONCAT_VECTORS(), foldExtendedSignBitTest(), foldShuffleOfConcatUndefs(), foldXorTruncShiftIntoCmp(), formSplatFromShuffles(), getAddressForMemoryInput(), getAVX2GatherNode(), getAVX512TruncNode(), getConstVector(), getContainerForFixedLengthVector(), getCopyFromParts(), getCopyFromPartsVector(), llvm::SelectionDAGBuilder::getCopyFromRegs(), llvm::RegsForValue::getCopyFromRegs(), getCopyToParts(), getCopyToPartsVector(), llvm::RegsForValue::getCopyToRegs(), getCppExceptionSymNode(), llvm::SelectionDAGBuilder::getFrameIndexTy(), getGatherNode(), getKnownUndefForVectorBinop(), getLifetimeNode(), getLimitedPrecisionExp2(), getLoadStackGuard(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), getMemsetValue(), getPredicateForFixedLengthVector(), getPredicateForScalableVector(), getPrefetchNode(), getPTest(), GetRegistersForValue(), getScatterNode(), getUniformBase(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::SelectionDAGBuilder::handleDebugValue(), llvm::SelectionDAGBuilder::init(), isAddSubOrSubAdd(), isBLACompatibleAddress(), isConsecutiveLSLoc(), isPackedVectorType(), LowerADDC_ADDE_SUBC_SUBE(), LowerADDSAT_SUBSAT(), LowerADDSUBCARRY(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), lowerBuildVectorAsBroadcast(), lowerBuildVectorToBitOp(), llvm::SelectionDAGBuilder::LowerCallTo(), LowerCTPOP(), llvm::SelectionDAGBuilder::LowerDeoptimizeCall(), llvm::SelectionDAGBuilder::lowerInvokable(), LowerMemOpCallTo(), LowerMSCATTER(), lowerShuffleAsElementInsertion(), lowerShuffleAsShift(), llvm::SelectionDAGBuilder::LowerStatepoint(), LowerStore(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_vXi32(), LowerVASTART(), lowerVECTOR_SHUFFLE(), LowerVectorAllZero(), LowerVSETCC(), LowerXALUO(), matchLSNode(), narrowExtractedVectorBinOp(), narrowExtractedVectorLoad(), narrowInsertExtractVectorBinOp(), llvm::ScheduleDAGSDNodes::newSUnit(), patchMatchingInput(), PerformABSCombine(), PerformADDCombineWithOperands(), performANDCombine(), PerformANDCombine(), PerformARMBUILD_VECTORCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), PerformExtendCombine(), performExtendCombine(), performGatherLoadCombine(), PerformLOADCombine(), performORCombine(), PerformORCombine(), PerformPREDICATE_CASTCombine(), performScatterStoreCombine(), performSelectCombine(), PerformShiftCombine(), PerformSTORECombine(), performTBISimplification(), PerformTruncatingStoreCombine(), PerformVDUPLANECombine(), PerformVECTOR_SHUFFLECombine(), PerformVMOVhrCombine(), PerformVMOVNCombine(), PerformVQMOVNCombine(), PerformXORCombine(), PromoteMaskArithmetic(), recoverFramePointer(), reduceBuildVecToShuffleWithZero(), refineIndexType(), scalarizeBinOpOfSplats(), scalarizeExtractedBinop(), llvm::TargetLowering::CallLoweringInfo::setLibCallee(), llvm::TargetLowering::ShrinkDemandedOp(), ShrinkLoadReplaceStoreWithStore(), simplifyI24(), llvm::TargetLowering::SimplifySetCC(), transformCallee(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTable(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), llvm::SelectionDAGBuilder::visitSPDescriptorFailure(), llvm::SelectionDAGBuilder::visitSPDescriptorParent(), llvm::SelectionDAGBuilder::visitSwitchCase(), and widenCtPop().
getTokenFactor()
SDValue SelectionDAG::getTokenFactor (const SDLoc & DL, SmallVectorImpl< SDValue > & Vals)
Creates a new TokenFactor containing Vals.
If Vals contains 64k values or more, move values into new TokenFactors in 64k-1 blocks, until the final TokenFactor has less than 64k operands.
Definition at line 10129 of file SelectionDAG.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), DL, llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorImpl< T >::erase(), llvm::SDNode::getMaxNumOperands(), getNode(), llvm::MVT::Other, llvm::SmallVectorBase< Size_T >::size(), llvm::ArrayRef< T >::slice(), and llvm::ISD::TokenFactor.
Referenced by llvm::SITargetLowering::LowerCall().
getTruncStore() [1/4]
SDValue SelectionDAG::getTruncStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, EVT SVT, MachineMemOperand * MMO)
Definition at line 7192 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::EVT::bitsLT(), E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::EVT::getScalarType(), getStore(), getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementCount(), getVTList(), llvm::EVT::isInteger(), llvm::EVT::isVector(), N, NewSDValueDbgMsg(), llvm::MVT::Other, llvm::ISD::STORE, llvm::RegState::Undef, and llvm::ISD::UNINDEXED.
getTruncStore() [2/4]
SDValue SelectionDAG::getTruncStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, EVT SVT, Align Alignment, MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes())
Definition at line 7171 of file SelectionDAG.cpp.
References assert(), getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::MemoryLocation::getSizeOrUnknown(), llvm::EVT::getStoreSize(), llvm::SDValue::getValueType(), InferPointerInfo(), llvm::PointerUnion< PTs >::isNull(), llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, llvm::MVT::Other, and llvm::MachinePointerInfo::V.
Referenced by chainLoadsAndStoresForMemcpy(), combineStore(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), getAddressForMemoryInput(), getMemcpyLoadsAndStores(), getTruncStore(), LowerINTRINSIC_W_CHAIN(), LowerPredicateStore(), PerformSplittingToNarrowingStores(), llvm::TargetLowering::scalarizeVectorStore(), llvm::AMDGPUTargetLowering::SplitVectorStore(), and llvm::HexagonDAGToDAGISel::StoreInstrForLoadIntrinsic().
getTruncStore() [3/4]
SDValue llvm::SelectionDAG::getTruncStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, EVT SVT, MaybeAlign Alignment = MaybeAlign(), MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes()) inline
Definition at line 1327 of file SelectionDAG.h.
References getEVTAlign(), and getTruncStore().
getTruncStore() [4/4]
SDValue llvm::SelectionDAG::getTruncStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, EVT SVT, unsigned Alignment, MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes()) inline
FIXME: Remove once transition to Align is over.
Definition at line 1338 of file SelectionDAG.h.
References getTruncStore().
getUNDEF()
SDValue llvm::SelectionDAG::getUNDEF (EVT VT) inline
Return an UNDEF node. UNDEF does not have a useful SDLoc.
Definition at line 950 of file SelectionDAG.h.
References getNode(), and llvm::ISD::UNDEF.
Referenced by addShuffleForVecExtend(), adjustLoadValueTypeImpl(), buildFromShuffleMostly(), buildMergeScalars(), buildScalarToVector(), canonicalizeShuffleMaskWithHorizOp(), CollectOpsToWiden(), combineAddOrSubToHADDorHSUB(), combineArithReduction(), combineBasicSADPattern(), combineBitcast(), combineBitcastToBoolVector(), combineBitcastvxi1(), combineBVOfConsecutiveLoads(), combineConcatVectorOfExtracts(), combineConcatVectorOps(), combineExtractSubvector(), combineExtractVectorElt(), combineExtractWithShuffle(), combineFaddFsub(), combineFP_EXTEND(), combineInsertSubvector(), combineMaskedLoadConstantMask(), combineSelect(), combineSetCCAtomicArith(), combineShuffleOfConcatUndef(), combineShuffleOfScalars(), combineSVEReductionOrderedFP(), combineTargetShuffle(), combineTruncateWithSat(), combineVectorPack(), combineX86ShuffleChain(), combineX86ShufflesRecursively(), CompactSwizzlableVector(), concatSubVectors(), convertLocVTToValVT(), convertShiftLeftToScale(), convertToScalableVector(), createMMXBuildVector(), detectAVGPattern(), EltsFromConsecutiveLoads(), emitNonHSAIntrinsicError(), emitRemovedIntrinsicError(), EmitTruncSStore(), ExpandHorizontalBinOp(), ExtendToType(), ExtractBitFromMaskVector(), FoldBUILD_VECTOR(), foldCONCAT_VECTORS(), FoldConstantArithmetic(), foldConstantFPMath(), FoldConstantVectorArithmetic(), FoldSetCC(), getBuildDwordsVector(), getConstVector(), getCopyFromPartsVector(), getExtLoad(), getGeneralPermuteNode(), getHopForBuildVector(), getKnownUndefForVectorBinop(), getLoad(), getNode(), getShuffleHalfVectors(), getShuffleScalarElt(), getShuffleVectorZeroOrUndef(), getSplatSourceVector(), getStore(), getTargetVShiftNode(), getTruncStore(), llvm::SelectionDAGBuilder::getValueImpl(), getVectorShuffle(), insert1BitVector(), isAddSubOrSubAdd(), isFNEG(), isHopBuildVector(), isHorizontalBinOpPart(), joinDwords(), lower1BitShuffle(), lower1BitShuffleAsKSHIFTR(), LowerAsSplatVectorLoad(), lowerAtomicArith(), LowerAVXCONCAT_VECTORS(), LowerAVXExtend(), LowerBITCAST(), LowerBITREVERSE_XOP(), llvm::VETargetLowering::lowerBUILD_VECTOR(), LowerBUILD_VECTORvXi1(), LowerBuildVectorOfFPTrunc(), LowerBuildVectorv4x32(), llvm::SITargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), LowerCONCAT_VECTORS(), LowerCONCAT_VECTORSvXi1(), LowerEXTEND_VECTOR_INREG(), LowerEXTRACT_SUBVECTOR(), lowerFCMPIntrinsic(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), lowerICMPIntrinsic(), lowerINT_TO_FP_vXi64(), LowerINTRINSIC_W_CHAIN(), llvm::MipsTargetLowering::lowerLOAD(), LowerMSCATTER(), LowerMUL(), LowerMULH(), LowerPredicateStore(), LowerSCALAR_TO_VECTOR(), LowerScalarImmediateShift(), LowerShift(), lowerShuffleAsBlend(), lowerShuffleAsBlendAndPermute(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsDecomposedShuffleMerge(), lowerShuffleAsElementInsertion(), lowerShuffleAsLanePermuteAndPermute(), lowerShuffleAsLanePermuteAndShuffle(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsRepeatedMaskAndLanePermute(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleAsUNPCKAndPermute(), lowerShuffleOfExtractsAsVperm(), lowerShuffleWithPSHUFB(), lowerShuffleWithSSE4A(), lowerShuffleWithUndefHalf(), lowerShuffleWithUNPCK256(), LowerSIGN_EXTEND_Mask(), llvm::SelectionDAGBuilder::LowerStatepoint(), LowerStore(), LowerTruncateVectorStore(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), lowerV16I8Shuffle(), lowerV2F64Shuffle(), lowerV2X128Shuffle(), lowerV4X128Shuffle(), lowerVECTOR_SHUFFLE(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE_i1(), LowerZERO_EXTEND_Mask(), matchBinaryPermuteShuffle(), matchBinaryShuffle(), matchShuffleAsInsertPS(), matchShuffleWithUNPCK(), NormalizeBuildVector(), padEltsToUndef(), partitionShuffleOfConcats(), PerformARMBUILD_VECTORCombine(), performCommonVectorExtendCombine(), llvm::R600TargetLowering::PerformDAGCombine(), performLDNT1Combine(), PerformMinMaxCombine(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), performSTNT1Combine(), PerformTruncatingStoreCombine(), PerformVECTOR_SHUFFLECombine(), performVECTOR_SHUFFLECombine(), llvm::AArch64TargetLowering::ReconstructShuffle(), ReplaceBITCASTResults(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), scalarizeBinOpOfSplats(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), simplifyDivRem(), simplifyFPBinop(), llvm::TargetLowering::SimplifyMultipleUseDemandedBits(), llvm::X86TargetLowering::SimplifyMultipleUseDemandedBitsForTargetNode(), simplifyShift(), splitAndLowerShuffle(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), truncateVectorWithPACK(), tryBuildVectorShuffle(), tryToFoldExtendOfConstant(), UnrollVectorOp(), UnrollVectorOverflowOp(), vectorizeExtractedCast(), widenSubVector(), widenVec(), WidenVector(), WidenVector(), and widenVectorToPartType().
getVAArg()
SDValue SelectionDAG::getVAArg (EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue SV, unsigned Align)
VAArg produces a result and token chain, and takes a pointer and a source value as input.
Definition at line 7550 of file SelectionDAG.cpp.
References getNode(), getTargetConstant(), getVTList(), llvm::MVT::i32, llvm::MVT::Other, and llvm::ISD::VAARG.
getValidMaximumShiftAmountConstant()
const APInt * SelectionDAG::getValidMaximumShiftAmountConstant (SDValue V, const APInt & DemandedElts) const
If a SHL/SRA/SRL node V has constant shift amounts that are all less than the element bit-width of the shift node, return the maximum value.
Definition at line 2635 of file SelectionDAG.cpp.
References assert(), llvm::BitWidth, llvm::numbers::e, llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getScalarValueSizeInBits(), getValidShiftAmountConstant(), llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SRL, and llvm::APInt::uge().
Referenced by ComputeNumSignBits(), llvm::TargetLowering::SimplifyDemandedBits(), and llvm::TargetLowering::SimplifyMultipleUseDemandedBits().
getValidMinimumShiftAmountConstant()
const APInt * SelectionDAG::getValidMinimumShiftAmountConstant (SDValue V, const APInt & DemandedElts) const
If a SHL/SRA/SRL node V has constant shift amounts that are all less than the element bit-width of the shift node, return the minimum value.
Definition at line 2606 of file SelectionDAG.cpp.
References assert(), llvm::BitWidth, llvm::numbers::e, llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getScalarValueSizeInBits(), getValidShiftAmountConstant(), llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SRL, llvm::APInt::uge(), and llvm::APInt::ule().
Referenced by computeKnownBits(), and ComputeNumSignBits().
getValidShiftAmountConstant()
const APInt * SelectionDAG::getValidShiftAmountConstant (SDValue V, const APInt & DemandedElts) const
If a SHL/SRA/SRL node V has a constant or splat constant shift amount that is less than the element bit-width of the shift node, return it.
Definition at line 2591 of file SelectionDAG.cpp.
References assert(), llvm::BitWidth, llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getScalarValueSizeInBits(), llvm::isConstOrConstSplat(), llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SRL, and llvm::APInt::ult().
Referenced by combineVectorSignBitsTruncation(), getValidMaximumShiftAmountConstant(), getValidMinimumShiftAmountConstant(), and llvm::TargetLowering::SimplifyDemandedBits().
getValueType()
SDValue SelectionDAG::getValueType (EVT VT)
Definition at line 1666 of file SelectionDAG.cpp.
References llvm::EVT::getSimpleVT(), llvm::EVT::isExtended(), llvm::EVT::isSimple(), N, and llvm::MVT::SimpleTy.
Referenced by addShuffleForVecExtend(), combineShiftRightArithmetic(), combineVectorTruncationWithPACKSS(), convertLocVTToValVT(), customLegalizeToWOpWithSExt(), emitRepmovs(), getAArch64Cmp(), getCopyFromParts(), llvm::RegsForValue::getCopyFromRegs(), getNode(), LowerBUILD_VECTOR_i1(), llvm::VETargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SITargetLowering::LowerCallResult(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::SITargetLowering::LowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerINSERT_VECTOR_ELT_i1(), lowerMSACopyIntr(), llvm::SelectionDAGBuilder::lowerRangeToAssertZExt(), llvm::MSP430TargetLowering::LowerShifts(), llvm::MSP430TargetLowering::LowerSIGN_EXTEND(), llvm::AMDGPUTargetLowering::LowerSIGN_EXTEND_INREG(), llvm::ARMTargetLowering::PerformCMOVCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performGatherLoadCombine(), performLD1Combine(), PerformMinMaxCombine(), performScatterStoreCombine(), performSignExtendInRegCombine(), performST1Combine(), PromoteMaskArithmetic(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::targetShrinkDemandedConstant(), truncateScalarIntegerArg(), UnpackFromArgumentSlot(), UnrollVectorOp(), and unrollVectorShift().
getVectorIdxConstant()
SDValue SelectionDAG::getVectorIdxConstant (uint64_t Val, const SDLoc & DL, bool isTarget = false)
Definition at line 1452 of file SelectionDAG.cpp.
References DL, getConstant(), getDataLayout(), and llvm::TargetLoweringBase::getVectorIdxTy().
Referenced by CollectOpsToWiden(), combineVectorSizedSetCCEquality(), getCopyFromPartsVector(), getCopyToPartsVector(), getNode(), getSplatValue(), matchBinOpReduction(), narrowExtractedVectorBinOp(), llvm::AArch64TargetLowering::PerformDAGCombine(), replaceShuffleOfInsert(), scalarizeBinOpOfSplats(), llvm::TargetLowering::scalarizeVectorStore(), llvm::AMDGPUTargetLowering::splitVector(), SplitVector(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), UnrollVectorOp(), llvm::AMDGPUTargetLowering::WidenOrSplitVectorLoad(), and WidenVector().
getVectorShuffle()
SDValue SelectionDAG::getVectorShuffle (EVT VT, const SDLoc & dl, SDValue N1, SDValue N2, ArrayRef< int > Mask)
Return an ISD::VECTOR_SHUFFLE node.
The number of elements in VT, which must be a vector type, must match the number of mask elements NumElts. An integer mask element equal to -1 is treated as undefined.
Definition at line 1727 of file SelectionDAG.cpp.
References AddNodeIDNode(), llvm::all_of(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), assert(), llvm::ISD::BITCAST, C, commuteShuffle(), llvm::copy(), E, llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), getSplatBuildVector(), llvm::BuildVectorSDNode::getSplatValue(), getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), getVTList(), llvm::TargetLoweringBase::hasVectorBlend(), llvm::SDValue::isUndef(), llvm::BitmaskEnumDetail::Mask(), N, NewSDValueDbgMsg(), llvm::BitVector::none(), Offset, and llvm::ISD::VECTOR_SHUFFLE.
Referenced by addShuffleForVecExtend(), buildFromShuffleMostly(), llvm::TargetLowering::buildLegalVectorShuffle(), BuildVSLDOI(), combineAddOrSubToHADDorHSUB(), combineArithReduction(), combineBasicSADPattern(), combineBVOfConsecutiveLoads(), combineFaddFsub(), combineHorizOpWithShuffle(), combineInsertSubvector(), combineMinMaxReduction(), combinePMULDQ(), combineSelect(), combineShuffle(), combineShuffleOfConcatUndef(), combineShuffleOfSplatVal(), combineSIntToFP(), combineToExtendBoolVectorInReg(), convertShiftLeftToScale(), createVariablePermute(), EltsFromConsecutiveLoads(), foldShuffleOfConcatUndefs(), formSplatFromShuffles(), GeneratePerfectShuffle(), getCommutedVectorShuffle(), getMOVL(), getShuffleHalfVectors(), getShuffleVectorZeroOrUndef(), getSToVPermuted(), getUnpackh(), getUnpackl(), isFNEG(), lower1BitShuffle(), lower256BitShuffle(), LowerAsSplatVectorLoad(), LowerBuildVectorv4x32(), LowerEXTEND_VECTOR_INREG(), LowerMUL(), LowerMULH(), LowerRotate(), LowerScalarImmediateShift(), LowerScalarVariableShift(), LowerShift(), lowerShuffleAsBlend(), lowerShuffleAsBlendAndPermute(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsDecomposedShuffleMerge(), lowerShuffleAsElementInsertion(), lowerShuffleAsLanePermuteAndPermute(), lowerShuffleAsLanePermuteAndRepeatedMask(), lowerShuffleAsLanePermuteAndShuffle(), lowerShuffleAsLanePermuteAndSHUFP(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsRepeatedMaskAndLanePermute(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleAsUNPCKAndPermute(), lowerShuffleAsVTRUNCAndUnpack(), lowerShuffleOfExtractsAsVperm(), lowerShuffleWithUNPCK256(), LowerSIGN_EXTEND(), LowerTruncateVecI1(), LowerUINT_TO_FP_i64(), lowerV16I8Shuffle(), lowerV2I64Shuffle(), lowerV4I32Shuffle(), lowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE_i1(), lowerVSELECTtoVectorShuffle(), LowerVSETCC(), partitionShuffleOfConcats(), performCommonVectorExtendCombine(), performConcatVectorsCombine(), performSelectCombine(), PerformTruncatingStoreCombine(), PerformVECTOR_SHUFFLECombine(), performVECTOR_SHUFFLECombine(), reduceVMULWidth(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::TargetLowering::SimplifyDemandedBits(), splitAndLowerShuffle(), truncateVectorWithPACK(), and vectorizeExtractedCast().
getVRegDbgValue()
SDDbgValue * SelectionDAG::getVRegDbgValue (DIVariable * Var, DIExpression * Expr, unsigned VReg, bool IsIndirect, const DebugLoc & DL, unsigned O)
Creates a VReg SDDbgValue node.
VReg.
Definition at line 8426 of file SelectionDAG.cpp.
References assert(), DL, llvm::SDDbgInfo::getAlloc(), llvm::RISCVFenceField::O, and llvm::SDDbgValue::VREG.
Referenced by llvm::SelectionDAGBuilder::handleDebugValue().
getVScale()
SDValue llvm::SelectionDAG::getVScale (const SDLoc & DL, EVT VT, APInt MulImm) inline
Return a node that represents the runtime scaling 'MulImm * RuntimeVL'.
Definition at line 955 of file SelectionDAG.h.
References assert(), DL, getConstant(), llvm::APInt::getMinSignedBits(), getNode(), llvm::EVT::getSizeInBits(), llvm::APInt::sextOrTrunc(), and llvm::ISD::VSCALE.
Referenced by clampDynamicVectorIndex(), getMemBasePlusOffset(), getNode(), llvm::SelectionDAGBuilder::getValueImpl(), and llvm::TargetLowering::IncrementMemoryAddress().
getVTList() [1/5]
SDVTList SelectionDAG::getVTList (ArrayRef< EVT > VTs)
Definition at line 7843 of file SelectionDAG.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), llvm::copy(), and llvm::ArrayRef< T >::size().
getVTList() [2/5]
SDVTList SelectionDAG::getVTList (EVT VT)
Return an SDVTList that represents the list of values specified.
Definition at line 7779 of file SelectionDAG.cpp.
References makeVTList().
Referenced by AddCombineTo64bitMLAL(), AddCombineTo64BitSMLAL16(), AddCombineTo64bitUMAAL(), llvm::X86TargetLowering::BuildFILD(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), CloneNodeWithValues(), combineADC(), combineAddOrSubToADCOrSBB(), combineADDToADDZE(), CombineBaseUpdate(), combineBitcast(), combineBVZEXTLOAD(), combineCMP(), combineConcatVectorOps(), combineInsertSubvector(), combineSBB(), combineSVEPrefetchVecBaseImmOff(), combineTargetShuffle(), CombineVLDDUP(), combineX86AddSub(), ConvertBooleanCarryToCarryFlag(), ConvertCarryFlagToBooleanCarry(), convertFPToInt(), convertIntToFP(), createLoadLR(), createStoreLR(), EltsFromConsecutiveLoads(), emitCLC(), EmitCmp(), emitComparison(), emitIntrinsicWithCCAndChain(), EmitMaskedTruncSStore(), emitRepmovs(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemchr(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::BPFSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcmp(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcpy(), EmitTest(), EmitTruncSStore(), EmitUnrolledSetTag(), Expand64BitShift(), llvm::TargetLowering::expandFixedPointDiv(), expandIntrinsicWChainHelper(), llvm::TargetLowering::expandMUL_LOHI(), ExpandREAD_REGISTER(), llvm::PPCTargetLowering::expandVSXLoadForLE(), llvm::PPCTargetLowering::expandVSXStoreForLE(), GeneratePerfectShuffle(), getAArch64XALUOOp(), llvm::MipsTargetLowering::getAddrGPRel(), getAddrSpaceCast(), getAssertAlign(), getAtomic(), getAVX2GatherNode(), getBasicBlock(), getBlockAddress(), getBoundedStrlen(), getCALLSEQ_END(), getCALLSEQ_START(), getConstant(), getConstantFP(), getConstantPool(), getCopyFromReg(), llvm::RegsForValue::getCopyFromRegs(), getCopyToReg(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), getFPBinOp(), getFPTernOp(), getFrameIndex(), getGatherNode(), getGlobalAddress(), getIndexedStore(), getJumpTable(), getLabelNode(), getLifetimeNode(), getLoad(), getMachineNode(), getMad64_32(), getMaskedLoad(), getMaskedStore(), getMDNode(), getMergeValues(), getNode(), getPseudoProbeNode(), getRegister(), getRegisterMask(), getScatterNode(), getSrcValue(), getStore(), getTargetIndex(), GetTLSADDR(), getTruncStore(), getVAArg(), getVectorShuffle(), getX86XALUOOp(), legalizeSVEGatherPrefetchOffsVec(), LowerABS(), LowerADDC_ADDE_SUBC_SUBE(), LowerADDSUBCARRY(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), llvm::VETargetLowering::lowerATOMIC_SWAP(), lowerAtomicArithWithLOCK(), lowerBuildVectorAsBroadcast(), llvm::SITargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), LowerCallResult(), LowerCMP_SWAP(), LowerCTLZ(), LowerCTTZ(), llvm::HexagonTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::VETargetLowering::lowerEH_SJLJ_SETJMP(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), LowerINTRINSIC_W_CHAIN(), LowerMGATHER(), LowerMSCATTER(), llvm::SystemZTargetLowering::LowerOperationWrapper(), LowerPARITY(), llvm::HexagonTargetLowering::LowerREADCYCLECOUNTER(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::RISCVTargetLowering::LowerReturn(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), llvm::LanaiTargetLowering::LowerSELECT_CC(), LowerSETCCCARRY(), lowerShuffleAsBroadcast(), LowerStore(), LowerSTORE(), llvm::VETargetLowering::lowerToTLSGeneralDynamicModel(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), lowerUINT_TO_FP_vXi32(), LowerVECTOR_SHUFFLE(), LowerXALUO(), narrowLoadToVZLoad(), PerformADDVecReduce(), llvm::ARMTargetLowering::PerformCMOVCombine(), performCONDCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performGatherLoadCombine(), PerformHWLoopCombine(), performLD1Combine(), performMaskedGatherScatterCombine(), PerformMVEVLDCombine(), performNEONPostLDSTCombine(), performPostLD1Combine(), performScatterStoreCombine(), PerformSETCCCombine(), performSignExtendInRegCombine(), PerformUMLALCombine(), PerformVDUPCombine(), ReplaceCMP_SWAP_128Results(), ReplaceCMP_SWAP_64Results(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), ReplaceLongIntrinsic(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), ReplaceREADCYCLECOUNTER(), llvm::SelectionDAGISel::SelectCodeCommon(), SelectNodeTo(), llvm::HexagonDAGToDAGISel::SelectTypecast(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), llvm::TargetLowering::SimplifySetCC(), and UnrollVectorOverflowOp().
getVTList() [3/5]
SDVTList SelectionDAG::getVTList (EVT VT1, EVT VT2)
Definition at line 7783 of file SelectionDAG.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), and llvm::EVT::getRawBits().
getVTList() [4/5]
SDVTList SelectionDAG::getVTList (EVT VT1, EVT VT2, EVT VT3)
Definition at line 7801 of file SelectionDAG.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), and llvm::EVT::getRawBits().
getVTList() [5/5]
SDVTList SelectionDAG::getVTList (EVT VT1, EVT VT2, EVT VT3, EVT VT4)
Definition at line 7821 of file SelectionDAG.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), and llvm::EVT::getRawBits().
getZeroExtendInReg()
SDValue SelectionDAG::getZeroExtendInReg (SDValue Op, const SDLoc & DL, EVT VT)
Return the expression required to zero extend the Op value assuming it was the smaller SrcTy value.
Definition at line 1274 of file SelectionDAG.cpp.
References llvm::ISD::AND, assert(), llvm::EVT::bitsLE(), DL, getConstant(), llvm::APInt::getLowBitsSet(), getNode(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getVectorElementCount(), llvm::EVT::isInteger(), and llvm::EVT::isVector().
Referenced by combineExtSetcc(), combineStore(), getPtrExtendInReg(), llvm::MSP430TargetLowering::LowerShifts(), LowerStore(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), PromoteMaskArithmetic(), and llvm::TargetLowering::SimplifyDemandedBits().
getZExtOrTrunc()
SDValue SelectionDAG::getZExtOrTrunc (SDValue Op, const SDLoc & DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either zero-extending or truncating it.
Definition at line 1259 of file SelectionDAG.cpp.
References llvm::EVT::bitsGT(), DL, getNode(), llvm::ISD::TRUNCATE, and llvm::ISD::ZERO_EXTEND.
Referenced by combineBitcast(), combineBitcastvxi1(), combineCompareEqual(), combineExtractVectorElt(), combineExtractWithShuffle(), combinePredicateReduction(), combineSelect(), combineSetCCMOVMSK(), combineShiftAnd1ToBitTest(), combineShiftToMULH(), combineShuffleOfScalars(), combineSubToSubus(), createVariablePermute(), earlyExpandDIVFIX(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemchr(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrnlen(), Expand64BitShift(), expandDivFix(), foldAddSubBoolOfMaskedVal(), foldCONCAT_VECTORS(), getPTest(), getPtrExtOrTrunc(), getShiftAmountOperand(), llvm::TargetLowering::getVectorElementPointer(), llvm::TargetLowering::IncrementMemoryAddress(), lowerBALLOTIntrinsic(), LowerBITCAST(), llvm::HexagonTargetLowering::LowerBITCAST(), lowerBuildVectorToBitOp(), LowerBuildVectorv16i8(), lowerFCMPIntrinsic(), LowerFGETSIGN(), llvm::AMDGPUTargetLowering::LowerFP_TO_FP16(), LowerFunnelShift(), lowerICMPIntrinsic(), LowerINTRINSIC_W_CHAIN(), LowerMULH(), llvm::SystemZTargetLowering::LowerOperationWrapper(), LowerShift(), lowerX86CmpEqZeroToCtlzSrl(), llvm::AMDGPUTargetLowering::performMulCombine(), llvm::AMDGPUTargetLowering::performMulhuCombine(), llvm::AMDGPUTargetLowering::performShlCombine(), llvm::AMDGPUTargetLowering::performTruncateCombine(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), and widenCtPop().
hasDebugValues()
bool llvm::SelectionDAG::hasDebugValues () const inline
Return true if there are any SDDbgValue nodes associated with this SelectionDAG.
Definition at line 1645 of file SelectionDAG.h.
References llvm::SDDbgInfo::empty().
Referenced by llvm::ScheduleDAGSDNodes::EmitSchedule().
haveNoCommonBitsSet()
bool SelectionDAG::haveNoCommonBitsSet (SDValue A, SDValue B) const
Return true if A and B have no common bits set.
As an example, this can allow an 'add' to be transformed into an 'or'.
Definition at line 4256 of file SelectionDAG.cpp.
References assert(), B, and computeKnownBits().
Referenced by detectAVGPattern().
InferPtrAlign()
MaybeAlign SelectionDAG::InferPtrAlign (SDValue Ptr) const
Infer alignment of a load / store address.
InferPtrAlignment - Infer alignment of a load / store address.
Return None if it cannot be inferred.
Definition at line 9709 of file SelectionDAG.cpp.
References Align, llvm::commonAlignment(), llvm::computeKnownBits(), llvm::KnownBits::countMinTrailingZeros(), llvm::SDValue::getConstantOperandVal(), getDataLayout(), llvm::MachineFunction::getFrameInfo(), getMachineFunction(), llvm::SDValue::getNode(), llvm::MachineFrameInfo::getObjectAlign(), llvm::SDValue::getOperand(), llvm::DataLayout::getPointerTypeSizeInBits(), llvm::GlobalValue::getType(), isBaseWithConstantOffset(), llvm::TargetLowering::isGAPlusOffset(), llvm::min(), and llvm::None.
Referenced by getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), and LowerAsSplatVectorLoad().
init()
void SelectionDAG::init (MachineFunction & NewMF, OptimizationRemarkEmitter & NewORE, Pass * PassPtr, const TargetLibraryInfo * LibraryInfo, LegacyDivergenceAnalysis * Divergence, ProfileSummaryInfo * PSIin, BlockFrequencyInfo * BFIin)
Prepare this SelectionDAG to process code in the given MachineFunction.
Definition at line 1125 of file SelectionDAG.cpp.
References llvm::Function::getContext(), llvm::MachineFunction::getFunction(), llvm::TargetSubtargetInfo::getSelectionDAGInfo(), getSubtarget(), and llvm::TargetSubtargetInfo::getTargetLowering().
Referenced by llvm::SelectionDAGISel::runOnMachineFunction().
isBaseWithConstantOffset()
bool SelectionDAG::isBaseWithConstantOffset (SDValue Op) const
Return true if the specified operand is an ISD::ADD with a ConstantSDNode on the right-hand side, or if it is an ISD::OR with a ConstantSDNode that is guaranteed to have the same semantics as an ADD.
This handles the equivalence: X|Cst == X+Cst iff X&Cst = 0.
Definition at line 4078 of file SelectionDAG.cpp.
References llvm::ISD::ADD, MaskedValueIsZero(), and llvm::ISD::OR.
Referenced by getBaseWithConstantOffset(), getBaseWithOffsetUsingSplitOR(), InferPtrAlign(), LowerAsSplatVectorLoad(), replaceZeroVectorStore(), and llvm::AVRDAGToDAGISel::SelectAddr().
isConstantFPBuildVectorOrConstantFP()
SDNode * SelectionDAG::isConstantFPBuildVectorOrConstantFP (SDValue N) const
Test whether the given value is a constant FP or similar node.
Definition at line 10096 of file SelectionDAG.cpp.
References llvm::ISD::isBuildVectorOfConstantFPSDNodes(), and N.
Referenced by isConstantValueOfAnyType(), and visitFMinMax().
isConstantIntBuildVectorOrConstantInt()
SDNode * SelectionDAG::isConstantIntBuildVectorOrConstantInt (SDValue N) const
Test whether the given value is a constant int or similar node.
Definition at line 10077 of file SelectionDAG.cpp.
References llvm::ISD::GlobalAddress, llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::TargetLowering::isOffsetFoldingLegal(), N, and llvm::ISD::SPLAT_VECTOR.
Referenced by combinePMULDQ(), foldAddSubOfSignBit(), isConstantValueOfAnyType(), salvageDebugInfo(), and stripConstantMask().
isConstantValueOfAnyType()
bool llvm::SelectionDAG::isConstantValueOfAnyType (SDValue N) const inline
Returns
true if N is any kind of constant or build_vector of constants, int or float. If a vector, it may not necessarily be a splat.
Definition at line 1969 of file SelectionDAG.h.
References isConstantFPBuildVectorOrConstantFP(), isConstantIntBuildVectorOrConstantInt(), and N.
Referenced by llvm::AMDGPUTargetLowering::performSelectCombine(), and simplifySelect().
isEqualTo()
bool SelectionDAG::isEqualTo (SDValue A, SDValue B) const
Test whether two SDValues are known to compare equal.
This is true if they are the same value, or if one is negative zero and the other positive zero.
Definition at line 4241 of file SelectionDAG.cpp.
References B.
Referenced by combineSelect().
isKnownNeverNaN()
bool SelectionDAG::isKnownNeverNaN (SDValue Op, bool SNaN = false, unsigned Depth = 0) const
Test whether the given SDValue is known to never be NaN.
If SNaN is true, returns if Op is known to never be a signaling NaN (it may still be a qNaN).
Definition at line 4090 of file SelectionDAG.cpp.
References llvm::ISD::BUILTIN_OP_END, C, llvm::Depth, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FABS, llvm::ISD::FADD, llvm::ISD::FCANONICALIZE, llvm::ISD::FCEIL, llvm::ISD::FCOPYSIGN, llvm::ISD::FCOS, llvm::ISD::FDIV, llvm::ISD::FEXP, llvm::ISD::FEXP2, llvm::ISD::FFLOOR, llvm::ISD::FLOG, llvm::ISD::FLOG10, llvm::ISD::FLOG2, llvm::ISD::FMA, llvm::ISD::FMAD, llvm::ISD::FMAXIMUM, llvm::ISD::FMAXNUM, llvm::ISD::FMAXNUM_IEEE, llvm::ISD::FMINIMUM, llvm::ISD::FMINNUM, llvm::ISD::FMINNUM_IEEE, llvm::ISD::FMUL, llvm::ISD::FNEARBYINT, llvm::ISD::FNEG, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FPOW, llvm::ISD::FPOWI, llvm::ISD::FREM, llvm::ISD::FRINT, llvm::ISD::FROUND, llvm::ISD::FROUNDEVEN, llvm::ISD::FSIN, llvm::ISD::FSQRT, llvm::ISD::FSUB, llvm::ISD::FTRUNC, getTarget(), llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::TargetLowering::isKnownNeverNaNForTargetNode(), isKnownNeverSNaN(), MaxRecursionDepth, llvm::ISD::SELECT, llvm::ISD::SINT_TO_FP, and llvm::ISD::UINT_TO_FP.
Referenced by combineFMinNumFMaxNum(), combineSelect(), llvm::AMDGPUTargetLowering::isKnownNeverNaNForTargetNode(), llvm::SITargetLowering::isKnownNeverNaNForTargetNode(), isKnownNeverSNaN(), and isLegalToCombineMinNumMaxNum().
isKnownNeverSNaN()
bool llvm::SelectionDAG::isKnownNeverSNaN (SDValue Op, unsigned Depth = 0) const inline
Returns
true if Op is known to never be a signaling NaN.
Definition at line 1812 of file SelectionDAG.h.
References llvm::Depth, and isKnownNeverNaN().
Referenced by llvm::SITargetLowering::isCanonicalized(), and isKnownNeverNaN().
isKnownNeverZero()
bool SelectionDAG::isKnownNeverZero (SDValue Op) const
Test whether the given SDValue is known to contain non-zero value(s).
Definition at line 4219 of file SelectionDAG.cpp.
References assert(), C, llvm::ISD::matchUnaryPredicate(), and llvm::ISD::OR.
Referenced by LowerShift().
isKnownNeverZeroFloat()
bool SelectionDAG::isKnownNeverZeroFloat (SDValue Op) const
Test whether the given floating point SDValue is known to never be positive or negative zero.
Definition at line 4208 of file SelectionDAG.cpp.
References assert(), and C.
Referenced by combineSelect().
isKnownToBeAPowerOfTwo()
bool SelectionDAG::isKnownToBeAPowerOfTwo (SDValue Val) const
Test if the given value is known to have exactly one bit set.
This differs from computeKnownBits in that it doesn't necessarily determine which bit is set.
Definition at line 3480 of file SelectionDAG.cpp.
References llvm::all_of(), llvm::BitWidth, llvm::ISD::BUILD_VECTOR, C, computeKnownBits(), llvm::KnownBits::countMaxPopulation(), llvm::KnownBits::countMinPopulation(), E, llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SDValue::getValueType(), llvm::isConstOrConstSplat(), llvm::SDNode::ops(), llvm::ISD::SHL, and llvm::ISD::SRL.
isSplatValue() [1/2]
bool SelectionDAG::isSplatValue (SDValue V, bool AllowUndefs = false)
Test whether V has a splatted value.
Helper wrapper to main isSplatValue function.
Definition at line 2514 of file SelectionDAG.cpp.
References assert(), llvm::APInt::getAllOnesValue(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::EVT::isScalableVector(), isSplatValue(), and llvm::EVT::isVector().
isSplatValue() [2/2]
bool SelectionDAG::isSplatValue (SDValue V, const APInt & DemandedElts, APInt & UndefElts, unsigned Depth = 0)
Test whether V has a splatted value for all the demanded elements.
isSplatValue - Return true if the vector V has the same value across all DemandedElts.
On success UndefElts will indicate the elements that have UNDEF values instead of the splat value, this is only guaranteed to be correct for DemandedElts.
NOTE: The function will return true for a demanded splat of UNDEF values.
For scalable vectors it does not make sense to specify which elements are demanded or undefined, therefore they are simply ignored.
Definition at line 2412 of file SelectionDAG.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, assert(), llvm::ISD::BUILD_VECTOR, llvm::Depth, llvm::ISD::EXTRACT_SUBVECTOR, llvm::APInt::extractBits(), llvm::APInt::getAllOnesValue(), llvm::APInt::getBitWidth(), llvm::SDValue::getConstantOperandVal(), llvm::APInt::getNullValue(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::EVT::isScalableVector(), llvm::SDValue::isUndef(), llvm::EVT::isVector(), llvm::BitmaskEnumDetail::Mask(), MaxRecursionDepth, llvm::APInt::setBit(), llvm::APInt::shl(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SPLAT_VECTOR, llvm::ISD::SUB, llvm::ISD::TRUNCATE, llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::ZERO_EXTEND, and llvm::APInt::zextOrSelf().
Referenced by getSplatSourceVector(), isSplatValue(), LowerRotate(), and llvm::X86TargetLowering::shouldProduceAndByConstByHoistingConstFromShiftsLHSOfAnd().
isUndef()
bool SelectionDAG::isUndef (unsigned Opcode, ArrayRef< SDValue > Ops)
Return true if the result of this operation is always undefined.
Definition at line 4906 of file SelectionDAG.cpp.
References llvm::any_of(), assert(), llvm::SDValue::getNode(), llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::isNullConstant(), llvm::SDValue::isUndef(), llvm::SDNode::op_values(), llvm::ISD::SDIV, llvm::ArrayRef< T >::size(), llvm::ISD::SREM, llvm::ISD::UDIV, and llvm::ISD::UREM.
Referenced by FoldConstantArithmetic(), FoldConstantVectorArithmetic(), and simplifyDivRem().
Legalize()
void SelectionDAG::Legalize ()
This transforms the SelectionDAG into a SelectionDAG that is compatible with the target instruction selector, as indicated by the TargetLowering object.
This is the entry point for the file.
Note that this is an involved process that may invalidate pointers into the graph.
Definition at line 5148 of file LegalizeDAG.cpp.
References allnodes_begin(), allnodes_end(), AssignTopologicalOrder(), DeleteNode(), E, llvm::SmallPtrSetImpl< PtrType >::erase(), llvm::SDValue::getNode(), getNode(), getRoot(), llvm::SmallPtrSetImpl< PtrType >::insert(), N, and RemoveDeadNodes().
LegalizeOp()
bool SelectionDAG::LegalizeOp (SDNode * N, SmallSetVector< SDNode *, 16 > & UpdatedNodes)
Transforms a SelectionDAG node and any operands to it into a node that is compatible with the target instruction selector, as indicated by the TargetLowering object.
Returns
true if N is a valid, legal node after calling this.
This essentially runs a single recursive walk of the Legalize process over the given node (and its operands). This can be used to incrementally legalize the DAG. All of the nodes which are directly replaced, potentially including N, are added to the output parameter UpdatedNodes so that the delta to the DAG can be understood by the caller.
When this returns false, N has been legalized in a way that make the pointer passed in no longer valid. It may have even been deleted from the DAG, and so it shouldn't be used further. When this returns true, the N passed in is a legal node, and can be immediately processed as such. This may still have done some work on the DAG, and will still populate UpdatedNodes with any new nodes replacing those originally in the DAG.
Definition at line 5197 of file LegalizeDAG.cpp.
References llvm::SmallPtrSetImpl< PtrType >::count(), llvm::SmallPtrSetImpl< PtrType >::insert(), and N.
LegalizeTypes()
bool SelectionDAG::LegalizeTypes ()
This transforms the SelectionDAG into a SelectionDAG that only uses types natively supported by the target.
Returns "true" if it made any changes.
Note that this is an involved process that may invalidate pointers into the graph.
Definition at line 1058 of file LegalizeTypes.cpp.
References llvm::DAGTypeLegalizer::run().
LegalizeVectors()
bool SelectionDAG::LegalizeVectors ()
This transforms the SelectionDAG into a SelectionDAG that only uses vector math operations supported by the target.
This is necessary as a separate step from Legalize because unrolling a vector operation can introduce illegal types, which requires running LegalizeTypes again.
This returns true if it made any changes; in that case, LegalizeTypes is called again before Legalize.
Note that this is an involved process that may invalidate pointers into the graph.
Definition at line 1481 of file LegalizeVectorOps.cpp.
LLVM_ATTRIBUTE_DEPRECATED() [1/4]
llvm::SelectionDAG::LLVM_ATTRIBUTE_DEPRECATED (inline SDValue getMemIntrinsicNode unsigned Opcode, const SDLoc &dl, SDVTList VTList, ArrayRef< SDValue > Ops, EVT MemVT, MachinePointerInfo PtrInfo, unsigned Alignment, MachineMemOperand::Flags Flags=MachineMemOperand::MOLoad| MachineMemOperand::MOStore, uint64_t Size=0, const AAMDNodes &AAInfo=AAMDNodes(), "") inline
Definition at line 1183 of file SelectionDAG.h.
References getMemIntrinsicNode(), and llvm::Check::Size.
LLVM_ATTRIBUTE_DEPRECATED() [2/4]
llvm::SelectionDAG::LLVM_ATTRIBUTE_DEPRECATED (SDValue getMemcpySDValue Chain, const SDLoc &dl, SDValue Dst, SDValue Src, SDValue Size, unsigned Align, bool isVol, bool AlwaysInline, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo, "Use the version that takes Align instead") inline
Definition at line 1020 of file SelectionDAG.h.
References getMemcpy(), and llvm::Check::Size.
LLVM_ATTRIBUTE_DEPRECATED() [3/4]
llvm::SelectionDAG::LLVM_ATTRIBUTE_DEPRECATED (SDValue getMemmoveSDValue Chain, const SDLoc &dl, SDValue Dst, SDValue Src, SDValue Size, unsigned Align, bool isVol, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo, "Use the version that takes Align instead") inline
Definition at line 1038 of file SelectionDAG.h.
References getMemmove(), and llvm::Check::Size.
LLVM_ATTRIBUTE_DEPRECATED() [4/4]
llvm::SelectionDAG::LLVM_ATTRIBUTE_DEPRECATED (SDValue getMemsetSDValue Chain, const SDLoc &dl, SDValue Dst, SDValue Src, SDValue Size, unsigned Align, bool isVol, bool isTailCall, MachinePointerInfo DstPtrInfo, "Use the version that takes Align instead") inline
Definition at line 1053 of file SelectionDAG.h.
References getMemset(), and llvm::Check::Size.
makeEquivalentMemoryOrdering() [1/2]
SDValue SelectionDAG::makeEquivalentMemoryOrdering (LoadSDNode * OldLoad, SDValue NewMemOp)
If an existing load has uses of its chain, create a token factor node with that chain and the new memory node's chain and update users of the old chain to the token factor.
This ensures that the new memory node will have the same relative memory dependency position as the old load. Returns the new merged load chain.
Definition at line 9047 of file SelectionDAG.cpp.
References assert(), llvm::SDValue::getNode(), llvm::SDValue::getValue(), and makeEquivalentMemoryOrdering().
makeEquivalentMemoryOrdering() [2/2]
SDValue SelectionDAG::makeEquivalentMemoryOrdering (SDValue OldChain, SDValue NewMemOpChain)
If an existing load has uses of its chain, create a token factor node with that chain and the new memory node's chain and update users of the old chain to the token factor.
This ensures that the new memory node will have the same relative memory dependency position as the old load. Returns the new merged load chain.
Definition at line 9029 of file SelectionDAG.cpp.
References assert(), getNode(), llvm::SDValue::getValueType(), llvm::MVT::Other, ReplaceAllUsesOfValueWith(), llvm::ISD::TokenFactor, UpdateNodeOperands(), and llvm::SDValue::use_empty().
Referenced by combineStore(), EltsFromConsecutiveLoads(), lowerShuffleAsBroadcast(), makeEquivalentMemoryOrdering(), narrowExtractedVectorLoad(), and llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode().
MaskedValueIsAllOnes()
bool SelectionDAG::MaskedValueIsAllOnes (SDValue Op, const APInt & Mask, unsigned Depth = 0) const
Return true if '(Op & Mask) == Mask'.
MaskedValueIsAllOnes - Return true if '(Op & Mask) == Mask'.
Op and Mask are known to be the same type.
Definition at line 2403 of file SelectionDAG.cpp.
References computeKnownBits(), llvm::Depth, and llvm::BitmaskEnumDetail::Mask().
MaskedValueIsZero() [1/2]
bool SelectionDAG::MaskedValueIsZero (SDValue V, const APInt & Mask, const APInt & DemandedElts, unsigned Depth = 0) const
Return true if 'Op & Mask' is known to be zero in DemandedElts.
MaskedValueIsZero - Return true if 'V & Mask' is known to be zero in DemandedElts.
We use this predicate to simplify operations downstream. Op and Mask are known to be the same type.
We use this predicate to simplify operations downstream. Mask is known to be zero for bits that V cannot have.
Definition at line 2396 of file SelectionDAG.cpp.
References computeKnownBits(), llvm::Depth, and llvm::BitmaskEnumDetail::Mask().
MaskedValueIsZero() [2/2]
bool SelectionDAG::MaskedValueIsZero (SDValue V, const APInt & Mask, unsigned Depth = 0) const
Return true if 'Op & Mask' is known to be zero.
MaskedValueIsZero - Return true if 'V & Mask' is known to be zero.
We use this predicate to simplify operations downstream. Op and Mask are known to be the same type.
We use this predicate to simplify operations downstream. Mask is known to be zero for bits that V cannot have.
Definition at line 2388 of file SelectionDAG.cpp.
References computeKnownBits(), llvm::Depth, and llvm::BitmaskEnumDetail::Mask().
Referenced by llvm::SelectionDAGISel::CheckAndMask(), combineAnd(), combineMulToPMADDWD(), combineMulToPMULDQ(), combineOr(), combineTargetShuffle(), combineVectorPack(), combineZext(), EmitCmp(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::TargetLowering::expandMUL_LOHI(), getFauxShuffleMask(), isBaseWithConstantOffset(), isTruncWithZeroHighBitsInput(), LowerAndToBT(), LowerPARITY(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), matchLSNode(), matchShuffleWithPACK(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), PerformORCombineToBFI(), PerformShiftCombine(), performSRLCombine(), ShrinkLoadReplaceStoreWithStore(), SignBitIsZero(), and llvm::TargetLowering::SimplifySetCC().
matchBinOpReduction()
SDValue SelectionDAG::matchBinOpReduction (SDNode * Extract, ISD::NodeType & BinOp, ArrayRef< ISD::NodeType > CandidateBinOps, bool AllowPartials = false)
Match a binop + shuffle pyramid that represents a horizontal reduction over the elements of a vector starting from the EXTRACT_VECTOR_ELT node /p Extract.
The reduction must use one of the opcodes listed in /p CandidateBinOps and on success /p BinOp will contain the matching opcode. Returns the vector that is being reduced on, or SDValue() if a reduction was not matched. If AllowPartials is set then in the case of a reduction pattern that only matches the first few stages, the extracted subvector of the start of the reduction is returned.
Definition at line 9447 of file SelectionDAG.cpp.
References llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FADD, llvm::SDValue::getConstantOperandAPInt(), getContext(), llvm::ShuffleVectorSDNode::getMaskElt(), getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarType(), llvm::SDValue::getValueType(), getVectorIdxConstant(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::SDNodeFlags::hasAllowReassociation(), llvm::SDNodeFlags::hasNoSignedZeros(), Index, llvm::TargetLoweringBase::isExtractSubvectorCheap(), llvm::isNullConstant(), llvm_unreachable, llvm::Log2_32(), and llvm::none_of().
Referenced by combineArithReduction(), combineBasicSADPattern(), combineMinMaxReduction(), combinePredicateReduction(), and MatchVectorAllZeroTest().
MorphNodeTo()
SDNode * SelectionDAG::MorphNodeTo (SDNode * N, unsigned Opc, SDVTList VTs, ArrayRef< SDValue > Ops)
This mutates the specified node to have the specified return type, opcode, and operands.
MorphNodeTo - This mutates the specified node to have the specified return type, opcode, and operands.
Note that MorphNodeTo returns the resultant node. If there is already a node of the specified opcode and operands, it returns that node instead of the current one. Note that the SDLoc need not be the same.
Using MorphNodeTo is faster than creating a new node and swapping it in with ReplaceAllUsesWith both because it often avoids allocating a new node, and because it doesn't require CSE recalculation for any of the node's users.
However, note that MorphNodeTo recursively deletes dead nodes from the DAG. As a consequence it isn't appropriate to use from within the DAG combiner or the legalizer which maintain worklists that would need to be updated when deleting things.
Definition at line 8116 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, llvm::SmallPtrSetImplBase::empty(), llvm::MVT::Glue, I, llvm::SmallPtrSetImpl< PtrType >::insert(), N, llvm::SDVTList::NumVTs, llvm::SmallVectorTemplateBase< T, bool >::push_back(), RemoveDeadNodes(), llvm::Use::set(), llvm::SDNode::use_empty(), and llvm::SDVTList::VTs.
Referenced by CloneNodeWithValues(), SelectNodeTo(), and llvm::HexagonDAGToDAGISel::SelectTypecast().
mutateStrictFPToFP()
SDNode * SelectionDAG::mutateStrictFPToFP (SDNode * Node)
Mutate the specified strict FP node to its non-strict equivalent, unlinking the node from its chain and dropping the metadata arguments.
The node must be a strict FP node.
Definition at line 8169 of file SelectionDAG.cpp.
operator=()
SelectionDAG& llvm::SelectionDAG::operator= (const SelectionDAG &) delete
RemoveDeadNode()
void SelectionDAG::RemoveDeadNode (SDNode * N)
Remove the specified node from the system.
If any of its operands then becomes dead, remove them as well. Inform UpdateListener for each node deleted.
Definition at line 851 of file SelectionDAG.cpp.
References llvm::NVPTXISD::Dummy, getRoot(), N, and RemoveDeadNodes().
Referenced by foldMaskAndShiftToExtract(), foldMaskAndShiftToScale(), foldMaskedShiftToBEXTR(), foldMaskedShiftToScaledMask(), llvm::TargetLowering::getCheaperNegatedExpression(), llvm::TargetLowering::getNegatedExpression(), llvm::SelectionDAGISel::ReplaceNode(), llvm::HexagonDAGToDAGISel::SelectBrevLdIntrinsic(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::HexagonDAGToDAGISel::SelectIndexedLoad(), llvm::AVRDAGToDAGISel::selectIndexedLoad(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), llvm::HexagonDAGToDAGISel::SelectIntrinsicWChain(), llvm::HexagonDAGToDAGISel::SelectNewCircIntrinsic(), SelectNodeTo(), llvm::HvxSelector::selectVAlign(), and llvm::HexagonDAGToDAGISel::tryLoadOfLoadIntrinsic().
RemoveDeadNodes() [1/2]
void SelectionDAG::RemoveDeadNodes ()
This method deletes all unreachable nodes in the SelectionDAG.
RemoveDeadNodes - This method deletes all unreachable nodes in the SelectionDAG.
Definition at line 797 of file SelectionDAG.cpp.
References llvm::NVPTXISD::Dummy, and getRoot().
Referenced by Legalize(), MorphNodeTo(), and RemoveDeadNode().
RemoveDeadNodes() [2/2]
void SelectionDAG::RemoveDeadNodes (SmallVectorImpl< SDNode * > & DeadNodes)
This method deletes the unreachable nodes in the given list, and any nodes that become unreachable as a result.
RemoveDeadNodes - This method deletes the unreachable nodes in the given list, and any nodes that become unreachable as a result.
Definition at line 817 of file SelectionDAG.cpp.
References llvm::ISD::DELETED_NODE, E, llvm::SmallVectorBase< Size_T >::empty(), I, N, llvm::SelectionDAG::DAGUpdateListener::Next, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::Use::set(), and llvm::SDNode::use_empty().
ReplaceAllUsesOfValuesWith()
void SelectionDAG::ReplaceAllUsesOfValuesWith (const SDValue * From, const SDValue * To, unsigned Num)
Like ReplaceAllUsesOfValueWith, but for multiple values at once.
ReplaceAllUsesOfValuesWith - Replace any uses of From with To, leaving uses of other values produced by From.getNode() alone.
This correctly handles the case where there is an overlap between the From values and the To values.
The same value may appear in both the From and To list. The Deleted vector is handled the same way as for ReplaceAllUsesWith.
Definition at line 8869 of file SelectionDAG.cpp.
References E, From, ReplaceAllUsesOfValueWith(), llvm::Use::set(), llvm::sort(), transferDbgValues(), llvm::SDNode::use_begin(), llvm::SDNode::use_end(), and Uses.
Referenced by llvm::SelectionDAGISel::ReplaceUses().
ReplaceAllUsesOfValueWith()
void SelectionDAG::ReplaceAllUsesOfValueWith (SDValue From, SDValue To)
Replace any uses of From with To, leaving uses of other values produced by From.getNode() alone.
ReplaceAllUsesOfValueWith - Replace any uses of From with To, leaving uses of other values produced by From.getNode() alone.
The Deleted vector is handled the same way as for ReplaceAllUsesWith.
Definition at line 8729 of file SelectionDAG.cpp.
References From, getRoot(), llvm::SDNode::use_iterator::getUse(), llvm::SDNode::isDivergent(), ReplaceAllUsesWith(), llvm::Use::set(), setRoot(), transferDbgValues(), and updateDivergence().
Referenced by AddCombineTo64bitMLAL(), AddCombineTo64BitSMLAL16(), AddCombineTo64bitUMAAL(), adjustSubwordCmp(), combineBitcast(), combineCarryDiamond(), combineConcatVectorOps(), combineCVTP2I_CVTTP2I(), combineCVTPH2PS(), combineEXTEND_VECTOR_INREG(), combineExtractWithShuffle(), combineInsertSubvector(), combineMOVDQ2Q(), combineSetCCAtomicArith(), combineSIntToFP(), combineTargetShuffle(), combineVSelectToBLENDV(), combineX86INT_TO_FP(), emitIntrinsicWithCCAndChain(), EmitTest(), lowerBuildVectorAsBroadcast(), llvm::HexagonTargetLowering::LowerDYNAMIC_STACKALLOC(), makeEquivalentMemoryOrdering(), llvm::PPCTargetLowering::PerformDAGCombine(), performDivRemCombine(), PerformHWLoopCombine(), performIntToFpCombine(), PerformORCombineToSMULWBT(), PerformSplittingToWideningLoad(), llvm::AMDGPUTargetLowering::performStoreCombine(), PerformVDUPCombine(), PerformVMOVhrCombine(), PerformVMOVrhCombine(), PerformVMOVRRDCombine(), ReplaceAllUsesOfValuesWith(), llvm::SelectionDAGISel::ReplaceUses(), SkipExtensionForVMULL(), tryToFoldExtOfExtload(), tryToFoldExtOfLoad(), and tryToFoldExtOfMaskedLoad().
ReplaceAllUsesWith() [1/3]
void SelectionDAG::ReplaceAllUsesWith (SDNode * From, const SDValue * To)
ReplaceAllUsesWith - Modify anything using 'From' to use 'To' instead.
This can cause recursive merging of nodes in the DAG.
This version can replace From with any result values. To must match the number and types of values returned by From.
Definition at line 8682 of file SelectionDAG.cpp.
References llvm::numbers::e, From, getNode(), getRoot(), llvm::SDNode::use_iterator::getUse(), llvm::SDNode::isDivergent(), ReplaceAllUsesWith(), llvm::Use::set(), setRoot(), transferDbgValues(), and updateDivergence().
ReplaceAllUsesWith() [2/3]
void SelectionDAG::ReplaceAllUsesWith (SDNode * From, SDNode * To)
ReplaceAllUsesWith - Modify anything using 'From' to use 'To' instead.
This can cause recursive merging of nodes in the DAG.
This version assumes that for each value of From, there is a corresponding value in To in the same position with the same type.
Definition at line 8626 of file SelectionDAG.cpp.
References assert(), llvm::numbers::e, From, getNode(), getRoot(), llvm::SDNode::use_iterator::getUse(), llvm::SDNode::getValueType(), llvm::SDNode::isDivergent(), setRoot(), transferDbgValues(), and updateDivergence().
ReplaceAllUsesWith() [3/3]
void SelectionDAG::ReplaceAllUsesWith (SDValue FromN, SDValue To)
Modify anything using 'From' to use 'To' instead.
ReplaceAllUsesWith - Modify anything using 'From' to use 'To' instead.
This can cause recursive merging of nodes in the DAG. Use the first version if 'From' is known to have a single result, use the second if you have two nodes with identical results (or if 'To' has a superset of the results of 'From'), use the third otherwise.
These methods all take an optional UpdateListener, which (if not null) is informed about nodes that are deleted and modified due to recursive changes in the dag.
These functions only replace all existing uses. It's possible that as these replacements are being performed, CSE may cause the From node to be given new uses. These new uses of From are left in place, and not automatically transferred to To.
This can cause recursive merging of nodes in the DAG.
This version assumes From has a single result value.
Definition at line 8575 of file SelectionDAG.cpp.
References assert(), From, llvm::SDValue::getNode(), llvm::SDValue::getResNo(), getRoot(), llvm::SDNode::use_iterator::getUse(), llvm::SDNode::isDivergent(), llvm::Use::set(), setRoot(), transferDbgValues(), and updateDivergence().
Referenced by emitComparison(), foldMaskAndShiftToExtract(), foldMaskAndShiftToScale(), foldMaskedShiftToBEXTR(), foldMaskedShiftToScaledMask(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), PerformBFICombine(), performCONDCombine(), llvm::AMDGPUTargetLowering::performFNegCombine(), PerformHWLoopCombine(), PerformLongShiftCombine(), PerformSplittingToNarrowingStores(), ReplaceAllUsesOfValueWith(), ReplaceAllUsesWith(), llvm::SelectionDAGISel::ReplaceNode(), llvm::SelectionDAGISel::ReplaceUses(), and SelectNodeTo().
RepositionNode()
void llvm::SelectionDAG::RepositionNode (allnodes_iterator Position, SDNode * N) inline
Move node N in the AllNodes list to be immediately before the given iterator Position.
This may be used to update the topological ordering when the list of nodes is modified.
Definition at line 1611 of file SelectionDAG.h.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::insert(), N, and llvm::iplist_impl< IntrusiveListT, TraitsT >::remove().
Referenced by insertDAGNode().
salvageDebugInfo()
void SelectionDAG::salvageDebugInfo (SDNode & N)
To be invoked on an SDNode that is slated to be erased.
This function mirrors llvm::salvageDebugInfo.
Definition at line 8496 of file SelectionDAG.cpp.
References llvm::ISD::ADD, AddDbgValue(), llvm::dbgs(), getDbgValue(), GetDbgValues(), llvm::SDValue::getNode(), llvm::SDValue::getResNo(), isConstantIntBuildVectorOrConstantInt(), LLVM_DEBUG, N, Offset, llvm::DIExpression::prepend(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::DIExpression::StackValue.
Referenced by llvm::SelectionDAGISel::SelectCodeCommon().
SelectNodeTo() [1/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT)
These are used for target selectors to mutate the specified node to have the specified return type, Target opcode, and operands.
SelectNodeTo - These are wrappers around MorphNodeTo that accept a machine opcode.
Note that target opcodes are stored as ~TargetOpcode in the node opcode field. The resultant node is returned.
Definition at line 8009 of file SelectionDAG.cpp.
References getVTList(), N, and llvm::None.
Referenced by SelectNodeTo(), tryBitfieldInsertOpFromOr(), and tryBitfieldInsertOpFromOrAndImm().
SelectNodeTo() [2/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT, ArrayRef< SDValue > Ops)
Definition at line 8038 of file SelectionDAG.cpp.
References getVTList(), N, and SelectNodeTo().
SelectNodeTo() [3/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT, SDValue Op1)
Definition at line 8015 of file SelectionDAG.cpp.
References getVTList(), N, and SelectNodeTo().
SelectNodeTo() [4/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT, SDValue Op1, SDValue Op2)
Definition at line 8022 of file SelectionDAG.cpp.
References getVTList(), N, and SelectNodeTo().
SelectNodeTo() [5/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT, SDValue Op1, SDValue Op2, SDValue Op3)
Definition at line 8030 of file SelectionDAG.cpp.
References getVTList(), N, and SelectNodeTo().
SelectNodeTo() [6/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT1, EVT VT2)
Definition at line 8050 of file SelectionDAG.cpp.
References getVTList(), N, llvm::None, and SelectNodeTo().
SelectNodeTo() [7/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT1, EVT VT2, ArrayRef< SDValue > Ops)
Definition at line 8044 of file SelectionDAG.cpp.
References getVTList(), N, and SelectNodeTo().
SelectNodeTo() [8/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT1, EVT VT2, EVT VT3, ArrayRef< SDValue > Ops)
Definition at line 8056 of file SelectionDAG.cpp.
References getVTList(), N, and SelectNodeTo().
SelectNodeTo() [9/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT1, EVT VT2, SDValue Op1, SDValue Op2)
Definition at line 8063 of file SelectionDAG.cpp.
References getVTList(), N, and SelectNodeTo().
SelectNodeTo() [10/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, SDVTList VTs, ArrayRef< SDValue > Ops)
Definition at line 8071 of file SelectionDAG.cpp.
References MorphNodeTo(), N, RemoveDeadNode(), and ReplaceAllUsesWith().
setFlagInserter()
void llvm::SelectionDAG::setFlagInserter (FlagInserter * FI) inline
Definition at line 460 of file SelectionDAG.h.
Referenced by llvm::SelectionDAG::FlagInserter::FlagInserter(), and llvm::SelectionDAG::FlagInserter::~FlagInserter().
setFunctionLoweringInfo()
void llvm::SelectionDAG::setFunctionLoweringInfo (FunctionLoweringInfo * FuncInfo) inline
Definition at line 436 of file SelectionDAG.h.
setGraphAttrs()
void SelectionDAG::setGraphAttrs (const SDNode * N, const char * Attrs)
Set graph attributes for a node. (eg. "color=red".)
setGraphAttrs - Set graph attributes for a node.
(eg. "color=red".)
Definition at line 195 of file SelectionDAGPrinter.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, llvm::errs(), N, and NodeGraphAttrs.
setGraphColor()
void SelectionDAG::setGraphColor (const SDNode * N, const char * Color)
Convenience for setting node color attribute.
setGraphColor - Convenience for setting node color attribute.
Definition at line 225 of file SelectionDAGPrinter.cpp.
References llvm::errs(), N, and NodeGraphAttrs.
setNodeMemRefs()
void SelectionDAG::setNodeMemRefs (MachineSDNode * N, ArrayRef< MachineMemOperand * > NewMemRefs)
Mutate the specified machine node's memory references to the provided list.
Definition at line 7985 of file SelectionDAG.cpp.
References llvm::copy(), llvm::ArrayRef< T >::empty(), N, and llvm::ArrayRef< T >::size().
Referenced by CloneNodeWithValues(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForSetTag(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), ReplaceCMP_SWAP_128Results(), ReplaceCMP_SWAP_64Results(), llvm::HexagonDAGToDAGISel::SelectBrevLdIntrinsic(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::HexagonDAGToDAGISel::SelectIndexedLoad(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), and llvm::X86InstrInfo::unfoldMemoryOperand().
setRoot()
const SDValue& llvm::SelectionDAG::setRoot (SDValue N) inline
Set the current root tag of the SelectionDAG.
Definition at line 529 of file SelectionDAG.h.
References assert(), llvm::checkForCycles(), N, and llvm::MVT::Other.
Referenced by llvm::SelectionDAGBuilder::LowerDeoptimizingReturn(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::SelectionDAGBuilder::lowerInvokable(), ReplaceAllUsesOfValueWith(), ReplaceAllUsesWith(), llvm::DAGTypeLegalizer::run(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTable(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), llvm::SelectionDAGBuilder::visitSPDescriptorFailure(), and llvm::SelectionDAGBuilder::visitSwitchCase().
setSubgraphColor()
void SelectionDAG::setSubgraphColor (SDNode * N, const char * Color)
Convenience for setting subgraph color attribute.
setSubgraphColor - Convenience for setting subgraph color attribute.
Definition at line 269 of file SelectionDAGPrinter.cpp.
References llvm::errs(), and N.
shouldOptForSize()
bool SelectionDAG::shouldOptForSize () const
Definition at line 1150 of file SelectionDAG.cpp.
References llvm::MachineBasicBlock::getBasicBlock(), llvm::MachineFunction::getFunction(), llvm::Function::hasOptSize(), llvm::FunctionLoweringInfo::MBB, and llvm::shouldOptimizeForSize().
Referenced by combineX86ShuffleChain(), ExpandPowI(), getConstantPool(), LowerAndToBT(), lowerBuildVectorAsBroadcast(), LowerFunnelShift(), lowerShuffleAsBlend(), shouldLowerMemFuncForSize(), llvm::SelectionDAGISel::shouldOptForSize(), and shouldUseHorizontalOp().
SignBitIsZero()
bool SelectionDAG::SignBitIsZero (SDValue Op, unsigned Depth = 0) const
Return true if the sign bit of Op is known to be zero.
SignBitIsZero - Return true if the sign bit of Op is known to be zero.
We use this predicate to simplify operations downstream.
Definition at line 2380 of file SelectionDAG.cpp.
References llvm::BitWidth, llvm::Depth, llvm::APInt::getSignMask(), and MaskedValueIsZero().
Referenced by canReduceVMulWidth(), combineUIntToFP(), getCmp(), and LowerVSETCC().
simplifyFPBinop()
SDValue SelectionDAG::simplifyFPBinop (unsigned Opcode, SDValue X, SDValue Y, SDNodeFlags Flags)
Try to simplify a floating-point binary operation into 1 of its operands or a constant.
Definition at line 7505 of file SelectionDAG.cpp.
References llvm::ISD::FADD, llvm::ISD::FDIV, llvm::ISD::FMUL, llvm::ISD::FSUB, getConstantFP(), getUNDEF(), llvm::ConstantFPSDNode::getValueAPF(), llvm::SDNodeFlags::hasNoInfs(), llvm::SDNodeFlags::hasNoNaNs(), llvm::SDNodeFlags::hasNoSignedZeros(), llvm::isConstOrConstSplatFP(), llvm::APFloat::isExactlyValue(), llvm::APFloat::isInfinity(), llvm::APFloat::isNaN(), llvm::APFloat::isNegZero(), llvm::APFloat::isPosZero(), llvm::APFloat::isZero(), X, llvm::SystemZISD::XC, and Y.
Referenced by getNode().
simplifySelect()
SDValue SelectionDAG::simplifySelect (SDValue Cond, SDValue TVal, SDValue FVal)
Try to simplify a select/vselect into 1 of its operands or a constant.
Definition at line 7451 of file SelectionDAG.cpp.
References Cond, F, isConstantValueOfAnyType(), and T.
Referenced by combineSelect(), and getNode().
simplifyShift()
SDValue SelectionDAG::simplifyShift (SDValue X, SDValue Y)
Try to simplify a shift into 1 of its operands or a constant.
Definition at line 7481 of file SelectionDAG.cpp.
References getConstant(), getUNDEF(), llvm::isNullOrNullSplat(), llvm::ISD::matchUnaryPredicate(), X, and Y.
Referenced by getNode().
SplitVector() [1/2]
std::pair<SDValue, SDValue> llvm::SelectionDAG::SplitVector (const SDValue & N, const SDLoc & DL) inline
Split the vector with EXTRACT_SUBVECTOR and return the low/high part.
Definition at line 1929 of file SelectionDAG.h.
References DL, GetSplitDestVTs(), N, and SplitVector().
SplitVector() [2/2]
std::pair< SDValue, SDValue > SelectionDAG::SplitVector (const SDValue & N, const SDLoc & DL, const EVT & LoVT, const EVT & HiVT)
Split the vector with EXTRACT_SUBVECTOR using the provides VTs and return the low/high part.
SplitVector - Split the vector with EXTRACT_SUBVECTOR and return the low/high part.
Definition at line 9790 of file SelectionDAG.cpp.
References assert(), DL, llvm::ISD::EXTRACT_SUBVECTOR, getNode(), getVectorIdxConstant(), llvm::EVT::getVectorMinNumElements(), llvm::MipsISD::Hi, llvm::EVT::isScalableVector(), llvm::MipsISD::Lo, and N.
Referenced by combineHorizOpWithShuffle(), combinePredicateReduction(), getPMOVMSKB(), LowerVectorAllZero(), llvm::X86TargetLowering::ReplaceNodeResults(), SplitVector(), and SplitVectorOperand().
SplitVectorOperand()
std::pair<SDValue, SDValue> llvm::SelectionDAG::SplitVectorOperand (const SDNode * N, unsigned OpNo) inline
Split the node's operand with EXTRACT_SUBVECTOR and return the low/high part.
Definition at line 1937 of file SelectionDAG.h.
References N, and SplitVector().
Referenced by LowerCVTPS2PH(), llvm::X86TargetLowering::ReplaceNodeResults(), ReplaceReductionResults(), llvm::SITargetLowering::splitBinaryVectorOp(), llvm::SITargetLowering::splitTernaryVectorOp(), and llvm::SITargetLowering::splitUnaryVectorOp().
transferDbgValues()
void SelectionDAG::transferDbgValues (SDValue From, SDValue To, unsigned OffsetInBits = 0, unsigned SizeInBits = 0, bool InvalidateDbg = true)
Transfer debug values from one node to another, while optionally generating fragment expressions for split-up values.
If InvalidateDbg is set, debug values are invalidated after they are transferred.
Definition at line 8436 of file SelectionDAG.cpp.
References AddDbgValue(), assert(), llvm::DIExpression::createFragmentExpression(), From, getDbgValue(), GetDbgValues(), llvm::SDNode::getHasDebugValue(), llvm::SDNode::getIROrder(), llvm::SDValue::getNode(), llvm::SDValue::getResNo(), llvm::max(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SDDbgValue::SDNODE.
Referenced by getNode(), ReplaceAllUsesOfValuesWith(), ReplaceAllUsesOfValueWith(), and ReplaceAllUsesWith().
UnrollVectorOp()
SDValue SelectionDAG::UnrollVectorOp (SDNode * N, unsigned ResNE = 0)
Utility function used by legalize and lowering to "unroll" a vector operation by splitting out the scalars and operating on each element individually.
If the ResNE is 0, fully unroll the vector op. If ResNE is less than the width of the vector op, unroll up to ResNE. If the ResNE is greater than the width of the vector op, unroll the vector op and fill the end of the resulting vector with UNDEFS.
Definition at line 9563 of file SelectionDAG.cpp.
References assert(), llvm::numbers::e, llvm::ISD::EXTRACT_VECTOR_ELT, getBuildVector(), getContext(), getNode(), getShiftAmountOperand(), getUNDEF(), llvm::SDValue::getValueType(), getValueType(), llvm::EVT::getVectorElementType(), getVectorIdxConstant(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::EVT::isVector(), N, llvm::AArch64CC::NE, Operands, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SELECT, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SRA, llvm::ISD::SRL, and llvm::ISD::VSELECT.
Referenced by LowerVectorFP_TO_INT(), LowerVectorINT_TO_FP(), and unrollVectorShift().
UnrollVectorOverflowOp()
std::pair< SDValue, SDValue > SelectionDAG::UnrollVectorOverflowOp (SDNode * N, unsigned ResNE = 0)
Like UnrollVectorOp(), but for the [US](ADD|SUB|MUL)O family of opcodes.
This is a separate function because those opcodes have two results.
Definition at line 9631 of file SelectionDAG.cpp.
References llvm::SmallVectorImpl< T >::append(), assert(), ExtractVectorElements(), getBoolConstant(), getBuildVector(), getConstant(), getContext(), getDataLayout(), getNode(), getSelect(), llvm::TargetLoweringBase::getSetCCResultType(), getUNDEF(), llvm::SDValue::getValue(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), getVTList(), N, llvm::AArch64CC::NE, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::ISD::SADDO, llvm::ISD::SMULO, llvm::ISD::SSUBO, llvm::ISD::UADDO, llvm::ISD::UMULO, and llvm::ISD::USUBO.
updateDivergence()
void SelectionDAG::updateDivergence (SDNode * N)
Definition at line 8823 of file SelectionDAG.cpp.
References llvm::append_range(), calculateDivergence(), llvm::SmallVectorBase< Size_T >::empty(), N, and llvm::SmallVectorImpl< T >::pop_back_val().
Referenced by ReplaceAllUsesOfValueWith(), ReplaceAllUsesWith(), and UpdateNodeOperands().
UpdateNodeOperands() [1/6]
SDNode * SelectionDAG::UpdateNodeOperands (SDNode * N, ArrayRef< SDValue > Ops)
Definition at line 7943 of file SelectionDAG.cpp.
References assert(), llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), llvm::lltok::equal, N, llvm::ArrayRef< T >::size(), and updateDivergence().
UpdateNodeOperands() [2/6]
SDNode * SelectionDAG::UpdateNodeOperands (SDNode * N, SDValue Op)
Mutate the specified node in-place to have the specified operands.
UpdateNodeOperands - Mutate the specified node in-place to have the specified operands.
If the resultant node already exists in the DAG, this does not modify the specified node, instead it returns the node that already exists. If the resultant node does not exist in the DAG, the input node is returned. As a degenerate case, if you specify the same input operands as the node already has, the input node is returned.
Definition at line 7869 of file SelectionDAG.cpp.
References assert(), N, and updateDivergence().
Referenced by makeEquivalentMemoryOrdering(), moveBelowOrigChain(), llvm::PPCTargetLowering::PerformDAGCombine(), and UpdateNodeOperands().
UpdateNodeOperands() [3/6]
SDNode * SelectionDAG::UpdateNodeOperands (SDNode * N, SDValue Op1, SDValue Op2)
Definition at line 7894 of file SelectionDAG.cpp.
References assert(), N, and updateDivergence().
UpdateNodeOperands() [4/6]
SDNode * SelectionDAG::UpdateNodeOperands (SDNode * N, SDValue Op1, SDValue Op2, SDValue Op3)
Definition at line 7923 of file SelectionDAG.cpp.
References N, and UpdateNodeOperands().
UpdateNodeOperands() [5/6]
SDNode * SelectionDAG::UpdateNodeOperands (SDNode * N, SDValue Op1, SDValue Op2, SDValue Op3, SDValue Op4)
Definition at line 7929 of file SelectionDAG.cpp.
References N, and UpdateNodeOperands().
UpdateNodeOperands() [6/6]
SDNode * SelectionDAG::UpdateNodeOperands (SDNode * N, SDValue Op1, SDValue Op2, SDValue Op3, SDValue Op4, SDValue Op5)
Definition at line 7936 of file SelectionDAG.cpp.
References N, and UpdateNodeOperands().
VerifyDAGDiverence()
void SelectionDAG::VerifyDAGDiverence ()
Definition at line 8855 of file SelectionDAG.cpp.
References assert(), calculateDivergence(), and N.
viewGraph() [1/2]
void SelectionDAG::viewGraph ()
Definition at line 163 of file SelectionDAGPrinter.cpp.
viewGraph() [2/2]
void SelectionDAG::viewGraph (const std::string & Title)
Pop up a GraphViz/gv window with the DAG rendered using 'dot'.
viewGraph - Pop up a ghostview window with the reachable parts of the DAG rendered using 'dot'.
Definition at line 150 of file SelectionDAGPrinter.cpp.
References llvm::errs(), getMachineFunction(), getName(), and ViewGraph().
WidenVector()
SDValue SelectionDAG::WidenVector (const SDValue & N, const SDLoc & DL)
Widen the vector up to the next power of two using INSERT_SUBVECTOR.
Definition at line 9812 of file SelectionDAG.cpp.
References DL, getContext(), getNode(), getUNDEF(), llvm::EVT::getVectorElementType(), getVectorIdxConstant(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::ISD::INSERT_SUBVECTOR, N, and llvm::NextPowerOf2().
Friends And Related Function Documentation
DAGUpdateListener
friend struct DAGUpdateListener friend
DAGUpdateListener is a friend so it can manipulate the listener stack.
Definition at line 366 of file SelectionDAG.h.
Member Data Documentation
const
llvm::SelectionDAG::const
Definition at line 1906 of file SelectionDAG.h.
instead
Use InferPtrAlign llvm::SelectionDAG::instead
Initial value:
{
    if (auto A = InferPtrAlign(Ptr))
      return A->value()
Definition at line 1907 of file SelectionDAG.h.
MaxRecursionDepth
constexpr unsigned llvm::SelectionDAG::MaxRecursionDepth = 6 static constexpr
Definition at line 423 of file SelectionDAG.h.
Referenced by computeKnownBits(), ComputeNumSignBits(), llvm::TargetLowering::getNegatedExpression(), llvm::PPCTargetLowering::getNegatedExpression(), getShuffleScalarElt(), getUsefulBits(), isFNEG(), isKnownNeverNaN(), isSplatValue(), PromoteMaskArithmetic(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifyDemandedVectorElts(), and llvm::TargetLowering::SimplifyMultipleUseDemandedBits().
NewNodesMustHaveLegalTypes
bool llvm::SelectionDAG::NewNodesMustHaveLegalTypes = false
When true, additional steps are taken to ensure that getConstant() and similar functions return DAG nodes that have legal types.
This is important after type legalization since any illegally typed nodes generated after this point will not experience type legalization.
Definition at line 362 of file SelectionDAG.h.
Referenced by FoldConstantArithmetic(), FoldConstantVectorArithmetic(), and getConstant().
NodeGraphAttrs
std::map<const SDNode *, std::string> llvm::SelectionDAG::NodeGraphAttrs
Definition at line 478 of file SelectionDAG.h.
Referenced by clearGraphAttrs(), getGraphAttrs(), setGraphAttrs(), and setGraphColor().
return
llvm::SelectionDAG::return
Definition at line 1910 of file SelectionDAG.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/SelectionDAG.h
lib/CodeGen/SelectionDAG/DAGCombiner.cpp
lib/CodeGen/SelectionDAG/LegalizeDAG.cpp
lib/CodeGen/SelectionDAG/LegalizeTypes.cpp
lib/CodeGen/SelectionDAG/LegalizeVectorOps.cpp
lib/CodeGen/SelectionDAG/SelectionDAG.cpp
lib/CodeGen/SelectionDAG/SelectionDAGDumper.cpp
lib/CodeGen/SelectionDAG/SelectionDAGPrinter.cpp