LLVM: lib/Transforms/Coroutines/CoroSplit.cpp File Reference
CoroSplit.cpp File Reference
#include "llvm/Transforms/Coroutines/CoroSplit.h"
#include "CoroInstr.h"
#include "CoroInternal.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Analysis/CallGraph.h"
#include "llvm/Analysis/CallGraphSCCPass.h"
#include "llvm/Analysis/LazyCallGraph.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/Verifier.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/PrettyStackTrace.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/CallGraphUpdater.h"
#include "llvm/Transforms/Utils/Cloning.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/ValueMapper.h"
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <initializer_list>
#include <iterator>
Macros
#define DEBUG_TYPE "coro-split"
Functions
static void maybeFreeRetconStorage (IRBuilder<> &Builder, const coro::Shape &Shape, Value *FramePtr, CallGraph *CG)
static bool replaceCoroEndAsync (AnyCoroEndInst *End)
Replace an llvm.coro.end.async.
static void replaceFallthroughCoroEnd (AnyCoroEndInst *End, const coro::Shape &Shape, Value *FramePtr, bool InResume, CallGraph *CG)
Replace a non-unwind call to llvm.coro.end.
static void replaceUnwindCoroEnd (AnyCoroEndInst *End, const coro::Shape &Shape, Value *FramePtr, bool InResume, CallGraph *CG)
Replace an unwind call to llvm.coro.end.
static void replaceCoroEnd (AnyCoroEndInst *End, const coro::Shape &Shape, Value *FramePtr, bool InResume, CallGraph *CG)
static void createResumeEntryBlock (Function &F, coro::Shape &Shape)
static Function * createCloneDeclaration (Function &OrigF, coro::Shape &Shape, const Twine &Suffix, Module::iterator InsertBefore)
static void replaceSwiftErrorOps (Function &F, coro::Shape &Shape, ValueToValueMapTy *VMap)
static void addFramePointerAttrs (AttributeList &Attrs, LLVMContext &Context, unsigned ParamIndex, uint64_t Size, Align Alignment)
static Function * createClone (Function &F, const Twine &Suffix, coro::Shape &Shape, CoroCloner::Kind FKind)
static void removeCoroEnds (const coro::Shape &Shape, CallGraph *CG)
Remove calls to llvm.coro.end in the original function.
static void updateAsyncFuncPointerContextSize (coro::Shape &Shape)
static void replaceFrameSize (coro::Shape &Shape)
static void setCoroInfo (Function &F, coro::Shape &Shape, ArrayRef< Function * > Fns)
static void updateCoroFrame (coro::Shape &Shape, Function *ResumeFn, Function *DestroyFn, Function *CleanupFn)
static void postSplitCleanup (Function &F)
static void scanPHIsAndUpdateValueMap (Instruction *Prev, BasicBlock *NewBlock, DenseMap< Value *, Value * > &ResolvedValues)
static bool simplifyTerminatorLeadingToRet (Instruction *InitialInst)
static bool shouldBeMustTail (const CallInst &CI, const Function &F)
static void addMustTailToCoroResumes (Function &F)
static void handleNoSuspendCoroutine (coro::Shape &Shape)
static bool hasCallsInBlockBetween (Instruction *From, Instruction *To)
static bool hasCallsInBlocksBetween (BasicBlock *SaveBB, BasicBlock *ResDesBB)
static bool hasCallsBetween (Instruction *Save, Instruction *ResumeOrDestroy)
static bool simplifySuspendPoint (CoroSuspendInst *Suspend, CoroBeginInst *CoroBegin)
static void simplifySuspendPoints (coro::Shape &Shape)
static void splitSwitchCoroutine (Function &F, coro::Shape &Shape, SmallVectorImpl< Function * > &Clones)
static void replaceAsyncResumeFunction (CoroSuspendAsyncInst *Suspend, Value *Continuation)
static void coerceArguments (IRBuilder<> &Builder, FunctionType *FnTy, ArrayRef< Value * > FnArgs, SmallVectorImpl< Value * > &CallArgs)
Coerce the arguments in FnArgs according to FnTy in CallArgs.
static void splitAsyncCoroutine (Function &F, coro::Shape &Shape, SmallVectorImpl< Function * > &Clones)
static void splitRetconCoroutine (Function &F, coro::Shape &Shape, SmallVectorImpl< Function * > &Clones)
static coro::Shape splitCoroutine (Function &F, SmallVectorImpl< Function * > &Clones, bool ReuseFrameSlot)
static void updateCallGraphAfterCoroutineSplit (Function &F, const coro::Shape &Shape, const SmallVectorImpl< Function * > &Clones, CallGraph &CG, CallGraphSCC &SCC)
static void updateCallGraphAfterCoroutineSplit (LazyCallGraph::Node &N, const coro::Shape &Shape, const SmallVectorImpl< Function * > &Clones, LazyCallGraph::SCC &C, LazyCallGraph &CG, CGSCCAnalysisManager &AM, CGSCCUpdateResult &UR, FunctionAnalysisManager &FAM)
static void prepareForSplit (Function &F, CallGraph &CG, bool MarkForAsyncRestart=false)
static void createDevirtTriggerFunc (CallGraph &CG, CallGraphSCC &SCC)
static void replacePrepare (CallInst *Prepare, LazyCallGraph &CG, LazyCallGraph::SCC &C)
Replace a call to llvm.coro.prepare.retcon.
static void replacePrepare (CallInst *Prepare, CallGraph &CG)
Replace a call to llvm.coro.prepare.retcon.
static bool replaceAllPrepares (Function *PrepareFn, LazyCallGraph &CG, LazyCallGraph::SCC &C)
static bool replaceAllPrepares (Function *PrepareFn, CallGraph &CG)
Remove calls to llvm.coro.prepare.retcon, a barrier meant to prevent IPO from operating on calls to a retcon coroutine before it's been split.
static bool declaresCoroSplitIntrinsics (const Module &M)
static void addPrepareFunction (const Module &M, SmallVectorImpl< Function * > &Fns, StringRef Name)
INITIALIZE_PASS_BEGIN (CoroSplitLegacy, "coro-split", "Split coroutine into a set of functions driving its state machine", false, false) INITIALIZE_PASS_END(CoroSplitLegacy
Variables
coro split
coro Split coroutine into a set of functions driving its state machine
coro Split coroutine into a set of functions driving its state false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "coro-split"
Definition at line 75 of file CoroSplit.cpp.
Function Documentation
addFramePointerAttrs()
static void addFramePointerAttrs (AttributeList & Attrs, LLVMContext & Context, unsigned ParamIndex, uint64_t Size, Align Alignment) static
Definition at line 791 of file CoroSplit.cpp.
References llvm::AttrBuilder::addAlignmentAttr(), llvm::AttrBuilder::addAttribute(), llvm::AttrBuilder::addDereferenceableAttr(), llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, Context, llvm::NoAlias, and llvm::Check::Size.
addMustTailToCoroResumes()
static void addMustTailToCoroResumes (Function & F) static
Definition at line 1206 of file CoroSplit.cpp.
References F, I, llvm::instructions(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::removeUnreachableBlocks(), shouldBeMustTail(), simplifyTerminatorLeadingToRet(), and llvm::CallInst::TCK_MustTail.
Referenced by splitSwitchCoroutine().
addPrepareFunction()
static void addPrepareFunction (const Module & M, SmallVectorImpl< Function * > & Fns, StringRef Name) static
Definition at line 2008 of file CoroSplit.cpp.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::CoroSplitPass::run().
coerceArguments()
static void coerceArguments (IRBuilder<> & Builder, FunctionType * FnTy, ArrayRef< Value * > FnArgs, SmallVectorImpl< Value * > & CallArgs) static
Coerce the arguments in FnArgs according to FnTy in CallArgs.
Definition at line 1460 of file CoroSplit.cpp.
References assert(), Builder, getType(), llvm::FunctionType::params(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::ArrayRef< T >::size().
Referenced by llvm::coro::createMustTailCall().
createClone()
static Function* createClone (Function & F, const Twine & Suffix, coro::Shape & Shape, CoroCloner::Kind FKind) static
Definition at line 954 of file CoroSplit.cpp.
References F.
Referenced by splitSwitchCoroutine().
createCloneDeclaration()
static Function* createCloneDeclaration (Function & OrigF, coro::Shape & Shape, const Twine & Suffix, Module::iterator InsertBefore) static
Definition at line 457 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, llvm::Function::addParamAttr(), llvm::coro::Async, llvm::Function::Create(), llvm::Value::getName(), llvm::GlobalValue::getParent(), llvm::coro::Shape::getResumeFunctionType(), and llvm::NoAlias.
Referenced by splitRetconCoroutine().
createDevirtTriggerFunc()
static void createDevirtTriggerFunc (CallGraph & CG, CallGraphSCC & SCC) static
Definition at line 1857 of file CoroSplit.cpp.
References llvm::Function::addFnAttr(), C, CORO_DEVIRT_TRIGGER_FN, llvm::Function::Create(), llvm::FunctionType::get(), llvm::Type::getInt8PtrTy(), llvm::CallGraph::getModule(), and llvm::Type::getVoidTy().
createResumeEntryBlock()
static void createResumeEntryBlock (Function & F, coro::Shape & Shape) static
Definition at line 327 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, assert(), Builder, C, llvm::coro::Shape::CoroSuspends, llvm::BasicBlock::Create(), llvm::PHINode::Create(), F, llvm::coro::Shape::FramePtr, llvm::coro::Shape::FrameTy, llvm::ConstantTokenNone::get(), llvm::ConstantPointerNull::get(), llvm::coro::Shape::getIndex(), llvm::coro::Shape::getIndexType(), llvm::coro::Shape::getSwitchIndexField(), Index, llvm::coro::Shape::SwitchFieldIndex::Resume, llvm::coro::Shape::SwitchLoweringStorage::ResumeEntryBlock, llvm::coro::Shape::SwitchLoweringStorage::ResumeSwitch, llvm::coro::Switch, and llvm::coro::Shape::SwitchLowering.
Referenced by splitSwitchCoroutine().
declaresCoroSplitIntrinsics()
static bool declaresCoroSplitIntrinsics (const Module & M) static
Definition at line 2002 of file CoroSplit.cpp.
References llvm::coro::declaresIntrinsics().
Referenced by llvm::CoroSplitPass::run().
handleNoSuspendCoroutine()
static void handleNoSuspendCoroutine (coro::Shape & Shape) static
Definition at line 1229 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, llvm::coro::Async, Builder, llvm::coro::Shape::CoroBegin, llvm::coro::Shape::FrameAlign, llvm::coro::Shape::FrameTy, llvm::UndefValue::get(), llvm::AnyCoroIdInst::getCoroAlloc(), llvm::CoroBeginInst::getId(), llvm::coro::replaceCoroFree(), llvm::coro::Retcon, llvm::coro::RetconOnce, and llvm::coro::Switch.
Referenced by splitCoroutine().
hasCallsBetween()
static bool hasCallsBetween (Instruction * Save, Instruction * ResumeOrDestroy) static
Definition at line 1304 of file CoroSplit.cpp.
References llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::Instruction::getParent(), hasCallsInBlockBetween(), and hasCallsInBlocksBetween().
Referenced by simplifySuspendPoint().
hasCallsInBlockBetween()
static bool hasCallsInBlockBetween (Instruction * From, Instruction * To) static
Definition at line 1263 of file CoroSplit.cpp.
References From, and I.
Referenced by hasCallsBetween(), and hasCallsInBlocksBetween().
hasCallsInBlocksBetween()
static bool hasCallsInBlocksBetween (BasicBlock * SaveBB, BasicBlock * ResDesBB) static
Definition at line 1275 of file CoroSplit.cpp.
References llvm::SmallPtrSetImpl< PtrType >::count(), llvm::SmallVectorBase< Size_T >::empty(), llvm::SmallPtrSetImpl< PtrType >::erase(), hasCallsInBlockBetween(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::predecessors(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by hasCallsBetween().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (CoroSplitLegacy , "coro-split" , "Split coroutine into a set of functions driving its state machine" , false , false)
maybeFreeRetconStorage()
static void maybeFreeRetconStorage (IRBuilder<> & Builder, const coro::Shape & Shape, Value * FramePtr, CallGraph * CG) static
Definition at line 167 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, assert(), Builder, llvm::coro::Shape::emitDealloc(), llvm::coro::Shape::RetconLoweringStorage::IsFrameInlineInStorage, llvm::coro::Retcon, llvm::coro::Shape::RetconLowering, and llvm::coro::RetconOnce.
postSplitCleanup()
static void postSplitCleanup (Function & F) static
Definition at line 1063 of file CoroSplit.cpp.
References llvm::legacy::FunctionPassManager::add(), llvm::createCFGSimplificationPass(), llvm::createEarlyCSEPass(), llvm::createSCCPPass(), llvm::legacy::FunctionPassManager::doFinalization(), llvm::legacy::FunctionPassManager::doInitialization(), llvm::errs(), F, llvm::removeUnreachableBlocks(), llvm::report_fatal_error(), llvm::legacy::FunctionPassManager::run(), and llvm::verifyFunction().
Referenced by splitSwitchCoroutine(), and updateCallGraphAfterCoroutineSplit().
prepareForSplit()
static void prepareForSplit (Function & F, CallGraph & CG, bool MarkForAsyncRestart = false) static
Definition at line 1820 of file CoroSplit.cpp.
References assert(), ASYNC_RESTART_AFTER_SPLIT, Context, CORO_DEVIRT_TRIGGER_FN, CORO_PRESPLIT_ATTR, llvm::CallInst::Create(), F, llvm::ConstantPointerNull::get(), llvm::FunctionType::get(), llvm::CallGraph::getCallsExternalNode(), llvm::Type::getInt8PtrTy(), llvm::Type::getVoidTy(), llvm::IndirectCall, llvm::coro::LowererBase::makeSubFnCall(), PREPARED_FOR_SPLIT, and llvm::CoroSubFnInst::RestartTrigger.
removeCoroEnds()
static void removeCoroEnds (const coro::Shape & Shape, CallGraph * CG) static
Remove calls to llvm.coro.end in the original function.
Definition at line 962 of file CoroSplit.cpp.
Referenced by updateCallGraphAfterCoroutineSplit().
replaceAllPrepares() [1/2]
static bool replaceAllPrepares (Function * PrepareFn, CallGraph & CG) static
Remove calls to llvm.coro.prepare.retcon, a barrier meant to prevent IPO from operating on calls to a retcon coroutine before it's been split.
This is only safe to do after we've split all retcon coroutines in the module. We can do that this in this pass because this pass does promise to split all retcon coroutines (as opposed to switch coroutines, which are lowered in multiple stages).
Definition at line 1989 of file CoroSplit.cpp.
References replacePrepare(), llvm::Value::use_begin(), and llvm::Value::use_end().
replaceAllPrepares() [2/2]
static bool replaceAllPrepares (Function * PrepareFn, LazyCallGraph & CG, LazyCallGraph::SCC & C) static
Definition at line 1970 of file CoroSplit.cpp.
References C, replacePrepare(), llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by llvm::CoroSplitPass::run().
replaceAsyncResumeFunction()
static void replaceAsyncResumeFunction (CoroSuspendAsyncInst * Suspend, Value * Continuation) static
Definition at line 1446 of file CoroSplit.cpp.
References Builder, Context, llvm::UndefValue::get(), llvm::Function::getContext(), llvm::Type::getInt8PtrTy(), llvm::BasicBlock::getParent(), llvm::Instruction::getParent(), llvm::CoroSuspendAsyncInst::getResumeFunction(), and llvm::User::setOperand().
replaceCoroEnd()
static void replaceCoroEnd (AnyCoroEndInst * End, const coro::Shape & Shape, Value * FramePtr, bool InResume, CallGraph * CG) static
Definition at line 312 of file CoroSplit.cpp.
replaceCoroEndAsync()
static bool replaceCoroEndAsync (AnyCoroEndInst * End) static
Replace an llvm.coro.end.async.
Will inline the must tail call function call if there is one.
Returns
true if cleanup of the coro.end block is needed, false otherwise.
Definition at line 181 of file CoroSplit.cpp.
replaceFallthroughCoroEnd()
static void replaceFallthroughCoroEnd (AnyCoroEndInst * End, const coro::Shape & Shape, Value * FramePtr, bool InResume, CallGraph * CG) static
Replace a non-unwind call to llvm.coro.end.
Definition at line 224 of file CoroSplit.cpp.
replaceFrameSize()
static void replaceFrameSize (coro::Shape & Shape) static
Definition at line 983 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, llvm::coro::Async, llvm::coro::Shape::CoroSizes, DL, llvm::Instruction::eraseFromParent(), llvm::coro::Shape::FrameTy, llvm::ConstantInt::get(), llvm::Value::replaceAllUsesWith(), llvm::Check::Size, and updateAsyncFuncPointerContextSize().
Referenced by splitCoroutine().
replacePrepare() [1/2]
static void replacePrepare (CallInst * Prepare, CallGraph & CG) static
Replace a call to llvm.coro.prepare.retcon.
Definition at line 1916 of file CoroSplit.cpp.
References llvm::CallGraphNode::addCalledFunction(), llvm::Instruction::eraseFromParent(), llvm::CallBase::getArgOperand(), llvm::Instruction::getFunction(), llvm::Use::getUser(), llvm::CallGraphNode::removeCallEdgeFor(), llvm::Value::replaceAllUsesWith(), llvm::Value::stripPointerCasts(), llvm::Value::use_begin(), llvm::Value::use_end(), and llvm::Value::uses().
replacePrepare() [2/2]
static void replacePrepare (CallInst * Prepare, LazyCallGraph & CG, LazyCallGraph::SCC & C) static
Replace a call to llvm.coro.prepare.retcon.
Definition at line 1880 of file CoroSplit.cpp.
References llvm::Instruction::eraseFromParent(), llvm::CallBase::getArgOperand(), llvm::Value::replaceAllUsesWith(), llvm::Value::stripPointerCasts(), llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by replaceAllPrepares().
replaceSwiftErrorOps()
static void replaceSwiftErrorOps (Function & F, coro::Shape & Shape, ValueToValueMapTy * VMap) static
Definition at line 573 of file CoroSplit.cpp.
References Arg, assert(), Builder, F, llvm::Type::getPointerElementType(), llvm::Value::getType(), and llvm::coro::Shape::SwiftErrorOps.
Referenced by splitCoroutine().
replaceUnwindCoroEnd()
static void replaceUnwindCoroEnd (AnyCoroEndInst * End, const coro::Shape & Shape, Value * FramePtr, bool InResume, CallGraph * CG) static
Replace an unwind call to llvm.coro.end.
Definition at line 282 of file CoroSplit.cpp.
scanPHIsAndUpdateValueMap()
static void scanPHIsAndUpdateValueMap (Instruction * Prev, BasicBlock * NewBlock, DenseMap< Value *, Value * > & ResolvedValues) static
Definition at line 1087 of file CoroSplit.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::Instruction::getParent(), llvm::BasicBlock::phis(), and VI.
Referenced by simplifyTerminatorLeadingToRet().
setCoroInfo()
static void setCoroInfo (Function & F, coro::Shape & Shape, ArrayRef< Function * > Fns) static
Definition at line 1014 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), llvm::ArrayRef< T >::begin(), C, llvm::ArrayRef< T >::end(), F, llvm::ConstantArray::get(), llvm::ArrayType::get(), llvm::Type::getInt8PtrTy(), llvm::GlobalValue::getParent(), llvm::ConstantExpr::getPointerCast(), llvm::coro::Shape::getSwitchCoroId(), llvm::GlobalValue::getType(), llvm::GlobalValue::PrivateLinkage, llvm::CoroIdInst::setInfo(), and llvm::coro::Switch.
Referenced by splitSwitchCoroutine().
shouldBeMustTail()
static bool shouldBeMustTail (const CallInst & CI, const Function & F) static
Definition at line 1171 of file CoroSplit.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, F, llvm::CallBase::getAttributes(), llvm::CallBase::getCallingConv(), llvm::CallBase::getFunctionType(), llvm::FunctionType::getNumParams(), llvm::FunctionType::getParamType(), llvm::Type::getPointerAddressSpace(), llvm::FunctionType::getReturnType(), llvm::CallBase::isInlineAsm(), llvm::Type::isPointerTy(), and llvm::Type::isVoidTy().
Referenced by addMustTailToCoroResumes().
simplifySuspendPoint()
static bool simplifySuspendPoint (CoroSuspendInst * Suspend, CoroBeginInst * CoroBegin) static
Definition at line 1329 of file CoroSplit.cpp.
References Callee, llvm::BranchInst::Create(), llvm::Instruction::eraseFromParent(), llvm::CallBase::getCalledOperand(), llvm::CoroSuspendInst::getCoroSave(), llvm::Instruction::getParent(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getPrevNode(), llvm::BasicBlock::getSinglePredecessor(), hasCallsBetween(), I, llvm::Value::replaceAllUsesWith(), and llvm::Value::stripPointerCasts().
Referenced by simplifySuspendPoints().
simplifySuspendPoints()
static void simplifySuspendPoints (coro::Shape & Shape) static
Definition at line 1389 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, llvm::coro::Shape::CoroBegin, llvm::coro::Shape::CoroSuspends, I, N, SI, simplifySuspendPoint(), std::swap(), and llvm::coro::Switch.
Referenced by splitCoroutine().
simplifyTerminatorLeadingToRet()
static bool simplifyTerminatorLeadingToRet (Instruction * InitialInst) static
Definition at line 1104 of file CoroSplit.cpp.
References llvm::ISD::BR, Cond, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::BasicBlock::getFirstNonPHIOrDbgOrLifetime(), llvm::Instruction::getParent(), llvm::ConstantInt::getZExtValue(), I, llvm::CmpInst::ICMP_EQ, llvm::BasicBlock::removePredecessor(), llvm::ReplaceInstWithInst(), scanPHIsAndUpdateValueMap(), and SI.
Referenced by addMustTailToCoroResumes().
splitAsyncCoroutine()
static void splitAsyncCoroutine (Function & F, coro::Shape & Shape, SmallVectorImpl< Function * > & Clones) static
Definition at line 1492 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, assert(), llvm::coro::Async, llvm::coro::Shape::AsyncLowering, Builder, Context, llvm::coro::Shape::CoroBegin, llvm::coro::Shape::CoroSuspends, llvm::SmallVectorBase< Size_T >::empty(), F, llvm::coro::Shape::AsyncLoweringStorage::FrameOffset, llvm::coro::Shape::FramePtr, llvm::CoroBeginInst::getId(), llvm::Type::getInt8PtrTy(), llvm::Type::getInt8Ty(), llvm::TrackingVH< ValueTy >::getValPtr(), llvm::NoAlias, llvm::Value::replaceAllUsesWith(), llvm::SmallVectorImpl< T >::reserve(), and llvm::AttributeList::ReturnIndex.
Referenced by splitCoroutine().
splitCoroutine()
static coro::Shape splitCoroutine (Function & F, SmallVectorImpl< Function * > & Clones, bool ReuseFrameSlot) static
Definition at line 1717 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, llvm::coro::Async, llvm::coro::buildCoroutineFrame(), llvm::coro::Shape::CoroBegin, llvm::coro::Shape::CoroSuspends, F, handleNoSuspendCoroutine(), llvm::removeUnreachableBlocks(), replaceFrameSize(), replaceSwiftErrorOps(), llvm::coro::Retcon, llvm::coro::RetconOnce, simplifySuspendPoints(), splitAsyncCoroutine(), splitRetconCoroutine(), splitSwitchCoroutine(), and llvm::coro::Switch.
Referenced by llvm::CoroSplitPass::run().
splitRetconCoroutine()
static void splitRetconCoroutine (Function & F, coro::Shape & Shape, SmallVectorImpl< Function * > & Clones) static
Definition at line 1573 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, assert(), llvm::MCID::Branch, Builder, llvm::coro::Shape::CoroBegin, llvm::coro::Shape::CoroSuspends, llvm::BasicBlock::Create(), createCloneDeclaration(), DL, llvm::numbers::e, E, llvm::coro::Shape::emitAlloc(), llvm::SmallVectorBase< Size_T >::empty(), F, llvm::coro::Shape::FramePtr, llvm::coro::Shape::FrameTy, llvm::UndefValue::get(), llvm::CoroBeginInst::getId(), llvm::Type::getPointerTo(), llvm::coro::Shape::getRetconResultTypes(), llvm::Value::getType(), llvm::TrackingVH< ValueTy >::getValPtr(), I, llvm::coro::Shape::RetconLoweringStorage::IsFrameInlineInStorage, llvm::NoAlias, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::SmallVectorImpl< T >::reserve(), llvm::coro::Retcon, llvm::coro::Shape::RetconLowering, llvm::coro::RetconOnce, llvm::coro::Shape::RetconLoweringStorage::ReturnBlock, llvm::AttributeList::ReturnIndex, llvm::SmallVectorBase< Size_T >::size(), and llvm::Check::Size.
Referenced by splitCoroutine().
splitSwitchCoroutine()
static void splitSwitchCoroutine (Function & F, coro::Shape & Shape, SmallVectorImpl< Function * > & Clones) static
Definition at line 1414 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, addMustTailToCoroResumes(), assert(), createClone(), createResumeEntryBlock(), llvm::SmallVectorBase< Size_T >::empty(), F, postSplitCleanup(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), setCoroInfo(), llvm::coro::Switch, and updateCoroFrame().
Referenced by splitCoroutine().
updateAsyncFuncPointerContextSize()
static void updateAsyncFuncPointerContextSize (coro::Shape & Shape) static
Definition at line 968 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, assert(), llvm::coro::Async, llvm::coro::Shape::AsyncLoweringStorage::AsyncFuncPointer, llvm::coro::Shape::AsyncLowering, llvm::coro::Shape::AsyncLoweringStorage::ContextSize, llvm::ConstantStruct::get(), llvm::ConstantInt::get(), llvm::GlobalVariable::getInitializer(), and llvm::GlobalVariable::setInitializer().
Referenced by replaceFrameSize().
updateCallGraphAfterCoroutineSplit() [1/2]
static void updateCallGraphAfterCoroutineSplit (Function & F, const coro::Shape & Shape, const SmallVectorImpl< Function * > & Clones, CallGraph & CG, CallGraphSCC & SCC) static
Definition at line 1761 of file CoroSplit.cpp.
References llvm::coro::Shape::CoroBegin, F, postSplitCleanup(), removeCoroEnds(), and llvm::coro::updateCallGraph().
Referenced by llvm::CoroSplitPass::run().
updateCallGraphAfterCoroutineSplit() [2/2]
static void updateCallGraphAfterCoroutineSplit (LazyCallGraph::Node & N, const coro::Shape & Shape, const SmallVectorImpl< Function * > & Clones, LazyCallGraph::SCC & C, LazyCallGraph & CG, CGSCCAnalysisManager & AM, CGSCCUpdateResult & UR, FunctionAnalysisManager & FAM) static
Definition at line 1774 of file CoroSplit.cpp.
References llvm::coro::Shape::CoroBegin.
updateCoroFrame()
static void updateCoroFrame (coro::Shape & Shape, Function * ResumeFn, Function * DestroyFn, Function * CleanupFn) static
Definition at line 1038 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, assert(), Builder, llvm::coro::Shape::SwitchFieldIndex::Destroy, llvm::coro::Shape::FramePtr, llvm::coro::Shape::FrameTy, llvm::AnyCoroIdInst::getCoroAlloc(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::coro::Shape::getSwitchCoroId(), llvm::coro::Shape::SwitchFieldIndex::Resume, and llvm::coro::Switch.
Referenced by splitSwitchCoroutine().
Variable Documentation
false
coro Split coroutine into a set of functions driving its state false
Definition at line 2198 of file CoroSplit.cpp.
machine
coro Split coroutine into a set of functions driving its state machine
Definition at line 2198 of file CoroSplit.cpp.
split
coro split
Definition at line 2197 of file CoroSplit.cpp.
Referenced by llvm::StringRef::split().