LLVM: lib/ProfileData/Coverage/CoverageMappingReader.cpp File Reference
CoverageMappingReader.cpp File Reference
#include "llvm/ProfileData/Coverage/CoverageMappingReader.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Triple.h"
#include "llvm/Object/Binary.h"
#include "llvm/Object/Error.h"
#include "llvm/Object/MachOUniversal.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Object/COFF.h"
#include "llvm/ProfileData/InstrProf.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compression.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <vector>
Classes
struct FilenameRange
A range of filename indices.
Macros
#define DEBUG_TYPE "coverage-mapping"
Functions
STATISTIC (CovMapNumRecords, "The # of coverage function records")
STATISTIC (CovMapNumUsedRecords, "The # of used coverage function records")
static Expected< bool > isCoverageMappingDummy (uint64_t Hash, StringRef Mapping)
template<typename T , support::endianness Endian>
static Error readCoverageMappingData (InstrProfSymtab &ProfileNames, StringRef CovMap, StringRef FuncRecords, std::vector< BinaryCoverageReader::ProfileMappingRecord > &Records, std::vector< StringRef > &Filenames, BinaryCoverageReader::DecompressedData &Decompressed)
static Expected< std::unique_ptr< BinaryCoverageReader > > loadTestingFormat (StringRef Data)
static Expected< std::vector< SectionRef > > lookupSections (ObjectFile &OF, StringRef Name)
Find all sections that match Name.
static Expected< std::unique_ptr< BinaryCoverageReader > > loadBinaryFormat (std::unique_ptr< Binary > Bin, StringRef Arch)
static bool isArchSpecifierInvalidOrMissing (Binary *Bin, StringRef Arch)
Determine whether Arch is invalid or empty, given Bin.
Variables
static const unsigned EncodingExpansionRegionBit
static const char * TestingFormatMagic = "llvmcovmtestdata"
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "coverage-mapping"
Definition at line 43 of file CoverageMappingReader.cpp.
Function Documentation
isArchSpecifierInvalidOrMissing()
static bool isArchSpecifierInvalidOrMissing (Binary * Bin, StringRef Arch) static
Determine whether Arch is invalid or empty, given Bin.
Definition at line 978 of file CoverageMappingReader.cpp.
Referenced by llvm::coverage::BinaryCoverageReader::create().
isCoverageMappingDummy()
static Expected<bool> isCoverageMappingDummy (uint64_t Hash, StringRef Mapping) static
Definition at line 451 of file CoverageMappingReader.cpp.
References llvm::coverage::RawCoverageMappingDummyChecker::isDummy().
loadBinaryFormat()
static Expected<std::unique_ptr<BinaryCoverageReader> > loadBinaryFormat (std::unique_ptr< Binary > Bin, StringRef Arch) static
Definition at line 902 of file CoverageMappingReader.cpp.
References llvm::support::big, llvm::consumeError(), llvm::InstrProfSymtab::create(), llvm::coverage::BinaryCoverageReader::createCoverageReaderFromBuffer(), E, llvm::StringRef::empty(), llvm::errorCodeToError(), llvm::getInstrProfSectionName(), llvm::support::little, lookupSections(), llvm::coverage::malformed, llvm::move(), and llvm::ARMBuildAttrs::Section.
loadTestingFormat()
static Expected<std::unique_ptr<BinaryCoverageReader> > loadTestingFormat (StringRef Data) static
Definition at line 839 of file CoverageMappingReader.cpp.
References llvm::Address, llvm::InstrProfSymtab::create(), llvm::coverage::BinaryCoverageReader::createCoverageReaderFromBuffer(), llvm::Data, llvm::decodeULEB128(), E, llvm::support::little, llvm::coverage::malformed, llvm::move(), N, llvm::offsetToAlignedAddr(), llvm::size(), TestingFormatMagic, and llvm::coverage::truncated.
Referenced by llvm::coverage::BinaryCoverageReader::create().
lookupSections()
static Expected<std::vector<SectionRef> > lookupSections (ObjectFile & OF, StringRef Name) static
Find all sections that match Name.
There may be more than one if comdats are in use, e.g. for the __llvm_covfun section on ELF.
Definition at line 877 of file CoverageMappingReader.cpp.
References N, llvm::coverage::no_data_found, llvm::ARMBuildAttrs::Section, llvm::object::ObjectFile::sections(), and llvm::Expected< T >::takeError().
Referenced by loadBinaryFormat().
readCoverageMappingData()
template<typename T , support::endianness Endian> static Error readCoverageMappingData (InstrProfSymtab & ProfileNames, StringRef CovMap, StringRef FuncRecords, std::vector< BinaryCoverageReader::ProfileMappingRecord > & Records, std::vector< StringRef > & Filenames, BinaryCoverageReader::DecompressedData & Decompressed) static
Definition at line 755 of file CoverageMappingReader.cpp.
References llvm::coverage::CurrentVersion, llvm::StringRef::data(), E, llvm::Expected< T >::get(), llvm::move(), llvm::None, llvm::StringRef::size(), llvm::Error::success(), llvm::Expected< T >::takeError(), llvm::coverage::unsupported_version, llvm::IndexedInstrProf::Version, and llvm::coverage::Version4.
STATISTIC() [1/2]
STATISTIC (CovMapNumRecords , "The # of coverage function records")
STATISTIC() [2/2]
STATISTIC (CovMapNumUsedRecords , "The # of used coverage function records")
Variable Documentation
EncodingExpansionRegionBit
const unsigned EncodingExpansionRegionBit static
Initial value:
= 1
                                                   << Counter::EncodingTagBits
Definition at line 202 of file CoverageMappingReader.cpp.
TestingFormatMagic
const char* TestingFormatMagic = "llvmcovmtestdata" static
Definition at line 799 of file CoverageMappingReader.cpp.
Referenced by llvm::coverage::BinaryCoverageReader::create(), and loadTestingFormat().