LLVM: lib/Transforms/Scalar/DeadStoreElimination.cpp File Reference
DeadStoreElimination.cpp File Reference
#include "llvm/Transforms/Scalar/DeadStoreElimination.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/CaptureTracking.h"
#include "llvm/Analysis/GlobalsModRef.h"
#include "llvm/Analysis/MemoryBuiltins.h"
#include "llvm/Analysis/MemoryDependenceAnalysis.h"
#include "llvm/Analysis/MemoryLocation.h"
#include "llvm/Analysis/MemorySSA.h"
#include "llvm/Analysis/MemorySSAUpdater.h"
#include "llvm/Analysis/PostDominators.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/Value.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/DebugCounter.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/AssumeBundleBuilder.h"
#include "llvm/Transforms/Utils/Local.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <iterator>
#include <map>
#include <utility>
Macros
#define DEBUG_TYPE "dse"
Typedefs
using OverlapIntervalsTy = std::map< int64_t, int64_t >
using InstOverlapIntervalsTy = DenseMap< Instruction *, OverlapIntervalsTy >
Functions
STATISTIC (NumRemainingStores, "Number of stores remaining after DSE")
STATISTIC (NumRedundantStores, "Number of redundant stores deleted")
STATISTIC (NumFastStores, "Number of stores deleted")
STATISTIC (NumFastOther, "Number of other instrs removed")
STATISTIC (NumCompletePartials, "Number of stores dead by later partials")
STATISTIC (NumModifiedStores, "Number of stores modified")
STATISTIC (NumCFGChecks, "Number of stores modified")
STATISTIC (NumCFGTries, "Number of stores modified")
STATISTIC (NumCFGSuccess, "Number of stores modified")
STATISTIC (NumGetDomMemoryDefPassed, "Number of times a valid candidate is returned from getDomMemoryDef")
STATISTIC (NumDomMemDefChecks, "Number iterations check for reads in getDomMemoryDef")
DEBUG_COUNTER (MemorySSACounter, "dse-memoryssa", "Controls which MemoryDefs are eliminated.")
static void deleteDeadInstruction (Instruction *I, BasicBlock::iterator *BBI, MemoryDependenceResults &MD, const TargetLibraryInfo &TLI, InstOverlapIntervalsTy &IOL, MapVector< Instruction *, bool > &ThrowableInst, SmallSetVector< const Value *, 16 > *ValueSet=nullptr)
Delete this instruction.
static bool hasAnalyzableMemoryWrite (Instruction *I, const TargetLibraryInfo &TLI)
Does this instruction write some memory? This only returns true for things that we can analyze with other helpers below.
static MemoryLocation getLocForWrite (Instruction *Inst, const TargetLibraryInfo &TLI)
Return a Location stored to by the specified instruction.
static MemoryLocation getLocForRead (Instruction *Inst, const TargetLibraryInfo &TLI)
Return the location read by the specified "hasAnalyzableMemoryWrite" instruction if any.
static bool isRemovable (Instruction *I)
If the value of this instruction and the memory it writes to is unused, may we delete this instruction?
static bool isShortenableAtTheEnd (Instruction *I)
Returns true if the end of this instruction can be safely shortened in length.
static bool isShortenableAtTheBeginning (Instruction *I)
Returns true if the beginning of this instruction can be safely shortened in length.
static Value * getStoredPointerOperand (Instruction *I, const TargetLibraryInfo &TLI)
Return the pointer that is being written to.
static uint64_t getPointerSize (const Value *V, const DataLayout &DL, const TargetLibraryInfo &TLI, const Function *F)
template<typename AATy >
static OverwriteResult isMaskedStoreOverwrite (const Instruction *Later, const Instruction *Earlier, AATy &AA)
Check if two instruction are masked stores that completely overwrite one another.
template<typename AATy >
static OverwriteResult isOverwrite (const Instruction *LaterI, const Instruction *EarlierI, const MemoryLocation &Later, const MemoryLocation &Earlier, const DataLayout &DL, const TargetLibraryInfo &TLI, int64_t &EarlierOff, int64_t &LaterOff, AATy &AA, const Function *F)
Return 'OW_Complete' if a store to the 'Later' location (by LaterI instruction) completely overwrites a store to the 'Earlier' location.
static OverwriteResult isPartialOverwrite (const MemoryLocation &Later, const MemoryLocation &Earlier, int64_t EarlierOff, int64_t LaterOff, Instruction *DepWrite, InstOverlapIntervalsTy &IOL)
Return 'OW_Complete' if a store to the 'Later' location completely overwrites a store to the 'Earlier' location, 'OW_End' if the end of the 'Earlier' location is completely overwritten by 'Later', 'OW_Begin' if the beginning of the 'Earlier' location is overwritten by 'Later'.
static bool isPossibleSelfRead (Instruction *Inst, const MemoryLocation &InstStoreLoc, Instruction *DepWrite, const TargetLibraryInfo &TLI, AliasAnalysis &AA)
If 'Inst' might be a self read (i.e.
template<typename AATy >
static bool memoryIsNotModifiedBetween (Instruction *FirstI, Instruction *SecondI, AATy &AA, const DataLayout &DL, DominatorTree *DT)
Returns true if the memory which is accessed by the second instruction is not modified between the first and the second instruction.
static void findUnconditionalPreds (SmallVectorImpl< BasicBlock * > &Blocks, BasicBlock *BB, DominatorTree *DT)
Find all blocks that will unconditionally lead to the block BB and append them to F.
static bool handleFree (CallInst *F, AliasAnalysis *AA, MemoryDependenceResults *MD, DominatorTree *DT, const TargetLibraryInfo *TLI, InstOverlapIntervalsTy &IOL, MapVector< Instruction *, bool > &ThrowableInst)
Handle frees of entire structures whose dependency is a store to a field of that structure.
static void removeAccessedObjects (const MemoryLocation &LoadedLoc, SmallSetVector< const Value *, 16 > &DeadStackObjects, const DataLayout &DL, AliasAnalysis *AA, const TargetLibraryInfo *TLI, const Function *F)
Check to see if the specified location may alias any of the stack objects in the DeadStackObjects set.
static bool handleEndBlock (BasicBlock &BB, AliasAnalysis *AA, MemoryDependenceResults *MD, const TargetLibraryInfo *TLI, InstOverlapIntervalsTy &IOL, MapVector< Instruction *, bool > &ThrowableInst)
Remove dead stores to stack-allocated locations in the function end block.
static bool tryToShorten (Instruction *EarlierWrite, int64_t &EarlierOffset, uint64_t &EarlierSize, int64_t LaterOffset, uint64_t LaterSize, bool IsOverwriteEnd)
static bool tryToShortenEnd (Instruction *EarlierWrite, OverlapIntervalsTy &IntervalMap, int64_t &EarlierStart, uint64_t &EarlierSize)
static bool tryToShortenBegin (Instruction *EarlierWrite, OverlapIntervalsTy &IntervalMap, int64_t &EarlierStart, uint64_t &EarlierSize)
static bool removePartiallyOverlappedStores (const DataLayout &DL, InstOverlapIntervalsTy &IOL, const TargetLibraryInfo &TLI)
static bool eliminateNoopStore (Instruction *Inst, BasicBlock::iterator &BBI, AliasAnalysis *AA, MemoryDependenceResults *MD, const DataLayout &DL, const TargetLibraryInfo *TLI, InstOverlapIntervalsTy &IOL, MapVector< Instruction *, bool > &ThrowableInst, DominatorTree *DT)
template<typename AATy >
static Constant * tryToMergePartialOverlappingStores (StoreInst *Earlier, StoreInst *Later, int64_t InstWriteOffset, int64_t DepWriteOffset, const DataLayout &DL, AATy &AA, DominatorTree *DT)
static bool eliminateDeadStores (BasicBlock &BB, AliasAnalysis *AA, MemoryDependenceResults *MD, DominatorTree *DT, const TargetLibraryInfo *TLI)
static bool eliminateDeadStores (Function &F, AliasAnalysis *AA, MemoryDependenceResults *MD, DominatorTree *DT, const TargetLibraryInfo *TLI)
INITIALIZE_PASS_BEGIN (DSELegacyPass, "dse", "Dead Store Elimination", false, false) INITIALIZE_PASS_END(DSELegacyPass
Variables
static cl::opt< bool > EnablePartialOverwriteTracking ("enable-dse-partial-overwrite-tracking", cl::init(true), cl::Hidden, cl::desc("Enable partial-overwrite tracking in DSE"))
static cl::opt< bool > EnablePartialStoreMerging ("enable-dse-partial-store-merging", cl::init(true), cl::Hidden, cl::desc("Enable partial store merging in DSE"))
static cl::opt< bool > EnableMemorySSA ("enable-dse-memoryssa", cl::init(true), cl::Hidden, cl::desc("Use the new MemorySSA-backed DSE."))
static cl::opt< unsigned > MemorySSAScanLimit ("dse-memoryssa-scanlimit", cl::init(150), cl::Hidden, cl::desc("The number of memory instructions to scan for " "dead store elimination (default = 100)"))
static cl::opt< unsigned > MemorySSAUpwardsStepLimit ("dse-memoryssa-walklimit", cl::init(90), cl::Hidden, cl::desc("The maximum number of steps while walking upwards to find " "MemoryDefs that may be killed (default = 90)"))
static cl::opt< unsigned > MemorySSAPartialStoreLimit ("dse-memoryssa-partial-store-limit", cl::init(5), cl::Hidden, cl::desc("The maximum number candidates that only partially overwrite the " "killing MemoryDef to consider" " (default = 5)"))
static cl::opt< unsigned > MemorySSADefsPerBlockLimit ("dse-memoryssa-defs-per-block-limit", cl::init(5000), cl::Hidden, cl::desc("The number of MemoryDefs we consider as candidates to eliminated " "other stores per basic block (default = 5000)"))
static cl::opt< unsigned > MemorySSASameBBStepCost ("dse-memoryssa-samebb-cost", cl::init(1), cl::Hidden, cl::desc("The cost of a step in the same basic block as the killing MemoryDef" "(default = 1)"))
static cl::opt< unsigned > MemorySSAOtherBBStepCost ("dse-memoryssa-otherbb-cost", cl::init(5), cl::Hidden, cl::desc("The cost of a step in a different basic " "block than the killing MemoryDef" "(default = 5)"))
static cl::opt< unsigned > MemorySSAPathCheckLimit ("dse-memoryssa-path-check-limit", cl::init(50), cl::Hidden, cl::desc("The maximum number of blocks to check when trying to prove that " "all paths to an exit go through a killing block (default = 50)"))
dse
Dead Store Elimination
Dead Store false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "dse"
Definition at line 79 of file DeadStoreElimination.cpp.
Typedef Documentation
InstOverlapIntervalsTy
using InstOverlapIntervalsTy = DenseMap<Instruction *, OverlapIntervalsTy>
Definition at line 154 of file DeadStoreElimination.cpp.
OverlapIntervalsTy
using OverlapIntervalsTy = std::map<int64_t, int64_t>
Definition at line 153 of file DeadStoreElimination.cpp.
Function Documentation
DEBUG_COUNTER()
DEBUG_COUNTER (MemorySSACounter , "dse-memoryssa" , "Controls which MemoryDefs are eliminated.")
deleteDeadInstruction()
static void deleteDeadInstruction (Instruction * I, BasicBlock::iterator * BBI, MemoryDependenceResults & MD, const TargetLibraryInfo & TLI, InstOverlapIntervalsTy & IOL, MapVector< Instruction *, bool > & ThrowableInst, SmallSetVector< const Value *, 16 > * ValueSet = nullptr) static
Delete this instruction.
Before we do, go through and zero out all the operands of this instruction. If any of them become dead, delete them and the computation tree that feeds them. If ValueSet is non-null, remove any deleted instructions from it as well.
Definition at line 161 of file DeadStoreElimination.cpp.
References llvm::MapVector< KeyT, ValueT, MapType, VectorType >::back(), llvm::numbers::e, llvm::MapVector< KeyT, ValueT, MapType, VectorType >::empty(), llvm::SmallVectorBase< Size_T >::empty(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::Instruction::eraseFromParent(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::find(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::User::getNumOperands(), llvm::User::getOperand(), I, llvm::isInstructionTriviallyDead(), op, llvm::MapVector< KeyT, ValueT, MapType, VectorType >::pop_back(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::MemoryDependenceResults::removeInstruction(), llvm::salvageDebugInfo(), llvm::salvageKnowledge(), and llvm::User::setOperand().
Referenced by eliminateDeadStores(), eliminateNoopStore(), and handleFree().
eliminateDeadStores() [1/2]
static bool eliminateDeadStores (BasicBlock & BB, AliasAnalysis * AA, MemoryDependenceResults * MD, DominatorTree * DT, const TargetLibraryInfo * TLI) static
Definition at line 1301 of file DeadStoreElimination.cpp.
References assert(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::back(), llvm::BasicBlock::begin(), C, llvm::Instruction::comesBefore(), llvm::dbgs(), deleteDeadInstruction(), DL, eliminateNoopStore(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::empty(), EnablePartialOverwriteTracking, EnablePartialStoreMerging, llvm::BasicBlock::end(), F, llvm::BasicBlock::front(), llvm::Module::getDataLayout(), llvm::MemoryDependenceResults::getDefaultBlockScanLimit(), llvm::MemoryDependenceResults::getDependency(), llvm::MemDepResult::getInst(), llvm::ilist_node_impl< OptionsT >::getIterator(), getLocForWrite(), llvm::AAResults::getModRefInfo(), llvm::BasicBlock::getModule(), llvm::Instruction::getNumSuccessors(), llvm::BasicBlock::getParent(), llvm::MemoryDependenceResults::getPointerDependencyFrom(), llvm::BasicBlock::getTerminator(), llvm::getUnderlyingObject(), llvm::LocationSize::getValue(), handleEndBlock(), handleFree(), hasAnalyzableMemoryWrite(), llvm::isAllocLikeFn(), llvm::MemDepResult::isClobber(), llvm::MemDepResult::isDef(), llvm::isFreeCall(), isOverwrite(), isPartialOverwrite(), isPossibleSelfRead(), llvm::isRefSet(), isRemovable(), isShortenableAtTheBeginning(), isShortenableAtTheEnd(), LLVM_DEBUG, llvm::Instruction::mayThrow(), llvm::ISD::OR, llvm::PointerMayBeCaptured(), llvm::MemoryLocation::Ptr, removePartiallyOverlappedStores(), SI, llvm::MemoryLocation::Size, tryToMergePartialOverlappingStores(), tryToShorten(), and llvm::BitmaskEnumDetail::Underlying().
Referenced by eliminateDeadStores(), and llvm::DSEPass::run().
eliminateDeadStores() [2/2]
static bool eliminateDeadStores (Function & F, AliasAnalysis * AA, MemoryDependenceResults * MD, DominatorTree * DT, const TargetLibraryInfo * TLI) static
Definition at line 1510 of file DeadStoreElimination.cpp.
References eliminateDeadStores(), F, and llvm::DominatorTree::isReachableFromEntry().
eliminateNoopStore()
static bool eliminateNoopStore (Instruction * Inst, BasicBlock::iterator & BBI, AliasAnalysis * AA, MemoryDependenceResults * MD, const DataLayout & DL, const TargetLibraryInfo * TLI, InstOverlapIntervalsTy & IOL, MapVector< Instruction *, bool > & ThrowableInst, DominatorTree * DT) static
Definition at line 1207 of file DeadStoreElimination.cpp.
References llvm::dbgs(), deleteDeadInstruction(), DL, llvm::getUnderlyingObject(), llvm::isCallocLikeFn(), llvm::Constant::isNullValue(), isRemovable(), LLVM_DEBUG, memoryIsNotModifiedBetween(), and SI.
Referenced by eliminateDeadStores().
findUnconditionalPreds()
static void findUnconditionalPreds (SmallVectorImpl< BasicBlock * > & Blocks, BasicBlock * BB, DominatorTree * DT) static
Find all blocks that will unconditionally lead to the block BB and append them to F.
Definition at line 806 of file DeadStoreElimination.cpp.
References E, llvm::Instruction::getNumSuccessors(), llvm::BasicBlock::getTerminator(), I, llvm::DominatorTree::isReachableFromEntry(), llvm::pred_begin(), llvm::pred_end(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by handleFree().
getLocForRead()
static MemoryLocation getLocForRead (Instruction * Inst, const TargetLibraryInfo & TLI) static
Return the location read by the specified "hasAnalyzableMemoryWrite" instruction if any.
Definition at line 294 of file DeadStoreElimination.cpp.
References assert(), llvm::MemoryLocation::getForSource(), and hasAnalyzableMemoryWrite().
Referenced by isPossibleSelfRead().
getLocForWrite()
static MemoryLocation getLocForWrite (Instruction * Inst, const TargetLibraryInfo & TLI) static
Return a Location stored to by the specified instruction.
If isRemovable returns true, this function and getLocForRead completely describe the memory operations for this instruction.
Definition at line 262 of file DeadStoreElimination.cpp.
References llvm::MemoryLocation::get(), llvm::MemoryLocation::getAfter(), llvm::MemoryLocation::getForArgument(), llvm::MemoryLocation::getForDest(), MI, and SI.
Referenced by eliminateDeadStores(), getStoredPointerOperand(), and removePartiallyOverlappedStores().
getPointerSize()
static uint64_t getPointerSize (const Value * V, const DataLayout & DL, const TargetLibraryInfo & TLI, const Function * F) static
Definition at line 387 of file DeadStoreElimination.cpp.
References DL, F, llvm::getObjectSize(), llvm::ObjectSizeOpts::NullIsUnknownSize, llvm::NullPointerIsDefined(), llvm::Check::Size, and llvm::MemoryLocation::UnknownSize.
Referenced by isOverwrite(), and removeAccessedObjects().
getStoredPointerOperand()
static Value* getStoredPointerOperand (Instruction * I, const TargetLibraryInfo & TLI) static
Return the pointer that is being written to.
Definition at line 377 of file DeadStoreElimination.cpp.
References assert(), getLocForWrite(), I, and llvm::MemoryLocation::Ptr.
Referenced by handleFree().
handleEndBlock()
static bool handleEndBlock (BasicBlock & BB, AliasAnalysis * AA, MemoryDependenceResults * MD, const TargetLibraryInfo * TLI, InstOverlapIntervalsTy & IOL, MapVector< Instruction *, bool > & ThrowableInst) static
Remove dead stores to stack-allocated locations in the function end block.
Ex: A = alloca i32 ... store i32 1, i32* A ret void
Definition at line 914 of file DeadStoreElimination.cpp.
Referenced by eliminateDeadStores().
handleFree()
static bool handleFree (CallInst * F, AliasAnalysis * AA, MemoryDependenceResults * MD, DominatorTree * DT, const TargetLibraryInfo * TLI, InstOverlapIntervalsTy & IOL, MapVector< Instruction *, bool > & ThrowableInst) static
Handle frees of entire structures whose dependency is a store to a field of that structure.
Definition at line 822 of file DeadStoreElimination.cpp.
References llvm::dbgs(), deleteDeadInstruction(), llvm::SmallVectorBase< Size_T >::empty(), F, findUnconditionalPreds(), llvm::MemoryLocation::getAfter(), llvm::MemDepResult::getInst(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MemoryDependenceResults::getPointerDependencyFrom(), getStoredPointerOperand(), llvm::BasicBlock::getTerminator(), llvm::getUnderlyingObject(), hasAnalyzableMemoryWrite(), llvm::MemDepResult::isClobber(), llvm::MemDepResult::isDef(), llvm::AAResults::isMustAlias(), llvm::MemDepResult::isNonLocal(), isRemovable(), LLVM_DEBUG, llvm::SmallVectorImpl< T >::pop_back_val(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by eliminateDeadStores().
hasAnalyzableMemoryWrite()
static bool hasAnalyzableMemoryWrite (Instruction * I, const TargetLibraryInfo & TLI) static
Does this instruction write some memory? This only returns true for things that we can analyze with other helpers below.
Definition at line 221 of file DeadStoreElimination.cpp.
References llvm::TargetLibraryInfo::getLibFunc(), llvm::TargetLibraryInfo::has(), and I.
Referenced by eliminateDeadStores(), getLocForRead(), and handleFree().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (DSELegacyPass , "dse" , "Dead Store Elimination" , false , false)
isMaskedStoreOverwrite()
template<typename AATy > static OverwriteResult isMaskedStoreOverwrite (const Instruction * Later, const Instruction * Earlier, AATy & AA) static
Check if two instruction are masked stores that completely overwrite one another.
More specifically, Later has to overwrite Earlier.
Definition at line 416 of file DeadStoreElimination.cpp.
References llvm::Value::stripPointerCasts().
Referenced by isOverwrite().
isOverwrite()
template<typename AATy > static OverwriteResult isOverwrite (const Instruction * LaterI, const Instruction * EarlierI, const MemoryLocation & Later, const MemoryLocation & Earlier, const DataLayout & DL, const TargetLibraryInfo & TLI, int64_t & EarlierOff, int64_t & LaterOff, AATy & AA, const Function * F) static
Return 'OW_Complete' if a store to the 'Later' location (by LaterI instruction) completely overwrites a store to the 'Earlier' location.
(by EarlierI instruction). Return OW_MaybePartial if Later does not completely overwrite Earlier, but they both write to the same underlying object. In that case, use isPartialOverwrite to check if Later partially overwrites Earlier. Returns 'OW_Unknown' if nothing can be determined.
Definition at line 447 of file DeadStoreElimination.cpp.
References DL, F, llvm::GetPointerBaseWithConstantOffset(), getPointerSize(), llvm::getUnderlyingObject(), llvm::LocationSize::getValue(), isMaskedStoreOverwrite(), llvm::LocationSize::isPrecise(), llvm::MemoryLocation::Ptr, llvm::MemoryLocation::Size, llvm::Value::stripPointerCasts(), and llvm::MemoryLocation::UnknownSize.
Referenced by eliminateDeadStores().
isPartialOverwrite()
static OverwriteResult isPartialOverwrite (const MemoryLocation & Later, const MemoryLocation & Earlier, int64_t EarlierOff, int64_t LaterOff, Instruction * DepWrite, InstOverlapIntervalsTy & IOL) static
Return 'OW_Complete' if a store to the 'Later' location completely overwrites a store to the 'Earlier' location, 'OW_End' if the end of the 'Earlier' location is completely overwritten by 'Later', 'OW_Begin' if the beginning of the 'Earlier' location is overwritten by 'Later'.
'OW_PartialEarlierWithFullLater' means that an earlier (big) store was overwritten by a latter (smaller) store which doesn't write outside the big store's memory locations. Returns 'OW_Unknown' if nothing can be determined. NOTE: This function must only be called if both Later and Earlier write to the same underlying object with valid EarlierOff and LaterOff.
Definition at line 548 of file DeadStoreElimination.cpp.
References assert(), llvm::dbgs(), EnablePartialOverwriteTracking, EnablePartialStoreMerging, llvm::LocationSize::getValue(), LLVM_DEBUG, llvm::max(), llvm::min(), and llvm::MemoryLocation::Size.
Referenced by eliminateDeadStores().
isPossibleSelfRead()
static bool isPossibleSelfRead (Instruction * Inst, const MemoryLocation & InstStoreLoc, Instruction * DepWrite, const TargetLibraryInfo & TLI, AliasAnalysis & AA) static
If 'Inst' might be a self read (i.e.
a noop copy of a memory region into an identical pointer) then it doesn't actually make its input dead in the traditional sense. Consider this case:
memmove(A <- B) memmove(A <- A)
In this case, the second store to A does not make the first store to A dead. The usual situation isn't an explicit A<-A store like this (which can be trivially removed) but a case where two pointers may alias.
This function detects when it is unsafe to remove a dependent instruction because the DSE inducing instruction may be a self-read.
Definition at line 675 of file DeadStoreElimination.cpp.
References getLocForRead(), llvm::AAResults::isMustAlias(), llvm::AAResults::isNoAlias(), and llvm::MemoryLocation::Ptr.
Referenced by eliminateDeadStores().
isRemovable()
static bool isRemovable (Instruction * I) static
If the value of this instruction and the memory it writes to is unused, may we delete this instruction?
Definition at line 307 of file DeadStoreElimination.cpp.
References I, llvm_unreachable, and SI.
Referenced by eliminateDeadStores(), eliminateNoopStore(), handleFree(), and removePartiallyOverlappedStores().
isShortenableAtTheBeginning()
static bool isShortenableAtTheBeginning (Instruction * I) static
Returns true if the beginning of this instruction can be safely shortened in length.
Definition at line 370 of file DeadStoreElimination.cpp.
References I.
Referenced by eliminateDeadStores(), and tryToShortenBegin().
isShortenableAtTheEnd()
static bool isShortenableAtTheEnd (Instruction * I) static
Returns true if the end of this instruction can be safely shortened in length.
Definition at line 345 of file DeadStoreElimination.cpp.
References I.
Referenced by eliminateDeadStores(), and tryToShortenEnd().
memoryIsNotModifiedBetween()
template<typename AATy > static bool memoryIsNotModifiedBetween (Instruction * FirstI, Instruction * SecondI, AATy & AA, const DataLayout & DL, DominatorTree * DT) static
Returns true if the memory which is accessed by the second instruction is not modified between the first and the second instruction.
Precondition: Second instruction must be dominated by the first instruction.
Definition at line 723 of file DeadStoreElimination.cpp.
References Addr, assert(), B, DL, llvm::SmallVectorBase< Size_T >::empty(), llvm::MemoryLocation::get(), llvm::PHITransAddr::getAddr(), llvm::Function::getEntryBlock(), llvm::BasicBlock::getParent(), llvm::Instruction::getParent(), llvm::MemoryLocation::getWithNewPtr(), I, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::isModSet(), llvm::PHITransAddr::IsPotentiallyPHITranslatable(), llvm::PHITransAddr::NeedsPHITranslationFromBlock(), llvm::PHITransAddr::PHITranslateValue(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::pred_begin(), llvm::pred_end(), llvm::MemoryLocation::Ptr, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by eliminateNoopStore(), and tryToMergePartialOverlappingStores().
removeAccessedObjects()
static void removeAccessedObjects (const MemoryLocation & LoadedLoc, SmallSetVector< const Value *, 16 > & DeadStackObjects, const DataLayout & DL, AliasAnalysis * AA, const TargetLibraryInfo * TLI, const Function * F) static
Check to see if the specified location may alias any of the stack objects in the DeadStackObjects set.
If so, they become live because the location is being loaded.
Definition at line 882 of file DeadStoreElimination.cpp.
References DL, F, getPointerSize(), llvm::getUnderlyingObject(), I, llvm::AAResults::isNoAlias(), llvm::MemoryLocation::Ptr, llvm::SetVector< T, Vector, Set >::remove(), and llvm::SetVector< T, Vector, Set >::remove_if().
removePartiallyOverlappedStores()
static bool removePartiallyOverlappedStores (const DataLayout & DL, InstOverlapIntervalsTy & IOL, const TargetLibraryInfo & TLI) static
Definition at line 1183 of file DeadStoreElimination.cpp.
References assert(), DL, llvm::IntervalMap< KeyT, ValT, N, Traits >::empty(), getLocForWrite(), llvm::GetPointerBaseWithConstantOffset(), llvm::LocationSize::getValue(), isRemovable(), llvm::MemoryLocation::Ptr, llvm::MemoryLocation::Size, llvm::Value::stripPointerCasts(), tryToShortenBegin(), and tryToShortenEnd().
Referenced by eliminateDeadStores().
STATISTIC() [1/11]
STATISTIC (NumCFGChecks , "Number of stores modified")
STATISTIC() [2/11]
STATISTIC (NumCFGSuccess , "Number of stores modified")
STATISTIC() [3/11]
STATISTIC (NumCFGTries , "Number of stores modified")
STATISTIC() [4/11]
STATISTIC (NumCompletePartials , "Number of stores dead by later partials")
STATISTIC() [5/11]
STATISTIC (NumDomMemDefChecks , "Number iterations check for reads in getDomMemoryDef")
STATISTIC() [6/11]
STATISTIC (NumFastOther , "Number of other instrs removed")
STATISTIC() [7/11]
STATISTIC (NumFastStores , "Number of stores deleted")
STATISTIC() [8/11]
STATISTIC (NumGetDomMemoryDefPassed , "Number of times a valid candidate is returned from getDomMemoryDef")
STATISTIC() [9/11]
STATISTIC (NumModifiedStores , "Number of stores modified")
STATISTIC() [10/11]
STATISTIC (NumRedundantStores , "Number of redundant stores deleted")
STATISTIC() [11/11]
STATISTIC (NumRemainingStores , "Number of stores remaining after DSE")
tryToMergePartialOverlappingStores()
template<typename AATy > static Constant* tryToMergePartialOverlappingStores (StoreInst * Earlier, StoreInst * Later, int64_t InstWriteOffset, int64_t DepWriteOffset, const DataLayout & DL, AATy & AA, DominatorTree * DT) static
Definition at line 1257 of file DeadStoreElimination.cpp.
References assert(), llvm::dbgs(), DL, llvm::ConstantInt::get(), llvm::APInt::getBitsSet(), llvm::APInt::getBitWidth(), llvm::Value::getType(), llvm::StoreInst::getValueOperand(), LLVM_DEBUG, llvm::BitmaskEnumDetail::Mask(), memoryIsNotModifiedBetween(), and llvm::APInt::zext().
Referenced by eliminateDeadStores().
tryToShorten()
static bool tryToShorten (Instruction * EarlierWrite, int64_t & EarlierOffset, uint64_t & EarlierSize, int64_t LaterOffset, uint64_t LaterSize, bool IsOverwriteEnd) static
Definition at line 1071 of file DeadStoreElimination.cpp.
References llvm::GetElementPtrInst::CreateInBounds(), llvm::dbgs(), llvm::ConstantInt::get(), llvm::Value::getType(), llvm::isPowerOf2_64(), LLVM_DEBUG, and llvm::Instruction::setDebugLoc().
Referenced by eliminateDeadStores(), tryToShortenBegin(), and tryToShortenEnd().
tryToShortenBegin()
static bool tryToShortenBegin (Instruction * EarlierWrite, OverlapIntervalsTy & IntervalMap, int64_t & EarlierStart, uint64_t & EarlierSize) static
Definition at line 1154 of file DeadStoreElimination.cpp.
References assert(), llvm::IntervalMap< KeyT, ValT, N, Traits >::begin(), llvm::IntervalMap< KeyT, ValT, N, Traits >::empty(), isShortenableAtTheBeginning(), and tryToShorten().
Referenced by removePartiallyOverlappedStores().
tryToShortenEnd()
static bool tryToShortenEnd (Instruction * EarlierWrite, OverlapIntervalsTy & IntervalMap, int64_t & EarlierStart, uint64_t & EarlierSize) static
Definition at line 1126 of file DeadStoreElimination.cpp.
References assert(), llvm::IntervalMap< KeyT, ValT, N, Traits >::empty(), llvm::IntervalMap< KeyT, ValT, N, Traits >::end(), isShortenableAtTheEnd(), and tryToShorten().
Referenced by removePartiallyOverlappedStores().
Variable Documentation
dse
dse
Definition at line 2757 of file DeadStoreElimination.cpp.
Elimination
Dead Store Elimination
Definition at line 2757 of file DeadStoreElimination.cpp.
EnableMemorySSA
cl::opt<bool> EnableMemorySSA("enable-dse-memoryssa", cl::init(true), cl::Hidden, cl::desc("Use the new MemorySSA-backed DSE.")) ("enable-dse-memoryssa" , cl::init(true) , cl::Hidden , cl::desc("Use the new MemorySSA-backed DSE.")) static
Referenced by llvm::DSEPass::run().
EnablePartialOverwriteTracking
cl::opt<bool> EnablePartialOverwriteTracking("enable-dse-partial-overwrite-tracking", cl::init(true), cl::Hidden, cl::desc("Enable partial-overwrite tracking in DSE")) ("enable-dse-partial-overwrite-tracking" , cl::init(true) , cl::Hidden , cl::desc("Enable partial-overwrite tracking in DSE")) static
Referenced by eliminateDeadStores(), and isPartialOverwrite().
EnablePartialStoreMerging
cl::opt<bool> EnablePartialStoreMerging("enable-dse-partial-store-merging", cl::init(true), cl::Hidden, cl::desc("Enable partial store merging in DSE")) ("enable-dse-partial-store-merging" , cl::init(true) , cl::Hidden , cl::desc("Enable partial store merging in DSE")) static
Referenced by eliminateDeadStores(), and isPartialOverwrite().
false
Dead Store false
Definition at line 2757 of file DeadStoreElimination.cpp.
MemorySSADefsPerBlockLimit
cl::opt<unsigned> MemorySSADefsPerBlockLimit("dse-memoryssa-defs-per-block-limit", cl::init(5000), cl::Hidden, cl::desc("The number of MemoryDefs we consider as candidates to eliminated " "other stores per basic block (default = 5000)")) ("dse-memoryssa-defs-per-block-limit" , cl::init(5000) , cl::Hidden , cl::desc("The number of MemoryDefs we consider as candidates to eliminated " "other stores per basic block (default = 5000)")) static
MemorySSAOtherBBStepCost
cl::opt<unsigned> MemorySSAOtherBBStepCost("dse-memoryssa-otherbb-cost", cl::init(5), cl::Hidden, cl::desc("The cost of a step in a different basic " "block than the killing MemoryDef" "(default = 5)")) ("dse-memoryssa-otherbb-cost" , cl::init(5) , cl::Hidden , cl::desc("The cost of a step in a different basic " "block than the killing MemoryDef" "(default = 5)")) static
MemorySSAPartialStoreLimit
cl::opt<unsigned> MemorySSAPartialStoreLimit("dse-memoryssa-partial-store-limit", cl::init(5), cl::Hidden, cl::desc("The maximum number candidates that only partially overwrite the " "killing MemoryDef to consider" " (default = 5)")) ("dse-memoryssa-partial-store-limit" , cl::init(5) , cl::Hidden , cl::desc("The maximum number candidates that only partially overwrite the " "killing MemoryDef to consider" " (default = 5)")) static
MemorySSAPathCheckLimit
cl::opt<unsigned> MemorySSAPathCheckLimit("dse-memoryssa-path-check-limit", cl::init(50), cl::Hidden, cl::desc("The maximum number of blocks to check when trying to prove that " "all paths to an exit go through a killing block (default = 50)")) ("dse-memoryssa-path-check-limit" , cl::init(50) , cl::Hidden , cl::desc("The maximum number of blocks to check when trying to prove that " "all paths to an exit go through a killing block (default = 50)")) static
MemorySSASameBBStepCost
cl::opt<unsigned> MemorySSASameBBStepCost("dse-memoryssa-samebb-cost", cl::init(1), cl::Hidden, cl::desc("The cost of a step in the same basic block as the killing MemoryDef" "(default = 1)")) ("dse-memoryssa-samebb-cost" , cl::init(1) , cl::Hidden , cl::desc("The cost of a step in the same basic block as the killing MemoryDef" "(default = 1)")) static
MemorySSAScanLimit
cl::opt<unsigned> MemorySSAScanLimit("dse-memoryssa-scanlimit", cl::init(150), cl::Hidden, cl::desc("The number of memory instructions to scan for " "dead store elimination (default = 100)")) ("dse-memoryssa-scanlimit" , cl::init(150) , cl::Hidden , cl::desc("The number of memory instructions to scan for " "dead store elimination (default = 100)")) static
MemorySSAUpwardsStepLimit
cl::opt<unsigned> MemorySSAUpwardsStepLimit("dse-memoryssa-walklimit", cl::init(90), cl::Hidden, cl::desc("The maximum number of steps while walking upwards to find " "MemoryDefs that may be killed (default = 90)")) ("dse-memoryssa-walklimit" , cl::init(90) , cl::Hidden , cl::desc("The maximum number of steps while walking upwards to find " "MemoryDefs that may be killed (default = 90)")) static