LLVM: lib/FileCheck/FileCheck.cpp File Reference
FileCheck.cpp File Reference
#include "llvm/FileCheck/FileCheck.h"
#include "FileCheckImpl.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Support/CheckedArithmetic.h"
#include "llvm/Support/FormatVariadic.h"
#include <cstdint>
#include <list>
#include <set>
#include <tuple>
#include <utility>
Functions
static int64_t getAsSigned (uint64_t UnsignedValue)
static char popFront (StringRef &S)
Variables
constexpr StringLiteral SpaceChars = " \t"
Function Documentation
getAsSigned()
static int64_t getAsSigned (uint64_t UnsignedValue) static
Definition at line 142 of file FileCheck.cpp.
Referenced by llvm::ExpressionValue::getAbsolute(), and llvm::ExpressionValue::getSignedValue().
popFront()
static char popFront (StringRef & S) static
Definition at line 451 of file FileCheck.cpp.
References C, llvm::StringRef::drop_front(), and llvm::StringRef::front().
Referenced by llvm::Pattern::parseNumericSubstitutionBlock().
Variable Documentation
SpaceChars
constexpr StringLiteral SpaceChars = " \t" constexpr
Definition at line 448 of file FileCheck.cpp.
Referenced by llvm::Pattern::parseNumericSubstitutionBlock().