LLVM: lib/Transforms/Utils/FixIrreducible.cpp File Reference
FixIrreducible.cpp File Reference
#include "llvm/Transforms/Utils/FixIrreducible.h"
#include "llvm/ADT/SCCIterator.h"
#include "llvm/Analysis/LoopIterator.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Utils.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
Classes
struct llvm::GraphTraits< Loop >
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "fix-irreducible"
Functions
INITIALIZE_PASS_BEGIN (FixIrreducible, "fix-irreducible", "Convert irreducible control-flow into natural loops", false, false) INITIALIZE_PASS_END(FixIrreducible
fix Convert irreducible control flow into natural static false void reconnectChildLoops (LoopInfo &LI, Loop *ParentLoop, Loop *NewLoop, SetVector< BasicBlock * > &Blocks, SetVector< BasicBlock * > &Headers)
static void createNaturalLoopInternal (LoopInfo &LI, DominatorTree &DT, Loop *ParentLoop, SetVector< BasicBlock * > &Blocks, SetVector< BasicBlock * > &Headers)
static BasicBlock * unwrapBlock (BasicBlock *B)
static BasicBlock * unwrapBlock (LoopBodyTraits::NodeRef &N)
static void createNaturalLoop (LoopInfo &LI, DominatorTree &DT, Function *F, SetVector< BasicBlock * > &Blocks, SetVector< BasicBlock * > &Headers)
static void createNaturalLoop (LoopInfo &LI, DominatorTree &DT, Loop &L, SetVector< BasicBlock * > &Blocks, SetVector< BasicBlock * > &Headers)
template<class Graph >
static bool makeReducible (LoopInfo &LI, DominatorTree &DT, Graph &&G)
static bool FixIrreducibleImpl (Function &F, LoopInfo &LI, DominatorTree &DT)
Variables
fix irreducible
fix Convert irreducible control flow into natural loops
fix Convert irreducible control flow into natural false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "fix-irreducible"
Definition at line 77 of file FixIrreducible.cpp.
Function Documentation
createNaturalLoop() [1/2]
static void createNaturalLoop (LoopInfo & LI, DominatorTree & DT, Function * F, SetVector< BasicBlock * > & Blocks, SetVector< BasicBlock * > & Headers) static
Definition at line 248 of file FixIrreducible.cpp.
References createNaturalLoopInternal().
Referenced by makeReducible().
createNaturalLoop() [2/2]
static void createNaturalLoop (LoopInfo & LI, DominatorTree & DT, Loop & L, SetVector< BasicBlock * > & Blocks, SetVector< BasicBlock * > & Headers) static
Definition at line 254 of file FixIrreducible.cpp.
References createNaturalLoopInternal().
createNaturalLoopInternal()
static void createNaturalLoopInternal (LoopInfo & LI, DominatorTree & DT, Loop * ParentLoop, SetVector< BasicBlock * > & Blocks, SetVector< BasicBlock * > & Headers) static
Definition at line 159 of file FixIrreducible.cpp.
References llvm::LoopBase< BlockT, LoopT >::addChildLoop(), llvm::LoopInfoBase< BlockT, LoopT >::addTopLevelLoop(), llvm::LoopInfoBase< BlockT, LoopT >::AllocateLoop(), assert(), llvm::LoopInfoBase< BlockT, LoopT >::changeLoopFor(), llvm::SetVector< T, Vector, Set >::count(), llvm::CreateControlFlowHub(), llvm::dbgs(), llvm::DomTreeUpdater::Eager, llvm::CallingConv::Fast, llvm::JumpTable::Full, G, llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), H, llvm::SetVector< T, Vector, Set >::insert(), LLVM_DEBUG, P, llvm::predecessors(), reconnectChildLoops(), llvm::LoopInfoBase< BlockT, LoopT >::verify(), llvm::DominatorTreeBase< NodeT, IsPostDom >::verify(), and llvm::LoopBase< BlockT, LoopT >::verifyLoop().
Referenced by createNaturalLoop().
FixIrreducibleImpl()
static bool FixIrreducibleImpl (Function & F, LoopInfo & LI, DominatorTree & DT) static
Definition at line 308 of file FixIrreducible.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::append_range(), llvm::dbgs(), llvm::SmallVectorBase< Size_T >::empty(), F, LLVM_DEBUG, makeReducible(), and llvm::SmallVectorImpl< T >::pop_back_val().
Referenced by llvm::FixIrreduciblePass::run().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (FixIrreducible , "fix-irreducible" , "Convert irreducible control-flow into natural loops" , false , false)
makeReducible()
template<class Graph > static bool makeReducible (LoopInfo & LI, DominatorTree & DT, Graph && G) static
Definition at line 262 of file FixIrreducible.cpp.
References assert(), llvm::SetVector< T, Vector, Set >::count(), createNaturalLoop(), llvm::dbgs(), llvm::SetVector< T, Vector, Set >::front(), G, llvm::SetVector< T, Vector, Set >::insert(), llvm::LoopInfoBase< BlockT, LoopT >::isLoopHeader(), llvm::DominatorTree::isReachableFromEntry(), LLVM_DEBUG, N, P, llvm::predecessors(), llvm::reverse(), llvm::scc_begin(), llvm::SetVector< T, Vector, Set >::size(), and unwrapBlock().
Referenced by FixIrreducibleImpl().
reconnectChildLoops()
fix Convert irreducible control flow into natural static false void reconnectChildLoops (LoopInfo & LI, Loop * ParentLoop, Loop * NewLoop, SetVector< BasicBlock * > & Blocks, SetVector< BasicBlock * > & Headers) static
Definition at line 117 of file FixIrreducible.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::dbgs(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::ARM_PROC::IE, LLVM_DEBUG, and llvm::partition().
Referenced by createNaturalLoopInternal().
unwrapBlock() [1/2]
static BasicBlock* unwrapBlock (BasicBlock * B) static
Definition at line 245 of file FixIrreducible.cpp.
References B.
Referenced by makeReducible().
unwrapBlock() [2/2]
static BasicBlock* unwrapBlock (LoopBodyTraits::NodeRef & N) static
Definition at line 246 of file FixIrreducible.cpp.
References N.
Variable Documentation
false
fix Convert irreducible control flow into natural false
Definition at line 113 of file FixIrreducible.cpp.
irreducible
fix irreducible
Definition at line 111 of file FixIrreducible.cpp.
loops
fix Convert irreducible control flow into natural loops
Definition at line 112 of file FixIrreducible.cpp.