LLVM: lib/Support/GraphWriter.cpp File Reference
GraphWriter.cpp File Reference
#include "llvm/Support/GraphWriter.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Config/config.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/ErrorOr.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Program.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <system_error>
#include <string>
#include <vector>
Functions
static std::string replaceIllegalFilenameChars (std::string Filename, const char ReplacementChar)
static bool ExecGraphViewer (StringRef ExecPath, std::vector< StringRef > &args, StringRef Filename, bool wait, std::string &ErrMsg)
static const char * getProgramName (GraphProgram::Name program)
Variables
static cl::opt< bool > ViewBackground ("view-background", cl::Hidden, cl::desc("Execute graph viewer in the background. Creates tmp file litter."))
Function Documentation
ExecGraphViewer()
static bool ExecGraphViewer (StringRef ExecPath, std::vector< StringRef > & args, StringRef Filename, bool wait, std::string & ErrMsg) static
Definition at line 118 of file GraphWriter.cpp.
References llvm::errs(), llvm::sys::ExecuteAndWait(), llvm::sys::ExecuteNoWait(), llvm::None, and llvm::sys::fs::remove().
Referenced by llvm::DisplayGraph().
getProgramName()
static const char* getProgramName (GraphProgram::Name program) static
Definition at line 157 of file GraphWriter.cpp.
References llvm::GraphProgram::CIRCO, llvm::GraphProgram::DOT, llvm::GraphProgram::FDP, llvm_unreachable, llvm::GraphProgram::NEATO, and llvm::GraphProgram::TWOPI.
Referenced by llvm::DisplayGraph().
replaceIllegalFilenameChars()
static std::string replaceIllegalFilenameChars (std::string Filename, const char ReplacementChar) static
Definition at line 79 of file GraphWriter.cpp.
References replace().
Referenced by llvm::createGraphFilename().
Variable Documentation
ViewBackground
cl::opt<bool> ViewBackground("view-background", cl::Hidden, cl::desc("Execute graph viewer in the background. Creates tmp file litter.")) ("view-background" , cl::Hidden , cl::desc("Execute graph viewer in the background. Creates tmp file litter.")) static
Referenced by llvm::DisplayGraph().