LLVM: lib/CodeGen/GlobalISel/InlineAsmLowering.cpp File Reference
InlineAsmLowering.cpp File Reference
This file implements the lowering from LLVM IR inline asm to MIR INLINEASM.
#include "llvm/CodeGen/GlobalISel/InlineAsmLowering.h"
#include "llvm/CodeGen/Analysis.h"
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
#include "llvm/CodeGen/GlobalISel/Utils.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
Macros
#define DEBUG_TYPE "inline-asm-lowering"
Functions
static void getRegistersForValue (MachineFunction &MF, MachineIRBuilder &MIRBuilder, GISelAsmOperandInfo &OpInfo, GISelAsmOperandInfo &RefOpInfo)
Assign virtual/physical registers for the specified register operand.
static unsigned getConstraintGenerality (TargetLowering::ConstraintType CT)
Return an integer indicating how general CT is.
static void chooseConstraint (TargetLowering::AsmOperandInfo &OpInfo, const TargetLowering *TLI)
static void computeConstraintToUse (const TargetLowering *TLI, TargetLowering::AsmOperandInfo &OpInfo)
static unsigned getNumOpRegs (const MachineInstr &I, unsigned OpIdx)
static bool buildAnyextOrCopy (Register Dst, Register Src, MachineIRBuilder &MIRBuilder)
Detailed Description
This file implements the lowering from LLVM IR inline asm to MIR INLINEASM.
Definition in file InlineAsmLowering.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "inline-asm-lowering"
Definition at line 26 of file InlineAsmLowering.cpp.
Function Documentation
buildAnyextOrCopy()
static bool buildAnyextOrCopy (Register Dst, Register Src, MachineIRBuilder & MIRBuilder) static
Definition at line 240 of file InlineAsmLowering.cpp.
References llvm::MachineIRBuilder::buildAnyExt(), llvm::MachineIRBuilder::buildCopy(), llvm::dbgs(), llvm::MachineIRBuilder::getMF(), llvm::MachineIRBuilder::getMRI(), llvm::MachineInstrBuilder::getReg(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), LLVM_DEBUG, MRI, llvm::LLT::scalar(), and TRI.
Referenced by llvm::InlineAsmLowering::lowerInlineAsm().
chooseConstraint()
static void chooseConstraint (TargetLowering::AsmOperandInfo & OpInfo, const TargetLowering * TLI) static
Definition at line 158 of file InlineAsmLowering.cpp.
References assert(), llvm::TargetLowering::C_Immediate, llvm::TargetLowering::C_Memory, llvm::TargetLowering::C_Other, llvm::TargetLowering::C_Register, llvm::TargetLowering::C_RegisterClass, llvm::TargetLowering::C_Unknown, llvm::InlineAsm::ConstraintInfo::Codes, llvm::TargetLowering::AsmOperandInfo::ConstraintCode, llvm::TargetLowering::AsmOperandInfo::ConstraintType, llvm::numbers::e, getConstraintGenerality(), llvm::TargetLowering::getConstraintType(), llvm::InlineAsm::ConstraintInfo::hasMatchingInput(), and llvm::InlineAsm::ConstraintInfo::isIndirect.
Referenced by computeConstraintToUse().
computeConstraintToUse()
static void computeConstraintToUse (const TargetLowering * TLI, TargetLowering::AsmOperandInfo & OpInfo) static
Definition at line 205 of file InlineAsmLowering.cpp.
References assert(), llvm::TargetLowering::AsmOperandInfo::CallOperandVal, chooseConstraint(), llvm::InlineAsm::ConstraintInfo::Codes, llvm::TargetLowering::AsmOperandInfo::ConstraintCode, llvm::TargetLowering::AsmOperandInfo::ConstraintType, llvm::TargetLowering::AsmOperandInfo::ConstraintVT, llvm::TargetLowering::getConstraintType(), and llvm::TargetLowering::LowerXConstraint().
Referenced by llvm::InlineAsmLowering::lowerInlineAsm().
getConstraintGenerality()
static unsigned getConstraintGenerality (TargetLowering::ConstraintType CT) static
Return an integer indicating how general CT is.
Definition at line 142 of file InlineAsmLowering.cpp.
References llvm::TargetLowering::C_Immediate, llvm::TargetLowering::C_Memory, llvm::TargetLowering::C_Other, llvm::TargetLowering::C_Register, llvm::TargetLowering::C_RegisterClass, llvm::TargetLowering::C_Unknown, and llvm_unreachable.
Referenced by chooseConstraint().
getNumOpRegs()
static unsigned getNumOpRegs (const MachineInstr & I, unsigned OpIdx) static
Definition at line 235 of file InlineAsmLowering.cpp.
References llvm::InlineAsm::getNumOperandRegisters(), and I.
Referenced by llvm::InlineAsmLowering::lowerInlineAsm().
getRegistersForValue()
static void getRegistersForValue (MachineFunction & MF, MachineIRBuilder & MIRBuilder, GISelAsmOperandInfo & OpInfo, GISelAsmOperandInfo & RefOpInfo) static
Assign virtual/physical registers for the specified register operand.
Definition at line 85 of file InlineAsmLowering.cpp.
References assert(), llvm::TargetRegisterClass::begin(), llvm::TargetLowering::C_Memory, llvm::MachineRegisterInfo::createVirtualRegister(), llvm::TargetRegisterClass::end(), llvm::Function::getContext(), llvm::MachineFunction::getFunction(), llvm::TargetLoweringBase::getNumRegisters(), llvm::TargetLowering::getRegForInlineAsmConstraint(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), I, llvm::MVT::Other, and TRI.
Referenced by llvm::InlineAsmLowering::lowerInlineAsm().