LLVM: llvm::orc::orcrpctpc Namespace Reference
llvm::orc::orcrpctpc Namespace Reference
Classes
struct ReserveMemRequestElement
struct ReserveMemResultElement
struct ReleaseOrFinalizeMemRequestElement
class GetTargetTriple
class GetPageSize
class ReserveMem
class FinalizeMem
class ReleaseMem
class WriteUInt8s
class WriteUInt16s
class WriteUInt32s
class WriteUInt64s
class WriteBuffers
class LoadDylib
class LookupSymbols
class RunMain
class RunWrapper
class CloseConnection
Typedefs
using ReserveMemRequest = std::vector< ReserveMemRequestElement >
using ReserveMemResult = std::vector< ReserveMemResultElement >
using ReleaseOrFinalizeMemRequest = std::vector< ReleaseOrFinalizeMemRequestElement >
using RemoteSymbolLookupSet = std::vector< std::pair< std::string, bool > >
using RemoteLookupRequest = std::pair< tpctypes::DylibHandle, RemoteSymbolLookupSet >
Enumerations
enum WireProtectionFlags : uint8_t { WPF_None = 0 , WPF_Read = 1U << 0 , WPF_Write = 1U << 1 , WPF_Exec = 1U << 2 }
Functions
WireProtectionFlags toWireProtectionFlags (sys::Memory::ProtectionFlags PF)
Convert from sys::Memory::ProtectionFlags.
sys::Memory::ProtectionFlags fromWireProtectionFlags (WireProtectionFlags WPF)
Typedef Documentation
ReleaseOrFinalizeMemRequest
using llvm::orc::orcrpctpc::ReleaseOrFinalizeMemRequest = typedef std::vector<ReleaseOrFinalizeMemRequestElement>
Definition at line 91 of file OrcRPCTPCServer.h.
RemoteLookupRequest
using llvm::orc::orcrpctpc::RemoteLookupRequest = typedef std::pair<tpctypes::DylibHandle, RemoteSymbolLookupSet>
Definition at line 280 of file OrcRPCTPCServer.h.
RemoteSymbolLookupSet
using llvm::orc::orcrpctpc::RemoteSymbolLookupSet = typedef std::vector<std::pair<std::string, bool> >
Definition at line 279 of file OrcRPCTPCServer.h.
ReserveMemRequest
using llvm::orc::orcrpctpc::ReserveMemRequest = typedef std::vector<ReserveMemRequestElement>
Definition at line 75 of file OrcRPCTPCServer.h.
ReserveMemResult
using llvm::orc::orcrpctpc::ReserveMemResult = typedef std::vector<ReserveMemResultElement>
Definition at line 83 of file OrcRPCTPCServer.h.
Enumeration Type Documentation
WireProtectionFlags
enum llvm::orc::orcrpctpc::WireProtectionFlags : uint8_t
Enumerator
WPF_None
WPF_Read
WPF_Write
WPF_Exec
Definition at line 36 of file OrcRPCTPCServer.h.
Function Documentation
fromWireProtectionFlags()
sys::Memory::ProtectionFlags llvm::orc::orcrpctpc::fromWireProtectionFlags (WireProtectionFlags WPF) inline
Definition at line 58 of file OrcRPCTPCServer.h.
References llvm::sys::Memory::MF_EXEC, llvm::sys::Memory::MF_READ, llvm::sys::Memory::MF_WRITE, WPF_Exec, WPF_Read, and WPF_Write.
Referenced by llvm::orc::OrcRPCTPCJITLinkMemoryManager< OrcRPCTPCImplT >::allocate().
toWireProtectionFlags()
WireProtectionFlags llvm::orc::orcrpctpc::toWireProtectionFlags (sys::Memory::ProtectionFlags PF) inline
Convert from sys::Memory::ProtectionFlags.
Definition at line 46 of file OrcRPCTPCServer.h.
References llvm::sys::Memory::MF_EXEC, llvm::sys::Memory::MF_READ, llvm::sys::Memory::MF_WRITE, WPF_Exec, WPF_None, WPF_Read, and WPF_Write.
Referenced by llvm::orc::OrcRPCTPCJITLinkMemoryManager< OrcRPCTPCImplT >::allocate(), llvm::orc::OrcRPCTPCJITLinkMemoryManager< OrcRPCTPCImplT >::OrcRPCAllocation::deallocate(), and llvm::orc::OrcRPCTPCJITLinkMemoryManager< OrcRPCTPCImplT >::OrcRPCAllocation::finalizeAsync().