LLVM: llvm::ELFYAML Namespace Reference
llvm::ELFYAML Namespace Reference
Classes
struct FileHeader
struct SectionHeader
struct Symbol
struct SectionOrType
struct DynamicEntry
struct BBAddrMapEntry
struct StackSizeEntry
struct NoteEntry
struct Chunk
struct Section
struct Fill
struct SectionHeaderTable
struct BBAddrMapSection
struct StackSizesSection
struct DynamicSection
struct RawContentSection
struct NoBitsSection
struct NoteSection
struct HashSection
struct GnuHashHeader
struct GnuHashSection
struct VernauxEntry
struct VerneedEntry
struct VerneedSection
struct AddrsigSection
struct LinkerOption
struct LinkerOptionsSection
struct DependentLibrariesSection
struct CallGraphEntry
struct CallGraphProfileSection
struct SymverSection
struct VerdefEntry
struct VerdefSection
struct GroupSection
struct Relocation
struct RelocationSection
struct RelrSection
struct SymtabShndxSection
struct ARMIndexTableEntry
struct ARMIndexTableSection
struct MipsABIFlags
struct ProgramHeader
struct Object
Functions
StringRef dropUniqueSuffix (StringRef S)
std::string appendUniqueSuffix (StringRef Name, const Twine &Msg)
template<class ELFT >
unsigned getDefaultShEntSize (unsigned EMachine, ELF_SHT SecType, StringRef SecName)
bool shouldAllocateFileSpace (ArrayRef< ProgramHeader > Phdrs, const NoBitsSection &S)
Function Documentation
appendUniqueSuffix()
std::string llvm::ELFYAML::appendUniqueSuffix (StringRef Name, const Twine & Msg)
Definition at line 646 of file ELFEmitter.cpp.
References llvm::MipsISD::Ret, SuffixEnd, and SuffixStart.
dropUniqueSuffix()
StringRef llvm::ELFYAML::dropUniqueSuffix (StringRef S)
Definition at line 653 of file ELFEmitter.cpp.
References llvm::StringRef::back(), llvm::StringRef::empty(), llvm::StringRef::rfind(), llvm::StringRef::substr(), SuffixEnd, and SuffixStart.
Referenced by llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Chunk > >::mapping().
getDefaultShEntSize()
template<class ELFT > unsigned llvm::ELFYAML::getDefaultShEntSize (unsigned EMachine, ELF_SHT SecType, StringRef SecName)
Definition at line 75 of file ELFYAML.h.
References llvm::ELF::EM_MIPS, llvm::ELF::SHT_DYNAMIC, llvm::ELF::SHT_DYNSYM, llvm::ELF::SHT_GNU_versym, llvm::ELF::SHT_GROUP, llvm::ELF::SHT_HASH, llvm::ELF::SHT_LLVM_CALL_GRAPH_PROFILE, llvm::ELF::SHT_MIPS_ABIFLAGS, llvm::ELF::SHT_REL, llvm::ELF::SHT_RELA, llvm::ELF::SHT_RELR, llvm::ELF::SHT_SYMTAB, and llvm::ELF::SHT_SYMTAB_SHNDX.
shouldAllocateFileSpace()
bool llvm::ELFYAML::shouldAllocateFileSpace (ArrayRef< ProgramHeader > Phdrs, const NoBitsSection & S)
Definition at line 1180 of file ELFEmitter.cpp.
References llvm::any_of(), C, and llvm::find_if().