LLVM: adjust::ldi Namespace Reference
adjust::ldi Namespace Reference
Fixups relating to the LDI instruction.
Functions
static void fixup (unsigned Size, const MCFixup &Fixup, uint64_t &Value, MCContext *Ctx=nullptr)
Adjusts a value to fix up the immediate of an LDI Rd, K instruction.
static void neg (uint64_t &Value)
static void lo8 (unsigned Size, const MCFixup &Fixup, uint64_t &Value, MCContext *Ctx=nullptr)
static void hi8 (unsigned Size, const MCFixup &Fixup, uint64_t &Value, MCContext *Ctx=nullptr)
static void hh8 (unsigned Size, const MCFixup &Fixup, uint64_t &Value, MCContext *Ctx=nullptr)
static void ms8 (unsigned Size, const MCFixup &Fixup, uint64_t &Value, MCContext *Ctx=nullptr)
Detailed Description
Fixups relating to the LDI instruction.
Function Documentation
fixup()
static void adjust::ldi::fixup (unsigned Size, const MCFixup & Fixup, uint64_t & Value, MCContext * Ctx = nullptr) static
Adjusts a value to fix up the immediate of an LDI Rd, K instruction.
Resolves to: 0000 KKKK 0000 KKKK Offset of 0 (so the result isn't left-shifted before application).
Definition at line 202 of file AVRAsmBackend.cpp.
Referenced by llvm::AVRAsmBackend::adjustFixupValue(), hh8(), hi8(), lo8(), and ms8().
hh8()
static void adjust::ldi::hh8 (unsigned Size, const MCFixup & Fixup, uint64_t & Value, MCContext * Ctx = nullptr) static
Definition at line 224 of file AVRAsmBackend.cpp.
References fixup(), Fixup, and llvm::Check::Size.
Referenced by llvm::AVRAsmBackend::adjustFixupValue().
hi8()
static void adjust::ldi::hi8 (unsigned Size, const MCFixup & Fixup, uint64_t & Value, MCContext * Ctx = nullptr) static
Definition at line 218 of file AVRAsmBackend.cpp.
References fixup(), Fixup, and llvm::Check::Size.
Referenced by llvm::AVRAsmBackend::adjustFixupValue().
lo8()
static void adjust::ldi::lo8 (unsigned Size, const MCFixup & Fixup, uint64_t & Value, MCContext * Ctx = nullptr) static
Definition at line 212 of file AVRAsmBackend.cpp.
References fixup(), Fixup, and llvm::Check::Size.
Referenced by llvm::AVRAsmBackend::adjustFixupValue().
ms8()
static void adjust::ldi::ms8 (unsigned Size, const MCFixup & Fixup, uint64_t & Value, MCContext * Ctx = nullptr) static
Definition at line 230 of file AVRAsmBackend.cpp.
References fixup(), Fixup, and llvm::Check::Size.
Referenced by llvm::AVRAsmBackend::adjustFixupValue().
neg()
static void adjust::ldi::neg (uint64_t & Value) static
Definition at line 210 of file AVRAsmBackend.cpp.
Referenced by llvm::AVRAsmBackend::adjustFixupValue().