LLVM: llvm::codegen Namespace Reference
llvm::codegen Namespace Reference
Classes
struct RegisterCodeGenFlags
Create this object with static storage to register codegen-related command line options.
Functions
std::string getMArch ()
std::string getMCPU ()
std::vector< std::string > getMAttrs ()
Reloc::Model getRelocModel ()
Optional< Reloc::Model > getExplicitRelocModel ()
ThreadModel::Model getThreadModel ()
CodeModel::Model getCodeModel ()
Optional< CodeModel::Model > getExplicitCodeModel ()
llvm::ExceptionHandling getExceptionModel ()
CodeGenFileType getFileType ()
Optional< CodeGenFileType > getExplicitFileType ()
llvm::FramePointer::FP getFramePointerUsage ()
bool getEnableUnsafeFPMath ()
bool getEnableNoInfsFPMath ()
bool getEnableNoNaNsFPMath ()
bool getEnableNoSignedZerosFPMath ()
bool getEnableNoTrappingFPMath ()
DenormalMode::DenormalModeKind getDenormalFPMath ()
DenormalMode::DenormalModeKind getDenormalFP32Math ()
bool getEnableHonorSignDependentRoundingFPMath ()
llvm::FloatABI::ABIType getFloatABIForCalls ()
llvm::FPOpFusion::FPOpFusionMode getFuseFPOps ()
bool getDontPlaceZerosInBSS ()
bool getEnableGuaranteedTailCallOpt ()
bool getEnableAIXExtendedAltivecABI ()
bool getDisableTailCalls ()
bool getStackSymbolOrdering ()
unsigned getOverrideStackAlignment ()
bool getStackRealign ()
std::string getTrapFuncName ()
bool getUseCtors ()
bool getRelaxELFRelocations ()
bool getDataSections ()
Optional< bool > getExplicitDataSections ()
bool getFunctionSections ()
Optional< bool > getExplicitFunctionSections ()
bool getIgnoreXCOFFVisibility ()
bool getXCOFFTracebackTable ()
std::string getBBSections ()
std::string getStackProtectorGuard ()
unsigned getStackProtectorGuardOffset ()
std::string getStackProtectorGuardReg ()
unsigned getTLSSize ()
bool getEmulatedTLS ()
bool getUniqueSectionNames ()
bool getUniqueBasicBlockSectionNames ()
llvm::EABI getEABIVersion ()
llvm::DebuggerKind getDebuggerTuningOpt ()
bool getEnableStackSizeSection ()
bool getEnableAddrsig ()
bool getEmitCallSiteInfo ()
bool getEnableMachineFunctionSplitter ()
bool getEnableDebugEntryValues ()
bool getPseudoProbeForProfiling ()
bool getValueTrackingVariableLocations ()
bool getForceDwarfFrameSection ()
bool getXRayOmitFunctionIndex ()
llvm::BasicBlockSection getBBSectionsMode (llvm::TargetOptions &Options)
llvm::StackProtectorGuards getStackProtectorGuardMode (llvm::TargetOptions &Options)
TargetOptions InitTargetOptionsFromCodeGenFlags (const llvm::Triple &TheTriple)
Common utility function tightly tied to the options listed here.
std::string getCPUStr ()
std::string getFeaturesStr ()
std::vector< std::string > getFeatureList ()
void renderBoolStringAttr (AttrBuilder &B, StringRef Name, bool Val)
void setFunctionAttributes (StringRef CPU, StringRef Features, Function &F)
Set function attributes of function F based on CPU, Features, and command line flags.
void setFunctionAttributes (StringRef CPU, StringRef Features, Module &M)
Set function attributes of functions in Module M based on CPU, Features, and command line flags.
Function Documentation
getBBSections()
std::string llvm::codegen::getBBSections ()
Referenced by getBBSectionsMode().
getBBSectionsMode()
llvm::BasicBlockSection llvm::codegen::getBBSectionsMode (llvm::TargetOptions & Options)
Definition at line 478 of file CommandFlags.cpp.
References llvm::All, llvm::TargetOptions::BBSectionsFuncListBuf, llvm::errs(), getBBSections(), llvm::ErrorOr< T >::getError(), llvm::MemoryBuffer::getFile(), llvm::Labels, llvm::List, llvm::move(), and llvm::None.
Referenced by InitTargetOptionsFromCodeGenFlags().
getCodeModel()
CodeModel::Model llvm::codegen::getCodeModel ()
Referenced by llvm::PPCTargetLowering::getPICJumpTableRelocBase(), llvm::PPCTargetLowering::getPICJumpTableRelocBaseExpr(), llvm::LanaiTargetLowering::LowerJumpTable(), llvm::SparcTargetLowering::makeAddress(), and llvm::VETargetLowering::makeAddress().
getCPUStr()
std::string llvm::codegen::getCPUStr ()
Definition at line 578 of file CommandFlags.cpp.
References llvm::sys::getHostCPUName(), and getMCPU().
getDataSections()
bool llvm::codegen::getDataSections ()
getDebuggerTuningOpt()
llvm::DebuggerKind llvm::codegen::getDebuggerTuningOpt ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getDenormalFP32Math()
DenormalMode::DenormalModeKind llvm::codegen::getDenormalFP32Math ()
Referenced by setFunctionAttributes().
getDenormalFPMath()
DenormalMode::DenormalModeKind llvm::codegen::getDenormalFPMath ()
Referenced by InitTargetOptionsFromCodeGenFlags(), and setFunctionAttributes().
getDisableTailCalls()
bool llvm::codegen::getDisableTailCalls ()
Referenced by setFunctionAttributes().
getDontPlaceZerosInBSS()
bool llvm::codegen::getDontPlaceZerosInBSS ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getEABIVersion()
llvm::EABI llvm::codegen::getEABIVersion ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getEmitCallSiteInfo()
bool llvm::codegen::getEmitCallSiteInfo ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getEmulatedTLS()
bool llvm::codegen::getEmulatedTLS ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getEnableAddrsig()
bool llvm::codegen::getEnableAddrsig ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getEnableAIXExtendedAltivecABI()
bool llvm::codegen::getEnableAIXExtendedAltivecABI ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getEnableDebugEntryValues()
bool llvm::codegen::getEnableDebugEntryValues ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getEnableGuaranteedTailCallOpt()
bool llvm::codegen::getEnableGuaranteedTailCallOpt ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getEnableHonorSignDependentRoundingFPMath()
bool llvm::codegen::getEnableHonorSignDependentRoundingFPMath ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getEnableMachineFunctionSplitter()
bool llvm::codegen::getEnableMachineFunctionSplitter ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getEnableNoInfsFPMath()
bool llvm::codegen::getEnableNoInfsFPMath ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getEnableNoNaNsFPMath()
bool llvm::codegen::getEnableNoNaNsFPMath ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getEnableNoSignedZerosFPMath()
bool llvm::codegen::getEnableNoSignedZerosFPMath ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getEnableNoTrappingFPMath()
bool llvm::codegen::getEnableNoTrappingFPMath ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getEnableStackSizeSection()
bool llvm::codegen::getEnableStackSizeSection ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getEnableUnsafeFPMath()
bool llvm::codegen::getEnableUnsafeFPMath ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getExceptionModel()
llvm::ExceptionHandling llvm::codegen::getExceptionModel ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getExplicitCodeModel()
Optional<CodeModel::Model> llvm::codegen::getExplicitCodeModel ()
getExplicitDataSections()
Optional<bool> llvm::codegen::getExplicitDataSections ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getExplicitFileType()
Optional<CodeGenFileType> llvm::codegen::getExplicitFileType ()
getExplicitFunctionSections()
Optional<bool> llvm::codegen::getExplicitFunctionSections ()
getExplicitRelocModel()
Optional<Reloc::Model> llvm::codegen::getExplicitRelocModel ()
getFeatureList()
std::vector< std::string > llvm::codegen::getFeatureList ()
Definition at line 608 of file CommandFlags.cpp.
References llvm::SubtargetFeatures::AddFeature(), F, llvm::SubtargetFeatures::getFeatures(), llvm::sys::getHostCPUFeatures(), getMAttrs(), and getMCPU().
getFeaturesStr()
std::string llvm::codegen::getFeaturesStr ()
Definition at line 588 of file CommandFlags.cpp.
References llvm::SubtargetFeatures::AddFeature(), F, llvm::sys::getHostCPUFeatures(), getMAttrs(), getMCPU(), and llvm::SubtargetFeatures::getString().
getFileType()
CodeGenFileType llvm::codegen::getFileType ()
getFloatABIForCalls()
llvm::FloatABI::ABIType llvm::codegen::getFloatABIForCalls ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getForceDwarfFrameSection()
bool llvm::codegen::getForceDwarfFrameSection ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getFramePointerUsage()
llvm::FramePointer::FP llvm::codegen::getFramePointerUsage ()
Referenced by setFunctionAttributes().
getFunctionSections()
bool llvm::codegen::getFunctionSections ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getFuseFPOps()
llvm::FPOpFusion::FPOpFusionMode llvm::codegen::getFuseFPOps ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getIgnoreXCOFFVisibility()
bool llvm::codegen::getIgnoreXCOFFVisibility ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getMArch()
std::string llvm::codegen::getMArch ()
getMAttrs()
std::vector<std::string> llvm::codegen::getMAttrs ()
Referenced by getFeatureList(), and getFeaturesStr().
getMCPU()
std::string llvm::codegen::getMCPU ()
Referenced by getCPUStr(), getFeatureList(), and getFeaturesStr().
getOverrideStackAlignment()
unsigned llvm::codegen::getOverrideStackAlignment ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getPseudoProbeForProfiling()
bool llvm::codegen::getPseudoProbeForProfiling ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getRelaxELFRelocations()
bool llvm::codegen::getRelaxELFRelocations ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getRelocModel()
Reloc::Model llvm::codegen::getRelocModel ()
getStackProtectorGuard()
std::string llvm::codegen::getStackProtectorGuard ()
Referenced by getStackProtectorGuardMode().
getStackProtectorGuardMode()
llvm::StackProtectorGuards llvm::codegen::getStackProtectorGuardMode (llvm::TargetOptions & Options)
Definition at line 499 of file CommandFlags.cpp.
References llvm::TargetOptions::BBSectionsFuncListBuf, llvm::errs(), llvm::ErrorOr< T >::getError(), llvm::MemoryBuffer::getFile(), getStackProtectorGuard(), llvm::Global, llvm::move(), llvm::None, and llvm::TLS.
Referenced by InitTargetOptionsFromCodeGenFlags().
getStackProtectorGuardOffset()
unsigned llvm::codegen::getStackProtectorGuardOffset ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getStackProtectorGuardReg()
std::string llvm::codegen::getStackProtectorGuardReg ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getStackRealign()
bool llvm::codegen::getStackRealign ()
Referenced by setFunctionAttributes().
getStackSymbolOrdering()
bool llvm::codegen::getStackSymbolOrdering ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getThreadModel()
ThreadModel::Model llvm::codegen::getThreadModel ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getTLSSize()
unsigned llvm::codegen::getTLSSize ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getTrapFuncName()
std::string llvm::codegen::getTrapFuncName ()
Referenced by setFunctionAttributes().
getUniqueBasicBlockSectionNames()
bool llvm::codegen::getUniqueBasicBlockSectionNames ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getUniqueSectionNames()
bool llvm::codegen::getUniqueSectionNames ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getUseCtors()
bool llvm::codegen::getUseCtors ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getValueTrackingVariableLocations()
bool llvm::codegen::getValueTrackingVariableLocations ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getXCOFFTracebackTable()
bool llvm::codegen::getXCOFFTracebackTable ()
Referenced by InitTargetOptionsFromCodeGenFlags().
getXRayOmitFunctionIndex()
bool llvm::codegen::getXRayOmitFunctionIndex ()
Referenced by InitTargetOptionsFromCodeGenFlags().
InitTargetOptionsFromCodeGenFlags()
TargetOptions llvm::codegen::InitTargetOptionsFromCodeGenFlags (const llvm::Triple & TheTriple)
Common utility function tightly tied to the options listed here.
Initializes a TargetOptions object with CodeGen flags and returns it. TheTriple is used to determine the default value for options if options are not explicitly specified. If those triple dependant options value do not have effect for your component, a default Triple() could be passed in.
Definition at line 519 of file CommandFlags.cpp.
References llvm::TargetOptions::AllowFPOpFusion, llvm::TargetOptions::BBSections, llvm::TargetOptions::DataSections, llvm::TargetOptions::DebuggerTuning, llvm::FloatABI::Default, llvm::TargetOptions::EABIVersion, llvm::TargetOptions::EmitAddrsig, llvm::TargetOptions::EmitCallSiteInfo, llvm::TargetOptions::EmitStackSizeSection, llvm::TargetOptions::EmulatedTLS, llvm::TargetOptions::EnableAIXExtendedAltivecABI, llvm::TargetOptions::EnableDebugEntryValues, llvm::TargetOptions::EnableMachineFunctionSplitter, llvm::TargetOptions::ExceptionModel, llvm::TargetOptions::ExplicitEmulatedTLS, llvm::TargetOptions::FloatABIType, llvm::TargetOptions::ForceDwarfFrameSection, llvm::TargetOptions::FunctionSections, getBBSectionsMode(), getDebuggerTuningOpt(), getDenormalFPMath(), getDontPlaceZerosInBSS(), getEABIVersion(), getEmitCallSiteInfo(), getEmulatedTLS(), getEnableAddrsig(), getEnableAIXExtendedAltivecABI(), getEnableDebugEntryValues(), getEnableGuaranteedTailCallOpt(), getEnableHonorSignDependentRoundingFPMath(), getEnableMachineFunctionSplitter(), getEnableNoInfsFPMath(), getEnableNoNaNsFPMath(), getEnableNoSignedZerosFPMath(), getEnableNoTrappingFPMath(), getEnableStackSizeSection(), getEnableUnsafeFPMath(), getExceptionModel(), getExplicitDataSections(), getFloatABIForCalls(), getForceDwarfFrameSection(), getFunctionSections(), getFuseFPOps(), getIgnoreXCOFFVisibility(), getOverrideStackAlignment(), getPseudoProbeForProfiling(), getRelaxELFRelocations(), getStackProtectorGuardMode(), getStackProtectorGuardOffset(), getStackProtectorGuardReg(), getStackSymbolOrdering(), getThreadModel(), getTLSSize(), getUniqueBasicBlockSectionNames(), getUniqueSectionNames(), getUseCtors(), llvm::Optional< T >::getValueOr(), getValueTrackingVariableLocations(), getXCOFFTracebackTable(), getXRayOmitFunctionIndex(), llvm::TargetOptions::GuaranteedTailCallOpt, llvm::Triple::hasDefaultDataSections(), llvm::TargetOptions::HonorSignDependentRoundingFPMathOption, llvm::TargetOptions::IgnoreXCOFFVisibility, llvm::mc::InitMCTargetOptionsFromFlags(), llvm::TargetOptions::MCOptions, llvm::TargetOptions::NoInfsFPMath, llvm::TargetOptions::NoNaNsFPMath, llvm::TargetOptions::NoSignedZerosFPMath, llvm::TargetOptions::NoTrappingFPMath, llvm::TargetOptions::NoZerosInBSS, llvm::TargetOptions::PseudoProbeForProfiling, llvm::TargetOptions::RelaxELFRelocations, llvm::TargetOptions::setFPDenormalMode(), llvm::TargetOptions::StackAlignmentOverride, llvm::TargetOptions::StackProtectorGuard, llvm::TargetOptions::StackProtectorGuardOffset, llvm::TargetOptions::StackProtectorGuardReg, llvm::TargetOptions::StackSymbolOrdering, llvm::TargetOptions::ThreadModel, llvm::TargetOptions::TLSSize, llvm::TargetOptions::UniqueBasicBlockSectionNames, llvm::TargetOptions::UniqueSectionNames, llvm::TargetOptions::UnsafeFPMath, llvm::TargetOptions::UseInitArray, llvm::TargetOptions::ValueTrackingVariableLocations, llvm::TargetOptions::XCOFFTracebackTable, and llvm::TargetOptions::XRayOmitFunctionIndex.
renderBoolStringAttr()
void llvm::codegen::renderBoolStringAttr (AttrBuilder & B, StringRef Name, bool Val)
Definition at line 628 of file CommandFlags.cpp.
References B.
setFunctionAttributes() [1/2]
void llvm::codegen::setFunctionAttributes (StringRef CPU, StringRef Features, Function & F)
Set function attributes of function F based on CPU, Features, and command line flags.
Definition at line 640 of file CommandFlags.cpp.
References llvm::AttrBuilder::addAttribute(), llvm::FramePointer::All, llvm::SmallString< InternalLen >::append(), llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, B, llvm::StringRef::empty(), F, llvm::AttributeList::FunctionIndex, llvm::Attribute::get(), getDenormalFP32Math(), getDenormalFPMath(), getDisableTailCalls(), getFramePointerUsage(), getStackRealign(), getTrapFuncName(), HANDLE_BOOL_ATTR, I, llvm::FramePointer::None, llvm::FramePointer::NonLeaf, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::dwarf::toStringRef().
Referenced by setFunctionAttributes().
setFunctionAttributes() [2/2]
void llvm::codegen::setFunctionAttributes (StringRef CPU, StringRef Features, Module & M)
Set function attributes of functions in Module M based on CPU, Features, and command line flags.
Definition at line 718 of file CommandFlags.cpp.
References F, and setFunctionAttributes().