LLVM: llvm::ELFAttrs Namespace Reference
llvm::ELFAttrs Namespace Reference
Enumerations
enum AttrType : unsigned { File = 1 , Section = 2 , Symbol = 3 }
enum AttrMagic { Format_Version = 0x41 }
Functions
StringRef attrTypeAsString (unsigned attr, TagNameMap tagNameMap, bool hasTagPrefix=true)
Optional< unsigned > attrTypeFromString (StringRef tag, TagNameMap tagNameMap)
Enumeration Type Documentation
AttrMagic
enum llvm::ELFAttrs::AttrMagic
Enumerator
Format_Version
Definition at line 33 of file ELFAttributes.h.
AttrType
enum llvm::ELFAttrs::AttrType : unsigned
Enumerator
File
Section
Symbol
Definition at line 26 of file ELFAttributes.h.
Function Documentation
attrTypeAsString()
StringRef llvm::ELFAttrs::attrTypeAsString (unsigned attr, TagNameMap tagNameMap, bool hasTagPrefix = true)
Definition at line 14 of file ELFAttributes.cpp.
References llvm::TagNameItem::attr, llvm::StringRef::drop_front(), llvm::ArrayRef< T >::end(), and llvm::find_if().
Referenced by llvm::ELFAttributeParser::integerAttribute(), llvm::ELFAttributeParser::printAttribute(), and llvm::ELFAttributeParser::stringAttribute().
attrTypeFromString()
Optional< unsigned > llvm::ELFAttrs::attrTypeFromString (StringRef tag, TagNameMap tagNameMap)
Definition at line 24 of file ELFAttributes.cpp.
References llvm::StringRef::drop_front(), llvm::ArrayRef< T >::end(), llvm::find_if(), llvm::None, llvm::StringRef::startswith(), and llvm::TagNameItem::tagName.