LLVM: lib/Analysis/ProfileSummaryInfo.cpp File Reference
ProfileSummaryInfo.cpp File Reference
#include "llvm/Analysis/ProfileSummaryInfo.h"
#include "llvm/Analysis/BlockFrequencyInfo.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ProfileSummary.h"
#include "llvm/InitializePasses.h"
#include "llvm/ProfileData/ProfileCommon.h"
#include "llvm/Support/CommandLine.h"
Functions
INITIALIZE_PASS (ProfileSummaryInfoWrapperPass, "profile-summary-info", "Profile summary info", false, true) ProfileSummaryInfoWrapperPass
Variables
static cl::opt< int > ProfileSummaryCutoffHot ("profile-summary-cutoff-hot", cl::Hidden, cl::init(990000), cl::ZeroOrMore, cl::desc("A count is hot if it exceeds the minimum count to" " reach this percentile of total counts."))
static cl::opt< int > ProfileSummaryCutoffCold ("profile-summary-cutoff-cold", cl::Hidden, cl::init(999999), cl::ZeroOrMore, cl::desc("A count is cold if it is below the minimum count" " to reach this percentile of total counts."))
static cl::opt< unsigned > ProfileSummaryHugeWorkingSetSizeThreshold ("profile-summary-huge-working-set-size-threshold", cl::Hidden, cl::init(15000), cl::ZeroOrMore, cl::desc("The code working set size is considered huge if the number of" " blocks required to reach the -profile-summary-cutoff-hot" " percentile exceeds this count."))
static cl::opt< unsigned > ProfileSummaryLargeWorkingSetSizeThreshold ("profile-summary-large-working-set-size-threshold", cl::Hidden, cl::init(12500), cl::ZeroOrMore, cl::desc("The code working set size is considered large if the number of" " blocks required to reach the -profile-summary-cutoff-hot" " percentile exceeds this count."))
static cl::opt< int > ProfileSummaryHotCount ("profile-summary-hot-count", cl::ReallyHidden, cl::ZeroOrMore, cl::desc("A fixed hot count that overrides the count derived from" " profile-summary-cutoff-hot"))
static cl::opt< int > ProfileSummaryColdCount ("profile-summary-cold-count", cl::ReallyHidden, cl::ZeroOrMore, cl::desc("A fixed cold count that overrides the count derived from" " profile-summary-cutoff-cold"))
static cl::opt< bool > PartialProfile ("partial-profile", cl::Hidden, cl::init(false), cl::desc("Specify the current profile is used as a partial profile."))
cl::opt< bool > ScalePartialSampleProfileWorkingSetSize ("scale-partial-sample-profile-working-set-size", cl::Hidden, cl::init(true), cl::desc("If true, scale the working set size of the partial sample profile " "by the partial profile ratio to reflect the size of the program " "being compiled."))
static cl::opt< double > PartialSampleProfileWorkingSetSizeScaleFactor ("partial-sample-profile-working-set-size-scale-factor", cl::Hidden, cl::init(0.008), cl::desc("The scale factor used to scale the working set size of the " "partial sample profile along with the partial profile ratio. " "This includes the factor of the profile counter per block " "and the factor to scale the working set size to use the same " "shared thresholds as PGO."))
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (ProfileSummaryInfoWrapperPass , "profile-summary-info" , "Profile summary info" , false , true)
Definition at line 421 of file ProfileSummaryInfo.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeProfileSummaryInfoWrapperPassPass().
Variable Documentation
PartialProfile
cl::opt<bool> PartialProfile("partial-profile", cl::Hidden, cl::init(false), cl::desc("Specify the current profile is used as a partial profile.")) ("partial-profile" , cl::Hidden , cl::init(false) , cl::desc("Specify the current profile is used as a partial profile.")) static
Referenced by llvm::ProfileSummaryInfo::hasPartialSampleProfile().
PartialSampleProfileWorkingSetSizeScaleFactor
cl::opt<double> PartialSampleProfileWorkingSetSizeScaleFactor("partial-sample-profile-working-set-size-scale-factor", cl::Hidden, cl::init(0.008), cl::desc("The scale factor used to scale the working set size of the " "partial sample profile along with the partial profile ratio. " "This includes the factor of the profile counter per block " "and the factor to scale the working set size to use the same " "shared thresholds as PGO.")) ("partial-sample-profile-working-set-size-scale-factor" , cl::Hidden , cl::init(0.008) , cl::desc("The scale factor used to scale the working set size of the " "partial sample profile along with the partial profile ratio. " "This includes the factor of the profile counter per block " "and the factor to scale the working set size to use the same " "shared thresholds as PGO.")) static
ProfileSummaryColdCount
cl::opt<int> ProfileSummaryColdCount("profile-summary-cold-count", cl::ReallyHidden, cl::ZeroOrMore, cl::desc("A fixed cold count that overrides the count derived from" " profile-summary-cutoff-cold")) ("profile-summary-cold-count" , cl::ReallyHidden , cl::ZeroOrMore , cl::desc("A fixed cold count that overrides the count derived from" " profile-summary-cutoff-cold")) static
ProfileSummaryCutoffCold
cl::opt<int> ProfileSummaryCutoffCold("profile-summary-cutoff-cold", cl::Hidden, cl::init(999999), cl::ZeroOrMore, cl::desc("A count is cold if it is below the minimum count" " to reach this percentile of total counts.")) ("profile-summary-cutoff-cold" , cl::Hidden , cl::init(999999) , cl::ZeroOrMore , cl::desc("A count is cold if it is below the minimum count" " to reach this percentile of total counts.")) static
ProfileSummaryCutoffHot
cl::opt<int> ProfileSummaryCutoffHot("profile-summary-cutoff-hot", cl::Hidden, cl::init(990000), cl::ZeroOrMore, cl::desc("A count is hot if it exceeds the minimum count to" " reach this percentile of total counts.")) ("profile-summary-cutoff-hot" , cl::Hidden , cl::init(990000) , cl::ZeroOrMore , cl::desc("A count is hot if it exceeds the minimum count to" " reach this percentile of total counts.")) static
ProfileSummaryHotCount
cl::opt<int> ProfileSummaryHotCount("profile-summary-hot-count", cl::ReallyHidden, cl::ZeroOrMore, cl::desc("A fixed hot count that overrides the count derived from" " profile-summary-cutoff-hot")) ("profile-summary-hot-count" , cl::ReallyHidden , cl::ZeroOrMore , cl::desc("A fixed hot count that overrides the count derived from" " profile-summary-cutoff-hot")) static
ProfileSummaryHugeWorkingSetSizeThreshold
cl::opt<unsigned> ProfileSummaryHugeWorkingSetSizeThreshold("profile-summary-huge-working-set-size-threshold", cl::Hidden, cl::init(15000), cl::ZeroOrMore, cl::desc("The code working set size is considered huge if the number of" " blocks required to reach the -profile-summary-cutoff-hot" " percentile exceeds this count.")) ("profile-summary-huge-working-set-size-threshold" , cl::Hidden , cl::init(15000) , cl::ZeroOrMore , cl::desc("The code working set size is considered huge if the number of" " blocks required to reach the -profile-summary-cutoff-hot" " percentile exceeds this count.")) static
ProfileSummaryLargeWorkingSetSizeThreshold
cl::opt<unsigned> ProfileSummaryLargeWorkingSetSizeThreshold("profile-summary-large-working-set-size-threshold", cl::Hidden, cl::init(12500), cl::ZeroOrMore, cl::desc("The code working set size is considered large if the number of" " blocks required to reach the -profile-summary-cutoff-hot" " percentile exceeds this count.")) ("profile-summary-large-working-set-size-threshold" , cl::Hidden , cl::init(12500) , cl::ZeroOrMore , cl::desc("The code working set size is considered large if the number of" " blocks required to reach the -profile-summary-cutoff-hot" " percentile exceeds this count.")) static
ScalePartialSampleProfileWorkingSetSize
cl::opt<bool> ScalePartialSampleProfileWorkingSetSize("scale-partial-sample-profile-working-set-size", cl::Hidden, cl::init(true), cl::desc("If true, scale the working set size of the partial sample profile " "by the partial profile ratio to reflect the size of the program " "being compiled.")) ("scale-partial-sample-profile-working-set-size" , cl::Hidden , cl::init(true) , cl::desc("If true, scale the working set size of the partial sample profile " "by the partial profile ratio to reflect the size of the program " "being compiled."))