LLVM: llvm::CallLowering::ArgInfo Struct Reference
llvm::CallLowering::ArgInfo Struct Reference
#include "llvm/CodeGen/GlobalISel/CallLowering.h"
Public Member Functions
ArgInfo (ArrayRef< Register > Regs, Type *Ty, ArrayRef< ISD::ArgFlagsTy > Flags=ArrayRef< ISD::ArgFlagsTy >(), bool IsFixed=true)
ArgInfo ()
Public Member Functions inherited from llvm::CallLowering::BaseArgInfo
BaseArgInfo (Type *Ty, ArrayRef< ISD::ArgFlagsTy > Flags=ArrayRef< ISD::ArgFlagsTy >(), bool IsFixed=true)
BaseArgInfo ()
Public Attributes
SmallVector< Register, 4 > Regs
SmallVector< Register, 2 > OrigRegs
Public Attributes inherited from llvm::CallLowering::BaseArgInfo
Type * Ty
SmallVector< ISD::ArgFlagsTy, 4 > Flags
bool IsFixed
Detailed Description
Definition at line 60 of file CallLowering.h.
Constructor & Destructor Documentation
ArgInfo() [1/2]
llvm::CallLowering::ArgInfo::ArgInfo (ArrayRef< Register > Regs, Type * Ty, ArrayRef< ISD::ArgFlagsTy > Flags = ArrayRef<ISD::ArgFlagsTy>(), bool IsFixed = true) inline
Definition at line 67 of file CallLowering.h.
References assert(), llvm::CallLowering::BaseArgInfo::Flags, llvm::Type::isEmptyTy(), llvm::Type::isVoidTy(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), Regs, and llvm::CallLowering::BaseArgInfo::Ty.
ArgInfo() [2/2]
llvm::CallLowering::ArgInfo::ArgInfo () inline
Definition at line 79 of file CallLowering.h.
Member Data Documentation
OrigRegs
SmallVector<Register, 2> llvm::CallLowering::ArgInfo::OrigRegs
Definition at line 65 of file CallLowering.h.
Regs
SmallVector<Register, 4> llvm::CallLowering::ArgInfo::Regs
Definition at line 61 of file CallLowering.h.
Referenced by ArgInfo(), llvm::AArch64CallLowering::lowerReturn(), and llvm::CallLowering::parametersInCSRMatch().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/GlobalISel/CallLowering.h