LLVM: llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode > Struct Template Reference
llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode > Struct Template Reference
#include "llvm/CodeGen/GlobalISel/MIPatternMatch.h"
Public Member Functions
CompareOp_match (const Pred_P &Pred, const LHS_P &LHS, const RHS_P &RHS)
template<typename OpTy >
bool match (const MachineRegisterInfo &MRI, OpTy &&Op)
Public Attributes
Pred_P P
LHS_P L
RHS_P R
Detailed Description
template<typename Pred_P, typename LHS_P, typename RHS_P, unsigned Opcode>
struct llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode >
Definition at line 394 of file MIPatternMatch.h.
Constructor & Destructor Documentation
CompareOp_match()
template<typename Pred_P , typename LHS_P , typename RHS_P , unsigned Opcode> llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode >::CompareOp_match (const Pred_P & Pred, const LHS_P & LHS, const RHS_P & RHS) inline
Definition at line 399 of file MIPatternMatch.h.
Member Function Documentation
match()
template<typename Pred_P , typename LHS_P , typename RHS_P , unsigned Opcode> template<typename OpTy > bool llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode >::match (const MachineRegisterInfo & MRI, OpTy && Op) inline
Definition at line 403 of file MIPatternMatch.h.
References llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getPredicate(), llvm::MachineOperand::getReg(), llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode >::L, llvm::MIPatternMatch::m_MInstr(), llvm::MIPatternMatch::mi_match(), MRI, llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode >::P, and llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode >::R.
Member Data Documentation
L
template<typename Pred_P , typename LHS_P , typename RHS_P , unsigned Opcode> LHS_P llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode >::L
Definition at line 396 of file MIPatternMatch.h.
Referenced by llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode >::match().
P
template<typename Pred_P , typename LHS_P , typename RHS_P , unsigned Opcode> Pred_P llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode >::P
Definition at line 395 of file MIPatternMatch.h.
Referenced by llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode >::match().
R
template<typename Pred_P , typename LHS_P , typename RHS_P , unsigned Opcode> RHS_P llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode >::R
Definition at line 397 of file MIPatternMatch.h.
Referenced by llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode >::match().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/GlobalISel/MIPatternMatch.h