LLVM: llvm::DiagnosticInfoOptimizationBase::Argument Struct Reference
llvm::DiagnosticInfoOptimizationBase::Argument Struct Reference
Used in the streaming interface as the general argument type.
#include "llvm/IR/DiagnosticInfo.h"
Public Member Functions
Argument (StringRef Str="")
Argument (StringRef Key, const Value *V)
Argument (StringRef Key, const Type *T)
Argument (StringRef Key, StringRef S)
Argument (StringRef Key, const char *S)
Argument (StringRef Key, int N)
Argument (StringRef Key, float N)
Argument (StringRef Key, long N)
Argument (StringRef Key, long long N)
Argument (StringRef Key, unsigned N)
Argument (StringRef Key, unsigned long N)
Argument (StringRef Key, unsigned long long N)
Argument (StringRef Key, ElementCount EC)
Argument (StringRef Key, bool B)
Argument (StringRef Key, DebugLoc dl)
Argument (StringRef Key, InstructionCost C)
Public Attributes
std::string Key
std::string Val
DiagnosticLocation Loc
Detailed Description
Used in the streaming interface as the general argument type.
It internally converts everything into a key-value pair.
Definition at line 420 of file DiagnosticInfo.h.
Constructor & Destructor Documentation
Argument() [1/16]
llvm::DiagnosticInfoOptimizationBase::Argument::Argument (StringRef Str = "") inline explicit
Definition at line 426 of file DiagnosticInfo.h.
Argument() [2/16]
DiagnosticInfoOptimizationBase::Argument::Argument (StringRef Key, const Value * V)
Definition at line 164 of file DiagnosticInfo.cpp.
References llvm::GlobalValue::dropLLVMManglingEscape(), F, llvm::Value::getName(), I, Loc, llvm::Value::printAsOperand(), string, and Val.
Argument() [3/16]
DiagnosticInfoOptimizationBase::Argument::Argument (StringRef Key, const Type * T)
Definition at line 185 of file DiagnosticInfo.cpp.
References string, T, and Val.
Argument() [4/16]
DiagnosticInfoOptimizationBase::Argument::Argument (StringRef Key, StringRef S)
Definition at line 191 of file DiagnosticInfo.cpp.
References string.
Argument() [5/16]
llvm::DiagnosticInfoOptimizationBase::Argument::Argument (StringRef Key, const char * S) inline
Definition at line 430 of file DiagnosticInfo.h.
Argument() [6/16]
DiagnosticInfoOptimizationBase::Argument::Argument (StringRef Key, int N)
Definition at line 194 of file DiagnosticInfo.cpp.
References string.
Argument() [7/16]
DiagnosticInfoOptimizationBase::Argument::Argument (StringRef Key, float N)
Definition at line 197 of file DiagnosticInfo.cpp.
References string.
Argument() [8/16]
DiagnosticInfoOptimizationBase::Argument::Argument (StringRef Key, long N)
Definition at line 200 of file DiagnosticInfo.cpp.
References string.
Argument() [9/16]
DiagnosticInfoOptimizationBase::Argument::Argument (StringRef Key, long long N)
Definition at line 203 of file DiagnosticInfo.cpp.
References string.
Argument() [10/16]
DiagnosticInfoOptimizationBase::Argument::Argument (StringRef Key, unsigned N)
Definition at line 206 of file DiagnosticInfo.cpp.
References string.
Argument() [11/16]
DiagnosticInfoOptimizationBase::Argument::Argument (StringRef Key, unsigned long N)
Definition at line 209 of file DiagnosticInfo.cpp.
References string.
Argument() [12/16]
DiagnosticInfoOptimizationBase::Argument::Argument (StringRef Key, unsigned long long N)
Definition at line 213 of file DiagnosticInfo.cpp.
References string.
Argument() [13/16]
DiagnosticInfoOptimizationBase::Argument::Argument (StringRef Key, ElementCount EC)
Definition at line 217 of file DiagnosticInfo.cpp.
References string, and Val.
Argument() [14/16]
llvm::DiagnosticInfoOptimizationBase::Argument::Argument (StringRef Key, bool B) inline
Definition at line 439 of file DiagnosticInfo.h.
Argument() [15/16]
DiagnosticInfoOptimizationBase::Argument::Argument (StringRef Key, DebugLoc dl)
Definition at line 231 of file DiagnosticInfo.cpp.
References llvm::DiagnosticLocation::getLine(), Loc, string, and Val.
Argument() [16/16]
DiagnosticInfoOptimizationBase::Argument::Argument (StringRef Key, InstructionCost C)
Definition at line 224 of file DiagnosticInfo.cpp.
References C, llvm::Value::print(), string, and Val.
Member Data Documentation
Key
std::string llvm::DiagnosticInfoOptimizationBase::Argument::Key
Definition at line 421 of file DiagnosticInfo.h.
Referenced by llvm::DiagnosticInfoMIROptimization::MachineArgument::MachineArgument().
Loc
DiagnosticLocation llvm::DiagnosticInfoOptimizationBase::Argument::Loc
Definition at line 424 of file DiagnosticInfo.h.
Referenced by Argument().
Val
std::string llvm::DiagnosticInfoOptimizationBase::Argument::Val
Definition at line 422 of file DiagnosticInfo.h.
Referenced by Argument(), and llvm::DiagnosticInfoMIROptimization::MachineArgument::MachineArgument().
The documentation for this struct was generated from the following files:
include/llvm/IR/DiagnosticInfo.h
lib/IR/DiagnosticInfo.cpp