LLVM: llvm::VectorizerValueMap Struct Reference
llvm::VectorizerValueMap Struct Reference
This is a helper struct for maintaining vectorization state.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VectorizerValueMap (unsigned UF, ElementCount VF)
Construct an empty map with the given unroll and vectorization factors.
bool hasAnyVectorValue (Value *Key) const
bool hasVectorValue (Value *Key, unsigned Part) const
bool hasAnyScalarValue (Value *Key) const
bool hasScalarValue (Value *Key, const VPIteration &Instance) const
Value * getVectorValue (Value *Key, unsigned Part)
Retrieve the existing vector value that corresponds to Key and Part.
Value * getScalarValue (Value *Key, const VPIteration &Instance)
Retrieve the existing scalar value that corresponds to Key and Instance.
void setVectorValue (Value *Key, unsigned Part, Value *Vector)
Set a vector value associated with Key and Part.
void setScalarValue (Value *Key, const VPIteration &Instance, Value *Scalar)
Set a scalar value associated with Key and Instance.
void resetVectorValue (Value *Key, unsigned Part, Value *Vector)
Reset the vector value associated with Key for the given Part.
void resetScalarValue (Value *Key, const VPIteration &Instance, Value *Scalar)
Reset the scalar value associated with Key for Part and Lane.
Friends
struct VPTransformState
Detailed Description
This is a helper struct for maintaining vectorization state.
It's used for mapping values from the original loop to their corresponding values in the new loop. Two mappings are maintained: one for vectorized values and one for scalarized values. Vectorized values are represented with UF vector values in the new loop, and scalarized values are represented with UF x VF scalar values in the new loop. UF and VF are the unroll and vectorization factors, respectively.
Entries can be added to either map with setVectorValue and setScalarValue, which assert that an entry was not already added before. If an entry is to replace an existing one, call resetVectorValue and resetScalarValue. This is currently needed to modify the mapped values during "fix-up" operations that occur once the first phase of widening is complete. These operations include type truncation and the second phase of recurrence widening.
Entries from either map can be retrieved using the getVectorValue and getScalarValue functions, which assert that the desired value exists.
Definition at line 119 of file VPlan.h.
Constructor & Destructor Documentation
VectorizerValueMap()
llvm::VectorizerValueMap::VectorizerValueMap (unsigned UF, ElementCount VF) inline
Construct an empty map with the given unroll and vectorization factors.
Definition at line 139 of file VPlan.h.
Member Function Documentation
getScalarValue()
Value* llvm::VectorizerValueMap::getScalarValue (Value * Key, const VPIteration & Instance) inline
Retrieve the existing scalar value that corresponds to Key and Instance.
Definition at line 185 of file VPlan.h.
References assert(), hasScalarValue(), llvm::VPIteration::Lane, and llvm::VPIteration::Part.
Referenced by llvm::InnerLoopVectorizer::getOrCreateScalarValue(), llvm::InnerLoopVectorizer::getOrCreateVectorValue(), and llvm::InnerLoopVectorizer::packScalarIntoVectorValue().
getVectorValue()
Value* llvm::VectorizerValueMap::getVectorValue (Value * Key, unsigned Part) inline
Retrieve the existing vector value that corresponds to Key and Part.
Definition at line 178 of file VPlan.h.
References assert(), and hasVectorValue().
Referenced by llvm::VPPredInstPHIRecipe::execute(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), llvm::InnerLoopVectorizer::fixNonInductionPHIs(), llvm::InnerLoopVectorizer::fixReduction(), llvm::InnerLoopVectorizer::getOrCreateVectorValue(), and llvm::InnerLoopVectorizer::packScalarIntoVectorValue().
hasAnyScalarValue()
bool llvm::VectorizerValueMap::hasAnyScalarValue (Value * Key) const inline
Returns
True if the map has any scalar entry for Key.
Definition at line 157 of file VPlan.h.
Referenced by llvm::InnerLoopVectorizer::getOrCreateVectorValue(), and hasScalarValue().
hasAnyVectorValue()
bool llvm::VectorizerValueMap::hasAnyVectorValue (Value * Key) const inline
Returns
True if the map has any vector entry for Key.
Definition at line 142 of file VPlan.h.
Referenced by hasVectorValue(), and llvm::InnerLoopVectorizer::truncateToMinimalBitwidths().
hasScalarValue()
bool llvm::VectorizerValueMap::hasScalarValue (Value * Key, const VPIteration & Instance) const inline
Returns
True if the map has a scalar entry for Key and Instance.
Definition at line 162 of file VPlan.h.
References assert(), llvm::LinearPolySize< LeafTy >::getKnownMinValue(), hasAnyScalarValue(), llvm::VPIteration::Lane, and llvm::VPIteration::Part.
Referenced by llvm::InnerLoopVectorizer::getOrCreateScalarValue(), getScalarValue(), resetScalarValue(), and setScalarValue().
hasVectorValue()
bool llvm::VectorizerValueMap::hasVectorValue (Value * Key, unsigned Part) const inline
Returns
True if the map has a vector entry for Key and Part.
Definition at line 147 of file VPlan.h.
References assert(), and hasAnyVectorValue().
Referenced by llvm::VPPredInstPHIRecipe::execute(), llvm::InnerLoopVectorizer::getOrCreateVectorValue(), getVectorValue(), resetVectorValue(), and setVectorValue().
resetScalarValue()
void llvm::VectorizerValueMap::resetScalarValue (Value * Key, const VPIteration & Instance, Value * Scalar) inline
Reset the scalar value associated with Key for Part and Lane.
This function can be used to update values that have already been scalarized. This is the case for "fix-up" operations including scalar phi nodes for scalarized and predicated instructions.
Definition at line 229 of file VPlan.h.
References assert(), hasScalarValue(), llvm::VPIteration::Lane, llvm::VPIteration::Part, and llvm::NVPTX::PTXLdStInstCode::Scalar.
Referenced by llvm::VPPredInstPHIRecipe::execute().
resetVectorValue()
void llvm::VectorizerValueMap::resetVectorValue (Value * Key, unsigned Part, Value * Vector) inline
Reset the vector value associated with Key for the given Part.
This function can be used to update values that have already been vectorized. This is the case for "fix-up" operations including type truncation and the second phase of recurrence vectorization.
Definition at line 220 of file VPlan.h.
References assert(), hasVectorValue(), and llvm::Vector.
Referenced by llvm::VPPredInstPHIRecipe::execute(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), llvm::InnerLoopVectorizer::fixReduction(), llvm::InnerLoopVectorizer::packScalarIntoVectorValue(), and llvm::InnerLoopVectorizer::truncateToMinimalBitwidths().
setScalarValue()
void llvm::VectorizerValueMap::setScalarValue (Value * Key, const VPIteration & Instance, Value * Scalar) inline
Set a scalar value associated with Key and Instance.
Assumes such a value is not already set.
Definition at line 203 of file VPlan.h.
References assert(), and hasScalarValue().
Referenced by llvm::InnerLoopVectorizer::buildScalarSteps(), llvm::InnerLoopVectorizer::recordVectorLoopValueForInductionCast(), llvm::InnerLoopVectorizer::scalarizeInstruction(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
setVectorValue()
void llvm::VectorizerValueMap::setVectorValue (Value * Key, unsigned Part, Value * Vector) inline
Set a vector value associated with Key and Part.
Assumes such a value is not already set. If it is, use resetVectorValue() instead.
Definition at line 192 of file VPlan.h.
References assert(), and hasVectorValue().
Referenced by llvm::VPReplicateRecipe::execute(), llvm::InnerLoopVectorizer::getOrCreateVectorValue(), llvm::InnerLoopVectorizer::recordVectorLoopValueForInductionCast(), llvm::InnerLoopVectorizer::setVectorValue(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
Friends And Related Function Documentation
VPTransformState
friend struct VPTransformState friend
Definition at line 120 of file VPlan.h.
The documentation for this struct was generated from the following file:
lib/Transforms/Vectorize/VPlan.h