LLVM: llvm::AnalysisGetter Struct Reference
llvm::AnalysisGetter Struct Reference
Wrapper for FunctoinAnalysisManager.
#include "llvm/Transforms/IPO/Attributor.h"
Public Member Functions
template<typename Analysis >
Analysis::Result * getAnalysis (const Function &F)
AnalysisGetter (FunctionAnalysisManager &FAM)
AnalysisGetter ()
Detailed Description
Wrapper for FunctoinAnalysisManager.
Definition at line 721 of file Attributor.h.
Constructor & Destructor Documentation
AnalysisGetter() [1/2]
llvm::AnalysisGetter::AnalysisGetter (FunctionAnalysisManager & FAM) inline
Definition at line 729 of file Attributor.h.
AnalysisGetter() [2/2]
llvm::AnalysisGetter::AnalysisGetter () inline
Definition at line 730 of file Attributor.h.
Member Function Documentation
getAnalysis()
template<typename Analysis > Analysis::Result* llvm::AnalysisGetter::getAnalysis (const Function & F) inline
Definition at line 723 of file Attributor.h.
References Analysis, F, and llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult().
Referenced by llvm::InformationCache::getAAResultsForFunction(), llvm::InformationCache::getAnalysisResultForFunction(), llvm::InformationCache::getPotentiallyReachable(), llvm::InformationCache::getTargetLibraryInfoForFunction(), and llvm::InformationCache::InformationCache().
The documentation for this struct was generated from the following file:
include/llvm/Transforms/IPO/Attributor.h