LLVM: llvm::AAMDNodes Struct Reference
llvm::AAMDNodes Struct Reference
A collection of metadata nodes that might be associated with a memory access used by the alias-analysis infrastructure.
#include "llvm/IR/Metadata.h"
Public Member Functions
AAMDNodes ()=default
AAMDNodes (MDNode *T, MDNode *TS, MDNode *S, MDNode *N)
bool operator== (const AAMDNodes &A) const
bool operator!= (const AAMDNodes &A) const
operator bool () const
AAMDNodes intersect (const AAMDNodes &Other)
Given two sets of AAMDNodes that apply to the same pointer, give the best AAMDNodes that are compatible with both (i.e.
AAMDNodes shift (size_t Offset)
Create a new AAMDNode that describes this AAMDNode after applying a constant offset to the start of the pointer.
Static Public Member Functions
static MDNode * ShiftTBAA (MDNode *M, size_t off)
static MDNode * ShiftTBAAStruct (MDNode *M, size_t off)
Public Attributes
MDNode * TBAA = nullptr
The tag for type-based alias analysis.
MDNode * TBAAStruct = nullptr
The tag for type-based alias analysis (tbaa struct).
MDNode * Scope = nullptr
The tag for alias scope specification (used with noalias).
MDNode * NoAlias = nullptr
The tag specifying the noalias scope.
Detailed Description
A collection of metadata nodes that might be associated with a memory access used by the alias-analysis infrastructure.
Definition at line 642 of file Metadata.h.
Constructor & Destructor Documentation
AAMDNodes() [1/2]
llvm::AAMDNodes::AAMDNodes () explicit default
AAMDNodes() [2/2]
llvm::AAMDNodes::AAMDNodes (MDNode * T, MDNode * TS, MDNode * S, MDNode * N) inline explicit
Definition at line 644 of file Metadata.h.
References T.
Member Function Documentation
intersect()
AAMDNodes llvm::AAMDNodes::intersect (const AAMDNodes & Other) inline
Given two sets of AAMDNodes that apply to the same pointer, give the best AAMDNodes that are compatible with both (i.e.
a set of nodes whose allowable aliasing conclusions are a subset of those allowable by both of the inputs). However, for efficiency reasons, do not create any new MDNodes.
Definition at line 681 of file Metadata.h.
References NoAlias, Other, Scope, TBAA, and TBAAStruct.
operator bool()
llvm::AAMDNodes::operator bool () const inline explicit
Definition at line 654 of file Metadata.h.
References NoAlias, Scope, TBAA, and TBAAStruct.
operator!=()
bool llvm::AAMDNodes::operator!= (const AAMDNodes & A) const inline
Definition at line 652 of file Metadata.h.
operator==()
bool llvm::AAMDNodes::operator== (const AAMDNodes & A) const inline
Definition at line 647 of file Metadata.h.
References NoAlias, Scope, TBAA, and TBAAStruct.
shift()
AAMDNodes llvm::AAMDNodes::shift (size_t Offset) inline
Create a new AAMDNode that describes this AAMDNode after applying a constant offset to the start of the pointer.
Definition at line 692 of file Metadata.h.
References NoAlias, Offset, Scope, ShiftTBAA(), ShiftTBAAStruct(), TBAA, and TBAAStruct.
ShiftTBAA()
MDNode * AAMDNodes::ShiftTBAA (MDNode * M, size_t off) static
Definition at line 741 of file TypeBasedAliasAnalysis.cpp.
References llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::ConstantInt::get(), llvm::MDNode::getContext(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::ConstantInt::getType(), llvm::ConstantInt::getZExtValue(), isStructPathTBAA(), Offset, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by shift().
ShiftTBAAStruct()
MDNode * AAMDNodes::ShiftTBAAStruct (MDNode * M, size_t off) static
Definition at line 792 of file TypeBasedAliasAnalysis.cpp.
References llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::ConstantInt::get(), llvm::MDNode::getContext(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::ConstantInt::getType(), llvm::ConstantInt::getZExtValue(), Offset, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::size().
Referenced by shift().
Member Data Documentation
NoAlias
MDNode* llvm::AAMDNodes::NoAlias = nullptr
The tag specifying the noalias scope.
Definition at line 668 of file Metadata.h.
Referenced by llvm::ScopedNoAliasAAResult::alias(), llvm::DenseMapInfo< AAMDNodes >::getHashValue(), llvm::ScopedNoAliasAAResult::getModRefInfo(), intersect(), operator bool(), operator==(), llvm::MachineMemOperand::print(), and shift().
Scope
MDNode* llvm::AAMDNodes::Scope = nullptr
The tag for alias scope specification (used with noalias).
Definition at line 665 of file Metadata.h.
Referenced by llvm::ScopedNoAliasAAResult::alias(), llvm::DenseMapInfo< AAMDNodes >::getHashValue(), llvm::ScopedNoAliasAAResult::getModRefInfo(), intersect(), operator bool(), operator==(), llvm::MachineMemOperand::print(), and shift().
TBAA
MDNode* llvm::AAMDNodes::TBAA = nullptr
The tag for type-based alias analysis.
Definition at line 659 of file Metadata.h.
Referenced by llvm::TypeBasedAAResult::alias(), llvm::DenseMapInfo< AAMDNodes >::getHashValue(), llvm::TypeBasedAAResult::getModRefInfo(), intersect(), operator bool(), operator==(), llvm::TypeBasedAAResult::pointsToConstantMemory(), llvm::MachineMemOperand::print(), and shift().
TBAAStruct
MDNode* llvm::AAMDNodes::TBAAStruct = nullptr
The tag for type-based alias analysis (tbaa struct).
Definition at line 662 of file Metadata.h.
Referenced by llvm::DenseMapInfo< AAMDNodes >::getHashValue(), intersect(), operator bool(), operator==(), and shift().
The documentation for this struct was generated from the following files:
include/llvm/IR/Metadata.h
lib/Analysis/TypeBasedAliasAnalysis.cpp