LLVM: lib/Analysis/TargetTransformInfo.cpp File Reference
TargetTransformInfo.cpp File Reference
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Analysis/CFG.h"
#include "llvm/Analysis/LoopIterator.h"
#include "llvm/Analysis/TargetTransformInfoImpl.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include <utility>
Macros
#define DEBUG_TYPE "tti"
Functions
static bool matchPairwiseShuffleMask (ShuffleVectorInst *SI, bool IsLeft, unsigned Level)
static Optional< TTI::ReductionData > getReductionData (Instruction *I)
static TTI::ReductionKind matchPairwiseReductionAtLevel (Instruction *I, unsigned Level, unsigned NumLevels)
static std::pair< Value *, ShuffleVectorInst * > getShuffleAndOtherOprd (Value *L, Value *R)
Variables
static cl::opt< bool > EnableReduxCost ("costmodel-reduxcost", cl::init(false), cl::Hidden, cl::desc("Recognize reduction patterns."))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "tti"
Definition at line 30 of file TargetTransformInfo.cpp.
Function Documentation
getReductionData()
static Optional<TTI::ReductionData> getReductionData (Instruction * I) static
Definition at line 1104 of file TargetTransformInfo.cpp.
References I, llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_OrdFMax(), llvm::PatternMatch::m_OrdFMin(), llvm::PatternMatch::m_SMax(), llvm::PatternMatch::m_SMin(), llvm::PatternMatch::m_UMax(), llvm::PatternMatch::m_UMin(), llvm::PatternMatch::m_UnordFMax(), llvm::PatternMatch::m_UnordFMin(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::None, llvm::TargetTransformInfo::RK_Arithmetic, llvm::TargetTransformInfo::RK_MinMax, llvm::TargetTransformInfo::RK_UnsignedMinMax, and SI.
Referenced by llvm::TargetTransformInfo::matchPairwiseReduction(), matchPairwiseReductionAtLevel(), and llvm::TargetTransformInfo::matchVectorSplittingReduction().
getShuffleAndOtherOprd()
static std::pair<Value *, ShuffleVectorInst *> getShuffleAndOtherOprd (Value * L, Value * R) static
Definition at line 1266 of file TargetTransformInfo.cpp.
Referenced by llvm::TargetTransformInfo::matchVectorSplittingReduction().
matchPairwiseReductionAtLevel()
static TTI::ReductionKind matchPairwiseReductionAtLevel (Instruction * I, unsigned Level, unsigned NumLevels) static
Definition at line 1127 of file TargetTransformInfo.cpp.
References assert(), llvm::User::getOperand(), getReductionData(), I, llvm::AArch64CC::LS, matchPairwiseShuffleMask(), and llvm::TargetTransformInfo::RK_None.
Referenced by llvm::TargetTransformInfo::matchPairwiseReduction().
matchPairwiseShuffleMask()
static bool matchPairwiseShuffleMask (ShuffleVectorInst * SI, bool IsLeft, unsigned Level) static
Definition at line 1083 of file TargetTransformInfo.cpp.
References llvm::numbers::e, llvm::BitmaskEnumDetail::Mask(), and SI.
Referenced by matchPairwiseReductionAtLevel().
Variable Documentation
EnableReduxCost
cl::opt<bool> EnableReduxCost("costmodel-reduxcost", cl::init(false), cl::Hidden, cl::desc("Recognize reduction patterns.")) ("costmodel-reduxcost" , cl::init(false) , cl::Hidden , cl::desc("Recognize reduction patterns.")) static
Referenced by llvm::TargetTransformInfo::matchPairwiseReduction(), and llvm::TargetTransformInfo::matchVectorSplittingReduction().