LLVM: lib/Transforms/Utils/UniqueInternalLinkageNames.cpp File Reference
UniqueInternalLinkageNames.cpp File Reference
#include "llvm/Transforms/Utils/UniqueInternalLinkageNames.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/MD5.h"
#include "llvm/Transforms/Utils/ModuleUtils.h"
Namespaces
llvm
This class represents lattice values for constants.
Functions
static bool uniqueifyInternalLinkageNames (Module &M)
INITIALIZE_PASS_BEGIN (UniqueInternalLinkageNamesLegacyPass, "unique-internal-linkage-names", "Uniqueify internal linkage names", false, false) INITIALIZE_PASS_END(UniqueInternalLinkageNamesLegacyPass
ModulePass * llvm::createUniqueInternalLinkageNamesPass ()
Variables
unique internal linkage names
unique internal linkage Uniqueify Internal linkage false
Function Documentation
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (UniqueInternalLinkageNamesLegacyPass , "unique-internal-linkage-names" , "Uniqueify internal linkage names" , false , false)
uniqueifyInternalLinkageNames()
static bool uniqueifyInternalLinkageNames (Module & M) static
Definition at line 26 of file UniqueInternalLinkageNames.cpp.
References llvm::MDBuilder::createString(), F, llvm::MD5::final(), llvm::SmallString< InternalLen >::str(), llvm::MD5::stringifyResult(), llvm::APInt::toString(), and llvm::MD5::update().
Referenced by llvm::UniqueInternalLinkageNamesPass::run().
Variable Documentation
false
unique internal linkage Uniqueify Internal linkage false
Definition at line 112 of file UniqueInternalLinkageNames.cpp.
names
unique internal linkage Uniqueify Internal linkage names
Definition at line 111 of file UniqueInternalLinkageNames.cpp.
Referenced by createIndexMap(), and llvm::toIRString().