LLVM: lib/IR/Value.cpp File Reference
Value.cpp File Reference
#include "llvm/IR/Value.h"
#include "LLVMContextImpl.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/DerivedUser.h"
#include "llvm/IR/GetElementPtrTypeIterator.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Statepoint.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/IR/ValueSymbolTable.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include "llvm/IR/Value.def"
#include "llvm/IR/Instruction.def"
Macros
#define HANDLE_VALUE(Name)
#define HANDLE_MEMORY_VALUE(Name)
#define HANDLE_CONSTANT(Name)
#define HANDLE_INSTRUCTION(Name) /* nothing */
#define HANDLE_INST(N, OPC, CLASS)
#define HANDLE_USER_INST(N, OPC, CLASS)
Functions
static Type * checkType (Type *Ty)
static bool isUnDroppableUser (const User *U)
static bool getSymTab (Value *V, ValueSymbolTable *&ST)
static bool contains (SmallPtrSetImpl< ConstantExpr * > &Cache, ConstantExpr *Expr, Constant *C)
static bool contains (Value *Expr, Value *V)
Variables
static cl::opt< unsigned > NonGlobalValueMaxNameSize ("non-global-value-max-name-size", cl::Hidden, cl::init(1024), cl::desc("Maximum size for the name of non-global values."))
Macro Definition Documentation
HANDLE_CONSTANT
#define HANDLE_CONSTANT (Name)
Value:
  case Value::Name##Val:                                                       \
    llvm_unreachable("constants should be destroyed with destroyConstant");    \
    break;
HANDLE_INST
#define HANDLE_INST (N, OPC, CLASS)
Value:
  case Value::InstructionVal + Instruction::OPC:                               \
    delete static_cast<CLASS *>(this);                                         \
    break;
HANDLE_INSTRUCTION
#define HANDLE_INSTRUCTION (Name) /* nothing */
HANDLE_MEMORY_VALUE
#define HANDLE_MEMORY_VALUE (Name)
Value:
  case Value::Name##Val:                                                       \
    static_cast<DerivedUser *>(this)->DeleteValue(                             \
        static_cast<DerivedUser *>(this));                                     \
    break;
HANDLE_USER_INST
#define HANDLE_USER_INST (N, OPC, CLASS)
HANDLE_VALUE
#define HANDLE_VALUE (Name)
Value:
  case Value::Name##Val:                                                       \
    delete static_cast<Name *>(this);                                          \
    break;
Function Documentation
checkType()
static Type* checkType (Type * Ty) inline static
Definition at line 48 of file Value.cpp.
References assert().
contains() [1/2]
static bool contains (SmallPtrSetImpl< ConstantExpr * > & Cache, ConstantExpr * Expr, Constant * C) static
Definition at line 458 of file Value.cpp.
References C, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::RISCVFenceField::O, and llvm::User::operands().
Referenced by contains(), and llvm::Value::replaceUsesOutsideBlock().
contains() [2/2]
static bool contains (Value * Expr, Value * V) static
Definition at line 475 of file Value.cpp.
References C, and contains().
getSymTab()
static bool getSymTab (Value * V, ValueSymbolTable *& ST) static
Definition at line 245 of file Value.cpp.
References assert(), I, P, and llvm::ARM_MB::ST.
Referenced by llvm::SymbolTableListTraits< ValueSubClass >::addNodeToList(), llvm::SymbolTableListTraits< ValueSubClass >::removeNodeFromList(), llvm::SymbolTableListTraits< ValueSubClass >::setSymTabObject(), llvm::Value::takeName(), and llvm::SymbolTableListTraits< ValueSubClass >::transferNodesFromList().
isUnDroppableUser()
static bool isUnDroppableUser (const User * U) static
Definition at line 162 of file Value.cpp.
References llvm::User::isDroppable().
Referenced by llvm::Value::hasNUndroppableUses(), and llvm::Value::hasNUndroppableUsesOrMore().
Variable Documentation
NonGlobalValueMaxNameSize
cl::opt<unsigned> NonGlobalValueMaxNameSize("non-global-value-max-name-size", cl::Hidden, cl::init(1024), cl::desc("Maximum size for the name of non-global values.")) ("non-global-value-max-name-size" , cl::Hidden , cl::init(1024) , cl::desc("Maximum size for the name of non-global values.")) static