LLVM: lib/Target/VE/VERegisterInfo.cpp File Reference
VERegisterInfo.cpp File Reference
#include "VERegisterInfo.h"
#include "VE.h"
#include "VESubtarget.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "VEGenRegisterInfo.inc"
Macros
#define GET_REGINFO_TARGET_DESC
#define RRCAS_multi_cases(NAME) NAME##rir : case NAME##rii
Functions
static unsigned offsetToDisp (MachineInstr &MI)
static void replaceFI (MachineFunction &MF, MachineBasicBlock::iterator II, MachineInstr &MI, const DebugLoc &dl, unsigned FIOperandNum, int Offset, Register FrameReg)
Macro Definition Documentation
GET_REGINFO_TARGET_DESC
#define GET_REGINFO_TARGET_DESC
Definition at line 30 of file VERegisterInfo.cpp.
RRCAS_multi_cases
#define RRCAS_multi_cases (NAME) NAME##rir : case NAME##rii
Function Documentation
offsetToDisp()
static unsigned offsetToDisp (MachineInstr & MI) static
Definition at line 113 of file VERegisterInfo.cpp.
References MI, and RRCAS_multi_cases.
Referenced by llvm::VERegisterInfo::eliminateFrameIndex(), and replaceFI().
replaceFI()
static void replaceFI (MachineFunction & MF, MachineBasicBlock::iterator II, MachineInstr & MI, const DebugLoc & dl, unsigned FIOperandNum, int Offset, Register FrameReg) static
Definition at line 136 of file VERegisterInfo.cpp.
References MI, Offset, and offsetToDisp().
Referenced by llvm::VERegisterInfo::eliminateFrameIndex().