LLVM: lib/CodeGen/WasmEHPrepare.cpp File Reference
WasmEHPrepare.cpp File Reference
#include "llvm/ADT/BreadthFirstIterator.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/Triple.h"
#include "llvm/Analysis/DomTreeUpdater.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/CodeGen/WasmEHFuncInfo.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsWebAssembly.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
Macros
#define DEBUG_TYPE "wasmehprepare"
Functions
INITIALIZE_PASS_BEGIN (WasmEHPrepare, DEBUG_TYPE, "Prepare WebAssembly exceptions", false, false) INITIALIZE_PASS_END(WasmEHPrepare
template<typename Container >
static void eraseDeadBBsAndChildren (const Container &BBs, DomTreeUpdater *DTU)
Variables
DEBUG_TYPE
Prepare WebAssembly exceptions
Prepare WebAssembly false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "wasmehprepare"
Definition at line 99 of file WasmEHPrepare.cpp.
Function Documentation
eraseDeadBBsAndChildren()
template<typename Container > static void eraseDeadBBsAndChildren (const Container & BBs, DomTreeUpdater * DTU) static
Definition at line 167 of file WasmEHPrepare.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::DeleteDeadBlock(), llvm::SmallVectorBase< Size_T >::empty(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::pred_empty(), llvm::succ_begin(), and llvm::succ_end().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (WasmEHPrepare , DEBUG_TYPE , "Prepare WebAssembly exceptions" , false , false)
Variable Documentation
DEBUG_TYPE
DEBUG_TYPE
Definition at line 146 of file WasmEHPrepare.cpp.
exceptions
Prepare WebAssembly exceptions
Definition at line 146 of file WasmEHPrepare.cpp.
false
Prepare WebAssembly false
Definition at line 147 of file WasmEHPrepare.cpp.