LLVM: lib/Target/WebAssembly/WebAssemblyCFGStackify.cpp File Reference
WebAssemblyCFGStackify.cpp File Reference
This file implements a CFG stacking pass.
#include "WebAssembly.h"
#include "WebAssemblyExceptionInfo.h"
#include "WebAssemblyMachineFunctionInfo.h"
#include "WebAssemblySortRegion.h"
#include "WebAssemblySubtarget.h"
#include "WebAssemblyUtilities.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/Target/TargetMachine.h"
Macros
#define DEBUG_TYPE "wasm-cfg-stackify"
Functions
STATISTIC (NumUnwindMismatches, "Number of EH pad unwind mismatches found")
INITIALIZE_PASS (WebAssemblyCFGStackify, DEBUG_TYPE, "Insert BLOCK/LOOP/TRY markers for WebAssembly scopes", false, false) FunctionPass *llvm
static bool explicitlyBranchesTo (MachineBasicBlock *Pred, MachineBasicBlock *MBB)
Test whether Pred has any terminators explicitly branching to MBB, as opposed to falling through.
template<typename Container >
static MachineBasicBlock::iterator getEarliestInsertPos (MachineBasicBlock *MBB, const Container &BeforeSet, const Container &AfterSet)
template<typename Container >
static MachineBasicBlock::iterator getLatestInsertPos (MachineBasicBlock *MBB, const Container &BeforeSet, const Container &AfterSet)
static unsigned getCopyOpcode (const TargetRegisterClass *RC)
static LLVM_ATTRIBUTE_UNUSED void unstackifyVRegsUsedInSplitBB (MachineBasicBlock &MBB, MachineBasicBlock &Split)
static unsigned getDepth (const SmallVectorImpl< const MachineBasicBlock * > &Stack, const MachineBasicBlock *MBB)
static void appendEndToFunction (MachineFunction &MF, const WebAssemblyInstrInfo &TII)
Detailed Description
This file implements a CFG stacking pass.
This pass inserts BLOCK, LOOP, and TRY markers to mark the start of scopes, since scope boundaries serve as the labels for WebAssembly's control transfers.
This is sufficient to convert arbitrary CFGs into a form that works on WebAssembly, provided that all loops are single-entry.
In case we use exceptions, this pass also fixes mismatches in unwind destinations created during transforming CFG into wasm structured format.
Definition in file WebAssemblyCFGStackify.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "wasm-cfg-stackify"
Definition at line 39 of file WebAssemblyCFGStackify.cpp.
Function Documentation
appendEndToFunction()
static void appendEndToFunction (MachineFunction & MF, const WebAssemblyInstrInfo & TII) static
Definition at line 910 of file WebAssemblyCFGStackify.cpp.
References llvm::MachineFunction::back(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::findPrevDebugLoc(), and TII.
explicitlyBranchesTo()
static bool explicitlyBranchesTo (MachineBasicBlock * Pred, MachineBasicBlock * MBB) static
Test whether Pred has any terminators explicitly branching to MBB, as opposed to falling through.
Note that it's possible (eg. in unoptimized code) for a branch instruction to both branch to a block and fallthrough to it, so we check the actual branch operands to see if there are any explicit mentions.
Definition at line 129 of file WebAssemblyCFGStackify.cpp.
References MBB, MI, and llvm::MachineBasicBlock::terminators().
getCopyOpcode()
static unsigned getCopyOpcode (const TargetRegisterClass * RC) static
Definition at line 746 of file WebAssemblyCFGStackify.cpp.
References llvm_unreachable.
Referenced by unstackifyVRegsUsedInSplitBB().
getDepth()
static unsigned getDepth (const SmallVectorImpl< const MachineBasicBlock * > & Stack, const MachineBasicBlock * MBB) static
Definition at line 835 of file WebAssemblyCFGStackify.cpp.
References assert(), llvm::Depth, MBB, llvm::reverse(), and X.
Referenced by llvm::RegionBase< RegionTraits< MachineFunction > >::addSubRegion(), llvm::DWARFUnit::getLastChild(), llvm::DWARFUnit::getParent(), llvm::DWARFUnit::getPreviousSibling(), llvm::DWARFUnit::getSibling(), llvm::PMStack::push(), and llvm::VLIWMachineScheduler::schedule().
getEarliestInsertPos()
template<typename Container > static MachineBasicBlock::iterator getEarliestInsertPos (MachineBasicBlock * MBB, const Container & BeforeSet, const Container & AfterSet) static
Definition at line 145 of file WebAssemblyCFGStackify.cpp.
References assert(), llvm::MachineBasicBlock::begin(), E, llvm::MachineBasicBlock::end(), and MBB.
getLatestInsertPos()
template<typename Container > static MachineBasicBlock::iterator getLatestInsertPos (MachineBasicBlock * MBB, const Container & BeforeSet, const Container & AfterSet) static
Definition at line 169 of file WebAssemblyCFGStackify.cpp.
References assert(), llvm::MachineBasicBlock::begin(), E, llvm::MachineBasicBlock::end(), and MBB.
INITIALIZE_PASS()
INITIALIZE_PASS (WebAssemblyCFGStackify , DEBUG_TYPE , "Insert BLOCK/LOOP/TRY markers for WebAssembly scopes" , false , false)
Definition at line 116 of file WebAssemblyCFGStackify.cpp.
STATISTIC()
STATISTIC (NumUnwindMismatches , "Number of EH pad unwind mismatches found")
unstackifyVRegsUsedInSplitBB()
static LLVM_ATTRIBUTE_UNUSED void unstackifyVRegsUsedInSplitBB (MachineBasicBlock & MBB, MachineBasicBlock & Split) static
Definition at line 771 of file WebAssemblyCFGStackify.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::tgtok::Def, E, llvm::MachineBasicBlock::end(), getCopyOpcode(), llvm::MachineFunction::getInfo(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), I, llvm::Register::isPhysicalRegister(), llvm::WebAssembly::isTee(), MBB, MI, MRI, Reg, and TII.