LLVM: lib/Target/WebAssembly/WebAssemblyMCInstLower.cpp File Reference
WebAssemblyMCInstLower.cpp File Reference
This file contains code to lower WebAssembly MachineInstrs to their corresponding MCInst records.
#include "WebAssemblyMCInstLower.h"
#include "MCTargetDesc/WebAssemblyMCTargetDesc.h"
#include "TargetInfo/WebAssemblyTargetInfo.h"
#include "WebAssemblyAsmPrinter.h"
#include "WebAssemblyMachineFunctionInfo.h"
#include "WebAssemblyRuntimeLibcallSignatures.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/IR/Constants.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCSymbolWasm.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
Functions
static void removeRegisterOperands (const MachineInstr *MI, MCInst &OutMI)
static wasm::ValType getType (const TargetRegisterClass *RC)
static void getFunctionReturns (const MachineInstr *MI, SmallVectorImpl< wasm::ValType > &Returns)
Variables
cl::opt< bool > WasmKeepRegisters ("wasm-keep-registers", cl::Hidden, cl::desc("WebAssembly: output stack registers in" " instruction output for test purposes only."), cl::init(false))
cl::opt< bool > EnableEmException
cl::opt< bool > EnableEmSjLj
Detailed Description
This file contains code to lower WebAssembly MachineInstrs to their corresponding MCInst records.
Definition in file WebAssemblyMCInstLower.cpp.
Function Documentation
getFunctionReturns()
static void getFunctionReturns (const MachineInstr * MI, SmallVectorImpl< wasm::ValType > & Returns) static
Definition at line 202 of file WebAssemblyMCInstLower.cpp.
References llvm::computeLegalValueVTs(), F, MI, llvm::SystemZISD::TM, and llvm::valTypesFromMVTs().
Referenced by llvm::WebAssemblyMCInstLower::lower().
getType()
static wasm::ValType getType (const TargetRegisterClass * RC) static
Definition at line 188 of file WebAssemblyMCInstLower.cpp.
References llvm::wasm::F32, llvm::wasm::F64, llvm::wasm::I32, llvm::wasm::I64, llvm_unreachable, and llvm::wasm::V128.
Referenced by allSameType(), llvm::MachineIRBuilder::buildBlockAddress(), llvm::MachineIRBuilder::buildBoolExt(), llvm::MachineIRBuilder::buildBrIndirect(), llvm::MachineIRBuilder::buildBrJT(), llvm::MachineIRBuilder::buildSequence(), llvm::ShuffleVectorInst::changesLength(), cloneConstantExprWithNewAddressSpace(), coerceArguments(), llvm::slpvectorizer::BoUpSLP::computeMinimumValueSizes(), llvm::ConstantFoldGetElementPtr(), llvm::Constant::containsConstantExpression(), llvm::VPReplicateRecipe::execute(), llvm::fuzzerop::gepDescriptor(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), llvm::Constant::getAggregateElement(), llvm::AAValueConstantRange::getAssumedConstantInt(), llvm::AAPotentialValues::getAssumedConstantInt(), llvm::getCopyDeclaration(), llvm::Intrinsic::getDeclaration(), llvm::CastInst::getDestTy(), getFPSequenceIfElementsMatch(), llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), llvm::ARMTTIImpl::getMemoryOpCost(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::ScalarEvolution::getMulExpr(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), llvm::MemTransferBase< BaseCL >::getSourceAddressSpace(), llvm::ConstantExpr::getWithOperands(), llvm::Constant::hasExactInverseFP(), llvm::ShuffleVectorInst::increasesLength(), llvm::IntrinsicCostAttributes::IntrinsicCostAttributes(), llvm::object::XCOFFObjectFile::is64Bit(), llvm::LandingPadInst::isCatch(), llvm::object::Elf_Sym_Impl< ELFT >::isCommon(), llvm::HexagonMCInstrInfo::isCompound(), llvm::Constant::isElementWiseEqual(), llvm::ShuffleVectorInst::isExtractSubvectorMask(), llvm::LandingPadInst::isFilter(), llvm::Constant::isFiniteNonZeroFP(), llvm::HexagonMCInstrInfo::isHVX(), llvm::Constant::isNaN(), llvm::Constant::isNegativeZeroValue(), llvm::Constant::isNormalFP(), llvm::Constant::isNotMinSignedValue(), llvm::Constant::isNotOneValue(), llvm::MachineInstr::isOperandSubregIdx(), isPointerValueDeadOnEntryToFunction(), LLVMBinaryGetType(), LLVMTypeOf(), llvm::WebAssemblyMCInstLower::lower(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::fuzzerop::matchFirstType(), matchScalarInAggregate(), llvm::fuzzerop::matchScalarOfFirstType(), llvm::MachineIRBuilder::materializePtrAdd(), PerformHeapAllocSRoA(), llvm::object::Elf_Sym_Impl< ELFT >::setBinding(), llvm::PHINode::setIncomingValue(), llvm::MemTransferBase< BaseCL >::setSource(), llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, false >, false >::setSymbol(), llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, true >, false >::setSymbol(), llvm::MemSetBase< BaseCL >::setValue(), SimplifyGEPInst(), speculatePHIs(), splitGlobal(), validExtractValueIndex(), validInsertValueIndex(), validShuffleVectorIndex(), llvm::InstCombinerImpl::visitLandingPadInst(), and llvm::InstCombinerImpl::visitLShr().
removeRegisterOperands()
static void removeRegisterOperands (const MachineInstr * MI, MCInst & OutMI) static
Definition at line 327 of file WebAssemblyMCInstLower.cpp.
References assert(), llvm::MCInst::erase(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::WebAssembly::getStackOpcode(), I, llvm::MachineOperand::isReg(), MI, and llvm::MCInst::setOpcode().
Referenced by llvm::WebAssemblyMCInstLower::lower().
Variable Documentation
EnableEmException
cl::opt<bool> EnableEmException extern
EnableEmSjLj
cl::opt<bool> EnableEmSjLj extern
WasmKeepRegisters
cl::opt<bool> WasmKeepRegisters("wasm-keep-registers", cl::Hidden, cl::desc("WebAssembly: output stack registers in" " instruction output for test purposes only."), cl::init(false)) ("wasm-keep-registers" , cl::Hidden , cl::desc("WebAssembly: output stack registers in" " instruction output for test purposes only.") , cl::init(false))
Referenced by llvm::WebAssemblyMCInstLower::lower().