LLVM: lib/Target/X86/X86PreTileConfig.cpp File Reference
X86PreTileConfig.cpp File Reference
#include "X86.h"
#include "X86InstrBuilder.h"
#include "X86RegisterInfo.h"
#include "X86Subtarget.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TileShapeInfo.h"
#include "llvm/InitializePasses.h"
Macros
#define DEBUG_TYPE "tile-pre-config"
Functions
INITIALIZE_PASS_BEGIN (X86PreTileConfig, "tilepreconfig", "Tile Register Configure", false, false) INITIALIZE_PASS_END(X86PreTileConfig
static Register buildConfigMI (MachineBasicBlock::iterator MI, int FrameIdx, const TargetInstrInfo *TII, MachineRegisterInfo *MRI, const X86Subtarget *ST)
static ShapeT getShape (const MachineInstr &MI, MachineRegisterInfo *MRI)
static void addTileCFGUse (MachineFunction &MF, Register CFG)
Variables
tilepreconfig
Tile Register Configure
Tile Register false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "tile-pre-config"
Definition at line 53 of file X86PreTileConfig.cpp.
Function Documentation
addTileCFGUse()
static void addTileCFGUse (MachineFunction & MF, Register CFG) static
Definition at line 222 of file X86PreTileConfig.cpp.
References CFG, llvm::MachineOperand::CreateReg(), MBB, and MI.
buildConfigMI()
static Register buildConfigMI (MachineBasicBlock::iterator MI, int FrameIdx, const TargetInstrInfo * TII, MachineRegisterInfo * MRI, const X86Subtarget * ST) static
Definition at line 101 of file X86PreTileConfig.cpp.
References llvm::addFrameReference(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), MBB, MI, MRI, llvm::ARM_MB::ST, TII, and llvm::RegState::Undef.
getShape()
static ShapeT getShape (const MachineInstr & MI, MachineRegisterInfo * MRI) static
Definition at line 128 of file X86PreTileConfig.cpp.
References llvm_unreachable, MI, and MRI.
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (X86PreTileConfig , "tilepreconfig" , "Tile Register Configure" , false , false)
Variable Documentation
Configure
Tile Register Configure
Definition at line 93 of file X86PreTileConfig.cpp.
false
Tile Register false
Definition at line 93 of file X86PreTileConfig.cpp.
tilepreconfig
tilepreconfig
Definition at line 92 of file X86PreTileConfig.cpp.