LLVM: lib/Target/X86/X86TileConfig.cpp File Reference
X86TileConfig.cpp File Reference
#include "X86.h"
#include "X86InstrBuilder.h"
#include "X86MachineFunctionInfo.h"
#include "X86RegisterInfo.h"
#include "X86Subtarget.h"
#include "llvm/CodeGen/LiveIntervals.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TileShapeInfo.h"
#include "llvm/CodeGen/VirtRegMap.h"
#include "llvm/InitializePasses.h"
Macros
#define DEBUG_TYPE "tile-config"
Functions
INITIALIZE_PASS_BEGIN (X86TileConfig, "tileconfig", "Tile Register Configure", false, false) INITIALIZE_PASS_END(X86TileConfig
static unsigned getTilePhysRegIndex (Register PhysReg)
static MachineInstr * storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, Register SrcReg, unsigned BitSize, int FrameIdx, int Offset, const TargetInstrInfo *TII, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI)
static MachineInstr * storeImmToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, int64_t Imm, unsigned BitSize, int FrameIdx, int Offset, const TargetInstrInfo *TII)
Variables
tileconfig
Tile Register Configure
Tile Register false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "tile-config"
Definition at line 40 of file X86TileConfig.cpp.
Function Documentation
getTilePhysRegIndex()
static unsigned getTilePhysRegIndex (Register PhysReg) static
Definition at line 98 of file X86TileConfig.cpp.
References assert().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (X86TileConfig , "tileconfig" , "Tile Register Configure" , false , false)
storeImmToStackSlot()
static MachineInstr* storeImmToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, int64_t Imm, unsigned BitSize, int FrameIdx, int Offset, const TargetInstrInfo * TII) static
Definition at line 121 of file X86TileConfig.cpp.
References llvm::addFrameReference(), llvm::MachineInstrBuilder::addImm(), llvm::BuildMI(), MBB, MI, Offset, and TII.
storeRegToStackSlot()
static MachineInstr* storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, Register SrcReg, unsigned BitSize, int FrameIdx, int Offset, const TargetInstrInfo * TII, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) static
Definition at line 105 of file X86TileConfig.cpp.
References llvm::addFrameReference(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), MBB, MI, Offset, TII, and TRI.
Variable Documentation
Configure
Tile Register Configure
Definition at line 86 of file X86TileConfig.cpp.
false
Tile Register false
Definition at line 87 of file X86TileConfig.cpp.
tileconfig
tileconfig
Definition at line 86 of file X86TileConfig.cpp.