LLVM: lib/Transforms/Utils/AMDGPUEmitPrintf.cpp File Reference
AMDGPUEmitPrintf.cpp File Reference
#include "llvm/Transforms/Utils/AMDGPUEmitPrintf.h"
#include "llvm/ADT/SparseBitVector.h"
#include "llvm/Analysis/ValueTracking.h"
Macros
#define DEBUG_TYPE "amdgpu-emit-printf"
Functions
static bool isCString (const Value *Arg)
static Value * fitArgInto64Bits (IRBuilder<> &Builder, Value *Arg)
static Value * callPrintfBegin (IRBuilder<> &Builder, Value *Version)
static Value * callAppendArgs (IRBuilder<> &Builder, Value *Desc, int NumArgs, Value *Arg0, Value *Arg1, Value *Arg2, Value *Arg3, Value *Arg4, Value *Arg5, Value *Arg6, bool IsLast)
static Value * appendArg (IRBuilder<> &Builder, Value *Desc, Value *Arg, bool IsLast)
static Value * getStrlenWithNull (IRBuilder<> &Builder, Value *Str)
static Value * callAppendStringN (IRBuilder<> &Builder, Value *Desc, Value *Str, Value *Length, bool isLast)
static Value * appendString (IRBuilder<> &Builder, Value *Desc, Value *Arg, bool IsLast)
static Value * processArg (IRBuilder<> &Builder, Value *Desc, Value *Arg, bool SpecIsCString, bool IsLast)
static void locateCStrings (SparseBitVector< 8 > &BV, Value *Fmt)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "amdgpu-emit-printf"
Definition at line 23 of file AMDGPUEmitPrintf.cpp.
Function Documentation
appendArg()
static Value* appendArg (IRBuilder<> & Builder, Value * Desc, Value * Arg, bool IsLast) static
Definition at line 85 of file AMDGPUEmitPrintf.cpp.
References Arg, Builder, callAppendArgs(), and fitArgInto64Bits().
Referenced by processArg().
appendString()
static Value* appendString (IRBuilder<> & Builder, Value * Desc, Value * Arg, bool IsLast) static
Definition at line 174 of file AMDGPUEmitPrintf.cpp.
References Arg, Builder, callAppendStringN(), and getStrlenWithNull().
Referenced by llvm::emitAMDGPUPrintfCall(), and processArg().
callAppendArgs()
static Value* callAppendArgs (IRBuilder<> & Builder, Value * Desc, int NumArgs, Value * Arg0, Value * Arg1, Value * Arg2, Value * Arg3, Value * Arg4, Value * Arg5, Value * Arg6, bool IsLast) static
Definition at line 69 of file AMDGPUEmitPrintf.cpp.
References Builder, Int32Ty, and M.
Referenced by appendArg().
callAppendStringN()
static Value* callAppendStringN (IRBuilder<> & Builder, Value * Desc, Value * Str, Value * Length, bool isLast) static
Definition at line 162 of file AMDGPUEmitPrintf.cpp.
References Builder, Int32Ty, and M.
Referenced by appendString().
callPrintfBegin()
static Value* callPrintfBegin (IRBuilder<> & Builder, Value * Version) static
Definition at line 62 of file AMDGPUEmitPrintf.cpp.
References Builder, M, and llvm::IndexedInstrProf::Version.
Referenced by llvm::emitAMDGPUPrintfCall().
fitArgInto64Bits()
static Value* fitArgInto64Bits (IRBuilder<> & Builder, Value * Arg) static
Definition at line 38 of file AMDGPUEmitPrintf.cpp.
References Arg, Builder, llvm::Type::DoubleTyID, and llvm_unreachable.
Referenced by appendArg().
getStrlenWithNull()
static Value* getStrlenWithNull (IRBuilder<> & Builder, Value * Str) static
Definition at line 95 of file AMDGPUEmitPrintf.cpp.
References llvm::BasicBlock::begin(), Builder, llvm::BranchInst::Create(), llvm::BasicBlock::Create(), llvm::Data, llvm::Instruction::eraseFromParent(), llvm::Constant::getNullValue(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), M, and llvm::BasicBlock::splitBasicBlock().
Referenced by appendString().
isCString()
static bool isCString (const Value * Arg) static
Definition at line 25 of file AMDGPUEmitPrintf.cpp.
References Arg.
Referenced by for(), and processArg().
locateCStrings()
static void locateCStrings (SparseBitVector< 8 > & BV, Value * Fmt) static
Definition at line 193 of file AMDGPUEmitPrintf.cpp.
References llvm::StringRef::count(), llvm::StringRef::empty(), llvm::StringRef::find_first_of(), llvm::getConstantStringInfo(), llvm::StringRef::npos, llvm::SparseBitVector< ElementSize >::set(), and llvm::StringRef::slice().
Referenced by llvm::emitAMDGPUPrintfCall().
processArg()
static Value* processArg (IRBuilder<> & Builder, Value * Desc, Value * Arg, bool SpecIsCString, bool IsLast) static
Definition at line 180 of file AMDGPUEmitPrintf.cpp.
References appendArg(), appendString(), Arg, Builder, and isCString().
Referenced by llvm::emitAMDGPUPrintfCall().