LLVM: llvm::object::WasmSymbol Class Reference
llvm::object::WasmSymbol Class Reference
#include "llvm/Object/Wasm.h"
Public Member Functions
WasmSymbol (const wasm::WasmSymbolInfo &Info, const wasm::WasmGlobalType *GlobalType, const wasm::WasmTableType *TableType, const wasm::WasmTagType *TagType, const wasm::WasmSignature *Signature)
bool isTypeFunction () const
bool isTypeTable () const
bool isTypeData () const
bool isTypeGlobal () const
bool isTypeSection () const
bool isTypeTag () const
bool isDefined () const
bool isUndefined () const
bool isBindingWeak () const
bool isBindingGlobal () const
bool isBindingLocal () const
unsigned getBinding () const
bool isHidden () const
unsigned getVisibility () const
void print (raw_ostream &Out) const
LLVM_DUMP_METHOD void dump () const
Public Attributes
const wasm::WasmSymbolInfo & Info
const wasm::WasmGlobalType * GlobalType
const wasm::WasmTableType * TableType
const wasm::WasmTagType * TagType
const wasm::WasmSignature * Signature
Detailed Description
Definition at line 35 of file Wasm.h.
Constructor & Destructor Documentation
WasmSymbol()
llvm::object::WasmSymbol::WasmSymbol (const wasm::WasmSymbolInfo & Info, const wasm::WasmGlobalType * GlobalType, const wasm::WasmTableType * TableType, const wasm::WasmTagType * TagType, const wasm::WasmSignature * Signature) inline
Definition at line 37 of file Wasm.h.
Member Function Documentation
dump()
LLVM_DUMP_METHOD void WasmSymbol::dump () const
Definition at line 54 of file WasmObjectFile.cpp.
References llvm::dbgs(), and print().
getBinding()
unsigned llvm::object::WasmSymbol::getBinding () const inline
Definition at line 87 of file Wasm.h.
References llvm::wasm::WasmSymbolInfo::Flags, Info, and llvm::wasm::WASM_SYMBOL_BINDING_MASK.
Referenced by isBindingGlobal(), isBindingLocal(), and isBindingWeak().
getVisibility()
unsigned llvm::object::WasmSymbol::getVisibility () const inline
Definition at line 95 of file Wasm.h.
References llvm::wasm::WasmSymbolInfo::Flags, Info, and llvm::wasm::WASM_SYMBOL_VISIBILITY_MASK.
Referenced by isHidden().
isBindingGlobal()
bool llvm::object::WasmSymbol::isBindingGlobal () const inline
Definition at line 79 of file Wasm.h.
References getBinding(), and llvm::wasm::WASM_SYMBOL_BINDING_GLOBAL.
isBindingLocal()
bool llvm::object::WasmSymbol::isBindingLocal () const inline
Definition at line 83 of file Wasm.h.
References getBinding(), and llvm::wasm::WASM_SYMBOL_BINDING_LOCAL.
Referenced by llvm::object::WasmObjectFile::getSymbolFlags().
isBindingWeak()
bool llvm::object::WasmSymbol::isBindingWeak () const inline
Definition at line 75 of file Wasm.h.
References getBinding(), and llvm::wasm::WASM_SYMBOL_BINDING_WEAK.
Referenced by llvm::object::WasmObjectFile::getSymbolFlags().
isDefined()
bool llvm::object::WasmSymbol::isDefined () const inline
Definition at line 69 of file Wasm.h.
References isUndefined().
Referenced by llvm::object::WasmObjectFile::getSymbolFlags(), and print().
isHidden()
bool llvm::object::WasmSymbol::isHidden () const inline
Definition at line 91 of file Wasm.h.
References getVisibility(), and llvm::wasm::WASM_SYMBOL_VISIBILITY_HIDDEN.
Referenced by llvm::object::WasmObjectFile::getSymbolFlags().
isTypeData()
bool llvm::object::WasmSymbol::isTypeData () const inline
Definition at line 57 of file Wasm.h.
References Info, llvm::wasm::WasmSymbolInfo::Kind, and llvm::wasm::WASM_SYMBOL_TYPE_DATA.
Referenced by print().
isTypeFunction()
bool llvm::object::WasmSymbol::isTypeFunction () const inline
Definition at line 51 of file Wasm.h.
References Info, llvm::wasm::WasmSymbolInfo::Kind, and llvm::wasm::WASM_SYMBOL_TYPE_FUNCTION.
Referenced by llvm::object::WasmObjectFile::getSymbolFlags().
isTypeGlobal()
bool llvm::object::WasmSymbol::isTypeGlobal () const inline
Definition at line 59 of file Wasm.h.
References Info, llvm::wasm::WasmSymbolInfo::Kind, and llvm::wasm::WASM_SYMBOL_TYPE_GLOBAL.
isTypeSection()
bool llvm::object::WasmSymbol::isTypeSection () const inline
Definition at line 63 of file Wasm.h.
References Info, llvm::wasm::WasmSymbolInfo::Kind, and llvm::wasm::WASM_SYMBOL_TYPE_SECTION.
isTypeTable()
bool llvm::object::WasmSymbol::isTypeTable () const inline
Definition at line 55 of file Wasm.h.
References Info, llvm::wasm::WasmSymbolInfo::Kind, and llvm::wasm::WASM_SYMBOL_TYPE_TABLE.
isTypeTag()
bool llvm::object::WasmSymbol::isTypeTag () const inline
Definition at line 67 of file Wasm.h.
References Info, llvm::wasm::WasmSymbolInfo::Kind, and llvm::wasm::WASM_SYMBOL_TYPE_TAG.
isUndefined()
bool llvm::object::WasmSymbol::isUndefined () const inline
Definition at line 71 of file Wasm.h.
References llvm::wasm::WasmSymbolInfo::Flags, Info, and llvm::wasm::WASM_SYMBOL_UNDEFINED.
Referenced by llvm::object::WasmObjectFile::getSymbolSection(), and isDefined().
print()
void WasmSymbol::print (raw_ostream & Out) const
Definition at line 40 of file WasmObjectFile.cpp.
References llvm::wasm::WasmSymbolInfo::DataRef, llvm::wasm::WasmSymbolInfo::ElementIndex, llvm::wasm::WasmSymbolInfo::Flags, Info, isDefined(), isTypeData(), llvm::wasm::WasmSymbolInfo::Kind, llvm::wasm::WasmSymbolInfo::Name, llvm::wasm::WasmDataReference::Offset, llvm::wasm::WasmDataReference::Segment, llvm::wasm::WasmDataReference::Size, llvm::toString(), and llvm::Twine::utohexstr().
Referenced by dump(), and llvm::operator<<().
Member Data Documentation
GlobalType
const wasm::WasmGlobalType* llvm::object::WasmSymbol::GlobalType
Definition at line 46 of file Wasm.h.
Info
const wasm::WasmSymbolInfo& llvm::object::WasmSymbol::Info
Definition at line 45 of file Wasm.h.
Referenced by getBinding(), llvm::object::WasmObjectFile::getSymbolName(), llvm::object::WasmObjectFile::getSymbolType(), getVisibility(), llvm::object::WasmObjectFile::getWasmSymbolValue(), isTypeData(), isTypeFunction(), isTypeGlobal(), isTypeSection(), isTypeTable(), isTypeTag(), isUndefined(), and print().
Signature
const wasm::WasmSignature* llvm::object::WasmSymbol::Signature
Definition at line 49 of file Wasm.h.
TableType
const wasm::WasmTableType* llvm::object::WasmSymbol::TableType
Definition at line 47 of file Wasm.h.
TagType
const wasm::WasmTagType* llvm::object::WasmSymbol::TagType
Definition at line 48 of file Wasm.h.
The documentation for this class was generated from the following files:
include/llvm/Object/Wasm.h
lib/Object/WasmObjectFile.cpp