LLVM: llvm::orc::OrcRPCExecutorProcessControlBase< RPCEndpointT > Class Template Reference
llvm::orc::OrcRPCExecutorProcessControlBase< RPCEndpointT > Class Template Reference
#include "llvm/ExecutionEngine/Orc/OrcRPCExecutorProcessControl.h"
Public Types
using ErrorReporter = unique_function< void(Error)>
using OnCloseConnectionFunction = unique_function< Error(Error)>
Public Types inherited from llvm::orc::ExecutorProcessControl
using SendResultFunction = unique_function< void(shared::WrapperFunctionResult)>
Sender to return the result of a WrapperFunction executed in the JIT.
Public Member Functions
OrcRPCExecutorProcessControlBase (std::shared_ptr< SymbolStringPool > SSP, RPCEndpointT &EP, ErrorReporter ReportError)
void reportError (Error Err)
RPCEndpointT & getEndpoint ()
Expected< tpctypes::DylibHandle > loadDylib (const char *DylibPath) override
Load the dynamic library at the given path and return a handle to it.
Expected< std::vector< tpctypes::LookupResult > > lookupSymbols (ArrayRef< LookupRequest > Request) override
Search for symbols in the target process.
Expected< int32_t > runAsMain (JITTargetAddress MainFnAddr, ArrayRef< std::string > Args) override
Run function with a main-like signature.
void callWrapperAsync (SendResultFunction OnComplete, JITTargetAddress WrapperFnAddr, ArrayRef< char > ArgBuffer) override
Run a wrapper function in the executor.
Error closeConnection (OnCloseConnectionFunction OnCloseConnection)
Error closeConnectionAndWait ()
Public Member Functions inherited from llvm::orc::ExecutorProcessControl
virtual ~ExecutorProcessControl ()
ExecutionSession & getExecutionSession ()
Return the ExecutionSession associated with this instance.
SymbolStringPtr intern (StringRef SymName)
Intern a symbol name in the SymbolStringPool.
std::shared_ptr< SymbolStringPool > getSymbolStringPool () const
Return a shared pointer to the SymbolStringPool for this instance.
const Triple & getTargetTriple () const
Return the Triple for the target process.
unsigned getPageSize () const
Get the page size for the target process.
const JITDispatchInfo & getJITDispatchInfo () const
Get the JIT dispatch function and context address for the executor.
MemoryAccess & getMemoryAccess () const
Return a MemoryAccess object for the target process.
jitlink::JITLinkMemoryManager & getMemMgr () const
Return a JITLinkMemoryManager for the target process.
virtual Error disconnect ()=0
Disconnect from the target process.
Protected Member Functions
Error initializeORCRPCEPCBase ()
Subclasses must call this during construction to initialize the TargetTriple and PageSize members.
Protected Member Functions inherited from llvm::orc::ExecutorProcessControl
ExecutorProcessControl (std::shared_ptr< SymbolStringPool > SSP)
Additional Inherited Members
Protected Attributes inherited from llvm::orc::ExecutorProcessControl
std::shared_ptr< SymbolStringPool > SSP
ExecutionSession * ES = nullptr
Triple TargetTriple
unsigned PageSize = 0
JITDispatchInfo JDI
MemoryAccess * MemAccess = nullptr
jitlink::JITLinkMemoryManager * MemMgr = nullptr
Detailed Description
template<typename RPCEndpointT>
class llvm::orc::OrcRPCExecutorProcessControlBase< RPCEndpointT >
Definition at line 277 of file OrcRPCExecutorProcessControl.h.
Member Typedef Documentation
ErrorReporter
template<typename RPCEndpointT > using llvm::orc::OrcRPCExecutorProcessControlBase< RPCEndpointT >::ErrorReporter = unique_function<void(Error)>
Definition at line 279 of file OrcRPCExecutorProcessControl.h.
OnCloseConnectionFunction
template<typename RPCEndpointT > using llvm::orc::OrcRPCExecutorProcessControlBase< RPCEndpointT >::OnCloseConnectionFunction = unique_function<Error(Error)>
Definition at line 281 of file OrcRPCExecutorProcessControl.h.
Constructor & Destructor Documentation
OrcRPCExecutorProcessControlBase()
template<typename RPCEndpointT > llvm::orc::OrcRPCExecutorProcessControlBase< RPCEndpointT >::OrcRPCExecutorProcessControlBase (std::shared_ptr< SymbolStringPool > SSP, RPCEndpointT & EP, ErrorReporter ReportError) inline
Definition at line 283 of file OrcRPCExecutorProcessControl.h.
Member Function Documentation
callWrapperAsync()
template<typename RPCEndpointT > void llvm::orc::OrcRPCExecutorProcessControlBase< RPCEndpointT >::callWrapperAsync (SendResultFunction OnComplete, JITTargetAddress WrapperFnAddr, ArrayRef< char > ArgBuffer) inline override virtual
Run a wrapper function in the executor.
The wrapper function should be callable as:
CWrapperFunctionResult fn(uint8_t *Data, uint64_t Size);
{.cpp}
The given OnComplete function will be called to return the result.
Implements llvm::orc::ExecutorProcessControl.
Definition at line 361 of file OrcRPCExecutorProcessControl.h.
References llvm::ArrayRef< T >::data(), llvm::dbgs(), DEBUG_WITH_TYPE, llvm::formatv(), move, llvm::ArrayRef< T >::size(), and llvm::toString().
closeConnection()
template<typename RPCEndpointT > Error llvm::orc::OrcRPCExecutorProcessControlBase< RPCEndpointT >::closeConnection (OnCloseConnectionFunction OnCloseConnection) inline
Definition at line 380 of file OrcRPCExecutorProcessControl.h.
References llvm::dbgs(), DEBUG_WITH_TYPE, and move.
closeConnectionAndWait()
template<typename RPCEndpointT > Error llvm::orc::OrcRPCExecutorProcessControlBase< RPCEndpointT >::closeConnectionAndWait () inline
Definition at line 386 of file OrcRPCExecutorProcessControl.h.
References F, and P.
getEndpoint()
template<typename RPCEndpointT > RPCEndpointT& llvm::orc::OrcRPCExecutorProcessControlBase< RPCEndpointT >::getEndpoint () inline
Definition at line 294 of file OrcRPCExecutorProcessControl.h.
initializeORCRPCEPCBase()
template<typename RPCEndpointT > Error llvm::orc::OrcRPCExecutorProcessControlBase< RPCEndpointT >::initializeORCRPCEPCBase () inline protected
Subclasses must call this during construction to initialize the TargetTriple and PageSize members.
Definition at line 402 of file OrcRPCExecutorProcessControl.h.
References PageSize, and llvm::Error::success().
loadDylib()
template<typename RPCEndpointT > Expected<tpctypes::DylibHandle> llvm::orc::OrcRPCExecutorProcessControlBase< RPCEndpointT >::loadDylib (const char * DylibPath) inline override virtual
Load the dynamic library at the given path and return a handle to it.
If LibraryPath is null this function will return the global handle for the target process.
Implements llvm::orc::ExecutorProcessControl.
Definition at line 296 of file OrcRPCExecutorProcessControl.h.
References llvm::dbgs(), DEBUG_WITH_TYPE, llvm::formatv(), and H.
lookupSymbols()
template<typename RPCEndpointT > Expected<std::vector<tpctypes::LookupResult> > llvm::orc::OrcRPCExecutorProcessControlBase< RPCEndpointT >::lookupSymbols (ArrayRef< LookupRequest > Request) inline override virtual
Search for symbols in the target process.
The result of the lookup is a 2-dimentional array of target addresses that correspond to the lookup order. If a required symbol is not found then this method will return an error. If a weakly referenced symbol is not found then it be assigned a '0' value in the result. that correspond to the lookup order.
Implements llvm::orc::ExecutorProcessControl.
Definition at line 316 of file OrcRPCExecutorProcessControl.h.
References llvm::dbgs(), DEBUG_WITH_TYPE, E, First, llvm::formatv(), and llvm::RISCVFenceField::R.
reportError()
template<typename RPCEndpointT > void llvm::orc::OrcRPCExecutorProcessControlBase< RPCEndpointT >::reportError (Error Err) inline
Definition at line 292 of file OrcRPCExecutorProcessControl.h.
runAsMain()
template<typename RPCEndpointT > Expected<int32_t> llvm::orc::OrcRPCExecutorProcessControlBase< RPCEndpointT >::runAsMain (JITTargetAddress MainFnAddr, ArrayRef< std::string > Args) inline override virtual
Run function with a main-like signature.
Implements llvm::orc::ExecutorProcessControl.
Definition at line 341 of file OrcRPCExecutorProcessControl.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::dbgs(), DEBUG_WITH_TYPE, llvm::formatv(), and I.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/OrcRPCExecutorProcessControl.h