LLVM: AMDGPUPostLegalizerCombinerHelper Class Reference
AMDGPUPostLegalizerCombinerHelper Class Reference
Classes
struct CvtF32UByteMatchInfo
struct FMinFMaxLegacyInfo
Public Member Functions
AMDGPUPostLegalizerCombinerHelper (MachineIRBuilder &B, CombinerHelper &Helper)
bool matchFMinFMaxLegacy (MachineInstr &MI, FMinFMaxLegacyInfo &Info)
void applySelectFCmpToFMinToFMaxLegacy (MachineInstr &MI, const FMinFMaxLegacyInfo &Info)
bool matchUCharToFloat (MachineInstr &MI)
void applyUCharToFloat (MachineInstr &MI)
bool matchCvtF32UByteN (MachineInstr &MI, CvtF32UByteMatchInfo &MatchInfo)
void applyCvtF32UByteN (MachineInstr &MI, const CvtF32UByteMatchInfo &MatchInfo)
bool matchRemoveFcanonicalize (MachineInstr &MI, Register &Reg)
Protected Attributes
MachineIRBuilder & B
MachineFunction & MF
MachineRegisterInfo & MRI
CombinerHelper & Helper
Detailed Description
Definition at line 32 of file AMDGPUPostLegalizerCombiner.cpp.
Constructor & Destructor Documentation
AMDGPUPostLegalizerCombinerHelper()
AMDGPUPostLegalizerCombinerHelper::AMDGPUPostLegalizerCombinerHelper (MachineIRBuilder & B, CombinerHelper & Helper) inline
Definition at line 40 of file AMDGPUPostLegalizerCombiner.cpp.
Member Function Documentation
applyCvtF32UByteN()
void AMDGPUPostLegalizerCombinerHelper::applyCvtF32UByteN (MachineInstr & MI, const CvtF32UByteMatchInfo & MatchInfo)
Definition at line 232 of file AMDGPUPostLegalizerCombiner.cpp.
References assert(), B, AMDGPUPostLegalizerCombinerHelper::CvtF32UByteMatchInfo::CvtVal, llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::LLT::isScalar(), MI, MRI, llvm::LLT::scalar(), and AMDGPUPostLegalizerCombinerHelper::CvtF32UByteMatchInfo::ShiftOffset.
applySelectFCmpToFMinToFMaxLegacy()
void AMDGPUPostLegalizerCombinerHelper::applySelectFCmpToFMinToFMaxLegacy (MachineInstr & MI, const FMinFMaxLegacyInfo & Info)
Definition at line 112 of file AMDGPUPostLegalizerCombiner.cpp.
References B, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, Info, llvm_unreachable, MI, X, and Y.
applyUCharToFloat()
void AMDGPUPostLegalizerCombinerHelper::applyUCharToFloat (MachineInstr & MI)
Definition at line 180 of file AMDGPUPostLegalizerCombiner.cpp.
References B, llvm::MachineRegisterInfo::getType(), MI, MRI, and llvm::LLT::scalar().
matchCvtF32UByteN()
bool AMDGPUPostLegalizerCombinerHelper::matchCvtF32UByteN (MachineInstr & MI, CvtF32UByteMatchInfo & MatchInfo)
Definition at line 204 of file AMDGPUPostLegalizerCombiner.cpp.
References AMDGPUPostLegalizerCombinerHelper::CvtF32UByteMatchInfo::CvtVal, llvm::MIPatternMatch::m_GLShr(), llvm::MIPatternMatch::m_GShl(), llvm::MIPatternMatch::m_GZExt(), llvm::MIPatternMatch::m_ICst(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, Offset, and AMDGPUPostLegalizerCombinerHelper::CvtF32UByteMatchInfo::ShiftOffset.
matchFMinFMaxLegacy()
bool AMDGPUPostLegalizerCombinerHelper::matchFMinFMaxLegacy (MachineInstr & MI, FMinFMaxLegacyInfo & Info)
Definition at line 73 of file AMDGPUPostLegalizerCombiner.cpp.
References Cond, llvm::CmpInst::FCMP_FALSE, llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_TRUE, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, llvm::MachineRegisterInfo::getType(), llvm::AMDGPUSubtarget::hasFminFmaxLegacy(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), Info, llvm::MIPatternMatch::m_GFCmp(), llvm::MIPatternMatch::m_Pred(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, and llvm::LLT::scalar().
matchRemoveFcanonicalize()
bool AMDGPUPostLegalizerCombinerHelper::matchRemoveFcanonicalize (MachineInstr & MI, Register & Reg)
Definition at line 250 of file AMDGPUPostLegalizerCombiner.cpp.
References llvm::SITargetLowering::isCanonicalized(), MI, and Reg.
matchUCharToFloat()
bool AMDGPUPostLegalizerCombinerHelper::matchUCharToFloat (MachineInstr & MI)
Definition at line 161 of file AMDGPUPostLegalizerCombiner.cpp.
References assert(), llvm::APInt::getHighBitsSet(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::BitmaskEnumDetail::Mask(), MI, MRI, and llvm::LLT::scalar().
Member Data Documentation
B
MachineIRBuilder& AMDGPUPostLegalizerCombinerHelper::B protected
Definition at line 34 of file AMDGPUPostLegalizerCombiner.cpp.
Helper
CombinerHelper& AMDGPUPostLegalizerCombinerHelper::Helper protected
Definition at line 37 of file AMDGPUPostLegalizerCombiner.cpp.
MF
MachineFunction& AMDGPUPostLegalizerCombinerHelper::MF protected
Definition at line 35 of file AMDGPUPostLegalizerCombiner.cpp.
MRI
MachineRegisterInfo& AMDGPUPostLegalizerCombinerHelper::MRI protected
Definition at line 36 of file AMDGPUPostLegalizerCombiner.cpp.
The documentation for this class was generated from the following file:
lib/Target/AMDGPU/AMDGPUPostLegalizerCombiner.cpp