LLVM: llvm::orc::shared::WrapperFunctionResult Class Reference
llvm::orc::shared::WrapperFunctionResult Class Reference
C++ wrapper function result: Same as CWrapperFunctionResult but auto-releases memory.
#include "llvm/ExecutionEngine/Orc/Shared/WrapperFunctionUtils.h"
Public Member Functions
WrapperFunctionResult ()
Create a default WrapperFunctionResult.
WrapperFunctionResult (detail::CWrapperFunctionResult R)
Create a WrapperFunctionResult by taking ownership of a detail::CWrapperFunctionResult.
WrapperFunctionResult (const WrapperFunctionResult &)=delete
WrapperFunctionResult & operator= (const WrapperFunctionResult &)=delete
WrapperFunctionResult (WrapperFunctionResult &&Other)
WrapperFunctionResult & operator= (WrapperFunctionResult &&Other)
~WrapperFunctionResult ()
detail::CWrapperFunctionResult release ()
Release ownership of the contained detail::CWrapperFunctionResult.
const char * data () const
Get a pointer to the data contained in this instance.
size_t size () const
Returns the size of the data contained in this instance.
bool empty () const
Returns true if this value is equivalent to a default-constructed WrapperFunctionResult.
const char * getOutOfBandError () const
If this value is an out-of-band error then this returns the error message, otherwise returns nullptr.
Static Public Member Functions
static char * allocate (WrapperFunctionResult &WFR, size_t Size)
Create a WrapperFunctionResult with the given size and return a pointer to the underlying memory.
static WrapperFunctionResult copyFrom (const char *Source, size_t Size)
Copy from the given char range.
static WrapperFunctionResult copyFrom (const char *Source)
Copy from the given null-terminated string (includes the null-terminator).
static WrapperFunctionResult copyFrom (const std::string &Source)
Copy from the given std::string (includes the null terminator).
static WrapperFunctionResult createOutOfBandError (const char *Msg)
Create an out-of-band error by copying the given string.
static WrapperFunctionResult createOutOfBandError (const std::string &Msg)
Create an out-of-band error by copying the given string.
Detailed Description
C++ wrapper function result: Same as CWrapperFunctionResult but auto-releases memory.
Definition at line 45 of file WrapperFunctionUtils.h.
Constructor & Destructor Documentation
WrapperFunctionResult() [1/4]
llvm::orc::shared::WrapperFunctionResult::WrapperFunctionResult () inline
Create a default WrapperFunctionResult.
Definition at line 48 of file WrapperFunctionUtils.h.
Referenced by allocate().
WrapperFunctionResult() [2/4]
llvm::orc::shared::WrapperFunctionResult::WrapperFunctionResult (detail::CWrapperFunctionResult R) inline
Create a WrapperFunctionResult by taking ownership of a detail::CWrapperFunctionResult.
Warning: This should only be used by clients writing wrapper-function caller utilities (like TargetProcessControl).
Definition at line 55 of file WrapperFunctionUtils.h.
WrapperFunctionResult() [3/4]
llvm::orc::shared::WrapperFunctionResult::WrapperFunctionResult (const WrapperFunctionResult &) delete
WrapperFunctionResult() [4/4]
llvm::orc::shared::WrapperFunctionResult::WrapperFunctionResult (WrapperFunctionResult && Other) inline
Definition at line 63 of file WrapperFunctionUtils.h.
References Other, and std::swap().
~WrapperFunctionResult()
llvm::orc::shared::WrapperFunctionResult::~WrapperFunctionResult () inline
Definition at line 74 of file WrapperFunctionUtils.h.
References llvm::orc::shared::detail::CWrapperFunctionResult::Data, llvm::orc::shared::detail::CWrapperFunctionResult::Size, llvm::orc::shared::detail::CWrapperFunctionResultDataUnion::Value, and llvm::orc::shared::detail::CWrapperFunctionResultDataUnion::ValuePtr.
Member Function Documentation
allocate()
static char* llvm::orc::shared::WrapperFunctionResult::allocate (WrapperFunctionResult & WFR, size_t Size) inline static
Create a WrapperFunctionResult with the given size and return a pointer to the underlying memory.
Definition at line 111 of file WrapperFunctionUtils.h.
References llvm::orc::shared::detail::CWrapperFunctionResult::Data, llvm::orc::shared::detail::CWrapperFunctionResult::Size, llvm::Check::Size, llvm::orc::shared::detail::CWrapperFunctionResultDataUnion::Value, llvm::orc::shared::detail::CWrapperFunctionResultDataUnion::ValuePtr, and WrapperFunctionResult().
Referenced by copyFrom(), and llvm::orc::shared::detail::serializeViaSPSToWrapperFunctionResult().
copyFrom() [1/3]
static WrapperFunctionResult llvm::orc::shared::WrapperFunctionResult::copyFrom (const char * Source) inline static
Copy from the given null-terminated string (includes the null-terminator).
Definition at line 133 of file WrapperFunctionUtils.h.
References copyFrom(), and llvm::Sched::Source.
copyFrom() [2/3]
static WrapperFunctionResult llvm::orc::shared::WrapperFunctionResult::copyFrom (const char * Source, size_t Size) inline static
Copy from the given char range.
Definition at line 125 of file WrapperFunctionUtils.h.
References allocate(), memcpy(), llvm::Check::Size, and llvm::Sched::Source.
Referenced by copyFrom().
copyFrom() [3/3]
static WrapperFunctionResult llvm::orc::shared::WrapperFunctionResult::copyFrom (const std::string & Source) inline static
Copy from the given std::string (includes the null terminator).
Definition at line 138 of file WrapperFunctionUtils.h.
References copyFrom(), and llvm::Sched::Source.
createOutOfBandError() [1/2]
static WrapperFunctionResult llvm::orc::shared::WrapperFunctionResult::createOutOfBandError (const char * Msg) inline static
Create an out-of-band error by copying the given string.
Definition at line 143 of file WrapperFunctionUtils.h.
References llvm::orc::shared::detail::CWrapperFunctionResult::Data, and llvm::orc::shared::detail::CWrapperFunctionResultDataUnion::ValuePtr.
Referenced by llvm::orc::shared::detail::WrapperFunctionHandlerHelper< RetT(ArgTs...), ResultSerializer, SPSTagTs... >::apply(), llvm::orc::shared::detail::WrapperFunctionAsyncHandlerHelper< RetT(SendResultT, ArgTs...), ResultSerializer, SPSTagTs... >::applyAsync(), createOutOfBandError(), llvm::orc::ExecutionSession::runJITDispatchHandler(), and llvm::orc::shared::detail::serializeViaSPSToWrapperFunctionResult().
createOutOfBandError() [2/2]
static WrapperFunctionResult llvm::orc::shared::WrapperFunctionResult::createOutOfBandError (const std::string & Msg) inline static
Create an out-of-band error by copying the given string.
Definition at line 153 of file WrapperFunctionUtils.h.
References createOutOfBandError().
data()
const char* llvm::orc::shared::WrapperFunctionResult::data () const inline
Get a pointer to the data contained in this instance.
Definition at line 92 of file WrapperFunctionUtils.h.
References assert(), llvm::orc::shared::detail::CWrapperFunctionResult::Data, llvm::orc::shared::detail::CWrapperFunctionResult::Size, llvm::orc::shared::detail::CWrapperFunctionResultDataUnion::Value, and llvm::orc::shared::detail::CWrapperFunctionResultDataUnion::ValuePtr.
Referenced by llvm::orc::shared::WrapperFunction< SPSRetTagT(SPSTagTs...)>::call().
empty()
bool llvm::orc::shared::WrapperFunctionResult::empty () const inline
Returns true if this value is equivalent to a default-constructed WrapperFunctionResult.
Definition at line 107 of file WrapperFunctionUtils.h.
References llvm::orc::shared::detail::CWrapperFunctionResult::Data, llvm::orc::shared::detail::CWrapperFunctionResult::Size, and llvm::orc::shared::detail::CWrapperFunctionResultDataUnion::ValuePtr.
getOutOfBandError()
const char* llvm::orc::shared::WrapperFunctionResult::getOutOfBandError () const inline
If this value is an out-of-band error then this returns the error message, otherwise returns nullptr.
Definition at line 159 of file WrapperFunctionUtils.h.
References llvm::orc::shared::detail::CWrapperFunctionResult::Data, llvm::orc::shared::detail::CWrapperFunctionResult::Size, and llvm::orc::shared::detail::CWrapperFunctionResultDataUnion::ValuePtr.
Referenced by llvm::orc::shared::WrapperFunction< SPSRetTagT(SPSTagTs...)>::call().
operator=() [1/2]
WrapperFunctionResult& llvm::orc::shared::WrapperFunctionResult::operator= (const WrapperFunctionResult &) delete
operator=() [2/2]
WrapperFunctionResult& llvm::orc::shared::WrapperFunctionResult::operator= (WrapperFunctionResult && Other) inline
Definition at line 68 of file WrapperFunctionUtils.h.
References move, Other, and std::swap().
release()
detail::CWrapperFunctionResult llvm::orc::shared::WrapperFunctionResult::release () inline
Release ownership of the contained detail::CWrapperFunctionResult.
Warning: Do not use – this method will be removed in the future. It only exists to temporarily support some code that will eventually be moved to the ORC runtime.
Definition at line 84 of file WrapperFunctionUtils.h.
References std::swap().
size()
size_t llvm::orc::shared::WrapperFunctionResult::size () const inline
Returns the size of the data contained in this instance.
Definition at line 99 of file WrapperFunctionUtils.h.
References assert(), llvm::orc::shared::detail::CWrapperFunctionResult::Data, llvm::orc::shared::detail::CWrapperFunctionResult::Size, and llvm::orc::shared::detail::CWrapperFunctionResultDataUnion::ValuePtr.
Referenced by llvm::orc::shared::WrapperFunction< SPSRetTagT(SPSTagTs...)>::call().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/WrapperFunctionUtils.h