LLVM: llvm::AArch64FunctionInfo Class Reference
llvm::AArch64FunctionInfo Class Reference final
AArch64FunctionInfo - This class is derived from MachineFunctionInfo and contains private AArch64-specific information for each MachineFunction.
#include "Target/AArch64/AArch64MachineFunctionInfo.h"
Classes
class MILOHDirective
Public Types
using SetOfInstructions = SmallPtrSet< const MachineInstr *, 16 >
using MILOHArgs = MILOHDirective::LOHArgs
using MILOHContainer = SmallVector< MILOHDirective, 32 >
Public Member Functions
AArch64FunctionInfo (MachineFunction &MF)
void initializeBaseYamlFields (const yaml::AArch64FunctionInfo &YamlMFI)
unsigned getBytesInStackArgArea () const
void setBytesInStackArgArea (unsigned bytes)
unsigned getArgumentStackToRestore () const
void setArgumentStackToRestore (unsigned bytes)
unsigned getTailCallReservedStack () const
void setTailCallReservedStack (unsigned bytes)
bool hasCalculatedStackSizeSVE () const
void setStackSizeSVE (uint64_t S)
uint64_t getStackSizeSVE () const
bool hasStackFrame () const
void setHasStackFrame (bool s)
bool isStackRealigned () const
void setStackRealigned (bool s)
bool hasCalleeSaveStackFreeSpace () const
void setCalleeSaveStackHasFreeSpace (bool s)
bool isSplitCSR () const
void setIsSplitCSR (bool s)
void setLocalStackSize (uint64_t Size)
uint64_t getLocalStackSize () const
void setOutliningStyle (std::string Style)
Optional< std::string > getOutliningStyle () const
void setCalleeSavedStackSize (unsigned Size)
unsigned getCalleeSavedStackSize (const MachineFrameInfo &MFI) const
unsigned getCalleeSavedStackSize () const
void setSVECalleeSavedStackSize (unsigned Size)
unsigned getSVECalleeSavedStackSize () const
void setMinMaxSVECSFrameIndex (int Min, int Max)
int getMinSVECSFrameIndex () const
int getMaxSVECSFrameIndex () const
void incNumLocalDynamicTLSAccesses ()
unsigned getNumLocalDynamicTLSAccesses () const
Optional< bool > hasRedZone () const
void setHasRedZone (bool s)
int getVarArgsStackIndex () const
void setVarArgsStackIndex (int Index)
int getVarArgsGPRIndex () const
void setVarArgsGPRIndex (int Index)
unsigned getVarArgsGPRSize () const
void setVarArgsGPRSize (unsigned Size)
int getVarArgsFPRIndex () const
void setVarArgsFPRIndex (int Index)
unsigned getVarArgsFPRSize () const
void setVarArgsFPRSize (unsigned Size)
unsigned getSRetReturnReg () const
void setSRetReturnReg (unsigned Reg)
unsigned getJumpTableEntrySize (int Idx) const
MCSymbol * getJumpTableEntryPCRelSymbol (int Idx) const
void setJumpTableEntryInfo (int Idx, unsigned Size, MCSymbol *PCRelSym)
const SetOfInstructions & getLOHRelated () const
const MILOHContainer & getLOHContainer () const
void addLOHDirective (MCLOHType Kind, MILOHArgs Args)
Add a LOH directive of this Kind and this Args.
SmallVectorImpl< ForwardedRegister > & getForwardedMustTailRegParms ()
Optional< int > getTaggedBasePointerIndex () const
void setTaggedBasePointerIndex (int Index)
unsigned getTaggedBasePointerOffset () const
void setTaggedBasePointerOffset (unsigned Offset)
int getCalleeSaveBaseToFrameRecordOffset () const
void setCalleeSaveBaseToFrameRecordOffset (int Offset)
bool shouldSignReturnAddress () const
bool shouldSignReturnAddress (bool SpillsLR) const
bool shouldSignWithBKey () const
bool branchTargetEnforcement () const
void setHasSwiftAsyncContext (bool HasContext)
bool hasSwiftAsyncContext () const
void setSwiftAsyncContextFrameIdx (int FI)
int getSwiftAsyncContextFrameIdx () const
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, MachineFunction &MF)
Factory function: default behavior is to call new using the supplied allocator.
Detailed Description
AArch64FunctionInfo - This class is derived from MachineFunctionInfo and contains private AArch64-specific information for each MachineFunction.
Definition at line 37 of file AArch64MachineFunctionInfo.h.
Member Typedef Documentation
MILOHArgs
using llvm::AArch64FunctionInfo::MILOHArgs = MILOHDirective::LOHArgs
Definition at line 360 of file AArch64MachineFunctionInfo.h.
MILOHContainer
using llvm::AArch64FunctionInfo::MILOHContainer = SmallVector<MILOHDirective, 32>
Definition at line 361 of file AArch64MachineFunctionInfo.h.
SetOfInstructions
using llvm::AArch64FunctionInfo::SetOfInstructions = SmallPtrSet<const MachineInstr *, 16>
Definition at line 337 of file AArch64MachineFunctionInfo.h.
Constructor & Destructor Documentation
AArch64FunctionInfo()
AArch64FunctionInfo::AArch64FunctionInfo (MachineFunction & MF) explicit
Definition at line 80 of file AArch64MachineFunctionInfo.cpp.
References assert(), llvm::StringRef::equals_insensitive(), F, llvm::MachineFunction::getFunction(), GetSignReturnAddress(), llvm::Function::hasFnAttribute(), and ShouldSignWithBKey().
Member Function Documentation
addLOHDirective()
void llvm::AArch64FunctionInfo::addLOHDirective (MCLOHType Kind, MILOHArgs Args) inline
Add a LOH directive of this Kind and this Args.
Definition at line 366 of file AArch64MachineFunctionInfo.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, and llvm::SmallPtrSetImpl< PtrType >::insert().
Referenced by handleADRP().
branchTargetEnforcement()
bool llvm::AArch64FunctionInfo::branchTargetEnforcement () const inline
Definition at line 399 of file AArch64MachineFunctionInfo.h.
Referenced by getCallOpcode().
getArgumentStackToRestore()
unsigned llvm::AArch64FunctionInfo::getArgumentStackToRestore () const inline
Definition at line 184 of file AArch64MachineFunctionInfo.h.
Referenced by getArgumentStackToRestore().
getBytesInStackArgArea()
unsigned llvm::AArch64FunctionInfo::getBytesInStackArgArea () const inline
Definition at line 181 of file AArch64MachineFunctionInfo.h.
getCalleeSaveBaseToFrameRecordOffset()
int llvm::AArch64FunctionInfo::getCalleeSaveBaseToFrameRecordOffset () const inline
Definition at line 387 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64FrameLowering::emitEpilogue(), getFPOffset(), and llvm::AArch64FrameLowering::resolveFrameOffsetReference().
getCalleeSavedStackSize() [1/2]
unsigned llvm::AArch64FunctionInfo::getCalleeSavedStackSize () const inline
Definition at line 277 of file AArch64MachineFunctionInfo.h.
References assert().
Referenced by getCalleeSavedStackSize().
getCalleeSavedStackSize() [2/2]
unsigned llvm::AArch64FunctionInfo::getCalleeSavedStackSize (const MachineFrameInfo & MFI) const inline
Definition at line 234 of file AArch64MachineFunctionInfo.h.
References llvm::alignTo(), assert(), llvm::TargetStackID::Default, llvm::MachineFrameInfo::getCalleeSavedInfo(), getCalleeSavedStackSize(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineFrameInfo::getStackID(), getSwiftAsyncContextFrameIdx(), Info, llvm::MachineFrameInfo::isCalleeSavedInfoValid(), llvm::max(), llvm::min(), Offset, and llvm::Check::Size.
Referenced by computeCalleeSaveRegisterPairs(), llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitPrologue(), getFPOffset(), and llvm::AArch64FrameLowering::resolveFrameOffsetReference().
getForwardedMustTailRegParms()
SmallVectorImpl<ForwardedRegister>& llvm::AArch64FunctionInfo::getForwardedMustTailRegParms () inline
Definition at line 371 of file AArch64MachineFunctionInfo.h.
Referenced by handleMustTailForwardedRegisters().
getJumpTableEntryPCRelSymbol()
MCSymbol* llvm::AArch64FunctionInfo::getJumpTableEntryPCRelSymbol (int Idx) const inline
Definition at line 328 of file AArch64MachineFunctionInfo.h.
getJumpTableEntrySize()
unsigned llvm::AArch64FunctionInfo::getJumpTableEntrySize (int Idx) const inline
Definition at line 325 of file AArch64MachineFunctionInfo.h.
getLocalStackSize()
uint64_t llvm::AArch64FunctionInfo::getLocalStackSize () const inline
Definition at line 219 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64FrameLowering::canUseRedZone(), llvm::AArch64FrameLowering::emitEpilogue(), and llvm::AArch64FrameLowering::resolveFrameOffsetReference().
getLOHContainer()
const MILOHContainer& llvm::AArch64FunctionInfo::getLOHContainer () const inline
Definition at line 363 of file AArch64MachineFunctionInfo.h.
getLOHRelated()
const SetOfInstructions& llvm::AArch64FunctionInfo::getLOHRelated () const inline
Definition at line 339 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64InstrInfo::getOutliningType().
getMaxSVECSFrameIndex()
int llvm::AArch64FunctionInfo::getMaxSVECSFrameIndex () const inline
Definition at line 297 of file AArch64MachineFunctionInfo.h.
getMinSVECSFrameIndex()
int llvm::AArch64FunctionInfo::getMinSVECSFrameIndex () const inline
Definition at line 296 of file AArch64MachineFunctionInfo.h.
getNumLocalDynamicTLSAccesses()
unsigned llvm::AArch64FunctionInfo::getNumLocalDynamicTLSAccesses () const inline
Definition at line 300 of file AArch64MachineFunctionInfo.h.
getOutliningStyle()
Optional<std::string> llvm::AArch64FunctionInfo::getOutliningStyle () const inline
Definition at line 222 of file AArch64MachineFunctionInfo.h.
getSRetReturnReg()
unsigned llvm::AArch64FunctionInfo::getSRetReturnReg () const inline
Definition at line 322 of file AArch64MachineFunctionInfo.h.
getStackSizeSVE()
uint64_t llvm::AArch64FunctionInfo::getStackSizeSVE () const inline
Definition at line 201 of file AArch64MachineFunctionInfo.h.
Referenced by getSVEStackSize(), llvm::AArch64RegisterInfo::hasBasePointer(), and llvm::AArch64RegisterInfo::useFPForScavengingIndex().
getSVECalleeSavedStackSize()
unsigned llvm::AArch64FunctionInfo::getSVECalleeSavedStackSize () const inline
Definition at line 287 of file AArch64MachineFunctionInfo.h.
Referenced by computeCalleeSaveRegisterPairs(), and llvm::AArch64FrameLowering::emitEpilogue().
getSwiftAsyncContextFrameIdx()
int llvm::AArch64FunctionInfo::getSwiftAsyncContextFrameIdx () const inline
Definition at line 409 of file AArch64MachineFunctionInfo.h.
Referenced by getCalleeSavedStackSize().
getTaggedBasePointerIndex()
Optional<int> llvm::AArch64FunctionInfo::getTaggedBasePointerIndex () const inline
Definition at line 375 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64FrameLowering::emitPrologue(), and llvm::AArch64FrameLowering::orderFrameObjects().
getTaggedBasePointerOffset()
unsigned llvm::AArch64FunctionInfo::getTaggedBasePointerOffset () const inline
Definition at line 380 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64RegisterInfo::eliminateFrameIndex().
getTailCallReservedStack()
unsigned llvm::AArch64FunctionInfo::getTailCallReservedStack () const inline
Definition at line 189 of file AArch64MachineFunctionInfo.h.
Referenced by getFixedObjectSize().
getVarArgsFPRIndex()
int llvm::AArch64FunctionInfo::getVarArgsFPRIndex () const inline
Definition at line 316 of file AArch64MachineFunctionInfo.h.
getVarArgsFPRSize()
unsigned llvm::AArch64FunctionInfo::getVarArgsFPRSize () const inline
Definition at line 319 of file AArch64MachineFunctionInfo.h.
getVarArgsGPRIndex()
int llvm::AArch64FunctionInfo::getVarArgsGPRIndex () const inline
Definition at line 310 of file AArch64MachineFunctionInfo.h.
getVarArgsGPRSize()
unsigned llvm::AArch64FunctionInfo::getVarArgsGPRSize () const inline
Definition at line 313 of file AArch64MachineFunctionInfo.h.
Referenced by getFixedObjectSize().
getVarArgsStackIndex()
int llvm::AArch64FunctionInfo::getVarArgsStackIndex () const inline
Definition at line 307 of file AArch64MachineFunctionInfo.h.
hasCalculatedStackSizeSVE()
bool llvm::AArch64FunctionInfo::hasCalculatedStackSizeSVE () const inline
Definition at line 194 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64RegisterInfo::hasBasePointer(), and llvm::AArch64RegisterInfo::useFPForScavengingIndex().
hasCalleeSaveStackFreeSpace()
bool llvm::AArch64FunctionInfo::hasCalleeSaveStackFreeSpace () const inline
Definition at line 209 of file AArch64MachineFunctionInfo.h.
Referenced by computeCalleeSaveRegisterPairs(), and llvm::AArch64FrameLowering::enableStackSlotScavenging().
hasRedZone()
Optional<bool> llvm::AArch64FunctionInfo::hasRedZone () const inline
Definition at line 304 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64InstrInfo::isFunctionSafeToOutlineFrom().
hasStackFrame()
bool llvm::AArch64FunctionInfo::hasStackFrame () const inline
Definition at line 203 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64FrameLowering::emitPrologue(), and llvm::AArch64FrameLowering::resolveFrameOffsetReference().
hasSwiftAsyncContext()
bool llvm::AArch64FunctionInfo::hasSwiftAsyncContext () const inline
Definition at line 404 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64FrameLowering::assignCalleeSavedSpillSlots(), computeCalleeSaveRegisterPairs(), llvm::AArch64FrameLowering::emitEpilogue(), and llvm::AArch64FrameLowering::emitPrologue().
incNumLocalDynamicTLSAccesses()
void llvm::AArch64FunctionInfo::incNumLocalDynamicTLSAccesses () inline
Definition at line 299 of file AArch64MachineFunctionInfo.h.
initializeBaseYamlFields()
void AArch64FunctionInfo::initializeBaseYamlFields (const yaml::AArch64FunctionInfo & YamlMFI)
Definition at line 31 of file AArch64MachineFunctionInfo.cpp.
References llvm::yaml::AArch64FunctionInfo::HasRedZone, and llvm::Optional< T >::hasValue().
isSplitCSR()
bool llvm::AArch64FunctionInfo::isSplitCSR () const inline
Definition at line 215 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64RegisterInfo::getCalleeSavedRegsViaCopy().
isStackRealigned()
bool llvm::AArch64FunctionInfo::isStackRealigned () const inline
Definition at line 206 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64FrameLowering::emitEpilogue().
setArgumentStackToRestore()
void llvm::AArch64FunctionInfo::setArgumentStackToRestore (unsigned bytes) inline
Definition at line 185 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64CallLowering::lowerFormalArguments().
setBytesInStackArgArea()
void llvm::AArch64FunctionInfo::setBytesInStackArgArea (unsigned bytes) inline
Definition at line 182 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64CallLowering::lowerFormalArguments().
setCalleeSaveBaseToFrameRecordOffset()
void llvm::AArch64FunctionInfo::setCalleeSaveBaseToFrameRecordOffset (int Offset) inline
Definition at line 390 of file AArch64MachineFunctionInfo.h.
References Offset.
Referenced by computeCalleeSaveRegisterPairs().
setCalleeSavedStackSize()
void llvm::AArch64FunctionInfo::setCalleeSavedStackSize (unsigned Size) inline
Definition at line 224 of file AArch64MachineFunctionInfo.h.
References llvm::Check::Size.
setCalleeSaveStackHasFreeSpace()
void llvm::AArch64FunctionInfo::setCalleeSaveStackHasFreeSpace (bool s) inline
Definition at line 212 of file AArch64MachineFunctionInfo.h.
References s.
setHasRedZone()
void llvm::AArch64FunctionInfo::setHasRedZone (bool s) inline
Definition at line 305 of file AArch64MachineFunctionInfo.h.
References s.
Referenced by llvm::AArch64FrameLowering::emitPrologue().
setHasStackFrame()
void llvm::AArch64FunctionInfo::setHasStackFrame (bool s) inline
Definition at line 204 of file AArch64MachineFunctionInfo.h.
References s.
setHasSwiftAsyncContext()
void llvm::AArch64FunctionInfo::setHasSwiftAsyncContext (bool HasContext) inline
Definition at line 401 of file AArch64MachineFunctionInfo.h.
setIsSplitCSR()
void llvm::AArch64FunctionInfo::setIsSplitCSR (bool s) inline
Definition at line 216 of file AArch64MachineFunctionInfo.h.
References s.
setJumpTableEntryInfo()
void llvm::AArch64FunctionInfo::setJumpTableEntryInfo (int Idx, unsigned Size, MCSymbol * PCRelSym) inline
Definition at line 331 of file AArch64MachineFunctionInfo.h.
References llvm::Check::Size.
setLocalStackSize()
void llvm::AArch64FunctionInfo::setLocalStackSize (uint64_t Size) inline
Definition at line 218 of file AArch64MachineFunctionInfo.h.
References llvm::Check::Size.
Referenced by llvm::AArch64FrameLowering::emitEpilogue(), and llvm::AArch64FrameLowering::emitPrologue().
setMinMaxSVECSFrameIndex()
void llvm::AArch64FunctionInfo::setMinMaxSVECSFrameIndex (int Min, int Max) inline
Definition at line 291 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized().
setOutliningStyle()
void llvm::AArch64FunctionInfo::setOutliningStyle (std::string Style) inline
Definition at line 221 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64InstrInfo::buildOutlinedFrame().
setSRetReturnReg()
void llvm::AArch64FunctionInfo::setSRetReturnReg (unsigned Reg) inline
Definition at line 323 of file AArch64MachineFunctionInfo.h.
References Reg.
setStackRealigned()
void llvm::AArch64FunctionInfo::setStackRealigned (bool s) inline
Definition at line 207 of file AArch64MachineFunctionInfo.h.
References s.
setStackSizeSVE()
void llvm::AArch64FunctionInfo::setStackSizeSVE (uint64_t S) inline
Definition at line 196 of file AArch64MachineFunctionInfo.h.
References S.
Referenced by llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized().
setSVECalleeSavedStackSize()
void llvm::AArch64FunctionInfo::setSVECalleeSavedStackSize (unsigned Size) inline
Definition at line 284 of file AArch64MachineFunctionInfo.h.
References llvm::Check::Size.
setSwiftAsyncContextFrameIdx()
void llvm::AArch64FunctionInfo::setSwiftAsyncContextFrameIdx (int FI) inline
Definition at line 406 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64FrameLowering::assignCalleeSavedSpillSlots().
setTaggedBasePointerIndex()
void llvm::AArch64FunctionInfo::setTaggedBasePointerIndex (int Index) inline
Definition at line 378 of file AArch64MachineFunctionInfo.h.
References Index.
setTaggedBasePointerOffset()
void llvm::AArch64FunctionInfo::setTaggedBasePointerOffset (unsigned Offset) inline
Definition at line 383 of file AArch64MachineFunctionInfo.h.
References Offset.
Referenced by llvm::AArch64FrameLowering::emitPrologue().
setTailCallReservedStack()
void llvm::AArch64FunctionInfo::setTailCallReservedStack (unsigned bytes) inline
Definition at line 190 of file AArch64MachineFunctionInfo.h.
setVarArgsFPRIndex()
void llvm::AArch64FunctionInfo::setVarArgsFPRIndex (int Index) inline
Definition at line 317 of file AArch64MachineFunctionInfo.h.
References Index.
setVarArgsFPRSize()
void llvm::AArch64FunctionInfo::setVarArgsFPRSize (unsigned Size) inline
Definition at line 320 of file AArch64MachineFunctionInfo.h.
References llvm::Check::Size.
setVarArgsGPRIndex()
void llvm::AArch64FunctionInfo::setVarArgsGPRIndex (int Index) inline
Definition at line 311 of file AArch64MachineFunctionInfo.h.
References Index.
setVarArgsGPRSize()
void llvm::AArch64FunctionInfo::setVarArgsGPRSize (unsigned Size) inline
Definition at line 314 of file AArch64MachineFunctionInfo.h.
References llvm::Check::Size.
setVarArgsStackIndex()
void llvm::AArch64FunctionInfo::setVarArgsStackIndex (int Index) inline
Definition at line 308 of file AArch64MachineFunctionInfo.h.
References Index.
Referenced by llvm::AArch64CallLowering::lowerFormalArguments().
shouldSignReturnAddress() [1/2]
bool AArch64FunctionInfo::shouldSignReturnAddress () const
Definition at line 112 of file AArch64MachineFunctionInfo.cpp.
References llvm::any_of(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFunction::getFrameInfo(), and Info.
Referenced by llvm::AArch64InstrInfo::buildOutlinedFrame(), and outliningCandidatesSigningScopeConsensus().
shouldSignReturnAddress() [2/2]
bool AArch64FunctionInfo::shouldSignReturnAddress (bool SpillsLR) const
Definition at line 104 of file AArch64MachineFunctionInfo.cpp.
shouldSignWithBKey()
bool llvm::AArch64FunctionInfo::shouldSignWithBKey () const inline
Definition at line 397 of file AArch64MachineFunctionInfo.h.
Referenced by outliningCandidatesSigningKeyConsensus().
The documentation for this class was generated from the following files:
lib/Target/AArch64/AArch64MachineFunctionInfo.h
lib/Target/AArch64/AArch64MachineFunctionInfo.cpp