LLVM: llvm::jitlink::SectionRange Class Reference
llvm::jitlink::SectionRange Class Reference
Represents a section address range via a pair of Block pointers to the first and last Blocks in the section.
#include "llvm/ExecutionEngine/JITLink/JITLink.h"
Public Member Functions
SectionRange ()=default
SectionRange (const Section &Sec)
Block * getFirstBlock () const
Block * getLastBlock () const
bool empty () const
JITTargetAddress getStart () const
JITTargetAddress getEnd () const
uint64_t getSize () const
Detailed Description
Represents a section address range via a pair of Block pointers to the first and last Blocks in the section.
Definition at line 745 of file JITLink.h.
Constructor & Destructor Documentation
SectionRange() [1/2]
llvm::jitlink::SectionRange::SectionRange () default
SectionRange() [2/2]
llvm::jitlink::SectionRange::SectionRange (const Section & Sec) inline
Definition at line 748 of file JITLink.h.
References B, llvm::jitlink::Section::blocks(), llvm::empty(), and llvm::jitlink::Addressable::getAddress().
Member Function Documentation
empty()
bool llvm::jitlink::SectionRange::empty () const inline
Definition at line 767 of file JITLink.h.
References assert().
getEnd()
JITTargetAddress llvm::jitlink::SectionRange::getEnd () const inline
Definition at line 774 of file JITLink.h.
References llvm::jitlink::Addressable::getAddress(), and llvm::jitlink::Block::getSize().
Referenced by getSize().
getFirstBlock()
Block* llvm::jitlink::SectionRange::getFirstBlock () const inline
Definition at line 759 of file JITLink.h.
References assert().
getLastBlock()
Block* llvm::jitlink::SectionRange::getLastBlock () const inline
Definition at line 763 of file JITLink.h.
References assert().
getSize()
uint64_t llvm::jitlink::SectionRange::getSize () const inline
Definition at line 777 of file JITLink.h.
References getEnd(), and getStart().
getStart()
JITTargetAddress llvm::jitlink::SectionRange::getStart () const inline
Definition at line 771 of file JITLink.h.
References llvm::jitlink::Addressable::getAddress().
Referenced by getSize(), and llvm::orc::ELFDebugObjectSection< ELFT >::setTargetMemoryRange().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/JITLink/JITLink.h