LLVM: llvm::ChangedIRComparer Class Reference
llvm::ChangedIRComparer Class Reference
#include "llvm/Passes/StandardInstrumentations.h"
Public Member Functions
ChangedIRComparer (raw_ostream &OS, const ChangedIRData &Before, const ChangedIRData &After, bool ColourMode)
void compare (Any IR, StringRef Prefix, StringRef PassID, StringRef Name)
Static Public Member Functions
static void analyzeIR (Any IR, ChangedIRData &Data)
Protected Member Functions
void handleFunctionCompare (StringRef Name, StringRef Prefix, StringRef PassID, bool InModule, const ChangedFuncData &Before, const ChangedFuncData &After)
Static Protected Member Functions
static const Module * getModuleForComparison (Any IR)
static bool generateFunctionData (ChangedIRData &Data, const Function &F)
Protected Attributes
const ChangedIRData & Before
const ChangedIRData & After
raw_ostream & Out
bool UseColour
Detailed Description
Definition at line 343 of file StandardInstrumentations.h.
Constructor & Destructor Documentation
ChangedIRComparer()
llvm::ChangedIRComparer::ChangedIRComparer (raw_ostream & OS, const ChangedIRData & Before, const ChangedIRData & After, bool ColourMode) inline
Definition at line 345 of file StandardInstrumentations.h.
Member Function Documentation
analyzeIR()
void ChangedIRComparer::analyzeIR (Any IR, ChangedIRData & Data) static
Definition at line 661 of file StandardInstrumentations.cpp.
References assert(), llvm::Data, F, generateFunctionData(), llvm::LoopBase< BlockT, LoopT >::getHeader(), getModuleForComparison(), llvm::BasicBlock::getParent(), IR, and M.
Referenced by llvm::InLineChangePrinter::generateIRRepresentation().
compare()
void ChangedIRComparer::compare (Any IR, StringRef Prefix, StringRef PassID, StringRef Name)
Definition at line 636 of file StandardInstrumentations.cpp.
References A, After, assert(), B, Before, llvm::StringMap< ValueTy, AllocatorTy >::begin(), llvm::OrderedChangedData< IRData >::getData(), getModuleForComparison(), handleFunctionCompare(), IR, llvm::cl::Prefix, llvm::OrderedChangedData< IRData >::report(), and llvm::StringMapImpl::size().
Referenced by llvm::InLineChangePrinter::handleAfter().
generateFunctionData()
bool ChangedIRComparer::generateFunctionData (ChangedIRData & Data, const Function & F) static protected
Definition at line 692 of file StandardInstrumentations.cpp.
References B, llvm::Data, F, llvm::OrderedChangedData< IRData >::getData(), llvm::OrderedChangedData< IRData >::getOrder(), llvm::StringMap< ValueTy, AllocatorTy >::insert(), and llvm::isFunctionInPrintList().
Referenced by analyzeIR().
getModuleForComparison()
const Module * ChangedIRComparer::getModuleForComparison (Any IR) static protected
Definition at line 681 of file StandardInstrumentations.cpp.
References IR.
Referenced by analyzeIR(), and compare().
handleFunctionCompare()
void ChangedIRComparer::handleFunctionCompare (StringRef Name, StringRef Prefix, StringRef PassID, bool InModule, const ChangedFuncData & Before, const ChangedFuncData & After) protected
Definition at line 1188 of file StandardInstrumentations.cpp.
References A, B, and llvm::OrderedChangedData< IRData >::report().
Referenced by compare().
Member Data Documentation
After
const ChangedIRData& llvm::ChangedIRComparer::After protected
Definition at line 370 of file StandardInstrumentations.h.
Referenced by compare().
Before
const ChangedIRData& llvm::ChangedIRComparer::Before protected
Definition at line 369 of file StandardInstrumentations.h.
Referenced by compare().
Out
raw_ostream& llvm::ChangedIRComparer::Out protected
Definition at line 371 of file StandardInstrumentations.h.
UseColour
bool llvm::ChangedIRComparer::UseColour protected
Definition at line 372 of file StandardInstrumentations.h.
The documentation for this class was generated from the following files:
include/llvm/Passes/StandardInstrumentations.h
lib/Passes/StandardInstrumentations.cpp