LLVM: llvm::Negator Class Reference
llvm::Negator Class Reference final
#include "Transforms/InstCombine/InstCombineInternal.h"
Static Public Member Functions
static LLVM_NODISCARD Value * Negate (bool LHSIsZero, Value *Root, InstCombinerImpl &IC)
Attempt to negate Root.
Detailed Description
Definition at line 737 of file InstCombineInternal.h.
Member Function Documentation
Negate()
LLVM_NODISCARD Value * Negator::Negate (bool LHSIsZero, Value * Root, InstCombinerImpl & IC) static
Attempt to negate Root.
Retuns nullptr if negation can't be performed, otherwise returns negated value.
Definition at line 489 of file InstCombineNegator.cpp.
References llvm::InstCombiner::Builder, llvm::IRBuilderBase::ClearInsertionPoint(), llvm::dbgs(), llvm::InstCombiner::getAssumptionCache(), llvm::Value::getContext(), llvm::InstCombiner::getDataLayout(), llvm::InstCombiner::getDominatorTree(), I, llvm::IRBuilderBase::Insert(), LLVM_DEBUG, N, NegatorEnabled, llvm::IRBuilderBase::SetCurrentDebugLocation(), and llvm::DebugCounter::shouldExecute().
Referenced by llvm::InstCombinerImpl::visitMul(), and llvm::InstCombinerImpl::visitSub().
The documentation for this class was generated from the following files:
lib/Transforms/InstCombine/InstCombineInternal.h
lib/Transforms/InstCombine/InstCombineNegator.cpp