LLVM: llvm::VectorType Class Reference
llvm::VectorType Class Reference
Base class of all SIMD vector types.
#include "llvm/IR/DerivedTypes.h"
Public Member Functions
VectorType (const VectorType &)=delete
VectorType & operator= (const VectorType &)=delete
Type * getElementType () const
ElementCount getElementCount () const
Return an ElementCount instance to represent the (possibly scalable) number of elements in the vector.
Public Member Functions inherited from llvm::Type
void print (raw_ostream &O, bool IsForDebug=false, bool NoDetails=false) const
Print the current type.
void dump () const
LLVMContext & getContext () const
Return the LLVMContext in which this type was uniqued.
TypeID getTypeID () const
Return the type id for the type.
bool isVoidTy () const
Return true if this is 'void'.
bool isHalfTy () const
Return true if this is 'half', a 16-bit IEEE fp type.
bool isBFloatTy () const
Return true if this is 'bfloat', a 16-bit bfloat type.
bool isFloatTy () const
Return true if this is 'float', a 32-bit IEEE fp type.
bool isDoubleTy () const
Return true if this is 'double', a 64-bit IEEE fp type.
bool isX86_FP80Ty () const
Return true if this is x86 long double.
bool isFP128Ty () const
Return true if this is 'fp128'.
bool isPPC_FP128Ty () const
Return true if this is powerpc long double.
bool isFloatingPointTy () const
Return true if this is one of the six floating-point types.
const fltSemantics & getFltSemantics () const
bool isX86_MMXTy () const
Return true if this is X86 MMX.
bool isX86_AMXTy () const
Return true if this is X86 AMX.
bool isFPOrFPVectorTy () const
Return true if this is a FP type or a vector of FP.
bool isLabelTy () const
Return true if this is 'label'.
bool isMetadataTy () const
Return true if this is 'metadata'.
bool isTokenTy () const
Return true if this is 'token'.
bool isIntegerTy () const
True if this is an instance of IntegerType.
bool isIntegerTy (unsigned Bitwidth) const
Return true if this is an IntegerType of the given width.
bool isIntOrIntVectorTy () const
Return true if this is an integer type or a vector of integer types.
bool isIntOrIntVectorTy (unsigned BitWidth) const
Return true if this is an integer type or a vector of integer types of the given width.
bool isIntOrPtrTy () const
Return true if this is an integer type or a pointer type.
bool isFunctionTy () const
True if this is an instance of FunctionType.
bool isStructTy () const
True if this is an instance of StructType.
bool isArrayTy () const
True if this is an instance of ArrayType.
bool isPointerTy () const
True if this is an instance of PointerType.
bool isOpaquePointerTy () const
True if this is an instance of an opaque PointerType.
bool isPtrOrPtrVectorTy () const
Return true if this is a pointer type or a vector of pointer types.
bool isVectorTy () const
True if this is an instance of VectorType.
bool canLosslesslyBitCastTo (Type *Ty) const
Return true if this type could be converted with a lossless BitCast to type 'Ty'.
bool isEmptyTy () const
Return true if this type is empty, that is, it has no elements or all of its elements are empty.
bool isFirstClassType () const
Return true if the type is "first class", meaning it is a valid type for a Value.
bool isSingleValueType () const
Return true if the type is a valid type for a register in codegen.
bool isAggregateType () const
Return true if the type is an aggregate type.
bool isSized (SmallPtrSetImpl< Type * > *Visited=nullptr) const
Return true if it makes sense to take the size of this type.
TypeSize getPrimitiveSizeInBits () const LLVM_READONLY
Return the basic size of this type if it is a primitive type.
unsigned getScalarSizeInBits () const LLVM_READONLY
If this is a vector type, return the getPrimitiveSizeInBits value for the element type.
int getFPMantissaWidth () const
Return the width of the mantissa of this type.
bool isIEEE () const
Return whether the type is IEEE compatible, as defined by the eponymous method in APFloat.
Type * getScalarType () const
If this is a vector type, return the element type, otherwise return 'this'.
subtype_iterator subtype_begin () const
subtype_iterator subtype_end () const
ArrayRef< Type * > subtypes () const
subtype_reverse_iterator subtype_rbegin () const
subtype_reverse_iterator subtype_rend () const
Type * getContainedType (unsigned i) const
This method is used to implement the type iterator (defined at the end of the file).
unsigned getNumContainedTypes () const
Return the number of types in the derived type.
unsigned getIntegerBitWidth () const
Type * getFunctionParamType (unsigned i) const
unsigned getFunctionNumParams () const
bool isFunctionVarArg () const
StringRef getStructName () const
unsigned getStructNumElements () const
Type * getStructElementType (unsigned N) const
uint64_t getArrayNumElements () const
Type * getArrayElementType () const
Type * getPointerElementType () const
Type * getWithNewType (Type *EltTy) const
Given vector type, change the element type, whilst keeping the old number of elements.
Type * getWithNewBitWidth (unsigned NewBitWidth) const
Given an integer or vector type, change the lane bitwidth to NewBitwidth, whilst keeping the old number of lanes.
Type * getExtendedType () const
Given scalar/vector integer type, returns a type with elements twice as wide as in the original type.
unsigned getPointerAddressSpace () const
Get the address space of this pointer or pointer vector type.
PointerType * getPointerTo (unsigned AddrSpace=0) const
Return a pointer to the current type.
Static Public Member Functions
static VectorType * get (Type *ElementType, ElementCount EC)
This static method is the primary way to construct an VectorType.
static VectorType * get (Type *ElementType, unsigned NumElements, bool Scalable)
static VectorType * get (Type *ElementType, const VectorType *Other)
static VectorType * getInteger (VectorType *VTy)
This static method gets a VectorType with the same number of elements as the input type, and the element type is an integer type of the same width as the input element type.
static VectorType * getExtendedElementVectorType (VectorType *VTy)
This static method is like getInteger except that the element types are twice as wide as the elements in the input type.
static VectorType * getTruncatedElementVectorType (VectorType *VTy)
static VectorType * getSubdividedVectorType (VectorType *VTy, int NumSubdivs)
static VectorType * getHalfElementsVectorType (VectorType *VTy)
This static method returns a VectorType with half as many elements as the input type and the same element type.
static VectorType * getDoubleElementsVectorType (VectorType *VTy)
This static method returns a VectorType with twice as many elements as the input type and the same element type.
static bool isValidElementType (Type *ElemTy)
Return true if the specified type is valid as a element type.
static bool classof (const Type *T)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::Type
static Type * getPrimitiveType (LLVMContext &C, TypeID IDNumber)
Return a type based on an identifier.
static Type * getVoidTy (LLVMContext &C)
static Type * getLabelTy (LLVMContext &C)
static Type * getHalfTy (LLVMContext &C)
static Type * getBFloatTy (LLVMContext &C)
static Type * getFloatTy (LLVMContext &C)
static Type * getDoubleTy (LLVMContext &C)
static Type * getMetadataTy (LLVMContext &C)
static Type * getX86_FP80Ty (LLVMContext &C)
static Type * getFP128Ty (LLVMContext &C)
static Type * getPPC_FP128Ty (LLVMContext &C)
static Type * getX86_MMXTy (LLVMContext &C)
static Type * getX86_AMXTy (LLVMContext &C)
static Type * getTokenTy (LLVMContext &C)
static IntegerType * getIntNTy (LLVMContext &C, unsigned N)
static IntegerType * getInt1Ty (LLVMContext &C)
static IntegerType * getInt8Ty (LLVMContext &C)
static IntegerType * getInt16Ty (LLVMContext &C)
static IntegerType * getInt32Ty (LLVMContext &C)
static IntegerType * getInt64Ty (LLVMContext &C)
static IntegerType * getInt128Ty (LLVMContext &C)
template<typename ScalarTy >
static Type * getScalarTy (LLVMContext &C)
static Type * getFloatingPointTy (LLVMContext &C, const fltSemantics &S)
static PointerType * getHalfPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getBFloatPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getFloatPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getDoublePtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getX86_FP80PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getFP128PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getPPC_FP128PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getX86_MMXPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getX86_AMXPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getIntNPtrTy (LLVMContext &C, unsigned N, unsigned AS=0)
static PointerType * getInt1PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt8PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt16PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt32PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt64PtrTy (LLVMContext &C, unsigned AS=0)
Protected Member Functions
VectorType (Type *ElType, unsigned EQ, Type::TypeID TID)
Protected Member Functions inherited from llvm::Type
Type (LLVMContext &C, TypeID tid)
~Type ()=default
unsigned getSubclassData () const
void setSubclassData (unsigned val)
Protected Attributes
const unsigned ElementQuantity
The element quantity of this vector.
Protected Attributes inherited from llvm::Type
unsigned NumContainedTys = 0
Keeps track of how many Type*'s there are in the ContainedTys list.
Type *const * ContainedTys = nullptr
A pointer to the array of Types contained by this Type.
Additional Inherited Members
Public Types inherited from llvm::Type
enum TypeID {
HalfTyID = 0, BFloatTyID, FloatTyID, DoubleTyID,
X86_FP80TyID, FP128TyID, PPC_FP128TyID, VoidTyID,
LabelTyID, MetadataTyID, X86_MMXTyID, X86_AMXTyID,
TokenTyID, IntegerTyID, FunctionTyID, PointerTyID,
StructTyID, ArrayTyID, FixedVectorTyID, ScalableVectorTyID
}
Definitions of all of the base types for the Type system.
using subtype_iterator = Type *const *
using subtype_reverse_iterator = std::reverse_iterator< subtype_iterator >
Detailed Description
Base class of all SIMD vector types.
Definition at line 388 of file DerivedTypes.h.
Constructor & Destructor Documentation
VectorType() [1/2]
VectorType::VectorType (Type * ElType, unsigned EQ, Type::TypeID TID) protected
Definition at line 627 of file Type.cpp.
References llvm::Type::ContainedTys, and llvm::Type::NumContainedTys.
VectorType() [2/2]
llvm::VectorType::VectorType (const VectorType &) delete
Member Function Documentation
classof()
static bool llvm::VectorType::classof (const Type * T) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 517 of file DerivedTypes.h.
References llvm::Type::FixedVectorTyID, llvm::Type::ScalableVectorTyID, and T.
get() [1/3]
static VectorType* llvm::VectorType::get (Type * ElementType, const VectorType * Other) inline static
Definition at line 432 of file DerivedTypes.h.
References get(), and Other.
get() [2/3]
VectorType * VectorType::get (Type * ElementType, ElementCount EC) static
This static method is the primary way to construct an VectorType.
Definition at line 634 of file Type.cpp.
References llvm::ScalableVectorType::get(), llvm::FixedVectorType::get(), llvm::LinearPolySize< LeafTy >::getKnownMinValue(), and llvm::LinearPolySize< LeafTy >::isScalable().
Referenced by buildNew(), llvm::InnerLoopVectorizer::buildScalarSteps(), llvm::LoopVectorizationCostModel::calculateRegisterUsage(), canonicalizeBitCastExtElt(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldGetElementPtr(), llvm::ShuffleVectorInst::convertShuffleMaskForBitcode(), createAllocaInstAtEntry(), llvm::IRBuilderBase::CreateMaskedGather(), llvm::IRBuilderBase::CreateMaskedScatter(), llvm::IRBuilderBase::CreateVectorSplat(), DecodeFixedType(), llvm::VPFirstOrderRecurrencePHIRecipe::execute(), llvm::VPReductionPHIRecipe::execute(), llvm::VPReplicateRecipe::execute(), llvm::InnerLoopVectorizer::fixReduction(), llvm::InstCombinerImpl::foldICmpAndConstant(), foldICmpBitCast(), llvm::InstCombinerImpl::foldICmpShlConstant(), get(), llvm::VPTransformState::get(), getAllocaPos(), llvm::VPIntrinsic::getDeclarationForParams(), getDoubleElementsVectorType(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getExtendedAddReductionCost(), getExtendedElementVectorType(), llvm::ConstantExpr::getFCmp(), llvm::GetElementPtrInst::getGEPReturnType(), llvm::ConstantExpr::getGetElementPtr(), getHalfElementsVectorType(), llvm::ConstantExpr::getICmp(), llvm::DataLayout::getIndexType(), getInteger(), llvm::DataLayout::getIntPtrType(), llvm::ConstantDataVector::getRaw(), getReducedType(), llvm::ConstantExpr::getShuffleVector(), llvm::ConstantVector::getSplat(), llvm::InnerLoopVectorizer::getStepVector(), getTruncatedElementVectorType(), llvm::Type::getWithNewType(), llvm::CmpInst::makeCmpResultType(), MaybeVectorizeType(), llvm::recognizeBSwapOrBitReverseIdiom(), SimplifyGEPInst(), llvm::ToVectorTy(), llvm::InnerLoopVectorizer::truncateToMinimalBitwidths(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), llvm::InnerLoopVectorizer::vectorizeMemoryInstruction(), llvm::InstCombinerImpl::visitAddrSpaceCast(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitGetElementPtrInst(), llvm::InstCombinerImpl::visitInsertElementInst(), llvm::InstCombinerImpl::visitTrunc(), llvm::InnerLoopVectorizer::widenCallInstruction(), llvm::InnerLoopVectorizer::widenInstruction(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
get() [3/3]
static VectorType* llvm::VectorType::get (Type * ElementType, unsigned NumElements, bool Scalable) inline static
Definition at line 426 of file DerivedTypes.h.
References llvm::LinearPolySize< ElementCount >::get(), and get().
getDoubleElementsVectorType()
static VectorType* llvm::VectorType::getDoubleElementsVectorType (VectorType * VTy) inline static
This static method returns a VectorType with twice as many elements as the input type and the same element type.
Definition at line 502 of file DerivedTypes.h.
References assert(), get(), getElementCount(), and getElementType().
Referenced by llvm::FixedVectorType::getDoubleElementsVectorType(), llvm::ScalableVectorType::getDoubleElementsVectorType(), and getSubdividedVectorType().
getElementCount()
ElementCount VectorType::getElementCount () const inline
Return an ElementCount instance to represent the (possibly scalable) number of elements in the vector.
Definition at line 626 of file DerivedTypes.h.
References ElementQuantity, and llvm::LinearPolySize< ElementCount >::get().
Referenced by llvm::SelectInst::areInvalidOperands(), BitCastConstantVector(), llvm::InnerLoopVectorizer::emitTransformedIndex(), llvm::VPReductionRecipe::execute(), llvm::InstCombinerImpl::FoldOpIntoSelect(), llvm::Constant::getAllOnesValue(), getDoubleElementsVectorType(), llvm::EVT::getEVT(), getExtendedElementVectorType(), getHalfElementsVectorType(), getInteger(), llvm::Type::getPrimitiveSizeInBits(), getTruncatedElementVectorType(), llvm::DataLayout::getTypeSizeInBits(), llvm::MVT::getVT(), instCombineSVETBL(), matchIntrinsicType(), and llvm::InstCombinerImpl::visitExtractElementInst().
getElementType()
Type* llvm::VectorType::getElementType () const inline
Definition at line 421 of file DerivedTypes.h.
Referenced by BitCastConstantVector(), CheckAndCreateOffsetAdd(), computeExtractCost(), llvm::ConstantFoldCastInstruction(), DecodeFixedType(), emitGlobalConstantVector(), llvm::VPReductionRecipe::execute(), llvm::findScalarElement(), foldConstantInsEltIntoShuffle(), llvm::Constant::getAllOnesValue(), getDoubleElementsVectorType(), llvm::EVT::getEVT(), getExtendedElementVectorType(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getExtractWithExtendCost(), llvm::AArch64TTIImpl::getExtractWithExtendCost(), getHalfElementsVectorType(), getInteger(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX2(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX512(), llvm::HexagonTTIImpl::getMemoryOpCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getMinMaxReductionCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getOrderedReductionCost(), llvm::Type::getPrimitiveSizeInBits(), llvm::GCNTTIImpl::getShuffleCost(), llvm::X86TTIImpl::getShuffleCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getTreeReductionCost(), getTruncatedElementVectorType(), llvm::DataLayout::getTypeSizeInBits(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::MVT::getVT(), llvm::ARMTargetLowering::isLegalInterleavedAccessType(), llvm::AArch64TargetLowering::isLegalInterleavedAccessType(), isVectorPromotionViable(), isVectorPromotionViableForSlice(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), matchIntrinsicType(), optimizeVectorResizeWithIntegerBitCasts(), UpgradeIntrinsicFunction1(), llvm::Interpreter::visitInsertElementInst(), and llvm::Interpreter::visitShuffleVectorInst().
getExtendedElementVectorType()
static VectorType* llvm::VectorType::getExtendedElementVectorType (VectorType * VTy) inline static
This static method is like getInteger except that the element types are twice as wide as the elements in the input type.
Definition at line 448 of file DerivedTypes.h.
References assert(), get(), getElementCount(), getElementType(), and llvm::Type::isIntOrIntVectorTy().
Referenced by DecodeFixedType(), llvm::X86TTIImpl::getArithmeticInstrCost(), llvm::FixedVectorType::getExtendedElementVectorType(), llvm::ScalableVectorType::getExtendedElementVectorType(), llvm::Type::getExtendedType(), and matchIntrinsicType().
getHalfElementsVectorType()
static VectorType* llvm::VectorType::getHalfElementsVectorType (VectorType * VTy) inline static
This static method returns a VectorType with half as many elements as the input type and the same element type.
Definition at line 492 of file DerivedTypes.h.
References assert(), get(), getElementCount(), and getElementType().
Referenced by DecodeFixedType(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getCastInstrCost(), llvm::FixedVectorType::getHalfElementsVectorType(), llvm::ScalableVectorType::getHalfElementsVectorType(), and matchIntrinsicType().
getInteger()
static VectorType* llvm::VectorType::getInteger (VectorType * VTy) inline static
This static method gets a VectorType with the same number of elements as the input type, and the element type is an integer type of the same width as the input element type.
Definition at line 439 of file DerivedTypes.h.
References assert(), llvm::IntegerType::get(), get(), llvm::Type::getContext(), getElementCount(), getElementType(), and llvm::Type::getPrimitiveSizeInBits().
Referenced by DecodeFixedType(), llvm::FixedVectorType::getInteger(), llvm::ScalableVectorType::getInteger(), getNegativeIsTrueBoolVec(), llvm::Constant::isElementWiseEqual(), matchIntrinsicType(), and simplifyX86movmsk().
getSubdividedVectorType()
static VectorType* llvm::VectorType::getSubdividedVectorType (VectorType * VTy, int NumSubdivs) inline static
Definition at line 482 of file DerivedTypes.h.
References getDoubleElementsVectorType(), getTruncatedElementVectorType(), and i.
Referenced by DecodeFixedType(), llvm::FixedVectorType::getSubdividedVectorType(), llvm::ScalableVectorType::getSubdividedVectorType(), and matchIntrinsicType().
getTruncatedElementVectorType()
static VectorType* llvm::VectorType::getTruncatedElementVectorType (VectorType * VTy) inline static
Definition at line 457 of file DerivedTypes.h.
References assert(), llvm::Type::DoubleTyID, llvm::Type::FloatTyID, llvm::IntegerType::get(), get(), llvm::Type::getContext(), getElementCount(), getElementType(), llvm::Type::getFloatTy(), llvm::Type::getHalfTy(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getTypeID(), llvm::Type::isFloatingPointTy(), and llvm_unreachable.
Referenced by DecodeFixedType(), getSubdividedVectorType(), llvm::FixedVectorType::getTruncatedElementVectorType(), llvm::ScalableVectorType::getTruncatedElementVectorType(), and matchIntrinsicType().
isValidElementType()
bool VectorType::isValidElementType (Type * ElemTy) static
Return true if the specified type is valid as a element type.
Definition at line 641 of file Type.cpp.
References llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), and llvm::Type::isPointerTy().
Referenced by llvm::LoopVectorizationCostModel::calculateRegisterUsage(), canonicalizeBitCastExtElt(), combineTargetShuffle(), llvm::ScalableVectorType::get(), llvm::FixedVectorType::get(), isValidElementType(), tryPromoteAllocaToVector(), and llvm::InstCombinerImpl::visitShuffleVectorInst().
operator=()
VectorType& llvm::VectorType::operator= (const VectorType &) delete
Member Data Documentation
ElementQuantity
const unsigned llvm::VectorType::ElementQuantity protected
The element quantity of this vector.
The meaning of this value depends on the type of vector:
For FixedVectorType = <ElementQuantity x ty>, there are exactly ElementQuantity elements in this vector.
For ScalableVectorType = <vscale x ElementQuantity x ty>, there are vscale * ElementQuantity elements in this vector, where vscale is a runtime-constant integer greater than 0.
Definition at line 413 of file DerivedTypes.h.
Referenced by getElementCount(), llvm::ScalableVectorType::getMinNumElements(), and llvm::FixedVectorType::getNumElements().
The documentation for this class was generated from the following files:
include/llvm/IR/DerivedTypes.h
lib/IR/Type.cpp