LLVM: llvm::InstCombinePass Class Reference
llvm::InstCombinePass Class Reference
#include "llvm/Transforms/InstCombine/InstCombine.h"
Public Member Functions
InstCombinePass ()
InstCombinePass (unsigned MaxIterations)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< InstCombinePass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 25 of file InstCombine.h.
Constructor & Destructor Documentation
InstCombinePass() [1/2]
InstCombinePass::InstCombinePass () explicit
Definition at line 4201 of file InstructionCombining.cpp.
InstCombinePass() [2/2]
InstCombinePass::InstCombinePass (unsigned MaxIterations) explicit
Definition at line 4203 of file InstructionCombining.cpp.
Member Function Documentation
run()
PreservedAnalyses InstCombinePass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 4206 of file InstructionCombining.cpp.
References llvm::PreservedAnalyses::all(), llvm::AMDGPUISD::BFI, combineInstructionsOverFunction(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::PreservedAnalyses::preserveSet().
The documentation for this class was generated from the following files:
include/llvm/Transforms/InstCombine/InstCombine.h
lib/Transforms/InstCombine/InstructionCombining.cpp