LLVM: llvm::ElementCount Class Reference
llvm::ElementCount Class Reference
#include "llvm/Support/TypeSize.h"
Public Member Functions
ElementCount ()
ElementCount (const LinearPolySize< ElementCount > &V)
bool isScalar () const
Counting predicates.
bool isVector () const
One or more elements.
Public Member Functions inherited from llvm::LinearPolySize< ElementCount >
ScalarTy getKnownMinValue () const
Returns the minimum value this size can represent.
bool isScalable () const
Returns whether the size is scaled by a runtime quantity (vscale).
bool isKnownEven () const
A return value of true indicates we know at compile time that the number of elements (vscale * Min) is definitely even.
bool isKnownMultipleOf (ScalarTy RHS) const
This function tells the caller whether the element count is known at compile time to be a multiple of the scalar value RHS.
ScalarTy getFixedValue () const
ElementCount divideCoefficientBy (ScalarTy RHS) const
We do not provide the '/' operator here because division for polynomial types does not work in the same way as for normal integer types.
ElementCount coefficientNextPowerOf2 () const
void print (raw_ostream &OS) const
Printing function.
Public Member Functions inherited from llvm::UnivariateLinearPolyBase< ElementCount >
bool operator== (const UnivariateLinearPolyBase &RHS) const
bool operator!= (const UnivariateLinearPolyBase &RHS) const
bool isZero () const
bool isNonZero () const
operator bool () const
ScalarTy getValue () const
ScalarTy getValue (unsigned Dim) const
ElementCount getWithIncrement (ScalarTy RHS) const
Add RHS to the value at the univariate dimension.
ElementCount getWithDecrement (ScalarTy RHS) const
Subtract RHS from the value at the univariate dimension.
Additional Inherited Members
Public Types inherited from llvm::LinearPolySize< ElementCount >
enum Dims
using ScalarTy = typename UnivariateLinearPolyBase< ElementCount >::ScalarTy
Public Types inherited from llvm::UnivariateLinearPolyBase< ElementCount >
using ScalarTy = typename LinearPolyBaseTypeTraits< ElementCount >::ScalarTy
Static Public Member Functions inherited from llvm::LinearPolySize< ElementCount >
static ElementCount getFixed (ScalarTy MinVal)
static ElementCount getScalable (ScalarTy MinVal)
static ElementCount get (ScalarTy MinVal, bool Scalable)
static ElementCount getNull ()
static bool isKnownLT (const LinearPolySize &LHS, const LinearPolySize &RHS)
static bool isKnownGT (const LinearPolySize &LHS, const LinearPolySize &RHS)
static bool isKnownLE (const LinearPolySize &LHS, const LinearPolySize &RHS)
static bool isKnownGE (const LinearPolySize &LHS, const LinearPolySize &RHS)
Static Public Attributes inherited from llvm::UnivariateLinearPolyBase< ElementCount >
static constexpr auto Dimensions
Protected Member Functions inherited from llvm::LinearPolySize< ElementCount >
LinearPolySize (ScalarTy MinVal, Dims D)
LinearPolySize (const UnivariateLinearPolyBase< ElementCount > &V)
Protected Member Functions inherited from llvm::UnivariateLinearPolyBase< ElementCount >
UnivariateLinearPolyBase (ScalarTy Val, unsigned UnivariateDim)
Protected Attributes inherited from llvm::UnivariateLinearPolyBase< ElementCount >
ScalarTy Value
unsigned UnivariateDim
Detailed Description
Definition at line 386 of file TypeSize.h.
Constructor & Destructor Documentation
ElementCount() [1/2]
llvm::ElementCount::ElementCount () inline
Definition at line 388 of file TypeSize.h.
ElementCount() [2/2]
llvm::ElementCount::ElementCount (const LinearPolySize< ElementCount > & V) inline
Definition at line 390 of file TypeSize.h.
Member Function Documentation
isScalar()
bool llvm::ElementCount::isScalar () const inline
Counting predicates.
Number of elements.. Exactly one element.
Definition at line 396 of file TypeSize.h.
References llvm::LinearPolySize< ElementCount >::getKnownMinValue(), and llvm::LinearPolySize< ElementCount >::isScalable().
Referenced by llvm::LoopVectorizationCostModel::collectInstsToScalarize(), llvm::LoopVectorizationCostModel::collectUniformsAndScalars(), llvm::VPFirstOrderRecurrencePHIRecipe::execute(), llvm::VPReductionPHIRecipe::execute(), llvm::VPWidenCanonicalIVRecipe::execute(), llvm::VPTransformState::get(), getCopyToPartsVector(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicInstrCost(), llvm::TargetLoweringBase::getPreferredVectorAction(), llvm::LoopVectorizationCostModel::getVectorCallCost(), llvm::TargetLoweringBase::getVectorTypeBreakdown(), llvm::hasVectorizeTransformation(), llvm::LoopVectorizationCostModel::isScalarAfterVectorization(), llvm::LoopVectorizationCostModel::isUniformAfterVectorization(), MaybeVectorizeType(), llvm::LoopVectorizationPlanner::planInVPlanNativePath(), llvm::LoopVectorizePass::processLoop(), llvm::LLT::scalarOrVector(), llvm::LoopVectorizationCostModel::selectInterleaveCount(), llvm::LoopVectorizationCostModel::selectVectorizationFactor(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), llvm::ToVectorTy(), llvm::LLT::vector(), llvm::InnerLoopVectorizer::widenGEP(), llvm::InnerLoopVectorizer::widenInstruction(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
isVector()
bool llvm::ElementCount::isVector () const inline
One or more elements.
Definition at line 398 of file TypeSize.h.
References llvm::LinearPolySize< ElementCount >::getKnownMinValue(), and llvm::LinearPolySize< ElementCount >::isScalable().
Referenced by llvm::InnerLoopVectorizer::buildScalarSteps(), llvm::LoopVectorizationCostModel::canTruncateToMinimalBitwidth(), llvm::LoopVectorizationCostModel::computeMaxVF(), llvm::VPFirstOrderRecurrencePHIRecipe::execute(), llvm::VPReductionRecipe::execute(), llvm::VPReplicateRecipe::execute(), llvm::InnerLoopVectorizer::fixFirstOrderRecurrence(), llvm::InnerLoopVectorizer::fixReduction(), llvm::InnerLoopVectorizer::fixVectorizedLoop(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicInstrCost(), llvm::LoopVectorizationCostModel::getWideningCost(), llvm::LoopVectorizationCostModel::getWideningDecision(), llvm::FixedScalableVFPair::hasVector(), llvm::hasVectorizeTransformation(), llvm::LoopVectorizationCostModel::isProfitableToScalarize(), llvm::LoopVectorizationPlanner::plan(), llvm::LoopVectorizePass::processLoop(), llvm::LoopVectorizationCostModel::requiresScalarEpilogue(), llvm::LoopVectorizationCostModel::selectInterleaveCount(), llvm::LoopVectorizationCostModel::setWideningDecision(), warnAboutLeftoverTransformations(), llvm::InnerLoopVectorizer::widenCallInstruction(), and llvm::InnerLoopVectorizer::widenGEP().
The documentation for this class was generated from the following file:
include/llvm/Support/TypeSize.h