LLVM: llvm::LoadAndStorePromoter Class Reference
llvm::LoadAndStorePromoter Class Reference
Helper class for promoting a collection of loads and stores into SSA Form using the SSAUpdater.
#include "llvm/Transforms/Utils/SSAUpdater.h"
Public Member Functions
LoadAndStorePromoter (ArrayRef< const Instruction * > Insts, SSAUpdater &S, StringRef Name=StringRef())
virtual ~LoadAndStorePromoter ()=default
void run (const SmallVectorImpl< Instruction * > &Insts)
This does the promotion.
virtual bool isInstInList (Instruction *I, const SmallVectorImpl< Instruction * > &Insts) const
Return true if the specified instruction is in the Inst list.
virtual void doExtraRewritesBeforeFinalDeletion ()
This hook is invoked after all the stores are found and inserted as available values.
virtual void replaceLoadWithValue (LoadInst *LI, Value *V) const
Clients can choose to implement this to get notified right before a load is RAUW'd another value.
virtual void instructionDeleted (Instruction *I) const
Called before each instruction is deleted.
virtual void updateDebugInfo (Instruction *I) const
Called to update debug info associated with the instruction.
Protected Attributes
SSAUpdater & SSA
Detailed Description
Helper class for promoting a collection of loads and stores into SSA Form using the SSAUpdater.
This handles complexities that SSAUpdater doesn't, such as multiple loads and stores in one block.
Clients of this class are expected to subclass this and implement the virtual methods.
Definition at line 136 of file SSAUpdater.h.
Constructor & Destructor Documentation
LoadAndStorePromoter()
LoadAndStorePromoter::LoadAndStorePromoter (ArrayRef< const Instruction * > Insts, SSAUpdater & S, StringRef Name = StringRef())
Definition at line 321 of file SSAUpdater.cpp.
References llvm::ArrayRef< T >::empty(), llvm::StringRef::empty(), llvm::Value::getName(), llvm::Value::getType(), llvm::SSAUpdater::Initialize(), and SSA.
~LoadAndStorePromoter()
virtual llvm::LoadAndStorePromoter::~LoadAndStorePromoter () virtual default
Member Function Documentation
doExtraRewritesBeforeFinalDeletion()
virtual void llvm::LoadAndStorePromoter::doExtraRewritesBeforeFinalDeletion () inline virtual
This hook is invoked after all the stores are found and inserted as available values.
Definition at line 161 of file SSAUpdater.h.
Referenced by run().
instructionDeleted()
virtual void llvm::LoadAndStorePromoter::instructionDeleted (Instruction * I) const inline virtual
Called before each instruction is deleted.
Definition at line 168 of file SSAUpdater.h.
Referenced by run().
isInstInList()
bool LoadAndStorePromoter::isInstInList (Instruction * I, const SmallVectorImpl< Instruction * > & Insts) const virtual
Return true if the specified instruction is in the Inst list.
The Insts list is the one passed into the constructor. Clients should implement this with a more efficient version if possible.
Definition at line 476 of file SSAUpdater.cpp.
References I, and llvm::is_contained().
Referenced by run().
replaceLoadWithValue()
virtual void llvm::LoadAndStorePromoter::replaceLoadWithValue (LoadInst * LI, Value * V) const inline virtual
Clients can choose to implement this to get notified right before a load is RAUW'd another value.
Definition at line 165 of file SSAUpdater.h.
Referenced by run().
run()
void LoadAndStorePromoter::run (const SmallVectorImpl< Instruction * > & Insts)
This does the promotion.
Insts is a list of loads and stores to promote, and Name is the basename for the PHIs to insert. After this is complete, the loads and stores are removed from the code.
Definition at line 337 of file SSAUpdater.cpp.
References llvm::SSAUpdater::AddAvailableValue(), assert(), BB, llvm::SmallVectorImpl< T >::clear(), llvm::TinyPtrVector< EltTy >::clear(), doExtraRewritesBeforeFinalDeletion(), llvm::TinyPtrVector< EltTy >::empty(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), llvm::UndefValue::get(), llvm::Value::getType(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), I, instructionDeleted(), isInstInList(), llvm::Value::replaceAllUsesWith(), replaceLoadWithValue(), SI, llvm::TinyPtrVector< EltTy >::size(), SSA, updateDebugInfo(), and llvm::Value::use_empty().
updateDebugInfo()
virtual void llvm::LoadAndStorePromoter::updateDebugInfo (Instruction * I) const inline virtual
Called to update debug info associated with the instruction.
Definition at line 171 of file SSAUpdater.h.
Referenced by run().
Member Data Documentation
SSA
SSAUpdater& llvm::LoadAndStorePromoter::SSA protected
Definition at line 138 of file SSAUpdater.h.
Referenced by LoadAndStorePromoter(), and run().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/SSAUpdater.h
lib/Transforms/Utils/SSAUpdater.cpp