LLVM: llvm::orc::remote::OrcRemoteTargetClient::RPCMMAlloc Class Reference
llvm::orc::remote::OrcRemoteTargetClient::RPCMMAlloc Class Reference
#include "llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h"
Public Member Functions
MutableArrayRef< char > getWorkingMemory (ProtectionFlags Seg) override
Should return the address of linker working memory for the segment with the given protection flags.
JITTargetAddress getTargetMemory (ProtectionFlags Seg) override
Should return the final address in the target process where the segment will reside.
void finalizeAsync (FinalizeContinuation OnFinalize) override
Should transfer from working memory to target memory, and release working memory.
Error deallocate () override
Should deallocate target memory.
Public Member Functions inherited from llvm::jitlink::JITLinkMemoryManager::Allocation
virtual ~Allocation ()
Error finalize ()
Calls finalizeAsync and waits for completion.
Static Public Member Functions
static Expected< std::unique_ptr< RPCMMAlloc > > Create (OrcRemoteTargetClient &Client, ResourceIdMgr::ResourceId Id, const SegmentsRequestMap &Request)
Additional Inherited Members
Public Types inherited from llvm::jitlink::JITLinkMemoryManager::Allocation
using FinalizeContinuation = std::function< void(Error)>
Detailed Description
Definition at line 333 of file OrcRemoteTargetClient.h.
Member Function Documentation
Create()
static Expected<std::unique_ptr<RPCMMAlloc> > llvm::orc::remote::OrcRemoteTargetClient::RPCMMAlloc::Create (OrcRemoteTargetClient & Client, ResourceIdMgr::ResourceId Id, const SegmentsRequestMap & Request) inline static
Definition at line 346 of file OrcRemoteTargetClient.h.
Referenced by llvm::orc::remote::OrcRemoteTargetClient::RemoteJITLinkMemoryManager::allocate().
deallocate()
Error llvm::orc::remote::OrcRemoteTargetClient::RPCMMAlloc::deallocate () inline override virtual
Should deallocate target memory.
Implements llvm::jitlink::JITLinkMemoryManager::Allocation.
Definition at line 375 of file OrcRemoteTargetClient.h.
References llvm::errorCodeToError(), and llvm::sys::Memory::releaseMappedMemory().
finalizeAsync()
void llvm::orc::remote::OrcRemoteTargetClient::RPCMMAlloc::finalizeAsync (FinalizeContinuation OnFinalize) inline override virtual
Should transfer from working memory to target memory, and release working memory.
Implements llvm::jitlink::JITLinkMemoryManager::Allocation.
Definition at line 370 of file OrcRemoteTargetClient.h.
getTargetMemory()
JITTargetAddress llvm::orc::remote::OrcRemoteTargetClient::RPCMMAlloc::getTargetMemory (ProtectionFlags Seg) inline override virtual
Should return the final address in the target process where the segment will reside.
Implements llvm::jitlink::JITLinkMemoryManager::Allocation.
Definition at line 365 of file OrcRemoteTargetClient.h.
References assert(), base, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), and llvm::pointerToJITTargetAddress().
getWorkingMemory()
MutableArrayRef<char> llvm::orc::remote::OrcRemoteTargetClient::RPCMMAlloc::getWorkingMemory (ProtectionFlags Seg) inline override virtual
Should return the address of linker working memory for the segment with the given protection flags.
Implements llvm::jitlink::JITLinkMemoryManager::Allocation.
Definition at line 359 of file OrcRemoteTargetClient.h.
References assert(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h