LLVM: llvm::orc::EPCEHFrameRegistrar Class Reference
llvm::orc::EPCEHFrameRegistrar Class Reference
Register/Deregisters EH frames in a remote process via a ExecutorProcessControl instance.
#include "llvm/ExecutionEngine/Orc/EPCEHFrameRegistrar.h"
Public Member Functions
EPCEHFrameRegistrar (ExecutionSession &ES, JITTargetAddress RegisterEHFrameWrapperFnAddr, JITTargetAddress DeregisterEHFRameWrapperFnAddr)
Create a EPCEHFrameRegistrar with the given ExecutorProcessControl object and registration/deregistration function addresses.
Error registerEHFrames (JITTargetAddress EHFrameSectionAddr, size_t EHFrameSectionSize) override
Error deregisterEHFrames (JITTargetAddress EHFrameSectionAddr, size_t EHFrameSectionSize) override
Public Member Functions inherited from llvm::jitlink::EHFrameRegistrar
virtual ~EHFrameRegistrar ()
Static Public Member Functions
static Expected< std::unique_ptr< EPCEHFrameRegistrar > > Create (ExecutionSession &ES)
Create from a ExecutorProcessControl instance alone.
Detailed Description
Register/Deregisters EH frames in a remote process via a ExecutorProcessControl instance.
Definition at line 25 of file EPCEHFrameRegistrar.h.
Constructor & Destructor Documentation
EPCEHFrameRegistrar()
llvm::orc::EPCEHFrameRegistrar::EPCEHFrameRegistrar (ExecutionSession & ES, JITTargetAddress RegisterEHFrameWrapperFnAddr, JITTargetAddress DeregisterEHFRameWrapperFnAddr) inline
Create a EPCEHFrameRegistrar with the given ExecutorProcessControl object and registration/deregistration function addresses.
Definition at line 35 of file EPCEHFrameRegistrar.h.
Member Function Documentation
Create()
Expected< std::unique_ptr< EPCEHFrameRegistrar > > llvm::orc::EPCEHFrameRegistrar::Create (ExecutionSession & ES) static
Create from a ExecutorProcessControl instance alone.
This will use the EPC's lookupSymbols method to find the registration/deregistration funciton addresses by name.
Definition at line 20 of file EPCEHFrameRegistrar.cpp.
References llvm::orc::SymbolLookupSet::add(), assert(), llvm::orc::ExecutionSession::getExecutorProcessControl(), llvm::orc::ExecutorProcessControl::loadDylib(), and llvm::size().
deregisterEHFrames()
Error llvm::orc::EPCEHFrameRegistrar::deregisterEHFrames (JITTargetAddress EHFrameSectionAddr, size_t EHFrameSectionSize) override virtual
Implements llvm::jitlink::EHFrameRegistrar.
Definition at line 65 of file EPCEHFrameRegistrar.cpp.
registerEHFrames()
Error llvm::orc::EPCEHFrameRegistrar::registerEHFrames (JITTargetAddress EHFrameSectionAddr, size_t EHFrameSectionSize) override virtual
Implements llvm::jitlink::EHFrameRegistrar.
Definition at line 58 of file EPCEHFrameRegistrar.cpp.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/EPCEHFrameRegistrar.h
lib/ExecutionEngine/Orc/EPCEHFrameRegistrar.cpp