LLVM: llvm::orc::ExecutorAddress Class Reference
llvm::orc::ExecutorAddress Class Reference
Represents an address in the executor process.
#include "llvm/ExecutionEngine/Orc/Shared/ExecutorAddress.h"
Public Member Functions
ExecutorAddress ()=default
ExecutorAddress (uint64_t Addr)
template<typename T >
T toPtr () const
Cast this ExecutorAddress to a pointer of the given type.
uint64_t getValue () const
void setValue (uint64_t Addr)
bool isNull () const
operator bool () const
ExecutorAddress & operator++ ()
ExecutorAddress & operator-- ()
ExecutorAddress operator++ (int)
ExecutorAddress operator-- (int)
ExecutorAddress & operator+= (const ExecutorAddrDiff Delta)
ExecutorAddress & operator-= (const ExecutorAddrDiff Delta)
Static Public Member Functions
template<typename T >
static ExecutorAddress fromPtr (T *Value)
Create an ExecutorAddress from the given pointer.
Friends
bool operator== (const ExecutorAddress &LHS, const ExecutorAddress &RHS)
bool operator!= (const ExecutorAddress &LHS, const ExecutorAddress &RHS)
bool operator< (const ExecutorAddress &LHS, const ExecutorAddress &RHS)
bool operator<= (const ExecutorAddress &LHS, const ExecutorAddress &RHS)
bool operator> (const ExecutorAddress &LHS, const ExecutorAddress &RHS)
bool operator>= (const ExecutorAddress &LHS, const ExecutorAddress &RHS)
Detailed Description
Represents an address in the executor process.
Definition at line 37 of file ExecutorAddress.h.
Constructor & Destructor Documentation
ExecutorAddress() [1/2]
llvm::orc::ExecutorAddress::ExecutorAddress () default
Referenced by fromPtr(), operator++(), and operator--().
ExecutorAddress() [2/2]
llvm::orc::ExecutorAddress::ExecutorAddress (uint64_t Addr) inline explicit
Definition at line 40 of file ExecutorAddress.h.
References Addr.
Member Function Documentation
fromPtr()
template<typename T > static ExecutorAddress llvm::orc::ExecutorAddress::fromPtr (T * Value) inline static
Create an ExecutorAddress from the given pointer.
Warning: This should only be used when JITing in-process.
Definition at line 44 of file ExecutorAddress.h.
References ExecutorAddress().
Referenced by llvm::orc::EPCDebugObjectRegistrar::registerDebugObject(), and llvm::orc::SelfExecutorProcessControl::SelfExecutorProcessControl().
getValue()
uint64_t llvm::orc::ExecutorAddress::getValue () const inline
Definition at line 59 of file ExecutorAddress.h.
Referenced by llvm::orc::operator+(), llvm::orc::operator-(), llvm::orc::shared::SPSSerializationTraits< SPSExecutorAddress, ExecutorAddress >::serialize(), and llvm::orc::shared::SPSSerializationTraits< SPSExecutorAddress, ExecutorAddress >::size().
isNull()
bool llvm::orc::ExecutorAddress::isNull () const inline
Definition at line 61 of file ExecutorAddress.h.
operator bool()
llvm::orc::ExecutorAddress::operator bool () const inline explicit
Definition at line 63 of file ExecutorAddress.h.
operator++() [1/2]
ExecutorAddress& llvm::orc::ExecutorAddress::operator++ () inline
Definition at line 95 of file ExecutorAddress.h.
operator++() [2/2]
ExecutorAddress llvm::orc::ExecutorAddress::operator++ (int) inline
Definition at line 103 of file ExecutorAddress.h.
References ExecutorAddress().
operator+=()
ExecutorAddress& llvm::orc::ExecutorAddress::operator+= (const ExecutorAddrDiff Delta) inline
Definition at line 106 of file ExecutorAddress.h.
References llvm::orc::ExecutorAddrDiff::getValue().
operator--() [1/2]
ExecutorAddress& llvm::orc::ExecutorAddress::operator-- () inline
Definition at line 99 of file ExecutorAddress.h.
operator--() [2/2]
ExecutorAddress llvm::orc::ExecutorAddress::operator-- (int) inline
Definition at line 104 of file ExecutorAddress.h.
References ExecutorAddress().
operator-=()
ExecutorAddress& llvm::orc::ExecutorAddress::operator-= (const ExecutorAddrDiff Delta) inline
Definition at line 111 of file ExecutorAddress.h.
References llvm::orc::ExecutorAddrDiff::getValue().
setValue()
void llvm::orc::ExecutorAddress::setValue (uint64_t Addr) inline
Definition at line 60 of file ExecutorAddress.h.
References Addr.
toPtr()
template<typename T > T llvm::orc::ExecutorAddress::toPtr () const inline
Cast this ExecutorAddress to a pointer of the given type.
Warning: This should only be esude when JITing in-process.
Definition at line 51 of file ExecutorAddress.h.
References assert(), and T.
Friends And Related Function Documentation
operator!=
bool operator!= (const ExecutorAddress & LHS, const ExecutorAddress & RHS) friend
Definition at line 70 of file ExecutorAddress.h.
operator<
bool operator< (const ExecutorAddress & LHS, const ExecutorAddress & RHS) friend
Definition at line 75 of file ExecutorAddress.h.
operator<=
bool operator<= (const ExecutorAddress & LHS, const ExecutorAddress & RHS) friend
Definition at line 80 of file ExecutorAddress.h.
operator==
bool operator== (const ExecutorAddress & LHS, const ExecutorAddress & RHS) friend
Definition at line 65 of file ExecutorAddress.h.
operator>
bool operator> (const ExecutorAddress & LHS, const ExecutorAddress & RHS) friend
Definition at line 85 of file ExecutorAddress.h.
operator>=
bool operator>= (const ExecutorAddress & LHS, const ExecutorAddress & RHS) friend
Definition at line 90 of file ExecutorAddress.h.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/ExecutorAddress.h