LLVM: llvm::ContextTrieNode Class Reference
llvm::ContextTrieNode Class Reference
#include "llvm/Transforms/IPO/SampleContextTracker.h"
Public Member Functions
ContextTrieNode (ContextTrieNode *Parent=nullptr, StringRef FName=StringRef(), FunctionSamples *FSamples=nullptr, LineLocation CallLoc={0, 0})
ContextTrieNode * getChildContext (const LineLocation &CallSite, StringRef CalleeName)
ContextTrieNode * getHottestChildContext (const LineLocation &CallSite)
ContextTrieNode * getOrCreateChildContext (const LineLocation &CallSite, StringRef CalleeName, bool AllowCreate=true)
ContextTrieNode & moveToChildContext (const LineLocation &CallSite, ContextTrieNode &&NodeToMove, StringRef ContextStrToRemove, bool DeleteNode=true)
void removeChildContext (const LineLocation &CallSite, StringRef CalleeName)
std::map< uint32_t, ContextTrieNode > & getAllChildContext ()
StringRef getFuncName () const
FunctionSamples * getFunctionSamples () const
void setFunctionSamples (FunctionSamples *FSamples)
LineLocation getCallSiteLoc () const
ContextTrieNode * getParentContext () const
void setParentContext (ContextTrieNode *Parent)
void dump ()
Detailed Description
Definition at line 36 of file SampleContextTracker.h.
Constructor & Destructor Documentation
ContextTrieNode()
llvm::ContextTrieNode::ContextTrieNode (ContextTrieNode * Parent = nullptr, StringRef FName = StringRef(), FunctionSamples * FSamples = nullptr, LineLocation CallLoc = {0, 0}) inline
Definition at line 38 of file SampleContextTracker.h.
Member Function Documentation
dump()
void llvm::ContextTrieNode::dump ()
Definition at line 140 of file SampleContextTracker.cpp.
References llvm::dbgs().
getAllChildContext()
std::map< uint32_t, ContextTrieNode > & llvm::ContextTrieNode::getAllChildContext ()
Definition at line 116 of file SampleContextTracker.cpp.
Referenced by llvm::SampleContextTracker::getIndirectCalleeContextSamplesFor(), llvm::sampleprof::ProfiledCallGraph::ProfiledCallGraph(), and llvm::SampleContextTracker::promoteMergeContextSamplesTree().
getCallSiteLoc()
LineLocation llvm::ContextTrieNode::getCallSiteLoc () const
Definition at line 130 of file SampleContextTracker.cpp.
Referenced by llvm::SampleContextTracker::getIndirectCalleeContextSamplesFor(), and llvm::SampleContextTracker::promoteMergeContextSamplesTree().
getChildContext()
ContextTrieNode * llvm::ContextTrieNode::getChildContext (const LineLocation & CallSite, StringRef CalleeName)
Definition at line 30 of file SampleContextTracker.cpp.
References llvm::StringRef::empty().
Referenced by llvm::SampleContextTracker::promoteMergeContextSamplesTree().
getFuncName()
StringRef llvm::ContextTrieNode::getFuncName () const
Definition at line 120 of file SampleContextTracker.cpp.
Referenced by llvm::sampleprof::ProfiledCallGraph::ProfiledCallGraph().
getFunctionSamples()
FunctionSamples * llvm::ContextTrieNode::getFunctionSamples () const
Definition at line 122 of file SampleContextTracker.cpp.
Referenced by llvm::SampleContextTracker::getCalleeContextSamplesFor(), llvm::SampleContextTracker::getContextSamplesFor(), getHottestChildContext(), llvm::SampleContextTracker::getIndirectCalleeContextSamplesFor(), llvm::SampleContextTracker::promoteMergeContextSamplesTree(), and llvm::SampleContextTracker::SampleContextTracker().
getHottestChildContext()
ContextTrieNode * llvm::ContextTrieNode::getHottestChildContext (const LineLocation & CallSite)
Definition at line 43 of file SampleContextTracker.cpp.
References getFunctionSamples(), and llvm::sampleprof::FunctionSamples::getTotalSamples().
getOrCreateChildContext()
ContextTrieNode * llvm::ContextTrieNode::getOrCreateChildContext (const LineLocation & CallSite, StringRef CalleeName, bool AllowCreate = true)
Definition at line 161 of file SampleContextTracker.cpp.
References assert().
getParentContext()
ContextTrieNode * llvm::ContextTrieNode::getParentContext () const
Definition at line 132 of file SampleContextTracker.cpp.
Referenced by llvm::SampleContextTracker::getContextSamplesFor(), and moveToChildContext().
moveToChildContext()
ContextTrieNode & llvm::ContextTrieNode::moveToChildContext (const LineLocation & CallSite, ContextTrieNode && NodeToMove, StringRef ContextStrToRemove, bool DeleteNode = true)
Definition at line 65 of file SampleContextTracker.cpp.
References assert(), getParentContext(), and setParentContext().
removeChildContext()
void llvm::ContextTrieNode::removeChildContext (const LineLocation & CallSite, StringRef CalleeName)
Definition at line 109 of file SampleContextTracker.cpp.
setFunctionSamples()
void llvm::ContextTrieNode::setFunctionSamples (FunctionSamples * FSamples)
Definition at line 126 of file SampleContextTracker.cpp.
Referenced by llvm::SampleContextTracker::SampleContextTracker().
setParentContext()
void llvm::ContextTrieNode::setParentContext (ContextTrieNode * Parent)
Definition at line 136 of file SampleContextTracker.cpp.
Referenced by moveToChildContext().
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/SampleContextTracker.h
lib/Transforms/IPO/SampleContextTracker.cpp