LLVM: llvm::LinearPolySize< LeafTy > Class Template Reference
llvm::LinearPolySize< LeafTy > Class Template Reference
LinearPolySize is a base class to represent sizes.
#include "llvm/Support/TypeSize.h"
Public Types
enum Dims : unsigned { FixedDim = 0, ScalableDim = 1 }
using ScalarTy = typename UnivariateLinearPolyBase< LeafTy >::ScalarTy
Public Types inherited from llvm::UnivariateLinearPolyBase< LeafTy >
using ScalarTy = typename LinearPolyBaseTypeTraits< LeafTy >::ScalarTy
Public Member Functions
ScalarTy getKnownMinValue () const
Returns the minimum value this size can represent.
bool isScalable () const
Returns whether the size is scaled by a runtime quantity (vscale).
bool isKnownEven () const
A return value of true indicates we know at compile time that the number of elements (vscale * Min) is definitely even.
bool isKnownMultipleOf (ScalarTy RHS) const
This function tells the caller whether the element count is known at compile time to be a multiple of the scalar value RHS.
ScalarTy getFixedValue () const
LeafTy divideCoefficientBy (ScalarTy RHS) const
We do not provide the '/' operator here because division for polynomial types does not work in the same way as for normal integer types.
LeafTy coefficientNextPowerOf2 () const
void print (raw_ostream &OS) const
Printing function.
Public Member Functions inherited from llvm::UnivariateLinearPolyBase< LeafTy >
bool operator== (const UnivariateLinearPolyBase &RHS) const
bool operator!= (const UnivariateLinearPolyBase &RHS) const
bool isZero () const
bool isNonZero () const
operator bool () const
ScalarTy getValue () const
ScalarTy getValue (unsigned Dim) const
LeafTy getWithIncrement (ScalarTy RHS) const
Add RHS to the value at the univariate dimension.
LeafTy getWithDecrement (ScalarTy RHS) const
Subtract RHS from the value at the univariate dimension.
Static Public Member Functions
static LeafTy getFixed (ScalarTy MinVal)
static LeafTy getScalable (ScalarTy MinVal)
static LeafTy get (ScalarTy MinVal, bool Scalable)
static LeafTy getNull ()
static bool isKnownLT (const LinearPolySize &LHS, const LinearPolySize &RHS)
static bool isKnownGT (const LinearPolySize &LHS, const LinearPolySize &RHS)
static bool isKnownLE (const LinearPolySize &LHS, const LinearPolySize &RHS)
static bool isKnownGE (const LinearPolySize &LHS, const LinearPolySize &RHS)
Protected Member Functions
LinearPolySize (ScalarTy MinVal, Dims D)
LinearPolySize (const UnivariateLinearPolyBase< LeafTy > &V)
Protected Member Functions inherited from llvm::UnivariateLinearPolyBase< LeafTy >
UnivariateLinearPolyBase (ScalarTy Val, unsigned UnivariateDim)
Friends
class UnivariateLinearPolyBase< LeafTy >
Additional Inherited Members
Static Public Attributes inherited from llvm::UnivariateLinearPolyBase< LeafTy >
static constexpr auto Dimensions = LinearPolyBaseTypeTraits<LeafTy>::Dimensions
Protected Attributes inherited from llvm::UnivariateLinearPolyBase< LeafTy >
ScalarTy Value
unsigned UnivariateDim
Detailed Description
template<typename LeafTy>
class llvm::LinearPolySize< LeafTy >
LinearPolySize is a base class to represent sizes.
It is either fixed-sized or it is scalable-sized, but it cannot be both.
Definition at line 265 of file TypeSize.h.
Member Typedef Documentation
ScalarTy
template<typename LeafTy > using llvm::LinearPolySize< LeafTy >::ScalarTy = typename UnivariateLinearPolyBase<LeafTy>::ScalarTy
Definition at line 272 of file TypeSize.h.
Member Enumeration Documentation
Dims
template<typename LeafTy > enum llvm::LinearPolySize::Dims : unsigned
Enumerator
FixedDim
ScalableDim
Definition at line 273 of file TypeSize.h.
Constructor & Destructor Documentation
LinearPolySize() [1/2]
template<typename LeafTy > llvm::LinearPolySize< LeafTy >::LinearPolySize (ScalarTy MinVal, Dims D) inline protected
Definition at line 276 of file TypeSize.h.
Referenced by llvm::LinearPolySize< TypeSize >::get(), llvm::LinearPolySize< TypeSize >::getFixed(), and llvm::LinearPolySize< TypeSize >::getScalable().
LinearPolySize() [2/2]
template<typename LeafTy > llvm::LinearPolySize< LeafTy >::LinearPolySize (const UnivariateLinearPolyBase< LeafTy > & V) inline protected
Definition at line 279 of file TypeSize.h.
Member Function Documentation
coefficientNextPowerOf2()
template<typename LeafTy > LeafTy llvm::LinearPolySize< LeafTy >::coefficientNextPowerOf2 () const inline
Definition at line 366 of file TypeSize.h.
Referenced by llvm::TargetLoweringBase::getVectorTypeBreakdown().
divideCoefficientBy()
template<typename LeafTy > LeafTy llvm::LinearPolySize< LeafTy >::divideCoefficientBy (ScalarTy RHS) const inline
We do not provide the '/' operator here because division for polynomial types does not work in the same way as for normal integer types.
We can only divide the minimum value (or coefficient) by RHS, which is not the same as (Min * Vscale) / RHS The caller is recommended to use this function in combination with isKnownMultipleOf(RHS), which lets the caller know if it's possible to perform a lossless divide by RHS.
Definition at line 361 of file TypeSize.h.
Referenced by llvm::LegalizerHelper::fewerElementsVectorMulo(), llvm::LegalizerHelper::fewerElementsVectorSelect(), llvm::LegalizerHelper::fewerElementsVectorShuffle(), getHalfSizedType(), llvm::getLCMType(), llvm::TargetLoweringBase::getVectorTypeBreakdown(), and getVectorTypeBreakdownMVT().
get()
template<typename LeafTy > static LeafTy llvm::LinearPolySize< LeafTy >::get (ScalarTy MinVal, bool Scalable) inline static
Definition at line 290 of file TypeSize.h.
Referenced by llvm::LinearPolySize< TypeSize >::coefficientNextPowerOf2(), llvm::LinearPolySize< TypeSize >::divideCoefficientBy(), and llvm::LinearPolySize< TypeSize >::getNull().
getFixed()
template<typename LeafTy > static LeafTy llvm::LinearPolySize< LeafTy >::getFixed (ScalarTy MinVal) inline static
Definition at line 284 of file TypeSize.h.
getFixedValue()
template<typename LeafTy > ScalarTy llvm::LinearPolySize< LeafTy >::getFixedValue () const inline
Definition at line 313 of file TypeSize.h.
Referenced by llvm::LoopVectorizationCostModel::computeMaxVF(), llvm::SelectionDAG::FoldConstantVectorArithmetic(), llvm::AArch64TTIImpl::getMaxNumElements(), llvm::VFABI::mangleTLIVectorName(), llvm::TargetLowering::SimplifyDemandedBits(), and llvm::TargetLowering::SimplifyDemandedVectorElts().
getKnownMinValue()
template<typename LeafTy > ScalarTy llvm::LinearPolySize< LeafTy >::getKnownMinValue () const inline
Returns the minimum value this size can represent.
Definition at line 297 of file TypeSize.h.
Referenced by llvm::LoopVectorizeHints::allowReordering(), llvm::InnerLoopVectorizer::buildScalarSteps(), llvm::VPIntrinsic::canIgnoreVectorLengthParam(), llvm::LinearPolySize< TypeSize >::coefficientNextPowerOf2(), llvm::TargetLoweringBase::computeRegisterProperties(), llvm::EpilogueVectorizerMainLoop::createEpilogueVectorizedLoopSkeleton(), llvm::EpilogueVectorizerEpilogueLoop::createEpilogueVectorizedLoopSkeleton(), createStepForVF(), llvm::IRBuilderBase::CreateVectorSplat(), llvm::RISCVTargetLowering::decomposeSubvectorInsertExtractToSubRegs(), llvm::LinearPolySize< TypeSize >::divideCoefficientBy(), llvm::EpilogueVectorizerMainLoop::emitMinimumIterationCountCheck(), llvm::EpilogueVectorizerEpilogueLoop::emitMinimumVectorEpilogueIterCountCheck(), llvm::VPRegionBlock::execute(), llvm::VPReplicateRecipe::execute(), llvm::VPWidenCanonicalIVRecipe::execute(), foldBitcastExtElt(), llvm::VectorType::get(), llvm::VPTransformState::get(), llvm::VPLane::getAsRuntimeExpr(), getCopyFromPartsVector(), llvm::SelectionDAG::GetDependentSplitDestVTs(), llvm::LinearPolySize< TypeSize >::getFixedValue(), llvm::DenseMapInfo< ElementCount >::getHashValue(), llvm::VPLane::getLastLaneForVF(), llvm::RISCVTargetLowering::getLMUL(), getMangledTypeStr(), llvm::AArch64TTIImpl::getMaxNumElements(), llvm::VPLane::getNumCachedLanes(), llvm::LLT::getNumElements(), llvm::InnerLoopVectorizer::getOrCreateVectorTripCount(), getPackedSVEVectorVT(), getPackedVectorTypeFromPredicateType(), llvm::MVT::getPow2VectorType(), llvm::EVT::getPow2VectorType(), llvm::Type::getPrimitiveSizeInBits(), llvm::getRuntimeVF(), llvm::ShuffleVectorInst::getShuffleMask(), llvm::ConstantVector::getSplat(), llvm::DataLayout::getTypeSizeInBits(), llvm::LoopVectorizationCostModel::getVectorCallCost(), llvm::EVT::getVectorMinNumElements(), llvm::TargetLoweringBase::getVectorTypeBreakdown(), getVectorTypeBreakdownMVT(), llvm::MVT::getVectorVT(), instCombineSVETBL(), llvm::VFRange::isEmpty(), llvm::LinearPolySize< TypeSize >::isKnownEven(), llvm::LinearPolySize< TypeSize >::isKnownGE(), llvm::LinearPolySize< TypeSize >::isKnownGT(), llvm::LinearPolySize< TypeSize >::isKnownLE(), llvm::LinearPolySize< TypeSize >::isKnownLT(), llvm::LinearPolySize< TypeSize >::isKnownMultipleOf(), llvm::VPLane::mapToCacheIndex(), llvm::ElementCountComparator::operator()(), llvm::AArch64TargetLowering::PerformDAGCombine(), llvm::LoopVectorizationPlanner::plan(), llvm::LoopVectorizationPlanner::planInVPlanNativePath(), llvm::LinearPolySize< TypeSize >::print(), llvm::EpilogueVectorizerMainLoop::printDebugTracesAtStart(), llvm::EpilogueVectorizerEpilogueLoop::printDebugTracesAtStart(), llvm::LoopVectorizePass::processLoop(), llvm::LoopVectorizationCostModel::selectInterleaveCount(), llvm::LoopVectorizationCostModel::selectVectorizationFactor(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), llvm::InnerLoopVectorizer::setDebugLocFromInst(), SimplifyShuffleVectorInst(), llvm::VFABI::tryDemangleForVFABI(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), llvm::VFRange::VFRange(), llvm::InstCombinerImpl::visitExtractElementInst(), llvm::InnerLoopVectorizer::widenCallInstruction(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
getNull()
template<typename LeafTy > static LeafTy llvm::LinearPolySize< LeafTy >::getNull () inline static
Definition at line 294 of file TypeSize.h.
getScalable()
template<typename LeafTy > static LeafTy llvm::LinearPolySize< LeafTy >::getScalable (ScalarTy MinVal) inline static
Definition at line 287 of file TypeSize.h.
isKnownEven()
template<typename LeafTy > bool llvm::LinearPolySize< LeafTy >::isKnownEven () const inline
A return value of true indicates we know at compile time that the number of elements (vscale * Min) is definitely even.
However, returning false does not guarantee that the total number of elements is odd.
Definition at line 303 of file TypeSize.h.
isKnownGE()
template<typename LeafTy > static bool llvm::LinearPolySize< LeafTy >::isKnownGE (const LinearPolySize< LeafTy > & LHS, const LinearPolySize< LeafTy > & RHS) inline static
Definition at line 347 of file TypeSize.h.
isKnownGT()
template<typename LeafTy > static bool llvm::LinearPolySize< LeafTy >::isKnownGT (const LinearPolySize< LeafTy > & LHS, const LinearPolySize< LeafTy > & RHS) inline static
Definition at line 335 of file TypeSize.h.
isKnownLE()
template<typename LeafTy > static bool llvm::LinearPolySize< LeafTy >::isKnownLE (const LinearPolySize< LeafTy > & LHS, const LinearPolySize< LeafTy > & RHS) inline static
Definition at line 341 of file TypeSize.h.
isKnownLT()
template<typename LeafTy > static bool llvm::LinearPolySize< LeafTy >::isKnownLT (const LinearPolySize< LeafTy > & LHS, const LinearPolySize< LeafTy > & RHS) inline static
Definition at line 329 of file TypeSize.h.
isKnownMultipleOf()
template<typename LeafTy > bool llvm::LinearPolySize< LeafTy >::isKnownMultipleOf (ScalarTy RHS) const inline
This function tells the caller whether the element count is known at compile time to be a multiple of the scalar value RHS.
Definition at line 306 of file TypeSize.h.
Referenced by getHalfSizedType(), llvm::EVT::isByteSized(), llvm::LLT::isByteSized(), and llvm::MVT::isByteSized().
isScalable()
template<typename LeafTy > bool llvm::LinearPolySize< LeafTy >::isScalable () const inline
Returns whether the size is scaled by a runtime quantity (vscale).
Definition at line 299 of file TypeSize.h.
Referenced by llvm::InnerLoopVectorizer::buildScalarSteps(), llvm::VPIntrinsic::canIgnoreVectorLengthParam(), llvm::LinearPolySize< TypeSize >::coefficientNextPowerOf2(), llvm::LoopVectorizationCostModel::collectInstsToScalarize(), computeKnownBitsFromOperator(), llvm::TargetLoweringBase::computeRegisterProperties(), llvm::SelectionDAG::CreateStackTemporary(), createStepForVF(), llvm::LinearPolySize< TypeSize >::divideCoefficientBy(), llvm::VPRegionBlock::execute(), llvm::VPReplicateRecipe::execute(), llvm::VPWidenCanonicalIVRecipe::execute(), llvm::FixedScalableVFPair::FixedScalableVFPair(), foldBitcastExtElt(), llvm::SelectionDAG::FoldConstantVectorArithmetic(), llvm::AArch64TargetLowering::functionArgumentNeedsConsecutiveRegisters(), llvm::VectorType::get(), llvm::VPTransformState::get(), llvm::TargetTransformInfoImplBase::getCastInstrCost(), getCopyFromPartsVector(), llvm::SelectionDAG::GetDependentSplitDestVTs(), llvm::LinearPolySize< TypeSize >::getFixedValue(), llvm::DenseMapInfo< ElementCount >::getHashValue(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicInstrCost(), llvm::VPLane::getLastLaneForVF(), getMangledTypeStr(), llvm::AArch64TTIImpl::getMaxNumElements(), llvm::AArch64InstrInfo::getMemOperandWithOffsetWidth(), llvm::VPLane::getNumCachedLanes(), llvm::InnerLoopVectorizer::getOrCreateVectorTripCount(), llvm::MVT::getPow2VectorType(), llvm::EVT::getPow2VectorType(), llvm::Type::getPrimitiveSizeInBits(), llvm::getRuntimeVF(), llvm::ShuffleVectorInst::getShuffleMask(), llvm::LLT::getSizeInBytes(), llvm::ConstantVector::getSplat(), llvm::EVT::getStoreSize(), llvm::MVT::getStoreSize(), llvm::DataLayout::getTypeStoreSize(), llvm::MVT::getVectorVT(), AAPointerInfoFloating::handleAccess(), llvm::VPRecipeBuilder::handleReplication(), llvm::InlineFunction(), llvm::isAArch64FrameOffsetLegal(), llvm::LinearPolySize< TypeSize >::isKnownGE(), llvm::LinearPolySize< TypeSize >::isKnownGT(), llvm::LinearPolySize< TypeSize >::isKnownLE(), llvm::LinearPolySize< TypeSize >::isKnownLT(), llvm::AArch64TTIImpl::isLegalToVectorizeReduction(), llvm::RISCVTTIImpl::isLegalToVectorizeReduction(), isLoadInvariantInLoop(), llvm::VFABI::mangleTLIVectorName(), llvm::VPLane::mapToCacheIndex(), llvm::ElementCountComparator::operator()(), llvm::LoopVectorizationPlanner::plan(), llvm::LoopVectorizationPlanner::planInVPlanNativePath(), llvm::LinearPolySize< TypeSize >::print(), replaceWithCallToVeclib(), llvm::LoopVectorizationCostModel::selectEpilogueVectorizationFactor(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifyDemandedVectorElts(), SimplifyShuffleVectorInst(), valueCoversEntireFragment(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), llvm::VFRange::VFRange(), llvm::InstCombinerImpl::visitExtractElementInst(), llvm::InnerLoopVectorizer::widenPHIInstruction(), and widenVectorToPartType().
print()
template<typename LeafTy > void llvm::LinearPolySize< LeafTy >::print (raw_ostream & OS) const inline
Printing function.
Definition at line 373 of file TypeSize.h.
Referenced by llvm::DiagnosticInfoOptimizationBase::Argument::Argument(), and llvm::operator<<().
Friends And Related Function Documentation
UnivariateLinearPolyBase< LeafTy >
template<typename LeafTy > friend class UnivariateLinearPolyBase< LeafTy > friend
Definition at line 244 of file TypeSize.h.
The documentation for this class was generated from the following file:
include/llvm/Support/TypeSize.h