LLVM: llvm::OrderedChangedData< IRData > Class Template Reference
llvm::OrderedChangedData< IRData > Class Template Reference
#include "llvm/Passes/StandardInstrumentations.h"
Public Member Functions
std::vector< std::string > & getOrder ()
const std::vector< std::string > & getOrder () const
StringMap< IRData > & getData ()
const StringMap< IRData > & getData () const
bool operator== (const OrderedChangedData< IRData > &That) const
Static Public Member Functions
static void report (const OrderedChangedData &Before, const OrderedChangedData &After, function_ref< void(const IRData *, const IRData *)> HandlePair)
Protected Attributes
std::vector< std::string > Order
StringMap< IRData > Data
Detailed Description
template<typename IRData>
class llvm::OrderedChangedData< IRData >
Definition at line 305 of file StandardInstrumentations.h.
Member Function Documentation
getData() [1/2]
template<typename IRData > StringMap<IRData>& llvm::OrderedChangedData< IRData >::getData () inline
Definition at line 312 of file StandardInstrumentations.h.
References llvm::OrderedChangedData< IRData >::Data.
Referenced by llvm::ChangedIRComparer::compare(), llvm::ChangedIRComparer::generateFunctionData(), llvm::OrderedChangedData< IRData >::operator==(), and llvm::OrderedChangedData< IRData >::report().
getData() [2/2]
template<typename IRData > const StringMap<IRData>& llvm::OrderedChangedData< IRData >::getData () const inline
Definition at line 313 of file StandardInstrumentations.h.
References llvm::OrderedChangedData< IRData >::Data.
getOrder() [1/2]
template<typename IRData > std::vector<std::string>& llvm::OrderedChangedData< IRData >::getOrder () inline
Definition at line 308 of file StandardInstrumentations.h.
References llvm::OrderedChangedData< IRData >::Order.
Referenced by llvm::ChangedIRComparer::generateFunctionData(), and llvm::OrderedChangedData< IRData >::report().
getOrder() [2/2]
template<typename IRData > const std::vector<std::string>& llvm::OrderedChangedData< IRData >::getOrder () const inline
Definition at line 309 of file StandardInstrumentations.h.
References llvm::OrderedChangedData< IRData >::Order.
operator==()
template<typename IRData > bool llvm::OrderedChangedData< IRData >::operator== (const OrderedChangedData< IRData > & That) const inline
Definition at line 315 of file StandardInstrumentations.h.
References llvm::OrderedChangedData< IRData >::Data, and llvm::OrderedChangedData< IRData >::getData().
report()
template<typename IRData > void OrderedChangedData::report (const OrderedChangedData< IRData > & Before, const OrderedChangedData< IRData > & After, function_ref< void(const IRData *, const IRData *)> HandlePair) static
Definition at line 569 of file StandardInstrumentations.cpp.
References llvm::OrderedChangedData< IRData >::getData(), llvm::OrderedChangedData< IRData >::getOrder(), and S.
Referenced by llvm::ChangedIRComparer::compare(), and llvm::ChangedIRComparer::handleFunctionCompare().
Member Data Documentation
Data
template<typename IRData > StringMap<IRData> llvm::OrderedChangedData< IRData >::Data protected
Definition at line 330 of file StandardInstrumentations.h.
Referenced by llvm::OrderedChangedData< IRData >::getData(), and llvm::OrderedChangedData< IRData >::operator==().
Order
template<typename IRData > std::vector<std::string> llvm::OrderedChangedData< IRData >::Order protected
Definition at line 329 of file StandardInstrumentations.h.
Referenced by llvm::OrderedChangedData< IRData >::getOrder().
The documentation for this class was generated from the following files:
include/llvm/Passes/StandardInstrumentations.h
lib/Passes/StandardInstrumentations.cpp