LLVM: llvm::orc::shared::FDRawByteChannel Class Reference
llvm::orc::shared::FDRawByteChannel Class Reference final
Serialization channel that reads from and writes from file descriptors.
#include "llvm/ExecutionEngine/Orc/Shared/FDRawByteChannel.h"
Public Member Functions
FDRawByteChannel (int InFD, int OutFD)
llvm::Error readBytes (char *Dst, unsigned Size) override
Read Size bytes from the stream into *Dst.
llvm::Error appendBytes (const char *Src, unsigned Size) override
Read size bytes from *Src and append them to the stream.
llvm::Error send () override
Flush the stream if possible.
Public Member Functions inherited from llvm::orc::shared::RawByteChannel
virtual ~RawByteChannel ()=default
template<typename FunctionIdT , typename SequenceIdT >
Error startSendMessage (const FunctionIdT &FnId, const SequenceIdT &SeqNo)
Notify the channel that we're starting a message send.
Error endSendMessage ()
Notify the channel that we're ending a message send.
template<typename FunctionIdT , typename SequenceNumberT >
Error startReceiveMessage (FunctionIdT &FnId, SequenceNumberT &SeqNo)
Notify the channel that we're starting a message receive.
Error endReceiveMessage ()
Notify the channel that we're ending a message receive.
std::mutex & getReadLock ()
Get the lock for stream reading.
std::mutex & getWriteLock ()
Get the lock for stream writing.
Detailed Description
Serialization channel that reads from and writes from file descriptors.
Definition at line 29 of file FDRawByteChannel.h.
Constructor & Destructor Documentation
FDRawByteChannel()
llvm::orc::shared::FDRawByteChannel::FDRawByteChannel (int InFD, int OutFD) inline
Definition at line 31 of file FDRawByteChannel.h.
Member Function Documentation
appendBytes()
llvm::Error llvm::orc::shared::FDRawByteChannel::appendBytes (const char * Src, unsigned Size) inline override virtual
Read size bytes from *Src and append them to the stream.
Implements llvm::orc::shared::RawByteChannel.
Definition at line 51 of file FDRawByteChannel.h.
References assert(), llvm::errorCodeToError(), llvm::Check::Size, llvm::Error::success(), and llvm::write().
readBytes()
llvm::Error llvm::orc::shared::FDRawByteChannel::readBytes (char * Dst, unsigned Size) inline override virtual
Read Size bytes from the stream into *Dst.
Implements llvm::orc::shared::RawByteChannel.
Definition at line 33 of file FDRawByteChannel.h.
References assert(), llvm::errorCodeToError(), llvm::support::endian::read(), llvm::Check::Size, and llvm::Error::success().
send()
llvm::Error llvm::orc::shared::FDRawByteChannel::send () inline override virtual
Flush the stream if possible.
Implements llvm::orc::shared::RawByteChannel.
Definition at line 69 of file FDRawByteChannel.h.
References llvm::Error::success().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/FDRawByteChannel.h