LLVM: llvm::orc::EPCDebugObjectRegistrar Class Reference
llvm::orc::EPCDebugObjectRegistrar Class Reference
Use ExecutorProcessControl to register debug objects locally or in a remote executor process.
#include "llvm/ExecutionEngine/Orc/EPCDebugObjectRegistrar.h"
Public Member Functions
EPCDebugObjectRegistrar (ExecutionSession &ES, JITTargetAddress RegisterFn)
Error registerDebugObject (sys::MemoryBlock TargetMem) override
Public Member Functions inherited from llvm::orc::DebugObjectRegistrar
virtual ~DebugObjectRegistrar ()
Detailed Description
Use ExecutorProcessControl to register debug objects locally or in a remote executor process.
Definition at line 41 of file EPCDebugObjectRegistrar.h.
Constructor & Destructor Documentation
EPCDebugObjectRegistrar()
llvm::orc::EPCDebugObjectRegistrar::EPCDebugObjectRegistrar (ExecutionSession & ES, JITTargetAddress RegisterFn) inline
Definition at line 43 of file EPCDebugObjectRegistrar.h.
Member Function Documentation
registerDebugObject()
Error llvm::orc::EPCDebugObjectRegistrar::registerDebugObject (sys::MemoryBlock TargetMem) override virtual
Implements llvm::orc::DebugObjectRegistrar.
Definition at line 45 of file EPCDebugObjectRegistrar.cpp.
References llvm::sys::MemoryBlock::allocatedSize(), llvm::sys::MemoryBlock::base(), llvm::orc::ExecutionSession::callSPSWrapper(), and llvm::orc::ExecutorAddress::fromPtr().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/EPCDebugObjectRegistrar.h
lib/ExecutionEngine/Orc/EPCDebugObjectRegistrar.cpp