LLVM: llvm::sampleprof::SampleContextTrimmer Class Reference
llvm::sampleprof::SampleContextTrimmer Class Reference
SampleContextTrimmer impelements helper functions to trim, merge cold context profiles.
#include "llvm/ProfileData/SampleProf.h"
Public Member Functions
SampleContextTrimmer (StringMap< FunctionSamples > &Profiles)
void trimAndMergeColdContextProfiles (uint64_t ColdCountThreshold, bool TrimColdContext, bool MergeColdContext, uint32_t ColdContextFrameLength)
void canonicalizeContextProfiles ()
Detailed Description
SampleContextTrimmer impelements helper functions to trim, merge cold context profiles.
It also supports context profile canonicalization to make sure ProfileMap's key is consistent with FunctionSample's name/context.
Definition at line 990 of file SampleProf.h.
Constructor & Destructor Documentation
SampleContextTrimmer()
llvm::sampleprof::SampleContextTrimmer::SampleContextTrimmer (StringMap< FunctionSamples > & Profiles) inline
Definition at line 992 of file SampleProf.h.
Member Function Documentation
canonicalizeContextProfiles()
void SampleContextTrimmer::canonicalizeContextProfiles ()
Definition at line 372 of file SampleProf.cpp.
References assert(), llvm::sampleprof::FunctionSamples::getNameWithContext(), I, llvm::MipsISD::Ret, and llvm::StringMap< ValueTy, AllocatorTy >::try_emplace().
trimAndMergeColdContextProfiles()
void SampleContextTrimmer::trimAndMergeColdContextProfiles (uint64_t ColdCountThreshold, bool TrimColdContext, bool MergeColdContext, uint32_t ColdContextFrameLength)
Definition at line 317 of file SampleProf.cpp.
References ColdCountThreshold, llvm::sampleprof::SampleContext::getNameWithoutContext(), llvm::sampleprof::FunctionSamples::getTotalSamples(), I, llvm::sampleprof::FunctionSamples::merge(), llvm::sampleprof::RawContext, llvm::MipsISD::Ret, llvm::sampleprof::FunctionSamples::setContext(), llvm::sampleprof::FunctionSamples::setName(), and llvm::StringMap< ValueTy, AllocatorTy >::try_emplace().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/SampleProf.h
lib/ProfileData/SampleProf.cpp