LLVM: llvm::orc::EHFrameRegistrationPlugin Class Reference
llvm::orc::EHFrameRegistrationPlugin Class Reference
#include "llvm/ExecutionEngine/Orc/ObjectLinkingLayer.h"
Public Member Functions
EHFrameRegistrationPlugin (ExecutionSession &ES, std::unique_ptr< jitlink::EHFrameRegistrar > Registrar)
void modifyPassConfig (MaterializationResponsibility &MR, jitlink::LinkGraph &G, jitlink::PassConfiguration &PassConfig) override
Error notifyEmitted (MaterializationResponsibility &MR) override
Error notifyFailed (MaterializationResponsibility &MR) override
Error notifyRemovingResources (ResourceKey K) override
void notifyTransferringResources (ResourceKey DstKey, ResourceKey SrcKey) override
Public Member Functions inherited from llvm::orc::ObjectLinkingLayer::Plugin
virtual ~Plugin ()
virtual void notifyMaterializing (MaterializationResponsibility &MR, jitlink::LinkGraph &G, jitlink::JITLinkContext &Ctx, MemoryBufferRef InputObject)
virtual void notifyLoaded (MaterializationResponsibility &MR)
virtual SyntheticSymbolDependenciesMap getSyntheticSymbolDependencies (MaterializationResponsibility &MR)
Return any dependencies that synthetic symbols (e.g.
Additional Inherited Members
Public Types inherited from llvm::orc::ObjectLinkingLayer::Plugin
using JITLinkSymbolSet = DenseSet< jitlink::Symbol * >
using SyntheticSymbolDependenciesMap = DenseMap< SymbolStringPtr, JITLinkSymbolSet >
Detailed Description
Definition at line 208 of file ObjectLinkingLayer.h.
Constructor & Destructor Documentation
EHFrameRegistrationPlugin()
llvm::orc::EHFrameRegistrationPlugin::EHFrameRegistrationPlugin (ExecutionSession & ES, std::unique_ptr< jitlink::EHFrameRegistrar > Registrar)
Definition at line 730 of file ObjectLinkingLayer.cpp.
Member Function Documentation
modifyPassConfig()
void llvm::orc::EHFrameRegistrationPlugin::modifyPassConfig (MaterializationResponsibility & MR, jitlink::LinkGraph & G, jitlink::PassConfiguration & PassConfig) override virtual
Reimplemented from llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 734 of file ObjectLinkingLayer.cpp.
References Addr, llvm::jitlink::createEHFrameRecorderPass(), G, llvm::jitlink::PassConfiguration::PostFixupPasses, and llvm::Check::Size.
notifyEmitted()
Error llvm::orc::EHFrameRegistrationPlugin::notifyEmitted (MaterializationResponsibility & MR) override virtual
Reimplemented from llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 749 of file ObjectLinkingLayer.cpp.
References assert(), llvm::Lock, and llvm::Error::success().
notifyFailed()
Error llvm::orc::EHFrameRegistrationPlugin::notifyFailed (MaterializationResponsibility & MR) override virtual
Implements llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 772 of file ObjectLinkingLayer.cpp.
References llvm::Lock, and llvm::Error::success().
notifyRemovingResources()
Error llvm::orc::EHFrameRegistrationPlugin::notifyRemovingResources (ResourceKey K) override virtual
Implements llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 779 of file ObjectLinkingLayer.cpp.
References I, and llvm::orc::ExecutionSession::runSessionLocked().
notifyTransferringResources()
void llvm::orc::EHFrameRegistrationPlugin::notifyTransferringResources (ResourceKey DstKey, ResourceKey SrcKey) override virtual
Implements llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 803 of file ObjectLinkingLayer.cpp.
References move, and SI.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/ObjectLinkingLayer.h
lib/ExecutionEngine/Orc/ObjectLinkingLayer.cpp