LLVM: llvm::sampleprof::SampleProfileWriterExtBinaryBase Class Reference
llvm::sampleprof::SampleProfileWriterExtBinaryBase Class Reference abstract
#include "llvm/ProfileData/SampleProfWriter.h"
Public Member Functions
virtual std::error_code write (const StringMap< FunctionSamples > &ProfileMap) override
Write all the sample profiles in the given map of samples.
virtual void setToCompressAllSections () override
void setToCompressSection (SecType Type)
virtual std::error_code writeSample (const FunctionSamples &S) override
Write samples of a top-level function to a binary file.
virtual void setUseMD5 () override
virtual void setPartialProfile () override
virtual void setProfileSymbolList (ProfileSymbolList *PSL) override
virtual void resetSecLayout (SectionLayout SL) override
Public Member Functions inherited from llvm::sampleprof::SampleProfileWriterBinary
SampleProfileWriterBinary (std::unique_ptr< raw_ostream > &OS)
Public Member Functions inherited from llvm::sampleprof::SampleProfileWriter
virtual ~SampleProfileWriter ()=default
raw_ostream & getOutputStream ()
Protected Member Functions
uint64_t markSectionStart (SecType Type, uint32_t LayoutIdx)
Return the current position and prepare to use it as the start position of a section given the section type Type and its position LayoutIdx in SectionHdrLayout.
std::error_code addNewSection (SecType Sec, uint32_t LayoutIdx, uint64_t SectionStart)
Add a new section into section header table given the section type Type, its position LayoutIdx in SectionHdrLayout and the location SectionStart where the section should be written to.
template<class SecFlagType >
void addSectionFlag (SecType Type, SecFlagType Flag)
template<class SecFlagType >
void addSectionFlag (uint32_t SectionIdx, SecFlagType Flag)
virtual std::error_code writeCustomSection (SecType Type)=0
virtual void verifySecLayout (SectionLayout SL)=0
virtual std::error_code writeSections (const StringMap< FunctionSamples > &ProfileMap)=0
virtual std::error_code writeOneSection (SecType Type, uint32_t LayoutIdx, const StringMap< FunctionSamples > &ProfileMap)
virtual std::error_code writeNameTable () override
std::error_code writeFuncMetadata (const StringMap< FunctionSamples > &Profiles)
std::error_code writeNameTableSection (const StringMap< FunctionSamples > &ProfileMap)
std::error_code writeFuncOffsetTable ()
std::error_code writeProfileSymbolListSection ()
Protected Member Functions inherited from llvm::sampleprof::SampleProfileWriterBinary
virtual std::error_code writeMagicIdent (SampleProfileFormat Format)
std::error_code writeSummary ()
std::error_code writeNameIdx (StringRef FName, bool IsContextName=false)
std::error_code writeBody (const FunctionSamples &S)
void stablizeNameTable (std::set< StringRef > &V)
void addName (StringRef FName, bool IsContextName=false)
void addNames (const FunctionSamples &S)
Protected Member Functions inherited from llvm::sampleprof::SampleProfileWriter
SampleProfileWriter (std::unique_ptr< raw_ostream > &OS)
virtual std::error_code writeFuncProfiles (const StringMap< FunctionSamples > &ProfileMap)
void computeSummary (const StringMap< FunctionSamples > &ProfileMap)
Compute summary for this profile.
Protected Attributes
SectionLayout SecLayout = DefaultLayout
SmallVector< SecHdrTableEntry, 8 > SectionHdrLayout
uint64_t SecLBRProfileStart = 0
Protected Attributes inherited from llvm::sampleprof::SampleProfileWriterBinary
MapVector< StringRef, uint32_t > NameTable
std::unordered_set< std::string > BracketedContextStr
Protected Attributes inherited from llvm::sampleprof::SampleProfileWriter
std::unique_ptr< raw_ostream > OutputStream
Output stream where to emit the profile to.
std::unique_ptr< ProfileSummary > Summary
Profile summary.
SampleProfileFormat Format = SPF_None
Profile format.
Additional Inherited Members
Static Public Member Functions inherited from llvm::sampleprof::SampleProfileWriter
static ErrorOr< std::unique_ptr< SampleProfileWriter > > create (StringRef Filename, SampleProfileFormat Format)
Profile writer factory.
static ErrorOr< std::unique_ptr< SampleProfileWriter > > create (std::unique_ptr< raw_ostream > &OS, SampleProfileFormat Format)
Create a new stream writer based on the value of Format.
Detailed Description
Definition at line 190 of file SampleProfWriter.h.
Member Function Documentation
addNewSection()
std::error_code SampleProfileWriterExtBinaryBase::addNewSection (SecType Sec, uint32_t LayoutIdx, uint64_t SectionStart) protected
Add a new section into section header table given the section type Type, its position LayoutIdx in SectionHdrLayout and the location SectionStart where the section should be written to.
Definition at line 118 of file SampleProfWriter.cpp.
References assert(), and SectionHdrLayout.
Referenced by writeOneSection().
addSectionFlag() [1/2]
template<class SecFlagType > void llvm::sampleprof::SampleProfileWriterExtBinaryBase::addSectionFlag (SecType Type, SecFlagType Flag) inline protected
Definition at line 238 of file SampleProfWriter.h.
Referenced by setPartialProfile(), setToCompressSection(), setUseMD5(), writeNameTableSection(), and writeOneSection().
addSectionFlag() [2/2]
template<class SecFlagType > void llvm::sampleprof::SampleProfileWriterExtBinaryBase::addSectionFlag (uint32_t SectionIdx, SecFlagType Flag) inline protected
Definition at line 245 of file SampleProfWriter.h.
References llvm::sampleprof::addSecFlag(), and SectionHdrLayout.
markSectionStart()
uint64_t SampleProfileWriterExtBinaryBase::markSectionStart (SecType Type, uint32_t LayoutIdx) protected
Return the current position and prepare to use it as the start position of a section given the section type Type and its position LayoutIdx in SectionHdrLayout.
Definition at line 83 of file SampleProfWriter.cpp.
References assert(), llvm::sampleprof::SampleProfileWriter::OutputStream, and SectionHdrLayout.
Referenced by writeOneSection().
resetSecLayout()
virtual void llvm::sampleprof::SampleProfileWriterExtBinaryBase::resetSecLayout (SectionLayout SL) inline override virtual
Reimplemented from llvm::sampleprof::SampleProfileWriter.
Definition at line 220 of file SampleProfWriter.h.
References verifySecLayout().
setPartialProfile()
virtual void llvm::sampleprof::SampleProfileWriterExtBinaryBase::setPartialProfile () inline override virtual
Reimplemented from llvm::sampleprof::SampleProfileWriter.
Definition at line 212 of file SampleProfWriter.h.
References addSectionFlag(), and llvm::sampleprof::SecProfSummary.
setProfileSymbolList()
virtual void llvm::sampleprof::SampleProfileWriterExtBinaryBase::setProfileSymbolList (ProfileSymbolList * PSL) inline override virtual
Reimplemented from llvm::sampleprof::SampleProfileWriter.
Definition at line 216 of file SampleProfWriter.h.
setToCompressAllSections()
void SampleProfileWriterExtBinaryBase::setToCompressAllSections () override virtual
Reimplemented from llvm::sampleprof::SampleProfileWriter.
Definition at line 579 of file SampleProfWriter.cpp.
setToCompressSection()
void SampleProfileWriterExtBinaryBase::setToCompressSection (SecType Type)
Definition at line 584 of file SampleProfWriter.cpp.
References addSectionFlag().
Referenced by writeOneSection().
setUseMD5()
virtual void llvm::sampleprof::SampleProfileWriterExtBinaryBase::setUseMD5 () inline override virtual
Reimplemented from llvm::sampleprof::SampleProfileWriter.
Definition at line 201 of file SampleProfWriter.h.
References addSectionFlag(), and llvm::sampleprof::SecNameTable.
verifySecLayout()
virtual void llvm::sampleprof::SampleProfileWriterExtBinaryBase::verifySecLayout (SectionLayout SL) protected pure virtual
Referenced by resetSecLayout().
write()
std::error_code SampleProfileWriterExtBinaryBase::write (const StringMap< FunctionSamples > & ProfileMap) override virtual
Write all the sample profiles in the given map of samples.
Returns
status code of the file update operation.
Reimplemented from llvm::sampleprof::SampleProfileWriter.
Definition at line 133 of file SampleProfWriter.cpp.
References llvm::success, and writeSections().
writeCustomSection()
virtual std::error_code llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeCustomSection (SecType Type) protected pure virtual
Referenced by writeOneSection().
writeFuncMetadata()
std::error_code SampleProfileWriterExtBinaryBase::writeFuncMetadata (const StringMap< FunctionSamples > & Profiles) protected
Definition at line 175 of file SampleProfWriter.cpp.
References llvm::sampleprof::SampleProfileWriter::OutputStream, llvm::sampleprof::FunctionSamples::ProfileIsCS, llvm::sampleprof::FunctionSamples::ProfileIsProbeBased, and llvm::success.
Referenced by writeOneSection().
writeFuncOffsetTable()
std::error_code SampleProfileWriterExtBinaryBase::writeFuncOffsetTable () protected
Definition at line 158 of file SampleProfWriter.cpp.
References llvm::encodeULEB128(), and llvm::sampleprof::SampleProfileWriter::OutputStream.
Referenced by writeOneSection().
writeNameTable()
std::error_code SampleProfileWriterExtBinaryBase::writeNameTable () override protected virtual
Reimplemented from llvm::sampleprof::SampleProfileWriterBinary.
Definition at line 192 of file SampleProfWriter.cpp.
References llvm::encodeULEB128(), llvm::support::little, llvm::MD5Hash(), N, llvm::sampleprof::SampleProfileWriterBinary::NameTable, llvm::sampleprof::SampleProfileWriter::OutputStream, llvm::sampleprof::SampleProfileWriterBinary::stablizeNameTable(), llvm::success, llvm::support::endian::Writer::write(), and llvm::sampleprof::SampleProfileWriterBinary::writeNameTable().
Referenced by writeNameTableSection().
writeNameTableSection()
std::error_code SampleProfileWriterExtBinaryBase::writeNameTableSection (const StringMap< FunctionSamples > & ProfileMap) protected
Definition at line 210 of file SampleProfWriter.cpp.
References llvm::sampleprof::SampleProfileWriterBinary::addName(), llvm::sampleprof::SampleProfileWriterBinary::addNames(), addSectionFlag(), assert(), I, llvm::sampleprof::SampleProfileWriterBinary::NameTable, llvm::StringRef::npos, llvm::sampleprof::FunctionSamples::ProfileIsCS, llvm::sampleprof::SecFlagInValid, llvm::sampleprof::SecNameTable, llvm::success, llvm::sampleprof::FunctionSamples::UniqSuffix, and writeNameTable().
Referenced by writeOneSection().
writeOneSection()
std::error_code SampleProfileWriterExtBinaryBase::writeOneSection (SecType Type, uint32_t LayoutIdx, const StringMap< FunctionSamples > & ProfileMap) protected virtual
Definition at line 243 of file SampleProfWriter.cpp.
References addNewSection(), addSectionFlag(), llvm::sampleprof::SampleProfileWriter::computeSummary(), markSectionStart(), llvm::sampleprof::SampleProfileWriter::OutputStream, llvm::sampleprof::FunctionSamples::ProfileIsCS, llvm::sampleprof::FunctionSamples::ProfileIsFS, llvm::sampleprof::FunctionSamples::ProfileIsProbeBased, llvm::sampleprof::SecFlagInValid, llvm::sampleprof::SecFlagInvalid, llvm::sampleprof::SecFuncMetadata, llvm::sampleprof::SecFuncOffsetTable, llvm::sampleprof::SecLBRProfile, SecLBRProfileStart, llvm::sampleprof::SecNameTable, llvm::sampleprof::SecProfileSymbolList, llvm::sampleprof::SecProfSummary, setToCompressSection(), llvm::success, llvm::sampleprof::ProfileSymbolList::toCompress(), writeCustomSection(), writeFuncMetadata(), writeFuncOffsetTable(), llvm::sampleprof::SampleProfileWriter::writeFuncProfiles(), writeNameTableSection(), writeProfileSymbolListSection(), and llvm::sampleprof::SampleProfileWriterBinary::writeSummary().
writeProfileSymbolListSection()
std::error_code SampleProfileWriterExtBinaryBase::writeProfileSymbolListSection () protected
Definition at line 235 of file SampleProfWriter.cpp.
References llvm::sampleprof::SampleProfileWriter::OutputStream, llvm::sampleprof::ProfileSymbolList::size(), llvm::success, and llvm::sampleprof::ProfileSymbolList::write().
Referenced by writeOneSection().
writeSample()
std::error_code SampleProfileWriterExtBinaryBase::writeSample (const FunctionSamples & S) override virtual
Write samples of a top-level function to a binary file.
Returns
true if the samples were written successfully, false otherwise.
Reimplemented from llvm::sampleprof::SampleProfileWriterBinary.
Definition at line 150 of file SampleProfWriter.cpp.
References llvm::encodeULEB128(), Offset, llvm::sampleprof::SampleProfileWriter::OutputStream, S, SecLBRProfileStart, and llvm::sampleprof::SampleProfileWriterBinary::writeBody().
writeSections()
virtual std::error_code llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeSections (const StringMap< FunctionSamples > & ProfileMap) protected pure virtual
Referenced by write().
Member Data Documentation
SecLayout
SectionLayout llvm::sampleprof::SampleProfileWriterExtBinaryBase::SecLayout = DefaultLayout protected
Definition at line 275 of file SampleProfWriter.h.
SecLBRProfileStart
uint64_t llvm::sampleprof::SampleProfileWriterExtBinaryBase::SecLBRProfileStart = 0 protected
Definition at line 286 of file SampleProfWriter.h.
Referenced by writeOneSection(), and writeSample().
SectionHdrLayout
SmallVector<SecHdrTableEntry, 8> llvm::sampleprof::SampleProfileWriterExtBinaryBase::SectionHdrLayout protected
Initial value:
=
      ExtBinaryHdrLayoutTable[DefaultLayout]
Definition at line 280 of file SampleProfWriter.h.
Referenced by addNewSection(), addSectionFlag(), and markSectionStart().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/SampleProfWriter.h
lib/ProfileData/SampleProfWriter.cpp