LLVM: llvm::ChangeReporter< IRUnitT > Class Template Reference
llvm::ChangeReporter< IRUnitT > Class Template Reference abstract
#include "llvm/Passes/StandardInstrumentations.h"
Public Member Functions
virtual ~ChangeReporter ()
void saveIRBeforePass (Any IR, StringRef PassID)
void handleIRAfterPass (Any IR, StringRef PassID)
void handleInvalidatedPass (StringRef PassID)
Protected Member Functions
ChangeReporter (bool RunInVerboseMode)
void registerRequiredCallbacks (PassInstrumentationCallbacks &PIC)
bool isInterestingFunction (const Function &F)
bool isInterestingPass (StringRef PassID)
bool isInteresting (Any IR, StringRef PassID)
virtual void handleInitialIR (Any IR)=0
virtual void generateIRRepresentation (Any IR, StringRef PassID, IRUnitT &Output)=0
virtual void omitAfter (StringRef PassID, std::string &Name)=0
virtual void handleAfter (StringRef PassID, std::string &Name, const IRUnitT &Before, const IRUnitT &After, Any)=0
virtual void handleInvalidated (StringRef PassID)=0
virtual void handleFiltered (StringRef PassID, std::string &Name)=0
virtual void handleIgnored (StringRef PassID, std::string &Name)=0
virtual bool same (const IRUnitT &Before, const IRUnitT &After)=0
Protected Attributes
std::vector< IRUnitT > BeforeStack
bool InitialIR = true
const bool VerboseMode
Detailed Description
template<typename IRUnitT>
class llvm::ChangeReporter< IRUnitT >
Definition at line 171 of file StandardInstrumentations.h.
Constructor & Destructor Documentation
ChangeReporter()
template<typename IRUnitT > llvm::ChangeReporter< IRUnitT >::ChangeReporter (bool RunInVerboseMode) inline protected
Definition at line 173 of file StandardInstrumentations.h.
~ChangeReporter()
template<typename IRUnitT > ChangeReporter::~ChangeReporter< IRUnitT > virtual
Definition at line 119 of file StandardInstrumentations.cpp.
Member Function Documentation
generateIRRepresentation()
template<typename IRUnitT > virtual void llvm::ChangeReporter< IRUnitT >::generateIRRepresentation (Any IR, StringRef PassID, IRUnitT & Output) protected pure virtual
Implemented in llvm::IRChangedPrinter, and llvm::InLineChangePrinter.
handleAfter()
template<typename IRUnitT > virtual void llvm::ChangeReporter< IRUnitT >::handleAfter (StringRef PassID, std::string & Name, const IRUnitT & Before, const IRUnitT & After, Any) protected pure virtual
Implemented in llvm::IRChangedPrinter, and llvm::InLineChangePrinter.
handleFiltered()
template<typename IRUnitT > virtual void llvm::ChangeReporter< IRUnitT >::handleFiltered (StringRef PassID, std::string & Name) protected pure virtual
Implemented in llvm::TextChangeReporter< IRUnitT >, llvm::TextChangeReporter< ChangedIRData >, and llvm::TextChangeReporter< std::string >.
handleIgnored()
template<typename IRUnitT > virtual void llvm::ChangeReporter< IRUnitT >::handleIgnored (StringRef PassID, std::string & Name) protected pure virtual
Implemented in llvm::TextChangeReporter< IRUnitT >, llvm::TextChangeReporter< ChangedIRData >, and llvm::TextChangeReporter< std::string >.
handleInitialIR()
template<typename IRUnitT > virtual void llvm::ChangeReporter< IRUnitT >::handleInitialIR (Any IR) protected pure virtual
Implemented in llvm::TextChangeReporter< IRUnitT >, llvm::TextChangeReporter< ChangedIRData >, and llvm::TextChangeReporter< std::string >.
handleInvalidated()
template<typename IRUnitT > virtual void llvm::ChangeReporter< IRUnitT >::handleInvalidated (StringRef PassID) protected pure virtual
Implemented in llvm::TextChangeReporter< IRUnitT >, llvm::TextChangeReporter< ChangedIRData >, and llvm::TextChangeReporter< std::string >.
handleInvalidatedPass()
template<typename IRUnitT > void ChangeReporter::handleInvalidatedPass (StringRef PassID)
Definition at line 455 of file StandardInstrumentations.cpp.
References assert().
handleIRAfterPass()
template<typename IRUnitT > void ChangeReporter::handleIRAfterPass (Any IR, StringRef PassID)
Definition at line 426 of file StandardInstrumentations.cpp.
References assert(), llvm::StringRef::back(), IR, and isInteresting().
isInteresting()
template<typename IRUnitT > bool ChangeReporter::isInteresting (Any IR, StringRef PassID) protected
Definition at line 396 of file StandardInstrumentations.cpp.
References IR.
isInterestingFunction()
template<typename IRUnitT > bool ChangeReporter::isInterestingFunction (const Function & F) protected
Definition at line 379 of file StandardInstrumentations.cpp.
References F, and llvm::isFunctionInPrintList().
isInterestingPass()
template<typename IRUnitT > bool ChangeReporter::isInterestingPass (StringRef PassID) protected
Definition at line 384 of file StandardInstrumentations.cpp.
References PrintPassesList, and llvm::StringRef::str().
omitAfter()
template<typename IRUnitT > virtual void llvm::ChangeReporter< IRUnitT >::omitAfter (StringRef PassID, std::string & Name) protected pure virtual
Implemented in llvm::TextChangeReporter< IRUnitT >, llvm::TextChangeReporter< ChangedIRData >, and llvm::TextChangeReporter< std::string >.
registerRequiredCallbacks()
template<typename IRUnitT > void ChangeReporter::registerRequiredCallbacks (PassInstrumentationCallbacks & PIC) protected
Definition at line 468 of file StandardInstrumentations.cpp.
References IR, P, PIC, llvm::PassInstrumentationCallbacks::registerAfterPassCallback(), llvm::PassInstrumentationCallbacks::registerAfterPassInvalidatedCallback(), and llvm::PassInstrumentationCallbacks::registerBeforeNonSkippedPassCallback().
Referenced by llvm::IRChangedPrinter::registerCallbacks(), and llvm::InLineChangePrinter::registerCallbacks().
same()
template<typename IRUnitT > virtual bool llvm::ChangeReporter< IRUnitT >::same (const IRUnitT & Before, const IRUnitT & After) protected pure virtual
Implemented in llvm::IRChangedPrinter, and llvm::InLineChangePrinter.
saveIRBeforePass()
template<typename IRUnitT > void ChangeReporter::saveIRBeforePass (Any IR, StringRef PassID)
Definition at line 405 of file StandardInstrumentations.cpp.
References llvm::Data, IR, and isInteresting().
Member Data Documentation
BeforeStack
template<typename IRUnitT > std::vector<IRUnitT> llvm::ChangeReporter< IRUnitT >::BeforeStack protected
Definition at line 222 of file StandardInstrumentations.h.
InitialIR
template<typename IRUnitT > bool llvm::ChangeReporter< IRUnitT >::InitialIR = true protected
Definition at line 224 of file StandardInstrumentations.h.
VerboseMode
template<typename IRUnitT > const bool llvm::ChangeReporter< IRUnitT >::VerboseMode protected
Definition at line 227 of file StandardInstrumentations.h.
The documentation for this class was generated from the following files:
include/llvm/Passes/StandardInstrumentations.h
lib/Passes/StandardInstrumentations.cpp