LLVM: llvm::PostGenericScheduler Class Reference
llvm::PostGenericScheduler Class Reference
PostGenericScheduler - Interface to the scheduling algorithm used by ScheduleDAGMI.
#include "llvm/CodeGen/MachineScheduler.h"
Public Member Functions
PostGenericScheduler (const MachineSchedContext *C)
~PostGenericScheduler () override=default
void initPolicy (MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned NumRegionInstrs) override
Optionally override the per-region scheduling policy.
bool shouldTrackPressure () const override
PostRA scheduling does not track pressure.
void initialize (ScheduleDAGMI *Dag) override
Initialize the strategy after building the DAG for a new region.
void registerRoots () override
Notify this strategy that all roots have been released (including those that depend on EntrySU or ExitSU).
SUnit * pickNode (bool &IsTopNode) override
Pick the next node to schedule.
void scheduleTree (unsigned SubtreeID) override
Scheduler callback to notify that a new subtree is scheduled.
void schedNode (SUnit *SU, bool IsTopNode) override
Called after ScheduleDAGMI has scheduled an instruction and updated scheduled/remaining flags in the DAG nodes.
void releaseTopNode (SUnit *SU) override
When all predecessor dependencies have been resolved, free this node for top-down scheduling.
void releaseBottomNode (SUnit *SU) override
When all successor dependencies have been resolved, free this node for bottom-up scheduling.
Public Member Functions inherited from llvm::MachineSchedStrategy
virtual ~MachineSchedStrategy ()=default
virtual void dumpPolicy () const
virtual bool shouldTrackLaneMasks () const
Returns true if lanemasks should be tracked.
virtual bool doMBBSchedRegionsTopDown () const
virtual void enterMBB (MachineBasicBlock *MBB)
Tell the strategy that MBB is about to be processed.
virtual void leaveMBB ()
Tell the strategy that current MBB is done.
Protected Member Functions
virtual bool tryCandidate (SchedCandidate &Cand, SchedCandidate &TryCand)
Apply a set of heuristics to a new candidate for PostRA scheduling.
void pickNodeFromQueue (SchedCandidate &Cand)
Protected Member Functions inherited from llvm::GenericSchedulerBase
GenericSchedulerBase (const MachineSchedContext *C)
void setPolicy (CandPolicy &Policy, bool IsPostRA, SchedBoundary &CurrZone, SchedBoundary *OtherZone)
Set the CandPolicy given a scheduling zone given the current resources and latencies inside and outside the zone.
void traceCandidate (const SchedCandidate &Cand)
Protected Attributes
ScheduleDAGMI * DAG = nullptr
SchedBoundary Top
SmallVector< SUnit *, 8 > BotRoots
Protected Attributes inherited from llvm::GenericSchedulerBase
const MachineSchedContext * Context
const TargetSchedModel * SchedModel = nullptr
const TargetRegisterInfo * TRI = nullptr
SchedRemainder Rem
Additional Inherited Members
Public Types inherited from llvm::GenericSchedulerBase
enum CandReason : uint8_t {
NoCand, Only1, PhysReg, RegExcess,
RegCritical, Stall, Cluster, Weak,
RegMax, ResourceReduce, ResourceDemand, BotHeightReduce,
BotPathReduce, TopDepthReduce, TopPathReduce, NextDefUse,
NodeOrder
}
Represent the type of SchedCandidate found within a single queue.
Static Public Member Functions inherited from llvm::GenericSchedulerBase
static const char * getReasonStr (GenericSchedulerBase::CandReason Reason)
Detailed Description
PostGenericScheduler - Interface to the scheduling algorithm used by ScheduleDAGMI.
Callbacks from ScheduleDAGMI: initPolicy -> initialize(DAG) -> registerRoots -> pickNode ...
Definition at line 1033 of file MachineScheduler.h.
Constructor & Destructor Documentation
PostGenericScheduler()
llvm::PostGenericScheduler::PostGenericScheduler (const MachineSchedContext * C) inline
Definition at line 1040 of file MachineScheduler.h.
~PostGenericScheduler()
llvm::PostGenericScheduler::~PostGenericScheduler () override default
Member Function Documentation
initialize()
void PostGenericScheduler::initialize (ScheduleDAGMI * DAG) override virtual
Initialize the strategy after building the DAG for a new region.
Implements llvm::MachineSchedStrategy.
Reimplemented in llvm::PPCPostRASchedStrategy.
Definition at line 3513 of file MachineScheduler.cpp.
References llvm::TargetInstrInfo::CreateTargetMIHazardRecognizer(), llvm::tgtok::Dag, llvm::TargetSubtargetInfo::getInstrInfo(), llvm::TargetSchedModel::getInstrItineraries(), llvm::ScheduleDAGInstrs::getSchedModel(), llvm::MachineFunction::getSubtarget(), llvm::SchedRemainder::init(), llvm::ScheduleDAG::MF, llvm::GenericSchedulerBase::Rem, llvm::GenericSchedulerBase::SchedModel, llvm::GenericSchedulerBase::TRI, and llvm::ScheduleDAG::TRI.
Referenced by llvm::PPCPostRASchedStrategy::initialize().
initPolicy()
void llvm::PostGenericScheduler::initPolicy (MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned NumRegionInstrs) inline override virtual
Optionally override the per-region scheduling policy.
Reimplemented from llvm::MachineSchedStrategy.
Definition at line 1045 of file MachineScheduler.h.
pickNode()
SUnit * PostGenericScheduler::pickNode (bool & IsTopNode) override virtual
Pick the next node to schedule.
Implements llvm::MachineSchedStrategy.
Reimplemented in llvm::PPCPostRASchedStrategy.
Definition at line 3608 of file MachineScheduler.cpp.
References assert(), llvm::ScheduleDAGMI::bottom(), llvm::dbgs(), llvm::SUnit::getInstr(), llvm::SUnit::isScheduled, LLVM_DEBUG, llvm::GenericSchedulerBase::NoCand, llvm::SUnit::NodeNum, llvm::GenericSchedulerBase::Only1, llvm::GenericSchedulerBase::SchedCandidate::Policy, llvm::GenericSchedulerBase::SchedCandidate::Reason, llvm::GenericSchedulerBase::setPolicy(), llvm::GenericSchedulerBase::SchedCandidate::SU, llvm::ScheduleDAGMI::top(), and tracePick().
Referenced by llvm::PPCPostRASchedStrategy::pickNode().
pickNodeFromQueue()
void PostGenericScheduler::pickNodeFromQueue (SchedCandidate & Cand) protected
Definition at line 3593 of file MachineScheduler.cpp.
References llvm::GenericSchedulerBase::SchedCandidate::AtTop, llvm::GenericSchedulerBase::SchedCandidate::initResourceDelta(), LLVM_DEBUG, llvm::GenericSchedulerBase::SchedCandidate::Policy, llvm::GenericSchedulerBase::SchedModel, llvm::GenericSchedulerBase::SchedCandidate::setBest(), llvm::GenericSchedulerBase::SchedCandidate::SU, and llvm::GenericSchedulerBase::traceCandidate().
registerRoots()
void PostGenericScheduler::registerRoots () override virtual
Notify this strategy that all roots have been released (including those that depend on EntrySU or ExitSU).
Reimplemented from llvm::MachineSchedStrategy.
Definition at line 3532 of file MachineScheduler.cpp.
References llvm::SchedRemainder::CriticalPath, llvm::dbgs(), llvm::DumpCriticalPathLength, llvm::errs(), llvm::ScheduleDAG::ExitSU, llvm::SUnit::getDepth(), LLVM_DEBUG, and llvm::GenericSchedulerBase::Rem.
releaseBottomNode()
void llvm::PostGenericScheduler::releaseBottomNode (SUnit * SU) inline override virtual
When all successor dependencies have been resolved, free this node for bottom-up scheduling.
Implements llvm::MachineSchedStrategy.
Definition at line 1073 of file MachineScheduler.h.
References BotRoots.
releaseTopNode()
void llvm::PostGenericScheduler::releaseTopNode (SUnit * SU) inline override virtual
When all predecessor dependencies have been resolved, free this node for top-down scheduling.
Implements llvm::MachineSchedStrategy.
Definition at line 1066 of file MachineScheduler.h.
References llvm::SUnit::isScheduled, llvm::SchedBoundary::releaseNode(), Top, and llvm::SUnit::TopReadyCycle.
schedNode()
void PostGenericScheduler::schedNode (SUnit * SU, bool IsTopNode) override virtual
Called after ScheduleDAGMI has scheduled an instruction and updated scheduled/remaining flags in the DAG nodes.
Implements llvm::MachineSchedStrategy.
Definition at line 3641 of file MachineScheduler.cpp.
References llvm::max(), and llvm::SUnit::TopReadyCycle.
scheduleTree()
void llvm::PostGenericScheduler::scheduleTree (unsigned SubtreeID) inline override virtual
Scheduler callback to notify that a new subtree is scheduled.
Reimplemented from llvm::MachineSchedStrategy.
Definition at line 1060 of file MachineScheduler.h.
References llvm_unreachable.
shouldTrackPressure()
bool llvm::PostGenericScheduler::shouldTrackPressure () const inline override virtual
PostRA scheduling does not track pressure.
Reimplemented from llvm::MachineSchedStrategy.
Definition at line 1052 of file MachineScheduler.h.
tryCandidate()
bool PostGenericScheduler::tryCandidate (SchedCandidate & Cand, SchedCandidate & TryCand) protected virtual
Apply a set of heuristics to a new candidate for PostRA scheduling.
Parameters
Cand provides the policy and current best candidate.
TryCand refers to the next SUnit candidate, otherwise uninitialized.
Returns
true if TryCand is better than Cand (Reason is NOT NoCand)
Reimplemented in llvm::PPCPostRASchedStrategy.
Definition at line 3551 of file MachineScheduler.cpp.
References llvm::GenericSchedulerBase::Cluster, llvm::GenericSchedulerBase::SchedResourceDelta::CritResources, llvm::GenericSchedulerBase::SchedResourceDelta::DemandedResources, llvm::ScheduleDAGMI::getNextClusterSucc(), llvm::GenericSchedulerBase::SchedCandidate::isValid(), llvm::GenericSchedulerBase::NoCand, llvm::SUnit::NodeNum, llvm::GenericSchedulerBase::NodeOrder, llvm::GenericSchedulerBase::SchedCandidate::Policy, llvm::GenericSchedulerBase::SchedCandidate::Reason, llvm::GenericSchedulerBase::CandPolicy::ReduceLatency, llvm::GenericSchedulerBase::SchedCandidate::ResDelta, llvm::GenericSchedulerBase::ResourceDemand, llvm::GenericSchedulerBase::ResourceReduce, llvm::GenericSchedulerBase::Stall, llvm::GenericSchedulerBase::SchedCandidate::SU, llvm::tryGreater(), llvm::tryLatency(), and llvm::tryLess().
Member Data Documentation
BotRoots
SmallVector<SUnit*, 8> llvm::PostGenericScheduler::BotRoots protected
Definition at line 1037 of file MachineScheduler.h.
Referenced by releaseBottomNode().
DAG
ScheduleDAGMI* llvm::PostGenericScheduler::DAG = nullptr protected
Definition at line 1035 of file MachineScheduler.h.
Referenced by llvm::PPCPostRASchedStrategy::tryCandidate().
Top
SchedBoundary llvm::PostGenericScheduler::Top protected
Definition at line 1036 of file MachineScheduler.h.
Referenced by releaseTopNode(), and llvm::PPCPostRASchedStrategy::tryCandidate().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineScheduler.h
lib/CodeGen/MachineScheduler.cpp