LLVM: llvm::GVN Class Reference
llvm::GVN Class Reference
The core GVN pass object.
#include "llvm/Transforms/Scalar/GVN.h"
Classes
struct Expression
class ValueTable
This class holds the mapping between values and value numbers.
Public Member Functions
GVN (GVNOptions Options={})
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Run the pass over the function.
void markInstructionForDeletion (Instruction *I)
This removes the specified instruction from our various maps and marks it for deletion.
DominatorTree & getDominatorTree () const
AAResults * getAliasAnalysis () const
MemoryDependenceResults & getMemDep () const
bool isPREEnabled () const
bool isLoadPREEnabled () const
bool isLoadInLoopPREEnabled () const
bool isLoadPRESplitBackedgeEnabled () const
bool isMemDepEnabled () const
Friends
class gvn::GVNLegacyPass
struct DenseMapInfo< Expression >
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< GVN >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
The core GVN pass object.
FIXME: We should have a good summary of the GVN algorithm implemented by this particular pass here.
Definition at line 118 of file GVN.h.
Constructor & Destructor Documentation
GVN()
llvm::GVN::GVN (GVNOptions Options = {}) inline
Definition at line 124 of file GVN.h.
Member Function Documentation
getAliasAnalysis()
AAResults* llvm::GVN::getAliasAnalysis () const inline
Definition at line 137 of file GVN.h.
References llvm::GVN::ValueTable::getAliasAnalysis().
getDominatorTree()
DominatorTree& llvm::GVN::getDominatorTree () const inline
Definition at line 136 of file GVN.h.
Referenced by ConstructSSAForLoadSet().
getMemDep()
MemoryDependenceResults& llvm::GVN::getMemDep () const inline
Definition at line 138 of file GVN.h.
Referenced by llvm::gvn::AvailableValue::MaterializeAdjustedValue().
isLoadInLoopPREEnabled()
bool GVN::isLoadInLoopPREEnabled () const
Definition at line 646 of file GVN.cpp.
References GVNEnableLoadInLoopPRE, and Options.
isLoadPREEnabled()
bool GVN::isLoadPREEnabled () const
Definition at line 642 of file GVN.cpp.
References GVNEnableLoadPRE, and Options.
isLoadPRESplitBackedgeEnabled()
bool GVN::isLoadPRESplitBackedgeEnabled () const
Definition at line 650 of file GVN.cpp.
References GVNEnableSplitBackedgeInLoadPRE, and Options.
isMemDepEnabled()
bool GVN::isMemDepEnabled () const
Definition at line 655 of file GVN.cpp.
References GVNEnableMemDep, and Options.
isPREEnabled()
bool GVN::isPREEnabled () const
Definition at line 638 of file GVN.cpp.
References GVNEnablePRE, and Options.
markInstructionForDeletion()
void llvm::GVN::markInstructionForDeletion (Instruction * I) inline
This removes the specified instruction from our various maps and marks it for deletion.
Definition at line 131 of file GVN.h.
References llvm::GVN::ValueTable::erase(), and I.
run()
PreservedAnalyses GVN::run (Function & F, FunctionAnalysisManager & AM)
Run the pass over the function.
Definition at line 659 of file GVN.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PreservedAnalyses::preserve(), and runImpl().
Friends And Related Function Documentation
DenseMapInfo< Expression >
friend struct DenseMapInfo< Expression > friend
Definition at line 215 of file GVN.h.
gvn::GVNLegacyPass
friend class gvn::GVNLegacyPass friend
Definition at line 215 of file GVN.h.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/GVN.h
lib/Transforms/Scalar/GVN.cpp