LLVM: llvm::CombinerHelper Class Reference
llvm::CombinerHelper Class Reference
#include "llvm/CodeGen/GlobalISel/CombinerHelper.h"
Public Member Functions
CombinerHelper (GISelChangeObserver &Observer, MachineIRBuilder &B, GISelKnownBits *KB=nullptr, MachineDominatorTree *MDT=nullptr, const LegalizerInfo *LI=nullptr)
GISelKnownBits * getKnownBits () const
const TargetLowering & getTargetLowering () const
bool isLegalOrBeforeLegalizer (const LegalityQuery &Query) const
void replaceRegWith (MachineRegisterInfo &MRI, Register FromReg, Register ToReg) const
MachineRegisterInfo::replaceRegWith() and inform the observer of the changes.
void replaceRegOpWith (MachineRegisterInfo &MRI, MachineOperand &FromRegOp, Register ToReg) const
Replace a single register operand with a new register and inform the observer of the changes.
bool tryCombineCopy (MachineInstr &MI)
If MI is COPY, try to combine it.
bool matchCombineCopy (MachineInstr &MI)
void applyCombineCopy (MachineInstr &MI)
bool isPredecessor (const MachineInstr &DefMI, const MachineInstr &UseMI)
Returns true if DefMI precedes UseMI or they are the same instruction.
bool dominates (const MachineInstr &DefMI, const MachineInstr &UseMI)
Returns true if DefMI dominates UseMI.
bool tryCombineExtendingLoads (MachineInstr &MI)
If MI is extend that consumes the result of a load, try to combine it.
bool matchCombineExtendingLoads (MachineInstr &MI, PreferredTuple &MatchInfo)
void applyCombineExtendingLoads (MachineInstr &MI, PreferredTuple &MatchInfo)
bool tryCombineIndexedLoadStore (MachineInstr &MI)
Combine MI into a pre-indexed or post-indexed load/store operation if legal and the surrounding code makes it useful.
bool matchCombineIndexedLoadStore (MachineInstr &MI, IndexedLoadStoreMatchInfo &MatchInfo)
void applyCombineIndexedLoadStore (MachineInstr &MI, IndexedLoadStoreMatchInfo &MatchInfo)
bool matchSextTruncSextLoad (MachineInstr &MI)
void applySextTruncSextLoad (MachineInstr &MI)
bool matchSextInRegOfLoad (MachineInstr &MI, std::tuple< Register, unsigned > &MatchInfo)
Match sext_inreg(load p), imm -> sextload p.
void applySextInRegOfLoad (MachineInstr &MI, std::tuple< Register, unsigned > &MatchInfo)
bool matchCombineDivRem (MachineInstr &MI, MachineInstr *&OtherMI)
Try to combine G_[SU]DIV and G_[SU]REM into a single G_[SU]DIVREM when their source operands are identical.
void applyCombineDivRem (MachineInstr &MI, MachineInstr *&OtherMI)
bool matchOptBrCondByInvertingCond (MachineInstr &MI, MachineInstr *&BrCond)
If a brcond's true block is not the fallthrough, make it so by inverting the condition and swapping operands.
void applyOptBrCondByInvertingCond (MachineInstr &MI, MachineInstr *&BrCond)
bool tryCombineConcatVectors (MachineInstr &MI)
If MI is G_CONCAT_VECTORS, try to combine it.
bool matchCombineConcatVectors (MachineInstr &MI, bool &IsUndef, SmallVectorImpl< Register > &Ops)
Check if the G_CONCAT_VECTORS MI is undef or if it can be flattened into a build_vector.
void applyCombineConcatVectors (MachineInstr &MI, bool IsUndef, const ArrayRef< Register > Ops)
Replace MI with a flattened build_vector with Ops or an implicit_def if IsUndef is true.
bool tryCombineShuffleVector (MachineInstr &MI)
Try to combine G_SHUFFLE_VECTOR into G_CONCAT_VECTORS.
bool matchCombineShuffleVector (MachineInstr &MI, SmallVectorImpl< Register > &Ops)
Check if the G_SHUFFLE_VECTOR MI can be replaced by a concat_vectors.
void applyCombineShuffleVector (MachineInstr &MI, const ArrayRef< Register > Ops)
Replace MI with a concat_vectors with Ops.
bool tryCombineMemCpyFamily (MachineInstr &MI, unsigned MaxLen=0)
Optimize memcpy intrinsics et al, e.g.
bool matchPtrAddImmedChain (MachineInstr &MI, PtrAddChain &MatchInfo)
void applyPtrAddImmedChain (MachineInstr &MI, PtrAddChain &MatchInfo)
bool matchShiftImmedChain (MachineInstr &MI, RegisterImmPair &MatchInfo)
Fold (shift (shift base, x), y) -> (shift base (x+y))
void applyShiftImmedChain (MachineInstr &MI, RegisterImmPair &MatchInfo)
bool matchShiftOfShiftedLogic (MachineInstr &MI, ShiftOfShiftedLogic &MatchInfo)
If we have a shift-by-constant of a bitwise logic op that itself has a shift-by-constant operand with identical opcode, we may be able to convert that into 2 independent shifts followed by the logic op.
void applyShiftOfShiftedLogic (MachineInstr &MI, ShiftOfShiftedLogic &MatchInfo)
bool matchCombineMulToShl (MachineInstr &MI, unsigned &ShiftVal)
Transform a multiply by a power-of-2 value to a left shift.
void applyCombineMulToShl (MachineInstr &MI, unsigned &ShiftVal)
bool matchCombineShlOfExtend (MachineInstr &MI, RegisterImmPair &MatchData)
void applyCombineShlOfExtend (MachineInstr &MI, const RegisterImmPair &MatchData)
bool matchCombineMergeUnmerge (MachineInstr &MI, Register &MatchInfo)
Fold away a merge of an unmerge of the corresponding values.
bool matchCombineShiftToUnmerge (MachineInstr &MI, unsigned TargetShiftSize, unsigned &ShiftVal)
Reduce a shift by a constant to an unmerge and a shift on a half sized type.
void applyCombineShiftToUnmerge (MachineInstr &MI, const unsigned &ShiftVal)
bool tryCombineShiftToUnmerge (MachineInstr &MI, unsigned TargetShiftAmount)
bool matchCombineUnmergeMergeToPlainValues (MachineInstr &MI, SmallVectorImpl< Register > &Operands)
Transform <ty,...> G_UNMERGE(G_MERGE ty X, Y, Z) -> ty X, Y, Z.
void applyCombineUnmergeMergeToPlainValues (MachineInstr &MI, SmallVectorImpl< Register > &Operands)
bool matchCombineUnmergeConstant (MachineInstr &MI, SmallVectorImpl< APInt > &Csts)
Transform G_UNMERGE Constant -> Constant1, Constant2, ...
void applyCombineUnmergeConstant (MachineInstr &MI, SmallVectorImpl< APInt > &Csts)
bool matchCombineUnmergeWithDeadLanesToTrunc (MachineInstr &MI)
Transform X, Y<dead> = G_UNMERGE Z -> X = G_TRUNC Z.
void applyCombineUnmergeWithDeadLanesToTrunc (MachineInstr &MI)
bool matchCombineUnmergeZExtToZExt (MachineInstr &MI)
Transform X, Y = G_UNMERGE(G_ZEXT(Z)) -> X = G_ZEXT(Z); Y = G_CONSTANT 0.
void applyCombineUnmergeZExtToZExt (MachineInstr &MI)
bool matchCombineConstantFoldFpUnary (MachineInstr &MI, Optional< APFloat > &Cst)
Transform fp_instr(cst) to constant result of the fp operation.
void applyCombineConstantFoldFpUnary (MachineInstr &MI, Optional< APFloat > &Cst)
bool matchCombineI2PToP2I (MachineInstr &MI, Register &Reg)
Transform IntToPtr(PtrToInt(x)) to x if cast is in the same address space.
void applyCombineI2PToP2I (MachineInstr &MI, Register &Reg)
bool matchCombineP2IToI2P (MachineInstr &MI, Register &Reg)
Transform PtrToInt(IntToPtr(x)) to x.
void applyCombineP2IToI2P (MachineInstr &MI, Register &Reg)
bool matchCombineAddP2IToPtrAdd (MachineInstr &MI, std::pair< Register, bool > &PtrRegAndCommute)
Transform G_ADD (G_PTRTOINT x), y -> G_PTRTOINT (G_PTR_ADD x, y) Transform G_ADD y, (G_PTRTOINT x) -> G_PTRTOINT (G_PTR_ADD x, y)
void applyCombineAddP2IToPtrAdd (MachineInstr &MI, std::pair< Register, bool > &PtrRegAndCommute)
bool matchCombineConstPtrAddToI2P (MachineInstr &MI, int64_t &NewCst)
void applyCombineConstPtrAddToI2P (MachineInstr &MI, int64_t &NewCst)
bool matchCombineAnyExtTrunc (MachineInstr &MI, Register &Reg)
Transform anyext(trunc(x)) to x.
void applyCombineAnyExtTrunc (MachineInstr &MI, Register &Reg)
bool matchCombineZextTrunc (MachineInstr &MI, Register &Reg)
Transform zext(trunc(x)) to x.
bool matchCombineExtOfExt (MachineInstr &MI, std::tuple< Register, unsigned > &MatchInfo)
Transform [asz]ext([asz]ext(x)) to [asz]ext x.
void applyCombineExtOfExt (MachineInstr &MI, std::tuple< Register, unsigned > &MatchInfo)
bool matchCombineFNegOfFNeg (MachineInstr &MI, Register &Reg)
Transform fneg(fneg(x)) to x.
bool matchCombineFAbsOfFAbs (MachineInstr &MI, Register &Src)
Match fabs(fabs(x)) to fabs(x).
void applyCombineFAbsOfFAbs (MachineInstr &MI, Register &Src)
bool matchCombineTruncOfExt (MachineInstr &MI, std::pair< Register, unsigned > &MatchInfo)
Transform trunc ([asz]ext x) to x or ([asz]ext x) or (trunc x).
void applyCombineTruncOfExt (MachineInstr &MI, std::pair< Register, unsigned > &MatchInfo)
bool matchCombineTruncOfShl (MachineInstr &MI, std::pair< Register, Register > &MatchInfo)
Transform trunc (shl x, K) to shl (trunc x), K => K < VT.getScalarSizeInBits().
void applyCombineTruncOfShl (MachineInstr &MI, std::pair< Register, Register > &MatchInfo)
void applyCombineMulByNegativeOne (MachineInstr &MI)
Transform G_MUL(x, -1) to G_SUB(0, x)
bool matchAnyExplicitUseIsUndef (MachineInstr &MI)
Return true if any explicit use operand on MI is defined by a G_IMPLICIT_DEF.
bool matchAllExplicitUsesAreUndef (MachineInstr &MI)
Return true if all register explicit use operands on MI are defined by a G_IMPLICIT_DEF.
bool matchUndefShuffleVectorMask (MachineInstr &MI)
Return true if a G_SHUFFLE_VECTOR instruction MI has an undef mask.
bool matchUndefStore (MachineInstr &MI)
Return true if a G_STORE instruction MI is storing an undef value.
bool matchUndefSelectCmp (MachineInstr &MI)
Return true if a G_SELECT instruction MI has an undef comparison.
bool matchConstantSelectCmp (MachineInstr &MI, unsigned &OpIdx)
Return true if a G_SELECT instruction MI has a constant comparison.
bool replaceInstWithFConstant (MachineInstr &MI, double C)
Replace an instruction with a G_FCONSTANT with value C.
bool replaceInstWithConstant (MachineInstr &MI, int64_t C)
Replace an instruction with a G_CONSTANT with value C.
bool replaceInstWithConstant (MachineInstr &MI, APInt C)
Replace an instruction with a G_CONSTANT with value C.
bool replaceInstWithUndef (MachineInstr &MI)
Replace an instruction with a G_IMPLICIT_DEF.
bool replaceSingleDefInstWithOperand (MachineInstr &MI, unsigned OpIdx)
Delete MI and replace all of its uses with its OpIdx-th operand.
bool replaceSingleDefInstWithReg (MachineInstr &MI, Register Replacement)
Delete MI and replace all of its uses with Replacement.
bool matchEqualDefs (const MachineOperand &MOP1, const MachineOperand &MOP2)
Return true if MOP1 and MOP2 are register operands are defined by equivalent instructions.
bool matchConstantOp (const MachineOperand &MOP, int64_t C)
Return true if MOP is defined by a G_CONSTANT with a value equal to C.
bool matchSelectSameVal (MachineInstr &MI)
Optimize (cond ? x : x) -> x.
bool matchBinOpSameVal (MachineInstr &MI)
Optimize (x op x) -> x.
bool matchOperandIsZero (MachineInstr &MI, unsigned OpIdx)
Check if operand OpIdx is zero.
bool matchOperandIsUndef (MachineInstr &MI, unsigned OpIdx)
Check if operand OpIdx is undef.
bool matchOperandIsKnownToBeAPowerOfTwo (MachineInstr &MI, unsigned OpIdx)
Check if operand OpIdx is known to be a power of 2.
bool eraseInst (MachineInstr &MI)
Erase MI.
bool matchSimplifyAddToSub (MachineInstr &MI, std::tuple< Register, Register > &MatchInfo)
Return true if MI is a G_ADD which can be simplified to a G_SUB.
void applySimplifyAddToSub (MachineInstr &MI, std::tuple< Register, Register > &MatchInfo)
bool matchHoistLogicOpWithSameOpcodeHands (MachineInstr &MI, InstructionStepsMatchInfo &MatchInfo)
Match (logic_op (op x...), (op y...)) -> (op (logic_op x, y))
void applyBuildInstructionSteps (MachineInstr &MI, InstructionStepsMatchInfo &MatchInfo)
Replace MI with a series of instructions described in MatchInfo.
bool matchAshrShlToSextInreg (MachineInstr &MI, std::tuple< Register, int64_t > &MatchInfo)
Match ashr (shl x, C), C -> sext_inreg (C)
void applyAshShlToSextInreg (MachineInstr &MI, std::tuple< Register, int64_t > &MatchInfo)
bool matchOverlappingAnd (MachineInstr &MI, std::function< void(MachineIRBuilder &)> &MatchInfo)
Fold and(and(x, C1), C2) -> C1&C2 ? and(x, C1&C2) : 0.
bool matchRedundantAnd (MachineInstr &MI, Register &Replacement)
bool matchRedundantOr (MachineInstr &MI, Register &Replacement)
bool matchRedundantSExtInReg (MachineInstr &MI)
bool matchNotCmp (MachineInstr &MI, SmallVectorImpl< Register > &RegsToNegate)
Combine inverting a result of a compare into the opposite cond code.
void applyNotCmp (MachineInstr &MI, SmallVectorImpl< Register > &RegsToNegate)
bool matchXorOfAndWithSameReg (MachineInstr &MI, std::pair< Register, Register > &MatchInfo)
Fold (xor (and x, y), y) -> (and (not x), y) {.
void applyXorOfAndWithSameReg (MachineInstr &MI, std::pair< Register, Register > &MatchInfo)
bool matchPtrAddZero (MachineInstr &MI)
}
void applyPtrAddZero (MachineInstr &MI)
void applySimplifyURemByPow2 (MachineInstr &MI)
Combine G_UREM x, (known power of 2) to an add and bitmasking.
bool matchCombineInsertVecElts (MachineInstr &MI, SmallVectorImpl< Register > &MatchInfo)
void applyCombineInsertVecElts (MachineInstr &MI, SmallVectorImpl< Register > &MatchInfo)
bool matchLoadOrCombine (MachineInstr &MI, std::function< void(MachineIRBuilder &)> &MatchInfo)
Match expression trees of the form.
bool matchExtendThroughPhis (MachineInstr &MI, MachineInstr *&ExtMI)
void applyExtendThroughPhis (MachineInstr &MI, MachineInstr *&ExtMI)
bool matchExtractVecEltBuildVec (MachineInstr &MI, Register &Reg)
void applyExtractVecEltBuildVec (MachineInstr &MI, Register &Reg)
bool matchExtractAllEltsFromBuildVector (MachineInstr &MI, SmallVectorImpl< std::pair< Register, MachineInstr * >> &MatchInfo)
void applyExtractAllEltsFromBuildVector (MachineInstr &MI, SmallVectorImpl< std::pair< Register, MachineInstr * >> &MatchInfo)
void applyBuildFn (MachineInstr &MI, std::function< void(MachineIRBuilder &)> &MatchInfo)
Use a function which takes in a MachineIRBuilder to perform a combine.
void applyBuildFnNoErase (MachineInstr &MI, std::function< void(MachineIRBuilder &)> &MatchInfo)
Use a function which takes in a MachineIRBuilder to perform a combine.
bool matchFunnelShiftToRotate (MachineInstr &MI)
Match an FSHL or FSHR that can be combined to a ROTR or ROTL rotate.
void applyFunnelShiftToRotate (MachineInstr &MI)
bool matchRotateOutOfRange (MachineInstr &MI)
void applyRotateOutOfRange (MachineInstr &MI)
bool matchICmpToTrueFalseKnownBits (MachineInstr &MI, int64_t &MatchInfo)
bool matchBitfieldExtractFromSExtInReg (MachineInstr &MI, std::function< void(MachineIRBuilder &)> &MatchInfo)
Form a G_SBFX from a G_SEXT_INREG fed by a right shift.
bool matchBitfieldExtractFromAnd (MachineInstr &MI, std::function< void(MachineIRBuilder &)> &MatchInfo)
Match: and (lshr x, cst), mask -> ubfx x, cst, width.
bool matchReassocPtrAdd (MachineInstr &MI, std::function< void(MachineIRBuilder &)> &MatchInfo)
Reassociate pointer calculations with G_ADD involved, to allow better addressing mode usage.
bool matchConstantFold (MachineInstr &MI, APInt &MatchInfo)
Do constant folding when opportunities are exposed after MIR building.
bool tryCombine (MachineInstr &MI)
Try to transform MI by using all of the above combine functions.
bool tryEmitMemcpyInline (MachineInstr &MI)
Emit loads and stores that perform the given memcpy.
Protected Attributes
MachineIRBuilder & Builder
MachineRegisterInfo & MRI
GISelChangeObserver & Observer
GISelKnownBits * KB
MachineDominatorTree * MDT
const LegalizerInfo * LI
Detailed Description
Definition at line 90 of file CombinerHelper.h.
Constructor & Destructor Documentation
CombinerHelper()
CombinerHelper::CombinerHelper (GISelChangeObserver & Observer, MachineIRBuilder & B, GISelKnownBits * KB = nullptr, MachineDominatorTree * MDT = nullptr, const LegalizerInfo * LI = nullptr)
Definition at line 45 of file CombinerHelper.cpp.
Member Function Documentation
applyAshShlToSextInreg()
void CombinerHelper::applyAshShlToSextInreg (MachineInstr & MI, std::tuple< Register, int64_t > & MatchInfo)
Definition at line 3039 of file CombinerHelper.cpp.
References assert(), Builder, llvm::MachineIRBuilder::buildSExtInReg(), llvm::LLT::getScalarSizeInBits(), llvm::MachineRegisterInfo::getType(), MI, MRI, llvm::MachineIRBuilder::setInstrAndDebugLoc(), and llvm::Check::Size.
applyBuildFn()
void CombinerHelper::applyBuildFn (MachineInstr & MI, std::function< void(MachineIRBuilder &)> & MatchInfo)
Use a function which takes in a MachineIRBuilder to perform a combine.
By default, it erases the instruction MI from the function.
Definition at line 3946 of file CombinerHelper.cpp.
References Builder, MI, and llvm::MachineIRBuilder::setInstrAndDebugLoc().
applyBuildFnNoErase()
void CombinerHelper::applyBuildFnNoErase (MachineInstr & MI, std::function< void(MachineIRBuilder &)> & MatchInfo)
Use a function which takes in a MachineIRBuilder to perform a combine.
This variant does not erase MI after calling the build function.
Definition at line 3953 of file CombinerHelper.cpp.
References Builder, MI, and llvm::MachineIRBuilder::setInstrAndDebugLoc().
applyBuildInstructionSteps()
void CombinerHelper::applyBuildInstructionSteps (MachineInstr & MI, InstructionStepsMatchInfo & MatchInfo)
Replace MI with a series of instructions described in MatchInfo.
Definition at line 3006 of file CombinerHelper.cpp.
References assert(), Builder, llvm::MachineIRBuilder::buildInstr(), llvm::InstructionStepsMatchInfo::InstrsToBuild, MI, and llvm::MachineIRBuilder::setInstr().
applyCombineAddP2IToPtrAdd()
void CombinerHelper::applyCombineAddP2IToPtrAdd (MachineInstr & MI, std::pair< Register, bool > & PtrRegAndCommute)
Definition at line 2392 of file CombinerHelper.cpp.
References Builder, llvm::MachineIRBuilder::buildPtrAdd(), llvm::MachineIRBuilder::buildPtrToInt(), llvm::MachineRegisterInfo::getType(), MI, MRI, llvm::MachineIRBuilder::setInstrAndDebugLoc(), and std::swap().
applyCombineAnyExtTrunc()
void llvm::CombinerHelper::applyCombineAnyExtTrunc (MachineInstr & MI, Register & Reg)
applyCombineConcatVectors()
void CombinerHelper::applyCombineConcatVectors (MachineInstr & MI, bool IsUndef, const ArrayRef< Register > Ops)
Replace MI with a flattened build_vector with Ops or an implicit_def if IsUndef is true.
Definition at line 222 of file CombinerHelper.cpp.
References llvm::MachineIRBuilder::buildBuildVector(), Builder, llvm::MachineIRBuilder::buildUndef(), llvm::MachineRegisterInfo::cloneVirtualRegister(), MI, MRI, replaceRegWith(), and llvm::MachineIRBuilder::setInsertPt().
Referenced by tryCombineConcatVectors().
applyCombineConstantFoldFpUnary()
void CombinerHelper::applyCombineConstantFoldFpUnary (MachineInstr & MI, Optional< APFloat > & Cst)
Definition at line 1685 of file CombinerHelper.cpp.
References assert(), Builder, llvm::MachineIRBuilder::buildFConstant(), llvm::ConstantFP::get(), llvm::Function::getContext(), llvm::MachineFunction::getFunction(), llvm::MachineIRBuilder::getMF(), llvm::Optional< T >::hasValue(), MI, and llvm::MachineIRBuilder::setInstrAndDebugLoc().
applyCombineConstPtrAddToI2P()
void CombinerHelper::applyCombineConstPtrAddToI2P (MachineInstr & MI, int64_t & NewCst)
Definition at line 2429 of file CombinerHelper.cpp.
References assert(), llvm::MachineIRBuilder::buildConstant(), Builder, MI, and llvm::MachineIRBuilder::setInstrAndDebugLoc().
applyCombineCopy()
void CombinerHelper::applyCombineCopy (MachineInstr & MI)
Definition at line 160 of file CombinerHelper.cpp.
References MI, MRI, and replaceRegWith().
Referenced by tryCombineCopy().
applyCombineDivRem()
void CombinerHelper::applyCombineDivRem (MachineInstr & MI, MachineInstr *& OtherMI)
Definition at line 1005 of file CombinerHelper.cpp.
References assert(), Builder, llvm::MachineIRBuilder::buildInstr(), dominates(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), getReg(), MI, and llvm::MachineIRBuilder::setInstrAndDebugLoc().
applyCombineExtendingLoads()
void CombinerHelper::applyCombineExtendingLoads (MachineInstr & MI, PreferredTuple & MatchInfo)
rewrites to:
rewrites to:
Definition at line 516 of file CombinerHelper.cpp.
References Builder, llvm::MachineIRBuilder::buildTrunc(), llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::MachineRegisterInfo::cloneVirtualRegister(), llvm::MachineInstr::eraseFromParent(), llvm::GISelChangeObserver::erasingInstr(), llvm::PreferredTuple::ExtendOpcode, llvm::MCInstrInfo::get(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getParent(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::MachineIRBuilder::getTII(), llvm::MachineRegisterInfo::getType(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::lookup(), llvm::PreferredTuple::MI, MI, MRI, Observer, replaceRegOpWith(), replaceRegWith(), llvm::MachineIRBuilder::setInsertPt(), llvm::MachineOperand::setReg(), llvm::PreferredTuple::Ty, llvm::MachineRegisterInfo::use_operands(), UseMI, and Uses.
Referenced by tryCombineExtendingLoads().
applyCombineExtOfExt()
void CombinerHelper::applyCombineExtOfExt (MachineInstr & MI, std::tuple< Register, unsigned > & MatchInfo)
Definition at line 2483 of file CombinerHelper.cpp.
References assert(), Builder, llvm::MachineIRBuilder::buildInstr(), llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), MI, Observer, Reg, and llvm::MachineIRBuilder::setInstrAndDebugLoc().
applyCombineFAbsOfFAbs()
void llvm::CombinerHelper::applyCombineFAbsOfFAbs (MachineInstr & MI, Register & Src)
applyCombineI2PToP2I()
void CombinerHelper::applyCombineI2PToP2I (MachineInstr & MI, Register & Reg)
Definition at line 2345 of file CombinerHelper.cpp.
References assert(), llvm::MachineIRBuilder::buildCopy(), Builder, MI, Reg, and llvm::MachineIRBuilder::setInstr().
applyCombineIndexedLoadStore()
void CombinerHelper::applyCombineIndexedLoadStore (MachineInstr & MI, IndexedLoadStoreMatchInfo & MatchInfo)
Definition at line 901 of file CombinerHelper.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addImm(), llvm::IndexedLoadStoreMatchInfo::Addr, llvm::MachineInstrBuilder::addUse(), llvm::IndexedLoadStoreMatchInfo::Base, llvm::MachineIRBuilder::buildInstr(), llvm::dbgs(), llvm::MachineInstr::eraseFromParent(), llvm::MachineRegisterInfo::getUniqueVRegDef(), llvm::IndexedLoadStoreMatchInfo::IsPre, LLVM_DEBUG, llvm_unreachable, MI, MRI, and llvm::IndexedLoadStoreMatchInfo::Offset.
Referenced by tryCombineIndexedLoadStore().
applyCombineInsertVecElts()
void CombinerHelper::applyCombineInsertVecElts (MachineInstr & MI, SmallVectorImpl< Register > & MatchInfo)
Definition at line 2887 of file CombinerHelper.cpp.
References llvm::MachineIRBuilder::buildBuildVector(), Builder, llvm::MachineIRBuilder::buildUndef(), getReg(), llvm::LLT::getScalarType(), llvm::MachineRegisterInfo::getType(), I, MI, MRI, and llvm::MachineIRBuilder::setInstr().
applyCombineMulByNegativeOne()
void CombinerHelper::applyCombineMulByNegativeOne (MachineInstr & MI)
Transform G_MUL(x, -1) to G_SUB(0, x)
Definition at line 2514 of file CombinerHelper.cpp.
References assert(), llvm::MachineIRBuilder::buildConstant(), Builder, llvm::MachineIRBuilder::buildSub(), llvm::MachineRegisterInfo::getType(), MI, MRI, and llvm::MachineIRBuilder::setInstrAndDebugLoc().
applyCombineMulToShl()
void CombinerHelper::applyCombineMulToShl (MachineInstr & MI, unsigned & ShiftVal)
Definition at line 1953 of file CombinerHelper.cpp.
References assert(), llvm::MachineIRBuilder::buildConstant(), llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::MCInstrInfo::get(), llvm::MachineIRBuilder::getTII(), llvm::MachineRegisterInfo::getType(), MI, MRI, and Observer.
applyCombineP2IToI2P()
void CombinerHelper::applyCombineP2IToI2P (MachineInstr & MI, Register & Reg)
Definition at line 2359 of file CombinerHelper.cpp.
References assert(), Builder, llvm::MachineIRBuilder::buildZExtOrTrunc(), MI, Reg, and llvm::MachineIRBuilder::setInstr().
applyCombineShiftToUnmerge()
void CombinerHelper::applyCombineShiftToUnmerge (MachineInstr & MI, const unsigned & ShiftVal)
Definition at line 2252 of file CombinerHelper.cpp.
References assert(), llvm::MachineIRBuilder::buildAShr(), llvm::MachineIRBuilder::buildConstant(), Builder, llvm::MachineIRBuilder::buildLShr(), llvm::MachineIRBuilder::buildMerge(), llvm::MachineIRBuilder::buildShl(), llvm::MachineIRBuilder::buildUnmerge(), llvm::MachineInstrBuilder::getReg(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::MipsISD::Hi, llvm::MipsISD::Lo, MI, MRI, llvm::LLT::scalar(), llvm::MachineIRBuilder::setInstr(), and llvm::Check::Size.
Referenced by tryCombineShiftToUnmerge().
applyCombineShlOfExtend()
void CombinerHelper::applyCombineShlOfExtend (MachineInstr & MI, const RegisterImmPair & MatchData)
Definition at line 2003 of file CombinerHelper.cpp.
References llvm::MachineIRBuilder::buildConstant(), Builder, llvm::MachineIRBuilder::buildShl(), llvm::MachineIRBuilder::buildZExt(), llvm::MachineRegisterInfo::getType(), llvm::RegisterImmPair::Imm, MI, MRI, llvm::RegisterImmPair::Reg, and llvm::MachineIRBuilder::setInstrAndDebugLoc().
applyCombineShuffleVector()
void CombinerHelper::applyCombineShuffleVector (MachineInstr & MI, const ArrayRef< Register > Ops)
Replace MI with a concat_vectors with Ops.
Definition at line 329 of file CombinerHelper.cpp.
References llvm::MachineIRBuilder::buildCopy(), Builder, llvm::MachineIRBuilder::buildMerge(), llvm::MachineRegisterInfo::cloneVirtualRegister(), MI, MRI, replaceRegWith(), llvm::MachineIRBuilder::setInsertPt(), and llvm::ArrayRef< T >::size().
Referenced by tryCombineShuffleVector().
applyCombineTruncOfExt()
void CombinerHelper::applyCombineTruncOfExt (MachineInstr & MI, std::pair< Register, unsigned > & MatchInfo)
Definition at line 2553 of file CombinerHelper.cpp.
References assert(), Builder, llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildTrunc(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), MI, MRI, replaceRegWith(), and llvm::MachineIRBuilder::setInstrAndDebugLoc().
applyCombineTruncOfShl()
void CombinerHelper::applyCombineTruncOfShl (MachineInstr & MI, std::pair< Register, Register > & MatchInfo)
Definition at line 2598 of file CombinerHelper.cpp.
References assert(), Builder, llvm::MachineIRBuilder::buildShl(), llvm::MachineIRBuilder::buildTrunc(), llvm::MachineInstr::getFlags(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), MI, MRI, and llvm::MachineIRBuilder::setInstrAndDebugLoc().
applyCombineUnmergeConstant()
void CombinerHelper::applyCombineUnmergeConstant (MachineInstr & MI, SmallVectorImpl< APInt > & Csts)
Definition at line 2119 of file CombinerHelper.cpp.
References assert(), llvm::MachineIRBuilder::buildConstant(), Builder, MI, and llvm::MachineIRBuilder::setInstrAndDebugLoc().
applyCombineUnmergeMergeToPlainValues()
void CombinerHelper::applyCombineUnmergeMergeToPlainValues (MachineInstr & MI, SmallVectorImpl< Register > & Operands)
Definition at line 2071 of file CombinerHelper.cpp.
References assert(), llvm::MachineIRBuilder::buildCast(), Builder, llvm::MachineRegisterInfo::getType(), MI, MRI, Operands, replaceRegWith(), and llvm::MachineIRBuilder::setInstrAndDebugLoc().
applyCombineUnmergeWithDeadLanesToTrunc()
void CombinerHelper::applyCombineUnmergeWithDeadLanesToTrunc (MachineInstr & MI)
Definition at line 2146 of file CombinerHelper.cpp.
References llvm::MachineIRBuilder::buildCast(), Builder, llvm::MachineIRBuilder::buildTrunc(), llvm::MachineInstrBuilder::getReg(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::LLT::isVector(), MI, MRI, llvm::LLT::scalar(), and llvm::MachineIRBuilder::setInstrAndDebugLoc().
applyCombineUnmergeZExtToZExt()
void CombinerHelper::applyCombineUnmergeZExtToZExt (MachineInstr & MI)
Definition at line 2193 of file CombinerHelper.cpp.
References assert(), llvm::MachineIRBuilder::buildConstant(), Builder, llvm::MachineIRBuilder::buildZExt(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineInstrBuilder::getReg(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), MI, MRI, replaceRegWith(), and llvm::MachineIRBuilder::setInstrAndDebugLoc().
applyExtendThroughPhis()
void CombinerHelper::applyExtendThroughPhis (MachineInstr & MI, MachineInstr *& ExtMI)
Definition at line 3790 of file CombinerHelper.cpp.
References llvm::MachineInstrBuilder::addDef(), assert(), Builder, llvm::MachineIRBuilder::buildExtOrTrunc(), llvm::MachineIRBuilder::buildInstrNoInsert(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), llvm::MachineBasicBlock::getFirstNonPHI(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::insert(), llvm::MachineIRBuilder::insertInstr(), MBB, MI, MRI, llvm::MachineIRBuilder::setDebugLoc(), llvm::MachineIRBuilder::setInsertPt(), and llvm::MachineIRBuilder::setInstrAndDebugLoc().
applyExtractAllEltsFromBuildVector()
void CombinerHelper::applyExtractAllEltsFromBuildVector (MachineInstr & MI, SmallVectorImpl< std::pair< Register, MachineInstr * >> & MatchInfo)
Definition at line 3934 of file CombinerHelper.cpp.
References assert(), MI, MRI, and replaceRegWith().
applyExtractVecEltBuildVec()
void CombinerHelper::applyExtractVecEltBuildVec (MachineInstr & MI, Register & Reg)
Definition at line 3873 of file CombinerHelper.cpp.
References assert(), Builder, llvm::MachineIRBuilder::buildTrunc(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), MI, MRI, Reg, replaceSingleDefInstWithReg(), and llvm::MachineIRBuilder::setInstrAndDebugLoc().
applyFunnelShiftToRotate()
void CombinerHelper::applyFunnelShiftToRotate (MachineInstr & MI)
Definition at line 3972 of file CombinerHelper.cpp.
References assert(), Builder, llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::MCInstrInfo::get(), llvm::MachineIRBuilder::getTII(), MI, and Observer.
applyNotCmp()
void CombinerHelper::applyNotCmp (MachineInstr & MI, SmallVectorImpl< Register > & RegsToNegate)
Definition at line 3271 of file CombinerHelper.cpp.
References Builder, llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::tgtok::Def, llvm::MCInstrInfo::get(), llvm::CmpInst::getInversePredicate(), llvm::MachineOperand::getPredicate(), llvm::MachineIRBuilder::getTII(), llvm::MachineRegisterInfo::getVRegDef(), llvm_unreachable, MI, MRI, Observer, Reg, replaceRegWith(), and llvm::MachineOperand::setPredicate().
applyOptBrCondByInvertingCond()
void CombinerHelper::applyOptBrCondByInvertingCond (MachineInstr & MI, MachineInstr *& BrCond)
Definition at line 1071 of file CombinerHelper.cpp.
References llvm::MachineIRBuilder::buildConstant(), Builder, llvm::MachineIRBuilder::buildXor(), llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::getICmpTrueVal(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), MI, MRI, Observer, llvm::MachineIRBuilder::setInstrAndDebugLoc(), llvm::MachineOperand::setMBB(), and llvm::MachineOperand::setReg().
applyPtrAddImmedChain()
void CombinerHelper::applyPtrAddImmedChain (MachineInstr & MI, PtrAddChain & MatchInfo)
Definition at line 1736 of file CombinerHelper.cpp.
References assert(), llvm::PtrAddChain::Base, llvm::MachineIRBuilder::buildConstant(), llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::MachineRegisterInfo::getType(), llvm::PtrAddChain::Imm, MI, MRI, and Observer.
applyPtrAddZero()
void CombinerHelper::applyPtrAddZero (MachineInstr & MI)
Definition at line 3366 of file CombinerHelper.cpp.
References assert(), Builder, llvm::MachineIRBuilder::buildIntToPtr(), MI, and llvm::MachineIRBuilder::setInstrAndDebugLoc().
applyRotateOutOfRange()
void CombinerHelper::applyRotateOutOfRange (MachineInstr & MI)
Definition at line 3999 of file CombinerHelper.cpp.
References assert(), llvm::tgtok::Bits, llvm::MachineIRBuilder::buildConstant(), Builder, llvm::MachineIRBuilder::buildURem(), llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::MachineInstrBuilder::getReg(), llvm::LLT::getScalarSizeInBits(), llvm::MachineRegisterInfo::getType(), MI, MRI, Observer, and llvm::MachineIRBuilder::setInstrAndDebugLoc().
applySextInRegOfLoad()
void CombinerHelper::applySextInRegOfLoad (MachineInstr & MI, std::tuple< Register, unsigned > & MatchInfo)
Definition at line 718 of file CombinerHelper.cpp.
References assert(), Builder, llvm::MachineIRBuilder::buildLoadInstr(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineIRBuilder::getMF(), llvm::GLoadStore::getMMO(), llvm::GLoadStore::getPointerReg(), llvm::MachineRegisterInfo::getVRegDef(), MI, MRI, and llvm::MachineIRBuilder::setInstrAndDebugLoc().
applySextTruncSextLoad()
void CombinerHelper::applySextTruncSextLoad (MachineInstr & MI)
Definition at line 680 of file CombinerHelper.cpp.
References assert(), llvm::MachineIRBuilder::buildCopy(), Builder, MI, and llvm::MachineIRBuilder::setInstrAndDebugLoc().
applyShiftImmedChain()
void CombinerHelper::applyShiftImmedChain (MachineInstr & MI, RegisterImmPair & MatchInfo)
Definition at line 1793 of file CombinerHelper.cpp.
References assert(), llvm::MachineIRBuilder::buildConstant(), Builder, llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::MachineInstrBuilder::getReg(), llvm::LLT::getScalarSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::RegisterImmPair::Imm, MI, MRI, Observer, llvm::RegisterImmPair::Reg, and llvm::MachineIRBuilder::setInstrAndDebugLoc().
applyShiftOfShiftedLogic()
void CombinerHelper::applyShiftOfShiftedLogic (MachineInstr & MI, ShiftOfShiftedLogic & MatchInfo)
Definition at line 1907 of file CombinerHelper.cpp.
References assert(), llvm::MachineIRBuilder::buildConstant(), Builder, llvm::MachineIRBuilder::buildInstr(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), getReg(), llvm::MachineInstrBuilder::getReg(), llvm::MachineRegisterInfo::getType(), llvm::ShiftOfShiftedLogic::Logic, llvm::ShiftOfShiftedLogic::LogicNonShiftReg, MI, MRI, llvm::MachineIRBuilder::setInstrAndDebugLoc(), llvm::ShiftOfShiftedLogic::Shift2, and llvm::ShiftOfShiftedLogic::ValSum.
applySimplifyAddToSub()
void CombinerHelper::applySimplifyAddToSub (MachineInstr & MI, std::tuple< Register, Register > & MatchInfo)
Definition at line 2906 of file CombinerHelper.cpp.
References Builder, llvm::MachineIRBuilder::buildSub(), MI, and llvm::MachineIRBuilder::setInstr().
applySimplifyURemByPow2()
void CombinerHelper::applySimplifyURemByPow2 (MachineInstr & MI)
Combine G_UREM x, (known power of 2) to an add and bitmasking.
The second source operand is known to be a power of 2.
Definition at line 3374 of file CombinerHelper.cpp.
References llvm::MCID::Add, llvm::MachineIRBuilder::buildAdd(), llvm::MachineIRBuilder::buildAnd(), llvm::MachineIRBuilder::buildConstant(), Builder, llvm::MachineRegisterInfo::getType(), MI, MRI, and llvm::MachineIRBuilder::setInstrAndDebugLoc().
applyXorOfAndWithSameReg()
void CombinerHelper::applyXorOfAndWithSameReg (MachineInstr & MI, std::pair< Register, Register > & MatchInfo)
Definition at line 3334 of file CombinerHelper.cpp.
References Builder, llvm::MachineIRBuilder::buildNot(), llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::MCInstrInfo::get(), llvm::MachineIRBuilder::getTII(), llvm::MachineRegisterInfo::getType(), MI, MRI, Observer, llvm::MachineIRBuilder::setInstrAndDebugLoc(), X, and Y.
dominates()
bool CombinerHelper::dominates (const MachineInstr & DefMI, const MachineInstr & UseMI)
Returns true if DefMI dominates UseMI.
By definition an instruction dominates itself.
If we haven't been provided with a MachineDominatorTree during construction, this function returns a conservative result that tracks just a single basic block.
Definition at line 642 of file CombinerHelper.cpp.
References assert(), DefMI, llvm::MachineDominatorTree::dominates(), isPredecessor(), MDT, and UseMI.
Referenced by applyCombineDivRem().
eraseInst()
bool CombinerHelper::eraseInst (MachineInstr & MI)
Erase MI.
Definition at line 2656 of file CombinerHelper.cpp.
References MI.
getKnownBits()
GISelKnownBits* llvm::CombinerHelper::getKnownBits () const inline
Definition at line 105 of file CombinerHelper.h.
References KB.
getTargetLowering()
const TargetLowering & CombinerHelper::getTargetLowering () const
Definition at line 54 of file CombinerHelper.cpp.
References Builder, llvm::MachineIRBuilder::getMF(), llvm::MachineFunction::getSubtarget(), and llvm::TargetSubtargetInfo::getTargetLowering().
Referenced by applyOptBrCondByInvertingCond(), matchBitfieldExtractFromAnd(), matchBitfieldExtractFromSExtInReg(), matchCombineShlOfExtend(), matchCombineTruncOfShl(), matchExtractVecEltBuildVec(), matchICmpToTrueFalseKnownBits(), and matchLoadOrCombine().
isLegalOrBeforeLegalizer()
bool CombinerHelper::isLegalOrBeforeLegalizer (const LegalityQuery & Query) const
Returns
true if the combine is running prior to legalization, or if Query is legal on the target.
Definition at line 118 of file CombinerHelper.cpp.
References llvm::LegalizeActionStep::Action, llvm::LegalizerInfo::getAction(), llvm::LegalizeActions::Legal, and LI.
Referenced by matchAshrShlToSextInreg(), matchCombineDivRem(), matchCombineShlOfExtend(), matchCombineTruncOfShl(), matchExtractVecEltBuildVec(), matchFunnelShiftToRotate(), matchHoistLogicOpWithSameOpcodeHands(), and matchLoadOrCombine().
isPredecessor()
bool CombinerHelper::isPredecessor (const MachineInstr & DefMI, const MachineInstr & UseMI)
Returns true if DefMI precedes UseMI or they are the same instruction.
Both must be in the same basic block.
Definition at line 626 of file CombinerHelper.cpp.
References assert(), DefMI, llvm::MachineBasicBlock::end(), llvm::find_if(), llvm_unreachable, MBB, MI, and UseMI.
Referenced by dominates().
matchAllExplicitUsesAreUndef()
bool CombinerHelper::matchAllExplicitUsesAreUndef (MachineInstr & MI)
Return true if all register explicit use operands on MI are defined by a G_IMPLICIT_DEF.
Definition at line 2621 of file CombinerHelper.cpp.
References llvm::all_of(), and MI.
matchAnyExplicitUseIsUndef()
bool CombinerHelper::matchAnyExplicitUseIsUndef (MachineInstr & MI)
Return true if any explicit use operand on MI is defined by a G_IMPLICIT_DEF.
Definition at line 2614 of file CombinerHelper.cpp.
References llvm::any_of(), and MI.
matchAshrShlToSextInreg()
bool CombinerHelper::matchAshrShlToSextInreg (MachineInstr & MI, std::tuple< Register, int64_t > & MatchInfo)
Match ashr (shl x, C), C -> sext_inreg (C)
Definition at line 3021 of file CombinerHelper.cpp.
References assert(), llvm::MachineRegisterInfo::getType(), isLegalOrBeforeLegalizer(), llvm::MIPatternMatch::m_GAShr(), llvm::MIPatternMatch::m_GShl(), llvm::MIPatternMatch::m_ICst(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchBinOpSameVal()
bool CombinerHelper::matchBinOpSameVal (MachineInstr & MI)
Optimize (x op x) -> x.
Definition at line 2770 of file CombinerHelper.cpp.
References llvm::canReplaceReg(), matchEqualDefs(), MI, and MRI.
matchBitfieldExtractFromAnd()
bool CombinerHelper::matchBitfieldExtractFromAnd (MachineInstr & MI, std::function< void(MachineIRBuilder &)> & MatchInfo)
Match: and (lshr x, cst), mask -> ubfx x, cst, width.
Form a G_UBFX from "(a srl b) & mask", where b and mask are constants.
Definition at line 4097 of file CombinerHelper.cpp.
References assert(), B, llvm::APInt::countTrailingOnes(), llvm::TargetLoweringBase::getPreferredShiftAmountTy(), llvm::LLT::getScalarSizeInBits(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::MIPatternMatch::m_GAnd(), llvm::MIPatternMatch::m_GLShr(), llvm::MIPatternMatch::m_ICst(), llvm::MIPatternMatch::m_OneNonDBGUse(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, and llvm::Check::Size.
matchBitfieldExtractFromSExtInReg()
bool CombinerHelper::matchBitfieldExtractFromSExtInReg (MachineInstr & MI, std::function< void(MachineIRBuilder &)> & MatchInfo)
Form a G_SBFX from a G_SEXT_INREG fed by a right shift.
Definition at line 4068 of file CombinerHelper.cpp.
References assert(), llvm::TargetLoweringBase::getPreferredShiftAmountTy(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::LegalizerInfo::isLegalOrCustom(), LI, MI, and MRI.
matchCombineAddP2IToPtrAdd()
bool CombinerHelper::matchCombineAddP2IToPtrAdd (MachineInstr & MI, std::pair< Register, bool > & PtrRegAndCommute)
Transform G_ADD (G_PTRTOINT x), y -> G_PTRTOINT (G_PTR_ADD x, y) Transform G_ADD y, (G_PTRTOINT x) -> G_PTRTOINT (G_PTR_ADD x, y)
Definition at line 2367 of file CombinerHelper.cpp.
References assert(), llvm::LLT::getScalarSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::MIPatternMatch::m_GPtrToInt(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchCombineAnyExtTrunc()
bool CombinerHelper::matchCombineAnyExtTrunc (MachineInstr & MI, Register & Reg)
Transform anyext(trunc(x)) to x.
Definition at line 2439 of file CombinerHelper.cpp.
References assert(), llvm::MachineRegisterInfo::getType(), llvm::MIPatternMatch::m_all_of(), llvm::MIPatternMatch::m_GTrunc(), llvm::MIPatternMatch::m_Reg(), llvm::MIPatternMatch::m_SpecificType(), MI, llvm::MIPatternMatch::mi_match(), MRI, and Reg.
matchCombineConcatVectors()
bool CombinerHelper::matchCombineConcatVectors (MachineInstr & MI, bool & IsUndef, SmallVectorImpl< Register > & Ops)
Check if the G_CONCAT_VECTORS MI is undef or if it can be flattened into a build_vector.
In the first case IsUndef will be true. In the second case Ops will contain the operands needed to produce the flattened build_vector.
Precondition
MI.getOpcode() == G_CONCAT_VECTORS.
Definition at line 177 of file CombinerHelper.cpp.
References assert(), Builder, llvm::MachineIRBuilder::buildUndef(), llvm::tgtok::Def, llvm::LLT::getNumElements(), llvm::LLT::getScalarType(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), MI, MRI, Reg, llvm::MachineIRBuilder::setInsertPt(), and llvm::RegState::Undef.
Referenced by tryCombineConcatVectors().
matchCombineConstantFoldFpUnary()
bool CombinerHelper::matchCombineConstantFoldFpUnary (MachineInstr & MI, Optional< APFloat > & Cst)
Transform fp_instr(cst) to constant result of the fp operation.
Definition at line 1676 of file CombinerHelper.cpp.
References constantFoldFpUnary(), llvm::MachineRegisterInfo::getType(), llvm::Optional< T >::hasValue(), MI, and MRI.
matchCombineConstPtrAddToI2P()
bool CombinerHelper::matchCombineConstPtrAddToI2P (MachineInstr & MI, int64_t & NewCst)
Definition at line 2411 of file CombinerHelper.cpp.
References assert(), Builder, llvm::getConstantVRegSExtVal(), llvm::MachineIRBuilder::getMF(), llvm::MachineFunction::getRegInfo(), llvm::MIPatternMatch::m_GIntToPtr(), llvm::MIPatternMatch::m_ICst(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchCombineCopy()
bool CombinerHelper::matchCombineCopy (MachineInstr & MI)
Definition at line 153 of file CombinerHelper.cpp.
References llvm::canReplaceReg(), MI, and MRI.
Referenced by tryCombineCopy().
matchCombineDivRem()
bool CombinerHelper::matchCombineDivRem (MachineInstr & MI, MachineInstr *& OtherMI)
Try to combine G_[SU]DIV and G_[SU]REM into a single G_[SU]DIVREM when their source operands are identical.
Definition at line 943 of file CombinerHelper.cpp.
References llvm::MachineRegisterInfo::getType(), isLegalOrBeforeLegalizer(), llvm_unreachable, matchEqualDefs(), MI, MRI, llvm::MachineRegisterInfo::use_nodbg_instructions(), and UseMI.
matchCombineExtendingLoads()
bool CombinerHelper::matchCombineExtendingLoads (MachineInstr & MI, PreferredTuple & MatchInfo)
Definition at line 438 of file CombinerHelper.cpp.
References llvm::LegalityQuery::MemDesc::AlignInBits, llvm::LegalizerInfo::getAction(), llvm::GAnyLoad::getDstReg(), llvm::GLoadStore::getMMO(), llvm::GLoadStore::getPointerReg(), llvm::MachineInstrBuilder::getReg(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::isPowerOf2_32(), llvm::LLT::isScalar(), llvm::LegalizeActions::Legal, LI, llvm::LegalityQuery::MemDesc::MemoryTy, MI, MRI, llvm::LegalityQuery::MemDesc::Ordering, llvm::MachineRegisterInfo::use_nodbg_instructions(), and UseMI.
Referenced by tryCombineExtendingLoads().
matchCombineExtOfExt()
bool CombinerHelper::matchCombineExtOfExt (MachineInstr & MI, std::tuple< Register, unsigned > & MatchInfo)
Transform [asz]ext([asz]ext(x)) to [asz]ext x.
Definition at line 2462 of file CombinerHelper.cpp.
References assert(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getVRegDef(), MI, and MRI.
matchCombineFAbsOfFAbs()
bool CombinerHelper::matchCombineFAbsOfFAbs (MachineInstr & MI, Register & Src)
Match fabs(fabs(x)) to fabs(x).
Definition at line 2532 of file CombinerHelper.cpp.
References assert(), llvm::MIPatternMatch::m_GFabs(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchCombineFNegOfFNeg()
bool CombinerHelper::matchCombineFNegOfFNeg (MachineInstr & MI, Register & Reg)
Transform fneg(fneg(x)) to x.
Definition at line 2526 of file CombinerHelper.cpp.
References assert(), llvm::MIPatternMatch::m_GFNeg(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, and Reg.
matchCombineI2PToP2I()
bool CombinerHelper::matchCombineI2PToP2I (MachineInstr & MI, Register & Reg)
Transform IntToPtr(PtrToInt(x)) to x if cast is in the same address space.
Definition at line 2336 of file CombinerHelper.cpp.
References assert(), llvm::MachineRegisterInfo::getType(), llvm::MIPatternMatch::m_all_of(), llvm::MIPatternMatch::m_GPtrToInt(), llvm::MIPatternMatch::m_Reg(), llvm::MIPatternMatch::m_SpecificType(), MI, llvm::MIPatternMatch::mi_match(), MRI, and Reg.
matchCombineIndexedLoadStore()
bool CombinerHelper::matchCombineIndexedLoadStore (MachineInstr & MI, IndexedLoadStoreMatchInfo & MatchInfo)
Definition at line 880 of file CombinerHelper.cpp.
References llvm::IndexedLoadStoreMatchInfo::Addr, llvm::IndexedLoadStoreMatchInfo::Base, ForceLegalIndexing, llvm::IndexedLoadStoreMatchInfo::IsPre, MI, and llvm::IndexedLoadStoreMatchInfo::Offset.
Referenced by tryCombineIndexedLoadStore().
matchCombineInsertVecElts()
bool CombinerHelper::matchCombineInsertVecElts (MachineInstr & MI, SmallVectorImpl< Register > & MatchInfo)
Definition at line 2846 of file CombinerHelper.cpp.
References assert(), llvm::LLT::getNumElements(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::hasOneUse(), I, isValid(), llvm::LLT::isVector(), llvm::MIPatternMatch::m_GInsertVecElt(), llvm::MIPatternMatch::m_ICst(), llvm::MIPatternMatch::m_MInstr(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, llvm::SmallVectorImpl< T >::resize(), and llvm::MachineRegisterInfo::use_instr_begin().
matchCombineMergeUnmerge()
bool CombinerHelper::matchCombineMergeUnmerge (MachineInstr & MI, Register & MatchInfo)
Fold away a merge of an unmerge of the corresponding values.
Definition at line 2017 of file CombinerHelper.cpp.
References llvm::SmallVectorImpl< T >::emplace_back(), I, Merge, MI, and MRI.
matchCombineMulToShl()
bool CombinerHelper::matchCombineMulToShl (MachineInstr & MI, unsigned & ShiftVal)
Transform a multiply by a power-of-2 value to a left shift.
Definition at line 1941 of file CombinerHelper.cpp.
References assert(), llvm::getConstantVRegValWithLookThrough(), MI, and MRI.
matchCombineP2IToI2P()
bool CombinerHelper::matchCombineP2IToI2P (MachineInstr & MI, Register & Reg)
Transform PtrToInt(IntToPtr(x)) to x.
Definition at line 2353 of file CombinerHelper.cpp.
References assert(), llvm::MIPatternMatch::m_GIntToPtr(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, and Reg.
matchCombineShiftToUnmerge()
bool CombinerHelper::matchCombineShiftToUnmerge (MachineInstr & MI, unsigned TargetShiftSize, unsigned & ShiftVal)
Reduce a shift by a constant to an unmerge and a shift on a half sized type.
This will not produce a shift smaller than TargetShiftSize.
Definition at line 2227 of file CombinerHelper.cpp.
References assert(), llvm::getConstantVRegValWithLookThrough(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::LLT::isVector(), MI, MRI, and llvm::Check::Size.
Referenced by tryCombineShiftToUnmerge().
matchCombineShlOfExtend()
bool CombinerHelper::matchCombineShlOfExtend (MachineInstr & MI, RegisterImmPair & MatchData)
Definition at line 1966 of file CombinerHelper.cpp.
References assert(), llvm::APInt::countLeadingOnes(), llvm::getConstantVRegValWithLookThrough(), llvm::GISelKnownBits::getKnownZeroes(), llvm::TargetLoweringBase::getPreferredShiftAmountTy(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::RegisterImmPair::Imm, isLegalOrBeforeLegalizer(), KB, LI, llvm::MIPatternMatch::m_GAnyExt(), llvm::MIPatternMatch::m_GSExt(), llvm::MIPatternMatch::m_GZExt(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, and llvm::RegisterImmPair::Reg.
matchCombineShuffleVector()
bool CombinerHelper::matchCombineShuffleVector (MachineInstr & MI, SmallVectorImpl< Register > & Ops)
Check if the G_SHUFFLE_VECTOR MI can be replaced by a concat_vectors.
Ops will contain the operands needed to produce the flattened concat_vectors.
Precondition
MI.getOpcode() == G_SHUFFLE_VECTOR.
Definition at line 253 of file CombinerHelper.cpp.
References assert(), Builder, llvm::MachineIRBuilder::buildUndef(), llvm::LLT::getNumElements(), llvm::MachineInstrBuilder::getReg(), llvm::MachineRegisterInfo::getType(), i, llvm::LLT::isVector(), llvm::BitmaskEnumDetail::Mask(), MI, MRI, and llvm::MachineIRBuilder::setInsertPt().
Referenced by tryCombineShuffleVector().
matchCombineTruncOfExt()
bool CombinerHelper::matchCombineTruncOfExt (MachineInstr & MI, std::pair< Register, unsigned > & MatchInfo)
Transform trunc ([asz]ext x) to x or ([asz]ext x) or (trunc x).
Definition at line 2539 of file CombinerHelper.cpp.
References assert(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getVRegDef(), MI, and MRI.
matchCombineTruncOfShl()
bool CombinerHelper::matchCombineTruncOfShl (MachineInstr & MI, std::pair< Register, Register > & MatchInfo)
Transform trunc (shl x, K) to shl (trunc x), K => K < VT.getScalarSizeInBits().
Definition at line 2574 of file CombinerHelper.cpp.
References assert(), llvm::KnownBits::countMinLeadingZeros(), llvm::KnownBits::getBitWidth(), llvm::GISelKnownBits::getKnownBits(), llvm::TargetLoweringBase::getPreferredShiftAmountTy(), llvm::LLT::getSizeInBits(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), isLegalOrBeforeLegalizer(), KB, llvm::Log2_32(), llvm::MIPatternMatch::m_GShl(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, and llvm::Check::Size.
matchCombineUnmergeConstant()
bool CombinerHelper::matchCombineUnmergeConstant (MachineInstr & MI, SmallVectorImpl< APInt > & Csts)
Transform G_UNMERGE Constant -> Constant1, Constant2, ...
Definition at line 2094 of file CombinerHelper.cpp.
References llvm::APFloat::bitcastToAPInt(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::MachineOperand::getCImm(), llvm::MachineOperand::getFPImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::ConstantInt::getValue(), llvm::ConstantFP::getValueAPF(), llvm::MachineRegisterInfo::getVRegDef(), llvm::APInt::lshr(), MI, MRI, and llvm::APInt::trunc().
matchCombineUnmergeMergeToPlainValues()
bool CombinerHelper::matchCombineUnmergeMergeToPlainValues (MachineInstr & MI, SmallVectorImpl< Register > & Operands)
Transform <ty,...> G_UNMERGE(G_MERGE ty X, Y, Z) -> ty X, Y, Z.
Definition at line 2044 of file CombinerHelper.cpp.
References assert(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), MI, MRI, Operands, and peekThroughBitcast().
matchCombineUnmergeWithDeadLanesToTrunc()
bool CombinerHelper::matchCombineUnmergeWithDeadLanesToTrunc (MachineInstr & MI)
Transform X, Y<dead> = G_UNMERGE Z -> X = G_TRUNC Z.
Definition at line 2135 of file CombinerHelper.cpp.
References assert(), MI, MRI, and llvm::MachineRegisterInfo::use_nodbg_empty().
matchCombineUnmergeZExtToZExt()
bool CombinerHelper::matchCombineUnmergeZExtToZExt (MachineInstr & MI)
Transform X, Y = G_UNMERGE(G_ZEXT(Z)) -> X = G_ZEXT(Z); Y = G_CONSTANT 0.
Definition at line 2167 of file CombinerHelper.cpp.
References assert(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::LLT::isVector(), llvm::MIPatternMatch::m_GZExt(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchCombineZextTrunc()
bool CombinerHelper::matchCombineZextTrunc (MachineInstr & MI, Register & Reg)
Transform zext(trunc(x)) to x.
Definition at line 2448 of file CombinerHelper.cpp.
References assert(), llvm::KnownBits::countMinLeadingZeros(), llvm::GISelKnownBits::getKnownBits(), llvm::LLT::getScalarSizeInBits(), llvm::MachineRegisterInfo::getType(), KB, llvm::MIPatternMatch::m_all_of(), llvm::MIPatternMatch::m_GTrunc(), llvm::MIPatternMatch::m_Reg(), llvm::MIPatternMatch::m_SpecificType(), MI, llvm::MIPatternMatch::mi_match(), MRI, and Reg.
matchConstantFold()
bool CombinerHelper::matchConstantFold (MachineInstr & MI, APInt & MatchInfo)
Do constant folding when opportunities are exposed after MIR building.
Definition at line 4257 of file CombinerHelper.cpp.
References llvm::ConstantFoldBinOp(), MI, and MRI.
matchConstantOp()
bool CombinerHelper::matchConstantOp (const MachineOperand & MOP, int64_t C)
Return true if MOP is defined by a G_CONSTANT with a value equal to C.
Definition at line 2733 of file CombinerHelper.cpp.
References llvm::getConstantVRegValWithLookThrough(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isReg(), and MRI.
Referenced by matchOperandIsZero().
matchConstantSelectCmp()
bool CombinerHelper::matchConstantSelectCmp (MachineInstr & MI, unsigned & OpIdx)
Return true if a G_SELECT instruction MI has a constant comparison.
If true, OpIdx will store the operand index of the known selected value.
Definition at line 2646 of file CombinerHelper.cpp.
References assert(), llvm::getConstantVRegValWithLookThrough(), MI, and MRI.
matchEqualDefs()
bool CombinerHelper::matchEqualDefs (const MachineOperand & MOP1, const MachineOperand & MOP2)
Return true if MOP1 and MOP2 are register operands are defined by equivalent instructions.
Definition at line 2661 of file CombinerHelper.cpp.
References llvm::any_of(), Builder, llvm::getDefIgnoringCopies(), llvm::MachineOperand::getReg(), llvm::MachineIRBuilder::getTII(), llvm::MachineInstr::isDereferenceableInvariantLoad(), llvm::MachineInstr::isIdenticalTo(), llvm::MachineOperand::isReg(), llvm::MachineInstr::mayLoadOrStore(), MRI, llvm::TargetInstrInfo::produceSameValue(), and llvm::MachineInstr::uses().
Referenced by matchBinOpSameVal(), matchCombineDivRem(), matchHoistLogicOpWithSameOpcodeHands(), and matchSelectSameVal().
matchExtendThroughPhis()
bool CombinerHelper::matchExtendThroughPhis (MachineInstr & MI, MachineInstr *& ExtMI)
Definition at line 3735 of file CombinerHelper.cpp.
References assert(), Builder, DefMI, llvm::getDefIgnoringCopies(), llvm::MachineInstr::getOpcode(), llvm::MachineIRBuilder::getTII(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::TargetInstrInfo::isExtendLikelyToBeFolded(), llvm::LLT::isVector(), MI, MRI, llvm::SmallPtrSetImplBase::size(), and llvm::MachineRegisterInfo::use_instr_nodbg_begin().
matchExtractAllEltsFromBuildVector()
bool CombinerHelper::matchExtractAllEltsFromBuildVector (MachineInstr & MI, SmallVectorImpl< std::pair< Register, MachineInstr * >> & MatchInfo)
Definition at line 3891 of file CombinerHelper.cpp.
References llvm::SmallBitVector::all(), assert(), llvm::getConstantVRegVal(), llvm::LLT::getNumElements(), llvm::MachineRegisterInfo::getType(), llvm::make_range(), MI, MRI, llvm::SmallBitVector::set(), llvm::MachineRegisterInfo::use_instr_nodbg_begin(), and llvm::MachineRegisterInfo::use_instr_nodbg_end().
matchExtractVecEltBuildVec()
bool CombinerHelper::matchExtractVecEltBuildVec (MachineInstr & MI, Register & Reg)
Definition at line 3836 of file CombinerHelper.cpp.
References assert(), llvm::getConstantVRegValWithLookThrough(), llvm::LLT::getElementType(), llvm::getMVTForLLT(), llvm::LLT::getNumElements(), llvm::getOpcodeDef(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), isLegalOrBeforeLegalizer(), MI, MRI, and Reg.
matchFunnelShiftToRotate()
bool CombinerHelper::matchFunnelShiftToRotate (MachineInstr & MI)
Match an FSHL or FSHR that can be combined to a ROTR or ROTL rotate.
Definition at line 3960 of file CombinerHelper.cpp.
References assert(), llvm::MachineRegisterInfo::getType(), isLegalOrBeforeLegalizer(), MI, MRI, X, and Y.
matchHoistLogicOpWithSameOpcodeHands()
bool CombinerHelper::matchHoistLogicOpWithSameOpcodeHands (MachineInstr & MI, InstructionStepsMatchInfo & MatchInfo)
Match (logic_op (op x...), (op y...)) -> (op (logic_op x, y))
Definition at line 2915 of file CombinerHelper.cpp.
References llvm::MachineInstrBuilder::addReg(), assert(), llvm::MachineRegisterInfo::createGenericVirtualRegister(), llvm::getDefIgnoringCopies(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), isLegalOrBeforeLegalizer(), llvm::MachineOperand::isReg(), llvm::Register::isValid(), matchEqualDefs(), MI, MRI, X, and Y.
matchICmpToTrueFalseKnownBits()
bool CombinerHelper::matchICmpToTrueFalseKnownBits (MachineInstr & MI, int64_t & MatchInfo)
Returns
true if a G_ICMP instruction MI can be replaced with a true or false constant based off of KnownBits information.
Definition at line 4014 of file CombinerHelper.cpp.
References assert(), llvm::KnownBits::eq(), llvm::getICmpTrueVal(), llvm::GISelKnownBits::getKnownBits(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::LLT::isVector(), KB, llvm_unreachable, MI, MRI, llvm::KnownBits::ne(), llvm::KnownBits::sge(), llvm::KnownBits::sgt(), llvm::KnownBits::sle(), llvm::KnownBits::slt(), llvm::KnownBits::uge(), llvm::KnownBits::ugt(), llvm::KnownBits::ule(), and llvm::KnownBits::ult().
matchLoadOrCombine()
bool CombinerHelper::matchLoadOrCombine (MachineInstr & MI, std::function< void(MachineIRBuilder &)> & MatchInfo)
Match expression trees of the form.
sN *a = ...
sM val = a[0] | (a[1] << N) | (a[2] << 2N) | (a[3] << 3N) ...
And check if the tree can be replaced with a M-bit load + possibly a bswap.
Definition at line 3620 of file CombinerHelper.cpp.
References llvm::LegalityQuery::MemDesc::AlignInBits, assert(), bigEndianByteAt(), llvm::MachineRegisterInfo::cloneVirtualRegister(), DL, llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, 4, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), llvm::Sched::Fast, llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, 4, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), llvm::MachineMemOperand::getAlign(), llvm::Function::getContext(), llvm::MachineFunction::getDataLayout(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::GLoadStore::getMMO(), llvm::MachineMemOperand::getPointerInfo(), llvm::GLoadStore::getPointerReg(), llvm::LLT::getSizeInBits(), llvm::MachineMemOperand::getSuccessOrdering(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::Optional< T >::hasValue(), llvm::DataLayout::isBigEndian(), isBigEndian(), isLegalOrBeforeLegalizer(), llvm::LLT::isVector(), littleEndianByteAt(), llvm::LegalityQuery::MemDesc::MemoryTy, MI, MRI, llvm::LegalityQuery::MemDesc::Ordering, and llvm::Align::value().
matchNotCmp()
bool CombinerHelper::matchNotCmp (MachineInstr & MI, SmallVectorImpl< Register > & RegsToNegate)
Combine inverting a result of a compare into the opposite cond code.
Definition at line 3194 of file CombinerHelper.cpp.
References assert(), Builder, llvm::tgtok::Def, llvm::getBuildVectorConstantSplat(), llvm::MachineIRBuilder::getMF(), llvm::LLT::getScalarSizeInBits(), llvm::LLT::getSizeInBits(), llvm::MachineFunction::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), I, isConstValidTrue(), llvm::LLT::isVector(), llvm::MIPatternMatch::m_GXor(), llvm::MIPatternMatch::m_ICst(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, and Reg.
matchOperandIsKnownToBeAPowerOfTwo()
bool CombinerHelper::matchOperandIsKnownToBeAPowerOfTwo (MachineInstr & MI, unsigned OpIdx)
Check if operand OpIdx is known to be a power of 2.
Definition at line 2788 of file CombinerHelper.cpp.
References llvm::MachineOperand::getReg(), llvm::isKnownToBeAPowerOfTwo(), KB, MI, and MRI.
matchOperandIsUndef()
bool CombinerHelper::matchOperandIsUndef (MachineInstr & MI, unsigned OpIdx)
Check if operand OpIdx is undef.
Definition at line 2782 of file CombinerHelper.cpp.
References llvm::getOpcodeDef(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isReg(), MI, and MRI.
matchOperandIsZero()
bool CombinerHelper::matchOperandIsZero (MachineInstr & MI, unsigned OpIdx)
Check if operand OpIdx is zero.
Definition at line 2776 of file CombinerHelper.cpp.
References llvm::canReplaceReg(), matchConstantOp(), MI, and MRI.
matchOptBrCondByInvertingCond()
bool CombinerHelper::matchOptBrCondByInvertingCond (MachineInstr & MI, MachineInstr *& BrCond)
If a brcond's true block is not the fallthrough, make it so by inverting the condition and swapping operands.
Definition at line 1037 of file CombinerHelper.cpp.
References assert(), llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::isLayoutSuccessor(), MBB, and MI.
matchOverlappingAnd()
bool CombinerHelper::matchOverlappingAnd (MachineInstr & MI, std::function< void(MachineIRBuilder &)> & MatchInfo)
Fold and(and(x, C1), C2) -> C1&C2 ? and(x, C1&C2) : 0.
and(and(x, C1), C2) -> C1&C2 ? and(x, C1&C2) : 0
Definition at line 3052 of file CombinerHelper.cpp.
References assert(), B, C1, llvm::MachineRegisterInfo::getType(), llvm::MIPatternMatch::m_GAnd(), llvm::MIPatternMatch::m_ICst(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, llvm::RISCVFenceField::R, and replaceRegWith().
matchPtrAddImmedChain()
bool CombinerHelper::matchPtrAddImmedChain (MachineInstr & MI, PtrAddChain & MatchInfo)
Definition at line 1696 of file CombinerHelper.cpp.
References llvm::PtrAddChain::Base, llvm::sampleprof::Base, llvm::getConstantVRegValWithLookThrough(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getUniqueVRegDef(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), llvm::PtrAddChain::Imm, MI, and MRI.
matchPtrAddZero()
bool CombinerHelper::matchPtrAddZero (MachineInstr & MI)
}
Combine G_PTR_ADD with nullptr to G_INTTOPTR
Definition at line 3348 of file CombinerHelper.cpp.
References assert(), Builder, DL, llvm::LLT::getAddressSpace(), llvm::getConstantVRegVal(), llvm::MachineFunction::getDataLayout(), llvm::MachineIRBuilder::getMF(), llvm::LLT::getScalarType(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), llvm::isBuildVectorAllZeros(), llvm::LLT::isPointer(), llvm::LLT::isVector(), MI, and MRI.
matchReassocPtrAdd()
bool CombinerHelper::matchReassocPtrAdd (MachineInstr & MI, std::function< void(MachineIRBuilder &)> & MatchInfo)
Reassociate pointer calculations with G_ADD involved, to allow better addressing mode usage.
Definition at line 4201 of file CombinerHelper.cpp.
References assert(), B, Builder, llvm::MachineIRBuilder::buildPtrAdd(), C1, llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::getConstantVRegVal(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), MI, MRI, and Observer.
matchRedundantAnd()
bool CombinerHelper::matchRedundantAnd (MachineInstr & MI, Register & Replacement)
Returns
true if MI is a G_AND instruction whose operands are x and y where x & y == x or x & y == y. (E.g., one of operands is all-ones value.)
Parameters
[in] MI - The G_AND instruction.
[out] Replacement - A register the G_AND should be replaced with on success.
Definition at line 3078 of file CombinerHelper.cpp.
References assert(), llvm::canReplaceReg(), llvm::GISelKnownBits::getKnownBits(), llvm::MachineRegisterInfo::getType(), llvm::LLT::isVector(), KB, MI, MRI, llvm::KnownBits::One, and llvm::KnownBits::Zero.
matchRedundantOr()
bool CombinerHelper::matchRedundantOr (MachineInstr & MI, Register & Replacement)
Returns
true if MI is a G_OR instruction whose operands are x and y where x | y == x or x | y == y. (E.g., one of operands is all-zeros value.)
Parameters
[in] MI - The G_OR instruction.
[out] Replacement - A register the G_OR should be replaced with on success.
Definition at line 3133 of file CombinerHelper.cpp.
References assert(), llvm::canReplaceReg(), llvm::GISelKnownBits::getKnownBits(), llvm::MachineRegisterInfo::getType(), llvm::LLT::isVector(), KB, MI, MRI, llvm::KnownBits::One, and llvm::KnownBits::Zero.
matchRedundantSExtInReg()
bool CombinerHelper::matchRedundantSExtInReg (MachineInstr & MI)
Returns
true if MI is a G_SEXT_INREG that can be erased.
Definition at line 3179 of file CombinerHelper.cpp.
References llvm::GISelKnownBits::computeNumSignBits(), llvm::LLT::getScalarSizeInBits(), llvm::MachineRegisterInfo::getType(), KB, MI, and MRI.
matchRotateOutOfRange()
bool CombinerHelper::matchRotateOutOfRange (MachineInstr & MI)
Definition at line 3984 of file CombinerHelper.cpp.
References assert(), llvm::LLT::getScalarSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::matchUnaryPredicate(), MI, and MRI.
matchSelectSameVal()
bool CombinerHelper::matchSelectSameVal (MachineInstr & MI)
Optimize (cond ? x : x) -> x.
Definition at line 2762 of file CombinerHelper.cpp.
References assert(), llvm::canReplaceReg(), matchEqualDefs(), MI, and MRI.
matchSextInRegOfLoad()
bool CombinerHelper::matchSextInRegOfLoad (MachineInstr & MI, std::tuple< Register, unsigned > & MatchInfo)
Match sext_inreg(load p), imm -> sextload p.
Definition at line 687 of file CombinerHelper.cpp.
References assert(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), llvm::isPowerOf2_32(), llvm::LLT::isVector(), MI, llvm::min(), and MRI.
matchSextTruncSextLoad()
bool CombinerHelper::matchSextTruncSextLoad (MachineInstr & MI)
Definition at line 654 of file CombinerHelper.cpp.
References assert(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::LLT::isVector(), llvm::MIPatternMatch::m_GTrunc(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchShiftImmedChain()
bool CombinerHelper::matchShiftImmedChain (MachineInstr & MI, RegisterImmPair & MatchInfo)
Fold (shift (shift base, x), y) -> (shift base (x+y))
Definition at line 1748 of file CombinerHelper.cpp.
References assert(), llvm::sampleprof::Base, llvm::getConstantVRegValWithLookThrough(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getScalarSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getUniqueVRegDef(), llvm::RegisterImmPair::Imm, MI, MRI, and llvm::RegisterImmPair::Reg.
matchShiftOfShiftedLogic()
bool CombinerHelper::matchShiftOfShiftedLogic (MachineInstr & MI, ShiftOfShiftedLogic & MatchInfo)
If we have a shift-by-constant of a bitwise logic op that itself has a shift-by-constant operand with identical opcode, we may be able to convert that into 2 independent shifts followed by the logic op.
Definition at line 1826 of file CombinerHelper.cpp.
References assert(), C1, llvm::getConstantVRegValWithLookThrough(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getScalarSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getUniqueVRegDef(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), llvm::ShiftOfShiftedLogic::Logic, llvm::ShiftOfShiftedLogic::LogicNonShiftReg, MI, MRI, llvm::ShiftOfShiftedLogic::Shift2, and llvm::ShiftOfShiftedLogic::ValSum.
matchSimplifyAddToSub()
bool CombinerHelper::matchSimplifyAddToSub (MachineInstr & MI, std::tuple< Register, Register > & MatchInfo)
Return true if MI is a G_ADD which can be simplified to a G_SUB.
Definition at line 2826 of file CombinerHelper.cpp.
References llvm::MIPatternMatch::m_Neg(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchUndefSelectCmp()
bool CombinerHelper::matchUndefSelectCmp (MachineInstr & MI)
Return true if a G_SELECT instruction MI has an undef comparison.
Definition at line 2640 of file CombinerHelper.cpp.
References assert(), llvm::getOpcodeDef(), MI, and MRI.
matchUndefShuffleVectorMask()
bool CombinerHelper::matchUndefShuffleVectorMask (MachineInstr & MI)
Return true if a G_SHUFFLE_VECTOR instruction MI has an undef mask.
Definition at line 2628 of file CombinerHelper.cpp.
References llvm::all_of(), assert(), llvm::BitmaskEnumDetail::Mask(), and MI.
matchUndefStore()
bool CombinerHelper::matchUndefStore (MachineInstr & MI)
Return true if a G_STORE instruction MI is storing an undef value.
Definition at line 2634 of file CombinerHelper.cpp.
References assert(), llvm::getOpcodeDef(), MI, and MRI.
matchXorOfAndWithSameReg()
bool CombinerHelper::matchXorOfAndWithSameReg (MachineInstr & MI, std::pair< Register, Register > & MatchInfo)
Fold (xor (and x, y), y) -> (and (not x), y) {.
Definition at line 3303 of file CombinerHelper.cpp.
References assert(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), llvm::MIPatternMatch::m_GAnd(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, std::swap(), X, and Y.
replaceInstWithConstant() [1/2]
bool CombinerHelper::replaceInstWithConstant (MachineInstr & MI, APInt C)
Replace an instruction with a G_CONSTANT with value C.
Definition at line 2810 of file CombinerHelper.cpp.
References assert(), llvm::MachineIRBuilder::buildConstant(), Builder, MI, and llvm::MachineIRBuilder::setInstr().
replaceInstWithConstant() [2/2]
bool CombinerHelper::replaceInstWithConstant (MachineInstr & MI, int64_t C)
Replace an instruction with a G_CONSTANT with value C.
Definition at line 2802 of file CombinerHelper.cpp.
References assert(), llvm::MachineIRBuilder::buildConstant(), Builder, MI, and llvm::MachineIRBuilder::setInstr().
replaceInstWithFConstant()
bool CombinerHelper::replaceInstWithFConstant (MachineInstr & MI, double C)
Replace an instruction with a G_FCONSTANT with value C.
Definition at line 2794 of file CombinerHelper.cpp.
References assert(), Builder, llvm::MachineIRBuilder::buildFConstant(), MI, and llvm::MachineIRBuilder::setInstr().
replaceInstWithUndef()
bool CombinerHelper::replaceInstWithUndef (MachineInstr & MI)
Replace an instruction with a G_IMPLICIT_DEF.
Definition at line 2818 of file CombinerHelper.cpp.
References assert(), Builder, llvm::MachineIRBuilder::buildUndef(), MI, and llvm::MachineIRBuilder::setInstr().
replaceRegOpWith()
void CombinerHelper::replaceRegOpWith (MachineRegisterInfo & MRI, MachineOperand & FromRegOp, Register ToReg) const
Replace a single register operand with a new register and inform the observer of the changes.
Definition at line 135 of file CombinerHelper.cpp.
References assert(), llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::MachineOperand::getParent(), Observer, and llvm::MachineOperand::setReg().
Referenced by applyCombineExtendingLoads().
replaceRegWith()
void CombinerHelper::replaceRegWith (MachineRegisterInfo & MRI, Register FromReg, Register ToReg) const
MachineRegisterInfo::replaceRegWith() and inform the observer of the changes.
Definition at line 123 of file CombinerHelper.cpp.
References llvm::MachineIRBuilder::buildCopy(), Builder, llvm::GISelChangeObserver::changingAllUsesOfReg(), llvm::MachineRegisterInfo::constrainRegAttrs(), llvm::GISelChangeObserver::finishedChangingAllUsesOfReg(), MRI, Observer, and llvm::MachineRegisterInfo::replaceRegWith().
Referenced by applyCombineConcatVectors(), applyCombineCopy(), applyCombineExtendingLoads(), applyCombineShuffleVector(), applyCombineTruncOfExt(), applyCombineUnmergeMergeToPlainValues(), applyCombineUnmergeZExtToZExt(), applyExtractAllEltsFromBuildVector(), applyNotCmp(), matchOverlappingAnd(), replaceSingleDefInstWithOperand(), and replaceSingleDefInstWithReg().
replaceSingleDefInstWithOperand()
bool CombinerHelper::replaceSingleDefInstWithOperand (MachineInstr & MI, unsigned OpIdx)
Delete MI and replace all of its uses with its OpIdx-th operand.
Definition at line 2741 of file CombinerHelper.cpp.
References assert(), llvm::canReplaceReg(), MI, MRI, and replaceRegWith().
replaceSingleDefInstWithReg()
bool CombinerHelper::replaceSingleDefInstWithReg (MachineInstr & MI, Register Replacement)
Delete MI and replace all of its uses with Replacement.
Definition at line 2752 of file CombinerHelper.cpp.
References assert(), llvm::canReplaceReg(), MI, MRI, and replaceRegWith().
Referenced by applyExtractVecEltBuildVec().
tryCombine()
bool CombinerHelper::tryCombine (MachineInstr & MI)
Try to transform MI by using all of the above combine functions.
Returns true if changed.
Definition at line 4267 of file CombinerHelper.cpp.
References MI, tryCombineCopy(), tryCombineExtendingLoads(), and tryCombineIndexedLoadStore().
tryCombineConcatVectors()
bool CombinerHelper::tryCombineConcatVectors (MachineInstr & MI)
If MI is G_CONCAT_VECTORS, try to combine it.
Returns true if MI changed. Right now, we support:
concat_vector(undef, undef) => undef
concat_vector(build_vector(A, B), build_vector(C, D)) => build_vector(A, B, C, D)
Precondition
MI.getOpcode() == G_CONCAT_VECTORS.
Definition at line 167 of file CombinerHelper.cpp.
References applyCombineConcatVectors(), matchCombineConcatVectors(), and MI.
tryCombineCopy()
bool CombinerHelper::tryCombineCopy (MachineInstr & MI)
If MI is COPY, try to combine it.
Returns true if MI changed.
Definition at line 146 of file CombinerHelper.cpp.
References applyCombineCopy(), matchCombineCopy(), and MI.
Referenced by tryCombine().
tryCombineExtendingLoads()
bool CombinerHelper::tryCombineExtendingLoads (MachineInstr & MI)
If MI is extend that consumes the result of a load, try to combine it.
Returns true if MI changed.
Definition at line 429 of file CombinerHelper.cpp.
References applyCombineExtendingLoads(), matchCombineExtendingLoads(), and MI.
Referenced by tryCombine().
tryCombineIndexedLoadStore()
bool CombinerHelper::tryCombineIndexedLoadStore (MachineInstr & MI)
Combine MI into a pre-indexed or post-indexed load/store operation if legal and the surrounding code makes it useful.
Definition at line 871 of file CombinerHelper.cpp.
References applyCombineIndexedLoadStore(), matchCombineIndexedLoadStore(), and MI.
Referenced by tryCombine().
tryCombineMemCpyFamily()
bool CombinerHelper::tryCombineMemCpyFamily (MachineInstr & MI, unsigned MaxLen = 0)
Optimize memcpy intrinsics et al, e.g.
constant len calls. /p MaxLen if non-zero specifies the max length of a mem libcall to inline.
For example (pre-indexed):
$addr = G_PTR_ADD $base, $offset
[...]
$val = G_LOAD $addr
[...]
$whatever = COPY $addr
-->
$val, $addr = G_INDEXED_LOAD $base, $offset, 1 (IsPre)
[...]
$whatever = COPY $addr
or (post-indexed):
G_STORE $val, $base
[...]
$addr = G_PTR_ADD $base, $offset
[...]
$whatever = COPY $addr
-->
$addr = G_INDEXED_STORE $val, $base, $offset
[...]
$whatever = COPY $addr
Definition at line 1574 of file CombinerHelper.cpp.
References assert(), llvm::getConstantVRegValWithLookThrough(), llvm::AMDGPU::HSAMD::Kernel::Arg::Key::IsVolatile, MI, MRI, shouldLowerMemFuncForSize(), and tryEmitMemcpyInline().
tryCombineShiftToUnmerge()
bool CombinerHelper::tryCombineShiftToUnmerge (MachineInstr & MI, unsigned TargetShiftAmount)
Definition at line 2325 of file CombinerHelper.cpp.
References applyCombineShiftToUnmerge(), matchCombineShiftToUnmerge(), and MI.
tryCombineShuffleVector()
bool CombinerHelper::tryCombineShuffleVector (MachineInstr & MI)
Try to combine G_SHUFFLE_VECTOR into G_CONCAT_VECTORS.
Returns true if MI changed.
Precondition
MI.getOpcode() == G_SHUFFLE_VECTOR.
Definition at line 244 of file CombinerHelper.cpp.
References applyCombineShuffleVector(), matchCombineShuffleVector(), and MI.
tryEmitMemcpyInline()
bool CombinerHelper::tryEmitMemcpyInline (MachineInstr & MI)
Emit loads and stores that perform the given memcpy.
Assumes MI is a G_MEMCPY_INLINE TODO: implement dynamically sized inline memcpy, and rename: s/bool tryEmit/void emit/
Definition at line 1324 of file CombinerHelper.cpp.
References assert(), llvm::getConstantVRegValWithLookThrough(), llvm::AMDGPU::HSAMD::Kernel::Arg::Key::IsVolatile, MI, and MRI.
Referenced by tryCombineMemCpyFamily().
Member Data Documentation
Builder
MachineIRBuilder& llvm::CombinerHelper::Builder protected
Definition at line 92 of file CombinerHelper.h.
Referenced by applyAshShlToSextInreg(), applyBuildFn(), applyBuildFnNoErase(), applyBuildInstructionSteps(), applyCombineAddP2IToPtrAdd(), applyCombineConcatVectors(), applyCombineConstantFoldFpUnary(), applyCombineConstPtrAddToI2P(), applyCombineDivRem(), applyCombineExtendingLoads(), applyCombineExtOfExt(), applyCombineI2PToP2I(), applyCombineInsertVecElts(), applyCombineMulByNegativeOne(), applyCombineP2IToI2P(), applyCombineShiftToUnmerge(), applyCombineShlOfExtend(), applyCombineShuffleVector(), applyCombineTruncOfExt(), applyCombineTruncOfShl(), applyCombineUnmergeConstant(), applyCombineUnmergeMergeToPlainValues(), applyCombineUnmergeWithDeadLanesToTrunc(), applyCombineUnmergeZExtToZExt(), applyExtendThroughPhis(), applyExtractVecEltBuildVec(), applyFunnelShiftToRotate(), applyNotCmp(), applyOptBrCondByInvertingCond(), applyPtrAddZero(), applyRotateOutOfRange(), applySextInRegOfLoad(), applySextTruncSextLoad(), applyShiftImmedChain(), applyShiftOfShiftedLogic(), applySimplifyAddToSub(), applySimplifyURemByPow2(), applyXorOfAndWithSameReg(), getTargetLowering(), matchCombineConcatVectors(), matchCombineConstPtrAddToI2P(), matchCombineShuffleVector(), matchEqualDefs(), matchExtendThroughPhis(), matchNotCmp(), matchPtrAddZero(), matchReassocPtrAdd(), replaceInstWithConstant(), replaceInstWithFConstant(), replaceInstWithUndef(), and replaceRegWith().
KB
GISelKnownBits* llvm::CombinerHelper::KB protected
Definition at line 95 of file CombinerHelper.h.
Referenced by getKnownBits(), matchCombineShlOfExtend(), matchCombineTruncOfShl(), matchCombineZextTrunc(), matchICmpToTrueFalseKnownBits(), matchOperandIsKnownToBeAPowerOfTwo(), matchRedundantAnd(), matchRedundantOr(), and matchRedundantSExtInReg().
LI
const LegalizerInfo* llvm::CombinerHelper::LI protected
Definition at line 97 of file CombinerHelper.h.
Referenced by isLegalOrBeforeLegalizer(), matchBitfieldExtractFromSExtInReg(), matchCombineExtendingLoads(), and matchCombineShlOfExtend().
MDT
MachineDominatorTree* llvm::CombinerHelper::MDT protected
Definition at line 96 of file CombinerHelper.h.
Referenced by dominates().
MRI
MachineRegisterInfo& llvm::CombinerHelper::MRI protected
Definition at line 93 of file CombinerHelper.h.
Referenced by applyAshShlToSextInreg(), applyCombineAddP2IToPtrAdd(), applyCombineConcatVectors(), applyCombineCopy(), applyCombineExtendingLoads(), applyCombineIndexedLoadStore(), applyCombineInsertVecElts(), applyCombineMulByNegativeOne(), applyCombineMulToShl(), applyCombineShiftToUnmerge(), applyCombineShlOfExtend(), applyCombineShuffleVector(), applyCombineTruncOfExt(), applyCombineTruncOfShl(), applyCombineUnmergeMergeToPlainValues(), applyCombineUnmergeWithDeadLanesToTrunc(), applyCombineUnmergeZExtToZExt(), applyExtendThroughPhis(), applyExtractAllEltsFromBuildVector(), applyExtractVecEltBuildVec(), applyNotCmp(), applyOptBrCondByInvertingCond(), applyPtrAddImmedChain(), applyRotateOutOfRange(), applySextInRegOfLoad(), applyShiftImmedChain(), applyShiftOfShiftedLogic(), applySimplifyURemByPow2(), applyXorOfAndWithSameReg(), matchAshrShlToSextInreg(), matchBinOpSameVal(), matchBitfieldExtractFromAnd(), matchBitfieldExtractFromSExtInReg(), matchCombineAddP2IToPtrAdd(), matchCombineAnyExtTrunc(), matchCombineConcatVectors(), matchCombineConstantFoldFpUnary(), matchCombineConstPtrAddToI2P(), matchCombineCopy(), matchCombineDivRem(), matchCombineExtendingLoads(), matchCombineExtOfExt(), matchCombineFAbsOfFAbs(), matchCombineFNegOfFNeg(), matchCombineI2PToP2I(), matchCombineInsertVecElts(), matchCombineMergeUnmerge(), matchCombineMulToShl(), matchCombineP2IToI2P(), matchCombineShiftToUnmerge(), matchCombineShlOfExtend(), matchCombineShuffleVector(), matchCombineTruncOfExt(), matchCombineTruncOfShl(), matchCombineUnmergeConstant(), matchCombineUnmergeMergeToPlainValues(), matchCombineUnmergeWithDeadLanesToTrunc(), matchCombineUnmergeZExtToZExt(), matchCombineZextTrunc(), matchConstantFold(), matchConstantOp(), matchConstantSelectCmp(), matchEqualDefs(), matchExtendThroughPhis(), matchExtractAllEltsFromBuildVector(), matchExtractVecEltBuildVec(), matchFunnelShiftToRotate(), matchHoistLogicOpWithSameOpcodeHands(), matchICmpToTrueFalseKnownBits(), matchLoadOrCombine(), matchNotCmp(), matchOperandIsKnownToBeAPowerOfTwo(), matchOperandIsUndef(), matchOperandIsZero(), matchOverlappingAnd(), matchPtrAddImmedChain(), matchPtrAddZero(), matchReassocPtrAdd(), matchRedundantAnd(), matchRedundantOr(), matchRedundantSExtInReg(), matchRotateOutOfRange(), matchSelectSameVal(), matchSextInRegOfLoad(), matchSextTruncSextLoad(), matchShiftImmedChain(), matchShiftOfShiftedLogic(), matchSimplifyAddToSub(), matchUndefSelectCmp(), matchUndefStore(), matchXorOfAndWithSameReg(), replaceRegWith(), replaceSingleDefInstWithOperand(), replaceSingleDefInstWithReg(), tryCombineMemCpyFamily(), and tryEmitMemcpyInline().
Observer
GISelChangeObserver& llvm::CombinerHelper::Observer protected
Definition at line 94 of file CombinerHelper.h.
Referenced by applyCombineExtendingLoads(), applyCombineExtOfExt(), applyCombineMulToShl(), applyFunnelShiftToRotate(), applyNotCmp(), applyOptBrCondByInvertingCond(), applyPtrAddImmedChain(), applyRotateOutOfRange(), applyShiftImmedChain(), applyXorOfAndWithSameReg(), matchReassocPtrAdd(), replaceRegOpWith(), and replaceRegWith().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GlobalISel/CombinerHelper.h
lib/CodeGen/GlobalISel/CombinerHelper.cpp