LLVM: llvm::orc::SelfExecutorProcessControl Class Reference
llvm::orc::SelfExecutorProcessControl Class Reference
A ExecutorProcessControl implementation targeting the current process.
#include "llvm/ExecutionEngine/Orc/ExecutorProcessControl.h"
Public Member Functions
SelfExecutorProcessControl (std::shared_ptr< SymbolStringPool > SSP, Triple TargetTriple, unsigned PageSize, std::unique_ptr< jitlink::JITLinkMemoryManager > MemMgr)
Expected< tpctypes::DylibHandle > loadDylib (const char *DylibPath) override
Load the dynamic library at the given path and return a handle to it.
Expected< std::vector< tpctypes::LookupResult > > lookupSymbols (ArrayRef< LookupRequest > Request) override
Search for symbols in the target process.
Expected< int32_t > runAsMain (JITTargetAddress MainFnAddr, ArrayRef< std::string > Args) override
Run function with a main-like signature.
void callWrapperAsync (SendResultFunction OnComplete, JITTargetAddress WrapperFnAddr, ArrayRef< char > ArgBuffer) override
Run a wrapper function in the executor.
Error disconnect () override
Disconnect from the target process.
Public Member Functions inherited from llvm::orc::ExecutorProcessControl
virtual ~ExecutorProcessControl ()
ExecutionSession & getExecutionSession ()
Return the ExecutionSession associated with this instance.
SymbolStringPtr intern (StringRef SymName)
Intern a symbol name in the SymbolStringPool.
std::shared_ptr< SymbolStringPool > getSymbolStringPool () const
Return a shared pointer to the SymbolStringPool for this instance.
const Triple & getTargetTriple () const
Return the Triple for the target process.
unsigned getPageSize () const
Get the page size for the target process.
const JITDispatchInfo & getJITDispatchInfo () const
Get the JIT dispatch function and context address for the executor.
MemoryAccess & getMemoryAccess () const
Return a MemoryAccess object for the target process.
jitlink::JITLinkMemoryManager & getMemMgr () const
Return a JITLinkMemoryManager for the target process.
Static Public Member Functions
static Expected< std::unique_ptr< SelfExecutorProcessControl > > Create (std::shared_ptr< SymbolStringPool > SSP=nullptr, std::unique_ptr< jitlink::JITLinkMemoryManager > MemMgr=nullptr)
Create a SelfExecutorProcessControl with the given symbol string pool and memory manager.
Additional Inherited Members
Public Types inherited from llvm::orc::ExecutorProcessControl
using SendResultFunction = unique_function< void(shared::WrapperFunctionResult)>
Sender to return the result of a WrapperFunction executed in the JIT.
Protected Member Functions inherited from llvm::orc::ExecutorProcessControl
ExecutorProcessControl (std::shared_ptr< SymbolStringPool > SSP)
Protected Attributes inherited from llvm::orc::ExecutorProcessControl
std::shared_ptr< SymbolStringPool > SSP
ExecutionSession * ES = nullptr
Triple TargetTriple
unsigned PageSize = 0
JITDispatchInfo JDI
MemoryAccess * MemAccess = nullptr
jitlink::JITLinkMemoryManager * MemMgr = nullptr
Detailed Description
A ExecutorProcessControl implementation targeting the current process.
Definition at line 244 of file ExecutorProcessControl.h.
Constructor & Destructor Documentation
SelfExecutorProcessControl()
llvm::orc::SelfExecutorProcessControl::SelfExecutorProcessControl (std::shared_ptr< SymbolStringPool > SSP, Triple TargetTriple, unsigned PageSize, std::unique_ptr< jitlink::JITLinkMemoryManager > MemMgr)
Definition at line 26 of file ExecutorProcessControl.cpp.
References llvm::orc::ExecutorAddress::fromPtr(), llvm::Triple::isOSBinFormatMachO(), llvm::orc::ExecutorProcessControl::JDI, llvm::orc::ExecutorProcessControl::MemAccess, llvm::orc::ExecutorProcessControl::MemMgr, move, llvm::orc::ExecutorProcessControl::PageSize, and llvm::orc::ExecutorProcessControl::TargetTriple.
Member Function Documentation
callWrapperAsync()
void llvm::orc::SelfExecutorProcessControl::callWrapperAsync (SendResultFunction OnComplete, JITTargetAddress WrapperFnAddr, ArrayRef< char > ArgBuffer) override virtual
Run a wrapper function in the executor.
The wrapper function should be callable as:
CWrapperFunctionResult fn(uint8_t *Data, uint64_t Size);
{.cpp}
The given OnComplete function will be called to return the result.
Implements llvm::orc::ExecutorProcessControl.
Definition at line 112 of file ExecutorProcessControl.cpp.
References llvm::ArrayRef< T >::data(), llvm::Data, llvm::ArrayRef< T >::size(), and llvm::Check::Size.
Create()
Expected< std::unique_ptr< SelfExecutorProcessControl > > llvm::orc::SelfExecutorProcessControl::Create (std::shared_ptr< SymbolStringPool > SSP = nullptr, std::unique_ptr< jitlink::JITLinkMemoryManager > MemMgr = nullptr) static
Create a SelfExecutorProcessControl with the given symbol string pool and memory manager.
If no symbol string pool is given then one will be created. If no memory manager is given a jitlink::InProcessMemoryManager will be created and used by default.
Definition at line 46 of file ExecutorProcessControl.cpp.
References llvm::sys::Process::getPageSize(), llvm::sys::getProcessTriple(), llvm::orc::ExecutorProcessControl::MemMgr, move, llvm::orc::ExecutorProcessControl::PageSize, and llvm::orc::ExecutorProcessControl::SSP.
Referenced by llvm::orc::LLJITBuilderState::prepareForConstruction().
disconnect()
Error llvm::orc::SelfExecutorProcessControl::disconnect () override virtual
Disconnect from the target process.
This should be called after the JIT session is shut down.
Implements llvm::orc::ExecutorProcessControl.
Definition at line 121 of file ExecutorProcessControl.cpp.
References llvm::Error::success().
loadDylib()
Expected< tpctypes::DylibHandle > llvm::orc::SelfExecutorProcessControl::loadDylib (const char * DylibPath) override virtual
Load the dynamic library at the given path and return a handle to it.
If LibraryPath is null this function will return the global handle for the target process.
Implements llvm::orc::ExecutorProcessControl.
Definition at line 64 of file ExecutorProcessControl.cpp.
References llvm::sys::DynamicLibrary::getPermanentLibrary(), llvm::inconvertibleErrorCode(), move, and llvm::pointerToJITTargetAddress().
lookupSymbols()
Expected< std::vector< tpctypes::LookupResult > > llvm::orc::SelfExecutorProcessControl::lookupSymbols (ArrayRef< LookupRequest > Request) override virtual
Search for symbols in the target process.
The result of the lookup is a 2-dimentional array of target addresses that correspond to the lookup order. If a required symbol is not found then this method will return an error. If a weakly referenced symbol is not found then it be assigned a '0' value in the result. that correspond to the lookup order.
Implements llvm::orc::ExecutorProcessControl.
Definition at line 75 of file ExecutorProcessControl.cpp.
References Addr, llvm::any_of(), assert(), DL, move, llvm::pointerToJITTargetAddress(), and llvm::RISCVFenceField::R.
runAsMain()
Expected< int32_t > llvm::orc::SelfExecutorProcessControl::runAsMain (JITTargetAddress MainFnAddr, ArrayRef< std::string > Args) override virtual
Run function with a main-like signature.
Implements llvm::orc::ExecutorProcessControl.
Definition at line 106 of file ExecutorProcessControl.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, int, and llvm::orc::runAsMain().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/ExecutorProcessControl.h
lib/ExecutionEngine/Orc/ExecutorProcessControl.cpp