LLVM: llvm::MCBinaryExpr Class Reference
llvm::MCBinaryExpr Class Reference
Binary assembler expressions.
#include "llvm/MC/MCExpr.h"
Public Types
enum Opcode {
Add, And, Div, EQ,
GT, GTE, LAnd, LOr,
LT, LTE, Mod, Mul,
NE, Or, OrNot, Shl,
AShr, LShr, Sub, Xor
}
Public Types inherited from llvm::MCExpr
enum ExprKind : uint8_t {
Binary, Constant, SymbolRef, Unary,
Target
}
Public Member Functions
Accessors
Opcode getOpcode () const
Get the kind of this binary expression.
const MCExpr * getLHS () const
Get the left-hand side expression of the binary operator.
const MCExpr * getRHS () const
Get the right-hand side expression of the binary operator.
Public Member Functions inherited from llvm::MCExpr
MCExpr (const MCExpr &)=delete
MCExpr & operator= (const MCExpr &)=delete
ExprKind getKind () const
SMLoc getLoc () const
void print (raw_ostream &OS, const MCAsmInfo *MAI, bool InParens=false) const
void dump () const
bool evaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout, const SectionAddrMap &Addrs) const
Try to evaluate the expression to an absolute value.
bool evaluateAsAbsolute (int64_t &Res) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler *Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool evaluateKnownAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool evaluateAsRelocatable (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
Try to evaluate the expression to a relocatable value, i.e.
bool evaluateAsValue (MCValue &Res, const MCAsmLayout &Layout) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
MCFragment * findAssociatedFragment () const
Find the "associated section" for this expression, which is currently defined as the absolute section for constants, or otherwise the section associated with the first defined symbol in the expression.
Static Public Member Functions
static bool classof (const MCExpr *E)
Construction
static const MCBinaryExpr * create (Opcode Op, const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx, SMLoc Loc=SMLoc())
static const MCBinaryExpr * createAdd (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * createAnd (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * createDiv (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * createEQ (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * createGT (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * createGTE (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * createLAnd (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * createLOr (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * createLT (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * createLTE (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * createMod (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * createMul (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * createNE (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * createOr (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * createShl (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * createAShr (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * createLShr (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * createSub (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * createXor (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCExpr
MCExpr (ExprKind Kind, SMLoc Loc, unsigned SubclassData=0)
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, const MCAsmLayout *Layout, const MCFixup *Fixup, const SectionAddrMap *Addrs, bool InSet) const
unsigned getSubclassData () const
Detailed Description
Binary assembler expressions.
Definition at line 479 of file MCExpr.h.
Member Enumeration Documentation
Opcode
enum llvm::MCBinaryExpr::Opcode
Enumerator
Add
Addition.
And
Bitwise and.
Div
Signed division.
EQ
Equality comparison.
GT
Signed greater than comparison (result is either 0 or some target-specific non-zero value)
GTE
Signed greater than or equal comparison (result is either 0 or some target-specific non-zero value).
LAnd
Logical and.
LOr
Logical or.
LT
Signed less than comparison (result is either 0 or some target-specific non-zero value).
LTE
Signed less than or equal comparison (result is either 0 or some target-specific non-zero value).
Mod
Signed remainder.
Mul
Multiplication.
NE
Inequality comparison.
Or
Bitwise or.
OrNot
Bitwise or not.
Shl
Shift left.
AShr
Arithmetic shift right.
LShr
Logical shift right.
Sub
Subtraction.
Xor
Bitwise exclusive or.
Definition at line 481 of file MCExpr.h.
Member Function Documentation
classof()
static bool llvm::MCBinaryExpr::classof (const MCExpr * E) inline static
Definition at line 633 of file MCExpr.h.
References llvm::MCExpr::Binary, and E.
create()
const MCBinaryExpr * MCBinaryExpr::create (Opcode Op, const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx, SMLoc Loc = SMLoc()) static
Definition at line 183 of file MCExpr.cpp.
Referenced by buildSymbolDiff(), createAdd(), createAnd(), createAShr(), createDiv(), createEQ(), createGT(), createGTE(), createLAnd(), createLOr(), createLShr(), createLT(), createLTE(), createMod(), createMul(), createNE(), createOr(), createShl(), createSub(), and createXor().
createAdd()
static const MCBinaryExpr* llvm::MCBinaryExpr::createAdd (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 523 of file MCExpr.h.
References Add, and create().
Referenced by llvm::MCWinCOFFStreamer::EmitCOFFImgRel32(), llvm::MCWinCOFFStreamer::EmitCOFFSecRel32(), llvm::ARMAsmPrinter::emitInstruction(), llvm::SystemZAsmPrinter::emitInstruction(), llvm::X86AsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitJumpTableAddrs(), llvm::ARMAsmPrinter::emitJumpTableTBInst(), llvm::AsmPrinter::emitLabelPlusOffset(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), EmitSymbolRefWithOfs(), llvm::AsmPrinter::emitXRayTable(), llvm::CodeViewContext::encodeDefRange(), llvm::MipsMCCodeEmitter::getBranchTarget21OpValue(), llvm::MipsMCCodeEmitter::getBranchTarget21OpValueMM(), llvm::MipsMCCodeEmitter::getBranchTarget26OpValue(), llvm::MipsMCCodeEmitter::getBranchTarget26OpValueMM(), llvm::MipsMCCodeEmitter::getBranchTargetOpValue(), llvm::MipsMCCodeEmitter::getBranchTargetOpValue1SImm16(), llvm::MipsMCCodeEmitter::getBranchTargetOpValueLsl2MMR6(), llvm::MipsMCCodeEmitter::getBranchTargetOpValueMMR6(), llvm::MipsTargetObjectFile::getDebugThreadLocalSymbol(), llvm::SystemZMCInstLower::getExpr(), llvm::X86_64MCAsmInfoDarwin::getExprForPersonalitySymbol(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), llvm::X86_64MachoTargetObjectFile::getIndirectSymViaGOTPCRel(), GetSymbolRef(), llvm::X86_64MachoTargetObjectFile::getTTypeGlobalReference(), llvm::AsmPrinter::lowerConstant(), LowerSymbolOperand(), llvm::AVRMCInstLower::lowerSymbolOperand(), llvm::LanaiMCInstLower::LowerSymbolOperand(), llvm::M68kMCInstLower::LowerSymbolOperand(), llvm::MSP430MCInstLower::LowerSymbolOperand(), lowerSymbolOperand(), llvm::AArch64MCInstLower::lowerSymbolOperandCOFF(), llvm::AArch64MCInstLower::lowerSymbolOperandDarwin(), llvm::AArch64MCInstLower::lowerSymbolOperandELF(), llvm::MCExternalSymbolizer::tryAddingSymbolicOperand(), and llvm::AArch64ExternalSymbolizer::tryAddingSymbolicOperand().
createAnd()
static const MCBinaryExpr* llvm::MCBinaryExpr::createAnd (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 528 of file MCExpr.h.
References And, and create().
Referenced by llvm::SIInstrInfo::insertIndirectBranch(), and llvm::AsmPrinter::lowerConstant().
createAShr()
static const MCBinaryExpr* llvm::MCBinaryExpr::createAShr (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 598 of file MCExpr.h.
References AShr, and create().
Referenced by llvm::SIInstrInfo::insertIndirectBranch().
createDiv()
static const MCBinaryExpr* llvm::MCBinaryExpr::createDiv (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 533 of file MCExpr.h.
References create(), and Div.
Referenced by llvm::ARMAsmPrinter::emitJumpTableTBInst(), and llvm::AsmPrinter::lowerConstant().
createEQ()
static const MCBinaryExpr* llvm::MCBinaryExpr::createEQ (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 538 of file MCExpr.h.
References create(), and EQ.
createGT()
static const MCBinaryExpr* llvm::MCBinaryExpr::createGT (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 543 of file MCExpr.h.
References create(), and GT.
createGTE()
static const MCBinaryExpr* llvm::MCBinaryExpr::createGTE (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 548 of file MCExpr.h.
References create(), and GTE.
createLAnd()
static const MCBinaryExpr* llvm::MCBinaryExpr::createLAnd (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 553 of file MCExpr.h.
References create(), and LAnd.
createLOr()
static const MCBinaryExpr* llvm::MCBinaryExpr::createLOr (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 558 of file MCExpr.h.
References create(), and LOr.
createLShr()
static const MCBinaryExpr* llvm::MCBinaryExpr::createLShr (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 603 of file MCExpr.h.
References create(), and LShr.
createLT()
static const MCBinaryExpr* llvm::MCBinaryExpr::createLT (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 563 of file MCExpr.h.
References create(), and LT.
createLTE()
static const MCBinaryExpr* llvm::MCBinaryExpr::createLTE (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 568 of file MCExpr.h.
References create(), and LTE.
createMod()
static const MCBinaryExpr* llvm::MCBinaryExpr::createMod (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 573 of file MCExpr.h.
References create(), and Mod.
Referenced by llvm::AsmPrinter::lowerConstant().
createMul()
static const MCBinaryExpr* llvm::MCBinaryExpr::createMul (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 578 of file MCExpr.h.
References create(), and Mul.
Referenced by llvm::AsmPrinter::lowerConstant().
createNE()
static const MCBinaryExpr* llvm::MCBinaryExpr::createNE (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 583 of file MCExpr.h.
References create(), and NE.
createOr()
static const MCBinaryExpr* llvm::MCBinaryExpr::createOr (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 588 of file MCExpr.h.
References create(), and Or.
Referenced by llvm::AsmPrinter::lowerConstant().
createShl()
static const MCBinaryExpr* llvm::MCBinaryExpr::createShl (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 593 of file MCExpr.h.
References create(), and Shl.
Referenced by llvm::AsmPrinter::lowerConstant().
createSub()
static const MCBinaryExpr* llvm::MCBinaryExpr::createSub (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 608 of file MCExpr.h.
References create(), and Sub.
Referenced by addNegOperand(), EmitAbsDifference(), llvm::MCStreamer::emitAbsoluteSymbolDiff(), llvm::MCStreamer::emitAbsoluteSymbolDiffAsULEB128(), llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor(), llvm::MipsTargetELFStreamer::emitDirectiveEnd(), llvm::AsmPrinter::emitFunctionBody(), llvm::AMDGPUTargetELFStreamer::EmitHSAMetadata(), llvm::ARMAsmPrinter::emitInstruction(), llvm::X86AsmPrinter::emitInstruction(), llvm::AMDGPUTargetELFStreamer::EmitISAVersion(), llvm::ARMAsmPrinter::emitJumpTableAddrs(), llvm::AsmPrinter::emitJumpTableInfo(), llvm::ARMAsmPrinter::emitJumpTableTBInst(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), EmitSymbolRefWithOfs(), llvm::AsmPrinter::emitXRayTable(), llvm::WasmException::endFunction(), GetAbsDifference(), llvm::MCAsmInfo::getExprForFDESymbol(), llvm::AArch64MCAsmInfoDarwin::getExprForPersonalitySymbol(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), llvm::AArch64_MachoTargetObjectFile::getIndirectSymViaGOTPCRel(), GetSymbolRef(), llvm::AArch64_MachoTargetObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFile::getTTypeReference(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), llvm::SIInstrInfo::insertIndirectBranch(), llvm::AsmPrinter::lowerConstant(), llvm::VETargetLowering::LowerCustomJumpTableEntry(), llvm::TargetLoweringObjectFileELF::lowerRelativeReference(), llvm::TargetLoweringObjectFileWasm::lowerRelativeReference(), llvm::FaultMaps::recordFaultingOp(), llvm::MCExternalSymbolizer::tryAddingSymbolicOperand(), and llvm::AArch64ExternalSymbolizer::tryAddingSymbolicOperand().
createXor()
static const MCBinaryExpr* llvm::MCBinaryExpr::createXor (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 613 of file MCExpr.h.
References create(), and Xor.
Referenced by llvm::AsmPrinter::lowerConstant().
getLHS()
const MCExpr* llvm::MCBinaryExpr::getLHS () const inline
Get the left-hand side expression of the binary operator.
Definition at line 626 of file MCExpr.h.
Referenced by llvm::MCExpr::evaluateAsRelocatableImpl(), EvaluateCRExpr(), llvm::MCExpr::findAssociatedFragment(), fixELFSymbolsInTLSFixupsImpl(), llvm::PPCMCCodeEmitter::getMemRI34PCRelEncoding(), hasGOTReference(), isEvaluated(), llvm::MCParserUtils::isSymbolUsedInExpression(), llvm::MCExpr::print(), llvm::RISCVAsmBackend::relaxDwarfCFA(), llvm::RISCVAsmBackend::relaxDwarfLineAddr(), startsWithGlobalOffsetTable(), and llvm::MCStreamer::visitUsedExpr().
getOpcode()
Opcode llvm::MCBinaryExpr::getOpcode () const inline
Get the kind of this binary expression.
Definition at line 623 of file MCExpr.h.
References llvm::MCExpr::getSubclassData().
Referenced by llvm::MCExpr::evaluateAsRelocatableImpl(), EvaluateCRExpr(), llvm::MCExpr::findAssociatedFragment(), llvm::PPCMCCodeEmitter::getMemRI34PCRelEncoding(), and llvm::MCExpr::print().
getRHS()
const MCExpr* llvm::MCBinaryExpr::getRHS () const inline
Get the right-hand side expression of the binary operator.
Definition at line 629 of file MCExpr.h.
Referenced by llvm::MCExpr::evaluateAsRelocatableImpl(), EvaluateCRExpr(), llvm::MCExpr::findAssociatedFragment(), fixELFSymbolsInTLSFixupsImpl(), llvm::PPCMCCodeEmitter::getMemRI34PCRelEncoding(), hasGOTReference(), isEvaluated(), llvm::MCParserUtils::isSymbolUsedInExpression(), llvm::MCExpr::print(), llvm::RISCVAsmBackend::relaxDwarfCFA(), llvm::RISCVAsmBackend::relaxDwarfLineAddr(), startsWithGlobalOffsetTable(), and llvm::MCStreamer::visitUsedExpr().
The documentation for this class was generated from the following files:
include/llvm/MC/MCExpr.h
lib/MC/MCExpr.cpp