LLVM: llvm::symbolize::LLVMSymbolizer Class Reference
llvm::symbolize::LLVMSymbolizer Class Reference
#include "llvm/DebugInfo/Symbolize/Symbolize.h"
Classes
struct Options
Public Member Functions
LLVMSymbolizer ()=default
LLVMSymbolizer (const Options &Opts)
~LLVMSymbolizer ()
Expected< DILineInfo > symbolizeCode (const ObjectFile &Obj, object::SectionedAddress ModuleOffset)
Expected< DILineInfo > symbolizeCode (const std::string &ModuleName, object::SectionedAddress ModuleOffset)
Expected< DIInliningInfo > symbolizeInlinedCode (const ObjectFile &Obj, object::SectionedAddress ModuleOffset)
Expected< DIInliningInfo > symbolizeInlinedCode (const std::string &ModuleName, object::SectionedAddress ModuleOffset)
Expected< DIGlobal > symbolizeData (const ObjectFile &Obj, object::SectionedAddress ModuleOffset)
Expected< DIGlobal > symbolizeData (const std::string &ModuleName, object::SectionedAddress ModuleOffset)
Expected< std::vector< DILocal > > symbolizeFrame (const ObjectFile &Obj, object::SectionedAddress ModuleOffset)
Expected< std::vector< DILocal > > symbolizeFrame (const std::string &ModuleName, object::SectionedAddress ModuleOffset)
void flush ()
Static Public Member Functions
static std::string DemangleName (const std::string &Name, const SymbolizableModule *DbiModuleDescriptor)
Detailed Description
Definition at line 37 of file Symbolize.h.
Constructor & Destructor Documentation
LLVMSymbolizer() [1/2]
llvm::symbolize::LLVMSymbolizer::LLVMSymbolizer () default
LLVMSymbolizer() [2/2]
llvm::symbolize::LLVMSymbolizer::LLVMSymbolizer (const Options & Opts) inline
Definition at line 55 of file Symbolize.h.
~LLVMSymbolizer()
llvm::symbolize::LLVMSymbolizer::~LLVMSymbolizer () inline
Definition at line 57 of file Symbolize.h.
Member Function Documentation
DemangleName()
std::string llvm::symbolize::LLVMSymbolizer::DemangleName (const std::string & Name, const SymbolizableModule * DbiModuleDescriptor) static
Definition at line 651 of file Symbolize.cpp.
References llvm::symbolize::SymbolizableModule::isWin32Module(), llvm::itaniumDemangle(), llvm::microsoftDemangle(), llvm::MSDF_NoAccessSpecifier, llvm::MSDF_NoCallingConvention, llvm::MSDF_NoMemberType, llvm::MSDF_NoReturnType, and llvm::sys::fs::status().
flush()
void llvm::symbolize::LLVMSymbolizer::flush ()
Definition at line 200 of file Symbolize.cpp.
symbolizeCode() [1/2]
Expected< DILineInfo > llvm::symbolize::LLVMSymbolizer::symbolizeCode (const ObjectFile & Obj, object::SectionedAddress ModuleOffset)
Definition at line 72 of file Symbolize.cpp.
symbolizeCode() [2/2]
Expected< DILineInfo > llvm::symbolize::LLVMSymbolizer::symbolizeCode (const std::string & ModuleName, object::SectionedAddress ModuleOffset)
Definition at line 78 of file Symbolize.cpp.
symbolizeData() [1/2]
Expected< DIGlobal > llvm::symbolize::LLVMSymbolizer::symbolizeData (const ObjectFile & Obj, object::SectionedAddress ModuleOffset)
Definition at line 154 of file Symbolize.cpp.
symbolizeData() [2/2]
Expected< DIGlobal > llvm::symbolize::LLVMSymbolizer::symbolizeData (const std::string & ModuleName, object::SectionedAddress ModuleOffset)
Definition at line 160 of file Symbolize.cpp.
symbolizeFrame() [1/2]
Expected< std::vector< DILocal > > llvm::symbolize::LLVMSymbolizer::symbolizeFrame (const ObjectFile & Obj, object::SectionedAddress ModuleOffset)
Definition at line 189 of file Symbolize.cpp.
symbolizeFrame() [2/2]
Expected< std::vector< DILocal > > llvm::symbolize::LLVMSymbolizer::symbolizeFrame (const std::string & ModuleName, object::SectionedAddress ModuleOffset)
Definition at line 195 of file Symbolize.cpp.
symbolizeInlinedCode() [1/2]
Expected< DIInliningInfo > llvm::symbolize::LLVMSymbolizer::symbolizeInlinedCode (const ObjectFile & Obj, object::SectionedAddress ModuleOffset)
Definition at line 115 of file Symbolize.cpp.
symbolizeInlinedCode() [2/2]
Expected< DIInliningInfo > llvm::symbolize::LLVMSymbolizer::symbolizeInlinedCode (const std::string & ModuleName, object::SectionedAddress ModuleOffset)
Definition at line 121 of file Symbolize.cpp.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/Symbolize/Symbolize.h
lib/DebugInfo/Symbolize/Symbolize.cpp