LLVM: llvm::InstructionOrdering Class Reference
llvm::InstructionOrdering Class Reference
Record instruction ordering so we can query their relative positions within a function.
#include "llvm/CodeGen/DbgEntityHistoryCalculator.h"
Public Member Functions
void initialize (const MachineFunction &MF)
void clear ()
bool isBefore (const MachineInstr *A, const MachineInstr *B) const
Check if instruction A comes before B, where A and B both belong to the MachineFunction passed to initialize().
Detailed Description
Record instruction ordering so we can query their relative positions within a function.
Meta instructions are given the same ordinal as the preceding non-meta instruction. Class state is invalid if MF is modified after calling initialize.
Definition at line 31 of file DbgEntityHistoryCalculator.h.
Member Function Documentation
clear()
void llvm::InstructionOrdering::clear () inline
Definition at line 34 of file DbgEntityHistoryCalculator.h.
Referenced by llvm::DebugHandlerBase::endFunction(), and initialize().
initialize()
void InstructionOrdering::initialize (const MachineFunction & MF)
Definition at line 40 of file DbgEntityHistoryCalculator.cpp.
References clear(), MBB, and MI.
Referenced by llvm::DebugHandlerBase::beginFunction().
isBefore()
bool InstructionOrdering::isBefore (const MachineInstr * A, const MachineInstr * B) const
Check if instruction A comes before B, where A and B both belong to the MachineFunction passed to initialize().
Definition at line 63 of file DbgEntityHistoryCalculator.cpp.
References A, assert(), and B.
Referenced by intersects(), and validThroughout().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/DbgEntityHistoryCalculator.h
lib/CodeGen/AsmPrinter/DbgEntityHistoryCalculator.cpp