LLVM: llvm::AliasSetsPrinterPass Class Reference
llvm::AliasSetsPrinterPass Class Reference
#include "llvm/Analysis/AliasSetTracker.h"
Public Member Functions
AliasSetsPrinterPass (raw_ostream &OS)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< AliasSetsPrinterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 461 of file AliasSetTracker.h.
Constructor & Destructor Documentation
AliasSetsPrinterPass()
print alias Alias Set true AliasSetsPrinterPass::AliasSetsPrinterPass (raw_ostream & OS) explicit
Definition at line 764 of file AliasSetTracker.cpp.
Member Function Documentation
run()
PreservedAnalyses AliasSetsPrinterPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 766 of file AliasSetTracker.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), I, and llvm::instructions().
The documentation for this class was generated from the following files:
include/llvm/Analysis/AliasSetTracker.h
lib/Analysis/AliasSetTracker.cpp