LLVM: llvm::orc::OrcRPCTPCServer< RPCEndpointT > Class Template Reference
llvm::orc::OrcRPCTPCServer< RPCEndpointT > Class Template Reference
TargetProcessControl for a process connected via an ORC RPC Endpoint.
#include "llvm/ExecutionEngine/Orc/TargetProcess/OrcRPCTPCServer.h"
Public Member Functions
OrcRPCTPCServer (RPCEndpointT &EP)
Create an OrcRPCTPCServer from the given endpoint.
void setProgramName (Optional< std::string > ProgramName=None)
Set the ProgramName to be used as the first argv element when running functions via runAsMain.
RPCEndpointT & getEndpoint ()
Get the RPC endpoint for this server.
Error run ()
Run the server loop.
Expected< shared::WrapperFunctionResult > runWrapperInJIT (JITTargetAddress FunctionId, ArrayRef< char > ArgBuffer)
Detailed Description
template<typename RPCEndpointT>
class llvm::orc::OrcRPCTPCServer< RPCEndpointT >
TargetProcessControl for a process connected via an ORC RPC Endpoint.
Definition at line 403 of file OrcRPCTPCServer.h.
Constructor & Destructor Documentation
OrcRPCTPCServer()
template<typename RPCEndpointT > llvm::orc::OrcRPCTPCServer< RPCEndpointT >::OrcRPCTPCServer (RPCEndpointT & EP) inline
Create an OrcRPCTPCServer from the given endpoint.
Definition at line 409 of file OrcRPCTPCServer.h.
References llvm::sys::Process::getPageSizeEstimate(), and llvm::sys::getProcessTriple().
Member Function Documentation
getEndpoint()
template<typename RPCEndpointT > RPCEndpointT& llvm::orc::OrcRPCTPCServer< RPCEndpointT >::getEndpoint () inline
Get the RPC endpoint for this server.
Definition at line 449 of file OrcRPCTPCServer.h.
run()
template<typename RPCEndpointT > Error llvm::orc::OrcRPCTPCServer< RPCEndpointT >::run () inline
Run the server loop.
Definition at line 452 of file OrcRPCTPCServer.h.
runWrapperInJIT()
template<typename RPCEndpointT > Expected<shared::WrapperFunctionResult> llvm::orc::OrcRPCTPCServer< RPCEndpointT >::runWrapperInJIT (JITTargetAddress FunctionId, ArrayRef< char > ArgBuffer) inline
Definition at line 461 of file OrcRPCTPCServer.h.
References llvm::ArrayRef< T >::data(), and llvm::ArrayRef< T >::size().
setProgramName()
template<typename RPCEndpointT > void llvm::orc::OrcRPCTPCServer< RPCEndpointT >::setProgramName (Optional< std::string > ProgramName = None) inline
Set the ProgramName to be used as the first argv element when running functions via runAsMain.
Definition at line 444 of file OrcRPCTPCServer.h.
References move.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/TargetProcess/OrcRPCTPCServer.h