LLVM: llvm::InlineAsmLowering Class Reference
llvm::InlineAsmLowering Class Reference
#include "llvm/CodeGen/GlobalISel/InlineAsmLowering.h"
Public Member Functions
bool lowerInlineAsm (MachineIRBuilder &MIRBuilder, const CallBase &CB, std::function< ArrayRef< Register >(const Value &Val)> GetOrCreateVRegs) const
Lower the given inline asm call instruction GetOrCreateVRegs is a callback to materialize a register for the input and output operands of the inline asm.
virtual bool lowerAsmOperandForConstraint (Value *Val, StringRef Constraint, std::vector< MachineOperand > &Ops, MachineIRBuilder &MIRBuilder) const
Lower the specified operand into the Ops vector.
InlineAsmLowering (const TargetLowering *TLI)
virtual ~InlineAsmLowering ()=default
Protected Member Functions
const TargetLowering * getTLI () const
Getter for generic TargetLowering class.
template<class XXXTargetLowering >
const XXXTargetLowering * getTLI () const
Getter for target specific TargetLowering class.
Detailed Description
Definition at line 28 of file InlineAsmLowering.h.
Constructor & Destructor Documentation
InlineAsmLowering()
llvm::InlineAsmLowering::InlineAsmLowering (const TargetLowering * TLI) inline
Definition at line 61 of file InlineAsmLowering.h.
~InlineAsmLowering()
virtual llvm::InlineAsmLowering::~InlineAsmLowering () virtual default
Member Function Documentation
getTLI() [1/2]
const TargetLowering* llvm::InlineAsmLowering::getTLI () const inline protected
Getter for generic TargetLowering class.
Definition at line 53 of file InlineAsmLowering.h.
getTLI() [2/2]
template<class XXXTargetLowering > const XXXTargetLowering* llvm::InlineAsmLowering::getTLI () const inline protected
Getter for target specific TargetLowering class.
Definition at line 56 of file InlineAsmLowering.h.
lowerAsmOperandForConstraint()
bool InlineAsmLowering::lowerAsmOperandForConstraint (Value * Val, StringRef Constraint, std::vector< MachineOperand > & Ops, MachineIRBuilder & MIRBuilder) const virtual
Lower the specified operand into the Ops vector.
Val is the IR input value to be lowered Constraint is the user supplied constraint string Ops is the vector to be filled with the lowered operands
Returns
True if the lowering succeeds, false otherwise.
Definition at line 659 of file InlineAsmLowering.cpp.
References assert(), llvm::MachineOperand::CreateImm(), and llvm::StringRef::size().
Referenced by lowerInlineAsm().
lowerInlineAsm()
bool InlineAsmLowering::lowerInlineAsm (MachineIRBuilder & MIRBuilder, const CallBase & CB, std::function< ArrayRef< Register >(const Value &Val)> GetOrCreateVRegs) const
Lower the given inline asm call instruction GetOrCreateVRegs is a callback to materialize a register for the input and output operands of the inline asm.
Returns
True if the lowering succeeds, false otherwise.
ConstraintOperands - Information about all of the constraints.
Definition at line 273 of file InlineAsmLowering.cpp.
References llvm::MachineInstrBuilder::addExternalSymbol(), llvm::MachineInstrBuilder::addImm(), assert(), buildAnyextOrCopy(), llvm::MachineIRBuilder::buildCopy(), llvm::MachineIRBuilder::buildInstrNoInsert(), llvm::MachineIRBuilder::buildTrunc(), llvm::TargetLowering::C_Immediate, llvm::TargetLowering::C_Memory, llvm::TargetLowering::C_Other, llvm::TargetLowering::C_Register, llvm::TargetLowering::C_RegisterClass, llvm::TargetLowering::C_Unknown, llvm::MCID::Call, llvm::TargetLowering::AsmOperandInfo::CallOperandVal, computeConstraintToUse(), llvm::InlineAsm::Constraint_Unknown, llvm::TargetLowering::AsmOperandInfo::ConstraintCode, llvm::TargetLowering::AsmOperandInfo::ConstraintType, llvm::MachineRegisterInfo::createGenericVirtualRegister(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::dbgs(), llvm::tgtok::Def, llvm::RegState::Define, DL, llvm::numbers::e, llvm::RegState::EarlyClobber, F, llvm::TargetLoweringBase::getAsmOperandValueType(), llvm::InlineAsm::getAsmString(), llvm::PointerType::getElementType(), llvm::InlineAsm::getFlagWord(), llvm::InlineAsm::getFlagWordForMatchingOp(), llvm::InlineAsm::getFlagWordForMem(), llvm::InlineAsm::getFlagWordForRegClass(), llvm::MachineFunction::getFunction(), llvm::TargetRegisterClass::getID(), llvm::getImplRegState(), llvm::TargetLowering::getInlineAsmMemConstraint(), llvm::TargetLowering::AsmOperandInfo::getMatchedOperand(), llvm::MachineIRBuilder::getMF(), llvm::MachineIRBuilder::getMRI(), llvm::MachineInstr::getNumOperands(), getNumOpRegs(), llvm::MachineRegisterInfo::getRegClass(), llvm::TargetSubtargetInfo::getRegisterInfo(), getRegistersForValue(), llvm::TargetRegisterInfo::getRegSizeInBits(), llvm::TargetLoweringBase::getSimpleValueType(), llvm::EVT::getSimpleVT(), llvm::LLT::getSizeInBits(), llvm::MachineFunction::getSubtarget(), llvm::MachineRegisterInfo::getType(), i, llvm::MVT::i64x8, llvm::tgtok::In, llvm::ISD::INLINEASM, llvm::MachineIRBuilder::insertInstr(), llvm::InlineAsm::isClobber, llvm::InlineAsm::ConstraintInfo::isEarlyClobber, llvm::InlineAsm::ConstraintInfo::isIndirect, llvm::InlineAsm::isInput, llvm::TargetLowering::AsmOperandInfo::isMatchingInputConstraint(), llvm::InlineAsm::isMemKind(), llvm::InlineAsm::isOutput, llvm::InlineAsm::isRegDefEarlyClobberKind(), llvm::InlineAsm::isRegDefKind(), llvm::Type::isSingleValueType(), llvm::InlineAsm::Kind_Clobber, llvm::InlineAsm::Kind_Imm, llvm::InlineAsm::Kind_Mem, llvm::InlineAsm::Kind_RegDef, llvm::InlineAsm::Kind_RegDefEarlyClobber, llvm::InlineAsm::Kind_RegUse, LLVM_DEBUG, lowerAsmOperandForConstraint(), MRI, llvm::MVT::Other, llvm::TargetLowering::ParseConstraints(), Reg, llvm::report_fatal_error(), llvm::LLT::scalar(), llvm::ArrayRef< T >::size(), TRI, and llvm::InlineAsm::ConstraintInfo::Type.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GlobalISel/InlineAsmLowering.h
lib/CodeGen/GlobalISel/InlineAsmLowering.cpp