LLVM: llvm::jitlink::LinkGraph Class Reference
llvm::jitlink::LinkGraph Class Reference
#include "llvm/ExecutionEngine/JITLink/JITLink.h"
Classes
class nested_collection_iterator
Public Types
using external_symbol_iterator = ExternalSymbolSet::iterator
using section_iterator = pointee_iterator< SectionList::iterator >
using const_section_iterator = pointee_iterator< SectionList::const_iterator >
using defined_symbol_iterator = nested_collection_iterator< const_section_iterator, Section::symbol_iterator, Symbol *, getSectionSymbols >
using const_defined_symbol_iterator = nested_collection_iterator< const_section_iterator, Section::const_symbol_iterator, const Symbol *, getSectionConstSymbols >
using block_iterator = nested_collection_iterator< const_section_iterator, Section::block_iterator, Block *, getSectionBlocks >
using const_block_iterator = nested_collection_iterator< const_section_iterator, Section::const_block_iterator, const Block *, getSectionConstBlocks >
using GetEdgeKindNameFunction = const char *(*)(Edge::Kind)
using SplitBlockCache = Optional< SmallVector< Symbol *, 8 > >
Cache type for the splitBlock function.
Public Member Functions
LinkGraph (std::string Name, const Triple &TT, unsigned PointerSize, support::endianness Endianness, GetEdgeKindNameFunction GetEdgeKindName)
const std::string & getName () const
Returns the name of this graph (usually the name of the original underlying MemoryBuffer).
const Triple & getTargetTriple () const
Returns the target triple for this Graph.
unsigned getPointerSize () const
Returns the pointer size for use in this graph.
support::endianness getEndianness () const
Returns the endianness of content in this graph.
const char * getEdgeKindName (Edge::Kind K) const
MutableArrayRef< char > allocateBuffer (size_t Size)
Allocate a mutable buffer of the given size using the LinkGraph's allocator.
MutableArrayRef< char > allocateContent (ArrayRef< char > Source)
Allocate a copy of the given string using the LinkGraph's allocator.
MutableArrayRef< char > allocateString (Twine Source)
Allocate a copy of the given string using the LinkGraph's allocator.
Section & createSection (StringRef Name, sys::Memory::ProtectionFlags Prot)
Create a section with the given name, protection flags, and alignment.
Block & createContentBlock (Section &Parent, ArrayRef< char > Content, uint64_t Address, uint64_t Alignment, uint64_t AlignmentOffset)
Create a content block.
Block & createMutableContentBlock (Section &Parent, MutableArrayRef< char > MutableContent, uint64_t Address, uint64_t Alignment, uint64_t AlignmentOffset)
Create a content block with initially mutable data.
Block & createZeroFillBlock (Section &Parent, uint64_t Size, uint64_t Address, uint64_t Alignment, uint64_t AlignmentOffset)
Create a zero-fill block.
Block & splitBlock (Block &B, size_t SplitIndex, SplitBlockCache *Cache=nullptr)
Splits block B at the given index which must be greater than zero.
Symbol & addExternalSymbol (StringRef Name, uint64_t Size, Linkage L)
Add an external symbol.
Symbol & addAbsoluteSymbol (StringRef Name, JITTargetAddress Address, uint64_t Size, Linkage L, Scope S, bool IsLive)
Add an absolute symbol.
Symbol & addCommonSymbol (StringRef Name, Scope S, Section &Section, JITTargetAddress Address, uint64_t Size, uint64_t Alignment, bool IsLive)
Convenience method for adding a weak zero-fill symbol.
Symbol & addAnonymousSymbol (Block &Content, JITTargetAddress Offset, JITTargetAddress Size, bool IsCallable, bool IsLive)
Add an anonymous symbol.
Symbol & addDefinedSymbol (Block &Content, JITTargetAddress Offset, StringRef Name, JITTargetAddress Size, Linkage L, Scope S, bool IsCallable, bool IsLive)
Add a named symbol.
iterator_range< section_iterator > sections ()
SectionList::size_type sections_size () const
Section * findSectionByName (StringRef Name)
Returns the section with the given name if it exists, otherwise returns null.
iterator_range< block_iterator > blocks ()
iterator_range< const_block_iterator > blocks () const
iterator_range< external_symbol_iterator > external_symbols ()
iterator_range< external_symbol_iterator > absolute_symbols ()
iterator_range< defined_symbol_iterator > defined_symbols ()
iterator_range< const_defined_symbol_iterator > defined_symbols () const
void makeExternal (Symbol &Sym)
Make the given symbol external (must not already be external).
void makeAbsolute (Symbol &Sym, JITTargetAddress Address)
Make the given symbol an absolute with the given address (must not already be absolute).
void makeDefined (Symbol &Sym, Block &Content, JITTargetAddress Offset, JITTargetAddress Size, Linkage L, Scope S, bool IsLive)
Turn an absolute or external symbol into a defined one by attaching it to a block.
void transferDefinedSymbol (Symbol &Sym, Block &DestBlock, JITTargetAddress NewOffset, Optional< JITTargetAddress > ExplicitNewSize)
Transfer a defined symbol from one block to another.
void transferBlock (Block &B, Section &NewSection)
Transfers the given Block and all Symbols pointing to it to the given Section.
void mergeSections (Section &DstSection, Section &SrcSection, bool PreserveSrcSection=false)
Move all blocks and symbols from the source section to the destination section.
void removeExternalSymbol (Symbol &Sym)
Removes an external symbol. Also removes the underlying Addressable.
void removeAbsoluteSymbol (Symbol &Sym)
Remove an absolute symbol. Also removes the underlying Addressable.
void removeDefinedSymbol (Symbol &Sym)
Removes defined symbols. Does not remove the underlying block.
void removeBlock (Block &B)
Remove a block.
void removeSection (Section &Sec)
Remove a section.
void dump (raw_ostream &OS)
Dump the graph.
Detailed Description
Definition at line 784 of file JITLink.h.
Member Typedef Documentation
block_iterator
using llvm::jitlink::LinkGraph::block_iterator = nested_collection_iterator<const_section_iterator, Section::block_iterator, Block *, getSectionBlocks>
Definition at line 902 of file JITLink.h.
const_block_iterator
using llvm::jitlink::LinkGraph::const_block_iterator = nested_collection_iterator<const_section_iterator, Section::const_block_iterator, const Block *, getSectionConstBlocks>
Definition at line 906 of file JITLink.h.
const_defined_symbol_iterator
using llvm::jitlink::LinkGraph::const_defined_symbol_iterator = nested_collection_iterator<const_section_iterator, Section::const_symbol_iterator, const Symbol *, getSectionConstSymbols>
Definition at line 897 of file JITLink.h.
const_section_iterator
using llvm::jitlink::LinkGraph::const_section_iterator = pointee_iterator<SectionList::const_iterator>
Definition at line 843 of file JITLink.h.
defined_symbol_iterator
using llvm::jitlink::LinkGraph::defined_symbol_iterator = nested_collection_iterator<const_section_iterator, Section::symbol_iterator, Symbol *, getSectionSymbols>
Definition at line 892 of file JITLink.h.
external_symbol_iterator
using llvm::jitlink::LinkGraph::external_symbol_iterator = ExternalSymbolSet::iterator
Definition at line 840 of file JITLink.h.
GetEdgeKindNameFunction
using llvm::jitlink::LinkGraph::GetEdgeKindNameFunction = const char *(*)(Edge::Kind)
Definition at line 911 of file JITLink.h.
section_iterator
using llvm::jitlink::LinkGraph::section_iterator = pointee_iterator<SectionList::iterator>
Definition at line 842 of file JITLink.h.
SplitBlockCache
using llvm::jitlink::LinkGraph::SplitBlockCache = Optional<SmallVector<Symbol *, 8> >
Cache type for the splitBlock function.
Definition at line 999 of file JITLink.h.
Constructor & Destructor Documentation
LinkGraph()
llvm::jitlink::LinkGraph::LinkGraph (std::string Name, const Triple & TT, unsigned PointerSize, support::endianness Endianness, GetEdgeKindNameFunction GetEdgeKindName) inline
Definition at line 913 of file JITLink.h.
Member Function Documentation
absolute_symbols()
iterator_range<external_symbol_iterator> llvm::jitlink::LinkGraph::absolute_symbols () inline
Definition at line 1145 of file JITLink.h.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::begin(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::end(), and llvm::make_range().
addAbsoluteSymbol()
Symbol& llvm::jitlink::LinkGraph::addAbsoluteSymbol (StringRef Name, JITTargetAddress Address, uint64_t Size, Linkage L, Scope S, bool IsLive) inline
Add an absolute symbol.
Definition at line 1058 of file JITLink.h.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), assert(), llvm::count_if(), llvm::jitlink::Symbol::getName(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), S, and llvm::Check::Size.
addAnonymousSymbol()
Symbol& llvm::jitlink::LinkGraph::addAnonymousSymbol (Block & Content, JITTargetAddress Offset, JITTargetAddress Size, bool IsCallable, bool IsLive) inline
Add an anonymous symbol.
Definition at line 1090 of file JITLink.h.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), Content, Offset, and llvm::Check::Size.
addCommonSymbol()
Symbol& llvm::jitlink::LinkGraph::addCommonSymbol (StringRef Name, Scope S, Section & Section, JITTargetAddress Address, uint64_t Size, uint64_t Alignment, bool IsLive) inline
Convenience method for adding a weak zero-fill symbol.
Definition at line 1073 of file JITLink.h.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), assert(), llvm::count_if(), defined_symbols(), llvm::jitlink::Symbol::getName(), S, and llvm::Check::Size.
addDefinedSymbol()
Symbol& llvm::jitlink::LinkGraph::addDefinedSymbol (Block & Content, JITTargetAddress Offset, StringRef Name, JITTargetAddress Size, Linkage L, Scope S, bool IsCallable, bool IsLive) inline
Add a named symbol.
Definition at line 1100 of file JITLink.h.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), assert(), Content, llvm::count_if(), defined_symbols(), llvm::jitlink::Symbol::getName(), Offset, S, and llvm::Check::Size.
addExternalSymbol()
Symbol& llvm::jitlink::LinkGraph::addExternalSymbol (StringRef Name, uint64_t Size, Linkage L) inline
Add an external symbol.
Some formats (e.g. ELF) allow Symbols to have sizes. For Symbols whose size is not known, you should substitute '0'. For external symbols Linkage determines whether the symbol must be present during lookup: Externals with strong linkage must be found or an error will be emitted. Externals with weak linkage are permitted to be undefined, in which case they are assigned a value of 0.
Definition at line 1044 of file JITLink.h.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), assert(), llvm::count_if(), llvm::jitlink::Symbol::getName(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), and llvm::Check::Size.
allocateBuffer()
MutableArrayRef<char> llvm::jitlink::LinkGraph::allocateBuffer (size_t Size) inline
Allocate a mutable buffer of the given size using the LinkGraph's allocator.
Definition at line 936 of file JITLink.h.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), and llvm::Check::Size.
allocateContent()
MutableArrayRef<char> llvm::jitlink::LinkGraph::allocateContent (ArrayRef< char > Source) inline
Allocate a copy of the given string using the LinkGraph's allocator.
This can be useful when renaming symbols or adding new content to the graph.
Definition at line 943 of file JITLink.h.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), llvm::copy(), and llvm::Sched::Source.
allocateString()
MutableArrayRef<char> llvm::jitlink::LinkGraph::allocateString (Twine Source) inline
Allocate a copy of the given string using the LinkGraph's allocator.
This can be useful when renaming symbols or adding new content to the graph.
Note: This Twine-based overload requires an extra string copy and an extra heap allocation for large strings. The ArrayRef<char> overload should be preferred where possible.
Definition at line 956 of file JITLink.h.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), llvm::copy(), and llvm::Sched::Source.
blocks() [1/2]
iterator_range<block_iterator> llvm::jitlink::LinkGraph::blocks () inline
Definition at line 1131 of file JITLink.h.
References llvm::make_range().
Referenced by llvm::jitlink::PerGraphGOTAndPLTStubsBuilder< BuilderImplT >::run().
blocks() [2/2]
iterator_range<const_block_iterator> llvm::jitlink::LinkGraph::blocks () const inline
Definition at line 1136 of file JITLink.h.
References llvm::make_range().
createContentBlock()
Block& llvm::jitlink::LinkGraph::createContentBlock (Section & Parent, ArrayRef< char > Content, uint64_t Address, uint64_t Alignment, uint64_t AlignmentOffset) inline
Create a content block.
Definition at line 977 of file JITLink.h.
References Content.
createMutableContentBlock()
Block& llvm::jitlink::LinkGraph::createMutableContentBlock (Section & Parent, MutableArrayRef< char > MutableContent, uint64_t Address, uint64_t Alignment, uint64_t AlignmentOffset) inline
Create a content block with initially mutable data.
Definition at line 984 of file JITLink.h.
createSection()
Section& llvm::jitlink::LinkGraph::createSection (StringRef Name, sys::Memory::ProtectionFlags Prot) inline
Create a section with the given name, protection flags, and alignment.
Definition at line 965 of file JITLink.h.
References assert(), llvm::find_if(), move, and llvm::ARMBuildAttrs::Section.
createZeroFillBlock()
Block& llvm::jitlink::LinkGraph::createZeroFillBlock (Section & Parent, uint64_t Size, uint64_t Address, uint64_t Alignment, uint64_t AlignmentOffset) inline
Create a zero-fill block.
Definition at line 993 of file JITLink.h.
References llvm::Check::Size.
defined_symbols() [1/2]
iterator_range<defined_symbol_iterator> llvm::jitlink::LinkGraph::defined_symbols () inline
Definition at line 1149 of file JITLink.h.
References llvm::make_range().
Referenced by addCommonSymbol(), and addDefinedSymbol().
defined_symbols() [2/2]
iterator_range<const_defined_symbol_iterator> llvm::jitlink::LinkGraph::defined_symbols () const inline
Definition at line 1154 of file JITLink.h.
References llvm::make_range().
dump()
void llvm::jitlink::LinkGraph::dump (raw_ostream & OS)
Dump the graph.
Definition at line 229 of file JITLink.cpp.
References llvm::sort().
external_symbols()
iterator_range<external_symbol_iterator> llvm::jitlink::LinkGraph::external_symbols () inline
Definition at line 1141 of file JITLink.h.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::begin(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::end(), and llvm::make_range().
findSectionByName()
Section* llvm::jitlink::LinkGraph::findSectionByName (StringRef Name) inline
Returns the section with the given name if it exists, otherwise returns null.
Definition at line 1124 of file JITLink.h.
References S, and sections().
getEdgeKindName()
const char* llvm::jitlink::LinkGraph::getEdgeKindName (Edge::Kind K) const inline
Definition at line 932 of file JITLink.h.
Referenced by llvm::jitlink::PerGraphGOTAndPLTStubsBuilder< BuilderImplT >::run().
getEndianness()
support::endianness llvm::jitlink::LinkGraph::getEndianness () const inline
Returns the endianness of content in this graph.
Definition at line 930 of file JITLink.h.
getName()
const std::string& llvm::jitlink::LinkGraph::getName () const inline
Returns the name of this graph (usually the name of the original underlying MemoryBuffer).
Definition at line 921 of file JITLink.h.
getPointerSize()
unsigned llvm::jitlink::LinkGraph::getPointerSize () const inline
Returns the pointer size for use in this graph.
Definition at line 927 of file JITLink.h.
getTargetTriple()
const Triple& llvm::jitlink::LinkGraph::getTargetTriple () const inline
Returns the target triple for this Graph.
Definition at line 924 of file JITLink.h.
makeAbsolute()
void llvm::jitlink::LinkGraph::makeAbsolute (Symbol & Sym, JITTargetAddress Address) inline
Make the given symbol an absolute with the given address (must not already be absolute).
Symbol size, linkage, scope, and callability, and liveness will be left unchanged. Symbol offset will be reset to 0.
Definition at line 1186 of file JITLink.h.
References assert(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::count(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::erase(), llvm::jitlink::Symbol::getAddressable(), llvm::jitlink::Symbol::getBlock(), llvm::jitlink::Symbol::getOffset(), llvm::jitlink::Block::getSection(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), llvm::jitlink::Symbol::isAbsolute(), llvm::jitlink::Symbol::isDefined(), and llvm::jitlink::Symbol::isExternal().
makeDefined()
void llvm::jitlink::LinkGraph::makeDefined (Symbol & Sym, Block & Content, JITTargetAddress Offset, JITTargetAddress Size, Linkage L, Scope S, bool IsLive) inline
Turn an absolute or external symbol into a defined one by attaching it to a block.
Symbol must not already be defined.
Definition at line 1205 of file JITLink.h.
References assert(), Content, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::count(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::erase(), llvm::jitlink::Symbol::isAbsolute(), llvm::jitlink::Symbol::isDefined(), Offset, S, llvm::jitlink::Symbol::setLinkage(), llvm::jitlink::Symbol::setLive(), llvm::jitlink::Symbol::setScope(), llvm::jitlink::Symbol::setSize(), and llvm::Check::Size.
makeExternal()
void llvm::jitlink::LinkGraph::makeExternal (Symbol & Sym) inline
Make the given symbol external (must not already be external).
Symbol size, linkage and callability will be left unchanged. Symbol scope will be set to Default, and offset will be reset to 0.
Definition at line 1164 of file JITLink.h.
References assert(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::count(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::erase(), llvm::jitlink::Symbol::getAddressable(), llvm::jitlink::Symbol::getBlock(), llvm::jitlink::Symbol::getOffset(), llvm::jitlink::Block::getSection(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), llvm::jitlink::Symbol::isAbsolute(), llvm::jitlink::Symbol::isDefined(), and llvm::jitlink::Symbol::isExternal().
mergeSections()
void llvm::jitlink::LinkGraph::mergeSections (Section & DstSection, Section & SrcSection, bool PreserveSrcSection = false) inline
Move all blocks and symbols from the source section to the destination section.
If PreserveSrcSection is true (or SrcSection and DstSection are the same) then SrcSection is preserved, otherwise it is removed (the default).
Definition at line 1279 of file JITLink.h.
References removeSection().
removeAbsoluteSymbol()
void llvm::jitlink::LinkGraph::removeAbsoluteSymbol (Symbol & Sym) inline
Remove an absolute symbol. Also removes the underlying Addressable.
Definition at line 1304 of file JITLink.h.
References assert(), llvm::sampleprof::Base, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::count(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::end(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::erase(), llvm::find_if(), llvm::jitlink::Symbol::isAbsolute(), and llvm::jitlink::Symbol::isDefined().
removeBlock()
void llvm::jitlink::LinkGraph::removeBlock (Block & B) inline
Remove a block.
The block reference is defunct after calling this function and should no longer be used.
Definition at line 1328 of file JITLink.h.
References assert(), B, and llvm::none_of().
removeDefinedSymbol()
void llvm::jitlink::LinkGraph::removeDefinedSymbol (Symbol & Sym) inline
Removes defined symbols. Does not remove the underlying block.
Definition at line 1320 of file JITLink.h.
References assert(), llvm::jitlink::Symbol::getBlock(), llvm::jitlink::Block::getSection(), and llvm::jitlink::Symbol::isDefined().
removeExternalSymbol()
void llvm::jitlink::LinkGraph::removeExternalSymbol (Symbol & Sym) inline
Removes an external symbol. Also removes the underlying Addressable.
Definition at line 1289 of file JITLink.h.
References assert(), llvm::sampleprof::Base, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::count(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::end(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::erase(), llvm::find_if(), llvm::jitlink::Symbol::isAbsolute(), and llvm::jitlink::Symbol::isDefined().
removeSection()
void llvm::jitlink::LinkGraph::removeSection (Section & Sec) inline
Remove a section.
The section reference is defunct after calling this function and should no longer be used.
Definition at line 1340 of file JITLink.h.
References assert(), llvm::find_if(), I, and S.
Referenced by mergeSections().
sections()
iterator_range<section_iterator> llvm::jitlink::LinkGraph::sections () inline
Definition at line 1115 of file JITLink.h.
References llvm::make_range().
Referenced by findSectionByName(), and llvm::orc::DebugObjectManagerPlugin::modifyPassConfig().
sections_size()
SectionList::size_type llvm::jitlink::LinkGraph::sections_size () const inline
Definition at line 1120 of file JITLink.h.
splitBlock()
Block & llvm::jitlink::LinkGraph::splitBlock (Block & B, size_t SplitIndex, SplitBlockCache * Cache = nullptr)
Splits block B at the given index which must be greater than zero.
If SplitIndex == B.getSize() then this function is a no-op and returns B. If SplitIndex < B.getSize() then this function returns a new block covering the range [ 0, SplitIndex), and B is modified to cover the range [ SplitIndex, B.size()).
The optional Cache parameter can be used to speed up repeated calls to splitBlock for a single block. If the value is None the cache will be treated as uninitialized and splitBlock will populate it. Otherwise it is assumed to contain the list of Symbols pointing at B, sorted in descending order of offset.
Notes:
splitBlock must be used with care. Splitting a block may cause incoming edges to become invalid if the edge target subexpression points outside the bounds of the newly split target block (E.g. an edge 'S + 10 : Pointer64' where S points to a newly split block whose size is less than 10). No attempt is made to detect invalidation of incoming edges, as in general this requires context that the LinkGraph does not have. Clients are responsible for ensuring that splitBlock is not used in a way that invalidates edges.
The newly introduced block will have a new ordinal which will be higher than any other ordinals in the section. Clients are responsible for re-assigning block ordinals to restore a compatible order if needed.
The cache is not automatically updated if new symbols are introduced between calls to splitBlock. Any newly introduced symbols may be added to the cache manually (descending offset order must be preserved), or the cache can be set to None and rebuilt by splitBlock on the next call.
Definition at line 154 of file JITLink.cpp.
References assert(), B, llvm::jitlink::Symbol::getOffset(), I, llvm::None, and llvm::sort().
transferBlock()
void llvm::jitlink::LinkGraph::transferBlock (Block & B, Section & NewSection) inline
Transfers the given Block and all Symbols pointing to it to the given Section.
No attempt is made to check compatibility of the source and destination sections. Blocks may be moved between sections with incompatible permissions (e.g. from data to text). The client is responsible for ensuring that this is safe.
Definition at line 1258 of file JITLink.h.
References B, and S.
transferDefinedSymbol()
void llvm::jitlink::LinkGraph::transferDefinedSymbol (Symbol & Sym, Block & DestBlock, JITTargetAddress NewOffset, Optional< JITTargetAddress > ExplicitNewSize) inline
Transfer a defined symbol from one block to another.
The symbol's offset within DestBlock is set to NewOffset.
If ExplicitNewSize is given as None then the size of the symbol will be checked and auto-truncated to at most the size of the remainder (from the given offset) of the size of the new block.
All other symbol attributes are unchanged.
Definition at line 1237 of file JITLink.h.
References llvm::jitlink::Block::getSize(), llvm::jitlink::Symbol::getSize(), and llvm::jitlink::Symbol::setSize().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/JITLink/JITLink.h
lib/ExecutionEngine/JITLink/JITLink.cpp