LLVM: llvm::VEMachineFunctionInfo Class Reference
llvm::VEMachineFunctionInfo Class Reference
#include "Target/VE/VEMachineFunctionInfo.h"
Public Member Functions
VEMachineFunctionInfo ()
VEMachineFunctionInfo (MachineFunction &MF)
Register getGlobalBaseReg () const
void setGlobalBaseReg (Register Reg)
int getVarArgsFrameOffset () const
void setVarArgsFrameOffset (int Offset)
void setLeafProc (bool rhs)
bool isLeafProc () const
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, MachineFunction &MF)
Factory function: default behavior is to call new using the supplied allocator.
Detailed Description
Definition at line 19 of file VEMachineFunctionInfo.h.
Constructor & Destructor Documentation
VEMachineFunctionInfo() [1/2]
llvm::VEMachineFunctionInfo::VEMachineFunctionInfo () inline
Definition at line 32 of file VEMachineFunctionInfo.h.
VEMachineFunctionInfo() [2/2]
llvm::VEMachineFunctionInfo::VEMachineFunctionInfo (MachineFunction & MF) inline explicit
Definition at line 34 of file VEMachineFunctionInfo.h.
Member Function Documentation
getGlobalBaseReg()
Register llvm::VEMachineFunctionInfo::getGlobalBaseReg () const inline
Definition at line 37 of file VEMachineFunctionInfo.h.
Referenced by llvm::VEInstrInfo::getGlobalBaseReg(), and llvm::VEFrameLowering::hasGOT().
getVarArgsFrameOffset()
int llvm::VEMachineFunctionInfo::getVarArgsFrameOffset () const inline
Definition at line 40 of file VEMachineFunctionInfo.h.
Referenced by llvm::VETargetLowering::lowerVASTART().
isLeafProc()
bool llvm::VEMachineFunctionInfo::isLeafProc () const inline
Definition at line 44 of file VEMachineFunctionInfo.h.
Referenced by llvm::VEFrameLowering::emitEpilogue(), llvm::VEFrameLowering::emitEpilogueInsns(), llvm::VEFrameLowering::emitPrologue(), and llvm::VEFrameLowering::emitPrologueInsns().
setGlobalBaseReg()
void llvm::VEMachineFunctionInfo::setGlobalBaseReg (Register Reg) inline
Definition at line 38 of file VEMachineFunctionInfo.h.
References Reg.
Referenced by llvm::VEInstrInfo::getGlobalBaseReg().
setLeafProc()
void llvm::VEMachineFunctionInfo::setLeafProc (bool rhs) inline
Definition at line 43 of file VEMachineFunctionInfo.h.
Referenced by llvm::VEFrameLowering::determineCalleeSaves().
setVarArgsFrameOffset()
void llvm::VEMachineFunctionInfo::setVarArgsFrameOffset (int Offset) inline
Definition at line 41 of file VEMachineFunctionInfo.h.
References Offset.
Referenced by llvm::VETargetLowering::LowerFormalArguments().
The documentation for this class was generated from the following files:
lib/Target/VE/VEMachineFunctionInfo.h
lib/Target/VE/VEMachineFunctionInfo.cpp