LLVM: SCEVLoopGuardRewriter Class Reference
SCEVLoopGuardRewriter Class Reference
This rewriter is similar to SCEVParameterRewriter (it replaces SCEVUnknown components following the Map (Value -> SCEV)), but skips AddRecExpr because we cannot guarantee that the replacement is loop invariant in the loop of the AddRec.
Public Member Functions
SCEVLoopGuardRewriter (ScalarEvolution &SE, ValueToSCEVMapTy &M)
const SCEV * visitAddRecExpr (const SCEVAddRecExpr *Expr)
const SCEV * visitUnknown (const SCEVUnknown *Expr)
Public Member Functions inherited from llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >
SCEVRewriteVisitor (ScalarEvolution &SE)
const SCEV * visit (const SCEV *S)
const SCEV * visitConstant (const SCEVConstant *Constant)
const SCEV * visitPtrToIntExpr (const SCEVPtrToIntExpr *Expr)
const SCEV * visitTruncateExpr (const SCEVTruncateExpr *Expr)
const SCEV * visitZeroExtendExpr (const SCEVZeroExtendExpr *Expr)
const SCEV * visitSignExtendExpr (const SCEVSignExtendExpr *Expr)
const SCEV * visitAddExpr (const SCEVAddExpr *Expr)
const SCEV * visitMulExpr (const SCEVMulExpr *Expr)
const SCEV * visitUDivExpr (const SCEVUDivExpr *Expr)
const SCEV * visitAddRecExpr (const SCEVAddRecExpr *Expr)
const SCEV * visitSMaxExpr (const SCEVSMaxExpr *Expr)
const SCEV * visitUMaxExpr (const SCEVUMaxExpr *Expr)
const SCEV * visitSMinExpr (const SCEVSMinExpr *Expr)
const SCEV * visitUMinExpr (const SCEVUMinExpr *Expr)
const SCEV * visitUnknown (const SCEVUnknown *Expr)
const SCEV * visitCouldNotCompute (const SCEVCouldNotCompute *Expr)
Public Member Functions inherited from llvm::SCEVVisitor< SCEVLoopGuardRewriter, const SCEV * >
const SCEV * visit (const SCEV *S)
const SCEV * visitCouldNotCompute (const SCEVCouldNotCompute *S)
Additional Inherited Members
Protected Attributes inherited from llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >
ScalarEvolution & SE
DenseMap< const SCEV *, const SCEV * > RewriteResults
Detailed Description
This rewriter is similar to SCEVParameterRewriter (it replaces SCEVUnknown components following the Map (Value -> SCEV)), but skips AddRecExpr because we cannot guarantee that the replacement is loop invariant in the loop of the AddRec.
Definition at line 13904 of file ScalarEvolution.cpp.
Constructor & Destructor Documentation
SCEVLoopGuardRewriter()
SCEVLoopGuardRewriter::SCEVLoopGuardRewriter (ScalarEvolution & SE, ValueToSCEVMapTy & M) inline
Definition at line 13908 of file ScalarEvolution.cpp.
References M.
Member Function Documentation
visitAddRecExpr()
const SCEV* SCEVLoopGuardRewriter::visitAddRecExpr (const SCEVAddRecExpr * Expr) inline
Definition at line 13911 of file ScalarEvolution.cpp.
visitUnknown()
const SCEV* SCEVLoopGuardRewriter::visitUnknown (const SCEVUnknown * Expr) inline
Definition at line 13913 of file ScalarEvolution.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::SCEVUnknown::getValue(), and I.
The documentation for this class was generated from the following file:
lib/Analysis/ScalarEvolution.cpp