LLVM: llvm::ARCSubtarget Class Reference
llvm::ARCSubtarget Class Reference
#include "Target/ARC/ARCSubtarget.h"
Public Member Functions
ARCSubtarget (const Triple &TT, const std::string &CPU, const std::string &FS, const TargetMachine &TM)
This constructor initializes the data members to match that of the specified triple.
void ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
Parses features string setting specified subtarget options.
const ARCInstrInfo * getInstrInfo () const override
const ARCFrameLowering * getFrameLowering () const override
const ARCTargetLowering * getTargetLowering () const override
const ARCRegisterInfo * getRegisterInfo () const override
const SelectionDAGTargetInfo * getSelectionDAGInfo () const override
bool hasNorm () const
Detailed Description
Definition at line 31 of file ARCSubtarget.h.
Constructor & Destructor Documentation
ARCSubtarget()
ARCSubtarget::ARCSubtarget (const Triple & TT, const std::string & CPU, const std::string & FS, const TargetMachine & TM)
This constructor initializes the data members to match that of the specified triple.
Definition at line 27 of file ARCSubtarget.cpp.
Member Function Documentation
getFrameLowering()
const ARCFrameLowering* llvm::ARCSubtarget::getFrameLowering () const inline override
Definition at line 51 of file ARCSubtarget.h.
getInstrInfo()
const ARCInstrInfo* llvm::ARCSubtarget::getInstrInfo () const inline override
Definition at line 50 of file ARCSubtarget.h.
Referenced by llvm::ARCFrameLowering::emitPrologue().
getRegisterInfo()
const ARCRegisterInfo* llvm::ARCSubtarget::getRegisterInfo () const inline override
Definition at line 57 of file ARCSubtarget.h.
References llvm::ARCInstrInfo::getRegisterInfo().
Referenced by llvm::ARCTargetLowering::ARCTargetLowering().
getSelectionDAGInfo()
const SelectionDAGTargetInfo* llvm::ARCSubtarget::getSelectionDAGInfo () const inline override
Definition at line 60 of file ARCSubtarget.h.
getTargetLowering()
const ARCTargetLowering* llvm::ARCSubtarget::getTargetLowering () const inline override
Definition at line 54 of file ARCSubtarget.h.
hasNorm()
bool llvm::ARCSubtarget::hasNorm () const inline
Definition at line 64 of file ARCSubtarget.h.
ParseSubtargetFeatures()
void llvm::ARCSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
Parses features string setting specified subtarget options.
Definition of function is auto generated by tblgen.
The documentation for this class was generated from the following files:
lib/Target/ARC/ARCSubtarget.h
lib/Target/ARC/ARCSubtarget.cpp