LLVM: DefaultInlineOrder< T, Container > Class Template Reference
DefaultInlineOrder< T, Container > Class Template Reference
Public Member Functions
size_t size () override
void push (const T &Elt) override
T pop () override
const_reference front () override
void erase_if (function_ref< bool(T)> Pred) override
Public Member Functions inherited from InlineOrder< T >
virtual ~InlineOrder ()
bool empty ()
Additional Inherited Members
Public Types inherited from InlineOrder< T >
using reference = T &
using const_reference = const T &
Detailed Description
template<typename T, typename Container = SmallVector<T, 16>>
class DefaultInlineOrder< T, Container >
Definition at line 698 of file Inliner.cpp.
Member Function Documentation
erase_if()
template<typename T , typename Container = SmallVector<T, 16>> void DefaultInlineOrder< T, Container >::erase_if (function_ref< bool(T)> Pred) inline override virtual
Implements InlineOrder< T >.
Definition at line 717 of file Inliner.cpp.
References llvm::remove_if().
front()
template<typename T , typename Container = SmallVector<T, 16>> const_reference DefaultInlineOrder< T, Container >::front () inline override virtual
Implements InlineOrder< T >.
Definition at line 712 of file Inliner.cpp.
References assert(), and llvm::size().
pop()
template<typename T , typename Container = SmallVector<T, 16>> T DefaultInlineOrder< T, Container >::pop () inline override virtual
Implements InlineOrder< T >.
Definition at line 707 of file Inliner.cpp.
References assert(), and llvm::size().
push()
template<typename T , typename Container = SmallVector<T, 16>> void DefaultInlineOrder< T, Container >::push (const T & Elt) inline override virtual
Implements InlineOrder< T >.
Definition at line 705 of file Inliner.cpp.
size()
template<typename T , typename Container = SmallVector<T, 16>> size_t DefaultInlineOrder< T, Container >::size () inline override virtual
Implements InlineOrder< T >.
Definition at line 703 of file Inliner.cpp.
The documentation for this class was generated from the following file:
lib/Transforms/IPO/Inliner.cpp