LLVM: RedirectingFSDirRemapIterImpl Class Reference
RedirectingFSDirRemapIterImpl Class Reference
Directory iterator implementation for RedirectingFileSystem's directory remap entries that maps the paths reported by the external file system's directory iterator back to the virtual directory's path.
Public Member Functions
RedirectingFSDirRemapIterImpl (std::string DirPath, llvm::vfs::directory_iterator ExtIter)
void setCurrentEntry ()
std::error_code increment () override
Sets CurrentEntry to the next entry in the directory on success, to directory_entry() at end, or returns a system-defined error_code.
Public Member Functions inherited from llvm::vfs::detail::DirIterImpl
virtual ~DirIterImpl ()
Additional Inherited Members
Public Attributes inherited from llvm::vfs::detail::DirIterImpl
directory_entry CurrentEntry
Detailed Description
Directory iterator implementation for RedirectingFileSystem's directory remap entries that maps the paths reported by the external file system's directory iterator back to the virtual directory's path.
Definition at line 1097 of file VirtualFileSystem.cpp.
Constructor & Destructor Documentation
RedirectingFSDirRemapIterImpl()
RedirectingFSDirRemapIterImpl::RedirectingFSDirRemapIterImpl (std::string DirPath, llvm::vfs::directory_iterator ExtIter) inline
Definition at line 1103 of file VirtualFileSystem.cpp.
Member Function Documentation
increment()
std::error_code RedirectingFSDirRemapIterImpl::increment () inline override virtual
Sets CurrentEntry to the next entry in the directory on success, to directory_entry() at end, or returns a system-defined error_code.
Implements llvm::vfs::detail::DirIterImpl.
Definition at line 1122 of file VirtualFileSystem.cpp.
References llvm::vfs::directory_iterator::increment().
setCurrentEntry()
void RedirectingFSDirRemapIterImpl::setCurrentEntry () inline
Definition at line 1111 of file VirtualFileSystem.cpp.
References llvm::sys::path::append(), llvm::sys::path::filename(), llvm::vfs::directory_entry::path(), and llvm::vfs::directory_entry::type().
The documentation for this class was generated from the following file:
lib/Support/VirtualFileSystem.cpp