LLVM: FunctionSpecializer Class Reference
FunctionSpecializer Class Reference
Public Member Functions
FunctionSpecializer (SCCPSolver &Solver, std::function< AssumptionCache &(Function &)> GetAC, std::function< TargetTransformInfo &(Function &)> GetTTI, std::function< TargetLibraryInfo &(Function &)> GetTLI)
bool specializeFunctions (SmallVectorImpl< Function * > &FuncDecls, SmallVectorImpl< Function * > &CurrentSpecializations)
Attempt to specialize functions in the module to enable constant propagation across function boundaries.
bool tryToReplaceWithConstant (Value *V)
Detailed Description
Definition at line 76 of file FunctionSpecialization.cpp.
Constructor & Destructor Documentation
FunctionSpecializer()
FunctionSpecializer::FunctionSpecializer (SCCPSolver & Solver, std::function< AssumptionCache &(Function &)> GetAC, std::function< TargetTransformInfo &(Function &)> GetTTI, std::function< TargetLibraryInfo &(Function &)> GetTLI) inline
Definition at line 89 of file FunctionSpecialization.cpp.
Member Function Documentation
specializeFunctions()
bool FunctionSpecializer::specializeFunctions (SmallVectorImpl< Function * > & FuncDecls, SmallVectorImpl< Function * > & CurrentSpecializations) inline
Attempt to specialize functions in the module to enable constant propagation across function boundaries.
Returns
true if at least one function is specialized.
Definition at line 100 of file FunctionSpecialization.cpp.
References Arg, llvm::dbgs(), F, LLVM_DEBUG, and tryToReplaceWithConstant().
tryToReplaceWithConstant()
bool FunctionSpecializer::tryToReplaceWithConstant (Value * V) inline
Definition at line 133 of file FunctionSpecialization.cpp.
References llvm::UndefValue::get(), llvm::SCCPSolver::getConstant(), llvm::SCCPSolver::getLatticeValueFor(), llvm::Value::getType(), llvm::ValueLatticeElement::isConstant(), isOverdefined(), llvm::Type::isSingleValueType(), llvm::Value::replaceAllUsesWith(), and llvm::Value::user_empty().
The documentation for this class was generated from the following file:
lib/Transforms/IPO/FunctionSpecialization.cpp