LLVM: llvm::CGSCCToFunctionPassAdaptor Class Reference
llvm::CGSCCToFunctionPassAdaptor Class Reference
Adaptor that maps from a SCC to its functions.
#include "llvm/Analysis/CGSCCPassManager.h"
Public Types
using PassConceptT = detail::PassConcept< Function, FunctionAnalysisManager >
Public Member Functions
CGSCCToFunctionPassAdaptor (std::unique_ptr< PassConceptT > Pass)
CGSCCToFunctionPassAdaptor (CGSCCToFunctionPassAdaptor &&Arg)
CGSCCToFunctionPassAdaptor & operator= (CGSCCToFunctionPassAdaptor RHS)
PreservedAnalyses run (LazyCallGraph::SCC &C, CGSCCAnalysisManager &AM, LazyCallGraph &CG, CGSCCUpdateResult &UR)
Runs the function pass across every function in the module.
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< CGSCCToFunctionPassAdaptor >
static StringRef name ()
Gets the name of the pass we are mixed into.
Friends
void swap (CGSCCToFunctionPassAdaptor &LHS, CGSCCToFunctionPassAdaptor &RHS)
Detailed Description
Adaptor that maps from a SCC to its functions.
Designed to allow composition of a FunctionPass(Manager) and a CGSCCPassManager. Note that if this pass is constructed with a pointer to a CGSCCAnalysisManager it will run the FunctionAnalysisManagerCGSCCProxy analysis prior to running the function pass over the SCC to enable a FunctionAnalysisManager to be used within this run safely.
Definition at line 459 of file CGSCCPassManager.h.
Member Typedef Documentation
PassConceptT
using llvm::CGSCCToFunctionPassAdaptor::PassConceptT = detail::PassConcept<Function, FunctionAnalysisManager>
Definition at line 462 of file CGSCCPassManager.h.
Constructor & Destructor Documentation
CGSCCToFunctionPassAdaptor() [1/2]
llvm::CGSCCToFunctionPassAdaptor::CGSCCToFunctionPassAdaptor (std::unique_ptr< PassConceptT > Pass) inline explicit
Definition at line 464 of file CGSCCPassManager.h.
CGSCCToFunctionPassAdaptor() [2/2]
llvm::CGSCCToFunctionPassAdaptor::CGSCCToFunctionPassAdaptor (CGSCCToFunctionPassAdaptor && Arg) inline
Definition at line 467 of file CGSCCPassManager.h.
Member Function Documentation
isRequired()
static bool llvm::CGSCCToFunctionPassAdaptor::isRequired () inline static
Definition at line 484 of file CGSCCPassManager.h.
operator=()
CGSCCToFunctionPassAdaptor& llvm::CGSCCToFunctionPassAdaptor::operator= (CGSCCToFunctionPassAdaptor RHS) inline
Definition at line 475 of file CGSCCPassManager.h.
References std::swap().
run()
PreservedAnalyses llvm::CGSCCToFunctionPassAdaptor::run (LazyCallGraph::SCC & C, CGSCCAnalysisManager & AM, LazyCallGraph & CG, CGSCCUpdateResult & UR)
Runs the function pass across every function in the module.
Definition at line 521 of file CGSCCPassManager.cpp.
References llvm::PreservedAnalyses::all(), assert(), llvm::dbgs(), F, FAM, llvm::PreservedAnalyses::getChecker(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PreservedAnalyses::intersect(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), LLVM_DEBUG, llvm::LazyCallGraph::lookupSCC(), move, N, llvm::PreservedAnalyses::preserve(), llvm::PreservedAnalyses::preserveSet(), llvm::PassInstrumentation::runAfterPass(), llvm::PassInstrumentation::runBeforePass(), and llvm::updateCGAndAnalysisManagerForFunctionPass().
Friends And Related Function Documentation
swap
void swap (CGSCCToFunctionPassAdaptor & LHS, CGSCCToFunctionPassAdaptor & RHS) friend
Definition at line 470 of file CGSCCPassManager.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/CGSCCPassManager.h
lib/Analysis/CGSCCPassManager.cpp