LLVM: ScopedAliasMetadataDeepCloner Class Reference
ScopedAliasMetadataDeepCloner Class Reference
Utility for cloning !noalias and !alias.scope metadata.
Public Member Functions
ScopedAliasMetadataDeepCloner (const Function *F)
void clone ()
Create a new clone of the scoped alias metadata, which will be used by subsequent remap() calls.
void remap (Function::iterator FStart, Function::iterator FEnd)
Remap instructions in the given range from the original to the cloned metadata.
Detailed Description
Utility for cloning !noalias and !alias.scope metadata.
When a code region using scoped alias metadata is inlined, the aliasing relationships may not hold between the two version. It is necessary to create a deep clone of the metadata, putting the two versions in separate scope domains.
Definition at line 837 of file InlineFunction.cpp.
Constructor & Destructor Documentation
ScopedAliasMetadataDeepCloner()
ScopedAliasMetadataDeepCloner::ScopedAliasMetadataDeepCloner (const Function * F)
Definition at line 855 of file InlineFunction.cpp.
References BB, F, I, and M.
Member Function Documentation
clone()
void ScopedAliasMetadataDeepCloner::clone ()
Create a new clone of the scoped alias metadata, which will be used by subsequent remap() calls.
Definition at line 883 of file InlineFunction.cpp.
References assert(), llvm::SmallVectorImpl< T >::clear(), llvm::MDNode::get(), llvm::MDTuple::getTemporary(), I, llvm::MDNode::isTemporary(), M, llvm::None, and llvm::MDNode::replaceAllUsesWith().
Referenced by llvm::InlineFunction().
remap()
void ScopedAliasMetadataDeepCloner::remap (Function::iterator FStart, Function::iterator FEnd)
Remap instructions in the given range from the original to the cloned metadata.
Definition at line 913 of file InlineFunction.cpp.
References BB, I, M, and llvm::make_range().
Referenced by llvm::InlineFunction().
The documentation for this class was generated from the following file:
lib/Transforms/Utils/InlineFunction.cpp