LLVM: llvm::orc::OrcRPCEPCJITLinkMemoryManager< OrcRPCEPCImplT > Class Template Reference
llvm::orc::OrcRPCEPCJITLinkMemoryManager< OrcRPCEPCImplT > Class Template Reference
JITLinkMemoryManager implementation for a process connected via an ORC RPC endpoint.
#include "llvm/ExecutionEngine/Orc/OrcRPCExecutorProcessControl.h"
Classes
class OrcRPCAllocation
Public Member Functions
OrcRPCEPCJITLinkMemoryManager (OrcRPCEPCImplT &Parent)
Expected< std::unique_ptr< Allocation > > allocate (const jitlink::JITLinkDylib *JD, const SegmentsRequestMap &Request) override
Create an Allocation object.
Public Member Functions inherited from llvm::jitlink::JITLinkMemoryManager
virtual ~JITLinkMemoryManager ()
Additional Inherited Members
Public Types inherited from llvm::jitlink::JITLinkMemoryManager
using ProtectionFlags = sys::Memory::ProtectionFlags
using SegmentsRequestMap = DenseMap< unsigned, SegmentRequest >
Detailed Description
template<typename OrcRPCEPCImplT>
class llvm::orc::OrcRPCEPCJITLinkMemoryManager< OrcRPCEPCImplT >
JITLinkMemoryManager implementation for a process connected via an ORC RPC endpoint.
Definition at line 28 of file OrcRPCExecutorProcessControl.h.
Constructor & Destructor Documentation
OrcRPCEPCJITLinkMemoryManager()
template<typename OrcRPCEPCImplT > llvm::orc::OrcRPCEPCJITLinkMemoryManager< OrcRPCEPCImplT >::OrcRPCEPCJITLinkMemoryManager (OrcRPCEPCImplT & Parent) inline
Definition at line 148 of file OrcRPCExecutorProcessControl.h.
Member Function Documentation
allocate()
template<typename OrcRPCEPCImplT > Expected<std::unique_ptr<Allocation> > llvm::orc::OrcRPCEPCJITLinkMemoryManager< OrcRPCEPCImplT >::allocate (const jitlink::JITLinkDylib * JD, const SegmentsRequestMap & Request) inline override virtual
Create an Allocation object.
The JD argument represents the target JITLinkDylib, and can be used by JITLinkMemoryManager implementers to manage per-dylib allocation pools (e.g. one pre-reserved address space slab per dylib to ensure that all allocations for the dylib are within a certain range). The JD argument may be null (representing an allocation not associated with any JITDylib.
The request argument describes the segment sizes and permisssions being requested.
Implements llvm::jitlink::JITLinkMemoryManager.
Definition at line 151 of file OrcRPCExecutorProcessControl.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin(), llvm::dbgs(), DEBUG_WITH_TYPE, E, llvm::formatv(), llvm::orc::orcrpctpc::fromWireProtectionFlags(), llvm::inconvertibleErrorCode(), llvm::max(), llvm::sys::Memory::MF_EXEC, llvm::sys::Memory::MF_READ, llvm::sys::Memory::MF_WRITE, move, and llvm::orc::orcrpctpc::toWireProtectionFlags().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/OrcRPCExecutorProcessControl.h