LLVM: llvm::orc::remote::OrcRemoteTargetClient Class Reference
llvm::orc::remote::OrcRemoteTargetClient Class Reference
This class provides utilities (including memory manager, indirect stubs manager, and compile callback manager types) that support remote JITing in ORC.
#include "llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h"
Classes
class RemoteCompileCallbackManager
Remote compile callback manager.
class RemoteIndirectStubsManager
Remote indirect stubs manager.
class RemoteJITLinkMemoryManager
class RemoteRTDyldMemoryManager
Remote-mapped RuntimeDyld-compatible memory manager.
class RemoteTrampolinePool
class RPCMMAlloc
Public Member Functions
Expected< int > callIntVoid (JITTargetAddress Addr)
Call the int(void) function at the given address in the target and return its result.
Expected< int > callIntInt (JITTargetAddress Addr, int Arg)
Call the int(int) function at the given address in the target and return its result.
Expected< int > callMain (JITTargetAddress Addr, const std::vector< std::string > &Args)
Call the int(int, char*[]) function at the given address in the target and return its result.
Error callVoidVoid (JITTargetAddress Addr)
Call the void() function at the given address in the target and wait for it to finish.
Expected< std::unique_ptr< RemoteRTDyldMemoryManager > > createRemoteMemoryManager ()
Create an RCMemoryManager which will allocate its memory on the remote target.
Expected< std::unique_ptr< RemoteJITLinkMemoryManager > > createRemoteJITLinkMemoryManager ()
Create a JITLink-compatible memory manager which will allocate working memory on the host and target memory on the remote target.
Expected< std::unique_ptr< RemoteIndirectStubsManager > > createIndirectStubsManager ()
Create an RCIndirectStubsManager that will allocate stubs on the remote target.
Expected< RemoteCompileCallbackManager & > enableCompileCallbacks (JITTargetAddress ErrorHandlerAddress)
Expected< JITTargetAddress > getSymbolAddress (StringRef Name)
Search for symbols in the remote process.
const std::string & getTargetTriple () const
Get the triple for the remote target.
Error terminateSession ()
Public Member Functions inherited from llvm::orc::shared::SingleThreadedRPCEndpoint< shared::RawByteChannel >
SingleThreadedRPCEndpoint (shared::RawByteChannel &C, bool LazyAutoNegotiation)
void addHandler (HandlerT Handler)
void addHandler (ClassT &Object, RetT(ClassT::*Method)(ArgTs...))
void addAsyncHandler (HandlerT Handler)
void addAsyncHandler (ClassT &Object, RetT(ClassT::*Method)(ArgTs...))
Add a class-method as a handler.
detail::ResultTraits< AltRetT >::ErrorReturnType callB (const ArgTs &...Args)
Public Member Functions inherited from llvm::orc::shared::detail::RPCEndpointBase< SingleThreadedRPCEndpoint< shared::RawByteChannel, uint32_t, uint32_t >, shared::RawByteChannel, uint32_t, uint32_t >
RPCEndpointBase (shared::RawByteChannel &C, bool LazyAutoNegotiation)
Construct an RPC instance on a channel.
Error negotiateFunction (bool Retry=false)
Negotiate a function id for Func with the other end of the channel.
Error appendCallAsync (HandlerT Handler, const ArgTs &...Args)
Append a call Func, does not call send on the channel.
Error sendAppendedCalls ()
Error callAsync (HandlerT Handler, const ArgTs &...Args)
Error handleOne ()
Handle one incoming call.
void abandonPendingResponses ()
Abandon all outstanding result handlers.
void removeHandler ()
Remove the handler for the given function.
void clearHandlers ()
Clear all handlers.
Static Public Member Functions
static Expected< std::unique_ptr< OrcRemoteTargetClient > > Create (shared::RawByteChannel &Channel, ExecutionSession &ES)
Create an OrcRemoteTargetClient.
Static Public Member Functions inherited from llvm::orc::shared::detail::RPCEndpointBase< SingleThreadedRPCEndpoint< shared::RawByteChannel, uint32_t, uint32_t >, shared::RawByteChannel, uint32_t, uint32_t >
static detail::ReadArgs< ArgTs... > readArgs (ArgTs &...Args)
Helper for handling setter procedures - this method returns a functor that sets the variables referred to by Args...
Additional Inherited Members
Protected Types inherited from llvm::orc::shared::detail::RPCEndpointBase< SingleThreadedRPCEndpoint< shared::RawByteChannel, uint32_t, uint32_t >, shared::RawByteChannel, uint32_t, uint32_t >
using WrappedHandlerFn = std::function< Error(shared::RawByteChannel &, uint32_t)>
Protected Member Functions inherited from llvm::orc::shared::detail::RPCEndpointBase< SingleThreadedRPCEndpoint< shared::RawByteChannel, uint32_t, uint32_t >, shared::RawByteChannel, uint32_t, uint32_t >
uint32_t getInvalidFunctionId () const
void addHandlerImpl (HandlerT Handler)
Add the given handler to the handler map and make it available for autonegotiation and execution.
void addAsyncHandlerImpl (HandlerT Handler)
Error handleResponse (uint32_t SeqNo)
uint32_t handleNegotiate (const std::string &Name)
Expected< uint32_t > getRemoteFunctionId (bool NegotiateIfNotInMap, bool NegotiateIfInvalid)
WrappedHandlerFn wrapHandler (HandlerT Handler)
WrappedHandlerFn wrapAsyncHandler (HandlerT Handler)
Protected Attributes inherited from llvm::orc::shared::detail::RPCEndpointBase< SingleThreadedRPCEndpoint< shared::RawByteChannel, uint32_t, uint32_t >, shared::RawByteChannel, uint32_t, uint32_t >
shared::RawByteChannel & C
bool LazyAutoNegotiation
RPCFunctionIdAllocator< uint32_t > FnIdAllocator
uint32_t ResponseId
std::map< std::string, uint32_t > LocalFunctionIds
std::map< const char *, uint32_t > RemoteFunctionIds
std::map< uint32_t, WrappedHandlerFn > Handlers
std::mutex ResponsesMutex
detail::SequenceNumberManager< uint32_t > SequenceNumberMgr
std::map< uint32_t, std::unique_ptr< detail::ResponseHandler< shared::RawByteChannel > > > PendingResponses
Detailed Description
This class provides utilities (including memory manager, indirect stubs manager, and compile callback manager types) that support remote JITing in ORC.
Each of the utility classes talks to a JIT server (an instance of the OrcRemoteTargetServer class) via an RPC system (see RPCUtils.h) to carry out its actions.
Definition at line 56 of file OrcRemoteTargetClient.h.
Member Function Documentation
callIntInt()
Expected<int> llvm::orc::remote::OrcRemoteTargetClient::callIntInt (JITTargetAddress Addr, int Arg) inline
Call the int(int) function at the given address in the target and return its result.
Definition at line 725 of file OrcRemoteTargetClient.h.
References Addr, Arg, llvm::dbgs(), llvm::format(), and LLVM_DEBUG.
callIntVoid()
Expected<int> llvm::orc::remote::OrcRemoteTargetClient::callIntVoid (JITTargetAddress Addr) inline
Call the int(void) function at the given address in the target and return its result.
Definition at line 717 of file OrcRemoteTargetClient.h.
References Addr, llvm::dbgs(), llvm::format(), and LLVM_DEBUG.
callMain()
Expected<int> llvm::orc::remote::OrcRemoteTargetClient::callMain (JITTargetAddress Addr, const std::vector< std::string > & Args) inline
Call the int(int, char*[]) function at the given address in the target and return its result.
Definition at line 733 of file OrcRemoteTargetClient.h.
References Addr, llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::dbgs(), llvm::format(), and LLVM_DEBUG.
callVoidVoid()
Error llvm::orc::remote::OrcRemoteTargetClient::callVoidVoid (JITTargetAddress Addr) inline
Call the void() function at the given address in the target and wait for it to finish.
Definition at line 742 of file OrcRemoteTargetClient.h.
References Addr, llvm::dbgs(), llvm::format(), and LLVM_DEBUG.
Create()
static Expected<std::unique_ptr<OrcRemoteTargetClient> > llvm::orc::remote::OrcRemoteTargetClient::Create (shared::RawByteChannel & Channel, ExecutionSession & ES) inline static
Create an OrcRemoteTargetClient.
Channel is the ChannelT instance to communicate on. It is assumed that the channel is ready to be read from and written to.
Definition at line 706 of file OrcRemoteTargetClient.h.
createIndirectStubsManager()
Expected<std::unique_ptr<RemoteIndirectStubsManager> > llvm::orc::remote::OrcRemoteTargetClient::createIndirectStubsManager () inline
Create an RCIndirectStubsManager that will allocate stubs on the remote target.
Definition at line 774 of file OrcRemoteTargetClient.h.
References llvm::orc::remote::ResourceIdMgr::getNext().
createRemoteJITLinkMemoryManager()
Expected<std::unique_ptr<RemoteJITLinkMemoryManager> > llvm::orc::remote::OrcRemoteTargetClient::createRemoteJITLinkMemoryManager () inline
Create a JITLink-compatible memory manager which will allocate working memory on the host and target memory on the remote target.
Definition at line 762 of file OrcRemoteTargetClient.h.
References llvm::orc::remote::ResourceIdMgr::getNext().
createRemoteMemoryManager()
Expected<std::unique_ptr<RemoteRTDyldMemoryManager> > llvm::orc::remote::OrcRemoteTargetClient::createRemoteMemoryManager () inline
Create an RCMemoryManager which will allocate its memory on the remote target.
Definition at line 751 of file OrcRemoteTargetClient.h.
References llvm::orc::remote::ResourceIdMgr::getNext().
enableCompileCallbacks()
Expected<RemoteCompileCallbackManager &> llvm::orc::remote::OrcRemoteTargetClient::enableCompileCallbacks (JITTargetAddress ErrorHandlerAddress) inline
Definition at line 782 of file OrcRemoteTargetClient.h.
References assert().
getSymbolAddress()
Expected<JITTargetAddress> llvm::orc::remote::OrcRemoteTargetClient::getSymbolAddress (StringRef Name) inline
Search for symbols in the remote process.
Note: This should be used by symbol resolvers after they've searched the local symbol table in the JIT stack.
Definition at line 798 of file OrcRemoteTargetClient.h.
getTargetTriple()
const std::string& llvm::orc::remote::OrcRemoteTargetClient::getTargetTriple () const inline
Get the triple for the remote target.
Definition at line 803 of file OrcRemoteTargetClient.h.
terminateSession()
Error llvm::orc::remote::OrcRemoteTargetClient::terminateSession () inline
Definition at line 805 of file OrcRemoteTargetClient.h.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h