LLVM: llvm::DWARFDebugLine::SectionParser Class Reference
llvm::DWARFDebugLine::SectionParser Class Reference
Helper to allow for parsing of an entire .debug_line section in sequence.
#include "llvm/DebugInfo/DWARF/DWARFDebugLine.h"
Public Types
using LineToUnitMap = std::map< uint64_t, DWARFUnit * >
Public Member Functions
SectionParser (DWARFDataExtractor &Data, const DWARFContext &C, DWARFUnitVector::iterator_range Units)
LineTable parseNext (function_ref< void(Error)> RecoverableErrorHandler, function_ref< void(Error)> UnrecoverableErrorHandler, raw_ostream *OS=nullptr, bool Verbose=false)
Get the next line table from the section.
void skip (function_ref< void(Error)> RecoverableErrorHandler, function_ref< void(Error)> UnrecoverableErrorHandler)
Skip the current line table and go to the following line table (if present) immediately.
bool done () const
Indicates if the parser has parsed as much as possible.
uint64_t getOffset () const
Get the offset the parser has reached.
Detailed Description
Helper to allow for parsing of an entire .debug_line section in sequence.
Definition at line 316 of file DWARFDebugLine.h.
Member Typedef Documentation
LineToUnitMap
using llvm::DWARFDebugLine::SectionParser::LineToUnitMap = std::map<uint64_t, DWARFUnit *>
Definition at line 318 of file DWARFDebugLine.h.
Constructor & Destructor Documentation
SectionParser()
DWARFDebugLine::SectionParser::SectionParser (DWARFDataExtractor & Data, const DWARFContext & C, DWARFUnitVector::iterator_range Units)
Definition at line 1431 of file DWARFDebugLine.cpp.
References buildLineToUnitMap(), and llvm::DataExtractor::isValidOffset().
Member Function Documentation
done()
bool llvm::DWARFDebugLine::SectionParser::done () const inline
Indicates if the parser has parsed as much as possible.
Note
Certain problems with the line table structure might mean that parsing stops before the end of the section is reached.
Definition at line 352 of file DWARFDebugLine.h.
Referenced by llvm::DWARFContext::dump().
getOffset()
uint64_t llvm::DWARFDebugLine::SectionParser::getOffset () const inline
Get the offset the parser has reached.
Definition at line 355 of file DWARFDebugLine.h.
Referenced by llvm::DWARFContext::dump().
parseNext()
DWARFDebugLine::LineTable DWARFDebugLine::SectionParser::parseNext (function_ref< void(Error)> RecoverableErrorHandler, function_ref< void(Error)> UnrecoverableErrorHandler, raw_ostream * OS = nullptr, bool Verbose = false)
Get the next line table from the section.
Report any issues via the handlers.
Parameters
RecoverableErrorHandler - any issues that don't prevent further parsing of the table will be reported through this handler.
UnrecoverableErrorHandler - any issues that prevent further parsing of the table will be reported through this handler.
OS - if not null, the parser will print information about the table as it parses it.
Verbose - if true, the parser will print verbose information when printing to the output.
Definition at line 1444 of file DWARFDebugLine.cpp.
References assert(), llvm::DataExtractor::isValidOffset(), llvm::AArch64CC::LT, and Offset.
Referenced by llvm::DWARFContext::dump().
skip()
void DWARFDebugLine::SectionParser::skip (function_ref< void(Error)> RecoverableErrorHandler, function_ref< void(Error)> UnrecoverableErrorHandler)
Skip the current line table and go to the following line table (if present) immediately.
Parameters
RecoverableErrorHandler - report any recoverable prologue parsing issues via this handler.
UnrecoverableErrorHandler - report any unrecoverable prologue parsing issues via this handler.
Definition at line 1460 of file DWARFDebugLine.cpp.
References assert(), llvm::DataExtractor::isValidOffset(), llvm::AArch64CC::LT, and Offset.
Referenced by llvm::DWARFContext::dump().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDebugLine.h
lib/DebugInfo/DWARF/DWARFDebugLine.cpp