LLVM: lib/DebugInfo/GSYM/DwarfTransformer.cpp File Reference
DwarfTransformer.cpp File Reference
#include <thread>
#include <unordered_set>
#include "llvm/DebugInfo/DIContext.h"
#include "llvm/DebugInfo/DWARF/DWARFContext.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ThreadPool.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/DebugInfo/GSYM/DwarfTransformer.h"
#include "llvm/DebugInfo/GSYM/FunctionInfo.h"
#include "llvm/DebugInfo/GSYM/GsymCreator.h"
#include "llvm/DebugInfo/GSYM/GsymReader.h"
#include "llvm/DebugInfo/GSYM/InlineInfo.h"
Classes
struct llvm::gsym::CUInfo
Functions
static DWARFDie GetParentDeclContextDIE (DWARFDie &Die)
static Optional< uint32_t > getQualifiedNameIndex (DWARFDie &Die, uint64_t Language, GsymCreator &Gsym)
Get the GsymCreator string table offset for the qualified name for the DIE passed in.
static bool hasInlineInfo (DWARFDie Die, uint32_t Depth)
static void parseInlineInfo (GsymCreator &Gsym, CUInfo &CUI, DWARFDie Die, uint32_t Depth, FunctionInfo &FI, InlineInfo &parent)
static void convertFunctionLineTable (raw_ostream &Log, CUInfo &CUI, DWARFDie Die, GsymCreator &Gsym, FunctionInfo &FI)
Function Documentation
convertFunctionLineTable()
static void convertFunctionLineTable (raw_ostream & Log, CUInfo & CUI, DWARFDie Die, GsymCreator & Gsym, FunctionInfo & FI) static
Definition at line 249 of file DwarfTransformer.cpp.
References llvm::DWARFDebugLine::Row::Address, llvm::object::SectionedAddress::Address, llvm::gsym::AddressRange::contains(), llvm::DWARFDie::dump(), llvm::gsym::CUInfo::DWARFToGSYMFileIndex(), llvm::gsym::FunctionInfo::endAddress(), llvm::DWARFDebugLine::Row::EndSequence, llvm::DWARFDebugLine::Row::File, llvm::DWARFDie::findRecursively(), llvm::DIDumpOptions::getForSingleDIE(), HEX64, llvm::gsym::GsymCreator::isQuiet(), llvm::AArch64CC::LE, llvm::DWARFDebugLine::Row::Line, llvm::gsym::CUInfo::LineTable, llvm::DWARFDebugLine::LineTable::lookupAddressRange(), llvm::None, llvm::gsym::FunctionInfo::OptLineTable, llvm::gsym::FunctionInfo::Range, llvm::DWARFDebugLine::LineTable::Rows, llvm::gsym::AddressRange::Start, llvm::gsym::FunctionInfo::startAddress(), llvm::dwarf::toUnsigned(), and llvm::object::SectionedAddress::UndefSection.
GetParentDeclContextDIE()
static DWARFDie GetParentDeclContextDIE (DWARFDie & Die) static
Definition at line 85 of file DwarfTransformer.cpp.
References llvm::DWARFDie::getAttributeValueAsReferencedDie(), llvm::DWARFDie::getParent(), and llvm::DWARFDie::getTag().
Referenced by getQualifiedNameIndex().
getQualifiedNameIndex()
static Optional<uint32_t> getQualifiedNameIndex (DWARFDie & Die, uint64_t Language, GsymCreator & Gsym) static
Get the GsymCreator string table offset for the qualified name for the DIE passed in.
This function will avoid making copies of any strings in the GsymCreator when possible. We don't need to copy a string when the string comes from our .debug_str section or is an inlined string in the .debug_info. If we create a qualified name string in this function by combining multiple strings in the DWARF string table or info, we will make a copy of the string when we add it to the string table.
Definition at line 130 of file DwarfTransformer.cpp.
References llvm::StringRef::back(), llvm::StringRef::contains(), llvm::StringRef::empty(), llvm::DWARFDie::findRecursively(), llvm::StringRef::front(), llvm::DWARFDie::getName(), GetParentDeclContextDIE(), llvm::gsym::GsymCreator::insertString(), llvm::AMDGPU::HSAMD::Kernel::Key::Language, llvm::None, llvm::ShortName, llvm::StringRef::size(), llvm::StringRef::startswith(), llvm::StringRef::str(), llvm::StringRef::substr(), and llvm::dwarf::toString().
Referenced by parseInlineInfo().
hasInlineInfo()
static bool hasInlineInfo (DWARFDie Die, uint32_t Depth) static
Definition at line 186 of file DwarfTransformer.cpp.
References llvm::DWARFDie::children(), llvm::Depth, and llvm::DWARFDie::getTag().
Referenced by parseInlineInfo().
parseInlineInfo()
static void parseInlineInfo (GsymCreator & Gsym, CUInfo & CUI, DWARFDie Die, uint32_t Depth, FunctionInfo & FI, InlineInfo & parent) static
Definition at line 207 of file DwarfTransformer.cpp.
References llvm::gsym::InlineInfo::CallFile, llvm::gsym::InlineInfo::CallLine, llvm::DWARFDie::children(), llvm::gsym::InlineInfo::Children, llvm::Depth, llvm::gsym::CUInfo::DWARFToGSYMFileIndex(), llvm::gsym::AddressRanges::empty(), llvm::gsym::FunctionInfo::endAddress(), llvm::DWARFDie::find(), llvm::Expected< T >::get(), llvm::DWARFDie::getAddressRanges(), getQualifiedNameIndex(), llvm::DWARFDie::getTag(), hasInlineInfo(), llvm::DWARFAddressRange::HighPC, llvm::gsym::AddressRanges::insert(), llvm::gsym::CUInfo::Language, llvm::DWARFAddressRange::LowPC, move, llvm::gsym::InlineInfo::Name, llvm::gsym::InlineInfo::Ranges, llvm::gsym::FunctionInfo::startAddress(), and llvm::dwarf::toUnsigned().