LLVM: lib/Transforms/Utils/EntryExitInstrumenter.cpp File Reference
EntryExitInstrumenter.cpp File Reference
#include "llvm/Transforms/Utils/EntryExitInstrumenter.h"
#include "llvm/Analysis/GlobalsModRef.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Utils.h"
Functions
static void insertCall (Function &CurFn, StringRef Func, Instruction *InsertionPt, DebugLoc DL)
static bool runOnFunction (Function &F, bool PostInlining)
INITIALIZE_PASS_BEGIN (EntryExitInstrumenter, "ee-instrument", "Instrument function entry/exit with calls to e.g. mcount() (pre inlining)", false, false) INITIALIZE_PASS_END(EntryExitInstrumenter
ee Instrument function entry exit with calls to e g mcount ()(pre inlining)"
ee Instrument function entry exit with calls to e g false INITIALIZE_PASS_BEGIN (PostInlineEntryExitInstrumenter, "post-inline-ee-instrument", "Instrument function entry/exit with calls to e.g. mcount() " "(post inlining)", false, false) INITIALIZE_PASS_END(PostInlineEntryExitInstrumenter
Variables
ee instrument
ee Instrument function entry exit with calls to e g false
Function Documentation
INITIALIZE_PASS_BEGIN() [1/2]
INITIALIZE_PASS_BEGIN (EntryExitInstrumenter , "ee-instrument" , "Instrument function entry/exit with calls to e.g. mcount() (pre inlining)" , false , false)
INITIALIZE_PASS_BEGIN() [2/2]
ee Instrument function entry exit with calls to e g false INITIALIZE_PASS_BEGIN (PostInlineEntryExitInstrumenter , "post-inline-ee-instrument" , "Instrument function entry/exit with calls to e.g. mcount() " "(post inlining)" , false , false)
insertCall()
static void insertCall (Function & CurFn, StringRef Func, Instruction * InsertionPt, DebugLoc DL) static
Definition at line 24 of file EntryExitInstrumenter.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::MCID::Call, llvm::CallInst::Create(), DL, llvm::FunctionType::get(), llvm::ConstantInt::get(), llvm::ConstantExpr::getBitCast(), llvm::BasicBlock::getContext(), llvm::Intrinsic::getDeclaration(), llvm::Type::getInt32Ty(), llvm::Type::getInt8PtrTy(), llvm::GlobalValue::getParent(), llvm::BasicBlock::getParent(), llvm::Instruction::getParent(), llvm::Type::getVoidTy(), M, llvm::report_fatal_error(), and llvm::Instruction::setDebugLoc().
Referenced by runOnFunction().
mcount()
ee Instrument function entry exit with calls to e g false post inline ee Instrument function entry exit with calls to e g mcount ()
runOnFunction()
static bool runOnFunction (Function & F, bool PostInlining) static
Definition at line 69 of file EntryExitInstrumenter.cpp.
References BB, DL, llvm::StringRef::empty(), F, llvm::AttributeList::FunctionIndex, llvm::MDNode::get(), and insertCall().
Referenced by INITIALIZE_PASS(), and llvm::EntryExitInstrumenterPass::run().
Variable Documentation
false
ee Instrument function entry exit with calls to e g false post inline ee Instrument function entry exit with calls to e g false
Definition at line 157 of file EntryExitInstrumenter.cpp.
instrument
ee Instrument function entry exit with calls to e g false post inline ee instrument
Definition at line 155 of file EntryExitInstrumenter.cpp.