LLVM: Coroutine transformations
Coroutine transformations
LLVM-C: C interface to LLVM » Transforms
Functions
void LLVMAddCoroEarlyPass (LLVMPassManagerRef PM)
See llvm::createCoroEarlyLegacyPass function.
void LLVMAddCoroSplitPass (LLVMPassManagerRef PM)
See llvm::createCoroSplitLegacyPass function.
void LLVMAddCoroElidePass (LLVMPassManagerRef PM)
See llvm::createCoroElideLegacyPass function.
void LLVMAddCoroCleanupPass (LLVMPassManagerRef PM)
See llvm::createCoroCleanupLegacyPass function.
void LLVMPassManagerBuilderAddCoroutinePassesToExtensionPoints (LLVMPassManagerBuilderRef PMB)
See llvm::addCoroutinePassesToExtensionPoints.
Detailed Description
Function Documentation
LLVMAddCoroCleanupPass()
void LLVMAddCoroCleanupPass (LLVMPassManagerRef PM)
See llvm::createCoroCleanupLegacyPass function.
Definition at line 744 of file Coroutines.cpp.
References llvm::createCoroCleanupLegacyPass(), and llvm::unwrap().
LLVMAddCoroEarlyPass()
void LLVMAddCoroEarlyPass (LLVMPassManagerRef PM)
See llvm::createCoroEarlyLegacyPass function.
Definition at line 732 of file Coroutines.cpp.
References llvm::createCoroEarlyLegacyPass(), and llvm::unwrap().
LLVMAddCoroElidePass()
void LLVMAddCoroElidePass (LLVMPassManagerRef PM)
See llvm::createCoroElideLegacyPass function.
Definition at line 740 of file Coroutines.cpp.
References llvm::createCoroElideLegacyPass(), and llvm::unwrap().
LLVMAddCoroSplitPass()
void LLVMAddCoroSplitPass (LLVMPassManagerRef PM)
See llvm::createCoroSplitLegacyPass function.
Definition at line 736 of file Coroutines.cpp.
References llvm::createCoroSplitLegacyPass(), and llvm::unwrap().
LLVMPassManagerBuilderAddCoroutinePassesToExtensionPoints()
void LLVMPassManagerBuilderAddCoroutinePassesToExtensionPoints (LLVMPassManagerBuilderRef PMB)
See llvm::addCoroutinePassesToExtensionPoints.
Definition at line 749 of file Coroutines.cpp.
References llvm::addCoroutinePassesToExtensionPoints(), Builder, and llvm::unwrap().