LLVM: lib/DebugInfo/PDB/Native/GSIStreamBuilder.cpp File Reference
GSIStreamBuilder.cpp File Reference
#include "llvm/DebugInfo/PDB/Native/GSIStreamBuilder.h"
#include "llvm/DebugInfo/CodeView/RecordName.h"
#include "llvm/DebugInfo/CodeView/SymbolDeserializer.h"
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
#include "llvm/DebugInfo/CodeView/SymbolSerializer.h"
#include "llvm/DebugInfo/MSF/MSFBuilder.h"
#include "llvm/DebugInfo/MSF/MSFCommon.h"
#include "llvm/DebugInfo/MSF/MappedBlockStream.h"
#include "llvm/DebugInfo/PDB/Native/GlobalsStream.h"
#include "llvm/DebugInfo/PDB/Native/Hash.h"
#include "llvm/Support/BinaryItemStream.h"
#include "llvm/Support/BinaryStreamWriter.h"
#include "llvm/Support/Parallel.h"
#include "llvm/Support/xxhash.h"
#include <algorithm>
#include <vector>
Classes
struct llvm::pdb::GSIHashStreamBuilder
struct llvm::pdb::SymbolDenseMapInfo
Functions
static uint32_t sizeOfPublic (const BulkPublic &Pub)
static CVSymbol serializePublic (uint8_t *Mem, const BulkPublic &Pub)
static bool isAsciiString (StringRef S)
static int gsiRecordCmp (StringRef S1, StringRef S2)
static Error writePublics (BinaryStreamWriter &Writer, ArrayRef< BulkPublic > Publics)
static Error writeRecords (BinaryStreamWriter &Writer, ArrayRef< CVSymbol > Records)
static std::vector< support::ulittle32_t > computeAddrMap (ArrayRef< BulkPublic > Publics)
Function Documentation
computeAddrMap()
static std::vector<support::ulittle32_t> computeAddrMap (ArrayRef< BulkPublic > Publics) static
Definition at line 417 of file GSIStreamBuilder.cpp.
References E, llvm::pdb::BulkPublic::getName(), I, llvm::pdb::BulkPublic::Offset, llvm::parallelSort(), llvm::RISCVFenceField::R, llvm::pdb::BulkPublic::Segment, and llvm::ArrayRef< T >::size().
gsiRecordCmp()
static int gsiRecordCmp (StringRef S1, StringRef S2) static
Definition at line 154 of file GSIStreamBuilder.cpp.
References llvm::StringRef::compare_insensitive(), llvm::StringRef::data(), isAsciiString(), LLVM_UNLIKELY, llvm::AArch64CC::LS, memcmp, and llvm::StringRef::size().
Referenced by llvm::pdb::GSIHashStreamBuilder::finalizeBuckets().
isAsciiString()
static bool isAsciiString (StringRef S) static
Definition at line 149 of file GSIStreamBuilder.cpp.
References llvm::all_of(), and S.
Referenced by gsiRecordCmp().
serializePublic()
static CVSymbol serializePublic (uint8_t * Mem, const BulkPublic & Pub) static
Definition at line 103 of file GSIStreamBuilder.cpp.
References llvm::alignTo(), llvm::Apple, assert(), llvm::makeArrayRef(), llvm::codeview::MaxRecordLength, memcpy(), llvm::min(), llvm::Check::Size, and sizeOfPublic().
Referenced by writePublics().
sizeOfPublic()
static uint32_t sizeOfPublic (const BulkPublic & Pub) static
Definition at line 96 of file GSIStreamBuilder.cpp.
References llvm::alignTo(), llvm::Apple, llvm::codeview::MaxRecordLength, and llvm::min().
Referenced by llvm::pdb::GSIStreamBuilder::addPublicSymbols(), serializePublic(), and writePublics().
writePublics()
static Error writePublics (BinaryStreamWriter & Writer, ArrayRef< BulkPublic > Publics) static
Definition at line 381 of file GSIStreamBuilder.cpp.
References llvm::Apple, E, serializePublic(), sizeOfPublic(), llvm::Error::success(), and llvm::BinaryStreamWriter::writeBytes().
writeRecords()
static Error writeRecords (BinaryStreamWriter & Writer, ArrayRef< CVSymbol > Records) static
Definition at line 393 of file GSIStreamBuilder.cpp.
References llvm::support::little, llvm::BinaryItemStream< T, Traits >::setItems(), and llvm::BinaryStreamWriter::writeStreamRef().