LLVM: lib/Transforms/InstCombine/InstCombineCompares.cpp File Reference
InstCombineCompares.cpp File Reference
#include "InstCombineInternal.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/IR/ConstantRange.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/GetElementPtrTypeIterator.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Transforms/InstCombine/InstCombiner.h"
Macros
#define DEBUG_TYPE "instcombine"
Functions
STATISTIC (NumSel, "Number of select opts")
static bool addWithOverflow (APInt &Result, const APInt &In1, const APInt &In2, bool IsSigned=false)
Compute Result = In1+In2, returning true if the result overflowed for this type.
static bool subWithOverflow (APInt &Result, const APInt &In1, const APInt &In2, bool IsSigned=false)
Compute Result = In1-In2, returning true if the result overflowed for this type.
static bool hasBranchUse (ICmpInst &I)
Given an icmp instruction, return true if any use of this comparison is a branch on sign bit comparison.
static bool isSignTest (ICmpInst::Predicate &Pred, const APInt &C)
Returns true if the exploded icmp can be expressed as a signed comparison to zero and updates the predicate accordingly.
static Value * evaluateGEPOffsetExpression (User *GEP, InstCombinerImpl &IC, const DataLayout &DL)
Return a value that can be used to compare the offset implied by a GEP to zero.
static bool canRewriteGEPAsOffset (Value *Start, Value *Base, const DataLayout &DL, SetVector< Value * > &Explored)
Returns true if we can rewrite Start as a GEP with pointer Base and some integer offset.
static void setInsertionPoint (IRBuilder<> &Builder, Value *V, bool Before=true)
static Value * rewriteGEPAsOffset (Value *Start, Value *Base, const DataLayout &DL, SetVector< Value * > &Explored)
Returns a re-written value of Start as an indexed GEP using Base as a pointer.
static std::pair< Value *, Value * > getAsConstantIndexedAddress (Value *V, const DataLayout &DL)
Looks through GEPs, IntToPtrInsts and PtrToIntInsts in order to express the input Value as a constant indexed GEP.
static Instruction * transformToIndexedCompare (GEPOperator *GEPLHS, Value *RHS, ICmpInst::Predicate Cond, const DataLayout &DL)
Converts (CMP GEPLHS, RHS) if this change would make RHS a constant.
static Instruction * processUGT_ADDCST_ADD (ICmpInst &I, Value *A, Value *B, ConstantInt *CI2, ConstantInt *CI1, InstCombinerImpl &IC)
The caller has matched a pattern of the form: I = icmp ugt (add (add A, B), CI2), CI1 If this is of the form: sum = a + b if (sum+128 >u 255) Then replace it with llvm.sadd.with.overflow.i8.
static Instruction * foldICmpShlOne (ICmpInst &Cmp, Instruction *Shl, const APInt &C)
Fold icmp (shl 1, Y), C.
static Instruction * foldICmpBitCast (ICmpInst &Cmp, InstCombiner::BuilderTy &Builder)
static Value * foldICmpWithLowBitMaskedVal (ICmpInst &I, InstCombiner::BuilderTy &Builder)
Some comparisons can be simplified.
static Value * foldICmpWithTruncSignExtendedVal (ICmpInst &I, InstCombiner::BuilderTy &Builder)
Some comparisons can be simplified.
static Value * foldShiftIntoShiftInAnotherHandOfAndInICmp (ICmpInst &I, const SimplifyQuery SQ, InstCombiner::BuilderTy &Builder)
static Instruction * foldICmpXNegX (ICmpInst &I)
static Instruction * foldICmpWithMinMax (ICmpInst &Cmp)
Fold icmp Pred min|max(X, Y), X.
static Instruction * foldICmpWithZextOrSext (ICmpInst &ICmp, InstCombiner::BuilderTy &Builder)
static bool isNeutralValue (Instruction::BinaryOps BinaryOp, Value *RHS)
static Instruction * processUMulZExtIdiom (ICmpInst &I, Value *MulVal, Value *OtherVal, InstCombinerImpl &IC)
Recognize and process idiom involving test for multiplication overflow.
static APInt getDemandedBitsLHSMask (ICmpInst &I, unsigned BitWidth)
When performing a comparison against a constant, it is possible that not all the bits in the LHS are demanded.
static bool swapMayExposeCSEOpportunities (const Value *Op0, const Value *Op1)
Check if the order of Op0 and Op1 as operands in an ICmpInst should be swapped.
static bool isChainSelectCmpBranch (const SelectInst *SI)
Return true when the instruction sequence within a block is select-cmp-br.
static ICmpInst * canonicalizeCmpWithConstant (ICmpInst &I)
If we have an icmp le or icmp ge instruction with a constant operand, turn it into the appropriate icmp lt or icmp gt instruction.
static Instruction * canonicalizeICmpBool (ICmpInst &I, InstCombiner::BuilderTy &Builder)
Integer compare with boolean values can always be turned into bitwise ops.
static Instruction * foldICmpWithHighBitMask (ICmpInst &Cmp, InstCombiner::BuilderTy &Builder)
static Instruction * foldVectorCmp (CmpInst &Cmp, InstCombiner::BuilderTy &Builder)
static Instruction * foldICmpOfUAddOv (ICmpInst &I)
static Instruction * foldFCmpReciprocalAndZero (FCmpInst &I, Instruction *LHSI, Constant *RHSC)
Fold (C / X) < 0.0 --> X < 0.0 if possible. Swap predicate if necessary.
static Instruction * foldFabsWithFcmpZero (FCmpInst &I, InstCombinerImpl &IC)
Optimize fabs(X) compared with zero.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "instcombine"
Definition at line 32 of file InstCombineCompares.cpp.
Function Documentation
addWithOverflow()
static bool addWithOverflow (APInt & Result, const APInt & In1, const APInt & In2, bool IsSigned = false) static
Compute Result = In1+In2, returning true if the result overflowed for this type.
Definition at line 40 of file InstCombineCompares.cpp.
References llvm::APInt::sadd_ov(), and llvm::APInt::uadd_ov().
Referenced by llvm::InstCombinerImpl::foldICmpDivConstant().
canonicalizeCmpWithConstant()
static ICmpInst* canonicalizeCmpWithConstant (ICmpInst & I) static
If we have an icmp le or icmp ge instruction with a constant operand, turn it into the appropriate icmp lt or icmp gt instruction.
This transform allows them to be folded in visitICmpInst.
Definition at line 5439 of file InstCombineCompares.cpp.
References llvm::InstCombiner::getFlippedStrictnessPredicateAndConstant(), I, llvm::InstCombiner::isCanonicalPredicate(), llvm::ICmpInst::isEquality(), and llvm::CmpInst::isIntPredicate().
Referenced by llvm::InstCombinerImpl::visitICmpInst().
canonicalizeICmpBool()
static Instruction* canonicalizeICmpBool (ICmpInst & I, InstCombiner::BuilderTy & Builder) static
Integer compare with boolean values can always be turned into bitwise ops.
Definition at line 5483 of file InstCombineCompares.cpp.
References A, assert(), B, Builder, llvm::BinaryOperator::CreateNot(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, LLVM_FALLTHROUGH, llvm_unreachable, llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), and std::swap().
Referenced by llvm::InstCombinerImpl::visitICmpInst().
canRewriteGEPAsOffset()
static bool canRewriteGEPAsOffset (Value * Start, Value * Base, const DataLayout & DL, SetVector< Value * > & Explored) static
Returns true if we can rewrite Start as a GEP with pointer Base and some integer offset.
The nodes that need to be re-written for this transformation will be added to Explored.
Definition at line 505 of file InstCombineCompares.cpp.
Referenced by transformToIndexedCompare().
evaluateGEPOffsetExpression()
static Value* evaluateGEPOffsetExpression (User * GEP, InstCombinerImpl & IC, const DataLayout & DL) static
Return a value that can be used to compare the offset implied by a GEP to zero.
For example, if we have &A[i], we want to return 'i' for "icmp ne i, 0". Note that, in general, indices can be complex, and scales are involved. The above expression would also be legal to codegen as "icmp ne (i*4), 0" (assuming A is a pointer to i32). This latter form is less amenable to optimization though, and we are allowed to generate the first by knowing that pointer arithmetic doesn't overflow.
If we can't emit an optimized form for this expression, this returns null.
Definition at line 410 of file InstCombineCompares.cpp.
References llvm::InstCombiner::Builder, llvm::IRBuilderBase::CreateAdd(), llvm::IRBuilderBase::CreateIntCast(), llvm::IRBuilderBase::CreateTrunc(), DL, llvm::numbers::e, GEP, llvm::gep_type_begin(), llvm::ConstantInt::get(), llvm::TypeSize::getFixedSize(), llvm::generic_gep_type_iterator< ItTy >::getIndexedType(), llvm::Type::getIntegerBitWidth(), llvm::Type::getPrimitiveSizeInBits(), llvm::ConstantInt::getSExtValue(), llvm::generic_gep_type_iterator< ItTy >::getStructTypeOrNull(), llvm::Value::getType(), llvm::ConstantInt::getZExtValue(), i, llvm::ConstantInt::isZero(), Offset, llvm::SignExtend64(), and llvm::Check::Size.
Referenced by llvm::InstCombinerImpl::foldGEPICmp().
foldFabsWithFcmpZero()
static Instruction* foldFabsWithFcmpZero (FCmpInst & I, InstCombinerImpl & IC) static
Optimize fabs(X) compared with zero.
Definition at line 6204 of file InstCombineCompares.cpp.
References assert(), llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, I, llvm_unreachable, llvm::PatternMatch::m_FAbs(), llvm::PatternMatch::m_PosZeroFP(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), P, llvm::InstCombinerImpl::replaceOperand(), and X.
Referenced by llvm::InstCombinerImpl::visitFCmpInst().
foldFCmpReciprocalAndZero()
static Instruction* foldFCmpReciprocalAndZero (FCmpInst & I, Instruction * LHSI, Constant * RHSC) static
Fold (C / X) < 0.0 --> X < 0.0 if possible. Swap predicate if necessary.
Definition at line 6157 of file InstCombineCompares.cpp.
References llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::User::getOperand(), llvm::Instruction::hasNoInfs(), I, llvm::PatternMatch::m_AnyZeroFP(), llvm::PatternMatch::m_APFloat(), and llvm::PatternMatch::match().
Referenced by llvm::InstCombinerImpl::visitFCmpInst().
foldICmpBitCast()
static Instruction* foldICmpBitCast (ICmpInst & Cmp, InstCombiner::BuilderTy & Builder) static
Definition at line 2833 of file InstCombineCompares.cpp.
References llvm::LegacyLegalizeActions::Bitcast, Builder, llvm::VectorType::get(), llvm::ConstantInt::get(), llvm::Constant::getAllOnesValue(), llvm::Constant::getNullValue(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::is_splat(), llvm::ICmpInst::isEquality(), llvm::Type::isPPC_FP128Ty(), llvm::InstCombiner::isSignBitCheck(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_FPExt(), llvm::PatternMatch::m_FPTrunc(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Shuffle(), llvm::PatternMatch::m_SIToFP(), llvm::PatternMatch::m_UIToFP(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::BitmaskEnumDetail::Mask(), llvm::PatternMatch::match(), and X.
Referenced by llvm::InstCombinerImpl::visitICmpInst().
foldICmpOfUAddOv()
static Instruction* foldICmpOfUAddOv (ICmpInst & I) static
Definition at line 5651 of file InstCombineCompares.cpp.
References A, B, llvm::ExtractValueInst::Create(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZeroInt(), and llvm::PatternMatch::match().
Referenced by llvm::InstCombinerImpl::visitICmpInst().
foldICmpShlOne()
static Instruction* foldICmpShlOne (ICmpInst & Cmp, Instruction * Shl, const APInt & C) static
Fold icmp (shl 1, Y), C.
Definition at line 2021 of file InstCombineCompares.cpp.
References llvm::ConstantInt::get(), llvm::CmpInst::getPredicate(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::ICmpInst::isEquality(), llvm::CmpInst::isSigned(), llvm::CmpInst::isUnsigned(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and Y.
Referenced by llvm::InstCombinerImpl::foldICmpShlConstant().
foldICmpWithHighBitMask()
static Instruction* foldICmpWithHighBitMask (ICmpInst & Cmp, InstCombiner::BuilderTy & Builder) static
Definition at line 5562 of file InstCombineCompares.cpp.
References Builder, llvm::CmpInst::Create(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_CombineOr(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), X, and Y.
Referenced by llvm::InstCombinerImpl::visitICmpInst().
foldICmpWithLowBitMaskedVal()
static Value* foldICmpWithLowBitMaskedVal (ICmpInst & I, InstCombiner::BuilderTy & Builder) static
Some comparisons can be simplified.
In this case, we are looking for comparisons that look like a check for a lossy truncation. Folds: icmp SrcPred (x & Mask), x to icmp DstPred x, Mask Where Mask is some pattern that produces all-ones in low bits: (-1 >> y) ((-1 << y) >> y) <- non-canonical, has extra uses ~(-1 << y) ((1 << y) + (-1)) <- non-canonical, has extra uses The Mask can be a constant, too. For some predicates, the operands are commutative. For others, x can only be on a specific side.
Definition at line 3418 of file InstCombineCompares.cpp.
References assert(), Builder, llvm::numbers::e, llvm::Constant::getAggregateElement(), I, i, llvm_unreachable, M, llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_CombineAnd(), llvm::PatternMatch::m_CombineOr(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_LowBitMask(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_NonNegative(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::Constant::replaceUndefsWith(), X, and Y.
Referenced by llvm::InstCombinerImpl::foldICmpBinOp().
foldICmpWithMinMax()
static Instruction* foldICmpWithMinMax (ICmpInst & Cmp) static
Fold icmp Pred min|max(X, Y), X.
Definition at line 4219 of file InstCombineCompares.cpp.
References llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::CmpInst::getSwappedPredicate(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::PatternMatch::m_c_SMax(), llvm::PatternMatch::m_c_SMin(), llvm::PatternMatch::m_c_UMax(), llvm::PatternMatch::m_c_UMin(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), std::swap(), X, and Y.
Referenced by llvm::InstCombinerImpl::visitICmpInst().
foldICmpWithTruncSignExtendedVal()
static Value* foldICmpWithTruncSignExtendedVal (ICmpInst & I, InstCombiner::BuilderTy & Builder) static
Some comparisons can be simplified.
In this case, we are looking for comparisons that look like a check for a lossy signed truncation. Folds: (MaskedBits is a constant.) ((x << MaskedBits) a>> MaskedBits) SrcPred x Into: (add x, (1 << (KeptBits-1))) DstPred (1 << KeptBits) Where KeptBits = bitwidth(x) - MaskedBits
Definition at line 3512 of file InstCombineCompares.cpp.
References assert(), llvm::BitWidth, Builder, C1, llvm::ConstantInt::get(), I, llvm::APInt::isPowerOf2(), llvm::APInt::lshr(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::APInt::shl(), T1, llvm::APInt::ugt(), llvm::APInt::ult(), and X.
Referenced by llvm::InstCombinerImpl::foldICmpBinOp().
foldICmpWithZextOrSext()
static Instruction* foldICmpWithZextOrSext (ICmpInst & ICmp, InstCombiner::BuilderTy & Builder) static
Definition at line 4480 of file InstCombineCompares.cpp.
References assert(), Builder, llvm::Constant::getAllOnesValue(), llvm::ConstantExpr::getCast(), llvm::Constant::getNullValue(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::Type::getScalarSizeInBits(), llvm::ConstantExpr::getTrunc(), llvm::ICmpInst::getUnsignedPredicate(), llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::ICmpInst::isEquality(), llvm::CmpInst::isSigned(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExtOrSExt(), llvm::PatternMatch::match(), X, and Y.
Referenced by llvm::InstCombinerImpl::foldICmpWithCastOp().
foldICmpXNegX()
static Instruction* foldICmpXNegX (ICmpInst & I) static
Definition at line 3816 of file InstCombineCompares.cpp.
References llvm::CmpInst::Create(), llvm::Constant::getNullValue(), llvm::ICmpInst::getSignedPredicate(), llvm::CmpInst::getSwappedPredicate(), I, llvm::CmpInst::isSigned(), llvm::CmpInst::isUnsigned(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_NSWNeg(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and X.
Referenced by llvm::InstCombinerImpl::foldICmpBinOp().
foldShiftIntoShiftInAnotherHandOfAndInICmp()
static Value* foldShiftIntoShiftInAnotherHandOfAndInICmp (ICmpInst & I, const SimplifyQuery SQ, InstCombiner::BuilderTy & Builder) static
Definition at line 3586 of file InstCombineCompares.cpp.
References assert(), Builder, llvm::computeKnownBits(), llvm::KnownBits::countMinLeadingZeros(), llvm::APInt::getAllOnesValue(), llvm::KnownBits::getBitWidth(), llvm::Constant::getNullValue(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::Constant::getUniqueInteger(), llvm::SimplifyQuery::getWithInstruction(), llvm::ConstantExpr::getZExtOrBitCast(), llvm::Value::hasOneUse(), I, llvm::Constant::isNullValue(), llvm::Type::isVectorTy(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_CombineAnd(), llvm::PatternMatch::m_Instruction(), llvm::PatternMatch::m_LogicalShift(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_SpecificInt_ICMP(), llvm::PatternMatch::m_TruncOrSelf(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::m_ZExtOrSelf(), llvm::PatternMatch::match(), llvm::SimplifyAddInst(), std::swap(), T1, llvm::APInt::ule(), llvm::APInt::ult(), X, and Y.
Referenced by llvm::InstCombinerImpl::foldICmpBinOp().
foldVectorCmp()
static Instruction* foldVectorCmp (CmpInst & Cmp, InstCombiner::BuilderTy & Builder) static
Definition at line 5605 of file InstCombineCompares.cpp.
References Builder, llvm::UndefValue::get(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::ConstantVector::getSplat(), llvm::Constant::getSplatValue(), llvm::Value::getType(), llvm::Value::hasOneUse(), M, llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_Shuffle(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by llvm::InstCombinerImpl::visitFCmpInst(), and llvm::InstCombinerImpl::visitICmpInst().
getAsConstantIndexedAddress()
static std::pair<Value *, Value *> getAsConstantIndexedAddress (Value * V, const DataLayout & DL) static
Looks through GEPs, IntToPtrInsts and PtrToIntInsts in order to express the input Value as a constant indexed GEP.
Returns a pair containing the GEPs Pointer and Index.
Definition at line 749 of file InstCombineCompares.cpp.
References DL, GEP, llvm::IntegerType::get(), llvm::ConstantExpr::getAdd(), llvm::Value::getContext(), llvm::Constant::getNullValue(), llvm::ConstantExpr::getSExtOrBitCast(), llvm::Value::getType(), and Index.
Referenced by transformToIndexedCompare().
getDemandedBitsLHSMask()
static APInt getDemandedBitsLHSMask (ICmpInst & I, unsigned BitWidth) static
When performing a comparison against a constant, it is possible that not all the bits in the LHS are demanded.
This helper method computes the mask that IS demanded.
Definition at line 4943 of file InstCombineCompares.cpp.
References llvm::BitWidth, llvm::APInt::countTrailingOnes(), llvm::APInt::countTrailingZeros(), llvm::APInt::getAllOnesValue(), llvm::APInt::getBitsSetFrom(), llvm::APInt::getSignMask(), I, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::InstCombiner::isSignBitCheck(), llvm::PatternMatch::m_APInt(), and llvm::PatternMatch::match().
Referenced by llvm::InstCombinerImpl::foldICmpUsingKnownBits().
hasBranchUse()
static bool hasBranchUse (ICmpInst & I) static
Given an icmp instruction, return true if any use of this comparison is a branch on sign bit comparison.
Definition at line 66 of file InstCombineCompares.cpp.
References I.
Referenced by llvm::InstCombinerImpl::foldICmpWithDominatingICmp().
isChainSelectCmpBranch()
static bool isChainSelectCmpBranch (const SelectInst * SI) static
Return true when the instruction sequence within a block is select-cmp-br.
Definition at line 5030 of file InstCombineCompares.cpp.
References BB, and SI.
Referenced by llvm::InstCombinerImpl::replacedSelectWithOperand().
isNeutralValue()
static bool isNeutralValue (Instruction::BinaryOps BinaryOp, Value * RHS) static
Definition at line 4626 of file InstCombineCompares.cpp.
References llvm::MCID::Add, llvm_unreachable, llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Zero(), and llvm::PatternMatch::match().
isSignTest()
static bool isSignTest (ICmpInst::Predicate & Pred, const APInt & C) static
Returns true if the exploded icmp can be expressed as a signed comparison to zero and updates the predicate accordingly.
The signedness of the comparison is preserved. TODO: Refactor with decomposeBitTestICmp()?
Definition at line 77 of file InstCombineCompares.cpp.
References llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::ICmpInst::isRelational(), and llvm::CmpInst::isSigned().
Referenced by llvm::InstCombinerImpl::foldICmpMulConstant(), and llvm::InstCombinerImpl::foldICmpShlConstant().
processUGT_ADDCST_ADD()
static Instruction* processUGT_ADDCST_ADD (ICmpInst & I, Value * A, Value * B, ConstantInt * CI2, ConstantInt * CI1, InstCombinerImpl & IC) static
The caller has matched a pattern of the form: I = icmp ugt (add (add A, B), CI2), CI1 If this is of the form: sum = a + b if (sum+128 >u 255) Then replace it with llvm.sadd.with.overflow.i8.
Definition at line 1241 of file InstCombineCompares.cpp.
References A, llvm::MCID::Add, B, llvm::InstCombiner::Builder, Builder, llvm::MCID::Call, llvm::InstCombinerImpl::ComputeNumSignBits(), llvm::APInt::countTrailingZeros(), llvm::ExtractValueInst::Create(), llvm::InstCombinerImpl::eraseInstFromFunction(), F, llvm::IntegerType::get(), llvm::ConstantInt::getBitWidth(), llvm::Value::getContext(), llvm::Intrinsic::getDeclaration(), llvm::APInt::getLowBitsSet(), llvm::User::getOperand(), llvm::Type::getPrimitiveSizeInBits(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::Value::hasOneUse(), I, llvm::APInt::isPowerOf2(), llvm::InstCombinerImpl::replaceInstUsesWith(), and llvm::Value::users().
Referenced by llvm::InstCombinerImpl::foldICmpWithConstant().
processUMulZExtIdiom()
static Instruction* processUMulZExtIdiom (ICmpInst & I, Value * MulVal, Value * OtherVal, InstCombinerImpl & IC) static
Recognize and process idiom involving test for multiplication overflow.
The caller has matched a pattern of the form: I = cmp u (mul(zext A, zext B), V The function checks if this is a test for overflow and if so replaces multiplication with call to 'mul.with.overflow' intrinsic.
Parameters
I Compare instruction.
MulVal Result of 'mult' instruction. It is one of the arguments of the compare instruction. Must be of integer type.
OtherVal The other argument of compare instruction.
Returns
Instruction which must replace the compare instruction, NULL if no replacement required.
Definition at line 4726 of file InstCombineCompares.cpp.
References A, llvm::InstCombiner::addToWorklist(), assert(), B, llvm::InstCombiner::Builder, Builder, llvm::MCID::Call, llvm::APInt::countLeadingZeros(), llvm::ExtractValueInst::Create(), llvm::BinaryOperator::CreateNot(), llvm::APInt::eq(), F, llvm::APInt::getBitWidth(), llvm::ConstantInt::getBitWidth(), llvm::Intrinsic::getDeclaration(), llvm::APInt::getMaxValue(), llvm::APInt::getOneBitSet(), llvm::Type::getPrimitiveSizeInBits(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::Value::hasNUsesOrMore(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::APInt::isPowerOf2(), llvm_unreachable, llvm::APInt::logBase2(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Value(), llvm::make_early_inc_range(), llvm::PatternMatch::match(), llvm::InstCombinerImpl::replaceInstUsesWith(), llvm::User::setOperand(), llvm::APInt::trunc(), llvm::Value::users(), and llvm::APInt::zext().
Referenced by llvm::InstCombinerImpl::visitICmpInst().
rewriteGEPAsOffset()
static Value* rewriteGEPAsOffset (Value * Start, Value * Base, const DataLayout & DL, SetVector< Value * > & Explored) static
Returns a re-written value of Start as an indexed GEP using Base as a pointer.
Definition at line 629 of file InstCombineCompares.cpp.
Referenced by transformToIndexedCompare().
setInsertionPoint()
static void setInsertionPoint (IRBuilder<> & Builder, Value * V, bool Before = true) static
Definition at line 604 of file InstCombineCompares.cpp.
References A, Builder, and I.
STATISTIC()
STATISTIC (NumSel , "Number of select opts")
subWithOverflow()
static bool subWithOverflow (APInt & Result, const APInt & In1, const APInt & In2, bool IsSigned = false) static
Compute Result = In1-In2, returning true if the result overflowed for this type.
Definition at line 53 of file InstCombineCompares.cpp.
References llvm::APInt::ssub_ov(), and llvm::APInt::usub_ov().
Referenced by llvm::InstCombinerImpl::foldICmpDivConstant(), and llvm::InstCombinerImpl::foldICmpSubConstant().
swapMayExposeCSEOpportunities()
static bool swapMayExposeCSEOpportunities (const Value * Op0, const Value * Op1) static
Check if the order of Op0 and Op1 as operands in an ICmpInst should be swapped.
The decision is based on how many times these two operands are reused as subtract operands and their positions in those instructions. The rationale is that several architectures use the same instruction for both subtract and cmp. Thus, it is better if the order of those operands match.
Returns
true if Op0 and Op1 should be swapped.
Definition at line 4980 of file InstCombineCompares.cpp.
References llvm::Value::getType(), llvm::Type::isPointerTy(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::match(), and llvm::Value::users().
Referenced by llvm::InstCombinerImpl::visitICmpInst().
transformToIndexedCompare()
static Instruction* transformToIndexedCompare (GEPOperator * GEPLHS, Value * RHS, ICmpInst::Predicate Cond, const DataLayout & DL) static
Converts (CMP GEPLHS, RHS) if this change would make RHS a constant.
We can look through PHIs, GEPs and casts in order to determine a common base between GEPLHS and RHS.
Definition at line 790 of file InstCombineCompares.cpp.
References canRewriteGEPAsOffset(), Cond, DL, getAsConstantIndexedAddress(), llvm::ICmpInst::getSignedPredicate(), llvm::Value::getType(), llvm::GEPOperator::hasAllConstantIndices(), Index, llvm::Type::isVectorTy(), and rewriteGEPAsOffset().
Referenced by llvm::InstCombinerImpl::foldGEPICmp().