LLVM: lib/IR/IRBuilder.cpp File Reference
IRBuilder.cpp File Reference
#include "llvm/IR/IRBuilder.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/None.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/NoFolder.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Statepoint.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/MathExtras.h"
#include <cassert>
#include <cstdint>
#include <vector>
#include "llvm/IR/ConstrainedOps.def"
Macros
#define INSTRUCTION(NAME, NARG, ROUND_MODE, INTRINSIC)
#define INSTRUCTION(NAME, NARG, ROUND_MODE, INTRINSIC)
Functions
static CallInst * createCallHelper (Function *Callee, ArrayRef< Value * > Ops, IRBuilderBase *Builder, const Twine &Name="", Instruction *FMFSource=nullptr, ArrayRef< OperandBundleDef > OpBundles={})
static CallInst * getReductionIntrinsic (IRBuilderBase *Builder, Intrinsic::ID ID, Value *Src)
template<typename T0 >
static std::vector< Value * > getStatepointArgs (IRBuilderBase &B, uint64_t ID, uint32_t NumPatchBytes, Value *ActualCallee, uint32_t Flags, ArrayRef< T0 > CallArgs)
template<typename T1 , typename T2 , typename T3 >
static std::vector< OperandBundleDef > getStatepointBundles (Optional< ArrayRef< T1 >> TransitionArgs, Optional< ArrayRef< T2 >> DeoptArgs, ArrayRef< T3 > GCArgs)
template<typename T0 , typename T1 , typename T2 , typename T3 >
static CallInst * CreateGCStatepointCallCommon (IRBuilderBase *Builder, uint64_t ID, uint32_t NumPatchBytes, Value *ActualCallee, uint32_t Flags, ArrayRef< T0 > CallArgs, Optional< ArrayRef< T1 >> TransitionArgs, Optional< ArrayRef< T2 >> DeoptArgs, ArrayRef< T3 > GCArgs, const Twine &Name)
template<typename T0 , typename T1 , typename T2 , typename T3 >
static InvokeInst * CreateGCStatepointInvokeCommon (IRBuilderBase *Builder, uint64_t ID, uint32_t NumPatchBytes, Value *ActualInvokee, BasicBlock *NormalDest, BasicBlock *UnwindDest, uint32_t Flags, ArrayRef< T0 > InvokeArgs, Optional< ArrayRef< T1 >> TransitionArgs, Optional< ArrayRef< T2 >> DeoptArgs, ArrayRef< T3 > GCArgs, const Twine &Name)
Macro Definition Documentation
INSTRUCTION [1/2]
#define INSTRUCTION (NAME, NARG, ROUND_MODE, INTRINSIC)
Value:
  case Intrinsic::INTRINSIC:                                \
    HasRoundingMD = ROUND_MODE;                             \
    break;
INSTRUCTION [2/2]
#define INSTRUCTION (NAME, NARG, ROUND_MODE, INTRINSIC)
Value:
  case Intrinsic::INTRINSIC:                                \
    HasRoundingMD = ROUND_MODE;                             \
    break;
Function Documentation
createCallHelper()
static CallInst* createCallHelper (Function * Callee, ArrayRef< Value * > Ops, IRBuilderBase * Builder, const Twine & Name = "", Instruction * FMFSource = nullptr, ArrayRef< OperandBundleDef > OpBundles = {}) static
Definition at line 72 of file IRBuilder.cpp.
Referenced by llvm::IRBuilderBase::CreateAssumption(), llvm::IRBuilderBase::CreateBinaryIntrinsic(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemCpy(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemMove(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemSet(), llvm::IRBuilderBase::CreateFAddReduce(), llvm::IRBuilderBase::CreateFMulReduce(), llvm::IRBuilderBase::CreateGCGetPointerBase(), llvm::IRBuilderBase::CreateGCGetPointerOffset(), llvm::IRBuilderBase::CreateGCRelocate(), llvm::IRBuilderBase::CreateGCResult(), llvm::IRBuilderBase::CreateIntrinsic(), llvm::IRBuilderBase::CreateInvariantStart(), llvm::IRBuilderBase::CreateLifetimeEnd(), llvm::IRBuilderBase::CreateLifetimeStart(), llvm::IRBuilderBase::CreateMemCpyInline(), llvm::IRBuilderBase::CreateMemMove(), llvm::IRBuilderBase::CreateMemSet(), llvm::IRBuilderBase::CreateMemTransferInst(), llvm::IRBuilderBase::CreateNoAliasScopeDeclaration(), llvm::IRBuilderBase::CreateUnaryIntrinsic(), llvm::IRBuilderBase::CreateVScale(), and getReductionIntrinsic().
CreateGCStatepointCallCommon()
template<typename T0 , typename T1 , typename T2 , typename T3 > static CallInst* CreateGCStatepointCallCommon (IRBuilderBase * Builder, uint64_t ID, uint32_t NumPatchBytes, Value * ActualCallee, uint32_t Flags, ArrayRef< T0 > CallArgs, Optional< ArrayRef< T1 >> TransitionArgs, Optional< ArrayRef< T2 >> DeoptArgs, ArrayRef< T3 > GCArgs, const Twine & Name) static
Definition at line 663 of file IRBuilder.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), Builder, llvm::Intrinsic::getDeclaration(), getStatepointArgs(), getStatepointBundles(), llvm::Value::getType(), and M.
CreateGCStatepointInvokeCommon()
template<typename T0 , typename T1 , typename T2 , typename T3 > static InvokeInst* CreateGCStatepointInvokeCommon (IRBuilderBase * Builder, uint64_t ID, uint32_t NumPatchBytes, Value * ActualInvokee, BasicBlock * NormalDest, BasicBlock * UnwindDest, uint32_t Flags, ArrayRef< T0 > InvokeArgs, Optional< ArrayRef< T1 >> TransitionArgs, Optional< ArrayRef< T2 >> DeoptArgs, ArrayRef< T3 > GCArgs, const Twine & Name) static
Definition at line 720 of file IRBuilder.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), Builder, llvm::Intrinsic::getDeclaration(), getStatepointArgs(), getStatepointBundles(), llvm::Value::getType(), and M.
getReductionIntrinsic()
static CallInst* getReductionIntrinsic (IRBuilderBase * Builder, Intrinsic::ID ID, Value * Src) static
Definition at line 359 of file IRBuilder.cpp.
References Builder, createCallHelper(), llvm::Intrinsic::getDeclaration(), llvm::Value::getType(), and M.
Referenced by llvm::IRBuilderBase::CreateAddReduce(), llvm::IRBuilderBase::CreateAndReduce(), llvm::IRBuilderBase::CreateFPMaxReduce(), llvm::IRBuilderBase::CreateFPMinReduce(), llvm::IRBuilderBase::CreateIntMaxReduce(), llvm::IRBuilderBase::CreateIntMinReduce(), llvm::IRBuilderBase::CreateMulReduce(), llvm::IRBuilderBase::CreateOrReduce(), and llvm::IRBuilderBase::CreateXorReduce().
getStatepointArgs()
template<typename T0 > static std::vector<Value *> getStatepointArgs (IRBuilderBase & B, uint64_t ID, uint32_t NumPatchBytes, Value * ActualCallee, uint32_t Flags, ArrayRef< T0 > CallArgs) static
Definition at line 621 of file IRBuilder.cpp.
References llvm::append_range(), llvm::AMDGPU::HSAMD::Kernel::Key::Args, B, and llvm::ArrayRef< T >::size().
Referenced by CreateGCStatepointCallCommon(), and CreateGCStatepointInvokeCommon().
getStatepointBundles()
template<typename T1 , typename T2 , typename T3 > static std::vector<OperandBundleDef> getStatepointBundles (Optional< ArrayRef< T1 >> TransitionArgs, Optional< ArrayRef< T2 >> DeoptArgs, ArrayRef< T3 > GCArgs) static
Definition at line 640 of file IRBuilder.cpp.
References llvm::append_range(), and llvm::ArrayRef< T >::size().
Referenced by CreateGCStatepointCallCommon(), and CreateGCStatepointInvokeCommon().