LLVM: lib/Analysis/IVUsers.cpp File Reference
IVUsers.cpp File Reference
#include "llvm/Analysis/IVUsers.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/CodeMetrics.h"
#include "llvm/Analysis/LoopAnalysisManager.h"
#include "llvm/Analysis/LoopPass.h"
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
Macros
#define DEBUG_TYPE "iv-users"
Functions
INITIALIZE_PASS_BEGIN (IVUsersWrapperPass, "iv-users", "Induction Variable Users", false, true) INITIALIZE_PASS_END(IVUsersWrapperPass
static bool isInteresting (const SCEV *S, const Instruction *I, const Loop *L, ScalarEvolution *SE, LoopInfo *LI)
isInteresting - Test whether the given expression is "interesting" when used by the given expression, within the context of analyzing the given loop.
static bool isSimplifiedLoopNest (BasicBlock *BB, const DominatorTree *DT, const LoopInfo *LI, SmallPtrSetImpl< Loop * > &SimpleLoopNests)
Return true if all loop headers that dominate this block are in simplified form.
static bool IVUseShouldUsePostIncValue (Instruction *User, Value *Operand, const Loop *L, DominatorTree *DT)
IVUseShouldUsePostIncValue - We have discovered a "User" of an IV expression and now we need to decide whether the user should use the preinc or post-inc value.
static const SCEVAddRecExpr * findAddRecForLoop (const SCEV *S, const Loop *L)
Variables
iv users
iv Induction Variable Users
iv Induction Variable false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "iv-users"
Definition at line 36 of file IVUsers.cpp.
Function Documentation
findAddRecForLoop()
static const SCEVAddRecExpr* findAddRecForLoop (const SCEV * S, const Loop * L) static
Definition at line 395 of file IVUsers.cpp.
References llvm::MCID::Add, and S.
Referenced by llvm::IVUsers::getStride().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (IVUsersWrapperPass , "iv-users" , "Induction Variable Users" , false , true)
isInteresting()
static bool isInteresting (const SCEV * S, const Instruction * I, const Loop * L, ScalarEvolution * SE, LoopInfo * LI) static
isInteresting - Test whether the given expression is "interesting" when used by the given expression, within the context of analyzing the given loop.
Definition at line 60 of file IVUsers.cpp.
References llvm::MCID::Add, llvm::LoopBase< BlockT, LoopT >::contains(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::ScalarEvolution::getSCEVAtScope(), I, and S.
Referenced by llvm::IVUsers::AddUsersImpl(), llvm::ChangeReporter< IRUnitT >::handleIRAfterPass(), llvm::ChangeReporter< IRUnitT >::saveIRBeforePass(), and shouldConvertOrWithNoCommonBitsToAdd().
isSimplifiedLoopNest()
static bool isSimplifiedLoopNest (BasicBlock * BB, const DominatorTree * DT, const LoopInfo * LI, SmallPtrSetImpl< Loop * > & SimpleLoopNests) static
Return true if all loop headers that dominate this block are in simplified form.
Definition at line 95 of file IVUsers.cpp.
References BB, llvm::SmallPtrSetImpl< PtrType >::count(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::DomTreeNodeBase< NodeT >::getIDom(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode(), llvm::SmallPtrSetImpl< PtrType >::insert(), and llvm::Loop::isLoopSimplifyForm().
Referenced by llvm::IVUsers::AddUsersImpl().
IVUseShouldUsePostIncValue()
static bool IVUseShouldUsePostIncValue (Instruction * User, Value * Operand, const Loop * L, DominatorTree * DT) static
IVUseShouldUsePostIncValue - We have discovered a "User" of an IV expression and now we need to decide whether the user should use the preinc or post-inc value.
If this user should use the post-inc version of the IV, return true.
Choosing wrong here can break dominance properties (if we choose to use the post-inc value when we cannot) or it can end up adding extra live-ranges to the loop, resulting in reg-reg copies (if we use the pre-inc value when we should use the post-inc value).
Definition at line 129 of file IVUsers.cpp.
References llvm::LoopBase< BlockT, LoopT >::contains(), llvm::DominatorTree::dominates(), llvm::numbers::e, llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::PHINode::getNumIncomingValues(), and i.
Referenced by llvm::IVUsers::AddUsersImpl().
Variable Documentation
false
iv Induction Variable false
Definition at line 53 of file IVUsers.cpp.
users
iv users
Definition at line 52 of file IVUsers.cpp.
Referenced by llvm::AnyCoroIdInst::getCoroAlloc(), llvm::AnyCoroIdInst::getCoroBegin(), llvm::Constant::isConstantUsed(), and llvm::isInlineViable().
Users
iv Induction Variable Users
Definition at line 52 of file IVUsers.cpp.
Referenced by llvm::VPValue::addUser(), llvm::findDefsUsedOutsideOfLoop(), llvm::mca::WriteState::getNumUsers(), llvm::VPValue::getNumUsers(), insertTrivialPHIs(), isAllocSiteRemovable(), isPossibleIndirectCallTarget(), isProfitableChain(), makeAllConstantUsesInstructions(), llvm::VPlanTransforms::mergeReplicateRegions(), llvm::VPValue::removeUser(), replaceWithConstant(), rewriteDebugUsers(), llvm::mca::WriteState::setEliminated(), sink(), tryPromoteAllocaToVector(), llvm::MachineRegisterInfo::updateDbgUsersToReg(), llvm::VPValue::user_begin(), llvm::VPValue::user_end(), and llvm::InstCombinerImpl::visitAllocSite().