LLVM: lib/Transforms/Vectorize/LoadStoreVectorizer.cpp File Reference
LoadStoreVectorizer.cpp File Reference
#include "llvm/Transforms/Vectorize/LoadStoreVectorizer.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/MemoryLocation.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/Analysis/VectorUtils.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Vectorize.h"
#include <algorithm>
#include <cassert>
#include <cstdlib>
#include <tuple>
#include <utility>
Macros
#define DEBUG_TYPE "load-store-vectorizer"
Functions
STATISTIC (NumVectorInstructions, "Number of vector accesses generated")
STATISTIC (NumScalarsVectorized, "Number of scalar accesses vectorized")
INITIALIZE_PASS_BEGIN (LoadStoreVectorizerLegacyPass, DEBUG_TYPE, "Vectorize load and Store instructions", false, false) INITIALIZE_PASS_DEPENDENCY(AssumptionCacheTracker)
INITIALIZE_PASS_END (LoadStoreVectorizerLegacyPass, DEBUG_TYPE, "Vectorize load and store instructions", false, false) Pass *llvm
static void propagateMetadata (Instruction *I, ArrayRef< Instruction * > IL)
static bool checkNoWrapFlags (Instruction *I, bool Signed)
static bool checkIfSafeAddSequence (const APInt &IdxDiff, Instruction *AddOpA, unsigned MatchingOpIdxA, Instruction *AddOpB, unsigned MatchingOpIdxB, bool Signed)
static ChainID getChainID (const Value *Ptr)
Variables
static const unsigned StackAdjustedAlignment = 4
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "load-store-vectorizer"
Definition at line 91 of file LoadStoreVectorizer.cpp.
Function Documentation
checkIfSafeAddSequence()
static bool checkIfSafeAddSequence (const APInt & IdxDiff, Instruction * AddOpA, unsigned MatchingOpIdxA, Instruction * AddOpB, unsigned MatchingOpIdxB, bool Signed) static
Definition at line 393 of file LoadStoreVectorizer.cpp.
References llvm::MCID::Add, assert(), checkNoWrapFlags(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::APInt::getSExtValue(), and Signed.
checkNoWrapFlags()
static bool checkNoWrapFlags (Instruction * I, bool Signed) static
Definition at line 387 of file LoadStoreVectorizer.cpp.
References llvm::Instruction::hasNoSignedWrap(), llvm::Instruction::hasNoUnsignedWrap(), I, and Signed.
Referenced by checkIfSafeAddSequence().
getChainID()
static ChainID getChainID (const Value * Ptr) static
Definition at line 809 of file LoadStoreVectorizer.cpp.
References llvm::getUnderlyingObject().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (LoadStoreVectorizerLegacyPass , DEBUG_TYPE , "Vectorize load and Store instructions" , false , false)
INITIALIZE_PASS_END()
INITIALIZE_PASS_END (LoadStoreVectorizerLegacyPass , DEBUG_TYPE , "Vectorize load and store instructions" , false , false)
Definition at line 230 of file LoadStoreVectorizer.cpp.
propagateMetadata()
static void propagateMetadata (Instruction * I, ArrayRef< Instruction * > IL) static
Definition at line 275 of file LoadStoreVectorizer.cpp.
References llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), I, and llvm::propagateMetadata().
STATISTIC() [1/2]
STATISTIC (NumScalarsVectorized , "Number of scalar accesses vectorized")
STATISTIC() [2/2]
STATISTIC (NumVectorInstructions , "Number of vector accesses generated")
Variable Documentation
StackAdjustedAlignment
const unsigned StackAdjustedAlignment = 4 static
Definition at line 97 of file LoadStoreVectorizer.cpp.