LLVM: lib/CodeGen/MachineModuleInfo.cpp File Reference
MachineModuleInfo.cpp File Reference
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/TinyPtrVector.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/InitializePasses.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCSymbolXCOFF.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Target/TargetMachine.h"
#include <algorithm>
#include <cassert>
#include <memory>
#include <utility>
#include <vector>
Classes
class llvm::MMIAddrLabelMapCallbackPtr
class llvm::MMIAddrLabelMap
Namespaces
llvm
---------------------— PointerInfo ------------------------------------—
Functions
static INITIALIZE_PASS(MachineModuleInfoWrapperPass, "machinemoduleinfo", "Machine Module Information", false, false) char MachineModuleInfoWrapperPass unsigned getLocCookie (const SMDiagnostic &SMD, const SourceMgr &SrcMgr, std::vector< const MDNode * > &LocInfos)
Function Documentation
getLocCookie()
static INITIALIZE_PASS (MachineModuleInfoWrapperPass, "machinemoduleinfo", "Machine Module Information", false, false) char MachineModuleInfoWrapperPass unsigned getLocCookie (const SMDiagnostic & SMD, const SourceMgr & SrcMgr, std::vector< const MDNode * > & LocInfos) static
Definition at line 372 of file MachineModuleInfo.cpp.
References llvm::SourceMgr::FindBufferContainingLoc(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), and llvm::SrcMgr.
Referenced by llvm::MachineModuleInfoWrapperPass::doInitialization().