LLVM: lib/MC/MCPseudoProbe.cpp File Reference
MCPseudoProbe.cpp File Reference
#include "llvm/MC/MCPseudoProbe.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCObjectStreamer.h"
#include "llvm/MC/MCStreamer.h"
Macros
#define DEBUG_TYPE "mcpseudoprobe"
Functions
static const MCExpr * buildSymbolDiff (MCObjectStreamer *MCOS, const MCSymbol *A, const MCSymbol *B)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mcpseudoprobe"
Definition at line 16 of file MCPseudoProbe.cpp.
Function Documentation
buildSymbolDiff()
static const MCExpr* buildSymbolDiff (MCObjectStreamer * MCOS, const MCSymbol * A, const MCSymbol * B) static
Definition at line 24 of file MCPseudoProbe.cpp.
References A, B, Context, llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::create(), llvm::MCStreamer::getContext(), llvm::MCBinaryExpr::Sub, and llvm::MCSymbolRefExpr::VK_None.
Referenced by llvm::MCPseudoProbe::emit().