LLVM: config Namespace Reference
config Namespace Reference
Functions
def get_input_signature ()
def get_output_signature ()
def get_output_spec ()
Variables
string POLICY_DECISION_LABEL = 'inlining_decision'
string POLICY_OUTPUT_SPEC
Detailed Description
Inlining Training config.
Function Documentation
get_input_signature()
def config.get_input_signature ()
Returns the list of features for LLVM inlining.
Definition at line 24 of file config.py.
Referenced by generate_mock_model.get_external_signature().
get_output_signature()
def config.get_output_signature ()
Definition at line 82 of file config.py.
Referenced by generate_mock_model.get_external_signature().
get_output_spec()
def config.get_output_spec ()
Definition at line 86 of file config.py.
Referenced by generate_mock_model.get_external_signature().
Variable Documentation
POLICY_DECISION_LABEL
string config.POLICY_DECISION_LABEL = 'inlining_decision'
Definition at line 5 of file config.py.
POLICY_OUTPUT_SPEC
string config.POLICY_OUTPUT_SPEC
Initial value:
 =  """
 [
     {
         "logging_name": "inlining_decision",
         "tensor_spec": {
             "name": "StatefulPartitionedCall",
             "port": 0,
             "type": "int64_t",
             "shape": [
                 1
             ]
         }
     }
 ]
 """
Definition at line 6 of file config.py.