LLVM: llvm::VNCoercion Namespace Reference
llvm::VNCoercion Namespace Reference
Functions
bool canCoerceMustAliasedValueToLoad (Value *StoredVal, Type *LoadTy, const DataLayout &DL)
Return true if CoerceAvailableValueToLoadType would succeed if it was called.
Value * coerceAvailableValueToLoadType (Value *StoredVal, Type *LoadedTy, IRBuilderBase &IRB, const DataLayout &DL)
If we saw a store of a value to memory, and then a load from a must-aliased pointer of a different type, try to coerce the stored value to the loaded type.
int analyzeLoadFromClobberingStore (Type *LoadTy, Value *LoadPtr, StoreInst *DepSI, const DataLayout &DL)
This function determines whether a value for the pointer LoadPtr can be extracted from the store at DepSI.
int analyzeLoadFromClobberingLoad (Type *LoadTy, Value *LoadPtr, LoadInst *DepLI, const DataLayout &DL)
This function determines whether a value for the pointer LoadPtr can be extracted from the load at DepLI.
int analyzeLoadFromClobberingMemInst (Type *LoadTy, Value *LoadPtr, MemIntrinsic *DepMI, const DataLayout &DL)
This function determines whether a value for the pointer LoadPtr can be extracted from the memory intrinsic at DepMI.
Value * getStoreValueForLoad (Value *SrcVal, unsigned Offset, Type *LoadTy, Instruction *InsertPt, const DataLayout &DL)
If analyzeLoadFromClobberingStore returned an offset, this function can be used to actually perform the extraction of the bits from the store.
Constant * getConstantStoreValueForLoad (Constant *SrcVal, unsigned Offset, Type *LoadTy, const DataLayout &DL)
Value * getLoadValueForLoad (LoadInst *SrcVal, unsigned Offset, Type *LoadTy, Instruction *InsertPt, const DataLayout &DL)
If analyzeLoadFromClobberingLoad returned an offset, this function can be used to actually perform the extraction of the bits from the load, including any necessary load widening.
Constant * getConstantLoadValueForLoad (Constant *SrcVal, unsigned Offset, Type *LoadTy, const DataLayout &DL)
Value * getMemInstValueForLoad (MemIntrinsic *SrcInst, unsigned Offset, Type *LoadTy, Instruction *InsertPt, const DataLayout &DL)
If analyzeLoadFromClobberingMemInst returned an offset, this function can be used to actually perform the extraction of the bits from the memory intrinsic.
Constant * getConstantMemInstValueForLoad (MemIntrinsic *SrcInst, unsigned Offset, Type *LoadTy, const DataLayout &DL)
static bool isFirstClassAggregateOrScalableType (Type *Ty)
template<class T , class HelperClass >
static T * coerceAvailableValueToLoadTypeHelper (T *StoredVal, Type *LoadedTy, HelperClass &Helper, const DataLayout &DL)
static int analyzeLoadFromClobberingWrite (Type *LoadTy, Value *LoadPtr, Value *WritePtr, uint64_t WriteSizeInBits, const DataLayout &DL)
This function is called when we have a memdep query of a load that ends up being a clobbering memory write (store, memset, memcpy, memmove).
static unsigned getLoadLoadClobberFullWidthSize (const Value *MemLocBase, int64_t MemLocOffs, unsigned MemLocSize, const LoadInst *LI)
Looks at a memory location for a load (specified by MemLocBase, Offs, and Size) and compares it against a load.
template<class T , class HelperClass >
static T * getStoreValueForLoadHelper (T *SrcVal, unsigned Offset, Type *LoadTy, HelperClass &Helper, const DataLayout &DL)
template<class T , class HelperClass >
T * getMemInstValueForLoadHelper (MemIntrinsic *SrcInst, unsigned Offset, Type *LoadTy, HelperClass &Helper, const DataLayout &DL)
Function Documentation
analyzeLoadFromClobberingLoad()
int llvm::VNCoercion::analyzeLoadFromClobberingLoad (Type * LoadTy, Value * LoadPtr, LoadInst * DepLI, const DataLayout & DL)
This function determines whether a value for the pointer LoadPtr can be extracted from the load at DepLI.
This function is called when we have a memdep query of a load that ends up being clobbered by another load.
On success, it returns the offset into DepLI that extraction would start. On failure, it returns -1.
See if the other load can feed into the second load.
Definition at line 332 of file VNCoercion.cpp.
References analyzeLoadFromClobberingWrite(), assert(), canCoerceMustAliasedValueToLoad(), DL, getLoadLoadClobberFullWidthSize(), llvm::GetPointerBaseWithConstantOffset(), llvm::LoadInst::getPointerOperand(), llvm::Value::getType(), llvm::Type::isArrayTy(), llvm::Type::isIntegerTy(), llvm::LoadInst::isSimple(), llvm::Type::isStructTy(), llvm::RISCVFenceField::R, and llvm::Check::Size.
analyzeLoadFromClobberingMemInst()
int llvm::VNCoercion::analyzeLoadFromClobberingMemInst (Type * LoadTy, Value * LoadPtr, MemIntrinsic * DepMI, const DataLayout & DL)
This function determines whether a value for the pointer LoadPtr can be extracted from the memory intrinsic at DepMI.
On success, it returns the offset into DepMI that extraction would start. On failure, it returns -1.
Definition at line 367 of file VNCoercion.cpp.
References analyzeLoadFromClobberingWrite(), llvm::ConstantFoldLoadFromConstPtr(), DL, llvm::PointerType::get(), llvm::ConstantInt::get(), llvm::ConstantExpr::getBitCast(), llvm::Value::getContext(), llvm::ConstantExpr::getGetElementPtr(), llvm::Type::getInt64Ty(), llvm::Type::getInt8PtrTy(), llvm::Type::getInt8Ty(), llvm::Type::getPointerAddressSpace(), llvm::Type::getScalarType(), llvm::MemTransferBase< BaseCL >::getSource(), llvm::Value::getType(), llvm::getUnderlyingObject(), llvm::ConstantInt::getZExtValue(), llvm::GlobalVariable::hasDefinitiveInitializer(), llvm::GlobalVariable::isConstant(), MI, and Offset.
analyzeLoadFromClobberingStore()
int llvm::VNCoercion::analyzeLoadFromClobberingStore (Type * LoadTy, Value * LoadPtr, StoreInst * DepSI, const DataLayout & DL)
This function determines whether a value for the pointer LoadPtr can be extracted from the store at DepSI.
This function is called when we have a memdep query of a load that ends up being a clobbering store.
On success, it returns the offset into DepSI that extraction would start. On failure, it returns -1.
Definition at line 226 of file VNCoercion.cpp.
References analyzeLoadFromClobberingWrite(), canCoerceMustAliasedValueToLoad(), DL, llvm::StoreInst::getPointerOperand(), llvm::Value::getType(), llvm::StoreInst::getValueOperand(), and isFirstClassAggregateOrScalableType().
analyzeLoadFromClobberingWrite()
static int llvm::VNCoercion::analyzeLoadFromClobberingWrite (Type * LoadTy, Value * LoadPtr, Value * WritePtr, uint64_t WriteSizeInBits, const DataLayout & DL) static
This function is called when we have a memdep query of a load that ends up being a clobbering memory write (store, memset, memcpy, memmove).
This means that the write may provide bits used by the load but we can't be sure because the pointers don't must-alias.
Check this case to see if there is anything more we can do before we give up. This returns -1 if we have to give up, or a byte number in the stored value of the piece that feeds the load.
Definition at line 176 of file VNCoercion.cpp.
References DL, llvm::GetPointerBaseWithConstantOffset(), and isFirstClassAggregateOrScalableType().
Referenced by analyzeLoadFromClobberingLoad(), analyzeLoadFromClobberingMemInst(), and analyzeLoadFromClobberingStore().
canCoerceMustAliasedValueToLoad()
bool llvm::VNCoercion::canCoerceMustAliasedValueToLoad (Value * StoredVal, Type * LoadTy, const DataLayout & DL)
Return true if CoerceAvailableValueToLoadType would succeed if it was called.
Return true if coerceAvailableValueToLoadType will succeed.
Definition at line 17 of file VNCoercion.cpp.
References llvm::alignTo(), DL, llvm::Type::getPointerAddressSpace(), llvm::Type::getScalarType(), llvm::Value::getType(), and isFirstClassAggregateOrScalableType().
Referenced by analyzeLoadFromClobberingLoad(), analyzeLoadFromClobberingStore(), and coerceAvailableValueToLoadTypeHelper().
coerceAvailableValueToLoadType()
Value * llvm::VNCoercion::coerceAvailableValueToLoadType (Value * StoredVal, Type * LoadedTy, IRBuilderBase & IRB, const DataLayout & DL)
If we saw a store of a value to memory, and then a load from a must-aliased pointer of a different type, try to coerce the stored value to the loaded type.
If we saw a store of a value to memory, and then a load from a must-aliased pointer of a different type, try to coerce the stored value.
LoadedTy is the type of the load we want to replace. IRB is IRBuilder used to insert new instructions.
If we can't do it, return null.
Definition at line 162 of file VNCoercion.cpp.
References coerceAvailableValueToLoadTypeHelper(), and DL.
coerceAvailableValueToLoadTypeHelper()
template<class T , class HelperClass > static T* llvm::VNCoercion::coerceAvailableValueToLoadTypeHelper (T * StoredVal, Type * LoadedTy, HelperClass & Helper, const DataLayout & DL) static
Definition at line 67 of file VNCoercion.cpp.
References assert(), canCoerceMustAliasedValueToLoad(), llvm::ConstantFoldConstant(), DL, llvm::IntegerType::get(), llvm::ConstantInt::get(), llvm::Type::getContext(), llvm::Type::isIntegerTy(), and llvm::Type::isPtrOrPtrVectorTy().
Referenced by coerceAvailableValueToLoadType(), getConstantStoreValueForLoad(), getMemInstValueForLoadHelper(), and getStoreValueForLoad().
getConstantLoadValueForLoad()
Constant * llvm::VNCoercion::getConstantLoadValueForLoad (Constant * SrcVal, unsigned Offset, Type * LoadTy, const DataLayout & DL)
Definition at line 535 of file VNCoercion.cpp.
References DL, getConstantStoreValueForLoad(), llvm::Value::getType(), and Offset.
getConstantMemInstValueForLoad()
Constant * llvm::VNCoercion::getConstantMemInstValueForLoad (MemIntrinsic * SrcInst, unsigned Offset, Type * LoadTy, const DataLayout & DL)
Definition at line 612 of file VNCoercion.cpp.
References DL, F, and Offset.
getConstantStoreValueForLoad()
Constant * llvm::VNCoercion::getConstantStoreValueForLoad (Constant * SrcVal, unsigned Offset, Type * LoadTy, const DataLayout & DL)
Definition at line 476 of file VNCoercion.cpp.
References coerceAvailableValueToLoadTypeHelper(), DL, F, getStoreValueForLoadHelper(), and Offset.
Referenced by getConstantLoadValueForLoad().
getLoadLoadClobberFullWidthSize()
static unsigned llvm::VNCoercion::getLoadLoadClobberFullWidthSize (const Value * MemLocBase, int64_t MemLocOffs, unsigned MemLocSize, const LoadInst * LI) static
Looks at a memory location for a load (specified by MemLocBase, Offs, and Size) and compares it against a load.
If the specified load could be safely widened to a larger integer load that is 1) still efficient, 2) safe for the target, and 3) would provide the specified memory location value, then this function returns the size in bytes of the load width to use. If not, this returns zero.
Definition at line 251 of file VNCoercion.cpp.
References DL, llvm::LoadInst::getAlignment(), llvm::Module::getDataLayout(), llvm::Instruction::getModule(), llvm::BasicBlock::getParent(), llvm::Instruction::getParent(), llvm::GetPointerBaseWithConstantOffset(), llvm::LoadInst::getPointerOperand(), llvm::Type::getPrimitiveSizeInBits(), llvm::Value::getType(), llvm::Function::hasFnAttribute(), llvm::LoadInst::isSimple(), and llvm::NextPowerOf2().
Referenced by analyzeLoadFromClobberingLoad().
getLoadValueForLoad()
Value * llvm::VNCoercion::getLoadValueForLoad (LoadInst * SrcVal, unsigned Offset, Type * LoadTy, Instruction * InsertPt, const DataLayout & DL)
If analyzeLoadFromClobberingLoad returned an offset, this function can be used to actually perform the extraction of the bits from the load, including any necessary load widening.
This function is called when we have a memdep query of a load that ends up being a clobbering load.
It inserts instructions to do so at InsertPt, and returns the extracted value.
This means that the load may provide bits used by the load but we can't be sure because the pointers don't must-alias. Check this case to see if there is anything more we can do before we give up.
Definition at line 488 of file VNCoercion.cpp.
References assert(), Builder, llvm::dbgs(), DL, llvm::IntegerType::get(), llvm::PointerType::get(), llvm::LoadInst::getAlign(), llvm::Type::getContext(), llvm::Instruction::getDebugLoc(), llvm::Instruction::getParent(), llvm::Type::getPointerAddressSpace(), llvm::LoadInst::getPointerOperand(), getStoreValueForLoad(), llvm::Value::getType(), llvm::Type::isIntegerTy(), llvm::isPowerOf2_32(), llvm::LoadInst::isSimple(), LLVM_DEBUG, llvm::NextPowerOf2(), Offset, llvm::Value::replaceAllUsesWith(), llvm::LoadInst::setAlignment(), and llvm::Value::takeName().
Referenced by llvm::gvn::AvailableValue::MaterializeAdjustedValue().
getMemInstValueForLoad()
Value * llvm::VNCoercion::getMemInstValueForLoad (MemIntrinsic * SrcInst, unsigned Offset, Type * LoadTy, Instruction * InsertPt, const DataLayout & DL)
If analyzeLoadFromClobberingMemInst returned an offset, this function can be used to actually perform the extraction of the bits from the memory intrinsic.
This function is called when we have a memdep query of a load that ends up being a clobbering mem intrinsic.
It inserts instructions to do so at InsertPt, and returns the extracted value.
Definition at line 604 of file VNCoercion.cpp.
References Builder, DL, and Offset.
Referenced by llvm::gvn::AvailableValue::MaterializeAdjustedValue().
getMemInstValueForLoadHelper()
template<class T , class HelperClass > T* llvm::VNCoercion::getMemInstValueForLoadHelper (MemIntrinsic * SrcInst, unsigned Offset, Type * LoadTy, HelperClass & Helper, const DataLayout & DL)
Definition at line 546 of file VNCoercion.cpp.
References coerceAvailableValueToLoadTypeHelper(), llvm::ConstantFoldLoadFromConstPtr(), DL, llvm::IntegerType::get(), llvm::PointerType::get(), llvm::ConstantInt::get(), llvm::ConstantExpr::getBitCast(), llvm::Type::getContext(), llvm::Value::getContext(), llvm::ConstantExpr::getGetElementPtr(), llvm::Type::getInt64Ty(), llvm::Type::getInt8PtrTy(), llvm::Type::getInt8Ty(), llvm::Type::getPointerAddressSpace(), llvm::MemTransferBase< BaseCL >::getSource(), llvm::Value::getType(), Offset, and T.
getStoreValueForLoad()
Value * llvm::VNCoercion::getStoreValueForLoad (Value * SrcVal, unsigned Offset, Type * LoadTy, Instruction * InsertPt, const DataLayout & DL)
If analyzeLoadFromClobberingStore returned an offset, this function can be used to actually perform the extraction of the bits from the store.
This function is called when we have a memdep query of a load that ends up being a clobbering store.
It inserts instructions to do so at InsertPt, and returns the extracted value.
This means that the store provides bits used by the load but the pointers don't must-alias. Check this case to see if there is anything more we can do before we give up.
Definition at line 468 of file VNCoercion.cpp.
References Builder, coerceAvailableValueToLoadTypeHelper(), DL, getStoreValueForLoadHelper(), and Offset.
Referenced by getLoadValueForLoad(), and llvm::gvn::AvailableValue::MaterializeAdjustedValue().
getStoreValueForLoadHelper()
template<class T , class HelperClass > static T* llvm::VNCoercion::getStoreValueForLoadHelper (T * SrcVal, unsigned Offset, Type * LoadTy, HelperClass & Helper, const DataLayout & DL) static
Definition at line 424 of file VNCoercion.cpp.
References DL, llvm::IntegerType::get(), llvm::ConstantInt::get(), llvm::Type::isPointerTy(), and Offset.
Referenced by getConstantStoreValueForLoad(), and getStoreValueForLoad().
isFirstClassAggregateOrScalableType()
static bool llvm::VNCoercion::isFirstClassAggregateOrScalableType (Type * Ty) static
Definition at line 12 of file VNCoercion.cpp.
References llvm::Type::isArrayTy(), and llvm::Type::isStructTy().
Referenced by analyzeLoadFromClobberingStore(), analyzeLoadFromClobberingWrite(), and canCoerceMustAliasedValueToLoad().