LLVM: llvm::coro Namespace Reference
llvm::coro Namespace Reference
Classes
struct LowererBase
struct Shape
Enumerations
enum ABI { ABI::Switch, ABI::Retcon, ABI::RetconOnce, ABI::Async }
Functions
bool declaresIntrinsics (const Module &M, const std::initializer_list< StringRef >)
void replaceCoroFree (CoroIdInst *CoroId, bool Elide)
void updateCallGraph (Function &Caller, ArrayRef< Function * > Funcs, CallGraph &CG, CallGraphSCC &SCC)
void salvageDebugInfo (SmallDenseMap< llvm::Value *, llvm::AllocaInst *, 4 > &DbgPtrAllocaCache, DbgVariableIntrinsic *DVI, bool ReuseFrameSlot)
Recover a dbg.declare prepared by the frontend and emit an alloca holding a pointer to the coroutine frame.
void buildCoroutineFrame (Function &F, Shape &Shape)
CallInst * createMustTailCall (DebugLoc Loc, Function *MustTailCallFn, ArrayRef< Value * > Arguments, IRBuilder<> &)
Enumeration Type Documentation
ABI
enum llvm::coro::ABI strong
Enumerator
Switch
The "resume-switch" lowering, where there are separate resume and destroy functions that are shared between all suspend points.
The coroutine frame implicitly stores the resume and destroy functions, the current index, and any promise value.
Retcon
The "returned-continuation" lowering, where each suspend point creates a single continuation function that is used for both resuming and destroying.
Does not support promises.
RetconOnce
The "unique returned-continuation" lowering, where each suspend point creates a single continuation function that is used for both resuming and destroying.
Does not support promises. The function is known to suspend at most once during its execution, and the return value of the continuation is void.
Async
The "async continuation" lowering, where each suspend point creates a single continuation function.
The continuation function is available as an intrinsic.
Definition at line 71 of file CoroInternal.h.
Function Documentation
buildCoroutineFrame()
void llvm::coro::buildCoroutineFrame (Function & F, Shape & Shape)
Definition at line 2587 of file CoroFrame.cpp.
References A, llvm::coro::Shape::ABI, llvm::AMDGPU::HSAMD::Kernel::Key::Args, Arguments, Builder, llvm::MCID::Call, cleanupSinglePredPHIs(), llvm::CoroIdInst::clearPromise(), collectFrameAllocas(), llvm::coro::Shape::CoroBegin, llvm::coro::Shape::CoroEnds, llvm::coro::Shape::CoroSuspends, createMustTailCall(), llvm::ArrayRef< T >::drop_front(), dumpAllocas(), dumpSpills(), eliminateSwiftError(), F, llvm::findDbgValues(), llvm::coro::Shape::getSwitchCoroId(), I, instructions, isCoroutineStructureIntrinsic(), isLocalAlloca(), LLVM_DEBUG, materializable(), llvm::coro::Shape::SwitchLoweringStorage::PromiseAlloca, rewriteMaterializableInstructions(), rewritePHIs(), sinkLifetimeStartMarkers(), splitAround(), and llvm::coro::Shape::SwitchLowering.
Referenced by splitCoroutine().
createMustTailCall()
CallInst * llvm::coro::createMustTailCall (DebugLoc Loc, Function * MustTailCallFn, ArrayRef< Value * > Arguments, IRBuilder<> & Builder)
Definition at line 1575 of file CoroSplit.cpp.
References Arguments, Builder, coerceArguments(), llvm::Function::getCallingConv(), llvm::Type::getPointerElementType(), llvm::GlobalValue::getType(), llvm::MipsISD::TailCall, and llvm::CallInst::TCK_MustTail.
Referenced by buildCoroutineFrame().
declaresIntrinsics()
bool llvm::coro::declaresIntrinsics (const Module & M, const std::initializer_list< StringRef > List)
Definition at line 161 of file Coroutines.cpp.
References assert(), isCoroutineIntrinsicName(), List, and M.
Referenced by declaresCoroCleanupIntrinsics(), declaresCoroEarlyIntrinsics(), declaresCoroElideIntrinsics(), and declaresCoroSplitIntrinsics().
replaceCoroFree()
void llvm::coro::replaceCoroFree (CoroIdInst * CoroId, bool Elide)
Definition at line 174 of file Coroutines.cpp.
References llvm::ConstantPointerNull::get(), llvm::Value::getContext(), llvm::Type::getInt8PtrTy(), and llvm::Value::users().
Referenced by handleNoSuspendCoroutine().
salvageDebugInfo()
void llvm::coro::salvageDebugInfo (SmallDenseMap< llvm::Value *, llvm::AllocaInst *, 4 > & DbgPtrAllocaCache, DbgVariableIntrinsic * DVI, bool ReuseFrameSlot)
Recover a dbg.declare prepared by the frontend and emit an alloca holding a pointer to the coroutine frame.
It makes no sense to move the dbg.value intrinsic.
Definition at line 2501 of file CoroFrame.cpp.
References Arg, Builder, EnableReuseStorageInFrame, F, llvm::DbgVariableIntrinsic::getExpression(), llvm::Instruction::getFunction(), llvm::Value::getType(), llvm::DbgVariableIntrinsic::getVariableLocationOp(), llvm::DIExpression::isComplex(), llvm::Instruction::moveAfter(), llvm::DbgVariableIntrinsic::replaceVariableLocationOp(), llvm::salvageDebugInfoImpl(), and llvm::DbgVariableIntrinsic::setExpression().
updateCallGraph()
void llvm::coro::updateCallGraph (Function & Caller, ArrayRef< Function * > Funcs, CallGraph & CG, CallGraphSCC & SCC)
Definition at line 215 of file Coroutines.cpp.
References buildCGN(), Callee, F, llvm::CallGraph::getOrInsertFunction(), and llvm::AMDGPU::CPol::SCC.
Referenced by updateCallGraphAfterCoroutineSplit().