LLVM: llvm::orc::shared Namespace Reference
llvm::orc::shared Namespace Reference
Namespaces
detail
Classes
class APICalls
Convenience class for grouping RPCFunctions into APIs that can be negotiated as a block.
class APICalls< APICalls< InnerFuncs... >, Funcs... >
class APICalls< Func, Funcs... >
class BadFunctionCall
BadFunctionCall is returned from handleOne when the remote makes a call with an unrecognized function id.
class ConnectionClosed
RPCConnectionClosed is returned from RPC operations if the RPC connection has already been closed due to either an error or graceful disconnection.
class CouldNotNegotiate
This error is returned if the remote does not have a handler installed for the given RPC function.
class FDRawByteChannel
Serialization channel that reads from and writes from file descriptors.
class InvalidSequenceNumberForResponse
InvalidSequenceNumberForResponse is returned from handleOne when a response call arrives with a sequence number that doesn't correspond to any in-flight function call.
class MultiThreadedRPCEndpoint
class ParallelCallGroup
Allows a set of asynchrounous calls to be dispatched, and then waited on as a group.
class RawByteChannel
Interface for byte-streams to be used with ORC Serialization.
class ResponseAbandoned
This non-fatal error will be passed to asynchronous result handlers in place of a result if the connection goes down before a result returns, or if the function to be called cannot be negotiated with the remote.
class RPCAsyncDispatch
Asynchronous dispatch for a function on an RPC endpoint.
class RPCFatalError
Base class of all fatal RPC errors (those that necessarily result in the termination of the RPC session).
class RPCFunction
class RPCFunction< DerivedFunc, RetT(ArgTs...)>
class RPCFunctionIdAllocator
Allocates RPC function ids during autonegotiation.
class RPCFunctionIdAllocator< T, std::enable_if_t< std::is_integral< T >::value > >
This specialization of RPCFunctionIdAllocator provides a default implementation for integral types.
class SequenceSerialization
Utility class for serializing sequences of values of varying types.
class SequenceSerialization< ChannelT >
class SequenceSerialization< ChannelT, ArgT >
class SequenceSerialization< ChannelT, ArgT, ArgTs... >
class SequenceTraits
class SerializationTraits
The SerializationTraits<ChannelT, T> class describes how to serialize and deserialize an instance of type T to/from an abstract channel of type ChannelT.
class SerializationTraits< ChannelT, bool, bool, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >
class SerializationTraits< ChannelT, Error >
class SerializationTraits< ChannelT, Expected< T >, Error >
SerializationTraits for Expected<T1> from an Error.
class SerializationTraits< ChannelT, Expected< T1 >, Expected< T2 > >
SerializationTraits for Expected<T1> from an Expected<T2>.
class SerializationTraits< ChannelT, Expected< T1 >, T2 >
SerializationTraits for Expected<T1> from a T2.
class SerializationTraits< ChannelT, JITSymbolFlags >
class SerializationTraits< ChannelT, Optional< T > >
class SerializationTraits< ChannelT, orcrpctpc::ExecutorProcessInfo >
class SerializationTraits< ChannelT, orcrpctpc::ReleaseOrFinalizeMemRequestElement >
class SerializationTraits< ChannelT, orcrpctpc::ReserveMemRequestElement >
class SerializationTraits< ChannelT, orcrpctpc::ReserveMemResultElement >
class SerializationTraits< ChannelT, remote::DirectBufferWriter, remote::DirectBufferWriter, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >
class SerializationTraits< ChannelT, std::map< K, V >, DenseMap< K2, V2 > >
class SerializationTraits< ChannelT, std::map< K, V >, std::map< K2, V2 > >
class SerializationTraits< ChannelT, std::pair< T1, T2 >, std::pair< T3, T4 > >
SerializationTraits default specialization for std::pair.
class SerializationTraits< ChannelT, std::set< T >, std::set< T2 > >
class SerializationTraits< ChannelT, std::string, std::string, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >
class SerializationTraits< ChannelT, std::string, StringRef, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >
class SerializationTraits< ChannelT, std::string, T, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value &&(std::is_same< T, const char * >::value||std::is_same< T, char * >::value)> >
class SerializationTraits< ChannelT, std::tuple< ArgTs... > >
SerializationTraits default specialization for std::tuple.
class SerializationTraits< ChannelT, std::vector< T > >
SerializationTraits default specialization for std::vector.
class SerializationTraits< ChannelT, std::vector< T >, ArrayRef< T > >
Enable vector serialization from an ArrayRef.
class SerializationTraits< ChannelT, T, T, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value &&(std::is_same< T, uint8_t >::value||std::is_same< T, int8_t >::value||std::is_same< T, uint16_t >::value||std::is_same< T, int16_t >::value||std::is_same< T, uint32_t >::value||std::is_same< T, int32_t >::value||std::is_same< T, uint64_t >::value||std::is_same< T, int64_t >::value||std::is_same< T, char >::value)> >
class SerializationTraits< ChannelT, tpctypes::BufferWrite, tpctypes::BufferWrite, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >
class SerializationTraits< ChannelT, WrapperFunctionResult, WrapperFunctionResult, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >
class SerializationTraits< ChannelT, WriteT, WriteT, std::enable_if_t< std::is_same< WriteT, tpctypes::UInt8Write >::value||std::is_same< WriteT, tpctypes::UInt16Write >::value||std::is_same< WriteT, tpctypes::UInt32Write >::value||std::is_same< WriteT, tpctypes::UInt64Write >::value > >
class SerializationTypeName
class SerializationTypeName< bool >
class SerializationTypeName< Error >
class SerializationTypeName< Expected< T > >
class SerializationTypeName< int16_t >
class SerializationTypeName< int32_t >
class SerializationTypeName< int64_t >
class SerializationTypeName< int8_t >
class SerializationTypeName< JITSymbolFlags >
class SerializationTypeName< Optional< T > >
class SerializationTypeName< orcrpctpc::ExecutorProcessInfo >
class SerializationTypeName< orcrpctpc::ReleaseOrFinalizeMemRequestElement >
class SerializationTypeName< orcrpctpc::ReserveMemRequestElement >
class SerializationTypeName< orcrpctpc::ReserveMemResultElement >
class SerializationTypeName< remote::DirectBufferWriter >
class SerializationTypeName< std::map< K, V > >
class SerializationTypeName< std::pair< T1, T2 > >
class SerializationTypeName< std::set< T > >
class SerializationTypeName< std::string >
class SerializationTypeName< std::tuple< ArgTs... > >
class SerializationTypeName< std::vector< T > >
class SerializationTypeName< tpctypes::BufferWrite >
class SerializationTypeName< tpctypes::UInt16Write >
class SerializationTypeName< tpctypes::UInt32Write >
class SerializationTypeName< tpctypes::UInt64Write >
class SerializationTypeName< tpctypes::UInt8Write >
class SerializationTypeName< uint16_t >
class SerializationTypeName< uint32_t >
class SerializationTypeName< uint64_t >
class SerializationTypeName< uint8_t >
class SerializationTypeName< void >
class SerializationTypeName< WrapperFunctionResult >
class SerializationTypeNameSequence
TypeNameSequence is a utility for rendering sequences of types to a string by rendering each type, separated by ", ".
class SingleThreadedRPCEndpoint
class SPSArgList
A utility class for serializing to a blob from a variadic list.
class SPSArgList< SPSTagT, SPSTagTs... >
class SPSArgList<>
class SPSEmpty
class SPSExecutorAddress
SPS tag type for executor addresseses.
class SPSExpected
SPS tag type for expecteds, which are either a T or a string representing an error.
class SPSInputBuffer
Input char buffer with underflow check.
class SPSOutputBuffer
Output char buffer with overflow check.
class SPSSequence
SPS tag type for sequences.
class SPSSerializationTraits
Specialize to describe how to serialize/deserialize to/from the given concrete type.
class SPSSerializationTraits< SPSEmpty, SPSEmpty >
Serialization for SPSEmpty type.
class SPSSerializationTraits< SPSError, detail::SPSSerializableError >
Serialize to a SPSError from a detail::SPSSerializableError.
class SPSSerializationTraits< SPSExecutorAddress, ExecutorAddress >
SPS serializatior for ExecutorAddress.
class SPSSerializationTraits< SPSExecutorAddress, uint64_t >
class SPSSerializationTraits< SPSExecutorAddressRange, ExecutorAddressRange >
Serialization traits for address ranges.
class SPSSerializationTraits< SPSExpected< SPSTagT >, detail::SPSSerializableError >
Serialize to a SPSExpected<SPSTagT> from a detail::SPSSerializableError.
class SPSSerializationTraits< SPSExpected< SPSTagT >, detail::SPSSerializableExpected< T > >
Serialize to a SPSExpected<SPSTagT> from a detail::SPSSerializableExpected<T>.
class SPSSerializationTraits< SPSExpected< SPSTagT >, T >
Serialize to a SPSExpected<SPSTagT> from a T.
class SPSSerializationTraits< SPSMachOJITDylibDeinitializers, MachOJITDylibDeinitializers >
class SPSSerializationTraits< SPSMachOJITDylibInitializers, MachOJITDylibInitializers >
Serialization traits for MachOJITDylibInitializers.
class SPSSerializationTraits< SPSMachOPerObjectSectionsToRegister, MachOPerObjectSectionsToRegister >
class SPSSerializationTraits< SPSSequence< SPSElementTagT >, SequenceT, std::enable_if_t< TrivialSPSSequenceSerialization< SPSElementTagT, SequenceT >::available > >
'Trivial' sequence serialization: Sequence is serialized as a uint64_t size followed by a for-earch loop over the elements of the sequence to serialize each of them.
class SPSSerializationTraits< SPSSequence< SPSTuple< SPSString, SPSValueT > >, StringMap< ValueT > >
class SPSSerializationTraits< SPSString, StringRef >
Serialization for StringRefs.
class SPSSerializationTraits< SPSTagT, SPSTagT, std::enable_if_t< std::is_same< SPSTagT, bool >::value||std::is_same< SPSTagT, char >::value||std::is_same< SPSTagT, int8_t >::value||std::is_same< SPSTagT, int16_t >::value||std::is_same< SPSTagT, int32_t >::value||std::is_same< SPSTagT, int64_t >::value||std::is_same< SPSTagT, uint8_t >::value||std::is_same< SPSTagT, uint16_t >::value||std::is_same< SPSTagT, uint32_t >::value||std::is_same< SPSTagT, uint64_t >::value > >
SPS serialization for integral types, bool, and char.
class SPSSerializationTraits< SPSTuple< SPSTagT1, SPSTagT2 >, std::pair< T1, T2 > >
SPSTuple serialization for std::pair.
class SPSTuple
SPS tag type for tuples.
class TrivialSPSSequenceDeserialization
Specialize this to implement 'trivial' sequence deserialization for a concrete sequence type.
class TrivialSPSSequenceDeserialization< char, std::string >
Trivial SPSSequence<char> -> std::string deserialization.
class TrivialSPSSequenceDeserialization< SPSElementTagT, std::vector< T > >
Trivial SPSSequence<SPSElementTagT> -> std::vector<T> deserialization.
class TrivialSPSSequenceSerialization
Specialize this to implement 'trivial' sequence serialization for a concrete sequence type.
class TrivialSPSSequenceSerialization< char, std::string >
Trivial std::string -> SPSSequence<char> serialization.
class TrivialSPSSequenceSerialization< SPSElementTagT, std::vector< T > >
Trivial std::vector<T> -> SPSSequence<SPSElementTagT> serialization.
class WrapperFunction
class WrapperFunction< SPSRetTagT(SPSTagTs...)>
class WrapperFunction< void(SPSTagTs...)>
class WrapperFunctionResult
C++ wrapper function result: Same as CWrapperFunctionResult but auto-releases memory.
Typedefs
using SPSMachOPerObjectSectionsToRegister = SPSTuple< SPSExecutorAddressRange, SPSExecutorAddressRange >
using SPSNamedExecutorAddressRangeSequenceMap = SPSSequence< SPSTuple< SPSString, SPSExecutorAddressRangeSequence > >
using SPSMachOJITDylibInitializers = SPSTuple< SPSString, SPSExecutorAddress, SPSExecutorAddress, SPSNamedExecutorAddressRangeSequenceMap >
using SPSMachOJITDylibInitializerSequence = SPSSequence< SPSMachOJITDylibInitializers >
using SPSMachOJITDylibDeinitializers = SPSEmpty
using SPSMachOJITDylibDeinitializerSequence = SPSSequence< SPSMachOJITDylibDeinitializers >
using SPSExecutorAddressRange = SPSTuple< SPSExecutorAddress, SPSExecutorAddress >
using SPSExecutorAddressRangeSequence = SPSSequence< SPSExecutorAddressRange >
using SPSString = SPSSequence< char >
SPS tag type for strings, which are equivalent to sequences of chars.
template<typename SPSTagT1 , typename SPSTagT2 >
using SPSMap = SPSSequence< SPSTuple< SPSTagT1, SPSTagT2 > >
SPS tag type for maps.
Functions
template<typename Func , typename RPCEndpointT >
RPCAsyncDispatch< RPCEndpointT, Func > rpcAsyncDispatch (RPCEndpointT &Endpoint)
Construct an asynchronous dispatcher from an RPC endpoint and a Func.
template<typename OStream >
OStream & operator<< (OStream &OS, const SerializationTypeNameSequence<> &V)
Render an empty TypeNameSequence to an ostream.
template<typename OStream , typename ArgT >
OStream & operator<< (OStream &OS, const SerializationTypeNameSequence< ArgT > &V)
Render a TypeNameSequence of a single type to an ostream.
template<typename OStream , typename ArgT1 , typename ArgT2 , typename... ArgTs>
OStream & operator<< (OStream &OS, const SerializationTypeNameSequence< ArgT1, ArgT2, ArgTs... > &V)
Render a TypeNameSequence of more than one type to an ostream.
template<typename ChannelT , typename... ArgTs>
Error serializeSeq (ChannelT &C, ArgTs &&...Args)
template<typename ChannelT , typename... ArgTs>
Error deserializeSeq (ChannelT &C, ArgTs &...Args)
template<typename ChannelT , typename ErrorInfoT , typename SerializeFtor , typename DeserializeFtor >
void registerErrorSerialization (std::string Name, SerializeFtor &&Serialize, DeserializeFtor &&Deserialize)
Registers a serializer and deserializer for the given error type on the given channel type.
template<typename ChannelT >
void registerStringError ()
Registers serialization/deserialization for StringError.
Typedef Documentation
SPSExecutorAddressRange
using llvm::orc::shared::SPSExecutorAddressRange = typedef SPSTuple<SPSExecutorAddress, SPSExecutorAddress>
Definition at line 173 of file ExecutorAddress.h.
SPSExecutorAddressRangeSequence
using llvm::orc::shared::SPSExecutorAddressRangeSequence = typedef SPSSequence<SPSExecutorAddressRange>
Definition at line 197 of file ExecutorAddress.h.
SPSMachOJITDylibDeinitializers
using llvm::orc::shared::SPSMachOJITDylibDeinitializers = typedef SPSEmpty
Definition at line 314 of file MachOPlatform.h.
SPSMachOJITDylibDeinitializerSequence
using llvm::orc::shared::SPSMachOJITDylibDeinitializerSequence = typedef SPSSequence<SPSMachOJITDylibDeinitializers>
Definition at line 316 of file MachOPlatform.h.
SPSMachOJITDylibInitializers
using llvm::orc::shared::SPSMachOJITDylibInitializers = typedef SPSTuple<SPSString, SPSExecutorAddress, SPSExecutorAddress, SPSNamedExecutorAddressRangeSequenceMap>
Definition at line 281 of file MachOPlatform.h.
SPSMachOJITDylibInitializerSequence
using llvm::orc::shared::SPSMachOJITDylibInitializerSequence = typedef SPSSequence<SPSMachOJITDylibInitializers>
Definition at line 285 of file MachOPlatform.h.
SPSMachOPerObjectSectionsToRegister
using llvm::orc::shared::SPSMachOPerObjectSectionsToRegister = typedef SPSTuple<SPSExecutorAddressRange, SPSExecutorAddressRange>
Definition at line 252 of file MachOPlatform.h.
SPSMap
template<typename SPSTagT1 , typename SPSTagT2 > using llvm::orc::shared::SPSMap = typedef SPSSequence<SPSTuple<SPSTagT1, SPSTagT2> >
SPS tag type for maps.
SPS maps are just sequences of (Key, Value) tuples.
Definition at line 207 of file SimplePackedSerialization.h.
SPSNamedExecutorAddressRangeSequenceMap
using llvm::orc::shared::SPSNamedExecutorAddressRangeSequenceMap = typedef SPSSequence<SPSTuple<SPSString, SPSExecutorAddressRangeSequence> >
Definition at line 278 of file MachOPlatform.h.
SPSString
using llvm::orc::shared::SPSString = typedef SPSSequence<char>
SPS tag type for strings, which are equivalent to sequences of chars.
Definition at line 194 of file SimplePackedSerialization.h.
Function Documentation
deserializeSeq()
template<typename ChannelT , typename... ArgTs> Error llvm::orc::shared::deserializeSeq (ChannelT & C, ArgTs &... Args)
Definition at line 313 of file Serialization.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args.
Referenced by llvm::orc::shared::SerializationTraits< ChannelT, orcrpctpc::ExecutorProcessInfo >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, orcrpctpc::ReleaseOrFinalizeMemRequestElement >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, orcrpctpc::ReserveMemRequestElement >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, orcrpctpc::ReserveMemResultElement >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, remote::DirectBufferWriter, remote::DirectBufferWriter, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >::deserialize(), and llvm::orc::shared::SerializationTraits< ChannelT, WriteT, WriteT, std::enable_if_t< std::is_same< WriteT, tpctypes::UInt8Write >::value||std::is_same< WriteT, tpctypes::UInt16Write >::value||std::is_same< WriteT, tpctypes::UInt32Write >::value||std::is_same< WriteT, tpctypes::UInt64Write >::value > >::deserialize().
operator<<() [1/3]
template<typename OStream , typename ArgT > OStream& llvm::orc::shared::operator<< (OStream & OS, const SerializationTypeNameSequence< ArgT > & V)
Render a TypeNameSequence of a single type to an ostream.
Definition at line 41 of file Serialization.h.
References getName().
operator<<() [2/3]
template<typename OStream , typename ArgT1 , typename ArgT2 , typename... ArgTs> OStream& llvm::orc::shared::operator<< (OStream & OS, const SerializationTypeNameSequence< ArgT1, ArgT2, ArgTs... > & V)
Render a TypeNameSequence of more than one type to an ostream.
Definition at line 48 of file Serialization.h.
References getName().
operator<<() [3/3]
template<typename OStream > OStream& llvm::orc::shared::operator<< (OStream & OS, const SerializationTypeNameSequence<> & V)
Render an empty TypeNameSequence to an ostream.
Definition at line 35 of file Serialization.h.
registerErrorSerialization()
template<typename ChannelT , typename ErrorInfoT , typename SerializeFtor , typename DeserializeFtor > void llvm::orc::shared::registerErrorSerialization (std::string Name, SerializeFtor && Serialize, DeserializeFtor && Deserialize)
Registers a serializer and deserializer for the given error type on the given channel type.
Definition at line 429 of file Serialization.h.
References move.
registerStringError()
template<typename ChannelT > void llvm::orc::shared::registerStringError ()
Registers serialization/deserialization for StringError.
Definition at line 437 of file Serialization.h.
References llvm::StringError::getMessage(), and serializeSeq().
rpcAsyncDispatch()
template<typename Func , typename RPCEndpointT > RPCAsyncDispatch<RPCEndpointT, Func> llvm::orc::shared::rpcAsyncDispatch (RPCEndpointT & Endpoint)
Construct an asynchronous dispatcher from an RPC endpoint and a Func.
Definition at line 1552 of file RPCUtils.h.
serializeSeq()
template<typename ChannelT , typename... ArgTs> Error llvm::orc::shared::serializeSeq (ChannelT & C, ArgTs &&... Args)
Definition at line 307 of file Serialization.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args.
Referenced by registerStringError(), llvm::orc::shared::SerializationTraits< ChannelT, JITSymbolFlags >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, orcrpctpc::ExecutorProcessInfo >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, orcrpctpc::ReleaseOrFinalizeMemRequestElement >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, orcrpctpc::ReserveMemRequestElement >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, orcrpctpc::ReserveMemResultElement >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, remote::DirectBufferWriter, remote::DirectBufferWriter, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, WriteT, WriteT, std::enable_if_t< std::is_same< WriteT, tpctypes::UInt8Write >::value||std::is_same< WriteT, tpctypes::UInt16Write >::value||std::is_same< WriteT, tpctypes::UInt32Write >::value||std::is_same< WriteT, tpctypes::UInt64Write >::value > >::serialize(), and llvm::orc::shared::SerializationTraits< ChannelT, Expected< T1 >, T2 >::serialize().