LLVM: llvm::APIntOps Namespace Reference
llvm::APIntOps Namespace Reference
Functions
const APInt & smin (const APInt &A, const APInt &B)
Determine the smaller of two APInts considered to be signed.
const APInt & smax (const APInt &A, const APInt &B)
Determine the larger of two APInts considered to be signed.
const APInt & umin (const APInt &A, const APInt &B)
Determine the smaller of two APInts considered to be unsigned.
const APInt & umax (const APInt &A, const APInt &B)
Determine the larger of two APInts considered to be unsigned.
APInt GreatestCommonDivisor (APInt A, APInt B)
Compute GCD of two unsigned APInt values.
double RoundAPIntToDouble (const APInt &APIVal)
Converts the given APInt to a double value.
double RoundSignedAPIntToDouble (const APInt &APIVal)
Converts the given APInt to a double value.
float RoundAPIntToFloat (const APInt &APIVal)
Converts the given APInt to a float value.
float RoundSignedAPIntToFloat (const APInt &APIVal)
Converts the given APInt to a float value.
APInt RoundDoubleToAPInt (double Double, unsigned width)
Converts the given double value into a APInt.
APInt RoundFloatToAPInt (float Float, unsigned width)
Converts a float value into a APInt.
APInt RoundingUDiv (const APInt &A, const APInt &B, APInt::Rounding RM)
Return A unsign-divided by B, rounded by the given rounding mode.
APInt RoundingSDiv (const APInt &A, const APInt &B, APInt::Rounding RM)
Return A sign-divided by B, rounded by the given rounding mode.
Optional< APInt > SolveQuadraticEquationWrap (APInt A, APInt B, APInt C, unsigned RangeWidth)
Let q(n) = An^2 + Bn + C, and BW = bit width of the value range (e.g.
Optional< unsigned > GetMostSignificantDifferentBit (const APInt &A, const APInt &B)
Compare two values, and if they are different, return the position of the most significant bit that is different in the values.
Function Documentation
GetMostSignificantDifferentBit()
Optional< unsigned > llvm::APIntOps::GetMostSignificantDifferentBit (const APInt & A, const APInt & B)
Compare two values, and if they are different, return the position of the most significant bit that is different in the values.
Definition at line 3051 of file APInt.cpp.
References A, assert(), B, llvm::countLeadingZeros(), and llvm::None.
GreatestCommonDivisor()
APInt llvm::APIntOps::GreatestCommonDivisor (APInt A, APInt B)
Compute GCD of two unsigned APInt values.
This function returns the greatest common divisor of the two APInt values using Stein's algorithm.
Returns
the greatest common divisor of A and B.
Definition at line 723 of file APInt.cpp.
References A, and B.
Referenced by llvm::ConstraintSystem::addVariableRow(), and gcd().
RoundAPIntToDouble()
double llvm::APIntOps::RoundAPIntToDouble (const APInt & APIVal) inline
Converts the given APInt to a double value.
Treats the APInt as an unsigned value for conversion purposes.
Definition at line 2198 of file APInt.h.
References llvm::APInt::roundToDouble().
Referenced by RoundAPIntToFloat().
RoundAPIntToFloat()
float llvm::APIntOps::RoundAPIntToFloat (const APInt & APIVal) inline
Converts the given APInt to a float value.
Definition at line 2210 of file APInt.h.
References RoundAPIntToDouble().
RoundDoubleToAPInt()
APInt llvm::APIntOps::RoundDoubleToAPInt (double Double, unsigned width)
Converts the given double value into a APInt.
This function convert a double value to an APInt value.
Definition at line 766 of file APInt.cpp.
References llvm::pdb::Double, and I.
Referenced by llvm::ExecutionEngine::getConstantValue(), and RoundFloatToAPInt().
RoundFloatToAPInt()
APInt llvm::APIntOps::RoundFloatToAPInt (float Float, unsigned width) inline
Converts a float value into a APInt.
Converts a float value into an APInt value.
Definition at line 2229 of file APInt.h.
References llvm::NVPTX::PTXLdStInstCode::Float, and RoundDoubleToAPInt().
Referenced by llvm::ExecutionEngine::getConstantValue().
RoundingSDiv()
APInt llvm::APIntOps::RoundingSDiv (const APInt & A, const APInt & B, APInt::Rounding RM)
Return A sign-divided by B, rounded by the given rounding mode.
Definition at line 2830 of file APInt.cpp.
References A, B, llvm::APInt::DOWN, llvm::APInt::isNegative(), llvm_unreachable, llvm::AArch64::RM, llvm::APInt::sdivrem(), llvm::APInt::TOWARD_ZERO, and llvm::APInt::UP.
Referenced by makeExactMulNSWRegion().
RoundingUDiv()
APInt llvm::APIntOps::RoundingUDiv (const APInt & A, const APInt & B, APInt::Rounding RM)
Return A unsign-divided by B, rounded by the given rounding mode.
Definition at line 2812 of file APInt.cpp.
References A, B, llvm::APInt::DOWN, llvm_unreachable, llvm::AArch64::RM, llvm::APInt::TOWARD_ZERO, llvm::APInt::udivrem(), and llvm::APInt::UP.
Referenced by makeExactMulNUWRegion().
RoundSignedAPIntToDouble()
double llvm::APIntOps::RoundSignedAPIntToDouble (const APInt & APIVal) inline
Converts the given APInt to a double value.
Treats the APInt as a signed value for conversion purposes.
Definition at line 2205 of file APInt.h.
References llvm::APInt::signedRoundToDouble().
RoundSignedAPIntToFloat()
float llvm::APIntOps::RoundSignedAPIntToFloat (const APInt & APIVal) inline
Converts the given APInt to a float value.
Treats the APInt as a signed value for conversion purposes.
Definition at line 2217 of file APInt.h.
References llvm::APInt::signedRoundToDouble().
smax()
const APInt& llvm::APIntOps::smax (const APInt & A, const APInt & B) inline
Determine the larger of two APInts considered to be signed.
Definition at line 2173 of file APInt.h.
References A, and B.
Referenced by llvm::canConstantFoldCallTo(), llvm::canConvertToMinOrMaxIntrinsic(), llvm::MinMaxIntrinsic::classof(), computeKnownBitsFromOperator(), foldClampRangeOfTwo(), llvm::ARMTTIImpl::getCmpSelInstrCost(), llvm::AArch64TTIImpl::getIntrinsicInstrCost(), llvm::ARMTTIImpl::getIntrinsicInstrCost(), llvm::getInverseMinMaxIntrinsic(), getMaxMinLimit(), getMaxMinPredicate(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::MinMaxIntrinsic::getPredicate(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getTypeBasedIntrinsicInstrCost(), llvm::X86TTIImpl::getTypeBasedIntrinsicInstrCost(), llvm::ConstantRange::intrinsic(), llvm::IntrinsicInst::isCommutative(), llvm::ConstantRange::isIntrinsicSupported(), llvm::isTriviallyVectorizable(), llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t, Commutable >::match(), setLimitsForIntrinsic(), simplifyBinaryIntrinsic(), llvm::ConstantRange::smax(), and llvm::InstCombinerImpl::visitCallInst().
smin()
const APInt& llvm::APIntOps::smin (const APInt & A, const APInt & B) inline
Determine the smaller of two APInts considered to be signed.
Definition at line 2168 of file APInt.h.
References A, and B.
Referenced by llvm::canConstantFoldCallTo(), llvm::canConvertToMinOrMaxIntrinsic(), llvm::MinMaxIntrinsic::classof(), computeKnownBitsFromOperator(), foldClampRangeOfTwo(), llvm::ARMTTIImpl::getCmpSelInstrCost(), llvm::AArch64TTIImpl::getIntrinsicInstrCost(), llvm::ARMTTIImpl::getIntrinsicInstrCost(), llvm::getInverseMinMaxIntrinsic(), getMaxMinLimit(), getMaxMinPredicate(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::MinMaxIntrinsic::getPredicate(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getTypeBasedIntrinsicInstrCost(), llvm::X86TTIImpl::getTypeBasedIntrinsicInstrCost(), llvm::ConstantRange::intrinsic(), llvm::IntrinsicInst::isCommutative(), llvm::ConstantRange::isIntrinsicSupported(), llvm::isTriviallyVectorizable(), llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t, Commutable >::match(), setLimitsForIntrinsic(), simplifyBinaryIntrinsic(), llvm::ConstantRange::smin(), and llvm::InstCombinerImpl::visitCallInst().
SolveQuadraticEquationWrap()
Optional< APInt > llvm::APIntOps::SolveQuadraticEquationWrap (APInt A, APInt B, APInt C, unsigned RangeWidth)
Let q(n) = An^2 + Bn + C, and BW = bit width of the value range (e.g.
32 for i32). This function finds the smallest number n, such that (a) n >= 0 and q(n) = 0, or (b) n >= 1 and q(n-1) and q(n), when evaluated in the set of all integers, belong to two different intervals [Rk, Rk+R), where R = 2^BW, and k is an integer. The idea here is to find when q(n) "overflows" 2^BW, while at the same time "allowing" subtraction. In unsigned modulo arithmetic a subtraction (treated as addition of negated numbers) would always count as an overflow, but here we want to allow values to decrease and increase as long as they are within the same interval. Specifically, adding of two negative numbers should not cause an overflow (as long as the magnitude does not exceed the bit width). On the other hand, given a positive number, adding a negative number to it can give a negative result, which would cause the value to go from [-2^BW, 0) to [0, 2^BW). In that sense, zero is treated as a special case of an overflow.
This function returns None if after finding k that minimizes the positive solution to q(n) = kR, both solutions are contained between two consecutive integers.
There are cases where q(n) > T, and q(n+1) < T (assuming evaluation in arithmetic modulo 2^BW, and treating the values as signed) by the virtue of signed overflow. This function will not find such an n, however it may find a value of n satisfying the inequalities due to an unsigned overflow (if the values are treated as unsigned). To find a solution for a signed overflow, treat it as a problem of finding an unsigned overflow with a range with of BW-1.
The returned value may have a different bit width from the input coefficients.
Definition at line 2861 of file APInt.cpp.
References A, llvm::APInt::abs(), assert(), B, D, llvm::dbgs(), llvm::APInt::getOneBitSet(), llvm::APInt::isNegative(), llvm::APInt::isNullValue(), LLVM_DEBUG, llvm::None, llvm::RISCVFenceField::R, llvm::APInt::sdivrem(), llvm::APInt::sgt(), llvm::APInt::srem(), T, llvm::APInt::udiv(), llvm::APInt::urem(), and X.
Referenced by SolveQuadraticAddRecExact(), and SolveQuadraticAddRecRange().
umax()
const APInt& llvm::APIntOps::umax (const APInt & A, const APInt & B) inline
Determine the larger of two APInts considered to be unsigned.
Definition at line 2183 of file APInt.h.
References A, and B.
Referenced by llvm::ConstantRange::abs(), llvm::ConstantRange::binaryOr(), llvm::canConstantFoldCallTo(), llvm::canConvertToMinOrMaxIntrinsic(), llvm::MinMaxIntrinsic::classof(), computeKnownBitsFromOperator(), foldClampRangeOfTwo(), llvm::ARMTTIImpl::getCmpSelInstrCost(), llvm::AArch64TTIImpl::getIntrinsicInstrCost(), llvm::ARMTTIImpl::getIntrinsicInstrCost(), llvm::getInverseMinMaxIntrinsic(), getMaxMinLimit(), getMaxMinPredicate(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::MinMaxIntrinsic::getPredicate(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getTypeBasedIntrinsicInstrCost(), llvm::X86TTIImpl::getTypeBasedIntrinsicInstrCost(), llvm::ConstantRange::intrinsic(), llvm::IntrinsicInst::isCommutative(), llvm::ConstantRange::isIntrinsicSupported(), llvm::isTriviallyVectorizable(), llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t, Commutable >::match(), setLimitsForIntrinsic(), simplifyBinaryIntrinsic(), llvm::ConstantRange::srem(), llvm::ConstantRange::umax(), llvm::InstCombinerImpl::visitAdd(), and llvm::InstCombinerImpl::visitCallInst().
umin()
const APInt& llvm::APIntOps::umin (const APInt & A, const APInt & B) inline
Determine the smaller of two APInts considered to be unsigned.
Definition at line 2178 of file APInt.h.
References A, and B.
Referenced by llvm::ConstantRange::abs(), llvm::ConstantRange::binaryAnd(), llvm::canConstantFoldCallTo(), llvm::canConvertToMinOrMaxIntrinsic(), llvm::MinMaxIntrinsic::classof(), computeKnownBitsFromOperator(), foldClampRangeOfTwo(), foldSignedTruncationCheck(), llvm::ARMTTIImpl::getCmpSelInstrCost(), llvm::AArch64TTIImpl::getIntrinsicInstrCost(), llvm::ARMTTIImpl::getIntrinsicInstrCost(), llvm::getInverseMinMaxIntrinsic(), getMaxMinLimit(), getMaxMinPredicate(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::MinMaxIntrinsic::getPredicate(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getTypeBasedIntrinsicInstrCost(), llvm::X86TTIImpl::getTypeBasedIntrinsicInstrCost(), llvm::ConstantRange::intrinsic(), llvm::IntrinsicInst::isCommutative(), llvm::ConstantRange::isIntrinsicSupported(), llvm::isTriviallyVectorizable(), llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t, Commutable >::match(), setLimitsForIntrinsic(), simplifyBinaryIntrinsic(), llvm::ConstantRange::srem(), llvm::ConstantRange::umin(), llvm::ConstantRange::urem(), llvm::InstCombinerImpl::visitCallInst(), and llvm::InstCombinerImpl::visitSub().