LLVM: include/llvm-c/OrcEE.h File Reference
OrcEE.h File Reference
#include "llvm-c/Error.h"
#include "llvm-c/ExecutionEngine.h"
#include "llvm-c/Orc.h"
#include "llvm-c/TargetMachine.h"
#include "llvm-c/Types.h"
Functions
LLVM_C_EXTERN_C_BEGIN LLVMOrcObjectLayerRef LLVMOrcCreateRTDyldObjectLinkingLayerWithSectionMemoryManager (LLVMOrcExecutionSessionRef ES)
Create a RTDyldObjectLinkingLayer instance using the standard SectionMemoryManager for memory management.
void LLVMOrcRTDyldObjectLinkingLayerRegisterJITEventListener (LLVMOrcObjectLayerRef RTDyldObjLinkingLayer, LLVMJITEventListenerRef Listener)
Add the given listener to the given RTDyldObjectLinkingLayer.
Function Documentation
LLVMOrcCreateRTDyldObjectLinkingLayerWithSectionMemoryManager()
LLVM_C_EXTERN_C_BEGIN LLVMOrcObjectLayerRef LLVMOrcCreateRTDyldObjectLinkingLayerWithSectionMemoryManager (LLVMOrcExecutionSessionRef ES)
Create a RTDyldObjectLinkingLayer instance using the standard SectionMemoryManager for memory management.
Definition at line 913 of file OrcV2CBindings.cpp.
References assert(), llvm::unwrap(), and llvm::wrap().
LLVMOrcRTDyldObjectLinkingLayerRegisterJITEventListener()
void LLVMOrcRTDyldObjectLinkingLayerRegisterJITEventListener (LLVMOrcObjectLayerRef RTDyldObjLinkingLayer, LLVMJITEventListenerRef Listener)
Add the given listener to the given RTDyldObjectLinkingLayer.
Note: Layer must be an RTDyldObjectLinkingLayer instance or behavior is undefined.
Definition at line 920 of file OrcV2CBindings.cpp.
References assert(), and llvm::unwrap().