LLVM: lib/ExecutionEngine/Orc/TargetProcess/RegisterEHFrames.cpp File Reference
RegisterEHFrames.cpp File Reference
#include "llvm/ExecutionEngine/Orc/TargetProcess/RegisterEHFrames.h"
#include "llvm/Config/config.h"
#include "llvm/ExecutionEngine/JITSymbol.h"
#include "llvm/Support/BinaryStreamReader.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/DynamicLibrary.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Support/FormatVariadic.h"
Namespaces
llvm
---------------------— PointerInfo ------------------------------------—
llvm::orc
Macros
#define DEBUG_TYPE "orc"
Functions
void llvm::orc::__register_frame (const void *)
void llvm::orc::__deregister_frame (const void *)
Error llvm::orc::registerFrameWrapper (const void *P)
Error llvm::orc::deregisterFrameWrapper (const void *P)
Error llvm::orc::registerEHFrameSection (const void *EHFrameSectionAddr, size_t EHFrameSectionSize)
Register frames in the given eh-frame section with libunwind.
Error llvm::orc::deregisterEHFrameSection (const void *EHFrameSectionAddr, size_t EHFrameSectionSize)
Unregister frames in the given eh-frame section with libunwind.
static Error registerEHFrameWrapper (JITTargetAddress Addr, uint64_t Size)
static Error deregisterEHFrameWrapper (JITTargetAddress Addr, uint64_t Size)
orc::shared::detail::CWrapperFunctionResult llvm_orc_registerEHFrameSectionWrapper (const char *Data, uint64_t Size)
orc::shared::detail::CWrapperFunctionResult llvm_orc_deregisterEHFrameSectionWrapper (const char *Data, uint64_t Size)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "orc"
Definition at line 22 of file RegisterEHFrames.cpp.
Function Documentation
deregisterEHFrameWrapper()
static Error deregisterEHFrameWrapper (JITTargetAddress Addr, uint64_t Size) static
Definition at line 163 of file RegisterEHFrames.cpp.
References Addr, llvm::orc::deregisterEHFrameSection(), and llvm::Check::Size.
Referenced by llvm_orc_deregisterEHFrameSectionWrapper().
llvm_orc_deregisterEHFrameSectionWrapper()
orc::shared::detail::CWrapperFunctionResult llvm_orc_deregisterEHFrameSectionWrapper (const char * Data, uint64_t Size)
Definition at line 176 of file RegisterEHFrames.cpp.
References llvm::Data, deregisterEHFrameWrapper(), handle, and llvm::Check::Size.
llvm_orc_registerEHFrameSectionWrapper()
orc::shared::detail::CWrapperFunctionResult llvm_orc_registerEHFrameSectionWrapper (const char * Data, uint64_t Size)
Definition at line 169 of file RegisterEHFrames.cpp.
References llvm::Data, handle, registerEHFrameWrapper(), and llvm::Check::Size.
registerEHFrameWrapper()
static Error registerEHFrameWrapper (JITTargetAddress Addr, uint64_t Size) static
Definition at line 158 of file RegisterEHFrames.cpp.
References Addr, llvm::orc::registerEHFrameSection(), and llvm::Check::Size.
Referenced by llvm_orc_registerEHFrameSectionWrapper().