LLVM: lib/Transforms/Utils/RelLookupTableConverter.cpp File Reference
RelLookupTableConverter.cpp File Reference
#include "llvm/Transforms/Utils/RelLookupTableConverter.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
Functions
static bool shouldConvertToRelLookupTable (Module &M, GlobalVariable &GV)
static GlobalVariable * createRelLookupTable (Function &Func, GlobalVariable &LookupTable)
static void convertToRelLookupTable (GlobalVariable &LookupTable)
static bool convertToRelativeLookupTables (Module &M, function_ref< TargetTransformInfo &(Function &)> GetTTI)
Function Documentation
convertToRelativeLookupTables()
static bool convertToRelativeLookupTables (Module & M, function_ref< TargetTransformInfo &(Function &)> GetTTI) static
Definition at line 172 of file RelLookupTableConverter.cpp.
References convertToRelLookupTable(), E, llvm::GlobalVariable::eraseFromParent(), M, and shouldConvertToRelLookupTable().
Referenced by llvm::RelLookupTableConverterPass::run().
convertToRelLookupTable()
static void convertToRelLookupTable (GlobalVariable & LookupTable) static
Definition at line 127 of file RelLookupTableConverter.cpp.
References llvm::sampleprof::Base, BB, Builder, createRelLookupTable(), GEP, llvm::ConstantInt::get(), llvm::Intrinsic::getDeclaration(), llvm::GlobalValue::getParent(), Index, llvm::SPII::Load, M, Offset, and llvm::Value::use_begin().
Referenced by convertToRelativeLookupTables().
createRelLookupTable()
static GlobalVariable* createRelLookupTable (Function & Func, GlobalVariable & LookupTable) static
Definition at line 90 of file RelLookupTableConverter.cpp.
References llvm::sampleprof::Base, llvm::ConstantArray::get(), llvm::ArrayType::get(), llvm::GlobalValue::getAddressSpace(), llvm::GlobalVariable::getInitializer(), llvm::Type::getInt32Ty(), llvm::GlobalValue::getLinkage(), llvm::Value::getName(), llvm::ArrayType::getNumElements(), llvm::GlobalValue::getParent(), llvm::ConstantExpr::getPtrToInt(), llvm::ConstantExpr::getSub(), llvm::GlobalValue::getThreadLocalMode(), llvm::ConstantExpr::getTrunc(), llvm::ConstantArray::getType(), llvm::GlobalValue::Global, llvm::GlobalVariable::isConstant(), llvm::GlobalVariable::isExternallyInitialized(), M, llvm::User::operands(), llvm::GlobalObject::setAlignment(), llvm::GlobalVariable::setInitializer(), and llvm::GlobalValue::setUnnamedAddr().
Referenced by convertToRelLookupTable().
shouldConvertToRelLookupTable()
static bool shouldConvertToRelLookupTable (Module & M, GlobalVariable & GV) static
Definition at line 27 of file RelLookupTableConverter.cpp.
References DL, GEP, llvm::ArrayType::getElementType(), llvm::GlobalVariable::getInitializer(), llvm::ConstantArray::getType(), llvm::GlobalVariable::hasInitializer(), llvm::GlobalValue::hasLocalLinkage(), llvm::Value::hasOneUse(), llvm::GlobalVariable::isConstant(), llvm::IsConstantOffsetFromGlobal(), llvm::GlobalValue::isDSOLocal(), llvm::GlobalValue::isImplicitDSOLocal(), llvm::Type::isPointerTy(), llvm::SPII::Load, M, Offset, llvm::User::operands(), and llvm::Value::use_begin().
Referenced by convertToRelativeLookupTables().