LLVM: lib/Target/AMDGPU/SIFoldOperands.cpp File Reference
SIFoldOperands.cpp File Reference
#include "AMDGPU.h"
#include "GCNSubtarget.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "SIMachineFunctionInfo.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
Macros
#define DEBUG_TYPE "si-fold-operands"
Functions
static unsigned macToMad (unsigned Opc)
static bool isInlineConstantIfFolded (const SIInstrInfo *TII, const MachineInstr &UseMI, unsigned OpNo, const MachineOperand &OpToFold)
static bool frameIndexMayFold (const SIInstrInfo *TII, const MachineInstr &UseMI, int OpNo, const MachineOperand &OpToFold)
static bool updateOperand (FoldCandidate &Fold, const SIInstrInfo &TII, const TargetRegisterInfo &TRI, const GCNSubtarget &ST)
static bool isUseMIInFoldList (ArrayRef< FoldCandidate > FoldList, const MachineInstr *MI)
static void appendFoldCandidate (SmallVectorImpl< FoldCandidate > &FoldList, MachineInstr *MI, unsigned OpNo, MachineOperand *FoldOp, bool Commuted=false, int ShrinkOp=-1)
static bool tryAddToFoldList (SmallVectorImpl< FoldCandidate > &FoldList, MachineInstr *MI, unsigned OpNo, MachineOperand *OpToFold, const SIInstrInfo *TII)
static bool isUseSafeToFold (const SIInstrInfo *TII, const MachineInstr &MI, const MachineOperand &UseMO)
static bool getRegSeqInit (SmallVectorImpl< std::pair< MachineOperand *, unsigned >> &Defs, Register UseReg, uint8_t OpTy, const SIInstrInfo *TII, const MachineRegisterInfo &MRI)
static bool tryToFoldACImm (const SIInstrInfo *TII, const MachineOperand &OpToFold, MachineInstr *UseMI, unsigned UseOpIdx, SmallVectorImpl< FoldCandidate > &FoldList)
static bool evalBinaryInstruction (unsigned Opcode, int32_t &Result, uint32_t LHS, uint32_t RHS)
static unsigned getMovOpc (bool IsScalar)
static void stripExtraCopyOperands (MachineInstr &MI)
Remove any leftover implicit operands from mutating the instruction.
static void mutateCopyOp (MachineInstr &MI, const MCInstrDesc &NewDesc)
static MachineOperand * getImmOrMaterializedImm (MachineRegisterInfo &MRI, MachineOperand &Op)
static bool tryConstantFoldOp (MachineRegisterInfo &MRI, const SIInstrInfo *TII, MachineInstr *MI)
static int getOModValue (unsigned Opc, int64_t Val)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "si-fold-operands"
Definition at line 18 of file SIFoldOperands.cpp.
Function Documentation
appendFoldCandidate()
static void appendFoldCandidate (SmallVectorImpl< FoldCandidate > & FoldList, MachineInstr * MI, unsigned OpNo, MachineOperand * FoldOp, bool Commuted = false, int ShrinkOp = -1) static
Definition at line 333 of file SIFoldOperands.cpp.
References llvm::dbgs(), LLVM_DEBUG, and MI.
Referenced by tryAddToFoldList(), and tryToFoldACImm().
evalBinaryInstruction()
static bool evalBinaryInstruction (unsigned Opcode, int32_t & Result, uint32_t LHS, uint32_t RHS) static
Definition at line 941 of file SIFoldOperands.cpp.
Referenced by tryConstantFoldOp().
frameIndexMayFold()
static bool frameIndexMayFold (const SIInstrInfo * TII, const MachineInstr & UseMI, int OpNo, const MachineOperand & OpToFold) static
Definition at line 175 of file SIFoldOperands.cpp.
References llvm::AMDGPU::getNamedOperandIdx(), llvm::MachineOperand::isFI(), TII, and UseMI.
getImmOrMaterializedImm()
static MachineOperand* getImmOrMaterializedImm (MachineRegisterInfo & MRI, MachineOperand & Op) static
Definition at line 1029 of file SIFoldOperands.cpp.
References llvm::tgtok::Def, llvm::MachineRegisterInfo::getVRegDef(), llvm::MachineOperand::isImm(), and MRI.
Referenced by tryConstantFoldOp().
getMovOpc()
static unsigned getMovOpc (bool IsScalar) static
Definition at line 1007 of file SIFoldOperands.cpp.
Referenced by tryConstantFoldOp().
getOModValue()
static int getOModValue (unsigned Opc, int64_t Val) static
Definition at line 1394 of file SIFoldOperands.cpp.
References llvm::SIOutMods::DIV2, llvm_unreachable, llvm::SIOutMods::MUL2, llvm::SIOutMods::MUL4, and llvm::SIOutMods::NONE.
getRegSeqInit()
static bool getRegSeqInit (SmallVectorImpl< std::pair< MachineOperand *, unsigned >> & Defs, Register UseReg, uint8_t OpTy, const SIInstrInfo * TII, const MachineRegisterInfo & MRI) static
Definition at line 497 of file SIFoldOperands.cpp.
References assert(), llvm::tgtok::Def, E, llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), llvm::MachineRegisterInfo::getVRegDef(), I, llvm::MachineOperand::isReg(), llvm::Register::isVirtual(), MRI, TII, and UseReg().
Referenced by tryToFoldACImm().
isInlineConstantIfFolded()
static bool isInlineConstantIfFolded (const SIInstrInfo * TII, const MachineInstr & UseMI, unsigned OpNo, const MachineOperand & OpToFold) static
Definition at line 151 of file SIFoldOperands.cpp.
References llvm::AMDGPU::getNamedOperandIdx(), macToMad(), llvm::MCOperandInfo::OperandType, llvm::MCInstrDesc::OpInfo, TII, and UseMI.
isUseMIInFoldList()
static bool isUseMIInFoldList (ArrayRef< FoldCandidate > FoldList, const MachineInstr * MI) static
Definition at line 324 of file SIFoldOperands.cpp.
References MI.
Referenced by tryAddToFoldList(), and tryToFoldACImm().
isUseSafeToFold()
static bool isUseSafeToFold (const SIInstrInfo * TII, const MachineInstr & MI, const MachineOperand & UseMO) static
Definition at line 476 of file SIFoldOperands.cpp.
References llvm::MachineOperand::isUndef(), llvm::M0(), MI, and TII.
macToMad()
static unsigned macToMad (unsigned Opc) static
Definition at line 131 of file SIFoldOperands.cpp.
Referenced by isInlineConstantIfFolded(), and tryAddToFoldList().
mutateCopyOp()
static void mutateCopyOp (MachineInstr & MI, const MCInstrDesc & NewDesc) static
Definition at line 1024 of file SIFoldOperands.cpp.
References MI, and stripExtraCopyOperands().
Referenced by tryConstantFoldOp().
stripExtraCopyOperands()
static void stripExtraCopyOperands (MachineInstr & MI) static
Remove any leftover implicit operands from mutating the instruction.
e.g. if we replace an s_and_b32 with a copy, we don't need the implicit scc def anymore.
Definition at line 1014 of file SIFoldOperands.cpp.
References llvm::MCInstrDesc::getNumImplicitDefs(), llvm::MCInstrDesc::getNumImplicitUses(), llvm::MCInstrDesc::getNumOperands(), I, and MI.
Referenced by mutateCopyOp(), and tryConstantFoldOp().
tryAddToFoldList()
static bool tryAddToFoldList (SmallVectorImpl< FoldCandidate > & FoldList, MachineInstr * MI, unsigned OpNo, MachineOperand * OpToFold, const SIInstrInfo * TII) static
Definition at line 346 of file SIFoldOperands.cpp.
References appendFoldCandidate(), assert(), llvm::TargetInstrInfo::CommuteAnyOperandIndex, llvm::numbers::e, llvm::MCInstrDesc::getNumOperands(), llvm::MachineOperand::getReg(), llvm::AMDGPU::getVOPe32(), i, llvm::MachineOperand::isFI(), llvm::MachineOperand::isGlobal(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isReg(), isUseMIInFoldList(), macToMad(), MI, MRI, llvm::SIRegisterInfo::opCanUseInlineConstant(), llvm::MCOperandInfo::OperandType, llvm::MCInstrDesc::OpInfo, and TII.
tryConstantFoldOp()
static bool tryConstantFoldOp (MachineRegisterInfo & MRI, const SIInstrInfo * TII, MachineInstr * MI) static
Definition at line 1050 of file SIFoldOperands.cpp.
References evalBinaryInstruction(), llvm::MachineOperand::getImm(), getImmOrMaterializedImm(), getMovOpc(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MachineOperand::isImm(), MI, MRI, mutateCopyOp(), stripExtraCopyOperands(), std::swap(), TII, and TRI.
tryToFoldACImm()
static bool tryToFoldACImm (const SIInstrInfo * TII, const MachineOperand & OpToFold, MachineInstr * UseMI, unsigned UseOpIdx, SmallVectorImpl< FoldCandidate > & FoldList) static
Definition at line 530 of file SIFoldOperands.cpp.
References appendFoldCandidate(), llvm::MachineOperand::ChangeToImmediate(), llvm::tgtok::Def, E, llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), getRegSeqInit(), llvm::MachineOperand::getSubReg(), llvm::MachineRegisterInfo::getVRegDef(), I, llvm::MachineOperand::isImm(), llvm::MachineOperand::isReg(), isUseMIInFoldList(), llvm::Register::isVirtual(), MRI, llvm::AMDGPU::OPERAND_REG_INLINE_AC_FIRST, llvm::AMDGPU::OPERAND_REG_INLINE_AC_LAST, llvm::AMDGPU::OPERAND_REG_INLINE_C_FIRST, llvm::AMDGPU::OPERAND_REG_INLINE_C_LAST, llvm::MCOperandInfo::OperandType, llvm::MCInstrDesc::OpInfo, TII, UseMI, and UseReg().
updateOperand()
static bool updateOperand (FoldCandidate & Fold, const SIInstrInfo & TII, const TargetRegisterInfo & TRI, const GCNSubtarget & ST) static
Definition at line 202 of file SIFoldOperands.cpp.
References llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::MachineOperand::ChangeToFrameIndex(), llvm::MachineOperand::ChangeToGA(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineBasicBlock::computeRegisterLiveness(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::dbgs(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::MachineOperand::getSubReg(), I, llvm::MachineOperand::isDef(), llvm::AMDGPU::isFoldableLiteralV216(), llvm::SIInstrFlags::IsMAI, llvm::SIInstrFlags::IsPacked, llvm::MachineOperand::isReg(), llvm::isUInt< 16 >(), llvm::MachineOperand::isUndef(), llvm::RegState::Kill, LLVM_DEBUG, llvm::MachineBasicBlock::LQR_Dead, MBB, MI, Mod, MRI, llvm::SISrcMods::OP_SEL_0, llvm::SISrcMods::OP_SEL_1, llvm::AMDGPU::OPERAND_REG_IMM_V2FP16, llvm::AMDGPU::OPERAND_REG_IMM_V2INT16, llvm::AMDGPU::OPERAND_REG_INLINE_C_V2FP16, llvm::AMDGPU::OPERAND_REG_INLINE_C_V2INT16, llvm::MachineOperand::setIsUndef(), llvm::MachineOperand::setReg(), llvm::ARM_MB::ST, llvm::MachineOperand::substVirtReg(), TII, TRI, and llvm::MachineRegisterInfo::use_nodbg_empty().