LLVM: lib/Analysis/StackLifetime.cpp File Reference
StackLifetime.cpp File Reference
#include "llvm/Analysis/StackLifetime.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/AssemblyAnnotationWriter.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FormattedStream.h"
#include <algorithm>
#include <memory>
#include <tuple>
Classes
class llvm::StackLifetime::LifetimeAnnotationWriter
Macros
#define DEBUG_TYPE "stack-lifetime"
Functions
static const AllocaInst * findMatchingAlloca (const IntrinsicInst &II, const DataLayout &DL)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "stack-lifetime"
Definition at line 37 of file StackLifetime.cpp.
Function Documentation
findMatchingAlloca()
static const AllocaInst* findMatchingAlloca (const IntrinsicInst & II, const DataLayout & DL) static
Definition at line 69 of file StackLifetime.cpp.
References DL, llvm::findAllocaForValue(), llvm::AllocaInst::getAllocationSizeInBits(), llvm::CallBase::getArgOperand(), and llvm::Check::Size.