LLVM: llvm::MDNodeKeyImpl< DICompositeType > Struct Reference
llvm::MDNodeKeyImpl< DICompositeType > Struct Reference
#include "IR/LLVMContextImpl.h"
Public Member Functions
MDNodeKeyImpl (unsigned Tag, MDString *Name, Metadata *File, unsigned Line, Metadata *Scope, Metadata *BaseType, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, unsigned Flags, Metadata *Elements, unsigned RuntimeLang, Metadata *VTableHolder, Metadata *TemplateParams, MDString *Identifier, Metadata *Discriminator, Metadata *DataLocation, Metadata *Associated, Metadata *Allocated, Metadata *Rank)
MDNodeKeyImpl (const DICompositeType *N)
bool isKeyOf (const DICompositeType *RHS) const
unsigned getHashValue () const
Public Attributes
unsigned Tag
MDString * Name
Metadata * File
unsigned Line
Metadata * Scope
Metadata * BaseType
uint64_t SizeInBits
uint64_t OffsetInBits
uint32_t AlignInBits
unsigned Flags
Metadata * Elements
unsigned RuntimeLang
Metadata * VTableHolder
Metadata * TemplateParams
MDString * Identifier
Metadata * Discriminator
Metadata * DataLocation
Metadata * Associated
Metadata * Allocated
Metadata * Rank
Detailed Description
Definition at line 552 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeKeyImpl() [1/2]
llvm::MDNodeKeyImpl< DICompositeType >::MDNodeKeyImpl (unsigned Tag, MDString * Name, Metadata * File, unsigned Line, Metadata * Scope, Metadata * BaseType, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, unsigned Flags, Metadata * Elements, unsigned RuntimeLang, Metadata * VTableHolder, Metadata * TemplateParams, MDString * Identifier, Metadata * Discriminator, Metadata * DataLocation, Metadata * Associated, Metadata * Allocated, Metadata * Rank) inline
Definition at line 574 of file LLVMContextImpl.h.
MDNodeKeyImpl() [2/2]
llvm::MDNodeKeyImpl< DICompositeType >::MDNodeKeyImpl (const DICompositeType * N) inline
Definition at line 589 of file LLVMContextImpl.h.
Member Function Documentation
getHashValue()
unsigned llvm::MDNodeKeyImpl< DICompositeType >::getHashValue () const inline
Definition at line 621 of file LLVMContextImpl.h.
References File, and llvm::hash_combine().
isKeyOf()
bool llvm::MDNodeKeyImpl< DICompositeType >::isKeyOf (const DICompositeType * RHS) const inline
Definition at line 603 of file LLVMContextImpl.h.
References File, llvm::DIType::getAlignInBits(), llvm::DIType::getFlags(), llvm::DIType::getLine(), llvm::DIType::getOffsetInBits(), llvm::DICompositeType::getRawAllocated(), llvm::DICompositeType::getRawAssociated(), llvm::DICompositeType::getRawBaseType(), llvm::DICompositeType::getRawDataLocation(), llvm::DICompositeType::getRawDiscriminator(), llvm::DICompositeType::getRawElements(), llvm::DIScope::getRawFile(), llvm::DICompositeType::getRawIdentifier(), llvm::DIType::getRawName(), llvm::DICompositeType::getRawRank(), llvm::DIType::getRawScope(), llvm::DICompositeType::getRawTemplateParams(), llvm::DICompositeType::getRawVTableHolder(), llvm::DICompositeType::getRuntimeLang(), llvm::DIType::getSizeInBits(), llvm::DINode::getTag(), and llvm::object::Identifier.
Member Data Documentation
AlignInBits
uint32_t llvm::MDNodeKeyImpl< DICompositeType >::AlignInBits
Definition at line 561 of file LLVMContextImpl.h.
Allocated
Metadata* llvm::MDNodeKeyImpl< DICompositeType >::Allocated
Definition at line 571 of file LLVMContextImpl.h.
Associated
Metadata* llvm::MDNodeKeyImpl< DICompositeType >::Associated
Definition at line 570 of file LLVMContextImpl.h.
BaseType
Metadata* llvm::MDNodeKeyImpl< DICompositeType >::BaseType
Definition at line 558 of file LLVMContextImpl.h.
DataLocation
Metadata* llvm::MDNodeKeyImpl< DICompositeType >::DataLocation
Definition at line 569 of file LLVMContextImpl.h.
Discriminator
Metadata* llvm::MDNodeKeyImpl< DICompositeType >::Discriminator
Definition at line 568 of file LLVMContextImpl.h.
Elements
Metadata* llvm::MDNodeKeyImpl< DICompositeType >::Elements
Definition at line 563 of file LLVMContextImpl.h.
File
Metadata* llvm::MDNodeKeyImpl< DICompositeType >::File
Definition at line 555 of file LLVMContextImpl.h.
Flags
unsigned llvm::MDNodeKeyImpl< DICompositeType >::Flags
Definition at line 562 of file LLVMContextImpl.h.
Identifier
MDString* llvm::MDNodeKeyImpl< DICompositeType >::Identifier
Definition at line 567 of file LLVMContextImpl.h.
Line
unsigned llvm::MDNodeKeyImpl< DICompositeType >::Line
Definition at line 556 of file LLVMContextImpl.h.
Name
MDString* llvm::MDNodeKeyImpl< DICompositeType >::Name
Definition at line 554 of file LLVMContextImpl.h.
OffsetInBits
uint64_t llvm::MDNodeKeyImpl< DICompositeType >::OffsetInBits
Definition at line 560 of file LLVMContextImpl.h.
Rank
Metadata* llvm::MDNodeKeyImpl< DICompositeType >::Rank
Definition at line 572 of file LLVMContextImpl.h.
RuntimeLang
unsigned llvm::MDNodeKeyImpl< DICompositeType >::RuntimeLang
Definition at line 564 of file LLVMContextImpl.h.
Scope
Metadata* llvm::MDNodeKeyImpl< DICompositeType >::Scope
Definition at line 557 of file LLVMContextImpl.h.
SizeInBits
uint64_t llvm::MDNodeKeyImpl< DICompositeType >::SizeInBits
Definition at line 559 of file LLVMContextImpl.h.
Tag
unsigned llvm::MDNodeKeyImpl< DICompositeType >::Tag
Definition at line 553 of file LLVMContextImpl.h.
TemplateParams
Metadata* llvm::MDNodeKeyImpl< DICompositeType >::TemplateParams
Definition at line 566 of file LLVMContextImpl.h.
VTableHolder
Metadata* llvm::MDNodeKeyImpl< DICompositeType >::VTableHolder
Definition at line 565 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h