LLVM: AACaptureUseTracker Struct Reference
AACaptureUseTracker Struct Reference final
Attributor-aware capture tracker.
Public Member Functions
AACaptureUseTracker (Attributor &A, AANoCapture &NoCaptureAA, const AAIsDead &IsDeadAA, AANoCapture::StateType &State, SmallSetVector< Value *, 4 > &PotentialCopies, unsigned &RemainingUsesToExplore)
Create a capture tracker that can lookup in-flight abstract attributes through the Attributor A.
bool valueMayBeCaptured (const Value *V)
Determine if V maybe captured. Also updates the state!
void tooManyUses () override
See CaptureTracker::tooManyUses().
bool isDereferenceableOrNull (Value *O, const DataLayout &DL) override
isDereferenceableOrNull - Overload to allow clients with additional knowledge about pointer dereferenceability to provide it and thereby avoid conservative responses when a pointer is compared to null.
bool captured (const Use *U) override
See CaptureTracker::captured(...).
void addPotentialCopy (CallBase &CB)
Register CS as potential copy of the value we are checking.
bool shouldExplore (const Use *U) override
See CaptureTracker::shouldExplore(...).
bool isCapturedIn (bool CapturedInMem, bool CapturedInInt, bool CapturedInRet)
Update the state according to CapturedInMem, CapturedInInt, and CapturedInRet, then return the appropriate value for use in the CaptureTracker::captured() interface.
Public Member Functions inherited from llvm::CaptureTracker
virtual ~CaptureTracker ()
Detailed Description
Attributor-aware capture tracker.
Definition at line 4741 of file AttributorAttributes.cpp.
Constructor & Destructor Documentation
AACaptureUseTracker()
AACaptureUseTracker::AACaptureUseTracker (Attributor & A, AANoCapture & NoCaptureAA, const AAIsDead & IsDeadAA, AANoCapture::StateType & State, SmallSetVector< Value *, 4 > & PotentialCopies, unsigned & RemainingUsesToExplore) inline
Create a capture tracker that can lookup in-flight abstract attributes through the Attributor A.
If a use leads to a potential capture, CapturedInMemory is set and the search is stopped. If a use leads to a return instruction, CommunicatedBack is set to true and CapturedInMemory is not changed. If a use leads to a ptr2int which may capture the value, CapturedInInteger is set. If a use is found that is currently assumed "no-capture-maybe-returned", the user is added to the PotentialCopies set. All values in PotentialCopies are later tracked as well. For every explored use we decrement RemainingUsesToExplore. Once it reaches 0, the search is stopped with CapturedInMemory and CapturedInInteger conservatively set to true.
Definition at line 4756 of file AttributorAttributes.cpp.
Member Function Documentation
addPotentialCopy()
void AACaptureUseTracker::addPotentialCopy (CallBase & CB) inline
Register CS as potential copy of the value we are checking.
Definition at line 4859 of file AttributorAttributes.cpp.
captured()
bool AACaptureUseTracker::captured (const Use * U) inline override virtual
See CaptureTracker::captured(...).
Implements llvm::CaptureTracker.
Definition at line 4788 of file AttributorAttributes.cpp.
References A, llvm::IRPosition::callsite_argument(), llvm::dbgs(), llvm::Instruction::getFunction(), llvm::AA::getPotentialCopiesOfStoredValue(), LLVM_DEBUG, and SI.
isCapturedIn()
bool AACaptureUseTracker::isCapturedIn (bool CapturedInMem, bool CapturedInInt, bool CapturedInRet) inline
Update the state according to CapturedInMem, CapturedInInt, and CapturedInRet, then return the appropriate value for use in the CaptureTracker::captured() interface.
Definition at line 4873 of file AttributorAttributes.cpp.
References llvm::dbgs(), LLVM_DEBUG, llvm::AANoCapture::NO_CAPTURE_MAYBE_RETURNED, llvm::AANoCapture::NOT_CAPTURED_IN_INT, llvm::AANoCapture::NOT_CAPTURED_IN_MEM, and llvm::AANoCapture::NOT_CAPTURED_IN_RET.
isDereferenceableOrNull()
bool AACaptureUseTracker::isDereferenceableOrNull (Value * O, const DataLayout & DL) inline override virtual
isDereferenceableOrNull - Overload to allow clients with additional knowledge about pointer dereferenceability to provide it and thereby avoid conservative responses when a pointer is compared to null.
Reimplemented from llvm::CaptureTracker.
Definition at line 4779 of file AttributorAttributes.cpp.
References A, DL, llvm::AADereferenceable::getAssumedDereferenceableBytes(), llvm::CaptureTracker::isDereferenceableOrNull(), llvm::RISCVFenceField::O, and llvm::IRPosition::value().
shouldExplore()
bool AACaptureUseTracker::shouldExplore (const Use * U) inline override virtual
See CaptureTracker::shouldExplore(...).
Reimplemented from llvm::CaptureTracker.
Definition at line 4862 of file AttributorAttributes.cpp.
References A.
tooManyUses()
void AACaptureUseTracker::tooManyUses () inline override virtual
See CaptureTracker::tooManyUses().
Implements llvm::CaptureTracker.
Definition at line 4775 of file AttributorAttributes.cpp.
References llvm::AANoCapture::NO_CAPTURE.
valueMayBeCaptured()
bool AACaptureUseTracker::valueMayBeCaptured (const Value * V) inline
Determine if V maybe captured. Also updates the state!
Definition at line 4765 of file AttributorAttributes.cpp.
References llvm::Value::getType(), llvm::Type::isPointerTy(), llvm::AANoCapture::NO_CAPTURE_MAYBE_RETURNED, and llvm::PointerMayBeCaptured().
Referenced by AANoCaptureImpl::updateImpl().
The documentation for this struct was generated from the following file:
lib/Transforms/IPO/AttributorAttributes.cpp