LLVM: llvm::MDNodeKeyImpl< DIStringType > Struct Reference
llvm::MDNodeKeyImpl< DIStringType > Struct Reference
#include "IR/LLVMContextImpl.h"
Public Member Functions
MDNodeKeyImpl (unsigned Tag, MDString *Name, Metadata *StringLength, Metadata *StringLengthExp, uint64_t SizeInBits, uint32_t AlignInBits, unsigned Encoding)
MDNodeKeyImpl (const DIStringType *N)
bool isKeyOf (const DIStringType *RHS) const
unsigned getHashValue () const
Public Attributes
unsigned Tag
MDString * Name
Metadata * StringLength
Metadata * StringLengthExp
uint64_t SizeInBits
uint32_t AlignInBits
unsigned Encoding
Detailed Description
Definition at line 431 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeKeyImpl() [1/2]
llvm::MDNodeKeyImpl< DIStringType >::MDNodeKeyImpl (unsigned Tag, MDString * Name, Metadata * StringLength, Metadata * StringLengthExp, uint64_t SizeInBits, uint32_t AlignInBits, unsigned Encoding) inline
Definition at line 440 of file LLVMContextImpl.h.
MDNodeKeyImpl() [2/2]
llvm::MDNodeKeyImpl< DIStringType >::MDNodeKeyImpl (const DIStringType * N) inline
Definition at line 446 of file LLVMContextImpl.h.
Member Function Documentation
getHashValue()
unsigned llvm::MDNodeKeyImpl< DIStringType >::getHashValue () const inline
Definition at line 459 of file LLVMContextImpl.h.
References llvm::hash_combine().
isKeyOf()
bool llvm::MDNodeKeyImpl< DIStringType >::isKeyOf (const DIStringType * RHS) const inline
Definition at line 453 of file LLVMContextImpl.h.
References llvm::DIType::getAlignInBits(), llvm::DIStringType::getEncoding(), llvm::DIType::getRawName(), llvm::DIType::getSizeInBits(), and llvm::DINode::getTag().
Member Data Documentation
AlignInBits
uint32_t llvm::MDNodeKeyImpl< DIStringType >::AlignInBits
Definition at line 437 of file LLVMContextImpl.h.
Encoding
unsigned llvm::MDNodeKeyImpl< DIStringType >::Encoding
Definition at line 438 of file LLVMContextImpl.h.
Name
MDString* llvm::MDNodeKeyImpl< DIStringType >::Name
Definition at line 433 of file LLVMContextImpl.h.
SizeInBits
uint64_t llvm::MDNodeKeyImpl< DIStringType >::SizeInBits
Definition at line 436 of file LLVMContextImpl.h.
StringLength
Metadata* llvm::MDNodeKeyImpl< DIStringType >::StringLength
Definition at line 434 of file LLVMContextImpl.h.
StringLengthExp
Metadata* llvm::MDNodeKeyImpl< DIStringType >::StringLengthExp
Definition at line 435 of file LLVMContextImpl.h.
Tag
unsigned llvm::MDNodeKeyImpl< DIStringType >::Tag
Definition at line 432 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h