LLVM: MipsOutgoingValueAssigner Struct Reference
MipsOutgoingValueAssigner Struct Reference
Public Member Functions
MipsOutgoingValueAssigner (CCAssignFn *AssignFn_, const char *Func, bool IsReturn)
bool assignArg (unsigned ValNo, EVT OrigVT, MVT ValVT, MVT LocVT, CCValAssign::LocInfo LocInfo, const CallLowering::ArgInfo &Info, ISD::ArgFlagsTy Flags, CCState &State_) override
Wrap call to (typically tablegenerated CCAssignFn).
Public Member Functions inherited from llvm::CallLowering::OutgoingValueAssigner
OutgoingValueAssigner (CCAssignFn *AssignFn_, CCAssignFn *AssignFnVarArg_=nullptr)
Public Member Functions inherited from llvm::CallLowering::ValueAssigner
ValueAssigner (bool IsIncoming, CCAssignFn *AssignFn_, CCAssignFn *AssignFnVarArg_=nullptr)
virtual ~ValueAssigner ()=default
bool isIncomingArgumentHandler () const
Returns true if the handler is dealing with incoming arguments, i.e.
CCAssignFn * getAssignFn (bool IsVarArg) const
Select the appropriate assignment function depending on whether this is a variadic call.
Public Attributes
const char * Func = nullptr
This is the name of the function being called FIXME: Relying on this is unsound.
bool IsReturn
Is this a return value, or an outgoing call operand.
Public Attributes inherited from llvm::CallLowering::ValueAssigner
CCAssignFn * AssignFn
Assignment function to use for a general call.
CCAssignFn * AssignFnVarArg
Assignment function to use for a variadic call.
uint64_t StackOffset = 0
Stack offset for next argument.
Detailed Description
Definition at line 27 of file MipsCallLowering.cpp.
Constructor & Destructor Documentation
MipsOutgoingValueAssigner()
MipsOutgoingValueAssigner::MipsOutgoingValueAssigner (CCAssignFn * AssignFn_, const char * Func, bool IsReturn) inline
Definition at line 35 of file MipsCallLowering.cpp.
Member Function Documentation
assignArg()
bool MipsOutgoingValueAssigner::assignArg (unsigned ValNo, EVT OrigVT, MVT ValVT, MVT LocVT, CCValAssign::LocInfo LocInfo, const CallLowering::ArgInfo & Info, ISD::ArgFlagsTy Flags, CCState & State) inline override virtual
Wrap call to (typically tablegenerated CCAssignFn).
This may be overridden to track additional state information as arguments are assigned or apply target specific hacks around the legacy infrastructure.
Reimplemented from llvm::CallLowering::ValueAssigner.
Definition at line 39 of file MipsCallLowering.cpp.
References llvm::CallLowering::ValueAssigner::assignArg(), llvm::EVT::getEVT(), Info, llvm::MipsCCState::PreAnalyzeCallOperand(), and llvm::MipsCCState::PreAnalyzeReturnValue().
Member Data Documentation
Func
const char* MipsOutgoingValueAssigner::Func = nullptr
This is the name of the function being called FIXME: Relying on this is unsound.
Definition at line 30 of file MipsCallLowering.cpp.
IsReturn
bool MipsOutgoingValueAssigner::IsReturn
Is this a return value, or an outgoing call operand.
Definition at line 33 of file MipsCallLowering.cpp.
The documentation for this struct was generated from the following file:
lib/Target/Mips/MipsCallLowering.cpp