LLVM: llvm::IRAttribute< AK, BaseType > Struct Template Reference
llvm::IRAttribute< AK, BaseType > Struct Template Reference
Helper class that provides common functionality to manifest IR attributes.
#include "llvm/Transforms/IPO/Attributor.h"
Public Member Functions
IRAttribute (const IRPosition &IRP)
virtual void initialize (Attributor &A) override
See AbstractAttribute::initialize(...).
ChangeStatus manifest (Attributor &A) override
See AbstractAttribute::manifest(...).
Attribute::AttrKind getAttrKind () const
Return the kind that identifies the abstract attribute implementation.
virtual void getDeducedAttributes (LLVMContext &Ctx, SmallVectorImpl< Attribute > &Attrs) const
Return the deduced attributes in Attrs.
Detailed Description
template<Attribute::AttrKind AK, typename BaseType>
struct llvm::IRAttribute< AK, BaseType >
Helper class that provides common functionality to manifest IR attributes.
Definition at line 2541 of file Attributor.h.
Constructor & Destructor Documentation
IRAttribute()
template<Attribute::AttrKind AK, typename BaseType > llvm::IRAttribute< AK, BaseType >::IRAttribute (const IRPosition & IRP) inline
Definition at line 2542 of file Attributor.h.
Member Function Documentation
getAttrKind()
template<Attribute::AttrKind AK, typename BaseType > Attribute::AttrKind llvm::IRAttribute< AK, BaseType >::getAttrKind () const inline
Return the kind that identifies the abstract attribute implementation.
Definition at line 2578 of file Attributor.h.
Referenced by llvm::IRAttribute< Attribute::Returned, AbstractAttribute >::getDeducedAttributes(), and llvm::IRAttribute< Attribute::Returned, AbstractAttribute >::initialize().
getDeducedAttributes()
template<Attribute::AttrKind AK, typename BaseType > virtual void llvm::IRAttribute< AK, BaseType >::getDeducedAttributes (LLVMContext & Ctx, SmallVectorImpl< Attribute > & Attrs) const inline virtual
Return the deduced attributes in Attrs.
Reimplemented in AAMemoryBehaviorImpl, AANoCaptureImpl, AAAlignImpl, and AADereferenceableImpl.
Definition at line 2581 of file Attributor.h.
Referenced by llvm::IRAttribute< Attribute::Returned, AbstractAttribute >::manifest().
initialize()
template<Attribute::AttrKind AK, typename BaseType > virtual void llvm::IRAttribute< AK, BaseType >::initialize (Attributor & A) inline override virtual
See AbstractAttribute::initialize(...).
Reimplemented in AAMemoryBehaviorCallSite, AAMemoryBehaviorCallSiteReturned, AAMemoryBehaviorCallSiteArgument, AAMemoryBehaviorArgument, AAMemoryBehaviorImpl, AANoCaptureCallSiteReturned, AANoCaptureReturned, AANoCaptureCallSiteArgument, AANoCaptureImpl, AANoReturnCallSite, AANoReturnImpl, AAAlignCallSiteReturned, AAAlignReturned, AAAlignImpl, AADereferenceableImpl, AANoAliasCallSiteReturned, AANoAliasReturned, AANoAliasCallSiteArgument, AANoAliasArgument, AANoAliasFloating, AAWillReturnCallSite, AAWillReturnFunction, AAWillReturnImpl, AANoRecurseCallSite, AANoRecurseFunction, AANonNullImpl, AANoFreeReturned, AANoFreeCallSite, AANoSyncCallSite, AAReturnedValuesCallSite, AAReturnedValuesImpl, and AANoUnwindCallSite.
Definition at line 2545 of file Attributor.h.
manifest()
template<Attribute::AttrKind AK, typename BaseType > ChangeStatus llvm::IRAttribute< AK, BaseType >::manifest (Attributor & A) inline override
See AbstractAttribute::manifest(...).
Definition at line 2568 of file Attributor.h.
Referenced by AAReturnedValuesImpl::manifest(), and AAMemoryBehaviorImpl::manifest().
The documentation for this struct was generated from the following file:
include/llvm/Transforms/IPO/Attributor.h