LLVM: llvm::AADepGraphNode Struct Reference
llvm::AADepGraphNode Struct Reference
}
#include "llvm/Transforms/IPO/Attributor.h"
Public Types
using DepTy = PointerIntPair< AADepGraphNode *, 1 >
using iterator = mapped_iterator< TinyPtrVector< DepTy >::iterator, decltype(&DepGetVal)>
using aaiterator = mapped_iterator< TinyPtrVector< DepTy >::iterator, decltype(&DepGetValAA)>
Public Member Functions
virtual ~AADepGraphNode ()
aaiterator begin ()
aaiterator end ()
iterator child_begin ()
iterator child_end ()
virtual void print (raw_ostream &OS) const
TinyPtrVector< DepTy > & getDeps ()
Protected Member Functions
operator AbstractAttribute * ()
Static Protected Member Functions
static AADepGraphNode * DepGetVal (DepTy &DT)
static AbstractAttribute * DepGetValAA (DepTy &DT)
Protected Attributes
TinyPtrVector< DepTy > Deps
Set of dependency graph nodes which should be updated if this one is updated.
Friends
struct Attributor
struct AADepGraph
Detailed Description
}
The data structure for the nodes of a dependency graph
Definition at line 227 of file Attributor.h.
Member Typedef Documentation
aaiterator
using llvm::AADepGraphNode::aaiterator = mapped_iterator<TinyPtrVector<DepTy>::iterator, decltype(&DepGetValAA)>
Definition at line 247 of file Attributor.h.
DepTy
using llvm::AADepGraphNode::DepTy = PointerIntPair<AADepGraphNode *, 1>
Definition at line 230 of file Attributor.h.
iterator
using llvm::AADepGraphNode::iterator = mapped_iterator<TinyPtrVector<DepTy>::iterator, decltype(&DepGetVal)>
Definition at line 245 of file Attributor.h.
Constructor & Destructor Documentation
~AADepGraphNode()
virtual llvm::AADepGraphNode::~AADepGraphNode () inline virtual
Definition at line 229 of file Attributor.h.
Member Function Documentation
begin()
aaiterator llvm::AADepGraphNode::begin () inline
Definition at line 250 of file Attributor.h.
References DepGetValAA(), and Deps.
Referenced by llvm::AAPotentialValues::getAssumedConstantInt(), llvm::AAIsDead::isLiveInstSet(), and llvm::AACallEdges::optimisticEdgesBegin().
child_begin()
iterator llvm::AADepGraphNode::child_begin () inline
Definition at line 252 of file Attributor.h.
References DepGetVal(), and Deps.
Referenced by llvm::AADepGraph::begin().
child_end()
iterator llvm::AADepGraphNode::child_end () inline
Definition at line 253 of file Attributor.h.
References DepGetVal(), and Deps.
Referenced by llvm::AADepGraph::end().
DepGetVal()
static AADepGraphNode* llvm::AADepGraphNode::DepGetVal (DepTy & DT) inline static protected
Definition at line 237 of file Attributor.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getPointer().
Referenced by child_begin(), and child_end().
DepGetValAA()
static AbstractAttribute* llvm::AADepGraphNode::DepGetValAA (DepTy & DT) inline static protected
Definition at line 238 of file Attributor.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getPointer().
Referenced by begin(), and end().
end()
aaiterator llvm::AADepGraphNode::end () inline
Definition at line 251 of file Attributor.h.
References DepGetValAA(), and Deps.
Referenced by llvm::AAIsDead::isLiveInstSet(), and llvm::AACallEdges::optimisticEdgesEnd().
getDeps()
TinyPtrVector<DepTy>& llvm::AADepGraphNode::getDeps () inline
Definition at line 256 of file Attributor.h.
References Deps.
operator AbstractAttribute *()
llvm::AADepGraphNode::operator AbstractAttribute * () inline protected
Definition at line 242 of file Attributor.h.
print()
virtual void llvm::AADepGraphNode::print (raw_ostream & OS) const inline virtual
Reimplemented in llvm::AbstractAttribute.
Definition at line 255 of file Attributor.h.
Friends And Related Function Documentation
AADepGraph
friend struct AADepGraph friend
Definition at line 259 of file Attributor.h.
Attributor
friend struct Attributor friend
Definition at line 258 of file Attributor.h.
Member Data Documentation
Deps
TinyPtrVector<DepTy> llvm::AADepGraphNode::Deps protected
Set of dependency graph nodes which should be updated if this one is updated.
The bit encodes if it is optional.
Definition at line 235 of file Attributor.h.
Referenced by begin(), child_begin(), child_end(), end(), getDeps(), llvm::AADepGraph::print(), llvm::AbstractAttribute::printWithDeps(), llvm::Attributor::registerAA(), and llvm::Attributor::~Attributor().
The documentation for this struct was generated from the following file:
include/llvm/Transforms/IPO/Attributor.h