LLVM: llvm::ThreadSanitizerPass Struct Reference
llvm::ThreadSanitizerPass Struct Reference
A function pass for tsan instrumentation.
#include "llvm/Transforms/Instrumentation/ThreadSanitizer.h"
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &FAM)
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< ThreadSanitizerPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
A function pass for tsan instrumentation.
Instruments functions to detect race conditions reads. This function pass inserts calls to runtime library functions. If the functions aren't declared yet, the pass inserts the declarations. Otherwise the existing globals are
Definition at line 28 of file ThreadSanitizer.h.
Member Function Documentation
isRequired()
static bool llvm::ThreadSanitizerPass::isRequired () inline static
Definition at line 31 of file ThreadSanitizer.h.
run() [1/2]
PreservedAnalyses ThreadSanitizerPass::run (Function & F, FunctionAnalysisManager & FAM)
Definition at line 201 of file ThreadSanitizer.cpp.
References llvm::PreservedAnalyses::all(), F, FAM, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::PreservedAnalyses::none().
run() [2/2]
PreservedAnalyses ThreadSanitizerPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 209 of file ThreadSanitizer.cpp.
References M, and llvm::PreservedAnalyses::none().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/Instrumentation/ThreadSanitizer.h
lib/Transforms/Instrumentation/ThreadSanitizer.cpp