LLVM: Status Struct Reference
Status Struct Reference
Public Member Functions
Status ()
Status (unsigned NewMask, unsigned NewMode)
Status merge (const Status &S) const
Status mergeUnknown (unsigned newMask)
Status intersect (const Status &S) const
Status delta (const Status &S) const
bool operator== (const Status &S) const
bool operator!= (const Status &S) const
bool isCompatible (Status &S)
bool isCombinable (Status &S)
Public Attributes
unsigned Mask
unsigned Mode
Detailed Description
Definition at line 28 of file SIModeRegister.cpp.
Constructor & Destructor Documentation
Status() [1/2]
Status::Status () inline
Definition at line 34 of file SIModeRegister.cpp.
Status() [2/2]
Status::Status (unsigned NewMask, unsigned NewMode) inline
Definition at line 36 of file SIModeRegister.cpp.
References llvm::BitmaskEnumDetail::Mask(), and Mode.
Member Function Documentation
delta()
Status Status::delta (const Status & S) const inline
Definition at line 61 of file SIModeRegister.cpp.
References llvm::BitmaskEnumDetail::Mask(), Mode, and S.
intersect()
Status Status::intersect (const Status & S) const inline
Definition at line 54 of file SIModeRegister.cpp.
References llvm::BitmaskEnumDetail::Mask(), Mode, and S.
isCombinable()
bool Status::isCombinable (Status & S) inline
Definition at line 75 of file SIModeRegister.cpp.
References llvm::BitmaskEnumDetail::Mask(), and S.
isCompatible()
bool Status::isCompatible (Status & S) inline
Definition at line 71 of file SIModeRegister.cpp.
References llvm::BitmaskEnumDetail::Mask(), Mode, and S.
merge()
Status Status::merge (const Status & S) const inline
Definition at line 42 of file SIModeRegister.cpp.
References llvm::BitmaskEnumDetail::Mask(), Mode, and S.
mergeUnknown()
Status Status::mergeUnknown (unsigned newMask) inline
Definition at line 48 of file SIModeRegister.cpp.
References llvm::BitmaskEnumDetail::Mask(), and Mode.
operator!=()
bool Status::operator!= (const Status & S) const inline
Definition at line 69 of file SIModeRegister.cpp.
References S.
operator==()
bool Status::operator== (const Status & S) const inline
Definition at line 65 of file SIModeRegister.cpp.
References llvm::BitmaskEnumDetail::Mask(), Mode, and S.
Member Data Documentation
Mask
unsigned Status::Mask
Definition at line 31 of file SIModeRegister.cpp.
Mode
unsigned Status::Mode
Definition at line 32 of file SIModeRegister.cpp.
The documentation for this struct was generated from the following file:
lib/Target/AMDGPU/SIModeRegister.cpp