LLVM: llvm::MaybeAlign Struct Reference
llvm::MaybeAlign Struct Reference
This struct is a compact representation of a valid (power of two) or undefined (0) alignment.
#include "llvm/Support/Alignment.h"
Public Member Functions
MaybeAlign ()=default
Default is undefined.
MaybeAlign (const MaybeAlign &Other)=default
Do not perform checks in case of copy/move construct/assign, because the checks have been performed when building Other.
MaybeAlign & operator= (const MaybeAlign &Other)=default
MaybeAlign (MaybeAlign &&Other)=default
MaybeAlign & operator= (MaybeAlign &&Other)=default
MaybeAlign (uint64_t Value)
Align valueOrOne () const
For convenience, returns a valid alignment or 1 if undefined.
Public Member Functions inherited from llvm::Optional< Align >
constexpr Optional ()
constexpr Optional (NoneType)
constexpr Optional (const Align &y)
constexpr Optional (const Optional &O)=default
constexpr Optional (Align &&y)
constexpr Optional (Optional &&O)=default
constexpr Optional (in_place_t, ArgTypes &&...Args)
Optional & operator= (Align &&y)
Optional & operator= (Optional &&O)=default
Optional & operator= (const Align &y)
Optional & operator= (const Optional &O)=default
void emplace (ArgTypes &&... Args)
Create a new object by constructing it in place with the given arguments.
void reset ()
constexpr const Align * getPointer () const
Align * getPointer ()
constexpr const Align & getValue () const LLVM_LVALUE_FUNCTION
Align & getValue () LLVM_LVALUE_FUNCTION
constexpr operator bool () const
constexpr bool hasValue () const
constexpr const Align * operator-> () const
Align * operator-> ()
constexpr const Align & operator* () const LLVM_LVALUE_FUNCTION
Align & operator* () LLVM_LVALUE_FUNCTION
constexpr Align getValueOr (U &&value) const LLVM_LVALUE_FUNCTION
auto map (const Function &F) const LLVM_LVALUE_FUNCTION -> Optional< decltype(F(getValue()))>
Apply a function to the value if present; otherwise return None.
Additional Inherited Members
Public Types inherited from llvm::Optional< Align >
using value_type = Align
Static Public Member Functions inherited from llvm::Optional< Align >
static constexpr Optional create (const Align *y)
Detailed Description
This struct is a compact representation of a valid (power of two) or undefined (0) alignment.
Definition at line 109 of file Alignment.h.
Constructor & Destructor Documentation
MaybeAlign() [1/4]
llvm::MaybeAlign::MaybeAlign () default
Default is undefined.
MaybeAlign() [2/4]
llvm::MaybeAlign::MaybeAlign (const MaybeAlign & Other) default
Do not perform checks in case of copy/move construct/assign, because the checks have been performed when building Other.
MaybeAlign() [3/4]
llvm::MaybeAlign::MaybeAlign (MaybeAlign && Other) default
MaybeAlign() [4/4]
llvm::MaybeAlign::MaybeAlign (uint64_t Value) inline explicit
Definition at line 126 of file Alignment.h.
References assert(), llvm::Optional< Align >::emplace(), and llvm::isPowerOf2_64().
Member Function Documentation
operator=() [1/2]
MaybeAlign& llvm::MaybeAlign::operator= (const MaybeAlign & Other) default
operator=() [2/2]
MaybeAlign& llvm::MaybeAlign::operator= (MaybeAlign && Other) default
valueOrOne()
Align llvm::MaybeAlign::valueOrOne () const inline
For convenience, returns a valid alignment or 1 if undefined.
Definition at line 134 of file Alignment.h.
References Align, llvm::Optional< Align >::getValue(), and llvm::Optional< Align >::hasValue().
Referenced by CC_RISCV(), CC_RISCV_FastCC(), llvm::expandMemCpyAsLoop(), llvm::expandMemMoveAsLoop(), llvm::expandMemSetAsLoop(), llvm::ConstantInt::getAlignValue(), llvm::HexagonTTIImpl::getMemoryOpCost(), llvm::X86TTIImpl::getMemoryOpCost(), llvm::ISD::ArgFlagsTy::getNonZeroMemAlign(), llvm::ISD::ArgFlagsTy::getNonZeroOrigAlign(), llvm::Value::getPointerAlignment(), hasTocDataAttr(), and llvm::MIRParserImpl::initializeMachineFunction().
The documentation for this struct was generated from the following file:
include/llvm/Support/Alignment.h