LLVM: llvm::VPlanVerifier Struct Reference
llvm::VPlanVerifier Struct Reference
Struct with utility functions that can be used to check the consistency and invariants of a VPlan, including the components of its H-CFG.
#include "Transforms/Vectorize/VPlanVerifier.h"
Public Member Functions
void verifyHierarchicalCFG (const VPRegionBlock *TopRegion) const
Verify the invariants of the H-CFG starting from TopRegion.
Detailed Description
Struct with utility functions that can be used to check the consistency and invariants of a VPlan, including the components of its H-CFG.
Definition at line 32 of file VPlanVerifier.h.
Member Function Documentation
verifyHierarchicalCFG()
void VPlanVerifier::verifyHierarchicalCFG (const VPRegionBlock * TopRegion) const
Verify the invariants of the H-CFG starting from TopRegion.
The verification process comprises the following steps:
Region/Block verification: Check the Region/Block verification invariants for every region in the H-CFG.
Definition at line 122 of file VPlanVerifier.cpp.
References assert(), llvm::dbgs(), EnableHCFGVerifier, llvm::VPBlockBase::getParent(), LLVM_DEBUG, and verifyRegionRec().
Referenced by llvm::VPlanHCFGBuilder::buildHierarchicalCFG().
The documentation for this struct was generated from the following files:
lib/Transforms/Vectorize/VPlanVerifier.h
lib/Transforms/Vectorize/VPlanVerifier.cpp