LLVM: SCEVDbgValueBuilder Struct Reference
SCEVDbgValueBuilder Struct Reference
Public Member Functions
SCEVDbgValueBuilder ()=default
SCEVDbgValueBuilder (const SCEVDbgValueBuilder &Base)
void pushOperator (uint64_t Op)
void pushUInt (uint64_t Operand)
void pushValue (llvm::Value *V)
Add a DW_OP_LLVM_arg to the expression, followed by the index of the value in the set of values referenced by the expression.
void pushValue (const SCEVUnknown *U)
bool pushConst (const SCEVConstant *C)
bool pushArithmeticExpr (const llvm::SCEVCommutativeExpr *CommExpr, uint64_t DwarfOp)
Several SCEV types are sequences of the same arithmetic operator applied to constants and values that may be extended or truncated.
bool pushCast (const llvm::SCEVCastExpr *C, bool IsSigned)
bool pushSCEV (const llvm::SCEV *S)
void setFinalExpression (llvm::DbgValueInst &DI, const DIExpression *OldExpr)
void setShortFinalExpression (llvm::DbgValueInst &DI, const DIExpression *OldExpr)
If a DVI can be emitted without a DIArgList, omit DW_OP_llvm_arg and the location op index 0.
void applyExprToDbgValue (llvm::DbgValueInst &DI, const DIExpression *OldExpr)
Once the IV and variable SCEV translation is complete, write it to the source DVI.
bool isIdentityFunction (uint64_t Op, const SCEV *S)
Return true if the combination of arithmetic operator and underlying SCEV constant value is an identity function.
bool SCEVToValueExpr (const llvm::SCEVAddRecExpr &SAR, ScalarEvolution &SE)
Convert a SCEV of a value to a DIExpression that is pushed onto the builder's expression stack.
bool SCEVToIterCountExpr (const llvm::SCEVAddRecExpr &SAR, ScalarEvolution &SE)
Convert a SCEV of a value to a DIExpression that is pushed onto the builder's expression stack.
Public Attributes
SmallVector< uint64_t, 6 > Expr
The DIExpression as we translate the SCEV.
SmallVector< llvm::ValueAsMetadata *, 2 > Values
The location ops of the DIExpression.
Detailed Description
Definition at line 5873 of file LoopStrengthReduce.cpp.
Constructor & Destructor Documentation
SCEVDbgValueBuilder() [1/2]
SCEVDbgValueBuilder::SCEVDbgValueBuilder () default
SCEVDbgValueBuilder() [2/2]
SCEVDbgValueBuilder::SCEVDbgValueBuilder (const SCEVDbgValueBuilder & Base) inline
Definition at line 5875 of file LoopStrengthReduce.cpp.
References llvm::sampleprof::Base, Expr, and Values.
Member Function Documentation
applyExprToDbgValue()
void SCEVDbgValueBuilder::applyExprToDbgValue (llvm::DbgValueInst & DI, const DIExpression * OldExpr) inline
Once the IV and variable SCEV translation is complete, write it to the source DVI.
Definition at line 6023 of file LoopStrengthReduce.cpp.
References assert(), llvm::dwarf::DW_OP_LLVM_arg, Expr, setFinalExpression(), setShortFinalExpression(), and Values.
Referenced by RewriteDVIUsingIterCount().
isIdentityFunction()
bool SCEVDbgValueBuilder::isIdentityFunction (uint64_t Op, const SCEV * S) inline
Return true if the combination of arithmetic operator and underlying SCEV constant value is an identity function.
Definition at line 6037 of file LoopStrengthReduce.cpp.
References I, and S.
pushArithmeticExpr()
bool SCEVDbgValueBuilder::pushArithmeticExpr (const llvm::SCEVCommutativeExpr * CommExpr, uint64_t DwarfOp) inline
Several SCEV types are sequences of the same arithmetic operator applied to constants and values that may be extended or truncated.
Definition at line 5919 of file LoopStrengthReduce.cpp.
References assert(), llvm::lltok::DwarfOp, llvm::SCEVNAryExpr::operands(), pushOperator(), pushSCEV(), and Success.
Referenced by pushSCEV().
pushCast()
bool SCEVDbgValueBuilder::pushCast (const llvm::SCEVCastExpr * C, bool IsSigned) inline
Definition at line 5936 of file LoopStrengthReduce.cpp.
References llvm::dwarf::DW_OP_LLVM_convert, llvm::Type::getIntegerBitWidth(), pushOperator(), pushSCEV(), and Success.
Referenced by pushSCEV().
pushConst()
bool SCEVDbgValueBuilder::pushConst (const SCEVConstant * C) inline
Definition at line 5909 of file LoopStrengthReduce.cpp.
References Expr.
Referenced by pushSCEV().
pushOperator()
void SCEVDbgValueBuilder::pushOperator (uint64_t Op) inline
Definition at line 5885 of file LoopStrengthReduce.cpp.
References Expr.
Referenced by pushArithmeticExpr(), pushCast(), and pushSCEV().
pushSCEV()
bool SCEVDbgValueBuilder::pushSCEV (const llvm::SCEV * S) inline
Definition at line 5950 of file LoopStrengthReduce.cpp.
References assert(), pushArithmeticExpr(), pushCast(), pushConst(), pushOperator(), pushValue(), S, and Success.
Referenced by pushArithmeticExpr(), and pushCast().
pushUInt()
void SCEVDbgValueBuilder::pushUInt (uint64_t Operand) inline
Definition at line 5886 of file LoopStrengthReduce.cpp.
References Expr.
pushValue() [1/2]
void SCEVDbgValueBuilder::pushValue (const SCEVUnknown * U) inline
Definition at line 5904 of file LoopStrengthReduce.cpp.
References pushValue().
pushValue() [2/2]
void SCEVDbgValueBuilder::pushValue (llvm::Value * V) inline
Add a DW_OP_LLVM_arg to the expression, followed by the index of the value in the set of values referenced by the expression.
Definition at line 5890 of file LoopStrengthReduce.cpp.
References llvm::dwarf::DW_OP_LLVM_arg, Expr, llvm::find(), llvm::ValueAsMetadata::get(), and Values.
Referenced by DbgRewriteSalvageableDVIs(), pushSCEV(), and pushValue().
SCEVToIterCountExpr()
bool SCEVDbgValueBuilder::SCEVToIterCountExpr (const llvm::SCEVAddRecExpr & SAR, ScalarEvolution & SE) inline
Convert a SCEV of a value to a DIExpression that is pushed onto the builder's expression stack.
The stack should already contain an expression for the iteration count, so that it can be multiplied by the stride and added to the start. Components of the expression are omitted if they are an identity function.
Definition at line 6088 of file LoopStrengthReduce.cpp.
References assert(), llvm::dbgs(), llvm::SCEVAddRecExpr::getStart(), llvm::SCEVAddRecExpr::isAffine(), and LLVM_DEBUG.
Referenced by DbgRewriteSalvageableDVIs().
SCEVToValueExpr()
bool SCEVDbgValueBuilder::SCEVToValueExpr (const llvm::SCEVAddRecExpr & SAR, ScalarEvolution & SE) inline
Convert a SCEV of a value to a DIExpression that is pushed onto the builder's expression stack.
The stack should already contain an expression for the iteration count, so that it can be multiplied by the stride and added to the start. Components of the expression are omitted if they are an identity function. Chain (non-affine) SCEVs are not supported.
Definition at line 6060 of file LoopStrengthReduce.cpp.
References assert(), llvm::SCEVAddRecExpr::getStart(), and llvm::SCEVAddRecExpr::isAffine().
Referenced by RewriteDVIUsingIterCount().
setFinalExpression()
void SCEVDbgValueBuilder::setFinalExpression (llvm::DbgValueInst & DI, const DIExpression * OldExpr) inline
Definition at line 5989 of file LoopStrengthReduce.cpp.
References assert(), Expr, llvm::MDNode::get(), llvm::Value::getContext(), llvm::DbgVariableIntrinsic::hasArgList(), llvm::DbgVariableIntrinsic::setExpression(), llvm::DbgVariableIntrinsic::setRawLocation(), and Values.
Referenced by applyExprToDbgValue().
setShortFinalExpression()
void SCEVDbgValueBuilder::setShortFinalExpression (llvm::DbgValueInst & DI, const DIExpression * OldExpr) inline
If a DVI can be emitted without a DIArgList, omit DW_OP_llvm_arg and the location op index 0.
Definition at line 6005 of file LoopStrengthReduce.cpp.
References assert(), llvm::dwarf::DW_OP_LLVM_arg, Expr, llvm::MetadataAsValue::get(), llvm::Value::getContext(), llvm::DbgVariableIntrinsic::hasArgList(), llvm::DbgVariableIntrinsic::replaceVariableLocationOp(), llvm::DbgVariableIntrinsic::setExpression(), and Values.
Referenced by applyExprToDbgValue().
Member Data Documentation
Expr
SmallVector<uint64_t, 6> SCEVDbgValueBuilder::Expr
The DIExpression as we translate the SCEV.
Definition at line 5881 of file LoopStrengthReduce.cpp.
Referenced by applyExprToDbgValue(), pushConst(), pushOperator(), pushUInt(), pushValue(), SCEVDbgValueBuilder(), setFinalExpression(), and setShortFinalExpression().
Values
SmallVector<llvm::ValueAsMetadata *, 2> SCEVDbgValueBuilder::Values
The location ops of the DIExpression.
Definition at line 5883 of file LoopStrengthReduce.cpp.
Referenced by applyExprToDbgValue(), pushValue(), SCEVDbgValueBuilder(), setFinalExpression(), and setShortFinalExpression().
The documentation for this struct was generated from the following file:
lib/Transforms/Scalar/LoopStrengthReduce.cpp