LLVM: llvm::PatchLocation Struct Reference
llvm::PatchLocation Struct Reference
#include "llvm/DWARFLinker/DWARFLinkerCompileUnit.h"
Public Member Functions
PatchLocation ()=default
PatchLocation (DIE::value_iterator I)
void set (uint64_t New) const
uint64_t get () const
Public Attributes
DIE::value_iterator I
Detailed Description
Definition at line 29 of file DWARFLinkerCompileUnit.h.
Constructor & Destructor Documentation
PatchLocation() [1/2]
llvm::PatchLocation::PatchLocation () default
PatchLocation() [2/2]
llvm::PatchLocation::PatchLocation (DIE::value_iterator I) inline
Definition at line 33 of file DWARFLinkerCompileUnit.h.
Member Function Documentation
get()
uint64_t llvm::PatchLocation::get () const inline
Definition at line 42 of file DWARFLinkerCompileUnit.h.
References assert(), and I.
set()
void llvm::PatchLocation::set (uint64_t New) const inline
Definition at line 35 of file DWARFLinkerCompileUnit.h.
References assert(), I, and llvm::yaml::isInteger().
Referenced by llvm::CompileUnit::fixupForwardReferences().
Member Data Documentation
I
DIE::value_iterator llvm::PatchLocation::I
Definition at line 30 of file DWARFLinkerCompileUnit.h.
Referenced by get(), and set().
The documentation for this struct was generated from the following file:
include/llvm/DWARFLinker/DWARFLinkerCompileUnit.h