LLVM: llvm::MDNodeKeyImpl< DITemplateValueParameter > Struct Reference
llvm::MDNodeKeyImpl< DITemplateValueParameter > Struct Reference
#include "IR/LLVMContextImpl.h"
Public Member Functions
MDNodeKeyImpl (unsigned Tag, MDString *Name, Metadata *Type, bool IsDefault, Metadata *Value)
MDNodeKeyImpl (const DITemplateValueParameter *N)
bool isKeyOf (const DITemplateValueParameter *RHS) const
unsigned getHashValue () const
Public Attributes
unsigned Tag
MDString * Name
Metadata * Type
bool IsDefault
Metadata * Value
Detailed Description
Definition at line 943 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeKeyImpl() [1/2]
llvm::MDNodeKeyImpl< DITemplateValueParameter >::MDNodeKeyImpl (unsigned Tag, MDString * Name, Metadata * Type, bool IsDefault, Metadata * Value) inline
Definition at line 950 of file LLVMContextImpl.h.
MDNodeKeyImpl() [2/2]
llvm::MDNodeKeyImpl< DITemplateValueParameter >::MDNodeKeyImpl (const DITemplateValueParameter * N) inline
Definition at line 953 of file LLVMContextImpl.h.
Member Function Documentation
getHashValue()
unsigned llvm::MDNodeKeyImpl< DITemplateValueParameter >::getHashValue () const inline
Definition at line 963 of file LLVMContextImpl.h.
References llvm::hash_combine().
isKeyOf()
bool llvm::MDNodeKeyImpl< DITemplateValueParameter >::isKeyOf (const DITemplateValueParameter * RHS) const inline
Definition at line 957 of file LLVMContextImpl.h.
References llvm::DITemplateParameter::getRawName(), llvm::DITemplateParameter::getRawType(), llvm::DINode::getTag(), llvm::DITemplateValueParameter::getValue(), and llvm::DITemplateParameter::isDefault().
Member Data Documentation
IsDefault
bool llvm::MDNodeKeyImpl< DITemplateValueParameter >::IsDefault
Definition at line 947 of file LLVMContextImpl.h.
Name
MDString* llvm::MDNodeKeyImpl< DITemplateValueParameter >::Name
Definition at line 945 of file LLVMContextImpl.h.
Tag
unsigned llvm::MDNodeKeyImpl< DITemplateValueParameter >::Tag
Definition at line 944 of file LLVMContextImpl.h.
Type
Metadata* llvm::MDNodeKeyImpl< DITemplateValueParameter >::Type
Definition at line 946 of file LLVMContextImpl.h.
Value
Metadata* llvm::MDNodeKeyImpl< DITemplateValueParameter >::Value
Definition at line 948 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h