LLVM: llvm::DenseMapInfo< ElementCount > Struct Reference
llvm::DenseMapInfo< ElementCount > Struct Reference
#include "llvm/Support/TypeSize.h"
Static Public Member Functions
static ElementCount getEmptyKey ()
static ElementCount getTombstoneKey ()
static unsigned getHashValue (const ElementCount &EltCnt)
static bool isEqual (const ElementCount &LHS, const ElementCount &RHS)
Detailed Description
Definition at line 504 of file TypeSize.h.
Member Function Documentation
getEmptyKey()
static ElementCount llvm::DenseMapInfo< ElementCount >::getEmptyKey () inline static
Definition at line 505 of file TypeSize.h.
References llvm::LinearPolySize< ElementCount >::getScalable().
getHashValue()
static unsigned llvm::DenseMapInfo< ElementCount >::getHashValue (const ElementCount & EltCnt) inline static
Definition at line 511 of file TypeSize.h.
References llvm::LinearPolySize< LeafTy >::getKnownMinValue(), and llvm::LinearPolySize< LeafTy >::isScalable().
getTombstoneKey()
static ElementCount llvm::DenseMapInfo< ElementCount >::getTombstoneKey () inline static
Definition at line 508 of file TypeSize.h.
References llvm::LinearPolySize< ElementCount >::getFixed().
isEqual()
static bool llvm::DenseMapInfo< ElementCount >::isEqual (const ElementCount & LHS, const ElementCount & RHS) inline static
Definition at line 519 of file TypeSize.h.
The documentation for this struct was generated from the following file:
include/llvm/Support/TypeSize.h