LLVM: llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, true >, false > Struct Template Reference
llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, true >, false > Struct Template Reference
#include "llvm/Object/ELFTypes.h"
Public Member Functions
uint64_t getRInfo (bool isMips64EL) const
void setRInfo (uint64_t R, bool IsMips64EL)
uint32_t getSymbol (bool isMips64EL) const
uint32_t getType (bool isMips64EL) const
void setSymbol (uint32_t s, bool IsMips64EL)
void setType (uint32_t t, bool IsMips64EL)
void setSymbolAndType (uint32_t s, uint32_t t, bool IsMips64EL)
Public Attributes
Elf_Addr r_offset
Elf_Xword r_info
Static Public Attributes
static const bool IsRela = false
Detailed Description
template<endianness TargetEndianness>
struct llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, true >, false >
Definition at line 430 of file ELFTypes.h.
Member Function Documentation
getRInfo()
template<endianness TargetEndianness> uint64_t llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, true >, false >::getRInfo (bool isMips64EL) const inline
Definition at line 436 of file ELFTypes.h.
References isMips64EL().
getSymbol()
template<endianness TargetEndianness> uint32_t llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, true >, false >::getSymbol (bool isMips64EL) const inline
Definition at line 457 of file ELFTypes.h.
References isMips64EL().
getType()
template<endianness TargetEndianness> uint32_t llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, true >, false >::getType (bool isMips64EL) const inline
Definition at line 460 of file ELFTypes.h.
References isMips64EL().
setRInfo()
template<endianness TargetEndianness> void llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, true >, false >::setRInfo (uint64_t R, bool IsMips64EL) inline
Definition at line 447 of file ELFTypes.h.
References llvm::RISCVFenceField::R.
setSymbol()
template<endianness TargetEndianness> void llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, true >, false >::setSymbol (uint32_t s, bool IsMips64EL) inline
Definition at line 463 of file ELFTypes.h.
References llvm::Intrinsic::getType(), and s.
setSymbolAndType()
template<endianness TargetEndianness> void llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, true >, false >::setSymbolAndType (uint32_t s, uint32_t t, bool IsMips64EL) inline
Definition at line 469 of file ELFTypes.h.
References s.
setType()
template<endianness TargetEndianness> void llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, true >, false >::setType (uint32_t t, bool IsMips64EL) inline
Definition at line 466 of file ELFTypes.h.
Member Data Documentation
IsRela
template<endianness TargetEndianness> const bool llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, true >, false >::IsRela = false static
Definition at line 432 of file ELFTypes.h.
r_info
template<endianness TargetEndianness> Elf_Xword llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, true >, false >::r_info
Definition at line 434 of file ELFTypes.h.
r_offset
template<endianness TargetEndianness> Elf_Addr llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, true >, false >::r_offset
Definition at line 433 of file ELFTypes.h.
The documentation for this struct was generated from the following file:
include/llvm/Object/ELFTypes.h