LLVM: llvm::AA::PointerInfo::OffsetAndSize Struct Reference
llvm::AA::PointerInfo::OffsetAndSize Struct Reference
Helper to represent an access offset and size, with logic to deal with uncertainty and check for overlapping accesses.
Public Types
using BaseTy = std::pair< int64_t, int64_t >
Public Member Functions
OffsetAndSize (int64_t Offset, int64_t Size)
OffsetAndSize (const BaseTy &P)
int64_t getOffset () const
int64_t getSize () const
bool mayOverlap (const OffsetAndSize &OAS) const
Return true if this offset and size pair might describe an address that overlaps with OAS.
Static Public Member Functions
static OffsetAndSize getUnknown ()
Static Public Attributes
static constexpr int64_t Unknown = 1 << 31
Constant used to represent unknown offset or sizes.
Detailed Description
Helper to represent an access offset and size, with logic to deal with uncertainty and check for overlapping accesses.
Definition at line 820 of file AttributorAttributes.cpp.
Member Typedef Documentation
BaseTy
using llvm::AA::PointerInfo::OffsetAndSize::BaseTy = std::pair<int64_t, int64_t>
Definition at line 821 of file AttributorAttributes.cpp.
Constructor & Destructor Documentation
OffsetAndSize() [1/2]
llvm::AA::PointerInfo::OffsetAndSize::OffsetAndSize (int64_t Offset, int64_t Size) inline
Definition at line 822 of file AttributorAttributes.cpp.
Referenced by llvm::AA::PointerInfo::OffsetAndSize::getUnknown().
OffsetAndSize() [2/2]
llvm::AA::PointerInfo::OffsetAndSize::OffsetAndSize (const BaseTy & P) inline
Definition at line 823 of file AttributorAttributes.cpp.
Member Function Documentation
getOffset()
int64_t llvm::AA::PointerInfo::OffsetAndSize::getOffset () const inline
Definition at line 824 of file AttributorAttributes.cpp.
Referenced by llvm::AA::PointerInfo::OffsetAndSize::mayOverlap().
getSize()
int64_t llvm::AA::PointerInfo::OffsetAndSize::getSize () const inline
Definition at line 825 of file AttributorAttributes.cpp.
Referenced by llvm::AA::PointerInfo::State::forallInterferingAccesses(), and llvm::AA::PointerInfo::OffsetAndSize::mayOverlap().
getUnknown()
static OffsetAndSize llvm::AA::PointerInfo::OffsetAndSize::getUnknown () inline static
Definition at line 826 of file AttributorAttributes.cpp.
References llvm::AA::PointerInfo::OffsetAndSize::OffsetAndSize(), and llvm::AA::PointerInfo::OffsetAndSize::Unknown.
mayOverlap()
bool llvm::AA::PointerInfo::OffsetAndSize::mayOverlap (const OffsetAndSize & OAS) const inline
Return true if this offset and size pair might describe an address that overlaps with OAS.
Definition at line 830 of file AttributorAttributes.cpp.
References llvm::AA::PointerInfo::OffsetAndSize::getOffset(), llvm::AA::PointerInfo::OffsetAndSize::getSize(), and llvm::AA::PointerInfo::OffsetAndSize::Unknown.
Referenced by llvm::AA::PointerInfo::State::forallInterferingAccesses().
Member Data Documentation
Unknown
constexpr int64_t llvm::AA::PointerInfo::OffsetAndSize::Unknown = 1 << 31 static constexpr
Constant used to represent unknown offset or sizes.
Definition at line 844 of file AttributorAttributes.cpp.
Referenced by llvm::AA::PointerInfo::OffsetAndSize::getUnknown(), and llvm::AA::PointerInfo::OffsetAndSize::mayOverlap().
The documentation for this struct was generated from the following file:
lib/Transforms/IPO/AttributorAttributes.cpp