LLVM: lib/MC/WasmObjectWriter.cpp File Reference
WasmObjectWriter.cpp File Reference
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/BinaryFormat/Wasm.h"
#include "llvm/BinaryFormat/WasmTraits.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAsmLayout.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixupKindInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSectionWasm.h"
#include "llvm/MC/MCSymbolWasm.h"
#include "llvm/MC/MCValue.h"
#include "llvm/MC/MCWasmObjectWriter.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/EndianStream.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/StringSaver.h"
#include <vector>
Macros
#define DEBUG_TYPE "mc"
Functions
static void addData (SmallVectorImpl< char > &DataBytes, MCSectionWasm &DataSection)
static bool isInSymtab (const MCSymbolWasm &Sym)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mc"
Definition at line 39 of file WasmObjectWriter.cpp.
Function Documentation
addData()
static void addData (SmallVectorImpl< char > & DataBytes, MCSectionWasm & DataSection) static
Definition at line 661 of file WasmObjectWriter.cpp.
References llvm::alignTo(), llvm::append_range(), llvm::dbgs(), llvm::errs(), llvm::MCSection::getAlignment(), llvm::MCSection::getName(), llvm::SmallVectorImpl< T >::insert(), LLVM_DEBUG, llvm_unreachable, llvm::report_fatal_error(), llvm::SmallVectorImpl< T >::resize(), and llvm::Check::Size.
isInSymtab()
static bool isInSymtab (const MCSymbolWasm & Sym) static
Definition at line 1257 of file WasmObjectWriter.cpp.
References llvm::MCSymbolWasm::isComdat(), llvm::MCSymbol::isDefined(), llvm::MCSymbolWasm::isSection(), llvm::MCSymbol::isTemporary(), llvm::MCSymbolWasm::isUsedInInitArray(), llvm::MCSymbol::isUsedInReloc(), and llvm::MCSymbolWasm::omitFromLinkingSection().