LLVM: lib/Target/X86/X86InstrFoldTables.cpp File Reference
X86InstrFoldTables.cpp File Reference
#include "X86InstrFoldTables.h"
#include "X86InstrInfo.h"
#include "llvm/ADT/STLExtras.h"
#include <vector>
Functions
static const X86MemoryFoldTableEntry * lookupFoldTableImpl (ArrayRef< X86MemoryFoldTableEntry > Table, unsigned RegOp)
Variables
static const X86MemoryFoldTableEntry MemoryFoldTable2Addr []
static const X86MemoryFoldTableEntry MemoryFoldTable0 []
static const X86MemoryFoldTableEntry MemoryFoldTable1 []
static const X86MemoryFoldTableEntry MemoryFoldTable2 []
static const X86MemoryFoldTableEntry MemoryFoldTable3 []
static const X86MemoryFoldTableEntry MemoryFoldTable4 []
static const X86MemoryFoldTableEntry BroadcastFoldTable2 []
static const X86MemoryFoldTableEntry BroadcastFoldTable3 []
static ManagedStatic< X86MemUnfoldTable > MemUnfoldTable
Function Documentation
lookupFoldTableImpl()
static const X86MemoryFoldTableEntry* lookupFoldTableImpl (ArrayRef< X86MemoryFoldTableEntry > Table, unsigned RegOp) static
Definition at line 5547 of file X86InstrFoldTables.cpp.
References assert(), llvm::sys::path::begin(), BroadcastFoldTable2, BroadcastFoldTable3, llvm::Data, llvm::ArrayRef< T >::end(), llvm::sys::path::end(), llvm::is_sorted(), llvm::lower_bound(), MemoryFoldTable0, MemoryFoldTable1, MemoryFoldTable2, MemoryFoldTable2Addr, MemoryFoldTable3, MemoryFoldTable4, and llvm::TB_NO_FORWARD.
Referenced by llvm::lookupFoldTable(), and llvm::lookupTwoAddrFoldTable().
Variable Documentation
BroadcastFoldTable2
const X86MemoryFoldTableEntry BroadcastFoldTable2[] static
Definition at line 5276 of file X86InstrFoldTables.cpp.
Referenced by lookupFoldTableImpl().
BroadcastFoldTable3
const X86MemoryFoldTableEntry BroadcastFoldTable3[] static
Definition at line 5429 of file X86InstrFoldTables.cpp.
Referenced by lookupFoldTableImpl().
MemoryFoldTable0
const X86MemoryFoldTableEntry MemoryFoldTable0[] static
Definition at line 254 of file X86InstrFoldTables.cpp.
Referenced by llvm::lookupFoldTable(), and lookupFoldTableImpl().
MemoryFoldTable1
const X86MemoryFoldTableEntry MemoryFoldTable1[] static
Definition at line 446 of file X86InstrFoldTables.cpp.
Referenced by llvm::lookupFoldTable(), and lookupFoldTableImpl().
MemoryFoldTable2
const X86MemoryFoldTableEntry MemoryFoldTable2[] static
Definition at line 1216 of file X86InstrFoldTables.cpp.
Referenced by llvm::lookupFoldTable(), and lookupFoldTableImpl().
MemoryFoldTable2Addr
const X86MemoryFoldTableEntry MemoryFoldTable2Addr[] static
Definition at line 35 of file X86InstrFoldTables.cpp.
Referenced by lookupFoldTableImpl(), and llvm::lookupTwoAddrFoldTable().
MemoryFoldTable3
const X86MemoryFoldTableEntry MemoryFoldTable3[] static
Definition at line 2998 of file X86InstrFoldTables.cpp.
Referenced by llvm::lookupFoldTable(), and lookupFoldTableImpl().
MemoryFoldTable4
const X86MemoryFoldTableEntry MemoryFoldTable4[] static
Definition at line 4347 of file X86InstrFoldTables.cpp.
Referenced by llvm::lookupFoldTable(), and lookupFoldTableImpl().
MemUnfoldTable
ManagedStatic<X86MemUnfoldTable> MemUnfoldTable static
Definition at line 5687 of file X86InstrFoldTables.cpp.
Referenced by llvm::lookupUnfoldTable().